var abastecer = {
	Indicative: {
		Present: {
			yo: "abastezco",
			tú: "abasteces",
			Ud: "abastece",
			nosotros: "abastecemos",
			vosotros: "abastecéis",
			Uds: "abastecen",
		},
		Preterite: {
			yo: "abastecí",
			tú: "abasteciste",
			Ud: "abasteció",
			nosotros: "abastecimos",
			vosotros: "abastecisteis",
			Uds: "abastecieron",
		},
		Imperfect: {
			yo: "abastecía",
			tú: "abastecías",
			Ud: "abastecía",
			nosotros: "abastecíamos",
			vosotros: "abastecíais",
			Uds: "abastecían",
		},
		Conditional: {
			yo: "abastecería",
			tú: "abastecerías",
			Ud: "abastecería",
			nosotros: "abasteceríamos",
			vosotros: "abasteceríais",
			Uds: "abastecerían",
		},
		Future: {
			yo: "abasteceré",
			tú: "abastecerás",
			Ud: "abastecerá",
			nosotros: "abasteceremos",
			vosotros: "abasteceréis",
			Uds: "abastecerán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "abastezca",
			tú: "abastezcas",
			Ud: "abastezca",
			nosotros: "abastezcamos",
			vosotros: "abastezcáis",
			Uds: "abastezcan",
		},
		Imperfect: {
			yo: "abasteciera",
			tú: "abastecieras",
			Ud: "abasteciera",
			nosotros: "abasteciéramos",
			vosotros: "abastecierais",
			Uds: "abastecieran",
		},
		Imperfect2: {
			yo: "abasteciese",
			tú: "abastecieses",
			Ud: "abasteciese",
			nosotros: "abasteciésemos",
			vosotros: "abastecieseis",
			Uds: "abasteciesen",
		},
		Future: {
			yo: "abasteciere",
			tú: "abastecieres",
			Ud: "abasteciere",
			nosotros: "abasteciéremos",
			vosotros: "abasteciereis",
			Uds: "abastecieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "abastece",
			Ud: "abastezca",
			nosotros: "abastezcamos",
			vosotros: "abasteced",
			Uds: "abastezcan",
		},
		Negative: {
			tú: "no abastezcas",
			Ud: "no abastezca",
			nosotros: "no abastezcamos",
			vosotros: "no abastezcáis",
			Uds: "no abastezcan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy abasteciendo",
			tú: "estás abasteciendo",
			Ud: "está abasteciendo",
			nosotros: "estamos abasteciendo",
			vosotros: "estáis abasteciendo",
			Uds: "están abasteciendo",
		},
		Preterite: {
			yo: "estuve abasteciendo",
			tú: "estuviste abasteciendo",
			Ud: "estuvo abasteciendo",
			nosotros: "estuvimos abasteciendo",
			vosotros: "estuvisteis abasteciendo",
			Uds: "estuvieron abasteciendo",
		},
		Imperfect: {
			Uds: "estaban abasteciendo",
			yo: "estaba abasteciendo",
			tú: "estabas abasteciendo",
			Ud: "estaba abasteciendo",
			nosotros: "estábamos abasteciendo",
			vosotros: "estabais abasteciendo",
		},
		Conditional: {
			yo: "estaría abasteciendo",
			tú: "estarías abasteciendo",
			Ud: "estaría abasteciendo",
			nosotros: "estaríamos abasteciendo",
			vosotros: "estaríais abasteciendo",
			Uds: "estarían abasteciendo",
		},
		Future: {
			yo: "estaré abasteciendo",
			tú: "estarás abasteciendo",
			Ud: "estará abasteciendo",
			nosotros: "estaremos abasteciendo",
			vosotros: "estaréis abasteciendo",
			Uds: "estarán abasteciendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he abastecido",
			tú: "has abastecido",
			Ud: "ha abastecido",
			nosotros: "hemos abastecido",
			vosotros: "habéis abastecido",
			Uds: "han abastecido",
		},
		Preterite: {
			yo: "hube abastecido",
			tú: "hubiste abastecido",
			Ud: "hubo abastecido",
			nosotros: "hubimos abastecido",
			vosotros: "hubisteis abastecido",
			Uds: "hubieron abastecido",
		},
		Past: {
			yo: "había abastecido",
			tú: "habías abastecido",
			Ud: "había abastecido",
			nosotros: "habíamos abastecido",
			vosotros: "habíais abastecido",
			Uds: "habían abastecido",
		},
		Conditional: {
			yo: "habría abastecido",
			tú: "habrías abastecido",
			Ud: "habría abastecido",
			nosotros: "habríamos abastecido",
			vosotros: "habríais abastecido",
			Uds: "habrían abastecido",
		},
		Future: {
			yo: "habré abastecido",
			tú: "habrás abastecido",
			Ud: "habrá abastecido",
			nosotros: "habremos abastecido",
			vosotros: "habréis abastecido",
			Uds: "habrán abastecido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya abastecido",
			tú: "hayas abastecido",
			Ud: "haya abastecido",
			nosotros: "hayamos abastecido",
			vosotros: "hayáis abastecido",
			Uds: "hayan abastecido",
		},
		Past: {
			yo: "hubiera abastecido",
			tú: "hubieras abastecido",
			Ud: "hubiera abastecido",
			nosotros: "hubiéramos abastecido",
			vosotros: "hubierais abastecido",
			Uds: "hubieran abastecido",
		},
		Future: {
			yo: "hubiere abastecido",
			tú: "hubieres abastecido",
			Ud: "hubiere abastecido",
			nosotros: "hubiéremos abastecido",
			vosotros: "hubiereis abastecido",
			Uds: "hubieren abastecido",
		},
	},
}
