var abonar = {
	Indicative: {
		Present: {
			yo: "abono",
			tú: "abonas",
			Ud: "abona",
			nosotros: "abonamos",
			vosotros: "abonáis",
			Uds: "abonan",
		},
		Preterite: {
			yo: "aboné",
			tú: "abonaste",
			Ud: "abonó",
			nosotros: "abonamos",
			vosotros: "abonasteis",
			Uds: "abonaron",
		},
		Imperfect: {
			yo: "abonaba",
			tú: "abonabas",
			Ud: "abonaba",
			nosotros: "abonábamos",
			vosotros: "abonabais",
			Uds: "abonaban",
		},
		Conditional: {
			yo: "abonaría",
			tú: "abonarías",
			Ud: "abonaría",
			nosotros: "abonaríamos",
			vosotros: "abonaríais",
			Uds: "abonarían",
		},
		Future: {
			yo: "abonaré",
			tú: "abonarás",
			Ud: "abonará",
			nosotros: "abonaremos",
			vosotros: "abonaréis",
			Uds: "abonarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "abone",
			tú: "abones",
			Ud: "abone",
			nosotros: "abonemos",
			vosotros: "abonéis",
			Uds: "abonen",
		},
		Imperfect: {
			yo: "abonara",
			tú: "abonaras",
			Ud: "abonara",
			nosotros: "abonáramos",
			vosotros: "abonarais",
			Uds: "abonaran",
		},
		Imperfect2: {
			yo: "abonase",
			tú: "abonases",
			Ud: "abonase",
			nosotros: "abonásemos",
			vosotros: "abonaseis",
			Uds: "abonasen",
		},
		Future: {
			yo: "abonare",
			tú: "abonares",
			Ud: "abonare",
			nosotros: "abonáremos",
			vosotros: "abonareis",
			Uds: "abonaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "abona",
			Ud: "abone",
			nosotros: "abonemos",
			vosotros: "abonad",
			Uds: "abonen",
		},
		Negative: {
			tú: "no abones",
			Ud: "no abone",
			nosotros: "no abonemos",
			vosotros: "no abonéis",
			Uds: "no abonen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy abonando",
			tú: "estás abonando",
			Ud: "está abonando",
			nosotros: "estamos abonando",
			vosotros: "estáis abonando",
			Uds: "están abonando",
		},
		Preterite: {
			yo: "estuve abonando",
			tú: "estuviste abonando",
			Ud: "estuvo abonando",
			nosotros: "estuvimos abonando",
			vosotros: "estuvisteis abonando",
			Uds: "estuvieron abonando",
		},
		Imperfect: {
			Uds: "estaban abonando",
			yo: "estaba abonando",
			tú: "estabas abonando",
			Ud: "estaba abonando",
			nosotros: "estábamos abonando",
			vosotros: "estabais abonando",
		},
		Conditional: {
			yo: "estaría abonando",
			tú: "estarías abonando",
			Ud: "estaría abonando",
			nosotros: "estaríamos abonando",
			vosotros: "estaríais abonando",
			Uds: "estarían abonando",
		},
		Future: {
			yo: "estaré abonando",
			tú: "estarás abonando",
			Ud: "estará abonando",
			nosotros: "estaremos abonando",
			vosotros: "estaréis abonando",
			Uds: "estarán abonando",
		},
	},
	Perfect: {
		Present: {
			yo: "he abonado",
			tú: "has abonado",
			Ud: "ha abonado",
			nosotros: "hemos abonado",
			vosotros: "habéis abonado",
			Uds: "han abonado",
		},
		Preterite: {
			yo: "hube abonado",
			tú: "hubiste abonado",
			Ud: "hubo abonado",
			nosotros: "hubimos abonado",
			vosotros: "hubisteis abonado",
			Uds: "hubieron abonado",
		},
		Past: {
			yo: "había abonado",
			tú: "habías abonado",
			Ud: "había abonado",
			nosotros: "habíamos abonado",
			vosotros: "habíais abonado",
			Uds: "habían abonado",
		},
		Conditional: {
			yo: "habría abonado",
			tú: "habrías abonado",
			Ud: "habría abonado",
			nosotros: "habríamos abonado",
			vosotros: "habríais abonado",
			Uds: "habrían abonado",
		},
		Future: {
			yo: "habré abonado",
			tú: "habrás abonado",
			Ud: "habrá abonado",
			nosotros: "habremos abonado",
			vosotros: "habréis abonado",
			Uds: "habrán abonado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya abonado",
			tú: "hayas abonado",
			Ud: "haya abonado",
			nosotros: "hayamos abonado",
			vosotros: "hayáis abonado",
			Uds: "hayan abonado",
		},
		Past: {
			yo: "hubiera abonado",
			tú: "hubieras abonado",
			Ud: "hubiera abonado",
			nosotros: "hubiéramos abonado",
			vosotros: "hubierais abonado",
			Uds: "hubieran abonado",
		},
		Future: {
			yo: "hubiere abonado",
			tú: "hubieres abonado",
			Ud: "hubiere abonado",
			nosotros: "hubiéremos abonado",
			vosotros: "hubiereis abonado",
			Uds: "hubieren abonado",
		},
	},
}
