var abordar = {
	Indicative: {
		Present: {
			yo: "abordo",
			tú: "abordas",
			Ud: "aborda",
			nosotros: "abordamos",
			vosotros: "abordáis",
			Uds: "abordan",
		},
		Preterite: {
			yo: "abordé",
			tú: "abordaste",
			Ud: "abordó",
			nosotros: "abordamos",
			vosotros: "abordasteis",
			Uds: "abordaron",
		},
		Imperfect: {
			yo: "abordaba",
			tú: "abordabas",
			Ud: "abordaba",
			nosotros: "abordábamos",
			vosotros: "abordabais",
			Uds: "abordaban",
		},
		Conditional: {
			yo: "abordaría",
			tú: "abordarías",
			Ud: "abordaría",
			nosotros: "abordaríamos",
			vosotros: "abordaríais",
			Uds: "abordarían",
		},
		Future: {
			yo: "abordaré",
			tú: "abordarás",
			Ud: "abordará",
			nosotros: "abordaremos",
			vosotros: "abordaréis",
			Uds: "abordarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "aborde",
			tú: "abordes",
			Ud: "aborde",
			nosotros: "abordemos",
			vosotros: "abordéis",
			Uds: "aborden",
		},
		Imperfect: {
			yo: "abordara",
			tú: "abordaras",
			Ud: "abordara",
			nosotros: "abordáramos",
			vosotros: "abordarais",
			Uds: "abordaran",
		},
		Imperfect2: {
			yo: "abordase",
			tú: "abordases",
			Ud: "abordase",
			nosotros: "abordásemos",
			vosotros: "abordaseis",
			Uds: "abordasen",
		},
		Future: {
			yo: "abordare",
			tú: "abordares",
			Ud: "abordare",
			nosotros: "abordáremos",
			vosotros: "abordareis",
			Uds: "abordaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "aborda",
			Ud: "aborde",
			nosotros: "abordemos",
			vosotros: "abordad",
			Uds: "aborden",
		},
		Negative: {
			tú: "no abordes",
			Ud: "no aborde",
			nosotros: "no abordemos",
			vosotros: "no abordéis",
			Uds: "no aborden",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy abordando",
			tú: "estás abordando",
			Ud: "está abordando",
			nosotros: "estamos abordando",
			vosotros: "estáis abordando",
			Uds: "están abordando",
		},
		Preterite: {
			yo: "estuve abordando",
			tú: "estuviste abordando",
			Ud: "estuvo abordando",
			nosotros: "estuvimos abordando",
			vosotros: "estuvisteis abordando",
			Uds: "estuvieron abordando",
		},
		Imperfect: {
			Uds: "estaban abordando",
			yo: "estaba abordando",
			tú: "estabas abordando",
			Ud: "estaba abordando",
			nosotros: "estábamos abordando",
			vosotros: "estabais abordando",
		},
		Conditional: {
			yo: "estaría abordando",
			tú: "estarías abordando",
			Ud: "estaría abordando",
			nosotros: "estaríamos abordando",
			vosotros: "estaríais abordando",
			Uds: "estarían abordando",
		},
		Future: {
			yo: "estaré abordando",
			tú: "estarás abordando",
			Ud: "estará abordando",
			nosotros: "estaremos abordando",
			vosotros: "estaréis abordando",
			Uds: "estarán abordando",
		},
	},
	Perfect: {
		Present: {
			yo: "he abordado",
			tú: "has abordado",
			Ud: "ha abordado",
			nosotros: "hemos abordado",
			vosotros: "habéis abordado",
			Uds: "han abordado",
		},
		Preterite: {
			yo: "hube abordado",
			tú: "hubiste abordado",
			Ud: "hubo abordado",
			nosotros: "hubimos abordado",
			vosotros: "hubisteis abordado",
			Uds: "hubieron abordado",
		},
		Past: {
			yo: "había abordado",
			tú: "habías abordado",
			Ud: "había abordado",
			nosotros: "habíamos abordado",
			vosotros: "habíais abordado",
			Uds: "habían abordado",
		},
		Conditional: {
			yo: "habría abordado",
			tú: "habrías abordado",
			Ud: "habría abordado",
			nosotros: "habríamos abordado",
			vosotros: "habríais abordado",
			Uds: "habrían abordado",
		},
		Future: {
			yo: "habré abordado",
			tú: "habrás abordado",
			Ud: "habrá abordado",
			nosotros: "habremos abordado",
			vosotros: "habréis abordado",
			Uds: "habrán abordado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya abordado",
			tú: "hayas abordado",
			Ud: "haya abordado",
			nosotros: "hayamos abordado",
			vosotros: "hayáis abordado",
			Uds: "hayan abordado",
		},
		Past: {
			yo: "hubiera abordado",
			tú: "hubieras abordado",
			Ud: "hubiera abordado",
			nosotros: "hubiéramos abordado",
			vosotros: "hubierais abordado",
			Uds: "hubieran abordado",
		},
		Future: {
			yo: "hubiere abordado",
			tú: "hubieres abordado",
			Ud: "hubiere abordado",
			nosotros: "hubiéremos abordado",
			vosotros: "hubiereis abordado",
			Uds: "hubieren abordado",
		},
	},
}
