var abortar = {
	Indicative: {
		Present: {
			yo: "aborto",
			tú: "abortas",
			Ud: "aborta",
			nosotros: "abortamos",
			vosotros: "abortáis",
			Uds: "abortan",
		},
		Preterite: {
			yo: "aborté",
			tú: "abortaste",
			Ud: "abortó",
			nosotros: "abortamos",
			vosotros: "abortasteis",
			Uds: "abortaron",
		},
		Imperfect: {
			yo: "abortaba",
			tú: "abortabas",
			Ud: "abortaba",
			nosotros: "abortábamos",
			vosotros: "abortabais",
			Uds: "abortaban",
		},
		Conditional: {
			yo: "abortaría",
			tú: "abortarías",
			Ud: "abortaría",
			nosotros: "abortaríamos",
			vosotros: "abortaríais",
			Uds: "abortarían",
		},
		Future: {
			yo: "abortaré",
			tú: "abortarás",
			Ud: "abortará",
			nosotros: "abortaremos",
			vosotros: "abortaréis",
			Uds: "abortarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "aborte",
			tú: "abortes",
			Ud: "aborte",
			nosotros: "abortemos",
			vosotros: "abortéis",
			Uds: "aborten",
		},
		Imperfect: {
			yo: "abortara",
			tú: "abortaras",
			Ud: "abortara",
			nosotros: "abortáramos",
			vosotros: "abortarais",
			Uds: "abortaran",
		},
		Imperfect2: {
			yo: "abortase",
			tú: "abortases",
			Ud: "abortase",
			nosotros: "abortásemos",
			vosotros: "abortaseis",
			Uds: "abortasen",
		},
		Future: {
			yo: "abortare",
			tú: "abortares",
			Ud: "abortare",
			nosotros: "abortáremos",
			vosotros: "abortareis",
			Uds: "abortaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "aborta",
			Ud: "aborte",
			nosotros: "abortemos",
			vosotros: "abortad",
			Uds: "aborten",
		},
		Negative: {
			tú: "no abortes",
			Ud: "no aborte",
			nosotros: "no abortemos",
			vosotros: "no abortéis",
			Uds: "no aborten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy abortando",
			tú: "estás abortando",
			Ud: "está abortando",
			nosotros: "estamos abortando",
			vosotros: "estáis abortando",
			Uds: "están abortando",
		},
		Preterite: {
			yo: "estuve abortando",
			tú: "estuviste abortando",
			Ud: "estuvo abortando",
			nosotros: "estuvimos abortando",
			vosotros: "estuvisteis abortando",
			Uds: "estuvieron abortando",
		},
		Imperfect: {
			Uds: "estaban abortando",
			yo: "estaba abortando",
			tú: "estabas abortando",
			Ud: "estaba abortando",
			nosotros: "estábamos abortando",
			vosotros: "estabais abortando",
		},
		Conditional: {
			yo: "estaría abortando",
			tú: "estarías abortando",
			Ud: "estaría abortando",
			nosotros: "estaríamos abortando",
			vosotros: "estaríais abortando",
			Uds: "estarían abortando",
		},
		Future: {
			yo: "estaré abortando",
			tú: "estarás abortando",
			Ud: "estará abortando",
			nosotros: "estaremos abortando",
			vosotros: "estaréis abortando",
			Uds: "estarán abortando",
		},
	},
	Perfect: {
		Present: {
			yo: "he abortado",
			tú: "has abortado",
			Ud: "ha abortado",
			nosotros: "hemos abortado",
			vosotros: "habéis abortado",
			Uds: "han abortado",
		},
		Preterite: {
			yo: "hube abortado",
			tú: "hubiste abortado",
			Ud: "hubo abortado",
			nosotros: "hubimos abortado",
			vosotros: "hubisteis abortado",
			Uds: "hubieron abortado",
		},
		Past: {
			yo: "había abortado",
			tú: "habías abortado",
			Ud: "había abortado",
			nosotros: "habíamos abortado",
			vosotros: "habíais abortado",
			Uds: "habían abortado",
		},
		Conditional: {
			yo: "habría abortado",
			tú: "habrías abortado",
			Ud: "habría abortado",
			nosotros: "habríamos abortado",
			vosotros: "habríais abortado",
			Uds: "habrían abortado",
		},
		Future: {
			yo: "habré abortado",
			tú: "habrás abortado",
			Ud: "habrá abortado",
			nosotros: "habremos abortado",
			vosotros: "habréis abortado",
			Uds: "habrán abortado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya abortado",
			tú: "hayas abortado",
			Ud: "haya abortado",
			nosotros: "hayamos abortado",
			vosotros: "hayáis abortado",
			Uds: "hayan abortado",
		},
		Past: {
			yo: "hubiera abortado",
			tú: "hubieras abortado",
			Ud: "hubiera abortado",
			nosotros: "hubiéramos abortado",
			vosotros: "hubierais abortado",
			Uds: "hubieran abortado",
		},
		Future: {
			yo: "hubiere abortado",
			tú: "hubieres abortado",
			Ud: "hubiere abortado",
			nosotros: "hubiéremos abortado",
			vosotros: "hubiereis abortado",
			Uds: "hubieren abortado",
		},
	},
}
