var abrasar = {
	Indicative: {
		Present: {
			yo: "abraso",
			tú: "abrasas",
			Ud: "abrasa",
			nosotros: "abrasamos",
			vosotros: "abrasáis",
			Uds: "abrasan",
		},
		Preterite: {
			yo: "abrasé",
			tú: "abrasaste",
			Ud: "abrasó",
			nosotros: "abrasamos",
			vosotros: "abrasasteis",
			Uds: "abrasaron",
		},
		Imperfect: {
			yo: "abrasaba",
			tú: "abrasabas",
			Ud: "abrasaba",
			nosotros: "abrasábamos",
			vosotros: "abrasabais",
			Uds: "abrasaban",
		},
		Conditional: {
			yo: "abrasaría",
			tú: "abrasarías",
			Ud: "abrasaría",
			nosotros: "abrasaríamos",
			vosotros: "abrasaríais",
			Uds: "abrasarían",
		},
		Future: {
			yo: "abrasaré",
			tú: "abrasarás",
			Ud: "abrasará",
			nosotros: "abrasaremos",
			vosotros: "abrasaréis",
			Uds: "abrasarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "abrase",
			tú: "abrases",
			Ud: "abrase",
			nosotros: "abrasemos",
			vosotros: "abraséis",
			Uds: "abrasen",
		},
		Imperfect: {
			yo: "abrasara",
			tú: "abrasaras",
			Ud: "abrasara",
			nosotros: "abrasáramos",
			vosotros: "abrasarais",
			Uds: "abrasaran",
		},
		Imperfect2: {
			yo: "abrasase",
			tú: "abrasases",
			Ud: "abrasase",
			nosotros: "abrasásemos",
			vosotros: "abrasaseis",
			Uds: "abrasasen",
		},
		Future: {
			yo: "abrasare",
			tú: "abrasares",
			Ud: "abrasare",
			nosotros: "abrasáremos",
			vosotros: "abrasareis",
			Uds: "abrasaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "abrasa",
			Ud: "abrase",
			nosotros: "abrasemos",
			vosotros: "abrasad",
			Uds: "abrasen",
		},
		Negative: {
			tú: "no abrases",
			Ud: "no abrase",
			nosotros: "no abrasemos",
			vosotros: "no abraséis",
			Uds: "no abrasen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy abrasando",
			tú: "estás abrasando",
			Ud: "está abrasando",
			nosotros: "estamos abrasando",
			vosotros: "estáis abrasando",
			Uds: "están abrasando",
		},
		Preterite: {
			yo: "estuve abrasando",
			tú: "estuviste abrasando",
			Ud: "estuvo abrasando",
			nosotros: "estuvimos abrasando",
			vosotros: "estuvisteis abrasando",
			Uds: "estuvieron abrasando",
		},
		Imperfect: {
			Uds: "estaban abrasando",
			yo: "estaba abrasando",
			tú: "estabas abrasando",
			Ud: "estaba abrasando",
			nosotros: "estábamos abrasando",
			vosotros: "estabais abrasando",
		},
		Conditional: {
			yo: "estaría abrasando",
			tú: "estarías abrasando",
			Ud: "estaría abrasando",
			nosotros: "estaríamos abrasando",
			vosotros: "estaríais abrasando",
			Uds: "estarían abrasando",
		},
		Future: {
			yo: "estaré abrasando",
			tú: "estarás abrasando",
			Ud: "estará abrasando",
			nosotros: "estaremos abrasando",
			vosotros: "estaréis abrasando",
			Uds: "estarán abrasando",
		},
	},
	Perfect: {
		Present: {
			yo: "he abrasado",
			tú: "has abrasado",
			Ud: "ha abrasado",
			nosotros: "hemos abrasado",
			vosotros: "habéis abrasado",
			Uds: "han abrasado",
		},
		Preterite: {
			yo: "hube abrasado",
			tú: "hubiste abrasado",
			Ud: "hubo abrasado",
			nosotros: "hubimos abrasado",
			vosotros: "hubisteis abrasado",
			Uds: "hubieron abrasado",
		},
		Past: {
			yo: "había abrasado",
			tú: "habías abrasado",
			Ud: "había abrasado",
			nosotros: "habíamos abrasado",
			vosotros: "habíais abrasado",
			Uds: "habían abrasado",
		},
		Conditional: {
			yo: "habría abrasado",
			tú: "habrías abrasado",
			Ud: "habría abrasado",
			nosotros: "habríamos abrasado",
			vosotros: "habríais abrasado",
			Uds: "habrían abrasado",
		},
		Future: {
			yo: "habré abrasado",
			tú: "habrás abrasado",
			Ud: "habrá abrasado",
			nosotros: "habremos abrasado",
			vosotros: "habréis abrasado",
			Uds: "habrán abrasado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya abrasado",
			tú: "hayas abrasado",
			Ud: "haya abrasado",
			nosotros: "hayamos abrasado",
			vosotros: "hayáis abrasado",
			Uds: "hayan abrasado",
		},
		Past: {
			yo: "hubiera abrasado",
			tú: "hubieras abrasado",
			Ud: "hubiera abrasado",
			nosotros: "hubiéramos abrasado",
			vosotros: "hubierais abrasado",
			Uds: "hubieran abrasado",
		},
		Future: {
			yo: "hubiere abrasado",
			tú: "hubieres abrasado",
			Ud: "hubiere abrasado",
			nosotros: "hubiéremos abrasado",
			vosotros: "hubiereis abrasado",
			Uds: "hubieren abrasado",
		},
	},
}
