var abrazar = {
	Indicative: {
		Present: {
			yo: "abrazo",
			tú: "abrazas",
			Ud: "abraza",
			nosotros: "abrazamos",
			vosotros: "abrazáis",
			Uds: "abrazan",
		},
		Preterite: {
			yo: "abracé",
			tú: "abrazaste",
			Ud: "abrazó",
			nosotros: "abrazamos",
			vosotros: "abrazasteis",
			Uds: "abrazaron",
		},
		Imperfect: {
			yo: "abrazaba",
			tú: "abrazabas",
			Ud: "abrazaba",
			nosotros: "abrazábamos",
			vosotros: "abrazabais",
			Uds: "abrazaban",
		},
		Conditional: {
			yo: "abrazaría",
			tú: "abrazarías",
			Ud: "abrazaría",
			nosotros: "abrazaríamos",
			vosotros: "abrazaríais",
			Uds: "abrazarían",
		},
		Future: {
			yo: "abrazaré",
			tú: "abrazarás",
			Ud: "abrazará",
			nosotros: "abrazaremos",
			vosotros: "abrazaréis",
			Uds: "abrazarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "abrace",
			tú: "abraces",
			Ud: "abrace",
			nosotros: "abracemos",
			vosotros: "abracéis",
			Uds: "abracen",
		},
		Imperfect: {
			yo: "abrazara",
			tú: "abrazaras",
			Ud: "abrazara",
			nosotros: "abrazáramos",
			vosotros: "abrazarais",
			Uds: "abrazaran",
		},
		Imperfect2: {
			yo: "abrazase",
			tú: "abrazases",
			Ud: "abrazase",
			nosotros: "abrazásemos",
			vosotros: "abrazaseis",
			Uds: "abrazasen",
		},
		Future: {
			yo: "abrazare",
			tú: "abrazares",
			Ud: "abrazare",
			nosotros: "abrazáremos",
			vosotros: "abrazareis",
			Uds: "abrazaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "abraza",
			Ud: "abrace",
			nosotros: "abracemos",
			vosotros: "abrazad",
			Uds: "abracen",
		},
		Negative: {
			tú: "no abraces",
			Ud: "no abrace",
			nosotros: "no abracemos",
			vosotros: "no abracéis",
			Uds: "no abracen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy abrazando",
			tú: "estás abrazando",
			Ud: "está abrazando",
			nosotros: "estamos abrazando",
			vosotros: "estáis abrazando",
			Uds: "están abrazando",
		},
		Preterite: {
			yo: "estuve abrazando",
			tú: "estuviste abrazando",
			Ud: "estuvo abrazando",
			nosotros: "estuvimos abrazando",
			vosotros: "estuvisteis abrazando",
			Uds: "estuvieron abrazando",
		},
		Imperfect: {
			Uds: "estaban abrazando",
			yo: "estaba abrazando",
			tú: "estabas abrazando",
			Ud: "estaba abrazando",
			nosotros: "estábamos abrazando",
			vosotros: "estabais abrazando",
		},
		Conditional: {
			yo: "estaría abrazando",
			tú: "estarías abrazando",
			Ud: "estaría abrazando",
			nosotros: "estaríamos abrazando",
			vosotros: "estaríais abrazando",
			Uds: "estarían abrazando",
		},
		Future: {
			yo: "estaré abrazando",
			tú: "estarás abrazando",
			Ud: "estará abrazando",
			nosotros: "estaremos abrazando",
			vosotros: "estaréis abrazando",
			Uds: "estarán abrazando",
		},
	},
	Perfect: {
		Present: {
			yo: "he abrazado",
			tú: "has abrazado",
			Ud: "ha abrazado",
			nosotros: "hemos abrazado",
			vosotros: "habéis abrazado",
			Uds: "han abrazado",
		},
		Preterite: {
			yo: "hube abrazado",
			tú: "hubiste abrazado",
			Ud: "hubo abrazado",
			nosotros: "hubimos abrazado",
			vosotros: "hubisteis abrazado",
			Uds: "hubieron abrazado",
		},
		Past: {
			yo: "había abrazado",
			tú: "habías abrazado",
			Ud: "había abrazado",
			nosotros: "habíamos abrazado",
			vosotros: "habíais abrazado",
			Uds: "habían abrazado",
		},
		Conditional: {
			yo: "habría abrazado",
			tú: "habrías abrazado",
			Ud: "habría abrazado",
			nosotros: "habríamos abrazado",
			vosotros: "habríais abrazado",
			Uds: "habrían abrazado",
		},
		Future: {
			yo: "habré abrazado",
			tú: "habrás abrazado",
			Ud: "habrá abrazado",
			nosotros: "habremos abrazado",
			vosotros: "habréis abrazado",
			Uds: "habrán abrazado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya abrazado",
			tú: "hayas abrazado",
			Ud: "haya abrazado",
			nosotros: "hayamos abrazado",
			vosotros: "hayáis abrazado",
			Uds: "hayan abrazado",
		},
		Past: {
			yo: "hubiera abrazado",
			tú: "hubieras abrazado",
			Ud: "hubiera abrazado",
			nosotros: "hubiéramos abrazado",
			vosotros: "hubierais abrazado",
			Uds: "hubieran abrazado",
		},
		Future: {
			yo: "hubiere abrazado",
			tú: "hubieres abrazado",
			Ud: "hubiere abrazado",
			nosotros: "hubiéremos abrazado",
			vosotros: "hubiereis abrazado",
			Uds: "hubieren abrazado",
		},
	},
}
