var abrir = {
	Indicative: {
		Present: {
			yo: "abro",
			tú: "abres",
			Ud: "abre",
			nosotros: "abrimos",
			vosotros: "abrís",
			Uds: "abren",
		},
		Preterite: {
			yo: "abrí",
			tú: "abriste",
			Ud: "abrió",
			nosotros: "abrimos",
			vosotros: "abristeis",
			Uds: "abrieron",
		},
		Imperfect: {
			yo: "abría",
			tú: "abrías",
			Ud: "abría",
			nosotros: "abríamos",
			vosotros: "abríais",
			Uds: "abrían",
		},
		Conditional: {
			yo: "abriría",
			tú: "abrirías",
			Ud: "abriría",
			nosotros: "abriríamos",
			vosotros: "abriríais",
			Uds: "abrirían",
		},
		Future: {
			yo: "abriré",
			tú: "abrirás",
			Ud: "abrirá",
			nosotros: "abriremos",
			vosotros: "abriréis",
			Uds: "abrirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "abra",
			tú: "abras",
			Ud: "abra",
			nosotros: "abramos",
			vosotros: "abráis",
			Uds: "abran",
		},
		Imperfect: {
			yo: "abriera",
			tú: "abrieras",
			Ud: "abriera",
			nosotros: "abriéramos",
			vosotros: "abrierais",
			Uds: "abrieran",
		},
		Imperfect2: {
			yo: "abriese",
			tú: "abrieses",
			Ud: "abriese",
			nosotros: "abriésemos",
			vosotros: "abrieseis",
			Uds: "abriesen",
		},
		Future: {
			yo: "abriere",
			tú: "abrieres",
			Ud: "abriere",
			nosotros: "abriéremos",
			vosotros: "abriereis",
			Uds: "abrieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "abre",
			Ud: "abra",
			nosotros: "abramos",
			vosotros: "abrid",
			Uds: "abran",
		},
		Negative: {
			tú: "no abras",
			Ud: "no abra",
			nosotros: "no abramos",
			vosotros: "no abráis",
			Uds: "no abran",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy abriendo",
			tú: "estás abriendo",
			Ud: "está abriendo",
			nosotros: "estamos abriendo",
			vosotros: "estáis abriendo",
			Uds: "están abriendo",
		},
		Preterite: {
			yo: "estuve abriendo",
			tú: "estuviste abriendo",
			Ud: "estuvo abriendo",
			nosotros: "estuvimos abriendo",
			vosotros: "estuvisteis abriendo",
			Uds: "estuvieron abriendo",
		},
		Imperfect: {
			Uds: "estaban abriendo",
			yo: "estaba abriendo",
			tú: "estabas abriendo",
			Ud: "estaba abriendo",
			nosotros: "estábamos abriendo",
			vosotros: "estabais abriendo",
		},
		Conditional: {
			yo: "estaría abriendo",
			tú: "estarías abriendo",
			Ud: "estaría abriendo",
			nosotros: "estaríamos abriendo",
			vosotros: "estaríais abriendo",
			Uds: "estarían abriendo",
		},
		Future: {
			yo: "estaré abriendo",
			tú: "estarás abriendo",
			Ud: "estará abriendo",
			nosotros: "estaremos abriendo",
			vosotros: "estaréis abriendo",
			Uds: "estarán abriendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he abierto",
			tú: "has abierto",
			Ud: "ha abierto",
			nosotros: "hemos abierto",
			vosotros: "habéis abierto",
			Uds: "han abierto",
		},
		Preterite: {
			yo: "hube abierto",
			tú: "hubiste abierto",
			Ud: "hubo abierto",
			nosotros: "hubimos abierto",
			vosotros: "hubisteis abierto",
			Uds: "hubieron abierto",
		},
		Past: {
			yo: "había abierto",
			tú: "habías abierto",
			Ud: "había abierto",
			nosotros: "habíamos abierto",
			vosotros: "habíais abierto",
			Uds: "habían abierto",
		},
		Conditional: {
			yo: "habría abierto",
			tú: "habrías abierto",
			Ud: "habría abierto",
			nosotros: "habríamos abierto",
			vosotros: "habríais abierto",
			Uds: "habrían abierto",
		},
		Future: {
			yo: "habré abierto",
			tú: "habrás abierto",
			Ud: "habrá abierto",
			nosotros: "habremos abierto",
			vosotros: "habréis abierto",
			Uds: "habrán abierto",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya abierto",
			tú: "hayas abierto",
			Ud: "haya abierto",
			nosotros: "hayamos abierto",
			vosotros: "hayáis abierto",
			Uds: "hayan abierto",
		},
		Past: {
			yo: "hubiera abierto",
			tú: "hubieras abierto",
			Ud: "hubiera abierto",
			nosotros: "hubiéramos abierto",
			vosotros: "hubierais abierto",
			Uds: "hubieran abierto",
		},
		Future: {
			yo: "hubiere abierto",
			tú: "hubieres abierto",
			Ud: "hubiere abierto",
			nosotros: "hubiéremos abierto",
			vosotros: "hubiereis abierto",
			Uds: "hubieren abierto",
		},
	},
}
