var abrochar = {
	Indicative: {
		Present: {
			yo: "abrocho",
			tú: "abrochas",
			Ud: "abrocha",
			nosotros: "abrochamos",
			vosotros: "abrocháis",
			Uds: "abrochan",
		},
		Preterite: {
			yo: "abroché",
			tú: "abrochaste",
			Ud: "abrochó",
			nosotros: "abrochamos",
			vosotros: "abrochasteis",
			Uds: "abrocharon",
		},
		Imperfect: {
			yo: "abrochaba",
			tú: "abrochabas",
			Ud: "abrochaba",
			nosotros: "abrochábamos",
			vosotros: "abrochabais",
			Uds: "abrochaban",
		},
		Conditional: {
			yo: "abrocharía",
			tú: "abrocharías",
			Ud: "abrocharía",
			nosotros: "abrocharíamos",
			vosotros: "abrocharíais",
			Uds: "abrocharían",
		},
		Future: {
			yo: "abrocharé",
			tú: "abrocharás",
			Ud: "abrochará",
			nosotros: "abrocharemos",
			vosotros: "abrocharéis",
			Uds: "abrocharán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "abroche",
			tú: "abroches",
			Ud: "abroche",
			nosotros: "abrochemos",
			vosotros: "abrochéis",
			Uds: "abrochen",
		},
		Imperfect: {
			yo: "abrochara",
			tú: "abrocharas",
			Ud: "abrochara",
			nosotros: "abrocháramos",
			vosotros: "abrocharais",
			Uds: "abrocharan",
		},
		Imperfect2: {
			yo: "abrochase",
			tú: "abrochases",
			Ud: "abrochase",
			nosotros: "abrochásemos",
			vosotros: "abrochaseis",
			Uds: "abrochasen",
		},
		Future: {
			yo: "abrochare",
			tú: "abrochares",
			Ud: "abrochare",
			nosotros: "abrocháremos",
			vosotros: "abrochareis",
			Uds: "abrocharen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "abrocha",
			Ud: "abroche",
			nosotros: "abrochemos",
			vosotros: "abrochad",
			Uds: "abrochen",
		},
		Negative: {
			tú: "no abroches",
			Ud: "no abroche",
			nosotros: "no abrochemos",
			vosotros: "no abrochéis",
			Uds: "no abrochen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy abrochando",
			tú: "estás abrochando",
			Ud: "está abrochando",
			nosotros: "estamos abrochando",
			vosotros: "estáis abrochando",
			Uds: "están abrochando",
		},
		Preterite: {
			yo: "estuve abrochando",
			tú: "estuviste abrochando",
			Ud: "estuvo abrochando",
			nosotros: "estuvimos abrochando",
			vosotros: "estuvisteis abrochando",
			Uds: "estuvieron abrochando",
		},
		Imperfect: {
			Uds: "estaban abrochando",
			yo: "estaba abrochando",
			tú: "estabas abrochando",
			Ud: "estaba abrochando",
			nosotros: "estábamos abrochando",
			vosotros: "estabais abrochando",
		},
		Conditional: {
			yo: "estaría abrochando",
			tú: "estarías abrochando",
			Ud: "estaría abrochando",
			nosotros: "estaríamos abrochando",
			vosotros: "estaríais abrochando",
			Uds: "estarían abrochando",
		},
		Future: {
			yo: "estaré abrochando",
			tú: "estarás abrochando",
			Ud: "estará abrochando",
			nosotros: "estaremos abrochando",
			vosotros: "estaréis abrochando",
			Uds: "estarán abrochando",
		},
	},
	Perfect: {
		Present: {
			yo: "he abrochado",
			tú: "has abrochado",
			Ud: "ha abrochado",
			nosotros: "hemos abrochado",
			vosotros: "habéis abrochado",
			Uds: "han abrochado",
		},
		Preterite: {
			yo: "hube abrochado",
			tú: "hubiste abrochado",
			Ud: "hubo abrochado",
			nosotros: "hubimos abrochado",
			vosotros: "hubisteis abrochado",
			Uds: "hubieron abrochado",
		},
		Past: {
			yo: "había abrochado",
			tú: "habías abrochado",
			Ud: "había abrochado",
			nosotros: "habíamos abrochado",
			vosotros: "habíais abrochado",
			Uds: "habían abrochado",
		},
		Conditional: {
			yo: "habría abrochado",
			tú: "habrías abrochado",
			Ud: "habría abrochado",
			nosotros: "habríamos abrochado",
			vosotros: "habríais abrochado",
			Uds: "habrían abrochado",
		},
		Future: {
			yo: "habré abrochado",
			tú: "habrás abrochado",
			Ud: "habrá abrochado",
			nosotros: "habremos abrochado",
			vosotros: "habréis abrochado",
			Uds: "habrán abrochado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya abrochado",
			tú: "hayas abrochado",
			Ud: "haya abrochado",
			nosotros: "hayamos abrochado",
			vosotros: "hayáis abrochado",
			Uds: "hayan abrochado",
		},
		Past: {
			yo: "hubiera abrochado",
			tú: "hubieras abrochado",
			Ud: "hubiera abrochado",
			nosotros: "hubiéramos abrochado",
			vosotros: "hubierais abrochado",
			Uds: "hubieran abrochado",
		},
		Future: {
			yo: "hubiere abrochado",
			tú: "hubieres abrochado",
			Ud: "hubiere abrochado",
			nosotros: "hubiéremos abrochado",
			vosotros: "hubiereis abrochado",
			Uds: "hubieren abrochado",
		},
	},
}
