var abrumar = {
	Indicative: {
		Present: {
			yo: "me abrumo",
			tú: "te abrumas",
			Ud: "se abruma",
			nosotros: "nos abrumamos",
			vosotros: "os abrumáis",
			Uds: "se abruman",
		},
		Preterite: {
			yo: "me abrumé",
			tú: "te abrumaste",
			Ud: "se abrumó",
			nosotros: "nos abrumamos",
			vosotros: "os abrumasteis",
			Uds: "se abrumaron",
		},
		Imperfect: {
			yo: "me abrumaba",
			tú: "te abrumabas",
			Ud: "se abrumaba",
			nosotros: "nos abrumábamos",
			vosotros: "os abrumabais",
			Uds: "se abrumaban",
		},
		Conditional: {
			yo: "me abrumaría",
			tú: "te abrumarías",
			Ud: "se abrumaría",
			nosotros: "nos abrumaríamos",
			vosotros: "os abrumaríais",
			Uds: "se abrumarían",
		},
		Future: {
			yo: "me abrumaré",
			tú: "te abrumarás",
			Ud: "se abrumará",
			nosotros: "nos abrumaremos",
			vosotros: "os abrumaréis",
			Uds: "se abrumarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "me abrume",
			tú: "te abrumes",
			Ud: "se abrume",
			nosotros: "nos abrumemos",
			vosotros: "os abruméis",
			Uds: "se abrumen",
		},
		Imperfect: {
			yo: "me abrumara",
			tú: "te abrumaras",
			Ud: "se abrumara",
			nosotros: "nos abrumáramos",
			vosotros: "os abrumarais",
			Uds: "se abrumaran",
		},
		Imperfect2: {
			yo: "me abrumase",
			tú: "te abrumases",
			Ud: "se abrumase",
			nosotros: "nos abrumásemos",
			vosotros: "os abrumaseis",
			Uds: "se abrumasen",
		},
		Future: {
			yo: "me abrumare",
			tú: "te abrumares",
			Ud: "se abrumare",
			nosotros: "nos abrumáremos",
			vosotros: "os abrumareis",
			Uds: "se abrumaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "abrúmate",
			Ud: "abrúmese",
			nosotros: "abrumémonos",
			vosotros: "abrumaos",
			Uds: "abrúmense",
		},
		Negative: {
			tú: "no te abrumes",
			Ud: "no se abrume",
			nosotros: "no nos abrumemos",
			vosotros: "no os abruméis",
			Uds: "no se abrumen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "me estoy abrumando",
			tú: "te estás abrumando",
			Ud: "se está abrumando",
			nosotros: "nos estamos abrumando",
			vosotros: "os estáis abrumando",
			Uds: "se están abrumando",
		},
		Preterite: {
			yo: "me estuve abrumando",
			tú: "te estuviste abrumando",
			Ud: "se estuvo abrumando",
			nosotros: "nos estuvimos abrumando",
			vosotros: "os estuvisteis abrumando",
			Uds: "se estuvieron abrumando",
		},
		Imperfect: {
			Uds: "se estaban abrumando",
			yo: "me estaba abrumando",
			tú: "te estabas abrumando",
			Ud: "se estaba abrumando",
			nosotros: "nos estábamos abrumando",
			vosotros: "os estabais abrumando",
		},
		Conditional: {
			yo: "me estaría abrumando",
			tú: "te estarías abrumando",
			Ud: "se estaría abrumando",
			nosotros: "nos estaríamos abrumando",
			vosotros: "os estaríais abrumando",
			Uds: "se estarían abrumando",
		},
		Future: {
			yo: "me estaré abrumando",
			tú: "te estarás abrumando",
			Ud: "se estará abrumando",
			nosotros: "nos estaremos abrumando",
			vosotros: "os estaréis abrumando",
			Uds: "se estarán abrumando",
		},
	},
	Perfect: {
		Present: {
			yo: "me he abrumado",
			tú: "te has abrumado",
			Ud: "se ha abrumado",
			nosotros: "nos hemos abrumado",
			vosotros: "os habéis abrumado",
			Uds: "se han abrumado",
		},
		Preterite: {
			yo: "me hube abrumado",
			tú: "te hubiste abrumado",
			Ud: "se hubo abrumado",
			nosotros: "nos hubimos abrumado",
			vosotros: "os hubisteis abrumado",
			Uds: "se hubieron abrumado",
		},
		Past: {
			yo: "me había abrumado",
			tú: "te habías abrumado",
			Ud: "se había abrumado",
			nosotros: "nos habíamos abrumado",
			vosotros: "os habíais abrumado",
			Uds: "se habían abrumado",
		},
		Conditional: {
			yo: "me habría abrumado",
			tú: "te habrías abrumado",
			Ud: "se habría abrumado",
			nosotros: "nos habríamos abrumado",
			vosotros: "os habríais abrumado",
			Uds: "se habrían abrumado",
		},
		Future: {
			yo: "me habré abrumado",
			tú: "te habrás abrumado",
			Ud: "se habrá abrumado",
			nosotros: "nos habremos abrumado",
			vosotros: "os habréis abrumado",
			Uds: "se habrán abrumado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "me haya abrumado",
			tú: "te hayas abrumado",
			Ud: "se haya abrumado",
			nosotros: "nos hayamos abrumado",
			vosotros: "os hayáis abrumado",
			Uds: "se hayan abrumado",
		},
		Past: {
			yo: "me hubiera abrumado",
			tú: "te hubieras abrumado",
			Ud: "se hubiera abrumado",
			nosotros: "nos hubiéramos abrumado",
			vosotros: "os hubierais abrumado",
			Uds: "se hubieran abrumado",
		},
		Future: {
			yo: "me hubiere abrumado",
			tú: "te hubieres abrumado",
			Ud: "se hubiere abrumado",
			nosotros: "nos hubiéremos abrumado",
			vosotros: "os hubiereis abrumado",
			Uds: "se hubieren abrumado",
		},
	},
}
