var abuchear = {
	Indicative: {
		Present: {
			yo: "abucheo",
			tú: "abucheas",
			Ud: "abuchea",
			nosotros: "abucheamos",
			vosotros: "abucheáis",
			Uds: "abuchean",
		},
		Preterite: {
			yo: "abucheé",
			tú: "abucheaste",
			Ud: "abucheó",
			nosotros: "abucheamos",
			vosotros: "abucheasteis",
			Uds: "abuchearon",
		},
		Imperfect: {
			yo: "abucheaba",
			tú: "abucheabas",
			Ud: "abucheaba",
			nosotros: "abucheábamos",
			vosotros: "abucheabais",
			Uds: "abucheaban",
		},
		Conditional: {
			yo: "abuchearía",
			tú: "abuchearías",
			Ud: "abuchearía",
			nosotros: "abuchearíamos",
			vosotros: "abuchearíais",
			Uds: "abuchearían",
		},
		Future: {
			yo: "abuchearé",
			tú: "abuchearás",
			Ud: "abucheará",
			nosotros: "abuchearemos",
			vosotros: "abuchearéis",
			Uds: "abuchearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "abuchee",
			tú: "abuchees",
			Ud: "abuchee",
			nosotros: "abucheemos",
			vosotros: "abucheéis",
			Uds: "abucheen",
		},
		Imperfect: {
			yo: "abucheara",
			tú: "abuchearas",
			Ud: "abucheara",
			nosotros: "abucheáramos",
			vosotros: "abuchearais",
			Uds: "abuchearan",
		},
		Imperfect2: {
			yo: "abuchease",
			tú: "abucheases",
			Ud: "abuchease",
			nosotros: "abucheásemos",
			vosotros: "abucheaseis",
			Uds: "abucheasen",
		},
		Future: {
			yo: "abucheare",
			tú: "abucheares",
			Ud: "abucheare",
			nosotros: "abucheáremos",
			vosotros: "abucheareis",
			Uds: "abuchearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "abuchea",
			Ud: "abuchee",
			nosotros: "abucheemos",
			vosotros: "abuchead",
			Uds: "abucheen",
		},
		Negative: {
			tú: "no abuchees",
			Ud: "no abuchee",
			nosotros: "no abucheemos",
			vosotros: "no abucheéis",
			Uds: "no abucheen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy abucheando",
			tú: "estás abucheando",
			Ud: "está abucheando",
			nosotros: "estamos abucheando",
			vosotros: "estáis abucheando",
			Uds: "están abucheando",
		},
		Preterite: {
			yo: "estuve abucheando",
			tú: "estuviste abucheando",
			Ud: "estuvo abucheando",
			nosotros: "estuvimos abucheando",
			vosotros: "estuvisteis abucheando",
			Uds: "estuvieron abucheando",
		},
		Imperfect: {
			Uds: "estaban abucheando",
			yo: "estaba abucheando",
			tú: "estabas abucheando",
			Ud: "estaba abucheando",
			nosotros: "estábamos abucheando",
			vosotros: "estabais abucheando",
		},
		Conditional: {
			yo: "estaría abucheando",
			tú: "estarías abucheando",
			Ud: "estaría abucheando",
			nosotros: "estaríamos abucheando",
			vosotros: "estaríais abucheando",
			Uds: "estarían abucheando",
		},
		Future: {
			yo: "estaré abucheando",
			tú: "estarás abucheando",
			Ud: "estará abucheando",
			nosotros: "estaremos abucheando",
			vosotros: "estaréis abucheando",
			Uds: "estarán abucheando",
		},
	},
	Perfect: {
		Present: {
			yo: "he abucheado",
			tú: "has abucheado",
			Ud: "ha abucheado",
			nosotros: "hemos abucheado",
			vosotros: "habéis abucheado",
			Uds: "han abucheado",
		},
		Preterite: {
			yo: "hube abucheado",
			tú: "hubiste abucheado",
			Ud: "hubo abucheado",
			nosotros: "hubimos abucheado",
			vosotros: "hubisteis abucheado",
			Uds: "hubieron abucheado",
		},
		Past: {
			yo: "había abucheado",
			tú: "habías abucheado",
			Ud: "había abucheado",
			nosotros: "habíamos abucheado",
			vosotros: "habíais abucheado",
			Uds: "habían abucheado",
		},
		Conditional: {
			yo: "habría abucheado",
			tú: "habrías abucheado",
			Ud: "habría abucheado",
			nosotros: "habríamos abucheado",
			vosotros: "habríais abucheado",
			Uds: "habrían abucheado",
		},
		Future: {
			yo: "habré abucheado",
			tú: "habrás abucheado",
			Ud: "habrá abucheado",
			nosotros: "habremos abucheado",
			vosotros: "habréis abucheado",
			Uds: "habrán abucheado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya abucheado",
			tú: "hayas abucheado",
			Ud: "haya abucheado",
			nosotros: "hayamos abucheado",
			vosotros: "hayáis abucheado",
			Uds: "hayan abucheado",
		},
		Past: {
			yo: "hubiera abucheado",
			tú: "hubieras abucheado",
			Ud: "hubiera abucheado",
			nosotros: "hubiéramos abucheado",
			vosotros: "hubierais abucheado",
			Uds: "hubieran abucheado",
		},
		Future: {
			yo: "hubiere abucheado",
			tú: "hubieres abucheado",
			Ud: "hubiere abucheado",
			nosotros: "hubiéremos abucheado",
			vosotros: "hubiereis abucheado",
			Uds: "hubieren abucheado",
		},
	},
}
