var acaparar = {
	Indicative: {
		Present: {
			yo: "acaparo",
			tú: "acaparas",
			Ud: "acapara",
			nosotros: "acaparamos",
			vosotros: "acaparáis",
			Uds: "acaparan",
		},
		Preterite: {
			yo: "acaparé",
			tú: "acaparaste",
			Ud: "acaparó",
			nosotros: "acaparamos",
			vosotros: "acaparasteis",
			Uds: "acapararon",
		},
		Imperfect: {
			yo: "acaparaba",
			tú: "acaparabas",
			Ud: "acaparaba",
			nosotros: "acaparábamos",
			vosotros: "acaparabais",
			Uds: "acaparaban",
		},
		Conditional: {
			yo: "acapararía",
			tú: "acapararías",
			Ud: "acapararía",
			nosotros: "acapararíamos",
			vosotros: "acapararíais",
			Uds: "acapararían",
		},
		Future: {
			yo: "acapararé",
			tú: "acapararás",
			Ud: "acaparará",
			nosotros: "acapararemos",
			vosotros: "acapararéis",
			Uds: "acapararán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "acapare",
			tú: "acapares",
			Ud: "acapare",
			nosotros: "acaparemos",
			vosotros: "acaparéis",
			Uds: "acaparen",
		},
		Imperfect: {
			yo: "acaparara",
			tú: "acapararas",
			Ud: "acaparara",
			nosotros: "acaparáramos",
			vosotros: "acapararais",
			Uds: "acapararan",
		},
		Imperfect2: {
			yo: "acaparase",
			tú: "acaparases",
			Ud: "acaparase",
			nosotros: "acaparásemos",
			vosotros: "acaparaseis",
			Uds: "acaparasen",
		},
		Future: {
			yo: "acaparare",
			tú: "acaparares",
			Ud: "acaparare",
			nosotros: "acaparáremos",
			vosotros: "acaparareis",
			Uds: "acapararen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "acapara",
			Ud: "acapare",
			nosotros: "acaparemos",
			vosotros: "acaparad",
			Uds: "acaparen",
		},
		Negative: {
			tú: "no acapares",
			Ud: "no acapare",
			nosotros: "no acaparemos",
			vosotros: "no acaparéis",
			Uds: "no acaparen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy acaparando",
			tú: "estás acaparando",
			Ud: "está acaparando",
			nosotros: "estamos acaparando",
			vosotros: "estáis acaparando",
			Uds: "están acaparando",
		},
		Preterite: {
			yo: "estuve acaparando",
			tú: "estuviste acaparando",
			Ud: "estuvo acaparando",
			nosotros: "estuvimos acaparando",
			vosotros: "estuvisteis acaparando",
			Uds: "estuvieron acaparando",
		},
		Imperfect: {
			Uds: "estaban acaparando",
			yo: "estaba acaparando",
			tú: "estabas acaparando",
			Ud: "estaba acaparando",
			nosotros: "estábamos acaparando",
			vosotros: "estabais acaparando",
		},
		Conditional: {
			yo: "estaría acaparando",
			tú: "estarías acaparando",
			Ud: "estaría acaparando",
			nosotros: "estaríamos acaparando",
			vosotros: "estaríais acaparando",
			Uds: "estarían acaparando",
		},
		Future: {
			yo: "estaré acaparando",
			tú: "estarás acaparando",
			Ud: "estará acaparando",
			nosotros: "estaremos acaparando",
			vosotros: "estaréis acaparando",
			Uds: "estarán acaparando",
		},
	},
	Perfect: {
		Present: {
			yo: "he acaparado",
			tú: "has acaparado",
			Ud: "ha acaparado",
			nosotros: "hemos acaparado",
			vosotros: "habéis acaparado",
			Uds: "han acaparado",
		},
		Preterite: {
			yo: "hube acaparado",
			tú: "hubiste acaparado",
			Ud: "hubo acaparado",
			nosotros: "hubimos acaparado",
			vosotros: "hubisteis acaparado",
			Uds: "hubieron acaparado",
		},
		Past: {
			yo: "había acaparado",
			tú: "habías acaparado",
			Ud: "había acaparado",
			nosotros: "habíamos acaparado",
			vosotros: "habíais acaparado",
			Uds: "habían acaparado",
		},
		Conditional: {
			yo: "habría acaparado",
			tú: "habrías acaparado",
			Ud: "habría acaparado",
			nosotros: "habríamos acaparado",
			vosotros: "habríais acaparado",
			Uds: "habrían acaparado",
		},
		Future: {
			yo: "habré acaparado",
			tú: "habrás acaparado",
			Ud: "habrá acaparado",
			nosotros: "habremos acaparado",
			vosotros: "habréis acaparado",
			Uds: "habrán acaparado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya acaparado",
			tú: "hayas acaparado",
			Ud: "haya acaparado",
			nosotros: "hayamos acaparado",
			vosotros: "hayáis acaparado",
			Uds: "hayan acaparado",
		},
		Past: {
			yo: "hubiera acaparado",
			tú: "hubieras acaparado",
			Ud: "hubiera acaparado",
			nosotros: "hubiéramos acaparado",
			vosotros: "hubierais acaparado",
			Uds: "hubieran acaparado",
		},
		Future: {
			yo: "hubiere acaparado",
			tú: "hubieres acaparado",
			Ud: "hubiere acaparado",
			nosotros: "hubiéremos acaparado",
			vosotros: "hubiereis acaparado",
			Uds: "hubieren acaparado",
		},
	},
}
