var acelerar = {
	Indicative: {
		Present: {
			yo: "acelero",
			tú: "aceleras",
			Ud: "acelera",
			nosotros: "aceleramos",
			vosotros: "aceleráis",
			Uds: "aceleran",
		},
		Preterite: {
			yo: "aceleré",
			tú: "aceleraste",
			Ud: "aceleró",
			nosotros: "aceleramos",
			vosotros: "acelerasteis",
			Uds: "aceleraron",
		},
		Imperfect: {
			yo: "aceleraba",
			tú: "acelerabas",
			Ud: "aceleraba",
			nosotros: "acelerábamos",
			vosotros: "acelerabais",
			Uds: "aceleraban",
		},
		Conditional: {
			yo: "aceleraría",
			tú: "acelerarías",
			Ud: "aceleraría",
			nosotros: "aceleraríamos",
			vosotros: "aceleraríais",
			Uds: "acelerarían",
		},
		Future: {
			yo: "aceleraré",
			tú: "acelerarás",
			Ud: "acelerará",
			nosotros: "aceleraremos",
			vosotros: "aceleraréis",
			Uds: "acelerarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "acelere",
			tú: "aceleres",
			Ud: "acelere",
			nosotros: "aceleremos",
			vosotros: "aceleréis",
			Uds: "aceleren",
		},
		Imperfect: {
			yo: "acelerara",
			tú: "aceleraras",
			Ud: "acelerara",
			nosotros: "aceleráramos",
			vosotros: "acelerarais",
			Uds: "aceleraran",
		},
		Imperfect2: {
			yo: "acelerase",
			tú: "acelerases",
			Ud: "acelerase",
			nosotros: "acelerásemos",
			vosotros: "aceleraseis",
			Uds: "acelerasen",
		},
		Future: {
			yo: "acelerare",
			tú: "acelerares",
			Ud: "acelerare",
			nosotros: "aceleráremos",
			vosotros: "acelerareis",
			Uds: "aceleraren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "acelera",
			Ud: "acelere",
			nosotros: "aceleremos",
			vosotros: "acelerad",
			Uds: "aceleren",
		},
		Negative: {
			tú: "no aceleres",
			Ud: "no acelere",
			nosotros: "no aceleremos",
			vosotros: "no aceleréis",
			Uds: "no aceleren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy acelerando",
			tú: "estás acelerando",
			Ud: "está acelerando",
			nosotros: "estamos acelerando",
			vosotros: "estáis acelerando",
			Uds: "están acelerando",
		},
		Preterite: {
			yo: "estuve acelerando",
			tú: "estuviste acelerando",
			Ud: "estuvo acelerando",
			nosotros: "estuvimos acelerando",
			vosotros: "estuvisteis acelerando",
			Uds: "estuvieron acelerando",
		},
		Imperfect: {
			Uds: "estaban acelerando",
			yo: "estaba acelerando",
			tú: "estabas acelerando",
			Ud: "estaba acelerando",
			nosotros: "estábamos acelerando",
			vosotros: "estabais acelerando",
		},
		Conditional: {
			yo: "estaría acelerando",
			tú: "estarías acelerando",
			Ud: "estaría acelerando",
			nosotros: "estaríamos acelerando",
			vosotros: "estaríais acelerando",
			Uds: "estarían acelerando",
		},
		Future: {
			yo: "estaré acelerando",
			tú: "estarás acelerando",
			Ud: "estará acelerando",
			nosotros: "estaremos acelerando",
			vosotros: "estaréis acelerando",
			Uds: "estarán acelerando",
		},
	},
	Perfect: {
		Present: {
			yo: "he acelerado",
			tú: "has acelerado",
			Ud: "ha acelerado",
			nosotros: "hemos acelerado",
			vosotros: "habéis acelerado",
			Uds: "han acelerado",
		},
		Preterite: {
			yo: "hube acelerado",
			tú: "hubiste acelerado",
			Ud: "hubo acelerado",
			nosotros: "hubimos acelerado",
			vosotros: "hubisteis acelerado",
			Uds: "hubieron acelerado",
		},
		Past: {
			yo: "había acelerado",
			tú: "habías acelerado",
			Ud: "había acelerado",
			nosotros: "habíamos acelerado",
			vosotros: "habíais acelerado",
			Uds: "habían acelerado",
		},
		Conditional: {
			yo: "habría acelerado",
			tú: "habrías acelerado",
			Ud: "habría acelerado",
			nosotros: "habríamos acelerado",
			vosotros: "habríais acelerado",
			Uds: "habrían acelerado",
		},
		Future: {
			yo: "habré acelerado",
			tú: "habrás acelerado",
			Ud: "habrá acelerado",
			nosotros: "habremos acelerado",
			vosotros: "habréis acelerado",
			Uds: "habrán acelerado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya acelerado",
			tú: "hayas acelerado",
			Ud: "haya acelerado",
			nosotros: "hayamos acelerado",
			vosotros: "hayáis acelerado",
			Uds: "hayan acelerado",
		},
		Past: {
			yo: "hubiera acelerado",
			tú: "hubieras acelerado",
			Ud: "hubiera acelerado",
			nosotros: "hubiéramos acelerado",
			vosotros: "hubierais acelerado",
			Uds: "hubieran acelerado",
		},
		Future: {
			yo: "hubiere acelerado",
			tú: "hubieres acelerado",
			Ud: "hubiere acelerado",
			nosotros: "hubiéremos acelerado",
			vosotros: "hubiereis acelerado",
			Uds: "hubieren acelerado",
		},
	},
}
