var acepillar = {
	Indicative: {
		Present: {
			yo: "acepillo",
			tú: "acepillas",
			Ud: "acepilla",
			nosotros: "acepillamos",
			vosotros: "acepilláis",
			Uds: "acepillan",
		},
		Preterite: {
			yo: "acepillé",
			tú: "acepillaste",
			Ud: "acepilló",
			nosotros: "acepillamos",
			vosotros: "acepillasteis",
			Uds: "acepillaron",
		},
		Imperfect: {
			yo: "acepillaba",
			tú: "acepillabas",
			Ud: "acepillaba",
			nosotros: "acepillábamos",
			vosotros: "acepillabais",
			Uds: "acepillaban",
		},
		Conditional: {
			yo: "acepillaría",
			tú: "acepillarías",
			Ud: "acepillaría",
			nosotros: "acepillaríamos",
			vosotros: "acepillaríais",
			Uds: "acepillarían",
		},
		Future: {
			yo: "acepillaré",
			tú: "acepillarás",
			Ud: "acepillará",
			nosotros: "acepillaremos",
			vosotros: "acepillaréis",
			Uds: "acepillarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "acepille",
			tú: "acepilles",
			Ud: "acepille",
			nosotros: "acepillemos",
			vosotros: "acepilléis",
			Uds: "acepillen",
		},
		Imperfect: {
			yo: "acepillara",
			tú: "acepillaras",
			Ud: "acepillara",
			nosotros: "acepilláramos",
			vosotros: "acepillarais",
			Uds: "acepillaran",
		},
		Imperfect2: {
			yo: "acepillase",
			tú: "acepillases",
			Ud: "acepillase",
			nosotros: "acepillásemos",
			vosotros: "acepillaseis",
			Uds: "acepillasen",
		},
		Future: {
			yo: "acepillare",
			tú: "acepillares",
			Ud: "acepillare",
			nosotros: "acepilláremos",
			vosotros: "acepillareis",
			Uds: "acepillaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "acepilla",
			Ud: "acepille",
			nosotros: "acepillemos",
			vosotros: "acepillad",
			Uds: "acepillen",
		},
		Negative: {
			tú: "no acepilles",
			Ud: "no acepille",
			nosotros: "no acepillemos",
			vosotros: "no acepilléis",
			Uds: "no acepillen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy acepillando",
			tú: "estás acepillando",
			Ud: "está acepillando",
			nosotros: "estamos acepillando",
			vosotros: "estáis acepillando",
			Uds: "están acepillando",
		},
		Preterite: {
			yo: "estuve acepillando",
			tú: "estuviste acepillando",
			Ud: "estuvo acepillando",
			nosotros: "estuvimos acepillando",
			vosotros: "estuvisteis acepillando",
			Uds: "estuvieron acepillando",
		},
		Imperfect: {
			Uds: "estaban acepillando",
			yo: "estaba acepillando",
			tú: "estabas acepillando",
			Ud: "estaba acepillando",
			nosotros: "estábamos acepillando",
			vosotros: "estabais acepillando",
		},
		Conditional: {
			yo: "estaría acepillando",
			tú: "estarías acepillando",
			Ud: "estaría acepillando",
			nosotros: "estaríamos acepillando",
			vosotros: "estaríais acepillando",
			Uds: "estarían acepillando",
		},
		Future: {
			yo: "estaré acepillando",
			tú: "estarás acepillando",
			Ud: "estará acepillando",
			nosotros: "estaremos acepillando",
			vosotros: "estaréis acepillando",
			Uds: "estarán acepillando",
		},
	},
	Perfect: {
		Present: {
			yo: "he acepillado",
			tú: "has acepillado",
			Ud: "ha acepillado",
			nosotros: "hemos acepillado",
			vosotros: "habéis acepillado",
			Uds: "han acepillado",
		},
		Preterite: {
			yo: "hube acepillado",
			tú: "hubiste acepillado",
			Ud: "hubo acepillado",
			nosotros: "hubimos acepillado",
			vosotros: "hubisteis acepillado",
			Uds: "hubieron acepillado",
		},
		Past: {
			yo: "había acepillado",
			tú: "habías acepillado",
			Ud: "había acepillado",
			nosotros: "habíamos acepillado",
			vosotros: "habíais acepillado",
			Uds: "habían acepillado",
		},
		Conditional: {
			yo: "habría acepillado",
			tú: "habrías acepillado",
			Ud: "habría acepillado",
			nosotros: "habríamos acepillado",
			vosotros: "habríais acepillado",
			Uds: "habrían acepillado",
		},
		Future: {
			yo: "habré acepillado",
			tú: "habrás acepillado",
			Ud: "habrá acepillado",
			nosotros: "habremos acepillado",
			vosotros: "habréis acepillado",
			Uds: "habrán acepillado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya acepillado",
			tú: "hayas acepillado",
			Ud: "haya acepillado",
			nosotros: "hayamos acepillado",
			vosotros: "hayáis acepillado",
			Uds: "hayan acepillado",
		},
		Past: {
			yo: "hubiera acepillado",
			tú: "hubieras acepillado",
			Ud: "hubiera acepillado",
			nosotros: "hubiéramos acepillado",
			vosotros: "hubierais acepillado",
			Uds: "hubieran acepillado",
		},
		Future: {
			yo: "hubiere acepillado",
			tú: "hubieres acepillado",
			Ud: "hubiere acepillado",
			nosotros: "hubiéremos acepillado",
			vosotros: "hubiereis acepillado",
			Uds: "hubieren acepillado",
		},
	},
}
