var acolchar = {
	Indicative: {
		Present: {
			yo: "acolcho",
			tú: "acolchas",
			Ud: "acolcha",
			nosotros: "acolchamos",
			vosotros: "acolcháis",
			Uds: "acolchan",
		},
		Preterite: {
			yo: "acolché",
			tú: "acolchaste",
			Ud: "acolchó",
			nosotros: "acolchamos",
			vosotros: "acolchasteis",
			Uds: "acolcharon",
		},
		Imperfect: {
			yo: "acolchaba",
			tú: "acolchabas",
			Ud: "acolchaba",
			nosotros: "acolchábamos",
			vosotros: "acolchabais",
			Uds: "acolchaban",
		},
		Conditional: {
			yo: "acolcharía",
			tú: "acolcharías",
			Ud: "acolcharía",
			nosotros: "acolcharíamos",
			vosotros: "acolcharíais",
			Uds: "acolcharían",
		},
		Future: {
			yo: "acolcharé",
			tú: "acolcharás",
			Ud: "acolchará",
			nosotros: "acolcharemos",
			vosotros: "acolcharéis",
			Uds: "acolcharán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "acolche",
			tú: "acolches",
			Ud: "acolche",
			nosotros: "acolchemos",
			vosotros: "acolchéis",
			Uds: "acolchen",
		},
		Imperfect: {
			yo: "acolchara",
			tú: "acolcharas",
			Ud: "acolchara",
			nosotros: "acolcháramos",
			vosotros: "acolcharais",
			Uds: "acolcharan",
		},
		Imperfect2: {
			yo: "acolchase",
			tú: "acolchases",
			Ud: "acolchase",
			nosotros: "acolchásemos",
			vosotros: "acolchaseis",
			Uds: "acolchasen",
		},
		Future: {
			yo: "acolchare",
			tú: "acolchares",
			Ud: "acolchare",
			nosotros: "acolcháremos",
			vosotros: "acolchareis",
			Uds: "acolcharen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "acolcha",
			Ud: "acolche",
			nosotros: "acolchemos",
			vosotros: "acolchad",
			Uds: "acolchen",
		},
		Negative: {
			tú: "no acolches",
			Ud: "no acolche",
			nosotros: "no acolchemos",
			vosotros: "no acolchéis",
			Uds: "no acolchen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy acolchando",
			tú: "estás acolchando",
			Ud: "está acolchando",
			nosotros: "estamos acolchando",
			vosotros: "estáis acolchando",
			Uds: "están acolchando",
		},
		Preterite: {
			yo: "estuve acolchando",
			tú: "estuviste acolchando",
			Ud: "estuvo acolchando",
			nosotros: "estuvimos acolchando",
			vosotros: "estuvisteis acolchando",
			Uds: "estuvieron acolchando",
		},
		Imperfect: {
			Uds: "estaban acolchando",
			yo: "estaba acolchando",
			tú: "estabas acolchando",
			Ud: "estaba acolchando",
			nosotros: "estábamos acolchando",
			vosotros: "estabais acolchando",
		},
		Conditional: {
			yo: "estaría acolchando",
			tú: "estarías acolchando",
			Ud: "estaría acolchando",
			nosotros: "estaríamos acolchando",
			vosotros: "estaríais acolchando",
			Uds: "estarían acolchando",
		},
		Future: {
			yo: "estaré acolchando",
			tú: "estarás acolchando",
			Ud: "estará acolchando",
			nosotros: "estaremos acolchando",
			vosotros: "estaréis acolchando",
			Uds: "estarán acolchando",
		},
	},
	Perfect: {
		Present: {
			yo: "he acolchado",
			tú: "has acolchado",
			Ud: "ha acolchado",
			nosotros: "hemos acolchado",
			vosotros: "habéis acolchado",
			Uds: "han acolchado",
		},
		Preterite: {
			yo: "hube acolchado",
			tú: "hubiste acolchado",
			Ud: "hubo acolchado",
			nosotros: "hubimos acolchado",
			vosotros: "hubisteis acolchado",
			Uds: "hubieron acolchado",
		},
		Past: {
			yo: "había acolchado",
			tú: "habías acolchado",
			Ud: "había acolchado",
			nosotros: "habíamos acolchado",
			vosotros: "habíais acolchado",
			Uds: "habían acolchado",
		},
		Conditional: {
			yo: "habría acolchado",
			tú: "habrías acolchado",
			Ud: "habría acolchado",
			nosotros: "habríamos acolchado",
			vosotros: "habríais acolchado",
			Uds: "habrían acolchado",
		},
		Future: {
			yo: "habré acolchado",
			tú: "habrás acolchado",
			Ud: "habrá acolchado",
			nosotros: "habremos acolchado",
			vosotros: "habréis acolchado",
			Uds: "habrán acolchado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya acolchado",
			tú: "hayas acolchado",
			Ud: "haya acolchado",
			nosotros: "hayamos acolchado",
			vosotros: "hayáis acolchado",
			Uds: "hayan acolchado",
		},
		Past: {
			yo: "hubiera acolchado",
			tú: "hubieras acolchado",
			Ud: "hubiera acolchado",
			nosotros: "hubiéramos acolchado",
			vosotros: "hubierais acolchado",
			Uds: "hubieran acolchado",
		},
		Future: {
			yo: "hubiere acolchado",
			tú: "hubieres acolchado",
			Ud: "hubiere acolchado",
			nosotros: "hubiéremos acolchado",
			vosotros: "hubiereis acolchado",
			Uds: "hubieren acolchado",
		},
	},
}
