var acortar = {
	Indicative: {
		Present: {
			yo: "acorto",
			tú: "acortas",
			Ud: "acorta",
			nosotros: "acortamos",
			vosotros: "acortáis",
			Uds: "acortan",
		},
		Preterite: {
			yo: "acorté",
			tú: "acortaste",
			Ud: "acortó",
			nosotros: "acortamos",
			vosotros: "acortasteis",
			Uds: "acortaron",
		},
		Imperfect: {
			yo: "acortaba",
			tú: "acortabas",
			Ud: "acortaba",
			nosotros: "acortábamos",
			vosotros: "acortabais",
			Uds: "acortaban",
		},
		Conditional: {
			yo: "acortaría",
			tú: "acortarías",
			Ud: "acortaría",
			nosotros: "acortaríamos",
			vosotros: "acortaríais",
			Uds: "acortarían",
		},
		Future: {
			yo: "acortaré",
			tú: "acortarás",
			Ud: "acortará",
			nosotros: "acortaremos",
			vosotros: "acortaréis",
			Uds: "acortarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "acorte",
			tú: "acortes",
			Ud: "acorte",
			nosotros: "acortemos",
			vosotros: "acortéis",
			Uds: "acorten",
		},
		Imperfect: {
			yo: "acortara",
			tú: "acortaras",
			Ud: "acortara",
			nosotros: "acortáramos",
			vosotros: "acortarais",
			Uds: "acortaran",
		},
		Imperfect2: {
			yo: "acortase",
			tú: "acortases",
			Ud: "acortase",
			nosotros: "acortásemos",
			vosotros: "acortaseis",
			Uds: "acortasen",
		},
		Future: {
			yo: "acortare",
			tú: "acortares",
			Ud: "acortare",
			nosotros: "acortáremos",
			vosotros: "acortareis",
			Uds: "acortaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "acorta",
			Ud: "acorte",
			nosotros: "acortemos",
			vosotros: "acortad",
			Uds: "acorten",
		},
		Negative: {
			tú: "no acortes",
			Ud: "no acorte",
			nosotros: "no acortemos",
			vosotros: "no acortéis",
			Uds: "no acorten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy acortando",
			tú: "estás acortando",
			Ud: "está acortando",
			nosotros: "estamos acortando",
			vosotros: "estáis acortando",
			Uds: "están acortando",
		},
		Preterite: {
			yo: "estuve acortando",
			tú: "estuviste acortando",
			Ud: "estuvo acortando",
			nosotros: "estuvimos acortando",
			vosotros: "estuvisteis acortando",
			Uds: "estuvieron acortando",
		},
		Imperfect: {
			Uds: "estaban acortando",
			yo: "estaba acortando",
			tú: "estabas acortando",
			Ud: "estaba acortando",
			nosotros: "estábamos acortando",
			vosotros: "estabais acortando",
		},
		Conditional: {
			yo: "estaría acortando",
			tú: "estarías acortando",
			Ud: "estaría acortando",
			nosotros: "estaríamos acortando",
			vosotros: "estaríais acortando",
			Uds: "estarían acortando",
		},
		Future: {
			yo: "estaré acortando",
			tú: "estarás acortando",
			Ud: "estará acortando",
			nosotros: "estaremos acortando",
			vosotros: "estaréis acortando",
			Uds: "estarán acortando",
		},
	},
	Perfect: {
		Present: {
			yo: "he acortado",
			tú: "has acortado",
			Ud: "ha acortado",
			nosotros: "hemos acortado",
			vosotros: "habéis acortado",
			Uds: "han acortado",
		},
		Preterite: {
			yo: "hube acortado",
			tú: "hubiste acortado",
			Ud: "hubo acortado",
			nosotros: "hubimos acortado",
			vosotros: "hubisteis acortado",
			Uds: "hubieron acortado",
		},
		Past: {
			yo: "había acortado",
			tú: "habías acortado",
			Ud: "había acortado",
			nosotros: "habíamos acortado",
			vosotros: "habíais acortado",
			Uds: "habían acortado",
		},
		Conditional: {
			yo: "habría acortado",
			tú: "habrías acortado",
			Ud: "habría acortado",
			nosotros: "habríamos acortado",
			vosotros: "habríais acortado",
			Uds: "habrían acortado",
		},
		Future: {
			yo: "habré acortado",
			tú: "habrás acortado",
			Ud: "habrá acortado",
			nosotros: "habremos acortado",
			vosotros: "habréis acortado",
			Uds: "habrán acortado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya acortado",
			tú: "hayas acortado",
			Ud: "haya acortado",
			nosotros: "hayamos acortado",
			vosotros: "hayáis acortado",
			Uds: "hayan acortado",
		},
		Past: {
			yo: "hubiera acortado",
			tú: "hubieras acortado",
			Ud: "hubiera acortado",
			nosotros: "hubiéramos acortado",
			vosotros: "hubierais acortado",
			Uds: "hubieran acortado",
		},
		Future: {
			yo: "hubiere acortado",
			tú: "hubieres acortado",
			Ud: "hubiere acortado",
			nosotros: "hubiéremos acortado",
			vosotros: "hubiereis acortado",
			Uds: "hubieren acortado",
		},
	},
}
