var acordar = {
	Indicative: {
		Present: {
			yo: "acuerdo",
			tú: "acuerdas",
			Ud: "acuerda",
			nosotros: "acordamos",
			vosotros: "acordáis",
			Uds: "acuerdan",
		},
		Preterite: {
			yo: "acordé",
			tú: "acordaste",
			Ud: "acordó",
			nosotros: "acordamos",
			vosotros: "acordasteis",
			Uds: "acordaron",
		},
		Imperfect: {
			yo: "acordaba",
			tú: "acordabas",
			Ud: "acordaba",
			nosotros: "acordábamos",
			vosotros: "acordabais",
			Uds: "acordaban",
		},
		Conditional: {
			yo: "acordaría",
			tú: "acordarías",
			Ud: "acordaría",
			nosotros: "acordaríamos",
			vosotros: "acordaríais",
			Uds: "acordarían",
		},
		Future: {
			yo: "acordaré",
			tú: "acordarás",
			Ud: "acordará",
			nosotros: "acordaremos",
			vosotros: "acordaréis",
			Uds: "acordarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "acuerde",
			tú: "acuerdes",
			Ud: "acuerde",
			nosotros: "acordemos",
			vosotros: "acordéis",
			Uds: "acuerden",
		},
		Imperfect: {
			yo: "acordara",
			tú: "acordaras",
			Ud: "acordara",
			nosotros: "acordáramos",
			vosotros: "acordarais",
			Uds: "acordaran",
		},
		Imperfect2: {
			yo: "acordase",
			tú: "acordases",
			Ud: "acordase",
			nosotros: "acordásemos",
			vosotros: "acordaseis",
			Uds: "acordasen",
		},
		Future: {
			yo: "acordare",
			tú: "acordares",
			Ud: "acordare",
			nosotros: "acordáremos",
			vosotros: "acordareis",
			Uds: "acordaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "acuerda",
			Ud: "acuerde",
			nosotros: "acordemos",
			vosotros: "acordad",
			Uds: "acuerden",
		},
		Negative: {
			tú: "no acuerdes",
			Ud: "no acuerde",
			nosotros: "no acordemos",
			vosotros: "no acordéis",
			Uds: "no acuerden",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy acordando",
			tú: "estás acordando",
			Ud: "está acordando",
			nosotros: "estamos acordando",
			vosotros: "estáis acordando",
			Uds: "están acordando",
		},
		Preterite: {
			yo: "estuve acordando",
			tú: "estuviste acordando",
			Ud: "estuvo acordando",
			nosotros: "estuvimos acordando",
			vosotros: "estuvisteis acordando",
			Uds: "estuvieron acordando",
		},
		Imperfect: {
			Uds: "estaban acordando",
			yo: "estaba acordando",
			tú: "estabas acordando",
			Ud: "estaba acordando",
			nosotros: "estábamos acordando",
			vosotros: "estabais acordando",
		},
		Conditional: {
			yo: "estaría acordando",
			tú: "estarías acordando",
			Ud: "estaría acordando",
			nosotros: "estaríamos acordando",
			vosotros: "estaríais acordando",
			Uds: "estarían acordando",
		},
		Future: {
			yo: "estaré acordando",
			tú: "estarás acordando",
			Ud: "estará acordando",
			nosotros: "estaremos acordando",
			vosotros: "estaréis acordando",
			Uds: "estarán acordando",
		},
	},
	Perfect: {
		Present: {
			yo: "he acordado",
			tú: "has acordado",
			Ud: "ha acordado",
			nosotros: "hemos acordado",
			vosotros: "habéis acordado",
			Uds: "han acordado",
		},
		Preterite: {
			yo: "hube acordado",
			tú: "hubiste acordado",
			Ud: "hubo acordado",
			nosotros: "hubimos acordado",
			vosotros: "hubisteis acordado",
			Uds: "hubieron acordado",
		},
		Past: {
			yo: "había acordado",
			tú: "habías acordado",
			Ud: "había acordado",
			nosotros: "habíamos acordado",
			vosotros: "habíais acordado",
			Uds: "habían acordado",
		},
		Conditional: {
			yo: "habría acordado",
			tú: "habrías acordado",
			Ud: "habría acordado",
			nosotros: "habríamos acordado",
			vosotros: "habríais acordado",
			Uds: "habrían acordado",
		},
		Future: {
			yo: "habré acordado",
			tú: "habrás acordado",
			Ud: "habrá acordado",
			nosotros: "habremos acordado",
			vosotros: "habréis acordado",
			Uds: "habrán acordado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya acordado",
			tú: "hayas acordado",
			Ud: "haya acordado",
			nosotros: "hayamos acordado",
			vosotros: "hayáis acordado",
			Uds: "hayan acordado",
		},
		Past: {
			yo: "hubiera acordado",
			tú: "hubieras acordado",
			Ud: "hubiera acordado",
			nosotros: "hubiéramos acordado",
			vosotros: "hubierais acordado",
			Uds: "hubieran acordado",
		},
		Future: {
			yo: "hubiere acordado",
			tú: "hubieres acordado",
			Ud: "hubiere acordado",
			nosotros: "hubiéremos acordado",
			vosotros: "hubiereis acordado",
			Uds: "hubieren acordado",
		},
	},
}
