var acrecentar = {
	Indicative: {
		Present: {
			yo: "acreciento",
			tú: "acrecientas",
			Ud: "acrecienta",
			nosotros: "acrecentamos",
			vosotros: "acrecentáis",
			Uds: "acrecientan",
		},
		Preterite: {
			yo: "acrecenté",
			tú: "acrecentaste",
			Ud: "acrecentó",
			nosotros: "acrecentamos",
			vosotros: "acrecentasteis",
			Uds: "acrecentaron",
		},
		Imperfect: {
			yo: "acrecentaba",
			tú: "acrecentabas",
			Ud: "acrecentaba",
			nosotros: "acrecentábamos",
			vosotros: "acrecentabais",
			Uds: "acrecentaban",
		},
		Conditional: {
			yo: "acrecentaría",
			tú: "acrecentarías",
			Ud: "acrecentaría",
			nosotros: "acrecentaríamos",
			vosotros: "acrecentaríais",
			Uds: "acrecentarían",
		},
		Future: {
			yo: "acrecentaré",
			tú: "acrecentarás",
			Ud: "acrecentará",
			nosotros: "acrecentaremos",
			vosotros: "acrecentaréis",
			Uds: "acrecentarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "acreciente",
			tú: "acrecientes",
			Ud: "acreciente",
			nosotros: "acrecentemos",
			vosotros: "acrecentéis",
			Uds: "acrecienten",
		},
		Imperfect: {
			yo: "acrecentara",
			tú: "acrecentaras",
			Ud: "acrecentara",
			nosotros: "acrecentáramos",
			vosotros: "acrecentarais",
			Uds: "acrecentaran",
		},
		Imperfect2: {
			yo: "acrecentase",
			tú: "acrecentases",
			Ud: "acrecentase",
			nosotros: "acrecentásemos",
			vosotros: "acrecentaseis",
			Uds: "acrecentasen",
		},
		Future: {
			yo: "acrecentare",
			tú: "acrecentares",
			Ud: "acrecentare",
			nosotros: "acrecentáremos",
			vosotros: "acrecentareis",
			Uds: "acrecentaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "acrecienta",
			Ud: "acreciente",
			nosotros: "acrecentemos",
			vosotros: "acrecentad",
			Uds: "acrecienten",
		},
		Negative: {
			tú: "no acrecientes",
			Ud: "no acreciente",
			nosotros: "no acrecentemos",
			vosotros: "no acrecentéis",
			Uds: "no acrecienten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy acrecentando",
			tú: "estás acrecentando",
			Ud: "está acrecentando",
			nosotros: "estamos acrecentando",
			vosotros: "estáis acrecentando",
			Uds: "están acrecentando",
		},
		Preterite: {
			yo: "estuve acrecentando",
			tú: "estuviste acrecentando",
			Ud: "estuvo acrecentando",
			nosotros: "estuvimos acrecentando",
			vosotros: "estuvisteis acrecentando",
			Uds: "estuvieron acrecentando",
		},
		Imperfect: {
			Uds: "estaban acrecentando",
			yo: "estaba acrecentando",
			tú: "estabas acrecentando",
			Ud: "estaba acrecentando",
			nosotros: "estábamos acrecentando",
			vosotros: "estabais acrecentando",
		},
		Conditional: {
			yo: "estaría acrecentando",
			tú: "estarías acrecentando",
			Ud: "estaría acrecentando",
			nosotros: "estaríamos acrecentando",
			vosotros: "estaríais acrecentando",
			Uds: "estarían acrecentando",
		},
		Future: {
			yo: "estaré acrecentando",
			tú: "estarás acrecentando",
			Ud: "estará acrecentando",
			nosotros: "estaremos acrecentando",
			vosotros: "estaréis acrecentando",
			Uds: "estarán acrecentando",
		},
	},
	Perfect: {
		Present: {
			yo: "he acrecentado",
			tú: "has acrecentado",
			Ud: "ha acrecentado",
			nosotros: "hemos acrecentado",
			vosotros: "habéis acrecentado",
			Uds: "han acrecentado",
		},
		Preterite: {
			yo: "hube acrecentado",
			tú: "hubiste acrecentado",
			Ud: "hubo acrecentado",
			nosotros: "hubimos acrecentado",
			vosotros: "hubisteis acrecentado",
			Uds: "hubieron acrecentado",
		},
		Past: {
			yo: "había acrecentado",
			tú: "habías acrecentado",
			Ud: "había acrecentado",
			nosotros: "habíamos acrecentado",
			vosotros: "habíais acrecentado",
			Uds: "habían acrecentado",
		},
		Conditional: {
			yo: "habría acrecentado",
			tú: "habrías acrecentado",
			Ud: "habría acrecentado",
			nosotros: "habríamos acrecentado",
			vosotros: "habríais acrecentado",
			Uds: "habrían acrecentado",
		},
		Future: {
			yo: "habré acrecentado",
			tú: "habrás acrecentado",
			Ud: "habrá acrecentado",
			nosotros: "habremos acrecentado",
			vosotros: "habréis acrecentado",
			Uds: "habrán acrecentado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya acrecentado",
			tú: "hayas acrecentado",
			Ud: "haya acrecentado",
			nosotros: "hayamos acrecentado",
			vosotros: "hayáis acrecentado",
			Uds: "hayan acrecentado",
		},
		Past: {
			yo: "hubiera acrecentado",
			tú: "hubieras acrecentado",
			Ud: "hubiera acrecentado",
			nosotros: "hubiéramos acrecentado",
			vosotros: "hubierais acrecentado",
			Uds: "hubieran acrecentado",
		},
		Future: {
			yo: "hubiere acrecentado",
			tú: "hubieres acrecentado",
			Ud: "hubiere acrecentado",
			nosotros: "hubiéremos acrecentado",
			vosotros: "hubiereis acrecentado",
			Uds: "hubieren acrecentado",
		},
	},
}
