var activar = {
	Indicative: {
		Present: {
			yo: "activo",
			tú: "activas",
			Ud: "activa",
			nosotros: "activamos",
			vosotros: "activáis",
			Uds: "activan",
		},
		Preterite: {
			yo: "activé",
			tú: "activaste",
			Ud: "activó",
			nosotros: "activamos",
			vosotros: "activasteis",
			Uds: "activaron",
		},
		Imperfect: {
			yo: "activaba",
			tú: "activabas",
			Ud: "activaba",
			nosotros: "activábamos",
			vosotros: "activabais",
			Uds: "activaban",
		},
		Conditional: {
			yo: "activaría",
			tú: "activarías",
			Ud: "activaría",
			nosotros: "activaríamos",
			vosotros: "activaríais",
			Uds: "activarían",
		},
		Future: {
			yo: "activaré",
			tú: "activarás",
			Ud: "activará",
			nosotros: "activaremos",
			vosotros: "activaréis",
			Uds: "activarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "active",
			tú: "actives",
			Ud: "active",
			nosotros: "activemos",
			vosotros: "activéis",
			Uds: "activen",
		},
		Imperfect: {
			yo: "activara",
			tú: "activaras",
			Ud: "activara",
			nosotros: "activáramos",
			vosotros: "activarais",
			Uds: "activaran",
		},
		Imperfect2: {
			yo: "activase",
			tú: "activases",
			Ud: "activase",
			nosotros: "activásemos",
			vosotros: "activaseis",
			Uds: "activasen",
		},
		Future: {
			yo: "activare",
			tú: "activares",
			Ud: "activare",
			nosotros: "activáremos",
			vosotros: "activareis",
			Uds: "activaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "activa",
			Ud: "active",
			nosotros: "activemos",
			vosotros: "activad",
			Uds: "activen",
		},
		Negative: {
			tú: "no actives",
			Ud: "no active",
			nosotros: "no activemos",
			vosotros: "no activéis",
			Uds: "no activen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy activando",
			tú: "estás activando",
			Ud: "está activando",
			nosotros: "estamos activando",
			vosotros: "estáis activando",
			Uds: "están activando",
		},
		Preterite: {
			yo: "estuve activando",
			tú: "estuviste activando",
			Ud: "estuvo activando",
			nosotros: "estuvimos activando",
			vosotros: "estuvisteis activando",
			Uds: "estuvieron activando",
		},
		Imperfect: {
			Uds: "estaban activando",
			yo: "estaba activando",
			tú: "estabas activando",
			Ud: "estaba activando",
			nosotros: "estábamos activando",
			vosotros: "estabais activando",
		},
		Conditional: {
			yo: "estaría activando",
			tú: "estarías activando",
			Ud: "estaría activando",
			nosotros: "estaríamos activando",
			vosotros: "estaríais activando",
			Uds: "estarían activando",
		},
		Future: {
			yo: "estaré activando",
			tú: "estarás activando",
			Ud: "estará activando",
			nosotros: "estaremos activando",
			vosotros: "estaréis activando",
			Uds: "estarán activando",
		},
	},
	Perfect: {
		Present: {
			yo: "he activado",
			tú: "has activado",
			Ud: "ha activado",
			nosotros: "hemos activado",
			vosotros: "habéis activado",
			Uds: "han activado",
		},
		Preterite: {
			yo: "hube activado",
			tú: "hubiste activado",
			Ud: "hubo activado",
			nosotros: "hubimos activado",
			vosotros: "hubisteis activado",
			Uds: "hubieron activado",
		},
		Past: {
			yo: "había activado",
			tú: "habías activado",
			Ud: "había activado",
			nosotros: "habíamos activado",
			vosotros: "habíais activado",
			Uds: "habían activado",
		},
		Conditional: {
			yo: "habría activado",
			tú: "habrías activado",
			Ud: "habría activado",
			nosotros: "habríamos activado",
			vosotros: "habríais activado",
			Uds: "habrían activado",
		},
		Future: {
			yo: "habré activado",
			tú: "habrás activado",
			Ud: "habrá activado",
			nosotros: "habremos activado",
			vosotros: "habréis activado",
			Uds: "habrán activado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya activado",
			tú: "hayas activado",
			Ud: "haya activado",
			nosotros: "hayamos activado",
			vosotros: "hayáis activado",
			Uds: "hayan activado",
		},
		Past: {
			yo: "hubiera activado",
			tú: "hubieras activado",
			Ud: "hubiera activado",
			nosotros: "hubiéramos activado",
			vosotros: "hubierais activado",
			Uds: "hubieran activado",
		},
		Future: {
			yo: "hubiere activado",
			tú: "hubieres activado",
			Ud: "hubiere activado",
			nosotros: "hubiéremos activado",
			vosotros: "hubiereis activado",
			Uds: "hubieren activado",
		},
	},
}
