var actuar = {
	Indicative: {
		Present: {
			yo: "actúo",
			tú: "actúas",
			Ud: "actúa",
			nosotros: "actuamos",
			vosotros: "actuáis",
			Uds: "actúan",
		},
		Preterite: {
			yo: "actué",
			tú: "actuaste",
			Ud: "actuó",
			nosotros: "actuamos",
			vosotros: "actuasteis",
			Uds: "actuaron",
		},
		Imperfect: {
			yo: "actuaba",
			tú: "actuabas",
			Ud: "actuaba",
			nosotros: "actuábamos",
			vosotros: "actuabais",
			Uds: "actuaban",
		},
		Conditional: {
			yo: "actuaría",
			tú: "actuarías",
			Ud: "actuaría",
			nosotros: "actuaríamos",
			vosotros: "actuaríais",
			Uds: "actuarían",
		},
		Future: {
			yo: "actuaré",
			tú: "actuarás",
			Ud: "actuará",
			nosotros: "actuaremos",
			vosotros: "actuaréis",
			Uds: "actuarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "actúe",
			tú: "actúes",
			Ud: "actúe",
			nosotros: "actuemos",
			vosotros: "actuéis",
			Uds: "actúen",
		},
		Imperfect: {
			yo: "actuara",
			tú: "actuaras",
			Ud: "actuara",
			nosotros: "actuáramos",
			vosotros: "actuarais",
			Uds: "actuaran",
		},
		Imperfect2: {
			yo: "actuase",
			tú: "actuases",
			Ud: "actuase",
			nosotros: "actuásemos",
			vosotros: "actuaseis",
			Uds: "actuasen",
		},
		Future: {
			yo: "actuare",
			tú: "actuares",
			Ud: "actuare",
			nosotros: "actuáremos",
			vosotros: "actuareis",
			Uds: "actuaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "actúa",
			Ud: "actúe",
			nosotros: "actuemos",
			vosotros: "actuad",
			Uds: "actúen",
		},
		Negative: {
			tú: "no actúes",
			Ud: "no actúe",
			nosotros: "no actuemos",
			vosotros: "no actuéis",
			Uds: "no actúen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy actuando",
			tú: "estás actuando",
			Ud: "está actuando",
			nosotros: "estamos actuando",
			vosotros: "estáis actuando",
			Uds: "están actuando",
		},
		Preterite: {
			yo: "estuve actuando",
			tú: "estuviste actuando",
			Ud: "estuvo actuando",
			nosotros: "estuvimos actuando",
			vosotros: "estuvisteis actuando",
			Uds: "estuvieron actuando",
		},
		Imperfect: {
			Uds: "estaban actuando",
			yo: "estaba actuando",
			tú: "estabas actuando",
			Ud: "estaba actuando",
			nosotros: "estábamos actuando",
			vosotros: "estabais actuando",
		},
		Conditional: {
			yo: "estaría actuando",
			tú: "estarías actuando",
			Ud: "estaría actuando",
			nosotros: "estaríamos actuando",
			vosotros: "estaríais actuando",
			Uds: "estarían actuando",
		},
		Future: {
			yo: "estaré actuando",
			tú: "estarás actuando",
			Ud: "estará actuando",
			nosotros: "estaremos actuando",
			vosotros: "estaréis actuando",
			Uds: "estarán actuando",
		},
	},
	Perfect: {
		Present: {
			yo: "he actuado",
			tú: "has actuado",
			Ud: "ha actuado",
			nosotros: "hemos actuado",
			vosotros: "habéis actuado",
			Uds: "han actuado",
		},
		Preterite: {
			yo: "hube actuado",
			tú: "hubiste actuado",
			Ud: "hubo actuado",
			nosotros: "hubimos actuado",
			vosotros: "hubisteis actuado",
			Uds: "hubieron actuado",
		},
		Past: {
			yo: "había actuado",
			tú: "habías actuado",
			Ud: "había actuado",
			nosotros: "habíamos actuado",
			vosotros: "habíais actuado",
			Uds: "habían actuado",
		},
		Conditional: {
			yo: "habría actuado",
			tú: "habrías actuado",
			Ud: "habría actuado",
			nosotros: "habríamos actuado",
			vosotros: "habríais actuado",
			Uds: "habrían actuado",
		},
		Future: {
			yo: "habré actuado",
			tú: "habrás actuado",
			Ud: "habrá actuado",
			nosotros: "habremos actuado",
			vosotros: "habréis actuado",
			Uds: "habrán actuado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya actuado",
			tú: "hayas actuado",
			Ud: "haya actuado",
			nosotros: "hayamos actuado",
			vosotros: "hayáis actuado",
			Uds: "hayan actuado",
		},
		Past: {
			yo: "hubiera actuado",
			tú: "hubieras actuado",
			Ud: "hubiera actuado",
			nosotros: "hubiéramos actuado",
			vosotros: "hubierais actuado",
			Uds: "hubieran actuado",
		},
		Future: {
			yo: "hubiere actuado",
			tú: "hubieres actuado",
			Ud: "hubiere actuado",
			nosotros: "hubiéremos actuado",
			vosotros: "hubiereis actuado",
			Uds: "hubieren actuado",
		},
	},
}
