var acusar = {
	Indicative: {
		Present: {
			yo: "acuso",
			tú: "acusas",
			Ud: "acusa",
			nosotros: "acusamos",
			vosotros: "acusáis",
			Uds: "acusan",
		},
		Preterite: {
			yo: "acusé",
			tú: "acusaste",
			Ud: "acusó",
			nosotros: "acusamos",
			vosotros: "acusasteis",
			Uds: "acusaron",
		},
		Imperfect: {
			yo: "acusaba",
			tú: "acusabas",
			Ud: "acusaba",
			nosotros: "acusábamos",
			vosotros: "acusabais",
			Uds: "acusaban",
		},
		Conditional: {
			yo: "acusaría",
			tú: "acusarías",
			Ud: "acusaría",
			nosotros: "acusaríamos",
			vosotros: "acusaríais",
			Uds: "acusarían",
		},
		Future: {
			yo: "acusaré",
			tú: "acusarás",
			Ud: "acusará",
			nosotros: "acusaremos",
			vosotros: "acusaréis",
			Uds: "acusarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "acuse",
			tú: "acuses",
			Ud: "acuse",
			nosotros: "acusemos",
			vosotros: "acuséis",
			Uds: "acusen",
		},
		Imperfect: {
			yo: "acusara",
			tú: "acusaras",
			Ud: "acusara",
			nosotros: "acusáramos",
			vosotros: "acusarais",
			Uds: "acusaran",
		},
		Imperfect2: {
			yo: "acusase",
			tú: "acusases",
			Ud: "acusase",
			nosotros: "acusásemos",
			vosotros: "acusaseis",
			Uds: "acusasen",
		},
		Future: {
			yo: "acusare",
			tú: "acusares",
			Ud: "acusare",
			nosotros: "acusáremos",
			vosotros: "acusareis",
			Uds: "acusaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "acusa",
			Ud: "acuse",
			nosotros: "acusemos",
			vosotros: "acusad",
			Uds: "acusen",
		},
		Negative: {
			tú: "no acuses",
			Ud: "no acuse",
			nosotros: "no acusemos",
			vosotros: "no acuséis",
			Uds: "no acusen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy acusando",
			tú: "estás acusando",
			Ud: "está acusando",
			nosotros: "estamos acusando",
			vosotros: "estáis acusando",
			Uds: "están acusando",
		},
		Preterite: {
			yo: "estuve acusando",
			tú: "estuviste acusando",
			Ud: "estuvo acusando",
			nosotros: "estuvimos acusando",
			vosotros: "estuvisteis acusando",
			Uds: "estuvieron acusando",
		},
		Imperfect: {
			Uds: "estaban acusando",
			yo: "estaba acusando",
			tú: "estabas acusando",
			Ud: "estaba acusando",
			nosotros: "estábamos acusando",
			vosotros: "estabais acusando",
		},
		Conditional: {
			yo: "estaría acusando",
			tú: "estarías acusando",
			Ud: "estaría acusando",
			nosotros: "estaríamos acusando",
			vosotros: "estaríais acusando",
			Uds: "estarían acusando",
		},
		Future: {
			yo: "estaré acusando",
			tú: "estarás acusando",
			Ud: "estará acusando",
			nosotros: "estaremos acusando",
			vosotros: "estaréis acusando",
			Uds: "estarán acusando",
		},
	},
	Perfect: {
		Present: {
			yo: "he acusado",
			tú: "has acusado",
			Ud: "ha acusado",
			nosotros: "hemos acusado",
			vosotros: "habéis acusado",
			Uds: "han acusado",
		},
		Preterite: {
			yo: "hube acusado",
			tú: "hubiste acusado",
			Ud: "hubo acusado",
			nosotros: "hubimos acusado",
			vosotros: "hubisteis acusado",
			Uds: "hubieron acusado",
		},
		Past: {
			yo: "había acusado",
			tú: "habías acusado",
			Ud: "había acusado",
			nosotros: "habíamos acusado",
			vosotros: "habíais acusado",
			Uds: "habían acusado",
		},
		Conditional: {
			yo: "habría acusado",
			tú: "habrías acusado",
			Ud: "habría acusado",
			nosotros: "habríamos acusado",
			vosotros: "habríais acusado",
			Uds: "habrían acusado",
		},
		Future: {
			yo: "habré acusado",
			tú: "habrás acusado",
			Ud: "habrá acusado",
			nosotros: "habremos acusado",
			vosotros: "habréis acusado",
			Uds: "habrán acusado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya acusado",
			tú: "hayas acusado",
			Ud: "haya acusado",
			nosotros: "hayamos acusado",
			vosotros: "hayáis acusado",
			Uds: "hayan acusado",
		},
		Past: {
			yo: "hubiera acusado",
			tú: "hubieras acusado",
			Ud: "hubiera acusado",
			nosotros: "hubiéramos acusado",
			vosotros: "hubierais acusado",
			Uds: "hubieran acusado",
		},
		Future: {
			yo: "hubiere acusado",
			tú: "hubieres acusado",
			Ud: "hubiere acusado",
			nosotros: "hubiéremos acusado",
			vosotros: "hubiereis acusado",
			Uds: "hubieren acusado",
		},
	},
}
