var acuñar = {
	Indicative: {
		Present: {
			yo: "acuño",
			tú: "acuñas",
			Ud: "acuña",
			nosotros: "acuñamos",
			vosotros: "acuñáis",
			Uds: "acuñan",
		},
		Preterite: {
			yo: "acuñé",
			tú: "acuñaste",
			Ud: "acuñó",
			nosotros: "acuñamos",
			vosotros: "acuñasteis",
			Uds: "acuñaron",
		},
		Imperfect: {
			yo: "acuñaba",
			tú: "acuñabas",
			Ud: "acuñaba",
			nosotros: "acuñábamos",
			vosotros: "acuñabais",
			Uds: "acuñaban",
		},
		Conditional: {
			yo: "acuñaría",
			tú: "acuñarías",
			Ud: "acuñaría",
			nosotros: "acuñaríamos",
			vosotros: "acuñaríais",
			Uds: "acuñarían",
		},
		Future: {
			yo: "acuñaré",
			tú: "acuñarás",
			Ud: "acuñará",
			nosotros: "acuñaremos",
			vosotros: "acuñaréis",
			Uds: "acuñarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "acuñe",
			tú: "acuñes",
			Ud: "acuñe",
			nosotros: "acuñemos",
			vosotros: "acuñéis",
			Uds: "acuñen",
		},
		Imperfect: {
			yo: "acuñara",
			tú: "acuñaras",
			Ud: "acuñara",
			nosotros: "acuñáramos",
			vosotros: "acuñarais",
			Uds: "acuñaran",
		},
		Imperfect2: {
			yo: "acuñase",
			tú: "acuñases",
			Ud: "acuñase",
			nosotros: "acuñásemos",
			vosotros: "acuñaseis",
			Uds: "acuñasen",
		},
		Future: {
			yo: "acuñare",
			tú: "acuñares",
			Ud: "acuñare",
			nosotros: "acuñáremos",
			vosotros: "acuñareis",
			Uds: "acuñaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "acuña",
			Ud: "acuñe",
			nosotros: "acuñemos",
			vosotros: "acuñad",
			Uds: "acuñen",
		},
		Negative: {
			tú: "no acuñes",
			Ud: "no acuñe",
			nosotros: "no acuñemos",
			vosotros: "no acuñéis",
			Uds: "no acuñen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy acuñando",
			tú: "estás acuñando",
			Ud: "está acuñando",
			nosotros: "estamos acuñando",
			vosotros: "estáis acuñando",
			Uds: "están acuñando",
		},
		Preterite: {
			yo: "estuve acuñando",
			tú: "estuviste acuñando",
			Ud: "estuvo acuñando",
			nosotros: "estuvimos acuñando",
			vosotros: "estuvisteis acuñando",
			Uds: "estuvieron acuñando",
		},
		Imperfect: {
			Uds: "estaban acuñando",
			yo: "estaba acuñando",
			tú: "estabas acuñando",
			Ud: "estaba acuñando",
			nosotros: "estábamos acuñando",
			vosotros: "estabais acuñando",
		},
		Conditional: {
			yo: "estaría acuñando",
			tú: "estarías acuñando",
			Ud: "estaría acuñando",
			nosotros: "estaríamos acuñando",
			vosotros: "estaríais acuñando",
			Uds: "estarían acuñando",
		},
		Future: {
			yo: "estaré acuñando",
			tú: "estarás acuñando",
			Ud: "estará acuñando",
			nosotros: "estaremos acuñando",
			vosotros: "estaréis acuñando",
			Uds: "estarán acuñando",
		},
	},
	Perfect: {
		Present: {
			yo: "he acuñado",
			tú: "has acuñado",
			Ud: "ha acuñado",
			nosotros: "hemos acuñado",
			vosotros: "habéis acuñado",
			Uds: "han acuñado",
		},
		Preterite: {
			yo: "hube acuñado",
			tú: "hubiste acuñado",
			Ud: "hubo acuñado",
			nosotros: "hubimos acuñado",
			vosotros: "hubisteis acuñado",
			Uds: "hubieron acuñado",
		},
		Past: {
			yo: "había acuñado",
			tú: "habías acuñado",
			Ud: "había acuñado",
			nosotros: "habíamos acuñado",
			vosotros: "habíais acuñado",
			Uds: "habían acuñado",
		},
		Conditional: {
			yo: "habría acuñado",
			tú: "habrías acuñado",
			Ud: "habría acuñado",
			nosotros: "habríamos acuñado",
			vosotros: "habríais acuñado",
			Uds: "habrían acuñado",
		},
		Future: {
			yo: "habré acuñado",
			tú: "habrás acuñado",
			Ud: "habrá acuñado",
			nosotros: "habremos acuñado",
			vosotros: "habréis acuñado",
			Uds: "habrán acuñado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya acuñado",
			tú: "hayas acuñado",
			Ud: "haya acuñado",
			nosotros: "hayamos acuñado",
			vosotros: "hayáis acuñado",
			Uds: "hayan acuñado",
		},
		Past: {
			yo: "hubiera acuñado",
			tú: "hubieras acuñado",
			Ud: "hubiera acuñado",
			nosotros: "hubiéramos acuñado",
			vosotros: "hubierais acuñado",
			Uds: "hubieran acuñado",
		},
		Future: {
			yo: "hubiere acuñado",
			tú: "hubieres acuñado",
			Ud: "hubiere acuñado",
			nosotros: "hubiéremos acuñado",
			vosotros: "hubiereis acuñado",
			Uds: "hubieren acuñado",
		},
	},
}
