var adjuntar = {
	Indicative: {
		Present: {
			yo: "adjunto",
			tú: "adjuntas",
			Ud: "adjunta",
			nosotros: "adjuntamos",
			vosotros: "adjuntáis",
			Uds: "adjuntan",
		},
		Preterite: {
			yo: "adjunté",
			tú: "adjuntaste",
			Ud: "adjuntó",
			nosotros: "adjuntamos",
			vosotros: "adjuntasteis",
			Uds: "adjuntaron",
		},
		Imperfect: {
			yo: "adjuntaba",
			tú: "adjuntabas",
			Ud: "adjuntaba",
			nosotros: "adjuntábamos",
			vosotros: "adjuntabais",
			Uds: "adjuntaban",
		},
		Conditional: {
			yo: "adjuntaría",
			tú: "adjuntarías",
			Ud: "adjuntaría",
			nosotros: "adjuntaríamos",
			vosotros: "adjuntaríais",
			Uds: "adjuntarían",
		},
		Future: {
			yo: "adjuntaré",
			tú: "adjuntarás",
			Ud: "adjuntará",
			nosotros: "adjuntaremos",
			vosotros: "adjuntaréis",
			Uds: "adjuntarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "adjunte",
			tú: "adjuntes",
			Ud: "adjunte",
			nosotros: "adjuntemos",
			vosotros: "adjuntéis",
			Uds: "adjunten",
		},
		Imperfect: {
			yo: "adjuntara",
			tú: "adjuntaras",
			Ud: "adjuntara",
			nosotros: "adjuntáramos",
			vosotros: "adjuntarais",
			Uds: "adjuntaran",
		},
		Imperfect2: {
			yo: "adjuntase",
			tú: "adjuntases",
			Ud: "adjuntase",
			nosotros: "adjuntásemos",
			vosotros: "adjuntaseis",
			Uds: "adjuntasen",
		},
		Future: {
			yo: "adjuntare",
			tú: "adjuntares",
			Ud: "adjuntare",
			nosotros: "adjuntáremos",
			vosotros: "adjuntareis",
			Uds: "adjuntaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "adjunta",
			Ud: "adjunte",
			nosotros: "adjuntemos",
			vosotros: "adjuntad",
			Uds: "adjunten",
		},
		Negative: {
			tú: "no adjuntes",
			Ud: "no adjunte",
			nosotros: "no adjuntemos",
			vosotros: "no adjuntéis",
			Uds: "no adjunten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy adjuntando",
			tú: "estás adjuntando",
			Ud: "está adjuntando",
			nosotros: "estamos adjuntando",
			vosotros: "estáis adjuntando",
			Uds: "están adjuntando",
		},
		Preterite: {
			yo: "estuve adjuntando",
			tú: "estuviste adjuntando",
			Ud: "estuvo adjuntando",
			nosotros: "estuvimos adjuntando",
			vosotros: "estuvisteis adjuntando",
			Uds: "estuvieron adjuntando",
		},
		Imperfect: {
			Uds: "estaban adjuntando",
			yo: "estaba adjuntando",
			tú: "estabas adjuntando",
			Ud: "estaba adjuntando",
			nosotros: "estábamos adjuntando",
			vosotros: "estabais adjuntando",
		},
		Conditional: {
			yo: "estaría adjuntando",
			tú: "estarías adjuntando",
			Ud: "estaría adjuntando",
			nosotros: "estaríamos adjuntando",
			vosotros: "estaríais adjuntando",
			Uds: "estarían adjuntando",
		},
		Future: {
			yo: "estaré adjuntando",
			tú: "estarás adjuntando",
			Ud: "estará adjuntando",
			nosotros: "estaremos adjuntando",
			vosotros: "estaréis adjuntando",
			Uds: "estarán adjuntando",
		},
	},
	Perfect: {
		Present: {
			yo: "he adjuntado",
			tú: "has adjuntado",
			Ud: "ha adjuntado",
			nosotros: "hemos adjuntado",
			vosotros: "habéis adjuntado",
			Uds: "han adjuntado",
		},
		Preterite: {
			yo: "hube adjuntado",
			tú: "hubiste adjuntado",
			Ud: "hubo adjuntado",
			nosotros: "hubimos adjuntado",
			vosotros: "hubisteis adjuntado",
			Uds: "hubieron adjuntado",
		},
		Past: {
			yo: "había adjuntado",
			tú: "habías adjuntado",
			Ud: "había adjuntado",
			nosotros: "habíamos adjuntado",
			vosotros: "habíais adjuntado",
			Uds: "habían adjuntado",
		},
		Conditional: {
			yo: "habría adjuntado",
			tú: "habrías adjuntado",
			Ud: "habría adjuntado",
			nosotros: "habríamos adjuntado",
			vosotros: "habríais adjuntado",
			Uds: "habrían adjuntado",
		},
		Future: {
			yo: "habré adjuntado",
			tú: "habrás adjuntado",
			Ud: "habrá adjuntado",
			nosotros: "habremos adjuntado",
			vosotros: "habréis adjuntado",
			Uds: "habrán adjuntado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya adjuntado",
			tú: "hayas adjuntado",
			Ud: "haya adjuntado",
			nosotros: "hayamos adjuntado",
			vosotros: "hayáis adjuntado",
			Uds: "hayan adjuntado",
		},
		Past: {
			yo: "hubiera adjuntado",
			tú: "hubieras adjuntado",
			Ud: "hubiera adjuntado",
			nosotros: "hubiéramos adjuntado",
			vosotros: "hubierais adjuntado",
			Uds: "hubieran adjuntado",
		},
		Future: {
			yo: "hubiere adjuntado",
			tú: "hubieres adjuntado",
			Ud: "hubiere adjuntado",
			nosotros: "hubiéremos adjuntado",
			vosotros: "hubiereis adjuntado",
			Uds: "hubieren adjuntado",
		},
	},
}
