var admitir = {
	Indicative: {
		Present: {
			yo: "admito",
			tú: "admites",
			Ud: "admite",
			nosotros: "admitimos",
			vosotros: "admitís",
			Uds: "admiten",
		},
		Preterite: {
			yo: "admití",
			tú: "admitiste",
			Ud: "admitió",
			nosotros: "admitimos",
			vosotros: "admitisteis",
			Uds: "admitieron",
		},
		Imperfect: {
			yo: "admitía",
			tú: "admitías",
			Ud: "admitía",
			nosotros: "admitíamos",
			vosotros: "admitíais",
			Uds: "admitían",
		},
		Conditional: {
			yo: "admitiría",
			tú: "admitirías",
			Ud: "admitiría",
			nosotros: "admitiríamos",
			vosotros: "admitiríais",
			Uds: "admitirían",
		},
		Future: {
			yo: "admitiré",
			tú: "admitirás",
			Ud: "admitirá",
			nosotros: "admitiremos",
			vosotros: "admitiréis",
			Uds: "admitirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "admita",
			tú: "admitas",
			Ud: "admita",
			nosotros: "admitamos",
			vosotros: "admitáis",
			Uds: "admitan",
		},
		Imperfect: {
			yo: "admitiera",
			tú: "admitieras",
			Ud: "admitiera",
			nosotros: "admitiéramos",
			vosotros: "admitierais",
			Uds: "admitieran",
		},
		Imperfect2: {
			yo: "admitiese",
			tú: "admitieses",
			Ud: "admitiese",
			nosotros: "admitiésemos",
			vosotros: "admitieseis",
			Uds: "admitiesen",
		},
		Future: {
			yo: "admitiere",
			tú: "admitieres",
			Ud: "admitiere",
			nosotros: "admitiéremos",
			vosotros: "admitiereis",
			Uds: "admitieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "admite",
			Ud: "admita",
			nosotros: "admitamos",
			vosotros: "admitid",
			Uds: "admitan",
		},
		Negative: {
			tú: "no admitas",
			Ud: "no admita",
			nosotros: "no admitamos",
			vosotros: "no admitáis",
			Uds: "no admitan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy admitiendo",
			tú: "estás admitiendo",
			Ud: "está admitiendo",
			nosotros: "estamos admitiendo",
			vosotros: "estáis admitiendo",
			Uds: "están admitiendo",
		},
		Preterite: {
			yo: "estuve admitiendo",
			tú: "estuviste admitiendo",
			Ud: "estuvo admitiendo",
			nosotros: "estuvimos admitiendo",
			vosotros: "estuvisteis admitiendo",
			Uds: "estuvieron admitiendo",
		},
		Imperfect: {
			Uds: "estaban admitiendo",
			yo: "estaba admitiendo",
			tú: "estabas admitiendo",
			Ud: "estaba admitiendo",
			nosotros: "estábamos admitiendo",
			vosotros: "estabais admitiendo",
		},
		Conditional: {
			yo: "estaría admitiendo",
			tú: "estarías admitiendo",
			Ud: "estaría admitiendo",
			nosotros: "estaríamos admitiendo",
			vosotros: "estaríais admitiendo",
			Uds: "estarían admitiendo",
		},
		Future: {
			yo: "estaré admitiendo",
			tú: "estarás admitiendo",
			Ud: "estará admitiendo",
			nosotros: "estaremos admitiendo",
			vosotros: "estaréis admitiendo",
			Uds: "estarán admitiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he admitido",
			tú: "has admitido",
			Ud: "ha admitido",
			nosotros: "hemos admitido",
			vosotros: "habéis admitido",
			Uds: "han admitido",
		},
		Preterite: {
			yo: "hube admitido",
			tú: "hubiste admitido",
			Ud: "hubo admitido",
			nosotros: "hubimos admitido",
			vosotros: "hubisteis admitido",
			Uds: "hubieron admitido",
		},
		Past: {
			yo: "había admitido",
			tú: "habías admitido",
			Ud: "había admitido",
			nosotros: "habíamos admitido",
			vosotros: "habíais admitido",
			Uds: "habían admitido",
		},
		Conditional: {
			yo: "habría admitido",
			tú: "habrías admitido",
			Ud: "habría admitido",
			nosotros: "habríamos admitido",
			vosotros: "habríais admitido",
			Uds: "habrían admitido",
		},
		Future: {
			yo: "habré admitido",
			tú: "habrás admitido",
			Ud: "habrá admitido",
			nosotros: "habremos admitido",
			vosotros: "habréis admitido",
			Uds: "habrán admitido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya admitido",
			tú: "hayas admitido",
			Ud: "haya admitido",
			nosotros: "hayamos admitido",
			vosotros: "hayáis admitido",
			Uds: "hayan admitido",
		},
		Past: {
			yo: "hubiera admitido",
			tú: "hubieras admitido",
			Ud: "hubiera admitido",
			nosotros: "hubiéramos admitido",
			vosotros: "hubierais admitido",
			Uds: "hubieran admitido",
		},
		Future: {
			yo: "hubiere admitido",
			tú: "hubieres admitido",
			Ud: "hubiere admitido",
			nosotros: "hubiéremos admitido",
			vosotros: "hubiereis admitido",
			Uds: "hubieren admitido",
		},
	},
}
