var adoptar = {
	Indicative: {
		Present: {
			yo: "adopto",
			tú: "adoptas",
			Ud: "adopta",
			nosotros: "adoptamos",
			vosotros: "adoptáis",
			Uds: "adoptan",
		},
		Preterite: {
			yo: "adopté",
			tú: "adoptaste",
			Ud: "adoptó",
			nosotros: "adoptamos",
			vosotros: "adoptasteis",
			Uds: "adoptaron",
		},
		Imperfect: {
			yo: "adoptaba",
			tú: "adoptabas",
			Ud: "adoptaba",
			nosotros: "adoptábamos",
			vosotros: "adoptabais",
			Uds: "adoptaban",
		},
		Conditional: {
			yo: "adoptaría",
			tú: "adoptarías",
			Ud: "adoptaría",
			nosotros: "adoptaríamos",
			vosotros: "adoptaríais",
			Uds: "adoptarían",
		},
		Future: {
			yo: "adoptaré",
			tú: "adoptarás",
			Ud: "adoptará",
			nosotros: "adoptaremos",
			vosotros: "adoptaréis",
			Uds: "adoptarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "adopte",
			tú: "adoptes",
			Ud: "adopte",
			nosotros: "adoptemos",
			vosotros: "adoptéis",
			Uds: "adopten",
		},
		Imperfect: {
			yo: "adoptara",
			tú: "adoptaras",
			Ud: "adoptara",
			nosotros: "adoptáramos",
			vosotros: "adoptarais",
			Uds: "adoptaran",
		},
		Imperfect2: {
			yo: "adoptase",
			tú: "adoptases",
			Ud: "adoptase",
			nosotros: "adoptásemos",
			vosotros: "adoptaseis",
			Uds: "adoptasen",
		},
		Future: {
			yo: "adoptare",
			tú: "adoptares",
			Ud: "adoptare",
			nosotros: "adoptáremos",
			vosotros: "adoptareis",
			Uds: "adoptaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "adopta",
			Ud: "adopte",
			nosotros: "adoptemos",
			vosotros: "adoptad",
			Uds: "adopten",
		},
		Negative: {
			tú: "no adoptes",
			Ud: "no adopte",
			nosotros: "no adoptemos",
			vosotros: "no adoptéis",
			Uds: "no adopten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy adoptando",
			tú: "estás adoptando",
			Ud: "está adoptando",
			nosotros: "estamos adoptando",
			vosotros: "estáis adoptando",
			Uds: "están adoptando",
		},
		Preterite: {
			yo: "estuve adoptando",
			tú: "estuviste adoptando",
			Ud: "estuvo adoptando",
			nosotros: "estuvimos adoptando",
			vosotros: "estuvisteis adoptando",
			Uds: "estuvieron adoptando",
		},
		Imperfect: {
			Uds: "estaban adoptando",
			yo: "estaba adoptando",
			tú: "estabas adoptando",
			Ud: "estaba adoptando",
			nosotros: "estábamos adoptando",
			vosotros: "estabais adoptando",
		},
		Conditional: {
			yo: "estaría adoptando",
			tú: "estarías adoptando",
			Ud: "estaría adoptando",
			nosotros: "estaríamos adoptando",
			vosotros: "estaríais adoptando",
			Uds: "estarían adoptando",
		},
		Future: {
			yo: "estaré adoptando",
			tú: "estarás adoptando",
			Ud: "estará adoptando",
			nosotros: "estaremos adoptando",
			vosotros: "estaréis adoptando",
			Uds: "estarán adoptando",
		},
	},
	Perfect: {
		Present: {
			yo: "he adoptado",
			tú: "has adoptado",
			Ud: "ha adoptado",
			nosotros: "hemos adoptado",
			vosotros: "habéis adoptado",
			Uds: "han adoptado",
		},
		Preterite: {
			yo: "hube adoptado",
			tú: "hubiste adoptado",
			Ud: "hubo adoptado",
			nosotros: "hubimos adoptado",
			vosotros: "hubisteis adoptado",
			Uds: "hubieron adoptado",
		},
		Past: {
			yo: "había adoptado",
			tú: "habías adoptado",
			Ud: "había adoptado",
			nosotros: "habíamos adoptado",
			vosotros: "habíais adoptado",
			Uds: "habían adoptado",
		},
		Conditional: {
			yo: "habría adoptado",
			tú: "habrías adoptado",
			Ud: "habría adoptado",
			nosotros: "habríamos adoptado",
			vosotros: "habríais adoptado",
			Uds: "habrían adoptado",
		},
		Future: {
			yo: "habré adoptado",
			tú: "habrás adoptado",
			Ud: "habrá adoptado",
			nosotros: "habremos adoptado",
			vosotros: "habréis adoptado",
			Uds: "habrán adoptado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya adoptado",
			tú: "hayas adoptado",
			Ud: "haya adoptado",
			nosotros: "hayamos adoptado",
			vosotros: "hayáis adoptado",
			Uds: "hayan adoptado",
		},
		Past: {
			yo: "hubiera adoptado",
			tú: "hubieras adoptado",
			Ud: "hubiera adoptado",
			nosotros: "hubiéramos adoptado",
			vosotros: "hubierais adoptado",
			Uds: "hubieran adoptado",
		},
		Future: {
			yo: "hubiere adoptado",
			tú: "hubieres adoptado",
			Ud: "hubiere adoptado",
			nosotros: "hubiéremos adoptado",
			vosotros: "hubiereis adoptado",
			Uds: "hubieren adoptado",
		},
	},
}
