var adornar = {
	Indicative: {
		Present: {
			yo: "adorno",
			tú: "adornas",
			Ud: "adorna",
			nosotros: "adornamos",
			vosotros: "adornáis",
			Uds: "adornan",
		},
		Preterite: {
			yo: "adorné",
			tú: "adornaste",
			Ud: "adornó",
			nosotros: "adornamos",
			vosotros: "adornasteis",
			Uds: "adornaron",
		},
		Imperfect: {
			yo: "adornaba",
			tú: "adornabas",
			Ud: "adornaba",
			nosotros: "adornábamos",
			vosotros: "adornabais",
			Uds: "adornaban",
		},
		Conditional: {
			yo: "adornaría",
			tú: "adornarías",
			Ud: "adornaría",
			nosotros: "adornaríamos",
			vosotros: "adornaríais",
			Uds: "adornarían",
		},
		Future: {
			yo: "adornaré",
			tú: "adornarás",
			Ud: "adornará",
			nosotros: "adornaremos",
			vosotros: "adornaréis",
			Uds: "adornarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "adorne",
			tú: "adornes",
			Ud: "adorne",
			nosotros: "adornemos",
			vosotros: "adornéis",
			Uds: "adornen",
		},
		Imperfect: {
			yo: "adornara",
			tú: "adornaras",
			Ud: "adornara",
			nosotros: "adornáramos",
			vosotros: "adornarais",
			Uds: "adornaran",
		},
		Imperfect2: {
			yo: "adornase",
			tú: "adornases",
			Ud: "adornase",
			nosotros: "adornásemos",
			vosotros: "adornaseis",
			Uds: "adornasen",
		},
		Future: {
			yo: "adornare",
			tú: "adornares",
			Ud: "adornare",
			nosotros: "adornáremos",
			vosotros: "adornareis",
			Uds: "adornaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "adorna",
			Ud: "adorne",
			nosotros: "adornemos",
			vosotros: "adornad",
			Uds: "adornen",
		},
		Negative: {
			tú: "no adornes",
			Ud: "no adorne",
			nosotros: "no adornemos",
			vosotros: "no adornéis",
			Uds: "no adornen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy adornando",
			tú: "estás adornando",
			Ud: "está adornando",
			nosotros: "estamos adornando",
			vosotros: "estáis adornando",
			Uds: "están adornando",
		},
		Preterite: {
			yo: "estuve adornando",
			tú: "estuviste adornando",
			Ud: "estuvo adornando",
			nosotros: "estuvimos adornando",
			vosotros: "estuvisteis adornando",
			Uds: "estuvieron adornando",
		},
		Imperfect: {
			Uds: "estaban adornando",
			yo: "estaba adornando",
			tú: "estabas adornando",
			Ud: "estaba adornando",
			nosotros: "estábamos adornando",
			vosotros: "estabais adornando",
		},
		Conditional: {
			yo: "estaría adornando",
			tú: "estarías adornando",
			Ud: "estaría adornando",
			nosotros: "estaríamos adornando",
			vosotros: "estaríais adornando",
			Uds: "estarían adornando",
		},
		Future: {
			yo: "estaré adornando",
			tú: "estarás adornando",
			Ud: "estará adornando",
			nosotros: "estaremos adornando",
			vosotros: "estaréis adornando",
			Uds: "estarán adornando",
		},
	},
	Perfect: {
		Present: {
			yo: "he adornado",
			tú: "has adornado",
			Ud: "ha adornado",
			nosotros: "hemos adornado",
			vosotros: "habéis adornado",
			Uds: "han adornado",
		},
		Preterite: {
			yo: "hube adornado",
			tú: "hubiste adornado",
			Ud: "hubo adornado",
			nosotros: "hubimos adornado",
			vosotros: "hubisteis adornado",
			Uds: "hubieron adornado",
		},
		Past: {
			yo: "había adornado",
			tú: "habías adornado",
			Ud: "había adornado",
			nosotros: "habíamos adornado",
			vosotros: "habíais adornado",
			Uds: "habían adornado",
		},
		Conditional: {
			yo: "habría adornado",
			tú: "habrías adornado",
			Ud: "habría adornado",
			nosotros: "habríamos adornado",
			vosotros: "habríais adornado",
			Uds: "habrían adornado",
		},
		Future: {
			yo: "habré adornado",
			tú: "habrás adornado",
			Ud: "habrá adornado",
			nosotros: "habremos adornado",
			vosotros: "habréis adornado",
			Uds: "habrán adornado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya adornado",
			tú: "hayas adornado",
			Ud: "haya adornado",
			nosotros: "hayamos adornado",
			vosotros: "hayáis adornado",
			Uds: "hayan adornado",
		},
		Past: {
			yo: "hubiera adornado",
			tú: "hubieras adornado",
			Ud: "hubiera adornado",
			nosotros: "hubiéramos adornado",
			vosotros: "hubierais adornado",
			Uds: "hubieran adornado",
		},
		Future: {
			yo: "hubiere adornado",
			tú: "hubieres adornado",
			Ud: "hubiere adornado",
			nosotros: "hubiéremos adornado",
			vosotros: "hubiereis adornado",
			Uds: "hubieren adornado",
		},
	},
}
