var afectar = {
	Indicative: {
		Present: {
			yo: "afecto",
			tú: "afectas",
			Ud: "afecta",
			nosotros: "afectamos",
			vosotros: "afectáis",
			Uds: "afectan",
		},
		Preterite: {
			yo: "afecté",
			tú: "afectaste",
			Ud: "afectó",
			nosotros: "afectamos",
			vosotros: "afectasteis",
			Uds: "afectaron",
		},
		Imperfect: {
			yo: "afectaba",
			tú: "afectabas",
			Ud: "afectaba",
			nosotros: "afectábamos",
			vosotros: "afectabais",
			Uds: "afectaban",
		},
		Conditional: {
			yo: "afectaría",
			tú: "afectarías",
			Ud: "afectaría",
			nosotros: "afectaríamos",
			vosotros: "afectaríais",
			Uds: "afectarían",
		},
		Future: {
			yo: "afectaré",
			tú: "afectarás",
			Ud: "afectará",
			nosotros: "afectaremos",
			vosotros: "afectaréis",
			Uds: "afectarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "afecte",
			tú: "afectes",
			Ud: "afecte",
			nosotros: "afectemos",
			vosotros: "afectéis",
			Uds: "afecten",
		},
		Imperfect: {
			yo: "afectara",
			tú: "afectaras",
			Ud: "afectara",
			nosotros: "afectáramos",
			vosotros: "afectarais",
			Uds: "afectaran",
		},
		Imperfect2: {
			yo: "afectase",
			tú: "afectases",
			Ud: "afectase",
			nosotros: "afectásemos",
			vosotros: "afectaseis",
			Uds: "afectasen",
		},
		Future: {
			yo: "afectare",
			tú: "afectares",
			Ud: "afectare",
			nosotros: "afectáremos",
			vosotros: "afectareis",
			Uds: "afectaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "afecta",
			Ud: "afecte",
			nosotros: "afectemos",
			vosotros: "afectad",
			Uds: "afecten",
		},
		Negative: {
			tú: "no afectes",
			Ud: "no afecte",
			nosotros: "no afectemos",
			vosotros: "no afectéis",
			Uds: "no afecten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy afectando",
			tú: "estás afectando",
			Ud: "está afectando",
			nosotros: "estamos afectando",
			vosotros: "estáis afectando",
			Uds: "están afectando",
		},
		Preterite: {
			yo: "estuve afectando",
			tú: "estuviste afectando",
			Ud: "estuvo afectando",
			nosotros: "estuvimos afectando",
			vosotros: "estuvisteis afectando",
			Uds: "estuvieron afectando",
		},
		Imperfect: {
			Uds: "estaban afectando",
			yo: "estaba afectando",
			tú: "estabas afectando",
			Ud: "estaba afectando",
			nosotros: "estábamos afectando",
			vosotros: "estabais afectando",
		},
		Conditional: {
			yo: "estaría afectando",
			tú: "estarías afectando",
			Ud: "estaría afectando",
			nosotros: "estaríamos afectando",
			vosotros: "estaríais afectando",
			Uds: "estarían afectando",
		},
		Future: {
			yo: "estaré afectando",
			tú: "estarás afectando",
			Ud: "estará afectando",
			nosotros: "estaremos afectando",
			vosotros: "estaréis afectando",
			Uds: "estarán afectando",
		},
	},
	Perfect: {
		Present: {
			yo: "he afectado",
			tú: "has afectado",
			Ud: "ha afectado",
			nosotros: "hemos afectado",
			vosotros: "habéis afectado",
			Uds: "han afectado",
		},
		Preterite: {
			yo: "hube afectado",
			tú: "hubiste afectado",
			Ud: "hubo afectado",
			nosotros: "hubimos afectado",
			vosotros: "hubisteis afectado",
			Uds: "hubieron afectado",
		},
		Past: {
			yo: "había afectado",
			tú: "habías afectado",
			Ud: "había afectado",
			nosotros: "habíamos afectado",
			vosotros: "habíais afectado",
			Uds: "habían afectado",
		},
		Conditional: {
			yo: "habría afectado",
			tú: "habrías afectado",
			Ud: "habría afectado",
			nosotros: "habríamos afectado",
			vosotros: "habríais afectado",
			Uds: "habrían afectado",
		},
		Future: {
			yo: "habré afectado",
			tú: "habrás afectado",
			Ud: "habrá afectado",
			nosotros: "habremos afectado",
			vosotros: "habréis afectado",
			Uds: "habrán afectado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya afectado",
			tú: "hayas afectado",
			Ud: "haya afectado",
			nosotros: "hayamos afectado",
			vosotros: "hayáis afectado",
			Uds: "hayan afectado",
		},
		Past: {
			yo: "hubiera afectado",
			tú: "hubieras afectado",
			Ud: "hubiera afectado",
			nosotros: "hubiéramos afectado",
			vosotros: "hubierais afectado",
			Uds: "hubieran afectado",
		},
		Future: {
			yo: "hubiere afectado",
			tú: "hubieres afectado",
			Ud: "hubiere afectado",
			nosotros: "hubiéremos afectado",
			vosotros: "hubiereis afectado",
			Uds: "hubieren afectado",
		},
	},
}
