var afilar = {
	Indicative: {
		Present: {
			yo: "afilo",
			tú: "afilas",
			Ud: "afila",
			nosotros: "afilamos",
			vosotros: "afiláis",
			Uds: "afilan",
		},
		Preterite: {
			yo: "afilé",
			tú: "afilaste",
			Ud: "afiló",
			nosotros: "afilamos",
			vosotros: "afilasteis",
			Uds: "afilaron",
		},
		Imperfect: {
			yo: "afilaba",
			tú: "afilabas",
			Ud: "afilaba",
			nosotros: "afilábamos",
			vosotros: "afilabais",
			Uds: "afilaban",
		},
		Conditional: {
			yo: "afilaría",
			tú: "afilarías",
			Ud: "afilaría",
			nosotros: "afilaríamos",
			vosotros: "afilaríais",
			Uds: "afilarían",
		},
		Future: {
			yo: "afilaré",
			tú: "afilarás",
			Ud: "afilará",
			nosotros: "afilaremos",
			vosotros: "afilaréis",
			Uds: "afilarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "afile",
			tú: "afiles",
			Ud: "afile",
			nosotros: "afilemos",
			vosotros: "afiléis",
			Uds: "afilen",
		},
		Imperfect: {
			yo: "afilara",
			tú: "afilaras",
			Ud: "afilara",
			nosotros: "afiláramos",
			vosotros: "afilarais",
			Uds: "afilaran",
		},
		Imperfect2: {
			yo: "afilase",
			tú: "afilases",
			Ud: "afilase",
			nosotros: "afilásemos",
			vosotros: "afilaseis",
			Uds: "afilasen",
		},
		Future: {
			yo: "afilare",
			tú: "afilares",
			Ud: "afilare",
			nosotros: "afiláremos",
			vosotros: "afilareis",
			Uds: "afilaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "afila",
			Ud: "afile",
			nosotros: "afilemos",
			vosotros: "afilad",
			Uds: "afilen",
		},
		Negative: {
			tú: "no afiles",
			Ud: "no afile",
			nosotros: "no afilemos",
			vosotros: "no afiléis",
			Uds: "no afilen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy afilando",
			tú: "estás afilando",
			Ud: "está afilando",
			nosotros: "estamos afilando",
			vosotros: "estáis afilando",
			Uds: "están afilando",
		},
		Preterite: {
			yo: "estuve afilando",
			tú: "estuviste afilando",
			Ud: "estuvo afilando",
			nosotros: "estuvimos afilando",
			vosotros: "estuvisteis afilando",
			Uds: "estuvieron afilando",
		},
		Imperfect: {
			Uds: "estaban afilando",
			yo: "estaba afilando",
			tú: "estabas afilando",
			Ud: "estaba afilando",
			nosotros: "estábamos afilando",
			vosotros: "estabais afilando",
		},
		Conditional: {
			yo: "estaría afilando",
			tú: "estarías afilando",
			Ud: "estaría afilando",
			nosotros: "estaríamos afilando",
			vosotros: "estaríais afilando",
			Uds: "estarían afilando",
		},
		Future: {
			yo: "estaré afilando",
			tú: "estarás afilando",
			Ud: "estará afilando",
			nosotros: "estaremos afilando",
			vosotros: "estaréis afilando",
			Uds: "estarán afilando",
		},
	},
	Perfect: {
		Present: {
			yo: "he afilado",
			tú: "has afilado",
			Ud: "ha afilado",
			nosotros: "hemos afilado",
			vosotros: "habéis afilado",
			Uds: "han afilado",
		},
		Preterite: {
			yo: "hube afilado",
			tú: "hubiste afilado",
			Ud: "hubo afilado",
			nosotros: "hubimos afilado",
			vosotros: "hubisteis afilado",
			Uds: "hubieron afilado",
		},
		Past: {
			yo: "había afilado",
			tú: "habías afilado",
			Ud: "había afilado",
			nosotros: "habíamos afilado",
			vosotros: "habíais afilado",
			Uds: "habían afilado",
		},
		Conditional: {
			yo: "habría afilado",
			tú: "habrías afilado",
			Ud: "habría afilado",
			nosotros: "habríamos afilado",
			vosotros: "habríais afilado",
			Uds: "habrían afilado",
		},
		Future: {
			yo: "habré afilado",
			tú: "habrás afilado",
			Ud: "habrá afilado",
			nosotros: "habremos afilado",
			vosotros: "habréis afilado",
			Uds: "habrán afilado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya afilado",
			tú: "hayas afilado",
			Ud: "haya afilado",
			nosotros: "hayamos afilado",
			vosotros: "hayáis afilado",
			Uds: "hayan afilado",
		},
		Past: {
			yo: "hubiera afilado",
			tú: "hubieras afilado",
			Ud: "hubiera afilado",
			nosotros: "hubiéramos afilado",
			vosotros: "hubierais afilado",
			Uds: "hubieran afilado",
		},
		Future: {
			yo: "hubiere afilado",
			tú: "hubieres afilado",
			Ud: "hubiere afilado",
			nosotros: "hubiéremos afilado",
			vosotros: "hubiereis afilado",
			Uds: "hubieren afilado",
		},
	},
}
