var afligir = {
	Indicative: {
		Present: {
			yo: "aflijo",
			tú: "afliges",
			Ud: "aflige",
			nosotros: "afligimos",
			vosotros: "afligís",
			Uds: "afligen",
		},
		Preterite: {
			yo: "afligí",
			tú: "afligiste",
			Ud: "afligió",
			nosotros: "afligimos",
			vosotros: "afligisteis",
			Uds: "afligieron",
		},
		Imperfect: {
			yo: "afligía",
			tú: "afligías",
			Ud: "afligía",
			nosotros: "afligíamos",
			vosotros: "afligíais",
			Uds: "afligían",
		},
		Conditional: {
			yo: "afligiría",
			tú: "afligirías",
			Ud: "afligiría",
			nosotros: "afligiríamos",
			vosotros: "afligiríais",
			Uds: "afligirían",
		},
		Future: {
			yo: "afligiré",
			tú: "afligirás",
			Ud: "afligirá",
			nosotros: "afligiremos",
			vosotros: "afligiréis",
			Uds: "afligirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "aflija",
			tú: "aflijas",
			Ud: "aflija",
			nosotros: "aflijamos",
			vosotros: "aflijáis",
			Uds: "aflijan",
		},
		Imperfect: {
			yo: "afligiera",
			tú: "afligieras",
			Ud: "afligiera",
			nosotros: "afligiéramos",
			vosotros: "afligierais",
			Uds: "afligieran",
		},
		Imperfect2: {
			yo: "afligiese",
			tú: "afligieses",
			Ud: "afligiese",
			nosotros: "afligiésemos",
			vosotros: "afligieseis",
			Uds: "afligiesen",
		},
		Future: {
			yo: "afligiere",
			tú: "afligieres",
			Ud: "afligiere",
			nosotros: "afligiéremos",
			vosotros: "afligiereis",
			Uds: "afligieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "aflige",
			Ud: "aflija",
			nosotros: "aflijamos",
			vosotros: "afligid",
			Uds: "aflijan",
		},
		Negative: {
			tú: "no aflijas",
			Ud: "no aflija",
			nosotros: "no aflijamos",
			vosotros: "no aflijáis",
			Uds: "no aflijan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy afligiendo",
			tú: "estás afligiendo",
			Ud: "está afligiendo",
			nosotros: "estamos afligiendo",
			vosotros: "estáis afligiendo",
			Uds: "están afligiendo",
		},
		Preterite: {
			yo: "estuve afligiendo",
			tú: "estuviste afligiendo",
			Ud: "estuvo afligiendo",
			nosotros: "estuvimos afligiendo",
			vosotros: "estuvisteis afligiendo",
			Uds: "estuvieron afligiendo",
		},
		Imperfect: {
			Uds: "estaban afligiendo",
			yo: "estaba afligiendo",
			tú: "estabas afligiendo",
			Ud: "estaba afligiendo",
			nosotros: "estábamos afligiendo",
			vosotros: "estabais afligiendo",
		},
		Conditional: {
			yo: "estaría afligiendo",
			tú: "estarías afligiendo",
			Ud: "estaría afligiendo",
			nosotros: "estaríamos afligiendo",
			vosotros: "estaríais afligiendo",
			Uds: "estarían afligiendo",
		},
		Future: {
			yo: "estaré afligiendo",
			tú: "estarás afligiendo",
			Ud: "estará afligiendo",
			nosotros: "estaremos afligiendo",
			vosotros: "estaréis afligiendo",
			Uds: "estarán afligiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he afligido",
			tú: "has afligido",
			Ud: "ha afligido",
			nosotros: "hemos afligido",
			vosotros: "habéis afligido",
			Uds: "han afligido",
		},
		Preterite: {
			yo: "hube afligido",
			tú: "hubiste afligido",
			Ud: "hubo afligido",
			nosotros: "hubimos afligido",
			vosotros: "hubisteis afligido",
			Uds: "hubieron afligido",
		},
		Past: {
			yo: "había afligido",
			tú: "habías afligido",
			Ud: "había afligido",
			nosotros: "habíamos afligido",
			vosotros: "habíais afligido",
			Uds: "habían afligido",
		},
		Conditional: {
			yo: "habría afligido",
			tú: "habrías afligido",
			Ud: "habría afligido",
			nosotros: "habríamos afligido",
			vosotros: "habríais afligido",
			Uds: "habrían afligido",
		},
		Future: {
			yo: "habré afligido",
			tú: "habrás afligido",
			Ud: "habrá afligido",
			nosotros: "habremos afligido",
			vosotros: "habréis afligido",
			Uds: "habrán afligido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya afligido",
			tú: "hayas afligido",
			Ud: "haya afligido",
			nosotros: "hayamos afligido",
			vosotros: "hayáis afligido",
			Uds: "hayan afligido",
		},
		Past: {
			yo: "hubiera afligido",
			tú: "hubieras afligido",
			Ud: "hubiera afligido",
			nosotros: "hubiéramos afligido",
			vosotros: "hubierais afligido",
			Uds: "hubieran afligido",
		},
		Future: {
			yo: "hubiere afligido",
			tú: "hubieres afligido",
			Ud: "hubiere afligido",
			nosotros: "hubiéremos afligido",
			vosotros: "hubiereis afligido",
			Uds: "hubieren afligido",
		},
	},
}
