var aflojar = {
	Indicative: {
		Present: {
			yo: "aflojo",
			tú: "aflojas",
			Ud: "afloja",
			nosotros: "aflojamos",
			vosotros: "aflojáis",
			Uds: "aflojan",
		},
		Preterite: {
			yo: "aflojé",
			tú: "aflojaste",
			Ud: "aflojó",
			nosotros: "aflojamos",
			vosotros: "aflojasteis",
			Uds: "aflojaron",
		},
		Imperfect: {
			yo: "aflojaba",
			tú: "aflojabas",
			Ud: "aflojaba",
			nosotros: "aflojábamos",
			vosotros: "aflojabais",
			Uds: "aflojaban",
		},
		Conditional: {
			yo: "aflojaría",
			tú: "aflojarías",
			Ud: "aflojaría",
			nosotros: "aflojaríamos",
			vosotros: "aflojaríais",
			Uds: "aflojarían",
		},
		Future: {
			yo: "aflojaré",
			tú: "aflojarás",
			Ud: "aflojará",
			nosotros: "aflojaremos",
			vosotros: "aflojaréis",
			Uds: "aflojarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "afloje",
			tú: "aflojes",
			Ud: "afloje",
			nosotros: "aflojemos",
			vosotros: "aflojéis",
			Uds: "aflojen",
		},
		Imperfect: {
			yo: "aflojara",
			tú: "aflojaras",
			Ud: "aflojara",
			nosotros: "aflojáramos",
			vosotros: "aflojarais",
			Uds: "aflojaran",
		},
		Imperfect2: {
			yo: "aflojase",
			tú: "aflojases",
			Ud: "aflojase",
			nosotros: "aflojásemos",
			vosotros: "aflojaseis",
			Uds: "aflojasen",
		},
		Future: {
			yo: "aflojare",
			tú: "aflojares",
			Ud: "aflojare",
			nosotros: "aflojáremos",
			vosotros: "aflojareis",
			Uds: "aflojaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "afloja",
			Ud: "afloje",
			nosotros: "aflojemos",
			vosotros: "aflojad",
			Uds: "aflojen",
		},
		Negative: {
			tú: "no aflojes",
			Ud: "no afloje",
			nosotros: "no aflojemos",
			vosotros: "no aflojéis",
			Uds: "no aflojen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy aflojando",
			tú: "estás aflojando",
			Ud: "está aflojando",
			nosotros: "estamos aflojando",
			vosotros: "estáis aflojando",
			Uds: "están aflojando",
		},
		Preterite: {
			yo: "estuve aflojando",
			tú: "estuviste aflojando",
			Ud: "estuvo aflojando",
			nosotros: "estuvimos aflojando",
			vosotros: "estuvisteis aflojando",
			Uds: "estuvieron aflojando",
		},
		Imperfect: {
			Uds: "estaban aflojando",
			yo: "estaba aflojando",
			tú: "estabas aflojando",
			Ud: "estaba aflojando",
			nosotros: "estábamos aflojando",
			vosotros: "estabais aflojando",
		},
		Conditional: {
			yo: "estaría aflojando",
			tú: "estarías aflojando",
			Ud: "estaría aflojando",
			nosotros: "estaríamos aflojando",
			vosotros: "estaríais aflojando",
			Uds: "estarían aflojando",
		},
		Future: {
			yo: "estaré aflojando",
			tú: "estarás aflojando",
			Ud: "estará aflojando",
			nosotros: "estaremos aflojando",
			vosotros: "estaréis aflojando",
			Uds: "estarán aflojando",
		},
	},
	Perfect: {
		Present: {
			yo: "he aflojado",
			tú: "has aflojado",
			Ud: "ha aflojado",
			nosotros: "hemos aflojado",
			vosotros: "habéis aflojado",
			Uds: "han aflojado",
		},
		Preterite: {
			yo: "hube aflojado",
			tú: "hubiste aflojado",
			Ud: "hubo aflojado",
			nosotros: "hubimos aflojado",
			vosotros: "hubisteis aflojado",
			Uds: "hubieron aflojado",
		},
		Past: {
			yo: "había aflojado",
			tú: "habías aflojado",
			Ud: "había aflojado",
			nosotros: "habíamos aflojado",
			vosotros: "habíais aflojado",
			Uds: "habían aflojado",
		},
		Conditional: {
			yo: "habría aflojado",
			tú: "habrías aflojado",
			Ud: "habría aflojado",
			nosotros: "habríamos aflojado",
			vosotros: "habríais aflojado",
			Uds: "habrían aflojado",
		},
		Future: {
			yo: "habré aflojado",
			tú: "habrás aflojado",
			Ud: "habrá aflojado",
			nosotros: "habremos aflojado",
			vosotros: "habréis aflojado",
			Uds: "habrán aflojado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya aflojado",
			tú: "hayas aflojado",
			Ud: "haya aflojado",
			nosotros: "hayamos aflojado",
			vosotros: "hayáis aflojado",
			Uds: "hayan aflojado",
		},
		Past: {
			yo: "hubiera aflojado",
			tú: "hubieras aflojado",
			Ud: "hubiera aflojado",
			nosotros: "hubiéramos aflojado",
			vosotros: "hubierais aflojado",
			Uds: "hubieran aflojado",
		},
		Future: {
			yo: "hubiere aflojado",
			tú: "hubieres aflojado",
			Ud: "hubiere aflojado",
			nosotros: "hubiéremos aflojado",
			vosotros: "hubiereis aflojado",
			Uds: "hubieren aflojado",
		},
	},
}
