var agobiar = {
	Indicative: {
		Present: {
			yo: "agobio",
			tú: "agobias",
			Ud: "agobia",
			nosotros: "agobiamos",
			vosotros: "agobiáis",
			Uds: "agobian",
		},
		Preterite: {
			yo: "agobié",
			tú: "agobiaste",
			Ud: "agobió",
			nosotros: "agobiamos",
			vosotros: "agobiasteis",
			Uds: "agobiaron",
		},
		Imperfect: {
			yo: "agobiaba",
			tú: "agobiabas",
			Ud: "agobiaba",
			nosotros: "agobiábamos",
			vosotros: "agobiabais",
			Uds: "agobiaban",
		},
		Conditional: {
			yo: "agobiaría",
			tú: "agobiarías",
			Ud: "agobiaría",
			nosotros: "agobiaríamos",
			vosotros: "agobiaríais",
			Uds: "agobiarían",
		},
		Future: {
			yo: "agobiaré",
			tú: "agobiarás",
			Ud: "agobiará",
			nosotros: "agobiaremos",
			vosotros: "agobiaréis",
			Uds: "agobiarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "agobie",
			tú: "agobies",
			Ud: "agobie",
			nosotros: "agobiemos",
			vosotros: "agobiéis",
			Uds: "agobien",
		},
		Imperfect: {
			yo: "agobiara",
			tú: "agobiaras",
			Ud: "agobiara",
			nosotros: "agobiáramos",
			vosotros: "agobiarais",
			Uds: "agobiaran",
		},
		Imperfect2: {
			yo: "agobiase",
			tú: "agobiases",
			Ud: "agobiase",
			nosotros: "agobiásemos",
			vosotros: "agobiaseis",
			Uds: "agobiasen",
		},
		Future: {
			yo: "agobiare",
			tú: "agobiares",
			Ud: "agobiare",
			nosotros: "agobiáremos",
			vosotros: "agobiareis",
			Uds: "agobiaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "agobia",
			Ud: "agobie",
			nosotros: "agobiemos",
			vosotros: "agobiad",
			Uds: "agobien",
		},
		Negative: {
			tú: "no agobies",
			Ud: "no agobie",
			nosotros: "no agobiemos",
			vosotros: "no agobiéis",
			Uds: "no agobien",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy agobiando",
			tú: "estás agobiando",
			Ud: "está agobiando",
			nosotros: "estamos agobiando",
			vosotros: "estáis agobiando",
			Uds: "están agobiando",
		},
		Preterite: {
			yo: "estuve agobiando",
			tú: "estuviste agobiando",
			Ud: "estuvo agobiando",
			nosotros: "estuvimos agobiando",
			vosotros: "estuvisteis agobiando",
			Uds: "estuvieron agobiando",
		},
		Imperfect: {
			Uds: "estaban agobiando",
			yo: "estaba agobiando",
			tú: "estabas agobiando",
			Ud: "estaba agobiando",
			nosotros: "estábamos agobiando",
			vosotros: "estabais agobiando",
		},
		Conditional: {
			yo: "estaría agobiando",
			tú: "estarías agobiando",
			Ud: "estaría agobiando",
			nosotros: "estaríamos agobiando",
			vosotros: "estaríais agobiando",
			Uds: "estarían agobiando",
		},
		Future: {
			yo: "estaré agobiando",
			tú: "estarás agobiando",
			Ud: "estará agobiando",
			nosotros: "estaremos agobiando",
			vosotros: "estaréis agobiando",
			Uds: "estarán agobiando",
		},
	},
	Perfect: {
		Present: {
			yo: "he agobiado",
			tú: "has agobiado",
			Ud: "ha agobiado",
			nosotros: "hemos agobiado",
			vosotros: "habéis agobiado",
			Uds: "han agobiado",
		},
		Preterite: {
			yo: "hube agobiado",
			tú: "hubiste agobiado",
			Ud: "hubo agobiado",
			nosotros: "hubimos agobiado",
			vosotros: "hubisteis agobiado",
			Uds: "hubieron agobiado",
		},
		Past: {
			yo: "había agobiado",
			tú: "habías agobiado",
			Ud: "había agobiado",
			nosotros: "habíamos agobiado",
			vosotros: "habíais agobiado",
			Uds: "habían agobiado",
		},
		Conditional: {
			yo: "habría agobiado",
			tú: "habrías agobiado",
			Ud: "habría agobiado",
			nosotros: "habríamos agobiado",
			vosotros: "habríais agobiado",
			Uds: "habrían agobiado",
		},
		Future: {
			yo: "habré agobiado",
			tú: "habrás agobiado",
			Ud: "habrá agobiado",
			nosotros: "habremos agobiado",
			vosotros: "habréis agobiado",
			Uds: "habrán agobiado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya agobiado",
			tú: "hayas agobiado",
			Ud: "haya agobiado",
			nosotros: "hayamos agobiado",
			vosotros: "hayáis agobiado",
			Uds: "hayan agobiado",
		},
		Past: {
			yo: "hubiera agobiado",
			tú: "hubieras agobiado",
			Ud: "hubiera agobiado",
			nosotros: "hubiéramos agobiado",
			vosotros: "hubierais agobiado",
			Uds: "hubieran agobiado",
		},
		Future: {
			yo: "hubiere agobiado",
			tú: "hubieres agobiado",
			Ud: "hubiere agobiado",
			nosotros: "hubiéremos agobiado",
			vosotros: "hubiereis agobiado",
			Uds: "hubieren agobiado",
		},
	},
}
