var agorar = {
	Indicative: {
		Present: {
			yo: "agüero",
			tú: "agüeras",
			Ud: "agüera",
			nosotros: "agoramos",
			vosotros: "agoráis",
			Uds: "agüeran",
		},
		Preterite: {
			yo: "agoré",
			tú: "agoraste",
			Ud: "agoró",
			nosotros: "agoramos",
			vosotros: "agorasteis",
			Uds: "agoraron",
		},
		Imperfect: {
			yo: "agoraba",
			tú: "agorabas",
			Ud: "agoraba",
			nosotros: "agorábamos",
			vosotros: "agorabais",
			Uds: "agoraban",
		},
		Conditional: {
			yo: "agoraría",
			tú: "agorarías",
			Ud: "agoraría",
			nosotros: "agoraríamos",
			vosotros: "agoraríais",
			Uds: "agorarían",
		},
		Future: {
			yo: "agoraré",
			tú: "agorarás",
			Ud: "agorará",
			nosotros: "agoraremos",
			vosotros: "agoraréis",
			Uds: "agorarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "agüere",
			tú: "agüeres",
			Ud: "agüere",
			nosotros: "agoremos",
			vosotros: "agoréis",
			Uds: "agüeren",
		},
		Imperfect: {
			yo: "agorara",
			tú: "agoraras",
			Ud: "agorara",
			nosotros: "agoráramos",
			vosotros: "agorarais",
			Uds: "agoraran",
		},
		Imperfect2: {
			yo: "agorase",
			tú: "agorases",
			Ud: "agorase",
			nosotros: "agorásemos",
			vosotros: "agoraseis",
			Uds: "agorasen",
		},
		Future: {
			yo: "agorare",
			tú: "agorares",
			Ud: "agorare",
			nosotros: "agoráremos",
			vosotros: "agorareis",
			Uds: "agoraren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "agüera",
			Ud: "agüere",
			nosotros: "agoremos",
			vosotros: "agorad",
			Uds: "agüeren",
		},
		Negative: {
			tú: "no agüeres",
			Ud: "no agüere",
			nosotros: "no agoremos",
			vosotros: "no agoréis",
			Uds: "no agüeren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy agorando",
			tú: "estás agorando",
			Ud: "está agorando",
			nosotros: "estamos agorando",
			vosotros: "estáis agorando",
			Uds: "están agorando",
		},
		Preterite: {
			yo: "estuve agorando",
			tú: "estuviste agorando",
			Ud: "estuvo agorando",
			nosotros: "estuvimos agorando",
			vosotros: "estuvisteis agorando",
			Uds: "estuvieron agorando",
		},
		Imperfect: {
			Uds: "estaban agorando",
			yo: "estaba agorando",
			tú: "estabas agorando",
			Ud: "estaba agorando",
			nosotros: "estábamos agorando",
			vosotros: "estabais agorando",
		},
		Conditional: {
			yo: "estaría agorando",
			tú: "estarías agorando",
			Ud: "estaría agorando",
			nosotros: "estaríamos agorando",
			vosotros: "estaríais agorando",
			Uds: "estarían agorando",
		},
		Future: {
			yo: "estaré agorando",
			tú: "estarás agorando",
			Ud: "estará agorando",
			nosotros: "estaremos agorando",
			vosotros: "estaréis agorando",
			Uds: "estarán agorando",
		},
	},
	Perfect: {
		Present: {
			yo: "he agorado",
			tú: "has agorado",
			Ud: "ha agorado",
			nosotros: "hemos agorado",
			vosotros: "habéis agorado",
			Uds: "han agorado",
		},
		Preterite: {
			yo: "hube agorado",
			tú: "hubiste agorado",
			Ud: "hubo agorado",
			nosotros: "hubimos agorado",
			vosotros: "hubisteis agorado",
			Uds: "hubieron agorado",
		},
		Past: {
			yo: "había agorado",
			tú: "habías agorado",
			Ud: "había agorado",
			nosotros: "habíamos agorado",
			vosotros: "habíais agorado",
			Uds: "habían agorado",
		},
		Conditional: {
			yo: "habría agorado",
			tú: "habrías agorado",
			Ud: "habría agorado",
			nosotros: "habríamos agorado",
			vosotros: "habríais agorado",
			Uds: "habrían agorado",
		},
		Future: {
			yo: "habré agorado",
			tú: "habrás agorado",
			Ud: "habrá agorado",
			nosotros: "habremos agorado",
			vosotros: "habréis agorado",
			Uds: "habrán agorado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya agorado",
			tú: "hayas agorado",
			Ud: "haya agorado",
			nosotros: "hayamos agorado",
			vosotros: "hayáis agorado",
			Uds: "hayan agorado",
		},
		Past: {
			yo: "hubiera agorado",
			tú: "hubieras agorado",
			Ud: "hubiera agorado",
			nosotros: "hubiéramos agorado",
			vosotros: "hubierais agorado",
			Uds: "hubieran agorado",
		},
		Future: {
			yo: "hubiere agorado",
			tú: "hubieres agorado",
			Ud: "hubiere agorado",
			nosotros: "hubiéremos agorado",
			vosotros: "hubiereis agorado",
			Uds: "hubieren agorado",
		},
	},
}
