var agotar = {
	Indicative: {
		Present: {
			yo: "agoto",
			tú: "agotas",
			Ud: "agota",
			nosotros: "agotamos",
			vosotros: "agotáis",
			Uds: "agotan",
		},
		Preterite: {
			yo: "agoté",
			tú: "agotaste",
			Ud: "agotó",
			nosotros: "agotamos",
			vosotros: "agotasteis",
			Uds: "agotaron",
		},
		Imperfect: {
			yo: "agotaba",
			tú: "agotabas",
			Ud: "agotaba",
			nosotros: "agotábamos",
			vosotros: "agotabais",
			Uds: "agotaban",
		},
		Conditional: {
			yo: "agotaría",
			tú: "agotarías",
			Ud: "agotaría",
			nosotros: "agotaríamos",
			vosotros: "agotaríais",
			Uds: "agotarían",
		},
		Future: {
			yo: "agotaré",
			tú: "agotarás",
			Ud: "agotará",
			nosotros: "agotaremos",
			vosotros: "agotaréis",
			Uds: "agotarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "agote",
			tú: "agotes",
			Ud: "agote",
			nosotros: "agotemos",
			vosotros: "agotéis",
			Uds: "agoten",
		},
		Imperfect: {
			yo: "agotara",
			tú: "agotaras",
			Ud: "agotara",
			nosotros: "agotáramos",
			vosotros: "agotarais",
			Uds: "agotaran",
		},
		Imperfect2: {
			yo: "agotase",
			tú: "agotases",
			Ud: "agotase",
			nosotros: "agotásemos",
			vosotros: "agotaseis",
			Uds: "agotasen",
		},
		Future: {
			yo: "agotare",
			tú: "agotares",
			Ud: "agotare",
			nosotros: "agotáremos",
			vosotros: "agotareis",
			Uds: "agotaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "agota",
			Ud: "agote",
			nosotros: "agotemos",
			vosotros: "agotad",
			Uds: "agoten",
		},
		Negative: {
			tú: "no agotes",
			Ud: "no agote",
			nosotros: "no agotemos",
			vosotros: "no agotéis",
			Uds: "no agoten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy agotando",
			tú: "estás agotando",
			Ud: "está agotando",
			nosotros: "estamos agotando",
			vosotros: "estáis agotando",
			Uds: "están agotando",
		},
		Preterite: {
			yo: "estuve agotando",
			tú: "estuviste agotando",
			Ud: "estuvo agotando",
			nosotros: "estuvimos agotando",
			vosotros: "estuvisteis agotando",
			Uds: "estuvieron agotando",
		},
		Imperfect: {
			Uds: "estaban agotando",
			yo: "estaba agotando",
			tú: "estabas agotando",
			Ud: "estaba agotando",
			nosotros: "estábamos agotando",
			vosotros: "estabais agotando",
		},
		Conditional: {
			yo: "estaría agotando",
			tú: "estarías agotando",
			Ud: "estaría agotando",
			nosotros: "estaríamos agotando",
			vosotros: "estaríais agotando",
			Uds: "estarían agotando",
		},
		Future: {
			yo: "estaré agotando",
			tú: "estarás agotando",
			Ud: "estará agotando",
			nosotros: "estaremos agotando",
			vosotros: "estaréis agotando",
			Uds: "estarán agotando",
		},
	},
	Perfect: {
		Present: {
			yo: "he agotado",
			tú: "has agotado",
			Ud: "ha agotado",
			nosotros: "hemos agotado",
			vosotros: "habéis agotado",
			Uds: "han agotado",
		},
		Preterite: {
			yo: "hube agotado",
			tú: "hubiste agotado",
			Ud: "hubo agotado",
			nosotros: "hubimos agotado",
			vosotros: "hubisteis agotado",
			Uds: "hubieron agotado",
		},
		Past: {
			yo: "había agotado",
			tú: "habías agotado",
			Ud: "había agotado",
			nosotros: "habíamos agotado",
			vosotros: "habíais agotado",
			Uds: "habían agotado",
		},
		Conditional: {
			yo: "habría agotado",
			tú: "habrías agotado",
			Ud: "habría agotado",
			nosotros: "habríamos agotado",
			vosotros: "habríais agotado",
			Uds: "habrían agotado",
		},
		Future: {
			yo: "habré agotado",
			tú: "habrás agotado",
			Ud: "habrá agotado",
			nosotros: "habremos agotado",
			vosotros: "habréis agotado",
			Uds: "habrán agotado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya agotado",
			tú: "hayas agotado",
			Ud: "haya agotado",
			nosotros: "hayamos agotado",
			vosotros: "hayáis agotado",
			Uds: "hayan agotado",
		},
		Past: {
			yo: "hubiera agotado",
			tú: "hubieras agotado",
			Ud: "hubiera agotado",
			nosotros: "hubiéramos agotado",
			vosotros: "hubierais agotado",
			Uds: "hubieran agotado",
		},
		Future: {
			yo: "hubiere agotado",
			tú: "hubieres agotado",
			Ud: "hubiere agotado",
			nosotros: "hubiéremos agotado",
			vosotros: "hubiereis agotado",
			Uds: "hubieren agotado",
		},
	},
}
