var agraviar = {
	Indicative: {
		Present: {
			yo: "agravio",
			tú: "agravias",
			Ud: "agravia",
			nosotros: "agraviamos",
			vosotros: "agraviáis",
			Uds: "agravian",
		},
		Preterite: {
			yo: "agravié",
			tú: "agraviaste",
			Ud: "agravió",
			nosotros: "agraviamos",
			vosotros: "agraviasteis",
			Uds: "agraviaron",
		},
		Imperfect: {
			yo: "agraviaba",
			tú: "agraviabas",
			Ud: "agraviaba",
			nosotros: "agraviábamos",
			vosotros: "agraviabais",
			Uds: "agraviaban",
		},
		Conditional: {
			yo: "agraviaría",
			tú: "agraviarías",
			Ud: "agraviaría",
			nosotros: "agraviaríamos",
			vosotros: "agraviaríais",
			Uds: "agraviarían",
		},
		Future: {
			yo: "agraviaré",
			tú: "agraviarás",
			Ud: "agraviará",
			nosotros: "agraviaremos",
			vosotros: "agraviaréis",
			Uds: "agraviarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "agravie",
			tú: "agravies",
			Ud: "agravie",
			nosotros: "agraviemos",
			vosotros: "agraviéis",
			Uds: "agravien",
		},
		Imperfect: {
			yo: "agraviara",
			tú: "agraviaras",
			Ud: "agraviara",
			nosotros: "agraviáramos",
			vosotros: "agraviarais",
			Uds: "agraviaran",
		},
		Imperfect2: {
			yo: "agraviase",
			tú: "agraviases",
			Ud: "agraviase",
			nosotros: "agraviásemos",
			vosotros: "agraviaseis",
			Uds: "agraviasen",
		},
		Future: {
			yo: "agraviare",
			tú: "agraviares",
			Ud: "agraviare",
			nosotros: "agraviáremos",
			vosotros: "agraviareis",
			Uds: "agraviaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "agravia",
			Ud: "agravie",
			nosotros: "agraviemos",
			vosotros: "agraviad",
			Uds: "agravien",
		},
		Negative: {
			tú: "no agravies",
			Ud: "no agravie",
			nosotros: "no agraviemos",
			vosotros: "no agraviéis",
			Uds: "no agravien",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy agraviando",
			tú: "estás agraviando",
			Ud: "está agraviando",
			nosotros: "estamos agraviando",
			vosotros: "estáis agraviando",
			Uds: "están agraviando",
		},
		Preterite: {
			yo: "estuve agraviando",
			tú: "estuviste agraviando",
			Ud: "estuvo agraviando",
			nosotros: "estuvimos agraviando",
			vosotros: "estuvisteis agraviando",
			Uds: "estuvieron agraviando",
		},
		Imperfect: {
			Uds: "estaban agraviando",
			yo: "estaba agraviando",
			tú: "estabas agraviando",
			Ud: "estaba agraviando",
			nosotros: "estábamos agraviando",
			vosotros: "estabais agraviando",
		},
		Conditional: {
			yo: "estaría agraviando",
			tú: "estarías agraviando",
			Ud: "estaría agraviando",
			nosotros: "estaríamos agraviando",
			vosotros: "estaríais agraviando",
			Uds: "estarían agraviando",
		},
		Future: {
			yo: "estaré agraviando",
			tú: "estarás agraviando",
			Ud: "estará agraviando",
			nosotros: "estaremos agraviando",
			vosotros: "estaréis agraviando",
			Uds: "estarán agraviando",
		},
	},
	Perfect: {
		Present: {
			yo: "he agraviado",
			tú: "has agraviado",
			Ud: "ha agraviado",
			nosotros: "hemos agraviado",
			vosotros: "habéis agraviado",
			Uds: "han agraviado",
		},
		Preterite: {
			yo: "hube agraviado",
			tú: "hubiste agraviado",
			Ud: "hubo agraviado",
			nosotros: "hubimos agraviado",
			vosotros: "hubisteis agraviado",
			Uds: "hubieron agraviado",
		},
		Past: {
			yo: "había agraviado",
			tú: "habías agraviado",
			Ud: "había agraviado",
			nosotros: "habíamos agraviado",
			vosotros: "habíais agraviado",
			Uds: "habían agraviado",
		},
		Conditional: {
			yo: "habría agraviado",
			tú: "habrías agraviado",
			Ud: "habría agraviado",
			nosotros: "habríamos agraviado",
			vosotros: "habríais agraviado",
			Uds: "habrían agraviado",
		},
		Future: {
			yo: "habré agraviado",
			tú: "habrás agraviado",
			Ud: "habrá agraviado",
			nosotros: "habremos agraviado",
			vosotros: "habréis agraviado",
			Uds: "habrán agraviado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya agraviado",
			tú: "hayas agraviado",
			Ud: "haya agraviado",
			nosotros: "hayamos agraviado",
			vosotros: "hayáis agraviado",
			Uds: "hayan agraviado",
		},
		Past: {
			yo: "hubiera agraviado",
			tú: "hubieras agraviado",
			Ud: "hubiera agraviado",
			nosotros: "hubiéramos agraviado",
			vosotros: "hubierais agraviado",
			Uds: "hubieran agraviado",
		},
		Future: {
			yo: "hubiere agraviado",
			tú: "hubieres agraviado",
			Ud: "hubiere agraviado",
			nosotros: "hubiéremos agraviado",
			vosotros: "hubiereis agraviado",
			Uds: "hubieren agraviado",
		},
	},
}
