var agriar = {
	Indicative: {
		Present: {
			yo: "agrío",
			tú: "agrías",
			Ud: "agría",
			nosotros: "agriamos",
			vosotros: "agriáis",
			Uds: "agrían",
		},
		Preterite: {
			yo: "agrié",
			tú: "agriaste",
			Ud: "agrió",
			nosotros: "agriamos",
			vosotros: "agriasteis",
			Uds: "agriaron",
		},
		Imperfect: {
			yo: "agriaba",
			tú: "agriabas",
			Ud: "agriaba",
			nosotros: "agriábamos",
			vosotros: "agriabais",
			Uds: "agriaban",
		},
		Conditional: {
			yo: "agriaría",
			tú: "agriarías",
			Ud: "agriaría",
			nosotros: "agriaríamos",
			vosotros: "agriaríais",
			Uds: "agriarían",
		},
		Future: {
			yo: "agriaré",
			tú: "agriarás",
			Ud: "agriará",
			nosotros: "agriaremos",
			vosotros: "agriaréis",
			Uds: "agriarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "agríe",
			tú: "agríes",
			Ud: "agríe",
			nosotros: "agriemos",
			vosotros: "agriéis",
			Uds: "agríen",
		},
		Imperfect: {
			yo: "agriara",
			tú: "agriaras",
			Ud: "agriara",
			nosotros: "agriáramos",
			vosotros: "agriarais",
			Uds: "agriaran",
		},
		Imperfect2: {
			yo: "agriase",
			tú: "agriases",
			Ud: "agriase",
			nosotros: "agriásemos",
			vosotros: "agriaseis",
			Uds: "agriasen",
		},
		Future: {
			yo: "agriare",
			tú: "agriares",
			Ud: "agriare",
			nosotros: "agriáremos",
			vosotros: "agriareis",
			Uds: "agriaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "agría",
			Ud: "agríe",
			nosotros: "agriemos",
			vosotros: "agriad",
			Uds: "agríen",
		},
		Negative: {
			tú: "no agríes",
			Ud: "no agríe",
			nosotros: "no agriemos",
			vosotros: "no agriéis",
			Uds: "no agríen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy agriando",
			tú: "estás agriando",
			Ud: "está agriando",
			nosotros: "estamos agriando",
			vosotros: "estáis agriando",
			Uds: "están agriando",
		},
		Preterite: {
			yo: "estuve agriando",
			tú: "estuviste agriando",
			Ud: "estuvo agriando",
			nosotros: "estuvimos agriando",
			vosotros: "estuvisteis agriando",
			Uds: "estuvieron agriando",
		},
		Imperfect: {
			Uds: "estaban agriando",
			yo: "estaba agriando",
			tú: "estabas agriando",
			Ud: "estaba agriando",
			nosotros: "estábamos agriando",
			vosotros: "estabais agriando",
		},
		Conditional: {
			yo: "estaría agriando",
			tú: "estarías agriando",
			Ud: "estaría agriando",
			nosotros: "estaríamos agriando",
			vosotros: "estaríais agriando",
			Uds: "estarían agriando",
		},
		Future: {
			yo: "estaré agriando",
			tú: "estarás agriando",
			Ud: "estará agriando",
			nosotros: "estaremos agriando",
			vosotros: "estaréis agriando",
			Uds: "estarán agriando",
		},
	},
	Perfect: {
		Present: {
			yo: "he agriado",
			tú: "has agriado",
			Ud: "ha agriado",
			nosotros: "hemos agriado",
			vosotros: "habéis agriado",
			Uds: "han agriado",
		},
		Preterite: {
			yo: "hube agriado",
			tú: "hubiste agriado",
			Ud: "hubo agriado",
			nosotros: "hubimos agriado",
			vosotros: "hubisteis agriado",
			Uds: "hubieron agriado",
		},
		Past: {
			yo: "había agriado",
			tú: "habías agriado",
			Ud: "había agriado",
			nosotros: "habíamos agriado",
			vosotros: "habíais agriado",
			Uds: "habían agriado",
		},
		Conditional: {
			yo: "habría agriado",
			tú: "habrías agriado",
			Ud: "habría agriado",
			nosotros: "habríamos agriado",
			vosotros: "habríais agriado",
			Uds: "habrían agriado",
		},
		Future: {
			yo: "habré agriado",
			tú: "habrás agriado",
			Ud: "habrá agriado",
			nosotros: "habremos agriado",
			vosotros: "habréis agriado",
			Uds: "habrán agriado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya agriado",
			tú: "hayas agriado",
			Ud: "haya agriado",
			nosotros: "hayamos agriado",
			vosotros: "hayáis agriado",
			Uds: "hayan agriado",
		},
		Past: {
			yo: "hubiera agriado",
			tú: "hubieras agriado",
			Ud: "hubiera agriado",
			nosotros: "hubiéramos agriado",
			vosotros: "hubierais agriado",
			Uds: "hubieran agriado",
		},
		Future: {
			yo: "hubiere agriado",
			tú: "hubieres agriado",
			Ud: "hubiere agriado",
			nosotros: "hubiéremos agriado",
			vosotros: "hubiereis agriado",
			Uds: "hubieren agriado",
		},
	},
}
