var aguardar = {
	Indicative: {
		Present: {
			yo: "aguardo",
			tú: "aguardas",
			Ud: "aguarda",
			nosotros: "aguardamos",
			vosotros: "aguardáis",
			Uds: "aguardan",
		},
		Preterite: {
			yo: "aguardé",
			tú: "aguardaste",
			Ud: "aguardó",
			nosotros: "aguardamos",
			vosotros: "aguardasteis",
			Uds: "aguardaron",
		},
		Imperfect: {
			yo: "aguardaba",
			tú: "aguardabas",
			Ud: "aguardaba",
			nosotros: "aguardábamos",
			vosotros: "aguardabais",
			Uds: "aguardaban",
		},
		Conditional: {
			yo: "aguardaría",
			tú: "aguardarías",
			Ud: "aguardaría",
			nosotros: "aguardaríamos",
			vosotros: "aguardaríais",
			Uds: "aguardarían",
		},
		Future: {
			yo: "aguardaré",
			tú: "aguardarás",
			Ud: "aguardará",
			nosotros: "aguardaremos",
			vosotros: "aguardaréis",
			Uds: "aguardarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "aguarde",
			tú: "aguardes",
			Ud: "aguarde",
			nosotros: "aguardemos",
			vosotros: "aguardéis",
			Uds: "aguarden",
		},
		Imperfect: {
			yo: "aguardara",
			tú: "aguardaras",
			Ud: "aguardara",
			nosotros: "aguardáramos",
			vosotros: "aguardarais",
			Uds: "aguardaran",
		},
		Imperfect2: {
			yo: "aguardase",
			tú: "aguardases",
			Ud: "aguardase",
			nosotros: "aguardásemos",
			vosotros: "aguardaseis",
			Uds: "aguardasen",
		},
		Future: {
			yo: "aguardare",
			tú: "aguardares",
			Ud: "aguardare",
			nosotros: "aguardáremos",
			vosotros: "aguardareis",
			Uds: "aguardaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "aguarda",
			Ud: "aguarde",
			nosotros: "aguardemos",
			vosotros: "aguardad",
			Uds: "aguarden",
		},
		Negative: {
			tú: "no aguardes",
			Ud: "no aguarde",
			nosotros: "no aguardemos",
			vosotros: "no aguardéis",
			Uds: "no aguarden",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy aguardando",
			tú: "estás aguardando",
			Ud: "está aguardando",
			nosotros: "estamos aguardando",
			vosotros: "estáis aguardando",
			Uds: "están aguardando",
		},
		Preterite: {
			yo: "estuve aguardando",
			tú: "estuviste aguardando",
			Ud: "estuvo aguardando",
			nosotros: "estuvimos aguardando",
			vosotros: "estuvisteis aguardando",
			Uds: "estuvieron aguardando",
		},
		Imperfect: {
			Uds: "estaban aguardando",
			yo: "estaba aguardando",
			tú: "estabas aguardando",
			Ud: "estaba aguardando",
			nosotros: "estábamos aguardando",
			vosotros: "estabais aguardando",
		},
		Conditional: {
			yo: "estaría aguardando",
			tú: "estarías aguardando",
			Ud: "estaría aguardando",
			nosotros: "estaríamos aguardando",
			vosotros: "estaríais aguardando",
			Uds: "estarían aguardando",
		},
		Future: {
			yo: "estaré aguardando",
			tú: "estarás aguardando",
			Ud: "estará aguardando",
			nosotros: "estaremos aguardando",
			vosotros: "estaréis aguardando",
			Uds: "estarán aguardando",
		},
	},
	Perfect: {
		Present: {
			yo: "he aguardado",
			tú: "has aguardado",
			Ud: "ha aguardado",
			nosotros: "hemos aguardado",
			vosotros: "habéis aguardado",
			Uds: "han aguardado",
		},
		Preterite: {
			yo: "hube aguardado",
			tú: "hubiste aguardado",
			Ud: "hubo aguardado",
			nosotros: "hubimos aguardado",
			vosotros: "hubisteis aguardado",
			Uds: "hubieron aguardado",
		},
		Past: {
			yo: "había aguardado",
			tú: "habías aguardado",
			Ud: "había aguardado",
			nosotros: "habíamos aguardado",
			vosotros: "habíais aguardado",
			Uds: "habían aguardado",
		},
		Conditional: {
			yo: "habría aguardado",
			tú: "habrías aguardado",
			Ud: "habría aguardado",
			nosotros: "habríamos aguardado",
			vosotros: "habríais aguardado",
			Uds: "habrían aguardado",
		},
		Future: {
			yo: "habré aguardado",
			tú: "habrás aguardado",
			Ud: "habrá aguardado",
			nosotros: "habremos aguardado",
			vosotros: "habréis aguardado",
			Uds: "habrán aguardado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya aguardado",
			tú: "hayas aguardado",
			Ud: "haya aguardado",
			nosotros: "hayamos aguardado",
			vosotros: "hayáis aguardado",
			Uds: "hayan aguardado",
		},
		Past: {
			yo: "hubiera aguardado",
			tú: "hubieras aguardado",
			Ud: "hubiera aguardado",
			nosotros: "hubiéramos aguardado",
			vosotros: "hubierais aguardado",
			Uds: "hubieran aguardado",
		},
		Future: {
			yo: "hubiere aguardado",
			tú: "hubieres aguardado",
			Ud: "hubiere aguardado",
			nosotros: "hubiéremos aguardado",
			vosotros: "hubiereis aguardado",
			Uds: "hubieren aguardado",
		},
	},
}
