var aguijar = {
	Indicative: {
		Present: {
			yo: "aguijo",
			tú: "aguijas",
			Ud: "aguija",
			nosotros: "aguijamos",
			vosotros: "aguijáis",
			Uds: "aguijan",
		},
		Preterite: {
			yo: "aguijé",
			tú: "aguijaste",
			Ud: "aguijó",
			nosotros: "aguijamos",
			vosotros: "aguijasteis",
			Uds: "aguijaron",
		},
		Imperfect: {
			yo: "aguijaba",
			tú: "aguijabas",
			Ud: "aguijaba",
			nosotros: "aguijábamos",
			vosotros: "aguijabais",
			Uds: "aguijaban",
		},
		Conditional: {
			yo: "aguijaría",
			tú: "aguijarías",
			Ud: "aguijaría",
			nosotros: "aguijaríamos",
			vosotros: "aguijaríais",
			Uds: "aguijarían",
		},
		Future: {
			yo: "aguijaré",
			tú: "aguijarás",
			Ud: "aguijará",
			nosotros: "aguijaremos",
			vosotros: "aguijaréis",
			Uds: "aguijarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "aguije",
			tú: "aguijes",
			Ud: "aguije",
			nosotros: "aguijemos",
			vosotros: "aguijéis",
			Uds: "aguijen",
		},
		Imperfect: {
			yo: "aguijara",
			tú: "aguijaras",
			Ud: "aguijara",
			nosotros: "aguijáramos",
			vosotros: "aguijarais",
			Uds: "aguijaran",
		},
		Imperfect2: {
			yo: "aguijase",
			tú: "aguijases",
			Ud: "aguijase",
			nosotros: "aguijásemos",
			vosotros: "aguijaseis",
			Uds: "aguijasen",
		},
		Future: {
			yo: "aguijare",
			tú: "aguijares",
			Ud: "aguijare",
			nosotros: "aguijáremos",
			vosotros: "aguijareis",
			Uds: "aguijaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "aguija",
			Ud: "aguije",
			nosotros: "aguijemos",
			vosotros: "aguijad",
			Uds: "aguijen",
		},
		Negative: {
			tú: "no aguijes",
			Ud: "no aguije",
			nosotros: "no aguijemos",
			vosotros: "no aguijéis",
			Uds: "no aguijen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy aguijando",
			tú: "estás aguijando",
			Ud: "está aguijando",
			nosotros: "estamos aguijando",
			vosotros: "estáis aguijando",
			Uds: "están aguijando",
		},
		Preterite: {
			yo: "estuve aguijando",
			tú: "estuviste aguijando",
			Ud: "estuvo aguijando",
			nosotros: "estuvimos aguijando",
			vosotros: "estuvisteis aguijando",
			Uds: "estuvieron aguijando",
		},
		Imperfect: {
			Uds: "estaban aguijando",
			yo: "estaba aguijando",
			tú: "estabas aguijando",
			Ud: "estaba aguijando",
			nosotros: "estábamos aguijando",
			vosotros: "estabais aguijando",
		},
		Conditional: {
			yo: "estaría aguijando",
			tú: "estarías aguijando",
			Ud: "estaría aguijando",
			nosotros: "estaríamos aguijando",
			vosotros: "estaríais aguijando",
			Uds: "estarían aguijando",
		},
		Future: {
			yo: "estaré aguijando",
			tú: "estarás aguijando",
			Ud: "estará aguijando",
			nosotros: "estaremos aguijando",
			vosotros: "estaréis aguijando",
			Uds: "estarán aguijando",
		},
	},
	Perfect: {
		Present: {
			yo: "he aguijado",
			tú: "has aguijado",
			Ud: "ha aguijado",
			nosotros: "hemos aguijado",
			vosotros: "habéis aguijado",
			Uds: "han aguijado",
		},
		Preterite: {
			yo: "hube aguijado",
			tú: "hubiste aguijado",
			Ud: "hubo aguijado",
			nosotros: "hubimos aguijado",
			vosotros: "hubisteis aguijado",
			Uds: "hubieron aguijado",
		},
		Past: {
			yo: "había aguijado",
			tú: "habías aguijado",
			Ud: "había aguijado",
			nosotros: "habíamos aguijado",
			vosotros: "habíais aguijado",
			Uds: "habían aguijado",
		},
		Conditional: {
			yo: "habría aguijado",
			tú: "habrías aguijado",
			Ud: "habría aguijado",
			nosotros: "habríamos aguijado",
			vosotros: "habríais aguijado",
			Uds: "habrían aguijado",
		},
		Future: {
			yo: "habré aguijado",
			tú: "habrás aguijado",
			Ud: "habrá aguijado",
			nosotros: "habremos aguijado",
			vosotros: "habréis aguijado",
			Uds: "habrán aguijado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya aguijado",
			tú: "hayas aguijado",
			Ud: "haya aguijado",
			nosotros: "hayamos aguijado",
			vosotros: "hayáis aguijado",
			Uds: "hayan aguijado",
		},
		Past: {
			yo: "hubiera aguijado",
			tú: "hubieras aguijado",
			Ud: "hubiera aguijado",
			nosotros: "hubiéramos aguijado",
			vosotros: "hubierais aguijado",
			Uds: "hubieran aguijado",
		},
		Future: {
			yo: "hubiere aguijado",
			tú: "hubieres aguijado",
			Ud: "hubiere aguijado",
			nosotros: "hubiéremos aguijado",
			vosotros: "hubiereis aguijado",
			Uds: "hubieren aguijado",
		},
	},
}
