var ahondar = {
	Indicative: {
		Present: {
			yo: "ahondo",
			tú: "ahondas",
			Ud: "ahonda",
			nosotros: "ahondamos",
			vosotros: "ahondáis",
			Uds: "ahondan",
		},
		Preterite: {
			yo: "ahondé",
			tú: "ahondaste",
			Ud: "ahondó",
			nosotros: "ahondamos",
			vosotros: "ahondasteis",
			Uds: "ahondaron",
		},
		Imperfect: {
			yo: "ahondaba",
			tú: "ahondabas",
			Ud: "ahondaba",
			nosotros: "ahondábamos",
			vosotros: "ahondabais",
			Uds: "ahondaban",
		},
		Conditional: {
			yo: "ahondaría",
			tú: "ahondarías",
			Ud: "ahondaría",
			nosotros: "ahondaríamos",
			vosotros: "ahondaríais",
			Uds: "ahondarían",
		},
		Future: {
			yo: "ahondaré",
			tú: "ahondarás",
			Ud: "ahondará",
			nosotros: "ahondaremos",
			vosotros: "ahondaréis",
			Uds: "ahondarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "ahonde",
			tú: "ahondes",
			Ud: "ahonde",
			nosotros: "ahondemos",
			vosotros: "ahondéis",
			Uds: "ahonden",
		},
		Imperfect: {
			yo: "ahondara",
			tú: "ahondaras",
			Ud: "ahondara",
			nosotros: "ahondáramos",
			vosotros: "ahondarais",
			Uds: "ahondaran",
		},
		Imperfect2: {
			yo: "ahondase",
			tú: "ahondases",
			Ud: "ahondase",
			nosotros: "ahondásemos",
			vosotros: "ahondaseis",
			Uds: "ahondasen",
		},
		Future: {
			yo: "ahondare",
			tú: "ahondares",
			Ud: "ahondare",
			nosotros: "ahondáremos",
			vosotros: "ahondareis",
			Uds: "ahondaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "ahonda",
			Ud: "ahonde",
			nosotros: "ahondemos",
			vosotros: "ahondad",
			Uds: "ahonden",
		},
		Negative: {
			tú: "no ahondes",
			Ud: "no ahonde",
			nosotros: "no ahondemos",
			vosotros: "no ahondéis",
			Uds: "no ahonden",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy ahondando",
			tú: "estás ahondando",
			Ud: "está ahondando",
			nosotros: "estamos ahondando",
			vosotros: "estáis ahondando",
			Uds: "están ahondando",
		},
		Preterite: {
			yo: "estuve ahondando",
			tú: "estuviste ahondando",
			Ud: "estuvo ahondando",
			nosotros: "estuvimos ahondando",
			vosotros: "estuvisteis ahondando",
			Uds: "estuvieron ahondando",
		},
		Imperfect: {
			Uds: "estaban ahondando",
			yo: "estaba ahondando",
			tú: "estabas ahondando",
			Ud: "estaba ahondando",
			nosotros: "estábamos ahondando",
			vosotros: "estabais ahondando",
		},
		Conditional: {
			yo: "estaría ahondando",
			tú: "estarías ahondando",
			Ud: "estaría ahondando",
			nosotros: "estaríamos ahondando",
			vosotros: "estaríais ahondando",
			Uds: "estarían ahondando",
		},
		Future: {
			yo: "estaré ahondando",
			tú: "estarás ahondando",
			Ud: "estará ahondando",
			nosotros: "estaremos ahondando",
			vosotros: "estaréis ahondando",
			Uds: "estarán ahondando",
		},
	},
	Perfect: {
		Present: {
			yo: "he ahondado",
			tú: "has ahondado",
			Ud: "ha ahondado",
			nosotros: "hemos ahondado",
			vosotros: "habéis ahondado",
			Uds: "han ahondado",
		},
		Preterite: {
			yo: "hube ahondado",
			tú: "hubiste ahondado",
			Ud: "hubo ahondado",
			nosotros: "hubimos ahondado",
			vosotros: "hubisteis ahondado",
			Uds: "hubieron ahondado",
		},
		Past: {
			yo: "había ahondado",
			tú: "habías ahondado",
			Ud: "había ahondado",
			nosotros: "habíamos ahondado",
			vosotros: "habíais ahondado",
			Uds: "habían ahondado",
		},
		Conditional: {
			yo: "habría ahondado",
			tú: "habrías ahondado",
			Ud: "habría ahondado",
			nosotros: "habríamos ahondado",
			vosotros: "habríais ahondado",
			Uds: "habrían ahondado",
		},
		Future: {
			yo: "habré ahondado",
			tú: "habrás ahondado",
			Ud: "habrá ahondado",
			nosotros: "habremos ahondado",
			vosotros: "habréis ahondado",
			Uds: "habrán ahondado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya ahondado",
			tú: "hayas ahondado",
			Ud: "haya ahondado",
			nosotros: "hayamos ahondado",
			vosotros: "hayáis ahondado",
			Uds: "hayan ahondado",
		},
		Past: {
			yo: "hubiera ahondado",
			tú: "hubieras ahondado",
			Ud: "hubiera ahondado",
			nosotros: "hubiéramos ahondado",
			vosotros: "hubierais ahondado",
			Uds: "hubieran ahondado",
		},
		Future: {
			yo: "hubiere ahondado",
			tú: "hubieres ahondado",
			Ud: "hubiere ahondado",
			nosotros: "hubiéremos ahondado",
			vosotros: "hubiereis ahondado",
			Uds: "hubieren ahondado",
		},
	},
}
