var airear = {
	Indicative: {
		Present: {
			yo: "aireo",
			tú: "aireas",
			Ud: "airea",
			nosotros: "aireamos",
			vosotros: "aireáis",
			Uds: "airean",
		},
		Preterite: {
			yo: "aireé",
			tú: "aireaste",
			Ud: "aireó",
			nosotros: "aireamos",
			vosotros: "aireasteis",
			Uds: "airearon",
		},
		Imperfect: {
			yo: "aireaba",
			tú: "aireabas",
			Ud: "aireaba",
			nosotros: "aireábamos",
			vosotros: "aireabais",
			Uds: "aireaban",
		},
		Conditional: {
			yo: "airearía",
			tú: "airearías",
			Ud: "airearía",
			nosotros: "airearíamos",
			vosotros: "airearíais",
			Uds: "airearían",
		},
		Future: {
			yo: "airearé",
			tú: "airearás",
			Ud: "aireará",
			nosotros: "airearemos",
			vosotros: "airearéis",
			Uds: "airearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "airee",
			tú: "airees",
			Ud: "airee",
			nosotros: "aireemos",
			vosotros: "aireéis",
			Uds: "aireen",
		},
		Imperfect: {
			yo: "aireara",
			tú: "airearas",
			Ud: "aireara",
			nosotros: "aireáramos",
			vosotros: "airearais",
			Uds: "airearan",
		},
		Imperfect2: {
			yo: "airease",
			tú: "aireases",
			Ud: "airease",
			nosotros: "aireásemos",
			vosotros: "aireaseis",
			Uds: "aireasen",
		},
		Future: {
			yo: "aireare",
			tú: "aireares",
			Ud: "aireare",
			nosotros: "aireáremos",
			vosotros: "aireareis",
			Uds: "airearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "airea",
			Ud: "airee",
			nosotros: "aireemos",
			vosotros: "airead",
			Uds: "aireen",
		},
		Negative: {
			tú: "no airees",
			Ud: "no airee",
			nosotros: "no aireemos",
			vosotros: "no aireéis",
			Uds: "no aireen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy aireando",
			tú: "estás aireando",
			Ud: "está aireando",
			nosotros: "estamos aireando",
			vosotros: "estáis aireando",
			Uds: "están aireando",
		},
		Preterite: {
			yo: "estuve aireando",
			tú: "estuviste aireando",
			Ud: "estuvo aireando",
			nosotros: "estuvimos aireando",
			vosotros: "estuvisteis aireando",
			Uds: "estuvieron aireando",
		},
		Imperfect: {
			Uds: "estaban aireando",
			yo: "estaba aireando",
			tú: "estabas aireando",
			Ud: "estaba aireando",
			nosotros: "estábamos aireando",
			vosotros: "estabais aireando",
		},
		Conditional: {
			yo: "estaría aireando",
			tú: "estarías aireando",
			Ud: "estaría aireando",
			nosotros: "estaríamos aireando",
			vosotros: "estaríais aireando",
			Uds: "estarían aireando",
		},
		Future: {
			yo: "estaré aireando",
			tú: "estarás aireando",
			Ud: "estará aireando",
			nosotros: "estaremos aireando",
			vosotros: "estaréis aireando",
			Uds: "estarán aireando",
		},
	},
	Perfect: {
		Present: {
			yo: "he aireado",
			tú: "has aireado",
			Ud: "ha aireado",
			nosotros: "hemos aireado",
			vosotros: "habéis aireado",
			Uds: "han aireado",
		},
		Preterite: {
			yo: "hube aireado",
			tú: "hubiste aireado",
			Ud: "hubo aireado",
			nosotros: "hubimos aireado",
			vosotros: "hubisteis aireado",
			Uds: "hubieron aireado",
		},
		Past: {
			yo: "había aireado",
			tú: "habías aireado",
			Ud: "había aireado",
			nosotros: "habíamos aireado",
			vosotros: "habíais aireado",
			Uds: "habían aireado",
		},
		Conditional: {
			yo: "habría aireado",
			tú: "habrías aireado",
			Ud: "habría aireado",
			nosotros: "habríamos aireado",
			vosotros: "habríais aireado",
			Uds: "habrían aireado",
		},
		Future: {
			yo: "habré aireado",
			tú: "habrás aireado",
			Ud: "habrá aireado",
			nosotros: "habremos aireado",
			vosotros: "habréis aireado",
			Uds: "habrán aireado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya aireado",
			tú: "hayas aireado",
			Ud: "haya aireado",
			nosotros: "hayamos aireado",
			vosotros: "hayáis aireado",
			Uds: "hayan aireado",
		},
		Past: {
			yo: "hubiera aireado",
			tú: "hubieras aireado",
			Ud: "hubiera aireado",
			nosotros: "hubiéramos aireado",
			vosotros: "hubierais aireado",
			Uds: "hubieran aireado",
		},
		Future: {
			yo: "hubiere aireado",
			tú: "hubieres aireado",
			Ud: "hubiere aireado",
			nosotros: "hubiéremos aireado",
			vosotros: "hubiereis aireado",
			Uds: "hubieren aireado",
		},
	},
}
