var alabar = {
	Indicative: {
		Present: {
			yo: "alabo",
			tú: "alabas",
			Ud: "alaba",
			nosotros: "alabamos",
			vosotros: "alabáis",
			Uds: "alaban",
		},
		Preterite: {
			yo: "alabé",
			tú: "alabaste",
			Ud: "alabó",
			nosotros: "alabamos",
			vosotros: "alabasteis",
			Uds: "alabaron",
		},
		Imperfect: {
			yo: "alababa",
			tú: "alababas",
			Ud: "alababa",
			nosotros: "alabábamos",
			vosotros: "alababais",
			Uds: "alababan",
		},
		Conditional: {
			yo: "alabaría",
			tú: "alabarías",
			Ud: "alabaría",
			nosotros: "alabaríamos",
			vosotros: "alabaríais",
			Uds: "alabarían",
		},
		Future: {
			yo: "alabaré",
			tú: "alabarás",
			Ud: "alabará",
			nosotros: "alabaremos",
			vosotros: "alabaréis",
			Uds: "alabarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "alabe",
			tú: "alabes",
			Ud: "alabe",
			nosotros: "alabemos",
			vosotros: "alabéis",
			Uds: "alaben",
		},
		Imperfect: {
			yo: "alabara",
			tú: "alabaras",
			Ud: "alabara",
			nosotros: "alabáramos",
			vosotros: "alabarais",
			Uds: "alabaran",
		},
		Imperfect2: {
			yo: "alabase",
			tú: "alabases",
			Ud: "alabase",
			nosotros: "alabásemos",
			vosotros: "alabaseis",
			Uds: "alabasen",
		},
		Future: {
			yo: "alabare",
			tú: "alabares",
			Ud: "alabare",
			nosotros: "alabáremos",
			vosotros: "alabareis",
			Uds: "alabaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "alaba",
			Ud: "alabe",
			nosotros: "alabemos",
			vosotros: "alabad",
			Uds: "alaben",
		},
		Negative: {
			tú: "no alabes",
			Ud: "no alabe",
			nosotros: "no alabemos",
			vosotros: "no alabéis",
			Uds: "no alaben",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy alabando",
			tú: "estás alabando",
			Ud: "está alabando",
			nosotros: "estamos alabando",
			vosotros: "estáis alabando",
			Uds: "están alabando",
		},
		Preterite: {
			yo: "estuve alabando",
			tú: "estuviste alabando",
			Ud: "estuvo alabando",
			nosotros: "estuvimos alabando",
			vosotros: "estuvisteis alabando",
			Uds: "estuvieron alabando",
		},
		Imperfect: {
			Uds: "estaban alabando",
			yo: "estaba alabando",
			tú: "estabas alabando",
			Ud: "estaba alabando",
			nosotros: "estábamos alabando",
			vosotros: "estabais alabando",
		},
		Conditional: {
			yo: "estaría alabando",
			tú: "estarías alabando",
			Ud: "estaría alabando",
			nosotros: "estaríamos alabando",
			vosotros: "estaríais alabando",
			Uds: "estarían alabando",
		},
		Future: {
			yo: "estaré alabando",
			tú: "estarás alabando",
			Ud: "estará alabando",
			nosotros: "estaremos alabando",
			vosotros: "estaréis alabando",
			Uds: "estarán alabando",
		},
	},
	Perfect: {
		Present: {
			yo: "he alabado",
			tú: "has alabado",
			Ud: "ha alabado",
			nosotros: "hemos alabado",
			vosotros: "habéis alabado",
			Uds: "han alabado",
		},
		Preterite: {
			yo: "hube alabado",
			tú: "hubiste alabado",
			Ud: "hubo alabado",
			nosotros: "hubimos alabado",
			vosotros: "hubisteis alabado",
			Uds: "hubieron alabado",
		},
		Past: {
			yo: "había alabado",
			tú: "habías alabado",
			Ud: "había alabado",
			nosotros: "habíamos alabado",
			vosotros: "habíais alabado",
			Uds: "habían alabado",
		},
		Conditional: {
			yo: "habría alabado",
			tú: "habrías alabado",
			Ud: "habría alabado",
			nosotros: "habríamos alabado",
			vosotros: "habríais alabado",
			Uds: "habrían alabado",
		},
		Future: {
			yo: "habré alabado",
			tú: "habrás alabado",
			Ud: "habrá alabado",
			nosotros: "habremos alabado",
			vosotros: "habréis alabado",
			Uds: "habrán alabado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya alabado",
			tú: "hayas alabado",
			Ud: "haya alabado",
			nosotros: "hayamos alabado",
			vosotros: "hayáis alabado",
			Uds: "hayan alabado",
		},
		Past: {
			yo: "hubiera alabado",
			tú: "hubieras alabado",
			Ud: "hubiera alabado",
			nosotros: "hubiéramos alabado",
			vosotros: "hubierais alabado",
			Uds: "hubieran alabado",
		},
		Future: {
			yo: "hubiere alabado",
			tú: "hubieres alabado",
			Ud: "hubiere alabado",
			nosotros: "hubiéremos alabado",
			vosotros: "hubiereis alabado",
			Uds: "hubieren alabado",
		},
	},
}
