var alargar = {
	Indicative: {
		Present: {
			yo: "alargo",
			tú: "alargas",
			Ud: "alarga",
			nosotros: "alargamos",
			vosotros: "alargáis",
			Uds: "alargan",
		},
		Preterite: {
			yo: "alargué",
			tú: "alargaste",
			Ud: "alargó",
			nosotros: "alargamos",
			vosotros: "alargasteis",
			Uds: "alargaron",
		},
		Imperfect: {
			yo: "alargaba",
			tú: "alargabas",
			Ud: "alargaba",
			nosotros: "alargábamos",
			vosotros: "alargabais",
			Uds: "alargaban",
		},
		Conditional: {
			yo: "alargaría",
			tú: "alargarías",
			Ud: "alargaría",
			nosotros: "alargaríamos",
			vosotros: "alargaríais",
			Uds: "alargarían",
		},
		Future: {
			yo: "alargaré",
			tú: "alargarás",
			Ud: "alargará",
			nosotros: "alargaremos",
			vosotros: "alargaréis",
			Uds: "alargarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "alargue",
			tú: "alargues",
			Ud: "alargue",
			nosotros: "alarguemos",
			vosotros: "alarguéis",
			Uds: "alarguen",
		},
		Imperfect: {
			yo: "alargara",
			tú: "alargaras",
			Ud: "alargara",
			nosotros: "alargáramos",
			vosotros: "alargarais",
			Uds: "alargaran",
		},
		Imperfect2: {
			yo: "alargase",
			tú: "alargases",
			Ud: "alargase",
			nosotros: "alargásemos",
			vosotros: "alargaseis",
			Uds: "alargasen",
		},
		Future: {
			yo: "alargare",
			tú: "alargares",
			Ud: "alargare",
			nosotros: "alargáremos",
			vosotros: "alargareis",
			Uds: "alargaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "alarga",
			Ud: "alargue",
			nosotros: "alarguemos",
			vosotros: "alargad",
			Uds: "alarguen",
		},
		Negative: {
			tú: "no alargues",
			Ud: "no alargue",
			nosotros: "no alarguemos",
			vosotros: "no alarguéis",
			Uds: "no alarguen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy alargando",
			tú: "estás alargando",
			Ud: "está alargando",
			nosotros: "estamos alargando",
			vosotros: "estáis alargando",
			Uds: "están alargando",
		},
		Preterite: {
			yo: "estuve alargando",
			tú: "estuviste alargando",
			Ud: "estuvo alargando",
			nosotros: "estuvimos alargando",
			vosotros: "estuvisteis alargando",
			Uds: "estuvieron alargando",
		},
		Imperfect: {
			Uds: "estaban alargando",
			yo: "estaba alargando",
			tú: "estabas alargando",
			Ud: "estaba alargando",
			nosotros: "estábamos alargando",
			vosotros: "estabais alargando",
		},
		Conditional: {
			yo: "estaría alargando",
			tú: "estarías alargando",
			Ud: "estaría alargando",
			nosotros: "estaríamos alargando",
			vosotros: "estaríais alargando",
			Uds: "estarían alargando",
		},
		Future: {
			yo: "estaré alargando",
			tú: "estarás alargando",
			Ud: "estará alargando",
			nosotros: "estaremos alargando",
			vosotros: "estaréis alargando",
			Uds: "estarán alargando",
		},
	},
	Perfect: {
		Present: {
			yo: "he alargado",
			tú: "has alargado",
			Ud: "ha alargado",
			nosotros: "hemos alargado",
			vosotros: "habéis alargado",
			Uds: "han alargado",
		},
		Preterite: {
			yo: "hube alargado",
			tú: "hubiste alargado",
			Ud: "hubo alargado",
			nosotros: "hubimos alargado",
			vosotros: "hubisteis alargado",
			Uds: "hubieron alargado",
		},
		Past: {
			yo: "había alargado",
			tú: "habías alargado",
			Ud: "había alargado",
			nosotros: "habíamos alargado",
			vosotros: "habíais alargado",
			Uds: "habían alargado",
		},
		Conditional: {
			yo: "habría alargado",
			tú: "habrías alargado",
			Ud: "habría alargado",
			nosotros: "habríamos alargado",
			vosotros: "habríais alargado",
			Uds: "habrían alargado",
		},
		Future: {
			yo: "habré alargado",
			tú: "habrás alargado",
			Ud: "habrá alargado",
			nosotros: "habremos alargado",
			vosotros: "habréis alargado",
			Uds: "habrán alargado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya alargado",
			tú: "hayas alargado",
			Ud: "haya alargado",
			nosotros: "hayamos alargado",
			vosotros: "hayáis alargado",
			Uds: "hayan alargado",
		},
		Past: {
			yo: "hubiera alargado",
			tú: "hubieras alargado",
			Ud: "hubiera alargado",
			nosotros: "hubiéramos alargado",
			vosotros: "hubierais alargado",
			Uds: "hubieran alargado",
		},
		Future: {
			yo: "hubiere alargado",
			tú: "hubieres alargado",
			Ud: "hubiere alargado",
			nosotros: "hubiéremos alargado",
			vosotros: "hubiereis alargado",
			Uds: "hubieren alargado",
		},
	},
}
