var alcanzar = {
	Indicative: {
		Present: {
			yo: "alcanzo",
			tú: "alcanzas",
			Ud: "alcanza",
			nosotros: "alcanzamos",
			vosotros: "alcanzáis",
			Uds: "alcanzan",
		},
		Preterite: {
			yo: "alcancé",
			tú: "alcanzaste",
			Ud: "alcanzó",
			nosotros: "alcanzamos",
			vosotros: "alcanzasteis",
			Uds: "alcanzaron",
		},
		Imperfect: {
			yo: "alcanzaba",
			tú: "alcanzabas",
			Ud: "alcanzaba",
			nosotros: "alcanzábamos",
			vosotros: "alcanzabais",
			Uds: "alcanzaban",
		},
		Conditional: {
			yo: "alcanzaría",
			tú: "alcanzarías",
			Ud: "alcanzaría",
			nosotros: "alcanzaríamos",
			vosotros: "alcanzaríais",
			Uds: "alcanzarían",
		},
		Future: {
			yo: "alcanzaré",
			tú: "alcanzarás",
			Ud: "alcanzará",
			nosotros: "alcanzaremos",
			vosotros: "alcanzaréis",
			Uds: "alcanzarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "alcance",
			tú: "alcances",
			Ud: "alcance",
			nosotros: "alcancemos",
			vosotros: "alcancéis",
			Uds: "alcancen",
		},
		Imperfect: {
			yo: "alcanzara",
			tú: "alcanzaras",
			Ud: "alcanzara",
			nosotros: "alcanzáramos",
			vosotros: "alcanzarais",
			Uds: "alcanzaran",
		},
		Imperfect2: {
			yo: "alcanzase",
			tú: "alcanzases",
			Ud: "alcanzase",
			nosotros: "alcanzásemos",
			vosotros: "alcanzaseis",
			Uds: "alcanzasen",
		},
		Future: {
			yo: "alcanzare",
			tú: "alcanzares",
			Ud: "alcanzare",
			nosotros: "alcanzáremos",
			vosotros: "alcanzareis",
			Uds: "alcanzaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "alcanza",
			Ud: "alcance",
			nosotros: "alcancemos",
			vosotros: "alcanzad",
			Uds: "alcancen",
		},
		Negative: {
			tú: "no alcances",
			Ud: "no alcance",
			nosotros: "no alcancemos",
			vosotros: "no alcancéis",
			Uds: "no alcancen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy alcanzando",
			tú: "estás alcanzando",
			Ud: "está alcanzando",
			nosotros: "estamos alcanzando",
			vosotros: "estáis alcanzando",
			Uds: "están alcanzando",
		},
		Preterite: {
			yo: "estuve alcanzando",
			tú: "estuviste alcanzando",
			Ud: "estuvo alcanzando",
			nosotros: "estuvimos alcanzando",
			vosotros: "estuvisteis alcanzando",
			Uds: "estuvieron alcanzando",
		},
		Imperfect: {
			Uds: "estaban alcanzando",
			yo: "estaba alcanzando",
			tú: "estabas alcanzando",
			Ud: "estaba alcanzando",
			nosotros: "estábamos alcanzando",
			vosotros: "estabais alcanzando",
		},
		Conditional: {
			yo: "estaría alcanzando",
			tú: "estarías alcanzando",
			Ud: "estaría alcanzando",
			nosotros: "estaríamos alcanzando",
			vosotros: "estaríais alcanzando",
			Uds: "estarían alcanzando",
		},
		Future: {
			yo: "estaré alcanzando",
			tú: "estarás alcanzando",
			Ud: "estará alcanzando",
			nosotros: "estaremos alcanzando",
			vosotros: "estaréis alcanzando",
			Uds: "estarán alcanzando",
		},
	},
	Perfect: {
		Present: {
			yo: "he alcanzado",
			tú: "has alcanzado",
			Ud: "ha alcanzado",
			nosotros: "hemos alcanzado",
			vosotros: "habéis alcanzado",
			Uds: "han alcanzado",
		},
		Preterite: {
			yo: "hube alcanzado",
			tú: "hubiste alcanzado",
			Ud: "hubo alcanzado",
			nosotros: "hubimos alcanzado",
			vosotros: "hubisteis alcanzado",
			Uds: "hubieron alcanzado",
		},
		Past: {
			yo: "había alcanzado",
			tú: "habías alcanzado",
			Ud: "había alcanzado",
			nosotros: "habíamos alcanzado",
			vosotros: "habíais alcanzado",
			Uds: "habían alcanzado",
		},
		Conditional: {
			yo: "habría alcanzado",
			tú: "habrías alcanzado",
			Ud: "habría alcanzado",
			nosotros: "habríamos alcanzado",
			vosotros: "habríais alcanzado",
			Uds: "habrían alcanzado",
		},
		Future: {
			yo: "habré alcanzado",
			tú: "habrás alcanzado",
			Ud: "habrá alcanzado",
			nosotros: "habremos alcanzado",
			vosotros: "habréis alcanzado",
			Uds: "habrán alcanzado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya alcanzado",
			tú: "hayas alcanzado",
			Ud: "haya alcanzado",
			nosotros: "hayamos alcanzado",
			vosotros: "hayáis alcanzado",
			Uds: "hayan alcanzado",
		},
		Past: {
			yo: "hubiera alcanzado",
			tú: "hubieras alcanzado",
			Ud: "hubiera alcanzado",
			nosotros: "hubiéramos alcanzado",
			vosotros: "hubierais alcanzado",
			Uds: "hubieran alcanzado",
		},
		Future: {
			yo: "hubiere alcanzado",
			tú: "hubieres alcanzado",
			Ud: "hubiere alcanzado",
			nosotros: "hubiéremos alcanzado",
			vosotros: "hubiereis alcanzado",
			Uds: "hubieren alcanzado",
		},
	},
}
