var alfombrar = {
	Indicative: {
		Present: {
			yo: "alfombro",
			tú: "alfombras",
			Ud: "alfombra",
			nosotros: "alfombramos",
			vosotros: "alfombráis",
			Uds: "alfombran",
		},
		Preterite: {
			yo: "alfombré",
			tú: "alfombraste",
			Ud: "alfombró",
			nosotros: "alfombramos",
			vosotros: "alfombrasteis",
			Uds: "alfombraron",
		},
		Imperfect: {
			yo: "alfombraba",
			tú: "alfombrabas",
			Ud: "alfombraba",
			nosotros: "alfombrábamos",
			vosotros: "alfombrabais",
			Uds: "alfombraban",
		},
		Conditional: {
			yo: "alfombraría",
			tú: "alfombrarías",
			Ud: "alfombraría",
			nosotros: "alfombraríamos",
			vosotros: "alfombraríais",
			Uds: "alfombrarían",
		},
		Future: {
			yo: "alfombraré",
			tú: "alfombrarás",
			Ud: "alfombrará",
			nosotros: "alfombraremos",
			vosotros: "alfombraréis",
			Uds: "alfombrarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "alfombre",
			tú: "alfombres",
			Ud: "alfombre",
			nosotros: "alfombremos",
			vosotros: "alfombréis",
			Uds: "alfombren",
		},
		Imperfect: {
			yo: "alfombrara",
			tú: "alfombraras",
			Ud: "alfombrara",
			nosotros: "alfombráramos",
			vosotros: "alfombrarais",
			Uds: "alfombraran",
		},
		Imperfect2: {
			yo: "alfombrase",
			tú: "alfombrases",
			Ud: "alfombrase",
			nosotros: "alfombrásemos",
			vosotros: "alfombraseis",
			Uds: "alfombrasen",
		},
		Future: {
			yo: "alfombrare",
			tú: "alfombrares",
			Ud: "alfombrare",
			nosotros: "alfombráremos",
			vosotros: "alfombrareis",
			Uds: "alfombraren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "alfombra",
			Ud: "alfombre",
			nosotros: "alfombremos",
			vosotros: "alfombrad",
			Uds: "alfombren",
		},
		Negative: {
			tú: "no alfombres",
			Ud: "no alfombre",
			nosotros: "no alfombremos",
			vosotros: "no alfombréis",
			Uds: "no alfombren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy alfombrando",
			tú: "estás alfombrando",
			Ud: "está alfombrando",
			nosotros: "estamos alfombrando",
			vosotros: "estáis alfombrando",
			Uds: "están alfombrando",
		},
		Preterite: {
			yo: "estuve alfombrando",
			tú: "estuviste alfombrando",
			Ud: "estuvo alfombrando",
			nosotros: "estuvimos alfombrando",
			vosotros: "estuvisteis alfombrando",
			Uds: "estuvieron alfombrando",
		},
		Imperfect: {
			Uds: "estaban alfombrando",
			yo: "estaba alfombrando",
			tú: "estabas alfombrando",
			Ud: "estaba alfombrando",
			nosotros: "estábamos alfombrando",
			vosotros: "estabais alfombrando",
		},
		Conditional: {
			yo: "estaría alfombrando",
			tú: "estarías alfombrando",
			Ud: "estaría alfombrando",
			nosotros: "estaríamos alfombrando",
			vosotros: "estaríais alfombrando",
			Uds: "estarían alfombrando",
		},
		Future: {
			yo: "estaré alfombrando",
			tú: "estarás alfombrando",
			Ud: "estará alfombrando",
			nosotros: "estaremos alfombrando",
			vosotros: "estaréis alfombrando",
			Uds: "estarán alfombrando",
		},
	},
	Perfect: {
		Present: {
			yo: "he alfombrado",
			tú: "has alfombrado",
			Ud: "ha alfombrado",
			nosotros: "hemos alfombrado",
			vosotros: "habéis alfombrado",
			Uds: "han alfombrado",
		},
		Preterite: {
			yo: "hube alfombrado",
			tú: "hubiste alfombrado",
			Ud: "hubo alfombrado",
			nosotros: "hubimos alfombrado",
			vosotros: "hubisteis alfombrado",
			Uds: "hubieron alfombrado",
		},
		Past: {
			yo: "había alfombrado",
			tú: "habías alfombrado",
			Ud: "había alfombrado",
			nosotros: "habíamos alfombrado",
			vosotros: "habíais alfombrado",
			Uds: "habían alfombrado",
		},
		Conditional: {
			yo: "habría alfombrado",
			tú: "habrías alfombrado",
			Ud: "habría alfombrado",
			nosotros: "habríamos alfombrado",
			vosotros: "habríais alfombrado",
			Uds: "habrían alfombrado",
		},
		Future: {
			yo: "habré alfombrado",
			tú: "habrás alfombrado",
			Ud: "habrá alfombrado",
			nosotros: "habremos alfombrado",
			vosotros: "habréis alfombrado",
			Uds: "habrán alfombrado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya alfombrado",
			tú: "hayas alfombrado",
			Ud: "haya alfombrado",
			nosotros: "hayamos alfombrado",
			vosotros: "hayáis alfombrado",
			Uds: "hayan alfombrado",
		},
		Past: {
			yo: "hubiera alfombrado",
			tú: "hubieras alfombrado",
			Ud: "hubiera alfombrado",
			nosotros: "hubiéramos alfombrado",
			vosotros: "hubierais alfombrado",
			Uds: "hubieran alfombrado",
		},
		Future: {
			yo: "hubiere alfombrado",
			tú: "hubieres alfombrado",
			Ud: "hubiere alfombrado",
			nosotros: "hubiéremos alfombrado",
			vosotros: "hubiereis alfombrado",
			Uds: "hubieren alfombrado",
		},
	},
}
