var alinear = {
	Indicative: {
		Present: {
			yo: "alineo",
			tú: "alineas",
			Ud: "alinea",
			nosotros: "alineamos",
			vosotros: "alineáis",
			Uds: "alinean",
		},
		Preterite: {
			yo: "alineé",
			tú: "alineaste",
			Ud: "alineó",
			nosotros: "alineamos",
			vosotros: "alineasteis",
			Uds: "alinearon",
		},
		Imperfect: {
			yo: "alineaba",
			tú: "alineabas",
			Ud: "alineaba",
			nosotros: "alineábamos",
			vosotros: "alineabais",
			Uds: "alineaban",
		},
		Conditional: {
			yo: "alinearía",
			tú: "alinearías",
			Ud: "alinearía",
			nosotros: "alinearíamos",
			vosotros: "alinearíais",
			Uds: "alinearían",
		},
		Future: {
			yo: "alinearé",
			tú: "alinearás",
			Ud: "alineará",
			nosotros: "alinearemos",
			vosotros: "alinearéis",
			Uds: "alinearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "alinee",
			tú: "alinees",
			Ud: "alinee",
			nosotros: "alineemos",
			vosotros: "alineéis",
			Uds: "alineen",
		},
		Imperfect: {
			yo: "alineara",
			tú: "alinearas",
			Ud: "alineara",
			nosotros: "alineáramos",
			vosotros: "alinearais",
			Uds: "alinearan",
		},
		Imperfect2: {
			yo: "alinease",
			tú: "alineases",
			Ud: "alinease",
			nosotros: "alineásemos",
			vosotros: "alineaseis",
			Uds: "alineasen",
		},
		Future: {
			yo: "alineare",
			tú: "alineares",
			Ud: "alineare",
			nosotros: "alineáremos",
			vosotros: "alineareis",
			Uds: "alinearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "alinea",
			Ud: "alinee",
			nosotros: "alineemos",
			vosotros: "alinead",
			Uds: "alineen",
		},
		Negative: {
			tú: "no alinees",
			Ud: "no alinee",
			nosotros: "no alineemos",
			vosotros: "no alineéis",
			Uds: "no alineen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy alineando",
			tú: "estás alineando",
			Ud: "está alineando",
			nosotros: "estamos alineando",
			vosotros: "estáis alineando",
			Uds: "están alineando",
		},
		Preterite: {
			yo: "estuve alineando",
			tú: "estuviste alineando",
			Ud: "estuvo alineando",
			nosotros: "estuvimos alineando",
			vosotros: "estuvisteis alineando",
			Uds: "estuvieron alineando",
		},
		Imperfect: {
			Uds: "estaban alineando",
			yo: "estaba alineando",
			tú: "estabas alineando",
			Ud: "estaba alineando",
			nosotros: "estábamos alineando",
			vosotros: "estabais alineando",
		},
		Conditional: {
			yo: "estaría alineando",
			tú: "estarías alineando",
			Ud: "estaría alineando",
			nosotros: "estaríamos alineando",
			vosotros: "estaríais alineando",
			Uds: "estarían alineando",
		},
		Future: {
			yo: "estaré alineando",
			tú: "estarás alineando",
			Ud: "estará alineando",
			nosotros: "estaremos alineando",
			vosotros: "estaréis alineando",
			Uds: "estarán alineando",
		},
	},
	Perfect: {
		Present: {
			yo: "he alineado",
			tú: "has alineado",
			Ud: "ha alineado",
			nosotros: "hemos alineado",
			vosotros: "habéis alineado",
			Uds: "han alineado",
		},
		Preterite: {
			yo: "hube alineado",
			tú: "hubiste alineado",
			Ud: "hubo alineado",
			nosotros: "hubimos alineado",
			vosotros: "hubisteis alineado",
			Uds: "hubieron alineado",
		},
		Past: {
			yo: "había alineado",
			tú: "habías alineado",
			Ud: "había alineado",
			nosotros: "habíamos alineado",
			vosotros: "habíais alineado",
			Uds: "habían alineado",
		},
		Conditional: {
			yo: "habría alineado",
			tú: "habrías alineado",
			Ud: "habría alineado",
			nosotros: "habríamos alineado",
			vosotros: "habríais alineado",
			Uds: "habrían alineado",
		},
		Future: {
			yo: "habré alineado",
			tú: "habrás alineado",
			Ud: "habrá alineado",
			nosotros: "habremos alineado",
			vosotros: "habréis alineado",
			Uds: "habrán alineado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya alineado",
			tú: "hayas alineado",
			Ud: "haya alineado",
			nosotros: "hayamos alineado",
			vosotros: "hayáis alineado",
			Uds: "hayan alineado",
		},
		Past: {
			yo: "hubiera alineado",
			tú: "hubieras alineado",
			Ud: "hubiera alineado",
			nosotros: "hubiéramos alineado",
			vosotros: "hubierais alineado",
			Uds: "hubieran alineado",
		},
		Future: {
			yo: "hubiere alineado",
			tú: "hubieres alineado",
			Ud: "hubiere alineado",
			nosotros: "hubiéremos alineado",
			vosotros: "hubiereis alineado",
			Uds: "hubieren alineado",
		},
	},
}
