var aliviar = {
	Indicative: {
		Present: {
			yo: "alivio",
			tú: "alivias",
			Ud: "alivia",
			nosotros: "aliviamos",
			vosotros: "aliviáis",
			Uds: "alivian",
		},
		Preterite: {
			yo: "alivié",
			tú: "aliviaste",
			Ud: "alivió",
			nosotros: "aliviamos",
			vosotros: "aliviasteis",
			Uds: "aliviaron",
		},
		Imperfect: {
			yo: "aliviaba",
			tú: "aliviabas",
			Ud: "aliviaba",
			nosotros: "aliviábamos",
			vosotros: "aliviabais",
			Uds: "aliviaban",
		},
		Conditional: {
			yo: "aliviaría",
			tú: "aliviarías",
			Ud: "aliviaría",
			nosotros: "aliviaríamos",
			vosotros: "aliviaríais",
			Uds: "aliviarían",
		},
		Future: {
			yo: "aliviaré",
			tú: "aliviarás",
			Ud: "aliviará",
			nosotros: "aliviaremos",
			vosotros: "aliviaréis",
			Uds: "aliviarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "alivie",
			tú: "alivies",
			Ud: "alivie",
			nosotros: "aliviemos",
			vosotros: "aliviéis",
			Uds: "alivien",
		},
		Imperfect: {
			yo: "aliviara",
			tú: "aliviaras",
			Ud: "aliviara",
			nosotros: "aliviáramos",
			vosotros: "aliviarais",
			Uds: "aliviaran",
		},
		Imperfect2: {
			yo: "aliviase",
			tú: "aliviases",
			Ud: "aliviase",
			nosotros: "aliviásemos",
			vosotros: "aliviaseis",
			Uds: "aliviasen",
		},
		Future: {
			yo: "aliviare",
			tú: "aliviares",
			Ud: "aliviare",
			nosotros: "aliviáremos",
			vosotros: "aliviareis",
			Uds: "aliviaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "alivia",
			Ud: "alivie",
			nosotros: "aliviemos",
			vosotros: "aliviad",
			Uds: "alivien",
		},
		Negative: {
			tú: "no alivies",
			Ud: "no alivie",
			nosotros: "no aliviemos",
			vosotros: "no aliviéis",
			Uds: "no alivien",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy aliviando",
			tú: "estás aliviando",
			Ud: "está aliviando",
			nosotros: "estamos aliviando",
			vosotros: "estáis aliviando",
			Uds: "están aliviando",
		},
		Preterite: {
			yo: "estuve aliviando",
			tú: "estuviste aliviando",
			Ud: "estuvo aliviando",
			nosotros: "estuvimos aliviando",
			vosotros: "estuvisteis aliviando",
			Uds: "estuvieron aliviando",
		},
		Imperfect: {
			Uds: "estaban aliviando",
			yo: "estaba aliviando",
			tú: "estabas aliviando",
			Ud: "estaba aliviando",
			nosotros: "estábamos aliviando",
			vosotros: "estabais aliviando",
		},
		Conditional: {
			yo: "estaría aliviando",
			tú: "estarías aliviando",
			Ud: "estaría aliviando",
			nosotros: "estaríamos aliviando",
			vosotros: "estaríais aliviando",
			Uds: "estarían aliviando",
		},
		Future: {
			yo: "estaré aliviando",
			tú: "estarás aliviando",
			Ud: "estará aliviando",
			nosotros: "estaremos aliviando",
			vosotros: "estaréis aliviando",
			Uds: "estarán aliviando",
		},
	},
	Perfect: {
		Present: {
			yo: "he aliviado",
			tú: "has aliviado",
			Ud: "ha aliviado",
			nosotros: "hemos aliviado",
			vosotros: "habéis aliviado",
			Uds: "han aliviado",
		},
		Preterite: {
			yo: "hube aliviado",
			tú: "hubiste aliviado",
			Ud: "hubo aliviado",
			nosotros: "hubimos aliviado",
			vosotros: "hubisteis aliviado",
			Uds: "hubieron aliviado",
		},
		Past: {
			yo: "había aliviado",
			tú: "habías aliviado",
			Ud: "había aliviado",
			nosotros: "habíamos aliviado",
			vosotros: "habíais aliviado",
			Uds: "habían aliviado",
		},
		Conditional: {
			yo: "habría aliviado",
			tú: "habrías aliviado",
			Ud: "habría aliviado",
			nosotros: "habríamos aliviado",
			vosotros: "habríais aliviado",
			Uds: "habrían aliviado",
		},
		Future: {
			yo: "habré aliviado",
			tú: "habrás aliviado",
			Ud: "habrá aliviado",
			nosotros: "habremos aliviado",
			vosotros: "habréis aliviado",
			Uds: "habrán aliviado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya aliviado",
			tú: "hayas aliviado",
			Ud: "haya aliviado",
			nosotros: "hayamos aliviado",
			vosotros: "hayáis aliviado",
			Uds: "hayan aliviado",
		},
		Past: {
			yo: "hubiera aliviado",
			tú: "hubieras aliviado",
			Ud: "hubiera aliviado",
			nosotros: "hubiéramos aliviado",
			vosotros: "hubierais aliviado",
			Uds: "hubieran aliviado",
		},
		Future: {
			yo: "hubiere aliviado",
			tú: "hubieres aliviado",
			Ud: "hubiere aliviado",
			nosotros: "hubiéremos aliviado",
			vosotros: "hubiereis aliviado",
			Uds: "hubieren aliviado",
		},
	},
}
