var allanar = {
	Indicative: {
		Present: {
			yo: "allano",
			tú: "allanas",
			Ud: "allana",
			nosotros: "allanamos",
			vosotros: "allanáis",
			Uds: "allanan",
		},
		Preterite: {
			yo: "allané",
			tú: "allanaste",
			Ud: "allanó",
			nosotros: "allanamos",
			vosotros: "allanasteis",
			Uds: "allanaron",
		},
		Imperfect: {
			yo: "allanaba",
			tú: "allanabas",
			Ud: "allanaba",
			nosotros: "allanábamos",
			vosotros: "allanabais",
			Uds: "allanaban",
		},
		Conditional: {
			yo: "allanaría",
			tú: "allanarías",
			Ud: "allanaría",
			nosotros: "allanaríamos",
			vosotros: "allanaríais",
			Uds: "allanarían",
		},
		Future: {
			yo: "allanaré",
			tú: "allanarás",
			Ud: "allanará",
			nosotros: "allanaremos",
			vosotros: "allanaréis",
			Uds: "allanarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "allane",
			tú: "allanes",
			Ud: "allane",
			nosotros: "allanemos",
			vosotros: "allanéis",
			Uds: "allanen",
		},
		Imperfect: {
			yo: "allanara",
			tú: "allanaras",
			Ud: "allanara",
			nosotros: "allanáramos",
			vosotros: "allanarais",
			Uds: "allanaran",
		},
		Imperfect2: {
			yo: "allanase",
			tú: "allanases",
			Ud: "allanase",
			nosotros: "allanásemos",
			vosotros: "allanaseis",
			Uds: "allanasen",
		},
		Future: {
			yo: "allanare",
			tú: "allanares",
			Ud: "allanare",
			nosotros: "allanáremos",
			vosotros: "allanareis",
			Uds: "allanaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "allana",
			Ud: "allane",
			nosotros: "allanemos",
			vosotros: "allanad",
			Uds: "allanen",
		},
		Negative: {
			tú: "no allanes",
			Ud: "no allane",
			nosotros: "no allanemos",
			vosotros: "no allanéis",
			Uds: "no allanen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy allanando",
			tú: "estás allanando",
			Ud: "está allanando",
			nosotros: "estamos allanando",
			vosotros: "estáis allanando",
			Uds: "están allanando",
		},
		Preterite: {
			yo: "estuve allanando",
			tú: "estuviste allanando",
			Ud: "estuvo allanando",
			nosotros: "estuvimos allanando",
			vosotros: "estuvisteis allanando",
			Uds: "estuvieron allanando",
		},
		Imperfect: {
			Uds: "estaban allanando",
			yo: "estaba allanando",
			tú: "estabas allanando",
			Ud: "estaba allanando",
			nosotros: "estábamos allanando",
			vosotros: "estabais allanando",
		},
		Conditional: {
			yo: "estaría allanando",
			tú: "estarías allanando",
			Ud: "estaría allanando",
			nosotros: "estaríamos allanando",
			vosotros: "estaríais allanando",
			Uds: "estarían allanando",
		},
		Future: {
			yo: "estaré allanando",
			tú: "estarás allanando",
			Ud: "estará allanando",
			nosotros: "estaremos allanando",
			vosotros: "estaréis allanando",
			Uds: "estarán allanando",
		},
	},
	Perfect: {
		Present: {
			yo: "he allanado",
			tú: "has allanado",
			Ud: "ha allanado",
			nosotros: "hemos allanado",
			vosotros: "habéis allanado",
			Uds: "han allanado",
		},
		Preterite: {
			yo: "hube allanado",
			tú: "hubiste allanado",
			Ud: "hubo allanado",
			nosotros: "hubimos allanado",
			vosotros: "hubisteis allanado",
			Uds: "hubieron allanado",
		},
		Past: {
			yo: "había allanado",
			tú: "habías allanado",
			Ud: "había allanado",
			nosotros: "habíamos allanado",
			vosotros: "habíais allanado",
			Uds: "habían allanado",
		},
		Conditional: {
			yo: "habría allanado",
			tú: "habrías allanado",
			Ud: "habría allanado",
			nosotros: "habríamos allanado",
			vosotros: "habríais allanado",
			Uds: "habrían allanado",
		},
		Future: {
			yo: "habré allanado",
			tú: "habrás allanado",
			Ud: "habrá allanado",
			nosotros: "habremos allanado",
			vosotros: "habréis allanado",
			Uds: "habrán allanado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya allanado",
			tú: "hayas allanado",
			Ud: "haya allanado",
			nosotros: "hayamos allanado",
			vosotros: "hayáis allanado",
			Uds: "hayan allanado",
		},
		Past: {
			yo: "hubiera allanado",
			tú: "hubieras allanado",
			Ud: "hubiera allanado",
			nosotros: "hubiéramos allanado",
			vosotros: "hubierais allanado",
			Uds: "hubieran allanado",
		},
		Future: {
			yo: "hubiere allanado",
			tú: "hubieres allanado",
			Ud: "hubiere allanado",
			nosotros: "hubiéremos allanado",
			vosotros: "hubiereis allanado",
			Uds: "hubieren allanado",
		},
	},
}
