var alojar = {
	Indicative: {
		Present: {
			yo: "alojo",
			tú: "alojas",
			Ud: "aloja",
			nosotros: "alojamos",
			vosotros: "alojáis",
			Uds: "alojan",
		},
		Preterite: {
			yo: "alojé",
			tú: "alojaste",
			Ud: "alojó",
			nosotros: "alojamos",
			vosotros: "alojasteis",
			Uds: "alojaron",
		},
		Imperfect: {
			yo: "alojaba",
			tú: "alojabas",
			Ud: "alojaba",
			nosotros: "alojábamos",
			vosotros: "alojabais",
			Uds: "alojaban",
		},
		Conditional: {
			yo: "alojaría",
			tú: "alojarías",
			Ud: "alojaría",
			nosotros: "alojaríamos",
			vosotros: "alojaríais",
			Uds: "alojarían",
		},
		Future: {
			yo: "alojaré",
			tú: "alojarás",
			Ud: "alojará",
			nosotros: "alojaremos",
			vosotros: "alojaréis",
			Uds: "alojarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "aloje",
			tú: "alojes",
			Ud: "aloje",
			nosotros: "alojemos",
			vosotros: "alojéis",
			Uds: "alojen",
		},
		Imperfect: {
			yo: "alojara",
			tú: "alojaras",
			Ud: "alojara",
			nosotros: "alojáramos",
			vosotros: "alojarais",
			Uds: "alojaran",
		},
		Imperfect2: {
			yo: "alojase",
			tú: "alojases",
			Ud: "alojase",
			nosotros: "alojásemos",
			vosotros: "alojaseis",
			Uds: "alojasen",
		},
		Future: {
			yo: "alojare",
			tú: "alojares",
			Ud: "alojare",
			nosotros: "alojáremos",
			vosotros: "alojareis",
			Uds: "alojaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "aloja",
			Ud: "aloje",
			nosotros: "alojemos",
			vosotros: "alojad",
			Uds: "alojen",
		},
		Negative: {
			tú: "no alojes",
			Ud: "no aloje",
			nosotros: "no alojemos",
			vosotros: "no alojéis",
			Uds: "no alojen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy alojando",
			tú: "estás alojando",
			Ud: "está alojando",
			nosotros: "estamos alojando",
			vosotros: "estáis alojando",
			Uds: "están alojando",
		},
		Preterite: {
			yo: "estuve alojando",
			tú: "estuviste alojando",
			Ud: "estuvo alojando",
			nosotros: "estuvimos alojando",
			vosotros: "estuvisteis alojando",
			Uds: "estuvieron alojando",
		},
		Imperfect: {
			Uds: "estaban alojando",
			yo: "estaba alojando",
			tú: "estabas alojando",
			Ud: "estaba alojando",
			nosotros: "estábamos alojando",
			vosotros: "estabais alojando",
		},
		Conditional: {
			yo: "estaría alojando",
			tú: "estarías alojando",
			Ud: "estaría alojando",
			nosotros: "estaríamos alojando",
			vosotros: "estaríais alojando",
			Uds: "estarían alojando",
		},
		Future: {
			yo: "estaré alojando",
			tú: "estarás alojando",
			Ud: "estará alojando",
			nosotros: "estaremos alojando",
			vosotros: "estaréis alojando",
			Uds: "estarán alojando",
		},
	},
	Perfect: {
		Present: {
			yo: "he alojado",
			tú: "has alojado",
			Ud: "ha alojado",
			nosotros: "hemos alojado",
			vosotros: "habéis alojado",
			Uds: "han alojado",
		},
		Preterite: {
			yo: "hube alojado",
			tú: "hubiste alojado",
			Ud: "hubo alojado",
			nosotros: "hubimos alojado",
			vosotros: "hubisteis alojado",
			Uds: "hubieron alojado",
		},
		Past: {
			yo: "había alojado",
			tú: "habías alojado",
			Ud: "había alojado",
			nosotros: "habíamos alojado",
			vosotros: "habíais alojado",
			Uds: "habían alojado",
		},
		Conditional: {
			yo: "habría alojado",
			tú: "habrías alojado",
			Ud: "habría alojado",
			nosotros: "habríamos alojado",
			vosotros: "habríais alojado",
			Uds: "habrían alojado",
		},
		Future: {
			yo: "habré alojado",
			tú: "habrás alojado",
			Ud: "habrá alojado",
			nosotros: "habremos alojado",
			vosotros: "habréis alojado",
			Uds: "habrán alojado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya alojado",
			tú: "hayas alojado",
			Ud: "haya alojado",
			nosotros: "hayamos alojado",
			vosotros: "hayáis alojado",
			Uds: "hayan alojado",
		},
		Past: {
			yo: "hubiera alojado",
			tú: "hubieras alojado",
			Ud: "hubiera alojado",
			nosotros: "hubiéramos alojado",
			vosotros: "hubierais alojado",
			Uds: "hubieran alojado",
		},
		Future: {
			yo: "hubiere alojado",
			tú: "hubieres alojado",
			Ud: "hubiere alojado",
			nosotros: "hubiéremos alojado",
			vosotros: "hubiereis alojado",
			Uds: "hubieren alojado",
		},
	},
}
