var aludir = {
	Indicative: {
		Present: {
			yo: "aludo",
			tú: "aludes",
			Ud: "alude",
			nosotros: "aludimos",
			vosotros: "aludís",
			Uds: "aluden",
		},
		Preterite: {
			yo: "aludí",
			tú: "aludiste",
			Ud: "aludió",
			nosotros: "aludimos",
			vosotros: "aludisteis",
			Uds: "aludieron",
		},
		Imperfect: {
			yo: "aludía",
			tú: "aludías",
			Ud: "aludía",
			nosotros: "aludíamos",
			vosotros: "aludíais",
			Uds: "aludían",
		},
		Conditional: {
			yo: "aludiría",
			tú: "aludirías",
			Ud: "aludiría",
			nosotros: "aludiríamos",
			vosotros: "aludiríais",
			Uds: "aludirían",
		},
		Future: {
			yo: "aludiré",
			tú: "aludirás",
			Ud: "aludirá",
			nosotros: "aludiremos",
			vosotros: "aludiréis",
			Uds: "aludirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "aluda",
			tú: "aludas",
			Ud: "aluda",
			nosotros: "aludamos",
			vosotros: "aludáis",
			Uds: "aludan",
		},
		Imperfect: {
			yo: "aludiera",
			tú: "aludieras",
			Ud: "aludiera",
			nosotros: "aludiéramos",
			vosotros: "aludierais",
			Uds: "aludieran",
		},
		Imperfect2: {
			yo: "aludiese",
			tú: "aludieses",
			Ud: "aludiese",
			nosotros: "aludiésemos",
			vosotros: "aludieseis",
			Uds: "aludiesen",
		},
		Future: {
			yo: "aludiere",
			tú: "aludieres",
			Ud: "aludiere",
			nosotros: "aludiéremos",
			vosotros: "aludiereis",
			Uds: "aludieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "alude",
			Ud: "aluda",
			nosotros: "aludamos",
			vosotros: "aludid",
			Uds: "aludan",
		},
		Negative: {
			tú: "no aludas",
			Ud: "no aluda",
			nosotros: "no aludamos",
			vosotros: "no aludáis",
			Uds: "no aludan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy aludiendo",
			tú: "estás aludiendo",
			Ud: "está aludiendo",
			nosotros: "estamos aludiendo",
			vosotros: "estáis aludiendo",
			Uds: "están aludiendo",
		},
		Preterite: {
			yo: "estuve aludiendo",
			tú: "estuviste aludiendo",
			Ud: "estuvo aludiendo",
			nosotros: "estuvimos aludiendo",
			vosotros: "estuvisteis aludiendo",
			Uds: "estuvieron aludiendo",
		},
		Imperfect: {
			Uds: "estaban aludiendo",
			yo: "estaba aludiendo",
			tú: "estabas aludiendo",
			Ud: "estaba aludiendo",
			nosotros: "estábamos aludiendo",
			vosotros: "estabais aludiendo",
		},
		Conditional: {
			yo: "estaría aludiendo",
			tú: "estarías aludiendo",
			Ud: "estaría aludiendo",
			nosotros: "estaríamos aludiendo",
			vosotros: "estaríais aludiendo",
			Uds: "estarían aludiendo",
		},
		Future: {
			yo: "estaré aludiendo",
			tú: "estarás aludiendo",
			Ud: "estará aludiendo",
			nosotros: "estaremos aludiendo",
			vosotros: "estaréis aludiendo",
			Uds: "estarán aludiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he aludido",
			tú: "has aludido",
			Ud: "ha aludido",
			nosotros: "hemos aludido",
			vosotros: "habéis aludido",
			Uds: "han aludido",
		},
		Preterite: {
			yo: "hube aludido",
			tú: "hubiste aludido",
			Ud: "hubo aludido",
			nosotros: "hubimos aludido",
			vosotros: "hubisteis aludido",
			Uds: "hubieron aludido",
		},
		Past: {
			yo: "había aludido",
			tú: "habías aludido",
			Ud: "había aludido",
			nosotros: "habíamos aludido",
			vosotros: "habíais aludido",
			Uds: "habían aludido",
		},
		Conditional: {
			yo: "habría aludido",
			tú: "habrías aludido",
			Ud: "habría aludido",
			nosotros: "habríamos aludido",
			vosotros: "habríais aludido",
			Uds: "habrían aludido",
		},
		Future: {
			yo: "habré aludido",
			tú: "habrás aludido",
			Ud: "habrá aludido",
			nosotros: "habremos aludido",
			vosotros: "habréis aludido",
			Uds: "habrán aludido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya aludido",
			tú: "hayas aludido",
			Ud: "haya aludido",
			nosotros: "hayamos aludido",
			vosotros: "hayáis aludido",
			Uds: "hayan aludido",
		},
		Past: {
			yo: "hubiera aludido",
			tú: "hubieras aludido",
			Ud: "hubiera aludido",
			nosotros: "hubiéramos aludido",
			vosotros: "hubierais aludido",
			Uds: "hubieran aludido",
		},
		Future: {
			yo: "hubiere aludido",
			tú: "hubieres aludido",
			Ud: "hubiere aludido",
			nosotros: "hubiéremos aludido",
			vosotros: "hubiereis aludido",
			Uds: "hubieren aludido",
		},
	},
}
