var alzar = {
	Indicative: {
		Present: {
			yo: "alzo",
			tú: "alzas",
			Ud: "alza",
			nosotros: "alzamos",
			vosotros: "alzáis",
			Uds: "alzan",
		},
		Preterite: {
			yo: "alcé",
			tú: "alzaste",
			Ud: "alzó",
			nosotros: "alzamos",
			vosotros: "alzasteis",
			Uds: "alzaron",
		},
		Imperfect: {
			yo: "alzaba",
			tú: "alzabas",
			Ud: "alzaba",
			nosotros: "alzábamos",
			vosotros: "alzabais",
			Uds: "alzaban",
		},
		Conditional: {
			yo: "alzaría",
			tú: "alzarías",
			Ud: "alzaría",
			nosotros: "alzaríamos",
			vosotros: "alzaríais",
			Uds: "alzarían",
		},
		Future: {
			yo: "alzaré",
			tú: "alzarás",
			Ud: "alzará",
			nosotros: "alzaremos",
			vosotros: "alzaréis",
			Uds: "alzarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "alce",
			tú: "alces",
			Ud: "alce",
			nosotros: "alcemos",
			vosotros: "alcéis",
			Uds: "alcen",
		},
		Imperfect: {
			yo: "alzara",
			tú: "alzaras",
			Ud: "alzara",
			nosotros: "alzáramos",
			vosotros: "alzarais",
			Uds: "alzaran",
		},
		Imperfect2: {
			yo: "alzase",
			tú: "alzases",
			Ud: "alzase",
			nosotros: "alzásemos",
			vosotros: "alzaseis",
			Uds: "alzasen",
		},
		Future: {
			yo: "alzare",
			tú: "alzares",
			Ud: "alzare",
			nosotros: "alzáremos",
			vosotros: "alzareis",
			Uds: "alzaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "alza",
			Ud: "alce",
			nosotros: "alcemos",
			vosotros: "alzad",
			Uds: "alcen",
		},
		Negative: {
			tú: "no alces",
			Ud: "no alce",
			nosotros: "no alcemos",
			vosotros: "no alcéis",
			Uds: "no alcen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy alzando",
			tú: "estás alzando",
			Ud: "está alzando",
			nosotros: "estamos alzando",
			vosotros: "estáis alzando",
			Uds: "están alzando",
		},
		Preterite: {
			yo: "estuve alzando",
			tú: "estuviste alzando",
			Ud: "estuvo alzando",
			nosotros: "estuvimos alzando",
			vosotros: "estuvisteis alzando",
			Uds: "estuvieron alzando",
		},
		Imperfect: {
			Uds: "estaban alzando",
			yo: "estaba alzando",
			tú: "estabas alzando",
			Ud: "estaba alzando",
			nosotros: "estábamos alzando",
			vosotros: "estabais alzando",
		},
		Conditional: {
			yo: "estaría alzando",
			tú: "estarías alzando",
			Ud: "estaría alzando",
			nosotros: "estaríamos alzando",
			vosotros: "estaríais alzando",
			Uds: "estarían alzando",
		},
		Future: {
			yo: "estaré alzando",
			tú: "estarás alzando",
			Ud: "estará alzando",
			nosotros: "estaremos alzando",
			vosotros: "estaréis alzando",
			Uds: "estarán alzando",
		},
	},
	Perfect: {
		Present: {
			yo: "he alzado",
			tú: "has alzado",
			Ud: "ha alzado",
			nosotros: "hemos alzado",
			vosotros: "habéis alzado",
			Uds: "han alzado",
		},
		Preterite: {
			yo: "hube alzado",
			tú: "hubiste alzado",
			Ud: "hubo alzado",
			nosotros: "hubimos alzado",
			vosotros: "hubisteis alzado",
			Uds: "hubieron alzado",
		},
		Past: {
			yo: "había alzado",
			tú: "habías alzado",
			Ud: "había alzado",
			nosotros: "habíamos alzado",
			vosotros: "habíais alzado",
			Uds: "habían alzado",
		},
		Conditional: {
			yo: "habría alzado",
			tú: "habrías alzado",
			Ud: "habría alzado",
			nosotros: "habríamos alzado",
			vosotros: "habríais alzado",
			Uds: "habrían alzado",
		},
		Future: {
			yo: "habré alzado",
			tú: "habrás alzado",
			Ud: "habrá alzado",
			nosotros: "habremos alzado",
			vosotros: "habréis alzado",
			Uds: "habrán alzado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya alzado",
			tú: "hayas alzado",
			Ud: "haya alzado",
			nosotros: "hayamos alzado",
			vosotros: "hayáis alzado",
			Uds: "hayan alzado",
		},
		Past: {
			yo: "hubiera alzado",
			tú: "hubieras alzado",
			Ud: "hubiera alzado",
			nosotros: "hubiéramos alzado",
			vosotros: "hubierais alzado",
			Uds: "hubieran alzado",
		},
		Future: {
			yo: "hubiere alzado",
			tú: "hubieres alzado",
			Ud: "hubiere alzado",
			nosotros: "hubiéremos alzado",
			vosotros: "hubiereis alzado",
			Uds: "hubieren alzado",
		},
	},
}
