var amamantar = {
	Indicative: {
		Present: {
			yo: "amamanto",
			tú: "amamantas",
			Ud: "amamanta",
			nosotros: "amamantamos",
			vosotros: "amamantáis",
			Uds: "amamantan",
		},
		Preterite: {
			yo: "amamanté",
			tú: "amamantaste",
			Ud: "amamantó",
			nosotros: "amamantamos",
			vosotros: "amamantasteis",
			Uds: "amamantaron",
		},
		Imperfect: {
			yo: "amamantaba",
			tú: "amamantabas",
			Ud: "amamantaba",
			nosotros: "amamantábamos",
			vosotros: "amamantabais",
			Uds: "amamantaban",
		},
		Conditional: {
			yo: "amamantaría",
			tú: "amamantarías",
			Ud: "amamantaría",
			nosotros: "amamantaríamos",
			vosotros: "amamantaríais",
			Uds: "amamantarían",
		},
		Future: {
			yo: "amamantaré",
			tú: "amamantarás",
			Ud: "amamantará",
			nosotros: "amamantaremos",
			vosotros: "amamantaréis",
			Uds: "amamantarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "amamante",
			tú: "amamantes",
			Ud: "amamante",
			nosotros: "amamantemos",
			vosotros: "amamantéis",
			Uds: "amamanten",
		},
		Imperfect: {
			yo: "amamantara",
			tú: "amamantaras",
			Ud: "amamantara",
			nosotros: "amamantáramos",
			vosotros: "amamantarais",
			Uds: "amamantaran",
		},
		Imperfect2: {
			yo: "amamantase",
			tú: "amamantases",
			Ud: "amamantase",
			nosotros: "amamantásemos",
			vosotros: "amamantaseis",
			Uds: "amamantasen",
		},
		Future: {
			yo: "amamantare",
			tú: "amamantares",
			Ud: "amamantare",
			nosotros: "amamantáremos",
			vosotros: "amamantareis",
			Uds: "amamantaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "amamanta",
			Ud: "amamante",
			nosotros: "amamantemos",
			vosotros: "amamantad",
			Uds: "amamanten",
		},
		Negative: {
			tú: "no amamantes",
			Ud: "no amamante",
			nosotros: "no amamantemos",
			vosotros: "no amamantéis",
			Uds: "no amamanten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy amamantando",
			tú: "estás amamantando",
			Ud: "está amamantando",
			nosotros: "estamos amamantando",
			vosotros: "estáis amamantando",
			Uds: "están amamantando",
		},
		Preterite: {
			yo: "estuve amamantando",
			tú: "estuviste amamantando",
			Ud: "estuvo amamantando",
			nosotros: "estuvimos amamantando",
			vosotros: "estuvisteis amamantando",
			Uds: "estuvieron amamantando",
		},
		Imperfect: {
			Uds: "estaban amamantando",
			yo: "estaba amamantando",
			tú: "estabas amamantando",
			Ud: "estaba amamantando",
			nosotros: "estábamos amamantando",
			vosotros: "estabais amamantando",
		},
		Conditional: {
			yo: "estaría amamantando",
			tú: "estarías amamantando",
			Ud: "estaría amamantando",
			nosotros: "estaríamos amamantando",
			vosotros: "estaríais amamantando",
			Uds: "estarían amamantando",
		},
		Future: {
			yo: "estaré amamantando",
			tú: "estarás amamantando",
			Ud: "estará amamantando",
			nosotros: "estaremos amamantando",
			vosotros: "estaréis amamantando",
			Uds: "estarán amamantando",
		},
	},
	Perfect: {
		Present: {
			yo: "he amamantado",
			tú: "has amamantado",
			Ud: "ha amamantado",
			nosotros: "hemos amamantado",
			vosotros: "habéis amamantado",
			Uds: "han amamantado",
		},
		Preterite: {
			yo: "hube amamantado",
			tú: "hubiste amamantado",
			Ud: "hubo amamantado",
			nosotros: "hubimos amamantado",
			vosotros: "hubisteis amamantado",
			Uds: "hubieron amamantado",
		},
		Past: {
			yo: "había amamantado",
			tú: "habías amamantado",
			Ud: "había amamantado",
			nosotros: "habíamos amamantado",
			vosotros: "habíais amamantado",
			Uds: "habían amamantado",
		},
		Conditional: {
			yo: "habría amamantado",
			tú: "habrías amamantado",
			Ud: "habría amamantado",
			nosotros: "habríamos amamantado",
			vosotros: "habríais amamantado",
			Uds: "habrían amamantado",
		},
		Future: {
			yo: "habré amamantado",
			tú: "habrás amamantado",
			Ud: "habrá amamantado",
			nosotros: "habremos amamantado",
			vosotros: "habréis amamantado",
			Uds: "habrán amamantado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya amamantado",
			tú: "hayas amamantado",
			Ud: "haya amamantado",
			nosotros: "hayamos amamantado",
			vosotros: "hayáis amamantado",
			Uds: "hayan amamantado",
		},
		Past: {
			yo: "hubiera amamantado",
			tú: "hubieras amamantado",
			Ud: "hubiera amamantado",
			nosotros: "hubiéramos amamantado",
			vosotros: "hubierais amamantado",
			Uds: "hubieran amamantado",
		},
		Future: {
			yo: "hubiere amamantado",
			tú: "hubieres amamantado",
			Ud: "hubiere amamantado",
			nosotros: "hubiéremos amamantado",
			vosotros: "hubiereis amamantado",
			Uds: "hubieren amamantado",
		},
	},
}
