var amar = {
	Indicative: {
		Present: {
			yo: "amo",
			tú: "amas",
			Ud: "ama",
			nosotros: "amamos",
			vosotros: "amáis",
			Uds: "aman",
		},
		Preterite: {
			yo: "amé",
			tú: "amaste",
			Ud: "amó",
			nosotros: "amamos",
			vosotros: "amasteis",
			Uds: "amaron",
		},
		Imperfect: {
			yo: "amaba",
			tú: "amabas",
			Ud: "amaba",
			nosotros: "amábamos",
			vosotros: "amabais",
			Uds: "amaban",
		},
		Conditional: {
			yo: "amaría",
			tú: "amarías",
			Ud: "amaría",
			nosotros: "amaríamos",
			vosotros: "amaríais",
			Uds: "amarían",
		},
		Future: {
			yo: "amaré",
			tú: "amarás",
			Ud: "amará",
			nosotros: "amaremos",
			vosotros: "amaréis",
			Uds: "amarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "ame",
			tú: "ames",
			Ud: "ame",
			nosotros: "amemos",
			vosotros: "améis",
			Uds: "amen",
		},
		Imperfect: {
			yo: "amara",
			tú: "amaras",
			Ud: "amara",
			nosotros: "amáramos",
			vosotros: "amarais",
			Uds: "amaran",
		},
		Imperfect2: {
			yo: "amase",
			tú: "amases",
			Ud: "amase",
			nosotros: "amásemos",
			vosotros: "amaseis",
			Uds: "amasen",
		},
		Future: {
			yo: "amare",
			tú: "amares",
			Ud: "amare",
			nosotros: "amáremos",
			vosotros: "amareis",
			Uds: "amaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "ama",
			Ud: "ame",
			nosotros: "amemos",
			vosotros: "amad",
			Uds: "amen",
		},
		Negative: {
			tú: "no ames",
			Ud: "no ame",
			nosotros: "no amemos",
			vosotros: "no améis",
			Uds: "no amen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy amando",
			tú: "estás amando",
			Ud: "está amando",
			nosotros: "estamos amando",
			vosotros: "estáis amando",
			Uds: "están amando",
		},
		Preterite: {
			yo: "estuve amando",
			tú: "estuviste amando",
			Ud: "estuvo amando",
			nosotros: "estuvimos amando",
			vosotros: "estuvisteis amando",
			Uds: "estuvieron amando",
		},
		Imperfect: {
			Uds: "estaban amando",
			yo: "estaba amando",
			tú: "estabas amando",
			Ud: "estaba amando",
			nosotros: "estábamos amando",
			vosotros: "estabais amando",
		},
		Conditional: {
			yo: "estaría amando",
			tú: "estarías amando",
			Ud: "estaría amando",
			nosotros: "estaríamos amando",
			vosotros: "estaríais amando",
			Uds: "estarían amando",
		},
		Future: {
			yo: "estaré amando",
			tú: "estarás amando",
			Ud: "estará amando",
			nosotros: "estaremos amando",
			vosotros: "estaréis amando",
			Uds: "estarán amando",
		},
	},
	Perfect: {
		Present: {
			yo: "he amado",
			tú: "has amado",
			Ud: "ha amado",
			nosotros: "hemos amado",
			vosotros: "habéis amado",
			Uds: "han amado",
		},
		Preterite: {
			yo: "hube amado",
			tú: "hubiste amado",
			Ud: "hubo amado",
			nosotros: "hubimos amado",
			vosotros: "hubisteis amado",
			Uds: "hubieron amado",
		},
		Past: {
			yo: "había amado",
			tú: "habías amado",
			Ud: "había amado",
			nosotros: "habíamos amado",
			vosotros: "habíais amado",
			Uds: "habían amado",
		},
		Conditional: {
			yo: "habría amado",
			tú: "habrías amado",
			Ud: "habría amado",
			nosotros: "habríamos amado",
			vosotros: "habríais amado",
			Uds: "habrían amado",
		},
		Future: {
			yo: "habré amado",
			tú: "habrás amado",
			Ud: "habrá amado",
			nosotros: "habremos amado",
			vosotros: "habréis amado",
			Uds: "habrán amado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya amado",
			tú: "hayas amado",
			Ud: "haya amado",
			nosotros: "hayamos amado",
			vosotros: "hayáis amado",
			Uds: "hayan amado",
		},
		Past: {
			yo: "hubiera amado",
			tú: "hubieras amado",
			Ud: "hubiera amado",
			nosotros: "hubiéramos amado",
			vosotros: "hubierais amado",
			Uds: "hubieran amado",
		},
		Future: {
			yo: "hubiere amado",
			tú: "hubieres amado",
			Ud: "hubiere amado",
			nosotros: "hubiéremos amado",
			vosotros: "hubiereis amado",
			Uds: "hubieren amado",
		},
	},
}
