var analizar = {
	Indicative: {
		Present: {
			yo: "analizo",
			tú: "analizas",
			Ud: "analiza",
			nosotros: "analizamos",
			vosotros: "analizáis",
			Uds: "analizan",
		},
		Preterite: {
			yo: "analicé",
			tú: "analizaste",
			Ud: "analizó",
			nosotros: "analizamos",
			vosotros: "analizasteis",
			Uds: "analizaron",
		},
		Imperfect: {
			yo: "analizaba",
			tú: "analizabas",
			Ud: "analizaba",
			nosotros: "analizábamos",
			vosotros: "analizabais",
			Uds: "analizaban",
		},
		Conditional: {
			yo: "analizaría",
			tú: "analizarías",
			Ud: "analizaría",
			nosotros: "analizaríamos",
			vosotros: "analizaríais",
			Uds: "analizarían",
		},
		Future: {
			yo: "analizaré",
			tú: "analizarás",
			Ud: "analizará",
			nosotros: "analizaremos",
			vosotros: "analizaréis",
			Uds: "analizarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "analice",
			tú: "analices",
			Ud: "analice",
			nosotros: "analicemos",
			vosotros: "analicéis",
			Uds: "analicen",
		},
		Imperfect: {
			yo: "analizara",
			tú: "analizaras",
			Ud: "analizara",
			nosotros: "analizáramos",
			vosotros: "analizarais",
			Uds: "analizaran",
		},
		Imperfect2: {
			yo: "analizase",
			tú: "analizases",
			Ud: "analizase",
			nosotros: "analizásemos",
			vosotros: "analizaseis",
			Uds: "analizasen",
		},
		Future: {
			yo: "analizare",
			tú: "analizares",
			Ud: "analizare",
			nosotros: "analizáremos",
			vosotros: "analizareis",
			Uds: "analizaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "analiza",
			Ud: "analice",
			nosotros: "analicemos",
			vosotros: "analizad",
			Uds: "analicen",
		},
		Negative: {
			tú: "no analices",
			Ud: "no analice",
			nosotros: "no analicemos",
			vosotros: "no analicéis",
			Uds: "no analicen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy analizando",
			tú: "estás analizando",
			Ud: "está analizando",
			nosotros: "estamos analizando",
			vosotros: "estáis analizando",
			Uds: "están analizando",
		},
		Preterite: {
			yo: "estuve analizando",
			tú: "estuviste analizando",
			Ud: "estuvo analizando",
			nosotros: "estuvimos analizando",
			vosotros: "estuvisteis analizando",
			Uds: "estuvieron analizando",
		},
		Imperfect: {
			Uds: "estaban analizando",
			yo: "estaba analizando",
			tú: "estabas analizando",
			Ud: "estaba analizando",
			nosotros: "estábamos analizando",
			vosotros: "estabais analizando",
		},
		Conditional: {
			yo: "estaría analizando",
			tú: "estarías analizando",
			Ud: "estaría analizando",
			nosotros: "estaríamos analizando",
			vosotros: "estaríais analizando",
			Uds: "estarían analizando",
		},
		Future: {
			yo: "estaré analizando",
			tú: "estarás analizando",
			Ud: "estará analizando",
			nosotros: "estaremos analizando",
			vosotros: "estaréis analizando",
			Uds: "estarán analizando",
		},
	},
	Perfect: {
		Present: {
			yo: "he analizado",
			tú: "has analizado",
			Ud: "ha analizado",
			nosotros: "hemos analizado",
			vosotros: "habéis analizado",
			Uds: "han analizado",
		},
		Preterite: {
			yo: "hube analizado",
			tú: "hubiste analizado",
			Ud: "hubo analizado",
			nosotros: "hubimos analizado",
			vosotros: "hubisteis analizado",
			Uds: "hubieron analizado",
		},
		Past: {
			yo: "había analizado",
			tú: "habías analizado",
			Ud: "había analizado",
			nosotros: "habíamos analizado",
			vosotros: "habíais analizado",
			Uds: "habían analizado",
		},
		Conditional: {
			yo: "habría analizado",
			tú: "habrías analizado",
			Ud: "habría analizado",
			nosotros: "habríamos analizado",
			vosotros: "habríais analizado",
			Uds: "habrían analizado",
		},
		Future: {
			yo: "habré analizado",
			tú: "habrás analizado",
			Ud: "habrá analizado",
			nosotros: "habremos analizado",
			vosotros: "habréis analizado",
			Uds: "habrán analizado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya analizado",
			tú: "hayas analizado",
			Ud: "haya analizado",
			nosotros: "hayamos analizado",
			vosotros: "hayáis analizado",
			Uds: "hayan analizado",
		},
		Past: {
			yo: "hubiera analizado",
			tú: "hubieras analizado",
			Ud: "hubiera analizado",
			nosotros: "hubiéramos analizado",
			vosotros: "hubierais analizado",
			Uds: "hubieran analizado",
		},
		Future: {
			yo: "hubiere analizado",
			tú: "hubieres analizado",
			Ud: "hubiere analizado",
			nosotros: "hubiéremos analizado",
			vosotros: "hubiereis analizado",
			Uds: "hubieren analizado",
		},
	},
}
