var anhelar = {
	Indicative: {
		Present: {
			yo: "anhelo",
			tú: "anhelas",
			Ud: "anhela",
			nosotros: "anhelamos",
			vosotros: "anheláis",
			Uds: "anhelan",
		},
		Preterite: {
			yo: "anhelé",
			tú: "anhelaste",
			Ud: "anheló",
			nosotros: "anhelamos",
			vosotros: "anhelasteis",
			Uds: "anhelaron",
		},
		Imperfect: {
			yo: "anhelaba",
			tú: "anhelabas",
			Ud: "anhelaba",
			nosotros: "anhelábamos",
			vosotros: "anhelabais",
			Uds: "anhelaban",
		},
		Conditional: {
			yo: "anhelaría",
			tú: "anhelarías",
			Ud: "anhelaría",
			nosotros: "anhelaríamos",
			vosotros: "anhelaríais",
			Uds: "anhelarían",
		},
		Future: {
			yo: "anhelaré",
			tú: "anhelarás",
			Ud: "anhelará",
			nosotros: "anhelaremos",
			vosotros: "anhelaréis",
			Uds: "anhelarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "anhele",
			tú: "anheles",
			Ud: "anhele",
			nosotros: "anhelemos",
			vosotros: "anheléis",
			Uds: "anhelen",
		},
		Imperfect: {
			yo: "anhelara",
			tú: "anhelaras",
			Ud: "anhelara",
			nosotros: "anheláramos",
			vosotros: "anhelarais",
			Uds: "anhelaran",
		},
		Imperfect2: {
			yo: "anhelase",
			tú: "anhelases",
			Ud: "anhelase",
			nosotros: "anhelásemos",
			vosotros: "anhelaseis",
			Uds: "anhelasen",
		},
		Future: {
			yo: "anhelare",
			tú: "anhelares",
			Ud: "anhelare",
			nosotros: "anheláremos",
			vosotros: "anhelareis",
			Uds: "anhelaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "anhela",
			Ud: "anhele",
			nosotros: "anhelemos",
			vosotros: "anhelad",
			Uds: "anhelen",
		},
		Negative: {
			tú: "no anheles",
			Ud: "no anhele",
			nosotros: "no anhelemos",
			vosotros: "no anheléis",
			Uds: "no anhelen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy anhelando",
			tú: "estás anhelando",
			Ud: "está anhelando",
			nosotros: "estamos anhelando",
			vosotros: "estáis anhelando",
			Uds: "están anhelando",
		},
		Preterite: {
			yo: "estuve anhelando",
			tú: "estuviste anhelando",
			Ud: "estuvo anhelando",
			nosotros: "estuvimos anhelando",
			vosotros: "estuvisteis anhelando",
			Uds: "estuvieron anhelando",
		},
		Imperfect: {
			Uds: "estaban anhelando",
			yo: "estaba anhelando",
			tú: "estabas anhelando",
			Ud: "estaba anhelando",
			nosotros: "estábamos anhelando",
			vosotros: "estabais anhelando",
		},
		Conditional: {
			yo: "estaría anhelando",
			tú: "estarías anhelando",
			Ud: "estaría anhelando",
			nosotros: "estaríamos anhelando",
			vosotros: "estaríais anhelando",
			Uds: "estarían anhelando",
		},
		Future: {
			yo: "estaré anhelando",
			tú: "estarás anhelando",
			Ud: "estará anhelando",
			nosotros: "estaremos anhelando",
			vosotros: "estaréis anhelando",
			Uds: "estarán anhelando",
		},
	},
	Perfect: {
		Present: {
			yo: "he anhelado",
			tú: "has anhelado",
			Ud: "ha anhelado",
			nosotros: "hemos anhelado",
			vosotros: "habéis anhelado",
			Uds: "han anhelado",
		},
		Preterite: {
			yo: "hube anhelado",
			tú: "hubiste anhelado",
			Ud: "hubo anhelado",
			nosotros: "hubimos anhelado",
			vosotros: "hubisteis anhelado",
			Uds: "hubieron anhelado",
		},
		Past: {
			yo: "había anhelado",
			tú: "habías anhelado",
			Ud: "había anhelado",
			nosotros: "habíamos anhelado",
			vosotros: "habíais anhelado",
			Uds: "habían anhelado",
		},
		Conditional: {
			yo: "habría anhelado",
			tú: "habrías anhelado",
			Ud: "habría anhelado",
			nosotros: "habríamos anhelado",
			vosotros: "habríais anhelado",
			Uds: "habrían anhelado",
		},
		Future: {
			yo: "habré anhelado",
			tú: "habrás anhelado",
			Ud: "habrá anhelado",
			nosotros: "habremos anhelado",
			vosotros: "habréis anhelado",
			Uds: "habrán anhelado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya anhelado",
			tú: "hayas anhelado",
			Ud: "haya anhelado",
			nosotros: "hayamos anhelado",
			vosotros: "hayáis anhelado",
			Uds: "hayan anhelado",
		},
		Past: {
			yo: "hubiera anhelado",
			tú: "hubieras anhelado",
			Ud: "hubiera anhelado",
			nosotros: "hubiéramos anhelado",
			vosotros: "hubierais anhelado",
			Uds: "hubieran anhelado",
		},
		Future: {
			yo: "hubiere anhelado",
			tú: "hubieres anhelado",
			Ud: "hubiere anhelado",
			nosotros: "hubiéremos anhelado",
			vosotros: "hubiereis anhelado",
			Uds: "hubieren anhelado",
		},
	},
}
