var animar = {
	Indicative: {
		Present: {
			yo: "animo",
			tú: "animas",
			Ud: "anima",
			nosotros: "animamos",
			vosotros: "animáis",
			Uds: "animan",
		},
		Preterite: {
			yo: "animé",
			tú: "animaste",
			Ud: "animó",
			nosotros: "animamos",
			vosotros: "animasteis",
			Uds: "animaron",
		},
		Imperfect: {
			yo: "animaba",
			tú: "animabas",
			Ud: "animaba",
			nosotros: "animábamos",
			vosotros: "animabais",
			Uds: "animaban",
		},
		Conditional: {
			yo: "animaría",
			tú: "animarías",
			Ud: "animaría",
			nosotros: "animaríamos",
			vosotros: "animaríais",
			Uds: "animarían",
		},
		Future: {
			yo: "animaré",
			tú: "animarás",
			Ud: "animará",
			nosotros: "animaremos",
			vosotros: "animaréis",
			Uds: "animarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "anime",
			tú: "animes",
			Ud: "anime",
			nosotros: "animemos",
			vosotros: "animéis",
			Uds: "animen",
		},
		Imperfect: {
			yo: "animara",
			tú: "animaras",
			Ud: "animara",
			nosotros: "animáramos",
			vosotros: "animarais",
			Uds: "animaran",
		},
		Imperfect2: {
			yo: "animase",
			tú: "animases",
			Ud: "animase",
			nosotros: "animásemos",
			vosotros: "animaseis",
			Uds: "animasen",
		},
		Future: {
			yo: "animare",
			tú: "animares",
			Ud: "animare",
			nosotros: "animáremos",
			vosotros: "animareis",
			Uds: "animaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "anima",
			Ud: "anime",
			nosotros: "animemos",
			vosotros: "animad",
			Uds: "animen",
		},
		Negative: {
			tú: "no animes",
			Ud: "no anime",
			nosotros: "no animemos",
			vosotros: "no animéis",
			Uds: "no animen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy animando",
			tú: "estás animando",
			Ud: "está animando",
			nosotros: "estamos animando",
			vosotros: "estáis animando",
			Uds: "están animando",
		},
		Preterite: {
			yo: "estuve animando",
			tú: "estuviste animando",
			Ud: "estuvo animando",
			nosotros: "estuvimos animando",
			vosotros: "estuvisteis animando",
			Uds: "estuvieron animando",
		},
		Imperfect: {
			Uds: "estaban animando",
			yo: "estaba animando",
			tú: "estabas animando",
			Ud: "estaba animando",
			nosotros: "estábamos animando",
			vosotros: "estabais animando",
		},
		Conditional: {
			yo: "estaría animando",
			tú: "estarías animando",
			Ud: "estaría animando",
			nosotros: "estaríamos animando",
			vosotros: "estaríais animando",
			Uds: "estarían animando",
		},
		Future: {
			yo: "estaré animando",
			tú: "estarás animando",
			Ud: "estará animando",
			nosotros: "estaremos animando",
			vosotros: "estaréis animando",
			Uds: "estarán animando",
		},
	},
	Perfect: {
		Present: {
			yo: "he animado",
			tú: "has animado",
			Ud: "ha animado",
			nosotros: "hemos animado",
			vosotros: "habéis animado",
			Uds: "han animado",
		},
		Preterite: {
			yo: "hube animado",
			tú: "hubiste animado",
			Ud: "hubo animado",
			nosotros: "hubimos animado",
			vosotros: "hubisteis animado",
			Uds: "hubieron animado",
		},
		Past: {
			yo: "había animado",
			tú: "habías animado",
			Ud: "había animado",
			nosotros: "habíamos animado",
			vosotros: "habíais animado",
			Uds: "habían animado",
		},
		Conditional: {
			yo: "habría animado",
			tú: "habrías animado",
			Ud: "habría animado",
			nosotros: "habríamos animado",
			vosotros: "habríais animado",
			Uds: "habrían animado",
		},
		Future: {
			yo: "habré animado",
			tú: "habrás animado",
			Ud: "habrá animado",
			nosotros: "habremos animado",
			vosotros: "habréis animado",
			Uds: "habrán animado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya animado",
			tú: "hayas animado",
			Ud: "haya animado",
			nosotros: "hayamos animado",
			vosotros: "hayáis animado",
			Uds: "hayan animado",
		},
		Past: {
			yo: "hubiera animado",
			tú: "hubieras animado",
			Ud: "hubiera animado",
			nosotros: "hubiéramos animado",
			vosotros: "hubierais animado",
			Uds: "hubieran animado",
		},
		Future: {
			yo: "hubiere animado",
			tú: "hubieres animado",
			Ud: "hubiere animado",
			nosotros: "hubiéremos animado",
			vosotros: "hubiereis animado",
			Uds: "hubieren animado",
		},
	},
}
