var anotar = {
	Indicative: {
		Present: {
			yo: "anoto",
			tú: "anotas",
			Ud: "anota",
			nosotros: "anotamos",
			vosotros: "anotáis",
			Uds: "anotan",
		},
		Preterite: {
			yo: "anoté",
			tú: "anotaste",
			Ud: "anotó",
			nosotros: "anotamos",
			vosotros: "anotasteis",
			Uds: "anotaron",
		},
		Imperfect: {
			yo: "anotaba",
			tú: "anotabas",
			Ud: "anotaba",
			nosotros: "anotábamos",
			vosotros: "anotabais",
			Uds: "anotaban",
		},
		Conditional: {
			yo: "anotaría",
			tú: "anotarías",
			Ud: "anotaría",
			nosotros: "anotaríamos",
			vosotros: "anotaríais",
			Uds: "anotarían",
		},
		Future: {
			yo: "anotaré",
			tú: "anotarás",
			Ud: "anotará",
			nosotros: "anotaremos",
			vosotros: "anotaréis",
			Uds: "anotarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "anote",
			tú: "anotes",
			Ud: "anote",
			nosotros: "anotemos",
			vosotros: "anotéis",
			Uds: "anoten",
		},
		Imperfect: {
			yo: "anotara",
			tú: "anotaras",
			Ud: "anotara",
			nosotros: "anotáramos",
			vosotros: "anotarais",
			Uds: "anotaran",
		},
		Imperfect2: {
			yo: "anotase",
			tú: "anotases",
			Ud: "anotase",
			nosotros: "anotásemos",
			vosotros: "anotaseis",
			Uds: "anotasen",
		},
		Future: {
			yo: "anotare",
			tú: "anotares",
			Ud: "anotare",
			nosotros: "anotáremos",
			vosotros: "anotareis",
			Uds: "anotaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "anota",
			Ud: "anote",
			nosotros: "anotemos",
			vosotros: "anotad",
			Uds: "anoten",
		},
		Negative: {
			tú: "no anotes",
			Ud: "no anote",
			nosotros: "no anotemos",
			vosotros: "no anotéis",
			Uds: "no anoten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy anotando",
			tú: "estás anotando",
			Ud: "está anotando",
			nosotros: "estamos anotando",
			vosotros: "estáis anotando",
			Uds: "están anotando",
		},
		Preterite: {
			yo: "estuve anotando",
			tú: "estuviste anotando",
			Ud: "estuvo anotando",
			nosotros: "estuvimos anotando",
			vosotros: "estuvisteis anotando",
			Uds: "estuvieron anotando",
		},
		Imperfect: {
			Uds: "estaban anotando",
			yo: "estaba anotando",
			tú: "estabas anotando",
			Ud: "estaba anotando",
			nosotros: "estábamos anotando",
			vosotros: "estabais anotando",
		},
		Conditional: {
			yo: "estaría anotando",
			tú: "estarías anotando",
			Ud: "estaría anotando",
			nosotros: "estaríamos anotando",
			vosotros: "estaríais anotando",
			Uds: "estarían anotando",
		},
		Future: {
			yo: "estaré anotando",
			tú: "estarás anotando",
			Ud: "estará anotando",
			nosotros: "estaremos anotando",
			vosotros: "estaréis anotando",
			Uds: "estarán anotando",
		},
	},
	Perfect: {
		Present: {
			yo: "he anotado",
			tú: "has anotado",
			Ud: "ha anotado",
			nosotros: "hemos anotado",
			vosotros: "habéis anotado",
			Uds: "han anotado",
		},
		Preterite: {
			yo: "hube anotado",
			tú: "hubiste anotado",
			Ud: "hubo anotado",
			nosotros: "hubimos anotado",
			vosotros: "hubisteis anotado",
			Uds: "hubieron anotado",
		},
		Past: {
			yo: "había anotado",
			tú: "habías anotado",
			Ud: "había anotado",
			nosotros: "habíamos anotado",
			vosotros: "habíais anotado",
			Uds: "habían anotado",
		},
		Conditional: {
			yo: "habría anotado",
			tú: "habrías anotado",
			Ud: "habría anotado",
			nosotros: "habríamos anotado",
			vosotros: "habríais anotado",
			Uds: "habrían anotado",
		},
		Future: {
			yo: "habré anotado",
			tú: "habrás anotado",
			Ud: "habrá anotado",
			nosotros: "habremos anotado",
			vosotros: "habréis anotado",
			Uds: "habrán anotado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya anotado",
			tú: "hayas anotado",
			Ud: "haya anotado",
			nosotros: "hayamos anotado",
			vosotros: "hayáis anotado",
			Uds: "hayan anotado",
		},
		Past: {
			yo: "hubiera anotado",
			tú: "hubieras anotado",
			Ud: "hubiera anotado",
			nosotros: "hubiéramos anotado",
			vosotros: "hubierais anotado",
			Uds: "hubieran anotado",
		},
		Future: {
			yo: "hubiere anotado",
			tú: "hubieres anotado",
			Ud: "hubiere anotado",
			nosotros: "hubiéremos anotado",
			vosotros: "hubiereis anotado",
			Uds: "hubieren anotado",
		},
	},
}
