var apaciguar = {
	Indicative: {
		Present: {
			yo: "apaciguo",
			tú: "apaciguas",
			Ud: "apacigua",
			nosotros: "apaciguamos",
			vosotros: "apaciguáis",
			Uds: "apaciguan",
		},
		Preterite: {
			yo: "apacigüé",
			tú: "apaciguaste",
			Ud: "apaciguó",
			nosotros: "apaciguamos",
			vosotros: "apaciguasteis",
			Uds: "apaciguaron",
		},
		Imperfect: {
			yo: "apaciguaba",
			tú: "apaciguabas",
			Ud: "apaciguaba",
			nosotros: "apaciguábamos",
			vosotros: "apaciguabais",
			Uds: "apaciguaban",
		},
		Conditional: {
			yo: "apaciguaría",
			tú: "apaciguarías",
			Ud: "apaciguaría",
			nosotros: "apaciguaríamos",
			vosotros: "apaciguaríais",
			Uds: "apaciguarían",
		},
		Future: {
			yo: "apaciguaré",
			tú: "apaciguarás",
			Ud: "apaciguará",
			nosotros: "apaciguaremos",
			vosotros: "apaciguaréis",
			Uds: "apaciguarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "apacigüe",
			tú: "apacigües",
			Ud: "apacigüe",
			nosotros: "apacigüemos",
			vosotros: "apacigüéis",
			Uds: "apacigüen",
		},
		Imperfect: {
			yo: "apaciguara",
			tú: "apaciguaras",
			Ud: "apaciguara",
			nosotros: "apaciguáramos",
			vosotros: "apaciguarais",
			Uds: "apaciguaran",
		},
		Imperfect2: {
			yo: "apaciguase",
			tú: "apaciguases",
			Ud: "apaciguase",
			nosotros: "apaciguásemos",
			vosotros: "apaciguaseis",
			Uds: "apaciguasen",
		},
		Future: {
			yo: "apaciguare",
			tú: "apaciguares",
			Ud: "apaciguare",
			nosotros: "apaciguáremos",
			vosotros: "apaciguareis",
			Uds: "apaciguaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "apacigua",
			Ud: "apacigüe",
			nosotros: "apacigüemos",
			vosotros: "apaciguad",
			Uds: "apacigüen",
		},
		Negative: {
			tú: "no apacigües",
			Ud: "no apacigüe",
			nosotros: "no apacigüemos",
			vosotros: "no apacigüéis",
			Uds: "no apacigüen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy apaciguando",
			tú: "estás apaciguando",
			Ud: "está apaciguando",
			nosotros: "estamos apaciguando",
			vosotros: "estáis apaciguando",
			Uds: "están apaciguando",
		},
		Preterite: {
			yo: "estuve apaciguando",
			tú: "estuviste apaciguando",
			Ud: "estuvo apaciguando",
			nosotros: "estuvimos apaciguando",
			vosotros: "estuvisteis apaciguando",
			Uds: "estuvieron apaciguando",
		},
		Imperfect: {
			Uds: "estaban apaciguando",
			yo: "estaba apaciguando",
			tú: "estabas apaciguando",
			Ud: "estaba apaciguando",
			nosotros: "estábamos apaciguando",
			vosotros: "estabais apaciguando",
		},
		Conditional: {
			yo: "estaría apaciguando",
			tú: "estarías apaciguando",
			Ud: "estaría apaciguando",
			nosotros: "estaríamos apaciguando",
			vosotros: "estaríais apaciguando",
			Uds: "estarían apaciguando",
		},
		Future: {
			yo: "estaré apaciguando",
			tú: "estarás apaciguando",
			Ud: "estará apaciguando",
			nosotros: "estaremos apaciguando",
			vosotros: "estaréis apaciguando",
			Uds: "estarán apaciguando",
		},
	},
	Perfect: {
		Present: {
			yo: "he apaciguado",
			tú: "has apaciguado",
			Ud: "ha apaciguado",
			nosotros: "hemos apaciguado",
			vosotros: "habéis apaciguado",
			Uds: "han apaciguado",
		},
		Preterite: {
			yo: "hube apaciguado",
			tú: "hubiste apaciguado",
			Ud: "hubo apaciguado",
			nosotros: "hubimos apaciguado",
			vosotros: "hubisteis apaciguado",
			Uds: "hubieron apaciguado",
		},
		Past: {
			yo: "había apaciguado",
			tú: "habías apaciguado",
			Ud: "había apaciguado",
			nosotros: "habíamos apaciguado",
			vosotros: "habíais apaciguado",
			Uds: "habían apaciguado",
		},
		Conditional: {
			yo: "habría apaciguado",
			tú: "habrías apaciguado",
			Ud: "habría apaciguado",
			nosotros: "habríamos apaciguado",
			vosotros: "habríais apaciguado",
			Uds: "habrían apaciguado",
		},
		Future: {
			yo: "habré apaciguado",
			tú: "habrás apaciguado",
			Ud: "habrá apaciguado",
			nosotros: "habremos apaciguado",
			vosotros: "habréis apaciguado",
			Uds: "habrán apaciguado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya apaciguado",
			tú: "hayas apaciguado",
			Ud: "haya apaciguado",
			nosotros: "hayamos apaciguado",
			vosotros: "hayáis apaciguado",
			Uds: "hayan apaciguado",
		},
		Past: {
			yo: "hubiera apaciguado",
			tú: "hubieras apaciguado",
			Ud: "hubiera apaciguado",
			nosotros: "hubiéramos apaciguado",
			vosotros: "hubierais apaciguado",
			Uds: "hubieran apaciguado",
		},
		Future: {
			yo: "hubiere apaciguado",
			tú: "hubieres apaciguado",
			Ud: "hubiere apaciguado",
			nosotros: "hubiéremos apaciguado",
			vosotros: "hubiereis apaciguado",
			Uds: "hubieren apaciguado",
		},
	},
}
