var aparejar = {
	Indicative: {
		Present: {
			yo: "aparejo",
			tú: "aparejas",
			Ud: "apareja",
			nosotros: "aparejamos",
			vosotros: "aparejáis",
			Uds: "aparejan",
		},
		Preterite: {
			yo: "aparejé",
			tú: "aparejaste",
			Ud: "aparejó",
			nosotros: "aparejamos",
			vosotros: "aparejasteis",
			Uds: "aparejaron",
		},
		Imperfect: {
			yo: "aparejaba",
			tú: "aparejabas",
			Ud: "aparejaba",
			nosotros: "aparejábamos",
			vosotros: "aparejabais",
			Uds: "aparejaban",
		},
		Conditional: {
			yo: "aparejaría",
			tú: "aparejarías",
			Ud: "aparejaría",
			nosotros: "aparejaríamos",
			vosotros: "aparejaríais",
			Uds: "aparejarían",
		},
		Future: {
			yo: "aparejaré",
			tú: "aparejarás",
			Ud: "aparejará",
			nosotros: "aparejaremos",
			vosotros: "aparejaréis",
			Uds: "aparejarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "apareje",
			tú: "aparejes",
			Ud: "apareje",
			nosotros: "aparejemos",
			vosotros: "aparejéis",
			Uds: "aparejen",
		},
		Imperfect: {
			yo: "aparejara",
			tú: "aparejaras",
			Ud: "aparejara",
			nosotros: "aparejáramos",
			vosotros: "aparejarais",
			Uds: "aparejaran",
		},
		Imperfect2: {
			yo: "aparejase",
			tú: "aparejases",
			Ud: "aparejase",
			nosotros: "aparejásemos",
			vosotros: "aparejaseis",
			Uds: "aparejasen",
		},
		Future: {
			yo: "aparejare",
			tú: "aparejares",
			Ud: "aparejare",
			nosotros: "aparejáremos",
			vosotros: "aparejareis",
			Uds: "aparejaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "apareja",
			Ud: "apareje",
			nosotros: "aparejemos",
			vosotros: "aparejad",
			Uds: "aparejen",
		},
		Negative: {
			tú: "no aparejes",
			Ud: "no apareje",
			nosotros: "no aparejemos",
			vosotros: "no aparejéis",
			Uds: "no aparejen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy aparejando",
			tú: "estás aparejando",
			Ud: "está aparejando",
			nosotros: "estamos aparejando",
			vosotros: "estáis aparejando",
			Uds: "están aparejando",
		},
		Preterite: {
			yo: "estuve aparejando",
			tú: "estuviste aparejando",
			Ud: "estuvo aparejando",
			nosotros: "estuvimos aparejando",
			vosotros: "estuvisteis aparejando",
			Uds: "estuvieron aparejando",
		},
		Imperfect: {
			Uds: "estaban aparejando",
			yo: "estaba aparejando",
			tú: "estabas aparejando",
			Ud: "estaba aparejando",
			nosotros: "estábamos aparejando",
			vosotros: "estabais aparejando",
		},
		Conditional: {
			yo: "estaría aparejando",
			tú: "estarías aparejando",
			Ud: "estaría aparejando",
			nosotros: "estaríamos aparejando",
			vosotros: "estaríais aparejando",
			Uds: "estarían aparejando",
		},
		Future: {
			yo: "estaré aparejando",
			tú: "estarás aparejando",
			Ud: "estará aparejando",
			nosotros: "estaremos aparejando",
			vosotros: "estaréis aparejando",
			Uds: "estarán aparejando",
		},
	},
	Perfect: {
		Present: {
			yo: "he aparejado",
			tú: "has aparejado",
			Ud: "ha aparejado",
			nosotros: "hemos aparejado",
			vosotros: "habéis aparejado",
			Uds: "han aparejado",
		},
		Preterite: {
			yo: "hube aparejado",
			tú: "hubiste aparejado",
			Ud: "hubo aparejado",
			nosotros: "hubimos aparejado",
			vosotros: "hubisteis aparejado",
			Uds: "hubieron aparejado",
		},
		Past: {
			yo: "había aparejado",
			tú: "habías aparejado",
			Ud: "había aparejado",
			nosotros: "habíamos aparejado",
			vosotros: "habíais aparejado",
			Uds: "habían aparejado",
		},
		Conditional: {
			yo: "habría aparejado",
			tú: "habrías aparejado",
			Ud: "habría aparejado",
			nosotros: "habríamos aparejado",
			vosotros: "habríais aparejado",
			Uds: "habrían aparejado",
		},
		Future: {
			yo: "habré aparejado",
			tú: "habrás aparejado",
			Ud: "habrá aparejado",
			nosotros: "habremos aparejado",
			vosotros: "habréis aparejado",
			Uds: "habrán aparejado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya aparejado",
			tú: "hayas aparejado",
			Ud: "haya aparejado",
			nosotros: "hayamos aparejado",
			vosotros: "hayáis aparejado",
			Uds: "hayan aparejado",
		},
		Past: {
			yo: "hubiera aparejado",
			tú: "hubieras aparejado",
			Ud: "hubiera aparejado",
			nosotros: "hubiéramos aparejado",
			vosotros: "hubierais aparejado",
			Uds: "hubieran aparejado",
		},
		Future: {
			yo: "hubiere aparejado",
			tú: "hubieres aparejado",
			Ud: "hubiere aparejado",
			nosotros: "hubiéremos aparejado",
			vosotros: "hubiereis aparejado",
			Uds: "hubieren aparejado",
		},
	},
}
