var aparear = {
	Indicative: {
		Present: {
			yo: "apareo",
			tú: "apareas",
			Ud: "aparea",
			nosotros: "apareamos",
			vosotros: "apareáis",
			Uds: "aparean",
		},
		Preterite: {
			yo: "apareé",
			tú: "apareaste",
			Ud: "apareó",
			nosotros: "apareamos",
			vosotros: "apareasteis",
			Uds: "aparearon",
		},
		Imperfect: {
			yo: "apareaba",
			tú: "apareabas",
			Ud: "apareaba",
			nosotros: "apareábamos",
			vosotros: "apareabais",
			Uds: "apareaban",
		},
		Conditional: {
			yo: "aparearía",
			tú: "aparearías",
			Ud: "aparearía",
			nosotros: "aparearíamos",
			vosotros: "aparearíais",
			Uds: "aparearían",
		},
		Future: {
			yo: "aparearé",
			tú: "aparearás",
			Ud: "apareará",
			nosotros: "aparearemos",
			vosotros: "aparearéis",
			Uds: "aparearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "aparee",
			tú: "aparees",
			Ud: "aparee",
			nosotros: "apareemos",
			vosotros: "apareéis",
			Uds: "apareen",
		},
		Imperfect: {
			yo: "apareara",
			tú: "aparearas",
			Ud: "apareara",
			nosotros: "apareáramos",
			vosotros: "aparearais",
			Uds: "aparearan",
		},
		Imperfect2: {
			yo: "aparease",
			tú: "apareases",
			Ud: "aparease",
			nosotros: "apareásemos",
			vosotros: "apareaseis",
			Uds: "apareasen",
		},
		Future: {
			yo: "apareare",
			tú: "apareares",
			Ud: "apareare",
			nosotros: "apareáremos",
			vosotros: "apareareis",
			Uds: "aparearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "aparea",
			Ud: "aparee",
			nosotros: "apareemos",
			vosotros: "aparead",
			Uds: "apareen",
		},
		Negative: {
			tú: "no aparees",
			Ud: "no aparee",
			nosotros: "no apareemos",
			vosotros: "no apareéis",
			Uds: "no apareen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy apareando",
			tú: "estás apareando",
			Ud: "está apareando",
			nosotros: "estamos apareando",
			vosotros: "estáis apareando",
			Uds: "están apareando",
		},
		Preterite: {
			yo: "estuve apareando",
			tú: "estuviste apareando",
			Ud: "estuvo apareando",
			nosotros: "estuvimos apareando",
			vosotros: "estuvisteis apareando",
			Uds: "estuvieron apareando",
		},
		Imperfect: {
			Uds: "estaban apareando",
			yo: "estaba apareando",
			tú: "estabas apareando",
			Ud: "estaba apareando",
			nosotros: "estábamos apareando",
			vosotros: "estabais apareando",
		},
		Conditional: {
			yo: "estaría apareando",
			tú: "estarías apareando",
			Ud: "estaría apareando",
			nosotros: "estaríamos apareando",
			vosotros: "estaríais apareando",
			Uds: "estarían apareando",
		},
		Future: {
			yo: "estaré apareando",
			tú: "estarás apareando",
			Ud: "estará apareando",
			nosotros: "estaremos apareando",
			vosotros: "estaréis apareando",
			Uds: "estarán apareando",
		},
	},
	Perfect: {
		Present: {
			yo: "he apareado",
			tú: "has apareado",
			Ud: "ha apareado",
			nosotros: "hemos apareado",
			vosotros: "habéis apareado",
			Uds: "han apareado",
		},
		Preterite: {
			yo: "hube apareado",
			tú: "hubiste apareado",
			Ud: "hubo apareado",
			nosotros: "hubimos apareado",
			vosotros: "hubisteis apareado",
			Uds: "hubieron apareado",
		},
		Past: {
			yo: "había apareado",
			tú: "habías apareado",
			Ud: "había apareado",
			nosotros: "habíamos apareado",
			vosotros: "habíais apareado",
			Uds: "habían apareado",
		},
		Conditional: {
			yo: "habría apareado",
			tú: "habrías apareado",
			Ud: "habría apareado",
			nosotros: "habríamos apareado",
			vosotros: "habríais apareado",
			Uds: "habrían apareado",
		},
		Future: {
			yo: "habré apareado",
			tú: "habrás apareado",
			Ud: "habrá apareado",
			nosotros: "habremos apareado",
			vosotros: "habréis apareado",
			Uds: "habrán apareado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya apareado",
			tú: "hayas apareado",
			Ud: "haya apareado",
			nosotros: "hayamos apareado",
			vosotros: "hayáis apareado",
			Uds: "hayan apareado",
		},
		Past: {
			yo: "hubiera apareado",
			tú: "hubieras apareado",
			Ud: "hubiera apareado",
			nosotros: "hubiéramos apareado",
			vosotros: "hubierais apareado",
			Uds: "hubieran apareado",
		},
		Future: {
			yo: "hubiere apareado",
			tú: "hubieres apareado",
			Ud: "hubiere apareado",
			nosotros: "hubiéremos apareado",
			vosotros: "hubiereis apareado",
			Uds: "hubieren apareado",
		},
	},
}
