var apestar = {
	Indicative: {
		Present: {
			yo: "apesto",
			tú: "apestas",
			Ud: "apesta",
			nosotros: "apestamos",
			vosotros: "apestáis",
			Uds: "apestan",
		},
		Preterite: {
			yo: "apesté",
			tú: "apestaste",
			Ud: "apestó",
			nosotros: "apestamos",
			vosotros: "apestasteis",
			Uds: "apestaron",
		},
		Imperfect: {
			yo: "apestaba",
			tú: "apestabas",
			Ud: "apestaba",
			nosotros: "apestábamos",
			vosotros: "apestabais",
			Uds: "apestaban",
		},
		Conditional: {
			yo: "apestaría",
			tú: "apestarías",
			Ud: "apestaría",
			nosotros: "apestaríamos",
			vosotros: "apestaríais",
			Uds: "apestarían",
		},
		Future: {
			yo: "apestaré",
			tú: "apestarás",
			Ud: "apestará",
			nosotros: "apestaremos",
			vosotros: "apestaréis",
			Uds: "apestarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "apeste",
			tú: "apestes",
			Ud: "apeste",
			nosotros: "apestemos",
			vosotros: "apestéis",
			Uds: "apesten",
		},
		Imperfect: {
			yo: "apestara",
			tú: "apestaras",
			Ud: "apestara",
			nosotros: "apestáramos",
			vosotros: "apestarais",
			Uds: "apestaran",
		},
		Imperfect2: {
			yo: "apestase",
			tú: "apestases",
			Ud: "apestase",
			nosotros: "apestásemos",
			vosotros: "apestaseis",
			Uds: "apestasen",
		},
		Future: {
			yo: "apestare",
			tú: "apestares",
			Ud: "apestare",
			nosotros: "apestáremos",
			vosotros: "apestareis",
			Uds: "apestaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "apesta",
			Ud: "apeste",
			nosotros: "apestemos",
			vosotros: "apestad",
			Uds: "apesten",
		},
		Negative: {
			tú: "no apestes",
			Ud: "no apeste",
			nosotros: "no apestemos",
			vosotros: "no apestéis",
			Uds: "no apesten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy apestando",
			tú: "estás apestando",
			Ud: "está apestando",
			nosotros: "estamos apestando",
			vosotros: "estáis apestando",
			Uds: "están apestando",
		},
		Preterite: {
			yo: "estuve apestando",
			tú: "estuviste apestando",
			Ud: "estuvo apestando",
			nosotros: "estuvimos apestando",
			vosotros: "estuvisteis apestando",
			Uds: "estuvieron apestando",
		},
		Imperfect: {
			Uds: "estaban apestando",
			yo: "estaba apestando",
			tú: "estabas apestando",
			Ud: "estaba apestando",
			nosotros: "estábamos apestando",
			vosotros: "estabais apestando",
		},
		Conditional: {
			yo: "estaría apestando",
			tú: "estarías apestando",
			Ud: "estaría apestando",
			nosotros: "estaríamos apestando",
			vosotros: "estaríais apestando",
			Uds: "estarían apestando",
		},
		Future: {
			yo: "estaré apestando",
			tú: "estarás apestando",
			Ud: "estará apestando",
			nosotros: "estaremos apestando",
			vosotros: "estaréis apestando",
			Uds: "estarán apestando",
		},
	},
	Perfect: {
		Present: {
			yo: "he apestado",
			tú: "has apestado",
			Ud: "ha apestado",
			nosotros: "hemos apestado",
			vosotros: "habéis apestado",
			Uds: "han apestado",
		},
		Preterite: {
			yo: "hube apestado",
			tú: "hubiste apestado",
			Ud: "hubo apestado",
			nosotros: "hubimos apestado",
			vosotros: "hubisteis apestado",
			Uds: "hubieron apestado",
		},
		Past: {
			yo: "había apestado",
			tú: "habías apestado",
			Ud: "había apestado",
			nosotros: "habíamos apestado",
			vosotros: "habíais apestado",
			Uds: "habían apestado",
		},
		Conditional: {
			yo: "habría apestado",
			tú: "habrías apestado",
			Ud: "habría apestado",
			nosotros: "habríamos apestado",
			vosotros: "habríais apestado",
			Uds: "habrían apestado",
		},
		Future: {
			yo: "habré apestado",
			tú: "habrás apestado",
			Ud: "habrá apestado",
			nosotros: "habremos apestado",
			vosotros: "habréis apestado",
			Uds: "habrán apestado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya apestado",
			tú: "hayas apestado",
			Ud: "haya apestado",
			nosotros: "hayamos apestado",
			vosotros: "hayáis apestado",
			Uds: "hayan apestado",
		},
		Past: {
			yo: "hubiera apestado",
			tú: "hubieras apestado",
			Ud: "hubiera apestado",
			nosotros: "hubiéramos apestado",
			vosotros: "hubierais apestado",
			Uds: "hubieran apestado",
		},
		Future: {
			yo: "hubiere apestado",
			tú: "hubieres apestado",
			Ud: "hubiere apestado",
			nosotros: "hubiéremos apestado",
			vosotros: "hubiereis apestado",
			Uds: "hubieren apestado",
		},
	},
}
