var apetecer = {
	Indicative: {
		Present: {
			yo: "apetezco",
			tú: "apeteces",
			Ud: "apetece",
			nosotros: "apetecemos",
			vosotros: "apetecéis",
			Uds: "apetecen",
		},
		Preterite: {
			yo: "apetecí",
			tú: "apeteciste",
			Ud: "apeteció",
			nosotros: "apetecimos",
			vosotros: "apetecisteis",
			Uds: "apetecieron",
		},
		Imperfect: {
			yo: "apetecía",
			tú: "apetecías",
			Ud: "apetecía",
			nosotros: "apetecíamos",
			vosotros: "apetecíais",
			Uds: "apetecían",
		},
		Conditional: {
			yo: "apetecería",
			tú: "apetecerías",
			Ud: "apetecería",
			nosotros: "apeteceríamos",
			vosotros: "apeteceríais",
			Uds: "apetecerían",
		},
		Future: {
			yo: "apeteceré",
			tú: "apetecerás",
			Ud: "apetecerá",
			nosotros: "apeteceremos",
			vosotros: "apeteceréis",
			Uds: "apetecerán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "apetezca",
			tú: "apetezcas",
			Ud: "apetezca",
			nosotros: "apetezcamos",
			vosotros: "apetezcáis",
			Uds: "apetezcan",
		},
		Imperfect: {
			yo: "apeteciera",
			tú: "apetecieras",
			Ud: "apeteciera",
			nosotros: "apeteciéramos",
			vosotros: "apetecierais",
			Uds: "apetecieran",
		},
		Imperfect2: {
			yo: "apeteciese",
			tú: "apetecieses",
			Ud: "apeteciese",
			nosotros: "apeteciésemos",
			vosotros: "apetecieseis",
			Uds: "apeteciesen",
		},
		Future: {
			yo: "apeteciere",
			tú: "apetecieres",
			Ud: "apeteciere",
			nosotros: "apeteciéremos",
			vosotros: "apeteciereis",
			Uds: "apetecieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "apetece",
			Ud: "apetezca",
			nosotros: "apetezcamos",
			vosotros: "apeteced",
			Uds: "apetezcan",
		},
		Negative: {
			tú: "no apetezcas",
			Ud: "no apetezca",
			nosotros: "no apetezcamos",
			vosotros: "no apetezcáis",
			Uds: "no apetezcan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy apeteciendo",
			tú: "estás apeteciendo",
			Ud: "está apeteciendo",
			nosotros: "estamos apeteciendo",
			vosotros: "estáis apeteciendo",
			Uds: "están apeteciendo",
		},
		Preterite: {
			yo: "estuve apeteciendo",
			tú: "estuviste apeteciendo",
			Ud: "estuvo apeteciendo",
			nosotros: "estuvimos apeteciendo",
			vosotros: "estuvisteis apeteciendo",
			Uds: "estuvieron apeteciendo",
		},
		Imperfect: {
			Uds: "estaban apeteciendo",
			yo: "estaba apeteciendo",
			tú: "estabas apeteciendo",
			Ud: "estaba apeteciendo",
			nosotros: "estábamos apeteciendo",
			vosotros: "estabais apeteciendo",
		},
		Conditional: {
			yo: "estaría apeteciendo",
			tú: "estarías apeteciendo",
			Ud: "estaría apeteciendo",
			nosotros: "estaríamos apeteciendo",
			vosotros: "estaríais apeteciendo",
			Uds: "estarían apeteciendo",
		},
		Future: {
			yo: "estaré apeteciendo",
			tú: "estarás apeteciendo",
			Ud: "estará apeteciendo",
			nosotros: "estaremos apeteciendo",
			vosotros: "estaréis apeteciendo",
			Uds: "estarán apeteciendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he apetecido",
			tú: "has apetecido",
			Ud: "ha apetecido",
			nosotros: "hemos apetecido",
			vosotros: "habéis apetecido",
			Uds: "han apetecido",
		},
		Preterite: {
			yo: "hube apetecido",
			tú: "hubiste apetecido",
			Ud: "hubo apetecido",
			nosotros: "hubimos apetecido",
			vosotros: "hubisteis apetecido",
			Uds: "hubieron apetecido",
		},
		Past: {
			yo: "había apetecido",
			tú: "habías apetecido",
			Ud: "había apetecido",
			nosotros: "habíamos apetecido",
			vosotros: "habíais apetecido",
			Uds: "habían apetecido",
		},
		Conditional: {
			yo: "habría apetecido",
			tú: "habrías apetecido",
			Ud: "habría apetecido",
			nosotros: "habríamos apetecido",
			vosotros: "habríais apetecido",
			Uds: "habrían apetecido",
		},
		Future: {
			yo: "habré apetecido",
			tú: "habrás apetecido",
			Ud: "habrá apetecido",
			nosotros: "habremos apetecido",
			vosotros: "habréis apetecido",
			Uds: "habrán apetecido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya apetecido",
			tú: "hayas apetecido",
			Ud: "haya apetecido",
			nosotros: "hayamos apetecido",
			vosotros: "hayáis apetecido",
			Uds: "hayan apetecido",
		},
		Past: {
			yo: "hubiera apetecido",
			tú: "hubieras apetecido",
			Ud: "hubiera apetecido",
			nosotros: "hubiéramos apetecido",
			vosotros: "hubierais apetecido",
			Uds: "hubieran apetecido",
		},
		Future: {
			yo: "hubiere apetecido",
			tú: "hubieres apetecido",
			Ud: "hubiere apetecido",
			nosotros: "hubiéremos apetecido",
			vosotros: "hubiereis apetecido",
			Uds: "hubieren apetecido",
		},
	},
}
