var aplicar = {
	Indicative: {
		Present: {
			yo: "aplico",
			tú: "aplicas",
			Ud: "aplica",
			nosotros: "aplicamos",
			vosotros: "aplicáis",
			Uds: "aplican",
		},
		Preterite: {
			yo: "apliqué",
			tú: "aplicaste",
			Ud: "aplicó",
			nosotros: "aplicamos",
			vosotros: "aplicasteis",
			Uds: "aplicaron",
		},
		Imperfect: {
			yo: "aplicaba",
			tú: "aplicabas",
			Ud: "aplicaba",
			nosotros: "aplicábamos",
			vosotros: "aplicabais",
			Uds: "aplicaban",
		},
		Conditional: {
			yo: "aplicaría",
			tú: "aplicarías",
			Ud: "aplicaría",
			nosotros: "aplicaríamos",
			vosotros: "aplicaríais",
			Uds: "aplicarían",
		},
		Future: {
			yo: "aplicaré",
			tú: "aplicarás",
			Ud: "aplicará",
			nosotros: "aplicaremos",
			vosotros: "aplicaréis",
			Uds: "aplicarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "aplique",
			tú: "apliques",
			Ud: "aplique",
			nosotros: "apliquemos",
			vosotros: "apliquéis",
			Uds: "apliquen",
		},
		Imperfect: {
			yo: "aplicara",
			tú: "aplicaras",
			Ud: "aplicara",
			nosotros: "aplicáramos",
			vosotros: "aplicarais",
			Uds: "aplicaran",
		},
		Imperfect2: {
			yo: "aplicase",
			tú: "aplicases",
			Ud: "aplicase",
			nosotros: "aplicásemos",
			vosotros: "aplicaseis",
			Uds: "aplicasen",
		},
		Future: {
			yo: "aplicare",
			tú: "aplicares",
			Ud: "aplicare",
			nosotros: "aplicáremos",
			vosotros: "aplicareis",
			Uds: "aplicaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "aplica",
			Ud: "aplique",
			nosotros: "apliquemos",
			vosotros: "aplicad",
			Uds: "apliquen",
		},
		Negative: {
			tú: "no apliques",
			Ud: "no aplique",
			nosotros: "no apliquemos",
			vosotros: "no apliquéis",
			Uds: "no apliquen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy aplicando",
			tú: "estás aplicando",
			Ud: "está aplicando",
			nosotros: "estamos aplicando",
			vosotros: "estáis aplicando",
			Uds: "están aplicando",
		},
		Preterite: {
			yo: "estuve aplicando",
			tú: "estuviste aplicando",
			Ud: "estuvo aplicando",
			nosotros: "estuvimos aplicando",
			vosotros: "estuvisteis aplicando",
			Uds: "estuvieron aplicando",
		},
		Imperfect: {
			Uds: "estaban aplicando",
			yo: "estaba aplicando",
			tú: "estabas aplicando",
			Ud: "estaba aplicando",
			nosotros: "estábamos aplicando",
			vosotros: "estabais aplicando",
		},
		Conditional: {
			yo: "estaría aplicando",
			tú: "estarías aplicando",
			Ud: "estaría aplicando",
			nosotros: "estaríamos aplicando",
			vosotros: "estaríais aplicando",
			Uds: "estarían aplicando",
		},
		Future: {
			yo: "estaré aplicando",
			tú: "estarás aplicando",
			Ud: "estará aplicando",
			nosotros: "estaremos aplicando",
			vosotros: "estaréis aplicando",
			Uds: "estarán aplicando",
		},
	},
	Perfect: {
		Present: {
			yo: "he aplicado",
			tú: "has aplicado",
			Ud: "ha aplicado",
			nosotros: "hemos aplicado",
			vosotros: "habéis aplicado",
			Uds: "han aplicado",
		},
		Preterite: {
			yo: "hube aplicado",
			tú: "hubiste aplicado",
			Ud: "hubo aplicado",
			nosotros: "hubimos aplicado",
			vosotros: "hubisteis aplicado",
			Uds: "hubieron aplicado",
		},
		Past: {
			yo: "había aplicado",
			tú: "habías aplicado",
			Ud: "había aplicado",
			nosotros: "habíamos aplicado",
			vosotros: "habíais aplicado",
			Uds: "habían aplicado",
		},
		Conditional: {
			yo: "habría aplicado",
			tú: "habrías aplicado",
			Ud: "habría aplicado",
			nosotros: "habríamos aplicado",
			vosotros: "habríais aplicado",
			Uds: "habrían aplicado",
		},
		Future: {
			yo: "habré aplicado",
			tú: "habrás aplicado",
			Ud: "habrá aplicado",
			nosotros: "habremos aplicado",
			vosotros: "habréis aplicado",
			Uds: "habrán aplicado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya aplicado",
			tú: "hayas aplicado",
			Ud: "haya aplicado",
			nosotros: "hayamos aplicado",
			vosotros: "hayáis aplicado",
			Uds: "hayan aplicado",
		},
		Past: {
			yo: "hubiera aplicado",
			tú: "hubieras aplicado",
			Ud: "hubiera aplicado",
			nosotros: "hubiéramos aplicado",
			vosotros: "hubierais aplicado",
			Uds: "hubieran aplicado",
		},
		Future: {
			yo: "hubiere aplicado",
			tú: "hubieres aplicado",
			Ud: "hubiere aplicado",
			nosotros: "hubiéremos aplicado",
			vosotros: "hubiereis aplicado",
			Uds: "hubieren aplicado",
		},
	},
}
