var apoyar = {
	Indicative: {
		Present: {
			yo: "apoyo",
			tú: "apoyas",
			Ud: "apoya",
			nosotros: "apoyamos",
			vosotros: "apoyáis",
			Uds: "apoyan",
		},
		Preterite: {
			yo: "apoyé",
			tú: "apoyaste",
			Ud: "apoyó",
			nosotros: "apoyamos",
			vosotros: "apoyasteis",
			Uds: "apoyaron",
		},
		Imperfect: {
			yo: "apoyaba",
			tú: "apoyabas",
			Ud: "apoyaba",
			nosotros: "apoyábamos",
			vosotros: "apoyabais",
			Uds: "apoyaban",
		},
		Conditional: {
			yo: "apoyaría",
			tú: "apoyarías",
			Ud: "apoyaría",
			nosotros: "apoyaríamos",
			vosotros: "apoyaríais",
			Uds: "apoyarían",
		},
		Future: {
			yo: "apoyaré",
			tú: "apoyarás",
			Ud: "apoyará",
			nosotros: "apoyaremos",
			vosotros: "apoyaréis",
			Uds: "apoyarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "apoye",
			tú: "apoyes",
			Ud: "apoye",
			nosotros: "apoyemos",
			vosotros: "apoyéis",
			Uds: "apoyen",
		},
		Imperfect: {
			yo: "apoyara",
			tú: "apoyaras",
			Ud: "apoyara",
			nosotros: "apoyáramos",
			vosotros: "apoyarais",
			Uds: "apoyaran",
		},
		Imperfect2: {
			yo: "apoyase",
			tú: "apoyases",
			Ud: "apoyase",
			nosotros: "apoyásemos",
			vosotros: "apoyaseis",
			Uds: "apoyasen",
		},
		Future: {
			yo: "apoyare",
			tú: "apoyares",
			Ud: "apoyare",
			nosotros: "apoyáremos",
			vosotros: "apoyareis",
			Uds: "apoyaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "apoya",
			Ud: "apoye",
			nosotros: "apoyemos",
			vosotros: "apoyad",
			Uds: "apoyen",
		},
		Negative: {
			tú: "no apoyes",
			Ud: "no apoye",
			nosotros: "no apoyemos",
			vosotros: "no apoyéis",
			Uds: "no apoyen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy apoyando",
			tú: "estás apoyando",
			Ud: "está apoyando",
			nosotros: "estamos apoyando",
			vosotros: "estáis apoyando",
			Uds: "están apoyando",
		},
		Preterite: {
			yo: "estuve apoyando",
			tú: "estuviste apoyando",
			Ud: "estuvo apoyando",
			nosotros: "estuvimos apoyando",
			vosotros: "estuvisteis apoyando",
			Uds: "estuvieron apoyando",
		},
		Imperfect: {
			Uds: "estaban apoyando",
			yo: "estaba apoyando",
			tú: "estabas apoyando",
			Ud: "estaba apoyando",
			nosotros: "estábamos apoyando",
			vosotros: "estabais apoyando",
		},
		Conditional: {
			yo: "estaría apoyando",
			tú: "estarías apoyando",
			Ud: "estaría apoyando",
			nosotros: "estaríamos apoyando",
			vosotros: "estaríais apoyando",
			Uds: "estarían apoyando",
		},
		Future: {
			yo: "estaré apoyando",
			tú: "estarás apoyando",
			Ud: "estará apoyando",
			nosotros: "estaremos apoyando",
			vosotros: "estaréis apoyando",
			Uds: "estarán apoyando",
		},
	},
	Perfect: {
		Present: {
			yo: "he apoyado",
			tú: "has apoyado",
			Ud: "ha apoyado",
			nosotros: "hemos apoyado",
			vosotros: "habéis apoyado",
			Uds: "han apoyado",
		},
		Preterite: {
			yo: "hube apoyado",
			tú: "hubiste apoyado",
			Ud: "hubo apoyado",
			nosotros: "hubimos apoyado",
			vosotros: "hubisteis apoyado",
			Uds: "hubieron apoyado",
		},
		Past: {
			yo: "había apoyado",
			tú: "habías apoyado",
			Ud: "había apoyado",
			nosotros: "habíamos apoyado",
			vosotros: "habíais apoyado",
			Uds: "habían apoyado",
		},
		Conditional: {
			yo: "habría apoyado",
			tú: "habrías apoyado",
			Ud: "habría apoyado",
			nosotros: "habríamos apoyado",
			vosotros: "habríais apoyado",
			Uds: "habrían apoyado",
		},
		Future: {
			yo: "habré apoyado",
			tú: "habrás apoyado",
			Ud: "habrá apoyado",
			nosotros: "habremos apoyado",
			vosotros: "habréis apoyado",
			Uds: "habrán apoyado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya apoyado",
			tú: "hayas apoyado",
			Ud: "haya apoyado",
			nosotros: "hayamos apoyado",
			vosotros: "hayáis apoyado",
			Uds: "hayan apoyado",
		},
		Past: {
			yo: "hubiera apoyado",
			tú: "hubieras apoyado",
			Ud: "hubiera apoyado",
			nosotros: "hubiéramos apoyado",
			vosotros: "hubierais apoyado",
			Uds: "hubieran apoyado",
		},
		Future: {
			yo: "hubiere apoyado",
			tú: "hubieres apoyado",
			Ud: "hubiere apoyado",
			nosotros: "hubiéremos apoyado",
			vosotros: "hubiereis apoyado",
			Uds: "hubieren apoyado",
		},
	},
}
