var aprender = {
	Indicative: {
		Present: {
			yo: "aprendo",
			tú: "aprendes",
			Ud: "aprende",
			nosotros: "aprendemos",
			vosotros: "aprendéis",
			Uds: "aprenden",
		},
		Preterite: {
			yo: "aprendí",
			tú: "aprendiste",
			Ud: "aprendió",
			nosotros: "aprendimos",
			vosotros: "aprendisteis",
			Uds: "aprendieron",
		},
		Imperfect: {
			yo: "aprendía",
			tú: "aprendías",
			Ud: "aprendía",
			nosotros: "aprendíamos",
			vosotros: "aprendíais",
			Uds: "aprendían",
		},
		Conditional: {
			yo: "aprendería",
			tú: "aprenderías",
			Ud: "aprendería",
			nosotros: "aprenderíamos",
			vosotros: "aprenderíais",
			Uds: "aprenderían",
		},
		Future: {
			yo: "aprenderé",
			tú: "aprenderás",
			Ud: "aprenderá",
			nosotros: "aprenderemos",
			vosotros: "aprenderéis",
			Uds: "aprenderán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "aprenda",
			tú: "aprendas",
			Ud: "aprenda",
			nosotros: "aprendamos",
			vosotros: "aprendáis",
			Uds: "aprendan",
		},
		Imperfect: {
			yo: "aprendiera",
			tú: "aprendieras",
			Ud: "aprendiera",
			nosotros: "aprendiéramos",
			vosotros: "aprendierais",
			Uds: "aprendieran",
		},
		Imperfect2: {
			yo: "aprendiese",
			tú: "aprendieses",
			Ud: "aprendiese",
			nosotros: "aprendiésemos",
			vosotros: "aprendieseis",
			Uds: "aprendiesen",
		},
		Future: {
			yo: "aprendiere",
			tú: "aprendieres",
			Ud: "aprendiere",
			nosotros: "aprendiéremos",
			vosotros: "aprendiereis",
			Uds: "aprendieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "aprende",
			Ud: "aprenda",
			nosotros: "aprendamos",
			vosotros: "aprended",
			Uds: "aprendan",
		},
		Negative: {
			tú: "no aprendas",
			Ud: "no aprenda",
			nosotros: "no aprendamos",
			vosotros: "no aprendáis",
			Uds: "no aprendan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy aprendiendo",
			tú: "estás aprendiendo",
			Ud: "está aprendiendo",
			nosotros: "estamos aprendiendo",
			vosotros: "estáis aprendiendo",
			Uds: "están aprendiendo",
		},
		Preterite: {
			yo: "estuve aprendiendo",
			tú: "estuviste aprendiendo",
			Ud: "estuvo aprendiendo",
			nosotros: "estuvimos aprendiendo",
			vosotros: "estuvisteis aprendiendo",
			Uds: "estuvieron aprendiendo",
		},
		Imperfect: {
			Uds: "estaban aprendiendo",
			yo: "estaba aprendiendo",
			tú: "estabas aprendiendo",
			Ud: "estaba aprendiendo",
			nosotros: "estábamos aprendiendo",
			vosotros: "estabais aprendiendo",
		},
		Conditional: {
			yo: "estaría aprendiendo",
			tú: "estarías aprendiendo",
			Ud: "estaría aprendiendo",
			nosotros: "estaríamos aprendiendo",
			vosotros: "estaríais aprendiendo",
			Uds: "estarían aprendiendo",
		},
		Future: {
			yo: "estaré aprendiendo",
			tú: "estarás aprendiendo",
			Ud: "estará aprendiendo",
			nosotros: "estaremos aprendiendo",
			vosotros: "estaréis aprendiendo",
			Uds: "estarán aprendiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he aprendido",
			tú: "has aprendido",
			Ud: "ha aprendido",
			nosotros: "hemos aprendido",
			vosotros: "habéis aprendido",
			Uds: "han aprendido",
		},
		Preterite: {
			yo: "hube aprendido",
			tú: "hubiste aprendido",
			Ud: "hubo aprendido",
			nosotros: "hubimos aprendido",
			vosotros: "hubisteis aprendido",
			Uds: "hubieron aprendido",
		},
		Past: {
			yo: "había aprendido",
			tú: "habías aprendido",
			Ud: "había aprendido",
			nosotros: "habíamos aprendido",
			vosotros: "habíais aprendido",
			Uds: "habían aprendido",
		},
		Conditional: {
			yo: "habría aprendido",
			tú: "habrías aprendido",
			Ud: "habría aprendido",
			nosotros: "habríamos aprendido",
			vosotros: "habríais aprendido",
			Uds: "habrían aprendido",
		},
		Future: {
			yo: "habré aprendido",
			tú: "habrás aprendido",
			Ud: "habrá aprendido",
			nosotros: "habremos aprendido",
			vosotros: "habréis aprendido",
			Uds: "habrán aprendido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya aprendido",
			tú: "hayas aprendido",
			Ud: "haya aprendido",
			nosotros: "hayamos aprendido",
			vosotros: "hayáis aprendido",
			Uds: "hayan aprendido",
		},
		Past: {
			yo: "hubiera aprendido",
			tú: "hubieras aprendido",
			Ud: "hubiera aprendido",
			nosotros: "hubiéramos aprendido",
			vosotros: "hubierais aprendido",
			Uds: "hubieran aprendido",
		},
		Future: {
			yo: "hubiere aprendido",
			tú: "hubieres aprendido",
			Ud: "hubiere aprendido",
			nosotros: "hubiéremos aprendido",
			vosotros: "hubiereis aprendido",
			Uds: "hubieren aprendido",
		},
	},
}
