var apremiar = {
	Indicative: {
		Present: {
			yo: "apremio",
			tú: "apremias",
			Ud: "apremia",
			nosotros: "apremiamos",
			vosotros: "apremiáis",
			Uds: "apremian",
		},
		Preterite: {
			yo: "apremié",
			tú: "apremiaste",
			Ud: "apremió",
			nosotros: "apremiamos",
			vosotros: "apremiasteis",
			Uds: "apremiaron",
		},
		Imperfect: {
			yo: "apremiaba",
			tú: "apremiabas",
			Ud: "apremiaba",
			nosotros: "apremiábamos",
			vosotros: "apremiabais",
			Uds: "apremiaban",
		},
		Conditional: {
			yo: "apremiaría",
			tú: "apremiarías",
			Ud: "apremiaría",
			nosotros: "apremiaríamos",
			vosotros: "apremiaríais",
			Uds: "apremiarían",
		},
		Future: {
			yo: "apremiaré",
			tú: "apremiarás",
			Ud: "apremiará",
			nosotros: "apremiaremos",
			vosotros: "apremiaréis",
			Uds: "apremiarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "apremie",
			tú: "apremies",
			Ud: "apremie",
			nosotros: "apremiemos",
			vosotros: "apremiéis",
			Uds: "apremien",
		},
		Imperfect: {
			yo: "apremiara",
			tú: "apremiaras",
			Ud: "apremiara",
			nosotros: "apremiáramos",
			vosotros: "apremiarais",
			Uds: "apremiaran",
		},
		Imperfect2: {
			yo: "apremiase",
			tú: "apremiases",
			Ud: "apremiase",
			nosotros: "apremiásemos",
			vosotros: "apremiaseis",
			Uds: "apremiasen",
		},
		Future: {
			yo: "apremiare",
			tú: "apremiares",
			Ud: "apremiare",
			nosotros: "apremiáremos",
			vosotros: "apremiareis",
			Uds: "apremiaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "apremia",
			Ud: "apremie",
			nosotros: "apremiemos",
			vosotros: "apremiad",
			Uds: "apremien",
		},
		Negative: {
			tú: "no apremies",
			Ud: "no apremie",
			nosotros: "no apremiemos",
			vosotros: "no apremiéis",
			Uds: "no apremien",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy apremiando",
			tú: "estás apremiando",
			Ud: "está apremiando",
			nosotros: "estamos apremiando",
			vosotros: "estáis apremiando",
			Uds: "están apremiando",
		},
		Preterite: {
			yo: "estuve apremiando",
			tú: "estuviste apremiando",
			Ud: "estuvo apremiando",
			nosotros: "estuvimos apremiando",
			vosotros: "estuvisteis apremiando",
			Uds: "estuvieron apremiando",
		},
		Imperfect: {
			Uds: "estaban apremiando",
			yo: "estaba apremiando",
			tú: "estabas apremiando",
			Ud: "estaba apremiando",
			nosotros: "estábamos apremiando",
			vosotros: "estabais apremiando",
		},
		Conditional: {
			yo: "estaría apremiando",
			tú: "estarías apremiando",
			Ud: "estaría apremiando",
			nosotros: "estaríamos apremiando",
			vosotros: "estaríais apremiando",
			Uds: "estarían apremiando",
		},
		Future: {
			yo: "estaré apremiando",
			tú: "estarás apremiando",
			Ud: "estará apremiando",
			nosotros: "estaremos apremiando",
			vosotros: "estaréis apremiando",
			Uds: "estarán apremiando",
		},
	},
	Perfect: {
		Present: {
			yo: "he apremiado",
			tú: "has apremiado",
			Ud: "ha apremiado",
			nosotros: "hemos apremiado",
			vosotros: "habéis apremiado",
			Uds: "han apremiado",
		},
		Preterite: {
			yo: "hube apremiado",
			tú: "hubiste apremiado",
			Ud: "hubo apremiado",
			nosotros: "hubimos apremiado",
			vosotros: "hubisteis apremiado",
			Uds: "hubieron apremiado",
		},
		Past: {
			yo: "había apremiado",
			tú: "habías apremiado",
			Ud: "había apremiado",
			nosotros: "habíamos apremiado",
			vosotros: "habíais apremiado",
			Uds: "habían apremiado",
		},
		Conditional: {
			yo: "habría apremiado",
			tú: "habrías apremiado",
			Ud: "habría apremiado",
			nosotros: "habríamos apremiado",
			vosotros: "habríais apremiado",
			Uds: "habrían apremiado",
		},
		Future: {
			yo: "habré apremiado",
			tú: "habrás apremiado",
			Ud: "habrá apremiado",
			nosotros: "habremos apremiado",
			vosotros: "habréis apremiado",
			Uds: "habrán apremiado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya apremiado",
			tú: "hayas apremiado",
			Ud: "haya apremiado",
			nosotros: "hayamos apremiado",
			vosotros: "hayáis apremiado",
			Uds: "hayan apremiado",
		},
		Past: {
			yo: "hubiera apremiado",
			tú: "hubieras apremiado",
			Ud: "hubiera apremiado",
			nosotros: "hubiéramos apremiado",
			vosotros: "hubierais apremiado",
			Uds: "hubieran apremiado",
		},
		Future: {
			yo: "hubiere apremiado",
			tú: "hubieres apremiado",
			Ud: "hubiere apremiado",
			nosotros: "hubiéremos apremiado",
			vosotros: "hubiereis apremiado",
			Uds: "hubieren apremiado",
		},
	},
}
