var aprobar = {
	Indicative: {
		Present: {
			yo: "apruebo",
			tú: "apruebas",
			Ud: "aprueba",
			nosotros: "aprobamos",
			vosotros: "aprobáis",
			Uds: "aprueban",
		},
		Preterite: {
			yo: "aprobé",
			tú: "aprobaste",
			Ud: "aprobó",
			nosotros: "aprobamos",
			vosotros: "aprobasteis",
			Uds: "aprobaron",
		},
		Imperfect: {
			yo: "aprobaba",
			tú: "aprobabas",
			Ud: "aprobaba",
			nosotros: "aprobábamos",
			vosotros: "aprobabais",
			Uds: "aprobaban",
		},
		Conditional: {
			yo: "aprobaría",
			tú: "aprobarías",
			Ud: "aprobaría",
			nosotros: "aprobaríamos",
			vosotros: "aprobaríais",
			Uds: "aprobarían",
		},
		Future: {
			yo: "aprobaré",
			tú: "aprobarás",
			Ud: "aprobará",
			nosotros: "aprobaremos",
			vosotros: "aprobaréis",
			Uds: "aprobarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "apruebe",
			tú: "apruebes",
			Ud: "apruebe",
			nosotros: "aprobemos",
			vosotros: "aprobéis",
			Uds: "aprueben",
		},
		Imperfect: {
			yo: "aprobara",
			tú: "aprobaras",
			Ud: "aprobara",
			nosotros: "aprobáramos",
			vosotros: "aprobarais",
			Uds: "aprobaran",
		},
		Imperfect2: {
			yo: "aprobase",
			tú: "aprobases",
			Ud: "aprobase",
			nosotros: "aprobásemos",
			vosotros: "aprobaseis",
			Uds: "aprobasen",
		},
		Future: {
			yo: "aprobare",
			tú: "aprobares",
			Ud: "aprobare",
			nosotros: "aprobáremos",
			vosotros: "aprobareis",
			Uds: "aprobaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "aprueba",
			Ud: "apruebe",
			nosotros: "aprobemos",
			vosotros: "aprobad",
			Uds: "aprueben",
		},
		Negative: {
			tú: "no apruebes",
			Ud: "no apruebe",
			nosotros: "no aprobemos",
			vosotros: "no aprobéis",
			Uds: "no aprueben",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy aprobando",
			tú: "estás aprobando",
			Ud: "está aprobando",
			nosotros: "estamos aprobando",
			vosotros: "estáis aprobando",
			Uds: "están aprobando",
		},
		Preterite: {
			yo: "estuve aprobando",
			tú: "estuviste aprobando",
			Ud: "estuvo aprobando",
			nosotros: "estuvimos aprobando",
			vosotros: "estuvisteis aprobando",
			Uds: "estuvieron aprobando",
		},
		Imperfect: {
			Uds: "estaban aprobando",
			yo: "estaba aprobando",
			tú: "estabas aprobando",
			Ud: "estaba aprobando",
			nosotros: "estábamos aprobando",
			vosotros: "estabais aprobando",
		},
		Conditional: {
			yo: "estaría aprobando",
			tú: "estarías aprobando",
			Ud: "estaría aprobando",
			nosotros: "estaríamos aprobando",
			vosotros: "estaríais aprobando",
			Uds: "estarían aprobando",
		},
		Future: {
			yo: "estaré aprobando",
			tú: "estarás aprobando",
			Ud: "estará aprobando",
			nosotros: "estaremos aprobando",
			vosotros: "estaréis aprobando",
			Uds: "estarán aprobando",
		},
	},
	Perfect: {
		Present: {
			yo: "he aprobado",
			tú: "has aprobado",
			Ud: "ha aprobado",
			nosotros: "hemos aprobado",
			vosotros: "habéis aprobado",
			Uds: "han aprobado",
		},
		Preterite: {
			yo: "hube aprobado",
			tú: "hubiste aprobado",
			Ud: "hubo aprobado",
			nosotros: "hubimos aprobado",
			vosotros: "hubisteis aprobado",
			Uds: "hubieron aprobado",
		},
		Past: {
			yo: "había aprobado",
			tú: "habías aprobado",
			Ud: "había aprobado",
			nosotros: "habíamos aprobado",
			vosotros: "habíais aprobado",
			Uds: "habían aprobado",
		},
		Conditional: {
			yo: "habría aprobado",
			tú: "habrías aprobado",
			Ud: "habría aprobado",
			nosotros: "habríamos aprobado",
			vosotros: "habríais aprobado",
			Uds: "habrían aprobado",
		},
		Future: {
			yo: "habré aprobado",
			tú: "habrás aprobado",
			Ud: "habrá aprobado",
			nosotros: "habremos aprobado",
			vosotros: "habréis aprobado",
			Uds: "habrán aprobado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya aprobado",
			tú: "hayas aprobado",
			Ud: "haya aprobado",
			nosotros: "hayamos aprobado",
			vosotros: "hayáis aprobado",
			Uds: "hayan aprobado",
		},
		Past: {
			yo: "hubiera aprobado",
			tú: "hubieras aprobado",
			Ud: "hubiera aprobado",
			nosotros: "hubiéramos aprobado",
			vosotros: "hubierais aprobado",
			Uds: "hubieran aprobado",
		},
		Future: {
			yo: "hubiere aprobado",
			tú: "hubieres aprobado",
			Ud: "hubiere aprobado",
			nosotros: "hubiéremos aprobado",
			vosotros: "hubiereis aprobado",
			Uds: "hubieren aprobado",
		},
	},
}
