var aproximar = {
	Indicative: {
		Present: {
			yo: "aproximo",
			tú: "aproximas",
			Ud: "aproxima",
			nosotros: "aproximamos",
			vosotros: "aproximáis",
			Uds: "aproximan",
		},
		Preterite: {
			yo: "aproximé",
			tú: "aproximaste",
			Ud: "aproximó",
			nosotros: "aproximamos",
			vosotros: "aproximasteis",
			Uds: "aproximaron",
		},
		Imperfect: {
			yo: "aproximaba",
			tú: "aproximabas",
			Ud: "aproximaba",
			nosotros: "aproximábamos",
			vosotros: "aproximabais",
			Uds: "aproximaban",
		},
		Conditional: {
			yo: "aproximaría",
			tú: "aproximarías",
			Ud: "aproximaría",
			nosotros: "aproximaríamos",
			vosotros: "aproximaríais",
			Uds: "aproximarían",
		},
		Future: {
			yo: "aproximaré",
			tú: "aproximarás",
			Ud: "aproximará",
			nosotros: "aproximaremos",
			vosotros: "aproximaréis",
			Uds: "aproximarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "aproxime",
			tú: "aproximes",
			Ud: "aproxime",
			nosotros: "aproximemos",
			vosotros: "aproximéis",
			Uds: "aproximen",
		},
		Imperfect: {
			yo: "aproximara",
			tú: "aproximaras",
			Ud: "aproximara",
			nosotros: "aproximáramos",
			vosotros: "aproximarais",
			Uds: "aproximaran",
		},
		Imperfect2: {
			yo: "aproximase",
			tú: "aproximases",
			Ud: "aproximase",
			nosotros: "aproximásemos",
			vosotros: "aproximaseis",
			Uds: "aproximasen",
		},
		Future: {
			yo: "aproximare",
			tú: "aproximares",
			Ud: "aproximare",
			nosotros: "aproximáremos",
			vosotros: "aproximareis",
			Uds: "aproximaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "aproxima",
			Ud: "aproxime",
			nosotros: "aproximemos",
			vosotros: "aproximad",
			Uds: "aproximen",
		},
		Negative: {
			tú: "no aproximes",
			Ud: "no aproxime",
			nosotros: "no aproximemos",
			vosotros: "no aproximéis",
			Uds: "no aproximen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy aproximando",
			tú: "estás aproximando",
			Ud: "está aproximando",
			nosotros: "estamos aproximando",
			vosotros: "estáis aproximando",
			Uds: "están aproximando",
		},
		Preterite: {
			yo: "estuve aproximando",
			tú: "estuviste aproximando",
			Ud: "estuvo aproximando",
			nosotros: "estuvimos aproximando",
			vosotros: "estuvisteis aproximando",
			Uds: "estuvieron aproximando",
		},
		Imperfect: {
			Uds: "estaban aproximando",
			yo: "estaba aproximando",
			tú: "estabas aproximando",
			Ud: "estaba aproximando",
			nosotros: "estábamos aproximando",
			vosotros: "estabais aproximando",
		},
		Conditional: {
			yo: "estaría aproximando",
			tú: "estarías aproximando",
			Ud: "estaría aproximando",
			nosotros: "estaríamos aproximando",
			vosotros: "estaríais aproximando",
			Uds: "estarían aproximando",
		},
		Future: {
			yo: "estaré aproximando",
			tú: "estarás aproximando",
			Ud: "estará aproximando",
			nosotros: "estaremos aproximando",
			vosotros: "estaréis aproximando",
			Uds: "estarán aproximando",
		},
	},
	Perfect: {
		Present: {
			yo: "he aproximado",
			tú: "has aproximado",
			Ud: "ha aproximado",
			nosotros: "hemos aproximado",
			vosotros: "habéis aproximado",
			Uds: "han aproximado",
		},
		Preterite: {
			yo: "hube aproximado",
			tú: "hubiste aproximado",
			Ud: "hubo aproximado",
			nosotros: "hubimos aproximado",
			vosotros: "hubisteis aproximado",
			Uds: "hubieron aproximado",
		},
		Past: {
			yo: "había aproximado",
			tú: "habías aproximado",
			Ud: "había aproximado",
			nosotros: "habíamos aproximado",
			vosotros: "habíais aproximado",
			Uds: "habían aproximado",
		},
		Conditional: {
			yo: "habría aproximado",
			tú: "habrías aproximado",
			Ud: "habría aproximado",
			nosotros: "habríamos aproximado",
			vosotros: "habríais aproximado",
			Uds: "habrían aproximado",
		},
		Future: {
			yo: "habré aproximado",
			tú: "habrás aproximado",
			Ud: "habrá aproximado",
			nosotros: "habremos aproximado",
			vosotros: "habréis aproximado",
			Uds: "habrán aproximado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya aproximado",
			tú: "hayas aproximado",
			Ud: "haya aproximado",
			nosotros: "hayamos aproximado",
			vosotros: "hayáis aproximado",
			Uds: "hayan aproximado",
		},
		Past: {
			yo: "hubiera aproximado",
			tú: "hubieras aproximado",
			Ud: "hubiera aproximado",
			nosotros: "hubiéramos aproximado",
			vosotros: "hubierais aproximado",
			Uds: "hubieran aproximado",
		},
		Future: {
			yo: "hubiere aproximado",
			tú: "hubieres aproximado",
			Ud: "hubiere aproximado",
			nosotros: "hubiéremos aproximado",
			vosotros: "hubiereis aproximado",
			Uds: "hubieren aproximado",
		},
	},
}
