var apuntar = {
	Indicative: {
		Present: {
			yo: "apunto",
			tú: "apuntas",
			Ud: "apunta",
			nosotros: "apuntamos",
			vosotros: "apuntáis",
			Uds: "apuntan",
		},
		Preterite: {
			yo: "apunté",
			tú: "apuntaste",
			Ud: "apuntó",
			nosotros: "apuntamos",
			vosotros: "apuntasteis",
			Uds: "apuntaron",
		},
		Imperfect: {
			yo: "apuntaba",
			tú: "apuntabas",
			Ud: "apuntaba",
			nosotros: "apuntábamos",
			vosotros: "apuntabais",
			Uds: "apuntaban",
		},
		Conditional: {
			yo: "apuntaría",
			tú: "apuntarías",
			Ud: "apuntaría",
			nosotros: "apuntaríamos",
			vosotros: "apuntaríais",
			Uds: "apuntarían",
		},
		Future: {
			yo: "apuntaré",
			tú: "apuntarás",
			Ud: "apuntará",
			nosotros: "apuntaremos",
			vosotros: "apuntaréis",
			Uds: "apuntarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "apunte",
			tú: "apuntes",
			Ud: "apunte",
			nosotros: "apuntemos",
			vosotros: "apuntéis",
			Uds: "apunten",
		},
		Imperfect: {
			yo: "apuntara",
			tú: "apuntaras",
			Ud: "apuntara",
			nosotros: "apuntáramos",
			vosotros: "apuntarais",
			Uds: "apuntaran",
		},
		Imperfect2: {
			yo: "apuntase",
			tú: "apuntases",
			Ud: "apuntase",
			nosotros: "apuntásemos",
			vosotros: "apuntaseis",
			Uds: "apuntasen",
		},
		Future: {
			yo: "apuntare",
			tú: "apuntares",
			Ud: "apuntare",
			nosotros: "apuntáremos",
			vosotros: "apuntareis",
			Uds: "apuntaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "apunta",
			Ud: "apunte",
			nosotros: "apuntemos",
			vosotros: "apuntad",
			Uds: "apunten",
		},
		Negative: {
			tú: "no apuntes",
			Ud: "no apunte",
			nosotros: "no apuntemos",
			vosotros: "no apuntéis",
			Uds: "no apunten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy apuntando",
			tú: "estás apuntando",
			Ud: "está apuntando",
			nosotros: "estamos apuntando",
			vosotros: "estáis apuntando",
			Uds: "están apuntando",
		},
		Preterite: {
			yo: "estuve apuntando",
			tú: "estuviste apuntando",
			Ud: "estuvo apuntando",
			nosotros: "estuvimos apuntando",
			vosotros: "estuvisteis apuntando",
			Uds: "estuvieron apuntando",
		},
		Imperfect: {
			Uds: "estaban apuntando",
			yo: "estaba apuntando",
			tú: "estabas apuntando",
			Ud: "estaba apuntando",
			nosotros: "estábamos apuntando",
			vosotros: "estabais apuntando",
		},
		Conditional: {
			yo: "estaría apuntando",
			tú: "estarías apuntando",
			Ud: "estaría apuntando",
			nosotros: "estaríamos apuntando",
			vosotros: "estaríais apuntando",
			Uds: "estarían apuntando",
		},
		Future: {
			yo: "estaré apuntando",
			tú: "estarás apuntando",
			Ud: "estará apuntando",
			nosotros: "estaremos apuntando",
			vosotros: "estaréis apuntando",
			Uds: "estarán apuntando",
		},
	},
	Perfect: {
		Present: {
			yo: "he apuntado",
			tú: "has apuntado",
			Ud: "ha apuntado",
			nosotros: "hemos apuntado",
			vosotros: "habéis apuntado",
			Uds: "han apuntado",
		},
		Preterite: {
			yo: "hube apuntado",
			tú: "hubiste apuntado",
			Ud: "hubo apuntado",
			nosotros: "hubimos apuntado",
			vosotros: "hubisteis apuntado",
			Uds: "hubieron apuntado",
		},
		Past: {
			yo: "había apuntado",
			tú: "habías apuntado",
			Ud: "había apuntado",
			nosotros: "habíamos apuntado",
			vosotros: "habíais apuntado",
			Uds: "habían apuntado",
		},
		Conditional: {
			yo: "habría apuntado",
			tú: "habrías apuntado",
			Ud: "habría apuntado",
			nosotros: "habríamos apuntado",
			vosotros: "habríais apuntado",
			Uds: "habrían apuntado",
		},
		Future: {
			yo: "habré apuntado",
			tú: "habrás apuntado",
			Ud: "habrá apuntado",
			nosotros: "habremos apuntado",
			vosotros: "habréis apuntado",
			Uds: "habrán apuntado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya apuntado",
			tú: "hayas apuntado",
			Ud: "haya apuntado",
			nosotros: "hayamos apuntado",
			vosotros: "hayáis apuntado",
			Uds: "hayan apuntado",
		},
		Past: {
			yo: "hubiera apuntado",
			tú: "hubieras apuntado",
			Ud: "hubiera apuntado",
			nosotros: "hubiéramos apuntado",
			vosotros: "hubierais apuntado",
			Uds: "hubieran apuntado",
		},
		Future: {
			yo: "hubiere apuntado",
			tú: "hubieres apuntado",
			Ud: "hubiere apuntado",
			nosotros: "hubiéremos apuntado",
			vosotros: "hubiereis apuntado",
			Uds: "hubieren apuntado",
		},
	},
}
