var apuñalar = {
	Indicative: {
		Present: {
			yo: "apuñalo",
			tú: "apuñalas",
			Ud: "apuñala",
			nosotros: "apuñalamos",
			vosotros: "apuñaláis",
			Uds: "apuñalan",
		},
		Preterite: {
			yo: "apuñalé",
			tú: "apuñalaste",
			Ud: "apuñaló",
			nosotros: "apuñalamos",
			vosotros: "apuñalasteis",
			Uds: "apuñalaron",
		},
		Imperfect: {
			yo: "apuñalaba",
			tú: "apuñalabas",
			Ud: "apuñalaba",
			nosotros: "apuñalábamos",
			vosotros: "apuñalabais",
			Uds: "apuñalaban",
		},
		Conditional: {
			yo: "apuñalaría",
			tú: "apuñalarías",
			Ud: "apuñalaría",
			nosotros: "apuñalaríamos",
			vosotros: "apuñalaríais",
			Uds: "apuñalarían",
		},
		Future: {
			yo: "apuñalaré",
			tú: "apuñalarás",
			Ud: "apuñalará",
			nosotros: "apuñalaremos",
			vosotros: "apuñalaréis",
			Uds: "apuñalarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "apuñale",
			tú: "apuñales",
			Ud: "apuñale",
			nosotros: "apuñalemos",
			vosotros: "apuñaléis",
			Uds: "apuñalen",
		},
		Imperfect: {
			yo: "apuñalara",
			tú: "apuñalaras",
			Ud: "apuñalara",
			nosotros: "apuñaláramos",
			vosotros: "apuñalarais",
			Uds: "apuñalaran",
		},
		Imperfect2: {
			yo: "apuñalase",
			tú: "apuñalases",
			Ud: "apuñalase",
			nosotros: "apuñalásemos",
			vosotros: "apuñalaseis",
			Uds: "apuñalasen",
		},
		Future: {
			yo: "apuñalare",
			tú: "apuñalares",
			Ud: "apuñalare",
			nosotros: "apuñaláremos",
			vosotros: "apuñalareis",
			Uds: "apuñalaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "apuñala",
			Ud: "apuñale",
			nosotros: "apuñalemos",
			vosotros: "apuñalad",
			Uds: "apuñalen",
		},
		Negative: {
			tú: "no apuñales",
			Ud: "no apuñale",
			nosotros: "no apuñalemos",
			vosotros: "no apuñaléis",
			Uds: "no apuñalen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy apuñalando",
			tú: "estás apuñalando",
			Ud: "está apuñalando",
			nosotros: "estamos apuñalando",
			vosotros: "estáis apuñalando",
			Uds: "están apuñalando",
		},
		Preterite: {
			yo: "estuve apuñalando",
			tú: "estuviste apuñalando",
			Ud: "estuvo apuñalando",
			nosotros: "estuvimos apuñalando",
			vosotros: "estuvisteis apuñalando",
			Uds: "estuvieron apuñalando",
		},
		Imperfect: {
			Uds: "estaban apuñalando",
			yo: "estaba apuñalando",
			tú: "estabas apuñalando",
			Ud: "estaba apuñalando",
			nosotros: "estábamos apuñalando",
			vosotros: "estabais apuñalando",
		},
		Conditional: {
			yo: "estaría apuñalando",
			tú: "estarías apuñalando",
			Ud: "estaría apuñalando",
			nosotros: "estaríamos apuñalando",
			vosotros: "estaríais apuñalando",
			Uds: "estarían apuñalando",
		},
		Future: {
			yo: "estaré apuñalando",
			tú: "estarás apuñalando",
			Ud: "estará apuñalando",
			nosotros: "estaremos apuñalando",
			vosotros: "estaréis apuñalando",
			Uds: "estarán apuñalando",
		},
	},
	Perfect: {
		Present: {
			yo: "he apuñalado",
			tú: "has apuñalado",
			Ud: "ha apuñalado",
			nosotros: "hemos apuñalado",
			vosotros: "habéis apuñalado",
			Uds: "han apuñalado",
		},
		Preterite: {
			yo: "hube apuñalado",
			tú: "hubiste apuñalado",
			Ud: "hubo apuñalado",
			nosotros: "hubimos apuñalado",
			vosotros: "hubisteis apuñalado",
			Uds: "hubieron apuñalado",
		},
		Past: {
			yo: "había apuñalado",
			tú: "habías apuñalado",
			Ud: "había apuñalado",
			nosotros: "habíamos apuñalado",
			vosotros: "habíais apuñalado",
			Uds: "habían apuñalado",
		},
		Conditional: {
			yo: "habría apuñalado",
			tú: "habrías apuñalado",
			Ud: "habría apuñalado",
			nosotros: "habríamos apuñalado",
			vosotros: "habríais apuñalado",
			Uds: "habrían apuñalado",
		},
		Future: {
			yo: "habré apuñalado",
			tú: "habrás apuñalado",
			Ud: "habrá apuñalado",
			nosotros: "habremos apuñalado",
			vosotros: "habréis apuñalado",
			Uds: "habrán apuñalado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya apuñalado",
			tú: "hayas apuñalado",
			Ud: "haya apuñalado",
			nosotros: "hayamos apuñalado",
			vosotros: "hayáis apuñalado",
			Uds: "hayan apuñalado",
		},
		Past: {
			yo: "hubiera apuñalado",
			tú: "hubieras apuñalado",
			Ud: "hubiera apuñalado",
			nosotros: "hubiéramos apuñalado",
			vosotros: "hubierais apuñalado",
			Uds: "hubieran apuñalado",
		},
		Future: {
			yo: "hubiere apuñalado",
			tú: "hubieres apuñalado",
			Ud: "hubiere apuñalado",
			nosotros: "hubiéremos apuñalado",
			vosotros: "hubiereis apuñalado",
			Uds: "hubieren apuñalado",
		},
	},
}
