var aquejar = {
	Indicative: {
		Present: {
			yo: "aquejo",
			tú: "aquejas",
			Ud: "aqueja",
			nosotros: "aquejamos",
			vosotros: "aquejáis",
			Uds: "aquejan",
		},
		Preterite: {
			yo: "aquejé",
			tú: "aquejaste",
			Ud: "aquejó",
			nosotros: "aquejamos",
			vosotros: "aquejasteis",
			Uds: "aquejaron",
		},
		Imperfect: {
			yo: "aquejaba",
			tú: "aquejabas",
			Ud: "aquejaba",
			nosotros: "aquejábamos",
			vosotros: "aquejabais",
			Uds: "aquejaban",
		},
		Conditional: {
			yo: "aquejaría",
			tú: "aquejarías",
			Ud: "aquejaría",
			nosotros: "aquejaríamos",
			vosotros: "aquejaríais",
			Uds: "aquejarían",
		},
		Future: {
			yo: "aquejaré",
			tú: "aquejarás",
			Ud: "aquejará",
			nosotros: "aquejaremos",
			vosotros: "aquejaréis",
			Uds: "aquejarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "aqueje",
			tú: "aquejes",
			Ud: "aqueje",
			nosotros: "aquejemos",
			vosotros: "aquejéis",
			Uds: "aquejen",
		},
		Imperfect: {
			yo: "aquejara",
			tú: "aquejaras",
			Ud: "aquejara",
			nosotros: "aquejáramos",
			vosotros: "aquejarais",
			Uds: "aquejaran",
		},
		Imperfect2: {
			yo: "aquejase",
			tú: "aquejases",
			Ud: "aquejase",
			nosotros: "aquejásemos",
			vosotros: "aquejaseis",
			Uds: "aquejasen",
		},
		Future: {
			yo: "aquejare",
			tú: "aquejares",
			Ud: "aquejare",
			nosotros: "aquejáremos",
			vosotros: "aquejareis",
			Uds: "aquejaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "aqueja",
			Ud: "aqueje",
			nosotros: "aquejemos",
			vosotros: "aquejad",
			Uds: "aquejen",
		},
		Negative: {
			tú: "no aquejes",
			Ud: "no aqueje",
			nosotros: "no aquejemos",
			vosotros: "no aquejéis",
			Uds: "no aquejen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy aquejando",
			tú: "estás aquejando",
			Ud: "está aquejando",
			nosotros: "estamos aquejando",
			vosotros: "estáis aquejando",
			Uds: "están aquejando",
		},
		Preterite: {
			yo: "estuve aquejando",
			tú: "estuviste aquejando",
			Ud: "estuvo aquejando",
			nosotros: "estuvimos aquejando",
			vosotros: "estuvisteis aquejando",
			Uds: "estuvieron aquejando",
		},
		Imperfect: {
			Uds: "estaban aquejando",
			yo: "estaba aquejando",
			tú: "estabas aquejando",
			Ud: "estaba aquejando",
			nosotros: "estábamos aquejando",
			vosotros: "estabais aquejando",
		},
		Conditional: {
			yo: "estaría aquejando",
			tú: "estarías aquejando",
			Ud: "estaría aquejando",
			nosotros: "estaríamos aquejando",
			vosotros: "estaríais aquejando",
			Uds: "estarían aquejando",
		},
		Future: {
			yo: "estaré aquejando",
			tú: "estarás aquejando",
			Ud: "estará aquejando",
			nosotros: "estaremos aquejando",
			vosotros: "estaréis aquejando",
			Uds: "estarán aquejando",
		},
	},
	Perfect: {
		Present: {
			yo: "he aquejado",
			tú: "has aquejado",
			Ud: "ha aquejado",
			nosotros: "hemos aquejado",
			vosotros: "habéis aquejado",
			Uds: "han aquejado",
		},
		Preterite: {
			yo: "hube aquejado",
			tú: "hubiste aquejado",
			Ud: "hubo aquejado",
			nosotros: "hubimos aquejado",
			vosotros: "hubisteis aquejado",
			Uds: "hubieron aquejado",
		},
		Past: {
			yo: "había aquejado",
			tú: "habías aquejado",
			Ud: "había aquejado",
			nosotros: "habíamos aquejado",
			vosotros: "habíais aquejado",
			Uds: "habían aquejado",
		},
		Conditional: {
			yo: "habría aquejado",
			tú: "habrías aquejado",
			Ud: "habría aquejado",
			nosotros: "habríamos aquejado",
			vosotros: "habríais aquejado",
			Uds: "habrían aquejado",
		},
		Future: {
			yo: "habré aquejado",
			tú: "habrás aquejado",
			Ud: "habrá aquejado",
			nosotros: "habremos aquejado",
			vosotros: "habréis aquejado",
			Uds: "habrán aquejado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya aquejado",
			tú: "hayas aquejado",
			Ud: "haya aquejado",
			nosotros: "hayamos aquejado",
			vosotros: "hayáis aquejado",
			Uds: "hayan aquejado",
		},
		Past: {
			yo: "hubiera aquejado",
			tú: "hubieras aquejado",
			Ud: "hubiera aquejado",
			nosotros: "hubiéramos aquejado",
			vosotros: "hubierais aquejado",
			Uds: "hubieran aquejado",
		},
		Future: {
			yo: "hubiere aquejado",
			tú: "hubieres aquejado",
			Ud: "hubiere aquejado",
			nosotros: "hubiéremos aquejado",
			vosotros: "hubiereis aquejado",
			Uds: "hubieren aquejado",
		},
	},
}
