var arbitrar = {
	Indicative: {
		Present: {
			yo: "arbitro",
			tú: "arbitras",
			Ud: "arbitra",
			nosotros: "arbitramos",
			vosotros: "arbitráis",
			Uds: "arbitran",
		},
		Preterite: {
			yo: "arbitré",
			tú: "arbitraste",
			Ud: "arbitró",
			nosotros: "arbitramos",
			vosotros: "arbitrasteis",
			Uds: "arbitraron",
		},
		Imperfect: {
			yo: "arbitraba",
			tú: "arbitrabas",
			Ud: "arbitraba",
			nosotros: "arbitrábamos",
			vosotros: "arbitrabais",
			Uds: "arbitraban",
		},
		Conditional: {
			yo: "arbitraría",
			tú: "arbitrarías",
			Ud: "arbitraría",
			nosotros: "arbitraríamos",
			vosotros: "arbitraríais",
			Uds: "arbitrarían",
		},
		Future: {
			yo: "arbitraré",
			tú: "arbitrarás",
			Ud: "arbitrará",
			nosotros: "arbitraremos",
			vosotros: "arbitraréis",
			Uds: "arbitrarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "arbitre",
			tú: "arbitres",
			Ud: "arbitre",
			nosotros: "arbitremos",
			vosotros: "arbitréis",
			Uds: "arbitren",
		},
		Imperfect: {
			yo: "arbitrara",
			tú: "arbitraras",
			Ud: "arbitrara",
			nosotros: "arbitráramos",
			vosotros: "arbitrarais",
			Uds: "arbitraran",
		},
		Imperfect2: {
			yo: "arbitrase",
			tú: "arbitrases",
			Ud: "arbitrase",
			nosotros: "arbitrásemos",
			vosotros: "arbitraseis",
			Uds: "arbitrasen",
		},
		Future: {
			yo: "arbitrare",
			tú: "arbitrares",
			Ud: "arbitrare",
			nosotros: "arbitráremos",
			vosotros: "arbitrareis",
			Uds: "arbitraren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "arbitra",
			Ud: "arbitre",
			nosotros: "arbitremos",
			vosotros: "arbitrad",
			Uds: "arbitren",
		},
		Negative: {
			tú: "no arbitres",
			Ud: "no arbitre",
			nosotros: "no arbitremos",
			vosotros: "no arbitréis",
			Uds: "no arbitren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy arbitrando",
			tú: "estás arbitrando",
			Ud: "está arbitrando",
			nosotros: "estamos arbitrando",
			vosotros: "estáis arbitrando",
			Uds: "están arbitrando",
		},
		Preterite: {
			yo: "estuve arbitrando",
			tú: "estuviste arbitrando",
			Ud: "estuvo arbitrando",
			nosotros: "estuvimos arbitrando",
			vosotros: "estuvisteis arbitrando",
			Uds: "estuvieron arbitrando",
		},
		Imperfect: {
			Uds: "estaban arbitrando",
			yo: "estaba arbitrando",
			tú: "estabas arbitrando",
			Ud: "estaba arbitrando",
			nosotros: "estábamos arbitrando",
			vosotros: "estabais arbitrando",
		},
		Conditional: {
			yo: "estaría arbitrando",
			tú: "estarías arbitrando",
			Ud: "estaría arbitrando",
			nosotros: "estaríamos arbitrando",
			vosotros: "estaríais arbitrando",
			Uds: "estarían arbitrando",
		},
		Future: {
			yo: "estaré arbitrando",
			tú: "estarás arbitrando",
			Ud: "estará arbitrando",
			nosotros: "estaremos arbitrando",
			vosotros: "estaréis arbitrando",
			Uds: "estarán arbitrando",
		},
	},
	Perfect: {
		Present: {
			yo: "he arbitrado",
			tú: "has arbitrado",
			Ud: "ha arbitrado",
			nosotros: "hemos arbitrado",
			vosotros: "habéis arbitrado",
			Uds: "han arbitrado",
		},
		Preterite: {
			yo: "hube arbitrado",
			tú: "hubiste arbitrado",
			Ud: "hubo arbitrado",
			nosotros: "hubimos arbitrado",
			vosotros: "hubisteis arbitrado",
			Uds: "hubieron arbitrado",
		},
		Past: {
			yo: "había arbitrado",
			tú: "habías arbitrado",
			Ud: "había arbitrado",
			nosotros: "habíamos arbitrado",
			vosotros: "habíais arbitrado",
			Uds: "habían arbitrado",
		},
		Conditional: {
			yo: "habría arbitrado",
			tú: "habrías arbitrado",
			Ud: "habría arbitrado",
			nosotros: "habríamos arbitrado",
			vosotros: "habríais arbitrado",
			Uds: "habrían arbitrado",
		},
		Future: {
			yo: "habré arbitrado",
			tú: "habrás arbitrado",
			Ud: "habrá arbitrado",
			nosotros: "habremos arbitrado",
			vosotros: "habréis arbitrado",
			Uds: "habrán arbitrado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya arbitrado",
			tú: "hayas arbitrado",
			Ud: "haya arbitrado",
			nosotros: "hayamos arbitrado",
			vosotros: "hayáis arbitrado",
			Uds: "hayan arbitrado",
		},
		Past: {
			yo: "hubiera arbitrado",
			tú: "hubieras arbitrado",
			Ud: "hubiera arbitrado",
			nosotros: "hubiéramos arbitrado",
			vosotros: "hubierais arbitrado",
			Uds: "hubieran arbitrado",
		},
		Future: {
			yo: "hubiere arbitrado",
			tú: "hubieres arbitrado",
			Ud: "hubiere arbitrado",
			nosotros: "hubiéremos arbitrado",
			vosotros: "hubiereis arbitrado",
			Uds: "hubieren arbitrado",
		},
	},
}
