var arder = {
	Indicative: {
		Present: {
			yo: "ardo",
			tú: "ardes",
			Ud: "arde",
			nosotros: "ardemos",
			vosotros: "ardéis",
			Uds: "arden",
		},
		Preterite: {
			yo: "ardí",
			tú: "ardiste",
			Ud: "ardió",
			nosotros: "ardimos",
			vosotros: "ardisteis",
			Uds: "ardieron",
		},
		Imperfect: {
			yo: "ardía",
			tú: "ardías",
			Ud: "ardía",
			nosotros: "ardíamos",
			vosotros: "ardíais",
			Uds: "ardían",
		},
		Conditional: {
			yo: "ardería",
			tú: "arderías",
			Ud: "ardería",
			nosotros: "arderíamos",
			vosotros: "arderíais",
			Uds: "arderían",
		},
		Future: {
			yo: "arderé",
			tú: "arderás",
			Ud: "arderá",
			nosotros: "arderemos",
			vosotros: "arderéis",
			Uds: "arderán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "arda",
			tú: "ardas",
			Ud: "arda",
			nosotros: "ardamos",
			vosotros: "ardáis",
			Uds: "ardan",
		},
		Imperfect: {
			yo: "ardiera",
			tú: "ardieras",
			Ud: "ardiera",
			nosotros: "ardiéramos",
			vosotros: "ardierais",
			Uds: "ardieran",
		},
		Imperfect2: {
			yo: "ardiese",
			tú: "ardieses",
			Ud: "ardiese",
			nosotros: "ardiésemos",
			vosotros: "ardieseis",
			Uds: "ardiesen",
		},
		Future: {
			yo: "ardiere",
			tú: "ardieres",
			Ud: "ardiere",
			nosotros: "ardiéremos",
			vosotros: "ardiereis",
			Uds: "ardieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "arde",
			Ud: "arda",
			nosotros: "ardamos",
			vosotros: "arded",
			Uds: "ardan",
		},
		Negative: {
			tú: "no ardas",
			Ud: "no arda",
			nosotros: "no ardamos",
			vosotros: "no ardáis",
			Uds: "no ardan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy ardiendo",
			tú: "estás ardiendo",
			Ud: "está ardiendo",
			nosotros: "estamos ardiendo",
			vosotros: "estáis ardiendo",
			Uds: "están ardiendo",
		},
		Preterite: {
			yo: "estuve ardiendo",
			tú: "estuviste ardiendo",
			Ud: "estuvo ardiendo",
			nosotros: "estuvimos ardiendo",
			vosotros: "estuvisteis ardiendo",
			Uds: "estuvieron ardiendo",
		},
		Imperfect: {
			Uds: "estaban ardiendo",
			yo: "estaba ardiendo",
			tú: "estabas ardiendo",
			Ud: "estaba ardiendo",
			nosotros: "estábamos ardiendo",
			vosotros: "estabais ardiendo",
		},
		Conditional: {
			yo: "estaría ardiendo",
			tú: "estarías ardiendo",
			Ud: "estaría ardiendo",
			nosotros: "estaríamos ardiendo",
			vosotros: "estaríais ardiendo",
			Uds: "estarían ardiendo",
		},
		Future: {
			yo: "estaré ardiendo",
			tú: "estarás ardiendo",
			Ud: "estará ardiendo",
			nosotros: "estaremos ardiendo",
			vosotros: "estaréis ardiendo",
			Uds: "estarán ardiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he ardido",
			tú: "has ardido",
			Ud: "ha ardido",
			nosotros: "hemos ardido",
			vosotros: "habéis ardido",
			Uds: "han ardido",
		},
		Preterite: {
			yo: "hube ardido",
			tú: "hubiste ardido",
			Ud: "hubo ardido",
			nosotros: "hubimos ardido",
			vosotros: "hubisteis ardido",
			Uds: "hubieron ardido",
		},
		Past: {
			yo: "había ardido",
			tú: "habías ardido",
			Ud: "había ardido",
			nosotros: "habíamos ardido",
			vosotros: "habíais ardido",
			Uds: "habían ardido",
		},
		Conditional: {
			yo: "habría ardido",
			tú: "habrías ardido",
			Ud: "habría ardido",
			nosotros: "habríamos ardido",
			vosotros: "habríais ardido",
			Uds: "habrían ardido",
		},
		Future: {
			yo: "habré ardido",
			tú: "habrás ardido",
			Ud: "habrá ardido",
			nosotros: "habremos ardido",
			vosotros: "habréis ardido",
			Uds: "habrán ardido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya ardido",
			tú: "hayas ardido",
			Ud: "haya ardido",
			nosotros: "hayamos ardido",
			vosotros: "hayáis ardido",
			Uds: "hayan ardido",
		},
		Past: {
			yo: "hubiera ardido",
			tú: "hubieras ardido",
			Ud: "hubiera ardido",
			nosotros: "hubiéramos ardido",
			vosotros: "hubierais ardido",
			Uds: "hubieran ardido",
		},
		Future: {
			yo: "hubiere ardido",
			tú: "hubieres ardido",
			Ud: "hubiere ardido",
			nosotros: "hubiéremos ardido",
			vosotros: "hubiereis ardido",
			Uds: "hubieren ardido",
		},
	},
}
