var argumentar = {
	Indicative: {
		Present: {
			yo: "argumento",
			tú: "argumentas",
			Ud: "argumenta",
			nosotros: "argumentamos",
			vosotros: "argumentáis",
			Uds: "argumentan",
		},
		Preterite: {
			yo: "argumenté",
			tú: "argumentaste",
			Ud: "argumentó",
			nosotros: "argumentamos",
			vosotros: "argumentasteis",
			Uds: "argumentaron",
		},
		Imperfect: {
			yo: "argumentaba",
			tú: "argumentabas",
			Ud: "argumentaba",
			nosotros: "argumentábamos",
			vosotros: "argumentabais",
			Uds: "argumentaban",
		},
		Conditional: {
			yo: "argumentaría",
			tú: "argumentarías",
			Ud: "argumentaría",
			nosotros: "argumentaríamos",
			vosotros: "argumentaríais",
			Uds: "argumentarían",
		},
		Future: {
			yo: "argumentaré",
			tú: "argumentarás",
			Ud: "argumentará",
			nosotros: "argumentaremos",
			vosotros: "argumentaréis",
			Uds: "argumentarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "argumente",
			tú: "argumentes",
			Ud: "argumente",
			nosotros: "argumentemos",
			vosotros: "argumentéis",
			Uds: "argumenten",
		},
		Imperfect: {
			yo: "argumentara",
			tú: "argumentaras",
			Ud: "argumentara",
			nosotros: "argumentáramos",
			vosotros: "argumentarais",
			Uds: "argumentaran",
		},
		Imperfect2: {
			yo: "argumentase",
			tú: "argumentases",
			Ud: "argumentase",
			nosotros: "argumentásemos",
			vosotros: "argumentaseis",
			Uds: "argumentasen",
		},
		Future: {
			yo: "argumentare",
			tú: "argumentares",
			Ud: "argumentare",
			nosotros: "argumentáremos",
			vosotros: "argumentareis",
			Uds: "argumentaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "argumenta",
			Ud: "argumente",
			nosotros: "argumentemos",
			vosotros: "argumentad",
			Uds: "argumenten",
		},
		Negative: {
			tú: "no argumentes",
			Ud: "no argumente",
			nosotros: "no argumentemos",
			vosotros: "no argumentéis",
			Uds: "no argumenten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy argumentando",
			tú: "estás argumentando",
			Ud: "está argumentando",
			nosotros: "estamos argumentando",
			vosotros: "estáis argumentando",
			Uds: "están argumentando",
		},
		Preterite: {
			yo: "estuve argumentando",
			tú: "estuviste argumentando",
			Ud: "estuvo argumentando",
			nosotros: "estuvimos argumentando",
			vosotros: "estuvisteis argumentando",
			Uds: "estuvieron argumentando",
		},
		Imperfect: {
			Uds: "estaban argumentando",
			yo: "estaba argumentando",
			tú: "estabas argumentando",
			Ud: "estaba argumentando",
			nosotros: "estábamos argumentando",
			vosotros: "estabais argumentando",
		},
		Conditional: {
			yo: "estaría argumentando",
			tú: "estarías argumentando",
			Ud: "estaría argumentando",
			nosotros: "estaríamos argumentando",
			vosotros: "estaríais argumentando",
			Uds: "estarían argumentando",
		},
		Future: {
			yo: "estaré argumentando",
			tú: "estarás argumentando",
			Ud: "estará argumentando",
			nosotros: "estaremos argumentando",
			vosotros: "estaréis argumentando",
			Uds: "estarán argumentando",
		},
	},
	Perfect: {
		Present: {
			yo: "he argumentado",
			tú: "has argumentado",
			Ud: "ha argumentado",
			nosotros: "hemos argumentado",
			vosotros: "habéis argumentado",
			Uds: "han argumentado",
		},
		Preterite: {
			yo: "hube argumentado",
			tú: "hubiste argumentado",
			Ud: "hubo argumentado",
			nosotros: "hubimos argumentado",
			vosotros: "hubisteis argumentado",
			Uds: "hubieron argumentado",
		},
		Past: {
			yo: "había argumentado",
			tú: "habías argumentado",
			Ud: "había argumentado",
			nosotros: "habíamos argumentado",
			vosotros: "habíais argumentado",
			Uds: "habían argumentado",
		},
		Conditional: {
			yo: "habría argumentado",
			tú: "habrías argumentado",
			Ud: "habría argumentado",
			nosotros: "habríamos argumentado",
			vosotros: "habríais argumentado",
			Uds: "habrían argumentado",
		},
		Future: {
			yo: "habré argumentado",
			tú: "habrás argumentado",
			Ud: "habrá argumentado",
			nosotros: "habremos argumentado",
			vosotros: "habréis argumentado",
			Uds: "habrán argumentado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya argumentado",
			tú: "hayas argumentado",
			Ud: "haya argumentado",
			nosotros: "hayamos argumentado",
			vosotros: "hayáis argumentado",
			Uds: "hayan argumentado",
		},
		Past: {
			yo: "hubiera argumentado",
			tú: "hubieras argumentado",
			Ud: "hubiera argumentado",
			nosotros: "hubiéramos argumentado",
			vosotros: "hubierais argumentado",
			Uds: "hubieran argumentado",
		},
		Future: {
			yo: "hubiere argumentado",
			tú: "hubieres argumentado",
			Ud: "hubiere argumentado",
			nosotros: "hubiéremos argumentado",
			vosotros: "hubiereis argumentado",
			Uds: "hubieren argumentado",
		},
	},
}
