var armar = {
	Indicative: {
		Present: {
			yo: "armo",
			tú: "armas",
			Ud: "arma",
			nosotros: "armamos",
			vosotros: "armáis",
			Uds: "arman",
		},
		Preterite: {
			yo: "armé",
			tú: "armaste",
			Ud: "armó",
			nosotros: "armamos",
			vosotros: "armasteis",
			Uds: "armaron",
		},
		Imperfect: {
			yo: "armaba",
			tú: "armabas",
			Ud: "armaba",
			nosotros: "armábamos",
			vosotros: "armabais",
			Uds: "armaban",
		},
		Conditional: {
			yo: "armaría",
			tú: "armarías",
			Ud: "armaría",
			nosotros: "armaríamos",
			vosotros: "armaríais",
			Uds: "armarían",
		},
		Future: {
			yo: "armaré",
			tú: "armarás",
			Ud: "armará",
			nosotros: "armaremos",
			vosotros: "armaréis",
			Uds: "armarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "arme",
			tú: "armes",
			Ud: "arme",
			nosotros: "armemos",
			vosotros: "arméis",
			Uds: "armen",
		},
		Imperfect: {
			yo: "armara",
			tú: "armaras",
			Ud: "armara",
			nosotros: "armáramos",
			vosotros: "armarais",
			Uds: "armaran",
		},
		Imperfect2: {
			yo: "armase",
			tú: "armases",
			Ud: "armase",
			nosotros: "armásemos",
			vosotros: "armaseis",
			Uds: "armasen",
		},
		Future: {
			yo: "armare",
			tú: "armares",
			Ud: "armare",
			nosotros: "armáremos",
			vosotros: "armareis",
			Uds: "armaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "arma",
			Ud: "arme",
			nosotros: "armemos",
			vosotros: "armad",
			Uds: "armen",
		},
		Negative: {
			tú: "no armes",
			Ud: "no arme",
			nosotros: "no armemos",
			vosotros: "no arméis",
			Uds: "no armen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy armando",
			tú: "estás armando",
			Ud: "está armando",
			nosotros: "estamos armando",
			vosotros: "estáis armando",
			Uds: "están armando",
		},
		Preterite: {
			yo: "estuve armando",
			tú: "estuviste armando",
			Ud: "estuvo armando",
			nosotros: "estuvimos armando",
			vosotros: "estuvisteis armando",
			Uds: "estuvieron armando",
		},
		Imperfect: {
			Uds: "estaban armando",
			yo: "estaba armando",
			tú: "estabas armando",
			Ud: "estaba armando",
			nosotros: "estábamos armando",
			vosotros: "estabais armando",
		},
		Conditional: {
			yo: "estaría armando",
			tú: "estarías armando",
			Ud: "estaría armando",
			nosotros: "estaríamos armando",
			vosotros: "estaríais armando",
			Uds: "estarían armando",
		},
		Future: {
			yo: "estaré armando",
			tú: "estarás armando",
			Ud: "estará armando",
			nosotros: "estaremos armando",
			vosotros: "estaréis armando",
			Uds: "estarán armando",
		},
	},
	Perfect: {
		Present: {
			yo: "he armado",
			tú: "has armado",
			Ud: "ha armado",
			nosotros: "hemos armado",
			vosotros: "habéis armado",
			Uds: "han armado",
		},
		Preterite: {
			yo: "hube armado",
			tú: "hubiste armado",
			Ud: "hubo armado",
			nosotros: "hubimos armado",
			vosotros: "hubisteis armado",
			Uds: "hubieron armado",
		},
		Past: {
			yo: "había armado",
			tú: "habías armado",
			Ud: "había armado",
			nosotros: "habíamos armado",
			vosotros: "habíais armado",
			Uds: "habían armado",
		},
		Conditional: {
			yo: "habría armado",
			tú: "habrías armado",
			Ud: "habría armado",
			nosotros: "habríamos armado",
			vosotros: "habríais armado",
			Uds: "habrían armado",
		},
		Future: {
			yo: "habré armado",
			tú: "habrás armado",
			Ud: "habrá armado",
			nosotros: "habremos armado",
			vosotros: "habréis armado",
			Uds: "habrán armado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya armado",
			tú: "hayas armado",
			Ud: "haya armado",
			nosotros: "hayamos armado",
			vosotros: "hayáis armado",
			Uds: "hayan armado",
		},
		Past: {
			yo: "hubiera armado",
			tú: "hubieras armado",
			Ud: "hubiera armado",
			nosotros: "hubiéramos armado",
			vosotros: "hubierais armado",
			Uds: "hubieran armado",
		},
		Future: {
			yo: "hubiere armado",
			tú: "hubieres armado",
			Ud: "hubiere armado",
			nosotros: "hubiéremos armado",
			vosotros: "hubiereis armado",
			Uds: "hubieren armado",
		},
	},
}
