var arquear = {
	Indicative: {
		Present: {
			yo: "arqueo",
			tú: "arqueas",
			Ud: "arquea",
			nosotros: "arqueamos",
			vosotros: "arqueáis",
			Uds: "arquean",
		},
		Preterite: {
			yo: "arqueé",
			tú: "arqueaste",
			Ud: "arqueó",
			nosotros: "arqueamos",
			vosotros: "arqueasteis",
			Uds: "arquearon",
		},
		Imperfect: {
			yo: "arqueaba",
			tú: "arqueabas",
			Ud: "arqueaba",
			nosotros: "arqueábamos",
			vosotros: "arqueabais",
			Uds: "arqueaban",
		},
		Conditional: {
			yo: "arquearía",
			tú: "arquearías",
			Ud: "arquearía",
			nosotros: "arquearíamos",
			vosotros: "arquearíais",
			Uds: "arquearían",
		},
		Future: {
			yo: "arquearé",
			tú: "arquearás",
			Ud: "arqueará",
			nosotros: "arquearemos",
			vosotros: "arquearéis",
			Uds: "arquearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "arquee",
			tú: "arquees",
			Ud: "arquee",
			nosotros: "arqueemos",
			vosotros: "arqueéis",
			Uds: "arqueen",
		},
		Imperfect: {
			yo: "arqueara",
			tú: "arquearas",
			Ud: "arqueara",
			nosotros: "arqueáramos",
			vosotros: "arquearais",
			Uds: "arquearan",
		},
		Imperfect2: {
			yo: "arquease",
			tú: "arqueases",
			Ud: "arquease",
			nosotros: "arqueásemos",
			vosotros: "arqueaseis",
			Uds: "arqueasen",
		},
		Future: {
			yo: "arqueare",
			tú: "arqueares",
			Ud: "arqueare",
			nosotros: "arqueáremos",
			vosotros: "arqueareis",
			Uds: "arquearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "arquea",
			Ud: "arquee",
			nosotros: "arqueemos",
			vosotros: "arquead",
			Uds: "arqueen",
		},
		Negative: {
			tú: "no arquees",
			Ud: "no arquee",
			nosotros: "no arqueemos",
			vosotros: "no arqueéis",
			Uds: "no arqueen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy arqueando",
			tú: "estás arqueando",
			Ud: "está arqueando",
			nosotros: "estamos arqueando",
			vosotros: "estáis arqueando",
			Uds: "están arqueando",
		},
		Preterite: {
			yo: "estuve arqueando",
			tú: "estuviste arqueando",
			Ud: "estuvo arqueando",
			nosotros: "estuvimos arqueando",
			vosotros: "estuvisteis arqueando",
			Uds: "estuvieron arqueando",
		},
		Imperfect: {
			Uds: "estaban arqueando",
			yo: "estaba arqueando",
			tú: "estabas arqueando",
			Ud: "estaba arqueando",
			nosotros: "estábamos arqueando",
			vosotros: "estabais arqueando",
		},
		Conditional: {
			yo: "estaría arqueando",
			tú: "estarías arqueando",
			Ud: "estaría arqueando",
			nosotros: "estaríamos arqueando",
			vosotros: "estaríais arqueando",
			Uds: "estarían arqueando",
		},
		Future: {
			yo: "estaré arqueando",
			tú: "estarás arqueando",
			Ud: "estará arqueando",
			nosotros: "estaremos arqueando",
			vosotros: "estaréis arqueando",
			Uds: "estarán arqueando",
		},
	},
	Perfect: {
		Present: {
			yo: "he arqueado",
			tú: "has arqueado",
			Ud: "ha arqueado",
			nosotros: "hemos arqueado",
			vosotros: "habéis arqueado",
			Uds: "han arqueado",
		},
		Preterite: {
			yo: "hube arqueado",
			tú: "hubiste arqueado",
			Ud: "hubo arqueado",
			nosotros: "hubimos arqueado",
			vosotros: "hubisteis arqueado",
			Uds: "hubieron arqueado",
		},
		Past: {
			yo: "había arqueado",
			tú: "habías arqueado",
			Ud: "había arqueado",
			nosotros: "habíamos arqueado",
			vosotros: "habíais arqueado",
			Uds: "habían arqueado",
		},
		Conditional: {
			yo: "habría arqueado",
			tú: "habrías arqueado",
			Ud: "habría arqueado",
			nosotros: "habríamos arqueado",
			vosotros: "habríais arqueado",
			Uds: "habrían arqueado",
		},
		Future: {
			yo: "habré arqueado",
			tú: "habrás arqueado",
			Ud: "habrá arqueado",
			nosotros: "habremos arqueado",
			vosotros: "habréis arqueado",
			Uds: "habrán arqueado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya arqueado",
			tú: "hayas arqueado",
			Ud: "haya arqueado",
			nosotros: "hayamos arqueado",
			vosotros: "hayáis arqueado",
			Uds: "hayan arqueado",
		},
		Past: {
			yo: "hubiera arqueado",
			tú: "hubieras arqueado",
			Ud: "hubiera arqueado",
			nosotros: "hubiéramos arqueado",
			vosotros: "hubierais arqueado",
			Uds: "hubieran arqueado",
		},
		Future: {
			yo: "hubiere arqueado",
			tú: "hubieres arqueado",
			Ud: "hubiere arqueado",
			nosotros: "hubiéremos arqueado",
			vosotros: "hubiereis arqueado",
			Uds: "hubieren arqueado",
		},
	},
}
