var arrebatar = {
	Indicative: {
		Present: {
			yo: "me arrebato",
			tú: "te arrebatas",
			Ud: "se arrebata",
			nosotros: "nos arrebatamos",
			vosotros: "os arrebatáis",
			Uds: "se arrebatan",
		},
		Preterite: {
			yo: "me arrebaté",
			tú: "te arrebataste",
			Ud: "se arrebató",
			nosotros: "nos arrebatamos",
			vosotros: "os arrebatasteis",
			Uds: "se arrebataron",
		},
		Imperfect: {
			yo: "me arrebataba",
			tú: "te arrebatabas",
			Ud: "se arrebataba",
			nosotros: "nos arrebatábamos",
			vosotros: "os arrebatabais",
			Uds: "se arrebataban",
		},
		Conditional: {
			yo: "me arrebataría",
			tú: "te arrebatarías",
			Ud: "se arrebataría",
			nosotros: "nos arrebataríamos",
			vosotros: "os arrebataríais",
			Uds: "se arrebatarían",
		},
		Future: {
			yo: "me arrebataré",
			tú: "te arrebatarás",
			Ud: "se arrebatará",
			nosotros: "nos arrebataremos",
			vosotros: "os arrebataréis",
			Uds: "se arrebatarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "me arrebate",
			tú: "te arrebates",
			Ud: "se arrebate",
			nosotros: "nos arrebatemos",
			vosotros: "os arrebatéis",
			Uds: "se arrebaten",
		},
		Imperfect: {
			yo: "me arrebatara",
			tú: "te arrebataras",
			Ud: "se arrebatara",
			nosotros: "nos arrebatáramos",
			vosotros: "os arrebatarais",
			Uds: "se arrebataran",
		},
		Imperfect2: {
			yo: "me arrebatase",
			tú: "te arrebatases",
			Ud: "se arrebatase",
			nosotros: "nos arrebatásemos",
			vosotros: "os arrebataseis",
			Uds: "se arrebatasen",
		},
		Future: {
			yo: "me arrebatare",
			tú: "te arrebatares",
			Ud: "se arrebatare",
			nosotros: "nos arrebatáremos",
			vosotros: "os arrebatareis",
			Uds: "se arrebataren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "arrebátate",
			Ud: "arrebátese",
			nosotros: "arrebatémonos",
			vosotros: "arrebataos",
			Uds: "arrebátense",
		},
		Negative: {
			tú: "no te arrebates",
			Ud: "no se arrebate",
			nosotros: "no nos arrebatemos",
			vosotros: "no os arrebatéis",
			Uds: "no se arrebaten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "me estoy arrebatando",
			tú: "te estás arrebatando",
			Ud: "se está arrebatando",
			nosotros: "nos estamos arrebatando",
			vosotros: "os estáis arrebatando",
			Uds: "se están arrebatando",
		},
		Preterite: {
			yo: "me estuve arrebatando",
			tú: "te estuviste arrebatando",
			Ud: "se estuvo arrebatando",
			nosotros: "nos estuvimos arrebatando",
			vosotros: "os estuvisteis arrebatando",
			Uds: "se estuvieron arrebatando",
		},
		Imperfect: {
			Uds: "se estaban arrebatando",
			yo: "me estaba arrebatando",
			tú: "te estabas arrebatando",
			Ud: "se estaba arrebatando",
			nosotros: "nos estábamos arrebatando",
			vosotros: "os estabais arrebatando",
		},
		Conditional: {
			yo: "me estaría arrebatando",
			tú: "te estarías arrebatando",
			Ud: "se estaría arrebatando",
			nosotros: "nos estaríamos arrebatando",
			vosotros: "os estaríais arrebatando",
			Uds: "se estarían arrebatando",
		},
		Future: {
			yo: "me estaré arrebatando",
			tú: "te estarás arrebatando",
			Ud: "se estará arrebatando",
			nosotros: "nos estaremos arrebatando",
			vosotros: "os estaréis arrebatando",
			Uds: "se estarán arrebatando",
		},
	},
	Perfect: {
		Present: {
			yo: "me he arrebatado",
			tú: "te has arrebatado",
			Ud: "se ha arrebatado",
			nosotros: "nos hemos arrebatado",
			vosotros: "os habéis arrebatado",
			Uds: "se han arrebatado",
		},
		Preterite: {
			yo: "me hube arrebatado",
			tú: "te hubiste arrebatado",
			Ud: "se hubo arrebatado",
			nosotros: "nos hubimos arrebatado",
			vosotros: "os hubisteis arrebatado",
			Uds: "se hubieron arrebatado",
		},
		Past: {
			yo: "me había arrebatado",
			tú: "te habías arrebatado",
			Ud: "se había arrebatado",
			nosotros: "nos habíamos arrebatado",
			vosotros: "os habíais arrebatado",
			Uds: "se habían arrebatado",
		},
		Conditional: {
			yo: "me habría arrebatado",
			tú: "te habrías arrebatado",
			Ud: "se habría arrebatado",
			nosotros: "nos habríamos arrebatado",
			vosotros: "os habríais arrebatado",
			Uds: "se habrían arrebatado",
		},
		Future: {
			yo: "me habré arrebatado",
			tú: "te habrás arrebatado",
			Ud: "se habrá arrebatado",
			nosotros: "nos habremos arrebatado",
			vosotros: "os habréis arrebatado",
			Uds: "se habrán arrebatado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "me haya arrebatado",
			tú: "te hayas arrebatado",
			Ud: "se haya arrebatado",
			nosotros: "nos hayamos arrebatado",
			vosotros: "os hayáis arrebatado",
			Uds: "se hayan arrebatado",
		},
		Past: {
			yo: "me hubiera arrebatado",
			tú: "te hubieras arrebatado",
			Ud: "se hubiera arrebatado",
			nosotros: "nos hubiéramos arrebatado",
			vosotros: "os hubierais arrebatado",
			Uds: "se hubieran arrebatado",
		},
		Future: {
			yo: "me hubiere arrebatado",
			tú: "te hubieres arrebatado",
			Ud: "se hubiere arrebatado",
			nosotros: "nos hubiéremos arrebatado",
			vosotros: "os hubiereis arrebatado",
			Uds: "se hubieren arrebatado",
		},
	},
}
