var arruinar = {
	Indicative: {
		Present: {
			yo: "arruino",
			tú: "arruinas",
			Ud: "arruina",
			nosotros: "arruinamos",
			vosotros: "arruináis",
			Uds: "arruinan",
		},
		Preterite: {
			yo: "arruiné",
			tú: "arruinaste",
			Ud: "arruinó",
			nosotros: "arruinamos",
			vosotros: "arruinasteis",
			Uds: "arruinaron",
		},
		Imperfect: {
			yo: "arruinaba",
			tú: "arruinabas",
			Ud: "arruinaba",
			nosotros: "arruinábamos",
			vosotros: "arruinabais",
			Uds: "arruinaban",
		},
		Conditional: {
			yo: "arruinaría",
			tú: "arruinarías",
			Ud: "arruinaría",
			nosotros: "arruinaríamos",
			vosotros: "arruinaríais",
			Uds: "arruinarían",
		},
		Future: {
			yo: "arruinaré",
			tú: "arruinarás",
			Ud: "arruinará",
			nosotros: "arruinaremos",
			vosotros: "arruinaréis",
			Uds: "arruinarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "arruine",
			tú: "arruines",
			Ud: "arruine",
			nosotros: "arruinemos",
			vosotros: "arruinéis",
			Uds: "arruinen",
		},
		Imperfect: {
			yo: "arruinara",
			tú: "arruinaras",
			Ud: "arruinara",
			nosotros: "arruináramos",
			vosotros: "arruinarais",
			Uds: "arruinaran",
		},
		Imperfect2: {
			yo: "arruinase",
			tú: "arruinases",
			Ud: "arruinase",
			nosotros: "arruinásemos",
			vosotros: "arruinaseis",
			Uds: "arruinasen",
		},
		Future: {
			yo: "arruinare",
			tú: "arruinares",
			Ud: "arruinare",
			nosotros: "arruináremos",
			vosotros: "arruinareis",
			Uds: "arruinaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "arruina",
			Ud: "arruine",
			nosotros: "arruinemos",
			vosotros: "arruinad",
			Uds: "arruinen",
		},
		Negative: {
			tú: "no arruines",
			Ud: "no arruine",
			nosotros: "no arruinemos",
			vosotros: "no arruinéis",
			Uds: "no arruinen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy arruinando",
			tú: "estás arruinando",
			Ud: "está arruinando",
			nosotros: "estamos arruinando",
			vosotros: "estáis arruinando",
			Uds: "están arruinando",
		},
		Preterite: {
			yo: "estuve arruinando",
			tú: "estuviste arruinando",
			Ud: "estuvo arruinando",
			nosotros: "estuvimos arruinando",
			vosotros: "estuvisteis arruinando",
			Uds: "estuvieron arruinando",
		},
		Imperfect: {
			Uds: "estaban arruinando",
			yo: "estaba arruinando",
			tú: "estabas arruinando",
			Ud: "estaba arruinando",
			nosotros: "estábamos arruinando",
			vosotros: "estabais arruinando",
		},
		Conditional: {
			yo: "estaría arruinando",
			tú: "estarías arruinando",
			Ud: "estaría arruinando",
			nosotros: "estaríamos arruinando",
			vosotros: "estaríais arruinando",
			Uds: "estarían arruinando",
		},
		Future: {
			yo: "estaré arruinando",
			tú: "estarás arruinando",
			Ud: "estará arruinando",
			nosotros: "estaremos arruinando",
			vosotros: "estaréis arruinando",
			Uds: "estarán arruinando",
		},
	},
	Perfect: {
		Present: {
			yo: "he arruinado",
			tú: "has arruinado",
			Ud: "ha arruinado",
			nosotros: "hemos arruinado",
			vosotros: "habéis arruinado",
			Uds: "han arruinado",
		},
		Preterite: {
			yo: "hube arruinado",
			tú: "hubiste arruinado",
			Ud: "hubo arruinado",
			nosotros: "hubimos arruinado",
			vosotros: "hubisteis arruinado",
			Uds: "hubieron arruinado",
		},
		Past: {
			yo: "había arruinado",
			tú: "habías arruinado",
			Ud: "había arruinado",
			nosotros: "habíamos arruinado",
			vosotros: "habíais arruinado",
			Uds: "habían arruinado",
		},
		Conditional: {
			yo: "habría arruinado",
			tú: "habrías arruinado",
			Ud: "habría arruinado",
			nosotros: "habríamos arruinado",
			vosotros: "habríais arruinado",
			Uds: "habrían arruinado",
		},
		Future: {
			yo: "habré arruinado",
			tú: "habrás arruinado",
			Ud: "habrá arruinado",
			nosotros: "habremos arruinado",
			vosotros: "habréis arruinado",
			Uds: "habrán arruinado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya arruinado",
			tú: "hayas arruinado",
			Ud: "haya arruinado",
			nosotros: "hayamos arruinado",
			vosotros: "hayáis arruinado",
			Uds: "hayan arruinado",
		},
		Past: {
			yo: "hubiera arruinado",
			tú: "hubieras arruinado",
			Ud: "hubiera arruinado",
			nosotros: "hubiéramos arruinado",
			vosotros: "hubierais arruinado",
			Uds: "hubieran arruinado",
		},
		Future: {
			yo: "hubiere arruinado",
			tú: "hubieres arruinado",
			Ud: "hubiere arruinado",
			nosotros: "hubiéremos arruinado",
			vosotros: "hubiereis arruinado",
			Uds: "hubieren arruinado",
		},
	},
}
