var asegurar = {
	Indicative: {
		Present: {
			yo: "aseguro",
			tú: "aseguras",
			Ud: "asegura",
			nosotros: "aseguramos",
			vosotros: "aseguráis",
			Uds: "aseguran",
		},
		Preterite: {
			yo: "aseguré",
			tú: "aseguraste",
			Ud: "aseguró",
			nosotros: "aseguramos",
			vosotros: "asegurasteis",
			Uds: "aseguraron",
		},
		Imperfect: {
			yo: "aseguraba",
			tú: "asegurabas",
			Ud: "aseguraba",
			nosotros: "asegurábamos",
			vosotros: "asegurabais",
			Uds: "aseguraban",
		},
		Conditional: {
			yo: "aseguraría",
			tú: "asegurarías",
			Ud: "aseguraría",
			nosotros: "aseguraríamos",
			vosotros: "aseguraríais",
			Uds: "asegurarían",
		},
		Future: {
			yo: "aseguraré",
			tú: "asegurarás",
			Ud: "asegurará",
			nosotros: "aseguraremos",
			vosotros: "aseguraréis",
			Uds: "asegurarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "asegure",
			tú: "asegures",
			Ud: "asegure",
			nosotros: "aseguremos",
			vosotros: "aseguréis",
			Uds: "aseguren",
		},
		Imperfect: {
			yo: "asegurara",
			tú: "aseguraras",
			Ud: "asegurara",
			nosotros: "aseguráramos",
			vosotros: "asegurarais",
			Uds: "aseguraran",
		},
		Imperfect2: {
			yo: "asegurase",
			tú: "asegurases",
			Ud: "asegurase",
			nosotros: "asegurásemos",
			vosotros: "aseguraseis",
			Uds: "asegurasen",
		},
		Future: {
			yo: "asegurare",
			tú: "asegurares",
			Ud: "asegurare",
			nosotros: "aseguráremos",
			vosotros: "asegurareis",
			Uds: "aseguraren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "asegura",
			Ud: "asegure",
			nosotros: "aseguremos",
			vosotros: "asegurad",
			Uds: "aseguren",
		},
		Negative: {
			tú: "no asegures",
			Ud: "no asegure",
			nosotros: "no aseguremos",
			vosotros: "no aseguréis",
			Uds: "no aseguren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy asegurando",
			tú: "estás asegurando",
			Ud: "está asegurando",
			nosotros: "estamos asegurando",
			vosotros: "estáis asegurando",
			Uds: "están asegurando",
		},
		Preterite: {
			yo: "estuve asegurando",
			tú: "estuviste asegurando",
			Ud: "estuvo asegurando",
			nosotros: "estuvimos asegurando",
			vosotros: "estuvisteis asegurando",
			Uds: "estuvieron asegurando",
		},
		Imperfect: {
			Uds: "estaban asegurando",
			yo: "estaba asegurando",
			tú: "estabas asegurando",
			Ud: "estaba asegurando",
			nosotros: "estábamos asegurando",
			vosotros: "estabais asegurando",
		},
		Conditional: {
			yo: "estaría asegurando",
			tú: "estarías asegurando",
			Ud: "estaría asegurando",
			nosotros: "estaríamos asegurando",
			vosotros: "estaríais asegurando",
			Uds: "estarían asegurando",
		},
		Future: {
			yo: "estaré asegurando",
			tú: "estarás asegurando",
			Ud: "estará asegurando",
			nosotros: "estaremos asegurando",
			vosotros: "estaréis asegurando",
			Uds: "estarán asegurando",
		},
	},
	Perfect: {
		Present: {
			yo: "he asegurado",
			tú: "has asegurado",
			Ud: "ha asegurado",
			nosotros: "hemos asegurado",
			vosotros: "habéis asegurado",
			Uds: "han asegurado",
		},
		Preterite: {
			yo: "hube asegurado",
			tú: "hubiste asegurado",
			Ud: "hubo asegurado",
			nosotros: "hubimos asegurado",
			vosotros: "hubisteis asegurado",
			Uds: "hubieron asegurado",
		},
		Past: {
			yo: "había asegurado",
			tú: "habías asegurado",
			Ud: "había asegurado",
			nosotros: "habíamos asegurado",
			vosotros: "habíais asegurado",
			Uds: "habían asegurado",
		},
		Conditional: {
			yo: "habría asegurado",
			tú: "habrías asegurado",
			Ud: "habría asegurado",
			nosotros: "habríamos asegurado",
			vosotros: "habríais asegurado",
			Uds: "habrían asegurado",
		},
		Future: {
			yo: "habré asegurado",
			tú: "habrás asegurado",
			Ud: "habrá asegurado",
			nosotros: "habremos asegurado",
			vosotros: "habréis asegurado",
			Uds: "habrán asegurado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya asegurado",
			tú: "hayas asegurado",
			Ud: "haya asegurado",
			nosotros: "hayamos asegurado",
			vosotros: "hayáis asegurado",
			Uds: "hayan asegurado",
		},
		Past: {
			yo: "hubiera asegurado",
			tú: "hubieras asegurado",
			Ud: "hubiera asegurado",
			nosotros: "hubiéramos asegurado",
			vosotros: "hubierais asegurado",
			Uds: "hubieran asegurado",
		},
		Future: {
			yo: "hubiere asegurado",
			tú: "hubieres asegurado",
			Ud: "hubiere asegurado",
			nosotros: "hubiéremos asegurado",
			vosotros: "hubiereis asegurado",
			Uds: "hubieren asegurado",
		},
	},
}
