var asignar = {
	Indicative: {
		Present: {
			yo: "asigno",
			tú: "asignas",
			Ud: "asigna",
			nosotros: "asignamos",
			vosotros: "asignáis",
			Uds: "asignan",
		},
		Preterite: {
			yo: "asigné",
			tú: "asignaste",
			Ud: "asignó",
			nosotros: "asignamos",
			vosotros: "asignasteis",
			Uds: "asignaron",
		},
		Imperfect: {
			yo: "asignaba",
			tú: "asignabas",
			Ud: "asignaba",
			nosotros: "asignábamos",
			vosotros: "asignabais",
			Uds: "asignaban",
		},
		Conditional: {
			yo: "asignaría",
			tú: "asignarías",
			Ud: "asignaría",
			nosotros: "asignaríamos",
			vosotros: "asignaríais",
			Uds: "asignarían",
		},
		Future: {
			yo: "asignaré",
			tú: "asignarás",
			Ud: "asignará",
			nosotros: "asignaremos",
			vosotros: "asignaréis",
			Uds: "asignarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "asigne",
			tú: "asignes",
			Ud: "asigne",
			nosotros: "asignemos",
			vosotros: "asignéis",
			Uds: "asignen",
		},
		Imperfect: {
			yo: "asignara",
			tú: "asignaras",
			Ud: "asignara",
			nosotros: "asignáramos",
			vosotros: "asignarais",
			Uds: "asignaran",
		},
		Imperfect2: {
			yo: "asignase",
			tú: "asignases",
			Ud: "asignase",
			nosotros: "asignásemos",
			vosotros: "asignaseis",
			Uds: "asignasen",
		},
		Future: {
			yo: "asignare",
			tú: "asignares",
			Ud: "asignare",
			nosotros: "asignáremos",
			vosotros: "asignareis",
			Uds: "asignaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "asigna",
			Ud: "asigne",
			nosotros: "asignemos",
			vosotros: "asignad",
			Uds: "asignen",
		},
		Negative: {
			tú: "no asignes",
			Ud: "no asigne",
			nosotros: "no asignemos",
			vosotros: "no asignéis",
			Uds: "no asignen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy asignando",
			tú: "estás asignando",
			Ud: "está asignando",
			nosotros: "estamos asignando",
			vosotros: "estáis asignando",
			Uds: "están asignando",
		},
		Preterite: {
			yo: "estuve asignando",
			tú: "estuviste asignando",
			Ud: "estuvo asignando",
			nosotros: "estuvimos asignando",
			vosotros: "estuvisteis asignando",
			Uds: "estuvieron asignando",
		},
		Imperfect: {
			Uds: "estaban asignando",
			yo: "estaba asignando",
			tú: "estabas asignando",
			Ud: "estaba asignando",
			nosotros: "estábamos asignando",
			vosotros: "estabais asignando",
		},
		Conditional: {
			yo: "estaría asignando",
			tú: "estarías asignando",
			Ud: "estaría asignando",
			nosotros: "estaríamos asignando",
			vosotros: "estaríais asignando",
			Uds: "estarían asignando",
		},
		Future: {
			yo: "estaré asignando",
			tú: "estarás asignando",
			Ud: "estará asignando",
			nosotros: "estaremos asignando",
			vosotros: "estaréis asignando",
			Uds: "estarán asignando",
		},
	},
	Perfect: {
		Present: {
			yo: "he asignado",
			tú: "has asignado",
			Ud: "ha asignado",
			nosotros: "hemos asignado",
			vosotros: "habéis asignado",
			Uds: "han asignado",
		},
		Preterite: {
			yo: "hube asignado",
			tú: "hubiste asignado",
			Ud: "hubo asignado",
			nosotros: "hubimos asignado",
			vosotros: "hubisteis asignado",
			Uds: "hubieron asignado",
		},
		Past: {
			yo: "había asignado",
			tú: "habías asignado",
			Ud: "había asignado",
			nosotros: "habíamos asignado",
			vosotros: "habíais asignado",
			Uds: "habían asignado",
		},
		Conditional: {
			yo: "habría asignado",
			tú: "habrías asignado",
			Ud: "habría asignado",
			nosotros: "habríamos asignado",
			vosotros: "habríais asignado",
			Uds: "habrían asignado",
		},
		Future: {
			yo: "habré asignado",
			tú: "habrás asignado",
			Ud: "habrá asignado",
			nosotros: "habremos asignado",
			vosotros: "habréis asignado",
			Uds: "habrán asignado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya asignado",
			tú: "hayas asignado",
			Ud: "haya asignado",
			nosotros: "hayamos asignado",
			vosotros: "hayáis asignado",
			Uds: "hayan asignado",
		},
		Past: {
			yo: "hubiera asignado",
			tú: "hubieras asignado",
			Ud: "hubiera asignado",
			nosotros: "hubiéramos asignado",
			vosotros: "hubierais asignado",
			Uds: "hubieran asignado",
		},
		Future: {
			yo: "hubiere asignado",
			tú: "hubieres asignado",
			Ud: "hubiere asignado",
			nosotros: "hubiéremos asignado",
			vosotros: "hubiereis asignado",
			Uds: "hubieren asignado",
		},
	},
}
