var asistir = {
	Indicative: {
		Present: {
			yo: "asisto",
			tú: "asistes",
			Ud: "asiste",
			nosotros: "asistimos",
			vosotros: "asistís",
			Uds: "asisten",
		},
		Preterite: {
			yo: "asistí",
			tú: "asististe",
			Ud: "asistió",
			nosotros: "asistimos",
			vosotros: "asististeis",
			Uds: "asistieron",
		},
		Imperfect: {
			yo: "asistía",
			tú: "asistías",
			Ud: "asistía",
			nosotros: "asistíamos",
			vosotros: "asistíais",
			Uds: "asistían",
		},
		Conditional: {
			yo: "asistiría",
			tú: "asistirías",
			Ud: "asistiría",
			nosotros: "asistiríamos",
			vosotros: "asistiríais",
			Uds: "asistirían",
		},
		Future: {
			yo: "asistiré",
			tú: "asistirás",
			Ud: "asistirá",
			nosotros: "asistiremos",
			vosotros: "asistiréis",
			Uds: "asistirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "asista",
			tú: "asistas",
			Ud: "asista",
			nosotros: "asistamos",
			vosotros: "asistáis",
			Uds: "asistan",
		},
		Imperfect: {
			yo: "asistiera",
			tú: "asistieras",
			Ud: "asistiera",
			nosotros: "asistiéramos",
			vosotros: "asistierais",
			Uds: "asistieran",
		},
		Imperfect2: {
			yo: "asistiese",
			tú: "asistieses",
			Ud: "asistiese",
			nosotros: "asistiésemos",
			vosotros: "asistieseis",
			Uds: "asistiesen",
		},
		Future: {
			yo: "asistiere",
			tú: "asistieres",
			Ud: "asistiere",
			nosotros: "asistiéremos",
			vosotros: "asistiereis",
			Uds: "asistieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "asiste",
			Ud: "asista",
			nosotros: "asistamos",
			vosotros: "asistid",
			Uds: "asistan",
		},
		Negative: {
			tú: "no asistas",
			Ud: "no asista",
			nosotros: "no asistamos",
			vosotros: "no asistáis",
			Uds: "no asistan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy asistiendo",
			tú: "estás asistiendo",
			Ud: "está asistiendo",
			nosotros: "estamos asistiendo",
			vosotros: "estáis asistiendo",
			Uds: "están asistiendo",
		},
		Preterite: {
			yo: "estuve asistiendo",
			tú: "estuviste asistiendo",
			Ud: "estuvo asistiendo",
			nosotros: "estuvimos asistiendo",
			vosotros: "estuvisteis asistiendo",
			Uds: "estuvieron asistiendo",
		},
		Imperfect: {
			Uds: "estaban asistiendo",
			yo: "estaba asistiendo",
			tú: "estabas asistiendo",
			Ud: "estaba asistiendo",
			nosotros: "estábamos asistiendo",
			vosotros: "estabais asistiendo",
		},
		Conditional: {
			yo: "estaría asistiendo",
			tú: "estarías asistiendo",
			Ud: "estaría asistiendo",
			nosotros: "estaríamos asistiendo",
			vosotros: "estaríais asistiendo",
			Uds: "estarían asistiendo",
		},
		Future: {
			yo: "estaré asistiendo",
			tú: "estarás asistiendo",
			Ud: "estará asistiendo",
			nosotros: "estaremos asistiendo",
			vosotros: "estaréis asistiendo",
			Uds: "estarán asistiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he asistido",
			tú: "has asistido",
			Ud: "ha asistido",
			nosotros: "hemos asistido",
			vosotros: "habéis asistido",
			Uds: "han asistido",
		},
		Preterite: {
			yo: "hube asistido",
			tú: "hubiste asistido",
			Ud: "hubo asistido",
			nosotros: "hubimos asistido",
			vosotros: "hubisteis asistido",
			Uds: "hubieron asistido",
		},
		Past: {
			yo: "había asistido",
			tú: "habías asistido",
			Ud: "había asistido",
			nosotros: "habíamos asistido",
			vosotros: "habíais asistido",
			Uds: "habían asistido",
		},
		Conditional: {
			yo: "habría asistido",
			tú: "habrías asistido",
			Ud: "habría asistido",
			nosotros: "habríamos asistido",
			vosotros: "habríais asistido",
			Uds: "habrían asistido",
		},
		Future: {
			yo: "habré asistido",
			tú: "habrás asistido",
			Ud: "habrá asistido",
			nosotros: "habremos asistido",
			vosotros: "habréis asistido",
			Uds: "habrán asistido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya asistido",
			tú: "hayas asistido",
			Ud: "haya asistido",
			nosotros: "hayamos asistido",
			vosotros: "hayáis asistido",
			Uds: "hayan asistido",
		},
		Past: {
			yo: "hubiera asistido",
			tú: "hubieras asistido",
			Ud: "hubiera asistido",
			nosotros: "hubiéramos asistido",
			vosotros: "hubierais asistido",
			Uds: "hubieran asistido",
		},
		Future: {
			yo: "hubiere asistido",
			tú: "hubieres asistido",
			Ud: "hubiere asistido",
			nosotros: "hubiéremos asistido",
			vosotros: "hubiereis asistido",
			Uds: "hubieren asistido",
		},
	},
}
