var asociar = {
	Indicative: {
		Present: {
			yo: "asocio",
			tú: "asocias",
			Ud: "asocia",
			nosotros: "asociamos",
			vosotros: "asociáis",
			Uds: "asocian",
		},
		Preterite: {
			yo: "asocié",
			tú: "asociaste",
			Ud: "asoció",
			nosotros: "asociamos",
			vosotros: "asociasteis",
			Uds: "asociaron",
		},
		Imperfect: {
			yo: "asociaba",
			tú: "asociabas",
			Ud: "asociaba",
			nosotros: "asociábamos",
			vosotros: "asociabais",
			Uds: "asociaban",
		},
		Conditional: {
			yo: "asociaría",
			tú: "asociarías",
			Ud: "asociaría",
			nosotros: "asociaríamos",
			vosotros: "asociaríais",
			Uds: "asociarían",
		},
		Future: {
			yo: "asociaré",
			tú: "asociarás",
			Ud: "asociará",
			nosotros: "asociaremos",
			vosotros: "asociaréis",
			Uds: "asociarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "asocie",
			tú: "asocies",
			Ud: "asocie",
			nosotros: "asociemos",
			vosotros: "asociéis",
			Uds: "asocien",
		},
		Imperfect: {
			yo: "asociara",
			tú: "asociaras",
			Ud: "asociara",
			nosotros: "asociáramos",
			vosotros: "asociarais",
			Uds: "asociaran",
		},
		Imperfect2: {
			yo: "asociase",
			tú: "asociases",
			Ud: "asociase",
			nosotros: "asociásemos",
			vosotros: "asociaseis",
			Uds: "asociasen",
		},
		Future: {
			yo: "asociare",
			tú: "asociares",
			Ud: "asociare",
			nosotros: "asociáremos",
			vosotros: "asociareis",
			Uds: "asociaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "asocia",
			Ud: "asocie",
			nosotros: "asociemos",
			vosotros: "asociad",
			Uds: "asocien",
		},
		Negative: {
			tú: "no asocies",
			Ud: "no asocie",
			nosotros: "no asociemos",
			vosotros: "no asociéis",
			Uds: "no asocien",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy asociando",
			tú: "estás asociando",
			Ud: "está asociando",
			nosotros: "estamos asociando",
			vosotros: "estáis asociando",
			Uds: "están asociando",
		},
		Preterite: {
			yo: "estuve asociando",
			tú: "estuviste asociando",
			Ud: "estuvo asociando",
			nosotros: "estuvimos asociando",
			vosotros: "estuvisteis asociando",
			Uds: "estuvieron asociando",
		},
		Imperfect: {
			Uds: "estaban asociando",
			yo: "estaba asociando",
			tú: "estabas asociando",
			Ud: "estaba asociando",
			nosotros: "estábamos asociando",
			vosotros: "estabais asociando",
		},
		Conditional: {
			yo: "estaría asociando",
			tú: "estarías asociando",
			Ud: "estaría asociando",
			nosotros: "estaríamos asociando",
			vosotros: "estaríais asociando",
			Uds: "estarían asociando",
		},
		Future: {
			yo: "estaré asociando",
			tú: "estarás asociando",
			Ud: "estará asociando",
			nosotros: "estaremos asociando",
			vosotros: "estaréis asociando",
			Uds: "estarán asociando",
		},
	},
	Perfect: {
		Present: {
			yo: "he asociado",
			tú: "has asociado",
			Ud: "ha asociado",
			nosotros: "hemos asociado",
			vosotros: "habéis asociado",
			Uds: "han asociado",
		},
		Preterite: {
			yo: "hube asociado",
			tú: "hubiste asociado",
			Ud: "hubo asociado",
			nosotros: "hubimos asociado",
			vosotros: "hubisteis asociado",
			Uds: "hubieron asociado",
		},
		Past: {
			yo: "había asociado",
			tú: "habías asociado",
			Ud: "había asociado",
			nosotros: "habíamos asociado",
			vosotros: "habíais asociado",
			Uds: "habían asociado",
		},
		Conditional: {
			yo: "habría asociado",
			tú: "habrías asociado",
			Ud: "habría asociado",
			nosotros: "habríamos asociado",
			vosotros: "habríais asociado",
			Uds: "habrían asociado",
		},
		Future: {
			yo: "habré asociado",
			tú: "habrás asociado",
			Ud: "habrá asociado",
			nosotros: "habremos asociado",
			vosotros: "habréis asociado",
			Uds: "habrán asociado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya asociado",
			tú: "hayas asociado",
			Ud: "haya asociado",
			nosotros: "hayamos asociado",
			vosotros: "hayáis asociado",
			Uds: "hayan asociado",
		},
		Past: {
			yo: "hubiera asociado",
			tú: "hubieras asociado",
			Ud: "hubiera asociado",
			nosotros: "hubiéramos asociado",
			vosotros: "hubierais asociado",
			Uds: "hubieran asociado",
		},
		Future: {
			yo: "hubiere asociado",
			tú: "hubieres asociado",
			Ud: "hubiere asociado",
			nosotros: "hubiéremos asociado",
			vosotros: "hubiereis asociado",
			Uds: "hubieren asociado",
		},
	},
}
