var asumir = {
	Indicative: {
		Present: {
			yo: "asumo",
			tú: "asumes",
			Ud: "asume",
			nosotros: "asumimos",
			vosotros: "asumís",
			Uds: "asumen",
		},
		Preterite: {
			yo: "asumí",
			tú: "asumiste",
			Ud: "asumió",
			nosotros: "asumimos",
			vosotros: "asumisteis",
			Uds: "asumieron",
		},
		Imperfect: {
			yo: "asumía",
			tú: "asumías",
			Ud: "asumía",
			nosotros: "asumíamos",
			vosotros: "asumíais",
			Uds: "asumían",
		},
		Conditional: {
			yo: "asumiría",
			tú: "asumirías",
			Ud: "asumiría",
			nosotros: "asumiríamos",
			vosotros: "asumiríais",
			Uds: "asumirían",
		},
		Future: {
			yo: "asumiré",
			tú: "asumirás",
			Ud: "asumirá",
			nosotros: "asumiremos",
			vosotros: "asumiréis",
			Uds: "asumirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "asuma",
			tú: "asumas",
			Ud: "asuma",
			nosotros: "asumamos",
			vosotros: "asumáis",
			Uds: "asuman",
		},
		Imperfect: {
			yo: "asumiera",
			tú: "asumieras",
			Ud: "asumiera",
			nosotros: "asumiéramos",
			vosotros: "asumierais",
			Uds: "asumieran",
		},
		Imperfect2: {
			yo: "asumiese",
			tú: "asumieses",
			Ud: "asumiese",
			nosotros: "asumiésemos",
			vosotros: "asumieseis",
			Uds: "asumiesen",
		},
		Future: {
			yo: "asumiere",
			tú: "asumieres",
			Ud: "asumiere",
			nosotros: "asumiéremos",
			vosotros: "asumiereis",
			Uds: "asumieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "asume",
			Ud: "asuma",
			nosotros: "asumamos",
			vosotros: "asumid",
			Uds: "asuman",
		},
		Negative: {
			tú: "no asumas",
			Ud: "no asuma",
			nosotros: "no asumamos",
			vosotros: "no asumáis",
			Uds: "no asuman",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy asumiendo",
			tú: "estás asumiendo",
			Ud: "está asumiendo",
			nosotros: "estamos asumiendo",
			vosotros: "estáis asumiendo",
			Uds: "están asumiendo",
		},
		Preterite: {
			yo: "estuve asumiendo",
			tú: "estuviste asumiendo",
			Ud: "estuvo asumiendo",
			nosotros: "estuvimos asumiendo",
			vosotros: "estuvisteis asumiendo",
			Uds: "estuvieron asumiendo",
		},
		Imperfect: {
			Uds: "estaban asumiendo",
			yo: "estaba asumiendo",
			tú: "estabas asumiendo",
			Ud: "estaba asumiendo",
			nosotros: "estábamos asumiendo",
			vosotros: "estabais asumiendo",
		},
		Conditional: {
			yo: "estaría asumiendo",
			tú: "estarías asumiendo",
			Ud: "estaría asumiendo",
			nosotros: "estaríamos asumiendo",
			vosotros: "estaríais asumiendo",
			Uds: "estarían asumiendo",
		},
		Future: {
			yo: "estaré asumiendo",
			tú: "estarás asumiendo",
			Ud: "estará asumiendo",
			nosotros: "estaremos asumiendo",
			vosotros: "estaréis asumiendo",
			Uds: "estarán asumiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he asumido",
			tú: "has asumido",
			Ud: "ha asumido",
			nosotros: "hemos asumido",
			vosotros: "habéis asumido",
			Uds: "han asumido",
		},
		Preterite: {
			yo: "hube asumido",
			tú: "hubiste asumido",
			Ud: "hubo asumido",
			nosotros: "hubimos asumido",
			vosotros: "hubisteis asumido",
			Uds: "hubieron asumido",
		},
		Past: {
			yo: "había asumido",
			tú: "habías asumido",
			Ud: "había asumido",
			nosotros: "habíamos asumido",
			vosotros: "habíais asumido",
			Uds: "habían asumido",
		},
		Conditional: {
			yo: "habría asumido",
			tú: "habrías asumido",
			Ud: "habría asumido",
			nosotros: "habríamos asumido",
			vosotros: "habríais asumido",
			Uds: "habrían asumido",
		},
		Future: {
			yo: "habré asumido",
			tú: "habrás asumido",
			Ud: "habrá asumido",
			nosotros: "habremos asumido",
			vosotros: "habréis asumido",
			Uds: "habrán asumido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya asumido",
			tú: "hayas asumido",
			Ud: "haya asumido",
			nosotros: "hayamos asumido",
			vosotros: "hayáis asumido",
			Uds: "hayan asumido",
		},
		Past: {
			yo: "hubiera asumido",
			tú: "hubieras asumido",
			Ud: "hubiera asumido",
			nosotros: "hubiéramos asumido",
			vosotros: "hubierais asumido",
			Uds: "hubieran asumido",
		},
		Future: {
			yo: "hubiere asumido",
			tú: "hubieres asumido",
			Ud: "hubiere asumido",
			nosotros: "hubiéremos asumido",
			vosotros: "hubiereis asumido",
			Uds: "hubieren asumido",
		},
	},
}
