var aterrizar = {
	Indicative: {
		Present: {
			yo: "aterrizo",
			tú: "aterrizas",
			Ud: "aterriza",
			nosotros: "aterrizamos",
			vosotros: "aterrizáis",
			Uds: "aterrizan",
		},
		Preterite: {
			yo: "aterricé",
			tú: "aterrizaste",
			Ud: "aterrizó",
			nosotros: "aterrizamos",
			vosotros: "aterrizasteis",
			Uds: "aterrizaron",
		},
		Imperfect: {
			yo: "aterrizaba",
			tú: "aterrizabas",
			Ud: "aterrizaba",
			nosotros: "aterrizábamos",
			vosotros: "aterrizabais",
			Uds: "aterrizaban",
		},
		Conditional: {
			yo: "aterrizaría",
			tú: "aterrizarías",
			Ud: "aterrizaría",
			nosotros: "aterrizaríamos",
			vosotros: "aterrizaríais",
			Uds: "aterrizarían",
		},
		Future: {
			yo: "aterrizaré",
			tú: "aterrizarás",
			Ud: "aterrizará",
			nosotros: "aterrizaremos",
			vosotros: "aterrizaréis",
			Uds: "aterrizarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "aterrice",
			tú: "aterrices",
			Ud: "aterrice",
			nosotros: "aterricemos",
			vosotros: "aterricéis",
			Uds: "aterricen",
		},
		Imperfect: {
			yo: "aterrizara",
			tú: "aterrizaras",
			Ud: "aterrizara",
			nosotros: "aterrizáramos",
			vosotros: "aterrizarais",
			Uds: "aterrizaran",
		},
		Imperfect2: {
			yo: "aterrizase",
			tú: "aterrizases",
			Ud: "aterrizase",
			nosotros: "aterrizásemos",
			vosotros: "aterrizaseis",
			Uds: "aterrizasen",
		},
		Future: {
			yo: "aterrizare",
			tú: "aterrizares",
			Ud: "aterrizare",
			nosotros: "aterrizáremos",
			vosotros: "aterrizareis",
			Uds: "aterrizaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "aterriza",
			Ud: "aterrice",
			nosotros: "aterricemos",
			vosotros: "aterrizad",
			Uds: "aterricen",
		},
		Negative: {
			tú: "no aterrices",
			Ud: "no aterrice",
			nosotros: "no aterricemos",
			vosotros: "no aterricéis",
			Uds: "no aterricen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy aterrizando",
			tú: "estás aterrizando",
			Ud: "está aterrizando",
			nosotros: "estamos aterrizando",
			vosotros: "estáis aterrizando",
			Uds: "están aterrizando",
		},
		Preterite: {
			yo: "estuve aterrizando",
			tú: "estuviste aterrizando",
			Ud: "estuvo aterrizando",
			nosotros: "estuvimos aterrizando",
			vosotros: "estuvisteis aterrizando",
			Uds: "estuvieron aterrizando",
		},
		Imperfect: {
			Uds: "estaban aterrizando",
			yo: "estaba aterrizando",
			tú: "estabas aterrizando",
			Ud: "estaba aterrizando",
			nosotros: "estábamos aterrizando",
			vosotros: "estabais aterrizando",
		},
		Conditional: {
			yo: "estaría aterrizando",
			tú: "estarías aterrizando",
			Ud: "estaría aterrizando",
			nosotros: "estaríamos aterrizando",
			vosotros: "estaríais aterrizando",
			Uds: "estarían aterrizando",
		},
		Future: {
			yo: "estaré aterrizando",
			tú: "estarás aterrizando",
			Ud: "estará aterrizando",
			nosotros: "estaremos aterrizando",
			vosotros: "estaréis aterrizando",
			Uds: "estarán aterrizando",
		},
	},
	Perfect: {
		Present: {
			yo: "he aterrizado",
			tú: "has aterrizado",
			Ud: "ha aterrizado",
			nosotros: "hemos aterrizado",
			vosotros: "habéis aterrizado",
			Uds: "han aterrizado",
		},
		Preterite: {
			yo: "hube aterrizado",
			tú: "hubiste aterrizado",
			Ud: "hubo aterrizado",
			nosotros: "hubimos aterrizado",
			vosotros: "hubisteis aterrizado",
			Uds: "hubieron aterrizado",
		},
		Past: {
			yo: "había aterrizado",
			tú: "habías aterrizado",
			Ud: "había aterrizado",
			nosotros: "habíamos aterrizado",
			vosotros: "habíais aterrizado",
			Uds: "habían aterrizado",
		},
		Conditional: {
			yo: "habría aterrizado",
			tú: "habrías aterrizado",
			Ud: "habría aterrizado",
			nosotros: "habríamos aterrizado",
			vosotros: "habríais aterrizado",
			Uds: "habrían aterrizado",
		},
		Future: {
			yo: "habré aterrizado",
			tú: "habrás aterrizado",
			Ud: "habrá aterrizado",
			nosotros: "habremos aterrizado",
			vosotros: "habréis aterrizado",
			Uds: "habrán aterrizado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya aterrizado",
			tú: "hayas aterrizado",
			Ud: "haya aterrizado",
			nosotros: "hayamos aterrizado",
			vosotros: "hayáis aterrizado",
			Uds: "hayan aterrizado",
		},
		Past: {
			yo: "hubiera aterrizado",
			tú: "hubieras aterrizado",
			Ud: "hubiera aterrizado",
			nosotros: "hubiéramos aterrizado",
			vosotros: "hubierais aterrizado",
			Uds: "hubieran aterrizado",
		},
		Future: {
			yo: "hubiere aterrizado",
			tú: "hubieres aterrizado",
			Ud: "hubiere aterrizado",
			nosotros: "hubiéremos aterrizado",
			vosotros: "hubiereis aterrizado",
			Uds: "hubieren aterrizado",
		},
	},
}
