var aterrar = {
	Indicative: {
		Present: {
			yo: "atierro",
			tú: "atierras",
			Ud: "atierra",
			nosotros: "aterramos",
			vosotros: "aterráis",
			Uds: "atierran",
		},
		Preterite: {
			yo: "aterré",
			tú: "aterraste",
			Ud: "aterró",
			nosotros: "aterramos",
			vosotros: "aterrasteis",
			Uds: "aterraron",
		},
		Imperfect: {
			yo: "aterraba",
			tú: "aterrabas",
			Ud: "aterraba",
			nosotros: "aterrábamos",
			vosotros: "aterrabais",
			Uds: "aterraban",
		},
		Conditional: {
			yo: "aterraría",
			tú: "aterrarías",
			Ud: "aterraría",
			nosotros: "aterraríamos",
			vosotros: "aterraríais",
			Uds: "aterrarían",
		},
		Future: {
			yo: "aterraré",
			tú: "aterrarás",
			Ud: "aterrará",
			nosotros: "aterraremos",
			vosotros: "aterraréis",
			Uds: "aterrarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "atierre",
			tú: "atierres",
			Ud: "atierre",
			nosotros: "aterremos",
			vosotros: "aterréis",
			Uds: "atierren",
		},
		Imperfect: {
			yo: "aterrara",
			tú: "aterraras",
			Ud: "aterrara",
			nosotros: "aterráramos",
			vosotros: "aterrarais",
			Uds: "aterraran",
		},
		Imperfect2: {
			yo: "aterrase",
			tú: "aterrases",
			Ud: "aterrase",
			nosotros: "aterrásemos",
			vosotros: "aterraseis",
			Uds: "aterrasen",
		},
		Future: {
			yo: "aterrare",
			tú: "aterrares",
			Ud: "aterrare",
			nosotros: "aterráremos",
			vosotros: "aterrareis",
			Uds: "aterraren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "atierra",
			Ud: "atierre",
			nosotros: "aterremos",
			vosotros: "aterrad",
			Uds: "atierren",
		},
		Negative: {
			tú: "no atierres",
			Ud: "no atierre",
			nosotros: "no aterremos",
			vosotros: "no aterréis",
			Uds: "no atierren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy aterrando",
			tú: "estás aterrando",
			Ud: "está aterrando",
			nosotros: "estamos aterrando",
			vosotros: "estáis aterrando",
			Uds: "están aterrando",
		},
		Preterite: {
			yo: "estuve aterrando",
			tú: "estuviste aterrando",
			Ud: "estuvo aterrando",
			nosotros: "estuvimos aterrando",
			vosotros: "estuvisteis aterrando",
			Uds: "estuvieron aterrando",
		},
		Imperfect: {
			Uds: "estaban aterrando",
			yo: "estaba aterrando",
			tú: "estabas aterrando",
			Ud: "estaba aterrando",
			nosotros: "estábamos aterrando",
			vosotros: "estabais aterrando",
		},
		Conditional: {
			yo: "estaría aterrando",
			tú: "estarías aterrando",
			Ud: "estaría aterrando",
			nosotros: "estaríamos aterrando",
			vosotros: "estaríais aterrando",
			Uds: "estarían aterrando",
		},
		Future: {
			yo: "estaré aterrando",
			tú: "estarás aterrando",
			Ud: "estará aterrando",
			nosotros: "estaremos aterrando",
			vosotros: "estaréis aterrando",
			Uds: "estarán aterrando",
		},
	},
	Perfect: {
		Present: {
			yo: "he aterrado",
			tú: "has aterrado",
			Ud: "ha aterrado",
			nosotros: "hemos aterrado",
			vosotros: "habéis aterrado",
			Uds: "han aterrado",
		},
		Preterite: {
			yo: "hube aterrado",
			tú: "hubiste aterrado",
			Ud: "hubo aterrado",
			nosotros: "hubimos aterrado",
			vosotros: "hubisteis aterrado",
			Uds: "hubieron aterrado",
		},
		Past: {
			yo: "había aterrado",
			tú: "habías aterrado",
			Ud: "había aterrado",
			nosotros: "habíamos aterrado",
			vosotros: "habíais aterrado",
			Uds: "habían aterrado",
		},
		Conditional: {
			yo: "habría aterrado",
			tú: "habrías aterrado",
			Ud: "habría aterrado",
			nosotros: "habríamos aterrado",
			vosotros: "habríais aterrado",
			Uds: "habrían aterrado",
		},
		Future: {
			yo: "habré aterrado",
			tú: "habrás aterrado",
			Ud: "habrá aterrado",
			nosotros: "habremos aterrado",
			vosotros: "habréis aterrado",
			Uds: "habrán aterrado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya aterrado",
			tú: "hayas aterrado",
			Ud: "haya aterrado",
			nosotros: "hayamos aterrado",
			vosotros: "hayáis aterrado",
			Uds: "hayan aterrado",
		},
		Past: {
			yo: "hubiera aterrado",
			tú: "hubieras aterrado",
			Ud: "hubiera aterrado",
			nosotros: "hubiéramos aterrado",
			vosotros: "hubierais aterrado",
			Uds: "hubieran aterrado",
		},
		Future: {
			yo: "hubiere aterrado",
			tú: "hubieres aterrado",
			Ud: "hubiere aterrado",
			nosotros: "hubiéremos aterrado",
			vosotros: "hubiereis aterrado",
			Uds: "hubieren aterrado",
		},
	},
}
