var atornillar = {
	Indicative: {
		Present: {
			yo: "atornillo",
			tú: "atornillas",
			Ud: "atornilla",
			nosotros: "atornillamos",
			vosotros: "atornilláis",
			Uds: "atornillan",
		},
		Preterite: {
			yo: "atornillé",
			tú: "atornillaste",
			Ud: "atornilló",
			nosotros: "atornillamos",
			vosotros: "atornillasteis",
			Uds: "atornillaron",
		},
		Imperfect: {
			yo: "atornillaba",
			tú: "atornillabas",
			Ud: "atornillaba",
			nosotros: "atornillábamos",
			vosotros: "atornillabais",
			Uds: "atornillaban",
		},
		Conditional: {
			yo: "atornillaría",
			tú: "atornillarías",
			Ud: "atornillaría",
			nosotros: "atornillaríamos",
			vosotros: "atornillaríais",
			Uds: "atornillarían",
		},
		Future: {
			yo: "atornillaré",
			tú: "atornillarás",
			Ud: "atornillará",
			nosotros: "atornillaremos",
			vosotros: "atornillaréis",
			Uds: "atornillarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "atornille",
			tú: "atornilles",
			Ud: "atornille",
			nosotros: "atornillemos",
			vosotros: "atornilléis",
			Uds: "atornillen",
		},
		Imperfect: {
			yo: "atornillara",
			tú: "atornillaras",
			Ud: "atornillara",
			nosotros: "atornilláramos",
			vosotros: "atornillarais",
			Uds: "atornillaran",
		},
		Imperfect2: {
			yo: "atornillase",
			tú: "atornillases",
			Ud: "atornillase",
			nosotros: "atornillásemos",
			vosotros: "atornillaseis",
			Uds: "atornillasen",
		},
		Future: {
			yo: "atornillare",
			tú: "atornillares",
			Ud: "atornillare",
			nosotros: "atornilláremos",
			vosotros: "atornillareis",
			Uds: "atornillaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "atornilla",
			Ud: "atornille",
			nosotros: "atornillemos",
			vosotros: "atornillad",
			Uds: "atornillen",
		},
		Negative: {
			tú: "no atornilles",
			Ud: "no atornille",
			nosotros: "no atornillemos",
			vosotros: "no atornilléis",
			Uds: "no atornillen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy atornillando",
			tú: "estás atornillando",
			Ud: "está atornillando",
			nosotros: "estamos atornillando",
			vosotros: "estáis atornillando",
			Uds: "están atornillando",
		},
		Preterite: {
			yo: "estuve atornillando",
			tú: "estuviste atornillando",
			Ud: "estuvo atornillando",
			nosotros: "estuvimos atornillando",
			vosotros: "estuvisteis atornillando",
			Uds: "estuvieron atornillando",
		},
		Imperfect: {
			Uds: "estaban atornillando",
			yo: "estaba atornillando",
			tú: "estabas atornillando",
			Ud: "estaba atornillando",
			nosotros: "estábamos atornillando",
			vosotros: "estabais atornillando",
		},
		Conditional: {
			yo: "estaría atornillando",
			tú: "estarías atornillando",
			Ud: "estaría atornillando",
			nosotros: "estaríamos atornillando",
			vosotros: "estaríais atornillando",
			Uds: "estarían atornillando",
		},
		Future: {
			yo: "estaré atornillando",
			tú: "estarás atornillando",
			Ud: "estará atornillando",
			nosotros: "estaremos atornillando",
			vosotros: "estaréis atornillando",
			Uds: "estarán atornillando",
		},
	},
	Perfect: {
		Present: {
			yo: "he atornillado",
			tú: "has atornillado",
			Ud: "ha atornillado",
			nosotros: "hemos atornillado",
			vosotros: "habéis atornillado",
			Uds: "han atornillado",
		},
		Preterite: {
			yo: "hube atornillado",
			tú: "hubiste atornillado",
			Ud: "hubo atornillado",
			nosotros: "hubimos atornillado",
			vosotros: "hubisteis atornillado",
			Uds: "hubieron atornillado",
		},
		Past: {
			yo: "había atornillado",
			tú: "habías atornillado",
			Ud: "había atornillado",
			nosotros: "habíamos atornillado",
			vosotros: "habíais atornillado",
			Uds: "habían atornillado",
		},
		Conditional: {
			yo: "habría atornillado",
			tú: "habrías atornillado",
			Ud: "habría atornillado",
			nosotros: "habríamos atornillado",
			vosotros: "habríais atornillado",
			Uds: "habrían atornillado",
		},
		Future: {
			yo: "habré atornillado",
			tú: "habrás atornillado",
			Ud: "habrá atornillado",
			nosotros: "habremos atornillado",
			vosotros: "habréis atornillado",
			Uds: "habrán atornillado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya atornillado",
			tú: "hayas atornillado",
			Ud: "haya atornillado",
			nosotros: "hayamos atornillado",
			vosotros: "hayáis atornillado",
			Uds: "hayan atornillado",
		},
		Past: {
			yo: "hubiera atornillado",
			tú: "hubieras atornillado",
			Ud: "hubiera atornillado",
			nosotros: "hubiéramos atornillado",
			vosotros: "hubierais atornillado",
			Uds: "hubieran atornillado",
		},
		Future: {
			yo: "hubiere atornillado",
			tú: "hubieres atornillado",
			Ud: "hubiere atornillado",
			nosotros: "hubiéremos atornillado",
			vosotros: "hubiereis atornillado",
			Uds: "hubieren atornillado",
		},
	},
}
