var atravesar = {
	Indicative: {
		Present: {
			yo: "atravieso",
			tú: "atraviesas",
			Ud: "atraviesa",
			nosotros: "atravesamos",
			vosotros: "atravesáis",
			Uds: "atraviesan",
		},
		Preterite: {
			yo: "atravesé",
			tú: "atravesaste",
			Ud: "atravesó",
			nosotros: "atravesamos",
			vosotros: "atravesasteis",
			Uds: "atravesaron",
		},
		Imperfect: {
			yo: "atravesaba",
			tú: "atravesabas",
			Ud: "atravesaba",
			nosotros: "atravesábamos",
			vosotros: "atravesabais",
			Uds: "atravesaban",
		},
		Conditional: {
			yo: "atravesaría",
			tú: "atravesarías",
			Ud: "atravesaría",
			nosotros: "atravesaríamos",
			vosotros: "atravesaríais",
			Uds: "atravesarían",
		},
		Future: {
			yo: "atravesaré",
			tú: "atravesarás",
			Ud: "atravesará",
			nosotros: "atravesaremos",
			vosotros: "atravesaréis",
			Uds: "atravesarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "atraviese",
			tú: "atravieses",
			Ud: "atraviese",
			nosotros: "atravesemos",
			vosotros: "atraveséis",
			Uds: "atraviesen",
		},
		Imperfect: {
			yo: "atravesara",
			tú: "atravesaras",
			Ud: "atravesara",
			nosotros: "atravesáramos",
			vosotros: "atravesarais",
			Uds: "atravesaran",
		},
		Imperfect2: {
			yo: "atravesase",
			tú: "atravesases",
			Ud: "atravesase",
			nosotros: "atravesásemos",
			vosotros: "atravesaseis",
			Uds: "atravesasen",
		},
		Future: {
			yo: "atravesare",
			tú: "atravesares",
			Ud: "atravesare",
			nosotros: "atravesáremos",
			vosotros: "atravesareis",
			Uds: "atravesaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "atraviesa",
			Ud: "atraviese",
			nosotros: "atravesemos",
			vosotros: "atravesad",
			Uds: "atraviesen",
		},
		Negative: {
			tú: "no atravieses",
			Ud: "no atraviese",
			nosotros: "no atravesemos",
			vosotros: "no atraveséis",
			Uds: "no atraviesen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy atravesando",
			tú: "estás atravesando",
			Ud: "está atravesando",
			nosotros: "estamos atravesando",
			vosotros: "estáis atravesando",
			Uds: "están atravesando",
		},
		Preterite: {
			yo: "estuve atravesando",
			tú: "estuviste atravesando",
			Ud: "estuvo atravesando",
			nosotros: "estuvimos atravesando",
			vosotros: "estuvisteis atravesando",
			Uds: "estuvieron atravesando",
		},
		Imperfect: {
			Uds: "estaban atravesando",
			yo: "estaba atravesando",
			tú: "estabas atravesando",
			Ud: "estaba atravesando",
			nosotros: "estábamos atravesando",
			vosotros: "estabais atravesando",
		},
		Conditional: {
			yo: "estaría atravesando",
			tú: "estarías atravesando",
			Ud: "estaría atravesando",
			nosotros: "estaríamos atravesando",
			vosotros: "estaríais atravesando",
			Uds: "estarían atravesando",
		},
		Future: {
			yo: "estaré atravesando",
			tú: "estarás atravesando",
			Ud: "estará atravesando",
			nosotros: "estaremos atravesando",
			vosotros: "estaréis atravesando",
			Uds: "estarán atravesando",
		},
	},
	Perfect: {
		Present: {
			yo: "he atravesado",
			tú: "has atravesado",
			Ud: "ha atravesado",
			nosotros: "hemos atravesado",
			vosotros: "habéis atravesado",
			Uds: "han atravesado",
		},
		Preterite: {
			yo: "hube atravesado",
			tú: "hubiste atravesado",
			Ud: "hubo atravesado",
			nosotros: "hubimos atravesado",
			vosotros: "hubisteis atravesado",
			Uds: "hubieron atravesado",
		},
		Past: {
			yo: "había atravesado",
			tú: "habías atravesado",
			Ud: "había atravesado",
			nosotros: "habíamos atravesado",
			vosotros: "habíais atravesado",
			Uds: "habían atravesado",
		},
		Conditional: {
			yo: "habría atravesado",
			tú: "habrías atravesado",
			Ud: "habría atravesado",
			nosotros: "habríamos atravesado",
			vosotros: "habríais atravesado",
			Uds: "habrían atravesado",
		},
		Future: {
			yo: "habré atravesado",
			tú: "habrás atravesado",
			Ud: "habrá atravesado",
			nosotros: "habremos atravesado",
			vosotros: "habréis atravesado",
			Uds: "habrán atravesado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya atravesado",
			tú: "hayas atravesado",
			Ud: "haya atravesado",
			nosotros: "hayamos atravesado",
			vosotros: "hayáis atravesado",
			Uds: "hayan atravesado",
		},
		Past: {
			yo: "hubiera atravesado",
			tú: "hubieras atravesado",
			Ud: "hubiera atravesado",
			nosotros: "hubiéramos atravesado",
			vosotros: "hubierais atravesado",
			Uds: "hubieran atravesado",
		},
		Future: {
			yo: "hubiere atravesado",
			tú: "hubieres atravesado",
			Ud: "hubiere atravesado",
			nosotros: "hubiéremos atravesado",
			vosotros: "hubiereis atravesado",
			Uds: "hubieren atravesado",
		},
	},
}
