var atropellar = {
	Indicative: {
		Present: {
			yo: "atropello",
			tú: "atropellas",
			Ud: "atropella",
			nosotros: "atropellamos",
			vosotros: "atropelláis",
			Uds: "atropellan",
		},
		Preterite: {
			yo: "atropellé",
			tú: "atropellaste",
			Ud: "atropelló",
			nosotros: "atropellamos",
			vosotros: "atropellasteis",
			Uds: "atropellaron",
		},
		Imperfect: {
			yo: "atropellaba",
			tú: "atropellabas",
			Ud: "atropellaba",
			nosotros: "atropellábamos",
			vosotros: "atropellabais",
			Uds: "atropellaban",
		},
		Conditional: {
			yo: "atropellaría",
			tú: "atropellarías",
			Ud: "atropellaría",
			nosotros: "atropellaríamos",
			vosotros: "atropellaríais",
			Uds: "atropellarían",
		},
		Future: {
			yo: "atropellaré",
			tú: "atropellarás",
			Ud: "atropellará",
			nosotros: "atropellaremos",
			vosotros: "atropellaréis",
			Uds: "atropellarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "atropelle",
			tú: "atropelles",
			Ud: "atropelle",
			nosotros: "atropellemos",
			vosotros: "atropelléis",
			Uds: "atropellen",
		},
		Imperfect: {
			yo: "atropellara",
			tú: "atropellaras",
			Ud: "atropellara",
			nosotros: "atropelláramos",
			vosotros: "atropellarais",
			Uds: "atropellaran",
		},
		Imperfect2: {
			yo: "atropellase",
			tú: "atropellases",
			Ud: "atropellase",
			nosotros: "atropellásemos",
			vosotros: "atropellaseis",
			Uds: "atropellasen",
		},
		Future: {
			yo: "atropellare",
			tú: "atropellares",
			Ud: "atropellare",
			nosotros: "atropelláremos",
			vosotros: "atropellareis",
			Uds: "atropellaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "atropella",
			Ud: "atropelle",
			nosotros: "atropellemos",
			vosotros: "atropellad",
			Uds: "atropellen",
		},
		Negative: {
			tú: "no atropelles",
			Ud: "no atropelle",
			nosotros: "no atropellemos",
			vosotros: "no atropelléis",
			Uds: "no atropellen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy atropellando",
			tú: "estás atropellando",
			Ud: "está atropellando",
			nosotros: "estamos atropellando",
			vosotros: "estáis atropellando",
			Uds: "están atropellando",
		},
		Preterite: {
			yo: "estuve atropellando",
			tú: "estuviste atropellando",
			Ud: "estuvo atropellando",
			nosotros: "estuvimos atropellando",
			vosotros: "estuvisteis atropellando",
			Uds: "estuvieron atropellando",
		},
		Imperfect: {
			Uds: "estaban atropellando",
			yo: "estaba atropellando",
			tú: "estabas atropellando",
			Ud: "estaba atropellando",
			nosotros: "estábamos atropellando",
			vosotros: "estabais atropellando",
		},
		Conditional: {
			yo: "estaría atropellando",
			tú: "estarías atropellando",
			Ud: "estaría atropellando",
			nosotros: "estaríamos atropellando",
			vosotros: "estaríais atropellando",
			Uds: "estarían atropellando",
		},
		Future: {
			yo: "estaré atropellando",
			tú: "estarás atropellando",
			Ud: "estará atropellando",
			nosotros: "estaremos atropellando",
			vosotros: "estaréis atropellando",
			Uds: "estarán atropellando",
		},
	},
	Perfect: {
		Present: {
			yo: "he atropellado",
			tú: "has atropellado",
			Ud: "ha atropellado",
			nosotros: "hemos atropellado",
			vosotros: "habéis atropellado",
			Uds: "han atropellado",
		},
		Preterite: {
			yo: "hube atropellado",
			tú: "hubiste atropellado",
			Ud: "hubo atropellado",
			nosotros: "hubimos atropellado",
			vosotros: "hubisteis atropellado",
			Uds: "hubieron atropellado",
		},
		Past: {
			yo: "había atropellado",
			tú: "habías atropellado",
			Ud: "había atropellado",
			nosotros: "habíamos atropellado",
			vosotros: "habíais atropellado",
			Uds: "habían atropellado",
		},
		Conditional: {
			yo: "habría atropellado",
			tú: "habrías atropellado",
			Ud: "habría atropellado",
			nosotros: "habríamos atropellado",
			vosotros: "habríais atropellado",
			Uds: "habrían atropellado",
		},
		Future: {
			yo: "habré atropellado",
			tú: "habrás atropellado",
			Ud: "habrá atropellado",
			nosotros: "habremos atropellado",
			vosotros: "habréis atropellado",
			Uds: "habrán atropellado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya atropellado",
			tú: "hayas atropellado",
			Ud: "haya atropellado",
			nosotros: "hayamos atropellado",
			vosotros: "hayáis atropellado",
			Uds: "hayan atropellado",
		},
		Past: {
			yo: "hubiera atropellado",
			tú: "hubieras atropellado",
			Ud: "hubiera atropellado",
			nosotros: "hubiéramos atropellado",
			vosotros: "hubierais atropellado",
			Uds: "hubieran atropellado",
		},
		Future: {
			yo: "hubiere atropellado",
			tú: "hubieres atropellado",
			Ud: "hubiere atropellado",
			nosotros: "hubiéremos atropellado",
			vosotros: "hubiereis atropellado",
			Uds: "hubieren atropellado",
		},
	},
}
