var aunar = {
	Indicative: {
		Present: {
			yo: "aúno",
			tú: "aúnas",
			Ud: "aúna",
			nosotros: "aunamos",
			vosotros: "aunáis",
			Uds: "aúnan",
		},
		Preterite: {
			yo: "auné",
			tú: "aunaste",
			Ud: "aunó",
			nosotros: "aunamos",
			vosotros: "aunasteis",
			Uds: "aunaron",
		},
		Imperfect: {
			yo: "aunaba",
			tú: "aunabas",
			Ud: "aunaba",
			nosotros: "aunábamos",
			vosotros: "aunabais",
			Uds: "aunaban",
		},
		Conditional: {
			yo: "aunaría",
			tú: "aunarías",
			Ud: "aunaría",
			nosotros: "aunaríamos",
			vosotros: "aunaríais",
			Uds: "aunarían",
		},
		Future: {
			yo: "aunaré",
			tú: "aunarás",
			Ud: "aunará",
			nosotros: "aunaremos",
			vosotros: "aunaréis",
			Uds: "aunarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "aúne",
			tú: "aúnes",
			Ud: "aúne",
			nosotros: "aunemos",
			vosotros: "aunéis",
			Uds: "aúnen",
		},
		Imperfect: {
			yo: "aunara",
			tú: "aunaras",
			Ud: "aunara",
			nosotros: "aunáramos",
			vosotros: "aunarais",
			Uds: "aunaran",
		},
		Imperfect2: {
			yo: "aunase",
			tú: "aunases",
			Ud: "aunase",
			nosotros: "aunásemos",
			vosotros: "aunaseis",
			Uds: "aunasen",
		},
		Future: {
			yo: "aunare",
			tú: "aunares",
			Ud: "aunare",
			nosotros: "aunáremos",
			vosotros: "aunareis",
			Uds: "aunaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "aúna",
			Ud: "aúne",
			nosotros: "aunemos",
			vosotros: "aunad",
			Uds: "aúnen",
		},
		Negative: {
			tú: "no aúnes",
			Ud: "no aúne",
			nosotros: "no aunemos",
			vosotros: "no aunéis",
			Uds: "no aúnen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy aunando",
			tú: "estás aunando",
			Ud: "está aunando",
			nosotros: "estamos aunando",
			vosotros: "estáis aunando",
			Uds: "están aunando",
		},
		Preterite: {
			yo: "estuve aunando",
			tú: "estuviste aunando",
			Ud: "estuvo aunando",
			nosotros: "estuvimos aunando",
			vosotros: "estuvisteis aunando",
			Uds: "estuvieron aunando",
		},
		Imperfect: {
			Uds: "estaban aunando",
			yo: "estaba aunando",
			tú: "estabas aunando",
			Ud: "estaba aunando",
			nosotros: "estábamos aunando",
			vosotros: "estabais aunando",
		},
		Conditional: {
			yo: "estaría aunando",
			tú: "estarías aunando",
			Ud: "estaría aunando",
			nosotros: "estaríamos aunando",
			vosotros: "estaríais aunando",
			Uds: "estarían aunando",
		},
		Future: {
			yo: "estaré aunando",
			tú: "estarás aunando",
			Ud: "estará aunando",
			nosotros: "estaremos aunando",
			vosotros: "estaréis aunando",
			Uds: "estarán aunando",
		},
	},
	Perfect: {
		Present: {
			yo: "he aunado",
			tú: "has aunado",
			Ud: "ha aunado",
			nosotros: "hemos aunado",
			vosotros: "habéis aunado",
			Uds: "han aunado",
		},
		Preterite: {
			yo: "hube aunado",
			tú: "hubiste aunado",
			Ud: "hubo aunado",
			nosotros: "hubimos aunado",
			vosotros: "hubisteis aunado",
			Uds: "hubieron aunado",
		},
		Past: {
			yo: "había aunado",
			tú: "habías aunado",
			Ud: "había aunado",
			nosotros: "habíamos aunado",
			vosotros: "habíais aunado",
			Uds: "habían aunado",
		},
		Conditional: {
			yo: "habría aunado",
			tú: "habrías aunado",
			Ud: "habría aunado",
			nosotros: "habríamos aunado",
			vosotros: "habríais aunado",
			Uds: "habrían aunado",
		},
		Future: {
			yo: "habré aunado",
			tú: "habrás aunado",
			Ud: "habrá aunado",
			nosotros: "habremos aunado",
			vosotros: "habréis aunado",
			Uds: "habrán aunado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya aunado",
			tú: "hayas aunado",
			Ud: "haya aunado",
			nosotros: "hayamos aunado",
			vosotros: "hayáis aunado",
			Uds: "hayan aunado",
		},
		Past: {
			yo: "hubiera aunado",
			tú: "hubieras aunado",
			Ud: "hubiera aunado",
			nosotros: "hubiéramos aunado",
			vosotros: "hubierais aunado",
			Uds: "hubieran aunado",
		},
		Future: {
			yo: "hubiere aunado",
			tú: "hubieres aunado",
			Ud: "hubiere aunado",
			nosotros: "hubiéremos aunado",
			vosotros: "hubiereis aunado",
			Uds: "hubieren aunado",
		},
	},
}
