var avanzar = {
	Indicative: {
		Present: {
			yo: "avanzo",
			tú: "avanzas",
			Ud: "avanza",
			nosotros: "avanzamos",
			vosotros: "avanzáis",
			Uds: "avanzan",
		},
		Preterite: {
			yo: "avancé",
			tú: "avanzaste",
			Ud: "avanzó",
			nosotros: "avanzamos",
			vosotros: "avanzasteis",
			Uds: "avanzaron",
		},
		Imperfect: {
			yo: "avanzaba",
			tú: "avanzabas",
			Ud: "avanzaba",
			nosotros: "avanzábamos",
			vosotros: "avanzabais",
			Uds: "avanzaban",
		},
		Conditional: {
			yo: "avanzaría",
			tú: "avanzarías",
			Ud: "avanzaría",
			nosotros: "avanzaríamos",
			vosotros: "avanzaríais",
			Uds: "avanzarían",
		},
		Future: {
			yo: "avanzaré",
			tú: "avanzarás",
			Ud: "avanzará",
			nosotros: "avanzaremos",
			vosotros: "avanzaréis",
			Uds: "avanzarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "avance",
			tú: "avances",
			Ud: "avance",
			nosotros: "avancemos",
			vosotros: "avancéis",
			Uds: "avancen",
		},
		Imperfect: {
			yo: "avanzara",
			tú: "avanzaras",
			Ud: "avanzara",
			nosotros: "avanzáramos",
			vosotros: "avanzarais",
			Uds: "avanzaran",
		},
		Imperfect2: {
			yo: "avanzase",
			tú: "avanzases",
			Ud: "avanzase",
			nosotros: "avanzásemos",
			vosotros: "avanzaseis",
			Uds: "avanzasen",
		},
		Future: {
			yo: "avanzare",
			tú: "avanzares",
			Ud: "avanzare",
			nosotros: "avanzáremos",
			vosotros: "avanzareis",
			Uds: "avanzaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "avanza",
			Ud: "avance",
			nosotros: "avancemos",
			vosotros: "avanzad",
			Uds: "avancen",
		},
		Negative: {
			tú: "no avances",
			Ud: "no avance",
			nosotros: "no avancemos",
			vosotros: "no avancéis",
			Uds: "no avancen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy avanzando",
			tú: "estás avanzando",
			Ud: "está avanzando",
			nosotros: "estamos avanzando",
			vosotros: "estáis avanzando",
			Uds: "están avanzando",
		},
		Preterite: {
			yo: "estuve avanzando",
			tú: "estuviste avanzando",
			Ud: "estuvo avanzando",
			nosotros: "estuvimos avanzando",
			vosotros: "estuvisteis avanzando",
			Uds: "estuvieron avanzando",
		},
		Imperfect: {
			Uds: "estaban avanzando",
			yo: "estaba avanzando",
			tú: "estabas avanzando",
			Ud: "estaba avanzando",
			nosotros: "estábamos avanzando",
			vosotros: "estabais avanzando",
		},
		Conditional: {
			yo: "estaría avanzando",
			tú: "estarías avanzando",
			Ud: "estaría avanzando",
			nosotros: "estaríamos avanzando",
			vosotros: "estaríais avanzando",
			Uds: "estarían avanzando",
		},
		Future: {
			yo: "estaré avanzando",
			tú: "estarás avanzando",
			Ud: "estará avanzando",
			nosotros: "estaremos avanzando",
			vosotros: "estaréis avanzando",
			Uds: "estarán avanzando",
		},
	},
	Perfect: {
		Present: {
			yo: "he avanzado",
			tú: "has avanzado",
			Ud: "ha avanzado",
			nosotros: "hemos avanzado",
			vosotros: "habéis avanzado",
			Uds: "han avanzado",
		},
		Preterite: {
			yo: "hube avanzado",
			tú: "hubiste avanzado",
			Ud: "hubo avanzado",
			nosotros: "hubimos avanzado",
			vosotros: "hubisteis avanzado",
			Uds: "hubieron avanzado",
		},
		Past: {
			yo: "había avanzado",
			tú: "habías avanzado",
			Ud: "había avanzado",
			nosotros: "habíamos avanzado",
			vosotros: "habíais avanzado",
			Uds: "habían avanzado",
		},
		Conditional: {
			yo: "habría avanzado",
			tú: "habrías avanzado",
			Ud: "habría avanzado",
			nosotros: "habríamos avanzado",
			vosotros: "habríais avanzado",
			Uds: "habrían avanzado",
		},
		Future: {
			yo: "habré avanzado",
			tú: "habrás avanzado",
			Ud: "habrá avanzado",
			nosotros: "habremos avanzado",
			vosotros: "habréis avanzado",
			Uds: "habrán avanzado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya avanzado",
			tú: "hayas avanzado",
			Ud: "haya avanzado",
			nosotros: "hayamos avanzado",
			vosotros: "hayáis avanzado",
			Uds: "hayan avanzado",
		},
		Past: {
			yo: "hubiera avanzado",
			tú: "hubieras avanzado",
			Ud: "hubiera avanzado",
			nosotros: "hubiéramos avanzado",
			vosotros: "hubierais avanzado",
			Uds: "hubieran avanzado",
		},
		Future: {
			yo: "hubiere avanzado",
			tú: "hubieres avanzado",
			Ud: "hubiere avanzado",
			nosotros: "hubiéremos avanzado",
			vosotros: "hubiereis avanzado",
			Uds: "hubieren avanzado",
		},
	},
}
