var averiguar = {
	Indicative: {
		Present: {
			yo: "averiguo",
			tú: "averiguas",
			Ud: "averigua",
			nosotros: "averiguamos",
			vosotros: "averiguáis",
			Uds: "averiguan",
		},
		Preterite: {
			yo: "averigüé",
			tú: "averiguaste",
			Ud: "averiguó",
			nosotros: "averiguamos",
			vosotros: "averiguasteis",
			Uds: "averiguaron",
		},
		Imperfect: {
			yo: "averiguaba",
			tú: "averiguabas",
			Ud: "averiguaba",
			nosotros: "averiguábamos",
			vosotros: "averiguabais",
			Uds: "averiguaban",
		},
		Conditional: {
			yo: "averiguaría",
			tú: "averiguarías",
			Ud: "averiguaría",
			nosotros: "averiguaríamos",
			vosotros: "averiguaríais",
			Uds: "averiguarían",
		},
		Future: {
			yo: "averiguaré",
			tú: "averiguarás",
			Ud: "averiguará",
			nosotros: "averiguaremos",
			vosotros: "averiguaréis",
			Uds: "averiguarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "averigüe",
			tú: "averigües",
			Ud: "averigüe",
			nosotros: "averigüemos",
			vosotros: "averigüéis",
			Uds: "averigüen",
		},
		Imperfect: {
			yo: "averiguara",
			tú: "averiguaras",
			Ud: "averiguara",
			nosotros: "averiguáramos",
			vosotros: "averiguarais",
			Uds: "averiguaran",
		},
		Imperfect2: {
			yo: "averiguase",
			tú: "averiguases",
			Ud: "averiguase",
			nosotros: "averiguásemos",
			vosotros: "averiguaseis",
			Uds: "averiguasen",
		},
		Future: {
			yo: "averiguare",
			tú: "averiguares",
			Ud: "averiguare",
			nosotros: "averiguáremos",
			vosotros: "averiguareis",
			Uds: "averiguaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "averigua",
			Ud: "averigüe",
			nosotros: "averigüemos",
			vosotros: "averiguad",
			Uds: "averigüen",
		},
		Negative: {
			tú: "no averigües",
			Ud: "no averigüe",
			nosotros: "no averigüemos",
			vosotros: "no averigüéis",
			Uds: "no averigüen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy averiguando",
			tú: "estás averiguando",
			Ud: "está averiguando",
			nosotros: "estamos averiguando",
			vosotros: "estáis averiguando",
			Uds: "están averiguando",
		},
		Preterite: {
			yo: "estuve averiguando",
			tú: "estuviste averiguando",
			Ud: "estuvo averiguando",
			nosotros: "estuvimos averiguando",
			vosotros: "estuvisteis averiguando",
			Uds: "estuvieron averiguando",
		},
		Imperfect: {
			Uds: "estaban averiguando",
			yo: "estaba averiguando",
			tú: "estabas averiguando",
			Ud: "estaba averiguando",
			nosotros: "estábamos averiguando",
			vosotros: "estabais averiguando",
		},
		Conditional: {
			yo: "estaría averiguando",
			tú: "estarías averiguando",
			Ud: "estaría averiguando",
			nosotros: "estaríamos averiguando",
			vosotros: "estaríais averiguando",
			Uds: "estarían averiguando",
		},
		Future: {
			yo: "estaré averiguando",
			tú: "estarás averiguando",
			Ud: "estará averiguando",
			nosotros: "estaremos averiguando",
			vosotros: "estaréis averiguando",
			Uds: "estarán averiguando",
		},
	},
	Perfect: {
		Present: {
			yo: "he averiguado",
			tú: "has averiguado",
			Ud: "ha averiguado",
			nosotros: "hemos averiguado",
			vosotros: "habéis averiguado",
			Uds: "han averiguado",
		},
		Preterite: {
			yo: "hube averiguado",
			tú: "hubiste averiguado",
			Ud: "hubo averiguado",
			nosotros: "hubimos averiguado",
			vosotros: "hubisteis averiguado",
			Uds: "hubieron averiguado",
		},
		Past: {
			yo: "había averiguado",
			tú: "habías averiguado",
			Ud: "había averiguado",
			nosotros: "habíamos averiguado",
			vosotros: "habíais averiguado",
			Uds: "habían averiguado",
		},
		Conditional: {
			yo: "habría averiguado",
			tú: "habrías averiguado",
			Ud: "habría averiguado",
			nosotros: "habríamos averiguado",
			vosotros: "habríais averiguado",
			Uds: "habrían averiguado",
		},
		Future: {
			yo: "habré averiguado",
			tú: "habrás averiguado",
			Ud: "habrá averiguado",
			nosotros: "habremos averiguado",
			vosotros: "habréis averiguado",
			Uds: "habrán averiguado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya averiguado",
			tú: "hayas averiguado",
			Ud: "haya averiguado",
			nosotros: "hayamos averiguado",
			vosotros: "hayáis averiguado",
			Uds: "hayan averiguado",
		},
		Past: {
			yo: "hubiera averiguado",
			tú: "hubieras averiguado",
			Ud: "hubiera averiguado",
			nosotros: "hubiéramos averiguado",
			vosotros: "hubierais averiguado",
			Uds: "hubieran averiguado",
		},
		Future: {
			yo: "hubiere averiguado",
			tú: "hubieres averiguado",
			Ud: "hubiere averiguado",
			nosotros: "hubiéremos averiguado",
			vosotros: "hubiereis averiguado",
			Uds: "hubieren averiguado",
		},
	},
}
