var babear = {
	Indicative: {
		Present: {
			yo: "babeo",
			tú: "babeas",
			Ud: "babea",
			nosotros: "babeamos",
			vosotros: "babeáis",
			Uds: "babean",
		},
		Preterite: {
			yo: "babeé",
			tú: "babeaste",
			Ud: "babeó",
			nosotros: "babeamos",
			vosotros: "babeasteis",
			Uds: "babearon",
		},
		Imperfect: {
			yo: "babeaba",
			tú: "babeabas",
			Ud: "babeaba",
			nosotros: "babeábamos",
			vosotros: "babeabais",
			Uds: "babeaban",
		},
		Conditional: {
			yo: "babearía",
			tú: "babearías",
			Ud: "babearía",
			nosotros: "babearíamos",
			vosotros: "babearíais",
			Uds: "babearían",
		},
		Future: {
			yo: "babearé",
			tú: "babearás",
			Ud: "babeará",
			nosotros: "babearemos",
			vosotros: "babearéis",
			Uds: "babearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "babee",
			tú: "babees",
			Ud: "babee",
			nosotros: "babeemos",
			vosotros: "babeéis",
			Uds: "babeen",
		},
		Imperfect: {
			yo: "babeara",
			tú: "babearas",
			Ud: "babeara",
			nosotros: "babeáramos",
			vosotros: "babearais",
			Uds: "babearan",
		},
		Imperfect2: {
			yo: "babease",
			tú: "babeases",
			Ud: "babease",
			nosotros: "babeásemos",
			vosotros: "babeaseis",
			Uds: "babeasen",
		},
		Future: {
			yo: "babeare",
			tú: "babeares",
			Ud: "babeare",
			nosotros: "babeáremos",
			vosotros: "babeareis",
			Uds: "babearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "babea",
			Ud: "babee",
			nosotros: "babeemos",
			vosotros: "babead",
			Uds: "babeen",
		},
		Negative: {
			tú: "no babees",
			Ud: "no babee",
			nosotros: "no babeemos",
			vosotros: "no babeéis",
			Uds: "no babeen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy babeando",
			tú: "estás babeando",
			Ud: "está babeando",
			nosotros: "estamos babeando",
			vosotros: "estáis babeando",
			Uds: "están babeando",
		},
		Preterite: {
			yo: "estuve babeando",
			tú: "estuviste babeando",
			Ud: "estuvo babeando",
			nosotros: "estuvimos babeando",
			vosotros: "estuvisteis babeando",
			Uds: "estuvieron babeando",
		},
		Imperfect: {
			Uds: "estaban babeando",
			yo: "estaba babeando",
			tú: "estabas babeando",
			Ud: "estaba babeando",
			nosotros: "estábamos babeando",
			vosotros: "estabais babeando",
		},
		Conditional: {
			yo: "estaría babeando",
			tú: "estarías babeando",
			Ud: "estaría babeando",
			nosotros: "estaríamos babeando",
			vosotros: "estaríais babeando",
			Uds: "estarían babeando",
		},
		Future: {
			yo: "estaré babeando",
			tú: "estarás babeando",
			Ud: "estará babeando",
			nosotros: "estaremos babeando",
			vosotros: "estaréis babeando",
			Uds: "estarán babeando",
		},
	},
	Perfect: {
		Present: {
			yo: "he babeado",
			tú: "has babeado",
			Ud: "ha babeado",
			nosotros: "hemos babeado",
			vosotros: "habéis babeado",
			Uds: "han babeado",
		},
		Preterite: {
			yo: "hube babeado",
			tú: "hubiste babeado",
			Ud: "hubo babeado",
			nosotros: "hubimos babeado",
			vosotros: "hubisteis babeado",
			Uds: "hubieron babeado",
		},
		Past: {
			yo: "había babeado",
			tú: "habías babeado",
			Ud: "había babeado",
			nosotros: "habíamos babeado",
			vosotros: "habíais babeado",
			Uds: "habían babeado",
		},
		Conditional: {
			yo: "habría babeado",
			tú: "habrías babeado",
			Ud: "habría babeado",
			nosotros: "habríamos babeado",
			vosotros: "habríais babeado",
			Uds: "habrían babeado",
		},
		Future: {
			yo: "habré babeado",
			tú: "habrás babeado",
			Ud: "habrá babeado",
			nosotros: "habremos babeado",
			vosotros: "habréis babeado",
			Uds: "habrán babeado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya babeado",
			tú: "hayas babeado",
			Ud: "haya babeado",
			nosotros: "hayamos babeado",
			vosotros: "hayáis babeado",
			Uds: "hayan babeado",
		},
		Past: {
			yo: "hubiera babeado",
			tú: "hubieras babeado",
			Ud: "hubiera babeado",
			nosotros: "hubiéramos babeado",
			vosotros: "hubierais babeado",
			Uds: "hubieran babeado",
		},
		Future: {
			yo: "hubiere babeado",
			tú: "hubieres babeado",
			Ud: "hubiere babeado",
			nosotros: "hubiéremos babeado",
			vosotros: "hubiereis babeado",
			Uds: "hubieren babeado",
		},
	},
}
