var bajar = {
	Indicative: {
		Present: {
			yo: "bajo",
			tú: "bajas",
			Ud: "baja",
			nosotros: "bajamos",
			vosotros: "bajáis",
			Uds: "bajan",
		},
		Preterite: {
			yo: "bajé",
			tú: "bajaste",
			Ud: "bajó",
			nosotros: "bajamos",
			vosotros: "bajasteis",
			Uds: "bajaron",
		},
		Imperfect: {
			yo: "bajaba",
			tú: "bajabas",
			Ud: "bajaba",
			nosotros: "bajábamos",
			vosotros: "bajabais",
			Uds: "bajaban",
		},
		Conditional: {
			yo: "bajaría",
			tú: "bajarías",
			Ud: "bajaría",
			nosotros: "bajaríamos",
			vosotros: "bajaríais",
			Uds: "bajarían",
		},
		Future: {
			yo: "bajaré",
			tú: "bajarás",
			Ud: "bajará",
			nosotros: "bajaremos",
			vosotros: "bajaréis",
			Uds: "bajarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "baje",
			tú: "bajes",
			Ud: "baje",
			nosotros: "bajemos",
			vosotros: "bajéis",
			Uds: "bajen",
		},
		Imperfect: {
			yo: "bajara",
			tú: "bajaras",
			Ud: "bajara",
			nosotros: "bajáramos",
			vosotros: "bajarais",
			Uds: "bajaran",
		},
		Imperfect2: {
			yo: "bajase",
			tú: "bajases",
			Ud: "bajase",
			nosotros: "bajásemos",
			vosotros: "bajaseis",
			Uds: "bajasen",
		},
		Future: {
			yo: "bajare",
			tú: "bajares",
			Ud: "bajare",
			nosotros: "bajáremos",
			vosotros: "bajareis",
			Uds: "bajaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "baja",
			Ud: "baje",
			nosotros: "bajemos",
			vosotros: "bajad",
			Uds: "bajen",
		},
		Negative: {
			tú: "no bajes",
			Ud: "no baje",
			nosotros: "no bajemos",
			vosotros: "no bajéis",
			Uds: "no bajen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy bajando",
			tú: "estás bajando",
			Ud: "está bajando",
			nosotros: "estamos bajando",
			vosotros: "estáis bajando",
			Uds: "están bajando",
		},
		Preterite: {
			yo: "estuve bajando",
			tú: "estuviste bajando",
			Ud: "estuvo bajando",
			nosotros: "estuvimos bajando",
			vosotros: "estuvisteis bajando",
			Uds: "estuvieron bajando",
		},
		Imperfect: {
			Uds: "estaban bajando",
			yo: "estaba bajando",
			tú: "estabas bajando",
			Ud: "estaba bajando",
			nosotros: "estábamos bajando",
			vosotros: "estabais bajando",
		},
		Conditional: {
			yo: "estaría bajando",
			tú: "estarías bajando",
			Ud: "estaría bajando",
			nosotros: "estaríamos bajando",
			vosotros: "estaríais bajando",
			Uds: "estarían bajando",
		},
		Future: {
			yo: "estaré bajando",
			tú: "estarás bajando",
			Ud: "estará bajando",
			nosotros: "estaremos bajando",
			vosotros: "estaréis bajando",
			Uds: "estarán bajando",
		},
	},
	Perfect: {
		Present: {
			yo: "he bajado",
			tú: "has bajado",
			Ud: "ha bajado",
			nosotros: "hemos bajado",
			vosotros: "habéis bajado",
			Uds: "han bajado",
		},
		Preterite: {
			yo: "hube bajado",
			tú: "hubiste bajado",
			Ud: "hubo bajado",
			nosotros: "hubimos bajado",
			vosotros: "hubisteis bajado",
			Uds: "hubieron bajado",
		},
		Past: {
			yo: "había bajado",
			tú: "habías bajado",
			Ud: "había bajado",
			nosotros: "habíamos bajado",
			vosotros: "habíais bajado",
			Uds: "habían bajado",
		},
		Conditional: {
			yo: "habría bajado",
			tú: "habrías bajado",
			Ud: "habría bajado",
			nosotros: "habríamos bajado",
			vosotros: "habríais bajado",
			Uds: "habrían bajado",
		},
		Future: {
			yo: "habré bajado",
			tú: "habrás bajado",
			Ud: "habrá bajado",
			nosotros: "habremos bajado",
			vosotros: "habréis bajado",
			Uds: "habrán bajado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya bajado",
			tú: "hayas bajado",
			Ud: "haya bajado",
			nosotros: "hayamos bajado",
			vosotros: "hayáis bajado",
			Uds: "hayan bajado",
		},
		Past: {
			yo: "hubiera bajado",
			tú: "hubieras bajado",
			Ud: "hubiera bajado",
			nosotros: "hubiéramos bajado",
			vosotros: "hubierais bajado",
			Uds: "hubieran bajado",
		},
		Future: {
			yo: "hubiere bajado",
			tú: "hubieres bajado",
			Ud: "hubiere bajado",
			nosotros: "hubiéremos bajado",
			vosotros: "hubiereis bajado",
			Uds: "hubieren bajado",
		},
	},
}
