var baldar = {
	Indicative: {
		Present: {
			yo: "baldo",
			tú: "baldas",
			Ud: "balda",
			nosotros: "baldamos",
			vosotros: "baldáis",
			Uds: "baldan",
		},
		Preterite: {
			yo: "baldé",
			tú: "baldaste",
			Ud: "baldó",
			nosotros: "baldamos",
			vosotros: "baldasteis",
			Uds: "baldaron",
		},
		Imperfect: {
			yo: "baldaba",
			tú: "baldabas",
			Ud: "baldaba",
			nosotros: "baldábamos",
			vosotros: "baldabais",
			Uds: "baldaban",
		},
		Conditional: {
			yo: "baldaría",
			tú: "baldarías",
			Ud: "baldaría",
			nosotros: "baldaríamos",
			vosotros: "baldaríais",
			Uds: "baldarían",
		},
		Future: {
			yo: "baldaré",
			tú: "baldarás",
			Ud: "baldará",
			nosotros: "baldaremos",
			vosotros: "baldaréis",
			Uds: "baldarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "balde",
			tú: "baldes",
			Ud: "balde",
			nosotros: "baldemos",
			vosotros: "baldéis",
			Uds: "balden",
		},
		Imperfect: {
			yo: "baldara",
			tú: "baldaras",
			Ud: "baldara",
			nosotros: "baldáramos",
			vosotros: "baldarais",
			Uds: "baldaran",
		},
		Imperfect2: {
			yo: "baldase",
			tú: "baldases",
			Ud: "baldase",
			nosotros: "baldásemos",
			vosotros: "baldaseis",
			Uds: "baldasen",
		},
		Future: {
			yo: "baldare",
			tú: "baldares",
			Ud: "baldare",
			nosotros: "baldáremos",
			vosotros: "baldareis",
			Uds: "baldaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "balda",
			Ud: "balde",
			nosotros: "baldemos",
			vosotros: "baldad",
			Uds: "balden",
		},
		Negative: {
			tú: "no baldes",
			Ud: "no balde",
			nosotros: "no baldemos",
			vosotros: "no baldéis",
			Uds: "no balden",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy baldando",
			tú: "estás baldando",
			Ud: "está baldando",
			nosotros: "estamos baldando",
			vosotros: "estáis baldando",
			Uds: "están baldando",
		},
		Preterite: {
			yo: "estuve baldando",
			tú: "estuviste baldando",
			Ud: "estuvo baldando",
			nosotros: "estuvimos baldando",
			vosotros: "estuvisteis baldando",
			Uds: "estuvieron baldando",
		},
		Imperfect: {
			Uds: "estaban baldando",
			yo: "estaba baldando",
			tú: "estabas baldando",
			Ud: "estaba baldando",
			nosotros: "estábamos baldando",
			vosotros: "estabais baldando",
		},
		Conditional: {
			yo: "estaría baldando",
			tú: "estarías baldando",
			Ud: "estaría baldando",
			nosotros: "estaríamos baldando",
			vosotros: "estaríais baldando",
			Uds: "estarían baldando",
		},
		Future: {
			yo: "estaré baldando",
			tú: "estarás baldando",
			Ud: "estará baldando",
			nosotros: "estaremos baldando",
			vosotros: "estaréis baldando",
			Uds: "estarán baldando",
		},
	},
	Perfect: {
		Present: {
			yo: "he baldado",
			tú: "has baldado",
			Ud: "ha baldado",
			nosotros: "hemos baldado",
			vosotros: "habéis baldado",
			Uds: "han baldado",
		},
		Preterite: {
			yo: "hube baldado",
			tú: "hubiste baldado",
			Ud: "hubo baldado",
			nosotros: "hubimos baldado",
			vosotros: "hubisteis baldado",
			Uds: "hubieron baldado",
		},
		Past: {
			yo: "había baldado",
			tú: "habías baldado",
			Ud: "había baldado",
			nosotros: "habíamos baldado",
			vosotros: "habíais baldado",
			Uds: "habían baldado",
		},
		Conditional: {
			yo: "habría baldado",
			tú: "habrías baldado",
			Ud: "habría baldado",
			nosotros: "habríamos baldado",
			vosotros: "habríais baldado",
			Uds: "habrían baldado",
		},
		Future: {
			yo: "habré baldado",
			tú: "habrás baldado",
			Ud: "habrá baldado",
			nosotros: "habremos baldado",
			vosotros: "habréis baldado",
			Uds: "habrán baldado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya baldado",
			tú: "hayas baldado",
			Ud: "haya baldado",
			nosotros: "hayamos baldado",
			vosotros: "hayáis baldado",
			Uds: "hayan baldado",
		},
		Past: {
			yo: "hubiera baldado",
			tú: "hubieras baldado",
			Ud: "hubiera baldado",
			nosotros: "hubiéramos baldado",
			vosotros: "hubierais baldado",
			Uds: "hubieran baldado",
		},
		Future: {
			yo: "hubiere baldado",
			tú: "hubieres baldado",
			Ud: "hubiere baldado",
			nosotros: "hubiéremos baldado",
			vosotros: "hubiereis baldado",
			Uds: "hubieren baldado",
		},
	},
}
