var bambolear = {
	Indicative: {
		Present: {
			yo: "bamboleo",
			tú: "bamboleas",
			Ud: "bambolea",
			nosotros: "bamboleamos",
			vosotros: "bamboleáis",
			Uds: "bambolean",
		},
		Preterite: {
			yo: "bamboleé",
			tú: "bamboleaste",
			Ud: "bamboleó",
			nosotros: "bamboleamos",
			vosotros: "bamboleasteis",
			Uds: "bambolearon",
		},
		Imperfect: {
			yo: "bamboleaba",
			tú: "bamboleabas",
			Ud: "bamboleaba",
			nosotros: "bamboleábamos",
			vosotros: "bamboleabais",
			Uds: "bamboleaban",
		},
		Conditional: {
			yo: "bambolearía",
			tú: "bambolearías",
			Ud: "bambolearía",
			nosotros: "bambolearíamos",
			vosotros: "bambolearíais",
			Uds: "bambolearían",
		},
		Future: {
			yo: "bambolearé",
			tú: "bambolearás",
			Ud: "bamboleará",
			nosotros: "bambolearemos",
			vosotros: "bambolearéis",
			Uds: "bambolearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "bambolee",
			tú: "bambolees",
			Ud: "bambolee",
			nosotros: "bamboleemos",
			vosotros: "bamboleéis",
			Uds: "bamboleen",
		},
		Imperfect: {
			yo: "bamboleara",
			tú: "bambolearas",
			Ud: "bamboleara",
			nosotros: "bamboleáramos",
			vosotros: "bambolearais",
			Uds: "bambolearan",
		},
		Imperfect2: {
			yo: "bambolease",
			tú: "bamboleases",
			Ud: "bambolease",
			nosotros: "bamboleásemos",
			vosotros: "bamboleaseis",
			Uds: "bamboleasen",
		},
		Future: {
			yo: "bamboleare",
			tú: "bamboleares",
			Ud: "bamboleare",
			nosotros: "bamboleáremos",
			vosotros: "bamboleareis",
			Uds: "bambolearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "bambolea",
			Ud: "bambolee",
			nosotros: "bamboleemos",
			vosotros: "bambolead",
			Uds: "bamboleen",
		},
		Negative: {
			tú: "no bambolees",
			Ud: "no bambolee",
			nosotros: "no bamboleemos",
			vosotros: "no bamboleéis",
			Uds: "no bamboleen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy bamboleando",
			tú: "estás bamboleando",
			Ud: "está bamboleando",
			nosotros: "estamos bamboleando",
			vosotros: "estáis bamboleando",
			Uds: "están bamboleando",
		},
		Preterite: {
			yo: "estuve bamboleando",
			tú: "estuviste bamboleando",
			Ud: "estuvo bamboleando",
			nosotros: "estuvimos bamboleando",
			vosotros: "estuvisteis bamboleando",
			Uds: "estuvieron bamboleando",
		},
		Imperfect: {
			Uds: "estaban bamboleando",
			yo: "estaba bamboleando",
			tú: "estabas bamboleando",
			Ud: "estaba bamboleando",
			nosotros: "estábamos bamboleando",
			vosotros: "estabais bamboleando",
		},
		Conditional: {
			yo: "estaría bamboleando",
			tú: "estarías bamboleando",
			Ud: "estaría bamboleando",
			nosotros: "estaríamos bamboleando",
			vosotros: "estaríais bamboleando",
			Uds: "estarían bamboleando",
		},
		Future: {
			yo: "estaré bamboleando",
			tú: "estarás bamboleando",
			Ud: "estará bamboleando",
			nosotros: "estaremos bamboleando",
			vosotros: "estaréis bamboleando",
			Uds: "estarán bamboleando",
		},
	},
	Perfect: {
		Present: {
			yo: "he bamboleado",
			tú: "has bamboleado",
			Ud: "ha bamboleado",
			nosotros: "hemos bamboleado",
			vosotros: "habéis bamboleado",
			Uds: "han bamboleado",
		},
		Preterite: {
			yo: "hube bamboleado",
			tú: "hubiste bamboleado",
			Ud: "hubo bamboleado",
			nosotros: "hubimos bamboleado",
			vosotros: "hubisteis bamboleado",
			Uds: "hubieron bamboleado",
		},
		Past: {
			yo: "había bamboleado",
			tú: "habías bamboleado",
			Ud: "había bamboleado",
			nosotros: "habíamos bamboleado",
			vosotros: "habíais bamboleado",
			Uds: "habían bamboleado",
		},
		Conditional: {
			yo: "habría bamboleado",
			tú: "habrías bamboleado",
			Ud: "habría bamboleado",
			nosotros: "habríamos bamboleado",
			vosotros: "habríais bamboleado",
			Uds: "habrían bamboleado",
		},
		Future: {
			yo: "habré bamboleado",
			tú: "habrás bamboleado",
			Ud: "habrá bamboleado",
			nosotros: "habremos bamboleado",
			vosotros: "habréis bamboleado",
			Uds: "habrán bamboleado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya bamboleado",
			tú: "hayas bamboleado",
			Ud: "haya bamboleado",
			nosotros: "hayamos bamboleado",
			vosotros: "hayáis bamboleado",
			Uds: "hayan bamboleado",
		},
		Past: {
			yo: "hubiera bamboleado",
			tú: "hubieras bamboleado",
			Ud: "hubiera bamboleado",
			nosotros: "hubiéramos bamboleado",
			vosotros: "hubierais bamboleado",
			Uds: "hubieran bamboleado",
		},
		Future: {
			yo: "hubiere bamboleado",
			tú: "hubieres bamboleado",
			Ud: "hubiere bamboleado",
			nosotros: "hubiéremos bamboleado",
			vosotros: "hubiereis bamboleado",
			Uds: "hubieren bamboleado",
		},
	},
}
