var barajar = {
	Indicative: {
		Present: {
			yo: "barajo",
			tú: "barajas",
			Ud: "baraja",
			nosotros: "barajamos",
			vosotros: "barajáis",
			Uds: "barajan",
		},
		Preterite: {
			yo: "barajé",
			tú: "barajaste",
			Ud: "barajó",
			nosotros: "barajamos",
			vosotros: "barajasteis",
			Uds: "barajaron",
		},
		Imperfect: {
			yo: "barajaba",
			tú: "barajabas",
			Ud: "barajaba",
			nosotros: "barajábamos",
			vosotros: "barajabais",
			Uds: "barajaban",
		},
		Conditional: {
			yo: "barajaría",
			tú: "barajarías",
			Ud: "barajaría",
			nosotros: "barajaríamos",
			vosotros: "barajaríais",
			Uds: "barajarían",
		},
		Future: {
			yo: "barajaré",
			tú: "barajarás",
			Ud: "barajará",
			nosotros: "barajaremos",
			vosotros: "barajaréis",
			Uds: "barajarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "baraje",
			tú: "barajes",
			Ud: "baraje",
			nosotros: "barajemos",
			vosotros: "barajéis",
			Uds: "barajen",
		},
		Imperfect: {
			yo: "barajara",
			tú: "barajaras",
			Ud: "barajara",
			nosotros: "barajáramos",
			vosotros: "barajarais",
			Uds: "barajaran",
		},
		Imperfect2: {
			yo: "barajase",
			tú: "barajases",
			Ud: "barajase",
			nosotros: "barajásemos",
			vosotros: "barajaseis",
			Uds: "barajasen",
		},
		Future: {
			yo: "barajare",
			tú: "barajares",
			Ud: "barajare",
			nosotros: "barajáremos",
			vosotros: "barajareis",
			Uds: "barajaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "baraja",
			Ud: "baraje",
			nosotros: "barajemos",
			vosotros: "barajad",
			Uds: "barajen",
		},
		Negative: {
			tú: "no barajes",
			Ud: "no baraje",
			nosotros: "no barajemos",
			vosotros: "no barajéis",
			Uds: "no barajen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy barajando",
			tú: "estás barajando",
			Ud: "está barajando",
			nosotros: "estamos barajando",
			vosotros: "estáis barajando",
			Uds: "están barajando",
		},
		Preterite: {
			yo: "estuve barajando",
			tú: "estuviste barajando",
			Ud: "estuvo barajando",
			nosotros: "estuvimos barajando",
			vosotros: "estuvisteis barajando",
			Uds: "estuvieron barajando",
		},
		Imperfect: {
			Uds: "estaban barajando",
			yo: "estaba barajando",
			tú: "estabas barajando",
			Ud: "estaba barajando",
			nosotros: "estábamos barajando",
			vosotros: "estabais barajando",
		},
		Conditional: {
			yo: "estaría barajando",
			tú: "estarías barajando",
			Ud: "estaría barajando",
			nosotros: "estaríamos barajando",
			vosotros: "estaríais barajando",
			Uds: "estarían barajando",
		},
		Future: {
			yo: "estaré barajando",
			tú: "estarás barajando",
			Ud: "estará barajando",
			nosotros: "estaremos barajando",
			vosotros: "estaréis barajando",
			Uds: "estarán barajando",
		},
	},
	Perfect: {
		Present: {
			yo: "he barajado",
			tú: "has barajado",
			Ud: "ha barajado",
			nosotros: "hemos barajado",
			vosotros: "habéis barajado",
			Uds: "han barajado",
		},
		Preterite: {
			yo: "hube barajado",
			tú: "hubiste barajado",
			Ud: "hubo barajado",
			nosotros: "hubimos barajado",
			vosotros: "hubisteis barajado",
			Uds: "hubieron barajado",
		},
		Past: {
			yo: "había barajado",
			tú: "habías barajado",
			Ud: "había barajado",
			nosotros: "habíamos barajado",
			vosotros: "habíais barajado",
			Uds: "habían barajado",
		},
		Conditional: {
			yo: "habría barajado",
			tú: "habrías barajado",
			Ud: "habría barajado",
			nosotros: "habríamos barajado",
			vosotros: "habríais barajado",
			Uds: "habrían barajado",
		},
		Future: {
			yo: "habré barajado",
			tú: "habrás barajado",
			Ud: "habrá barajado",
			nosotros: "habremos barajado",
			vosotros: "habréis barajado",
			Uds: "habrán barajado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya barajado",
			tú: "hayas barajado",
			Ud: "haya barajado",
			nosotros: "hayamos barajado",
			vosotros: "hayáis barajado",
			Uds: "hayan barajado",
		},
		Past: {
			yo: "hubiera barajado",
			tú: "hubieras barajado",
			Ud: "hubiera barajado",
			nosotros: "hubiéramos barajado",
			vosotros: "hubierais barajado",
			Uds: "hubieran barajado",
		},
		Future: {
			yo: "hubiere barajado",
			tú: "hubieres barajado",
			Ud: "hubiere barajado",
			nosotros: "hubiéremos barajado",
			vosotros: "hubiereis barajado",
			Uds: "hubieren barajado",
		},
	},
}
