var barrer = {
	Indicative: {
		Present: {
			yo: "barro",
			tú: "barres",
			Ud: "barre",
			nosotros: "barremos",
			vosotros: "barréis",
			Uds: "barren",
		},
		Preterite: {
			yo: "barrí",
			tú: "barriste",
			Ud: "barrió",
			nosotros: "barrimos",
			vosotros: "barristeis",
			Uds: "barrieron",
		},
		Imperfect: {
			yo: "barría",
			tú: "barrías",
			Ud: "barría",
			nosotros: "barríamos",
			vosotros: "barríais",
			Uds: "barrían",
		},
		Conditional: {
			yo: "barrería",
			tú: "barrerías",
			Ud: "barrería",
			nosotros: "barreríamos",
			vosotros: "barreríais",
			Uds: "barrerían",
		},
		Future: {
			yo: "barreré",
			tú: "barrerás",
			Ud: "barrerá",
			nosotros: "barreremos",
			vosotros: "barreréis",
			Uds: "barrerán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "barra",
			tú: "barras",
			Ud: "barra",
			nosotros: "barramos",
			vosotros: "barráis",
			Uds: "barran",
		},
		Imperfect: {
			yo: "barriera",
			tú: "barrieras",
			Ud: "barriera",
			nosotros: "barriéramos",
			vosotros: "barrierais",
			Uds: "barrieran",
		},
		Imperfect2: {
			yo: "barriese",
			tú: "barrieses",
			Ud: "barriese",
			nosotros: "barriésemos",
			vosotros: "barrieseis",
			Uds: "barriesen",
		},
		Future: {
			yo: "barriere",
			tú: "barrieres",
			Ud: "barriere",
			nosotros: "barriéremos",
			vosotros: "barriereis",
			Uds: "barrieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "barre",
			Ud: "barra",
			nosotros: "barramos",
			vosotros: "barred",
			Uds: "barran",
		},
		Negative: {
			tú: "no barras",
			Ud: "no barra",
			nosotros: "no barramos",
			vosotros: "no barráis",
			Uds: "no barran",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy barriendo",
			tú: "estás barriendo",
			Ud: "está barriendo",
			nosotros: "estamos barriendo",
			vosotros: "estáis barriendo",
			Uds: "están barriendo",
		},
		Preterite: {
			yo: "estuve barriendo",
			tú: "estuviste barriendo",
			Ud: "estuvo barriendo",
			nosotros: "estuvimos barriendo",
			vosotros: "estuvisteis barriendo",
			Uds: "estuvieron barriendo",
		},
		Imperfect: {
			Uds: "estaban barriendo",
			yo: "estaba barriendo",
			tú: "estabas barriendo",
			Ud: "estaba barriendo",
			nosotros: "estábamos barriendo",
			vosotros: "estabais barriendo",
		},
		Conditional: {
			yo: "estaría barriendo",
			tú: "estarías barriendo",
			Ud: "estaría barriendo",
			nosotros: "estaríamos barriendo",
			vosotros: "estaríais barriendo",
			Uds: "estarían barriendo",
		},
		Future: {
			yo: "estaré barriendo",
			tú: "estarás barriendo",
			Ud: "estará barriendo",
			nosotros: "estaremos barriendo",
			vosotros: "estaréis barriendo",
			Uds: "estarán barriendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he barrido",
			tú: "has barrido",
			Ud: "ha barrido",
			nosotros: "hemos barrido",
			vosotros: "habéis barrido",
			Uds: "han barrido",
		},
		Preterite: {
			yo: "hube barrido",
			tú: "hubiste barrido",
			Ud: "hubo barrido",
			nosotros: "hubimos barrido",
			vosotros: "hubisteis barrido",
			Uds: "hubieron barrido",
		},
		Past: {
			yo: "había barrido",
			tú: "habías barrido",
			Ud: "había barrido",
			nosotros: "habíamos barrido",
			vosotros: "habíais barrido",
			Uds: "habían barrido",
		},
		Conditional: {
			yo: "habría barrido",
			tú: "habrías barrido",
			Ud: "habría barrido",
			nosotros: "habríamos barrido",
			vosotros: "habríais barrido",
			Uds: "habrían barrido",
		},
		Future: {
			yo: "habré barrido",
			tú: "habrás barrido",
			Ud: "habrá barrido",
			nosotros: "habremos barrido",
			vosotros: "habréis barrido",
			Uds: "habrán barrido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya barrido",
			tú: "hayas barrido",
			Ud: "haya barrido",
			nosotros: "hayamos barrido",
			vosotros: "hayáis barrido",
			Uds: "hayan barrido",
		},
		Past: {
			yo: "hubiera barrido",
			tú: "hubieras barrido",
			Ud: "hubiera barrido",
			nosotros: "hubiéramos barrido",
			vosotros: "hubierais barrido",
			Uds: "hubieran barrido",
		},
		Future: {
			yo: "hubiere barrido",
			tú: "hubieres barrido",
			Ud: "hubiere barrido",
			nosotros: "hubiéremos barrido",
			vosotros: "hubiereis barrido",
			Uds: "hubieren barrido",
		},
	},
}
