var batear = {
	Indicative: {
		Present: {
			yo: "bateo",
			tú: "bateas",
			Ud: "batea",
			nosotros: "bateamos",
			vosotros: "bateáis",
			Uds: "batean",
		},
		Preterite: {
			yo: "bateé",
			tú: "bateaste",
			Ud: "bateó",
			nosotros: "bateamos",
			vosotros: "bateasteis",
			Uds: "batearon",
		},
		Imperfect: {
			yo: "bateaba",
			tú: "bateabas",
			Ud: "bateaba",
			nosotros: "bateábamos",
			vosotros: "bateabais",
			Uds: "bateaban",
		},
		Conditional: {
			yo: "batearía",
			tú: "batearías",
			Ud: "batearía",
			nosotros: "batearíamos",
			vosotros: "batearíais",
			Uds: "batearían",
		},
		Future: {
			yo: "batearé",
			tú: "batearás",
			Ud: "bateará",
			nosotros: "batearemos",
			vosotros: "batearéis",
			Uds: "batearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "batee",
			tú: "batees",
			Ud: "batee",
			nosotros: "bateemos",
			vosotros: "bateéis",
			Uds: "bateen",
		},
		Imperfect: {
			yo: "bateara",
			tú: "batearas",
			Ud: "bateara",
			nosotros: "bateáramos",
			vosotros: "batearais",
			Uds: "batearan",
		},
		Imperfect2: {
			yo: "batease",
			tú: "bateases",
			Ud: "batease",
			nosotros: "bateásemos",
			vosotros: "bateaseis",
			Uds: "bateasen",
		},
		Future: {
			yo: "bateare",
			tú: "bateares",
			Ud: "bateare",
			nosotros: "bateáremos",
			vosotros: "bateareis",
			Uds: "batearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "batea",
			Ud: "batee",
			nosotros: "bateemos",
			vosotros: "batead",
			Uds: "bateen",
		},
		Negative: {
			tú: "no batees",
			Ud: "no batee",
			nosotros: "no bateemos",
			vosotros: "no bateéis",
			Uds: "no bateen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy bateando",
			tú: "estás bateando",
			Ud: "está bateando",
			nosotros: "estamos bateando",
			vosotros: "estáis bateando",
			Uds: "están bateando",
		},
		Preterite: {
			yo: "estuve bateando",
			tú: "estuviste bateando",
			Ud: "estuvo bateando",
			nosotros: "estuvimos bateando",
			vosotros: "estuvisteis bateando",
			Uds: "estuvieron bateando",
		},
		Imperfect: {
			Uds: "estaban bateando",
			yo: "estaba bateando",
			tú: "estabas bateando",
			Ud: "estaba bateando",
			nosotros: "estábamos bateando",
			vosotros: "estabais bateando",
		},
		Conditional: {
			yo: "estaría bateando",
			tú: "estarías bateando",
			Ud: "estaría bateando",
			nosotros: "estaríamos bateando",
			vosotros: "estaríais bateando",
			Uds: "estarían bateando",
		},
		Future: {
			yo: "estaré bateando",
			tú: "estarás bateando",
			Ud: "estará bateando",
			nosotros: "estaremos bateando",
			vosotros: "estaréis bateando",
			Uds: "estarán bateando",
		},
	},
	Perfect: {
		Present: {
			yo: "he bateado",
			tú: "has bateado",
			Ud: "ha bateado",
			nosotros: "hemos bateado",
			vosotros: "habéis bateado",
			Uds: "han bateado",
		},
		Preterite: {
			yo: "hube bateado",
			tú: "hubiste bateado",
			Ud: "hubo bateado",
			nosotros: "hubimos bateado",
			vosotros: "hubisteis bateado",
			Uds: "hubieron bateado",
		},
		Past: {
			yo: "había bateado",
			tú: "habías bateado",
			Ud: "había bateado",
			nosotros: "habíamos bateado",
			vosotros: "habíais bateado",
			Uds: "habían bateado",
		},
		Conditional: {
			yo: "habría bateado",
			tú: "habrías bateado",
			Ud: "habría bateado",
			nosotros: "habríamos bateado",
			vosotros: "habríais bateado",
			Uds: "habrían bateado",
		},
		Future: {
			yo: "habré bateado",
			tú: "habrás bateado",
			Ud: "habrá bateado",
			nosotros: "habremos bateado",
			vosotros: "habréis bateado",
			Uds: "habrán bateado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya bateado",
			tú: "hayas bateado",
			Ud: "haya bateado",
			nosotros: "hayamos bateado",
			vosotros: "hayáis bateado",
			Uds: "hayan bateado",
		},
		Past: {
			yo: "hubiera bateado",
			tú: "hubieras bateado",
			Ud: "hubiera bateado",
			nosotros: "hubiéramos bateado",
			vosotros: "hubierais bateado",
			Uds: "hubieran bateado",
		},
		Future: {
			yo: "hubiere bateado",
			tú: "hubieres bateado",
			Ud: "hubiere bateado",
			nosotros: "hubiéremos bateado",
			vosotros: "hubiereis bateado",
			Uds: "hubieren bateado",
		},
	},
}
