var batir = {
	Indicative: {
		Present: {
			yo: "bato",
			tú: "bates",
			Ud: "bate",
			nosotros: "batimos",
			vosotros: "batís",
			Uds: "baten",
		},
		Preterite: {
			yo: "batí",
			tú: "batiste",
			Ud: "batió",
			nosotros: "batimos",
			vosotros: "batisteis",
			Uds: "batieron",
		},
		Imperfect: {
			yo: "batía",
			tú: "batías",
			Ud: "batía",
			nosotros: "batíamos",
			vosotros: "batíais",
			Uds: "batían",
		},
		Conditional: {
			yo: "batiría",
			tú: "batirías",
			Ud: "batiría",
			nosotros: "batiríamos",
			vosotros: "batiríais",
			Uds: "batirían",
		},
		Future: {
			yo: "batiré",
			tú: "batirás",
			Ud: "batirá",
			nosotros: "batiremos",
			vosotros: "batiréis",
			Uds: "batirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "bata",
			tú: "batas",
			Ud: "bata",
			nosotros: "batamos",
			vosotros: "batáis",
			Uds: "batan",
		},
		Imperfect: {
			yo: "batiera",
			tú: "batieras",
			Ud: "batiera",
			nosotros: "batiéramos",
			vosotros: "batierais",
			Uds: "batieran",
		},
		Imperfect2: {
			yo: "batiese",
			tú: "batieses",
			Ud: "batiese",
			nosotros: "batiésemos",
			vosotros: "batieseis",
			Uds: "batiesen",
		},
		Future: {
			yo: "batiere",
			tú: "batieres",
			Ud: "batiere",
			nosotros: "batiéremos",
			vosotros: "batiereis",
			Uds: "batieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "bate",
			Ud: "bata",
			nosotros: "batamos",
			vosotros: "batid",
			Uds: "batan",
		},
		Negative: {
			tú: "no batas",
			Ud: "no bata",
			nosotros: "no batamos",
			vosotros: "no batáis",
			Uds: "no batan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy batiendo",
			tú: "estás batiendo",
			Ud: "está batiendo",
			nosotros: "estamos batiendo",
			vosotros: "estáis batiendo",
			Uds: "están batiendo",
		},
		Preterite: {
			yo: "estuve batiendo",
			tú: "estuviste batiendo",
			Ud: "estuvo batiendo",
			nosotros: "estuvimos batiendo",
			vosotros: "estuvisteis batiendo",
			Uds: "estuvieron batiendo",
		},
		Imperfect: {
			Uds: "estaban batiendo",
			yo: "estaba batiendo",
			tú: "estabas batiendo",
			Ud: "estaba batiendo",
			nosotros: "estábamos batiendo",
			vosotros: "estabais batiendo",
		},
		Conditional: {
			yo: "estaría batiendo",
			tú: "estarías batiendo",
			Ud: "estaría batiendo",
			nosotros: "estaríamos batiendo",
			vosotros: "estaríais batiendo",
			Uds: "estarían batiendo",
		},
		Future: {
			yo: "estaré batiendo",
			tú: "estarás batiendo",
			Ud: "estará batiendo",
			nosotros: "estaremos batiendo",
			vosotros: "estaréis batiendo",
			Uds: "estarán batiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he batido",
			tú: "has batido",
			Ud: "ha batido",
			nosotros: "hemos batido",
			vosotros: "habéis batido",
			Uds: "han batido",
		},
		Preterite: {
			yo: "hube batido",
			tú: "hubiste batido",
			Ud: "hubo batido",
			nosotros: "hubimos batido",
			vosotros: "hubisteis batido",
			Uds: "hubieron batido",
		},
		Past: {
			yo: "había batido",
			tú: "habías batido",
			Ud: "había batido",
			nosotros: "habíamos batido",
			vosotros: "habíais batido",
			Uds: "habían batido",
		},
		Conditional: {
			yo: "habría batido",
			tú: "habrías batido",
			Ud: "habría batido",
			nosotros: "habríamos batido",
			vosotros: "habríais batido",
			Uds: "habrían batido",
		},
		Future: {
			yo: "habré batido",
			tú: "habrás batido",
			Ud: "habrá batido",
			nosotros: "habremos batido",
			vosotros: "habréis batido",
			Uds: "habrán batido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya batido",
			tú: "hayas batido",
			Ud: "haya batido",
			nosotros: "hayamos batido",
			vosotros: "hayáis batido",
			Uds: "hayan batido",
		},
		Past: {
			yo: "hubiera batido",
			tú: "hubieras batido",
			Ud: "hubiera batido",
			nosotros: "hubiéramos batido",
			vosotros: "hubierais batido",
			Uds: "hubieran batido",
		},
		Future: {
			yo: "hubiere batido",
			tú: "hubieres batido",
			Ud: "hubiere batido",
			nosotros: "hubiéremos batido",
			vosotros: "hubiereis batido",
			Uds: "hubieren batido",
		},
	},
}
