var bombardear = {
	Indicative: {
		Present: {
			yo: "bombardeo",
			tú: "bombardeas",
			Ud: "bombardea",
			nosotros: "bombardeamos",
			vosotros: "bombardeáis",
			Uds: "bombardean",
		},
		Preterite: {
			yo: "bombardeé",
			tú: "bombardeaste",
			Ud: "bombardeó",
			nosotros: "bombardeamos",
			vosotros: "bombardeasteis",
			Uds: "bombardearon",
		},
		Imperfect: {
			yo: "bombardeaba",
			tú: "bombardeabas",
			Ud: "bombardeaba",
			nosotros: "bombardeábamos",
			vosotros: "bombardeabais",
			Uds: "bombardeaban",
		},
		Conditional: {
			yo: "bombardearía",
			tú: "bombardearías",
			Ud: "bombardearía",
			nosotros: "bombardearíamos",
			vosotros: "bombardearíais",
			Uds: "bombardearían",
		},
		Future: {
			yo: "bombardearé",
			tú: "bombardearás",
			Ud: "bombardeará",
			nosotros: "bombardearemos",
			vosotros: "bombardearéis",
			Uds: "bombardearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "bombardee",
			tú: "bombardees",
			Ud: "bombardee",
			nosotros: "bombardeemos",
			vosotros: "bombardeéis",
			Uds: "bombardeen",
		},
		Imperfect: {
			yo: "bombardeara",
			tú: "bombardearas",
			Ud: "bombardeara",
			nosotros: "bombardeáramos",
			vosotros: "bombardearais",
			Uds: "bombardearan",
		},
		Imperfect2: {
			yo: "bombardease",
			tú: "bombardeases",
			Ud: "bombardease",
			nosotros: "bombardeásemos",
			vosotros: "bombardeaseis",
			Uds: "bombardeasen",
		},
		Future: {
			yo: "bombardeare",
			tú: "bombardeares",
			Ud: "bombardeare",
			nosotros: "bombardeáremos",
			vosotros: "bombardeareis",
			Uds: "bombardearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "bombardea",
			Ud: "bombardee",
			nosotros: "bombardeemos",
			vosotros: "bombardead",
			Uds: "bombardeen",
		},
		Negative: {
			tú: "no bombardees",
			Ud: "no bombardee",
			nosotros: "no bombardeemos",
			vosotros: "no bombardeéis",
			Uds: "no bombardeen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy bombardeando",
			tú: "estás bombardeando",
			Ud: "está bombardeando",
			nosotros: "estamos bombardeando",
			vosotros: "estáis bombardeando",
			Uds: "están bombardeando",
		},
		Preterite: {
			yo: "estuve bombardeando",
			tú: "estuviste bombardeando",
			Ud: "estuvo bombardeando",
			nosotros: "estuvimos bombardeando",
			vosotros: "estuvisteis bombardeando",
			Uds: "estuvieron bombardeando",
		},
		Imperfect: {
			Uds: "estaban bombardeando",
			yo: "estaba bombardeando",
			tú: "estabas bombardeando",
			Ud: "estaba bombardeando",
			nosotros: "estábamos bombardeando",
			vosotros: "estabais bombardeando",
		},
		Conditional: {
			yo: "estaría bombardeando",
			tú: "estarías bombardeando",
			Ud: "estaría bombardeando",
			nosotros: "estaríamos bombardeando",
			vosotros: "estaríais bombardeando",
			Uds: "estarían bombardeando",
		},
		Future: {
			yo: "estaré bombardeando",
			tú: "estarás bombardeando",
			Ud: "estará bombardeando",
			nosotros: "estaremos bombardeando",
			vosotros: "estaréis bombardeando",
			Uds: "estarán bombardeando",
		},
	},
	Perfect: {
		Present: {
			yo: "he bombardeado",
			tú: "has bombardeado",
			Ud: "ha bombardeado",
			nosotros: "hemos bombardeado",
			vosotros: "habéis bombardeado",
			Uds: "han bombardeado",
		},
		Preterite: {
			yo: "hube bombardeado",
			tú: "hubiste bombardeado",
			Ud: "hubo bombardeado",
			nosotros: "hubimos bombardeado",
			vosotros: "hubisteis bombardeado",
			Uds: "hubieron bombardeado",
		},
		Past: {
			yo: "había bombardeado",
			tú: "habías bombardeado",
			Ud: "había bombardeado",
			nosotros: "habíamos bombardeado",
			vosotros: "habíais bombardeado",
			Uds: "habían bombardeado",
		},
		Conditional: {
			yo: "habría bombardeado",
			tú: "habrías bombardeado",
			Ud: "habría bombardeado",
			nosotros: "habríamos bombardeado",
			vosotros: "habríais bombardeado",
			Uds: "habrían bombardeado",
		},
		Future: {
			yo: "habré bombardeado",
			tú: "habrás bombardeado",
			Ud: "habrá bombardeado",
			nosotros: "habremos bombardeado",
			vosotros: "habréis bombardeado",
			Uds: "habrán bombardeado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya bombardeado",
			tú: "hayas bombardeado",
			Ud: "haya bombardeado",
			nosotros: "hayamos bombardeado",
			vosotros: "hayáis bombardeado",
			Uds: "hayan bombardeado",
		},
		Past: {
			yo: "hubiera bombardeado",
			tú: "hubieras bombardeado",
			Ud: "hubiera bombardeado",
			nosotros: "hubiéramos bombardeado",
			vosotros: "hubierais bombardeado",
			Uds: "hubieran bombardeado",
		},
		Future: {
			yo: "hubiere bombardeado",
			tú: "hubieres bombardeado",
			Ud: "hubiere bombardeado",
			nosotros: "hubiéremos bombardeado",
			vosotros: "hubiereis bombardeado",
			Uds: "hubieren bombardeado",
		},
	},
}
