var bordar = {
	Indicative: {
		Present: {
			yo: "bordo",
			tú: "bordas",
			Ud: "borda",
			nosotros: "bordamos",
			vosotros: "bordáis",
			Uds: "bordan",
		},
		Preterite: {
			yo: "bordé",
			tú: "bordaste",
			Ud: "bordó",
			nosotros: "bordamos",
			vosotros: "bordasteis",
			Uds: "bordaron",
		},
		Imperfect: {
			yo: "bordaba",
			tú: "bordabas",
			Ud: "bordaba",
			nosotros: "bordábamos",
			vosotros: "bordabais",
			Uds: "bordaban",
		},
		Conditional: {
			yo: "bordaría",
			tú: "bordarías",
			Ud: "bordaría",
			nosotros: "bordaríamos",
			vosotros: "bordaríais",
			Uds: "bordarían",
		},
		Future: {
			yo: "bordaré",
			tú: "bordarás",
			Ud: "bordará",
			nosotros: "bordaremos",
			vosotros: "bordaréis",
			Uds: "bordarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "borde",
			tú: "bordes",
			Ud: "borde",
			nosotros: "bordemos",
			vosotros: "bordéis",
			Uds: "borden",
		},
		Imperfect: {
			yo: "bordara",
			tú: "bordaras",
			Ud: "bordara",
			nosotros: "bordáramos",
			vosotros: "bordarais",
			Uds: "bordaran",
		},
		Imperfect2: {
			yo: "bordase",
			tú: "bordases",
			Ud: "bordase",
			nosotros: "bordásemos",
			vosotros: "bordaseis",
			Uds: "bordasen",
		},
		Future: {
			yo: "bordare",
			tú: "bordares",
			Ud: "bordare",
			nosotros: "bordáremos",
			vosotros: "bordareis",
			Uds: "bordaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "borda",
			Ud: "borde",
			nosotros: "bordemos",
			vosotros: "bordad",
			Uds: "borden",
		},
		Negative: {
			tú: "no bordes",
			Ud: "no borde",
			nosotros: "no bordemos",
			vosotros: "no bordéis",
			Uds: "no borden",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy bordando",
			tú: "estás bordando",
			Ud: "está bordando",
			nosotros: "estamos bordando",
			vosotros: "estáis bordando",
			Uds: "están bordando",
		},
		Preterite: {
			yo: "estuve bordando",
			tú: "estuviste bordando",
			Ud: "estuvo bordando",
			nosotros: "estuvimos bordando",
			vosotros: "estuvisteis bordando",
			Uds: "estuvieron bordando",
		},
		Imperfect: {
			Uds: "estaban bordando",
			yo: "estaba bordando",
			tú: "estabas bordando",
			Ud: "estaba bordando",
			nosotros: "estábamos bordando",
			vosotros: "estabais bordando",
		},
		Conditional: {
			yo: "estaría bordando",
			tú: "estarías bordando",
			Ud: "estaría bordando",
			nosotros: "estaríamos bordando",
			vosotros: "estaríais bordando",
			Uds: "estarían bordando",
		},
		Future: {
			yo: "estaré bordando",
			tú: "estarás bordando",
			Ud: "estará bordando",
			nosotros: "estaremos bordando",
			vosotros: "estaréis bordando",
			Uds: "estarán bordando",
		},
	},
	Perfect: {
		Present: {
			yo: "he bordado",
			tú: "has bordado",
			Ud: "ha bordado",
			nosotros: "hemos bordado",
			vosotros: "habéis bordado",
			Uds: "han bordado",
		},
		Preterite: {
			yo: "hube bordado",
			tú: "hubiste bordado",
			Ud: "hubo bordado",
			nosotros: "hubimos bordado",
			vosotros: "hubisteis bordado",
			Uds: "hubieron bordado",
		},
		Past: {
			yo: "había bordado",
			tú: "habías bordado",
			Ud: "había bordado",
			nosotros: "habíamos bordado",
			vosotros: "habíais bordado",
			Uds: "habían bordado",
		},
		Conditional: {
			yo: "habría bordado",
			tú: "habrías bordado",
			Ud: "habría bordado",
			nosotros: "habríamos bordado",
			vosotros: "habríais bordado",
			Uds: "habrían bordado",
		},
		Future: {
			yo: "habré bordado",
			tú: "habrás bordado",
			Ud: "habrá bordado",
			nosotros: "habremos bordado",
			vosotros: "habréis bordado",
			Uds: "habrán bordado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya bordado",
			tú: "hayas bordado",
			Ud: "haya bordado",
			nosotros: "hayamos bordado",
			vosotros: "hayáis bordado",
			Uds: "hayan bordado",
		},
		Past: {
			yo: "hubiera bordado",
			tú: "hubieras bordado",
			Ud: "hubiera bordado",
			nosotros: "hubiéramos bordado",
			vosotros: "hubierais bordado",
			Uds: "hubieran bordado",
		},
		Future: {
			yo: "hubiere bordado",
			tú: "hubieres bordado",
			Ud: "hubiere bordado",
			nosotros: "hubiéremos bordado",
			vosotros: "hubiereis bordado",
			Uds: "hubieren bordado",
		},
	},
}
