var bostezar = {
	Indicative: {
		Present: {
			yo: "bostezo",
			tú: "bostezas",
			Ud: "bosteza",
			nosotros: "bostezamos",
			vosotros: "bostezáis",
			Uds: "bostezan",
		},
		Preterite: {
			yo: "bostecé",
			tú: "bostezaste",
			Ud: "bostezó",
			nosotros: "bostezamos",
			vosotros: "bostezasteis",
			Uds: "bostezaron",
		},
		Imperfect: {
			yo: "bostezaba",
			tú: "bostezabas",
			Ud: "bostezaba",
			nosotros: "bostezábamos",
			vosotros: "bostezabais",
			Uds: "bostezaban",
		},
		Conditional: {
			yo: "bostezaría",
			tú: "bostezarías",
			Ud: "bostezaría",
			nosotros: "bostezaríamos",
			vosotros: "bostezaríais",
			Uds: "bostezarían",
		},
		Future: {
			yo: "bostezaré",
			tú: "bostezarás",
			Ud: "bostezará",
			nosotros: "bostezaremos",
			vosotros: "bostezaréis",
			Uds: "bostezarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "bostece",
			tú: "bosteces",
			Ud: "bostece",
			nosotros: "bostecemos",
			vosotros: "bostecéis",
			Uds: "bostecen",
		},
		Imperfect: {
			yo: "bostezara",
			tú: "bostezaras",
			Ud: "bostezara",
			nosotros: "bostezáramos",
			vosotros: "bostezarais",
			Uds: "bostezaran",
		},
		Imperfect2: {
			yo: "bostezase",
			tú: "bostezases",
			Ud: "bostezase",
			nosotros: "bostezásemos",
			vosotros: "bostezaseis",
			Uds: "bostezasen",
		},
		Future: {
			yo: "bostezare",
			tú: "bostezares",
			Ud: "bostezare",
			nosotros: "bostezáremos",
			vosotros: "bostezareis",
			Uds: "bostezaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "bosteza",
			Ud: "bostece",
			nosotros: "bostecemos",
			vosotros: "bostezad",
			Uds: "bostecen",
		},
		Negative: {
			tú: "no bosteces",
			Ud: "no bostece",
			nosotros: "no bostecemos",
			vosotros: "no bostecéis",
			Uds: "no bostecen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy bostezando",
			tú: "estás bostezando",
			Ud: "está bostezando",
			nosotros: "estamos bostezando",
			vosotros: "estáis bostezando",
			Uds: "están bostezando",
		},
		Preterite: {
			yo: "estuve bostezando",
			tú: "estuviste bostezando",
			Ud: "estuvo bostezando",
			nosotros: "estuvimos bostezando",
			vosotros: "estuvisteis bostezando",
			Uds: "estuvieron bostezando",
		},
		Imperfect: {
			Uds: "estaban bostezando",
			yo: "estaba bostezando",
			tú: "estabas bostezando",
			Ud: "estaba bostezando",
			nosotros: "estábamos bostezando",
			vosotros: "estabais bostezando",
		},
		Conditional: {
			yo: "estaría bostezando",
			tú: "estarías bostezando",
			Ud: "estaría bostezando",
			nosotros: "estaríamos bostezando",
			vosotros: "estaríais bostezando",
			Uds: "estarían bostezando",
		},
		Future: {
			yo: "estaré bostezando",
			tú: "estarás bostezando",
			Ud: "estará bostezando",
			nosotros: "estaremos bostezando",
			vosotros: "estaréis bostezando",
			Uds: "estarán bostezando",
		},
	},
	Perfect: {
		Present: {
			yo: "he bostezado",
			tú: "has bostezado",
			Ud: "ha bostezado",
			nosotros: "hemos bostezado",
			vosotros: "habéis bostezado",
			Uds: "han bostezado",
		},
		Preterite: {
			yo: "hube bostezado",
			tú: "hubiste bostezado",
			Ud: "hubo bostezado",
			nosotros: "hubimos bostezado",
			vosotros: "hubisteis bostezado",
			Uds: "hubieron bostezado",
		},
		Past: {
			yo: "había bostezado",
			tú: "habías bostezado",
			Ud: "había bostezado",
			nosotros: "habíamos bostezado",
			vosotros: "habíais bostezado",
			Uds: "habían bostezado",
		},
		Conditional: {
			yo: "habría bostezado",
			tú: "habrías bostezado",
			Ud: "habría bostezado",
			nosotros: "habríamos bostezado",
			vosotros: "habríais bostezado",
			Uds: "habrían bostezado",
		},
		Future: {
			yo: "habré bostezado",
			tú: "habrás bostezado",
			Ud: "habrá bostezado",
			nosotros: "habremos bostezado",
			vosotros: "habréis bostezado",
			Uds: "habrán bostezado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya bostezado",
			tú: "hayas bostezado",
			Ud: "haya bostezado",
			nosotros: "hayamos bostezado",
			vosotros: "hayáis bostezado",
			Uds: "hayan bostezado",
		},
		Past: {
			yo: "hubiera bostezado",
			tú: "hubieras bostezado",
			Ud: "hubiera bostezado",
			nosotros: "hubiéramos bostezado",
			vosotros: "hubierais bostezado",
			Uds: "hubieran bostezado",
		},
		Future: {
			yo: "hubiere bostezado",
			tú: "hubieres bostezado",
			Ud: "hubiere bostezado",
			nosotros: "hubiéremos bostezado",
			vosotros: "hubiereis bostezado",
			Uds: "hubieren bostezado",
		},
	},
}
