var brillar = {
	Indicative: {
		Present: {
			yo: "brillo",
			tú: "brillas",
			Ud: "brilla",
			nosotros: "brillamos",
			vosotros: "brilláis",
			Uds: "brillan",
		},
		Preterite: {
			yo: "brillé",
			tú: "brillaste",
			Ud: "brilló",
			nosotros: "brillamos",
			vosotros: "brillasteis",
			Uds: "brillaron",
		},
		Imperfect: {
			yo: "brillaba",
			tú: "brillabas",
			Ud: "brillaba",
			nosotros: "brillábamos",
			vosotros: "brillabais",
			Uds: "brillaban",
		},
		Conditional: {
			yo: "brillaría",
			tú: "brillarías",
			Ud: "brillaría",
			nosotros: "brillaríamos",
			vosotros: "brillaríais",
			Uds: "brillarían",
		},
		Future: {
			yo: "brillaré",
			tú: "brillarás",
			Ud: "brillará",
			nosotros: "brillaremos",
			vosotros: "brillaréis",
			Uds: "brillarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "brille",
			tú: "brilles",
			Ud: "brille",
			nosotros: "brillemos",
			vosotros: "brilléis",
			Uds: "brillen",
		},
		Imperfect: {
			yo: "brillara",
			tú: "brillaras",
			Ud: "brillara",
			nosotros: "brilláramos",
			vosotros: "brillarais",
			Uds: "brillaran",
		},
		Imperfect2: {
			yo: "brillase",
			tú: "brillases",
			Ud: "brillase",
			nosotros: "brillásemos",
			vosotros: "brillaseis",
			Uds: "brillasen",
		},
		Future: {
			yo: "brillare",
			tú: "brillares",
			Ud: "brillare",
			nosotros: "brilláremos",
			vosotros: "brillareis",
			Uds: "brillaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "brilla",
			Ud: "brille",
			nosotros: "brillemos",
			vosotros: "brillad",
			Uds: "brillen",
		},
		Negative: {
			tú: "no brilles",
			Ud: "no brille",
			nosotros: "no brillemos",
			vosotros: "no brilléis",
			Uds: "no brillen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy brillando",
			tú: "estás brillando",
			Ud: "está brillando",
			nosotros: "estamos brillando",
			vosotros: "estáis brillando",
			Uds: "están brillando",
		},
		Preterite: {
			yo: "estuve brillando",
			tú: "estuviste brillando",
			Ud: "estuvo brillando",
			nosotros: "estuvimos brillando",
			vosotros: "estuvisteis brillando",
			Uds: "estuvieron brillando",
		},
		Imperfect: {
			Uds: "estaban brillando",
			yo: "estaba brillando",
			tú: "estabas brillando",
			Ud: "estaba brillando",
			nosotros: "estábamos brillando",
			vosotros: "estabais brillando",
		},
		Conditional: {
			yo: "estaría brillando",
			tú: "estarías brillando",
			Ud: "estaría brillando",
			nosotros: "estaríamos brillando",
			vosotros: "estaríais brillando",
			Uds: "estarían brillando",
		},
		Future: {
			yo: "estaré brillando",
			tú: "estarás brillando",
			Ud: "estará brillando",
			nosotros: "estaremos brillando",
			vosotros: "estaréis brillando",
			Uds: "estarán brillando",
		},
	},
	Perfect: {
		Present: {
			yo: "he brillado",
			tú: "has brillado",
			Ud: "ha brillado",
			nosotros: "hemos brillado",
			vosotros: "habéis brillado",
			Uds: "han brillado",
		},
		Preterite: {
			yo: "hube brillado",
			tú: "hubiste brillado",
			Ud: "hubo brillado",
			nosotros: "hubimos brillado",
			vosotros: "hubisteis brillado",
			Uds: "hubieron brillado",
		},
		Past: {
			yo: "había brillado",
			tú: "habías brillado",
			Ud: "había brillado",
			nosotros: "habíamos brillado",
			vosotros: "habíais brillado",
			Uds: "habían brillado",
		},
		Conditional: {
			yo: "habría brillado",
			tú: "habrías brillado",
			Ud: "habría brillado",
			nosotros: "habríamos brillado",
			vosotros: "habríais brillado",
			Uds: "habrían brillado",
		},
		Future: {
			yo: "habré brillado",
			tú: "habrás brillado",
			Ud: "habrá brillado",
			nosotros: "habremos brillado",
			vosotros: "habréis brillado",
			Uds: "habrán brillado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya brillado",
			tú: "hayas brillado",
			Ud: "haya brillado",
			nosotros: "hayamos brillado",
			vosotros: "hayáis brillado",
			Uds: "hayan brillado",
		},
		Past: {
			yo: "hubiera brillado",
			tú: "hubieras brillado",
			Ud: "hubiera brillado",
			nosotros: "hubiéramos brillado",
			vosotros: "hubierais brillado",
			Uds: "hubieran brillado",
		},
		Future: {
			yo: "hubiere brillado",
			tú: "hubieres brillado",
			Ud: "hubiere brillado",
			nosotros: "hubiéremos brillado",
			vosotros: "hubiereis brillado",
			Uds: "hubieren brillado",
		},
	},
}
