var bromear = {
	Indicative: {
		Present: {
			yo: "bromeo",
			tú: "bromeas",
			Ud: "bromea",
			nosotros: "bromeamos",
			vosotros: "bromeáis",
			Uds: "bromean",
		},
		Preterite: {
			yo: "bromeé",
			tú: "bromeaste",
			Ud: "bromeó",
			nosotros: "bromeamos",
			vosotros: "bromeasteis",
			Uds: "bromearon",
		},
		Imperfect: {
			yo: "bromeaba",
			tú: "bromeabas",
			Ud: "bromeaba",
			nosotros: "bromeábamos",
			vosotros: "bromeabais",
			Uds: "bromeaban",
		},
		Conditional: {
			yo: "bromearía",
			tú: "bromearías",
			Ud: "bromearía",
			nosotros: "bromearíamos",
			vosotros: "bromearíais",
			Uds: "bromearían",
		},
		Future: {
			yo: "bromearé",
			tú: "bromearás",
			Ud: "bromeará",
			nosotros: "bromearemos",
			vosotros: "bromearéis",
			Uds: "bromearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "bromee",
			tú: "bromees",
			Ud: "bromee",
			nosotros: "bromeemos",
			vosotros: "bromeéis",
			Uds: "bromeen",
		},
		Imperfect: {
			yo: "bromeara",
			tú: "bromearas",
			Ud: "bromeara",
			nosotros: "bromeáramos",
			vosotros: "bromearais",
			Uds: "bromearan",
		},
		Imperfect2: {
			yo: "bromease",
			tú: "bromeases",
			Ud: "bromease",
			nosotros: "bromeásemos",
			vosotros: "bromeaseis",
			Uds: "bromeasen",
		},
		Future: {
			yo: "bromeare",
			tú: "bromeares",
			Ud: "bromeare",
			nosotros: "bromeáremos",
			vosotros: "bromeareis",
			Uds: "bromearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "bromea",
			Ud: "bromee",
			nosotros: "bromeemos",
			vosotros: "bromead",
			Uds: "bromeen",
		},
		Negative: {
			tú: "no bromees",
			Ud: "no bromee",
			nosotros: "no bromeemos",
			vosotros: "no bromeéis",
			Uds: "no bromeen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy bromeando",
			tú: "estás bromeando",
			Ud: "está bromeando",
			nosotros: "estamos bromeando",
			vosotros: "estáis bromeando",
			Uds: "están bromeando",
		},
		Preterite: {
			yo: "estuve bromeando",
			tú: "estuviste bromeando",
			Ud: "estuvo bromeando",
			nosotros: "estuvimos bromeando",
			vosotros: "estuvisteis bromeando",
			Uds: "estuvieron bromeando",
		},
		Imperfect: {
			Uds: "estaban bromeando",
			yo: "estaba bromeando",
			tú: "estabas bromeando",
			Ud: "estaba bromeando",
			nosotros: "estábamos bromeando",
			vosotros: "estabais bromeando",
		},
		Conditional: {
			yo: "estaría bromeando",
			tú: "estarías bromeando",
			Ud: "estaría bromeando",
			nosotros: "estaríamos bromeando",
			vosotros: "estaríais bromeando",
			Uds: "estarían bromeando",
		},
		Future: {
			yo: "estaré bromeando",
			tú: "estarás bromeando",
			Ud: "estará bromeando",
			nosotros: "estaremos bromeando",
			vosotros: "estaréis bromeando",
			Uds: "estarán bromeando",
		},
	},
	Perfect: {
		Present: {
			yo: "he bromeado",
			tú: "has bromeado",
			Ud: "ha bromeado",
			nosotros: "hemos bromeado",
			vosotros: "habéis bromeado",
			Uds: "han bromeado",
		},
		Preterite: {
			yo: "hube bromeado",
			tú: "hubiste bromeado",
			Ud: "hubo bromeado",
			nosotros: "hubimos bromeado",
			vosotros: "hubisteis bromeado",
			Uds: "hubieron bromeado",
		},
		Past: {
			yo: "había bromeado",
			tú: "habías bromeado",
			Ud: "había bromeado",
			nosotros: "habíamos bromeado",
			vosotros: "habíais bromeado",
			Uds: "habían bromeado",
		},
		Conditional: {
			yo: "habría bromeado",
			tú: "habrías bromeado",
			Ud: "habría bromeado",
			nosotros: "habríamos bromeado",
			vosotros: "habríais bromeado",
			Uds: "habrían bromeado",
		},
		Future: {
			yo: "habré bromeado",
			tú: "habrás bromeado",
			Ud: "habrá bromeado",
			nosotros: "habremos bromeado",
			vosotros: "habréis bromeado",
			Uds: "habrán bromeado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya bromeado",
			tú: "hayas bromeado",
			Ud: "haya bromeado",
			nosotros: "hayamos bromeado",
			vosotros: "hayáis bromeado",
			Uds: "hayan bromeado",
		},
		Past: {
			yo: "hubiera bromeado",
			tú: "hubieras bromeado",
			Ud: "hubiera bromeado",
			nosotros: "hubiéramos bromeado",
			vosotros: "hubierais bromeado",
			Uds: "hubieran bromeado",
		},
		Future: {
			yo: "hubiere bromeado",
			tú: "hubieres bromeado",
			Ud: "hubiere bromeado",
			nosotros: "hubiéremos bromeado",
			vosotros: "hubiereis bromeado",
			Uds: "hubieren bromeado",
		},
	},
}
