var brotar = {
	Indicative: {
		Present: {
			yo: "broto",
			tú: "brotas",
			Ud: "brota",
			nosotros: "brotamos",
			vosotros: "brotáis",
			Uds: "brotan",
		},
		Preterite: {
			yo: "broté",
			tú: "brotaste",
			Ud: "brotó",
			nosotros: "brotamos",
			vosotros: "brotasteis",
			Uds: "brotaron",
		},
		Imperfect: {
			yo: "brotaba",
			tú: "brotabas",
			Ud: "brotaba",
			nosotros: "brotábamos",
			vosotros: "brotabais",
			Uds: "brotaban",
		},
		Conditional: {
			yo: "brotaría",
			tú: "brotarías",
			Ud: "brotaría",
			nosotros: "brotaríamos",
			vosotros: "brotaríais",
			Uds: "brotarían",
		},
		Future: {
			yo: "brotaré",
			tú: "brotarás",
			Ud: "brotará",
			nosotros: "brotaremos",
			vosotros: "brotaréis",
			Uds: "brotarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "brote",
			tú: "brotes",
			Ud: "brote",
			nosotros: "brotemos",
			vosotros: "brotéis",
			Uds: "broten",
		},
		Imperfect: {
			yo: "brotara",
			tú: "brotaras",
			Ud: "brotara",
			nosotros: "brotáramos",
			vosotros: "brotarais",
			Uds: "brotaran",
		},
		Imperfect2: {
			yo: "brotase",
			tú: "brotases",
			Ud: "brotase",
			nosotros: "brotásemos",
			vosotros: "brotaseis",
			Uds: "brotasen",
		},
		Future: {
			yo: "brotare",
			tú: "brotares",
			Ud: "brotare",
			nosotros: "brotáremos",
			vosotros: "brotareis",
			Uds: "brotaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "brota",
			Ud: "brote",
			nosotros: "brotemos",
			vosotros: "brotad",
			Uds: "broten",
		},
		Negative: {
			tú: "no brotes",
			Ud: "no brote",
			nosotros: "no brotemos",
			vosotros: "no brotéis",
			Uds: "no broten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy brotando",
			tú: "estás brotando",
			Ud: "está brotando",
			nosotros: "estamos brotando",
			vosotros: "estáis brotando",
			Uds: "están brotando",
		},
		Preterite: {
			yo: "estuve brotando",
			tú: "estuviste brotando",
			Ud: "estuvo brotando",
			nosotros: "estuvimos brotando",
			vosotros: "estuvisteis brotando",
			Uds: "estuvieron brotando",
		},
		Imperfect: {
			Uds: "estaban brotando",
			yo: "estaba brotando",
			tú: "estabas brotando",
			Ud: "estaba brotando",
			nosotros: "estábamos brotando",
			vosotros: "estabais brotando",
		},
		Conditional: {
			yo: "estaría brotando",
			tú: "estarías brotando",
			Ud: "estaría brotando",
			nosotros: "estaríamos brotando",
			vosotros: "estaríais brotando",
			Uds: "estarían brotando",
		},
		Future: {
			yo: "estaré brotando",
			tú: "estarás brotando",
			Ud: "estará brotando",
			nosotros: "estaremos brotando",
			vosotros: "estaréis brotando",
			Uds: "estarán brotando",
		},
	},
	Perfect: {
		Present: {
			yo: "he brotado",
			tú: "has brotado",
			Ud: "ha brotado",
			nosotros: "hemos brotado",
			vosotros: "habéis brotado",
			Uds: "han brotado",
		},
		Preterite: {
			yo: "hube brotado",
			tú: "hubiste brotado",
			Ud: "hubo brotado",
			nosotros: "hubimos brotado",
			vosotros: "hubisteis brotado",
			Uds: "hubieron brotado",
		},
		Past: {
			yo: "había brotado",
			tú: "habías brotado",
			Ud: "había brotado",
			nosotros: "habíamos brotado",
			vosotros: "habíais brotado",
			Uds: "habían brotado",
		},
		Conditional: {
			yo: "habría brotado",
			tú: "habrías brotado",
			Ud: "habría brotado",
			nosotros: "habríamos brotado",
			vosotros: "habríais brotado",
			Uds: "habrían brotado",
		},
		Future: {
			yo: "habré brotado",
			tú: "habrás brotado",
			Ud: "habrá brotado",
			nosotros: "habremos brotado",
			vosotros: "habréis brotado",
			Uds: "habrán brotado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya brotado",
			tú: "hayas brotado",
			Ud: "haya brotado",
			nosotros: "hayamos brotado",
			vosotros: "hayáis brotado",
			Uds: "hayan brotado",
		},
		Past: {
			yo: "hubiera brotado",
			tú: "hubieras brotado",
			Ud: "hubiera brotado",
			nosotros: "hubiéramos brotado",
			vosotros: "hubierais brotado",
			Uds: "hubieran brotado",
		},
		Future: {
			yo: "hubiere brotado",
			tú: "hubieres brotado",
			Ud: "hubiere brotado",
			nosotros: "hubiéremos brotado",
			vosotros: "hubiereis brotado",
			Uds: "hubieren brotado",
		},
	},
}
