var bucear = {
	Indicative: {
		Present: {
			yo: "buceo",
			tú: "buceas",
			Ud: "bucea",
			nosotros: "buceamos",
			vosotros: "buceáis",
			Uds: "bucean",
		},
		Preterite: {
			yo: "buceé",
			tú: "buceaste",
			Ud: "buceó",
			nosotros: "buceamos",
			vosotros: "buceasteis",
			Uds: "bucearon",
		},
		Imperfect: {
			yo: "buceaba",
			tú: "buceabas",
			Ud: "buceaba",
			nosotros: "buceábamos",
			vosotros: "buceabais",
			Uds: "buceaban",
		},
		Conditional: {
			yo: "bucearía",
			tú: "bucearías",
			Ud: "bucearía",
			nosotros: "bucearíamos",
			vosotros: "bucearíais",
			Uds: "bucearían",
		},
		Future: {
			yo: "bucearé",
			tú: "bucearás",
			Ud: "buceará",
			nosotros: "bucearemos",
			vosotros: "bucearéis",
			Uds: "bucearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "bucee",
			tú: "bucees",
			Ud: "bucee",
			nosotros: "buceemos",
			vosotros: "buceéis",
			Uds: "buceen",
		},
		Imperfect: {
			yo: "buceara",
			tú: "bucearas",
			Ud: "buceara",
			nosotros: "buceáramos",
			vosotros: "bucearais",
			Uds: "bucearan",
		},
		Imperfect2: {
			yo: "bucease",
			tú: "buceases",
			Ud: "bucease",
			nosotros: "buceásemos",
			vosotros: "buceaseis",
			Uds: "buceasen",
		},
		Future: {
			yo: "buceare",
			tú: "buceares",
			Ud: "buceare",
			nosotros: "buceáremos",
			vosotros: "buceareis",
			Uds: "bucearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "bucea",
			Ud: "bucee",
			nosotros: "buceemos",
			vosotros: "bucead",
			Uds: "buceen",
		},
		Negative: {
			tú: "no bucees",
			Ud: "no bucee",
			nosotros: "no buceemos",
			vosotros: "no buceéis",
			Uds: "no buceen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy buceando",
			tú: "estás buceando",
			Ud: "está buceando",
			nosotros: "estamos buceando",
			vosotros: "estáis buceando",
			Uds: "están buceando",
		},
		Preterite: {
			yo: "estuve buceando",
			tú: "estuviste buceando",
			Ud: "estuvo buceando",
			nosotros: "estuvimos buceando",
			vosotros: "estuvisteis buceando",
			Uds: "estuvieron buceando",
		},
		Imperfect: {
			Uds: "estaban buceando",
			yo: "estaba buceando",
			tú: "estabas buceando",
			Ud: "estaba buceando",
			nosotros: "estábamos buceando",
			vosotros: "estabais buceando",
		},
		Conditional: {
			yo: "estaría buceando",
			tú: "estarías buceando",
			Ud: "estaría buceando",
			nosotros: "estaríamos buceando",
			vosotros: "estaríais buceando",
			Uds: "estarían buceando",
		},
		Future: {
			yo: "estaré buceando",
			tú: "estarás buceando",
			Ud: "estará buceando",
			nosotros: "estaremos buceando",
			vosotros: "estaréis buceando",
			Uds: "estarán buceando",
		},
	},
	Perfect: {
		Present: {
			yo: "he buceado",
			tú: "has buceado",
			Ud: "ha buceado",
			nosotros: "hemos buceado",
			vosotros: "habéis buceado",
			Uds: "han buceado",
		},
		Preterite: {
			yo: "hube buceado",
			tú: "hubiste buceado",
			Ud: "hubo buceado",
			nosotros: "hubimos buceado",
			vosotros: "hubisteis buceado",
			Uds: "hubieron buceado",
		},
		Past: {
			yo: "había buceado",
			tú: "habías buceado",
			Ud: "había buceado",
			nosotros: "habíamos buceado",
			vosotros: "habíais buceado",
			Uds: "habían buceado",
		},
		Conditional: {
			yo: "habría buceado",
			tú: "habrías buceado",
			Ud: "habría buceado",
			nosotros: "habríamos buceado",
			vosotros: "habríais buceado",
			Uds: "habrían buceado",
		},
		Future: {
			yo: "habré buceado",
			tú: "habrás buceado",
			Ud: "habrá buceado",
			nosotros: "habremos buceado",
			vosotros: "habréis buceado",
			Uds: "habrán buceado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya buceado",
			tú: "hayas buceado",
			Ud: "haya buceado",
			nosotros: "hayamos buceado",
			vosotros: "hayáis buceado",
			Uds: "hayan buceado",
		},
		Past: {
			yo: "hubiera buceado",
			tú: "hubieras buceado",
			Ud: "hubiera buceado",
			nosotros: "hubiéramos buceado",
			vosotros: "hubierais buceado",
			Uds: "hubieran buceado",
		},
		Future: {
			yo: "hubiere buceado",
			tú: "hubieres buceado",
			Ud: "hubiere buceado",
			nosotros: "hubiéremos buceado",
			vosotros: "hubiereis buceado",
			Uds: "hubieren buceado",
		},
	},
}
