var caer = {
	Indicative: {
		Present: {
			yo: "caigo",
			tú: "caes",
			Ud: "cae",
			nosotros: "caemos",
			vosotros: "caéis",
			Uds: "caen",
		},
		Preterite: {
			yo: "caí",
			tú: "caíste",
			Ud: "cayó",
			nosotros: "caímos",
			vosotros: "caísteis",
			Uds: "cayeron",
		},
		Imperfect: {
			yo: "caía",
			tú: "caías",
			Ud: "caía",
			nosotros: "caíamos",
			vosotros: "caíais",
			Uds: "caían",
		},
		Conditional: {
			yo: "caería",
			tú: "caerías",
			Ud: "caería",
			nosotros: "caeríamos",
			vosotros: "caeríais",
			Uds: "caerían",
		},
		Future: {
			yo: "caeré",
			tú: "caerás",
			Ud: "caerá",
			nosotros: "caeremos",
			vosotros: "caeréis",
			Uds: "caerán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "caiga",
			tú: "caigas",
			Ud: "caiga",
			nosotros: "caigamos",
			vosotros: "caigáis",
			Uds: "caigan",
		},
		Imperfect: {
			yo: "cayera",
			tú: "cayeras",
			Ud: "cayera",
			nosotros: "cayéramos",
			vosotros: "cayerais",
			Uds: "cayeran",
		},
		Imperfect2: {
			yo: "cayese",
			tú: "cayeses",
			Ud: "cayese",
			nosotros: "cayésemos",
			vosotros: "cayeseis",
			Uds: "cayesen",
		},
		Future: {
			yo: "cayere",
			tú: "cayeres",
			Ud: "cayere",
			nosotros: "cayéremos",
			vosotros: "cayereis",
			Uds: "cayeren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "cae",
			Ud: "caiga",
			nosotros: "caigamos",
			vosotros: "caed",
			Uds: "caigan",
		},
		Negative: {
			tú: "no caigas",
			Ud: "no caiga",
			nosotros: "no caigamos",
			vosotros: "no caigáis",
			Uds: "no caigan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy cayendo",
			tú: "estás cayendo",
			Ud: "está cayendo",
			nosotros: "estamos cayendo",
			vosotros: "estáis cayendo",
			Uds: "están cayendo",
		},
		Preterite: {
			yo: "estuve cayendo",
			tú: "estuviste cayendo",
			Ud: "estuvo cayendo",
			nosotros: "estuvimos cayendo",
			vosotros: "estuvisteis cayendo",
			Uds: "estuvieron cayendo",
		},
		Imperfect: {
			Uds: "estaban cayendo",
			yo: "estaba cayendo",
			tú: "estabas cayendo",
			Ud: "estaba cayendo",
			nosotros: "estábamos cayendo",
			vosotros: "estabais cayendo",
		},
		Conditional: {
			yo: "estaría cayendo",
			tú: "estarías cayendo",
			Ud: "estaría cayendo",
			nosotros: "estaríamos cayendo",
			vosotros: "estaríais cayendo",
			Uds: "estarían cayendo",
		},
		Future: {
			yo: "estaré cayendo",
			tú: "estarás cayendo",
			Ud: "estará cayendo",
			nosotros: "estaremos cayendo",
			vosotros: "estaréis cayendo",
			Uds: "estarán cayendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he caído",
			tú: "has caído",
			Ud: "ha caído",
			nosotros: "hemos caído",
			vosotros: "habéis caído",
			Uds: "han caído",
		},
		Preterite: {
			yo: "hube caído",
			tú: "hubiste caído",
			Ud: "hubo caído",
			nosotros: "hubimos caído",
			vosotros: "hubisteis caído",
			Uds: "hubieron caído",
		},
		Past: {
			yo: "había caído",
			tú: "habías caído",
			Ud: "había caído",
			nosotros: "habíamos caído",
			vosotros: "habíais caído",
			Uds: "habían caído",
		},
		Conditional: {
			yo: "habría caído",
			tú: "habrías caído",
			Ud: "habría caído",
			nosotros: "habríamos caído",
			vosotros: "habríais caído",
			Uds: "habrían caído",
		},
		Future: {
			yo: "habré caído",
			tú: "habrás caído",
			Ud: "habrá caído",
			nosotros: "habremos caído",
			vosotros: "habréis caído",
			Uds: "habrán caído",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya caído",
			tú: "hayas caído",
			Ud: "haya caído",
			nosotros: "hayamos caído",
			vosotros: "hayáis caído",
			Uds: "hayan caído",
		},
		Past: {
			yo: "hubiera caído",
			tú: "hubieras caído",
			Ud: "hubiera caído",
			nosotros: "hubiéramos caído",
			vosotros: "hubierais caído",
			Uds: "hubieran caído",
		},
		Future: {
			yo: "hubiere caído",
			tú: "hubieres caído",
			Ud: "hubiere caído",
			nosotros: "hubiéremos caído",
			vosotros: "hubiereis caído",
			Uds: "hubieren caído",
		},
	},
}
