var calzar = {
	Indicative: {
		Present: {
			yo: "calzo",
			tú: "calzas",
			Ud: "calza",
			nosotros: "calzamos",
			vosotros: "calzáis",
			Uds: "calzan",
		},
		Preterite: {
			yo: "calcé",
			tú: "calzaste",
			Ud: "calzó",
			nosotros: "calzamos",
			vosotros: "calzasteis",
			Uds: "calzaron",
		},
		Imperfect: {
			yo: "calzaba",
			tú: "calzabas",
			Ud: "calzaba",
			nosotros: "calzábamos",
			vosotros: "calzabais",
			Uds: "calzaban",
		},
		Conditional: {
			yo: "calzaría",
			tú: "calzarías",
			Ud: "calzaría",
			nosotros: "calzaríamos",
			vosotros: "calzaríais",
			Uds: "calzarían",
		},
		Future: {
			yo: "calzaré",
			tú: "calzarás",
			Ud: "calzará",
			nosotros: "calzaremos",
			vosotros: "calzaréis",
			Uds: "calzarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "calce",
			tú: "calces",
			Ud: "calce",
			nosotros: "calcemos",
			vosotros: "calcéis",
			Uds: "calcen",
		},
		Imperfect: {
			yo: "calzara",
			tú: "calzaras",
			Ud: "calzara",
			nosotros: "calzáramos",
			vosotros: "calzarais",
			Uds: "calzaran",
		},
		Imperfect2: {
			yo: "calzase",
			tú: "calzases",
			Ud: "calzase",
			nosotros: "calzásemos",
			vosotros: "calzaseis",
			Uds: "calzasen",
		},
		Future: {
			yo: "calzare",
			tú: "calzares",
			Ud: "calzare",
			nosotros: "calzáremos",
			vosotros: "calzareis",
			Uds: "calzaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "calza",
			Ud: "calce",
			nosotros: "calcemos",
			vosotros: "calzad",
			Uds: "calcen",
		},
		Negative: {
			tú: "no calces",
			Ud: "no calce",
			nosotros: "no calcemos",
			vosotros: "no calcéis",
			Uds: "no calcen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy calzando",
			tú: "estás calzando",
			Ud: "está calzando",
			nosotros: "estamos calzando",
			vosotros: "estáis calzando",
			Uds: "están calzando",
		},
		Preterite: {
			yo: "estuve calzando",
			tú: "estuviste calzando",
			Ud: "estuvo calzando",
			nosotros: "estuvimos calzando",
			vosotros: "estuvisteis calzando",
			Uds: "estuvieron calzando",
		},
		Imperfect: {
			Uds: "estaban calzando",
			yo: "estaba calzando",
			tú: "estabas calzando",
			Ud: "estaba calzando",
			nosotros: "estábamos calzando",
			vosotros: "estabais calzando",
		},
		Conditional: {
			yo: "estaría calzando",
			tú: "estarías calzando",
			Ud: "estaría calzando",
			nosotros: "estaríamos calzando",
			vosotros: "estaríais calzando",
			Uds: "estarían calzando",
		},
		Future: {
			yo: "estaré calzando",
			tú: "estarás calzando",
			Ud: "estará calzando",
			nosotros: "estaremos calzando",
			vosotros: "estaréis calzando",
			Uds: "estarán calzando",
		},
	},
	Perfect: {
		Present: {
			yo: "he calzado",
			tú: "has calzado",
			Ud: "ha calzado",
			nosotros: "hemos calzado",
			vosotros: "habéis calzado",
			Uds: "han calzado",
		},
		Preterite: {
			yo: "hube calzado",
			tú: "hubiste calzado",
			Ud: "hubo calzado",
			nosotros: "hubimos calzado",
			vosotros: "hubisteis calzado",
			Uds: "hubieron calzado",
		},
		Past: {
			yo: "había calzado",
			tú: "habías calzado",
			Ud: "había calzado",
			nosotros: "habíamos calzado",
			vosotros: "habíais calzado",
			Uds: "habían calzado",
		},
		Conditional: {
			yo: "habría calzado",
			tú: "habrías calzado",
			Ud: "habría calzado",
			nosotros: "habríamos calzado",
			vosotros: "habríais calzado",
			Uds: "habrían calzado",
		},
		Future: {
			yo: "habré calzado",
			tú: "habrás calzado",
			Ud: "habrá calzado",
			nosotros: "habremos calzado",
			vosotros: "habréis calzado",
			Uds: "habrán calzado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya calzado",
			tú: "hayas calzado",
			Ud: "haya calzado",
			nosotros: "hayamos calzado",
			vosotros: "hayáis calzado",
			Uds: "hayan calzado",
		},
		Past: {
			yo: "hubiera calzado",
			tú: "hubieras calzado",
			Ud: "hubiera calzado",
			nosotros: "hubiéramos calzado",
			vosotros: "hubierais calzado",
			Uds: "hubieran calzado",
		},
		Future: {
			yo: "hubiere calzado",
			tú: "hubieres calzado",
			Ud: "hubiere calzado",
			nosotros: "hubiéremos calzado",
			vosotros: "hubiereis calzado",
			Uds: "hubieren calzado",
		},
	},
}
