var caminar = {
	Indicative: {
		Present: {
			yo: "camino",
			tú: "caminas",
			Ud: "camina",
			nosotros: "caminamos",
			vosotros: "camináis",
			Uds: "caminan",
		},
		Preterite: {
			yo: "caminé",
			tú: "caminaste",
			Ud: "caminó",
			nosotros: "caminamos",
			vosotros: "caminasteis",
			Uds: "caminaron",
		},
		Imperfect: {
			yo: "caminaba",
			tú: "caminabas",
			Ud: "caminaba",
			nosotros: "caminábamos",
			vosotros: "caminabais",
			Uds: "caminaban",
		},
		Conditional: {
			yo: "caminaría",
			tú: "caminarías",
			Ud: "caminaría",
			nosotros: "caminaríamos",
			vosotros: "caminaríais",
			Uds: "caminarían",
		},
		Future: {
			yo: "caminaré",
			tú: "caminarás",
			Ud: "caminará",
			nosotros: "caminaremos",
			vosotros: "caminaréis",
			Uds: "caminarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "camine",
			tú: "camines",
			Ud: "camine",
			nosotros: "caminemos",
			vosotros: "caminéis",
			Uds: "caminen",
		},
		Imperfect: {
			yo: "caminara",
			tú: "caminaras",
			Ud: "caminara",
			nosotros: "camináramos",
			vosotros: "caminarais",
			Uds: "caminaran",
		},
		Imperfect2: {
			yo: "caminase",
			tú: "caminases",
			Ud: "caminase",
			nosotros: "caminásemos",
			vosotros: "caminaseis",
			Uds: "caminasen",
		},
		Future: {
			yo: "caminare",
			tú: "caminares",
			Ud: "caminare",
			nosotros: "camináremos",
			vosotros: "caminareis",
			Uds: "caminaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "camina",
			Ud: "camine",
			nosotros: "caminemos",
			vosotros: "caminad",
			Uds: "caminen",
		},
		Negative: {
			tú: "no camines",
			Ud: "no camine",
			nosotros: "no caminemos",
			vosotros: "no caminéis",
			Uds: "no caminen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy caminando",
			tú: "estás caminando",
			Ud: "está caminando",
			nosotros: "estamos caminando",
			vosotros: "estáis caminando",
			Uds: "están caminando",
		},
		Preterite: {
			yo: "estuve caminando",
			tú: "estuviste caminando",
			Ud: "estuvo caminando",
			nosotros: "estuvimos caminando",
			vosotros: "estuvisteis caminando",
			Uds: "estuvieron caminando",
		},
		Imperfect: {
			Uds: "estaban caminando",
			yo: "estaba caminando",
			tú: "estabas caminando",
			Ud: "estaba caminando",
			nosotros: "estábamos caminando",
			vosotros: "estabais caminando",
		},
		Conditional: {
			yo: "estaría caminando",
			tú: "estarías caminando",
			Ud: "estaría caminando",
			nosotros: "estaríamos caminando",
			vosotros: "estaríais caminando",
			Uds: "estarían caminando",
		},
		Future: {
			yo: "estaré caminando",
			tú: "estarás caminando",
			Ud: "estará caminando",
			nosotros: "estaremos caminando",
			vosotros: "estaréis caminando",
			Uds: "estarán caminando",
		},
	},
	Perfect: {
		Present: {
			yo: "he caminado",
			tú: "has caminado",
			Ud: "ha caminado",
			nosotros: "hemos caminado",
			vosotros: "habéis caminado",
			Uds: "han caminado",
		},
		Preterite: {
			yo: "hube caminado",
			tú: "hubiste caminado",
			Ud: "hubo caminado",
			nosotros: "hubimos caminado",
			vosotros: "hubisteis caminado",
			Uds: "hubieron caminado",
		},
		Past: {
			yo: "había caminado",
			tú: "habías caminado",
			Ud: "había caminado",
			nosotros: "habíamos caminado",
			vosotros: "habíais caminado",
			Uds: "habían caminado",
		},
		Conditional: {
			yo: "habría caminado",
			tú: "habrías caminado",
			Ud: "habría caminado",
			nosotros: "habríamos caminado",
			vosotros: "habríais caminado",
			Uds: "habrían caminado",
		},
		Future: {
			yo: "habré caminado",
			tú: "habrás caminado",
			Ud: "habrá caminado",
			nosotros: "habremos caminado",
			vosotros: "habréis caminado",
			Uds: "habrán caminado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya caminado",
			tú: "hayas caminado",
			Ud: "haya caminado",
			nosotros: "hayamos caminado",
			vosotros: "hayáis caminado",
			Uds: "hayan caminado",
		},
		Past: {
			yo: "hubiera caminado",
			tú: "hubieras caminado",
			Ud: "hubiera caminado",
			nosotros: "hubiéramos caminado",
			vosotros: "hubierais caminado",
			Uds: "hubieran caminado",
		},
		Future: {
			yo: "hubiere caminado",
			tú: "hubieres caminado",
			Ud: "hubiere caminado",
			nosotros: "hubiéremos caminado",
			vosotros: "hubiereis caminado",
			Uds: "hubieren caminado",
		},
	},
}
