var cancelar = {
	Indicative: {
		Present: {
			yo: "cancelo",
			tú: "cancelas",
			Ud: "cancela",
			nosotros: "cancelamos",
			vosotros: "canceláis",
			Uds: "cancelan",
		},
		Preterite: {
			yo: "cancelé",
			tú: "cancelaste",
			Ud: "canceló",
			nosotros: "cancelamos",
			vosotros: "cancelasteis",
			Uds: "cancelaron",
		},
		Imperfect: {
			yo: "cancelaba",
			tú: "cancelabas",
			Ud: "cancelaba",
			nosotros: "cancelábamos",
			vosotros: "cancelabais",
			Uds: "cancelaban",
		},
		Conditional: {
			yo: "cancelaría",
			tú: "cancelarías",
			Ud: "cancelaría",
			nosotros: "cancelaríamos",
			vosotros: "cancelaríais",
			Uds: "cancelarían",
		},
		Future: {
			yo: "cancelaré",
			tú: "cancelarás",
			Ud: "cancelará",
			nosotros: "cancelaremos",
			vosotros: "cancelaréis",
			Uds: "cancelarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "cancele",
			tú: "canceles",
			Ud: "cancele",
			nosotros: "cancelemos",
			vosotros: "canceléis",
			Uds: "cancelen",
		},
		Imperfect: {
			yo: "cancelara",
			tú: "cancelaras",
			Ud: "cancelara",
			nosotros: "canceláramos",
			vosotros: "cancelarais",
			Uds: "cancelaran",
		},
		Imperfect2: {
			yo: "cancelase",
			tú: "cancelases",
			Ud: "cancelase",
			nosotros: "cancelásemos",
			vosotros: "cancelaseis",
			Uds: "cancelasen",
		},
		Future: {
			yo: "cancelare",
			tú: "cancelares",
			Ud: "cancelare",
			nosotros: "canceláremos",
			vosotros: "cancelareis",
			Uds: "cancelaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "cancela",
			Ud: "cancele",
			nosotros: "cancelemos",
			vosotros: "cancelad",
			Uds: "cancelen",
		},
		Negative: {
			tú: "no canceles",
			Ud: "no cancele",
			nosotros: "no cancelemos",
			vosotros: "no canceléis",
			Uds: "no cancelen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy cancelando",
			tú: "estás cancelando",
			Ud: "está cancelando",
			nosotros: "estamos cancelando",
			vosotros: "estáis cancelando",
			Uds: "están cancelando",
		},
		Preterite: {
			yo: "estuve cancelando",
			tú: "estuviste cancelando",
			Ud: "estuvo cancelando",
			nosotros: "estuvimos cancelando",
			vosotros: "estuvisteis cancelando",
			Uds: "estuvieron cancelando",
		},
		Imperfect: {
			Uds: "estaban cancelando",
			yo: "estaba cancelando",
			tú: "estabas cancelando",
			Ud: "estaba cancelando",
			nosotros: "estábamos cancelando",
			vosotros: "estabais cancelando",
		},
		Conditional: {
			yo: "estaría cancelando",
			tú: "estarías cancelando",
			Ud: "estaría cancelando",
			nosotros: "estaríamos cancelando",
			vosotros: "estaríais cancelando",
			Uds: "estarían cancelando",
		},
		Future: {
			yo: "estaré cancelando",
			tú: "estarás cancelando",
			Ud: "estará cancelando",
			nosotros: "estaremos cancelando",
			vosotros: "estaréis cancelando",
			Uds: "estarán cancelando",
		},
	},
	Perfect: {
		Present: {
			yo: "he cancelado",
			tú: "has cancelado",
			Ud: "ha cancelado",
			nosotros: "hemos cancelado",
			vosotros: "habéis cancelado",
			Uds: "han cancelado",
		},
		Preterite: {
			yo: "hube cancelado",
			tú: "hubiste cancelado",
			Ud: "hubo cancelado",
			nosotros: "hubimos cancelado",
			vosotros: "hubisteis cancelado",
			Uds: "hubieron cancelado",
		},
		Past: {
			yo: "había cancelado",
			tú: "habías cancelado",
			Ud: "había cancelado",
			nosotros: "habíamos cancelado",
			vosotros: "habíais cancelado",
			Uds: "habían cancelado",
		},
		Conditional: {
			yo: "habría cancelado",
			tú: "habrías cancelado",
			Ud: "habría cancelado",
			nosotros: "habríamos cancelado",
			vosotros: "habríais cancelado",
			Uds: "habrían cancelado",
		},
		Future: {
			yo: "habré cancelado",
			tú: "habrás cancelado",
			Ud: "habrá cancelado",
			nosotros: "habremos cancelado",
			vosotros: "habréis cancelado",
			Uds: "habrán cancelado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya cancelado",
			tú: "hayas cancelado",
			Ud: "haya cancelado",
			nosotros: "hayamos cancelado",
			vosotros: "hayáis cancelado",
			Uds: "hayan cancelado",
		},
		Past: {
			yo: "hubiera cancelado",
			tú: "hubieras cancelado",
			Ud: "hubiera cancelado",
			nosotros: "hubiéramos cancelado",
			vosotros: "hubierais cancelado",
			Uds: "hubieran cancelado",
		},
		Future: {
			yo: "hubiere cancelado",
			tú: "hubieres cancelado",
			Ud: "hubiere cancelado",
			nosotros: "hubiéremos cancelado",
			vosotros: "hubiereis cancelado",
			Uds: "hubieren cancelado",
		},
	},
}
