var cansar = {
	Indicative: {
		Present: {
			yo: "canso",
			tú: "cansas",
			Ud: "cansa",
			nosotros: "cansamos",
			vosotros: "cansáis",
			Uds: "cansan",
		},
		Preterite: {
			yo: "cansé",
			tú: "cansaste",
			Ud: "cansó",
			nosotros: "cansamos",
			vosotros: "cansasteis",
			Uds: "cansaron",
		},
		Imperfect: {
			yo: "cansaba",
			tú: "cansabas",
			Ud: "cansaba",
			nosotros: "cansábamos",
			vosotros: "cansabais",
			Uds: "cansaban",
		},
		Conditional: {
			yo: "cansaría",
			tú: "cansarías",
			Ud: "cansaría",
			nosotros: "cansaríamos",
			vosotros: "cansaríais",
			Uds: "cansarían",
		},
		Future: {
			yo: "cansaré",
			tú: "cansarás",
			Ud: "cansará",
			nosotros: "cansaremos",
			vosotros: "cansaréis",
			Uds: "cansarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "canse",
			tú: "canses",
			Ud: "canse",
			nosotros: "cansemos",
			vosotros: "canséis",
			Uds: "cansen",
		},
		Imperfect: {
			yo: "cansara",
			tú: "cansaras",
			Ud: "cansara",
			nosotros: "cansáramos",
			vosotros: "cansarais",
			Uds: "cansaran",
		},
		Imperfect2: {
			yo: "cansase",
			tú: "cansases",
			Ud: "cansase",
			nosotros: "cansásemos",
			vosotros: "cansaseis",
			Uds: "cansasen",
		},
		Future: {
			yo: "cansare",
			tú: "cansares",
			Ud: "cansare",
			nosotros: "cansáremos",
			vosotros: "cansareis",
			Uds: "cansaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "cansa",
			Ud: "canse",
			nosotros: "cansemos",
			vosotros: "cansad",
			Uds: "cansen",
		},
		Negative: {
			tú: "no canses",
			Ud: "no canse",
			nosotros: "no cansemos",
			vosotros: "no canséis",
			Uds: "no cansen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy cansando",
			tú: "estás cansando",
			Ud: "está cansando",
			nosotros: "estamos cansando",
			vosotros: "estáis cansando",
			Uds: "están cansando",
		},
		Preterite: {
			yo: "estuve cansando",
			tú: "estuviste cansando",
			Ud: "estuvo cansando",
			nosotros: "estuvimos cansando",
			vosotros: "estuvisteis cansando",
			Uds: "estuvieron cansando",
		},
		Imperfect: {
			Uds: "estaban cansando",
			yo: "estaba cansando",
			tú: "estabas cansando",
			Ud: "estaba cansando",
			nosotros: "estábamos cansando",
			vosotros: "estabais cansando",
		},
		Conditional: {
			yo: "estaría cansando",
			tú: "estarías cansando",
			Ud: "estaría cansando",
			nosotros: "estaríamos cansando",
			vosotros: "estaríais cansando",
			Uds: "estarían cansando",
		},
		Future: {
			yo: "estaré cansando",
			tú: "estarás cansando",
			Ud: "estará cansando",
			nosotros: "estaremos cansando",
			vosotros: "estaréis cansando",
			Uds: "estarán cansando",
		},
	},
	Perfect: {
		Present: {
			yo: "he cansado",
			tú: "has cansado",
			Ud: "ha cansado",
			nosotros: "hemos cansado",
			vosotros: "habéis cansado",
			Uds: "han cansado",
		},
		Preterite: {
			yo: "hube cansado",
			tú: "hubiste cansado",
			Ud: "hubo cansado",
			nosotros: "hubimos cansado",
			vosotros: "hubisteis cansado",
			Uds: "hubieron cansado",
		},
		Past: {
			yo: "había cansado",
			tú: "habías cansado",
			Ud: "había cansado",
			nosotros: "habíamos cansado",
			vosotros: "habíais cansado",
			Uds: "habían cansado",
		},
		Conditional: {
			yo: "habría cansado",
			tú: "habrías cansado",
			Ud: "habría cansado",
			nosotros: "habríamos cansado",
			vosotros: "habríais cansado",
			Uds: "habrían cansado",
		},
		Future: {
			yo: "habré cansado",
			tú: "habrás cansado",
			Ud: "habrá cansado",
			nosotros: "habremos cansado",
			vosotros: "habréis cansado",
			Uds: "habrán cansado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya cansado",
			tú: "hayas cansado",
			Ud: "haya cansado",
			nosotros: "hayamos cansado",
			vosotros: "hayáis cansado",
			Uds: "hayan cansado",
		},
		Past: {
			yo: "hubiera cansado",
			tú: "hubieras cansado",
			Ud: "hubiera cansado",
			nosotros: "hubiéramos cansado",
			vosotros: "hubierais cansado",
			Uds: "hubieran cansado",
		},
		Future: {
			yo: "hubiere cansado",
			tú: "hubieres cansado",
			Ud: "hubiere cansado",
			nosotros: "hubiéremos cansado",
			vosotros: "hubiereis cansado",
			Uds: "hubieren cansado",
		},
	},
}
