var cargar = {
	Indicative: {
		Present: {
			yo: "cargo",
			tú: "cargas",
			Ud: "carga",
			nosotros: "cargamos",
			vosotros: "cargáis",
			Uds: "cargan",
		},
		Preterite: {
			yo: "cargué",
			tú: "cargaste",
			Ud: "cargó",
			nosotros: "cargamos",
			vosotros: "cargasteis",
			Uds: "cargaron",
		},
		Imperfect: {
			yo: "cargaba",
			tú: "cargabas",
			Ud: "cargaba",
			nosotros: "cargábamos",
			vosotros: "cargabais",
			Uds: "cargaban",
		},
		Conditional: {
			yo: "cargaría",
			tú: "cargarías",
			Ud: "cargaría",
			nosotros: "cargaríamos",
			vosotros: "cargaríais",
			Uds: "cargarían",
		},
		Future: {
			yo: "cargaré",
			tú: "cargarás",
			Ud: "cargará",
			nosotros: "cargaremos",
			vosotros: "cargaréis",
			Uds: "cargarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "cargue",
			tú: "cargues",
			Ud: "cargue",
			nosotros: "carguemos",
			vosotros: "carguéis",
			Uds: "carguen",
		},
		Imperfect: {
			yo: "cargara",
			tú: "cargaras",
			Ud: "cargara",
			nosotros: "cargáramos",
			vosotros: "cargarais",
			Uds: "cargaran",
		},
		Imperfect2: {
			yo: "cargase",
			tú: "cargases",
			Ud: "cargase",
			nosotros: "cargásemos",
			vosotros: "cargaseis",
			Uds: "cargasen",
		},
		Future: {
			yo: "cargare",
			tú: "cargares",
			Ud: "cargare",
			nosotros: "cargáremos",
			vosotros: "cargareis",
			Uds: "cargaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "carga",
			Ud: "cargue",
			nosotros: "carguemos",
			vosotros: "cargad",
			Uds: "carguen",
		},
		Negative: {
			tú: "no cargues",
			Ud: "no cargue",
			nosotros: "no carguemos",
			vosotros: "no carguéis",
			Uds: "no carguen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy cargando",
			tú: "estás cargando",
			Ud: "está cargando",
			nosotros: "estamos cargando",
			vosotros: "estáis cargando",
			Uds: "están cargando",
		},
		Preterite: {
			yo: "estuve cargando",
			tú: "estuviste cargando",
			Ud: "estuvo cargando",
			nosotros: "estuvimos cargando",
			vosotros: "estuvisteis cargando",
			Uds: "estuvieron cargando",
		},
		Imperfect: {
			Uds: "estaban cargando",
			yo: "estaba cargando",
			tú: "estabas cargando",
			Ud: "estaba cargando",
			nosotros: "estábamos cargando",
			vosotros: "estabais cargando",
		},
		Conditional: {
			yo: "estaría cargando",
			tú: "estarías cargando",
			Ud: "estaría cargando",
			nosotros: "estaríamos cargando",
			vosotros: "estaríais cargando",
			Uds: "estarían cargando",
		},
		Future: {
			yo: "estaré cargando",
			tú: "estarás cargando",
			Ud: "estará cargando",
			nosotros: "estaremos cargando",
			vosotros: "estaréis cargando",
			Uds: "estarán cargando",
		},
	},
	Perfect: {
		Present: {
			yo: "he cargado",
			tú: "has cargado",
			Ud: "ha cargado",
			nosotros: "hemos cargado",
			vosotros: "habéis cargado",
			Uds: "han cargado",
		},
		Preterite: {
			yo: "hube cargado",
			tú: "hubiste cargado",
			Ud: "hubo cargado",
			nosotros: "hubimos cargado",
			vosotros: "hubisteis cargado",
			Uds: "hubieron cargado",
		},
		Past: {
			yo: "había cargado",
			tú: "habías cargado",
			Ud: "había cargado",
			nosotros: "habíamos cargado",
			vosotros: "habíais cargado",
			Uds: "habían cargado",
		},
		Conditional: {
			yo: "habría cargado",
			tú: "habrías cargado",
			Ud: "habría cargado",
			nosotros: "habríamos cargado",
			vosotros: "habríais cargado",
			Uds: "habrían cargado",
		},
		Future: {
			yo: "habré cargado",
			tú: "habrás cargado",
			Ud: "habrá cargado",
			nosotros: "habremos cargado",
			vosotros: "habréis cargado",
			Uds: "habrán cargado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya cargado",
			tú: "hayas cargado",
			Ud: "haya cargado",
			nosotros: "hayamos cargado",
			vosotros: "hayáis cargado",
			Uds: "hayan cargado",
		},
		Past: {
			yo: "hubiera cargado",
			tú: "hubieras cargado",
			Ud: "hubiera cargado",
			nosotros: "hubiéramos cargado",
			vosotros: "hubierais cargado",
			Uds: "hubieran cargado",
		},
		Future: {
			yo: "hubiere cargado",
			tú: "hubieres cargado",
			Ud: "hubiere cargado",
			nosotros: "hubiéremos cargado",
			vosotros: "hubiereis cargado",
			Uds: "hubieren cargado",
		},
	},
}
