var castrar = {
	Indicative: {
		Present: {
			yo: "castro",
			tú: "castras",
			Ud: "castra",
			nosotros: "castramos",
			vosotros: "castráis",
			Uds: "castran",
		},
		Preterite: {
			yo: "castré",
			tú: "castraste",
			Ud: "castró",
			nosotros: "castramos",
			vosotros: "castrasteis",
			Uds: "castraron",
		},
		Imperfect: {
			yo: "castraba",
			tú: "castrabas",
			Ud: "castraba",
			nosotros: "castrábamos",
			vosotros: "castrabais",
			Uds: "castraban",
		},
		Conditional: {
			yo: "castraría",
			tú: "castrarías",
			Ud: "castraría",
			nosotros: "castraríamos",
			vosotros: "castraríais",
			Uds: "castrarían",
		},
		Future: {
			yo: "castraré",
			tú: "castrarás",
			Ud: "castrará",
			nosotros: "castraremos",
			vosotros: "castraréis",
			Uds: "castrarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "castre",
			tú: "castres",
			Ud: "castre",
			nosotros: "castremos",
			vosotros: "castréis",
			Uds: "castren",
		},
		Imperfect: {
			yo: "castrara",
			tú: "castraras",
			Ud: "castrara",
			nosotros: "castráramos",
			vosotros: "castrarais",
			Uds: "castraran",
		},
		Imperfect2: {
			yo: "castrase",
			tú: "castrases",
			Ud: "castrase",
			nosotros: "castrásemos",
			vosotros: "castraseis",
			Uds: "castrasen",
		},
		Future: {
			yo: "castrare",
			tú: "castrares",
			Ud: "castrare",
			nosotros: "castráremos",
			vosotros: "castrareis",
			Uds: "castraren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "castra",
			Ud: "castre",
			nosotros: "castremos",
			vosotros: "castrad",
			Uds: "castren",
		},
		Negative: {
			tú: "no castres",
			Ud: "no castre",
			nosotros: "no castremos",
			vosotros: "no castréis",
			Uds: "no castren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy castrando",
			tú: "estás castrando",
			Ud: "está castrando",
			nosotros: "estamos castrando",
			vosotros: "estáis castrando",
			Uds: "están castrando",
		},
		Preterite: {
			yo: "estuve castrando",
			tú: "estuviste castrando",
			Ud: "estuvo castrando",
			nosotros: "estuvimos castrando",
			vosotros: "estuvisteis castrando",
			Uds: "estuvieron castrando",
		},
		Imperfect: {
			Uds: "estaban castrando",
			yo: "estaba castrando",
			tú: "estabas castrando",
			Ud: "estaba castrando",
			nosotros: "estábamos castrando",
			vosotros: "estabais castrando",
		},
		Conditional: {
			yo: "estaría castrando",
			tú: "estarías castrando",
			Ud: "estaría castrando",
			nosotros: "estaríamos castrando",
			vosotros: "estaríais castrando",
			Uds: "estarían castrando",
		},
		Future: {
			yo: "estaré castrando",
			tú: "estarás castrando",
			Ud: "estará castrando",
			nosotros: "estaremos castrando",
			vosotros: "estaréis castrando",
			Uds: "estarán castrando",
		},
	},
	Perfect: {
		Present: {
			yo: "he castrado",
			tú: "has castrado",
			Ud: "ha castrado",
			nosotros: "hemos castrado",
			vosotros: "habéis castrado",
			Uds: "han castrado",
		},
		Preterite: {
			yo: "hube castrado",
			tú: "hubiste castrado",
			Ud: "hubo castrado",
			nosotros: "hubimos castrado",
			vosotros: "hubisteis castrado",
			Uds: "hubieron castrado",
		},
		Past: {
			yo: "había castrado",
			tú: "habías castrado",
			Ud: "había castrado",
			nosotros: "habíamos castrado",
			vosotros: "habíais castrado",
			Uds: "habían castrado",
		},
		Conditional: {
			yo: "habría castrado",
			tú: "habrías castrado",
			Ud: "habría castrado",
			nosotros: "habríamos castrado",
			vosotros: "habríais castrado",
			Uds: "habrían castrado",
		},
		Future: {
			yo: "habré castrado",
			tú: "habrás castrado",
			Ud: "habrá castrado",
			nosotros: "habremos castrado",
			vosotros: "habréis castrado",
			Uds: "habrán castrado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya castrado",
			tú: "hayas castrado",
			Ud: "haya castrado",
			nosotros: "hayamos castrado",
			vosotros: "hayáis castrado",
			Uds: "hayan castrado",
		},
		Past: {
			yo: "hubiera castrado",
			tú: "hubieras castrado",
			Ud: "hubiera castrado",
			nosotros: "hubiéramos castrado",
			vosotros: "hubierais castrado",
			Uds: "hubieran castrado",
		},
		Future: {
			yo: "hubiere castrado",
			tú: "hubieres castrado",
			Ud: "hubiere castrado",
			nosotros: "hubiéremos castrado",
			vosotros: "hubiereis castrado",
			Uds: "hubieren castrado",
		},
	},
}
