var cecear = {
	Indicative: {
		Present: {
			yo: "ceceo",
			tú: "ceceas",
			Ud: "cecea",
			nosotros: "ceceamos",
			vosotros: "ceceáis",
			Uds: "cecean",
		},
		Preterite: {
			yo: "ceceé",
			tú: "ceceaste",
			Ud: "ceceó",
			nosotros: "ceceamos",
			vosotros: "ceceasteis",
			Uds: "cecearon",
		},
		Imperfect: {
			yo: "ceceaba",
			tú: "ceceabas",
			Ud: "ceceaba",
			nosotros: "ceceábamos",
			vosotros: "ceceabais",
			Uds: "ceceaban",
		},
		Conditional: {
			yo: "cecearía",
			tú: "cecearías",
			Ud: "cecearía",
			nosotros: "cecearíamos",
			vosotros: "cecearíais",
			Uds: "cecearían",
		},
		Future: {
			yo: "cecearé",
			tú: "cecearás",
			Ud: "ceceará",
			nosotros: "cecearemos",
			vosotros: "cecearéis",
			Uds: "cecearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "cecee",
			tú: "cecees",
			Ud: "cecee",
			nosotros: "ceceemos",
			vosotros: "ceceéis",
			Uds: "ceceen",
		},
		Imperfect: {
			yo: "ceceara",
			tú: "cecearas",
			Ud: "ceceara",
			nosotros: "ceceáramos",
			vosotros: "cecearais",
			Uds: "cecearan",
		},
		Imperfect2: {
			yo: "cecease",
			tú: "ceceases",
			Ud: "cecease",
			nosotros: "ceceásemos",
			vosotros: "ceceaseis",
			Uds: "ceceasen",
		},
		Future: {
			yo: "ceceare",
			tú: "ceceares",
			Ud: "ceceare",
			nosotros: "ceceáremos",
			vosotros: "ceceareis",
			Uds: "cecearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "cecea",
			Ud: "cecee",
			nosotros: "ceceemos",
			vosotros: "cecead",
			Uds: "ceceen",
		},
		Negative: {
			tú: "no cecees",
			Ud: "no cecee",
			nosotros: "no ceceemos",
			vosotros: "no ceceéis",
			Uds: "no ceceen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy ceceando",
			tú: "estás ceceando",
			Ud: "está ceceando",
			nosotros: "estamos ceceando",
			vosotros: "estáis ceceando",
			Uds: "están ceceando",
		},
		Preterite: {
			yo: "estuve ceceando",
			tú: "estuviste ceceando",
			Ud: "estuvo ceceando",
			nosotros: "estuvimos ceceando",
			vosotros: "estuvisteis ceceando",
			Uds: "estuvieron ceceando",
		},
		Imperfect: {
			Uds: "estaban ceceando",
			yo: "estaba ceceando",
			tú: "estabas ceceando",
			Ud: "estaba ceceando",
			nosotros: "estábamos ceceando",
			vosotros: "estabais ceceando",
		},
		Conditional: {
			yo: "estaría ceceando",
			tú: "estarías ceceando",
			Ud: "estaría ceceando",
			nosotros: "estaríamos ceceando",
			vosotros: "estaríais ceceando",
			Uds: "estarían ceceando",
		},
		Future: {
			yo: "estaré ceceando",
			tú: "estarás ceceando",
			Ud: "estará ceceando",
			nosotros: "estaremos ceceando",
			vosotros: "estaréis ceceando",
			Uds: "estarán ceceando",
		},
	},
	Perfect: {
		Present: {
			yo: "he ceceado",
			tú: "has ceceado",
			Ud: "ha ceceado",
			nosotros: "hemos ceceado",
			vosotros: "habéis ceceado",
			Uds: "han ceceado",
		},
		Preterite: {
			yo: "hube ceceado",
			tú: "hubiste ceceado",
			Ud: "hubo ceceado",
			nosotros: "hubimos ceceado",
			vosotros: "hubisteis ceceado",
			Uds: "hubieron ceceado",
		},
		Past: {
			yo: "había ceceado",
			tú: "habías ceceado",
			Ud: "había ceceado",
			nosotros: "habíamos ceceado",
			vosotros: "habíais ceceado",
			Uds: "habían ceceado",
		},
		Conditional: {
			yo: "habría ceceado",
			tú: "habrías ceceado",
			Ud: "habría ceceado",
			nosotros: "habríamos ceceado",
			vosotros: "habríais ceceado",
			Uds: "habrían ceceado",
		},
		Future: {
			yo: "habré ceceado",
			tú: "habrás ceceado",
			Ud: "habrá ceceado",
			nosotros: "habremos ceceado",
			vosotros: "habréis ceceado",
			Uds: "habrán ceceado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya ceceado",
			tú: "hayas ceceado",
			Ud: "haya ceceado",
			nosotros: "hayamos ceceado",
			vosotros: "hayáis ceceado",
			Uds: "hayan ceceado",
		},
		Past: {
			yo: "hubiera ceceado",
			tú: "hubieras ceceado",
			Ud: "hubiera ceceado",
			nosotros: "hubiéramos ceceado",
			vosotros: "hubierais ceceado",
			Uds: "hubieran ceceado",
		},
		Future: {
			yo: "hubiere ceceado",
			tú: "hubieres ceceado",
			Ud: "hubiere ceceado",
			nosotros: "hubiéremos ceceado",
			vosotros: "hubiereis ceceado",
			Uds: "hubieren ceceado",
		},
	},
}
