var cegar = {
	Indicative: {
		Present: {
			yo: "ciego",
			tú: "ciegas",
			Ud: "ciega",
			nosotros: "cegamos",
			vosotros: "cegáis",
			Uds: "ciegan",
		},
		Preterite: {
			yo: "cegué",
			tú: "cegaste",
			Ud: "cegó",
			nosotros: "cegamos",
			vosotros: "cegasteis",
			Uds: "cegaron",
		},
		Imperfect: {
			yo: "cegaba",
			tú: "cegabas",
			Ud: "cegaba",
			nosotros: "cegábamos",
			vosotros: "cegabais",
			Uds: "cegaban",
		},
		Conditional: {
			yo: "cegaría",
			tú: "cegarías",
			Ud: "cegaría",
			nosotros: "cegaríamos",
			vosotros: "cegaríais",
			Uds: "cegarían",
		},
		Future: {
			yo: "cegaré",
			tú: "cegarás",
			Ud: "cegará",
			nosotros: "cegaremos",
			vosotros: "cegaréis",
			Uds: "cegarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "ciegue",
			tú: "ciegues",
			Ud: "ciegue",
			nosotros: "ceguemos",
			vosotros: "ceguéis",
			Uds: "cieguen",
		},
		Imperfect: {
			yo: "cegara",
			tú: "cegaras",
			Ud: "cegara",
			nosotros: "cegáramos",
			vosotros: "cegarais",
			Uds: "cegaran",
		},
		Imperfect2: {
			yo: "cegase",
			tú: "cegases",
			Ud: "cegase",
			nosotros: "cegásemos",
			vosotros: "cegaseis",
			Uds: "cegasen",
		},
		Future: {
			yo: "cegare",
			tú: "cegares",
			Ud: "cegare",
			nosotros: "cegáremos",
			vosotros: "cegareis",
			Uds: "cegaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "ciega",
			Ud: "ciegue",
			nosotros: "ceguemos",
			vosotros: "cegad",
			Uds: "cieguen",
		},
		Negative: {
			tú: "no ciegues",
			Ud: "no ciegue",
			nosotros: "no ceguemos",
			vosotros: "no ceguéis",
			Uds: "no cieguen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy cegando",
			tú: "estás cegando",
			Ud: "está cegando",
			nosotros: "estamos cegando",
			vosotros: "estáis cegando",
			Uds: "están cegando",
		},
		Preterite: {
			yo: "estuve cegando",
			tú: "estuviste cegando",
			Ud: "estuvo cegando",
			nosotros: "estuvimos cegando",
			vosotros: "estuvisteis cegando",
			Uds: "estuvieron cegando",
		},
		Imperfect: {
			Uds: "estaban cegando",
			yo: "estaba cegando",
			tú: "estabas cegando",
			Ud: "estaba cegando",
			nosotros: "estábamos cegando",
			vosotros: "estabais cegando",
		},
		Conditional: {
			yo: "estaría cegando",
			tú: "estarías cegando",
			Ud: "estaría cegando",
			nosotros: "estaríamos cegando",
			vosotros: "estaríais cegando",
			Uds: "estarían cegando",
		},
		Future: {
			yo: "estaré cegando",
			tú: "estarás cegando",
			Ud: "estará cegando",
			nosotros: "estaremos cegando",
			vosotros: "estaréis cegando",
			Uds: "estarán cegando",
		},
	},
	Perfect: {
		Present: {
			yo: "he cegado",
			tú: "has cegado",
			Ud: "ha cegado",
			nosotros: "hemos cegado",
			vosotros: "habéis cegado",
			Uds: "han cegado",
		},
		Preterite: {
			yo: "hube cegado",
			tú: "hubiste cegado",
			Ud: "hubo cegado",
			nosotros: "hubimos cegado",
			vosotros: "hubisteis cegado",
			Uds: "hubieron cegado",
		},
		Past: {
			yo: "había cegado",
			tú: "habías cegado",
			Ud: "había cegado",
			nosotros: "habíamos cegado",
			vosotros: "habíais cegado",
			Uds: "habían cegado",
		},
		Conditional: {
			yo: "habría cegado",
			tú: "habrías cegado",
			Ud: "habría cegado",
			nosotros: "habríamos cegado",
			vosotros: "habríais cegado",
			Uds: "habrían cegado",
		},
		Future: {
			yo: "habré cegado",
			tú: "habrás cegado",
			Ud: "habrá cegado",
			nosotros: "habremos cegado",
			vosotros: "habréis cegado",
			Uds: "habrán cegado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya cegado",
			tú: "hayas cegado",
			Ud: "haya cegado",
			nosotros: "hayamos cegado",
			vosotros: "hayáis cegado",
			Uds: "hayan cegado",
		},
		Past: {
			yo: "hubiera cegado",
			tú: "hubieras cegado",
			Ud: "hubiera cegado",
			nosotros: "hubiéramos cegado",
			vosotros: "hubierais cegado",
			Uds: "hubieran cegado",
		},
		Future: {
			yo: "hubiere cegado",
			tú: "hubieres cegado",
			Ud: "hubiere cegado",
			nosotros: "hubiéremos cegado",
			vosotros: "hubiereis cegado",
			Uds: "hubieren cegado",
		},
	},
}
