var cementar = {
	Indicative: {
		Present: {
			yo: "cemento",
			tú: "cementas",
			Ud: "cementa",
			nosotros: "cementamos",
			vosotros: "cementáis",
			Uds: "cementan",
		},
		Preterite: {
			yo: "cementé",
			tú: "cementaste",
			Ud: "cementó",
			nosotros: "cementamos",
			vosotros: "cementasteis",
			Uds: "cementaron",
		},
		Imperfect: {
			yo: "cementaba",
			tú: "cementabas",
			Ud: "cementaba",
			nosotros: "cementábamos",
			vosotros: "cementabais",
			Uds: "cementaban",
		},
		Conditional: {
			yo: "cementaría",
			tú: "cementarías",
			Ud: "cementaría",
			nosotros: "cementaríamos",
			vosotros: "cementaríais",
			Uds: "cementarían",
		},
		Future: {
			yo: "cementaré",
			tú: "cementarás",
			Ud: "cementará",
			nosotros: "cementaremos",
			vosotros: "cementaréis",
			Uds: "cementarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "cemente",
			tú: "cementes",
			Ud: "cemente",
			nosotros: "cementemos",
			vosotros: "cementéis",
			Uds: "cementen",
		},
		Imperfect: {
			yo: "cementara",
			tú: "cementaras",
			Ud: "cementara",
			nosotros: "cementáramos",
			vosotros: "cementarais",
			Uds: "cementaran",
		},
		Imperfect2: {
			yo: "cementase",
			tú: "cementases",
			Ud: "cementase",
			nosotros: "cementásemos",
			vosotros: "cementaseis",
			Uds: "cementasen",
		},
		Future: {
			yo: "cementare",
			tú: "cementares",
			Ud: "cementare",
			nosotros: "cementáremos",
			vosotros: "cementareis",
			Uds: "cementaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "cementa",
			Ud: "cemente",
			nosotros: "cementemos",
			vosotros: "cementad",
			Uds: "cementen",
		},
		Negative: {
			tú: "no cementes",
			Ud: "no cemente",
			nosotros: "no cementemos",
			vosotros: "no cementéis",
			Uds: "no cementen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy cementando",
			tú: "estás cementando",
			Ud: "está cementando",
			nosotros: "estamos cementando",
			vosotros: "estáis cementando",
			Uds: "están cementando",
		},
		Preterite: {
			yo: "estuve cementando",
			tú: "estuviste cementando",
			Ud: "estuvo cementando",
			nosotros: "estuvimos cementando",
			vosotros: "estuvisteis cementando",
			Uds: "estuvieron cementando",
		},
		Imperfect: {
			Uds: "estaban cementando",
			yo: "estaba cementando",
			tú: "estabas cementando",
			Ud: "estaba cementando",
			nosotros: "estábamos cementando",
			vosotros: "estabais cementando",
		},
		Conditional: {
			yo: "estaría cementando",
			tú: "estarías cementando",
			Ud: "estaría cementando",
			nosotros: "estaríamos cementando",
			vosotros: "estaríais cementando",
			Uds: "estarían cementando",
		},
		Future: {
			yo: "estaré cementando",
			tú: "estarás cementando",
			Ud: "estará cementando",
			nosotros: "estaremos cementando",
			vosotros: "estaréis cementando",
			Uds: "estarán cementando",
		},
	},
	Perfect: {
		Present: {
			yo: "he cementado",
			tú: "has cementado",
			Ud: "ha cementado",
			nosotros: "hemos cementado",
			vosotros: "habéis cementado",
			Uds: "han cementado",
		},
		Preterite: {
			yo: "hube cementado",
			tú: "hubiste cementado",
			Ud: "hubo cementado",
			nosotros: "hubimos cementado",
			vosotros: "hubisteis cementado",
			Uds: "hubieron cementado",
		},
		Past: {
			yo: "había cementado",
			tú: "habías cementado",
			Ud: "había cementado",
			nosotros: "habíamos cementado",
			vosotros: "habíais cementado",
			Uds: "habían cementado",
		},
		Conditional: {
			yo: "habría cementado",
			tú: "habrías cementado",
			Ud: "habría cementado",
			nosotros: "habríamos cementado",
			vosotros: "habríais cementado",
			Uds: "habrían cementado",
		},
		Future: {
			yo: "habré cementado",
			tú: "habrás cementado",
			Ud: "habrá cementado",
			nosotros: "habremos cementado",
			vosotros: "habréis cementado",
			Uds: "habrán cementado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya cementado",
			tú: "hayas cementado",
			Ud: "haya cementado",
			nosotros: "hayamos cementado",
			vosotros: "hayáis cementado",
			Uds: "hayan cementado",
		},
		Past: {
			yo: "hubiera cementado",
			tú: "hubieras cementado",
			Ud: "hubiera cementado",
			nosotros: "hubiéramos cementado",
			vosotros: "hubierais cementado",
			Uds: "hubieran cementado",
		},
		Future: {
			yo: "hubiere cementado",
			tú: "hubieres cementado",
			Ud: "hubiere cementado",
			nosotros: "hubiéremos cementado",
			vosotros: "hubiereis cementado",
			Uds: "hubieren cementado",
		},
	},
}
