var charlar = {
	Indicative: {
		Present: {
			yo: "charlo",
			tú: "charlas",
			Ud: "charla",
			nosotros: "charlamos",
			vosotros: "charláis",
			Uds: "charlan",
		},
		Preterite: {
			yo: "charlé",
			tú: "charlaste",
			Ud: "charló",
			nosotros: "charlamos",
			vosotros: "charlasteis",
			Uds: "charlaron",
		},
		Imperfect: {
			yo: "charlaba",
			tú: "charlabas",
			Ud: "charlaba",
			nosotros: "charlábamos",
			vosotros: "charlabais",
			Uds: "charlaban",
		},
		Conditional: {
			yo: "charlaría",
			tú: "charlarías",
			Ud: "charlaría",
			nosotros: "charlaríamos",
			vosotros: "charlaríais",
			Uds: "charlarían",
		},
		Future: {
			yo: "charlaré",
			tú: "charlarás",
			Ud: "charlará",
			nosotros: "charlaremos",
			vosotros: "charlaréis",
			Uds: "charlarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "charle",
			tú: "charles",
			Ud: "charle",
			nosotros: "charlemos",
			vosotros: "charléis",
			Uds: "charlen",
		},
		Imperfect: {
			yo: "charlara",
			tú: "charlaras",
			Ud: "charlara",
			nosotros: "charláramos",
			vosotros: "charlarais",
			Uds: "charlaran",
		},
		Imperfect2: {
			yo: "charlase",
			tú: "charlases",
			Ud: "charlase",
			nosotros: "charlásemos",
			vosotros: "charlaseis",
			Uds: "charlasen",
		},
		Future: {
			yo: "charlare",
			tú: "charlares",
			Ud: "charlare",
			nosotros: "charláremos",
			vosotros: "charlareis",
			Uds: "charlaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "charla",
			Ud: "charle",
			nosotros: "charlemos",
			vosotros: "charlad",
			Uds: "charlen",
		},
		Negative: {
			tú: "no charles",
			Ud: "no charle",
			nosotros: "no charlemos",
			vosotros: "no charléis",
			Uds: "no charlen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy charlando",
			tú: "estás charlando",
			Ud: "está charlando",
			nosotros: "estamos charlando",
			vosotros: "estáis charlando",
			Uds: "están charlando",
		},
		Preterite: {
			yo: "estuve charlando",
			tú: "estuviste charlando",
			Ud: "estuvo charlando",
			nosotros: "estuvimos charlando",
			vosotros: "estuvisteis charlando",
			Uds: "estuvieron charlando",
		},
		Imperfect: {
			Uds: "estaban charlando",
			yo: "estaba charlando",
			tú: "estabas charlando",
			Ud: "estaba charlando",
			nosotros: "estábamos charlando",
			vosotros: "estabais charlando",
		},
		Conditional: {
			yo: "estaría charlando",
			tú: "estarías charlando",
			Ud: "estaría charlando",
			nosotros: "estaríamos charlando",
			vosotros: "estaríais charlando",
			Uds: "estarían charlando",
		},
		Future: {
			yo: "estaré charlando",
			tú: "estarás charlando",
			Ud: "estará charlando",
			nosotros: "estaremos charlando",
			vosotros: "estaréis charlando",
			Uds: "estarán charlando",
		},
	},
	Perfect: {
		Present: {
			yo: "he charlado",
			tú: "has charlado",
			Ud: "ha charlado",
			nosotros: "hemos charlado",
			vosotros: "habéis charlado",
			Uds: "han charlado",
		},
		Preterite: {
			yo: "hube charlado",
			tú: "hubiste charlado",
			Ud: "hubo charlado",
			nosotros: "hubimos charlado",
			vosotros: "hubisteis charlado",
			Uds: "hubieron charlado",
		},
		Past: {
			yo: "había charlado",
			tú: "habías charlado",
			Ud: "había charlado",
			nosotros: "habíamos charlado",
			vosotros: "habíais charlado",
			Uds: "habían charlado",
		},
		Conditional: {
			yo: "habría charlado",
			tú: "habrías charlado",
			Ud: "habría charlado",
			nosotros: "habríamos charlado",
			vosotros: "habríais charlado",
			Uds: "habrían charlado",
		},
		Future: {
			yo: "habré charlado",
			tú: "habrás charlado",
			Ud: "habrá charlado",
			nosotros: "habremos charlado",
			vosotros: "habréis charlado",
			Uds: "habrán charlado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya charlado",
			tú: "hayas charlado",
			Ud: "haya charlado",
			nosotros: "hayamos charlado",
			vosotros: "hayáis charlado",
			Uds: "hayan charlado",
		},
		Past: {
			yo: "hubiera charlado",
			tú: "hubieras charlado",
			Ud: "hubiera charlado",
			nosotros: "hubiéramos charlado",
			vosotros: "hubierais charlado",
			Uds: "hubieran charlado",
		},
		Future: {
			yo: "hubiere charlado",
			tú: "hubieres charlado",
			Ud: "hubiere charlado",
			nosotros: "hubiéremos charlado",
			vosotros: "hubiereis charlado",
			Uds: "hubieren charlado",
		},
	},
}
