var chupar = {
	Indicative: {
		Present: {
			yo: "chupo",
			tú: "chupas",
			Ud: "chupa",
			nosotros: "chupamos",
			vosotros: "chupáis",
			Uds: "chupan",
		},
		Preterite: {
			yo: "chupé",
			tú: "chupaste",
			Ud: "chupó",
			nosotros: "chupamos",
			vosotros: "chupasteis",
			Uds: "chuparon",
		},
		Imperfect: {
			yo: "chupaba",
			tú: "chupabas",
			Ud: "chupaba",
			nosotros: "chupábamos",
			vosotros: "chupabais",
			Uds: "chupaban",
		},
		Conditional: {
			yo: "chuparía",
			tú: "chuparías",
			Ud: "chuparía",
			nosotros: "chuparíamos",
			vosotros: "chuparíais",
			Uds: "chuparían",
		},
		Future: {
			yo: "chuparé",
			tú: "chuparás",
			Ud: "chupará",
			nosotros: "chuparemos",
			vosotros: "chuparéis",
			Uds: "chuparán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "chupe",
			tú: "chupes",
			Ud: "chupe",
			nosotros: "chupemos",
			vosotros: "chupéis",
			Uds: "chupen",
		},
		Imperfect: {
			yo: "chupara",
			tú: "chuparas",
			Ud: "chupara",
			nosotros: "chupáramos",
			vosotros: "chuparais",
			Uds: "chuparan",
		},
		Imperfect2: {
			yo: "chupase",
			tú: "chupases",
			Ud: "chupase",
			nosotros: "chupásemos",
			vosotros: "chupaseis",
			Uds: "chupasen",
		},
		Future: {
			yo: "chupare",
			tú: "chupares",
			Ud: "chupare",
			nosotros: "chupáremos",
			vosotros: "chupareis",
			Uds: "chuparen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "chupa",
			Ud: "chupe",
			nosotros: "chupemos",
			vosotros: "chupad",
			Uds: "chupen",
		},
		Negative: {
			tú: "no chupes",
			Ud: "no chupe",
			nosotros: "no chupemos",
			vosotros: "no chupéis",
			Uds: "no chupen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy chupando",
			tú: "estás chupando",
			Ud: "está chupando",
			nosotros: "estamos chupando",
			vosotros: "estáis chupando",
			Uds: "están chupando",
		},
		Preterite: {
			yo: "estuve chupando",
			tú: "estuviste chupando",
			Ud: "estuvo chupando",
			nosotros: "estuvimos chupando",
			vosotros: "estuvisteis chupando",
			Uds: "estuvieron chupando",
		},
		Imperfect: {
			Uds: "estaban chupando",
			yo: "estaba chupando",
			tú: "estabas chupando",
			Ud: "estaba chupando",
			nosotros: "estábamos chupando",
			vosotros: "estabais chupando",
		},
		Conditional: {
			yo: "estaría chupando",
			tú: "estarías chupando",
			Ud: "estaría chupando",
			nosotros: "estaríamos chupando",
			vosotros: "estaríais chupando",
			Uds: "estarían chupando",
		},
		Future: {
			yo: "estaré chupando",
			tú: "estarás chupando",
			Ud: "estará chupando",
			nosotros: "estaremos chupando",
			vosotros: "estaréis chupando",
			Uds: "estarán chupando",
		},
	},
	Perfect: {
		Present: {
			yo: "he chupado",
			tú: "has chupado",
			Ud: "ha chupado",
			nosotros: "hemos chupado",
			vosotros: "habéis chupado",
			Uds: "han chupado",
		},
		Preterite: {
			yo: "hube chupado",
			tú: "hubiste chupado",
			Ud: "hubo chupado",
			nosotros: "hubimos chupado",
			vosotros: "hubisteis chupado",
			Uds: "hubieron chupado",
		},
		Past: {
			yo: "había chupado",
			tú: "habías chupado",
			Ud: "había chupado",
			nosotros: "habíamos chupado",
			vosotros: "habíais chupado",
			Uds: "habían chupado",
		},
		Conditional: {
			yo: "habría chupado",
			tú: "habrías chupado",
			Ud: "habría chupado",
			nosotros: "habríamos chupado",
			vosotros: "habríais chupado",
			Uds: "habrían chupado",
		},
		Future: {
			yo: "habré chupado",
			tú: "habrás chupado",
			Ud: "habrá chupado",
			nosotros: "habremos chupado",
			vosotros: "habréis chupado",
			Uds: "habrán chupado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya chupado",
			tú: "hayas chupado",
			Ud: "haya chupado",
			nosotros: "hayamos chupado",
			vosotros: "hayáis chupado",
			Uds: "hayan chupado",
		},
		Past: {
			yo: "hubiera chupado",
			tú: "hubieras chupado",
			Ud: "hubiera chupado",
			nosotros: "hubiéramos chupado",
			vosotros: "hubierais chupado",
			Uds: "hubieran chupado",
		},
		Future: {
			yo: "hubiere chupado",
			tú: "hubieres chupado",
			Ud: "hubiere chupado",
			nosotros: "hubiéremos chupado",
			vosotros: "hubiereis chupado",
			Uds: "hubieren chupado",
		},
	},
}
