var cocinar = {
	Indicative: {
		Present: {
			yo: "cocino",
			tú: "cocinas",
			Ud: "cocina",
			nosotros: "cocinamos",
			vosotros: "cocináis",
			Uds: "cocinan",
		},
		Preterite: {
			yo: "cociné",
			tú: "cocinaste",
			Ud: "cocinó",
			nosotros: "cocinamos",
			vosotros: "cocinasteis",
			Uds: "cocinaron",
		},
		Imperfect: {
			yo: "cocinaba",
			tú: "cocinabas",
			Ud: "cocinaba",
			nosotros: "cocinábamos",
			vosotros: "cocinabais",
			Uds: "cocinaban",
		},
		Conditional: {
			yo: "cocinaría",
			tú: "cocinarías",
			Ud: "cocinaría",
			nosotros: "cocinaríamos",
			vosotros: "cocinaríais",
			Uds: "cocinarían",
		},
		Future: {
			yo: "cocinaré",
			tú: "cocinarás",
			Ud: "cocinará",
			nosotros: "cocinaremos",
			vosotros: "cocinaréis",
			Uds: "cocinarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "cocine",
			tú: "cocines",
			Ud: "cocine",
			nosotros: "cocinemos",
			vosotros: "cocinéis",
			Uds: "cocinen",
		},
		Imperfect: {
			yo: "cocinara",
			tú: "cocinaras",
			Ud: "cocinara",
			nosotros: "cocináramos",
			vosotros: "cocinarais",
			Uds: "cocinaran",
		},
		Imperfect2: {
			yo: "cocinase",
			tú: "cocinases",
			Ud: "cocinase",
			nosotros: "cocinásemos",
			vosotros: "cocinaseis",
			Uds: "cocinasen",
		},
		Future: {
			yo: "cocinare",
			tú: "cocinares",
			Ud: "cocinare",
			nosotros: "cocináremos",
			vosotros: "cocinareis",
			Uds: "cocinaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "cocina",
			Ud: "cocine",
			nosotros: "cocinemos",
			vosotros: "cocinad",
			Uds: "cocinen",
		},
		Negative: {
			tú: "no cocines",
			Ud: "no cocine",
			nosotros: "no cocinemos",
			vosotros: "no cocinéis",
			Uds: "no cocinen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy cocinando",
			tú: "estás cocinando",
			Ud: "está cocinando",
			nosotros: "estamos cocinando",
			vosotros: "estáis cocinando",
			Uds: "están cocinando",
		},
		Preterite: {
			yo: "estuve cocinando",
			tú: "estuviste cocinando",
			Ud: "estuvo cocinando",
			nosotros: "estuvimos cocinando",
			vosotros: "estuvisteis cocinando",
			Uds: "estuvieron cocinando",
		},
		Imperfect: {
			Uds: "estaban cocinando",
			yo: "estaba cocinando",
			tú: "estabas cocinando",
			Ud: "estaba cocinando",
			nosotros: "estábamos cocinando",
			vosotros: "estabais cocinando",
		},
		Conditional: {
			yo: "estaría cocinando",
			tú: "estarías cocinando",
			Ud: "estaría cocinando",
			nosotros: "estaríamos cocinando",
			vosotros: "estaríais cocinando",
			Uds: "estarían cocinando",
		},
		Future: {
			yo: "estaré cocinando",
			tú: "estarás cocinando",
			Ud: "estará cocinando",
			nosotros: "estaremos cocinando",
			vosotros: "estaréis cocinando",
			Uds: "estarán cocinando",
		},
	},
	Perfect: {
		Present: {
			yo: "he cocinado",
			tú: "has cocinado",
			Ud: "ha cocinado",
			nosotros: "hemos cocinado",
			vosotros: "habéis cocinado",
			Uds: "han cocinado",
		},
		Preterite: {
			yo: "hube cocinado",
			tú: "hubiste cocinado",
			Ud: "hubo cocinado",
			nosotros: "hubimos cocinado",
			vosotros: "hubisteis cocinado",
			Uds: "hubieron cocinado",
		},
		Past: {
			yo: "había cocinado",
			tú: "habías cocinado",
			Ud: "había cocinado",
			nosotros: "habíamos cocinado",
			vosotros: "habíais cocinado",
			Uds: "habían cocinado",
		},
		Conditional: {
			yo: "habría cocinado",
			tú: "habrías cocinado",
			Ud: "habría cocinado",
			nosotros: "habríamos cocinado",
			vosotros: "habríais cocinado",
			Uds: "habrían cocinado",
		},
		Future: {
			yo: "habré cocinado",
			tú: "habrás cocinado",
			Ud: "habrá cocinado",
			nosotros: "habremos cocinado",
			vosotros: "habréis cocinado",
			Uds: "habrán cocinado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya cocinado",
			tú: "hayas cocinado",
			Ud: "haya cocinado",
			nosotros: "hayamos cocinado",
			vosotros: "hayáis cocinado",
			Uds: "hayan cocinado",
		},
		Past: {
			yo: "hubiera cocinado",
			tú: "hubieras cocinado",
			Ud: "hubiera cocinado",
			nosotros: "hubiéramos cocinado",
			vosotros: "hubierais cocinado",
			Uds: "hubieran cocinado",
		},
		Future: {
			yo: "hubiere cocinado",
			tú: "hubieres cocinado",
			Ud: "hubiere cocinado",
			nosotros: "hubiéremos cocinado",
			vosotros: "hubiereis cocinado",
			Uds: "hubieren cocinado",
		},
	},
}
