var coexistir = {
	Indicative: {
		Present: {
			yo: "coexisto",
			tú: "coexistes",
			Ud: "coexiste",
			nosotros: "coexistimos",
			vosotros: "coexistís",
			Uds: "coexisten",
		},
		Preterite: {
			yo: "coexistí",
			tú: "coexististe",
			Ud: "coexistió",
			nosotros: "coexistimos",
			vosotros: "coexististeis",
			Uds: "coexistieron",
		},
		Imperfect: {
			yo: "coexistía",
			tú: "coexistías",
			Ud: "coexistía",
			nosotros: "coexistíamos",
			vosotros: "coexistíais",
			Uds: "coexistían",
		},
		Conditional: {
			yo: "coexistiría",
			tú: "coexistirías",
			Ud: "coexistiría",
			nosotros: "coexistiríamos",
			vosotros: "coexistiríais",
			Uds: "coexistirían",
		},
		Future: {
			yo: "coexistiré",
			tú: "coexistirás",
			Ud: "coexistirá",
			nosotros: "coexistiremos",
			vosotros: "coexistiréis",
			Uds: "coexistirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "coexista",
			tú: "coexistas",
			Ud: "coexista",
			nosotros: "coexistamos",
			vosotros: "coexistáis",
			Uds: "coexistan",
		},
		Imperfect: {
			yo: "coexistiera",
			tú: "coexistieras",
			Ud: "coexistiera",
			nosotros: "coexistiéramos",
			vosotros: "coexistierais",
			Uds: "coexistieran",
		},
		Imperfect2: {
			yo: "coexistiese",
			tú: "coexistieses",
			Ud: "coexistiese",
			nosotros: "coexistiésemos",
			vosotros: "coexistieseis",
			Uds: "coexistiesen",
		},
		Future: {
			yo: "coexistiere",
			tú: "coexistieres",
			Ud: "coexistiere",
			nosotros: "coexistiéremos",
			vosotros: "coexistiereis",
			Uds: "coexistieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "coexiste",
			Ud: "coexista",
			nosotros: "coexistamos",
			vosotros: "coexistid",
			Uds: "coexistan",
		},
		Negative: {
			tú: "no coexistas",
			Ud: "no coexista",
			nosotros: "no coexistamos",
			vosotros: "no coexistáis",
			Uds: "no coexistan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy coexistiendo",
			tú: "estás coexistiendo",
			Ud: "está coexistiendo",
			nosotros: "estamos coexistiendo",
			vosotros: "estáis coexistiendo",
			Uds: "están coexistiendo",
		},
		Preterite: {
			yo: "estuve coexistiendo",
			tú: "estuviste coexistiendo",
			Ud: "estuvo coexistiendo",
			nosotros: "estuvimos coexistiendo",
			vosotros: "estuvisteis coexistiendo",
			Uds: "estuvieron coexistiendo",
		},
		Imperfect: {
			Uds: "estaban coexistiendo",
			yo: "estaba coexistiendo",
			tú: "estabas coexistiendo",
			Ud: "estaba coexistiendo",
			nosotros: "estábamos coexistiendo",
			vosotros: "estabais coexistiendo",
		},
		Conditional: {
			yo: "estaría coexistiendo",
			tú: "estarías coexistiendo",
			Ud: "estaría coexistiendo",
			nosotros: "estaríamos coexistiendo",
			vosotros: "estaríais coexistiendo",
			Uds: "estarían coexistiendo",
		},
		Future: {
			yo: "estaré coexistiendo",
			tú: "estarás coexistiendo",
			Ud: "estará coexistiendo",
			nosotros: "estaremos coexistiendo",
			vosotros: "estaréis coexistiendo",
			Uds: "estarán coexistiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he coexistido",
			tú: "has coexistido",
			Ud: "ha coexistido",
			nosotros: "hemos coexistido",
			vosotros: "habéis coexistido",
			Uds: "han coexistido",
		},
		Preterite: {
			yo: "hube coexistido",
			tú: "hubiste coexistido",
			Ud: "hubo coexistido",
			nosotros: "hubimos coexistido",
			vosotros: "hubisteis coexistido",
			Uds: "hubieron coexistido",
		},
		Past: {
			yo: "había coexistido",
			tú: "habías coexistido",
			Ud: "había coexistido",
			nosotros: "habíamos coexistido",
			vosotros: "habíais coexistido",
			Uds: "habían coexistido",
		},
		Conditional: {
			yo: "habría coexistido",
			tú: "habrías coexistido",
			Ud: "habría coexistido",
			nosotros: "habríamos coexistido",
			vosotros: "habríais coexistido",
			Uds: "habrían coexistido",
		},
		Future: {
			yo: "habré coexistido",
			tú: "habrás coexistido",
			Ud: "habrá coexistido",
			nosotros: "habremos coexistido",
			vosotros: "habréis coexistido",
			Uds: "habrán coexistido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya coexistido",
			tú: "hayas coexistido",
			Ud: "haya coexistido",
			nosotros: "hayamos coexistido",
			vosotros: "hayáis coexistido",
			Uds: "hayan coexistido",
		},
		Past: {
			yo: "hubiera coexistido",
			tú: "hubieras coexistido",
			Ud: "hubiera coexistido",
			nosotros: "hubiéramos coexistido",
			vosotros: "hubierais coexistido",
			Uds: "hubieran coexistido",
		},
		Future: {
			yo: "hubiere coexistido",
			tú: "hubieres coexistido",
			Ud: "hubiere coexistido",
			nosotros: "hubiéremos coexistido",
			vosotros: "hubiereis coexistido",
			Uds: "hubieren coexistido",
		},
	},
}
