var colorar = {
	Indicative: {
		Present: {
			yo: "coloro",
			tú: "coloras",
			Ud: "colora",
			nosotros: "coloramos",
			vosotros: "coloráis",
			Uds: "coloran",
		},
		Preterite: {
			yo: "coloré",
			tú: "coloraste",
			Ud: "coloró",
			nosotros: "coloramos",
			vosotros: "colorasteis",
			Uds: "coloraron",
		},
		Imperfect: {
			yo: "coloraba",
			tú: "colorabas",
			Ud: "coloraba",
			nosotros: "colorábamos",
			vosotros: "colorabais",
			Uds: "coloraban",
		},
		Conditional: {
			yo: "coloraría",
			tú: "colorarías",
			Ud: "coloraría",
			nosotros: "coloraríamos",
			vosotros: "coloraríais",
			Uds: "colorarían",
		},
		Future: {
			yo: "coloraré",
			tú: "colorarás",
			Ud: "colorará",
			nosotros: "coloraremos",
			vosotros: "coloraréis",
			Uds: "colorarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "colore",
			tú: "colores",
			Ud: "colore",
			nosotros: "coloremos",
			vosotros: "coloréis",
			Uds: "coloren",
		},
		Imperfect: {
			yo: "colorara",
			tú: "coloraras",
			Ud: "colorara",
			nosotros: "coloráramos",
			vosotros: "colorarais",
			Uds: "coloraran",
		},
		Imperfect2: {
			yo: "colorase",
			tú: "colorases",
			Ud: "colorase",
			nosotros: "colorásemos",
			vosotros: "coloraseis",
			Uds: "colorasen",
		},
		Future: {
			yo: "colorare",
			tú: "colorares",
			Ud: "colorare",
			nosotros: "coloráremos",
			vosotros: "colorareis",
			Uds: "coloraren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "colora",
			Ud: "colore",
			nosotros: "coloremos",
			vosotros: "colorad",
			Uds: "coloren",
		},
		Negative: {
			tú: "no colores",
			Ud: "no colore",
			nosotros: "no coloremos",
			vosotros: "no coloréis",
			Uds: "no coloren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy colorando",
			tú: "estás colorando",
			Ud: "está colorando",
			nosotros: "estamos colorando",
			vosotros: "estáis colorando",
			Uds: "están colorando",
		},
		Preterite: {
			yo: "estuve colorando",
			tú: "estuviste colorando",
			Ud: "estuvo colorando",
			nosotros: "estuvimos colorando",
			vosotros: "estuvisteis colorando",
			Uds: "estuvieron colorando",
		},
		Imperfect: {
			Uds: "estaban colorando",
			yo: "estaba colorando",
			tú: "estabas colorando",
			Ud: "estaba colorando",
			nosotros: "estábamos colorando",
			vosotros: "estabais colorando",
		},
		Conditional: {
			yo: "estaría colorando",
			tú: "estarías colorando",
			Ud: "estaría colorando",
			nosotros: "estaríamos colorando",
			vosotros: "estaríais colorando",
			Uds: "estarían colorando",
		},
		Future: {
			yo: "estaré colorando",
			tú: "estarás colorando",
			Ud: "estará colorando",
			nosotros: "estaremos colorando",
			vosotros: "estaréis colorando",
			Uds: "estarán colorando",
		},
	},
	Perfect: {
		Present: {
			yo: "he colorado",
			tú: "has colorado",
			Ud: "ha colorado",
			nosotros: "hemos colorado",
			vosotros: "habéis colorado",
			Uds: "han colorado",
		},
		Preterite: {
			yo: "hube colorado",
			tú: "hubiste colorado",
			Ud: "hubo colorado",
			nosotros: "hubimos colorado",
			vosotros: "hubisteis colorado",
			Uds: "hubieron colorado",
		},
		Past: {
			yo: "había colorado",
			tú: "habías colorado",
			Ud: "había colorado",
			nosotros: "habíamos colorado",
			vosotros: "habíais colorado",
			Uds: "habían colorado",
		},
		Conditional: {
			yo: "habría colorado",
			tú: "habrías colorado",
			Ud: "habría colorado",
			nosotros: "habríamos colorado",
			vosotros: "habríais colorado",
			Uds: "habrían colorado",
		},
		Future: {
			yo: "habré colorado",
			tú: "habrás colorado",
			Ud: "habrá colorado",
			nosotros: "habremos colorado",
			vosotros: "habréis colorado",
			Uds: "habrán colorado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya colorado",
			tú: "hayas colorado",
			Ud: "haya colorado",
			nosotros: "hayamos colorado",
			vosotros: "hayáis colorado",
			Uds: "hayan colorado",
		},
		Past: {
			yo: "hubiera colorado",
			tú: "hubieras colorado",
			Ud: "hubiera colorado",
			nosotros: "hubiéramos colorado",
			vosotros: "hubierais colorado",
			Uds: "hubieran colorado",
		},
		Future: {
			yo: "hubiere colorado",
			tú: "hubieres colorado",
			Ud: "hubiere colorado",
			nosotros: "hubiéremos colorado",
			vosotros: "hubiereis colorado",
			Uds: "hubieren colorado",
		},
	},
}
