var combinar = {
	Indicative: {
		Present: {
			yo: "combino",
			tú: "combinas",
			Ud: "combina",
			nosotros: "combinamos",
			vosotros: "combináis",
			Uds: "combinan",
		},
		Preterite: {
			yo: "combiné",
			tú: "combinaste",
			Ud: "combinó",
			nosotros: "combinamos",
			vosotros: "combinasteis",
			Uds: "combinaron",
		},
		Imperfect: {
			yo: "combinaba",
			tú: "combinabas",
			Ud: "combinaba",
			nosotros: "combinábamos",
			vosotros: "combinabais",
			Uds: "combinaban",
		},
		Conditional: {
			yo: "combinaría",
			tú: "combinarías",
			Ud: "combinaría",
			nosotros: "combinaríamos",
			vosotros: "combinaríais",
			Uds: "combinarían",
		},
		Future: {
			yo: "combinaré",
			tú: "combinarás",
			Ud: "combinará",
			nosotros: "combinaremos",
			vosotros: "combinaréis",
			Uds: "combinarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "combine",
			tú: "combines",
			Ud: "combine",
			nosotros: "combinemos",
			vosotros: "combinéis",
			Uds: "combinen",
		},
		Imperfect: {
			yo: "combinara",
			tú: "combinaras",
			Ud: "combinara",
			nosotros: "combináramos",
			vosotros: "combinarais",
			Uds: "combinaran",
		},
		Imperfect2: {
			yo: "combinase",
			tú: "combinases",
			Ud: "combinase",
			nosotros: "combinásemos",
			vosotros: "combinaseis",
			Uds: "combinasen",
		},
		Future: {
			yo: "combinare",
			tú: "combinares",
			Ud: "combinare",
			nosotros: "combináremos",
			vosotros: "combinareis",
			Uds: "combinaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "combina",
			Ud: "combine",
			nosotros: "combinemos",
			vosotros: "combinad",
			Uds: "combinen",
		},
		Negative: {
			tú: "no combines",
			Ud: "no combine",
			nosotros: "no combinemos",
			vosotros: "no combinéis",
			Uds: "no combinen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy combinando",
			tú: "estás combinando",
			Ud: "está combinando",
			nosotros: "estamos combinando",
			vosotros: "estáis combinando",
			Uds: "están combinando",
		},
		Preterite: {
			yo: "estuve combinando",
			tú: "estuviste combinando",
			Ud: "estuvo combinando",
			nosotros: "estuvimos combinando",
			vosotros: "estuvisteis combinando",
			Uds: "estuvieron combinando",
		},
		Imperfect: {
			Uds: "estaban combinando",
			yo: "estaba combinando",
			tú: "estabas combinando",
			Ud: "estaba combinando",
			nosotros: "estábamos combinando",
			vosotros: "estabais combinando",
		},
		Conditional: {
			yo: "estaría combinando",
			tú: "estarías combinando",
			Ud: "estaría combinando",
			nosotros: "estaríamos combinando",
			vosotros: "estaríais combinando",
			Uds: "estarían combinando",
		},
		Future: {
			yo: "estaré combinando",
			tú: "estarás combinando",
			Ud: "estará combinando",
			nosotros: "estaremos combinando",
			vosotros: "estaréis combinando",
			Uds: "estarán combinando",
		},
	},
	Perfect: {
		Present: {
			yo: "he combinado",
			tú: "has combinado",
			Ud: "ha combinado",
			nosotros: "hemos combinado",
			vosotros: "habéis combinado",
			Uds: "han combinado",
		},
		Preterite: {
			yo: "hube combinado",
			tú: "hubiste combinado",
			Ud: "hubo combinado",
			nosotros: "hubimos combinado",
			vosotros: "hubisteis combinado",
			Uds: "hubieron combinado",
		},
		Past: {
			yo: "había combinado",
			tú: "habías combinado",
			Ud: "había combinado",
			nosotros: "habíamos combinado",
			vosotros: "habíais combinado",
			Uds: "habían combinado",
		},
		Conditional: {
			yo: "habría combinado",
			tú: "habrías combinado",
			Ud: "habría combinado",
			nosotros: "habríamos combinado",
			vosotros: "habríais combinado",
			Uds: "habrían combinado",
		},
		Future: {
			yo: "habré combinado",
			tú: "habrás combinado",
			Ud: "habrá combinado",
			nosotros: "habremos combinado",
			vosotros: "habréis combinado",
			Uds: "habrán combinado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya combinado",
			tú: "hayas combinado",
			Ud: "haya combinado",
			nosotros: "hayamos combinado",
			vosotros: "hayáis combinado",
			Uds: "hayan combinado",
		},
		Past: {
			yo: "hubiera combinado",
			tú: "hubieras combinado",
			Ud: "hubiera combinado",
			nosotros: "hubiéramos combinado",
			vosotros: "hubierais combinado",
			Uds: "hubieran combinado",
		},
		Future: {
			yo: "hubiere combinado",
			tú: "hubieres combinado",
			Ud: "hubiere combinado",
			nosotros: "hubiéremos combinado",
			vosotros: "hubiereis combinado",
			Uds: "hubieren combinado",
		},
	},
}
