var comerciar = {
	Indicative: {
		Present: {
			yo: "comercio",
			tú: "comercias",
			Ud: "comercia",
			nosotros: "comerciamos",
			vosotros: "comerciáis",
			Uds: "comercian",
		},
		Preterite: {
			yo: "comercié",
			tú: "comerciaste",
			Ud: "comerció",
			nosotros: "comerciamos",
			vosotros: "comerciasteis",
			Uds: "comerciaron",
		},
		Imperfect: {
			yo: "comerciaba",
			tú: "comerciabas",
			Ud: "comerciaba",
			nosotros: "comerciábamos",
			vosotros: "comerciabais",
			Uds: "comerciaban",
		},
		Conditional: {
			yo: "comerciaría",
			tú: "comerciarías",
			Ud: "comerciaría",
			nosotros: "comerciaríamos",
			vosotros: "comerciaríais",
			Uds: "comerciarían",
		},
		Future: {
			yo: "comerciaré",
			tú: "comerciarás",
			Ud: "comerciará",
			nosotros: "comerciaremos",
			vosotros: "comerciaréis",
			Uds: "comerciarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "comercie",
			tú: "comercies",
			Ud: "comercie",
			nosotros: "comerciemos",
			vosotros: "comerciéis",
			Uds: "comercien",
		},
		Imperfect: {
			yo: "comerciara",
			tú: "comerciaras",
			Ud: "comerciara",
			nosotros: "comerciáramos",
			vosotros: "comerciarais",
			Uds: "comerciaran",
		},
		Imperfect2: {
			yo: "comerciase",
			tú: "comerciases",
			Ud: "comerciase",
			nosotros: "comerciásemos",
			vosotros: "comerciaseis",
			Uds: "comerciasen",
		},
		Future: {
			yo: "comerciare",
			tú: "comerciares",
			Ud: "comerciare",
			nosotros: "comerciáremos",
			vosotros: "comerciareis",
			Uds: "comerciaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "comercia",
			Ud: "comercie",
			nosotros: "comerciemos",
			vosotros: "comerciad",
			Uds: "comercien",
		},
		Negative: {
			tú: "no comercies",
			Ud: "no comercie",
			nosotros: "no comerciemos",
			vosotros: "no comerciéis",
			Uds: "no comercien",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy comerciando",
			tú: "estás comerciando",
			Ud: "está comerciando",
			nosotros: "estamos comerciando",
			vosotros: "estáis comerciando",
			Uds: "están comerciando",
		},
		Preterite: {
			yo: "estuve comerciando",
			tú: "estuviste comerciando",
			Ud: "estuvo comerciando",
			nosotros: "estuvimos comerciando",
			vosotros: "estuvisteis comerciando",
			Uds: "estuvieron comerciando",
		},
		Imperfect: {
			Uds: "estaban comerciando",
			yo: "estaba comerciando",
			tú: "estabas comerciando",
			Ud: "estaba comerciando",
			nosotros: "estábamos comerciando",
			vosotros: "estabais comerciando",
		},
		Conditional: {
			yo: "estaría comerciando",
			tú: "estarías comerciando",
			Ud: "estaría comerciando",
			nosotros: "estaríamos comerciando",
			vosotros: "estaríais comerciando",
			Uds: "estarían comerciando",
		},
		Future: {
			yo: "estaré comerciando",
			tú: "estarás comerciando",
			Ud: "estará comerciando",
			nosotros: "estaremos comerciando",
			vosotros: "estaréis comerciando",
			Uds: "estarán comerciando",
		},
	},
	Perfect: {
		Present: {
			yo: "he comerciado",
			tú: "has comerciado",
			Ud: "ha comerciado",
			nosotros: "hemos comerciado",
			vosotros: "habéis comerciado",
			Uds: "han comerciado",
		},
		Preterite: {
			yo: "hube comerciado",
			tú: "hubiste comerciado",
			Ud: "hubo comerciado",
			nosotros: "hubimos comerciado",
			vosotros: "hubisteis comerciado",
			Uds: "hubieron comerciado",
		},
		Past: {
			yo: "había comerciado",
			tú: "habías comerciado",
			Ud: "había comerciado",
			nosotros: "habíamos comerciado",
			vosotros: "habíais comerciado",
			Uds: "habían comerciado",
		},
		Conditional: {
			yo: "habría comerciado",
			tú: "habrías comerciado",
			Ud: "habría comerciado",
			nosotros: "habríamos comerciado",
			vosotros: "habríais comerciado",
			Uds: "habrían comerciado",
		},
		Future: {
			yo: "habré comerciado",
			tú: "habrás comerciado",
			Ud: "habrá comerciado",
			nosotros: "habremos comerciado",
			vosotros: "habréis comerciado",
			Uds: "habrán comerciado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya comerciado",
			tú: "hayas comerciado",
			Ud: "haya comerciado",
			nosotros: "hayamos comerciado",
			vosotros: "hayáis comerciado",
			Uds: "hayan comerciado",
		},
		Past: {
			yo: "hubiera comerciado",
			tú: "hubieras comerciado",
			Ud: "hubiera comerciado",
			nosotros: "hubiéramos comerciado",
			vosotros: "hubierais comerciado",
			Uds: "hubieran comerciado",
		},
		Future: {
			yo: "hubiere comerciado",
			tú: "hubieres comerciado",
			Ud: "hubiere comerciado",
			nosotros: "hubiéremos comerciado",
			vosotros: "hubiereis comerciado",
			Uds: "hubieren comerciado",
		},
	},
}
