var cometer = {
	Indicative: {
		Present: {
			yo: "cometo",
			tú: "cometes",
			Ud: "comete",
			nosotros: "cometemos",
			vosotros: "cometéis",
			Uds: "cometen",
		},
		Preterite: {
			yo: "cometí",
			tú: "cometiste",
			Ud: "cometió",
			nosotros: "cometimos",
			vosotros: "cometisteis",
			Uds: "cometieron",
		},
		Imperfect: {
			yo: "cometía",
			tú: "cometías",
			Ud: "cometía",
			nosotros: "cometíamos",
			vosotros: "cometíais",
			Uds: "cometían",
		},
		Conditional: {
			yo: "cometería",
			tú: "cometerías",
			Ud: "cometería",
			nosotros: "cometeríamos",
			vosotros: "cometeríais",
			Uds: "cometerían",
		},
		Future: {
			yo: "cometeré",
			tú: "cometerás",
			Ud: "cometerá",
			nosotros: "cometeremos",
			vosotros: "cometeréis",
			Uds: "cometerán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "cometa",
			tú: "cometas",
			Ud: "cometa",
			nosotros: "cometamos",
			vosotros: "cometáis",
			Uds: "cometan",
		},
		Imperfect: {
			yo: "cometiera",
			tú: "cometieras",
			Ud: "cometiera",
			nosotros: "cometiéramos",
			vosotros: "cometierais",
			Uds: "cometieran",
		},
		Imperfect2: {
			yo: "cometiese",
			tú: "cometieses",
			Ud: "cometiese",
			nosotros: "cometiésemos",
			vosotros: "cometieseis",
			Uds: "cometiesen",
		},
		Future: {
			yo: "cometiere",
			tú: "cometieres",
			Ud: "cometiere",
			nosotros: "cometiéremos",
			vosotros: "cometiereis",
			Uds: "cometieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "comete",
			Ud: "cometa",
			nosotros: "cometamos",
			vosotros: "cometed",
			Uds: "cometan",
		},
		Negative: {
			tú: "no cometas",
			Ud: "no cometa",
			nosotros: "no cometamos",
			vosotros: "no cometáis",
			Uds: "no cometan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy cometiendo",
			tú: "estás cometiendo",
			Ud: "está cometiendo",
			nosotros: "estamos cometiendo",
			vosotros: "estáis cometiendo",
			Uds: "están cometiendo",
		},
		Preterite: {
			yo: "estuve cometiendo",
			tú: "estuviste cometiendo",
			Ud: "estuvo cometiendo",
			nosotros: "estuvimos cometiendo",
			vosotros: "estuvisteis cometiendo",
			Uds: "estuvieron cometiendo",
		},
		Imperfect: {
			Uds: "estaban cometiendo",
			yo: "estaba cometiendo",
			tú: "estabas cometiendo",
			Ud: "estaba cometiendo",
			nosotros: "estábamos cometiendo",
			vosotros: "estabais cometiendo",
		},
		Conditional: {
			yo: "estaría cometiendo",
			tú: "estarías cometiendo",
			Ud: "estaría cometiendo",
			nosotros: "estaríamos cometiendo",
			vosotros: "estaríais cometiendo",
			Uds: "estarían cometiendo",
		},
		Future: {
			yo: "estaré cometiendo",
			tú: "estarás cometiendo",
			Ud: "estará cometiendo",
			nosotros: "estaremos cometiendo",
			vosotros: "estaréis cometiendo",
			Uds: "estarán cometiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he cometido",
			tú: "has cometido",
			Ud: "ha cometido",
			nosotros: "hemos cometido",
			vosotros: "habéis cometido",
			Uds: "han cometido",
		},
		Preterite: {
			yo: "hube cometido",
			tú: "hubiste cometido",
			Ud: "hubo cometido",
			nosotros: "hubimos cometido",
			vosotros: "hubisteis cometido",
			Uds: "hubieron cometido",
		},
		Past: {
			yo: "había cometido",
			tú: "habías cometido",
			Ud: "había cometido",
			nosotros: "habíamos cometido",
			vosotros: "habíais cometido",
			Uds: "habían cometido",
		},
		Conditional: {
			yo: "habría cometido",
			tú: "habrías cometido",
			Ud: "habría cometido",
			nosotros: "habríamos cometido",
			vosotros: "habríais cometido",
			Uds: "habrían cometido",
		},
		Future: {
			yo: "habré cometido",
			tú: "habrás cometido",
			Ud: "habrá cometido",
			nosotros: "habremos cometido",
			vosotros: "habréis cometido",
			Uds: "habrán cometido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya cometido",
			tú: "hayas cometido",
			Ud: "haya cometido",
			nosotros: "hayamos cometido",
			vosotros: "hayáis cometido",
			Uds: "hayan cometido",
		},
		Past: {
			yo: "hubiera cometido",
			tú: "hubieras cometido",
			Ud: "hubiera cometido",
			nosotros: "hubiéramos cometido",
			vosotros: "hubierais cometido",
			Uds: "hubieran cometido",
		},
		Future: {
			yo: "hubiere cometido",
			tú: "hubieres cometido",
			Ud: "hubiere cometido",
			nosotros: "hubiéremos cometido",
			vosotros: "hubiereis cometido",
			Uds: "hubieren cometido",
		},
	},
}
