var comisionar = {
	Indicative: {
		Present: {
			yo: "comisiono",
			tú: "comisionas",
			Ud: "comisiona",
			nosotros: "comisionamos",
			vosotros: "comisionáis",
			Uds: "comisionan",
		},
		Preterite: {
			yo: "comisioné",
			tú: "comisionaste",
			Ud: "comisionó",
			nosotros: "comisionamos",
			vosotros: "comisionasteis",
			Uds: "comisionaron",
		},
		Imperfect: {
			yo: "comisionaba",
			tú: "comisionabas",
			Ud: "comisionaba",
			nosotros: "comisionábamos",
			vosotros: "comisionabais",
			Uds: "comisionaban",
		},
		Conditional: {
			yo: "comisionaría",
			tú: "comisionarías",
			Ud: "comisionaría",
			nosotros: "comisionaríamos",
			vosotros: "comisionaríais",
			Uds: "comisionarían",
		},
		Future: {
			yo: "comisionaré",
			tú: "comisionarás",
			Ud: "comisionará",
			nosotros: "comisionaremos",
			vosotros: "comisionaréis",
			Uds: "comisionarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "comisione",
			tú: "comisiones",
			Ud: "comisione",
			nosotros: "comisionemos",
			vosotros: "comisionéis",
			Uds: "comisionen",
		},
		Imperfect: {
			yo: "comisionara",
			tú: "comisionaras",
			Ud: "comisionara",
			nosotros: "comisionáramos",
			vosotros: "comisionarais",
			Uds: "comisionaran",
		},
		Imperfect2: {
			yo: "comisionase",
			tú: "comisionases",
			Ud: "comisionase",
			nosotros: "comisionásemos",
			vosotros: "comisionaseis",
			Uds: "comisionasen",
		},
		Future: {
			yo: "comisionare",
			tú: "comisionares",
			Ud: "comisionare",
			nosotros: "comisionáremos",
			vosotros: "comisionareis",
			Uds: "comisionaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "comisiona",
			Ud: "comisione",
			nosotros: "comisionemos",
			vosotros: "comisionad",
			Uds: "comisionen",
		},
		Negative: {
			tú: "no comisiones",
			Ud: "no comisione",
			nosotros: "no comisionemos",
			vosotros: "no comisionéis",
			Uds: "no comisionen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy comisionando",
			tú: "estás comisionando",
			Ud: "está comisionando",
			nosotros: "estamos comisionando",
			vosotros: "estáis comisionando",
			Uds: "están comisionando",
		},
		Preterite: {
			yo: "estuve comisionando",
			tú: "estuviste comisionando",
			Ud: "estuvo comisionando",
			nosotros: "estuvimos comisionando",
			vosotros: "estuvisteis comisionando",
			Uds: "estuvieron comisionando",
		},
		Imperfect: {
			Uds: "estaban comisionando",
			yo: "estaba comisionando",
			tú: "estabas comisionando",
			Ud: "estaba comisionando",
			nosotros: "estábamos comisionando",
			vosotros: "estabais comisionando",
		},
		Conditional: {
			yo: "estaría comisionando",
			tú: "estarías comisionando",
			Ud: "estaría comisionando",
			nosotros: "estaríamos comisionando",
			vosotros: "estaríais comisionando",
			Uds: "estarían comisionando",
		},
		Future: {
			yo: "estaré comisionando",
			tú: "estarás comisionando",
			Ud: "estará comisionando",
			nosotros: "estaremos comisionando",
			vosotros: "estaréis comisionando",
			Uds: "estarán comisionando",
		},
	},
	Perfect: {
		Present: {
			yo: "he comisionado",
			tú: "has comisionado",
			Ud: "ha comisionado",
			nosotros: "hemos comisionado",
			vosotros: "habéis comisionado",
			Uds: "han comisionado",
		},
		Preterite: {
			yo: "hube comisionado",
			tú: "hubiste comisionado",
			Ud: "hubo comisionado",
			nosotros: "hubimos comisionado",
			vosotros: "hubisteis comisionado",
			Uds: "hubieron comisionado",
		},
		Past: {
			yo: "había comisionado",
			tú: "habías comisionado",
			Ud: "había comisionado",
			nosotros: "habíamos comisionado",
			vosotros: "habíais comisionado",
			Uds: "habían comisionado",
		},
		Conditional: {
			yo: "habría comisionado",
			tú: "habrías comisionado",
			Ud: "habría comisionado",
			nosotros: "habríamos comisionado",
			vosotros: "habríais comisionado",
			Uds: "habrían comisionado",
		},
		Future: {
			yo: "habré comisionado",
			tú: "habrás comisionado",
			Ud: "habrá comisionado",
			nosotros: "habremos comisionado",
			vosotros: "habréis comisionado",
			Uds: "habrán comisionado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya comisionado",
			tú: "hayas comisionado",
			Ud: "haya comisionado",
			nosotros: "hayamos comisionado",
			vosotros: "hayáis comisionado",
			Uds: "hayan comisionado",
		},
		Past: {
			yo: "hubiera comisionado",
			tú: "hubieras comisionado",
			Ud: "hubiera comisionado",
			nosotros: "hubiéramos comisionado",
			vosotros: "hubierais comisionado",
			Uds: "hubieran comisionado",
		},
		Future: {
			yo: "hubiere comisionado",
			tú: "hubieres comisionado",
			Ud: "hubiere comisionado",
			nosotros: "hubiéremos comisionado",
			vosotros: "hubiereis comisionado",
			Uds: "hubieren comisionado",
		},
	},
}
