var completar = {
	Indicative: {
		Present: {
			yo: "completo",
			tú: "completas",
			Ud: "completa",
			nosotros: "completamos",
			vosotros: "completáis",
			Uds: "completan",
		},
		Preterite: {
			yo: "completé",
			tú: "completaste",
			Ud: "completó",
			nosotros: "completamos",
			vosotros: "completasteis",
			Uds: "completaron",
		},
		Imperfect: {
			yo: "completaba",
			tú: "completabas",
			Ud: "completaba",
			nosotros: "completábamos",
			vosotros: "completabais",
			Uds: "completaban",
		},
		Conditional: {
			yo: "completaría",
			tú: "completarías",
			Ud: "completaría",
			nosotros: "completaríamos",
			vosotros: "completaríais",
			Uds: "completarían",
		},
		Future: {
			yo: "completaré",
			tú: "completarás",
			Ud: "completará",
			nosotros: "completaremos",
			vosotros: "completaréis",
			Uds: "completarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "complete",
			tú: "completes",
			Ud: "complete",
			nosotros: "completemos",
			vosotros: "completéis",
			Uds: "completen",
		},
		Imperfect: {
			yo: "completara",
			tú: "completaras",
			Ud: "completara",
			nosotros: "completáramos",
			vosotros: "completarais",
			Uds: "completaran",
		},
		Imperfect2: {
			yo: "completase",
			tú: "completases",
			Ud: "completase",
			nosotros: "completásemos",
			vosotros: "completaseis",
			Uds: "completasen",
		},
		Future: {
			yo: "completare",
			tú: "completares",
			Ud: "completare",
			nosotros: "completáremos",
			vosotros: "completareis",
			Uds: "completaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "completa",
			Ud: "complete",
			nosotros: "completemos",
			vosotros: "completad",
			Uds: "completen",
		},
		Negative: {
			tú: "no completes",
			Ud: "no complete",
			nosotros: "no completemos",
			vosotros: "no completéis",
			Uds: "no completen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy completando",
			tú: "estás completando",
			Ud: "está completando",
			nosotros: "estamos completando",
			vosotros: "estáis completando",
			Uds: "están completando",
		},
		Preterite: {
			yo: "estuve completando",
			tú: "estuviste completando",
			Ud: "estuvo completando",
			nosotros: "estuvimos completando",
			vosotros: "estuvisteis completando",
			Uds: "estuvieron completando",
		},
		Imperfect: {
			Uds: "estaban completando",
			yo: "estaba completando",
			tú: "estabas completando",
			Ud: "estaba completando",
			nosotros: "estábamos completando",
			vosotros: "estabais completando",
		},
		Conditional: {
			yo: "estaría completando",
			tú: "estarías completando",
			Ud: "estaría completando",
			nosotros: "estaríamos completando",
			vosotros: "estaríais completando",
			Uds: "estarían completando",
		},
		Future: {
			yo: "estaré completando",
			tú: "estarás completando",
			Ud: "estará completando",
			nosotros: "estaremos completando",
			vosotros: "estaréis completando",
			Uds: "estarán completando",
		},
	},
	Perfect: {
		Present: {
			yo: "he completado",
			tú: "has completado",
			Ud: "ha completado",
			nosotros: "hemos completado",
			vosotros: "habéis completado",
			Uds: "han completado",
		},
		Preterite: {
			yo: "hube completado",
			tú: "hubiste completado",
			Ud: "hubo completado",
			nosotros: "hubimos completado",
			vosotros: "hubisteis completado",
			Uds: "hubieron completado",
		},
		Past: {
			yo: "había completado",
			tú: "habías completado",
			Ud: "había completado",
			nosotros: "habíamos completado",
			vosotros: "habíais completado",
			Uds: "habían completado",
		},
		Conditional: {
			yo: "habría completado",
			tú: "habrías completado",
			Ud: "habría completado",
			nosotros: "habríamos completado",
			vosotros: "habríais completado",
			Uds: "habrían completado",
		},
		Future: {
			yo: "habré completado",
			tú: "habrás completado",
			Ud: "habrá completado",
			nosotros: "habremos completado",
			vosotros: "habréis completado",
			Uds: "habrán completado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya completado",
			tú: "hayas completado",
			Ud: "haya completado",
			nosotros: "hayamos completado",
			vosotros: "hayáis completado",
			Uds: "hayan completado",
		},
		Past: {
			yo: "hubiera completado",
			tú: "hubieras completado",
			Ud: "hubiera completado",
			nosotros: "hubiéramos completado",
			vosotros: "hubierais completado",
			Uds: "hubieran completado",
		},
		Future: {
			yo: "hubiere completado",
			tú: "hubieres completado",
			Ud: "hubiere completado",
			nosotros: "hubiéremos completado",
			vosotros: "hubiereis completado",
			Uds: "hubieren completado",
		},
	},
}
