var comprar = {
	Indicative: {
		Present: {
			yo: "compro",
			tú: "compras",
			Ud: "compra",
			nosotros: "compramos",
			vosotros: "compráis",
			Uds: "compran",
		},
		Preterite: {
			yo: "compré",
			tú: "compraste",
			Ud: "compró",
			nosotros: "compramos",
			vosotros: "comprasteis",
			Uds: "compraron",
		},
		Imperfect: {
			yo: "compraba",
			tú: "comprabas",
			Ud: "compraba",
			nosotros: "comprábamos",
			vosotros: "comprabais",
			Uds: "compraban",
		},
		Conditional: {
			yo: "compraría",
			tú: "comprarías",
			Ud: "compraría",
			nosotros: "compraríamos",
			vosotros: "compraríais",
			Uds: "comprarían",
		},
		Future: {
			yo: "compraré",
			tú: "comprarás",
			Ud: "comprará",
			nosotros: "compraremos",
			vosotros: "compraréis",
			Uds: "comprarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "compre",
			tú: "compres",
			Ud: "compre",
			nosotros: "compremos",
			vosotros: "compréis",
			Uds: "compren",
		},
		Imperfect: {
			yo: "comprara",
			tú: "compraras",
			Ud: "comprara",
			nosotros: "compráramos",
			vosotros: "comprarais",
			Uds: "compraran",
		},
		Imperfect2: {
			yo: "comprase",
			tú: "comprases",
			Ud: "comprase",
			nosotros: "comprásemos",
			vosotros: "compraseis",
			Uds: "comprasen",
		},
		Future: {
			yo: "comprare",
			tú: "comprares",
			Ud: "comprare",
			nosotros: "compráremos",
			vosotros: "comprareis",
			Uds: "compraren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "compra",
			Ud: "compre",
			nosotros: "compremos",
			vosotros: "comprad",
			Uds: "compren",
		},
		Negative: {
			tú: "no compres",
			Ud: "no compre",
			nosotros: "no compremos",
			vosotros: "no compréis",
			Uds: "no compren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy comprando",
			tú: "estás comprando",
			Ud: "está comprando",
			nosotros: "estamos comprando",
			vosotros: "estáis comprando",
			Uds: "están comprando",
		},
		Preterite: {
			yo: "estuve comprando",
			tú: "estuviste comprando",
			Ud: "estuvo comprando",
			nosotros: "estuvimos comprando",
			vosotros: "estuvisteis comprando",
			Uds: "estuvieron comprando",
		},
		Imperfect: {
			Uds: "estaban comprando",
			yo: "estaba comprando",
			tú: "estabas comprando",
			Ud: "estaba comprando",
			nosotros: "estábamos comprando",
			vosotros: "estabais comprando",
		},
		Conditional: {
			yo: "estaría comprando",
			tú: "estarías comprando",
			Ud: "estaría comprando",
			nosotros: "estaríamos comprando",
			vosotros: "estaríais comprando",
			Uds: "estarían comprando",
		},
		Future: {
			yo: "estaré comprando",
			tú: "estarás comprando",
			Ud: "estará comprando",
			nosotros: "estaremos comprando",
			vosotros: "estaréis comprando",
			Uds: "estarán comprando",
		},
	},
	Perfect: {
		Present: {
			yo: "he comprado",
			tú: "has comprado",
			Ud: "ha comprado",
			nosotros: "hemos comprado",
			vosotros: "habéis comprado",
			Uds: "han comprado",
		},
		Preterite: {
			yo: "hube comprado",
			tú: "hubiste comprado",
			Ud: "hubo comprado",
			nosotros: "hubimos comprado",
			vosotros: "hubisteis comprado",
			Uds: "hubieron comprado",
		},
		Past: {
			yo: "había comprado",
			tú: "habías comprado",
			Ud: "había comprado",
			nosotros: "habíamos comprado",
			vosotros: "habíais comprado",
			Uds: "habían comprado",
		},
		Conditional: {
			yo: "habría comprado",
			tú: "habrías comprado",
			Ud: "habría comprado",
			nosotros: "habríamos comprado",
			vosotros: "habríais comprado",
			Uds: "habrían comprado",
		},
		Future: {
			yo: "habré comprado",
			tú: "habrás comprado",
			Ud: "habrá comprado",
			nosotros: "habremos comprado",
			vosotros: "habréis comprado",
			Uds: "habrán comprado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya comprado",
			tú: "hayas comprado",
			Ud: "haya comprado",
			nosotros: "hayamos comprado",
			vosotros: "hayáis comprado",
			Uds: "hayan comprado",
		},
		Past: {
			yo: "hubiera comprado",
			tú: "hubieras comprado",
			Ud: "hubiera comprado",
			nosotros: "hubiéramos comprado",
			vosotros: "hubierais comprado",
			Uds: "hubieran comprado",
		},
		Future: {
			yo: "hubiere comprado",
			tú: "hubieres comprado",
			Ud: "hubiere comprado",
			nosotros: "hubiéremos comprado",
			vosotros: "hubiereis comprado",
			Uds: "hubieren comprado",
		},
	},
}
