var compilar = {
	Indicative: {
		Present: {
			yo: "compilo",
			tú: "compilas",
			Ud: "compila",
			nosotros: "compilamos",
			vosotros: "compiláis",
			Uds: "compilan",
		},
		Preterite: {
			yo: "compilé",
			tú: "compilaste",
			Ud: "compiló",
			nosotros: "compilamos",
			vosotros: "compilasteis",
			Uds: "compilaron",
		},
		Imperfect: {
			yo: "compilaba",
			tú: "compilabas",
			Ud: "compilaba",
			nosotros: "compilábamos",
			vosotros: "compilabais",
			Uds: "compilaban",
		},
		Conditional: {
			yo: "compilaría",
			tú: "compilarías",
			Ud: "compilaría",
			nosotros: "compilaríamos",
			vosotros: "compilaríais",
			Uds: "compilarían",
		},
		Future: {
			yo: "compilaré",
			tú: "compilarás",
			Ud: "compilará",
			nosotros: "compilaremos",
			vosotros: "compilaréis",
			Uds: "compilarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "compile",
			tú: "compiles",
			Ud: "compile",
			nosotros: "compilemos",
			vosotros: "compiléis",
			Uds: "compilen",
		},
		Imperfect: {
			yo: "compilara",
			tú: "compilaras",
			Ud: "compilara",
			nosotros: "compiláramos",
			vosotros: "compilarais",
			Uds: "compilaran",
		},
		Imperfect2: {
			yo: "compilase",
			tú: "compilases",
			Ud: "compilase",
			nosotros: "compilásemos",
			vosotros: "compilaseis",
			Uds: "compilasen",
		},
		Future: {
			yo: "compilare",
			tú: "compilares",
			Ud: "compilare",
			nosotros: "compiláremos",
			vosotros: "compilareis",
			Uds: "compilaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "compila",
			Ud: "compile",
			nosotros: "compilemos",
			vosotros: "compilad",
			Uds: "compilen",
		},
		Negative: {
			tú: "no compiles",
			Ud: "no compile",
			nosotros: "no compilemos",
			vosotros: "no compiléis",
			Uds: "no compilen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy compilando",
			tú: "estás compilando",
			Ud: "está compilando",
			nosotros: "estamos compilando",
			vosotros: "estáis compilando",
			Uds: "están compilando",
		},
		Preterite: {
			yo: "estuve compilando",
			tú: "estuviste compilando",
			Ud: "estuvo compilando",
			nosotros: "estuvimos compilando",
			vosotros: "estuvisteis compilando",
			Uds: "estuvieron compilando",
		},
		Imperfect: {
			Uds: "estaban compilando",
			yo: "estaba compilando",
			tú: "estabas compilando",
			Ud: "estaba compilando",
			nosotros: "estábamos compilando",
			vosotros: "estabais compilando",
		},
		Conditional: {
			yo: "estaría compilando",
			tú: "estarías compilando",
			Ud: "estaría compilando",
			nosotros: "estaríamos compilando",
			vosotros: "estaríais compilando",
			Uds: "estarían compilando",
		},
		Future: {
			yo: "estaré compilando",
			tú: "estarás compilando",
			Ud: "estará compilando",
			nosotros: "estaremos compilando",
			vosotros: "estaréis compilando",
			Uds: "estarán compilando",
		},
	},
	Perfect: {
		Present: {
			yo: "he compilado",
			tú: "has compilado",
			Ud: "ha compilado",
			nosotros: "hemos compilado",
			vosotros: "habéis compilado",
			Uds: "han compilado",
		},
		Preterite: {
			yo: "hube compilado",
			tú: "hubiste compilado",
			Ud: "hubo compilado",
			nosotros: "hubimos compilado",
			vosotros: "hubisteis compilado",
			Uds: "hubieron compilado",
		},
		Past: {
			yo: "había compilado",
			tú: "habías compilado",
			Ud: "había compilado",
			nosotros: "habíamos compilado",
			vosotros: "habíais compilado",
			Uds: "habían compilado",
		},
		Conditional: {
			yo: "habría compilado",
			tú: "habrías compilado",
			Ud: "habría compilado",
			nosotros: "habríamos compilado",
			vosotros: "habríais compilado",
			Uds: "habrían compilado",
		},
		Future: {
			yo: "habré compilado",
			tú: "habrás compilado",
			Ud: "habrá compilado",
			nosotros: "habremos compilado",
			vosotros: "habréis compilado",
			Uds: "habrán compilado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya compilado",
			tú: "hayas compilado",
			Ud: "haya compilado",
			nosotros: "hayamos compilado",
			vosotros: "hayáis compilado",
			Uds: "hayan compilado",
		},
		Past: {
			yo: "hubiera compilado",
			tú: "hubieras compilado",
			Ud: "hubiera compilado",
			nosotros: "hubiéramos compilado",
			vosotros: "hubierais compilado",
			Uds: "hubieran compilado",
		},
		Future: {
			yo: "hubiere compilado",
			tú: "hubieres compilado",
			Ud: "hubiere compilado",
			nosotros: "hubiéremos compilado",
			vosotros: "hubiereis compilado",
			Uds: "hubieren compilado",
		},
	},
}
