var concretar = {
	Indicative: {
		Present: {
			yo: "concreto",
			tú: "concretas",
			Ud: "concreta",
			nosotros: "concretamos",
			vosotros: "concretáis",
			Uds: "concretan",
		},
		Preterite: {
			yo: "concreté",
			tú: "concretaste",
			Ud: "concretó",
			nosotros: "concretamos",
			vosotros: "concretasteis",
			Uds: "concretaron",
		},
		Imperfect: {
			yo: "concretaba",
			tú: "concretabas",
			Ud: "concretaba",
			nosotros: "concretábamos",
			vosotros: "concretabais",
			Uds: "concretaban",
		},
		Conditional: {
			yo: "concretaría",
			tú: "concretarías",
			Ud: "concretaría",
			nosotros: "concretaríamos",
			vosotros: "concretaríais",
			Uds: "concretarían",
		},
		Future: {
			yo: "concretaré",
			tú: "concretarás",
			Ud: "concretará",
			nosotros: "concretaremos",
			vosotros: "concretaréis",
			Uds: "concretarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "concrete",
			tú: "concretes",
			Ud: "concrete",
			nosotros: "concretemos",
			vosotros: "concretéis",
			Uds: "concreten",
		},
		Imperfect: {
			yo: "concretara",
			tú: "concretaras",
			Ud: "concretara",
			nosotros: "concretáramos",
			vosotros: "concretarais",
			Uds: "concretaran",
		},
		Imperfect2: {
			yo: "concretase",
			tú: "concretases",
			Ud: "concretase",
			nosotros: "concretásemos",
			vosotros: "concretaseis",
			Uds: "concretasen",
		},
		Future: {
			yo: "concretare",
			tú: "concretares",
			Ud: "concretare",
			nosotros: "concretáremos",
			vosotros: "concretareis",
			Uds: "concretaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "concreta",
			Ud: "concrete",
			nosotros: "concretemos",
			vosotros: "concretad",
			Uds: "concreten",
		},
		Negative: {
			tú: "no concretes",
			Ud: "no concrete",
			nosotros: "no concretemos",
			vosotros: "no concretéis",
			Uds: "no concreten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy concretando",
			tú: "estás concretando",
			Ud: "está concretando",
			nosotros: "estamos concretando",
			vosotros: "estáis concretando",
			Uds: "están concretando",
		},
		Preterite: {
			yo: "estuve concretando",
			tú: "estuviste concretando",
			Ud: "estuvo concretando",
			nosotros: "estuvimos concretando",
			vosotros: "estuvisteis concretando",
			Uds: "estuvieron concretando",
		},
		Imperfect: {
			Uds: "estaban concretando",
			yo: "estaba concretando",
			tú: "estabas concretando",
			Ud: "estaba concretando",
			nosotros: "estábamos concretando",
			vosotros: "estabais concretando",
		},
		Conditional: {
			yo: "estaría concretando",
			tú: "estarías concretando",
			Ud: "estaría concretando",
			nosotros: "estaríamos concretando",
			vosotros: "estaríais concretando",
			Uds: "estarían concretando",
		},
		Future: {
			yo: "estaré concretando",
			tú: "estarás concretando",
			Ud: "estará concretando",
			nosotros: "estaremos concretando",
			vosotros: "estaréis concretando",
			Uds: "estarán concretando",
		},
	},
	Perfect: {
		Present: {
			yo: "he concretado",
			tú: "has concretado",
			Ud: "ha concretado",
			nosotros: "hemos concretado",
			vosotros: "habéis concretado",
			Uds: "han concretado",
		},
		Preterite: {
			yo: "hube concretado",
			tú: "hubiste concretado",
			Ud: "hubo concretado",
			nosotros: "hubimos concretado",
			vosotros: "hubisteis concretado",
			Uds: "hubieron concretado",
		},
		Past: {
			yo: "había concretado",
			tú: "habías concretado",
			Ud: "había concretado",
			nosotros: "habíamos concretado",
			vosotros: "habíais concretado",
			Uds: "habían concretado",
		},
		Conditional: {
			yo: "habría concretado",
			tú: "habrías concretado",
			Ud: "habría concretado",
			nosotros: "habríamos concretado",
			vosotros: "habríais concretado",
			Uds: "habrían concretado",
		},
		Future: {
			yo: "habré concretado",
			tú: "habrás concretado",
			Ud: "habrá concretado",
			nosotros: "habremos concretado",
			vosotros: "habréis concretado",
			Uds: "habrán concretado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya concretado",
			tú: "hayas concretado",
			Ud: "haya concretado",
			nosotros: "hayamos concretado",
			vosotros: "hayáis concretado",
			Uds: "hayan concretado",
		},
		Past: {
			yo: "hubiera concretado",
			tú: "hubieras concretado",
			Ud: "hubiera concretado",
			nosotros: "hubiéramos concretado",
			vosotros: "hubierais concretado",
			Uds: "hubieran concretado",
		},
		Future: {
			yo: "hubiere concretado",
			tú: "hubieres concretado",
			Ud: "hubiere concretado",
			nosotros: "hubiéremos concretado",
			vosotros: "hubiereis concretado",
			Uds: "hubieren concretado",
		},
	},
}
