var condicionar = {
	Indicative: {
		Present: {
			yo: "condiciono",
			tú: "condicionas",
			Ud: "condiciona",
			nosotros: "condicionamos",
			vosotros: "condicionáis",
			Uds: "condicionan",
		},
		Preterite: {
			yo: "condicioné",
			tú: "condicionaste",
			Ud: "condicionó",
			nosotros: "condicionamos",
			vosotros: "condicionasteis",
			Uds: "condicionaron",
		},
		Imperfect: {
			yo: "condicionaba",
			tú: "condicionabas",
			Ud: "condicionaba",
			nosotros: "condicionábamos",
			vosotros: "condicionabais",
			Uds: "condicionaban",
		},
		Conditional: {
			yo: "condicionaría",
			tú: "condicionarías",
			Ud: "condicionaría",
			nosotros: "condicionaríamos",
			vosotros: "condicionaríais",
			Uds: "condicionarían",
		},
		Future: {
			yo: "condicionaré",
			tú: "condicionarás",
			Ud: "condicionará",
			nosotros: "condicionaremos",
			vosotros: "condicionaréis",
			Uds: "condicionarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "condicione",
			tú: "condiciones",
			Ud: "condicione",
			nosotros: "condicionemos",
			vosotros: "condicionéis",
			Uds: "condicionen",
		},
		Imperfect: {
			yo: "condicionara",
			tú: "condicionaras",
			Ud: "condicionara",
			nosotros: "condicionáramos",
			vosotros: "condicionarais",
			Uds: "condicionaran",
		},
		Imperfect2: {
			yo: "condicionase",
			tú: "condicionases",
			Ud: "condicionase",
			nosotros: "condicionásemos",
			vosotros: "condicionaseis",
			Uds: "condicionasen",
		},
		Future: {
			yo: "condicionare",
			tú: "condicionares",
			Ud: "condicionare",
			nosotros: "condicionáremos",
			vosotros: "condicionareis",
			Uds: "condicionaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "condiciona",
			Ud: "condicione",
			nosotros: "condicionemos",
			vosotros: "condicionad",
			Uds: "condicionen",
		},
		Negative: {
			tú: "no condiciones",
			Ud: "no condicione",
			nosotros: "no condicionemos",
			vosotros: "no condicionéis",
			Uds: "no condicionen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy condicionando",
			tú: "estás condicionando",
			Ud: "está condicionando",
			nosotros: "estamos condicionando",
			vosotros: "estáis condicionando",
			Uds: "están condicionando",
		},
		Preterite: {
			yo: "estuve condicionando",
			tú: "estuviste condicionando",
			Ud: "estuvo condicionando",
			nosotros: "estuvimos condicionando",
			vosotros: "estuvisteis condicionando",
			Uds: "estuvieron condicionando",
		},
		Imperfect: {
			Uds: "estaban condicionando",
			yo: "estaba condicionando",
			tú: "estabas condicionando",
			Ud: "estaba condicionando",
			nosotros: "estábamos condicionando",
			vosotros: "estabais condicionando",
		},
		Conditional: {
			yo: "estaría condicionando",
			tú: "estarías condicionando",
			Ud: "estaría condicionando",
			nosotros: "estaríamos condicionando",
			vosotros: "estaríais condicionando",
			Uds: "estarían condicionando",
		},
		Future: {
			yo: "estaré condicionando",
			tú: "estarás condicionando",
			Ud: "estará condicionando",
			nosotros: "estaremos condicionando",
			vosotros: "estaréis condicionando",
			Uds: "estarán condicionando",
		},
	},
	Perfect: {
		Present: {
			yo: "he condicionado",
			tú: "has condicionado",
			Ud: "ha condicionado",
			nosotros: "hemos condicionado",
			vosotros: "habéis condicionado",
			Uds: "han condicionado",
		},
		Preterite: {
			yo: "hube condicionado",
			tú: "hubiste condicionado",
			Ud: "hubo condicionado",
			nosotros: "hubimos condicionado",
			vosotros: "hubisteis condicionado",
			Uds: "hubieron condicionado",
		},
		Past: {
			yo: "había condicionado",
			tú: "habías condicionado",
			Ud: "había condicionado",
			nosotros: "habíamos condicionado",
			vosotros: "habíais condicionado",
			Uds: "habían condicionado",
		},
		Conditional: {
			yo: "habría condicionado",
			tú: "habrías condicionado",
			Ud: "habría condicionado",
			nosotros: "habríamos condicionado",
			vosotros: "habríais condicionado",
			Uds: "habrían condicionado",
		},
		Future: {
			yo: "habré condicionado",
			tú: "habrás condicionado",
			Ud: "habrá condicionado",
			nosotros: "habremos condicionado",
			vosotros: "habréis condicionado",
			Uds: "habrán condicionado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya condicionado",
			tú: "hayas condicionado",
			Ud: "haya condicionado",
			nosotros: "hayamos condicionado",
			vosotros: "hayáis condicionado",
			Uds: "hayan condicionado",
		},
		Past: {
			yo: "hubiera condicionado",
			tú: "hubieras condicionado",
			Ud: "hubiera condicionado",
			nosotros: "hubiéramos condicionado",
			vosotros: "hubierais condicionado",
			Uds: "hubieran condicionado",
		},
		Future: {
			yo: "hubiere condicionado",
			tú: "hubieres condicionado",
			Ud: "hubiere condicionado",
			nosotros: "hubiéremos condicionado",
			vosotros: "hubiereis condicionado",
			Uds: "hubieren condicionado",
		},
	},
}
