var conformar = {
	Indicative: {
		Present: {
			yo: "conformo",
			tú: "conformas",
			Ud: "conforma",
			nosotros: "conformamos",
			vosotros: "conformáis",
			Uds: "conforman",
		},
		Preterite: {
			yo: "conformé",
			tú: "conformaste",
			Ud: "conformó",
			nosotros: "conformamos",
			vosotros: "conformasteis",
			Uds: "conformaron",
		},
		Imperfect: {
			yo: "conformaba",
			tú: "conformabas",
			Ud: "conformaba",
			nosotros: "conformábamos",
			vosotros: "conformabais",
			Uds: "conformaban",
		},
		Conditional: {
			yo: "conformaría",
			tú: "conformarías",
			Ud: "conformaría",
			nosotros: "conformaríamos",
			vosotros: "conformaríais",
			Uds: "conformarían",
		},
		Future: {
			yo: "conformaré",
			tú: "conformarás",
			Ud: "conformará",
			nosotros: "conformaremos",
			vosotros: "conformaréis",
			Uds: "conformarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "conforme",
			tú: "conformes",
			Ud: "conforme",
			nosotros: "conformemos",
			vosotros: "conforméis",
			Uds: "conformen",
		},
		Imperfect: {
			yo: "conformara",
			tú: "conformaras",
			Ud: "conformara",
			nosotros: "conformáramos",
			vosotros: "conformarais",
			Uds: "conformaran",
		},
		Imperfect2: {
			yo: "conformase",
			tú: "conformases",
			Ud: "conformase",
			nosotros: "conformásemos",
			vosotros: "conformaseis",
			Uds: "conformasen",
		},
		Future: {
			yo: "conformare",
			tú: "conformares",
			Ud: "conformare",
			nosotros: "conformáremos",
			vosotros: "conformareis",
			Uds: "conformaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "conforma",
			Ud: "conforme",
			nosotros: "conformemos",
			vosotros: "conformad",
			Uds: "conformen",
		},
		Negative: {
			tú: "no conformes",
			Ud: "no conforme",
			nosotros: "no conformemos",
			vosotros: "no conforméis",
			Uds: "no conformen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy conformando",
			tú: "estás conformando",
			Ud: "está conformando",
			nosotros: "estamos conformando",
			vosotros: "estáis conformando",
			Uds: "están conformando",
		},
		Preterite: {
			yo: "estuve conformando",
			tú: "estuviste conformando",
			Ud: "estuvo conformando",
			nosotros: "estuvimos conformando",
			vosotros: "estuvisteis conformando",
			Uds: "estuvieron conformando",
		},
		Imperfect: {
			Uds: "estaban conformando",
			yo: "estaba conformando",
			tú: "estabas conformando",
			Ud: "estaba conformando",
			nosotros: "estábamos conformando",
			vosotros: "estabais conformando",
		},
		Conditional: {
			yo: "estaría conformando",
			tú: "estarías conformando",
			Ud: "estaría conformando",
			nosotros: "estaríamos conformando",
			vosotros: "estaríais conformando",
			Uds: "estarían conformando",
		},
		Future: {
			yo: "estaré conformando",
			tú: "estarás conformando",
			Ud: "estará conformando",
			nosotros: "estaremos conformando",
			vosotros: "estaréis conformando",
			Uds: "estarán conformando",
		},
	},
	Perfect: {
		Present: {
			yo: "he conformado",
			tú: "has conformado",
			Ud: "ha conformado",
			nosotros: "hemos conformado",
			vosotros: "habéis conformado",
			Uds: "han conformado",
		},
		Preterite: {
			yo: "hube conformado",
			tú: "hubiste conformado",
			Ud: "hubo conformado",
			nosotros: "hubimos conformado",
			vosotros: "hubisteis conformado",
			Uds: "hubieron conformado",
		},
		Past: {
			yo: "había conformado",
			tú: "habías conformado",
			Ud: "había conformado",
			nosotros: "habíamos conformado",
			vosotros: "habíais conformado",
			Uds: "habían conformado",
		},
		Conditional: {
			yo: "habría conformado",
			tú: "habrías conformado",
			Ud: "habría conformado",
			nosotros: "habríamos conformado",
			vosotros: "habríais conformado",
			Uds: "habrían conformado",
		},
		Future: {
			yo: "habré conformado",
			tú: "habrás conformado",
			Ud: "habrá conformado",
			nosotros: "habremos conformado",
			vosotros: "habréis conformado",
			Uds: "habrán conformado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya conformado",
			tú: "hayas conformado",
			Ud: "haya conformado",
			nosotros: "hayamos conformado",
			vosotros: "hayáis conformado",
			Uds: "hayan conformado",
		},
		Past: {
			yo: "hubiera conformado",
			tú: "hubieras conformado",
			Ud: "hubiera conformado",
			nosotros: "hubiéramos conformado",
			vosotros: "hubierais conformado",
			Uds: "hubieran conformado",
		},
		Future: {
			yo: "hubiere conformado",
			tú: "hubieres conformado",
			Ud: "hubiere conformado",
			nosotros: "hubiéremos conformado",
			vosotros: "hubiereis conformado",
			Uds: "hubieren conformado",
		},
	},
}
