var confluir = {
	Indicative: {
		Present: {
			yo: "confluyo",
			tú: "confluyes",
			Ud: "confluye",
			nosotros: "confluimos",
			vosotros: "confluís",
			Uds: "confluyen",
		},
		Preterite: {
			yo: "confluí",
			tú: "confluiste",
			Ud: "confluyó",
			nosotros: "confluimos",
			vosotros: "confluisteis",
			Uds: "confluyeron",
		},
		Imperfect: {
			yo: "confluía",
			tú: "confluías",
			Ud: "confluía",
			nosotros: "confluíamos",
			vosotros: "confluíais",
			Uds: "confluían",
		},
		Conditional: {
			yo: "confluiría",
			tú: "confluirías",
			Ud: "confluiría",
			nosotros: "confluiríamos",
			vosotros: "confluiríais",
			Uds: "confluirían",
		},
		Future: {
			yo: "confluiré",
			tú: "confluirás",
			Ud: "confluirá",
			nosotros: "confluiremos",
			vosotros: "confluiréis",
			Uds: "confluirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "confluya",
			tú: "confluyas",
			Ud: "confluya",
			nosotros: "confluyamos",
			vosotros: "confluyáis",
			Uds: "confluyan",
		},
		Imperfect: {
			yo: "confluyera",
			tú: "confluyeras",
			Ud: "confluyera",
			nosotros: "confluyéramos",
			vosotros: "confluyerais",
			Uds: "confluyeran",
		},
		Imperfect2: {
			yo: "confluyese",
			tú: "confluyeses",
			Ud: "confluyese",
			nosotros: "confluyésemos",
			vosotros: "confluyeseis",
			Uds: "confluyesen",
		},
		Future: {
			yo: "confluyere",
			tú: "confluyeres",
			Ud: "confluyere",
			nosotros: "confluyéremos",
			vosotros: "confluyereis",
			Uds: "confluyeren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "confluye",
			Ud: "confluya",
			nosotros: "confluyamos",
			vosotros: "confluid",
			Uds: "confluyan",
		},
		Negative: {
			tú: "no confluyas",
			Ud: "no confluya",
			nosotros: "no confluyamos",
			vosotros: "no confluyáis",
			Uds: "no confluyan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy confluyendo",
			tú: "estás confluyendo",
			Ud: "está confluyendo",
			nosotros: "estamos confluyendo",
			vosotros: "estáis confluyendo",
			Uds: "están confluyendo",
		},
		Preterite: {
			yo: "estuve confluyendo",
			tú: "estuviste confluyendo",
			Ud: "estuvo confluyendo",
			nosotros: "estuvimos confluyendo",
			vosotros: "estuvisteis confluyendo",
			Uds: "estuvieron confluyendo",
		},
		Imperfect: {
			Uds: "estaban confluyendo",
			yo: "estaba confluyendo",
			tú: "estabas confluyendo",
			Ud: "estaba confluyendo",
			nosotros: "estábamos confluyendo",
			vosotros: "estabais confluyendo",
		},
		Conditional: {
			yo: "estaría confluyendo",
			tú: "estarías confluyendo",
			Ud: "estaría confluyendo",
			nosotros: "estaríamos confluyendo",
			vosotros: "estaríais confluyendo",
			Uds: "estarían confluyendo",
		},
		Future: {
			yo: "estaré confluyendo",
			tú: "estarás confluyendo",
			Ud: "estará confluyendo",
			nosotros: "estaremos confluyendo",
			vosotros: "estaréis confluyendo",
			Uds: "estarán confluyendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he confluido",
			tú: "has confluido",
			Ud: "ha confluido",
			nosotros: "hemos confluido",
			vosotros: "habéis confluido",
			Uds: "han confluido",
		},
		Preterite: {
			yo: "hube confluido",
			tú: "hubiste confluido",
			Ud: "hubo confluido",
			nosotros: "hubimos confluido",
			vosotros: "hubisteis confluido",
			Uds: "hubieron confluido",
		},
		Past: {
			yo: "había confluido",
			tú: "habías confluido",
			Ud: "había confluido",
			nosotros: "habíamos confluido",
			vosotros: "habíais confluido",
			Uds: "habían confluido",
		},
		Conditional: {
			yo: "habría confluido",
			tú: "habrías confluido",
			Ud: "habría confluido",
			nosotros: "habríamos confluido",
			vosotros: "habríais confluido",
			Uds: "habrían confluido",
		},
		Future: {
			yo: "habré confluido",
			tú: "habrás confluido",
			Ud: "habrá confluido",
			nosotros: "habremos confluido",
			vosotros: "habréis confluido",
			Uds: "habrán confluido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya confluido",
			tú: "hayas confluido",
			Ud: "haya confluido",
			nosotros: "hayamos confluido",
			vosotros: "hayáis confluido",
			Uds: "hayan confluido",
		},
		Past: {
			yo: "hubiera confluido",
			tú: "hubieras confluido",
			Ud: "hubiera confluido",
			nosotros: "hubiéramos confluido",
			vosotros: "hubierais confluido",
			Uds: "hubieran confluido",
		},
		Future: {
			yo: "hubiere confluido",
			tú: "hubieres confluido",
			Ud: "hubiere confluido",
			nosotros: "hubiéremos confluido",
			vosotros: "hubiereis confluido",
			Uds: "hubieren confluido",
		},
	},
}
