var conferir = {
	Indicative: {
		Present: {
			yo: "confiero",
			tú: "confieres",
			Ud: "confiere",
			nosotros: "conferimos",
			vosotros: "conferís",
			Uds: "confieren",
		},
		Preterite: {
			yo: "conferí",
			tú: "conferiste",
			Ud: "confirió",
			nosotros: "conferimos",
			vosotros: "conferisteis",
			Uds: "confirieron",
		},
		Imperfect: {
			yo: "confería",
			tú: "conferías",
			Ud: "confería",
			nosotros: "conferíamos",
			vosotros: "conferíais",
			Uds: "conferían",
		},
		Conditional: {
			yo: "conferiría",
			tú: "conferirías",
			Ud: "conferiría",
			nosotros: "conferiríamos",
			vosotros: "conferiríais",
			Uds: "conferirían",
		},
		Future: {
			yo: "conferiré",
			tú: "conferirás",
			Ud: "conferirá",
			nosotros: "conferiremos",
			vosotros: "conferiréis",
			Uds: "conferirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "confiera",
			tú: "confieras",
			Ud: "confiera",
			nosotros: "confiramos",
			vosotros: "confiráis",
			Uds: "confieran",
		},
		Imperfect: {
			yo: "confiriera",
			tú: "confirieras",
			Ud: "confiriera",
			nosotros: "confiriéramos",
			vosotros: "confirierais",
			Uds: "confirieran",
		},
		Imperfect2: {
			yo: "confiriese",
			tú: "confirieses",
			Ud: "confiriese",
			nosotros: "confiriésemos",
			vosotros: "confirieseis",
			Uds: "confiriesen",
		},
		Future: {
			yo: "confiriere",
			tú: "confirieres",
			Ud: "confiriere",
			nosotros: "confiriéremos",
			vosotros: "confiriereis",
			Uds: "confirieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "confiere",
			Ud: "confiera",
			nosotros: "confiramos",
			vosotros: "conferid",
			Uds: "confieran",
		},
		Negative: {
			tú: "no confieras",
			Ud: "no confiera",
			nosotros: "no confiramos",
			vosotros: "no confiráis",
			Uds: "no confieran",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy confiriendo",
			tú: "estás confiriendo",
			Ud: "está confiriendo",
			nosotros: "estamos confiriendo",
			vosotros: "estáis confiriendo",
			Uds: "están confiriendo",
		},
		Preterite: {
			yo: "estuve confiriendo",
			tú: "estuviste confiriendo",
			Ud: "estuvo confiriendo",
			nosotros: "estuvimos confiriendo",
			vosotros: "estuvisteis confiriendo",
			Uds: "estuvieron confiriendo",
		},
		Imperfect: {
			Uds: "estaban confiriendo",
			yo: "estaba confiriendo",
			tú: "estabas confiriendo",
			Ud: "estaba confiriendo",
			nosotros: "estábamos confiriendo",
			vosotros: "estabais confiriendo",
		},
		Conditional: {
			yo: "estaría confiriendo",
			tú: "estarías confiriendo",
			Ud: "estaría confiriendo",
			nosotros: "estaríamos confiriendo",
			vosotros: "estaríais confiriendo",
			Uds: "estarían confiriendo",
		},
		Future: {
			yo: "estaré confiriendo",
			tú: "estarás confiriendo",
			Ud: "estará confiriendo",
			nosotros: "estaremos confiriendo",
			vosotros: "estaréis confiriendo",
			Uds: "estarán confiriendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he conferido",
			tú: "has conferido",
			Ud: "ha conferido",
			nosotros: "hemos conferido",
			vosotros: "habéis conferido",
			Uds: "han conferido",
		},
		Preterite: {
			yo: "hube conferido",
			tú: "hubiste conferido",
			Ud: "hubo conferido",
			nosotros: "hubimos conferido",
			vosotros: "hubisteis conferido",
			Uds: "hubieron conferido",
		},
		Past: {
			yo: "había conferido",
			tú: "habías conferido",
			Ud: "había conferido",
			nosotros: "habíamos conferido",
			vosotros: "habíais conferido",
			Uds: "habían conferido",
		},
		Conditional: {
			yo: "habría conferido",
			tú: "habrías conferido",
			Ud: "habría conferido",
			nosotros: "habríamos conferido",
			vosotros: "habríais conferido",
			Uds: "habrían conferido",
		},
		Future: {
			yo: "habré conferido",
			tú: "habrás conferido",
			Ud: "habrá conferido",
			nosotros: "habremos conferido",
			vosotros: "habréis conferido",
			Uds: "habrán conferido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya conferido",
			tú: "hayas conferido",
			Ud: "haya conferido",
			nosotros: "hayamos conferido",
			vosotros: "hayáis conferido",
			Uds: "hayan conferido",
		},
		Past: {
			yo: "hubiera conferido",
			tú: "hubieras conferido",
			Ud: "hubiera conferido",
			nosotros: "hubiéramos conferido",
			vosotros: "hubierais conferido",
			Uds: "hubieran conferido",
		},
		Future: {
			yo: "hubiere conferido",
			tú: "hubieres conferido",
			Ud: "hubiere conferido",
			nosotros: "hubiéremos conferido",
			vosotros: "hubiereis conferido",
			Uds: "hubieren conferido",
		},
	},
}
