var consultar = {
	Indicative: {
		Present: {
			yo: "consulto",
			tú: "consultas",
			Ud: "consulta",
			nosotros: "consultamos",
			vosotros: "consultáis",
			Uds: "consultan",
		},
		Preterite: {
			yo: "consulté",
			tú: "consultaste",
			Ud: "consultó",
			nosotros: "consultamos",
			vosotros: "consultasteis",
			Uds: "consultaron",
		},
		Imperfect: {
			yo: "consultaba",
			tú: "consultabas",
			Ud: "consultaba",
			nosotros: "consultábamos",
			vosotros: "consultabais",
			Uds: "consultaban",
		},
		Conditional: {
			yo: "consultaría",
			tú: "consultarías",
			Ud: "consultaría",
			nosotros: "consultaríamos",
			vosotros: "consultaríais",
			Uds: "consultarían",
		},
		Future: {
			yo: "consultaré",
			tú: "consultarás",
			Ud: "consultará",
			nosotros: "consultaremos",
			vosotros: "consultaréis",
			Uds: "consultarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "consulte",
			tú: "consultes",
			Ud: "consulte",
			nosotros: "consultemos",
			vosotros: "consultéis",
			Uds: "consulten",
		},
		Imperfect: {
			yo: "consultara",
			tú: "consultaras",
			Ud: "consultara",
			nosotros: "consultáramos",
			vosotros: "consultarais",
			Uds: "consultaran",
		},
		Imperfect2: {
			yo: "consultase",
			tú: "consultases",
			Ud: "consultase",
			nosotros: "consultásemos",
			vosotros: "consultaseis",
			Uds: "consultasen",
		},
		Future: {
			yo: "consultare",
			tú: "consultares",
			Ud: "consultare",
			nosotros: "consultáremos",
			vosotros: "consultareis",
			Uds: "consultaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "consulta",
			Ud: "consulte",
			nosotros: "consultemos",
			vosotros: "consultad",
			Uds: "consulten",
		},
		Negative: {
			tú: "no consultes",
			Ud: "no consulte",
			nosotros: "no consultemos",
			vosotros: "no consultéis",
			Uds: "no consulten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy consultando",
			tú: "estás consultando",
			Ud: "está consultando",
			nosotros: "estamos consultando",
			vosotros: "estáis consultando",
			Uds: "están consultando",
		},
		Preterite: {
			yo: "estuve consultando",
			tú: "estuviste consultando",
			Ud: "estuvo consultando",
			nosotros: "estuvimos consultando",
			vosotros: "estuvisteis consultando",
			Uds: "estuvieron consultando",
		},
		Imperfect: {
			Uds: "estaban consultando",
			yo: "estaba consultando",
			tú: "estabas consultando",
			Ud: "estaba consultando",
			nosotros: "estábamos consultando",
			vosotros: "estabais consultando",
		},
		Conditional: {
			yo: "estaría consultando",
			tú: "estarías consultando",
			Ud: "estaría consultando",
			nosotros: "estaríamos consultando",
			vosotros: "estaríais consultando",
			Uds: "estarían consultando",
		},
		Future: {
			yo: "estaré consultando",
			tú: "estarás consultando",
			Ud: "estará consultando",
			nosotros: "estaremos consultando",
			vosotros: "estaréis consultando",
			Uds: "estarán consultando",
		},
	},
	Perfect: {
		Present: {
			yo: "he consultado",
			tú: "has consultado",
			Ud: "ha consultado",
			nosotros: "hemos consultado",
			vosotros: "habéis consultado",
			Uds: "han consultado",
		},
		Preterite: {
			yo: "hube consultado",
			tú: "hubiste consultado",
			Ud: "hubo consultado",
			nosotros: "hubimos consultado",
			vosotros: "hubisteis consultado",
			Uds: "hubieron consultado",
		},
		Past: {
			yo: "había consultado",
			tú: "habías consultado",
			Ud: "había consultado",
			nosotros: "habíamos consultado",
			vosotros: "habíais consultado",
			Uds: "habían consultado",
		},
		Conditional: {
			yo: "habría consultado",
			tú: "habrías consultado",
			Ud: "habría consultado",
			nosotros: "habríamos consultado",
			vosotros: "habríais consultado",
			Uds: "habrían consultado",
		},
		Future: {
			yo: "habré consultado",
			tú: "habrás consultado",
			Ud: "habrá consultado",
			nosotros: "habremos consultado",
			vosotros: "habréis consultado",
			Uds: "habrán consultado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya consultado",
			tú: "hayas consultado",
			Ud: "haya consultado",
			nosotros: "hayamos consultado",
			vosotros: "hayáis consultado",
			Uds: "hayan consultado",
		},
		Past: {
			yo: "hubiera consultado",
			tú: "hubieras consultado",
			Ud: "hubiera consultado",
			nosotros: "hubiéramos consultado",
			vosotros: "hubierais consultado",
			Uds: "hubieran consultado",
		},
		Future: {
			yo: "hubiere consultado",
			tú: "hubieres consultado",
			Ud: "hubiere consultado",
			nosotros: "hubiéremos consultado",
			vosotros: "hubiereis consultado",
			Uds: "hubieren consultado",
		},
	},
}
