var consagrar = {
	Indicative: {
		Present: {
			yo: "consagro",
			tú: "consagras",
			Ud: "consagra",
			nosotros: "consagramos",
			vosotros: "consagráis",
			Uds: "consagran",
		},
		Preterite: {
			yo: "consagré",
			tú: "consagraste",
			Ud: "consagró",
			nosotros: "consagramos",
			vosotros: "consagrasteis",
			Uds: "consagraron",
		},
		Imperfect: {
			yo: "consagraba",
			tú: "consagrabas",
			Ud: "consagraba",
			nosotros: "consagrábamos",
			vosotros: "consagrabais",
			Uds: "consagraban",
		},
		Conditional: {
			yo: "consagraría",
			tú: "consagrarías",
			Ud: "consagraría",
			nosotros: "consagraríamos",
			vosotros: "consagraríais",
			Uds: "consagrarían",
		},
		Future: {
			yo: "consagraré",
			tú: "consagrarás",
			Ud: "consagrará",
			nosotros: "consagraremos",
			vosotros: "consagraréis",
			Uds: "consagrarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "consagre",
			tú: "consagres",
			Ud: "consagre",
			nosotros: "consagremos",
			vosotros: "consagréis",
			Uds: "consagren",
		},
		Imperfect: {
			yo: "consagrara",
			tú: "consagraras",
			Ud: "consagrara",
			nosotros: "consagráramos",
			vosotros: "consagrarais",
			Uds: "consagraran",
		},
		Imperfect2: {
			yo: "consagrase",
			tú: "consagrases",
			Ud: "consagrase",
			nosotros: "consagrásemos",
			vosotros: "consagraseis",
			Uds: "consagrasen",
		},
		Future: {
			yo: "consagrare",
			tú: "consagrares",
			Ud: "consagrare",
			nosotros: "consagráremos",
			vosotros: "consagrareis",
			Uds: "consagraren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "consagra",
			Ud: "consagre",
			nosotros: "consagremos",
			vosotros: "consagrad",
			Uds: "consagren",
		},
		Negative: {
			tú: "no consagres",
			Ud: "no consagre",
			nosotros: "no consagremos",
			vosotros: "no consagréis",
			Uds: "no consagren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy consagrando",
			tú: "estás consagrando",
			Ud: "está consagrando",
			nosotros: "estamos consagrando",
			vosotros: "estáis consagrando",
			Uds: "están consagrando",
		},
		Preterite: {
			yo: "estuve consagrando",
			tú: "estuviste consagrando",
			Ud: "estuvo consagrando",
			nosotros: "estuvimos consagrando",
			vosotros: "estuvisteis consagrando",
			Uds: "estuvieron consagrando",
		},
		Imperfect: {
			Uds: "estaban consagrando",
			yo: "estaba consagrando",
			tú: "estabas consagrando",
			Ud: "estaba consagrando",
			nosotros: "estábamos consagrando",
			vosotros: "estabais consagrando",
		},
		Conditional: {
			yo: "estaría consagrando",
			tú: "estarías consagrando",
			Ud: "estaría consagrando",
			nosotros: "estaríamos consagrando",
			vosotros: "estaríais consagrando",
			Uds: "estarían consagrando",
		},
		Future: {
			yo: "estaré consagrando",
			tú: "estarás consagrando",
			Ud: "estará consagrando",
			nosotros: "estaremos consagrando",
			vosotros: "estaréis consagrando",
			Uds: "estarán consagrando",
		},
	},
	Perfect: {
		Present: {
			yo: "he consagrado",
			tú: "has consagrado",
			Ud: "ha consagrado",
			nosotros: "hemos consagrado",
			vosotros: "habéis consagrado",
			Uds: "han consagrado",
		},
		Preterite: {
			yo: "hube consagrado",
			tú: "hubiste consagrado",
			Ud: "hubo consagrado",
			nosotros: "hubimos consagrado",
			vosotros: "hubisteis consagrado",
			Uds: "hubieron consagrado",
		},
		Past: {
			yo: "había consagrado",
			tú: "habías consagrado",
			Ud: "había consagrado",
			nosotros: "habíamos consagrado",
			vosotros: "habíais consagrado",
			Uds: "habían consagrado",
		},
		Conditional: {
			yo: "habría consagrado",
			tú: "habrías consagrado",
			Ud: "habría consagrado",
			nosotros: "habríamos consagrado",
			vosotros: "habríais consagrado",
			Uds: "habrían consagrado",
		},
		Future: {
			yo: "habré consagrado",
			tú: "habrás consagrado",
			Ud: "habrá consagrado",
			nosotros: "habremos consagrado",
			vosotros: "habréis consagrado",
			Uds: "habrán consagrado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya consagrado",
			tú: "hayas consagrado",
			Ud: "haya consagrado",
			nosotros: "hayamos consagrado",
			vosotros: "hayáis consagrado",
			Uds: "hayan consagrado",
		},
		Past: {
			yo: "hubiera consagrado",
			tú: "hubieras consagrado",
			Ud: "hubiera consagrado",
			nosotros: "hubiéramos consagrado",
			vosotros: "hubierais consagrado",
			Uds: "hubieran consagrado",
		},
		Future: {
			yo: "hubiere consagrado",
			tú: "hubieres consagrado",
			Ud: "hubiere consagrado",
			nosotros: "hubiéremos consagrado",
			vosotros: "hubiereis consagrado",
			Uds: "hubieren consagrado",
		},
	},
}
