var constar = {
	Indicative: {
		Present: {
			yo: "consto",
			tú: "constas",
			Ud: "consta",
			nosotros: "constamos",
			vosotros: "constáis",
			Uds: "constan",
		},
		Preterite: {
			yo: "consté",
			tú: "constaste",
			Ud: "constó",
			nosotros: "constamos",
			vosotros: "constasteis",
			Uds: "constaron",
		},
		Imperfect: {
			yo: "constaba",
			tú: "constabas",
			Ud: "constaba",
			nosotros: "constábamos",
			vosotros: "constabais",
			Uds: "constaban",
		},
		Conditional: {
			yo: "constaría",
			tú: "constarías",
			Ud: "constaría",
			nosotros: "constaríamos",
			vosotros: "constaríais",
			Uds: "constarían",
		},
		Future: {
			yo: "constaré",
			tú: "constarás",
			Ud: "constará",
			nosotros: "constaremos",
			vosotros: "constaréis",
			Uds: "constarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "conste",
			tú: "constes",
			Ud: "conste",
			nosotros: "constemos",
			vosotros: "constéis",
			Uds: "consten",
		},
		Imperfect: {
			yo: "constara",
			tú: "constaras",
			Ud: "constara",
			nosotros: "constáramos",
			vosotros: "constarais",
			Uds: "constaran",
		},
		Imperfect2: {
			yo: "constase",
			tú: "constases",
			Ud: "constase",
			nosotros: "constásemos",
			vosotros: "constaseis",
			Uds: "constasen",
		},
		Future: {
			yo: "constare",
			tú: "constares",
			Ud: "constare",
			nosotros: "constáremos",
			vosotros: "constareis",
			Uds: "constaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "consta",
			Ud: "conste",
			nosotros: "constemos",
			vosotros: "constad",
			Uds: "consten",
		},
		Negative: {
			tú: "no constes",
			Ud: "no conste",
			nosotros: "no constemos",
			vosotros: "no constéis",
			Uds: "no consten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy constando",
			tú: "estás constando",
			Ud: "está constando",
			nosotros: "estamos constando",
			vosotros: "estáis constando",
			Uds: "están constando",
		},
		Preterite: {
			yo: "estuve constando",
			tú: "estuviste constando",
			Ud: "estuvo constando",
			nosotros: "estuvimos constando",
			vosotros: "estuvisteis constando",
			Uds: "estuvieron constando",
		},
		Imperfect: {
			Uds: "estaban constando",
			yo: "estaba constando",
			tú: "estabas constando",
			Ud: "estaba constando",
			nosotros: "estábamos constando",
			vosotros: "estabais constando",
		},
		Conditional: {
			yo: "estaría constando",
			tú: "estarías constando",
			Ud: "estaría constando",
			nosotros: "estaríamos constando",
			vosotros: "estaríais constando",
			Uds: "estarían constando",
		},
		Future: {
			yo: "estaré constando",
			tú: "estarás constando",
			Ud: "estará constando",
			nosotros: "estaremos constando",
			vosotros: "estaréis constando",
			Uds: "estarán constando",
		},
	},
	Perfect: {
		Present: {
			yo: "he constado",
			tú: "has constado",
			Ud: "ha constado",
			nosotros: "hemos constado",
			vosotros: "habéis constado",
			Uds: "han constado",
		},
		Preterite: {
			yo: "hube constado",
			tú: "hubiste constado",
			Ud: "hubo constado",
			nosotros: "hubimos constado",
			vosotros: "hubisteis constado",
			Uds: "hubieron constado",
		},
		Past: {
			yo: "había constado",
			tú: "habías constado",
			Ud: "había constado",
			nosotros: "habíamos constado",
			vosotros: "habíais constado",
			Uds: "habían constado",
		},
		Conditional: {
			yo: "habría constado",
			tú: "habrías constado",
			Ud: "habría constado",
			nosotros: "habríamos constado",
			vosotros: "habríais constado",
			Uds: "habrían constado",
		},
		Future: {
			yo: "habré constado",
			tú: "habrás constado",
			Ud: "habrá constado",
			nosotros: "habremos constado",
			vosotros: "habréis constado",
			Uds: "habrán constado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya constado",
			tú: "hayas constado",
			Ud: "haya constado",
			nosotros: "hayamos constado",
			vosotros: "hayáis constado",
			Uds: "hayan constado",
		},
		Past: {
			yo: "hubiera constado",
			tú: "hubieras constado",
			Ud: "hubiera constado",
			nosotros: "hubiéramos constado",
			vosotros: "hubierais constado",
			Uds: "hubieran constado",
		},
		Future: {
			yo: "hubiere constado",
			tú: "hubieres constado",
			Ud: "hubiere constado",
			nosotros: "hubiéremos constado",
			vosotros: "hubiereis constado",
			Uds: "hubieren constado",
		},
	},
}
