var construir = {
	Indicative: {
		Present: {
			yo: "construyo",
			tú: "construyes",
			Ud: "construye",
			nosotros: "construimos",
			vosotros: "construís",
			Uds: "construyen",
		},
		Preterite: {
			yo: "construí",
			tú: "construiste",
			Ud: "construyó",
			nosotros: "construimos",
			vosotros: "construisteis",
			Uds: "construyeron",
		},
		Imperfect: {
			yo: "construía",
			tú: "construías",
			Ud: "construía",
			nosotros: "construíamos",
			vosotros: "construíais",
			Uds: "construían",
		},
		Conditional: {
			yo: "construiría",
			tú: "construirías",
			Ud: "construiría",
			nosotros: "construiríamos",
			vosotros: "construiríais",
			Uds: "construirían",
		},
		Future: {
			yo: "construiré",
			tú: "construirás",
			Ud: "construirá",
			nosotros: "construiremos",
			vosotros: "construiréis",
			Uds: "construirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "construya",
			tú: "construyas",
			Ud: "construya",
			nosotros: "construyamos",
			vosotros: "construyáis",
			Uds: "construyan",
		},
		Imperfect: {
			yo: "construyera",
			tú: "construyeras",
			Ud: "construyera",
			nosotros: "construyéramos",
			vosotros: "construyerais",
			Uds: "construyeran",
		},
		Imperfect2: {
			yo: "construyese",
			tú: "construyeses",
			Ud: "construyese",
			nosotros: "construyésemos",
			vosotros: "construyeseis",
			Uds: "construyesen",
		},
		Future: {
			yo: "construyere",
			tú: "construyeres",
			Ud: "construyere",
			nosotros: "construyéremos",
			vosotros: "construyereis",
			Uds: "construyeren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "construye",
			Ud: "construya",
			nosotros: "construyamos",
			vosotros: "construid",
			Uds: "construyan",
		},
		Negative: {
			tú: "no construyas",
			Ud: "no construya",
			nosotros: "no construyamos",
			vosotros: "no construyáis",
			Uds: "no construyan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy construyendo",
			tú: "estás construyendo",
			Ud: "está construyendo",
			nosotros: "estamos construyendo",
			vosotros: "estáis construyendo",
			Uds: "están construyendo",
		},
		Preterite: {
			yo: "estuve construyendo",
			tú: "estuviste construyendo",
			Ud: "estuvo construyendo",
			nosotros: "estuvimos construyendo",
			vosotros: "estuvisteis construyendo",
			Uds: "estuvieron construyendo",
		},
		Imperfect: {
			Uds: "estaban construyendo",
			yo: "estaba construyendo",
			tú: "estabas construyendo",
			Ud: "estaba construyendo",
			nosotros: "estábamos construyendo",
			vosotros: "estabais construyendo",
		},
		Conditional: {
			yo: "estaría construyendo",
			tú: "estarías construyendo",
			Ud: "estaría construyendo",
			nosotros: "estaríamos construyendo",
			vosotros: "estaríais construyendo",
			Uds: "estarían construyendo",
		},
		Future: {
			yo: "estaré construyendo",
			tú: "estarás construyendo",
			Ud: "estará construyendo",
			nosotros: "estaremos construyendo",
			vosotros: "estaréis construyendo",
			Uds: "estarán construyendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he construido",
			tú: "has construido",
			Ud: "ha construido",
			nosotros: "hemos construido",
			vosotros: "habéis construido",
			Uds: "han construido",
		},
		Preterite: {
			yo: "hube construido",
			tú: "hubiste construido",
			Ud: "hubo construido",
			nosotros: "hubimos construido",
			vosotros: "hubisteis construido",
			Uds: "hubieron construido",
		},
		Past: {
			yo: "había construido",
			tú: "habías construido",
			Ud: "había construido",
			nosotros: "habíamos construido",
			vosotros: "habíais construido",
			Uds: "habían construido",
		},
		Conditional: {
			yo: "habría construido",
			tú: "habrías construido",
			Ud: "habría construido",
			nosotros: "habríamos construido",
			vosotros: "habríais construido",
			Uds: "habrían construido",
		},
		Future: {
			yo: "habré construido",
			tú: "habrás construido",
			Ud: "habrá construido",
			nosotros: "habremos construido",
			vosotros: "habréis construido",
			Uds: "habrán construido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya construido",
			tú: "hayas construido",
			Ud: "haya construido",
			nosotros: "hayamos construido",
			vosotros: "hayáis construido",
			Uds: "hayan construido",
		},
		Past: {
			yo: "hubiera construido",
			tú: "hubieras construido",
			Ud: "hubiera construido",
			nosotros: "hubiéramos construido",
			vosotros: "hubierais construido",
			Uds: "hubieran construido",
		},
		Future: {
			yo: "hubiere construido",
			tú: "hubieres construido",
			Ud: "hubiere construido",
			nosotros: "hubiéremos construido",
			vosotros: "hubiereis construido",
			Uds: "hubieren construido",
		},
	},
}
