var conspirar = {
	Indicative: {
		Present: {
			yo: "conspiro",
			tú: "conspiras",
			Ud: "conspira",
			nosotros: "conspiramos",
			vosotros: "conspiráis",
			Uds: "conspiran",
		},
		Preterite: {
			yo: "conspiré",
			tú: "conspiraste",
			Ud: "conspiró",
			nosotros: "conspiramos",
			vosotros: "conspirasteis",
			Uds: "conspiraron",
		},
		Imperfect: {
			yo: "conspiraba",
			tú: "conspirabas",
			Ud: "conspiraba",
			nosotros: "conspirábamos",
			vosotros: "conspirabais",
			Uds: "conspiraban",
		},
		Conditional: {
			yo: "conspiraría",
			tú: "conspirarías",
			Ud: "conspiraría",
			nosotros: "conspiraríamos",
			vosotros: "conspiraríais",
			Uds: "conspirarían",
		},
		Future: {
			yo: "conspiraré",
			tú: "conspirarás",
			Ud: "conspirará",
			nosotros: "conspiraremos",
			vosotros: "conspiraréis",
			Uds: "conspirarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "conspire",
			tú: "conspires",
			Ud: "conspire",
			nosotros: "conspiremos",
			vosotros: "conspiréis",
			Uds: "conspiren",
		},
		Imperfect: {
			yo: "conspirara",
			tú: "conspiraras",
			Ud: "conspirara",
			nosotros: "conspiráramos",
			vosotros: "conspirarais",
			Uds: "conspiraran",
		},
		Imperfect2: {
			yo: "conspirase",
			tú: "conspirases",
			Ud: "conspirase",
			nosotros: "conspirásemos",
			vosotros: "conspiraseis",
			Uds: "conspirasen",
		},
		Future: {
			yo: "conspirare",
			tú: "conspirares",
			Ud: "conspirare",
			nosotros: "conspiráremos",
			vosotros: "conspirareis",
			Uds: "conspiraren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "conspira",
			Ud: "conspire",
			nosotros: "conspiremos",
			vosotros: "conspirad",
			Uds: "conspiren",
		},
		Negative: {
			tú: "no conspires",
			Ud: "no conspire",
			nosotros: "no conspiremos",
			vosotros: "no conspiréis",
			Uds: "no conspiren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy conspirando",
			tú: "estás conspirando",
			Ud: "está conspirando",
			nosotros: "estamos conspirando",
			vosotros: "estáis conspirando",
			Uds: "están conspirando",
		},
		Preterite: {
			yo: "estuve conspirando",
			tú: "estuviste conspirando",
			Ud: "estuvo conspirando",
			nosotros: "estuvimos conspirando",
			vosotros: "estuvisteis conspirando",
			Uds: "estuvieron conspirando",
		},
		Imperfect: {
			Uds: "estaban conspirando",
			yo: "estaba conspirando",
			tú: "estabas conspirando",
			Ud: "estaba conspirando",
			nosotros: "estábamos conspirando",
			vosotros: "estabais conspirando",
		},
		Conditional: {
			yo: "estaría conspirando",
			tú: "estarías conspirando",
			Ud: "estaría conspirando",
			nosotros: "estaríamos conspirando",
			vosotros: "estaríais conspirando",
			Uds: "estarían conspirando",
		},
		Future: {
			yo: "estaré conspirando",
			tú: "estarás conspirando",
			Ud: "estará conspirando",
			nosotros: "estaremos conspirando",
			vosotros: "estaréis conspirando",
			Uds: "estarán conspirando",
		},
	},
	Perfect: {
		Present: {
			yo: "he conspirado",
			tú: "has conspirado",
			Ud: "ha conspirado",
			nosotros: "hemos conspirado",
			vosotros: "habéis conspirado",
			Uds: "han conspirado",
		},
		Preterite: {
			yo: "hube conspirado",
			tú: "hubiste conspirado",
			Ud: "hubo conspirado",
			nosotros: "hubimos conspirado",
			vosotros: "hubisteis conspirado",
			Uds: "hubieron conspirado",
		},
		Past: {
			yo: "había conspirado",
			tú: "habías conspirado",
			Ud: "había conspirado",
			nosotros: "habíamos conspirado",
			vosotros: "habíais conspirado",
			Uds: "habían conspirado",
		},
		Conditional: {
			yo: "habría conspirado",
			tú: "habrías conspirado",
			Ud: "habría conspirado",
			nosotros: "habríamos conspirado",
			vosotros: "habríais conspirado",
			Uds: "habrían conspirado",
		},
		Future: {
			yo: "habré conspirado",
			tú: "habrás conspirado",
			Ud: "habrá conspirado",
			nosotros: "habremos conspirado",
			vosotros: "habréis conspirado",
			Uds: "habrán conspirado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya conspirado",
			tú: "hayas conspirado",
			Ud: "haya conspirado",
			nosotros: "hayamos conspirado",
			vosotros: "hayáis conspirado",
			Uds: "hayan conspirado",
		},
		Past: {
			yo: "hubiera conspirado",
			tú: "hubieras conspirado",
			Ud: "hubiera conspirado",
			nosotros: "hubiéramos conspirado",
			vosotros: "hubierais conspirado",
			Uds: "hubieran conspirado",
		},
		Future: {
			yo: "hubiere conspirado",
			tú: "hubieres conspirado",
			Ud: "hubiere conspirado",
			nosotros: "hubiéremos conspirado",
			vosotros: "hubiereis conspirado",
			Uds: "hubieren conspirado",
		},
	},
}
