var consistir = {
	Indicative: {
		Present: {
			yo: "consisto",
			tú: "consistes",
			Ud: "consiste",
			nosotros: "consistimos",
			vosotros: "consistís",
			Uds: "consisten",
		},
		Preterite: {
			yo: "consistí",
			tú: "consististe",
			Ud: "consistió",
			nosotros: "consistimos",
			vosotros: "consististeis",
			Uds: "consistieron",
		},
		Imperfect: {
			yo: "consistía",
			tú: "consistías",
			Ud: "consistía",
			nosotros: "consistíamos",
			vosotros: "consistíais",
			Uds: "consistían",
		},
		Conditional: {
			yo: "consistiría",
			tú: "consistirías",
			Ud: "consistiría",
			nosotros: "consistiríamos",
			vosotros: "consistiríais",
			Uds: "consistirían",
		},
		Future: {
			yo: "consistiré",
			tú: "consistirás",
			Ud: "consistirá",
			nosotros: "consistiremos",
			vosotros: "consistiréis",
			Uds: "consistirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "consista",
			tú: "consistas",
			Ud: "consista",
			nosotros: "consistamos",
			vosotros: "consistáis",
			Uds: "consistan",
		},
		Imperfect: {
			yo: "consistiera",
			tú: "consistieras",
			Ud: "consistiera",
			nosotros: "consistiéramos",
			vosotros: "consistierais",
			Uds: "consistieran",
		},
		Imperfect2: {
			yo: "consistiese",
			tú: "consistieses",
			Ud: "consistiese",
			nosotros: "consistiésemos",
			vosotros: "consistieseis",
			Uds: "consistiesen",
		},
		Future: {
			yo: "consistiere",
			tú: "consistieres",
			Ud: "consistiere",
			nosotros: "consistiéremos",
			vosotros: "consistiereis",
			Uds: "consistieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "consiste",
			Ud: "consista",
			nosotros: "consistamos",
			vosotros: "consistid",
			Uds: "consistan",
		},
		Negative: {
			tú: "no consistas",
			Ud: "no consista",
			nosotros: "no consistamos",
			vosotros: "no consistáis",
			Uds: "no consistan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy consistiendo",
			tú: "estás consistiendo",
			Ud: "está consistiendo",
			nosotros: "estamos consistiendo",
			vosotros: "estáis consistiendo",
			Uds: "están consistiendo",
		},
		Preterite: {
			yo: "estuve consistiendo",
			tú: "estuviste consistiendo",
			Ud: "estuvo consistiendo",
			nosotros: "estuvimos consistiendo",
			vosotros: "estuvisteis consistiendo",
			Uds: "estuvieron consistiendo",
		},
		Imperfect: {
			Uds: "estaban consistiendo",
			yo: "estaba consistiendo",
			tú: "estabas consistiendo",
			Ud: "estaba consistiendo",
			nosotros: "estábamos consistiendo",
			vosotros: "estabais consistiendo",
		},
		Conditional: {
			yo: "estaría consistiendo",
			tú: "estarías consistiendo",
			Ud: "estaría consistiendo",
			nosotros: "estaríamos consistiendo",
			vosotros: "estaríais consistiendo",
			Uds: "estarían consistiendo",
		},
		Future: {
			yo: "estaré consistiendo",
			tú: "estarás consistiendo",
			Ud: "estará consistiendo",
			nosotros: "estaremos consistiendo",
			vosotros: "estaréis consistiendo",
			Uds: "estarán consistiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he consistido",
			tú: "has consistido",
			Ud: "ha consistido",
			nosotros: "hemos consistido",
			vosotros: "habéis consistido",
			Uds: "han consistido",
		},
		Preterite: {
			yo: "hube consistido",
			tú: "hubiste consistido",
			Ud: "hubo consistido",
			nosotros: "hubimos consistido",
			vosotros: "hubisteis consistido",
			Uds: "hubieron consistido",
		},
		Past: {
			yo: "había consistido",
			tú: "habías consistido",
			Ud: "había consistido",
			nosotros: "habíamos consistido",
			vosotros: "habíais consistido",
			Uds: "habían consistido",
		},
		Conditional: {
			yo: "habría consistido",
			tú: "habrías consistido",
			Ud: "habría consistido",
			nosotros: "habríamos consistido",
			vosotros: "habríais consistido",
			Uds: "habrían consistido",
		},
		Future: {
			yo: "habré consistido",
			tú: "habrás consistido",
			Ud: "habrá consistido",
			nosotros: "habremos consistido",
			vosotros: "habréis consistido",
			Uds: "habrán consistido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya consistido",
			tú: "hayas consistido",
			Ud: "haya consistido",
			nosotros: "hayamos consistido",
			vosotros: "hayáis consistido",
			Uds: "hayan consistido",
		},
		Past: {
			yo: "hubiera consistido",
			tú: "hubieras consistido",
			Ud: "hubiera consistido",
			nosotros: "hubiéramos consistido",
			vosotros: "hubierais consistido",
			Uds: "hubieran consistido",
		},
		Future: {
			yo: "hubiere consistido",
			tú: "hubieres consistido",
			Ud: "hubiere consistido",
			nosotros: "hubiéremos consistido",
			vosotros: "hubiereis consistido",
			Uds: "hubieren consistido",
		},
	},
}
