var contribuir = {
	Indicative: {
		Present: {
			yo: "contribuyo",
			tú: "contribuyes",
			Ud: "contribuye",
			nosotros: "contribuimos",
			vosotros: "contribuís",
			Uds: "contribuyen",
		},
		Preterite: {
			yo: "contribuí",
			tú: "contribuiste",
			Ud: "contribuyó",
			nosotros: "contribuimos",
			vosotros: "contribuisteis",
			Uds: "contribuyeron",
		},
		Imperfect: {
			yo: "contribuía",
			tú: "contribuías",
			Ud: "contribuía",
			nosotros: "contribuíamos",
			vosotros: "contribuíais",
			Uds: "contribuían",
		},
		Conditional: {
			yo: "contribuiría",
			tú: "contribuirías",
			Ud: "contribuiría",
			nosotros: "contribuiríamos",
			vosotros: "contribuiríais",
			Uds: "contribuirían",
		},
		Future: {
			yo: "contribuiré",
			tú: "contribuirás",
			Ud: "contribuirá",
			nosotros: "contribuiremos",
			vosotros: "contribuiréis",
			Uds: "contribuirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "contribuya",
			tú: "contribuyas",
			Ud: "contribuya",
			nosotros: "contribuyamos",
			vosotros: "contribuyáis",
			Uds: "contribuyan",
		},
		Imperfect: {
			yo: "contribuyera",
			tú: "contribuyeras",
			Ud: "contribuyera",
			nosotros: "contribuyéramos",
			vosotros: "contribuyerais",
			Uds: "contribuyeran",
		},
		Imperfect2: {
			yo: "contribuyese",
			tú: "contribuyeses",
			Ud: "contribuyese",
			nosotros: "contribuyésemos",
			vosotros: "contribuyeseis",
			Uds: "contribuyesen",
		},
		Future: {
			yo: "contribuyere",
			tú: "contribuyeres",
			Ud: "contribuyere",
			nosotros: "contribuyéremos",
			vosotros: "contribuyereis",
			Uds: "contribuyeren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "contribuye",
			Ud: "contribuya",
			nosotros: "contribuyamos",
			vosotros: "contribuid",
			Uds: "contribuyan",
		},
		Negative: {
			tú: "no contribuyas",
			Ud: "no contribuya",
			nosotros: "no contribuyamos",
			vosotros: "no contribuyáis",
			Uds: "no contribuyan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy contribuyendo",
			tú: "estás contribuyendo",
			Ud: "está contribuyendo",
			nosotros: "estamos contribuyendo",
			vosotros: "estáis contribuyendo",
			Uds: "están contribuyendo",
		},
		Preterite: {
			yo: "estuve contribuyendo",
			tú: "estuviste contribuyendo",
			Ud: "estuvo contribuyendo",
			nosotros: "estuvimos contribuyendo",
			vosotros: "estuvisteis contribuyendo",
			Uds: "estuvieron contribuyendo",
		},
		Imperfect: {
			Uds: "estaban contribuyendo",
			yo: "estaba contribuyendo",
			tú: "estabas contribuyendo",
			Ud: "estaba contribuyendo",
			nosotros: "estábamos contribuyendo",
			vosotros: "estabais contribuyendo",
		},
		Conditional: {
			yo: "estaría contribuyendo",
			tú: "estarías contribuyendo",
			Ud: "estaría contribuyendo",
			nosotros: "estaríamos contribuyendo",
			vosotros: "estaríais contribuyendo",
			Uds: "estarían contribuyendo",
		},
		Future: {
			yo: "estaré contribuyendo",
			tú: "estarás contribuyendo",
			Ud: "estará contribuyendo",
			nosotros: "estaremos contribuyendo",
			vosotros: "estaréis contribuyendo",
			Uds: "estarán contribuyendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he contribuido",
			tú: "has contribuido",
			Ud: "ha contribuido",
			nosotros: "hemos contribuido",
			vosotros: "habéis contribuido",
			Uds: "han contribuido",
		},
		Preterite: {
			yo: "hube contribuido",
			tú: "hubiste contribuido",
			Ud: "hubo contribuido",
			nosotros: "hubimos contribuido",
			vosotros: "hubisteis contribuido",
			Uds: "hubieron contribuido",
		},
		Past: {
			yo: "había contribuido",
			tú: "habías contribuido",
			Ud: "había contribuido",
			nosotros: "habíamos contribuido",
			vosotros: "habíais contribuido",
			Uds: "habían contribuido",
		},
		Conditional: {
			yo: "habría contribuido",
			tú: "habrías contribuido",
			Ud: "habría contribuido",
			nosotros: "habríamos contribuido",
			vosotros: "habríais contribuido",
			Uds: "habrían contribuido",
		},
		Future: {
			yo: "habré contribuido",
			tú: "habrás contribuido",
			Ud: "habrá contribuido",
			nosotros: "habremos contribuido",
			vosotros: "habréis contribuido",
			Uds: "habrán contribuido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya contribuido",
			tú: "hayas contribuido",
			Ud: "haya contribuido",
			nosotros: "hayamos contribuido",
			vosotros: "hayáis contribuido",
			Uds: "hayan contribuido",
		},
		Past: {
			yo: "hubiera contribuido",
			tú: "hubieras contribuido",
			Ud: "hubiera contribuido",
			nosotros: "hubiéramos contribuido",
			vosotros: "hubierais contribuido",
			Uds: "hubieran contribuido",
		},
		Future: {
			yo: "hubiere contribuido",
			tú: "hubieres contribuido",
			Ud: "hubiere contribuido",
			nosotros: "hubiéremos contribuido",
			vosotros: "hubiereis contribuido",
			Uds: "hubieren contribuido",
		},
	},
}
