var contratar = {
	Indicative: {
		Present: {
			yo: "contrato",
			tú: "contratas",
			Ud: "contrata",
			nosotros: "contratamos",
			vosotros: "contratáis",
			Uds: "contratan",
		},
		Preterite: {
			yo: "contraté",
			tú: "contrataste",
			Ud: "contrató",
			nosotros: "contratamos",
			vosotros: "contratasteis",
			Uds: "contrataron",
		},
		Imperfect: {
			yo: "contrataba",
			tú: "contratabas",
			Ud: "contrataba",
			nosotros: "contratábamos",
			vosotros: "contratabais",
			Uds: "contrataban",
		},
		Conditional: {
			yo: "contrataría",
			tú: "contratarías",
			Ud: "contrataría",
			nosotros: "contrataríamos",
			vosotros: "contrataríais",
			Uds: "contratarían",
		},
		Future: {
			yo: "contrataré",
			tú: "contratarás",
			Ud: "contratará",
			nosotros: "contrataremos",
			vosotros: "contrataréis",
			Uds: "contratarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "contrate",
			tú: "contrates",
			Ud: "contrate",
			nosotros: "contratemos",
			vosotros: "contratéis",
			Uds: "contraten",
		},
		Imperfect: {
			yo: "contratara",
			tú: "contrataras",
			Ud: "contratara",
			nosotros: "contratáramos",
			vosotros: "contratarais",
			Uds: "contrataran",
		},
		Imperfect2: {
			yo: "contratase",
			tú: "contratases",
			Ud: "contratase",
			nosotros: "contratásemos",
			vosotros: "contrataseis",
			Uds: "contratasen",
		},
		Future: {
			yo: "contratare",
			tú: "contratares",
			Ud: "contratare",
			nosotros: "contratáremos",
			vosotros: "contratareis",
			Uds: "contrataren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "contrata",
			Ud: "contrate",
			nosotros: "contratemos",
			vosotros: "contratad",
			Uds: "contraten",
		},
		Negative: {
			tú: "no contrates",
			Ud: "no contrate",
			nosotros: "no contratemos",
			vosotros: "no contratéis",
			Uds: "no contraten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy contratando",
			tú: "estás contratando",
			Ud: "está contratando",
			nosotros: "estamos contratando",
			vosotros: "estáis contratando",
			Uds: "están contratando",
		},
		Preterite: {
			yo: "estuve contratando",
			tú: "estuviste contratando",
			Ud: "estuvo contratando",
			nosotros: "estuvimos contratando",
			vosotros: "estuvisteis contratando",
			Uds: "estuvieron contratando",
		},
		Imperfect: {
			Uds: "estaban contratando",
			yo: "estaba contratando",
			tú: "estabas contratando",
			Ud: "estaba contratando",
			nosotros: "estábamos contratando",
			vosotros: "estabais contratando",
		},
		Conditional: {
			yo: "estaría contratando",
			tú: "estarías contratando",
			Ud: "estaría contratando",
			nosotros: "estaríamos contratando",
			vosotros: "estaríais contratando",
			Uds: "estarían contratando",
		},
		Future: {
			yo: "estaré contratando",
			tú: "estarás contratando",
			Ud: "estará contratando",
			nosotros: "estaremos contratando",
			vosotros: "estaréis contratando",
			Uds: "estarán contratando",
		},
	},
	Perfect: {
		Present: {
			yo: "he contratado",
			tú: "has contratado",
			Ud: "ha contratado",
			nosotros: "hemos contratado",
			vosotros: "habéis contratado",
			Uds: "han contratado",
		},
		Preterite: {
			yo: "hube contratado",
			tú: "hubiste contratado",
			Ud: "hubo contratado",
			nosotros: "hubimos contratado",
			vosotros: "hubisteis contratado",
			Uds: "hubieron contratado",
		},
		Past: {
			yo: "había contratado",
			tú: "habías contratado",
			Ud: "había contratado",
			nosotros: "habíamos contratado",
			vosotros: "habíais contratado",
			Uds: "habían contratado",
		},
		Conditional: {
			yo: "habría contratado",
			tú: "habrías contratado",
			Ud: "habría contratado",
			nosotros: "habríamos contratado",
			vosotros: "habríais contratado",
			Uds: "habrían contratado",
		},
		Future: {
			yo: "habré contratado",
			tú: "habrás contratado",
			Ud: "habrá contratado",
			nosotros: "habremos contratado",
			vosotros: "habréis contratado",
			Uds: "habrán contratado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya contratado",
			tú: "hayas contratado",
			Ud: "haya contratado",
			nosotros: "hayamos contratado",
			vosotros: "hayáis contratado",
			Uds: "hayan contratado",
		},
		Past: {
			yo: "hubiera contratado",
			tú: "hubieras contratado",
			Ud: "hubiera contratado",
			nosotros: "hubiéramos contratado",
			vosotros: "hubierais contratado",
			Uds: "hubieran contratado",
		},
		Future: {
			yo: "hubiere contratado",
			tú: "hubieres contratado",
			Ud: "hubiere contratado",
			nosotros: "hubiéremos contratado",
			vosotros: "hubiereis contratado",
			Uds: "hubieren contratado",
		},
	},
}
