var contestar = {
	Indicative: {
		Present: {
			yo: "contesto",
			tú: "contestas",
			Ud: "contesta",
			nosotros: "contestamos",
			vosotros: "contestáis",
			Uds: "contestan",
		},
		Preterite: {
			yo: "contesté",
			tú: "contestaste",
			Ud: "contestó",
			nosotros: "contestamos",
			vosotros: "contestasteis",
			Uds: "contestaron",
		},
		Imperfect: {
			yo: "contestaba",
			tú: "contestabas",
			Ud: "contestaba",
			nosotros: "contestábamos",
			vosotros: "contestabais",
			Uds: "contestaban",
		},
		Conditional: {
			yo: "contestaría",
			tú: "contestarías",
			Ud: "contestaría",
			nosotros: "contestaríamos",
			vosotros: "contestaríais",
			Uds: "contestarían",
		},
		Future: {
			yo: "contestaré",
			tú: "contestarás",
			Ud: "contestará",
			nosotros: "contestaremos",
			vosotros: "contestaréis",
			Uds: "contestarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "conteste",
			tú: "contestes",
			Ud: "conteste",
			nosotros: "contestemos",
			vosotros: "contestéis",
			Uds: "contesten",
		},
		Imperfect: {
			yo: "contestara",
			tú: "contestaras",
			Ud: "contestara",
			nosotros: "contestáramos",
			vosotros: "contestarais",
			Uds: "contestaran",
		},
		Imperfect2: {
			yo: "contestase",
			tú: "contestases",
			Ud: "contestase",
			nosotros: "contestásemos",
			vosotros: "contestaseis",
			Uds: "contestasen",
		},
		Future: {
			yo: "contestare",
			tú: "contestares",
			Ud: "contestare",
			nosotros: "contestáremos",
			vosotros: "contestareis",
			Uds: "contestaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "contesta",
			Ud: "conteste",
			nosotros: "contestemos",
			vosotros: "contestad",
			Uds: "contesten",
		},
		Negative: {
			tú: "no contestes",
			Ud: "no conteste",
			nosotros: "no contestemos",
			vosotros: "no contestéis",
			Uds: "no contesten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy contestando",
			tú: "estás contestando",
			Ud: "está contestando",
			nosotros: "estamos contestando",
			vosotros: "estáis contestando",
			Uds: "están contestando",
		},
		Preterite: {
			yo: "estuve contestando",
			tú: "estuviste contestando",
			Ud: "estuvo contestando",
			nosotros: "estuvimos contestando",
			vosotros: "estuvisteis contestando",
			Uds: "estuvieron contestando",
		},
		Imperfect: {
			Uds: "estaban contestando",
			yo: "estaba contestando",
			tú: "estabas contestando",
			Ud: "estaba contestando",
			nosotros: "estábamos contestando",
			vosotros: "estabais contestando",
		},
		Conditional: {
			yo: "estaría contestando",
			tú: "estarías contestando",
			Ud: "estaría contestando",
			nosotros: "estaríamos contestando",
			vosotros: "estaríais contestando",
			Uds: "estarían contestando",
		},
		Future: {
			yo: "estaré contestando",
			tú: "estarás contestando",
			Ud: "estará contestando",
			nosotros: "estaremos contestando",
			vosotros: "estaréis contestando",
			Uds: "estarán contestando",
		},
	},
	Perfect: {
		Present: {
			yo: "he contestado",
			tú: "has contestado",
			Ud: "ha contestado",
			nosotros: "hemos contestado",
			vosotros: "habéis contestado",
			Uds: "han contestado",
		},
		Preterite: {
			yo: "hube contestado",
			tú: "hubiste contestado",
			Ud: "hubo contestado",
			nosotros: "hubimos contestado",
			vosotros: "hubisteis contestado",
			Uds: "hubieron contestado",
		},
		Past: {
			yo: "había contestado",
			tú: "habías contestado",
			Ud: "había contestado",
			nosotros: "habíamos contestado",
			vosotros: "habíais contestado",
			Uds: "habían contestado",
		},
		Conditional: {
			yo: "habría contestado",
			tú: "habrías contestado",
			Ud: "habría contestado",
			nosotros: "habríamos contestado",
			vosotros: "habríais contestado",
			Uds: "habrían contestado",
		},
		Future: {
			yo: "habré contestado",
			tú: "habrás contestado",
			Ud: "habrá contestado",
			nosotros: "habremos contestado",
			vosotros: "habréis contestado",
			Uds: "habrán contestado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya contestado",
			tú: "hayas contestado",
			Ud: "haya contestado",
			nosotros: "hayamos contestado",
			vosotros: "hayáis contestado",
			Uds: "hayan contestado",
		},
		Past: {
			yo: "hubiera contestado",
			tú: "hubieras contestado",
			Ud: "hubiera contestado",
			nosotros: "hubiéramos contestado",
			vosotros: "hubierais contestado",
			Uds: "hubieran contestado",
		},
		Future: {
			yo: "hubiere contestado",
			tú: "hubieres contestado",
			Ud: "hubiere contestado",
			nosotros: "hubiéremos contestado",
			vosotros: "hubiereis contestado",
			Uds: "hubieren contestado",
		},
	},
}
