var contemplar = {
	Indicative: {
		Present: {
			yo: "contemplo",
			tú: "contemplas",
			Ud: "contempla",
			nosotros: "contemplamos",
			vosotros: "contempláis",
			Uds: "contemplan",
		},
		Preterite: {
			yo: "contemplé",
			tú: "contemplaste",
			Ud: "contempló",
			nosotros: "contemplamos",
			vosotros: "contemplasteis",
			Uds: "contemplaron",
		},
		Imperfect: {
			yo: "contemplaba",
			tú: "contemplabas",
			Ud: "contemplaba",
			nosotros: "contemplábamos",
			vosotros: "contemplabais",
			Uds: "contemplaban",
		},
		Conditional: {
			yo: "contemplaría",
			tú: "contemplarías",
			Ud: "contemplaría",
			nosotros: "contemplaríamos",
			vosotros: "contemplaríais",
			Uds: "contemplarían",
		},
		Future: {
			yo: "contemplaré",
			tú: "contemplarás",
			Ud: "contemplará",
			nosotros: "contemplaremos",
			vosotros: "contemplaréis",
			Uds: "contemplarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "contemple",
			tú: "contemples",
			Ud: "contemple",
			nosotros: "contemplemos",
			vosotros: "contempléis",
			Uds: "contemplen",
		},
		Imperfect: {
			yo: "contemplara",
			tú: "contemplaras",
			Ud: "contemplara",
			nosotros: "contempláramos",
			vosotros: "contemplarais",
			Uds: "contemplaran",
		},
		Imperfect2: {
			yo: "contemplase",
			tú: "contemplases",
			Ud: "contemplase",
			nosotros: "contemplásemos",
			vosotros: "contemplaseis",
			Uds: "contemplasen",
		},
		Future: {
			yo: "contemplare",
			tú: "contemplares",
			Ud: "contemplare",
			nosotros: "contempláremos",
			vosotros: "contemplareis",
			Uds: "contemplaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "contempla",
			Ud: "contemple",
			nosotros: "contemplemos",
			vosotros: "contemplad",
			Uds: "contemplen",
		},
		Negative: {
			tú: "no contemples",
			Ud: "no contemple",
			nosotros: "no contemplemos",
			vosotros: "no contempléis",
			Uds: "no contemplen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy contemplando",
			tú: "estás contemplando",
			Ud: "está contemplando",
			nosotros: "estamos contemplando",
			vosotros: "estáis contemplando",
			Uds: "están contemplando",
		},
		Preterite: {
			yo: "estuve contemplando",
			tú: "estuviste contemplando",
			Ud: "estuvo contemplando",
			nosotros: "estuvimos contemplando",
			vosotros: "estuvisteis contemplando",
			Uds: "estuvieron contemplando",
		},
		Imperfect: {
			Uds: "estaban contemplando",
			yo: "estaba contemplando",
			tú: "estabas contemplando",
			Ud: "estaba contemplando",
			nosotros: "estábamos contemplando",
			vosotros: "estabais contemplando",
		},
		Conditional: {
			yo: "estaría contemplando",
			tú: "estarías contemplando",
			Ud: "estaría contemplando",
			nosotros: "estaríamos contemplando",
			vosotros: "estaríais contemplando",
			Uds: "estarían contemplando",
		},
		Future: {
			yo: "estaré contemplando",
			tú: "estarás contemplando",
			Ud: "estará contemplando",
			nosotros: "estaremos contemplando",
			vosotros: "estaréis contemplando",
			Uds: "estarán contemplando",
		},
	},
	Perfect: {
		Present: {
			yo: "he contemplado",
			tú: "has contemplado",
			Ud: "ha contemplado",
			nosotros: "hemos contemplado",
			vosotros: "habéis contemplado",
			Uds: "han contemplado",
		},
		Preterite: {
			yo: "hube contemplado",
			tú: "hubiste contemplado",
			Ud: "hubo contemplado",
			nosotros: "hubimos contemplado",
			vosotros: "hubisteis contemplado",
			Uds: "hubieron contemplado",
		},
		Past: {
			yo: "había contemplado",
			tú: "habías contemplado",
			Ud: "había contemplado",
			nosotros: "habíamos contemplado",
			vosotros: "habíais contemplado",
			Uds: "habían contemplado",
		},
		Conditional: {
			yo: "habría contemplado",
			tú: "habrías contemplado",
			Ud: "habría contemplado",
			nosotros: "habríamos contemplado",
			vosotros: "habríais contemplado",
			Uds: "habrían contemplado",
		},
		Future: {
			yo: "habré contemplado",
			tú: "habrás contemplado",
			Ud: "habrá contemplado",
			nosotros: "habremos contemplado",
			vosotros: "habréis contemplado",
			Uds: "habrán contemplado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya contemplado",
			tú: "hayas contemplado",
			Ud: "haya contemplado",
			nosotros: "hayamos contemplado",
			vosotros: "hayáis contemplado",
			Uds: "hayan contemplado",
		},
		Past: {
			yo: "hubiera contemplado",
			tú: "hubieras contemplado",
			Ud: "hubiera contemplado",
			nosotros: "hubiéramos contemplado",
			vosotros: "hubierais contemplado",
			Uds: "hubieran contemplado",
		},
		Future: {
			yo: "hubiere contemplado",
			tú: "hubieres contemplado",
			Ud: "hubiere contemplado",
			nosotros: "hubiéremos contemplado",
			vosotros: "hubiereis contemplado",
			Uds: "hubieren contemplado",
		},
	},
}
