var cooperar = {
	Indicative: {
		Present: {
			yo: "coopero",
			tú: "cooperas",
			Ud: "coopera",
			nosotros: "cooperamos",
			vosotros: "cooperáis",
			Uds: "cooperan",
		},
		Preterite: {
			yo: "cooperé",
			tú: "cooperaste",
			Ud: "cooperó",
			nosotros: "cooperamos",
			vosotros: "cooperasteis",
			Uds: "cooperaron",
		},
		Imperfect: {
			yo: "cooperaba",
			tú: "cooperabas",
			Ud: "cooperaba",
			nosotros: "cooperábamos",
			vosotros: "cooperabais",
			Uds: "cooperaban",
		},
		Conditional: {
			yo: "cooperaría",
			tú: "cooperarías",
			Ud: "cooperaría",
			nosotros: "cooperaríamos",
			vosotros: "cooperaríais",
			Uds: "cooperarían",
		},
		Future: {
			yo: "cooperaré",
			tú: "cooperarás",
			Ud: "cooperará",
			nosotros: "cooperaremos",
			vosotros: "cooperaréis",
			Uds: "cooperarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "coopere",
			tú: "cooperes",
			Ud: "coopere",
			nosotros: "cooperemos",
			vosotros: "cooperéis",
			Uds: "cooperen",
		},
		Imperfect: {
			yo: "cooperara",
			tú: "cooperaras",
			Ud: "cooperara",
			nosotros: "cooperáramos",
			vosotros: "cooperarais",
			Uds: "cooperaran",
		},
		Imperfect2: {
			yo: "cooperase",
			tú: "cooperases",
			Ud: "cooperase",
			nosotros: "cooperásemos",
			vosotros: "cooperaseis",
			Uds: "cooperasen",
		},
		Future: {
			yo: "cooperare",
			tú: "cooperares",
			Ud: "cooperare",
			nosotros: "cooperáremos",
			vosotros: "cooperareis",
			Uds: "cooperaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "coopera",
			Ud: "coopere",
			nosotros: "cooperemos",
			vosotros: "cooperad",
			Uds: "cooperen",
		},
		Negative: {
			tú: "no cooperes",
			Ud: "no coopere",
			nosotros: "no cooperemos",
			vosotros: "no cooperéis",
			Uds: "no cooperen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy cooperando",
			tú: "estás cooperando",
			Ud: "está cooperando",
			nosotros: "estamos cooperando",
			vosotros: "estáis cooperando",
			Uds: "están cooperando",
		},
		Preterite: {
			yo: "estuve cooperando",
			tú: "estuviste cooperando",
			Ud: "estuvo cooperando",
			nosotros: "estuvimos cooperando",
			vosotros: "estuvisteis cooperando",
			Uds: "estuvieron cooperando",
		},
		Imperfect: {
			Uds: "estaban cooperando",
			yo: "estaba cooperando",
			tú: "estabas cooperando",
			Ud: "estaba cooperando",
			nosotros: "estábamos cooperando",
			vosotros: "estabais cooperando",
		},
		Conditional: {
			yo: "estaría cooperando",
			tú: "estarías cooperando",
			Ud: "estaría cooperando",
			nosotros: "estaríamos cooperando",
			vosotros: "estaríais cooperando",
			Uds: "estarían cooperando",
		},
		Future: {
			yo: "estaré cooperando",
			tú: "estarás cooperando",
			Ud: "estará cooperando",
			nosotros: "estaremos cooperando",
			vosotros: "estaréis cooperando",
			Uds: "estarán cooperando",
		},
	},
	Perfect: {
		Present: {
			yo: "he cooperado",
			tú: "has cooperado",
			Ud: "ha cooperado",
			nosotros: "hemos cooperado",
			vosotros: "habéis cooperado",
			Uds: "han cooperado",
		},
		Preterite: {
			yo: "hube cooperado",
			tú: "hubiste cooperado",
			Ud: "hubo cooperado",
			nosotros: "hubimos cooperado",
			vosotros: "hubisteis cooperado",
			Uds: "hubieron cooperado",
		},
		Past: {
			yo: "había cooperado",
			tú: "habías cooperado",
			Ud: "había cooperado",
			nosotros: "habíamos cooperado",
			vosotros: "habíais cooperado",
			Uds: "habían cooperado",
		},
		Conditional: {
			yo: "habría cooperado",
			tú: "habrías cooperado",
			Ud: "habría cooperado",
			nosotros: "habríamos cooperado",
			vosotros: "habríais cooperado",
			Uds: "habrían cooperado",
		},
		Future: {
			yo: "habré cooperado",
			tú: "habrás cooperado",
			Ud: "habrá cooperado",
			nosotros: "habremos cooperado",
			vosotros: "habréis cooperado",
			Uds: "habrán cooperado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya cooperado",
			tú: "hayas cooperado",
			Ud: "haya cooperado",
			nosotros: "hayamos cooperado",
			vosotros: "hayáis cooperado",
			Uds: "hayan cooperado",
		},
		Past: {
			yo: "hubiera cooperado",
			tú: "hubieras cooperado",
			Ud: "hubiera cooperado",
			nosotros: "hubiéramos cooperado",
			vosotros: "hubierais cooperado",
			Uds: "hubieran cooperado",
		},
		Future: {
			yo: "hubiere cooperado",
			tú: "hubieres cooperado",
			Ud: "hubiere cooperado",
			nosotros: "hubiéremos cooperado",
			vosotros: "hubiereis cooperado",
			Uds: "hubieren cooperado",
		},
	},
}
