var coordinar = {
	Indicative: {
		Present: {
			yo: "coordino",
			tú: "coordinas",
			Ud: "coordina",
			nosotros: "coordinamos",
			vosotros: "coordináis",
			Uds: "coordinan",
		},
		Preterite: {
			yo: "coordiné",
			tú: "coordinaste",
			Ud: "coordinó",
			nosotros: "coordinamos",
			vosotros: "coordinasteis",
			Uds: "coordinaron",
		},
		Imperfect: {
			yo: "coordinaba",
			tú: "coordinabas",
			Ud: "coordinaba",
			nosotros: "coordinábamos",
			vosotros: "coordinabais",
			Uds: "coordinaban",
		},
		Conditional: {
			yo: "coordinaría",
			tú: "coordinarías",
			Ud: "coordinaría",
			nosotros: "coordinaríamos",
			vosotros: "coordinaríais",
			Uds: "coordinarían",
		},
		Future: {
			yo: "coordinaré",
			tú: "coordinarás",
			Ud: "coordinará",
			nosotros: "coordinaremos",
			vosotros: "coordinaréis",
			Uds: "coordinarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "coordine",
			tú: "coordines",
			Ud: "coordine",
			nosotros: "coordinemos",
			vosotros: "coordinéis",
			Uds: "coordinen",
		},
		Imperfect: {
			yo: "coordinara",
			tú: "coordinaras",
			Ud: "coordinara",
			nosotros: "coordináramos",
			vosotros: "coordinarais",
			Uds: "coordinaran",
		},
		Imperfect2: {
			yo: "coordinase",
			tú: "coordinases",
			Ud: "coordinase",
			nosotros: "coordinásemos",
			vosotros: "coordinaseis",
			Uds: "coordinasen",
		},
		Future: {
			yo: "coordinare",
			tú: "coordinares",
			Ud: "coordinare",
			nosotros: "coordináremos",
			vosotros: "coordinareis",
			Uds: "coordinaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "coordina",
			Ud: "coordine",
			nosotros: "coordinemos",
			vosotros: "coordinad",
			Uds: "coordinen",
		},
		Negative: {
			tú: "no coordines",
			Ud: "no coordine",
			nosotros: "no coordinemos",
			vosotros: "no coordinéis",
			Uds: "no coordinen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy coordinando",
			tú: "estás coordinando",
			Ud: "está coordinando",
			nosotros: "estamos coordinando",
			vosotros: "estáis coordinando",
			Uds: "están coordinando",
		},
		Preterite: {
			yo: "estuve coordinando",
			tú: "estuviste coordinando",
			Ud: "estuvo coordinando",
			nosotros: "estuvimos coordinando",
			vosotros: "estuvisteis coordinando",
			Uds: "estuvieron coordinando",
		},
		Imperfect: {
			Uds: "estaban coordinando",
			yo: "estaba coordinando",
			tú: "estabas coordinando",
			Ud: "estaba coordinando",
			nosotros: "estábamos coordinando",
			vosotros: "estabais coordinando",
		},
		Conditional: {
			yo: "estaría coordinando",
			tú: "estarías coordinando",
			Ud: "estaría coordinando",
			nosotros: "estaríamos coordinando",
			vosotros: "estaríais coordinando",
			Uds: "estarían coordinando",
		},
		Future: {
			yo: "estaré coordinando",
			tú: "estarás coordinando",
			Ud: "estará coordinando",
			nosotros: "estaremos coordinando",
			vosotros: "estaréis coordinando",
			Uds: "estarán coordinando",
		},
	},
	Perfect: {
		Present: {
			yo: "he coordinado",
			tú: "has coordinado",
			Ud: "ha coordinado",
			nosotros: "hemos coordinado",
			vosotros: "habéis coordinado",
			Uds: "han coordinado",
		},
		Preterite: {
			yo: "hube coordinado",
			tú: "hubiste coordinado",
			Ud: "hubo coordinado",
			nosotros: "hubimos coordinado",
			vosotros: "hubisteis coordinado",
			Uds: "hubieron coordinado",
		},
		Past: {
			yo: "había coordinado",
			tú: "habías coordinado",
			Ud: "había coordinado",
			nosotros: "habíamos coordinado",
			vosotros: "habíais coordinado",
			Uds: "habían coordinado",
		},
		Conditional: {
			yo: "habría coordinado",
			tú: "habrías coordinado",
			Ud: "habría coordinado",
			nosotros: "habríamos coordinado",
			vosotros: "habríais coordinado",
			Uds: "habrían coordinado",
		},
		Future: {
			yo: "habré coordinado",
			tú: "habrás coordinado",
			Ud: "habrá coordinado",
			nosotros: "habremos coordinado",
			vosotros: "habréis coordinado",
			Uds: "habrán coordinado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya coordinado",
			tú: "hayas coordinado",
			Ud: "haya coordinado",
			nosotros: "hayamos coordinado",
			vosotros: "hayáis coordinado",
			Uds: "hayan coordinado",
		},
		Past: {
			yo: "hubiera coordinado",
			tú: "hubieras coordinado",
			Ud: "hubiera coordinado",
			nosotros: "hubiéramos coordinado",
			vosotros: "hubierais coordinado",
			Uds: "hubieran coordinado",
		},
		Future: {
			yo: "hubiere coordinado",
			tú: "hubieres coordinado",
			Ud: "hubiere coordinado",
			nosotros: "hubiéremos coordinado",
			vosotros: "hubiereis coordinado",
			Uds: "hubieren coordinado",
		},
	},
}
