var crear = {
	Indicative: {
		Present: {
			yo: "creo",
			tú: "creas",
			Ud: "crea",
			nosotros: "creamos",
			vosotros: "creáis",
			Uds: "crean",
		},
		Preterite: {
			yo: "creé",
			tú: "creaste",
			Ud: "creó",
			nosotros: "creamos",
			vosotros: "creasteis",
			Uds: "crearon",
		},
		Imperfect: {
			yo: "creaba",
			tú: "creabas",
			Ud: "creaba",
			nosotros: "creábamos",
			vosotros: "creabais",
			Uds: "creaban",
		},
		Conditional: {
			yo: "crearía",
			tú: "crearías",
			Ud: "crearía",
			nosotros: "crearíamos",
			vosotros: "crearíais",
			Uds: "crearían",
		},
		Future: {
			yo: "crearé",
			tú: "crearás",
			Ud: "creará",
			nosotros: "crearemos",
			vosotros: "crearéis",
			Uds: "crearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "cree",
			tú: "crees",
			Ud: "cree",
			nosotros: "creemos",
			vosotros: "creéis",
			Uds: "creen",
		},
		Imperfect: {
			yo: "creara",
			tú: "crearas",
			Ud: "creara",
			nosotros: "creáramos",
			vosotros: "crearais",
			Uds: "crearan",
		},
		Imperfect2: {
			yo: "crease",
			tú: "creases",
			Ud: "crease",
			nosotros: "creásemos",
			vosotros: "creaseis",
			Uds: "creasen",
		},
		Future: {
			yo: "creare",
			tú: "creares",
			Ud: "creare",
			nosotros: "creáremos",
			vosotros: "creareis",
			Uds: "crearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "crea",
			Ud: "cree",
			nosotros: "creemos",
			vosotros: "cread",
			Uds: "creen",
		},
		Negative: {
			tú: "no crees",
			Ud: "no cree",
			nosotros: "no creemos",
			vosotros: "no creéis",
			Uds: "no creen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy creando",
			tú: "estás creando",
			Ud: "está creando",
			nosotros: "estamos creando",
			vosotros: "estáis creando",
			Uds: "están creando",
		},
		Preterite: {
			yo: "estuve creando",
			tú: "estuviste creando",
			Ud: "estuvo creando",
			nosotros: "estuvimos creando",
			vosotros: "estuvisteis creando",
			Uds: "estuvieron creando",
		},
		Imperfect: {
			Uds: "estaban creando",
			yo: "estaba creando",
			tú: "estabas creando",
			Ud: "estaba creando",
			nosotros: "estábamos creando",
			vosotros: "estabais creando",
		},
		Conditional: {
			yo: "estaría creando",
			tú: "estarías creando",
			Ud: "estaría creando",
			nosotros: "estaríamos creando",
			vosotros: "estaríais creando",
			Uds: "estarían creando",
		},
		Future: {
			yo: "estaré creando",
			tú: "estarás creando",
			Ud: "estará creando",
			nosotros: "estaremos creando",
			vosotros: "estaréis creando",
			Uds: "estarán creando",
		},
	},
	Perfect: {
		Present: {
			yo: "he creado",
			tú: "has creado",
			Ud: "ha creado",
			nosotros: "hemos creado",
			vosotros: "habéis creado",
			Uds: "han creado",
		},
		Preterite: {
			yo: "hube creado",
			tú: "hubiste creado",
			Ud: "hubo creado",
			nosotros: "hubimos creado",
			vosotros: "hubisteis creado",
			Uds: "hubieron creado",
		},
		Past: {
			yo: "había creado",
			tú: "habías creado",
			Ud: "había creado",
			nosotros: "habíamos creado",
			vosotros: "habíais creado",
			Uds: "habían creado",
		},
		Conditional: {
			yo: "habría creado",
			tú: "habrías creado",
			Ud: "habría creado",
			nosotros: "habríamos creado",
			vosotros: "habríais creado",
			Uds: "habrían creado",
		},
		Future: {
			yo: "habré creado",
			tú: "habrás creado",
			Ud: "habrá creado",
			nosotros: "habremos creado",
			vosotros: "habréis creado",
			Uds: "habrán creado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya creado",
			tú: "hayas creado",
			Ud: "haya creado",
			nosotros: "hayamos creado",
			vosotros: "hayáis creado",
			Uds: "hayan creado",
		},
		Past: {
			yo: "hubiera creado",
			tú: "hubieras creado",
			Ud: "hubiera creado",
			nosotros: "hubiéramos creado",
			vosotros: "hubierais creado",
			Uds: "hubieran creado",
		},
		Future: {
			yo: "hubiere creado",
			tú: "hubieres creado",
			Ud: "hubiere creado",
			nosotros: "hubiéremos creado",
			vosotros: "hubiereis creado",
			Uds: "hubieren creado",
		},
	},
}
