var criticar = {
	Indicative: {
		Present: {
			yo: "critico",
			tú: "criticas",
			Ud: "critica",
			nosotros: "criticamos",
			vosotros: "criticáis",
			Uds: "critican",
		},
		Preterite: {
			yo: "critiqué",
			tú: "criticaste",
			Ud: "criticó",
			nosotros: "criticamos",
			vosotros: "criticasteis",
			Uds: "criticaron",
		},
		Imperfect: {
			yo: "criticaba",
			tú: "criticabas",
			Ud: "criticaba",
			nosotros: "criticábamos",
			vosotros: "criticabais",
			Uds: "criticaban",
		},
		Conditional: {
			yo: "criticaría",
			tú: "criticarías",
			Ud: "criticaría",
			nosotros: "criticaríamos",
			vosotros: "criticaríais",
			Uds: "criticarían",
		},
		Future: {
			yo: "criticaré",
			tú: "criticarás",
			Ud: "criticará",
			nosotros: "criticaremos",
			vosotros: "criticaréis",
			Uds: "criticarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "critique",
			tú: "critiques",
			Ud: "critique",
			nosotros: "critiquemos",
			vosotros: "critiquéis",
			Uds: "critiquen",
		},
		Imperfect: {
			yo: "criticara",
			tú: "criticaras",
			Ud: "criticara",
			nosotros: "criticáramos",
			vosotros: "criticarais",
			Uds: "criticaran",
		},
		Imperfect2: {
			yo: "criticase",
			tú: "criticases",
			Ud: "criticase",
			nosotros: "criticásemos",
			vosotros: "criticaseis",
			Uds: "criticasen",
		},
		Future: {
			yo: "criticare",
			tú: "criticares",
			Ud: "criticare",
			nosotros: "criticáremos",
			vosotros: "criticareis",
			Uds: "criticaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "critica",
			Ud: "critique",
			nosotros: "critiquemos",
			vosotros: "criticad",
			Uds: "critiquen",
		},
		Negative: {
			tú: "no critiques",
			Ud: "no critique",
			nosotros: "no critiquemos",
			vosotros: "no critiquéis",
			Uds: "no critiquen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy criticando",
			tú: "estás criticando",
			Ud: "está criticando",
			nosotros: "estamos criticando",
			vosotros: "estáis criticando",
			Uds: "están criticando",
		},
		Preterite: {
			yo: "estuve criticando",
			tú: "estuviste criticando",
			Ud: "estuvo criticando",
			nosotros: "estuvimos criticando",
			vosotros: "estuvisteis criticando",
			Uds: "estuvieron criticando",
		},
		Imperfect: {
			Uds: "estaban criticando",
			yo: "estaba criticando",
			tú: "estabas criticando",
			Ud: "estaba criticando",
			nosotros: "estábamos criticando",
			vosotros: "estabais criticando",
		},
		Conditional: {
			yo: "estaría criticando",
			tú: "estarías criticando",
			Ud: "estaría criticando",
			nosotros: "estaríamos criticando",
			vosotros: "estaríais criticando",
			Uds: "estarían criticando",
		},
		Future: {
			yo: "estaré criticando",
			tú: "estarás criticando",
			Ud: "estará criticando",
			nosotros: "estaremos criticando",
			vosotros: "estaréis criticando",
			Uds: "estarán criticando",
		},
	},
	Perfect: {
		Present: {
			yo: "he criticado",
			tú: "has criticado",
			Ud: "ha criticado",
			nosotros: "hemos criticado",
			vosotros: "habéis criticado",
			Uds: "han criticado",
		},
		Preterite: {
			yo: "hube criticado",
			tú: "hubiste criticado",
			Ud: "hubo criticado",
			nosotros: "hubimos criticado",
			vosotros: "hubisteis criticado",
			Uds: "hubieron criticado",
		},
		Past: {
			yo: "había criticado",
			tú: "habías criticado",
			Ud: "había criticado",
			nosotros: "habíamos criticado",
			vosotros: "habíais criticado",
			Uds: "habían criticado",
		},
		Conditional: {
			yo: "habría criticado",
			tú: "habrías criticado",
			Ud: "habría criticado",
			nosotros: "habríamos criticado",
			vosotros: "habríais criticado",
			Uds: "habrían criticado",
		},
		Future: {
			yo: "habré criticado",
			tú: "habrás criticado",
			Ud: "habrá criticado",
			nosotros: "habremos criticado",
			vosotros: "habréis criticado",
			Uds: "habrán criticado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya criticado",
			tú: "hayas criticado",
			Ud: "haya criticado",
			nosotros: "hayamos criticado",
			vosotros: "hayáis criticado",
			Uds: "hayan criticado",
		},
		Past: {
			yo: "hubiera criticado",
			tú: "hubieras criticado",
			Ud: "hubiera criticado",
			nosotros: "hubiéramos criticado",
			vosotros: "hubierais criticado",
			Uds: "hubieran criticado",
		},
		Future: {
			yo: "hubiere criticado",
			tú: "hubieres criticado",
			Ud: "hubiere criticado",
			nosotros: "hubiéremos criticado",
			vosotros: "hubiereis criticado",
			Uds: "hubieren criticado",
		},
	},
}
