var cursar = {
	Indicative: {
		Present: {
			yo: "curso",
			tú: "cursas",
			Ud: "cursa",
			nosotros: "cursamos",
			vosotros: "cursáis",
			Uds: "cursan",
		},
		Preterite: {
			yo: "cursé",
			tú: "cursaste",
			Ud: "cursó",
			nosotros: "cursamos",
			vosotros: "cursasteis",
			Uds: "cursaron",
		},
		Imperfect: {
			yo: "cursaba",
			tú: "cursabas",
			Ud: "cursaba",
			nosotros: "cursábamos",
			vosotros: "cursabais",
			Uds: "cursaban",
		},
		Conditional: {
			yo: "cursaría",
			tú: "cursarías",
			Ud: "cursaría",
			nosotros: "cursaríamos",
			vosotros: "cursaríais",
			Uds: "cursarían",
		},
		Future: {
			yo: "cursaré",
			tú: "cursarás",
			Ud: "cursará",
			nosotros: "cursaremos",
			vosotros: "cursaréis",
			Uds: "cursarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "curse",
			tú: "curses",
			Ud: "curse",
			nosotros: "cursemos",
			vosotros: "curséis",
			Uds: "cursen",
		},
		Imperfect: {
			yo: "cursara",
			tú: "cursaras",
			Ud: "cursara",
			nosotros: "cursáramos",
			vosotros: "cursarais",
			Uds: "cursaran",
		},
		Imperfect2: {
			yo: "cursase",
			tú: "cursases",
			Ud: "cursase",
			nosotros: "cursásemos",
			vosotros: "cursaseis",
			Uds: "cursasen",
		},
		Future: {
			yo: "cursare",
			tú: "cursares",
			Ud: "cursare",
			nosotros: "cursáremos",
			vosotros: "cursareis",
			Uds: "cursaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "cursa",
			Ud: "curse",
			nosotros: "cursemos",
			vosotros: "cursad",
			Uds: "cursen",
		},
		Negative: {
			tú: "no curses",
			Ud: "no curse",
			nosotros: "no cursemos",
			vosotros: "no curséis",
			Uds: "no cursen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy cursando",
			tú: "estás cursando",
			Ud: "está cursando",
			nosotros: "estamos cursando",
			vosotros: "estáis cursando",
			Uds: "están cursando",
		},
		Preterite: {
			yo: "estuve cursando",
			tú: "estuviste cursando",
			Ud: "estuvo cursando",
			nosotros: "estuvimos cursando",
			vosotros: "estuvisteis cursando",
			Uds: "estuvieron cursando",
		},
		Imperfect: {
			Uds: "estaban cursando",
			yo: "estaba cursando",
			tú: "estabas cursando",
			Ud: "estaba cursando",
			nosotros: "estábamos cursando",
			vosotros: "estabais cursando",
		},
		Conditional: {
			yo: "estaría cursando",
			tú: "estarías cursando",
			Ud: "estaría cursando",
			nosotros: "estaríamos cursando",
			vosotros: "estaríais cursando",
			Uds: "estarían cursando",
		},
		Future: {
			yo: "estaré cursando",
			tú: "estarás cursando",
			Ud: "estará cursando",
			nosotros: "estaremos cursando",
			vosotros: "estaréis cursando",
			Uds: "estarán cursando",
		},
	},
	Perfect: {
		Present: {
			yo: "he cursado",
			tú: "has cursado",
			Ud: "ha cursado",
			nosotros: "hemos cursado",
			vosotros: "habéis cursado",
			Uds: "han cursado",
		},
		Preterite: {
			yo: "hube cursado",
			tú: "hubiste cursado",
			Ud: "hubo cursado",
			nosotros: "hubimos cursado",
			vosotros: "hubisteis cursado",
			Uds: "hubieron cursado",
		},
		Past: {
			yo: "había cursado",
			tú: "habías cursado",
			Ud: "había cursado",
			nosotros: "habíamos cursado",
			vosotros: "habíais cursado",
			Uds: "habían cursado",
		},
		Conditional: {
			yo: "habría cursado",
			tú: "habrías cursado",
			Ud: "habría cursado",
			nosotros: "habríamos cursado",
			vosotros: "habríais cursado",
			Uds: "habrían cursado",
		},
		Future: {
			yo: "habré cursado",
			tú: "habrás cursado",
			Ud: "habrá cursado",
			nosotros: "habremos cursado",
			vosotros: "habréis cursado",
			Uds: "habrán cursado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya cursado",
			tú: "hayas cursado",
			Ud: "haya cursado",
			nosotros: "hayamos cursado",
			vosotros: "hayáis cursado",
			Uds: "hayan cursado",
		},
		Past: {
			yo: "hubiera cursado",
			tú: "hubieras cursado",
			Ud: "hubiera cursado",
			nosotros: "hubiéramos cursado",
			vosotros: "hubierais cursado",
			Uds: "hubieran cursado",
		},
		Future: {
			yo: "hubiere cursado",
			tú: "hubieres cursado",
			Ud: "hubiere cursado",
			nosotros: "hubiéremos cursado",
			vosotros: "hubiereis cursado",
			Uds: "hubieren cursado",
		},
	},
}
