var deambular = {
	Indicative: {
		Present: {
			yo: "deambulo",
			tú: "deambulas",
			Ud: "deambula",
			nosotros: "deambulamos",
			vosotros: "deambuláis",
			Uds: "deambulan",
		},
		Preterite: {
			yo: "deambulé",
			tú: "deambulaste",
			Ud: "deambuló",
			nosotros: "deambulamos",
			vosotros: "deambulasteis",
			Uds: "deambularon",
		},
		Imperfect: {
			yo: "deambulaba",
			tú: "deambulabas",
			Ud: "deambulaba",
			nosotros: "deambulábamos",
			vosotros: "deambulabais",
			Uds: "deambulaban",
		},
		Conditional: {
			yo: "deambularía",
			tú: "deambularías",
			Ud: "deambularía",
			nosotros: "deambularíamos",
			vosotros: "deambularíais",
			Uds: "deambularían",
		},
		Future: {
			yo: "deambularé",
			tú: "deambularás",
			Ud: "deambulará",
			nosotros: "deambularemos",
			vosotros: "deambularéis",
			Uds: "deambularán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "deambule",
			tú: "deambules",
			Ud: "deambule",
			nosotros: "deambulemos",
			vosotros: "deambuléis",
			Uds: "deambulen",
		},
		Imperfect: {
			yo: "deambulara",
			tú: "deambularas",
			Ud: "deambulara",
			nosotros: "deambuláramos",
			vosotros: "deambularais",
			Uds: "deambularan",
		},
		Imperfect2: {
			yo: "deambulase",
			tú: "deambulases",
			Ud: "deambulase",
			nosotros: "deambulásemos",
			vosotros: "deambulaseis",
			Uds: "deambulasen",
		},
		Future: {
			yo: "deambulare",
			tú: "deambulares",
			Ud: "deambulare",
			nosotros: "deambuláremos",
			vosotros: "deambulareis",
			Uds: "deambularen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "deambula",
			Ud: "deambule",
			nosotros: "deambulemos",
			vosotros: "deambulad",
			Uds: "deambulen",
		},
		Negative: {
			tú: "no deambules",
			Ud: "no deambule",
			nosotros: "no deambulemos",
			vosotros: "no deambuléis",
			Uds: "no deambulen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy deambulando",
			tú: "estás deambulando",
			Ud: "está deambulando",
			nosotros: "estamos deambulando",
			vosotros: "estáis deambulando",
			Uds: "están deambulando",
		},
		Preterite: {
			yo: "estuve deambulando",
			tú: "estuviste deambulando",
			Ud: "estuvo deambulando",
			nosotros: "estuvimos deambulando",
			vosotros: "estuvisteis deambulando",
			Uds: "estuvieron deambulando",
		},
		Imperfect: {
			Uds: "estaban deambulando",
			yo: "estaba deambulando",
			tú: "estabas deambulando",
			Ud: "estaba deambulando",
			nosotros: "estábamos deambulando",
			vosotros: "estabais deambulando",
		},
		Conditional: {
			yo: "estaría deambulando",
			tú: "estarías deambulando",
			Ud: "estaría deambulando",
			nosotros: "estaríamos deambulando",
			vosotros: "estaríais deambulando",
			Uds: "estarían deambulando",
		},
		Future: {
			yo: "estaré deambulando",
			tú: "estarás deambulando",
			Ud: "estará deambulando",
			nosotros: "estaremos deambulando",
			vosotros: "estaréis deambulando",
			Uds: "estarán deambulando",
		},
	},
	Perfect: {
		Present: {
			yo: "he deambulado",
			tú: "has deambulado",
			Ud: "ha deambulado",
			nosotros: "hemos deambulado",
			vosotros: "habéis deambulado",
			Uds: "han deambulado",
		},
		Preterite: {
			yo: "hube deambulado",
			tú: "hubiste deambulado",
			Ud: "hubo deambulado",
			nosotros: "hubimos deambulado",
			vosotros: "hubisteis deambulado",
			Uds: "hubieron deambulado",
		},
		Past: {
			yo: "había deambulado",
			tú: "habías deambulado",
			Ud: "había deambulado",
			nosotros: "habíamos deambulado",
			vosotros: "habíais deambulado",
			Uds: "habían deambulado",
		},
		Conditional: {
			yo: "habría deambulado",
			tú: "habrías deambulado",
			Ud: "habría deambulado",
			nosotros: "habríamos deambulado",
			vosotros: "habríais deambulado",
			Uds: "habrían deambulado",
		},
		Future: {
			yo: "habré deambulado",
			tú: "habrás deambulado",
			Ud: "habrá deambulado",
			nosotros: "habremos deambulado",
			vosotros: "habréis deambulado",
			Uds: "habrán deambulado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya deambulado",
			tú: "hayas deambulado",
			Ud: "haya deambulado",
			nosotros: "hayamos deambulado",
			vosotros: "hayáis deambulado",
			Uds: "hayan deambulado",
		},
		Past: {
			yo: "hubiera deambulado",
			tú: "hubieras deambulado",
			Ud: "hubiera deambulado",
			nosotros: "hubiéramos deambulado",
			vosotros: "hubierais deambulado",
			Uds: "hubieran deambulado",
		},
		Future: {
			yo: "hubiere deambulado",
			tú: "hubieres deambulado",
			Ud: "hubiere deambulado",
			nosotros: "hubiéremos deambulado",
			vosotros: "hubiereis deambulado",
			Uds: "hubieren deambulado",
		},
	},
}
