var decomisar = {
	Indicative: {
		Present: {
			yo: "decomiso",
			tú: "decomisas",
			Ud: "decomisa",
			nosotros: "decomisamos",
			vosotros: "decomisáis",
			Uds: "decomisan",
		},
		Preterite: {
			yo: "decomisé",
			tú: "decomisaste",
			Ud: "decomisó",
			nosotros: "decomisamos",
			vosotros: "decomisasteis",
			Uds: "decomisaron",
		},
		Imperfect: {
			yo: "decomisaba",
			tú: "decomisabas",
			Ud: "decomisaba",
			nosotros: "decomisábamos",
			vosotros: "decomisabais",
			Uds: "decomisaban",
		},
		Conditional: {
			yo: "decomisaría",
			tú: "decomisarías",
			Ud: "decomisaría",
			nosotros: "decomisaríamos",
			vosotros: "decomisaríais",
			Uds: "decomisarían",
		},
		Future: {
			yo: "decomisaré",
			tú: "decomisarás",
			Ud: "decomisará",
			nosotros: "decomisaremos",
			vosotros: "decomisaréis",
			Uds: "decomisarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "decomise",
			tú: "decomises",
			Ud: "decomise",
			nosotros: "decomisemos",
			vosotros: "decomiséis",
			Uds: "decomisen",
		},
		Imperfect: {
			yo: "decomisara",
			tú: "decomisaras",
			Ud: "decomisara",
			nosotros: "decomisáramos",
			vosotros: "decomisarais",
			Uds: "decomisaran",
		},
		Imperfect2: {
			yo: "decomisase",
			tú: "decomisases",
			Ud: "decomisase",
			nosotros: "decomisásemos",
			vosotros: "decomisaseis",
			Uds: "decomisasen",
		},
		Future: {
			yo: "decomisare",
			tú: "decomisares",
			Ud: "decomisare",
			nosotros: "decomisáremos",
			vosotros: "decomisareis",
			Uds: "decomisaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "decomisa",
			Ud: "decomise",
			nosotros: "decomisemos",
			vosotros: "decomisad",
			Uds: "decomisen",
		},
		Negative: {
			tú: "no decomises",
			Ud: "no decomise",
			nosotros: "no decomisemos",
			vosotros: "no decomiséis",
			Uds: "no decomisen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy decomisando",
			tú: "estás decomisando",
			Ud: "está decomisando",
			nosotros: "estamos decomisando",
			vosotros: "estáis decomisando",
			Uds: "están decomisando",
		},
		Preterite: {
			yo: "estuve decomisando",
			tú: "estuviste decomisando",
			Ud: "estuvo decomisando",
			nosotros: "estuvimos decomisando",
			vosotros: "estuvisteis decomisando",
			Uds: "estuvieron decomisando",
		},
		Imperfect: {
			Uds: "estaban decomisando",
			yo: "estaba decomisando",
			tú: "estabas decomisando",
			Ud: "estaba decomisando",
			nosotros: "estábamos decomisando",
			vosotros: "estabais decomisando",
		},
		Conditional: {
			yo: "estaría decomisando",
			tú: "estarías decomisando",
			Ud: "estaría decomisando",
			nosotros: "estaríamos decomisando",
			vosotros: "estaríais decomisando",
			Uds: "estarían decomisando",
		},
		Future: {
			yo: "estaré decomisando",
			tú: "estarás decomisando",
			Ud: "estará decomisando",
			nosotros: "estaremos decomisando",
			vosotros: "estaréis decomisando",
			Uds: "estarán decomisando",
		},
	},
	Perfect: {
		Present: {
			yo: "he decomisado",
			tú: "has decomisado",
			Ud: "ha decomisado",
			nosotros: "hemos decomisado",
			vosotros: "habéis decomisado",
			Uds: "han decomisado",
		},
		Preterite: {
			yo: "hube decomisado",
			tú: "hubiste decomisado",
			Ud: "hubo decomisado",
			nosotros: "hubimos decomisado",
			vosotros: "hubisteis decomisado",
			Uds: "hubieron decomisado",
		},
		Past: {
			yo: "había decomisado",
			tú: "habías decomisado",
			Ud: "había decomisado",
			nosotros: "habíamos decomisado",
			vosotros: "habíais decomisado",
			Uds: "habían decomisado",
		},
		Conditional: {
			yo: "habría decomisado",
			tú: "habrías decomisado",
			Ud: "habría decomisado",
			nosotros: "habríamos decomisado",
			vosotros: "habríais decomisado",
			Uds: "habrían decomisado",
		},
		Future: {
			yo: "habré decomisado",
			tú: "habrás decomisado",
			Ud: "habrá decomisado",
			nosotros: "habremos decomisado",
			vosotros: "habréis decomisado",
			Uds: "habrán decomisado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya decomisado",
			tú: "hayas decomisado",
			Ud: "haya decomisado",
			nosotros: "hayamos decomisado",
			vosotros: "hayáis decomisado",
			Uds: "hayan decomisado",
		},
		Past: {
			yo: "hubiera decomisado",
			tú: "hubieras decomisado",
			Ud: "hubiera decomisado",
			nosotros: "hubiéramos decomisado",
			vosotros: "hubierais decomisado",
			Uds: "hubieran decomisado",
		},
		Future: {
			yo: "hubiere decomisado",
			tú: "hubieres decomisado",
			Ud: "hubiere decomisado",
			nosotros: "hubiéremos decomisado",
			vosotros: "hubiereis decomisado",
			Uds: "hubieren decomisado",
		},
	},
}
