var deducir = {
	Indicative: {
		Present: {
			yo: "deduzco",
			tú: "deduces",
			Ud: "deduce",
			nosotros: "deducimos",
			vosotros: "deducís",
			Uds: "deducen",
		},
		Preterite: {
			yo: "deduje",
			tú: "dedujiste",
			Ud: "dedujo",
			nosotros: "dedujimos",
			vosotros: "dedujisteis",
			Uds: "dedujeron",
		},
		Imperfect: {
			yo: "deducía",
			tú: "deducías",
			Ud: "deducía",
			nosotros: "deducíamos",
			vosotros: "deducíais",
			Uds: "deducían",
		},
		Conditional: {
			yo: "deduciría",
			tú: "deducirías",
			Ud: "deduciría",
			nosotros: "deduciríamos",
			vosotros: "deduciríais",
			Uds: "deducirían",
		},
		Future: {
			yo: "deduciré",
			tú: "deducirás",
			Ud: "deducirá",
			nosotros: "deduciremos",
			vosotros: "deduciréis",
			Uds: "deducirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "deduzca",
			tú: "deduzcas",
			Ud: "deduzca",
			nosotros: "deduzcamos",
			vosotros: "deduzcáis",
			Uds: "deduzcan",
		},
		Imperfect: {
			yo: "dedujera",
			tú: "dedujeras",
			Ud: "dedujera",
			nosotros: "dedujéramos",
			vosotros: "dedujerais",
			Uds: "dedujeran",
		},
		Imperfect2: {
			yo: "dedujese",
			tú: "dedujeses",
			Ud: "dedujese",
			nosotros: "dedujésemos",
			vosotros: "dedujeseis",
			Uds: "dedujesen",
		},
		Future: {
			yo: "dedujere",
			tú: "dedujeres",
			Ud: "dedujere",
			nosotros: "dedujéremos",
			vosotros: "dedujereis",
			Uds: "dedujeren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "deduce",
			Ud: "deduzca",
			nosotros: "deduzcamos",
			vosotros: "deducid",
			Uds: "deduzcan",
		},
		Negative: {
			tú: "no deduzcas",
			Ud: "no deduzca",
			nosotros: "no deduzcamos",
			vosotros: "no deduzcáis",
			Uds: "no deduzcan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy deduciendo",
			tú: "estás deduciendo",
			Ud: "está deduciendo",
			nosotros: "estamos deduciendo",
			vosotros: "estáis deduciendo",
			Uds: "están deduciendo",
		},
		Preterite: {
			yo: "estuve deduciendo",
			tú: "estuviste deduciendo",
			Ud: "estuvo deduciendo",
			nosotros: "estuvimos deduciendo",
			vosotros: "estuvisteis deduciendo",
			Uds: "estuvieron deduciendo",
		},
		Imperfect: {
			Uds: "estaban deduciendo",
			yo: "estaba deduciendo",
			tú: "estabas deduciendo",
			Ud: "estaba deduciendo",
			nosotros: "estábamos deduciendo",
			vosotros: "estabais deduciendo",
		},
		Conditional: {
			yo: "estaría deduciendo",
			tú: "estarías deduciendo",
			Ud: "estaría deduciendo",
			nosotros: "estaríamos deduciendo",
			vosotros: "estaríais deduciendo",
			Uds: "estarían deduciendo",
		},
		Future: {
			yo: "estaré deduciendo",
			tú: "estarás deduciendo",
			Ud: "estará deduciendo",
			nosotros: "estaremos deduciendo",
			vosotros: "estaréis deduciendo",
			Uds: "estarán deduciendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he deducido",
			tú: "has deducido",
			Ud: "ha deducido",
			nosotros: "hemos deducido",
			vosotros: "habéis deducido",
			Uds: "han deducido",
		},
		Preterite: {
			yo: "hube deducido",
			tú: "hubiste deducido",
			Ud: "hubo deducido",
			nosotros: "hubimos deducido",
			vosotros: "hubisteis deducido",
			Uds: "hubieron deducido",
		},
		Past: {
			yo: "había deducido",
			tú: "habías deducido",
			Ud: "había deducido",
			nosotros: "habíamos deducido",
			vosotros: "habíais deducido",
			Uds: "habían deducido",
		},
		Conditional: {
			yo: "habría deducido",
			tú: "habrías deducido",
			Ud: "habría deducido",
			nosotros: "habríamos deducido",
			vosotros: "habríais deducido",
			Uds: "habrían deducido",
		},
		Future: {
			yo: "habré deducido",
			tú: "habrás deducido",
			Ud: "habrá deducido",
			nosotros: "habremos deducido",
			vosotros: "habréis deducido",
			Uds: "habrán deducido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya deducido",
			tú: "hayas deducido",
			Ud: "haya deducido",
			nosotros: "hayamos deducido",
			vosotros: "hayáis deducido",
			Uds: "hayan deducido",
		},
		Past: {
			yo: "hubiera deducido",
			tú: "hubieras deducido",
			Ud: "hubiera deducido",
			nosotros: "hubiéramos deducido",
			vosotros: "hubierais deducido",
			Uds: "hubieran deducido",
		},
		Future: {
			yo: "hubiere deducido",
			tú: "hubieres deducido",
			Ud: "hubiere deducido",
			nosotros: "hubiéremos deducido",
			vosotros: "hubiereis deducido",
			Uds: "hubieren deducido",
		},
	},
}
