var degenerar = {
	Indicative: {
		Present: {
			yo: "degenero",
			tú: "degeneras",
			Ud: "degenera",
			nosotros: "degeneramos",
			vosotros: "degeneráis",
			Uds: "degeneran",
		},
		Preterite: {
			yo: "degeneré",
			tú: "degeneraste",
			Ud: "degeneró",
			nosotros: "degeneramos",
			vosotros: "degenerasteis",
			Uds: "degeneraron",
		},
		Imperfect: {
			yo: "degeneraba",
			tú: "degenerabas",
			Ud: "degeneraba",
			nosotros: "degenerábamos",
			vosotros: "degenerabais",
			Uds: "degeneraban",
		},
		Conditional: {
			yo: "degeneraría",
			tú: "degenerarías",
			Ud: "degeneraría",
			nosotros: "degeneraríamos",
			vosotros: "degeneraríais",
			Uds: "degenerarían",
		},
		Future: {
			yo: "degeneraré",
			tú: "degenerarás",
			Ud: "degenerará",
			nosotros: "degeneraremos",
			vosotros: "degeneraréis",
			Uds: "degenerarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "degenere",
			tú: "degeneres",
			Ud: "degenere",
			nosotros: "degeneremos",
			vosotros: "degeneréis",
			Uds: "degeneren",
		},
		Imperfect: {
			yo: "degenerara",
			tú: "degeneraras",
			Ud: "degenerara",
			nosotros: "degeneráramos",
			vosotros: "degenerarais",
			Uds: "degeneraran",
		},
		Imperfect2: {
			yo: "degenerase",
			tú: "degenerases",
			Ud: "degenerase",
			nosotros: "degenerásemos",
			vosotros: "degeneraseis",
			Uds: "degenerasen",
		},
		Future: {
			yo: "degenerare",
			tú: "degenerares",
			Ud: "degenerare",
			nosotros: "degeneráremos",
			vosotros: "degenerareis",
			Uds: "degeneraren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "degenera",
			Ud: "degenere",
			nosotros: "degeneremos",
			vosotros: "degenerad",
			Uds: "degeneren",
		},
		Negative: {
			tú: "no degeneres",
			Ud: "no degenere",
			nosotros: "no degeneremos",
			vosotros: "no degeneréis",
			Uds: "no degeneren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy degenerando",
			tú: "estás degenerando",
			Ud: "está degenerando",
			nosotros: "estamos degenerando",
			vosotros: "estáis degenerando",
			Uds: "están degenerando",
		},
		Preterite: {
			yo: "estuve degenerando",
			tú: "estuviste degenerando",
			Ud: "estuvo degenerando",
			nosotros: "estuvimos degenerando",
			vosotros: "estuvisteis degenerando",
			Uds: "estuvieron degenerando",
		},
		Imperfect: {
			Uds: "estaban degenerando",
			yo: "estaba degenerando",
			tú: "estabas degenerando",
			Ud: "estaba degenerando",
			nosotros: "estábamos degenerando",
			vosotros: "estabais degenerando",
		},
		Conditional: {
			yo: "estaría degenerando",
			tú: "estarías degenerando",
			Ud: "estaría degenerando",
			nosotros: "estaríamos degenerando",
			vosotros: "estaríais degenerando",
			Uds: "estarían degenerando",
		},
		Future: {
			yo: "estaré degenerando",
			tú: "estarás degenerando",
			Ud: "estará degenerando",
			nosotros: "estaremos degenerando",
			vosotros: "estaréis degenerando",
			Uds: "estarán degenerando",
		},
	},
	Perfect: {
		Present: {
			yo: "he degenerado",
			tú: "has degenerado",
			Ud: "ha degenerado",
			nosotros: "hemos degenerado",
			vosotros: "habéis degenerado",
			Uds: "han degenerado",
		},
		Preterite: {
			yo: "hube degenerado",
			tú: "hubiste degenerado",
			Ud: "hubo degenerado",
			nosotros: "hubimos degenerado",
			vosotros: "hubisteis degenerado",
			Uds: "hubieron degenerado",
		},
		Past: {
			yo: "había degenerado",
			tú: "habías degenerado",
			Ud: "había degenerado",
			nosotros: "habíamos degenerado",
			vosotros: "habíais degenerado",
			Uds: "habían degenerado",
		},
		Conditional: {
			yo: "habría degenerado",
			tú: "habrías degenerado",
			Ud: "habría degenerado",
			nosotros: "habríamos degenerado",
			vosotros: "habríais degenerado",
			Uds: "habrían degenerado",
		},
		Future: {
			yo: "habré degenerado",
			tú: "habrás degenerado",
			Ud: "habrá degenerado",
			nosotros: "habremos degenerado",
			vosotros: "habréis degenerado",
			Uds: "habrán degenerado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya degenerado",
			tú: "hayas degenerado",
			Ud: "haya degenerado",
			nosotros: "hayamos degenerado",
			vosotros: "hayáis degenerado",
			Uds: "hayan degenerado",
		},
		Past: {
			yo: "hubiera degenerado",
			tú: "hubieras degenerado",
			Ud: "hubiera degenerado",
			nosotros: "hubiéramos degenerado",
			vosotros: "hubierais degenerado",
			Uds: "hubieran degenerado",
		},
		Future: {
			yo: "hubiere degenerado",
			tú: "hubieres degenerado",
			Ud: "hubiere degenerado",
			nosotros: "hubiéremos degenerado",
			vosotros: "hubiereis degenerado",
			Uds: "hubieren degenerado",
		},
	},
}
