var delatar = {
	Indicative: {
		Present: {
			yo: "delato",
			tú: "delatas",
			Ud: "delata",
			nosotros: "delatamos",
			vosotros: "delatáis",
			Uds: "delatan",
		},
		Preterite: {
			yo: "delaté",
			tú: "delataste",
			Ud: "delató",
			nosotros: "delatamos",
			vosotros: "delatasteis",
			Uds: "delataron",
		},
		Imperfect: {
			yo: "delataba",
			tú: "delatabas",
			Ud: "delataba",
			nosotros: "delatábamos",
			vosotros: "delatabais",
			Uds: "delataban",
		},
		Conditional: {
			yo: "delataría",
			tú: "delatarías",
			Ud: "delataría",
			nosotros: "delataríamos",
			vosotros: "delataríais",
			Uds: "delatarían",
		},
		Future: {
			yo: "delataré",
			tú: "delatarás",
			Ud: "delatará",
			nosotros: "delataremos",
			vosotros: "delataréis",
			Uds: "delatarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "delate",
			tú: "delates",
			Ud: "delate",
			nosotros: "delatemos",
			vosotros: "delatéis",
			Uds: "delaten",
		},
		Imperfect: {
			yo: "delatara",
			tú: "delataras",
			Ud: "delatara",
			nosotros: "delatáramos",
			vosotros: "delatarais",
			Uds: "delataran",
		},
		Imperfect2: {
			yo: "delatase",
			tú: "delatases",
			Ud: "delatase",
			nosotros: "delatásemos",
			vosotros: "delataseis",
			Uds: "delatasen",
		},
		Future: {
			yo: "delatare",
			tú: "delatares",
			Ud: "delatare",
			nosotros: "delatáremos",
			vosotros: "delatareis",
			Uds: "delataren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "delata",
			Ud: "delate",
			nosotros: "delatemos",
			vosotros: "delatad",
			Uds: "delaten",
		},
		Negative: {
			tú: "no delates",
			Ud: "no delate",
			nosotros: "no delatemos",
			vosotros: "no delatéis",
			Uds: "no delaten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy delatando",
			tú: "estás delatando",
			Ud: "está delatando",
			nosotros: "estamos delatando",
			vosotros: "estáis delatando",
			Uds: "están delatando",
		},
		Preterite: {
			yo: "estuve delatando",
			tú: "estuviste delatando",
			Ud: "estuvo delatando",
			nosotros: "estuvimos delatando",
			vosotros: "estuvisteis delatando",
			Uds: "estuvieron delatando",
		},
		Imperfect: {
			Uds: "estaban delatando",
			yo: "estaba delatando",
			tú: "estabas delatando",
			Ud: "estaba delatando",
			nosotros: "estábamos delatando",
			vosotros: "estabais delatando",
		},
		Conditional: {
			yo: "estaría delatando",
			tú: "estarías delatando",
			Ud: "estaría delatando",
			nosotros: "estaríamos delatando",
			vosotros: "estaríais delatando",
			Uds: "estarían delatando",
		},
		Future: {
			yo: "estaré delatando",
			tú: "estarás delatando",
			Ud: "estará delatando",
			nosotros: "estaremos delatando",
			vosotros: "estaréis delatando",
			Uds: "estarán delatando",
		},
	},
	Perfect: {
		Present: {
			yo: "he delatado",
			tú: "has delatado",
			Ud: "ha delatado",
			nosotros: "hemos delatado",
			vosotros: "habéis delatado",
			Uds: "han delatado",
		},
		Preterite: {
			yo: "hube delatado",
			tú: "hubiste delatado",
			Ud: "hubo delatado",
			nosotros: "hubimos delatado",
			vosotros: "hubisteis delatado",
			Uds: "hubieron delatado",
		},
		Past: {
			yo: "había delatado",
			tú: "habías delatado",
			Ud: "había delatado",
			nosotros: "habíamos delatado",
			vosotros: "habíais delatado",
			Uds: "habían delatado",
		},
		Conditional: {
			yo: "habría delatado",
			tú: "habrías delatado",
			Ud: "habría delatado",
			nosotros: "habríamos delatado",
			vosotros: "habríais delatado",
			Uds: "habrían delatado",
		},
		Future: {
			yo: "habré delatado",
			tú: "habrás delatado",
			Ud: "habrá delatado",
			nosotros: "habremos delatado",
			vosotros: "habréis delatado",
			Uds: "habrán delatado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya delatado",
			tú: "hayas delatado",
			Ud: "haya delatado",
			nosotros: "hayamos delatado",
			vosotros: "hayáis delatado",
			Uds: "hayan delatado",
		},
		Past: {
			yo: "hubiera delatado",
			tú: "hubieras delatado",
			Ud: "hubiera delatado",
			nosotros: "hubiéramos delatado",
			vosotros: "hubierais delatado",
			Uds: "hubieran delatado",
		},
		Future: {
			yo: "hubiere delatado",
			tú: "hubieres delatado",
			Ud: "hubiere delatado",
			nosotros: "hubiéremos delatado",
			vosotros: "hubiereis delatado",
			Uds: "hubieren delatado",
		},
	},
}
