var delegar = {
	Indicative: {
		Present: {
			yo: "delego",
			tú: "delegas",
			Ud: "delega",
			nosotros: "delegamos",
			vosotros: "delegáis",
			Uds: "delegan",
		},
		Preterite: {
			yo: "delegué",
			tú: "delegaste",
			Ud: "delegó",
			nosotros: "delegamos",
			vosotros: "delegasteis",
			Uds: "delegaron",
		},
		Imperfect: {
			yo: "delegaba",
			tú: "delegabas",
			Ud: "delegaba",
			nosotros: "delegábamos",
			vosotros: "delegabais",
			Uds: "delegaban",
		},
		Conditional: {
			yo: "delegaría",
			tú: "delegarías",
			Ud: "delegaría",
			nosotros: "delegaríamos",
			vosotros: "delegaríais",
			Uds: "delegarían",
		},
		Future: {
			yo: "delegaré",
			tú: "delegarás",
			Ud: "delegará",
			nosotros: "delegaremos",
			vosotros: "delegaréis",
			Uds: "delegarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "delegue",
			tú: "delegues",
			Ud: "delegue",
			nosotros: "deleguemos",
			vosotros: "deleguéis",
			Uds: "deleguen",
		},
		Imperfect: {
			yo: "delegara",
			tú: "delegaras",
			Ud: "delegara",
			nosotros: "delegáramos",
			vosotros: "delegarais",
			Uds: "delegaran",
		},
		Imperfect2: {
			yo: "delegase",
			tú: "delegases",
			Ud: "delegase",
			nosotros: "delegásemos",
			vosotros: "delegaseis",
			Uds: "delegasen",
		},
		Future: {
			yo: "delegare",
			tú: "delegares",
			Ud: "delegare",
			nosotros: "delegáremos",
			vosotros: "delegareis",
			Uds: "delegaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "delega",
			Ud: "delegue",
			nosotros: "deleguemos",
			vosotros: "delegad",
			Uds: "deleguen",
		},
		Negative: {
			tú: "no delegues",
			Ud: "no delegue",
			nosotros: "no deleguemos",
			vosotros: "no deleguéis",
			Uds: "no deleguen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy delegando",
			tú: "estás delegando",
			Ud: "está delegando",
			nosotros: "estamos delegando",
			vosotros: "estáis delegando",
			Uds: "están delegando",
		},
		Preterite: {
			yo: "estuve delegando",
			tú: "estuviste delegando",
			Ud: "estuvo delegando",
			nosotros: "estuvimos delegando",
			vosotros: "estuvisteis delegando",
			Uds: "estuvieron delegando",
		},
		Imperfect: {
			Uds: "estaban delegando",
			yo: "estaba delegando",
			tú: "estabas delegando",
			Ud: "estaba delegando",
			nosotros: "estábamos delegando",
			vosotros: "estabais delegando",
		},
		Conditional: {
			yo: "estaría delegando",
			tú: "estarías delegando",
			Ud: "estaría delegando",
			nosotros: "estaríamos delegando",
			vosotros: "estaríais delegando",
			Uds: "estarían delegando",
		},
		Future: {
			yo: "estaré delegando",
			tú: "estarás delegando",
			Ud: "estará delegando",
			nosotros: "estaremos delegando",
			vosotros: "estaréis delegando",
			Uds: "estarán delegando",
		},
	},
	Perfect: {
		Present: {
			yo: "he delegado",
			tú: "has delegado",
			Ud: "ha delegado",
			nosotros: "hemos delegado",
			vosotros: "habéis delegado",
			Uds: "han delegado",
		},
		Preterite: {
			yo: "hube delegado",
			tú: "hubiste delegado",
			Ud: "hubo delegado",
			nosotros: "hubimos delegado",
			vosotros: "hubisteis delegado",
			Uds: "hubieron delegado",
		},
		Past: {
			yo: "había delegado",
			tú: "habías delegado",
			Ud: "había delegado",
			nosotros: "habíamos delegado",
			vosotros: "habíais delegado",
			Uds: "habían delegado",
		},
		Conditional: {
			yo: "habría delegado",
			tú: "habrías delegado",
			Ud: "habría delegado",
			nosotros: "habríamos delegado",
			vosotros: "habríais delegado",
			Uds: "habrían delegado",
		},
		Future: {
			yo: "habré delegado",
			tú: "habrás delegado",
			Ud: "habrá delegado",
			nosotros: "habremos delegado",
			vosotros: "habréis delegado",
			Uds: "habrán delegado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya delegado",
			tú: "hayas delegado",
			Ud: "haya delegado",
			nosotros: "hayamos delegado",
			vosotros: "hayáis delegado",
			Uds: "hayan delegado",
		},
		Past: {
			yo: "hubiera delegado",
			tú: "hubieras delegado",
			Ud: "hubiera delegado",
			nosotros: "hubiéramos delegado",
			vosotros: "hubierais delegado",
			Uds: "hubieran delegado",
		},
		Future: {
			yo: "hubiere delegado",
			tú: "hubieres delegado",
			Ud: "hubiere delegado",
			nosotros: "hubiéremos delegado",
			vosotros: "hubiereis delegado",
			Uds: "hubieren delegado",
		},
	},
}
