var delimitar = {
	Indicative: {
		Present: {
			yo: "delimito",
			tú: "delimitas",
			Ud: "delimita",
			nosotros: "delimitamos",
			vosotros: "delimitáis",
			Uds: "delimitan",
		},
		Preterite: {
			yo: "delimité",
			tú: "delimitaste",
			Ud: "delimitó",
			nosotros: "delimitamos",
			vosotros: "delimitasteis",
			Uds: "delimitaron",
		},
		Imperfect: {
			yo: "delimitaba",
			tú: "delimitabas",
			Ud: "delimitaba",
			nosotros: "delimitábamos",
			vosotros: "delimitabais",
			Uds: "delimitaban",
		},
		Conditional: {
			yo: "delimitaría",
			tú: "delimitarías",
			Ud: "delimitaría",
			nosotros: "delimitaríamos",
			vosotros: "delimitaríais",
			Uds: "delimitarían",
		},
		Future: {
			yo: "delimitaré",
			tú: "delimitarás",
			Ud: "delimitará",
			nosotros: "delimitaremos",
			vosotros: "delimitaréis",
			Uds: "delimitarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "delimite",
			tú: "delimites",
			Ud: "delimite",
			nosotros: "delimitemos",
			vosotros: "delimitéis",
			Uds: "delimiten",
		},
		Imperfect: {
			yo: "delimitara",
			tú: "delimitaras",
			Ud: "delimitara",
			nosotros: "delimitáramos",
			vosotros: "delimitarais",
			Uds: "delimitaran",
		},
		Imperfect2: {
			yo: "delimitase",
			tú: "delimitases",
			Ud: "delimitase",
			nosotros: "delimitásemos",
			vosotros: "delimitaseis",
			Uds: "delimitasen",
		},
		Future: {
			yo: "delimitare",
			tú: "delimitares",
			Ud: "delimitare",
			nosotros: "delimitáremos",
			vosotros: "delimitareis",
			Uds: "delimitaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "delimita",
			Ud: "delimite",
			nosotros: "delimitemos",
			vosotros: "delimitad",
			Uds: "delimiten",
		},
		Negative: {
			tú: "no delimites",
			Ud: "no delimite",
			nosotros: "no delimitemos",
			vosotros: "no delimitéis",
			Uds: "no delimiten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy delimitando",
			tú: "estás delimitando",
			Ud: "está delimitando",
			nosotros: "estamos delimitando",
			vosotros: "estáis delimitando",
			Uds: "están delimitando",
		},
		Preterite: {
			yo: "estuve delimitando",
			tú: "estuviste delimitando",
			Ud: "estuvo delimitando",
			nosotros: "estuvimos delimitando",
			vosotros: "estuvisteis delimitando",
			Uds: "estuvieron delimitando",
		},
		Imperfect: {
			Uds: "estaban delimitando",
			yo: "estaba delimitando",
			tú: "estabas delimitando",
			Ud: "estaba delimitando",
			nosotros: "estábamos delimitando",
			vosotros: "estabais delimitando",
		},
		Conditional: {
			yo: "estaría delimitando",
			tú: "estarías delimitando",
			Ud: "estaría delimitando",
			nosotros: "estaríamos delimitando",
			vosotros: "estaríais delimitando",
			Uds: "estarían delimitando",
		},
		Future: {
			yo: "estaré delimitando",
			tú: "estarás delimitando",
			Ud: "estará delimitando",
			nosotros: "estaremos delimitando",
			vosotros: "estaréis delimitando",
			Uds: "estarán delimitando",
		},
	},
	Perfect: {
		Present: {
			yo: "he delimitado",
			tú: "has delimitado",
			Ud: "ha delimitado",
			nosotros: "hemos delimitado",
			vosotros: "habéis delimitado",
			Uds: "han delimitado",
		},
		Preterite: {
			yo: "hube delimitado",
			tú: "hubiste delimitado",
			Ud: "hubo delimitado",
			nosotros: "hubimos delimitado",
			vosotros: "hubisteis delimitado",
			Uds: "hubieron delimitado",
		},
		Past: {
			yo: "había delimitado",
			tú: "habías delimitado",
			Ud: "había delimitado",
			nosotros: "habíamos delimitado",
			vosotros: "habíais delimitado",
			Uds: "habían delimitado",
		},
		Conditional: {
			yo: "habría delimitado",
			tú: "habrías delimitado",
			Ud: "habría delimitado",
			nosotros: "habríamos delimitado",
			vosotros: "habríais delimitado",
			Uds: "habrían delimitado",
		},
		Future: {
			yo: "habré delimitado",
			tú: "habrás delimitado",
			Ud: "habrá delimitado",
			nosotros: "habremos delimitado",
			vosotros: "habréis delimitado",
			Uds: "habrán delimitado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya delimitado",
			tú: "hayas delimitado",
			Ud: "haya delimitado",
			nosotros: "hayamos delimitado",
			vosotros: "hayáis delimitado",
			Uds: "hayan delimitado",
		},
		Past: {
			yo: "hubiera delimitado",
			tú: "hubieras delimitado",
			Ud: "hubiera delimitado",
			nosotros: "hubiéramos delimitado",
			vosotros: "hubierais delimitado",
			Uds: "hubieran delimitado",
		},
		Future: {
			yo: "hubiere delimitado",
			tú: "hubieres delimitado",
			Ud: "hubiere delimitado",
			nosotros: "hubiéremos delimitado",
			vosotros: "hubiereis delimitado",
			Uds: "hubieren delimitado",
		},
	},
}
