var deliberar = {
	Indicative: {
		Present: {
			yo: "delibero",
			tú: "deliberas",
			Ud: "delibera",
			nosotros: "deliberamos",
			vosotros: "deliberáis",
			Uds: "deliberan",
		},
		Preterite: {
			yo: "deliberé",
			tú: "deliberaste",
			Ud: "deliberó",
			nosotros: "deliberamos",
			vosotros: "deliberasteis",
			Uds: "deliberaron",
		},
		Imperfect: {
			yo: "deliberaba",
			tú: "deliberabas",
			Ud: "deliberaba",
			nosotros: "deliberábamos",
			vosotros: "deliberabais",
			Uds: "deliberaban",
		},
		Conditional: {
			yo: "deliberaría",
			tú: "deliberarías",
			Ud: "deliberaría",
			nosotros: "deliberaríamos",
			vosotros: "deliberaríais",
			Uds: "deliberarían",
		},
		Future: {
			yo: "deliberaré",
			tú: "deliberarás",
			Ud: "deliberará",
			nosotros: "deliberaremos",
			vosotros: "deliberaréis",
			Uds: "deliberarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "delibere",
			tú: "deliberes",
			Ud: "delibere",
			nosotros: "deliberemos",
			vosotros: "deliberéis",
			Uds: "deliberen",
		},
		Imperfect: {
			yo: "deliberara",
			tú: "deliberaras",
			Ud: "deliberara",
			nosotros: "deliberáramos",
			vosotros: "deliberarais",
			Uds: "deliberaran",
		},
		Imperfect2: {
			yo: "deliberase",
			tú: "deliberases",
			Ud: "deliberase",
			nosotros: "deliberásemos",
			vosotros: "deliberaseis",
			Uds: "deliberasen",
		},
		Future: {
			yo: "deliberare",
			tú: "deliberares",
			Ud: "deliberare",
			nosotros: "deliberáremos",
			vosotros: "deliberareis",
			Uds: "deliberaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "delibera",
			Ud: "delibere",
			nosotros: "deliberemos",
			vosotros: "deliberad",
			Uds: "deliberen",
		},
		Negative: {
			tú: "no deliberes",
			Ud: "no delibere",
			nosotros: "no deliberemos",
			vosotros: "no deliberéis",
			Uds: "no deliberen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy deliberando",
			tú: "estás deliberando",
			Ud: "está deliberando",
			nosotros: "estamos deliberando",
			vosotros: "estáis deliberando",
			Uds: "están deliberando",
		},
		Preterite: {
			yo: "estuve deliberando",
			tú: "estuviste deliberando",
			Ud: "estuvo deliberando",
			nosotros: "estuvimos deliberando",
			vosotros: "estuvisteis deliberando",
			Uds: "estuvieron deliberando",
		},
		Imperfect: {
			Uds: "estaban deliberando",
			yo: "estaba deliberando",
			tú: "estabas deliberando",
			Ud: "estaba deliberando",
			nosotros: "estábamos deliberando",
			vosotros: "estabais deliberando",
		},
		Conditional: {
			yo: "estaría deliberando",
			tú: "estarías deliberando",
			Ud: "estaría deliberando",
			nosotros: "estaríamos deliberando",
			vosotros: "estaríais deliberando",
			Uds: "estarían deliberando",
		},
		Future: {
			yo: "estaré deliberando",
			tú: "estarás deliberando",
			Ud: "estará deliberando",
			nosotros: "estaremos deliberando",
			vosotros: "estaréis deliberando",
			Uds: "estarán deliberando",
		},
	},
	Perfect: {
		Present: {
			yo: "he deliberado",
			tú: "has deliberado",
			Ud: "ha deliberado",
			nosotros: "hemos deliberado",
			vosotros: "habéis deliberado",
			Uds: "han deliberado",
		},
		Preterite: {
			yo: "hube deliberado",
			tú: "hubiste deliberado",
			Ud: "hubo deliberado",
			nosotros: "hubimos deliberado",
			vosotros: "hubisteis deliberado",
			Uds: "hubieron deliberado",
		},
		Past: {
			yo: "había deliberado",
			tú: "habías deliberado",
			Ud: "había deliberado",
			nosotros: "habíamos deliberado",
			vosotros: "habíais deliberado",
			Uds: "habían deliberado",
		},
		Conditional: {
			yo: "habría deliberado",
			tú: "habrías deliberado",
			Ud: "habría deliberado",
			nosotros: "habríamos deliberado",
			vosotros: "habríais deliberado",
			Uds: "habrían deliberado",
		},
		Future: {
			yo: "habré deliberado",
			tú: "habrás deliberado",
			Ud: "habrá deliberado",
			nosotros: "habremos deliberado",
			vosotros: "habréis deliberado",
			Uds: "habrán deliberado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya deliberado",
			tú: "hayas deliberado",
			Ud: "haya deliberado",
			nosotros: "hayamos deliberado",
			vosotros: "hayáis deliberado",
			Uds: "hayan deliberado",
		},
		Past: {
			yo: "hubiera deliberado",
			tú: "hubieras deliberado",
			Ud: "hubiera deliberado",
			nosotros: "hubiéramos deliberado",
			vosotros: "hubierais deliberado",
			Uds: "hubieran deliberado",
		},
		Future: {
			yo: "hubiere deliberado",
			tú: "hubieres deliberado",
			Ud: "hubiere deliberado",
			nosotros: "hubiéremos deliberado",
			vosotros: "hubiereis deliberado",
			Uds: "hubieren deliberado",
		},
	},
}
