var demandar = {
	Indicative: {
		Present: {
			yo: "demando",
			tú: "demandas",
			Ud: "demanda",
			nosotros: "demandamos",
			vosotros: "demandáis",
			Uds: "demandan",
		},
		Preterite: {
			yo: "demandé",
			tú: "demandaste",
			Ud: "demandó",
			nosotros: "demandamos",
			vosotros: "demandasteis",
			Uds: "demandaron",
		},
		Imperfect: {
			yo: "demandaba",
			tú: "demandabas",
			Ud: "demandaba",
			nosotros: "demandábamos",
			vosotros: "demandabais",
			Uds: "demandaban",
		},
		Conditional: {
			yo: "demandaría",
			tú: "demandarías",
			Ud: "demandaría",
			nosotros: "demandaríamos",
			vosotros: "demandaríais",
			Uds: "demandarían",
		},
		Future: {
			yo: "demandaré",
			tú: "demandarás",
			Ud: "demandará",
			nosotros: "demandaremos",
			vosotros: "demandaréis",
			Uds: "demandarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "demande",
			tú: "demandes",
			Ud: "demande",
			nosotros: "demandemos",
			vosotros: "demandéis",
			Uds: "demanden",
		},
		Imperfect: {
			yo: "demandara",
			tú: "demandaras",
			Ud: "demandara",
			nosotros: "demandáramos",
			vosotros: "demandarais",
			Uds: "demandaran",
		},
		Imperfect2: {
			yo: "demandase",
			tú: "demandases",
			Ud: "demandase",
			nosotros: "demandásemos",
			vosotros: "demandaseis",
			Uds: "demandasen",
		},
		Future: {
			yo: "demandare",
			tú: "demandares",
			Ud: "demandare",
			nosotros: "demandáremos",
			vosotros: "demandareis",
			Uds: "demandaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "demanda",
			Ud: "demande",
			nosotros: "demandemos",
			vosotros: "demandad",
			Uds: "demanden",
		},
		Negative: {
			tú: "no demandes",
			Ud: "no demande",
			nosotros: "no demandemos",
			vosotros: "no demandéis",
			Uds: "no demanden",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy demandando",
			tú: "estás demandando",
			Ud: "está demandando",
			nosotros: "estamos demandando",
			vosotros: "estáis demandando",
			Uds: "están demandando",
		},
		Preterite: {
			yo: "estuve demandando",
			tú: "estuviste demandando",
			Ud: "estuvo demandando",
			nosotros: "estuvimos demandando",
			vosotros: "estuvisteis demandando",
			Uds: "estuvieron demandando",
		},
		Imperfect: {
			Uds: "estaban demandando",
			yo: "estaba demandando",
			tú: "estabas demandando",
			Ud: "estaba demandando",
			nosotros: "estábamos demandando",
			vosotros: "estabais demandando",
		},
		Conditional: {
			yo: "estaría demandando",
			tú: "estarías demandando",
			Ud: "estaría demandando",
			nosotros: "estaríamos demandando",
			vosotros: "estaríais demandando",
			Uds: "estarían demandando",
		},
		Future: {
			yo: "estaré demandando",
			tú: "estarás demandando",
			Ud: "estará demandando",
			nosotros: "estaremos demandando",
			vosotros: "estaréis demandando",
			Uds: "estarán demandando",
		},
	},
	Perfect: {
		Present: {
			yo: "he demandado",
			tú: "has demandado",
			Ud: "ha demandado",
			nosotros: "hemos demandado",
			vosotros: "habéis demandado",
			Uds: "han demandado",
		},
		Preterite: {
			yo: "hube demandado",
			tú: "hubiste demandado",
			Ud: "hubo demandado",
			nosotros: "hubimos demandado",
			vosotros: "hubisteis demandado",
			Uds: "hubieron demandado",
		},
		Past: {
			yo: "había demandado",
			tú: "habías demandado",
			Ud: "había demandado",
			nosotros: "habíamos demandado",
			vosotros: "habíais demandado",
			Uds: "habían demandado",
		},
		Conditional: {
			yo: "habría demandado",
			tú: "habrías demandado",
			Ud: "habría demandado",
			nosotros: "habríamos demandado",
			vosotros: "habríais demandado",
			Uds: "habrían demandado",
		},
		Future: {
			yo: "habré demandado",
			tú: "habrás demandado",
			Ud: "habrá demandado",
			nosotros: "habremos demandado",
			vosotros: "habréis demandado",
			Uds: "habrán demandado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya demandado",
			tú: "hayas demandado",
			Ud: "haya demandado",
			nosotros: "hayamos demandado",
			vosotros: "hayáis demandado",
			Uds: "hayan demandado",
		},
		Past: {
			yo: "hubiera demandado",
			tú: "hubieras demandado",
			Ud: "hubiera demandado",
			nosotros: "hubiéramos demandado",
			vosotros: "hubierais demandado",
			Uds: "hubieran demandado",
		},
		Future: {
			yo: "hubiere demandado",
			tú: "hubieres demandado",
			Ud: "hubiere demandado",
			nosotros: "hubiéremos demandado",
			vosotros: "hubiereis demandado",
			Uds: "hubieren demandado",
		},
	},
}
