var denominar = {
	Indicative: {
		Present: {
			yo: "denomino",
			tú: "denominas",
			Ud: "denomina",
			nosotros: "denominamos",
			vosotros: "denomináis",
			Uds: "denominan",
		},
		Preterite: {
			yo: "denominé",
			tú: "denominaste",
			Ud: "denominó",
			nosotros: "denominamos",
			vosotros: "denominasteis",
			Uds: "denominaron",
		},
		Imperfect: {
			yo: "denominaba",
			tú: "denominabas",
			Ud: "denominaba",
			nosotros: "denominábamos",
			vosotros: "denominabais",
			Uds: "denominaban",
		},
		Conditional: {
			yo: "denominaría",
			tú: "denominarías",
			Ud: "denominaría",
			nosotros: "denominaríamos",
			vosotros: "denominaríais",
			Uds: "denominarían",
		},
		Future: {
			yo: "denominaré",
			tú: "denominarás",
			Ud: "denominará",
			nosotros: "denominaremos",
			vosotros: "denominaréis",
			Uds: "denominarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "denomine",
			tú: "denomines",
			Ud: "denomine",
			nosotros: "denominemos",
			vosotros: "denominéis",
			Uds: "denominen",
		},
		Imperfect: {
			yo: "denominara",
			tú: "denominaras",
			Ud: "denominara",
			nosotros: "denomináramos",
			vosotros: "denominarais",
			Uds: "denominaran",
		},
		Imperfect2: {
			yo: "denominase",
			tú: "denominases",
			Ud: "denominase",
			nosotros: "denominásemos",
			vosotros: "denominaseis",
			Uds: "denominasen",
		},
		Future: {
			yo: "denominare",
			tú: "denominares",
			Ud: "denominare",
			nosotros: "denomináremos",
			vosotros: "denominareis",
			Uds: "denominaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "denomina",
			Ud: "denomine",
			nosotros: "denominemos",
			vosotros: "denominad",
			Uds: "denominen",
		},
		Negative: {
			tú: "no denomines",
			Ud: "no denomine",
			nosotros: "no denominemos",
			vosotros: "no denominéis",
			Uds: "no denominen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy denominando",
			tú: "estás denominando",
			Ud: "está denominando",
			nosotros: "estamos denominando",
			vosotros: "estáis denominando",
			Uds: "están denominando",
		},
		Preterite: {
			yo: "estuve denominando",
			tú: "estuviste denominando",
			Ud: "estuvo denominando",
			nosotros: "estuvimos denominando",
			vosotros: "estuvisteis denominando",
			Uds: "estuvieron denominando",
		},
		Imperfect: {
			Uds: "estaban denominando",
			yo: "estaba denominando",
			tú: "estabas denominando",
			Ud: "estaba denominando",
			nosotros: "estábamos denominando",
			vosotros: "estabais denominando",
		},
		Conditional: {
			yo: "estaría denominando",
			tú: "estarías denominando",
			Ud: "estaría denominando",
			nosotros: "estaríamos denominando",
			vosotros: "estaríais denominando",
			Uds: "estarían denominando",
		},
		Future: {
			yo: "estaré denominando",
			tú: "estarás denominando",
			Ud: "estará denominando",
			nosotros: "estaremos denominando",
			vosotros: "estaréis denominando",
			Uds: "estarán denominando",
		},
	},
	Perfect: {
		Present: {
			yo: "he denominado",
			tú: "has denominado",
			Ud: "ha denominado",
			nosotros: "hemos denominado",
			vosotros: "habéis denominado",
			Uds: "han denominado",
		},
		Preterite: {
			yo: "hube denominado",
			tú: "hubiste denominado",
			Ud: "hubo denominado",
			nosotros: "hubimos denominado",
			vosotros: "hubisteis denominado",
			Uds: "hubieron denominado",
		},
		Past: {
			yo: "había denominado",
			tú: "habías denominado",
			Ud: "había denominado",
			nosotros: "habíamos denominado",
			vosotros: "habíais denominado",
			Uds: "habían denominado",
		},
		Conditional: {
			yo: "habría denominado",
			tú: "habrías denominado",
			Ud: "habría denominado",
			nosotros: "habríamos denominado",
			vosotros: "habríais denominado",
			Uds: "habrían denominado",
		},
		Future: {
			yo: "habré denominado",
			tú: "habrás denominado",
			Ud: "habrá denominado",
			nosotros: "habremos denominado",
			vosotros: "habréis denominado",
			Uds: "habrán denominado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya denominado",
			tú: "hayas denominado",
			Ud: "haya denominado",
			nosotros: "hayamos denominado",
			vosotros: "hayáis denominado",
			Uds: "hayan denominado",
		},
		Past: {
			yo: "hubiera denominado",
			tú: "hubieras denominado",
			Ud: "hubiera denominado",
			nosotros: "hubiéramos denominado",
			vosotros: "hubierais denominado",
			Uds: "hubieran denominado",
		},
		Future: {
			yo: "hubiere denominado",
			tú: "hubieres denominado",
			Ud: "hubiere denominado",
			nosotros: "hubiéremos denominado",
			vosotros: "hubiereis denominado",
			Uds: "hubieren denominado",
		},
	},
}
