var deponer = {
	Indicative: {
		Present: {
			yo: "depongo",
			tú: "depones",
			Ud: "depone",
			nosotros: "deponemos",
			vosotros: "deponéis",
			Uds: "deponen",
		},
		Preterite: {
			yo: "depuse",
			tú: "depusiste",
			Ud: "depuso",
			nosotros: "depusimos",
			vosotros: "depusisteis",
			Uds: "depusieron",
		},
		Imperfect: {
			yo: "deponía",
			tú: "deponías",
			Ud: "deponía",
			nosotros: "deponíamos",
			vosotros: "deponíais",
			Uds: "deponían",
		},
		Conditional: {
			yo: "depondría",
			tú: "depondrías",
			Ud: "depondría",
			nosotros: "depondríamos",
			vosotros: "depondríais",
			Uds: "depondrían",
		},
		Future: {
			yo: "depondré",
			tú: "depondrás",
			Ud: "depondrá",
			nosotros: "depondremos",
			vosotros: "depondréis",
			Uds: "depondrán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "deponga",
			tú: "depongas",
			Ud: "deponga",
			nosotros: "depongamos",
			vosotros: "depongáis",
			Uds: "depongan",
		},
		Imperfect: {
			yo: "depusiera",
			tú: "depusieras",
			Ud: "depusiera",
			nosotros: "depusiéramos",
			vosotros: "depusierais",
			Uds: "depusieran",
		},
		Imperfect2: {
			yo: "depusiese",
			tú: "depusieses",
			Ud: "depusiese",
			nosotros: "depusiésemos",
			vosotros: "depusieseis",
			Uds: "depusiesen",
		},
		Future: {
			yo: "depusiere",
			tú: "depusieres",
			Ud: "depusiere",
			nosotros: "depusiéremos",
			vosotros: "depusiereis",
			Uds: "depusieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "depón",
			Ud: "deponga",
			nosotros: "depongamos",
			vosotros: "deponed",
			Uds: "depongan",
		},
		Negative: {
			tú: "no depongas",
			Ud: "no deponga",
			nosotros: "no depongamos",
			vosotros: "no depongáis",
			Uds: "no depongan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy deponiendo",
			tú: "estás deponiendo",
			Ud: "está deponiendo",
			nosotros: "estamos deponiendo",
			vosotros: "estáis deponiendo",
			Uds: "están deponiendo",
		},
		Preterite: {
			yo: "estuve deponiendo",
			tú: "estuviste deponiendo",
			Ud: "estuvo deponiendo",
			nosotros: "estuvimos deponiendo",
			vosotros: "estuvisteis deponiendo",
			Uds: "estuvieron deponiendo",
		},
		Imperfect: {
			Uds: "estaban deponiendo",
			yo: "estaba deponiendo",
			tú: "estabas deponiendo",
			Ud: "estaba deponiendo",
			nosotros: "estábamos deponiendo",
			vosotros: "estabais deponiendo",
		},
		Conditional: {
			yo: "estaría deponiendo",
			tú: "estarías deponiendo",
			Ud: "estaría deponiendo",
			nosotros: "estaríamos deponiendo",
			vosotros: "estaríais deponiendo",
			Uds: "estarían deponiendo",
		},
		Future: {
			yo: "estaré deponiendo",
			tú: "estarás deponiendo",
			Ud: "estará deponiendo",
			nosotros: "estaremos deponiendo",
			vosotros: "estaréis deponiendo",
			Uds: "estarán deponiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he depuesto",
			tú: "has depuesto",
			Ud: "ha depuesto",
			nosotros: "hemos depuesto",
			vosotros: "habéis depuesto",
			Uds: "han depuesto",
		},
		Preterite: {
			yo: "hube depuesto",
			tú: "hubiste depuesto",
			Ud: "hubo depuesto",
			nosotros: "hubimos depuesto",
			vosotros: "hubisteis depuesto",
			Uds: "hubieron depuesto",
		},
		Past: {
			yo: "había depuesto",
			tú: "habías depuesto",
			Ud: "había depuesto",
			nosotros: "habíamos depuesto",
			vosotros: "habíais depuesto",
			Uds: "habían depuesto",
		},
		Conditional: {
			yo: "habría depuesto",
			tú: "habrías depuesto",
			Ud: "habría depuesto",
			nosotros: "habríamos depuesto",
			vosotros: "habríais depuesto",
			Uds: "habrían depuesto",
		},
		Future: {
			yo: "habré depuesto",
			tú: "habrás depuesto",
			Ud: "habrá depuesto",
			nosotros: "habremos depuesto",
			vosotros: "habréis depuesto",
			Uds: "habrán depuesto",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya depuesto",
			tú: "hayas depuesto",
			Ud: "haya depuesto",
			nosotros: "hayamos depuesto",
			vosotros: "hayáis depuesto",
			Uds: "hayan depuesto",
		},
		Past: {
			yo: "hubiera depuesto",
			tú: "hubieras depuesto",
			Ud: "hubiera depuesto",
			nosotros: "hubiéramos depuesto",
			vosotros: "hubierais depuesto",
			Uds: "hubieran depuesto",
		},
		Future: {
			yo: "hubiere depuesto",
			tú: "hubieres depuesto",
			Ud: "hubiere depuesto",
			nosotros: "hubiéremos depuesto",
			vosotros: "hubiereis depuesto",
			Uds: "hubieren depuesto",
		},
	},
}
