var depositar = {
	Indicative: {
		Present: {
			yo: "deposito",
			tú: "depositas",
			Ud: "deposita",
			nosotros: "depositamos",
			vosotros: "depositáis",
			Uds: "depositan",
		},
		Preterite: {
			yo: "deposité",
			tú: "depositaste",
			Ud: "depositó",
			nosotros: "depositamos",
			vosotros: "depositasteis",
			Uds: "depositaron",
		},
		Imperfect: {
			yo: "depositaba",
			tú: "depositabas",
			Ud: "depositaba",
			nosotros: "depositábamos",
			vosotros: "depositabais",
			Uds: "depositaban",
		},
		Conditional: {
			yo: "depositaría",
			tú: "depositarías",
			Ud: "depositaría",
			nosotros: "depositaríamos",
			vosotros: "depositaríais",
			Uds: "depositarían",
		},
		Future: {
			yo: "depositaré",
			tú: "depositarás",
			Ud: "depositará",
			nosotros: "depositaremos",
			vosotros: "depositaréis",
			Uds: "depositarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "deposite",
			tú: "deposites",
			Ud: "deposite",
			nosotros: "depositemos",
			vosotros: "depositéis",
			Uds: "depositen",
		},
		Imperfect: {
			yo: "depositara",
			tú: "depositaras",
			Ud: "depositara",
			nosotros: "depositáramos",
			vosotros: "depositarais",
			Uds: "depositaran",
		},
		Imperfect2: {
			yo: "depositase",
			tú: "depositases",
			Ud: "depositase",
			nosotros: "depositásemos",
			vosotros: "depositaseis",
			Uds: "depositasen",
		},
		Future: {
			yo: "depositare",
			tú: "depositares",
			Ud: "depositare",
			nosotros: "depositáremos",
			vosotros: "depositareis",
			Uds: "depositaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "deposita",
			Ud: "deposite",
			nosotros: "depositemos",
			vosotros: "depositad",
			Uds: "depositen",
		},
		Negative: {
			tú: "no deposites",
			Ud: "no deposite",
			nosotros: "no depositemos",
			vosotros: "no depositéis",
			Uds: "no depositen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy depositando",
			tú: "estás depositando",
			Ud: "está depositando",
			nosotros: "estamos depositando",
			vosotros: "estáis depositando",
			Uds: "están depositando",
		},
		Preterite: {
			yo: "estuve depositando",
			tú: "estuviste depositando",
			Ud: "estuvo depositando",
			nosotros: "estuvimos depositando",
			vosotros: "estuvisteis depositando",
			Uds: "estuvieron depositando",
		},
		Imperfect: {
			Uds: "estaban depositando",
			yo: "estaba depositando",
			tú: "estabas depositando",
			Ud: "estaba depositando",
			nosotros: "estábamos depositando",
			vosotros: "estabais depositando",
		},
		Conditional: {
			yo: "estaría depositando",
			tú: "estarías depositando",
			Ud: "estaría depositando",
			nosotros: "estaríamos depositando",
			vosotros: "estaríais depositando",
			Uds: "estarían depositando",
		},
		Future: {
			yo: "estaré depositando",
			tú: "estarás depositando",
			Ud: "estará depositando",
			nosotros: "estaremos depositando",
			vosotros: "estaréis depositando",
			Uds: "estarán depositando",
		},
	},
	Perfect: {
		Present: {
			yo: "he depositado",
			tú: "has depositado",
			Ud: "ha depositado",
			nosotros: "hemos depositado",
			vosotros: "habéis depositado",
			Uds: "han depositado",
		},
		Preterite: {
			yo: "hube depositado",
			tú: "hubiste depositado",
			Ud: "hubo depositado",
			nosotros: "hubimos depositado",
			vosotros: "hubisteis depositado",
			Uds: "hubieron depositado",
		},
		Past: {
			yo: "había depositado",
			tú: "habías depositado",
			Ud: "había depositado",
			nosotros: "habíamos depositado",
			vosotros: "habíais depositado",
			Uds: "habían depositado",
		},
		Conditional: {
			yo: "habría depositado",
			tú: "habrías depositado",
			Ud: "habría depositado",
			nosotros: "habríamos depositado",
			vosotros: "habríais depositado",
			Uds: "habrían depositado",
		},
		Future: {
			yo: "habré depositado",
			tú: "habrás depositado",
			Ud: "habrá depositado",
			nosotros: "habremos depositado",
			vosotros: "habréis depositado",
			Uds: "habrán depositado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya depositado",
			tú: "hayas depositado",
			Ud: "haya depositado",
			nosotros: "hayamos depositado",
			vosotros: "hayáis depositado",
			Uds: "hayan depositado",
		},
		Past: {
			yo: "hubiera depositado",
			tú: "hubieras depositado",
			Ud: "hubiera depositado",
			nosotros: "hubiéramos depositado",
			vosotros: "hubierais depositado",
			Uds: "hubieran depositado",
		},
		Future: {
			yo: "hubiere depositado",
			tú: "hubieres depositado",
			Ud: "hubiere depositado",
			nosotros: "hubiéremos depositado",
			vosotros: "hubiereis depositado",
			Uds: "hubieren depositado",
		},
	},
}
