var derretir = {
	Indicative: {
		Present: {
			yo: "derrito",
			tú: "derrites",
			Ud: "derrite",
			nosotros: "derretimos",
			vosotros: "derretís",
			Uds: "derriten",
		},
		Preterite: {
			yo: "derretí",
			tú: "derretiste",
			Ud: "derritió",
			nosotros: "derretimos",
			vosotros: "derretisteis",
			Uds: "derritieron",
		},
		Imperfect: {
			yo: "derretía",
			tú: "derretías",
			Ud: "derretía",
			nosotros: "derretíamos",
			vosotros: "derretíais",
			Uds: "derretían",
		},
		Conditional: {
			yo: "derretiría",
			tú: "derretirías",
			Ud: "derretiría",
			nosotros: "derretiríamos",
			vosotros: "derretiríais",
			Uds: "derretirían",
		},
		Future: {
			yo: "derretiré",
			tú: "derretirás",
			Ud: "derretirá",
			nosotros: "derretiremos",
			vosotros: "derretiréis",
			Uds: "derretirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "derrita",
			tú: "derritas",
			Ud: "derrita",
			nosotros: "derritamos",
			vosotros: "derritáis",
			Uds: "derritan",
		},
		Imperfect: {
			yo: "derritiera",
			tú: "derritieras",
			Ud: "derritiera",
			nosotros: "derritiéramos",
			vosotros: "derritierais",
			Uds: "derritieran",
		},
		Imperfect2: {
			yo: "derritiese",
			tú: "derritieses",
			Ud: "derritiese",
			nosotros: "derritiésemos",
			vosotros: "derritieseis",
			Uds: "derritiesen",
		},
		Future: {
			yo: "derritiere",
			tú: "derritieres",
			Ud: "derritiere",
			nosotros: "derritiéremos",
			vosotros: "derritiereis",
			Uds: "derritieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "derrite",
			Ud: "derrita",
			nosotros: "derritamos",
			vosotros: "derretid",
			Uds: "derritan",
		},
		Negative: {
			tú: "no derritas",
			Ud: "no derrita",
			nosotros: "no derritamos",
			vosotros: "no derritáis",
			Uds: "no derritan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy derritiendo",
			tú: "estás derritiendo",
			Ud: "está derritiendo",
			nosotros: "estamos derritiendo",
			vosotros: "estáis derritiendo",
			Uds: "están derritiendo",
		},
		Preterite: {
			yo: "estuve derritiendo",
			tú: "estuviste derritiendo",
			Ud: "estuvo derritiendo",
			nosotros: "estuvimos derritiendo",
			vosotros: "estuvisteis derritiendo",
			Uds: "estuvieron derritiendo",
		},
		Imperfect: {
			Uds: "estaban derritiendo",
			yo: "estaba derritiendo",
			tú: "estabas derritiendo",
			Ud: "estaba derritiendo",
			nosotros: "estábamos derritiendo",
			vosotros: "estabais derritiendo",
		},
		Conditional: {
			yo: "estaría derritiendo",
			tú: "estarías derritiendo",
			Ud: "estaría derritiendo",
			nosotros: "estaríamos derritiendo",
			vosotros: "estaríais derritiendo",
			Uds: "estarían derritiendo",
		},
		Future: {
			yo: "estaré derritiendo",
			tú: "estarás derritiendo",
			Ud: "estará derritiendo",
			nosotros: "estaremos derritiendo",
			vosotros: "estaréis derritiendo",
			Uds: "estarán derritiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he derretido",
			tú: "has derretido",
			Ud: "ha derretido",
			nosotros: "hemos derretido",
			vosotros: "habéis derretido",
			Uds: "han derretido",
		},
		Preterite: {
			yo: "hube derretido",
			tú: "hubiste derretido",
			Ud: "hubo derretido",
			nosotros: "hubimos derretido",
			vosotros: "hubisteis derretido",
			Uds: "hubieron derretido",
		},
		Past: {
			yo: "había derretido",
			tú: "habías derretido",
			Ud: "había derretido",
			nosotros: "habíamos derretido",
			vosotros: "habíais derretido",
			Uds: "habían derretido",
		},
		Conditional: {
			yo: "habría derretido",
			tú: "habrías derretido",
			Ud: "habría derretido",
			nosotros: "habríamos derretido",
			vosotros: "habríais derretido",
			Uds: "habrían derretido",
		},
		Future: {
			yo: "habré derretido",
			tú: "habrás derretido",
			Ud: "habrá derretido",
			nosotros: "habremos derretido",
			vosotros: "habréis derretido",
			Uds: "habrán derretido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya derretido",
			tú: "hayas derretido",
			Ud: "haya derretido",
			nosotros: "hayamos derretido",
			vosotros: "hayáis derretido",
			Uds: "hayan derretido",
		},
		Past: {
			yo: "hubiera derretido",
			tú: "hubieras derretido",
			Ud: "hubiera derretido",
			nosotros: "hubiéramos derretido",
			vosotros: "hubierais derretido",
			Uds: "hubieran derretido",
		},
		Future: {
			yo: "hubiere derretido",
			tú: "hubieres derretido",
			Ud: "hubiere derretido",
			nosotros: "hubiéremos derretido",
			vosotros: "hubiereis derretido",
			Uds: "hubieren derretido",
		},
	},
}
