var derruir = {
	Indicative: {
		Present: {
			yo: "derruyo",
			tú: "derruyes",
			Ud: "derruye",
			nosotros: "derruimos",
			vosotros: "derruís",
			Uds: "derruyen",
		},
		Preterite: {
			yo: "derruí",
			tú: "derruiste",
			Ud: "derruyó",
			nosotros: "derruimos",
			vosotros: "derruisteis",
			Uds: "derruyeron",
		},
		Imperfect: {
			yo: "derruía",
			tú: "derruías",
			Ud: "derruía",
			nosotros: "derruíamos",
			vosotros: "derruíais",
			Uds: "derruían",
		},
		Conditional: {
			yo: "derruiría",
			tú: "derruirías",
			Ud: "derruiría",
			nosotros: "derruiríamos",
			vosotros: "derruiríais",
			Uds: "derruirían",
		},
		Future: {
			yo: "derruiré",
			tú: "derruirás",
			Ud: "derruirá",
			nosotros: "derruiremos",
			vosotros: "derruiréis",
			Uds: "derruirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "derruya",
			tú: "derruyas",
			Ud: "derruya",
			nosotros: "derruyamos",
			vosotros: "derruyáis",
			Uds: "derruyan",
		},
		Imperfect: {
			yo: "derruyera",
			tú: "derruyeras",
			Ud: "derruyera",
			nosotros: "derruyéramos",
			vosotros: "derruyerais",
			Uds: "derruyeran",
		},
		Imperfect2: {
			yo: "derruyese",
			tú: "derruyeses",
			Ud: "derruyese",
			nosotros: "derruyésemos",
			vosotros: "derruyeseis",
			Uds: "derruyesen",
		},
		Future: {
			yo: "derruyere",
			tú: "derruyeres",
			Ud: "derruyere",
			nosotros: "derruyéremos",
			vosotros: "derruyereis",
			Uds: "derruyeren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "derruye",
			Ud: "derruya",
			nosotros: "derruyamos",
			vosotros: "derruid",
			Uds: "derruyan",
		},
		Negative: {
			tú: "no derruyas",
			Ud: "no derruya",
			nosotros: "no derruyamos",
			vosotros: "no derruyáis",
			Uds: "no derruyan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy derruyendo",
			tú: "estás derruyendo",
			Ud: "está derruyendo",
			nosotros: "estamos derruyendo",
			vosotros: "estáis derruyendo",
			Uds: "están derruyendo",
		},
		Preterite: {
			yo: "estuve derruyendo",
			tú: "estuviste derruyendo",
			Ud: "estuvo derruyendo",
			nosotros: "estuvimos derruyendo",
			vosotros: "estuvisteis derruyendo",
			Uds: "estuvieron derruyendo",
		},
		Imperfect: {
			Uds: "estaban derruyendo",
			yo: "estaba derruyendo",
			tú: "estabas derruyendo",
			Ud: "estaba derruyendo",
			nosotros: "estábamos derruyendo",
			vosotros: "estabais derruyendo",
		},
		Conditional: {
			yo: "estaría derruyendo",
			tú: "estarías derruyendo",
			Ud: "estaría derruyendo",
			nosotros: "estaríamos derruyendo",
			vosotros: "estaríais derruyendo",
			Uds: "estarían derruyendo",
		},
		Future: {
			yo: "estaré derruyendo",
			tú: "estarás derruyendo",
			Ud: "estará derruyendo",
			nosotros: "estaremos derruyendo",
			vosotros: "estaréis derruyendo",
			Uds: "estarán derruyendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he derruido",
			tú: "has derruido",
			Ud: "ha derruido",
			nosotros: "hemos derruido",
			vosotros: "habéis derruido",
			Uds: "han derruido",
		},
		Preterite: {
			yo: "hube derruido",
			tú: "hubiste derruido",
			Ud: "hubo derruido",
			nosotros: "hubimos derruido",
			vosotros: "hubisteis derruido",
			Uds: "hubieron derruido",
		},
		Past: {
			yo: "había derruido",
			tú: "habías derruido",
			Ud: "había derruido",
			nosotros: "habíamos derruido",
			vosotros: "habíais derruido",
			Uds: "habían derruido",
		},
		Conditional: {
			yo: "habría derruido",
			tú: "habrías derruido",
			Ud: "habría derruido",
			nosotros: "habríamos derruido",
			vosotros: "habríais derruido",
			Uds: "habrían derruido",
		},
		Future: {
			yo: "habré derruido",
			tú: "habrás derruido",
			Ud: "habrá derruido",
			nosotros: "habremos derruido",
			vosotros: "habréis derruido",
			Uds: "habrán derruido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya derruido",
			tú: "hayas derruido",
			Ud: "haya derruido",
			nosotros: "hayamos derruido",
			vosotros: "hayáis derruido",
			Uds: "hayan derruido",
		},
		Past: {
			yo: "hubiera derruido",
			tú: "hubieras derruido",
			Ud: "hubiera derruido",
			nosotros: "hubiéramos derruido",
			vosotros: "hubierais derruido",
			Uds: "hubieran derruido",
		},
		Future: {
			yo: "hubiere derruido",
			tú: "hubieres derruido",
			Ud: "hubiere derruido",
			nosotros: "hubiéremos derruido",
			vosotros: "hubiereis derruido",
			Uds: "hubieren derruido",
		},
	},
}
