var derrotar = {
	Indicative: {
		Present: {
			yo: "me derroto",
			tú: "te derrotas",
			Ud: "se derrota",
			nosotros: "nos derrotamos",
			vosotros: "os derrotáis",
			Uds: "se derrotan",
		},
		Preterite: {
			yo: "me derroté",
			tú: "te derrotaste",
			Ud: "se derrotó",
			nosotros: "nos derrotamos",
			vosotros: "os derrotasteis",
			Uds: "se derrotaron",
		},
		Imperfect: {
			yo: "me derrotaba",
			tú: "te derrotabas",
			Ud: "se derrotaba",
			nosotros: "nos derrotábamos",
			vosotros: "os derrotabais",
			Uds: "se derrotaban",
		},
		Conditional: {
			yo: "me derrotaría",
			tú: "te derrotarías",
			Ud: "se derrotaría",
			nosotros: "nos derrotaríamos",
			vosotros: "os derrotaríais",
			Uds: "se derrotarían",
		},
		Future: {
			yo: "me derrotaré",
			tú: "te derrotarás",
			Ud: "se derrotará",
			nosotros: "nos derrotaremos",
			vosotros: "os derrotaréis",
			Uds: "se derrotarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "me derrote",
			tú: "te derrotes",
			Ud: "se derrote",
			nosotros: "nos derrotemos",
			vosotros: "os derrotéis",
			Uds: "se derroten",
		},
		Imperfect: {
			yo: "me derrotara",
			tú: "te derrotaras",
			Ud: "se derrotara",
			nosotros: "nos derrotáramos",
			vosotros: "os derrotarais",
			Uds: "se derrotaran",
		},
		Imperfect2: {
			yo: "me derrotase",
			tú: "te derrotases",
			Ud: "se derrotase",
			nosotros: "nos derrotásemos",
			vosotros: "os derrotaseis",
			Uds: "se derrotasen",
		},
		Future: {
			yo: "me derrotare",
			tú: "te derrotares",
			Ud: "se derrotare",
			nosotros: "nos derrotáremos",
			vosotros: "os derrotareis",
			Uds: "se derrotaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "derrótate",
			Ud: "derrótese",
			nosotros: "derrotémonos",
			vosotros: "derrotaos",
			Uds: "derrótense",
		},
		Negative: {
			tú: "no te derrotes",
			Ud: "no se derrote",
			nosotros: "no nos derrotemos",
			vosotros: "no os derrotéis",
			Uds: "no se derroten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "me estoy derrotando",
			tú: "te estás derrotando",
			Ud: "se está derrotando",
			nosotros: "nos estamos derrotando",
			vosotros: "os estáis derrotando",
			Uds: "se están derrotando",
		},
		Preterite: {
			yo: "me estuve derrotando",
			tú: "te estuviste derrotando",
			Ud: "se estuvo derrotando",
			nosotros: "nos estuvimos derrotando",
			vosotros: "os estuvisteis derrotando",
			Uds: "se estuvieron derrotando",
		},
		Imperfect: {
			Uds: "se estaban derrotando",
			yo: "me estaba derrotando",
			tú: "te estabas derrotando",
			Ud: "se estaba derrotando",
			nosotros: "nos estábamos derrotando",
			vosotros: "os estabais derrotando",
		},
		Conditional: {
			yo: "me estaría derrotando",
			tú: "te estarías derrotando",
			Ud: "se estaría derrotando",
			nosotros: "nos estaríamos derrotando",
			vosotros: "os estaríais derrotando",
			Uds: "se estarían derrotando",
		},
		Future: {
			yo: "me estaré derrotando",
			tú: "te estarás derrotando",
			Ud: "se estará derrotando",
			nosotros: "nos estaremos derrotando",
			vosotros: "os estaréis derrotando",
			Uds: "se estarán derrotando",
		},
	},
	Perfect: {
		Present: {
			yo: "me he derrotado",
			tú: "te has derrotado",
			Ud: "se ha derrotado",
			nosotros: "nos hemos derrotado",
			vosotros: "os habéis derrotado",
			Uds: "se han derrotado",
		},
		Preterite: {
			yo: "me hube derrotado",
			tú: "te hubiste derrotado",
			Ud: "se hubo derrotado",
			nosotros: "nos hubimos derrotado",
			vosotros: "os hubisteis derrotado",
			Uds: "se hubieron derrotado",
		},
		Past: {
			yo: "me había derrotado",
			tú: "te habías derrotado",
			Ud: "se había derrotado",
			nosotros: "nos habíamos derrotado",
			vosotros: "os habíais derrotado",
			Uds: "se habían derrotado",
		},
		Conditional: {
			yo: "me habría derrotado",
			tú: "te habrías derrotado",
			Ud: "se habría derrotado",
			nosotros: "nos habríamos derrotado",
			vosotros: "os habríais derrotado",
			Uds: "se habrían derrotado",
		},
		Future: {
			yo: "me habré derrotado",
			tú: "te habrás derrotado",
			Ud: "se habrá derrotado",
			nosotros: "nos habremos derrotado",
			vosotros: "os habréis derrotado",
			Uds: "se habrán derrotado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "me haya derrotado",
			tú: "te hayas derrotado",
			Ud: "se haya derrotado",
			nosotros: "nos hayamos derrotado",
			vosotros: "os hayáis derrotado",
			Uds: "se hayan derrotado",
		},
		Past: {
			yo: "me hubiera derrotado",
			tú: "te hubieras derrotado",
			Ud: "se hubiera derrotado",
			nosotros: "nos hubiéramos derrotado",
			vosotros: "os hubierais derrotado",
			Uds: "se hubieran derrotado",
		},
		Future: {
			yo: "me hubiere derrotado",
			tú: "te hubieres derrotado",
			Ud: "se hubiere derrotado",
			nosotros: "nos hubiéremos derrotado",
			vosotros: "os hubiereis derrotado",
			Uds: "se hubieren derrotado",
		},
	},
}
