var desayunar = {
	Indicative: {
		Present: {
			yo: "desayuno",
			tú: "desayunas",
			Ud: "desayuna",
			nosotros: "desayunamos",
			vosotros: "desayunáis",
			Uds: "desayunan",
		},
		Preterite: {
			yo: "desayuné",
			tú: "desayunaste",
			Ud: "desayunó",
			nosotros: "desayunamos",
			vosotros: "desayunasteis",
			Uds: "desayunaron",
		},
		Imperfect: {
			yo: "desayunaba",
			tú: "desayunabas",
			Ud: "desayunaba",
			nosotros: "desayunábamos",
			vosotros: "desayunabais",
			Uds: "desayunaban",
		},
		Conditional: {
			yo: "desayunaría",
			tú: "desayunarías",
			Ud: "desayunaría",
			nosotros: "desayunaríamos",
			vosotros: "desayunaríais",
			Uds: "desayunarían",
		},
		Future: {
			yo: "desayunaré",
			tú: "desayunarás",
			Ud: "desayunará",
			nosotros: "desayunaremos",
			vosotros: "desayunaréis",
			Uds: "desayunarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "desayune",
			tú: "desayunes",
			Ud: "desayune",
			nosotros: "desayunemos",
			vosotros: "desayunéis",
			Uds: "desayunen",
		},
		Imperfect: {
			yo: "desayunara",
			tú: "desayunaras",
			Ud: "desayunara",
			nosotros: "desayunáramos",
			vosotros: "desayunarais",
			Uds: "desayunaran",
		},
		Imperfect2: {
			yo: "desayunase",
			tú: "desayunases",
			Ud: "desayunase",
			nosotros: "desayunásemos",
			vosotros: "desayunaseis",
			Uds: "desayunasen",
		},
		Future: {
			yo: "desayunare",
			tú: "desayunares",
			Ud: "desayunare",
			nosotros: "desayunáremos",
			vosotros: "desayunareis",
			Uds: "desayunaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "desayuna",
			Ud: "desayune",
			nosotros: "desayunemos",
			vosotros: "desayunad",
			Uds: "desayunen",
		},
		Negative: {
			tú: "no desayunes",
			Ud: "no desayune",
			nosotros: "no desayunemos",
			vosotros: "no desayunéis",
			Uds: "no desayunen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy desayunando",
			tú: "estás desayunando",
			Ud: "está desayunando",
			nosotros: "estamos desayunando",
			vosotros: "estáis desayunando",
			Uds: "están desayunando",
		},
		Preterite: {
			yo: "estuve desayunando",
			tú: "estuviste desayunando",
			Ud: "estuvo desayunando",
			nosotros: "estuvimos desayunando",
			vosotros: "estuvisteis desayunando",
			Uds: "estuvieron desayunando",
		},
		Imperfect: {
			Uds: "estaban desayunando",
			yo: "estaba desayunando",
			tú: "estabas desayunando",
			Ud: "estaba desayunando",
			nosotros: "estábamos desayunando",
			vosotros: "estabais desayunando",
		},
		Conditional: {
			yo: "estaría desayunando",
			tú: "estarías desayunando",
			Ud: "estaría desayunando",
			nosotros: "estaríamos desayunando",
			vosotros: "estaríais desayunando",
			Uds: "estarían desayunando",
		},
		Future: {
			yo: "estaré desayunando",
			tú: "estarás desayunando",
			Ud: "estará desayunando",
			nosotros: "estaremos desayunando",
			vosotros: "estaréis desayunando",
			Uds: "estarán desayunando",
		},
	},
	Perfect: {
		Present: {
			yo: "he desayunado",
			tú: "has desayunado",
			Ud: "ha desayunado",
			nosotros: "hemos desayunado",
			vosotros: "habéis desayunado",
			Uds: "han desayunado",
		},
		Preterite: {
			yo: "hube desayunado",
			tú: "hubiste desayunado",
			Ud: "hubo desayunado",
			nosotros: "hubimos desayunado",
			vosotros: "hubisteis desayunado",
			Uds: "hubieron desayunado",
		},
		Past: {
			yo: "había desayunado",
			tú: "habías desayunado",
			Ud: "había desayunado",
			nosotros: "habíamos desayunado",
			vosotros: "habíais desayunado",
			Uds: "habían desayunado",
		},
		Conditional: {
			yo: "habría desayunado",
			tú: "habrías desayunado",
			Ud: "habría desayunado",
			nosotros: "habríamos desayunado",
			vosotros: "habríais desayunado",
			Uds: "habrían desayunado",
		},
		Future: {
			yo: "habré desayunado",
			tú: "habrás desayunado",
			Ud: "habrá desayunado",
			nosotros: "habremos desayunado",
			vosotros: "habréis desayunado",
			Uds: "habrán desayunado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya desayunado",
			tú: "hayas desayunado",
			Ud: "haya desayunado",
			nosotros: "hayamos desayunado",
			vosotros: "hayáis desayunado",
			Uds: "hayan desayunado",
		},
		Past: {
			yo: "hubiera desayunado",
			tú: "hubieras desayunado",
			Ud: "hubiera desayunado",
			nosotros: "hubiéramos desayunado",
			vosotros: "hubierais desayunado",
			Uds: "hubieran desayunado",
		},
		Future: {
			yo: "hubiere desayunado",
			tú: "hubieres desayunado",
			Ud: "hubiere desayunado",
			nosotros: "hubiéremos desayunado",
			vosotros: "hubiereis desayunado",
			Uds: "hubieren desayunado",
		},
	},
}
