var desanimar = {
	Indicative: {
		Present: {
			yo: "desanimo",
			tú: "desanimas",
			Ud: "desanima",
			nosotros: "desanimamos",
			vosotros: "desanimáis",
			Uds: "desaniman",
		},
		Preterite: {
			yo: "desanimé",
			tú: "desanimaste",
			Ud: "desanimó",
			nosotros: "desanimamos",
			vosotros: "desanimasteis",
			Uds: "desanimaron",
		},
		Imperfect: {
			yo: "desanimaba",
			tú: "desanimabas",
			Ud: "desanimaba",
			nosotros: "desanimábamos",
			vosotros: "desanimabais",
			Uds: "desanimaban",
		},
		Conditional: {
			yo: "desanimaría",
			tú: "desanimarías",
			Ud: "desanimaría",
			nosotros: "desanimaríamos",
			vosotros: "desanimaríais",
			Uds: "desanimarían",
		},
		Future: {
			yo: "desanimaré",
			tú: "desanimarás",
			Ud: "desanimará",
			nosotros: "desanimaremos",
			vosotros: "desanimaréis",
			Uds: "desanimarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "desanime",
			tú: "desanimes",
			Ud: "desanime",
			nosotros: "desanimemos",
			vosotros: "desaniméis",
			Uds: "desanimen",
		},
		Imperfect: {
			yo: "desanimara",
			tú: "desanimaras",
			Ud: "desanimara",
			nosotros: "desanimáramos",
			vosotros: "desanimarais",
			Uds: "desanimaran",
		},
		Imperfect2: {
			yo: "desanimase",
			tú: "desanimases",
			Ud: "desanimase",
			nosotros: "desanimásemos",
			vosotros: "desanimaseis",
			Uds: "desanimasen",
		},
		Future: {
			yo: "desanimare",
			tú: "desanimares",
			Ud: "desanimare",
			nosotros: "desanimáremos",
			vosotros: "desanimareis",
			Uds: "desanimaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "desanima",
			Ud: "desanime",
			nosotros: "desanimemos",
			vosotros: "desanimad",
			Uds: "desanimen",
		},
		Negative: {
			tú: "no desanimes",
			Ud: "no desanime",
			nosotros: "no desanimemos",
			vosotros: "no desaniméis",
			Uds: "no desanimen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy desanimando",
			tú: "estás desanimando",
			Ud: "está desanimando",
			nosotros: "estamos desanimando",
			vosotros: "estáis desanimando",
			Uds: "están desanimando",
		},
		Preterite: {
			yo: "estuve desanimando",
			tú: "estuviste desanimando",
			Ud: "estuvo desanimando",
			nosotros: "estuvimos desanimando",
			vosotros: "estuvisteis desanimando",
			Uds: "estuvieron desanimando",
		},
		Imperfect: {
			Uds: "estaban desanimando",
			yo: "estaba desanimando",
			tú: "estabas desanimando",
			Ud: "estaba desanimando",
			nosotros: "estábamos desanimando",
			vosotros: "estabais desanimando",
		},
		Conditional: {
			yo: "estaría desanimando",
			tú: "estarías desanimando",
			Ud: "estaría desanimando",
			nosotros: "estaríamos desanimando",
			vosotros: "estaríais desanimando",
			Uds: "estarían desanimando",
		},
		Future: {
			yo: "estaré desanimando",
			tú: "estarás desanimando",
			Ud: "estará desanimando",
			nosotros: "estaremos desanimando",
			vosotros: "estaréis desanimando",
			Uds: "estarán desanimando",
		},
	},
	Perfect: {
		Present: {
			yo: "he desanimado",
			tú: "has desanimado",
			Ud: "ha desanimado",
			nosotros: "hemos desanimado",
			vosotros: "habéis desanimado",
			Uds: "han desanimado",
		},
		Preterite: {
			yo: "hube desanimado",
			tú: "hubiste desanimado",
			Ud: "hubo desanimado",
			nosotros: "hubimos desanimado",
			vosotros: "hubisteis desanimado",
			Uds: "hubieron desanimado",
		},
		Past: {
			yo: "había desanimado",
			tú: "habías desanimado",
			Ud: "había desanimado",
			nosotros: "habíamos desanimado",
			vosotros: "habíais desanimado",
			Uds: "habían desanimado",
		},
		Conditional: {
			yo: "habría desanimado",
			tú: "habrías desanimado",
			Ud: "habría desanimado",
			nosotros: "habríamos desanimado",
			vosotros: "habríais desanimado",
			Uds: "habrían desanimado",
		},
		Future: {
			yo: "habré desanimado",
			tú: "habrás desanimado",
			Ud: "habrá desanimado",
			nosotros: "habremos desanimado",
			vosotros: "habréis desanimado",
			Uds: "habrán desanimado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya desanimado",
			tú: "hayas desanimado",
			Ud: "haya desanimado",
			nosotros: "hayamos desanimado",
			vosotros: "hayáis desanimado",
			Uds: "hayan desanimado",
		},
		Past: {
			yo: "hubiera desanimado",
			tú: "hubieras desanimado",
			Ud: "hubiera desanimado",
			nosotros: "hubiéramos desanimado",
			vosotros: "hubierais desanimado",
			Uds: "hubieran desanimado",
		},
		Future: {
			yo: "hubiere desanimado",
			tú: "hubieres desanimado",
			Ud: "hubiere desanimado",
			nosotros: "hubiéremos desanimado",
			vosotros: "hubiereis desanimado",
			Uds: "hubieren desanimado",
		},
	},
}
