var descascarar = {
	Indicative: {
		Present: {
			yo: "descascaro",
			tú: "descascaras",
			Ud: "descascara",
			nosotros: "descascaramos",
			vosotros: "descascaráis",
			Uds: "descascaran",
		},
		Preterite: {
			yo: "descascaré",
			tú: "descascaraste",
			Ud: "descascaró",
			nosotros: "descascaramos",
			vosotros: "descascarasteis",
			Uds: "descascararon",
		},
		Imperfect: {
			yo: "descascaraba",
			tú: "descascarabas",
			Ud: "descascaraba",
			nosotros: "descascarábamos",
			vosotros: "descascarabais",
			Uds: "descascaraban",
		},
		Conditional: {
			yo: "descascararía",
			tú: "descascararías",
			Ud: "descascararía",
			nosotros: "descascararíamos",
			vosotros: "descascararíais",
			Uds: "descascararían",
		},
		Future: {
			yo: "descascararé",
			tú: "descascararás",
			Ud: "descascarará",
			nosotros: "descascararemos",
			vosotros: "descascararéis",
			Uds: "descascararán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "descascare",
			tú: "descascares",
			Ud: "descascare",
			nosotros: "descascaremos",
			vosotros: "descascaréis",
			Uds: "descascaren",
		},
		Imperfect: {
			yo: "descascarara",
			tú: "descascararas",
			Ud: "descascarara",
			nosotros: "descascaráramos",
			vosotros: "descascararais",
			Uds: "descascararan",
		},
		Imperfect2: {
			yo: "descascarase",
			tú: "descascarases",
			Ud: "descascarase",
			nosotros: "descascarásemos",
			vosotros: "descascaraseis",
			Uds: "descascarasen",
		},
		Future: {
			yo: "descascarare",
			tú: "descascarares",
			Ud: "descascarare",
			nosotros: "descascaráremos",
			vosotros: "descascarareis",
			Uds: "descascararen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "descascara",
			Ud: "descascare",
			nosotros: "descascaremos",
			vosotros: "descascarad",
			Uds: "descascaren",
		},
		Negative: {
			tú: "no descascares",
			Ud: "no descascare",
			nosotros: "no descascaremos",
			vosotros: "no descascaréis",
			Uds: "no descascaren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy descascarando",
			tú: "estás descascarando",
			Ud: "está descascarando",
			nosotros: "estamos descascarando",
			vosotros: "estáis descascarando",
			Uds: "están descascarando",
		},
		Preterite: {
			yo: "estuve descascarando",
			tú: "estuviste descascarando",
			Ud: "estuvo descascarando",
			nosotros: "estuvimos descascarando",
			vosotros: "estuvisteis descascarando",
			Uds: "estuvieron descascarando",
		},
		Imperfect: {
			Uds: "estaban descascarando",
			yo: "estaba descascarando",
			tú: "estabas descascarando",
			Ud: "estaba descascarando",
			nosotros: "estábamos descascarando",
			vosotros: "estabais descascarando",
		},
		Conditional: {
			yo: "estaría descascarando",
			tú: "estarías descascarando",
			Ud: "estaría descascarando",
			nosotros: "estaríamos descascarando",
			vosotros: "estaríais descascarando",
			Uds: "estarían descascarando",
		},
		Future: {
			yo: "estaré descascarando",
			tú: "estarás descascarando",
			Ud: "estará descascarando",
			nosotros: "estaremos descascarando",
			vosotros: "estaréis descascarando",
			Uds: "estarán descascarando",
		},
	},
	Perfect: {
		Present: {
			yo: "he descascarado",
			tú: "has descascarado",
			Ud: "ha descascarado",
			nosotros: "hemos descascarado",
			vosotros: "habéis descascarado",
			Uds: "han descascarado",
		},
		Preterite: {
			yo: "hube descascarado",
			tú: "hubiste descascarado",
			Ud: "hubo descascarado",
			nosotros: "hubimos descascarado",
			vosotros: "hubisteis descascarado",
			Uds: "hubieron descascarado",
		},
		Past: {
			yo: "había descascarado",
			tú: "habías descascarado",
			Ud: "había descascarado",
			nosotros: "habíamos descascarado",
			vosotros: "habíais descascarado",
			Uds: "habían descascarado",
		},
		Conditional: {
			yo: "habría descascarado",
			tú: "habrías descascarado",
			Ud: "habría descascarado",
			nosotros: "habríamos descascarado",
			vosotros: "habríais descascarado",
			Uds: "habrían descascarado",
		},
		Future: {
			yo: "habré descascarado",
			tú: "habrás descascarado",
			Ud: "habrá descascarado",
			nosotros: "habremos descascarado",
			vosotros: "habréis descascarado",
			Uds: "habrán descascarado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya descascarado",
			tú: "hayas descascarado",
			Ud: "haya descascarado",
			nosotros: "hayamos descascarado",
			vosotros: "hayáis descascarado",
			Uds: "hayan descascarado",
		},
		Past: {
			yo: "hubiera descascarado",
			tú: "hubieras descascarado",
			Ud: "hubiera descascarado",
			nosotros: "hubiéramos descascarado",
			vosotros: "hubierais descascarado",
			Uds: "hubieran descascarado",
		},
		Future: {
			yo: "hubiere descascarado",
			tú: "hubieres descascarado",
			Ud: "hubiere descascarado",
			nosotros: "hubiéremos descascarado",
			vosotros: "hubiereis descascarado",
			Uds: "hubieren descascarado",
		},
	},
}
