var descartar = {
	Indicative: {
		Present: {
			yo: "descarto",
			tú: "descartas",
			Ud: "descarta",
			nosotros: "descartamos",
			vosotros: "descartáis",
			Uds: "descartan",
		},
		Preterite: {
			yo: "descarté",
			tú: "descartaste",
			Ud: "descartó",
			nosotros: "descartamos",
			vosotros: "descartasteis",
			Uds: "descartaron",
		},
		Imperfect: {
			yo: "descartaba",
			tú: "descartabas",
			Ud: "descartaba",
			nosotros: "descartábamos",
			vosotros: "descartabais",
			Uds: "descartaban",
		},
		Conditional: {
			yo: "descartaría",
			tú: "descartarías",
			Ud: "descartaría",
			nosotros: "descartaríamos",
			vosotros: "descartaríais",
			Uds: "descartarían",
		},
		Future: {
			yo: "descartaré",
			tú: "descartarás",
			Ud: "descartará",
			nosotros: "descartaremos",
			vosotros: "descartaréis",
			Uds: "descartarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "descarte",
			tú: "descartes",
			Ud: "descarte",
			nosotros: "descartemos",
			vosotros: "descartéis",
			Uds: "descarten",
		},
		Imperfect: {
			yo: "descartara",
			tú: "descartaras",
			Ud: "descartara",
			nosotros: "descartáramos",
			vosotros: "descartarais",
			Uds: "descartaran",
		},
		Imperfect2: {
			yo: "descartase",
			tú: "descartases",
			Ud: "descartase",
			nosotros: "descartásemos",
			vosotros: "descartaseis",
			Uds: "descartasen",
		},
		Future: {
			yo: "descartare",
			tú: "descartares",
			Ud: "descartare",
			nosotros: "descartáremos",
			vosotros: "descartareis",
			Uds: "descartaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "descarta",
			Ud: "descarte",
			nosotros: "descartemos",
			vosotros: "descartad",
			Uds: "descarten",
		},
		Negative: {
			tú: "no descartes",
			Ud: "no descarte",
			nosotros: "no descartemos",
			vosotros: "no descartéis",
			Uds: "no descarten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy descartando",
			tú: "estás descartando",
			Ud: "está descartando",
			nosotros: "estamos descartando",
			vosotros: "estáis descartando",
			Uds: "están descartando",
		},
		Preterite: {
			yo: "estuve descartando",
			tú: "estuviste descartando",
			Ud: "estuvo descartando",
			nosotros: "estuvimos descartando",
			vosotros: "estuvisteis descartando",
			Uds: "estuvieron descartando",
		},
		Imperfect: {
			Uds: "estaban descartando",
			yo: "estaba descartando",
			tú: "estabas descartando",
			Ud: "estaba descartando",
			nosotros: "estábamos descartando",
			vosotros: "estabais descartando",
		},
		Conditional: {
			yo: "estaría descartando",
			tú: "estarías descartando",
			Ud: "estaría descartando",
			nosotros: "estaríamos descartando",
			vosotros: "estaríais descartando",
			Uds: "estarían descartando",
		},
		Future: {
			yo: "estaré descartando",
			tú: "estarás descartando",
			Ud: "estará descartando",
			nosotros: "estaremos descartando",
			vosotros: "estaréis descartando",
			Uds: "estarán descartando",
		},
	},
	Perfect: {
		Present: {
			yo: "he descartado",
			tú: "has descartado",
			Ud: "ha descartado",
			nosotros: "hemos descartado",
			vosotros: "habéis descartado",
			Uds: "han descartado",
		},
		Preterite: {
			yo: "hube descartado",
			tú: "hubiste descartado",
			Ud: "hubo descartado",
			nosotros: "hubimos descartado",
			vosotros: "hubisteis descartado",
			Uds: "hubieron descartado",
		},
		Past: {
			yo: "había descartado",
			tú: "habías descartado",
			Ud: "había descartado",
			nosotros: "habíamos descartado",
			vosotros: "habíais descartado",
			Uds: "habían descartado",
		},
		Conditional: {
			yo: "habría descartado",
			tú: "habrías descartado",
			Ud: "habría descartado",
			nosotros: "habríamos descartado",
			vosotros: "habríais descartado",
			Uds: "habrían descartado",
		},
		Future: {
			yo: "habré descartado",
			tú: "habrás descartado",
			Ud: "habrá descartado",
			nosotros: "habremos descartado",
			vosotros: "habréis descartado",
			Uds: "habrán descartado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya descartado",
			tú: "hayas descartado",
			Ud: "haya descartado",
			nosotros: "hayamos descartado",
			vosotros: "hayáis descartado",
			Uds: "hayan descartado",
		},
		Past: {
			yo: "hubiera descartado",
			tú: "hubieras descartado",
			Ud: "hubiera descartado",
			nosotros: "hubiéramos descartado",
			vosotros: "hubierais descartado",
			Uds: "hubieran descartado",
		},
		Future: {
			yo: "hubiere descartado",
			tú: "hubieres descartado",
			Ud: "hubiere descartado",
			nosotros: "hubiéremos descartado",
			vosotros: "hubiereis descartado",
			Uds: "hubieren descartado",
		},
	},
}
