var descender = {
	Indicative: {
		Present: {
			yo: "desciendo",
			tú: "desciendes",
			Ud: "desciende",
			nosotros: "descendemos",
			vosotros: "descendéis",
			Uds: "descienden",
		},
		Preterite: {
			yo: "descendí",
			tú: "descendiste",
			Ud: "descendió",
			nosotros: "descendimos",
			vosotros: "descendisteis",
			Uds: "descendieron",
		},
		Imperfect: {
			yo: "descendía",
			tú: "descendías",
			Ud: "descendía",
			nosotros: "descendíamos",
			vosotros: "descendíais",
			Uds: "descendían",
		},
		Conditional: {
			yo: "descendería",
			tú: "descenderías",
			Ud: "descendería",
			nosotros: "descenderíamos",
			vosotros: "descenderíais",
			Uds: "descenderían",
		},
		Future: {
			yo: "descenderé",
			tú: "descenderás",
			Ud: "descenderá",
			nosotros: "descenderemos",
			vosotros: "descenderéis",
			Uds: "descenderán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "descienda",
			tú: "desciendas",
			Ud: "descienda",
			nosotros: "descendamos",
			vosotros: "descendáis",
			Uds: "desciendan",
		},
		Imperfect: {
			yo: "descendiera",
			tú: "descendieras",
			Ud: "descendiera",
			nosotros: "descendiéramos",
			vosotros: "descendierais",
			Uds: "descendieran",
		},
		Imperfect2: {
			yo: "descendiese",
			tú: "descendieses",
			Ud: "descendiese",
			nosotros: "descendiésemos",
			vosotros: "descendieseis",
			Uds: "descendiesen",
		},
		Future: {
			yo: "descendiere",
			tú: "descendieres",
			Ud: "descendiere",
			nosotros: "descendiéremos",
			vosotros: "descendiereis",
			Uds: "descendieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "desciende",
			Ud: "descienda",
			nosotros: "descendamos",
			vosotros: "descended",
			Uds: "desciendan",
		},
		Negative: {
			tú: "no desciendas",
			Ud: "no descienda",
			nosotros: "no descendamos",
			vosotros: "no descendáis",
			Uds: "no desciendan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy descendiendo",
			tú: "estás descendiendo",
			Ud: "está descendiendo",
			nosotros: "estamos descendiendo",
			vosotros: "estáis descendiendo",
			Uds: "están descendiendo",
		},
		Preterite: {
			yo: "estuve descendiendo",
			tú: "estuviste descendiendo",
			Ud: "estuvo descendiendo",
			nosotros: "estuvimos descendiendo",
			vosotros: "estuvisteis descendiendo",
			Uds: "estuvieron descendiendo",
		},
		Imperfect: {
			Uds: "estaban descendiendo",
			yo: "estaba descendiendo",
			tú: "estabas descendiendo",
			Ud: "estaba descendiendo",
			nosotros: "estábamos descendiendo",
			vosotros: "estabais descendiendo",
		},
		Conditional: {
			yo: "estaría descendiendo",
			tú: "estarías descendiendo",
			Ud: "estaría descendiendo",
			nosotros: "estaríamos descendiendo",
			vosotros: "estaríais descendiendo",
			Uds: "estarían descendiendo",
		},
		Future: {
			yo: "estaré descendiendo",
			tú: "estarás descendiendo",
			Ud: "estará descendiendo",
			nosotros: "estaremos descendiendo",
			vosotros: "estaréis descendiendo",
			Uds: "estarán descendiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he descendido",
			tú: "has descendido",
			Ud: "ha descendido",
			nosotros: "hemos descendido",
			vosotros: "habéis descendido",
			Uds: "han descendido",
		},
		Preterite: {
			yo: "hube descendido",
			tú: "hubiste descendido",
			Ud: "hubo descendido",
			nosotros: "hubimos descendido",
			vosotros: "hubisteis descendido",
			Uds: "hubieron descendido",
		},
		Past: {
			yo: "había descendido",
			tú: "habías descendido",
			Ud: "había descendido",
			nosotros: "habíamos descendido",
			vosotros: "habíais descendido",
			Uds: "habían descendido",
		},
		Conditional: {
			yo: "habría descendido",
			tú: "habrías descendido",
			Ud: "habría descendido",
			nosotros: "habríamos descendido",
			vosotros: "habríais descendido",
			Uds: "habrían descendido",
		},
		Future: {
			yo: "habré descendido",
			tú: "habrás descendido",
			Ud: "habrá descendido",
			nosotros: "habremos descendido",
			vosotros: "habréis descendido",
			Uds: "habrán descendido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya descendido",
			tú: "hayas descendido",
			Ud: "haya descendido",
			nosotros: "hayamos descendido",
			vosotros: "hayáis descendido",
			Uds: "hayan descendido",
		},
		Past: {
			yo: "hubiera descendido",
			tú: "hubieras descendido",
			Ud: "hubiera descendido",
			nosotros: "hubiéramos descendido",
			vosotros: "hubierais descendido",
			Uds: "hubieran descendido",
		},
		Future: {
			yo: "hubiere descendido",
			tú: "hubieres descendido",
			Ud: "hubiere descendido",
			nosotros: "hubiéremos descendido",
			vosotros: "hubiereis descendido",
			Uds: "hubieren descendido",
		},
	},
}
