var descifrar = {
	Indicative: {
		Present: {
			yo: "descifro",
			tú: "descifras",
			Ud: "descifra",
			nosotros: "desciframos",
			vosotros: "descifráis",
			Uds: "descifran",
		},
		Preterite: {
			yo: "descifré",
			tú: "descifraste",
			Ud: "descifró",
			nosotros: "desciframos",
			vosotros: "descifrasteis",
			Uds: "descifraron",
		},
		Imperfect: {
			yo: "descifraba",
			tú: "descifrabas",
			Ud: "descifraba",
			nosotros: "descifrábamos",
			vosotros: "descifrabais",
			Uds: "descifraban",
		},
		Conditional: {
			yo: "descifraría",
			tú: "descifrarías",
			Ud: "descifraría",
			nosotros: "descifraríamos",
			vosotros: "descifraríais",
			Uds: "descifrarían",
		},
		Future: {
			yo: "descifraré",
			tú: "descifrarás",
			Ud: "descifrará",
			nosotros: "descifraremos",
			vosotros: "descifraréis",
			Uds: "descifrarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "descifre",
			tú: "descifres",
			Ud: "descifre",
			nosotros: "descifremos",
			vosotros: "descifréis",
			Uds: "descifren",
		},
		Imperfect: {
			yo: "descifrara",
			tú: "descifraras",
			Ud: "descifrara",
			nosotros: "descifráramos",
			vosotros: "descifrarais",
			Uds: "descifraran",
		},
		Imperfect2: {
			yo: "descifrase",
			tú: "descifrases",
			Ud: "descifrase",
			nosotros: "descifrásemos",
			vosotros: "descifraseis",
			Uds: "descifrasen",
		},
		Future: {
			yo: "descifrare",
			tú: "descifrares",
			Ud: "descifrare",
			nosotros: "descifráremos",
			vosotros: "descifrareis",
			Uds: "descifraren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "descifra",
			Ud: "descifre",
			nosotros: "descifremos",
			vosotros: "descifrad",
			Uds: "descifren",
		},
		Negative: {
			tú: "no descifres",
			Ud: "no descifre",
			nosotros: "no descifremos",
			vosotros: "no descifréis",
			Uds: "no descifren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy descifrando",
			tú: "estás descifrando",
			Ud: "está descifrando",
			nosotros: "estamos descifrando",
			vosotros: "estáis descifrando",
			Uds: "están descifrando",
		},
		Preterite: {
			yo: "estuve descifrando",
			tú: "estuviste descifrando",
			Ud: "estuvo descifrando",
			nosotros: "estuvimos descifrando",
			vosotros: "estuvisteis descifrando",
			Uds: "estuvieron descifrando",
		},
		Imperfect: {
			Uds: "estaban descifrando",
			yo: "estaba descifrando",
			tú: "estabas descifrando",
			Ud: "estaba descifrando",
			nosotros: "estábamos descifrando",
			vosotros: "estabais descifrando",
		},
		Conditional: {
			yo: "estaría descifrando",
			tú: "estarías descifrando",
			Ud: "estaría descifrando",
			nosotros: "estaríamos descifrando",
			vosotros: "estaríais descifrando",
			Uds: "estarían descifrando",
		},
		Future: {
			yo: "estaré descifrando",
			tú: "estarás descifrando",
			Ud: "estará descifrando",
			nosotros: "estaremos descifrando",
			vosotros: "estaréis descifrando",
			Uds: "estarán descifrando",
		},
	},
	Perfect: {
		Present: {
			yo: "he descifrado",
			tú: "has descifrado",
			Ud: "ha descifrado",
			nosotros: "hemos descifrado",
			vosotros: "habéis descifrado",
			Uds: "han descifrado",
		},
		Preterite: {
			yo: "hube descifrado",
			tú: "hubiste descifrado",
			Ud: "hubo descifrado",
			nosotros: "hubimos descifrado",
			vosotros: "hubisteis descifrado",
			Uds: "hubieron descifrado",
		},
		Past: {
			yo: "había descifrado",
			tú: "habías descifrado",
			Ud: "había descifrado",
			nosotros: "habíamos descifrado",
			vosotros: "habíais descifrado",
			Uds: "habían descifrado",
		},
		Conditional: {
			yo: "habría descifrado",
			tú: "habrías descifrado",
			Ud: "habría descifrado",
			nosotros: "habríamos descifrado",
			vosotros: "habríais descifrado",
			Uds: "habrían descifrado",
		},
		Future: {
			yo: "habré descifrado",
			tú: "habrás descifrado",
			Ud: "habrá descifrado",
			nosotros: "habremos descifrado",
			vosotros: "habréis descifrado",
			Uds: "habrán descifrado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya descifrado",
			tú: "hayas descifrado",
			Ud: "haya descifrado",
			nosotros: "hayamos descifrado",
			vosotros: "hayáis descifrado",
			Uds: "hayan descifrado",
		},
		Past: {
			yo: "hubiera descifrado",
			tú: "hubieras descifrado",
			Ud: "hubiera descifrado",
			nosotros: "hubiéramos descifrado",
			vosotros: "hubierais descifrado",
			Uds: "hubieran descifrado",
		},
		Future: {
			yo: "hubiere descifrado",
			tú: "hubieres descifrado",
			Ud: "hubiere descifrado",
			nosotros: "hubiéremos descifrado",
			vosotros: "hubiereis descifrado",
			Uds: "hubieren descifrado",
		},
	},
}
