var desechar = {
	Indicative: {
		Present: {
			yo: "desecho",
			tú: "desechas",
			Ud: "desecha",
			nosotros: "desechamos",
			vosotros: "desecháis",
			Uds: "desechan",
		},
		Preterite: {
			yo: "deseché",
			tú: "desechaste",
			Ud: "desechó",
			nosotros: "desechamos",
			vosotros: "desechasteis",
			Uds: "desecharon",
		},
		Imperfect: {
			yo: "desechaba",
			tú: "desechabas",
			Ud: "desechaba",
			nosotros: "desechábamos",
			vosotros: "desechabais",
			Uds: "desechaban",
		},
		Conditional: {
			yo: "desecharía",
			tú: "desecharías",
			Ud: "desecharía",
			nosotros: "desecharíamos",
			vosotros: "desecharíais",
			Uds: "desecharían",
		},
		Future: {
			yo: "desecharé",
			tú: "desecharás",
			Ud: "desechará",
			nosotros: "desecharemos",
			vosotros: "desecharéis",
			Uds: "desecharán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "deseche",
			tú: "deseches",
			Ud: "deseche",
			nosotros: "desechemos",
			vosotros: "desechéis",
			Uds: "desechen",
		},
		Imperfect: {
			yo: "desechara",
			tú: "desecharas",
			Ud: "desechara",
			nosotros: "desecháramos",
			vosotros: "desecharais",
			Uds: "desecharan",
		},
		Imperfect2: {
			yo: "desechase",
			tú: "desechases",
			Ud: "desechase",
			nosotros: "desechásemos",
			vosotros: "desechaseis",
			Uds: "desechasen",
		},
		Future: {
			yo: "desechare",
			tú: "desechares",
			Ud: "desechare",
			nosotros: "desecháremos",
			vosotros: "desechareis",
			Uds: "desecharen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "desecha",
			Ud: "deseche",
			nosotros: "desechemos",
			vosotros: "desechad",
			Uds: "desechen",
		},
		Negative: {
			tú: "no deseches",
			Ud: "no deseche",
			nosotros: "no desechemos",
			vosotros: "no desechéis",
			Uds: "no desechen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy desechando",
			tú: "estás desechando",
			Ud: "está desechando",
			nosotros: "estamos desechando",
			vosotros: "estáis desechando",
			Uds: "están desechando",
		},
		Preterite: {
			yo: "estuve desechando",
			tú: "estuviste desechando",
			Ud: "estuvo desechando",
			nosotros: "estuvimos desechando",
			vosotros: "estuvisteis desechando",
			Uds: "estuvieron desechando",
		},
		Imperfect: {
			Uds: "estaban desechando",
			yo: "estaba desechando",
			tú: "estabas desechando",
			Ud: "estaba desechando",
			nosotros: "estábamos desechando",
			vosotros: "estabais desechando",
		},
		Conditional: {
			yo: "estaría desechando",
			tú: "estarías desechando",
			Ud: "estaría desechando",
			nosotros: "estaríamos desechando",
			vosotros: "estaríais desechando",
			Uds: "estarían desechando",
		},
		Future: {
			yo: "estaré desechando",
			tú: "estarás desechando",
			Ud: "estará desechando",
			nosotros: "estaremos desechando",
			vosotros: "estaréis desechando",
			Uds: "estarán desechando",
		},
	},
	Perfect: {
		Present: {
			yo: "he desechado",
			tú: "has desechado",
			Ud: "ha desechado",
			nosotros: "hemos desechado",
			vosotros: "habéis desechado",
			Uds: "han desechado",
		},
		Preterite: {
			yo: "hube desechado",
			tú: "hubiste desechado",
			Ud: "hubo desechado",
			nosotros: "hubimos desechado",
			vosotros: "hubisteis desechado",
			Uds: "hubieron desechado",
		},
		Past: {
			yo: "había desechado",
			tú: "habías desechado",
			Ud: "había desechado",
			nosotros: "habíamos desechado",
			vosotros: "habíais desechado",
			Uds: "habían desechado",
		},
		Conditional: {
			yo: "habría desechado",
			tú: "habrías desechado",
			Ud: "habría desechado",
			nosotros: "habríamos desechado",
			vosotros: "habríais desechado",
			Uds: "habrían desechado",
		},
		Future: {
			yo: "habré desechado",
			tú: "habrás desechado",
			Ud: "habrá desechado",
			nosotros: "habremos desechado",
			vosotros: "habréis desechado",
			Uds: "habrán desechado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya desechado",
			tú: "hayas desechado",
			Ud: "haya desechado",
			nosotros: "hayamos desechado",
			vosotros: "hayáis desechado",
			Uds: "hayan desechado",
		},
		Past: {
			yo: "hubiera desechado",
			tú: "hubieras desechado",
			Ud: "hubiera desechado",
			nosotros: "hubiéramos desechado",
			vosotros: "hubierais desechado",
			Uds: "hubieran desechado",
		},
		Future: {
			yo: "hubiere desechado",
			tú: "hubieres desechado",
			Ud: "hubiere desechado",
			nosotros: "hubiéremos desechado",
			vosotros: "hubiereis desechado",
			Uds: "hubieren desechado",
		},
	},
}
