var desembarcar = {
	Indicative: {
		Present: {
			yo: "desembarco",
			tú: "desembarcas",
			Ud: "desembarca",
			nosotros: "desembarcamos",
			vosotros: "desembarcáis",
			Uds: "desembarcan",
		},
		Preterite: {
			yo: "desembarqué",
			tú: "desembarcaste",
			Ud: "desembarcó",
			nosotros: "desembarcamos",
			vosotros: "desembarcasteis",
			Uds: "desembarcaron",
		},
		Imperfect: {
			yo: "desembarcaba",
			tú: "desembarcabas",
			Ud: "desembarcaba",
			nosotros: "desembarcábamos",
			vosotros: "desembarcabais",
			Uds: "desembarcaban",
		},
		Conditional: {
			yo: "desembarcaría",
			tú: "desembarcarías",
			Ud: "desembarcaría",
			nosotros: "desembarcaríamos",
			vosotros: "desembarcaríais",
			Uds: "desembarcarían",
		},
		Future: {
			yo: "desembarcaré",
			tú: "desembarcarás",
			Ud: "desembarcará",
			nosotros: "desembarcaremos",
			vosotros: "desembarcaréis",
			Uds: "desembarcarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "desembarque",
			tú: "desembarques",
			Ud: "desembarque",
			nosotros: "desembarquemos",
			vosotros: "desembarquéis",
			Uds: "desembarquen",
		},
		Imperfect: {
			yo: "desembarcara",
			tú: "desembarcaras",
			Ud: "desembarcara",
			nosotros: "desembarcáramos",
			vosotros: "desembarcarais",
			Uds: "desembarcaran",
		},
		Imperfect2: {
			yo: "desembarcase",
			tú: "desembarcases",
			Ud: "desembarcase",
			nosotros: "desembarcásemos",
			vosotros: "desembarcaseis",
			Uds: "desembarcasen",
		},
		Future: {
			yo: "desembarcare",
			tú: "desembarcares",
			Ud: "desembarcare",
			nosotros: "desembarcáremos",
			vosotros: "desembarcareis",
			Uds: "desembarcaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "desembarca",
			Ud: "desembarque",
			nosotros: "desembarquemos",
			vosotros: "desembarcad",
			Uds: "desembarquen",
		},
		Negative: {
			tú: "no desembarques",
			Ud: "no desembarque",
			nosotros: "no desembarquemos",
			vosotros: "no desembarquéis",
			Uds: "no desembarquen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy desembarcando",
			tú: "estás desembarcando",
			Ud: "está desembarcando",
			nosotros: "estamos desembarcando",
			vosotros: "estáis desembarcando",
			Uds: "están desembarcando",
		},
		Preterite: {
			yo: "estuve desembarcando",
			tú: "estuviste desembarcando",
			Ud: "estuvo desembarcando",
			nosotros: "estuvimos desembarcando",
			vosotros: "estuvisteis desembarcando",
			Uds: "estuvieron desembarcando",
		},
		Imperfect: {
			Uds: "estaban desembarcando",
			yo: "estaba desembarcando",
			tú: "estabas desembarcando",
			Ud: "estaba desembarcando",
			nosotros: "estábamos desembarcando",
			vosotros: "estabais desembarcando",
		},
		Conditional: {
			yo: "estaría desembarcando",
			tú: "estarías desembarcando",
			Ud: "estaría desembarcando",
			nosotros: "estaríamos desembarcando",
			vosotros: "estaríais desembarcando",
			Uds: "estarían desembarcando",
		},
		Future: {
			yo: "estaré desembarcando",
			tú: "estarás desembarcando",
			Ud: "estará desembarcando",
			nosotros: "estaremos desembarcando",
			vosotros: "estaréis desembarcando",
			Uds: "estarán desembarcando",
		},
	},
	Perfect: {
		Present: {
			yo: "he desembarcado",
			tú: "has desembarcado",
			Ud: "ha desembarcado",
			nosotros: "hemos desembarcado",
			vosotros: "habéis desembarcado",
			Uds: "han desembarcado",
		},
		Preterite: {
			yo: "hube desembarcado",
			tú: "hubiste desembarcado",
			Ud: "hubo desembarcado",
			nosotros: "hubimos desembarcado",
			vosotros: "hubisteis desembarcado",
			Uds: "hubieron desembarcado",
		},
		Past: {
			yo: "había desembarcado",
			tú: "habías desembarcado",
			Ud: "había desembarcado",
			nosotros: "habíamos desembarcado",
			vosotros: "habíais desembarcado",
			Uds: "habían desembarcado",
		},
		Conditional: {
			yo: "habría desembarcado",
			tú: "habrías desembarcado",
			Ud: "habría desembarcado",
			nosotros: "habríamos desembarcado",
			vosotros: "habríais desembarcado",
			Uds: "habrían desembarcado",
		},
		Future: {
			yo: "habré desembarcado",
			tú: "habrás desembarcado",
			Ud: "habrá desembarcado",
			nosotros: "habremos desembarcado",
			vosotros: "habréis desembarcado",
			Uds: "habrán desembarcado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya desembarcado",
			tú: "hayas desembarcado",
			Ud: "haya desembarcado",
			nosotros: "hayamos desembarcado",
			vosotros: "hayáis desembarcado",
			Uds: "hayan desembarcado",
		},
		Past: {
			yo: "hubiera desembarcado",
			tú: "hubieras desembarcado",
			Ud: "hubiera desembarcado",
			nosotros: "hubiéramos desembarcado",
			vosotros: "hubierais desembarcado",
			Uds: "hubieran desembarcado",
		},
		Future: {
			yo: "hubiere desembarcado",
			tú: "hubieres desembarcado",
			Ud: "hubiere desembarcado",
			nosotros: "hubiéremos desembarcado",
			vosotros: "hubiereis desembarcado",
			Uds: "hubieren desembarcado",
		},
	},
}
