var deshilachar = {
	Indicative: {
		Present: {
			yo: "deshilacho",
			tú: "deshilachas",
			Ud: "deshilacha",
			nosotros: "deshilachamos",
			vosotros: "deshilacháis",
			Uds: "deshilachan",
		},
		Preterite: {
			yo: "deshilaché",
			tú: "deshilachaste",
			Ud: "deshilachó",
			nosotros: "deshilachamos",
			vosotros: "deshilachasteis",
			Uds: "deshilacharon",
		},
		Imperfect: {
			yo: "deshilachaba",
			tú: "deshilachabas",
			Ud: "deshilachaba",
			nosotros: "deshilachábamos",
			vosotros: "deshilachabais",
			Uds: "deshilachaban",
		},
		Conditional: {
			yo: "deshilacharía",
			tú: "deshilacharías",
			Ud: "deshilacharía",
			nosotros: "deshilacharíamos",
			vosotros: "deshilacharíais",
			Uds: "deshilacharían",
		},
		Future: {
			yo: "deshilacharé",
			tú: "deshilacharás",
			Ud: "deshilachará",
			nosotros: "deshilacharemos",
			vosotros: "deshilacharéis",
			Uds: "deshilacharán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "deshilache",
			tú: "deshilaches",
			Ud: "deshilache",
			nosotros: "deshilachemos",
			vosotros: "deshilachéis",
			Uds: "deshilachen",
		},
		Imperfect: {
			yo: "deshilachara",
			tú: "deshilacharas",
			Ud: "deshilachara",
			nosotros: "deshilacháramos",
			vosotros: "deshilacharais",
			Uds: "deshilacharan",
		},
		Imperfect2: {
			yo: "deshilachase",
			tú: "deshilachases",
			Ud: "deshilachase",
			nosotros: "deshilachásemos",
			vosotros: "deshilachaseis",
			Uds: "deshilachasen",
		},
		Future: {
			yo: "deshilachare",
			tú: "deshilachares",
			Ud: "deshilachare",
			nosotros: "deshilacháremos",
			vosotros: "deshilachareis",
			Uds: "deshilacharen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "deshilacha",
			Ud: "deshilache",
			nosotros: "deshilachemos",
			vosotros: "deshilachad",
			Uds: "deshilachen",
		},
		Negative: {
			tú: "no deshilaches",
			Ud: "no deshilache",
			nosotros: "no deshilachemos",
			vosotros: "no deshilachéis",
			Uds: "no deshilachen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy deshilachando",
			tú: "estás deshilachando",
			Ud: "está deshilachando",
			nosotros: "estamos deshilachando",
			vosotros: "estáis deshilachando",
			Uds: "están deshilachando",
		},
		Preterite: {
			yo: "estuve deshilachando",
			tú: "estuviste deshilachando",
			Ud: "estuvo deshilachando",
			nosotros: "estuvimos deshilachando",
			vosotros: "estuvisteis deshilachando",
			Uds: "estuvieron deshilachando",
		},
		Imperfect: {
			Uds: "estaban deshilachando",
			yo: "estaba deshilachando",
			tú: "estabas deshilachando",
			Ud: "estaba deshilachando",
			nosotros: "estábamos deshilachando",
			vosotros: "estabais deshilachando",
		},
		Conditional: {
			yo: "estaría deshilachando",
			tú: "estarías deshilachando",
			Ud: "estaría deshilachando",
			nosotros: "estaríamos deshilachando",
			vosotros: "estaríais deshilachando",
			Uds: "estarían deshilachando",
		},
		Future: {
			yo: "estaré deshilachando",
			tú: "estarás deshilachando",
			Ud: "estará deshilachando",
			nosotros: "estaremos deshilachando",
			vosotros: "estaréis deshilachando",
			Uds: "estarán deshilachando",
		},
	},
	Perfect: {
		Present: {
			yo: "he deshilachado",
			tú: "has deshilachado",
			Ud: "ha deshilachado",
			nosotros: "hemos deshilachado",
			vosotros: "habéis deshilachado",
			Uds: "han deshilachado",
		},
		Preterite: {
			yo: "hube deshilachado",
			tú: "hubiste deshilachado",
			Ud: "hubo deshilachado",
			nosotros: "hubimos deshilachado",
			vosotros: "hubisteis deshilachado",
			Uds: "hubieron deshilachado",
		},
		Past: {
			yo: "había deshilachado",
			tú: "habías deshilachado",
			Ud: "había deshilachado",
			nosotros: "habíamos deshilachado",
			vosotros: "habíais deshilachado",
			Uds: "habían deshilachado",
		},
		Conditional: {
			yo: "habría deshilachado",
			tú: "habrías deshilachado",
			Ud: "habría deshilachado",
			nosotros: "habríamos deshilachado",
			vosotros: "habríais deshilachado",
			Uds: "habrían deshilachado",
		},
		Future: {
			yo: "habré deshilachado",
			tú: "habrás deshilachado",
			Ud: "habrá deshilachado",
			nosotros: "habremos deshilachado",
			vosotros: "habréis deshilachado",
			Uds: "habrán deshilachado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya deshilachado",
			tú: "hayas deshilachado",
			Ud: "haya deshilachado",
			nosotros: "hayamos deshilachado",
			vosotros: "hayáis deshilachado",
			Uds: "hayan deshilachado",
		},
		Past: {
			yo: "hubiera deshilachado",
			tú: "hubieras deshilachado",
			Ud: "hubiera deshilachado",
			nosotros: "hubiéramos deshilachado",
			vosotros: "hubierais deshilachado",
			Uds: "hubieran deshilachado",
		},
		Future: {
			yo: "hubiere deshilachado",
			tú: "hubieres deshilachado",
			Ud: "hubiere deshilachado",
			nosotros: "hubiéremos deshilachado",
			vosotros: "hubiereis deshilachado",
			Uds: "hubieren deshilachado",
		},
	},
}
