var designar = {
	Indicative: {
		Present: {
			yo: "designo",
			tú: "designas",
			Ud: "designa",
			nosotros: "designamos",
			vosotros: "designáis",
			Uds: "designan",
		},
		Preterite: {
			yo: "designé",
			tú: "designaste",
			Ud: "designó",
			nosotros: "designamos",
			vosotros: "designasteis",
			Uds: "designaron",
		},
		Imperfect: {
			yo: "designaba",
			tú: "designabas",
			Ud: "designaba",
			nosotros: "designábamos",
			vosotros: "designabais",
			Uds: "designaban",
		},
		Conditional: {
			yo: "designaría",
			tú: "designarías",
			Ud: "designaría",
			nosotros: "designaríamos",
			vosotros: "designaríais",
			Uds: "designarían",
		},
		Future: {
			yo: "designaré",
			tú: "designarás",
			Ud: "designará",
			nosotros: "designaremos",
			vosotros: "designaréis",
			Uds: "designarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "designe",
			tú: "designes",
			Ud: "designe",
			nosotros: "designemos",
			vosotros: "designéis",
			Uds: "designen",
		},
		Imperfect: {
			yo: "designara",
			tú: "designaras",
			Ud: "designara",
			nosotros: "designáramos",
			vosotros: "designarais",
			Uds: "designaran",
		},
		Imperfect2: {
			yo: "designase",
			tú: "designases",
			Ud: "designase",
			nosotros: "designásemos",
			vosotros: "designaseis",
			Uds: "designasen",
		},
		Future: {
			yo: "designare",
			tú: "designares",
			Ud: "designare",
			nosotros: "designáremos",
			vosotros: "designareis",
			Uds: "designaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "designa",
			Ud: "designe",
			nosotros: "designemos",
			vosotros: "designad",
			Uds: "designen",
		},
		Negative: {
			tú: "no designes",
			Ud: "no designe",
			nosotros: "no designemos",
			vosotros: "no designéis",
			Uds: "no designen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy designando",
			tú: "estás designando",
			Ud: "está designando",
			nosotros: "estamos designando",
			vosotros: "estáis designando",
			Uds: "están designando",
		},
		Preterite: {
			yo: "estuve designando",
			tú: "estuviste designando",
			Ud: "estuvo designando",
			nosotros: "estuvimos designando",
			vosotros: "estuvisteis designando",
			Uds: "estuvieron designando",
		},
		Imperfect: {
			Uds: "estaban designando",
			yo: "estaba designando",
			tú: "estabas designando",
			Ud: "estaba designando",
			nosotros: "estábamos designando",
			vosotros: "estabais designando",
		},
		Conditional: {
			yo: "estaría designando",
			tú: "estarías designando",
			Ud: "estaría designando",
			nosotros: "estaríamos designando",
			vosotros: "estaríais designando",
			Uds: "estarían designando",
		},
		Future: {
			yo: "estaré designando",
			tú: "estarás designando",
			Ud: "estará designando",
			nosotros: "estaremos designando",
			vosotros: "estaréis designando",
			Uds: "estarán designando",
		},
	},
	Perfect: {
		Present: {
			yo: "he designado",
			tú: "has designado",
			Ud: "ha designado",
			nosotros: "hemos designado",
			vosotros: "habéis designado",
			Uds: "han designado",
		},
		Preterite: {
			yo: "hube designado",
			tú: "hubiste designado",
			Ud: "hubo designado",
			nosotros: "hubimos designado",
			vosotros: "hubisteis designado",
			Uds: "hubieron designado",
		},
		Past: {
			yo: "había designado",
			tú: "habías designado",
			Ud: "había designado",
			nosotros: "habíamos designado",
			vosotros: "habíais designado",
			Uds: "habían designado",
		},
		Conditional: {
			yo: "habría designado",
			tú: "habrías designado",
			Ud: "habría designado",
			nosotros: "habríamos designado",
			vosotros: "habríais designado",
			Uds: "habrían designado",
		},
		Future: {
			yo: "habré designado",
			tú: "habrás designado",
			Ud: "habrá designado",
			nosotros: "habremos designado",
			vosotros: "habréis designado",
			Uds: "habrán designado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya designado",
			tú: "hayas designado",
			Ud: "haya designado",
			nosotros: "hayamos designado",
			vosotros: "hayáis designado",
			Uds: "hayan designado",
		},
		Past: {
			yo: "hubiera designado",
			tú: "hubieras designado",
			Ud: "hubiera designado",
			nosotros: "hubiéramos designado",
			vosotros: "hubierais designado",
			Uds: "hubieran designado",
		},
		Future: {
			yo: "hubiere designado",
			tú: "hubieres designado",
			Ud: "hubiere designado",
			nosotros: "hubiéremos designado",
			vosotros: "hubiereis designado",
			Uds: "hubieren designado",
		},
	},
}
