var desistir = {
	Indicative: {
		Present: {
			yo: "desisto",
			tú: "desistes",
			Ud: "desiste",
			nosotros: "desistimos",
			vosotros: "desistís",
			Uds: "desisten",
		},
		Preterite: {
			yo: "desistí",
			tú: "desististe",
			Ud: "desistió",
			nosotros: "desistimos",
			vosotros: "desististeis",
			Uds: "desistieron",
		},
		Imperfect: {
			yo: "desistía",
			tú: "desistías",
			Ud: "desistía",
			nosotros: "desistíamos",
			vosotros: "desistíais",
			Uds: "desistían",
		},
		Conditional: {
			yo: "desistiría",
			tú: "desistirías",
			Ud: "desistiría",
			nosotros: "desistiríamos",
			vosotros: "desistiríais",
			Uds: "desistirían",
		},
		Future: {
			yo: "desistiré",
			tú: "desistirás",
			Ud: "desistirá",
			nosotros: "desistiremos",
			vosotros: "desistiréis",
			Uds: "desistirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "desista",
			tú: "desistas",
			Ud: "desista",
			nosotros: "desistamos",
			vosotros: "desistáis",
			Uds: "desistan",
		},
		Imperfect: {
			yo: "desistiera",
			tú: "desistieras",
			Ud: "desistiera",
			nosotros: "desistiéramos",
			vosotros: "desistierais",
			Uds: "desistieran",
		},
		Imperfect2: {
			yo: "desistiese",
			tú: "desistieses",
			Ud: "desistiese",
			nosotros: "desistiésemos",
			vosotros: "desistieseis",
			Uds: "desistiesen",
		},
		Future: {
			yo: "desistiere",
			tú: "desistieres",
			Ud: "desistiere",
			nosotros: "desistiéremos",
			vosotros: "desistiereis",
			Uds: "desistieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "desiste",
			Ud: "desista",
			nosotros: "desistamos",
			vosotros: "desistid",
			Uds: "desistan",
		},
		Negative: {
			tú: "no desistas",
			Ud: "no desista",
			nosotros: "no desistamos",
			vosotros: "no desistáis",
			Uds: "no desistan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy desistiendo",
			tú: "estás desistiendo",
			Ud: "está desistiendo",
			nosotros: "estamos desistiendo",
			vosotros: "estáis desistiendo",
			Uds: "están desistiendo",
		},
		Preterite: {
			yo: "estuve desistiendo",
			tú: "estuviste desistiendo",
			Ud: "estuvo desistiendo",
			nosotros: "estuvimos desistiendo",
			vosotros: "estuvisteis desistiendo",
			Uds: "estuvieron desistiendo",
		},
		Imperfect: {
			Uds: "estaban desistiendo",
			yo: "estaba desistiendo",
			tú: "estabas desistiendo",
			Ud: "estaba desistiendo",
			nosotros: "estábamos desistiendo",
			vosotros: "estabais desistiendo",
		},
		Conditional: {
			yo: "estaría desistiendo",
			tú: "estarías desistiendo",
			Ud: "estaría desistiendo",
			nosotros: "estaríamos desistiendo",
			vosotros: "estaríais desistiendo",
			Uds: "estarían desistiendo",
		},
		Future: {
			yo: "estaré desistiendo",
			tú: "estarás desistiendo",
			Ud: "estará desistiendo",
			nosotros: "estaremos desistiendo",
			vosotros: "estaréis desistiendo",
			Uds: "estarán desistiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he desistido",
			tú: "has desistido",
			Ud: "ha desistido",
			nosotros: "hemos desistido",
			vosotros: "habéis desistido",
			Uds: "han desistido",
		},
		Preterite: {
			yo: "hube desistido",
			tú: "hubiste desistido",
			Ud: "hubo desistido",
			nosotros: "hubimos desistido",
			vosotros: "hubisteis desistido",
			Uds: "hubieron desistido",
		},
		Past: {
			yo: "había desistido",
			tú: "habías desistido",
			Ud: "había desistido",
			nosotros: "habíamos desistido",
			vosotros: "habíais desistido",
			Uds: "habían desistido",
		},
		Conditional: {
			yo: "habría desistido",
			tú: "habrías desistido",
			Ud: "habría desistido",
			nosotros: "habríamos desistido",
			vosotros: "habríais desistido",
			Uds: "habrían desistido",
		},
		Future: {
			yo: "habré desistido",
			tú: "habrás desistido",
			Ud: "habrá desistido",
			nosotros: "habremos desistido",
			vosotros: "habréis desistido",
			Uds: "habrán desistido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya desistido",
			tú: "hayas desistido",
			Ud: "haya desistido",
			nosotros: "hayamos desistido",
			vosotros: "hayáis desistido",
			Uds: "hayan desistido",
		},
		Past: {
			yo: "hubiera desistido",
			tú: "hubieras desistido",
			Ud: "hubiera desistido",
			nosotros: "hubiéramos desistido",
			vosotros: "hubierais desistido",
			Uds: "hubieran desistido",
		},
		Future: {
			yo: "hubiere desistido",
			tú: "hubieres desistido",
			Ud: "hubiere desistido",
			nosotros: "hubiéremos desistido",
			vosotros: "hubiereis desistido",
			Uds: "hubieren desistido",
		},
	},
}
