var desintegrar = {
	Indicative: {
		Present: {
			yo: "desintegro",
			tú: "desintegras",
			Ud: "desintegra",
			nosotros: "desintegramos",
			vosotros: "desintegráis",
			Uds: "desintegran",
		},
		Preterite: {
			yo: "desintegré",
			tú: "desintegraste",
			Ud: "desintegró",
			nosotros: "desintegramos",
			vosotros: "desintegrasteis",
			Uds: "desintegraron",
		},
		Imperfect: {
			yo: "desintegraba",
			tú: "desintegrabas",
			Ud: "desintegraba",
			nosotros: "desintegrábamos",
			vosotros: "desintegrabais",
			Uds: "desintegraban",
		},
		Conditional: {
			yo: "desintegraría",
			tú: "desintegrarías",
			Ud: "desintegraría",
			nosotros: "desintegraríamos",
			vosotros: "desintegraríais",
			Uds: "desintegrarían",
		},
		Future: {
			yo: "desintegraré",
			tú: "desintegrarás",
			Ud: "desintegrará",
			nosotros: "desintegraremos",
			vosotros: "desintegraréis",
			Uds: "desintegrarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "desintegre",
			tú: "desintegres",
			Ud: "desintegre",
			nosotros: "desintegremos",
			vosotros: "desintegréis",
			Uds: "desintegren",
		},
		Imperfect: {
			yo: "desintegrara",
			tú: "desintegraras",
			Ud: "desintegrara",
			nosotros: "desintegráramos",
			vosotros: "desintegrarais",
			Uds: "desintegraran",
		},
		Imperfect2: {
			yo: "desintegrase",
			tú: "desintegrases",
			Ud: "desintegrase",
			nosotros: "desintegrásemos",
			vosotros: "desintegraseis",
			Uds: "desintegrasen",
		},
		Future: {
			yo: "desintegrare",
			tú: "desintegrares",
			Ud: "desintegrare",
			nosotros: "desintegráremos",
			vosotros: "desintegrareis",
			Uds: "desintegraren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "desintegra",
			Ud: "desintegre",
			nosotros: "desintegremos",
			vosotros: "desintegrad",
			Uds: "desintegren",
		},
		Negative: {
			tú: "no desintegres",
			Ud: "no desintegre",
			nosotros: "no desintegremos",
			vosotros: "no desintegréis",
			Uds: "no desintegren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy desintegrando",
			tú: "estás desintegrando",
			Ud: "está desintegrando",
			nosotros: "estamos desintegrando",
			vosotros: "estáis desintegrando",
			Uds: "están desintegrando",
		},
		Preterite: {
			yo: "estuve desintegrando",
			tú: "estuviste desintegrando",
			Ud: "estuvo desintegrando",
			nosotros: "estuvimos desintegrando",
			vosotros: "estuvisteis desintegrando",
			Uds: "estuvieron desintegrando",
		},
		Imperfect: {
			Uds: "estaban desintegrando",
			yo: "estaba desintegrando",
			tú: "estabas desintegrando",
			Ud: "estaba desintegrando",
			nosotros: "estábamos desintegrando",
			vosotros: "estabais desintegrando",
		},
		Conditional: {
			yo: "estaría desintegrando",
			tú: "estarías desintegrando",
			Ud: "estaría desintegrando",
			nosotros: "estaríamos desintegrando",
			vosotros: "estaríais desintegrando",
			Uds: "estarían desintegrando",
		},
		Future: {
			yo: "estaré desintegrando",
			tú: "estarás desintegrando",
			Ud: "estará desintegrando",
			nosotros: "estaremos desintegrando",
			vosotros: "estaréis desintegrando",
			Uds: "estarán desintegrando",
		},
	},
	Perfect: {
		Present: {
			yo: "he desintegrado",
			tú: "has desintegrado",
			Ud: "ha desintegrado",
			nosotros: "hemos desintegrado",
			vosotros: "habéis desintegrado",
			Uds: "han desintegrado",
		},
		Preterite: {
			yo: "hube desintegrado",
			tú: "hubiste desintegrado",
			Ud: "hubo desintegrado",
			nosotros: "hubimos desintegrado",
			vosotros: "hubisteis desintegrado",
			Uds: "hubieron desintegrado",
		},
		Past: {
			yo: "había desintegrado",
			tú: "habías desintegrado",
			Ud: "había desintegrado",
			nosotros: "habíamos desintegrado",
			vosotros: "habíais desintegrado",
			Uds: "habían desintegrado",
		},
		Conditional: {
			yo: "habría desintegrado",
			tú: "habrías desintegrado",
			Ud: "habría desintegrado",
			nosotros: "habríamos desintegrado",
			vosotros: "habríais desintegrado",
			Uds: "habrían desintegrado",
		},
		Future: {
			yo: "habré desintegrado",
			tú: "habrás desintegrado",
			Ud: "habrá desintegrado",
			nosotros: "habremos desintegrado",
			vosotros: "habréis desintegrado",
			Uds: "habrán desintegrado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya desintegrado",
			tú: "hayas desintegrado",
			Ud: "haya desintegrado",
			nosotros: "hayamos desintegrado",
			vosotros: "hayáis desintegrado",
			Uds: "hayan desintegrado",
		},
		Past: {
			yo: "hubiera desintegrado",
			tú: "hubieras desintegrado",
			Ud: "hubiera desintegrado",
			nosotros: "hubiéramos desintegrado",
			vosotros: "hubierais desintegrado",
			Uds: "hubieran desintegrado",
		},
		Future: {
			yo: "hubiere desintegrado",
			tú: "hubieres desintegrado",
			Ud: "hubiere desintegrado",
			nosotros: "hubiéremos desintegrado",
			vosotros: "hubiereis desintegrado",
			Uds: "hubieren desintegrado",
		},
	},
}
