var desocupar = {
	Indicative: {
		Present: {
			yo: "desocupo",
			tú: "desocupas",
			Ud: "desocupa",
			nosotros: "desocupamos",
			vosotros: "desocupáis",
			Uds: "desocupan",
		},
		Preterite: {
			yo: "desocupé",
			tú: "desocupaste",
			Ud: "desocupó",
			nosotros: "desocupamos",
			vosotros: "desocupasteis",
			Uds: "desocuparon",
		},
		Imperfect: {
			yo: "desocupaba",
			tú: "desocupabas",
			Ud: "desocupaba",
			nosotros: "desocupábamos",
			vosotros: "desocupabais",
			Uds: "desocupaban",
		},
		Conditional: {
			yo: "desocuparía",
			tú: "desocuparías",
			Ud: "desocuparía",
			nosotros: "desocuparíamos",
			vosotros: "desocuparíais",
			Uds: "desocuparían",
		},
		Future: {
			yo: "desocuparé",
			tú: "desocuparás",
			Ud: "desocupará",
			nosotros: "desocuparemos",
			vosotros: "desocuparéis",
			Uds: "desocuparán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "desocupe",
			tú: "desocupes",
			Ud: "desocupe",
			nosotros: "desocupemos",
			vosotros: "desocupéis",
			Uds: "desocupen",
		},
		Imperfect: {
			yo: "desocupara",
			tú: "desocuparas",
			Ud: "desocupara",
			nosotros: "desocupáramos",
			vosotros: "desocuparais",
			Uds: "desocuparan",
		},
		Imperfect2: {
			yo: "desocupase",
			tú: "desocupases",
			Ud: "desocupase",
			nosotros: "desocupásemos",
			vosotros: "desocupaseis",
			Uds: "desocupasen",
		},
		Future: {
			yo: "desocupare",
			tú: "desocupares",
			Ud: "desocupare",
			nosotros: "desocupáremos",
			vosotros: "desocupareis",
			Uds: "desocuparen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "desocupa",
			Ud: "desocupe",
			nosotros: "desocupemos",
			vosotros: "desocupad",
			Uds: "desocupen",
		},
		Negative: {
			tú: "no desocupes",
			Ud: "no desocupe",
			nosotros: "no desocupemos",
			vosotros: "no desocupéis",
			Uds: "no desocupen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy desocupando",
			tú: "estás desocupando",
			Ud: "está desocupando",
			nosotros: "estamos desocupando",
			vosotros: "estáis desocupando",
			Uds: "están desocupando",
		},
		Preterite: {
			yo: "estuve desocupando",
			tú: "estuviste desocupando",
			Ud: "estuvo desocupando",
			nosotros: "estuvimos desocupando",
			vosotros: "estuvisteis desocupando",
			Uds: "estuvieron desocupando",
		},
		Imperfect: {
			Uds: "estaban desocupando",
			yo: "estaba desocupando",
			tú: "estabas desocupando",
			Ud: "estaba desocupando",
			nosotros: "estábamos desocupando",
			vosotros: "estabais desocupando",
		},
		Conditional: {
			yo: "estaría desocupando",
			tú: "estarías desocupando",
			Ud: "estaría desocupando",
			nosotros: "estaríamos desocupando",
			vosotros: "estaríais desocupando",
			Uds: "estarían desocupando",
		},
		Future: {
			yo: "estaré desocupando",
			tú: "estarás desocupando",
			Ud: "estará desocupando",
			nosotros: "estaremos desocupando",
			vosotros: "estaréis desocupando",
			Uds: "estarán desocupando",
		},
	},
	Perfect: {
		Present: {
			yo: "he desocupado",
			tú: "has desocupado",
			Ud: "ha desocupado",
			nosotros: "hemos desocupado",
			vosotros: "habéis desocupado",
			Uds: "han desocupado",
		},
		Preterite: {
			yo: "hube desocupado",
			tú: "hubiste desocupado",
			Ud: "hubo desocupado",
			nosotros: "hubimos desocupado",
			vosotros: "hubisteis desocupado",
			Uds: "hubieron desocupado",
		},
		Past: {
			yo: "había desocupado",
			tú: "habías desocupado",
			Ud: "había desocupado",
			nosotros: "habíamos desocupado",
			vosotros: "habíais desocupado",
			Uds: "habían desocupado",
		},
		Conditional: {
			yo: "habría desocupado",
			tú: "habrías desocupado",
			Ud: "habría desocupado",
			nosotros: "habríamos desocupado",
			vosotros: "habríais desocupado",
			Uds: "habrían desocupado",
		},
		Future: {
			yo: "habré desocupado",
			tú: "habrás desocupado",
			Ud: "habrá desocupado",
			nosotros: "habremos desocupado",
			vosotros: "habréis desocupado",
			Uds: "habrán desocupado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya desocupado",
			tú: "hayas desocupado",
			Ud: "haya desocupado",
			nosotros: "hayamos desocupado",
			vosotros: "hayáis desocupado",
			Uds: "hayan desocupado",
		},
		Past: {
			yo: "hubiera desocupado",
			tú: "hubieras desocupado",
			Ud: "hubiera desocupado",
			nosotros: "hubiéramos desocupado",
			vosotros: "hubierais desocupado",
			Uds: "hubieran desocupado",
		},
		Future: {
			yo: "hubiere desocupado",
			tú: "hubieres desocupado",
			Ud: "hubiere desocupado",
			nosotros: "hubiéremos desocupado",
			vosotros: "hubiereis desocupado",
			Uds: "hubieren desocupado",
		},
	},
}
