var desplumar = {
	Indicative: {
		Present: {
			yo: "desplumo",
			tú: "desplumas",
			Ud: "despluma",
			nosotros: "desplumamos",
			vosotros: "desplumáis",
			Uds: "despluman",
		},
		Preterite: {
			yo: "desplumé",
			tú: "desplumaste",
			Ud: "desplumó",
			nosotros: "desplumamos",
			vosotros: "desplumasteis",
			Uds: "desplumaron",
		},
		Imperfect: {
			yo: "desplumaba",
			tú: "desplumabas",
			Ud: "desplumaba",
			nosotros: "desplumábamos",
			vosotros: "desplumabais",
			Uds: "desplumaban",
		},
		Conditional: {
			yo: "desplumaría",
			tú: "desplumarías",
			Ud: "desplumaría",
			nosotros: "desplumaríamos",
			vosotros: "desplumaríais",
			Uds: "desplumarían",
		},
		Future: {
			yo: "desplumaré",
			tú: "desplumarás",
			Ud: "desplumará",
			nosotros: "desplumaremos",
			vosotros: "desplumaréis",
			Uds: "desplumarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "desplume",
			tú: "desplumes",
			Ud: "desplume",
			nosotros: "desplumemos",
			vosotros: "despluméis",
			Uds: "desplumen",
		},
		Imperfect: {
			yo: "desplumara",
			tú: "desplumaras",
			Ud: "desplumara",
			nosotros: "desplumáramos",
			vosotros: "desplumarais",
			Uds: "desplumaran",
		},
		Imperfect2: {
			yo: "desplumase",
			tú: "desplumases",
			Ud: "desplumase",
			nosotros: "desplumásemos",
			vosotros: "desplumaseis",
			Uds: "desplumasen",
		},
		Future: {
			yo: "desplumare",
			tú: "desplumares",
			Ud: "desplumare",
			nosotros: "desplumáremos",
			vosotros: "desplumareis",
			Uds: "desplumaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "despluma",
			Ud: "desplume",
			nosotros: "desplumemos",
			vosotros: "desplumad",
			Uds: "desplumen",
		},
		Negative: {
			tú: "no desplumes",
			Ud: "no desplume",
			nosotros: "no desplumemos",
			vosotros: "no despluméis",
			Uds: "no desplumen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy desplumando",
			tú: "estás desplumando",
			Ud: "está desplumando",
			nosotros: "estamos desplumando",
			vosotros: "estáis desplumando",
			Uds: "están desplumando",
		},
		Preterite: {
			yo: "estuve desplumando",
			tú: "estuviste desplumando",
			Ud: "estuvo desplumando",
			nosotros: "estuvimos desplumando",
			vosotros: "estuvisteis desplumando",
			Uds: "estuvieron desplumando",
		},
		Imperfect: {
			Uds: "estaban desplumando",
			yo: "estaba desplumando",
			tú: "estabas desplumando",
			Ud: "estaba desplumando",
			nosotros: "estábamos desplumando",
			vosotros: "estabais desplumando",
		},
		Conditional: {
			yo: "estaría desplumando",
			tú: "estarías desplumando",
			Ud: "estaría desplumando",
			nosotros: "estaríamos desplumando",
			vosotros: "estaríais desplumando",
			Uds: "estarían desplumando",
		},
		Future: {
			yo: "estaré desplumando",
			tú: "estarás desplumando",
			Ud: "estará desplumando",
			nosotros: "estaremos desplumando",
			vosotros: "estaréis desplumando",
			Uds: "estarán desplumando",
		},
	},
	Perfect: {
		Present: {
			yo: "he desplumado",
			tú: "has desplumado",
			Ud: "ha desplumado",
			nosotros: "hemos desplumado",
			vosotros: "habéis desplumado",
			Uds: "han desplumado",
		},
		Preterite: {
			yo: "hube desplumado",
			tú: "hubiste desplumado",
			Ud: "hubo desplumado",
			nosotros: "hubimos desplumado",
			vosotros: "hubisteis desplumado",
			Uds: "hubieron desplumado",
		},
		Past: {
			yo: "había desplumado",
			tú: "habías desplumado",
			Ud: "había desplumado",
			nosotros: "habíamos desplumado",
			vosotros: "habíais desplumado",
			Uds: "habían desplumado",
		},
		Conditional: {
			yo: "habría desplumado",
			tú: "habrías desplumado",
			Ud: "habría desplumado",
			nosotros: "habríamos desplumado",
			vosotros: "habríais desplumado",
			Uds: "habrían desplumado",
		},
		Future: {
			yo: "habré desplumado",
			tú: "habrás desplumado",
			Ud: "habrá desplumado",
			nosotros: "habremos desplumado",
			vosotros: "habréis desplumado",
			Uds: "habrán desplumado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya desplumado",
			tú: "hayas desplumado",
			Ud: "haya desplumado",
			nosotros: "hayamos desplumado",
			vosotros: "hayáis desplumado",
			Uds: "hayan desplumado",
		},
		Past: {
			yo: "hubiera desplumado",
			tú: "hubieras desplumado",
			Ud: "hubiera desplumado",
			nosotros: "hubiéramos desplumado",
			vosotros: "hubierais desplumado",
			Uds: "hubieran desplumado",
		},
		Future: {
			yo: "hubiere desplumado",
			tú: "hubieres desplumado",
			Ud: "hubiere desplumado",
			nosotros: "hubiéremos desplumado",
			vosotros: "hubiereis desplumado",
			Uds: "hubieren desplumado",
		},
	},
}
