var despertar = {
	Indicative: {
		Present: {
			yo: "despierto",
			tú: "despiertas",
			Ud: "despierta",
			nosotros: "despertamos",
			vosotros: "despertáis",
			Uds: "despiertan",
		},
		Preterite: {
			yo: "desperté",
			tú: "despertaste",
			Ud: "despertó",
			nosotros: "despertamos",
			vosotros: "despertasteis",
			Uds: "despertaron",
		},
		Imperfect: {
			yo: "despertaba",
			tú: "despertabas",
			Ud: "despertaba",
			nosotros: "despertábamos",
			vosotros: "despertabais",
			Uds: "despertaban",
		},
		Conditional: {
			yo: "despertaría",
			tú: "despertarías",
			Ud: "despertaría",
			nosotros: "despertaríamos",
			vosotros: "despertaríais",
			Uds: "despertarían",
		},
		Future: {
			yo: "despertaré",
			tú: "despertarás",
			Ud: "despertará",
			nosotros: "despertaremos",
			vosotros: "despertaréis",
			Uds: "despertarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "despierte",
			tú: "despiertes",
			Ud: "despierte",
			nosotros: "despertemos",
			vosotros: "despertéis",
			Uds: "despierten",
		},
		Imperfect: {
			yo: "despertara",
			tú: "despertaras",
			Ud: "despertara",
			nosotros: "despertáramos",
			vosotros: "despertarais",
			Uds: "despertaran",
		},
		Imperfect2: {
			yo: "despertase",
			tú: "despertases",
			Ud: "despertase",
			nosotros: "despertásemos",
			vosotros: "despertaseis",
			Uds: "despertasen",
		},
		Future: {
			yo: "despertare",
			tú: "despertares",
			Ud: "despertare",
			nosotros: "despertáremos",
			vosotros: "despertareis",
			Uds: "despertaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "despierta",
			Ud: "despierte",
			nosotros: "despertemos",
			vosotros: "despertad",
			Uds: "despierten",
		},
		Negative: {
			tú: "no despiertes",
			Ud: "no despierte",
			nosotros: "no despertemos",
			vosotros: "no despertéis",
			Uds: "no despierten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy despertando",
			tú: "estás despertando",
			Ud: "está despertando",
			nosotros: "estamos despertando",
			vosotros: "estáis despertando",
			Uds: "están despertando",
		},
		Preterite: {
			yo: "estuve despertando",
			tú: "estuviste despertando",
			Ud: "estuvo despertando",
			nosotros: "estuvimos despertando",
			vosotros: "estuvisteis despertando",
			Uds: "estuvieron despertando",
		},
		Imperfect: {
			Uds: "estaban despertando",
			yo: "estaba despertando",
			tú: "estabas despertando",
			Ud: "estaba despertando",
			nosotros: "estábamos despertando",
			vosotros: "estabais despertando",
		},
		Conditional: {
			yo: "estaría despertando",
			tú: "estarías despertando",
			Ud: "estaría despertando",
			nosotros: "estaríamos despertando",
			vosotros: "estaríais despertando",
			Uds: "estarían despertando",
		},
		Future: {
			yo: "estaré despertando",
			tú: "estarás despertando",
			Ud: "estará despertando",
			nosotros: "estaremos despertando",
			vosotros: "estaréis despertando",
			Uds: "estarán despertando",
		},
	},
	Perfect: {
		Present: {
			yo: "he despertado",
			tú: "has despertado",
			Ud: "ha despertado",
			nosotros: "hemos despertado",
			vosotros: "habéis despertado",
			Uds: "han despertado",
		},
		Preterite: {
			yo: "hube despertado",
			tú: "hubiste despertado",
			Ud: "hubo despertado",
			nosotros: "hubimos despertado",
			vosotros: "hubisteis despertado",
			Uds: "hubieron despertado",
		},
		Past: {
			yo: "había despertado",
			tú: "habías despertado",
			Ud: "había despertado",
			nosotros: "habíamos despertado",
			vosotros: "habíais despertado",
			Uds: "habían despertado",
		},
		Conditional: {
			yo: "habría despertado",
			tú: "habrías despertado",
			Ud: "habría despertado",
			nosotros: "habríamos despertado",
			vosotros: "habríais despertado",
			Uds: "habrían despertado",
		},
		Future: {
			yo: "habré despertado",
			tú: "habrás despertado",
			Ud: "habrá despertado",
			nosotros: "habremos despertado",
			vosotros: "habréis despertado",
			Uds: "habrán despertado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya despertado",
			tú: "hayas despertado",
			Ud: "haya despertado",
			nosotros: "hayamos despertado",
			vosotros: "hayáis despertado",
			Uds: "hayan despertado",
		},
		Past: {
			yo: "hubiera despertado",
			tú: "hubieras despertado",
			Ud: "hubiera despertado",
			nosotros: "hubiéramos despertado",
			vosotros: "hubierais despertado",
			Uds: "hubieran despertado",
		},
		Future: {
			yo: "hubiere despertado",
			tú: "hubieres despertado",
			Ud: "hubiere despertado",
			nosotros: "hubiéremos despertado",
			vosotros: "hubiereis despertado",
			Uds: "hubieren despertado",
		},
	},
}
