var despachar = {
	Indicative: {
		Present: {
			yo: "despacho",
			tú: "despachas",
			Ud: "despacha",
			nosotros: "despachamos",
			vosotros: "despacháis",
			Uds: "despachan",
		},
		Preterite: {
			yo: "despaché",
			tú: "despachaste",
			Ud: "despachó",
			nosotros: "despachamos",
			vosotros: "despachasteis",
			Uds: "despacharon",
		},
		Imperfect: {
			yo: "despachaba",
			tú: "despachabas",
			Ud: "despachaba",
			nosotros: "despachábamos",
			vosotros: "despachabais",
			Uds: "despachaban",
		},
		Conditional: {
			yo: "despacharía",
			tú: "despacharías",
			Ud: "despacharía",
			nosotros: "despacharíamos",
			vosotros: "despacharíais",
			Uds: "despacharían",
		},
		Future: {
			yo: "despacharé",
			tú: "despacharás",
			Ud: "despachará",
			nosotros: "despacharemos",
			vosotros: "despacharéis",
			Uds: "despacharán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "despache",
			tú: "despaches",
			Ud: "despache",
			nosotros: "despachemos",
			vosotros: "despachéis",
			Uds: "despachen",
		},
		Imperfect: {
			yo: "despachara",
			tú: "despacharas",
			Ud: "despachara",
			nosotros: "despacháramos",
			vosotros: "despacharais",
			Uds: "despacharan",
		},
		Imperfect2: {
			yo: "despachase",
			tú: "despachases",
			Ud: "despachase",
			nosotros: "despachásemos",
			vosotros: "despachaseis",
			Uds: "despachasen",
		},
		Future: {
			yo: "despachare",
			tú: "despachares",
			Ud: "despachare",
			nosotros: "despacháremos",
			vosotros: "despachareis",
			Uds: "despacharen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "despacha",
			Ud: "despache",
			nosotros: "despachemos",
			vosotros: "despachad",
			Uds: "despachen",
		},
		Negative: {
			tú: "no despaches",
			Ud: "no despache",
			nosotros: "no despachemos",
			vosotros: "no despachéis",
			Uds: "no despachen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy despachando",
			tú: "estás despachando",
			Ud: "está despachando",
			nosotros: "estamos despachando",
			vosotros: "estáis despachando",
			Uds: "están despachando",
		},
		Preterite: {
			yo: "estuve despachando",
			tú: "estuviste despachando",
			Ud: "estuvo despachando",
			nosotros: "estuvimos despachando",
			vosotros: "estuvisteis despachando",
			Uds: "estuvieron despachando",
		},
		Imperfect: {
			Uds: "estaban despachando",
			yo: "estaba despachando",
			tú: "estabas despachando",
			Ud: "estaba despachando",
			nosotros: "estábamos despachando",
			vosotros: "estabais despachando",
		},
		Conditional: {
			yo: "estaría despachando",
			tú: "estarías despachando",
			Ud: "estaría despachando",
			nosotros: "estaríamos despachando",
			vosotros: "estaríais despachando",
			Uds: "estarían despachando",
		},
		Future: {
			yo: "estaré despachando",
			tú: "estarás despachando",
			Ud: "estará despachando",
			nosotros: "estaremos despachando",
			vosotros: "estaréis despachando",
			Uds: "estarán despachando",
		},
	},
	Perfect: {
		Present: {
			yo: "he despachado",
			tú: "has despachado",
			Ud: "ha despachado",
			nosotros: "hemos despachado",
			vosotros: "habéis despachado",
			Uds: "han despachado",
		},
		Preterite: {
			yo: "hube despachado",
			tú: "hubiste despachado",
			Ud: "hubo despachado",
			nosotros: "hubimos despachado",
			vosotros: "hubisteis despachado",
			Uds: "hubieron despachado",
		},
		Past: {
			yo: "había despachado",
			tú: "habías despachado",
			Ud: "había despachado",
			nosotros: "habíamos despachado",
			vosotros: "habíais despachado",
			Uds: "habían despachado",
		},
		Conditional: {
			yo: "habría despachado",
			tú: "habrías despachado",
			Ud: "habría despachado",
			nosotros: "habríamos despachado",
			vosotros: "habríais despachado",
			Uds: "habrían despachado",
		},
		Future: {
			yo: "habré despachado",
			tú: "habrás despachado",
			Ud: "habrá despachado",
			nosotros: "habremos despachado",
			vosotros: "habréis despachado",
			Uds: "habrán despachado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya despachado",
			tú: "hayas despachado",
			Ud: "haya despachado",
			nosotros: "hayamos despachado",
			vosotros: "hayáis despachado",
			Uds: "hayan despachado",
		},
		Past: {
			yo: "hubiera despachado",
			tú: "hubieras despachado",
			Ud: "hubiera despachado",
			nosotros: "hubiéramos despachado",
			vosotros: "hubierais despachado",
			Uds: "hubieran despachado",
		},
		Future: {
			yo: "hubiere despachado",
			tú: "hubieres despachado",
			Ud: "hubiere despachado",
			nosotros: "hubiéremos despachado",
			vosotros: "hubiereis despachado",
			Uds: "hubieren despachado",
		},
	},
}
