var desplegar = {
	Indicative: {
		Present: {
			yo: "despliego",
			tú: "despliegas",
			Ud: "despliega",
			nosotros: "desplegamos",
			vosotros: "desplegáis",
			Uds: "despliegan",
		},
		Preterite: {
			yo: "desplegué",
			tú: "desplegaste",
			Ud: "desplegó",
			nosotros: "desplegamos",
			vosotros: "desplegasteis",
			Uds: "desplegaron",
		},
		Imperfect: {
			yo: "desplegaba",
			tú: "desplegabas",
			Ud: "desplegaba",
			nosotros: "desplegábamos",
			vosotros: "desplegabais",
			Uds: "desplegaban",
		},
		Conditional: {
			yo: "desplegaría",
			tú: "desplegarías",
			Ud: "desplegaría",
			nosotros: "desplegaríamos",
			vosotros: "desplegaríais",
			Uds: "desplegarían",
		},
		Future: {
			yo: "desplegaré",
			tú: "desplegarás",
			Ud: "desplegará",
			nosotros: "desplegaremos",
			vosotros: "desplegaréis",
			Uds: "desplegarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "despliegue",
			tú: "despliegues",
			Ud: "despliegue",
			nosotros: "despleguemos",
			vosotros: "despleguéis",
			Uds: "desplieguen",
		},
		Imperfect: {
			yo: "desplegara",
			tú: "desplegaras",
			Ud: "desplegara",
			nosotros: "desplegáramos",
			vosotros: "desplegarais",
			Uds: "desplegaran",
		},
		Imperfect2: {
			yo: "desplegase",
			tú: "desplegases",
			Ud: "desplegase",
			nosotros: "desplegásemos",
			vosotros: "desplegaseis",
			Uds: "desplegasen",
		},
		Future: {
			yo: "desplegare",
			tú: "desplegares",
			Ud: "desplegare",
			nosotros: "desplegáremos",
			vosotros: "desplegareis",
			Uds: "desplegaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "despliega",
			Ud: "despliegue",
			nosotros: "despleguemos",
			vosotros: "desplegad",
			Uds: "desplieguen",
		},
		Negative: {
			tú: "no despliegues",
			Ud: "no despliegue",
			nosotros: "no despleguemos",
			vosotros: "no despleguéis",
			Uds: "no desplieguen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy desplegando",
			tú: "estás desplegando",
			Ud: "está desplegando",
			nosotros: "estamos desplegando",
			vosotros: "estáis desplegando",
			Uds: "están desplegando",
		},
		Preterite: {
			yo: "estuve desplegando",
			tú: "estuviste desplegando",
			Ud: "estuvo desplegando",
			nosotros: "estuvimos desplegando",
			vosotros: "estuvisteis desplegando",
			Uds: "estuvieron desplegando",
		},
		Imperfect: {
			Uds: "estaban desplegando",
			yo: "estaba desplegando",
			tú: "estabas desplegando",
			Ud: "estaba desplegando",
			nosotros: "estábamos desplegando",
			vosotros: "estabais desplegando",
		},
		Conditional: {
			yo: "estaría desplegando",
			tú: "estarías desplegando",
			Ud: "estaría desplegando",
			nosotros: "estaríamos desplegando",
			vosotros: "estaríais desplegando",
			Uds: "estarían desplegando",
		},
		Future: {
			yo: "estaré desplegando",
			tú: "estarás desplegando",
			Ud: "estará desplegando",
			nosotros: "estaremos desplegando",
			vosotros: "estaréis desplegando",
			Uds: "estarán desplegando",
		},
	},
	Perfect: {
		Present: {
			yo: "he desplegado",
			tú: "has desplegado",
			Ud: "ha desplegado",
			nosotros: "hemos desplegado",
			vosotros: "habéis desplegado",
			Uds: "han desplegado",
		},
		Preterite: {
			yo: "hube desplegado",
			tú: "hubiste desplegado",
			Ud: "hubo desplegado",
			nosotros: "hubimos desplegado",
			vosotros: "hubisteis desplegado",
			Uds: "hubieron desplegado",
		},
		Past: {
			yo: "había desplegado",
			tú: "habías desplegado",
			Ud: "había desplegado",
			nosotros: "habíamos desplegado",
			vosotros: "habíais desplegado",
			Uds: "habían desplegado",
		},
		Conditional: {
			yo: "habría desplegado",
			tú: "habrías desplegado",
			Ud: "habría desplegado",
			nosotros: "habríamos desplegado",
			vosotros: "habríais desplegado",
			Uds: "habrían desplegado",
		},
		Future: {
			yo: "habré desplegado",
			tú: "habrás desplegado",
			Ud: "habrá desplegado",
			nosotros: "habremos desplegado",
			vosotros: "habréis desplegado",
			Uds: "habrán desplegado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya desplegado",
			tú: "hayas desplegado",
			Ud: "haya desplegado",
			nosotros: "hayamos desplegado",
			vosotros: "hayáis desplegado",
			Uds: "hayan desplegado",
		},
		Past: {
			yo: "hubiera desplegado",
			tú: "hubieras desplegado",
			Ud: "hubiera desplegado",
			nosotros: "hubiéramos desplegado",
			vosotros: "hubierais desplegado",
			Uds: "hubieran desplegado",
		},
		Future: {
			yo: "hubiere desplegado",
			tú: "hubieres desplegado",
			Ud: "hubiere desplegado",
			nosotros: "hubiéremos desplegado",
			vosotros: "hubiereis desplegado",
			Uds: "hubieren desplegado",
		},
	},
}
