var despreciar = {
	Indicative: {
		Present: {
			yo: "desprecio",
			tú: "desprecias",
			Ud: "desprecia",
			nosotros: "despreciamos",
			vosotros: "despreciáis",
			Uds: "desprecian",
		},
		Preterite: {
			yo: "desprecié",
			tú: "despreciaste",
			Ud: "despreció",
			nosotros: "despreciamos",
			vosotros: "despreciasteis",
			Uds: "despreciaron",
		},
		Imperfect: {
			yo: "despreciaba",
			tú: "despreciabas",
			Ud: "despreciaba",
			nosotros: "despreciábamos",
			vosotros: "despreciabais",
			Uds: "despreciaban",
		},
		Conditional: {
			yo: "despreciaría",
			tú: "despreciarías",
			Ud: "despreciaría",
			nosotros: "despreciaríamos",
			vosotros: "despreciaríais",
			Uds: "despreciarían",
		},
		Future: {
			yo: "despreciaré",
			tú: "despreciarás",
			Ud: "despreciará",
			nosotros: "despreciaremos",
			vosotros: "despreciaréis",
			Uds: "despreciarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "desprecie",
			tú: "desprecies",
			Ud: "desprecie",
			nosotros: "despreciemos",
			vosotros: "despreciéis",
			Uds: "desprecien",
		},
		Imperfect: {
			yo: "despreciara",
			tú: "despreciaras",
			Ud: "despreciara",
			nosotros: "despreciáramos",
			vosotros: "despreciarais",
			Uds: "despreciaran",
		},
		Imperfect2: {
			yo: "despreciase",
			tú: "despreciases",
			Ud: "despreciase",
			nosotros: "despreciásemos",
			vosotros: "despreciaseis",
			Uds: "despreciasen",
		},
		Future: {
			yo: "despreciare",
			tú: "despreciares",
			Ud: "despreciare",
			nosotros: "despreciáremos",
			vosotros: "despreciareis",
			Uds: "despreciaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "desprecia",
			Ud: "desprecie",
			nosotros: "despreciemos",
			vosotros: "despreciad",
			Uds: "desprecien",
		},
		Negative: {
			tú: "no desprecies",
			Ud: "no desprecie",
			nosotros: "no despreciemos",
			vosotros: "no despreciéis",
			Uds: "no desprecien",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy despreciando",
			tú: "estás despreciando",
			Ud: "está despreciando",
			nosotros: "estamos despreciando",
			vosotros: "estáis despreciando",
			Uds: "están despreciando",
		},
		Preterite: {
			yo: "estuve despreciando",
			tú: "estuviste despreciando",
			Ud: "estuvo despreciando",
			nosotros: "estuvimos despreciando",
			vosotros: "estuvisteis despreciando",
			Uds: "estuvieron despreciando",
		},
		Imperfect: {
			Uds: "estaban despreciando",
			yo: "estaba despreciando",
			tú: "estabas despreciando",
			Ud: "estaba despreciando",
			nosotros: "estábamos despreciando",
			vosotros: "estabais despreciando",
		},
		Conditional: {
			yo: "estaría despreciando",
			tú: "estarías despreciando",
			Ud: "estaría despreciando",
			nosotros: "estaríamos despreciando",
			vosotros: "estaríais despreciando",
			Uds: "estarían despreciando",
		},
		Future: {
			yo: "estaré despreciando",
			tú: "estarás despreciando",
			Ud: "estará despreciando",
			nosotros: "estaremos despreciando",
			vosotros: "estaréis despreciando",
			Uds: "estarán despreciando",
		},
	},
	Perfect: {
		Present: {
			yo: "he despreciado",
			tú: "has despreciado",
			Ud: "ha despreciado",
			nosotros: "hemos despreciado",
			vosotros: "habéis despreciado",
			Uds: "han despreciado",
		},
		Preterite: {
			yo: "hube despreciado",
			tú: "hubiste despreciado",
			Ud: "hubo despreciado",
			nosotros: "hubimos despreciado",
			vosotros: "hubisteis despreciado",
			Uds: "hubieron despreciado",
		},
		Past: {
			yo: "había despreciado",
			tú: "habías despreciado",
			Ud: "había despreciado",
			nosotros: "habíamos despreciado",
			vosotros: "habíais despreciado",
			Uds: "habían despreciado",
		},
		Conditional: {
			yo: "habría despreciado",
			tú: "habrías despreciado",
			Ud: "habría despreciado",
			nosotros: "habríamos despreciado",
			vosotros: "habríais despreciado",
			Uds: "habrían despreciado",
		},
		Future: {
			yo: "habré despreciado",
			tú: "habrás despreciado",
			Ud: "habrá despreciado",
			nosotros: "habremos despreciado",
			vosotros: "habréis despreciado",
			Uds: "habrán despreciado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya despreciado",
			tú: "hayas despreciado",
			Ud: "haya despreciado",
			nosotros: "hayamos despreciado",
			vosotros: "hayáis despreciado",
			Uds: "hayan despreciado",
		},
		Past: {
			yo: "hubiera despreciado",
			tú: "hubieras despreciado",
			Ud: "hubiera despreciado",
			nosotros: "hubiéramos despreciado",
			vosotros: "hubierais despreciado",
			Uds: "hubieran despreciado",
		},
		Future: {
			yo: "hubiere despreciado",
			tú: "hubieres despreciado",
			Ud: "hubiere despreciado",
			nosotros: "hubiéremos despreciado",
			vosotros: "hubiereis despreciado",
			Uds: "hubieren despreciado",
		},
	},
}
