var destornillar = {
	Indicative: {
		Present: {
			yo: "destornillo",
			tú: "destornillas",
			Ud: "destornilla",
			nosotros: "destornillamos",
			vosotros: "destornilláis",
			Uds: "destornillan",
		},
		Preterite: {
			yo: "destornillé",
			tú: "destornillaste",
			Ud: "destornilló",
			nosotros: "destornillamos",
			vosotros: "destornillasteis",
			Uds: "destornillaron",
		},
		Imperfect: {
			yo: "destornillaba",
			tú: "destornillabas",
			Ud: "destornillaba",
			nosotros: "destornillábamos",
			vosotros: "destornillabais",
			Uds: "destornillaban",
		},
		Conditional: {
			yo: "destornillaría",
			tú: "destornillarías",
			Ud: "destornillaría",
			nosotros: "destornillaríamos",
			vosotros: "destornillaríais",
			Uds: "destornillarían",
		},
		Future: {
			yo: "destornillaré",
			tú: "destornillarás",
			Ud: "destornillará",
			nosotros: "destornillaremos",
			vosotros: "destornillaréis",
			Uds: "destornillarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "destornille",
			tú: "destornilles",
			Ud: "destornille",
			nosotros: "destornillemos",
			vosotros: "destornilléis",
			Uds: "destornillen",
		},
		Imperfect: {
			yo: "destornillara",
			tú: "destornillaras",
			Ud: "destornillara",
			nosotros: "destornilláramos",
			vosotros: "destornillarais",
			Uds: "destornillaran",
		},
		Imperfect2: {
			yo: "destornillase",
			tú: "destornillases",
			Ud: "destornillase",
			nosotros: "destornillásemos",
			vosotros: "destornillaseis",
			Uds: "destornillasen",
		},
		Future: {
			yo: "destornillare",
			tú: "destornillares",
			Ud: "destornillare",
			nosotros: "destornilláremos",
			vosotros: "destornillareis",
			Uds: "destornillaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "destornilla",
			Ud: "destornille",
			nosotros: "destornillemos",
			vosotros: "destornillad",
			Uds: "destornillen",
		},
		Negative: {
			tú: "no destornilles",
			Ud: "no destornille",
			nosotros: "no destornillemos",
			vosotros: "no destornilléis",
			Uds: "no destornillen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy destornillando",
			tú: "estás destornillando",
			Ud: "está destornillando",
			nosotros: "estamos destornillando",
			vosotros: "estáis destornillando",
			Uds: "están destornillando",
		},
		Preterite: {
			yo: "estuve destornillando",
			tú: "estuviste destornillando",
			Ud: "estuvo destornillando",
			nosotros: "estuvimos destornillando",
			vosotros: "estuvisteis destornillando",
			Uds: "estuvieron destornillando",
		},
		Imperfect: {
			Uds: "estaban destornillando",
			yo: "estaba destornillando",
			tú: "estabas destornillando",
			Ud: "estaba destornillando",
			nosotros: "estábamos destornillando",
			vosotros: "estabais destornillando",
		},
		Conditional: {
			yo: "estaría destornillando",
			tú: "estarías destornillando",
			Ud: "estaría destornillando",
			nosotros: "estaríamos destornillando",
			vosotros: "estaríais destornillando",
			Uds: "estarían destornillando",
		},
		Future: {
			yo: "estaré destornillando",
			tú: "estarás destornillando",
			Ud: "estará destornillando",
			nosotros: "estaremos destornillando",
			vosotros: "estaréis destornillando",
			Uds: "estarán destornillando",
		},
	},
	Perfect: {
		Present: {
			yo: "he destornillado",
			tú: "has destornillado",
			Ud: "ha destornillado",
			nosotros: "hemos destornillado",
			vosotros: "habéis destornillado",
			Uds: "han destornillado",
		},
		Preterite: {
			yo: "hube destornillado",
			tú: "hubiste destornillado",
			Ud: "hubo destornillado",
			nosotros: "hubimos destornillado",
			vosotros: "hubisteis destornillado",
			Uds: "hubieron destornillado",
		},
		Past: {
			yo: "había destornillado",
			tú: "habías destornillado",
			Ud: "había destornillado",
			nosotros: "habíamos destornillado",
			vosotros: "habíais destornillado",
			Uds: "habían destornillado",
		},
		Conditional: {
			yo: "habría destornillado",
			tú: "habrías destornillado",
			Ud: "habría destornillado",
			nosotros: "habríamos destornillado",
			vosotros: "habríais destornillado",
			Uds: "habrían destornillado",
		},
		Future: {
			yo: "habré destornillado",
			tú: "habrás destornillado",
			Ud: "habrá destornillado",
			nosotros: "habremos destornillado",
			vosotros: "habréis destornillado",
			Uds: "habrán destornillado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya destornillado",
			tú: "hayas destornillado",
			Ud: "haya destornillado",
			nosotros: "hayamos destornillado",
			vosotros: "hayáis destornillado",
			Uds: "hayan destornillado",
		},
		Past: {
			yo: "hubiera destornillado",
			tú: "hubieras destornillado",
			Ud: "hubiera destornillado",
			nosotros: "hubiéramos destornillado",
			vosotros: "hubierais destornillado",
			Uds: "hubieran destornillado",
		},
		Future: {
			yo: "hubiere destornillado",
			tú: "hubieres destornillado",
			Ud: "hubiere destornillado",
			nosotros: "hubiéremos destornillado",
			vosotros: "hubiereis destornillado",
			Uds: "hubieren destornillado",
		},
	},
}
