var dibujar = {
	Indicative: {
		Present: {
			yo: "dibujo",
			tú: "dibujas",
			Ud: "dibuja",
			nosotros: "dibujamos",
			vosotros: "dibujáis",
			Uds: "dibujan",
		},
		Preterite: {
			yo: "dibujé",
			tú: "dibujaste",
			Ud: "dibujó",
			nosotros: "dibujamos",
			vosotros: "dibujasteis",
			Uds: "dibujaron",
		},
		Imperfect: {
			yo: "dibujaba",
			tú: "dibujabas",
			Ud: "dibujaba",
			nosotros: "dibujábamos",
			vosotros: "dibujabais",
			Uds: "dibujaban",
		},
		Conditional: {
			yo: "dibujaría",
			tú: "dibujarías",
			Ud: "dibujaría",
			nosotros: "dibujaríamos",
			vosotros: "dibujaríais",
			Uds: "dibujarían",
		},
		Future: {
			yo: "dibujaré",
			tú: "dibujarás",
			Ud: "dibujará",
			nosotros: "dibujaremos",
			vosotros: "dibujaréis",
			Uds: "dibujarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "dibuje",
			tú: "dibujes",
			Ud: "dibuje",
			nosotros: "dibujemos",
			vosotros: "dibujéis",
			Uds: "dibujen",
		},
		Imperfect: {
			yo: "dibujara",
			tú: "dibujaras",
			Ud: "dibujara",
			nosotros: "dibujáramos",
			vosotros: "dibujarais",
			Uds: "dibujaran",
		},
		Imperfect2: {
			yo: "dibujase",
			tú: "dibujases",
			Ud: "dibujase",
			nosotros: "dibujásemos",
			vosotros: "dibujaseis",
			Uds: "dibujasen",
		},
		Future: {
			yo: "dibujare",
			tú: "dibujares",
			Ud: "dibujare",
			nosotros: "dibujáremos",
			vosotros: "dibujareis",
			Uds: "dibujaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "dibuja",
			Ud: "dibuje",
			nosotros: "dibujemos",
			vosotros: "dibujad",
			Uds: "dibujen",
		},
		Negative: {
			tú: "no dibujes",
			Ud: "no dibuje",
			nosotros: "no dibujemos",
			vosotros: "no dibujéis",
			Uds: "no dibujen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy dibujando",
			tú: "estás dibujando",
			Ud: "está dibujando",
			nosotros: "estamos dibujando",
			vosotros: "estáis dibujando",
			Uds: "están dibujando",
		},
		Preterite: {
			yo: "estuve dibujando",
			tú: "estuviste dibujando",
			Ud: "estuvo dibujando",
			nosotros: "estuvimos dibujando",
			vosotros: "estuvisteis dibujando",
			Uds: "estuvieron dibujando",
		},
		Imperfect: {
			Uds: "estaban dibujando",
			yo: "estaba dibujando",
			tú: "estabas dibujando",
			Ud: "estaba dibujando",
			nosotros: "estábamos dibujando",
			vosotros: "estabais dibujando",
		},
		Conditional: {
			yo: "estaría dibujando",
			tú: "estarías dibujando",
			Ud: "estaría dibujando",
			nosotros: "estaríamos dibujando",
			vosotros: "estaríais dibujando",
			Uds: "estarían dibujando",
		},
		Future: {
			yo: "estaré dibujando",
			tú: "estarás dibujando",
			Ud: "estará dibujando",
			nosotros: "estaremos dibujando",
			vosotros: "estaréis dibujando",
			Uds: "estarán dibujando",
		},
	},
	Perfect: {
		Present: {
			yo: "he dibujado",
			tú: "has dibujado",
			Ud: "ha dibujado",
			nosotros: "hemos dibujado",
			vosotros: "habéis dibujado",
			Uds: "han dibujado",
		},
		Preterite: {
			yo: "hube dibujado",
			tú: "hubiste dibujado",
			Ud: "hubo dibujado",
			nosotros: "hubimos dibujado",
			vosotros: "hubisteis dibujado",
			Uds: "hubieron dibujado",
		},
		Past: {
			yo: "había dibujado",
			tú: "habías dibujado",
			Ud: "había dibujado",
			nosotros: "habíamos dibujado",
			vosotros: "habíais dibujado",
			Uds: "habían dibujado",
		},
		Conditional: {
			yo: "habría dibujado",
			tú: "habrías dibujado",
			Ud: "habría dibujado",
			nosotros: "habríamos dibujado",
			vosotros: "habríais dibujado",
			Uds: "habrían dibujado",
		},
		Future: {
			yo: "habré dibujado",
			tú: "habrás dibujado",
			Ud: "habrá dibujado",
			nosotros: "habremos dibujado",
			vosotros: "habréis dibujado",
			Uds: "habrán dibujado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya dibujado",
			tú: "hayas dibujado",
			Ud: "haya dibujado",
			nosotros: "hayamos dibujado",
			vosotros: "hayáis dibujado",
			Uds: "hayan dibujado",
		},
		Past: {
			yo: "hubiera dibujado",
			tú: "hubieras dibujado",
			Ud: "hubiera dibujado",
			nosotros: "hubiéramos dibujado",
			vosotros: "hubierais dibujado",
			Uds: "hubieran dibujado",
		},
		Future: {
			yo: "hubiere dibujado",
			tú: "hubieres dibujado",
			Ud: "hubiere dibujado",
			nosotros: "hubiéremos dibujado",
			vosotros: "hubiereis dibujado",
			Uds: "hubieren dibujado",
		},
	},
}
