var dictar = {
	Indicative: {
		Present: {
			yo: "dicto",
			tú: "dictas",
			Ud: "dicta",
			nosotros: "dictamos",
			vosotros: "dictáis",
			Uds: "dictan",
		},
		Preterite: {
			yo: "dicté",
			tú: "dictaste",
			Ud: "dictó",
			nosotros: "dictamos",
			vosotros: "dictasteis",
			Uds: "dictaron",
		},
		Imperfect: {
			yo: "dictaba",
			tú: "dictabas",
			Ud: "dictaba",
			nosotros: "dictábamos",
			vosotros: "dictabais",
			Uds: "dictaban",
		},
		Conditional: {
			yo: "dictaría",
			tú: "dictarías",
			Ud: "dictaría",
			nosotros: "dictaríamos",
			vosotros: "dictaríais",
			Uds: "dictarían",
		},
		Future: {
			yo: "dictaré",
			tú: "dictarás",
			Ud: "dictará",
			nosotros: "dictaremos",
			vosotros: "dictaréis",
			Uds: "dictarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "dicte",
			tú: "dictes",
			Ud: "dicte",
			nosotros: "dictemos",
			vosotros: "dictéis",
			Uds: "dicten",
		},
		Imperfect: {
			yo: "dictara",
			tú: "dictaras",
			Ud: "dictara",
			nosotros: "dictáramos",
			vosotros: "dictarais",
			Uds: "dictaran",
		},
		Imperfect2: {
			yo: "dictase",
			tú: "dictases",
			Ud: "dictase",
			nosotros: "dictásemos",
			vosotros: "dictaseis",
			Uds: "dictasen",
		},
		Future: {
			yo: "dictare",
			tú: "dictares",
			Ud: "dictare",
			nosotros: "dictáremos",
			vosotros: "dictareis",
			Uds: "dictaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "dicta",
			Ud: "dicte",
			nosotros: "dictemos",
			vosotros: "dictad",
			Uds: "dicten",
		},
		Negative: {
			tú: "no dictes",
			Ud: "no dicte",
			nosotros: "no dictemos",
			vosotros: "no dictéis",
			Uds: "no dicten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy dictando",
			tú: "estás dictando",
			Ud: "está dictando",
			nosotros: "estamos dictando",
			vosotros: "estáis dictando",
			Uds: "están dictando",
		},
		Preterite: {
			yo: "estuve dictando",
			tú: "estuviste dictando",
			Ud: "estuvo dictando",
			nosotros: "estuvimos dictando",
			vosotros: "estuvisteis dictando",
			Uds: "estuvieron dictando",
		},
		Imperfect: {
			Uds: "estaban dictando",
			yo: "estaba dictando",
			tú: "estabas dictando",
			Ud: "estaba dictando",
			nosotros: "estábamos dictando",
			vosotros: "estabais dictando",
		},
		Conditional: {
			yo: "estaría dictando",
			tú: "estarías dictando",
			Ud: "estaría dictando",
			nosotros: "estaríamos dictando",
			vosotros: "estaríais dictando",
			Uds: "estarían dictando",
		},
		Future: {
			yo: "estaré dictando",
			tú: "estarás dictando",
			Ud: "estará dictando",
			nosotros: "estaremos dictando",
			vosotros: "estaréis dictando",
			Uds: "estarán dictando",
		},
	},
	Perfect: {
		Present: {
			yo: "he dictado",
			tú: "has dictado",
			Ud: "ha dictado",
			nosotros: "hemos dictado",
			vosotros: "habéis dictado",
			Uds: "han dictado",
		},
		Preterite: {
			yo: "hube dictado",
			tú: "hubiste dictado",
			Ud: "hubo dictado",
			nosotros: "hubimos dictado",
			vosotros: "hubisteis dictado",
			Uds: "hubieron dictado",
		},
		Past: {
			yo: "había dictado",
			tú: "habías dictado",
			Ud: "había dictado",
			nosotros: "habíamos dictado",
			vosotros: "habíais dictado",
			Uds: "habían dictado",
		},
		Conditional: {
			yo: "habría dictado",
			tú: "habrías dictado",
			Ud: "habría dictado",
			nosotros: "habríamos dictado",
			vosotros: "habríais dictado",
			Uds: "habrían dictado",
		},
		Future: {
			yo: "habré dictado",
			tú: "habrás dictado",
			Ud: "habrá dictado",
			nosotros: "habremos dictado",
			vosotros: "habréis dictado",
			Uds: "habrán dictado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya dictado",
			tú: "hayas dictado",
			Ud: "haya dictado",
			nosotros: "hayamos dictado",
			vosotros: "hayáis dictado",
			Uds: "hayan dictado",
		},
		Past: {
			yo: "hubiera dictado",
			tú: "hubieras dictado",
			Ud: "hubiera dictado",
			nosotros: "hubiéramos dictado",
			vosotros: "hubierais dictado",
			Uds: "hubieran dictado",
		},
		Future: {
			yo: "hubiere dictado",
			tú: "hubieres dictado",
			Ud: "hubiere dictado",
			nosotros: "hubiéremos dictado",
			vosotros: "hubiereis dictado",
			Uds: "hubieren dictado",
		},
	},
}
