var dilatar = {
	Indicative: {
		Present: {
			yo: "dilato",
			tú: "dilatas",
			Ud: "dilata",
			nosotros: "dilatamos",
			vosotros: "dilatáis",
			Uds: "dilatan",
		},
		Preterite: {
			yo: "dilaté",
			tú: "dilataste",
			Ud: "dilató",
			nosotros: "dilatamos",
			vosotros: "dilatasteis",
			Uds: "dilataron",
		},
		Imperfect: {
			yo: "dilataba",
			tú: "dilatabas",
			Ud: "dilataba",
			nosotros: "dilatábamos",
			vosotros: "dilatabais",
			Uds: "dilataban",
		},
		Conditional: {
			yo: "dilataría",
			tú: "dilatarías",
			Ud: "dilataría",
			nosotros: "dilataríamos",
			vosotros: "dilataríais",
			Uds: "dilatarían",
		},
		Future: {
			yo: "dilataré",
			tú: "dilatarás",
			Ud: "dilatará",
			nosotros: "dilataremos",
			vosotros: "dilataréis",
			Uds: "dilatarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "dilate",
			tú: "dilates",
			Ud: "dilate",
			nosotros: "dilatemos",
			vosotros: "dilatéis",
			Uds: "dilaten",
		},
		Imperfect: {
			yo: "dilatara",
			tú: "dilataras",
			Ud: "dilatara",
			nosotros: "dilatáramos",
			vosotros: "dilatarais",
			Uds: "dilataran",
		},
		Imperfect2: {
			yo: "dilatase",
			tú: "dilatases",
			Ud: "dilatase",
			nosotros: "dilatásemos",
			vosotros: "dilataseis",
			Uds: "dilatasen",
		},
		Future: {
			yo: "dilatare",
			tú: "dilatares",
			Ud: "dilatare",
			nosotros: "dilatáremos",
			vosotros: "dilatareis",
			Uds: "dilataren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "dilata",
			Ud: "dilate",
			nosotros: "dilatemos",
			vosotros: "dilatad",
			Uds: "dilaten",
		},
		Negative: {
			tú: "no dilates",
			Ud: "no dilate",
			nosotros: "no dilatemos",
			vosotros: "no dilatéis",
			Uds: "no dilaten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy dilatando",
			tú: "estás dilatando",
			Ud: "está dilatando",
			nosotros: "estamos dilatando",
			vosotros: "estáis dilatando",
			Uds: "están dilatando",
		},
		Preterite: {
			yo: "estuve dilatando",
			tú: "estuviste dilatando",
			Ud: "estuvo dilatando",
			nosotros: "estuvimos dilatando",
			vosotros: "estuvisteis dilatando",
			Uds: "estuvieron dilatando",
		},
		Imperfect: {
			Uds: "estaban dilatando",
			yo: "estaba dilatando",
			tú: "estabas dilatando",
			Ud: "estaba dilatando",
			nosotros: "estábamos dilatando",
			vosotros: "estabais dilatando",
		},
		Conditional: {
			yo: "estaría dilatando",
			tú: "estarías dilatando",
			Ud: "estaría dilatando",
			nosotros: "estaríamos dilatando",
			vosotros: "estaríais dilatando",
			Uds: "estarían dilatando",
		},
		Future: {
			yo: "estaré dilatando",
			tú: "estarás dilatando",
			Ud: "estará dilatando",
			nosotros: "estaremos dilatando",
			vosotros: "estaréis dilatando",
			Uds: "estarán dilatando",
		},
	},
	Perfect: {
		Present: {
			yo: "he dilatado",
			tú: "has dilatado",
			Ud: "ha dilatado",
			nosotros: "hemos dilatado",
			vosotros: "habéis dilatado",
			Uds: "han dilatado",
		},
		Preterite: {
			yo: "hube dilatado",
			tú: "hubiste dilatado",
			Ud: "hubo dilatado",
			nosotros: "hubimos dilatado",
			vosotros: "hubisteis dilatado",
			Uds: "hubieron dilatado",
		},
		Past: {
			yo: "había dilatado",
			tú: "habías dilatado",
			Ud: "había dilatado",
			nosotros: "habíamos dilatado",
			vosotros: "habíais dilatado",
			Uds: "habían dilatado",
		},
		Conditional: {
			yo: "habría dilatado",
			tú: "habrías dilatado",
			Ud: "habría dilatado",
			nosotros: "habríamos dilatado",
			vosotros: "habríais dilatado",
			Uds: "habrían dilatado",
		},
		Future: {
			yo: "habré dilatado",
			tú: "habrás dilatado",
			Ud: "habrá dilatado",
			nosotros: "habremos dilatado",
			vosotros: "habréis dilatado",
			Uds: "habrán dilatado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya dilatado",
			tú: "hayas dilatado",
			Ud: "haya dilatado",
			nosotros: "hayamos dilatado",
			vosotros: "hayáis dilatado",
			Uds: "hayan dilatado",
		},
		Past: {
			yo: "hubiera dilatado",
			tú: "hubieras dilatado",
			Ud: "hubiera dilatado",
			nosotros: "hubiéramos dilatado",
			vosotros: "hubierais dilatado",
			Uds: "hubieran dilatado",
		},
		Future: {
			yo: "hubiere dilatado",
			tú: "hubieres dilatado",
			Ud: "hubiere dilatado",
			nosotros: "hubiéremos dilatado",
			vosotros: "hubiereis dilatado",
			Uds: "hubieren dilatado",
		},
	},
}
