var dilucidar = {
	Indicative: {
		Present: {
			yo: "dilucido",
			tú: "dilucidas",
			Ud: "dilucida",
			nosotros: "dilucidamos",
			vosotros: "dilucidáis",
			Uds: "dilucidan",
		},
		Preterite: {
			yo: "dilucidé",
			tú: "dilucidaste",
			Ud: "dilucidó",
			nosotros: "dilucidamos",
			vosotros: "dilucidasteis",
			Uds: "dilucidaron",
		},
		Imperfect: {
			yo: "dilucidaba",
			tú: "dilucidabas",
			Ud: "dilucidaba",
			nosotros: "dilucidábamos",
			vosotros: "dilucidabais",
			Uds: "dilucidaban",
		},
		Conditional: {
			yo: "dilucidaría",
			tú: "dilucidarías",
			Ud: "dilucidaría",
			nosotros: "dilucidaríamos",
			vosotros: "dilucidaríais",
			Uds: "dilucidarían",
		},
		Future: {
			yo: "dilucidaré",
			tú: "dilucidarás",
			Ud: "dilucidará",
			nosotros: "dilucidaremos",
			vosotros: "dilucidaréis",
			Uds: "dilucidarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "dilucide",
			tú: "dilucides",
			Ud: "dilucide",
			nosotros: "dilucidemos",
			vosotros: "dilucidéis",
			Uds: "diluciden",
		},
		Imperfect: {
			yo: "dilucidara",
			tú: "dilucidaras",
			Ud: "dilucidara",
			nosotros: "dilucidáramos",
			vosotros: "dilucidarais",
			Uds: "dilucidaran",
		},
		Imperfect2: {
			yo: "dilucidase",
			tú: "dilucidases",
			Ud: "dilucidase",
			nosotros: "dilucidásemos",
			vosotros: "dilucidaseis",
			Uds: "dilucidasen",
		},
		Future: {
			yo: "dilucidare",
			tú: "dilucidares",
			Ud: "dilucidare",
			nosotros: "dilucidáremos",
			vosotros: "dilucidareis",
			Uds: "dilucidaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "dilucida",
			Ud: "dilucide",
			nosotros: "dilucidemos",
			vosotros: "dilucidad",
			Uds: "diluciden",
		},
		Negative: {
			tú: "no dilucides",
			Ud: "no dilucide",
			nosotros: "no dilucidemos",
			vosotros: "no dilucidéis",
			Uds: "no diluciden",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy dilucidando",
			tú: "estás dilucidando",
			Ud: "está dilucidando",
			nosotros: "estamos dilucidando",
			vosotros: "estáis dilucidando",
			Uds: "están dilucidando",
		},
		Preterite: {
			yo: "estuve dilucidando",
			tú: "estuviste dilucidando",
			Ud: "estuvo dilucidando",
			nosotros: "estuvimos dilucidando",
			vosotros: "estuvisteis dilucidando",
			Uds: "estuvieron dilucidando",
		},
		Imperfect: {
			Uds: "estaban dilucidando",
			yo: "estaba dilucidando",
			tú: "estabas dilucidando",
			Ud: "estaba dilucidando",
			nosotros: "estábamos dilucidando",
			vosotros: "estabais dilucidando",
		},
		Conditional: {
			yo: "estaría dilucidando",
			tú: "estarías dilucidando",
			Ud: "estaría dilucidando",
			nosotros: "estaríamos dilucidando",
			vosotros: "estaríais dilucidando",
			Uds: "estarían dilucidando",
		},
		Future: {
			yo: "estaré dilucidando",
			tú: "estarás dilucidando",
			Ud: "estará dilucidando",
			nosotros: "estaremos dilucidando",
			vosotros: "estaréis dilucidando",
			Uds: "estarán dilucidando",
		},
	},
	Perfect: {
		Present: {
			yo: "he dilucidado",
			tú: "has dilucidado",
			Ud: "ha dilucidado",
			nosotros: "hemos dilucidado",
			vosotros: "habéis dilucidado",
			Uds: "han dilucidado",
		},
		Preterite: {
			yo: "hube dilucidado",
			tú: "hubiste dilucidado",
			Ud: "hubo dilucidado",
			nosotros: "hubimos dilucidado",
			vosotros: "hubisteis dilucidado",
			Uds: "hubieron dilucidado",
		},
		Past: {
			yo: "había dilucidado",
			tú: "habías dilucidado",
			Ud: "había dilucidado",
			nosotros: "habíamos dilucidado",
			vosotros: "habíais dilucidado",
			Uds: "habían dilucidado",
		},
		Conditional: {
			yo: "habría dilucidado",
			tú: "habrías dilucidado",
			Ud: "habría dilucidado",
			nosotros: "habríamos dilucidado",
			vosotros: "habríais dilucidado",
			Uds: "habrían dilucidado",
		},
		Future: {
			yo: "habré dilucidado",
			tú: "habrás dilucidado",
			Ud: "habrá dilucidado",
			nosotros: "habremos dilucidado",
			vosotros: "habréis dilucidado",
			Uds: "habrán dilucidado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya dilucidado",
			tú: "hayas dilucidado",
			Ud: "haya dilucidado",
			nosotros: "hayamos dilucidado",
			vosotros: "hayáis dilucidado",
			Uds: "hayan dilucidado",
		},
		Past: {
			yo: "hubiera dilucidado",
			tú: "hubieras dilucidado",
			Ud: "hubiera dilucidado",
			nosotros: "hubiéramos dilucidado",
			vosotros: "hubierais dilucidado",
			Uds: "hubieran dilucidado",
		},
		Future: {
			yo: "hubiere dilucidado",
			tú: "hubieres dilucidado",
			Ud: "hubiere dilucidado",
			nosotros: "hubiéremos dilucidado",
			vosotros: "hubiereis dilucidado",
			Uds: "hubieren dilucidado",
		},
	},
}
