var dinamitar = {
	Indicative: {
		Present: {
			yo: "dinamito",
			tú: "dinamitas",
			Ud: "dinamita",
			nosotros: "dinamitamos",
			vosotros: "dinamitáis",
			Uds: "dinamitan",
		},
		Preterite: {
			yo: "dinamité",
			tú: "dinamitaste",
			Ud: "dinamitó",
			nosotros: "dinamitamos",
			vosotros: "dinamitasteis",
			Uds: "dinamitaron",
		},
		Imperfect: {
			yo: "dinamitaba",
			tú: "dinamitabas",
			Ud: "dinamitaba",
			nosotros: "dinamitábamos",
			vosotros: "dinamitabais",
			Uds: "dinamitaban",
		},
		Conditional: {
			yo: "dinamitaría",
			tú: "dinamitarías",
			Ud: "dinamitaría",
			nosotros: "dinamitaríamos",
			vosotros: "dinamitaríais",
			Uds: "dinamitarían",
		},
		Future: {
			yo: "dinamitaré",
			tú: "dinamitarás",
			Ud: "dinamitará",
			nosotros: "dinamitaremos",
			vosotros: "dinamitaréis",
			Uds: "dinamitarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "dinamite",
			tú: "dinamites",
			Ud: "dinamite",
			nosotros: "dinamitemos",
			vosotros: "dinamitéis",
			Uds: "dinamiten",
		},
		Imperfect: {
			yo: "dinamitara",
			tú: "dinamitaras",
			Ud: "dinamitara",
			nosotros: "dinamitáramos",
			vosotros: "dinamitarais",
			Uds: "dinamitaran",
		},
		Imperfect2: {
			yo: "dinamitase",
			tú: "dinamitases",
			Ud: "dinamitase",
			nosotros: "dinamitásemos",
			vosotros: "dinamitaseis",
			Uds: "dinamitasen",
		},
		Future: {
			yo: "dinamitare",
			tú: "dinamitares",
			Ud: "dinamitare",
			nosotros: "dinamitáremos",
			vosotros: "dinamitareis",
			Uds: "dinamitaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "dinamita",
			Ud: "dinamite",
			nosotros: "dinamitemos",
			vosotros: "dinamitad",
			Uds: "dinamiten",
		},
		Negative: {
			tú: "no dinamites",
			Ud: "no dinamite",
			nosotros: "no dinamitemos",
			vosotros: "no dinamitéis",
			Uds: "no dinamiten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy dinamitando",
			tú: "estás dinamitando",
			Ud: "está dinamitando",
			nosotros: "estamos dinamitando",
			vosotros: "estáis dinamitando",
			Uds: "están dinamitando",
		},
		Preterite: {
			yo: "estuve dinamitando",
			tú: "estuviste dinamitando",
			Ud: "estuvo dinamitando",
			nosotros: "estuvimos dinamitando",
			vosotros: "estuvisteis dinamitando",
			Uds: "estuvieron dinamitando",
		},
		Imperfect: {
			Uds: "estaban dinamitando",
			yo: "estaba dinamitando",
			tú: "estabas dinamitando",
			Ud: "estaba dinamitando",
			nosotros: "estábamos dinamitando",
			vosotros: "estabais dinamitando",
		},
		Conditional: {
			yo: "estaría dinamitando",
			tú: "estarías dinamitando",
			Ud: "estaría dinamitando",
			nosotros: "estaríamos dinamitando",
			vosotros: "estaríais dinamitando",
			Uds: "estarían dinamitando",
		},
		Future: {
			yo: "estaré dinamitando",
			tú: "estarás dinamitando",
			Ud: "estará dinamitando",
			nosotros: "estaremos dinamitando",
			vosotros: "estaréis dinamitando",
			Uds: "estarán dinamitando",
		},
	},
	Perfect: {
		Present: {
			yo: "he dinamitado",
			tú: "has dinamitado",
			Ud: "ha dinamitado",
			nosotros: "hemos dinamitado",
			vosotros: "habéis dinamitado",
			Uds: "han dinamitado",
		},
		Preterite: {
			yo: "hube dinamitado",
			tú: "hubiste dinamitado",
			Ud: "hubo dinamitado",
			nosotros: "hubimos dinamitado",
			vosotros: "hubisteis dinamitado",
			Uds: "hubieron dinamitado",
		},
		Past: {
			yo: "había dinamitado",
			tú: "habías dinamitado",
			Ud: "había dinamitado",
			nosotros: "habíamos dinamitado",
			vosotros: "habíais dinamitado",
			Uds: "habían dinamitado",
		},
		Conditional: {
			yo: "habría dinamitado",
			tú: "habrías dinamitado",
			Ud: "habría dinamitado",
			nosotros: "habríamos dinamitado",
			vosotros: "habríais dinamitado",
			Uds: "habrían dinamitado",
		},
		Future: {
			yo: "habré dinamitado",
			tú: "habrás dinamitado",
			Ud: "habrá dinamitado",
			nosotros: "habremos dinamitado",
			vosotros: "habréis dinamitado",
			Uds: "habrán dinamitado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya dinamitado",
			tú: "hayas dinamitado",
			Ud: "haya dinamitado",
			nosotros: "hayamos dinamitado",
			vosotros: "hayáis dinamitado",
			Uds: "hayan dinamitado",
		},
		Past: {
			yo: "hubiera dinamitado",
			tú: "hubieras dinamitado",
			Ud: "hubiera dinamitado",
			nosotros: "hubiéramos dinamitado",
			vosotros: "hubierais dinamitado",
			Uds: "hubieran dinamitado",
		},
		Future: {
			yo: "hubiere dinamitado",
			tú: "hubieres dinamitado",
			Ud: "hubiere dinamitado",
			nosotros: "hubiéremos dinamitado",
			vosotros: "hubiereis dinamitado",
			Uds: "hubieren dinamitado",
		},
	},
}
