var discrepar = {
	Indicative: {
		Present: {
			yo: "discrepo",
			tú: "discrepas",
			Ud: "discrepa",
			nosotros: "discrepamos",
			vosotros: "discrepáis",
			Uds: "discrepan",
		},
		Preterite: {
			yo: "discrepé",
			tú: "discrepaste",
			Ud: "discrepó",
			nosotros: "discrepamos",
			vosotros: "discrepasteis",
			Uds: "discreparon",
		},
		Imperfect: {
			yo: "discrepaba",
			tú: "discrepabas",
			Ud: "discrepaba",
			nosotros: "discrepábamos",
			vosotros: "discrepabais",
			Uds: "discrepaban",
		},
		Conditional: {
			yo: "discreparía",
			tú: "discreparías",
			Ud: "discreparía",
			nosotros: "discreparíamos",
			vosotros: "discreparíais",
			Uds: "discreparían",
		},
		Future: {
			yo: "discreparé",
			tú: "discreparás",
			Ud: "discrepará",
			nosotros: "discreparemos",
			vosotros: "discreparéis",
			Uds: "discreparán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "discrepe",
			tú: "discrepes",
			Ud: "discrepe",
			nosotros: "discrepemos",
			vosotros: "discrepéis",
			Uds: "discrepen",
		},
		Imperfect: {
			yo: "discrepara",
			tú: "discreparas",
			Ud: "discrepara",
			nosotros: "discrepáramos",
			vosotros: "discreparais",
			Uds: "discreparan",
		},
		Imperfect2: {
			yo: "discrepase",
			tú: "discrepases",
			Ud: "discrepase",
			nosotros: "discrepásemos",
			vosotros: "discrepaseis",
			Uds: "discrepasen",
		},
		Future: {
			yo: "discrepare",
			tú: "discrepares",
			Ud: "discrepare",
			nosotros: "discrepáremos",
			vosotros: "discrepareis",
			Uds: "discreparen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "discrepa",
			Ud: "discrepe",
			nosotros: "discrepemos",
			vosotros: "discrepad",
			Uds: "discrepen",
		},
		Negative: {
			tú: "no discrepes",
			Ud: "no discrepe",
			nosotros: "no discrepemos",
			vosotros: "no discrepéis",
			Uds: "no discrepen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy discrepando",
			tú: "estás discrepando",
			Ud: "está discrepando",
			nosotros: "estamos discrepando",
			vosotros: "estáis discrepando",
			Uds: "están discrepando",
		},
		Preterite: {
			yo: "estuve discrepando",
			tú: "estuviste discrepando",
			Ud: "estuvo discrepando",
			nosotros: "estuvimos discrepando",
			vosotros: "estuvisteis discrepando",
			Uds: "estuvieron discrepando",
		},
		Imperfect: {
			Uds: "estaban discrepando",
			yo: "estaba discrepando",
			tú: "estabas discrepando",
			Ud: "estaba discrepando",
			nosotros: "estábamos discrepando",
			vosotros: "estabais discrepando",
		},
		Conditional: {
			yo: "estaría discrepando",
			tú: "estarías discrepando",
			Ud: "estaría discrepando",
			nosotros: "estaríamos discrepando",
			vosotros: "estaríais discrepando",
			Uds: "estarían discrepando",
		},
		Future: {
			yo: "estaré discrepando",
			tú: "estarás discrepando",
			Ud: "estará discrepando",
			nosotros: "estaremos discrepando",
			vosotros: "estaréis discrepando",
			Uds: "estarán discrepando",
		},
	},
	Perfect: {
		Present: {
			yo: "he discrepado",
			tú: "has discrepado",
			Ud: "ha discrepado",
			nosotros: "hemos discrepado",
			vosotros: "habéis discrepado",
			Uds: "han discrepado",
		},
		Preterite: {
			yo: "hube discrepado",
			tú: "hubiste discrepado",
			Ud: "hubo discrepado",
			nosotros: "hubimos discrepado",
			vosotros: "hubisteis discrepado",
			Uds: "hubieron discrepado",
		},
		Past: {
			yo: "había discrepado",
			tú: "habías discrepado",
			Ud: "había discrepado",
			nosotros: "habíamos discrepado",
			vosotros: "habíais discrepado",
			Uds: "habían discrepado",
		},
		Conditional: {
			yo: "habría discrepado",
			tú: "habrías discrepado",
			Ud: "habría discrepado",
			nosotros: "habríamos discrepado",
			vosotros: "habríais discrepado",
			Uds: "habrían discrepado",
		},
		Future: {
			yo: "habré discrepado",
			tú: "habrás discrepado",
			Ud: "habrá discrepado",
			nosotros: "habremos discrepado",
			vosotros: "habréis discrepado",
			Uds: "habrán discrepado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya discrepado",
			tú: "hayas discrepado",
			Ud: "haya discrepado",
			nosotros: "hayamos discrepado",
			vosotros: "hayáis discrepado",
			Uds: "hayan discrepado",
		},
		Past: {
			yo: "hubiera discrepado",
			tú: "hubieras discrepado",
			Ud: "hubiera discrepado",
			nosotros: "hubiéramos discrepado",
			vosotros: "hubierais discrepado",
			Uds: "hubieran discrepado",
		},
		Future: {
			yo: "hubiere discrepado",
			tú: "hubieres discrepado",
			Ud: "hubiere discrepado",
			nosotros: "hubiéremos discrepado",
			vosotros: "hubiereis discrepado",
			Uds: "hubieren discrepado",
		},
	},
}
