var discutir = {
	Indicative: {
		Present: {
			yo: "discuto",
			tú: "discutes",
			Ud: "discute",
			nosotros: "discutimos",
			vosotros: "discutís",
			Uds: "discuten",
		},
		Preterite: {
			yo: "discutí",
			tú: "discutiste",
			Ud: "discutió",
			nosotros: "discutimos",
			vosotros: "discutisteis",
			Uds: "discutieron",
		},
		Imperfect: {
			yo: "discutía",
			tú: "discutías",
			Ud: "discutía",
			nosotros: "discutíamos",
			vosotros: "discutíais",
			Uds: "discutían",
		},
		Conditional: {
			yo: "discutiría",
			tú: "discutirías",
			Ud: "discutiría",
			nosotros: "discutiríamos",
			vosotros: "discutiríais",
			Uds: "discutirían",
		},
		Future: {
			yo: "discutiré",
			tú: "discutirás",
			Ud: "discutirá",
			nosotros: "discutiremos",
			vosotros: "discutiréis",
			Uds: "discutirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "discuta",
			tú: "discutas",
			Ud: "discuta",
			nosotros: "discutamos",
			vosotros: "discutáis",
			Uds: "discutan",
		},
		Imperfect: {
			yo: "discutiera",
			tú: "discutieras",
			Ud: "discutiera",
			nosotros: "discutiéramos",
			vosotros: "discutierais",
			Uds: "discutieran",
		},
		Imperfect2: {
			yo: "discutiese",
			tú: "discutieses",
			Ud: "discutiese",
			nosotros: "discutiésemos",
			vosotros: "discutieseis",
			Uds: "discutiesen",
		},
		Future: {
			yo: "discutiere",
			tú: "discutieres",
			Ud: "discutiere",
			nosotros: "discutiéremos",
			vosotros: "discutiereis",
			Uds: "discutieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "discute",
			Ud: "discuta",
			nosotros: "discutamos",
			vosotros: "discutid",
			Uds: "discutan",
		},
		Negative: {
			tú: "no discutas",
			Ud: "no discuta",
			nosotros: "no discutamos",
			vosotros: "no discutáis",
			Uds: "no discutan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy discutiendo",
			tú: "estás discutiendo",
			Ud: "está discutiendo",
			nosotros: "estamos discutiendo",
			vosotros: "estáis discutiendo",
			Uds: "están discutiendo",
		},
		Preterite: {
			yo: "estuve discutiendo",
			tú: "estuviste discutiendo",
			Ud: "estuvo discutiendo",
			nosotros: "estuvimos discutiendo",
			vosotros: "estuvisteis discutiendo",
			Uds: "estuvieron discutiendo",
		},
		Imperfect: {
			Uds: "estaban discutiendo",
			yo: "estaba discutiendo",
			tú: "estabas discutiendo",
			Ud: "estaba discutiendo",
			nosotros: "estábamos discutiendo",
			vosotros: "estabais discutiendo",
		},
		Conditional: {
			yo: "estaría discutiendo",
			tú: "estarías discutiendo",
			Ud: "estaría discutiendo",
			nosotros: "estaríamos discutiendo",
			vosotros: "estaríais discutiendo",
			Uds: "estarían discutiendo",
		},
		Future: {
			yo: "estaré discutiendo",
			tú: "estarás discutiendo",
			Ud: "estará discutiendo",
			nosotros: "estaremos discutiendo",
			vosotros: "estaréis discutiendo",
			Uds: "estarán discutiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he discutido",
			tú: "has discutido",
			Ud: "ha discutido",
			nosotros: "hemos discutido",
			vosotros: "habéis discutido",
			Uds: "han discutido",
		},
		Preterite: {
			yo: "hube discutido",
			tú: "hubiste discutido",
			Ud: "hubo discutido",
			nosotros: "hubimos discutido",
			vosotros: "hubisteis discutido",
			Uds: "hubieron discutido",
		},
		Past: {
			yo: "había discutido",
			tú: "habías discutido",
			Ud: "había discutido",
			nosotros: "habíamos discutido",
			vosotros: "habíais discutido",
			Uds: "habían discutido",
		},
		Conditional: {
			yo: "habría discutido",
			tú: "habrías discutido",
			Ud: "habría discutido",
			nosotros: "habríamos discutido",
			vosotros: "habríais discutido",
			Uds: "habrían discutido",
		},
		Future: {
			yo: "habré discutido",
			tú: "habrás discutido",
			Ud: "habrá discutido",
			nosotros: "habremos discutido",
			vosotros: "habréis discutido",
			Uds: "habrán discutido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya discutido",
			tú: "hayas discutido",
			Ud: "haya discutido",
			nosotros: "hayamos discutido",
			vosotros: "hayáis discutido",
			Uds: "hayan discutido",
		},
		Past: {
			yo: "hubiera discutido",
			tú: "hubieras discutido",
			Ud: "hubiera discutido",
			nosotros: "hubiéramos discutido",
			vosotros: "hubierais discutido",
			Uds: "hubieran discutido",
		},
		Future: {
			yo: "hubiere discutido",
			tú: "hubieres discutido",
			Ud: "hubiere discutido",
			nosotros: "hubiéremos discutido",
			vosotros: "hubiereis discutido",
			Uds: "hubieren discutido",
		},
	},
}
