var diseñar = {
	Indicative: {
		Present: {
			yo: "diseño",
			tú: "diseñas",
			Ud: "diseña",
			nosotros: "diseñamos",
			vosotros: "diseñáis",
			Uds: "diseñan",
		},
		Preterite: {
			yo: "diseñé",
			tú: "diseñaste",
			Ud: "diseñó",
			nosotros: "diseñamos",
			vosotros: "diseñasteis",
			Uds: "diseñaron",
		},
		Imperfect: {
			yo: "diseñaba",
			tú: "diseñabas",
			Ud: "diseñaba",
			nosotros: "diseñábamos",
			vosotros: "diseñabais",
			Uds: "diseñaban",
		},
		Conditional: {
			yo: "diseñaría",
			tú: "diseñarías",
			Ud: "diseñaría",
			nosotros: "diseñaríamos",
			vosotros: "diseñaríais",
			Uds: "diseñarían",
		},
		Future: {
			yo: "diseñaré",
			tú: "diseñarás",
			Ud: "diseñará",
			nosotros: "diseñaremos",
			vosotros: "diseñaréis",
			Uds: "diseñarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "diseñe",
			tú: "diseñes",
			Ud: "diseñe",
			nosotros: "diseñemos",
			vosotros: "diseñéis",
			Uds: "diseñen",
		},
		Imperfect: {
			yo: "diseñara",
			tú: "diseñaras",
			Ud: "diseñara",
			nosotros: "diseñáramos",
			vosotros: "diseñarais",
			Uds: "diseñaran",
		},
		Imperfect2: {
			yo: "diseñase",
			tú: "diseñases",
			Ud: "diseñase",
			nosotros: "diseñásemos",
			vosotros: "diseñaseis",
			Uds: "diseñasen",
		},
		Future: {
			yo: "diseñare",
			tú: "diseñares",
			Ud: "diseñare",
			nosotros: "diseñáremos",
			vosotros: "diseñareis",
			Uds: "diseñaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "diseña",
			Ud: "diseñe",
			nosotros: "diseñemos",
			vosotros: "diseñad",
			Uds: "diseñen",
		},
		Negative: {
			tú: "no diseñes",
			Ud: "no diseñe",
			nosotros: "no diseñemos",
			vosotros: "no diseñéis",
			Uds: "no diseñen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy diseñando",
			tú: "estás diseñando",
			Ud: "está diseñando",
			nosotros: "estamos diseñando",
			vosotros: "estáis diseñando",
			Uds: "están diseñando",
		},
		Preterite: {
			yo: "estuve diseñando",
			tú: "estuviste diseñando",
			Ud: "estuvo diseñando",
			nosotros: "estuvimos diseñando",
			vosotros: "estuvisteis diseñando",
			Uds: "estuvieron diseñando",
		},
		Imperfect: {
			Uds: "estaban diseñando",
			yo: "estaba diseñando",
			tú: "estabas diseñando",
			Ud: "estaba diseñando",
			nosotros: "estábamos diseñando",
			vosotros: "estabais diseñando",
		},
		Conditional: {
			yo: "estaría diseñando",
			tú: "estarías diseñando",
			Ud: "estaría diseñando",
			nosotros: "estaríamos diseñando",
			vosotros: "estaríais diseñando",
			Uds: "estarían diseñando",
		},
		Future: {
			yo: "estaré diseñando",
			tú: "estarás diseñando",
			Ud: "estará diseñando",
			nosotros: "estaremos diseñando",
			vosotros: "estaréis diseñando",
			Uds: "estarán diseñando",
		},
	},
	Perfect: {
		Present: {
			yo: "he diseñado",
			tú: "has diseñado",
			Ud: "ha diseñado",
			nosotros: "hemos diseñado",
			vosotros: "habéis diseñado",
			Uds: "han diseñado",
		},
		Preterite: {
			yo: "hube diseñado",
			tú: "hubiste diseñado",
			Ud: "hubo diseñado",
			nosotros: "hubimos diseñado",
			vosotros: "hubisteis diseñado",
			Uds: "hubieron diseñado",
		},
		Past: {
			yo: "había diseñado",
			tú: "habías diseñado",
			Ud: "había diseñado",
			nosotros: "habíamos diseñado",
			vosotros: "habíais diseñado",
			Uds: "habían diseñado",
		},
		Conditional: {
			yo: "habría diseñado",
			tú: "habrías diseñado",
			Ud: "habría diseñado",
			nosotros: "habríamos diseñado",
			vosotros: "habríais diseñado",
			Uds: "habrían diseñado",
		},
		Future: {
			yo: "habré diseñado",
			tú: "habrás diseñado",
			Ud: "habrá diseñado",
			nosotros: "habremos diseñado",
			vosotros: "habréis diseñado",
			Uds: "habrán diseñado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya diseñado",
			tú: "hayas diseñado",
			Ud: "haya diseñado",
			nosotros: "hayamos diseñado",
			vosotros: "hayáis diseñado",
			Uds: "hayan diseñado",
		},
		Past: {
			yo: "hubiera diseñado",
			tú: "hubieras diseñado",
			Ud: "hubiera diseñado",
			nosotros: "hubiéramos diseñado",
			vosotros: "hubierais diseñado",
			Uds: "hubieran diseñado",
		},
		Future: {
			yo: "hubiere diseñado",
			tú: "hubieres diseñado",
			Ud: "hubiere diseñado",
			nosotros: "hubiéremos diseñado",
			vosotros: "hubiereis diseñado",
			Uds: "hubieren diseñado",
		},
	},
}
