var disentir = {
	Indicative: {
		Present: {
			yo: "disiento",
			tú: "disientes",
			Ud: "disiente",
			nosotros: "disentimos",
			vosotros: "disentís",
			Uds: "disienten",
		},
		Preterite: {
			yo: "disentí",
			tú: "disentiste",
			Ud: "disintió",
			nosotros: "disentimos",
			vosotros: "disentisteis",
			Uds: "disintieron",
		},
		Imperfect: {
			yo: "disentía",
			tú: "disentías",
			Ud: "disentía",
			nosotros: "disentíamos",
			vosotros: "disentíais",
			Uds: "disentían",
		},
		Conditional: {
			yo: "disentiría",
			tú: "disentirías",
			Ud: "disentiría",
			nosotros: "disentiríamos",
			vosotros: "disentiríais",
			Uds: "disentirían",
		},
		Future: {
			yo: "disentiré",
			tú: "disentirás",
			Ud: "disentirá",
			nosotros: "disentiremos",
			vosotros: "disentiréis",
			Uds: "disentirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "disienta",
			tú: "disientas",
			Ud: "disienta",
			nosotros: "disintamos",
			vosotros: "disintáis",
			Uds: "disientan",
		},
		Imperfect: {
			yo: "disintiera",
			tú: "disintieras",
			Ud: "disintiera",
			nosotros: "disintiéramos",
			vosotros: "disintierais",
			Uds: "disintieran",
		},
		Imperfect2: {
			yo: "disintiese",
			tú: "disintieses",
			Ud: "disintiese",
			nosotros: "disintiésemos",
			vosotros: "disintieseis",
			Uds: "disintiesen",
		},
		Future: {
			yo: "disintiere",
			tú: "disintieres",
			Ud: "disintiere",
			nosotros: "disintiéremos",
			vosotros: "disintiereis",
			Uds: "disintieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "disiente",
			Ud: "disienta",
			nosotros: "disintamos",
			vosotros: "disentid",
			Uds: "disientan",
		},
		Negative: {
			tú: "no disientas",
			Ud: "no disienta",
			nosotros: "no disintamos",
			vosotros: "no disintáis",
			Uds: "no disientan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy disintiendo",
			tú: "estás disintiendo",
			Ud: "está disintiendo",
			nosotros: "estamos disintiendo",
			vosotros: "estáis disintiendo",
			Uds: "están disintiendo",
		},
		Preterite: {
			yo: "estuve disintiendo",
			tú: "estuviste disintiendo",
			Ud: "estuvo disintiendo",
			nosotros: "estuvimos disintiendo",
			vosotros: "estuvisteis disintiendo",
			Uds: "estuvieron disintiendo",
		},
		Imperfect: {
			Uds: "estaban disintiendo",
			yo: "estaba disintiendo",
			tú: "estabas disintiendo",
			Ud: "estaba disintiendo",
			nosotros: "estábamos disintiendo",
			vosotros: "estabais disintiendo",
		},
		Conditional: {
			yo: "estaría disintiendo",
			tú: "estarías disintiendo",
			Ud: "estaría disintiendo",
			nosotros: "estaríamos disintiendo",
			vosotros: "estaríais disintiendo",
			Uds: "estarían disintiendo",
		},
		Future: {
			yo: "estaré disintiendo",
			tú: "estarás disintiendo",
			Ud: "estará disintiendo",
			nosotros: "estaremos disintiendo",
			vosotros: "estaréis disintiendo",
			Uds: "estarán disintiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he disentido",
			tú: "has disentido",
			Ud: "ha disentido",
			nosotros: "hemos disentido",
			vosotros: "habéis disentido",
			Uds: "han disentido",
		},
		Preterite: {
			yo: "hube disentido",
			tú: "hubiste disentido",
			Ud: "hubo disentido",
			nosotros: "hubimos disentido",
			vosotros: "hubisteis disentido",
			Uds: "hubieron disentido",
		},
		Past: {
			yo: "había disentido",
			tú: "habías disentido",
			Ud: "había disentido",
			nosotros: "habíamos disentido",
			vosotros: "habíais disentido",
			Uds: "habían disentido",
		},
		Conditional: {
			yo: "habría disentido",
			tú: "habrías disentido",
			Ud: "habría disentido",
			nosotros: "habríamos disentido",
			vosotros: "habríais disentido",
			Uds: "habrían disentido",
		},
		Future: {
			yo: "habré disentido",
			tú: "habrás disentido",
			Ud: "habrá disentido",
			nosotros: "habremos disentido",
			vosotros: "habréis disentido",
			Uds: "habrán disentido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya disentido",
			tú: "hayas disentido",
			Ud: "haya disentido",
			nosotros: "hayamos disentido",
			vosotros: "hayáis disentido",
			Uds: "hayan disentido",
		},
		Past: {
			yo: "hubiera disentido",
			tú: "hubieras disentido",
			Ud: "hubiera disentido",
			nosotros: "hubiéramos disentido",
			vosotros: "hubierais disentido",
			Uds: "hubieran disentido",
		},
		Future: {
			yo: "hubiere disentido",
			tú: "hubieres disentido",
			Ud: "hubiere disentido",
			nosotros: "hubiéremos disentido",
			vosotros: "hubiereis disentido",
			Uds: "hubieren disentido",
		},
	},
}
