var disfrutar = {
	Indicative: {
		Present: {
			yo: "disfruto",
			tú: "disfrutas",
			Ud: "disfruta",
			nosotros: "disfrutamos",
			vosotros: "disfrutáis",
			Uds: "disfrutan",
		},
		Preterite: {
			yo: "disfruté",
			tú: "disfrutaste",
			Ud: "disfrutó",
			nosotros: "disfrutamos",
			vosotros: "disfrutasteis",
			Uds: "disfrutaron",
		},
		Imperfect: {
			yo: "disfrutaba",
			tú: "disfrutabas",
			Ud: "disfrutaba",
			nosotros: "disfrutábamos",
			vosotros: "disfrutabais",
			Uds: "disfrutaban",
		},
		Conditional: {
			yo: "disfrutaría",
			tú: "disfrutarías",
			Ud: "disfrutaría",
			nosotros: "disfrutaríamos",
			vosotros: "disfrutaríais",
			Uds: "disfrutarían",
		},
		Future: {
			yo: "disfrutaré",
			tú: "disfrutarás",
			Ud: "disfrutará",
			nosotros: "disfrutaremos",
			vosotros: "disfrutaréis",
			Uds: "disfrutarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "disfrute",
			tú: "disfrutes",
			Ud: "disfrute",
			nosotros: "disfrutemos",
			vosotros: "disfrutéis",
			Uds: "disfruten",
		},
		Imperfect: {
			yo: "disfrutara",
			tú: "disfrutaras",
			Ud: "disfrutara",
			nosotros: "disfrutáramos",
			vosotros: "disfrutarais",
			Uds: "disfrutaran",
		},
		Imperfect2: {
			yo: "disfrutase",
			tú: "disfrutases",
			Ud: "disfrutase",
			nosotros: "disfrutásemos",
			vosotros: "disfrutaseis",
			Uds: "disfrutasen",
		},
		Future: {
			yo: "disfrutare",
			tú: "disfrutares",
			Ud: "disfrutare",
			nosotros: "disfrutáremos",
			vosotros: "disfrutareis",
			Uds: "disfrutaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "disfruta",
			Ud: "disfrute",
			nosotros: "disfrutemos",
			vosotros: "disfrutad",
			Uds: "disfruten",
		},
		Negative: {
			tú: "no disfrutes",
			Ud: "no disfrute",
			nosotros: "no disfrutemos",
			vosotros: "no disfrutéis",
			Uds: "no disfruten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy disfrutando",
			tú: "estás disfrutando",
			Ud: "está disfrutando",
			nosotros: "estamos disfrutando",
			vosotros: "estáis disfrutando",
			Uds: "están disfrutando",
		},
		Preterite: {
			yo: "estuve disfrutando",
			tú: "estuviste disfrutando",
			Ud: "estuvo disfrutando",
			nosotros: "estuvimos disfrutando",
			vosotros: "estuvisteis disfrutando",
			Uds: "estuvieron disfrutando",
		},
		Imperfect: {
			Uds: "estaban disfrutando",
			yo: "estaba disfrutando",
			tú: "estabas disfrutando",
			Ud: "estaba disfrutando",
			nosotros: "estábamos disfrutando",
			vosotros: "estabais disfrutando",
		},
		Conditional: {
			yo: "estaría disfrutando",
			tú: "estarías disfrutando",
			Ud: "estaría disfrutando",
			nosotros: "estaríamos disfrutando",
			vosotros: "estaríais disfrutando",
			Uds: "estarían disfrutando",
		},
		Future: {
			yo: "estaré disfrutando",
			tú: "estarás disfrutando",
			Ud: "estará disfrutando",
			nosotros: "estaremos disfrutando",
			vosotros: "estaréis disfrutando",
			Uds: "estarán disfrutando",
		},
	},
	Perfect: {
		Present: {
			yo: "he disfrutado",
			tú: "has disfrutado",
			Ud: "ha disfrutado",
			nosotros: "hemos disfrutado",
			vosotros: "habéis disfrutado",
			Uds: "han disfrutado",
		},
		Preterite: {
			yo: "hube disfrutado",
			tú: "hubiste disfrutado",
			Ud: "hubo disfrutado",
			nosotros: "hubimos disfrutado",
			vosotros: "hubisteis disfrutado",
			Uds: "hubieron disfrutado",
		},
		Past: {
			yo: "había disfrutado",
			tú: "habías disfrutado",
			Ud: "había disfrutado",
			nosotros: "habíamos disfrutado",
			vosotros: "habíais disfrutado",
			Uds: "habían disfrutado",
		},
		Conditional: {
			yo: "habría disfrutado",
			tú: "habrías disfrutado",
			Ud: "habría disfrutado",
			nosotros: "habríamos disfrutado",
			vosotros: "habríais disfrutado",
			Uds: "habrían disfrutado",
		},
		Future: {
			yo: "habré disfrutado",
			tú: "habrás disfrutado",
			Ud: "habrá disfrutado",
			nosotros: "habremos disfrutado",
			vosotros: "habréis disfrutado",
			Uds: "habrán disfrutado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya disfrutado",
			tú: "hayas disfrutado",
			Ud: "haya disfrutado",
			nosotros: "hayamos disfrutado",
			vosotros: "hayáis disfrutado",
			Uds: "hayan disfrutado",
		},
		Past: {
			yo: "hubiera disfrutado",
			tú: "hubieras disfrutado",
			Ud: "hubiera disfrutado",
			nosotros: "hubiéramos disfrutado",
			vosotros: "hubierais disfrutado",
			Uds: "hubieran disfrutado",
		},
		Future: {
			yo: "hubiere disfrutado",
			tú: "hubieres disfrutado",
			Ud: "hubiere disfrutado",
			nosotros: "hubiéremos disfrutado",
			vosotros: "hubiereis disfrutado",
			Uds: "hubieren disfrutado",
		},
	},
}
