var disgustar = {
	Indicative: {
		Present: {
			yo: "disgusto",
			tú: "disgustas",
			Ud: "disgusta",
			nosotros: "disgustamos",
			vosotros: "disgustáis",
			Uds: "disgustan",
		},
		Preterite: {
			yo: "disgusté",
			tú: "disgustaste",
			Ud: "disgustó",
			nosotros: "disgustamos",
			vosotros: "disgustasteis",
			Uds: "disgustaron",
		},
		Imperfect: {
			yo: "disgustaba",
			tú: "disgustabas",
			Ud: "disgustaba",
			nosotros: "disgustábamos",
			vosotros: "disgustabais",
			Uds: "disgustaban",
		},
		Conditional: {
			yo: "disgustaría",
			tú: "disgustarías",
			Ud: "disgustaría",
			nosotros: "disgustaríamos",
			vosotros: "disgustaríais",
			Uds: "disgustarían",
		},
		Future: {
			yo: "disgustaré",
			tú: "disgustarás",
			Ud: "disgustará",
			nosotros: "disgustaremos",
			vosotros: "disgustaréis",
			Uds: "disgustarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "disguste",
			tú: "disgustes",
			Ud: "disguste",
			nosotros: "disgustemos",
			vosotros: "disgustéis",
			Uds: "disgusten",
		},
		Imperfect: {
			yo: "disgustara",
			tú: "disgustaras",
			Ud: "disgustara",
			nosotros: "disgustáramos",
			vosotros: "disgustarais",
			Uds: "disgustaran",
		},
		Imperfect2: {
			yo: "disgustase",
			tú: "disgustases",
			Ud: "disgustase",
			nosotros: "disgustásemos",
			vosotros: "disgustaseis",
			Uds: "disgustasen",
		},
		Future: {
			yo: "disgustare",
			tú: "disgustares",
			Ud: "disgustare",
			nosotros: "disgustáremos",
			vosotros: "disgustareis",
			Uds: "disgustaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "disgusta",
			Ud: "disguste",
			nosotros: "disgustemos",
			vosotros: "disgustad",
			Uds: "disgusten",
		},
		Negative: {
			tú: "no disgustes",
			Ud: "no disguste",
			nosotros: "no disgustemos",
			vosotros: "no disgustéis",
			Uds: "no disgusten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy disgustando",
			tú: "estás disgustando",
			Ud: "está disgustando",
			nosotros: "estamos disgustando",
			vosotros: "estáis disgustando",
			Uds: "están disgustando",
		},
		Preterite: {
			yo: "estuve disgustando",
			tú: "estuviste disgustando",
			Ud: "estuvo disgustando",
			nosotros: "estuvimos disgustando",
			vosotros: "estuvisteis disgustando",
			Uds: "estuvieron disgustando",
		},
		Imperfect: {
			Uds: "estaban disgustando",
			yo: "estaba disgustando",
			tú: "estabas disgustando",
			Ud: "estaba disgustando",
			nosotros: "estábamos disgustando",
			vosotros: "estabais disgustando",
		},
		Conditional: {
			yo: "estaría disgustando",
			tú: "estarías disgustando",
			Ud: "estaría disgustando",
			nosotros: "estaríamos disgustando",
			vosotros: "estaríais disgustando",
			Uds: "estarían disgustando",
		},
		Future: {
			yo: "estaré disgustando",
			tú: "estarás disgustando",
			Ud: "estará disgustando",
			nosotros: "estaremos disgustando",
			vosotros: "estaréis disgustando",
			Uds: "estarán disgustando",
		},
	},
	Perfect: {
		Present: {
			yo: "he disgustado",
			tú: "has disgustado",
			Ud: "ha disgustado",
			nosotros: "hemos disgustado",
			vosotros: "habéis disgustado",
			Uds: "han disgustado",
		},
		Preterite: {
			yo: "hube disgustado",
			tú: "hubiste disgustado",
			Ud: "hubo disgustado",
			nosotros: "hubimos disgustado",
			vosotros: "hubisteis disgustado",
			Uds: "hubieron disgustado",
		},
		Past: {
			yo: "había disgustado",
			tú: "habías disgustado",
			Ud: "había disgustado",
			nosotros: "habíamos disgustado",
			vosotros: "habíais disgustado",
			Uds: "habían disgustado",
		},
		Conditional: {
			yo: "habría disgustado",
			tú: "habrías disgustado",
			Ud: "habría disgustado",
			nosotros: "habríamos disgustado",
			vosotros: "habríais disgustado",
			Uds: "habrían disgustado",
		},
		Future: {
			yo: "habré disgustado",
			tú: "habrás disgustado",
			Ud: "habrá disgustado",
			nosotros: "habremos disgustado",
			vosotros: "habréis disgustado",
			Uds: "habrán disgustado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya disgustado",
			tú: "hayas disgustado",
			Ud: "haya disgustado",
			nosotros: "hayamos disgustado",
			vosotros: "hayáis disgustado",
			Uds: "hayan disgustado",
		},
		Past: {
			yo: "hubiera disgustado",
			tú: "hubieras disgustado",
			Ud: "hubiera disgustado",
			nosotros: "hubiéramos disgustado",
			vosotros: "hubierais disgustado",
			Uds: "hubieran disgustado",
		},
		Future: {
			yo: "hubiere disgustado",
			tú: "hubieres disgustado",
			Ud: "hubiere disgustado",
			nosotros: "hubiéremos disgustado",
			vosotros: "hubiereis disgustado",
			Uds: "hubieren disgustado",
		},
	},
}
