var disipar = {
	Indicative: {
		Present: {
			yo: "disipo",
			tú: "disipas",
			Ud: "disipa",
			nosotros: "disipamos",
			vosotros: "disipáis",
			Uds: "disipan",
		},
		Preterite: {
			yo: "disipé",
			tú: "disipaste",
			Ud: "disipó",
			nosotros: "disipamos",
			vosotros: "disipasteis",
			Uds: "disiparon",
		},
		Imperfect: {
			yo: "disipaba",
			tú: "disipabas",
			Ud: "disipaba",
			nosotros: "disipábamos",
			vosotros: "disipabais",
			Uds: "disipaban",
		},
		Conditional: {
			yo: "disiparía",
			tú: "disiparías",
			Ud: "disiparía",
			nosotros: "disiparíamos",
			vosotros: "disiparíais",
			Uds: "disiparían",
		},
		Future: {
			yo: "disiparé",
			tú: "disiparás",
			Ud: "disipará",
			nosotros: "disiparemos",
			vosotros: "disiparéis",
			Uds: "disiparán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "disipe",
			tú: "disipes",
			Ud: "disipe",
			nosotros: "disipemos",
			vosotros: "disipéis",
			Uds: "disipen",
		},
		Imperfect: {
			yo: "disipara",
			tú: "disiparas",
			Ud: "disipara",
			nosotros: "disipáramos",
			vosotros: "disiparais",
			Uds: "disiparan",
		},
		Imperfect2: {
			yo: "disipase",
			tú: "disipases",
			Ud: "disipase",
			nosotros: "disipásemos",
			vosotros: "disipaseis",
			Uds: "disipasen",
		},
		Future: {
			yo: "disipare",
			tú: "disipares",
			Ud: "disipare",
			nosotros: "disipáremos",
			vosotros: "disipareis",
			Uds: "disiparen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "disipa",
			Ud: "disipe",
			nosotros: "disipemos",
			vosotros: "disipad",
			Uds: "disipen",
		},
		Negative: {
			tú: "no disipes",
			Ud: "no disipe",
			nosotros: "no disipemos",
			vosotros: "no disipéis",
			Uds: "no disipen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy disipando",
			tú: "estás disipando",
			Ud: "está disipando",
			nosotros: "estamos disipando",
			vosotros: "estáis disipando",
			Uds: "están disipando",
		},
		Preterite: {
			yo: "estuve disipando",
			tú: "estuviste disipando",
			Ud: "estuvo disipando",
			nosotros: "estuvimos disipando",
			vosotros: "estuvisteis disipando",
			Uds: "estuvieron disipando",
		},
		Imperfect: {
			Uds: "estaban disipando",
			yo: "estaba disipando",
			tú: "estabas disipando",
			Ud: "estaba disipando",
			nosotros: "estábamos disipando",
			vosotros: "estabais disipando",
		},
		Conditional: {
			yo: "estaría disipando",
			tú: "estarías disipando",
			Ud: "estaría disipando",
			nosotros: "estaríamos disipando",
			vosotros: "estaríais disipando",
			Uds: "estarían disipando",
		},
		Future: {
			yo: "estaré disipando",
			tú: "estarás disipando",
			Ud: "estará disipando",
			nosotros: "estaremos disipando",
			vosotros: "estaréis disipando",
			Uds: "estarán disipando",
		},
	},
	Perfect: {
		Present: {
			yo: "he disipado",
			tú: "has disipado",
			Ud: "ha disipado",
			nosotros: "hemos disipado",
			vosotros: "habéis disipado",
			Uds: "han disipado",
		},
		Preterite: {
			yo: "hube disipado",
			tú: "hubiste disipado",
			Ud: "hubo disipado",
			nosotros: "hubimos disipado",
			vosotros: "hubisteis disipado",
			Uds: "hubieron disipado",
		},
		Past: {
			yo: "había disipado",
			tú: "habías disipado",
			Ud: "había disipado",
			nosotros: "habíamos disipado",
			vosotros: "habíais disipado",
			Uds: "habían disipado",
		},
		Conditional: {
			yo: "habría disipado",
			tú: "habrías disipado",
			Ud: "habría disipado",
			nosotros: "habríamos disipado",
			vosotros: "habríais disipado",
			Uds: "habrían disipado",
		},
		Future: {
			yo: "habré disipado",
			tú: "habrás disipado",
			Ud: "habrá disipado",
			nosotros: "habremos disipado",
			vosotros: "habréis disipado",
			Uds: "habrán disipado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya disipado",
			tú: "hayas disipado",
			Ud: "haya disipado",
			nosotros: "hayamos disipado",
			vosotros: "hayáis disipado",
			Uds: "hayan disipado",
		},
		Past: {
			yo: "hubiera disipado",
			tú: "hubieras disipado",
			Ud: "hubiera disipado",
			nosotros: "hubiéramos disipado",
			vosotros: "hubierais disipado",
			Uds: "hubieran disipado",
		},
		Future: {
			yo: "hubiere disipado",
			tú: "hubieres disipado",
			Ud: "hubiere disipado",
			nosotros: "hubiéremos disipado",
			vosotros: "hubiereis disipado",
			Uds: "hubieren disipado",
		},
	},
}
