var disponer = {
	Indicative: {
		Present: {
			yo: "dispongo",
			tú: "dispones",
			Ud: "dispone",
			nosotros: "disponemos",
			vosotros: "disponéis",
			Uds: "disponen",
		},
		Preterite: {
			yo: "dispuse",
			tú: "dispusiste",
			Ud: "dispuso",
			nosotros: "dispusimos",
			vosotros: "dispusisteis",
			Uds: "dispusieron",
		},
		Imperfect: {
			yo: "disponía",
			tú: "disponías",
			Ud: "disponía",
			nosotros: "disponíamos",
			vosotros: "disponíais",
			Uds: "disponían",
		},
		Conditional: {
			yo: "dispondría",
			tú: "dispondrías",
			Ud: "dispondría",
			nosotros: "dispondríamos",
			vosotros: "dispondríais",
			Uds: "dispondrían",
		},
		Future: {
			yo: "dispondré",
			tú: "dispondrás",
			Ud: "dispondrá",
			nosotros: "dispondremos",
			vosotros: "dispondréis",
			Uds: "dispondrán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "disponga",
			tú: "dispongas",
			Ud: "disponga",
			nosotros: "dispongamos",
			vosotros: "dispongáis",
			Uds: "dispongan",
		},
		Imperfect: {
			yo: "dispusiera",
			tú: "dispusieras",
			Ud: "dispusiera",
			nosotros: "dispusiéramos",
			vosotros: "dispusierais",
			Uds: "dispusieran",
		},
		Imperfect2: {
			yo: "dispusiese",
			tú: "dispusieses",
			Ud: "dispusiese",
			nosotros: "dispusiésemos",
			vosotros: "dispusieseis",
			Uds: "dispusiesen",
		},
		Future: {
			yo: "dispusiere",
			tú: "dispusieres",
			Ud: "dispusiere",
			nosotros: "dispusiéremos",
			vosotros: "dispusiereis",
			Uds: "dispusieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "dispón",
			Ud: "disponga",
			nosotros: "dispongamos",
			vosotros: "disponed",
			Uds: "dispongan",
		},
		Negative: {
			tú: "no dispongas",
			Ud: "no disponga",
			nosotros: "no dispongamos",
			vosotros: "no dispongáis",
			Uds: "no dispongan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy disponiendo",
			tú: "estás disponiendo",
			Ud: "está disponiendo",
			nosotros: "estamos disponiendo",
			vosotros: "estáis disponiendo",
			Uds: "están disponiendo",
		},
		Preterite: {
			yo: "estuve disponiendo",
			tú: "estuviste disponiendo",
			Ud: "estuvo disponiendo",
			nosotros: "estuvimos disponiendo",
			vosotros: "estuvisteis disponiendo",
			Uds: "estuvieron disponiendo",
		},
		Imperfect: {
			Uds: "estaban disponiendo",
			yo: "estaba disponiendo",
			tú: "estabas disponiendo",
			Ud: "estaba disponiendo",
			nosotros: "estábamos disponiendo",
			vosotros: "estabais disponiendo",
		},
		Conditional: {
			yo: "estaría disponiendo",
			tú: "estarías disponiendo",
			Ud: "estaría disponiendo",
			nosotros: "estaríamos disponiendo",
			vosotros: "estaríais disponiendo",
			Uds: "estarían disponiendo",
		},
		Future: {
			yo: "estaré disponiendo",
			tú: "estarás disponiendo",
			Ud: "estará disponiendo",
			nosotros: "estaremos disponiendo",
			vosotros: "estaréis disponiendo",
			Uds: "estarán disponiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he dispuesto",
			tú: "has dispuesto",
			Ud: "ha dispuesto",
			nosotros: "hemos dispuesto",
			vosotros: "habéis dispuesto",
			Uds: "han dispuesto",
		},
		Preterite: {
			yo: "hube dispuesto",
			tú: "hubiste dispuesto",
			Ud: "hubo dispuesto",
			nosotros: "hubimos dispuesto",
			vosotros: "hubisteis dispuesto",
			Uds: "hubieron dispuesto",
		},
		Past: {
			yo: "había dispuesto",
			tú: "habías dispuesto",
			Ud: "había dispuesto",
			nosotros: "habíamos dispuesto",
			vosotros: "habíais dispuesto",
			Uds: "habían dispuesto",
		},
		Conditional: {
			yo: "habría dispuesto",
			tú: "habrías dispuesto",
			Ud: "habría dispuesto",
			nosotros: "habríamos dispuesto",
			vosotros: "habríais dispuesto",
			Uds: "habrían dispuesto",
		},
		Future: {
			yo: "habré dispuesto",
			tú: "habrás dispuesto",
			Ud: "habrá dispuesto",
			nosotros: "habremos dispuesto",
			vosotros: "habréis dispuesto",
			Uds: "habrán dispuesto",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya dispuesto",
			tú: "hayas dispuesto",
			Ud: "haya dispuesto",
			nosotros: "hayamos dispuesto",
			vosotros: "hayáis dispuesto",
			Uds: "hayan dispuesto",
		},
		Past: {
			yo: "hubiera dispuesto",
			tú: "hubieras dispuesto",
			Ud: "hubiera dispuesto",
			nosotros: "hubiéramos dispuesto",
			vosotros: "hubierais dispuesto",
			Uds: "hubieran dispuesto",
		},
		Future: {
			yo: "hubiere dispuesto",
			tú: "hubieres dispuesto",
			Ud: "hubiere dispuesto",
			nosotros: "hubiéremos dispuesto",
			vosotros: "hubiereis dispuesto",
			Uds: "hubieren dispuesto",
		},
	},
}
