var distraer = {
	Indicative: {
		Present: {
			yo: "distraigo",
			tú: "distraes",
			Ud: "distrae",
			nosotros: "distraemos",
			vosotros: "distraéis",
			Uds: "distraen",
		},
		Preterite: {
			yo: "distraje",
			tú: "distrajiste",
			Ud: "distrajo",
			nosotros: "distrajimos",
			vosotros: "distrajisteis",
			Uds: "distrajeron",
		},
		Imperfect: {
			yo: "distraía",
			tú: "distraías",
			Ud: "distraía",
			nosotros: "distraíamos",
			vosotros: "distraíais",
			Uds: "distraían",
		},
		Conditional: {
			yo: "distraería",
			tú: "distraerías",
			Ud: "distraería",
			nosotros: "distraeríamos",
			vosotros: "distraeríais",
			Uds: "distraerían",
		},
		Future: {
			yo: "distraeré",
			tú: "distraerás",
			Ud: "distraerá",
			nosotros: "distraeremos",
			vosotros: "distraeréis",
			Uds: "distraerán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "distraiga",
			tú: "distraigas",
			Ud: "distraiga",
			nosotros: "distraigamos",
			vosotros: "distraigáis",
			Uds: "distraigan",
		},
		Imperfect: {
			yo: "distrajera",
			tú: "distrajeras",
			Ud: "distrajera",
			nosotros: "distrajéramos",
			vosotros: "distrajerais",
			Uds: "distrajeran",
		},
		Imperfect2: {
			yo: "distrajese",
			tú: "distrajeses",
			Ud: "distrajese",
			nosotros: "distrajésemos",
			vosotros: "distrajeseis",
			Uds: "distrajesen",
		},
		Future: {
			yo: "distrajere",
			tú: "distrajeres",
			Ud: "distrajere",
			nosotros: "distrajéremos",
			vosotros: "distrajereis",
			Uds: "distrajeren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "distrae",
			Ud: "distraiga",
			nosotros: "distraigamos",
			vosotros: "distraed",
			Uds: "distraigan",
		},
		Negative: {
			tú: "no distraigas",
			Ud: "no distraiga",
			nosotros: "no distraigamos",
			vosotros: "no distraigáis",
			Uds: "no distraigan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy distrayendo",
			tú: "estás distrayendo",
			Ud: "está distrayendo",
			nosotros: "estamos distrayendo",
			vosotros: "estáis distrayendo",
			Uds: "están distrayendo",
		},
		Preterite: {
			yo: "estuve distrayendo",
			tú: "estuviste distrayendo",
			Ud: "estuvo distrayendo",
			nosotros: "estuvimos distrayendo",
			vosotros: "estuvisteis distrayendo",
			Uds: "estuvieron distrayendo",
		},
		Imperfect: {
			Uds: "estaban distrayendo",
			yo: "estaba distrayendo",
			tú: "estabas distrayendo",
			Ud: "estaba distrayendo",
			nosotros: "estábamos distrayendo",
			vosotros: "estabais distrayendo",
		},
		Conditional: {
			yo: "estaría distrayendo",
			tú: "estarías distrayendo",
			Ud: "estaría distrayendo",
			nosotros: "estaríamos distrayendo",
			vosotros: "estaríais distrayendo",
			Uds: "estarían distrayendo",
		},
		Future: {
			yo: "estaré distrayendo",
			tú: "estarás distrayendo",
			Ud: "estará distrayendo",
			nosotros: "estaremos distrayendo",
			vosotros: "estaréis distrayendo",
			Uds: "estarán distrayendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he distraído",
			tú: "has distraído",
			Ud: "ha distraído",
			nosotros: "hemos distraído",
			vosotros: "habéis distraído",
			Uds: "han distraído",
		},
		Preterite: {
			yo: "hube distraído",
			tú: "hubiste distraído",
			Ud: "hubo distraído",
			nosotros: "hubimos distraído",
			vosotros: "hubisteis distraído",
			Uds: "hubieron distraído",
		},
		Past: {
			yo: "había distraído",
			tú: "habías distraído",
			Ud: "había distraído",
			nosotros: "habíamos distraído",
			vosotros: "habíais distraído",
			Uds: "habían distraído",
		},
		Conditional: {
			yo: "habría distraído",
			tú: "habrías distraído",
			Ud: "habría distraído",
			nosotros: "habríamos distraído",
			vosotros: "habríais distraído",
			Uds: "habrían distraído",
		},
		Future: {
			yo: "habré distraído",
			tú: "habrás distraído",
			Ud: "habrá distraído",
			nosotros: "habremos distraído",
			vosotros: "habréis distraído",
			Uds: "habrán distraído",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya distraído",
			tú: "hayas distraído",
			Ud: "haya distraído",
			nosotros: "hayamos distraído",
			vosotros: "hayáis distraído",
			Uds: "hayan distraído",
		},
		Past: {
			yo: "hubiera distraído",
			tú: "hubieras distraído",
			Ud: "hubiera distraído",
			nosotros: "hubiéramos distraído",
			vosotros: "hubierais distraído",
			Uds: "hubieran distraído",
		},
		Future: {
			yo: "hubiere distraído",
			tú: "hubieres distraído",
			Ud: "hubiere distraído",
			nosotros: "hubiéremos distraído",
			vosotros: "hubiereis distraído",
			Uds: "hubieren distraído",
		},
	},
}
