var disuadir = {
	Indicative: {
		Present: {
			yo: "disuado",
			tú: "disuades",
			Ud: "disuade",
			nosotros: "disuadimos",
			vosotros: "disuadís",
			Uds: "disuaden",
		},
		Preterite: {
			yo: "disuadí",
			tú: "disuadiste",
			Ud: "disuadió",
			nosotros: "disuadimos",
			vosotros: "disuadisteis",
			Uds: "disuadieron",
		},
		Imperfect: {
			yo: "disuadía",
			tú: "disuadías",
			Ud: "disuadía",
			nosotros: "disuadíamos",
			vosotros: "disuadíais",
			Uds: "disuadían",
		},
		Conditional: {
			yo: "disuadiría",
			tú: "disuadirías",
			Ud: "disuadiría",
			nosotros: "disuadiríamos",
			vosotros: "disuadiríais",
			Uds: "disuadirían",
		},
		Future: {
			yo: "disuadiré",
			tú: "disuadirás",
			Ud: "disuadirá",
			nosotros: "disuadiremos",
			vosotros: "disuadiréis",
			Uds: "disuadirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "disuada",
			tú: "disuadas",
			Ud: "disuada",
			nosotros: "disuadamos",
			vosotros: "disuadáis",
			Uds: "disuadan",
		},
		Imperfect: {
			yo: "disuadiera",
			tú: "disuadieras",
			Ud: "disuadiera",
			nosotros: "disuadiéramos",
			vosotros: "disuadierais",
			Uds: "disuadieran",
		},
		Imperfect2: {
			yo: "disuadiese",
			tú: "disuadieses",
			Ud: "disuadiese",
			nosotros: "disuadiésemos",
			vosotros: "disuadieseis",
			Uds: "disuadiesen",
		},
		Future: {
			yo: "disuadiere",
			tú: "disuadieres",
			Ud: "disuadiere",
			nosotros: "disuadiéremos",
			vosotros: "disuadiereis",
			Uds: "disuadieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "disuade",
			Ud: "disuada",
			nosotros: "disuadamos",
			vosotros: "disuadid",
			Uds: "disuadan",
		},
		Negative: {
			tú: "no disuadas",
			Ud: "no disuada",
			nosotros: "no disuadamos",
			vosotros: "no disuadáis",
			Uds: "no disuadan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy disuadiendo",
			tú: "estás disuadiendo",
			Ud: "está disuadiendo",
			nosotros: "estamos disuadiendo",
			vosotros: "estáis disuadiendo",
			Uds: "están disuadiendo",
		},
		Preterite: {
			yo: "estuve disuadiendo",
			tú: "estuviste disuadiendo",
			Ud: "estuvo disuadiendo",
			nosotros: "estuvimos disuadiendo",
			vosotros: "estuvisteis disuadiendo",
			Uds: "estuvieron disuadiendo",
		},
		Imperfect: {
			Uds: "estaban disuadiendo",
			yo: "estaba disuadiendo",
			tú: "estabas disuadiendo",
			Ud: "estaba disuadiendo",
			nosotros: "estábamos disuadiendo",
			vosotros: "estabais disuadiendo",
		},
		Conditional: {
			yo: "estaría disuadiendo",
			tú: "estarías disuadiendo",
			Ud: "estaría disuadiendo",
			nosotros: "estaríamos disuadiendo",
			vosotros: "estaríais disuadiendo",
			Uds: "estarían disuadiendo",
		},
		Future: {
			yo: "estaré disuadiendo",
			tú: "estarás disuadiendo",
			Ud: "estará disuadiendo",
			nosotros: "estaremos disuadiendo",
			vosotros: "estaréis disuadiendo",
			Uds: "estarán disuadiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he disuadido",
			tú: "has disuadido",
			Ud: "ha disuadido",
			nosotros: "hemos disuadido",
			vosotros: "habéis disuadido",
			Uds: "han disuadido",
		},
		Preterite: {
			yo: "hube disuadido",
			tú: "hubiste disuadido",
			Ud: "hubo disuadido",
			nosotros: "hubimos disuadido",
			vosotros: "hubisteis disuadido",
			Uds: "hubieron disuadido",
		},
		Past: {
			yo: "había disuadido",
			tú: "habías disuadido",
			Ud: "había disuadido",
			nosotros: "habíamos disuadido",
			vosotros: "habíais disuadido",
			Uds: "habían disuadido",
		},
		Conditional: {
			yo: "habría disuadido",
			tú: "habrías disuadido",
			Ud: "habría disuadido",
			nosotros: "habríamos disuadido",
			vosotros: "habríais disuadido",
			Uds: "habrían disuadido",
		},
		Future: {
			yo: "habré disuadido",
			tú: "habrás disuadido",
			Ud: "habrá disuadido",
			nosotros: "habremos disuadido",
			vosotros: "habréis disuadido",
			Uds: "habrán disuadido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya disuadido",
			tú: "hayas disuadido",
			Ud: "haya disuadido",
			nosotros: "hayamos disuadido",
			vosotros: "hayáis disuadido",
			Uds: "hayan disuadido",
		},
		Past: {
			yo: "hubiera disuadido",
			tú: "hubieras disuadido",
			Ud: "hubiera disuadido",
			nosotros: "hubiéramos disuadido",
			vosotros: "hubierais disuadido",
			Uds: "hubieran disuadido",
		},
		Future: {
			yo: "hubiere disuadido",
			tú: "hubieres disuadido",
			Ud: "hubiere disuadido",
			nosotros: "hubiéremos disuadido",
			vosotros: "hubiereis disuadido",
			Uds: "hubieren disuadido",
		},
	},
}
