var divertir = {
	Indicative: {
		Present: {
			yo: "divierto",
			tú: "diviertes",
			Ud: "divierte",
			nosotros: "divertimos",
			vosotros: "divertís",
			Uds: "divierten",
		},
		Preterite: {
			yo: "divertí",
			tú: "divertiste",
			Ud: "divirtió",
			nosotros: "divertimos",
			vosotros: "divertisteis",
			Uds: "divirtieron",
		},
		Imperfect: {
			yo: "divertía",
			tú: "divertías",
			Ud: "divertía",
			nosotros: "divertíamos",
			vosotros: "divertíais",
			Uds: "divertían",
		},
		Conditional: {
			yo: "divertiría",
			tú: "divertirías",
			Ud: "divertiría",
			nosotros: "divertiríamos",
			vosotros: "divertiríais",
			Uds: "divertirían",
		},
		Future: {
			yo: "divertiré",
			tú: "divertirás",
			Ud: "divertirá",
			nosotros: "divertiremos",
			vosotros: "divertiréis",
			Uds: "divertirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "divierta",
			tú: "diviertas",
			Ud: "divierta",
			nosotros: "divirtamos",
			vosotros: "divirtáis",
			Uds: "diviertan",
		},
		Imperfect: {
			yo: "divirtiera",
			tú: "divirtieras",
			Ud: "divirtiera",
			nosotros: "divirtiéramos",
			vosotros: "divirtierais",
			Uds: "divirtieran",
		},
		Imperfect2: {
			yo: "divirtiese",
			tú: "divirtieses",
			Ud: "divirtiese",
			nosotros: "divirtiésemos",
			vosotros: "divirtieseis",
			Uds: "divirtiesen",
		},
		Future: {
			yo: "divirtiere",
			tú: "divirtieres",
			Ud: "divirtiere",
			nosotros: "divirtiéremos",
			vosotros: "divirtiereis",
			Uds: "divirtieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "divierte",
			Ud: "divierta",
			nosotros: "divirtamos",
			vosotros: "divertid",
			Uds: "diviertan",
		},
		Negative: {
			tú: "no diviertas",
			Ud: "no divierta",
			nosotros: "no divirtamos",
			vosotros: "no divirtáis",
			Uds: "no diviertan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy divirtiendo",
			tú: "estás divirtiendo",
			Ud: "está divirtiendo",
			nosotros: "estamos divirtiendo",
			vosotros: "estáis divirtiendo",
			Uds: "están divirtiendo",
		},
		Preterite: {
			yo: "estuve divirtiendo",
			tú: "estuviste divirtiendo",
			Ud: "estuvo divirtiendo",
			nosotros: "estuvimos divirtiendo",
			vosotros: "estuvisteis divirtiendo",
			Uds: "estuvieron divirtiendo",
		},
		Imperfect: {
			Uds: "estaban divirtiendo",
			yo: "estaba divirtiendo",
			tú: "estabas divirtiendo",
			Ud: "estaba divirtiendo",
			nosotros: "estábamos divirtiendo",
			vosotros: "estabais divirtiendo",
		},
		Conditional: {
			yo: "estaría divirtiendo",
			tú: "estarías divirtiendo",
			Ud: "estaría divirtiendo",
			nosotros: "estaríamos divirtiendo",
			vosotros: "estaríais divirtiendo",
			Uds: "estarían divirtiendo",
		},
		Future: {
			yo: "estaré divirtiendo",
			tú: "estarás divirtiendo",
			Ud: "estará divirtiendo",
			nosotros: "estaremos divirtiendo",
			vosotros: "estaréis divirtiendo",
			Uds: "estarán divirtiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he divertido",
			tú: "has divertido",
			Ud: "ha divertido",
			nosotros: "hemos divertido",
			vosotros: "habéis divertido",
			Uds: "han divertido",
		},
		Preterite: {
			yo: "hube divertido",
			tú: "hubiste divertido",
			Ud: "hubo divertido",
			nosotros: "hubimos divertido",
			vosotros: "hubisteis divertido",
			Uds: "hubieron divertido",
		},
		Past: {
			yo: "había divertido",
			tú: "habías divertido",
			Ud: "había divertido",
			nosotros: "habíamos divertido",
			vosotros: "habíais divertido",
			Uds: "habían divertido",
		},
		Conditional: {
			yo: "habría divertido",
			tú: "habrías divertido",
			Ud: "habría divertido",
			nosotros: "habríamos divertido",
			vosotros: "habríais divertido",
			Uds: "habrían divertido",
		},
		Future: {
			yo: "habré divertido",
			tú: "habrás divertido",
			Ud: "habrá divertido",
			nosotros: "habremos divertido",
			vosotros: "habréis divertido",
			Uds: "habrán divertido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya divertido",
			tú: "hayas divertido",
			Ud: "haya divertido",
			nosotros: "hayamos divertido",
			vosotros: "hayáis divertido",
			Uds: "hayan divertido",
		},
		Past: {
			yo: "hubiera divertido",
			tú: "hubieras divertido",
			Ud: "hubiera divertido",
			nosotros: "hubiéramos divertido",
			vosotros: "hubierais divertido",
			Uds: "hubieran divertido",
		},
		Future: {
			yo: "hubiere divertido",
			tú: "hubieres divertido",
			Ud: "hubiere divertido",
			nosotros: "hubiéremos divertido",
			vosotros: "hubiereis divertido",
			Uds: "hubieren divertido",
		},
	},
}
