var dividir = {
	Indicative: {
		Present: {
			yo: "divido",
			tú: "divides",
			Ud: "divide",
			nosotros: "dividimos",
			vosotros: "dividís",
			Uds: "dividen",
		},
		Preterite: {
			yo: "dividí",
			tú: "dividiste",
			Ud: "dividió",
			nosotros: "dividimos",
			vosotros: "dividisteis",
			Uds: "dividieron",
		},
		Imperfect: {
			yo: "dividía",
			tú: "dividías",
			Ud: "dividía",
			nosotros: "dividíamos",
			vosotros: "dividíais",
			Uds: "dividían",
		},
		Conditional: {
			yo: "dividiría",
			tú: "dividirías",
			Ud: "dividiría",
			nosotros: "dividiríamos",
			vosotros: "dividiríais",
			Uds: "dividirían",
		},
		Future: {
			yo: "dividiré",
			tú: "dividirás",
			Ud: "dividirá",
			nosotros: "dividiremos",
			vosotros: "dividiréis",
			Uds: "dividirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "divida",
			tú: "dividas",
			Ud: "divida",
			nosotros: "dividamos",
			vosotros: "dividáis",
			Uds: "dividan",
		},
		Imperfect: {
			yo: "dividiera",
			tú: "dividieras",
			Ud: "dividiera",
			nosotros: "dividiéramos",
			vosotros: "dividierais",
			Uds: "dividieran",
		},
		Imperfect2: {
			yo: "dividiese",
			tú: "dividieses",
			Ud: "dividiese",
			nosotros: "dividiésemos",
			vosotros: "dividieseis",
			Uds: "dividiesen",
		},
		Future: {
			yo: "dividiere",
			tú: "dividieres",
			Ud: "dividiere",
			nosotros: "dividiéremos",
			vosotros: "dividiereis",
			Uds: "dividieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "divide",
			Ud: "divida",
			nosotros: "dividamos",
			vosotros: "dividid",
			Uds: "dividan",
		},
		Negative: {
			tú: "no dividas",
			Ud: "no divida",
			nosotros: "no dividamos",
			vosotros: "no dividáis",
			Uds: "no dividan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy dividiendo",
			tú: "estás dividiendo",
			Ud: "está dividiendo",
			nosotros: "estamos dividiendo",
			vosotros: "estáis dividiendo",
			Uds: "están dividiendo",
		},
		Preterite: {
			yo: "estuve dividiendo",
			tú: "estuviste dividiendo",
			Ud: "estuvo dividiendo",
			nosotros: "estuvimos dividiendo",
			vosotros: "estuvisteis dividiendo",
			Uds: "estuvieron dividiendo",
		},
		Imperfect: {
			Uds: "estaban dividiendo",
			yo: "estaba dividiendo",
			tú: "estabas dividiendo",
			Ud: "estaba dividiendo",
			nosotros: "estábamos dividiendo",
			vosotros: "estabais dividiendo",
		},
		Conditional: {
			yo: "estaría dividiendo",
			tú: "estarías dividiendo",
			Ud: "estaría dividiendo",
			nosotros: "estaríamos dividiendo",
			vosotros: "estaríais dividiendo",
			Uds: "estarían dividiendo",
		},
		Future: {
			yo: "estaré dividiendo",
			tú: "estarás dividiendo",
			Ud: "estará dividiendo",
			nosotros: "estaremos dividiendo",
			vosotros: "estaréis dividiendo",
			Uds: "estarán dividiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he dividido",
			tú: "has dividido",
			Ud: "ha dividido",
			nosotros: "hemos dividido",
			vosotros: "habéis dividido",
			Uds: "han dividido",
		},
		Preterite: {
			yo: "hube dividido",
			tú: "hubiste dividido",
			Ud: "hubo dividido",
			nosotros: "hubimos dividido",
			vosotros: "hubisteis dividido",
			Uds: "hubieron dividido",
		},
		Past: {
			yo: "había dividido",
			tú: "habías dividido",
			Ud: "había dividido",
			nosotros: "habíamos dividido",
			vosotros: "habíais dividido",
			Uds: "habían dividido",
		},
		Conditional: {
			yo: "habría dividido",
			tú: "habrías dividido",
			Ud: "habría dividido",
			nosotros: "habríamos dividido",
			vosotros: "habríais dividido",
			Uds: "habrían dividido",
		},
		Future: {
			yo: "habré dividido",
			tú: "habrás dividido",
			Ud: "habrá dividido",
			nosotros: "habremos dividido",
			vosotros: "habréis dividido",
			Uds: "habrán dividido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya dividido",
			tú: "hayas dividido",
			Ud: "haya dividido",
			nosotros: "hayamos dividido",
			vosotros: "hayáis dividido",
			Uds: "hayan dividido",
		},
		Past: {
			yo: "hubiera dividido",
			tú: "hubieras dividido",
			Ud: "hubiera dividido",
			nosotros: "hubiéramos dividido",
			vosotros: "hubierais dividido",
			Uds: "hubieran dividido",
		},
		Future: {
			yo: "hubiere dividido",
			tú: "hubieres dividido",
			Ud: "hubiere dividido",
			nosotros: "hubiéremos dividido",
			vosotros: "hubiereis dividido",
			Uds: "hubieren dividido",
		},
	},
}
