var divorciar = {
	Indicative: {
		Present: {
			yo: "divorcio",
			tú: "divorcias",
			Ud: "divorcia",
			nosotros: "divorciamos",
			vosotros: "divorciáis",
			Uds: "divorcian",
		},
		Preterite: {
			yo: "divorcié",
			tú: "divorciaste",
			Ud: "divorció",
			nosotros: "divorciamos",
			vosotros: "divorciasteis",
			Uds: "divorciaron",
		},
		Imperfect: {
			yo: "divorciaba",
			tú: "divorciabas",
			Ud: "divorciaba",
			nosotros: "divorciábamos",
			vosotros: "divorciabais",
			Uds: "divorciaban",
		},
		Conditional: {
			yo: "divorciaría",
			tú: "divorciarías",
			Ud: "divorciaría",
			nosotros: "divorciaríamos",
			vosotros: "divorciaríais",
			Uds: "divorciarían",
		},
		Future: {
			yo: "divorciaré",
			tú: "divorciarás",
			Ud: "divorciará",
			nosotros: "divorciaremos",
			vosotros: "divorciaréis",
			Uds: "divorciarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "divorcie",
			tú: "divorcies",
			Ud: "divorcie",
			nosotros: "divorciemos",
			vosotros: "divorciéis",
			Uds: "divorcien",
		},
		Imperfect: {
			yo: "divorciara",
			tú: "divorciaras",
			Ud: "divorciara",
			nosotros: "divorciáramos",
			vosotros: "divorciarais",
			Uds: "divorciaran",
		},
		Imperfect2: {
			yo: "divorciase",
			tú: "divorciases",
			Ud: "divorciase",
			nosotros: "divorciásemos",
			vosotros: "divorciaseis",
			Uds: "divorciasen",
		},
		Future: {
			yo: "divorciare",
			tú: "divorciares",
			Ud: "divorciare",
			nosotros: "divorciáremos",
			vosotros: "divorciareis",
			Uds: "divorciaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "divorcia",
			Ud: "divorcie",
			nosotros: "divorciemos",
			vosotros: "divorciad",
			Uds: "divorcien",
		},
		Negative: {
			tú: "no divorcies",
			Ud: "no divorcie",
			nosotros: "no divorciemos",
			vosotros: "no divorciéis",
			Uds: "no divorcien",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy divorciando",
			tú: "estás divorciando",
			Ud: "está divorciando",
			nosotros: "estamos divorciando",
			vosotros: "estáis divorciando",
			Uds: "están divorciando",
		},
		Preterite: {
			yo: "estuve divorciando",
			tú: "estuviste divorciando",
			Ud: "estuvo divorciando",
			nosotros: "estuvimos divorciando",
			vosotros: "estuvisteis divorciando",
			Uds: "estuvieron divorciando",
		},
		Imperfect: {
			Uds: "estaban divorciando",
			yo: "estaba divorciando",
			tú: "estabas divorciando",
			Ud: "estaba divorciando",
			nosotros: "estábamos divorciando",
			vosotros: "estabais divorciando",
		},
		Conditional: {
			yo: "estaría divorciando",
			tú: "estarías divorciando",
			Ud: "estaría divorciando",
			nosotros: "estaríamos divorciando",
			vosotros: "estaríais divorciando",
			Uds: "estarían divorciando",
		},
		Future: {
			yo: "estaré divorciando",
			tú: "estarás divorciando",
			Ud: "estará divorciando",
			nosotros: "estaremos divorciando",
			vosotros: "estaréis divorciando",
			Uds: "estarán divorciando",
		},
	},
	Perfect: {
		Present: {
			yo: "he divorciado",
			tú: "has divorciado",
			Ud: "ha divorciado",
			nosotros: "hemos divorciado",
			vosotros: "habéis divorciado",
			Uds: "han divorciado",
		},
		Preterite: {
			yo: "hube divorciado",
			tú: "hubiste divorciado",
			Ud: "hubo divorciado",
			nosotros: "hubimos divorciado",
			vosotros: "hubisteis divorciado",
			Uds: "hubieron divorciado",
		},
		Past: {
			yo: "había divorciado",
			tú: "habías divorciado",
			Ud: "había divorciado",
			nosotros: "habíamos divorciado",
			vosotros: "habíais divorciado",
			Uds: "habían divorciado",
		},
		Conditional: {
			yo: "habría divorciado",
			tú: "habrías divorciado",
			Ud: "habría divorciado",
			nosotros: "habríamos divorciado",
			vosotros: "habríais divorciado",
			Uds: "habrían divorciado",
		},
		Future: {
			yo: "habré divorciado",
			tú: "habrás divorciado",
			Ud: "habrá divorciado",
			nosotros: "habremos divorciado",
			vosotros: "habréis divorciado",
			Uds: "habrán divorciado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya divorciado",
			tú: "hayas divorciado",
			Ud: "haya divorciado",
			nosotros: "hayamos divorciado",
			vosotros: "hayáis divorciado",
			Uds: "hayan divorciado",
		},
		Past: {
			yo: "hubiera divorciado",
			tú: "hubieras divorciado",
			Ud: "hubiera divorciado",
			nosotros: "hubiéramos divorciado",
			vosotros: "hubierais divorciado",
			Uds: "hubieran divorciado",
		},
		Future: {
			yo: "hubiere divorciado",
			tú: "hubieres divorciado",
			Ud: "hubiere divorciado",
			nosotros: "hubiéremos divorciado",
			vosotros: "hubiereis divorciado",
			Uds: "hubieren divorciado",
		},
	},
}
