var doblar = {
	Indicative: {
		Present: {
			yo: "doblo",
			tú: "doblas",
			Ud: "dobla",
			nosotros: "doblamos",
			vosotros: "dobláis",
			Uds: "doblan",
		},
		Preterite: {
			yo: "doblé",
			tú: "doblaste",
			Ud: "dobló",
			nosotros: "doblamos",
			vosotros: "doblasteis",
			Uds: "doblaron",
		},
		Imperfect: {
			yo: "doblaba",
			tú: "doblabas",
			Ud: "doblaba",
			nosotros: "doblábamos",
			vosotros: "doblabais",
			Uds: "doblaban",
		},
		Conditional: {
			yo: "doblaría",
			tú: "doblarías",
			Ud: "doblaría",
			nosotros: "doblaríamos",
			vosotros: "doblaríais",
			Uds: "doblarían",
		},
		Future: {
			yo: "doblaré",
			tú: "doblarás",
			Ud: "doblará",
			nosotros: "doblaremos",
			vosotros: "doblaréis",
			Uds: "doblarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "doble",
			tú: "dobles",
			Ud: "doble",
			nosotros: "doblemos",
			vosotros: "dobléis",
			Uds: "doblen",
		},
		Imperfect: {
			yo: "doblara",
			tú: "doblaras",
			Ud: "doblara",
			nosotros: "dobláramos",
			vosotros: "doblarais",
			Uds: "doblaran",
		},
		Imperfect2: {
			yo: "doblase",
			tú: "doblases",
			Ud: "doblase",
			nosotros: "doblásemos",
			vosotros: "doblaseis",
			Uds: "doblasen",
		},
		Future: {
			yo: "doblare",
			tú: "doblares",
			Ud: "doblare",
			nosotros: "dobláremos",
			vosotros: "doblareis",
			Uds: "doblaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "dobla",
			Ud: "doble",
			nosotros: "doblemos",
			vosotros: "doblad",
			Uds: "doblen",
		},
		Negative: {
			tú: "no dobles",
			Ud: "no doble",
			nosotros: "no doblemos",
			vosotros: "no dobléis",
			Uds: "no doblen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy doblando",
			tú: "estás doblando",
			Ud: "está doblando",
			nosotros: "estamos doblando",
			vosotros: "estáis doblando",
			Uds: "están doblando",
		},
		Preterite: {
			yo: "estuve doblando",
			tú: "estuviste doblando",
			Ud: "estuvo doblando",
			nosotros: "estuvimos doblando",
			vosotros: "estuvisteis doblando",
			Uds: "estuvieron doblando",
		},
		Imperfect: {
			Uds: "estaban doblando",
			yo: "estaba doblando",
			tú: "estabas doblando",
			Ud: "estaba doblando",
			nosotros: "estábamos doblando",
			vosotros: "estabais doblando",
		},
		Conditional: {
			yo: "estaría doblando",
			tú: "estarías doblando",
			Ud: "estaría doblando",
			nosotros: "estaríamos doblando",
			vosotros: "estaríais doblando",
			Uds: "estarían doblando",
		},
		Future: {
			yo: "estaré doblando",
			tú: "estarás doblando",
			Ud: "estará doblando",
			nosotros: "estaremos doblando",
			vosotros: "estaréis doblando",
			Uds: "estarán doblando",
		},
	},
	Perfect: {
		Present: {
			yo: "he doblado",
			tú: "has doblado",
			Ud: "ha doblado",
			nosotros: "hemos doblado",
			vosotros: "habéis doblado",
			Uds: "han doblado",
		},
		Preterite: {
			yo: "hube doblado",
			tú: "hubiste doblado",
			Ud: "hubo doblado",
			nosotros: "hubimos doblado",
			vosotros: "hubisteis doblado",
			Uds: "hubieron doblado",
		},
		Past: {
			yo: "había doblado",
			tú: "habías doblado",
			Ud: "había doblado",
			nosotros: "habíamos doblado",
			vosotros: "habíais doblado",
			Uds: "habían doblado",
		},
		Conditional: {
			yo: "habría doblado",
			tú: "habrías doblado",
			Ud: "habría doblado",
			nosotros: "habríamos doblado",
			vosotros: "habríais doblado",
			Uds: "habrían doblado",
		},
		Future: {
			yo: "habré doblado",
			tú: "habrás doblado",
			Ud: "habrá doblado",
			nosotros: "habremos doblado",
			vosotros: "habréis doblado",
			Uds: "habrán doblado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya doblado",
			tú: "hayas doblado",
			Ud: "haya doblado",
			nosotros: "hayamos doblado",
			vosotros: "hayáis doblado",
			Uds: "hayan doblado",
		},
		Past: {
			yo: "hubiera doblado",
			tú: "hubieras doblado",
			Ud: "hubiera doblado",
			nosotros: "hubiéramos doblado",
			vosotros: "hubierais doblado",
			Uds: "hubieran doblado",
		},
		Future: {
			yo: "hubiere doblado",
			tú: "hubieres doblado",
			Ud: "hubiere doblado",
			nosotros: "hubiéremos doblado",
			vosotros: "hubiereis doblado",
			Uds: "hubieren doblado",
		},
	},
}
