var dotar = {
	Indicative: {
		Present: {
			yo: "doto",
			tú: "dotas",
			Ud: "dota",
			nosotros: "dotamos",
			vosotros: "dotáis",
			Uds: "dotan",
		},
		Preterite: {
			yo: "doté",
			tú: "dotaste",
			Ud: "dotó",
			nosotros: "dotamos",
			vosotros: "dotasteis",
			Uds: "dotaron",
		},
		Imperfect: {
			yo: "dotaba",
			tú: "dotabas",
			Ud: "dotaba",
			nosotros: "dotábamos",
			vosotros: "dotabais",
			Uds: "dotaban",
		},
		Conditional: {
			yo: "dotaría",
			tú: "dotarías",
			Ud: "dotaría",
			nosotros: "dotaríamos",
			vosotros: "dotaríais",
			Uds: "dotarían",
		},
		Future: {
			yo: "dotaré",
			tú: "dotarás",
			Ud: "dotará",
			nosotros: "dotaremos",
			vosotros: "dotaréis",
			Uds: "dotarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "dote",
			tú: "dotes",
			Ud: "dote",
			nosotros: "dotemos",
			vosotros: "dotéis",
			Uds: "doten",
		},
		Imperfect: {
			yo: "dotara",
			tú: "dotaras",
			Ud: "dotara",
			nosotros: "dotáramos",
			vosotros: "dotarais",
			Uds: "dotaran",
		},
		Imperfect2: {
			yo: "dotase",
			tú: "dotases",
			Ud: "dotase",
			nosotros: "dotásemos",
			vosotros: "dotaseis",
			Uds: "dotasen",
		},
		Future: {
			yo: "dotare",
			tú: "dotares",
			Ud: "dotare",
			nosotros: "dotáremos",
			vosotros: "dotareis",
			Uds: "dotaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "dota",
			Ud: "dote",
			nosotros: "dotemos",
			vosotros: "dotad",
			Uds: "doten",
		},
		Negative: {
			tú: "no dotes",
			Ud: "no dote",
			nosotros: "no dotemos",
			vosotros: "no dotéis",
			Uds: "no doten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy dotando",
			tú: "estás dotando",
			Ud: "está dotando",
			nosotros: "estamos dotando",
			vosotros: "estáis dotando",
			Uds: "están dotando",
		},
		Preterite: {
			yo: "estuve dotando",
			tú: "estuviste dotando",
			Ud: "estuvo dotando",
			nosotros: "estuvimos dotando",
			vosotros: "estuvisteis dotando",
			Uds: "estuvieron dotando",
		},
		Imperfect: {
			Uds: "estaban dotando",
			yo: "estaba dotando",
			tú: "estabas dotando",
			Ud: "estaba dotando",
			nosotros: "estábamos dotando",
			vosotros: "estabais dotando",
		},
		Conditional: {
			yo: "estaría dotando",
			tú: "estarías dotando",
			Ud: "estaría dotando",
			nosotros: "estaríamos dotando",
			vosotros: "estaríais dotando",
			Uds: "estarían dotando",
		},
		Future: {
			yo: "estaré dotando",
			tú: "estarás dotando",
			Ud: "estará dotando",
			nosotros: "estaremos dotando",
			vosotros: "estaréis dotando",
			Uds: "estarán dotando",
		},
	},
	Perfect: {
		Present: {
			yo: "he dotado",
			tú: "has dotado",
			Ud: "ha dotado",
			nosotros: "hemos dotado",
			vosotros: "habéis dotado",
			Uds: "han dotado",
		},
		Preterite: {
			yo: "hube dotado",
			tú: "hubiste dotado",
			Ud: "hubo dotado",
			nosotros: "hubimos dotado",
			vosotros: "hubisteis dotado",
			Uds: "hubieron dotado",
		},
		Past: {
			yo: "había dotado",
			tú: "habías dotado",
			Ud: "había dotado",
			nosotros: "habíamos dotado",
			vosotros: "habíais dotado",
			Uds: "habían dotado",
		},
		Conditional: {
			yo: "habría dotado",
			tú: "habrías dotado",
			Ud: "habría dotado",
			nosotros: "habríamos dotado",
			vosotros: "habríais dotado",
			Uds: "habrían dotado",
		},
		Future: {
			yo: "habré dotado",
			tú: "habrás dotado",
			Ud: "habrá dotado",
			nosotros: "habremos dotado",
			vosotros: "habréis dotado",
			Uds: "habrán dotado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya dotado",
			tú: "hayas dotado",
			Ud: "haya dotado",
			nosotros: "hayamos dotado",
			vosotros: "hayáis dotado",
			Uds: "hayan dotado",
		},
		Past: {
			yo: "hubiera dotado",
			tú: "hubieras dotado",
			Ud: "hubiera dotado",
			nosotros: "hubiéramos dotado",
			vosotros: "hubierais dotado",
			Uds: "hubieran dotado",
		},
		Future: {
			yo: "hubiere dotado",
			tú: "hubieres dotado",
			Ud: "hubiere dotado",
			nosotros: "hubiéremos dotado",
			vosotros: "hubiereis dotado",
			Uds: "hubieren dotado",
		},
	},
}
