var driblar = {
	Indicative: {
		Present: {
			yo: "driblo",
			tú: "driblas",
			Ud: "dribla",
			nosotros: "driblamos",
			vosotros: "dribláis",
			Uds: "driblan",
		},
		Preterite: {
			yo: "driblé",
			tú: "driblaste",
			Ud: "dribló",
			nosotros: "driblamos",
			vosotros: "driblasteis",
			Uds: "driblaron",
		},
		Imperfect: {
			yo: "driblaba",
			tú: "driblabas",
			Ud: "driblaba",
			nosotros: "driblábamos",
			vosotros: "driblabais",
			Uds: "driblaban",
		},
		Conditional: {
			yo: "driblaría",
			tú: "driblarías",
			Ud: "driblaría",
			nosotros: "driblaríamos",
			vosotros: "driblaríais",
			Uds: "driblarían",
		},
		Future: {
			yo: "driblaré",
			tú: "driblarás",
			Ud: "driblará",
			nosotros: "driblaremos",
			vosotros: "driblaréis",
			Uds: "driblarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "drible",
			tú: "dribles",
			Ud: "drible",
			nosotros: "driblemos",
			vosotros: "dribléis",
			Uds: "driblen",
		},
		Imperfect: {
			yo: "driblara",
			tú: "driblaras",
			Ud: "driblara",
			nosotros: "dribláramos",
			vosotros: "driblarais",
			Uds: "driblaran",
		},
		Imperfect2: {
			yo: "driblase",
			tú: "driblases",
			Ud: "driblase",
			nosotros: "driblásemos",
			vosotros: "driblaseis",
			Uds: "driblasen",
		},
		Future: {
			yo: "driblare",
			tú: "driblares",
			Ud: "driblare",
			nosotros: "dribláremos",
			vosotros: "driblareis",
			Uds: "driblaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "dribla",
			Ud: "drible",
			nosotros: "driblemos",
			vosotros: "driblad",
			Uds: "driblen",
		},
		Negative: {
			tú: "no dribles",
			Ud: "no drible",
			nosotros: "no driblemos",
			vosotros: "no dribléis",
			Uds: "no driblen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy driblando",
			tú: "estás driblando",
			Ud: "está driblando",
			nosotros: "estamos driblando",
			vosotros: "estáis driblando",
			Uds: "están driblando",
		},
		Preterite: {
			yo: "estuve driblando",
			tú: "estuviste driblando",
			Ud: "estuvo driblando",
			nosotros: "estuvimos driblando",
			vosotros: "estuvisteis driblando",
			Uds: "estuvieron driblando",
		},
		Imperfect: {
			Uds: "estaban driblando",
			yo: "estaba driblando",
			tú: "estabas driblando",
			Ud: "estaba driblando",
			nosotros: "estábamos driblando",
			vosotros: "estabais driblando",
		},
		Conditional: {
			yo: "estaría driblando",
			tú: "estarías driblando",
			Ud: "estaría driblando",
			nosotros: "estaríamos driblando",
			vosotros: "estaríais driblando",
			Uds: "estarían driblando",
		},
		Future: {
			yo: "estaré driblando",
			tú: "estarás driblando",
			Ud: "estará driblando",
			nosotros: "estaremos driblando",
			vosotros: "estaréis driblando",
			Uds: "estarán driblando",
		},
	},
	Perfect: {
		Present: {
			yo: "he driblado",
			tú: "has driblado",
			Ud: "ha driblado",
			nosotros: "hemos driblado",
			vosotros: "habéis driblado",
			Uds: "han driblado",
		},
		Preterite: {
			yo: "hube driblado",
			tú: "hubiste driblado",
			Ud: "hubo driblado",
			nosotros: "hubimos driblado",
			vosotros: "hubisteis driblado",
			Uds: "hubieron driblado",
		},
		Past: {
			yo: "había driblado",
			tú: "habías driblado",
			Ud: "había driblado",
			nosotros: "habíamos driblado",
			vosotros: "habíais driblado",
			Uds: "habían driblado",
		},
		Conditional: {
			yo: "habría driblado",
			tú: "habrías driblado",
			Ud: "habría driblado",
			nosotros: "habríamos driblado",
			vosotros: "habríais driblado",
			Uds: "habrían driblado",
		},
		Future: {
			yo: "habré driblado",
			tú: "habrás driblado",
			Ud: "habrá driblado",
			nosotros: "habremos driblado",
			vosotros: "habréis driblado",
			Uds: "habrán driblado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya driblado",
			tú: "hayas driblado",
			Ud: "haya driblado",
			nosotros: "hayamos driblado",
			vosotros: "hayáis driblado",
			Uds: "hayan driblado",
		},
		Past: {
			yo: "hubiera driblado",
			tú: "hubieras driblado",
			Ud: "hubiera driblado",
			nosotros: "hubiéramos driblado",
			vosotros: "hubierais driblado",
			Uds: "hubieran driblado",
		},
		Future: {
			yo: "hubiere driblado",
			tú: "hubieres driblado",
			Ud: "hubiere driblado",
			nosotros: "hubiéremos driblado",
			vosotros: "hubiereis driblado",
			Uds: "hubieren driblado",
		},
	},
}
