var echar = {
	Indicative: {
		Present: {
			yo: "echo",
			tú: "echas",
			Ud: "echa",
			nosotros: "echamos",
			vosotros: "echáis",
			Uds: "echan",
		},
		Preterite: {
			yo: "eché",
			tú: "echaste",
			Ud: "echó",
			nosotros: "echamos",
			vosotros: "echasteis",
			Uds: "echaron",
		},
		Imperfect: {
			yo: "echaba",
			tú: "echabas",
			Ud: "echaba",
			nosotros: "echábamos",
			vosotros: "echabais",
			Uds: "echaban",
		},
		Conditional: {
			yo: "echaría",
			tú: "echarías",
			Ud: "echaría",
			nosotros: "echaríamos",
			vosotros: "echaríais",
			Uds: "echarían",
		},
		Future: {
			yo: "echaré",
			tú: "echarás",
			Ud: "echará",
			nosotros: "echaremos",
			vosotros: "echaréis",
			Uds: "echarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "eche",
			tú: "eches",
			Ud: "eche",
			nosotros: "echemos",
			vosotros: "echéis",
			Uds: "echen",
		},
		Imperfect: {
			yo: "echara",
			tú: "echaras",
			Ud: "echara",
			nosotros: "echáramos",
			vosotros: "echarais",
			Uds: "echaran",
		},
		Imperfect2: {
			yo: "echase",
			tú: "echases",
			Ud: "echase",
			nosotros: "echásemos",
			vosotros: "echaseis",
			Uds: "echasen",
		},
		Future: {
			yo: "echare",
			tú: "echares",
			Ud: "echare",
			nosotros: "echáremos",
			vosotros: "echareis",
			Uds: "echaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "echa",
			Ud: "eche",
			nosotros: "echemos",
			vosotros: "echad",
			Uds: "echen",
		},
		Negative: {
			tú: "no eches",
			Ud: "no eche",
			nosotros: "no echemos",
			vosotros: "no echéis",
			Uds: "no echen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy echando",
			tú: "estás echando",
			Ud: "está echando",
			nosotros: "estamos echando",
			vosotros: "estáis echando",
			Uds: "están echando",
		},
		Preterite: {
			yo: "estuve echando",
			tú: "estuviste echando",
			Ud: "estuvo echando",
			nosotros: "estuvimos echando",
			vosotros: "estuvisteis echando",
			Uds: "estuvieron echando",
		},
		Imperfect: {
			Uds: "estaban echando",
			yo: "estaba echando",
			tú: "estabas echando",
			Ud: "estaba echando",
			nosotros: "estábamos echando",
			vosotros: "estabais echando",
		},
		Conditional: {
			yo: "estaría echando",
			tú: "estarías echando",
			Ud: "estaría echando",
			nosotros: "estaríamos echando",
			vosotros: "estaríais echando",
			Uds: "estarían echando",
		},
		Future: {
			yo: "estaré echando",
			tú: "estarás echando",
			Ud: "estará echando",
			nosotros: "estaremos echando",
			vosotros: "estaréis echando",
			Uds: "estarán echando",
		},
	},
	Perfect: {
		Present: {
			yo: "he echado",
			tú: "has echado",
			Ud: "ha echado",
			nosotros: "hemos echado",
			vosotros: "habéis echado",
			Uds: "han echado",
		},
		Preterite: {
			yo: "hube echado",
			tú: "hubiste echado",
			Ud: "hubo echado",
			nosotros: "hubimos echado",
			vosotros: "hubisteis echado",
			Uds: "hubieron echado",
		},
		Past: {
			yo: "había echado",
			tú: "habías echado",
			Ud: "había echado",
			nosotros: "habíamos echado",
			vosotros: "habíais echado",
			Uds: "habían echado",
		},
		Conditional: {
			yo: "habría echado",
			tú: "habrías echado",
			Ud: "habría echado",
			nosotros: "habríamos echado",
			vosotros: "habríais echado",
			Uds: "habrían echado",
		},
		Future: {
			yo: "habré echado",
			tú: "habrás echado",
			Ud: "habrá echado",
			nosotros: "habremos echado",
			vosotros: "habréis echado",
			Uds: "habrán echado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya echado",
			tú: "hayas echado",
			Ud: "haya echado",
			nosotros: "hayamos echado",
			vosotros: "hayáis echado",
			Uds: "hayan echado",
		},
		Past: {
			yo: "hubiera echado",
			tú: "hubieras echado",
			Ud: "hubiera echado",
			nosotros: "hubiéramos echado",
			vosotros: "hubierais echado",
			Uds: "hubieran echado",
		},
		Future: {
			yo: "hubiere echado",
			tú: "hubieres echado",
			Ud: "hubiere echado",
			nosotros: "hubiéremos echado",
			vosotros: "hubiereis echado",
			Uds: "hubieren echado",
		},
	},
}
