var eclipsar = {
	Indicative: {
		Present: {
			yo: "eclipso",
			tú: "eclipsas",
			Ud: "eclipsa",
			nosotros: "eclipsamos",
			vosotros: "eclipsáis",
			Uds: "eclipsan",
		},
		Preterite: {
			yo: "eclipsé",
			tú: "eclipsaste",
			Ud: "eclipsó",
			nosotros: "eclipsamos",
			vosotros: "eclipsasteis",
			Uds: "eclipsaron",
		},
		Imperfect: {
			yo: "eclipsaba",
			tú: "eclipsabas",
			Ud: "eclipsaba",
			nosotros: "eclipsábamos",
			vosotros: "eclipsabais",
			Uds: "eclipsaban",
		},
		Conditional: {
			yo: "eclipsaría",
			tú: "eclipsarías",
			Ud: "eclipsaría",
			nosotros: "eclipsaríamos",
			vosotros: "eclipsaríais",
			Uds: "eclipsarían",
		},
		Future: {
			yo: "eclipsaré",
			tú: "eclipsarás",
			Ud: "eclipsará",
			nosotros: "eclipsaremos",
			vosotros: "eclipsaréis",
			Uds: "eclipsarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "eclipse",
			tú: "eclipses",
			Ud: "eclipse",
			nosotros: "eclipsemos",
			vosotros: "eclipséis",
			Uds: "eclipsen",
		},
		Imperfect: {
			yo: "eclipsara",
			tú: "eclipsaras",
			Ud: "eclipsara",
			nosotros: "eclipsáramos",
			vosotros: "eclipsarais",
			Uds: "eclipsaran",
		},
		Imperfect2: {
			yo: "eclipsase",
			tú: "eclipsases",
			Ud: "eclipsase",
			nosotros: "eclipsásemos",
			vosotros: "eclipsaseis",
			Uds: "eclipsasen",
		},
		Future: {
			yo: "eclipsare",
			tú: "eclipsares",
			Ud: "eclipsare",
			nosotros: "eclipsáremos",
			vosotros: "eclipsareis",
			Uds: "eclipsaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "eclipsa",
			Ud: "eclipse",
			nosotros: "eclipsemos",
			vosotros: "eclipsad",
			Uds: "eclipsen",
		},
		Negative: {
			tú: "no eclipses",
			Ud: "no eclipse",
			nosotros: "no eclipsemos",
			vosotros: "no eclipséis",
			Uds: "no eclipsen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy eclipsando",
			tú: "estás eclipsando",
			Ud: "está eclipsando",
			nosotros: "estamos eclipsando",
			vosotros: "estáis eclipsando",
			Uds: "están eclipsando",
		},
		Preterite: {
			yo: "estuve eclipsando",
			tú: "estuviste eclipsando",
			Ud: "estuvo eclipsando",
			nosotros: "estuvimos eclipsando",
			vosotros: "estuvisteis eclipsando",
			Uds: "estuvieron eclipsando",
		},
		Imperfect: {
			Uds: "estaban eclipsando",
			yo: "estaba eclipsando",
			tú: "estabas eclipsando",
			Ud: "estaba eclipsando",
			nosotros: "estábamos eclipsando",
			vosotros: "estabais eclipsando",
		},
		Conditional: {
			yo: "estaría eclipsando",
			tú: "estarías eclipsando",
			Ud: "estaría eclipsando",
			nosotros: "estaríamos eclipsando",
			vosotros: "estaríais eclipsando",
			Uds: "estarían eclipsando",
		},
		Future: {
			yo: "estaré eclipsando",
			tú: "estarás eclipsando",
			Ud: "estará eclipsando",
			nosotros: "estaremos eclipsando",
			vosotros: "estaréis eclipsando",
			Uds: "estarán eclipsando",
		},
	},
	Perfect: {
		Present: {
			yo: "he eclipsado",
			tú: "has eclipsado",
			Ud: "ha eclipsado",
			nosotros: "hemos eclipsado",
			vosotros: "habéis eclipsado",
			Uds: "han eclipsado",
		},
		Preterite: {
			yo: "hube eclipsado",
			tú: "hubiste eclipsado",
			Ud: "hubo eclipsado",
			nosotros: "hubimos eclipsado",
			vosotros: "hubisteis eclipsado",
			Uds: "hubieron eclipsado",
		},
		Past: {
			yo: "había eclipsado",
			tú: "habías eclipsado",
			Ud: "había eclipsado",
			nosotros: "habíamos eclipsado",
			vosotros: "habíais eclipsado",
			Uds: "habían eclipsado",
		},
		Conditional: {
			yo: "habría eclipsado",
			tú: "habrías eclipsado",
			Ud: "habría eclipsado",
			nosotros: "habríamos eclipsado",
			vosotros: "habríais eclipsado",
			Uds: "habrían eclipsado",
		},
		Future: {
			yo: "habré eclipsado",
			tú: "habrás eclipsado",
			Ud: "habrá eclipsado",
			nosotros: "habremos eclipsado",
			vosotros: "habréis eclipsado",
			Uds: "habrán eclipsado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya eclipsado",
			tú: "hayas eclipsado",
			Ud: "haya eclipsado",
			nosotros: "hayamos eclipsado",
			vosotros: "hayáis eclipsado",
			Uds: "hayan eclipsado",
		},
		Past: {
			yo: "hubiera eclipsado",
			tú: "hubieras eclipsado",
			Ud: "hubiera eclipsado",
			nosotros: "hubiéramos eclipsado",
			vosotros: "hubierais eclipsado",
			Uds: "hubieran eclipsado",
		},
		Future: {
			yo: "hubiere eclipsado",
			tú: "hubieres eclipsado",
			Ud: "hubiere eclipsado",
			nosotros: "hubiéremos eclipsado",
			vosotros: "hubiereis eclipsado",
			Uds: "hubieren eclipsado",
		},
	},
}
