var edificar = {
	Indicative: {
		Present: {
			yo: "edifico",
			tú: "edificas",
			Ud: "edifica",
			nosotros: "edificamos",
			vosotros: "edificáis",
			Uds: "edifican",
		},
		Preterite: {
			yo: "edifiqué",
			tú: "edificaste",
			Ud: "edificó",
			nosotros: "edificamos",
			vosotros: "edificasteis",
			Uds: "edificaron",
		},
		Imperfect: {
			yo: "edificaba",
			tú: "edificabas",
			Ud: "edificaba",
			nosotros: "edificábamos",
			vosotros: "edificabais",
			Uds: "edificaban",
		},
		Conditional: {
			yo: "edificaría",
			tú: "edificarías",
			Ud: "edificaría",
			nosotros: "edificaríamos",
			vosotros: "edificaríais",
			Uds: "edificarían",
		},
		Future: {
			yo: "edificaré",
			tú: "edificarás",
			Ud: "edificará",
			nosotros: "edificaremos",
			vosotros: "edificaréis",
			Uds: "edificarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "edifique",
			tú: "edifiques",
			Ud: "edifique",
			nosotros: "edifiquemos",
			vosotros: "edifiquéis",
			Uds: "edifiquen",
		},
		Imperfect: {
			yo: "edificara",
			tú: "edificaras",
			Ud: "edificara",
			nosotros: "edificáramos",
			vosotros: "edificarais",
			Uds: "edificaran",
		},
		Imperfect2: {
			yo: "edificase",
			tú: "edificases",
			Ud: "edificase",
			nosotros: "edificásemos",
			vosotros: "edificaseis",
			Uds: "edificasen",
		},
		Future: {
			yo: "edificare",
			tú: "edificares",
			Ud: "edificare",
			nosotros: "edificáremos",
			vosotros: "edificareis",
			Uds: "edificaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "edifica",
			Ud: "edifique",
			nosotros: "edifiquemos",
			vosotros: "edificad",
			Uds: "edifiquen",
		},
		Negative: {
			tú: "no edifiques",
			Ud: "no edifique",
			nosotros: "no edifiquemos",
			vosotros: "no edifiquéis",
			Uds: "no edifiquen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy edificando",
			tú: "estás edificando",
			Ud: "está edificando",
			nosotros: "estamos edificando",
			vosotros: "estáis edificando",
			Uds: "están edificando",
		},
		Preterite: {
			yo: "estuve edificando",
			tú: "estuviste edificando",
			Ud: "estuvo edificando",
			nosotros: "estuvimos edificando",
			vosotros: "estuvisteis edificando",
			Uds: "estuvieron edificando",
		},
		Imperfect: {
			Uds: "estaban edificando",
			yo: "estaba edificando",
			tú: "estabas edificando",
			Ud: "estaba edificando",
			nosotros: "estábamos edificando",
			vosotros: "estabais edificando",
		},
		Conditional: {
			yo: "estaría edificando",
			tú: "estarías edificando",
			Ud: "estaría edificando",
			nosotros: "estaríamos edificando",
			vosotros: "estaríais edificando",
			Uds: "estarían edificando",
		},
		Future: {
			yo: "estaré edificando",
			tú: "estarás edificando",
			Ud: "estará edificando",
			nosotros: "estaremos edificando",
			vosotros: "estaréis edificando",
			Uds: "estarán edificando",
		},
	},
	Perfect: {
		Present: {
			yo: "he edificado",
			tú: "has edificado",
			Ud: "ha edificado",
			nosotros: "hemos edificado",
			vosotros: "habéis edificado",
			Uds: "han edificado",
		},
		Preterite: {
			yo: "hube edificado",
			tú: "hubiste edificado",
			Ud: "hubo edificado",
			nosotros: "hubimos edificado",
			vosotros: "hubisteis edificado",
			Uds: "hubieron edificado",
		},
		Past: {
			yo: "había edificado",
			tú: "habías edificado",
			Ud: "había edificado",
			nosotros: "habíamos edificado",
			vosotros: "habíais edificado",
			Uds: "habían edificado",
		},
		Conditional: {
			yo: "habría edificado",
			tú: "habrías edificado",
			Ud: "habría edificado",
			nosotros: "habríamos edificado",
			vosotros: "habríais edificado",
			Uds: "habrían edificado",
		},
		Future: {
			yo: "habré edificado",
			tú: "habrás edificado",
			Ud: "habrá edificado",
			nosotros: "habremos edificado",
			vosotros: "habréis edificado",
			Uds: "habrán edificado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya edificado",
			tú: "hayas edificado",
			Ud: "haya edificado",
			nosotros: "hayamos edificado",
			vosotros: "hayáis edificado",
			Uds: "hayan edificado",
		},
		Past: {
			yo: "hubiera edificado",
			tú: "hubieras edificado",
			Ud: "hubiera edificado",
			nosotros: "hubiéramos edificado",
			vosotros: "hubierais edificado",
			Uds: "hubieran edificado",
		},
		Future: {
			yo: "hubiere edificado",
			tú: "hubieres edificado",
			Ud: "hubiere edificado",
			nosotros: "hubiéremos edificado",
			vosotros: "hubiereis edificado",
			Uds: "hubieren edificado",
		},
	},
}
