var elogiar = {
	Indicative: {
		Present: {
			yo: "elogio",
			tú: "elogias",
			Ud: "elogia",
			nosotros: "elogiamos",
			vosotros: "elogiáis",
			Uds: "elogian",
		},
		Preterite: {
			yo: "elogié",
			tú: "elogiaste",
			Ud: "elogió",
			nosotros: "elogiamos",
			vosotros: "elogiasteis",
			Uds: "elogiaron",
		},
		Imperfect: {
			yo: "elogiaba",
			tú: "elogiabas",
			Ud: "elogiaba",
			nosotros: "elogiábamos",
			vosotros: "elogiabais",
			Uds: "elogiaban",
		},
		Conditional: {
			yo: "elogiaría",
			tú: "elogiarías",
			Ud: "elogiaría",
			nosotros: "elogiaríamos",
			vosotros: "elogiaríais",
			Uds: "elogiarían",
		},
		Future: {
			yo: "elogiaré",
			tú: "elogiarás",
			Ud: "elogiará",
			nosotros: "elogiaremos",
			vosotros: "elogiaréis",
			Uds: "elogiarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "elogie",
			tú: "elogies",
			Ud: "elogie",
			nosotros: "elogiemos",
			vosotros: "elogiéis",
			Uds: "elogien",
		},
		Imperfect: {
			yo: "elogiara",
			tú: "elogiaras",
			Ud: "elogiara",
			nosotros: "elogiáramos",
			vosotros: "elogiarais",
			Uds: "elogiaran",
		},
		Imperfect2: {
			yo: "elogiase",
			tú: "elogiases",
			Ud: "elogiase",
			nosotros: "elogiásemos",
			vosotros: "elogiaseis",
			Uds: "elogiasen",
		},
		Future: {
			yo: "elogiare",
			tú: "elogiares",
			Ud: "elogiare",
			nosotros: "elogiáremos",
			vosotros: "elogiareis",
			Uds: "elogiaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "elogia",
			Ud: "elogie",
			nosotros: "elogiemos",
			vosotros: "elogiad",
			Uds: "elogien",
		},
		Negative: {
			tú: "no elogies",
			Ud: "no elogie",
			nosotros: "no elogiemos",
			vosotros: "no elogiéis",
			Uds: "no elogien",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy elogiando",
			tú: "estás elogiando",
			Ud: "está elogiando",
			nosotros: "estamos elogiando",
			vosotros: "estáis elogiando",
			Uds: "están elogiando",
		},
		Preterite: {
			yo: "estuve elogiando",
			tú: "estuviste elogiando",
			Ud: "estuvo elogiando",
			nosotros: "estuvimos elogiando",
			vosotros: "estuvisteis elogiando",
			Uds: "estuvieron elogiando",
		},
		Imperfect: {
			Uds: "estaban elogiando",
			yo: "estaba elogiando",
			tú: "estabas elogiando",
			Ud: "estaba elogiando",
			nosotros: "estábamos elogiando",
			vosotros: "estabais elogiando",
		},
		Conditional: {
			yo: "estaría elogiando",
			tú: "estarías elogiando",
			Ud: "estaría elogiando",
			nosotros: "estaríamos elogiando",
			vosotros: "estaríais elogiando",
			Uds: "estarían elogiando",
		},
		Future: {
			yo: "estaré elogiando",
			tú: "estarás elogiando",
			Ud: "estará elogiando",
			nosotros: "estaremos elogiando",
			vosotros: "estaréis elogiando",
			Uds: "estarán elogiando",
		},
	},
	Perfect: {
		Present: {
			yo: "he elogiado",
			tú: "has elogiado",
			Ud: "ha elogiado",
			nosotros: "hemos elogiado",
			vosotros: "habéis elogiado",
			Uds: "han elogiado",
		},
		Preterite: {
			yo: "hube elogiado",
			tú: "hubiste elogiado",
			Ud: "hubo elogiado",
			nosotros: "hubimos elogiado",
			vosotros: "hubisteis elogiado",
			Uds: "hubieron elogiado",
		},
		Past: {
			yo: "había elogiado",
			tú: "habías elogiado",
			Ud: "había elogiado",
			nosotros: "habíamos elogiado",
			vosotros: "habíais elogiado",
			Uds: "habían elogiado",
		},
		Conditional: {
			yo: "habría elogiado",
			tú: "habrías elogiado",
			Ud: "habría elogiado",
			nosotros: "habríamos elogiado",
			vosotros: "habríais elogiado",
			Uds: "habrían elogiado",
		},
		Future: {
			yo: "habré elogiado",
			tú: "habrás elogiado",
			Ud: "habrá elogiado",
			nosotros: "habremos elogiado",
			vosotros: "habréis elogiado",
			Uds: "habrán elogiado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya elogiado",
			tú: "hayas elogiado",
			Ud: "haya elogiado",
			nosotros: "hayamos elogiado",
			vosotros: "hayáis elogiado",
			Uds: "hayan elogiado",
		},
		Past: {
			yo: "hubiera elogiado",
			tú: "hubieras elogiado",
			Ud: "hubiera elogiado",
			nosotros: "hubiéramos elogiado",
			vosotros: "hubierais elogiado",
			Uds: "hubieran elogiado",
		},
		Future: {
			yo: "hubiere elogiado",
			tú: "hubieres elogiado",
			Ud: "hubiere elogiado",
			nosotros: "hubiéremos elogiado",
			vosotros: "hubiereis elogiado",
			Uds: "hubieren elogiado",
		},
	},
}
