var embarcar = {
	Indicative: {
		Present: {
			yo: "embarco",
			tú: "embarcas",
			Ud: "embarca",
			nosotros: "embarcamos",
			vosotros: "embarcáis",
			Uds: "embarcan",
		},
		Preterite: {
			yo: "embarqué",
			tú: "embarcaste",
			Ud: "embarcó",
			nosotros: "embarcamos",
			vosotros: "embarcasteis",
			Uds: "embarcaron",
		},
		Imperfect: {
			yo: "embarcaba",
			tú: "embarcabas",
			Ud: "embarcaba",
			nosotros: "embarcábamos",
			vosotros: "embarcabais",
			Uds: "embarcaban",
		},
		Conditional: {
			yo: "embarcaría",
			tú: "embarcarías",
			Ud: "embarcaría",
			nosotros: "embarcaríamos",
			vosotros: "embarcaríais",
			Uds: "embarcarían",
		},
		Future: {
			yo: "embarcaré",
			tú: "embarcarás",
			Ud: "embarcará",
			nosotros: "embarcaremos",
			vosotros: "embarcaréis",
			Uds: "embarcarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "embarque",
			tú: "embarques",
			Ud: "embarque",
			nosotros: "embarquemos",
			vosotros: "embarquéis",
			Uds: "embarquen",
		},
		Imperfect: {
			yo: "embarcara",
			tú: "embarcaras",
			Ud: "embarcara",
			nosotros: "embarcáramos",
			vosotros: "embarcarais",
			Uds: "embarcaran",
		},
		Imperfect2: {
			yo: "embarcase",
			tú: "embarcases",
			Ud: "embarcase",
			nosotros: "embarcásemos",
			vosotros: "embarcaseis",
			Uds: "embarcasen",
		},
		Future: {
			yo: "embarcare",
			tú: "embarcares",
			Ud: "embarcare",
			nosotros: "embarcáremos",
			vosotros: "embarcareis",
			Uds: "embarcaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "embarca",
			Ud: "embarque",
			nosotros: "embarquemos",
			vosotros: "embarcad",
			Uds: "embarquen",
		},
		Negative: {
			tú: "no embarques",
			Ud: "no embarque",
			nosotros: "no embarquemos",
			vosotros: "no embarquéis",
			Uds: "no embarquen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy embarcando",
			tú: "estás embarcando",
			Ud: "está embarcando",
			nosotros: "estamos embarcando",
			vosotros: "estáis embarcando",
			Uds: "están embarcando",
		},
		Preterite: {
			yo: "estuve embarcando",
			tú: "estuviste embarcando",
			Ud: "estuvo embarcando",
			nosotros: "estuvimos embarcando",
			vosotros: "estuvisteis embarcando",
			Uds: "estuvieron embarcando",
		},
		Imperfect: {
			Uds: "estaban embarcando",
			yo: "estaba embarcando",
			tú: "estabas embarcando",
			Ud: "estaba embarcando",
			nosotros: "estábamos embarcando",
			vosotros: "estabais embarcando",
		},
		Conditional: {
			yo: "estaría embarcando",
			tú: "estarías embarcando",
			Ud: "estaría embarcando",
			nosotros: "estaríamos embarcando",
			vosotros: "estaríais embarcando",
			Uds: "estarían embarcando",
		},
		Future: {
			yo: "estaré embarcando",
			tú: "estarás embarcando",
			Ud: "estará embarcando",
			nosotros: "estaremos embarcando",
			vosotros: "estaréis embarcando",
			Uds: "estarán embarcando",
		},
	},
	Perfect: {
		Present: {
			yo: "he embarcado",
			tú: "has embarcado",
			Ud: "ha embarcado",
			nosotros: "hemos embarcado",
			vosotros: "habéis embarcado",
			Uds: "han embarcado",
		},
		Preterite: {
			yo: "hube embarcado",
			tú: "hubiste embarcado",
			Ud: "hubo embarcado",
			nosotros: "hubimos embarcado",
			vosotros: "hubisteis embarcado",
			Uds: "hubieron embarcado",
		},
		Past: {
			yo: "había embarcado",
			tú: "habías embarcado",
			Ud: "había embarcado",
			nosotros: "habíamos embarcado",
			vosotros: "habíais embarcado",
			Uds: "habían embarcado",
		},
		Conditional: {
			yo: "habría embarcado",
			tú: "habrías embarcado",
			Ud: "habría embarcado",
			nosotros: "habríamos embarcado",
			vosotros: "habríais embarcado",
			Uds: "habrían embarcado",
		},
		Future: {
			yo: "habré embarcado",
			tú: "habrás embarcado",
			Ud: "habrá embarcado",
			nosotros: "habremos embarcado",
			vosotros: "habréis embarcado",
			Uds: "habrán embarcado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya embarcado",
			tú: "hayas embarcado",
			Ud: "haya embarcado",
			nosotros: "hayamos embarcado",
			vosotros: "hayáis embarcado",
			Uds: "hayan embarcado",
		},
		Past: {
			yo: "hubiera embarcado",
			tú: "hubieras embarcado",
			Ud: "hubiera embarcado",
			nosotros: "hubiéramos embarcado",
			vosotros: "hubierais embarcado",
			Uds: "hubieran embarcado",
		},
		Future: {
			yo: "hubiere embarcado",
			tú: "hubieres embarcado",
			Ud: "hubiere embarcado",
			nosotros: "hubiéremos embarcado",
			vosotros: "hubiereis embarcado",
			Uds: "hubieren embarcado",
		},
	},
}
