var embalsar = {
	Indicative: {
		Present: {
			yo: "embalso",
			tú: "embalsas",
			Ud: "embalsa",
			nosotros: "embalsamos",
			vosotros: "embalsáis",
			Uds: "embalsan",
		},
		Preterite: {
			yo: "embalsé",
			tú: "embalsaste",
			Ud: "embalsó",
			nosotros: "embalsamos",
			vosotros: "embalsasteis",
			Uds: "embalsaron",
		},
		Imperfect: {
			yo: "embalsaba",
			tú: "embalsabas",
			Ud: "embalsaba",
			nosotros: "embalsábamos",
			vosotros: "embalsabais",
			Uds: "embalsaban",
		},
		Conditional: {
			yo: "embalsaría",
			tú: "embalsarías",
			Ud: "embalsaría",
			nosotros: "embalsaríamos",
			vosotros: "embalsaríais",
			Uds: "embalsarían",
		},
		Future: {
			yo: "embalsaré",
			tú: "embalsarás",
			Ud: "embalsará",
			nosotros: "embalsaremos",
			vosotros: "embalsaréis",
			Uds: "embalsarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "embalse",
			tú: "embalses",
			Ud: "embalse",
			nosotros: "embalsemos",
			vosotros: "embalséis",
			Uds: "embalsen",
		},
		Imperfect: {
			yo: "embalsara",
			tú: "embalsaras",
			Ud: "embalsara",
			nosotros: "embalsáramos",
			vosotros: "embalsarais",
			Uds: "embalsaran",
		},
		Imperfect2: {
			yo: "embalsase",
			tú: "embalsases",
			Ud: "embalsase",
			nosotros: "embalsásemos",
			vosotros: "embalsaseis",
			Uds: "embalsasen",
		},
		Future: {
			yo: "embalsare",
			tú: "embalsares",
			Ud: "embalsare",
			nosotros: "embalsáremos",
			vosotros: "embalsareis",
			Uds: "embalsaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "embalsa",
			Ud: "embalse",
			nosotros: "embalsemos",
			vosotros: "embalsad",
			Uds: "embalsen",
		},
		Negative: {
			tú: "no embalses",
			Ud: "no embalse",
			nosotros: "no embalsemos",
			vosotros: "no embalséis",
			Uds: "no embalsen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy embalsando",
			tú: "estás embalsando",
			Ud: "está embalsando",
			nosotros: "estamos embalsando",
			vosotros: "estáis embalsando",
			Uds: "están embalsando",
		},
		Preterite: {
			yo: "estuve embalsando",
			tú: "estuviste embalsando",
			Ud: "estuvo embalsando",
			nosotros: "estuvimos embalsando",
			vosotros: "estuvisteis embalsando",
			Uds: "estuvieron embalsando",
		},
		Imperfect: {
			Uds: "estaban embalsando",
			yo: "estaba embalsando",
			tú: "estabas embalsando",
			Ud: "estaba embalsando",
			nosotros: "estábamos embalsando",
			vosotros: "estabais embalsando",
		},
		Conditional: {
			yo: "estaría embalsando",
			tú: "estarías embalsando",
			Ud: "estaría embalsando",
			nosotros: "estaríamos embalsando",
			vosotros: "estaríais embalsando",
			Uds: "estarían embalsando",
		},
		Future: {
			yo: "estaré embalsando",
			tú: "estarás embalsando",
			Ud: "estará embalsando",
			nosotros: "estaremos embalsando",
			vosotros: "estaréis embalsando",
			Uds: "estarán embalsando",
		},
	},
	Perfect: {
		Present: {
			yo: "he embalsado",
			tú: "has embalsado",
			Ud: "ha embalsado",
			nosotros: "hemos embalsado",
			vosotros: "habéis embalsado",
			Uds: "han embalsado",
		},
		Preterite: {
			yo: "hube embalsado",
			tú: "hubiste embalsado",
			Ud: "hubo embalsado",
			nosotros: "hubimos embalsado",
			vosotros: "hubisteis embalsado",
			Uds: "hubieron embalsado",
		},
		Past: {
			yo: "había embalsado",
			tú: "habías embalsado",
			Ud: "había embalsado",
			nosotros: "habíamos embalsado",
			vosotros: "habíais embalsado",
			Uds: "habían embalsado",
		},
		Conditional: {
			yo: "habría embalsado",
			tú: "habrías embalsado",
			Ud: "habría embalsado",
			nosotros: "habríamos embalsado",
			vosotros: "habríais embalsado",
			Uds: "habrían embalsado",
		},
		Future: {
			yo: "habré embalsado",
			tú: "habrás embalsado",
			Ud: "habrá embalsado",
			nosotros: "habremos embalsado",
			vosotros: "habréis embalsado",
			Uds: "habrán embalsado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya embalsado",
			tú: "hayas embalsado",
			Ud: "haya embalsado",
			nosotros: "hayamos embalsado",
			vosotros: "hayáis embalsado",
			Uds: "hayan embalsado",
		},
		Past: {
			yo: "hubiera embalsado",
			tú: "hubieras embalsado",
			Ud: "hubiera embalsado",
			nosotros: "hubiéramos embalsado",
			vosotros: "hubierais embalsado",
			Uds: "hubieran embalsado",
		},
		Future: {
			yo: "hubiere embalsado",
			tú: "hubieres embalsado",
			Ud: "hubiere embalsado",
			nosotros: "hubiéremos embalsado",
			vosotros: "hubiereis embalsado",
			Uds: "hubieren embalsado",
		},
	},
}
