var embotellar = {
	Indicative: {
		Present: {
			yo: "embotello",
			tú: "embotellas",
			Ud: "embotella",
			nosotros: "embotellamos",
			vosotros: "embotelláis",
			Uds: "embotellan",
		},
		Preterite: {
			yo: "embotellé",
			tú: "embotellaste",
			Ud: "embotelló",
			nosotros: "embotellamos",
			vosotros: "embotellasteis",
			Uds: "embotellaron",
		},
		Imperfect: {
			yo: "embotellaba",
			tú: "embotellabas",
			Ud: "embotellaba",
			nosotros: "embotellábamos",
			vosotros: "embotellabais",
			Uds: "embotellaban",
		},
		Conditional: {
			yo: "embotellaría",
			tú: "embotellarías",
			Ud: "embotellaría",
			nosotros: "embotellaríamos",
			vosotros: "embotellaríais",
			Uds: "embotellarían",
		},
		Future: {
			yo: "embotellaré",
			tú: "embotellarás",
			Ud: "embotellará",
			nosotros: "embotellaremos",
			vosotros: "embotellaréis",
			Uds: "embotellarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "embotelle",
			tú: "embotelles",
			Ud: "embotelle",
			nosotros: "embotellemos",
			vosotros: "embotelléis",
			Uds: "embotellen",
		},
		Imperfect: {
			yo: "embotellara",
			tú: "embotellaras",
			Ud: "embotellara",
			nosotros: "embotelláramos",
			vosotros: "embotellarais",
			Uds: "embotellaran",
		},
		Imperfect2: {
			yo: "embotellase",
			tú: "embotellases",
			Ud: "embotellase",
			nosotros: "embotellásemos",
			vosotros: "embotellaseis",
			Uds: "embotellasen",
		},
		Future: {
			yo: "embotellare",
			tú: "embotellares",
			Ud: "embotellare",
			nosotros: "embotelláremos",
			vosotros: "embotellareis",
			Uds: "embotellaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "embotella",
			Ud: "embotelle",
			nosotros: "embotellemos",
			vosotros: "embotellad",
			Uds: "embotellen",
		},
		Negative: {
			tú: "no embotelles",
			Ud: "no embotelle",
			nosotros: "no embotellemos",
			vosotros: "no embotelléis",
			Uds: "no embotellen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy embotellando",
			tú: "estás embotellando",
			Ud: "está embotellando",
			nosotros: "estamos embotellando",
			vosotros: "estáis embotellando",
			Uds: "están embotellando",
		},
		Preterite: {
			yo: "estuve embotellando",
			tú: "estuviste embotellando",
			Ud: "estuvo embotellando",
			nosotros: "estuvimos embotellando",
			vosotros: "estuvisteis embotellando",
			Uds: "estuvieron embotellando",
		},
		Imperfect: {
			Uds: "estaban embotellando",
			yo: "estaba embotellando",
			tú: "estabas embotellando",
			Ud: "estaba embotellando",
			nosotros: "estábamos embotellando",
			vosotros: "estabais embotellando",
		},
		Conditional: {
			yo: "estaría embotellando",
			tú: "estarías embotellando",
			Ud: "estaría embotellando",
			nosotros: "estaríamos embotellando",
			vosotros: "estaríais embotellando",
			Uds: "estarían embotellando",
		},
		Future: {
			yo: "estaré embotellando",
			tú: "estarás embotellando",
			Ud: "estará embotellando",
			nosotros: "estaremos embotellando",
			vosotros: "estaréis embotellando",
			Uds: "estarán embotellando",
		},
	},
	Perfect: {
		Present: {
			yo: "he embotellado",
			tú: "has embotellado",
			Ud: "ha embotellado",
			nosotros: "hemos embotellado",
			vosotros: "habéis embotellado",
			Uds: "han embotellado",
		},
		Preterite: {
			yo: "hube embotellado",
			tú: "hubiste embotellado",
			Ud: "hubo embotellado",
			nosotros: "hubimos embotellado",
			vosotros: "hubisteis embotellado",
			Uds: "hubieron embotellado",
		},
		Past: {
			yo: "había embotellado",
			tú: "habías embotellado",
			Ud: "había embotellado",
			nosotros: "habíamos embotellado",
			vosotros: "habíais embotellado",
			Uds: "habían embotellado",
		},
		Conditional: {
			yo: "habría embotellado",
			tú: "habrías embotellado",
			Ud: "habría embotellado",
			nosotros: "habríamos embotellado",
			vosotros: "habríais embotellado",
			Uds: "habrían embotellado",
		},
		Future: {
			yo: "habré embotellado",
			tú: "habrás embotellado",
			Ud: "habrá embotellado",
			nosotros: "habremos embotellado",
			vosotros: "habréis embotellado",
			Uds: "habrán embotellado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya embotellado",
			tú: "hayas embotellado",
			Ud: "haya embotellado",
			nosotros: "hayamos embotellado",
			vosotros: "hayáis embotellado",
			Uds: "hayan embotellado",
		},
		Past: {
			yo: "hubiera embotellado",
			tú: "hubieras embotellado",
			Ud: "hubiera embotellado",
			nosotros: "hubiéramos embotellado",
			vosotros: "hubierais embotellado",
			Uds: "hubieran embotellado",
		},
		Future: {
			yo: "hubiere embotellado",
			tú: "hubieres embotellado",
			Ud: "hubiere embotellado",
			nosotros: "hubiéremos embotellado",
			vosotros: "hubiereis embotellado",
			Uds: "hubieren embotellado",
		},
	},
}
