var embrujar = {
	Indicative: {
		Present: {
			yo: "embrujo",
			tú: "embrujas",
			Ud: "embruja",
			nosotros: "embrujamos",
			vosotros: "embrujáis",
			Uds: "embrujan",
		},
		Preterite: {
			yo: "embrujé",
			tú: "embrujaste",
			Ud: "embrujó",
			nosotros: "embrujamos",
			vosotros: "embrujasteis",
			Uds: "embrujaron",
		},
		Imperfect: {
			yo: "embrujaba",
			tú: "embrujabas",
			Ud: "embrujaba",
			nosotros: "embrujábamos",
			vosotros: "embrujabais",
			Uds: "embrujaban",
		},
		Conditional: {
			yo: "embrujaría",
			tú: "embrujarías",
			Ud: "embrujaría",
			nosotros: "embrujaríamos",
			vosotros: "embrujaríais",
			Uds: "embrujarían",
		},
		Future: {
			yo: "embrujaré",
			tú: "embrujarás",
			Ud: "embrujará",
			nosotros: "embrujaremos",
			vosotros: "embrujaréis",
			Uds: "embrujarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "embruje",
			tú: "embrujes",
			Ud: "embruje",
			nosotros: "embrujemos",
			vosotros: "embrujéis",
			Uds: "embrujen",
		},
		Imperfect: {
			yo: "embrujara",
			tú: "embrujaras",
			Ud: "embrujara",
			nosotros: "embrujáramos",
			vosotros: "embrujarais",
			Uds: "embrujaran",
		},
		Imperfect2: {
			yo: "embrujase",
			tú: "embrujases",
			Ud: "embrujase",
			nosotros: "embrujásemos",
			vosotros: "embrujaseis",
			Uds: "embrujasen",
		},
		Future: {
			yo: "embrujare",
			tú: "embrujares",
			Ud: "embrujare",
			nosotros: "embrujáremos",
			vosotros: "embrujareis",
			Uds: "embrujaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "embruja",
			Ud: "embruje",
			nosotros: "embrujemos",
			vosotros: "embrujad",
			Uds: "embrujen",
		},
		Negative: {
			tú: "no embrujes",
			Ud: "no embruje",
			nosotros: "no embrujemos",
			vosotros: "no embrujéis",
			Uds: "no embrujen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy embrujando",
			tú: "estás embrujando",
			Ud: "está embrujando",
			nosotros: "estamos embrujando",
			vosotros: "estáis embrujando",
			Uds: "están embrujando",
		},
		Preterite: {
			yo: "estuve embrujando",
			tú: "estuviste embrujando",
			Ud: "estuvo embrujando",
			nosotros: "estuvimos embrujando",
			vosotros: "estuvisteis embrujando",
			Uds: "estuvieron embrujando",
		},
		Imperfect: {
			Uds: "estaban embrujando",
			yo: "estaba embrujando",
			tú: "estabas embrujando",
			Ud: "estaba embrujando",
			nosotros: "estábamos embrujando",
			vosotros: "estabais embrujando",
		},
		Conditional: {
			yo: "estaría embrujando",
			tú: "estarías embrujando",
			Ud: "estaría embrujando",
			nosotros: "estaríamos embrujando",
			vosotros: "estaríais embrujando",
			Uds: "estarían embrujando",
		},
		Future: {
			yo: "estaré embrujando",
			tú: "estarás embrujando",
			Ud: "estará embrujando",
			nosotros: "estaremos embrujando",
			vosotros: "estaréis embrujando",
			Uds: "estarán embrujando",
		},
	},
	Perfect: {
		Present: {
			yo: "he embrujado",
			tú: "has embrujado",
			Ud: "ha embrujado",
			nosotros: "hemos embrujado",
			vosotros: "habéis embrujado",
			Uds: "han embrujado",
		},
		Preterite: {
			yo: "hube embrujado",
			tú: "hubiste embrujado",
			Ud: "hubo embrujado",
			nosotros: "hubimos embrujado",
			vosotros: "hubisteis embrujado",
			Uds: "hubieron embrujado",
		},
		Past: {
			yo: "había embrujado",
			tú: "habías embrujado",
			Ud: "había embrujado",
			nosotros: "habíamos embrujado",
			vosotros: "habíais embrujado",
			Uds: "habían embrujado",
		},
		Conditional: {
			yo: "habría embrujado",
			tú: "habrías embrujado",
			Ud: "habría embrujado",
			nosotros: "habríamos embrujado",
			vosotros: "habríais embrujado",
			Uds: "habrían embrujado",
		},
		Future: {
			yo: "habré embrujado",
			tú: "habrás embrujado",
			Ud: "habrá embrujado",
			nosotros: "habremos embrujado",
			vosotros: "habréis embrujado",
			Uds: "habrán embrujado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya embrujado",
			tú: "hayas embrujado",
			Ud: "haya embrujado",
			nosotros: "hayamos embrujado",
			vosotros: "hayáis embrujado",
			Uds: "hayan embrujado",
		},
		Past: {
			yo: "hubiera embrujado",
			tú: "hubieras embrujado",
			Ud: "hubiera embrujado",
			nosotros: "hubiéramos embrujado",
			vosotros: "hubierais embrujado",
			Uds: "hubieran embrujado",
		},
		Future: {
			yo: "hubiere embrujado",
			tú: "hubieres embrujado",
			Ud: "hubiere embrujado",
			nosotros: "hubiéremos embrujado",
			vosotros: "hubiereis embrujado",
			Uds: "hubieren embrujado",
		},
	},
}
