var emocionar = {
	Indicative: {
		Present: {
			yo: "emociono",
			tú: "emocionas",
			Ud: "emociona",
			nosotros: "emocionamos",
			vosotros: "emocionáis",
			Uds: "emocionan",
		},
		Preterite: {
			yo: "emocioné",
			tú: "emocionaste",
			Ud: "emocionó",
			nosotros: "emocionamos",
			vosotros: "emocionasteis",
			Uds: "emocionaron",
		},
		Imperfect: {
			yo: "emocionaba",
			tú: "emocionabas",
			Ud: "emocionaba",
			nosotros: "emocionábamos",
			vosotros: "emocionabais",
			Uds: "emocionaban",
		},
		Conditional: {
			yo: "emocionaría",
			tú: "emocionarías",
			Ud: "emocionaría",
			nosotros: "emocionaríamos",
			vosotros: "emocionaríais",
			Uds: "emocionarían",
		},
		Future: {
			yo: "emocionaré",
			tú: "emocionarás",
			Ud: "emocionará",
			nosotros: "emocionaremos",
			vosotros: "emocionaréis",
			Uds: "emocionarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "emocione",
			tú: "emociones",
			Ud: "emocione",
			nosotros: "emocionemos",
			vosotros: "emocionéis",
			Uds: "emocionen",
		},
		Imperfect: {
			yo: "emocionara",
			tú: "emocionaras",
			Ud: "emocionara",
			nosotros: "emocionáramos",
			vosotros: "emocionarais",
			Uds: "emocionaran",
		},
		Imperfect2: {
			yo: "emocionase",
			tú: "emocionases",
			Ud: "emocionase",
			nosotros: "emocionásemos",
			vosotros: "emocionaseis",
			Uds: "emocionasen",
		},
		Future: {
			yo: "emocionare",
			tú: "emocionares",
			Ud: "emocionare",
			nosotros: "emocionáremos",
			vosotros: "emocionareis",
			Uds: "emocionaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "emociona",
			Ud: "emocione",
			nosotros: "emocionemos",
			vosotros: "emocionad",
			Uds: "emocionen",
		},
		Negative: {
			tú: "no emociones",
			Ud: "no emocione",
			nosotros: "no emocionemos",
			vosotros: "no emocionéis",
			Uds: "no emocionen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy emocionando",
			tú: "estás emocionando",
			Ud: "está emocionando",
			nosotros: "estamos emocionando",
			vosotros: "estáis emocionando",
			Uds: "están emocionando",
		},
		Preterite: {
			yo: "estuve emocionando",
			tú: "estuviste emocionando",
			Ud: "estuvo emocionando",
			nosotros: "estuvimos emocionando",
			vosotros: "estuvisteis emocionando",
			Uds: "estuvieron emocionando",
		},
		Imperfect: {
			Uds: "estaban emocionando",
			yo: "estaba emocionando",
			tú: "estabas emocionando",
			Ud: "estaba emocionando",
			nosotros: "estábamos emocionando",
			vosotros: "estabais emocionando",
		},
		Conditional: {
			yo: "estaría emocionando",
			tú: "estarías emocionando",
			Ud: "estaría emocionando",
			nosotros: "estaríamos emocionando",
			vosotros: "estaríais emocionando",
			Uds: "estarían emocionando",
		},
		Future: {
			yo: "estaré emocionando",
			tú: "estarás emocionando",
			Ud: "estará emocionando",
			nosotros: "estaremos emocionando",
			vosotros: "estaréis emocionando",
			Uds: "estarán emocionando",
		},
	},
	Perfect: {
		Present: {
			yo: "he emocionado",
			tú: "has emocionado",
			Ud: "ha emocionado",
			nosotros: "hemos emocionado",
			vosotros: "habéis emocionado",
			Uds: "han emocionado",
		},
		Preterite: {
			yo: "hube emocionado",
			tú: "hubiste emocionado",
			Ud: "hubo emocionado",
			nosotros: "hubimos emocionado",
			vosotros: "hubisteis emocionado",
			Uds: "hubieron emocionado",
		},
		Past: {
			yo: "había emocionado",
			tú: "habías emocionado",
			Ud: "había emocionado",
			nosotros: "habíamos emocionado",
			vosotros: "habíais emocionado",
			Uds: "habían emocionado",
		},
		Conditional: {
			yo: "habría emocionado",
			tú: "habrías emocionado",
			Ud: "habría emocionado",
			nosotros: "habríamos emocionado",
			vosotros: "habríais emocionado",
			Uds: "habrían emocionado",
		},
		Future: {
			yo: "habré emocionado",
			tú: "habrás emocionado",
			Ud: "habrá emocionado",
			nosotros: "habremos emocionado",
			vosotros: "habréis emocionado",
			Uds: "habrán emocionado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya emocionado",
			tú: "hayas emocionado",
			Ud: "haya emocionado",
			nosotros: "hayamos emocionado",
			vosotros: "hayáis emocionado",
			Uds: "hayan emocionado",
		},
		Past: {
			yo: "hubiera emocionado",
			tú: "hubieras emocionado",
			Ud: "hubiera emocionado",
			nosotros: "hubiéramos emocionado",
			vosotros: "hubierais emocionado",
			Uds: "hubieran emocionado",
		},
		Future: {
			yo: "hubiere emocionado",
			tú: "hubieres emocionado",
			Ud: "hubiere emocionado",
			nosotros: "hubiéremos emocionado",
			vosotros: "hubiereis emocionado",
			Uds: "hubieren emocionado",
		},
	},
}
