var empacar = {
	Indicative: {
		Present: {
			yo: "empaco",
			tú: "empacas",
			Ud: "empaca",
			nosotros: "empacamos",
			vosotros: "empacáis",
			Uds: "empacan",
		},
		Preterite: {
			yo: "empaqué",
			tú: "empacaste",
			Ud: "empacó",
			nosotros: "empacamos",
			vosotros: "empacasteis",
			Uds: "empacaron",
		},
		Imperfect: {
			yo: "empacaba",
			tú: "empacabas",
			Ud: "empacaba",
			nosotros: "empacábamos",
			vosotros: "empacabais",
			Uds: "empacaban",
		},
		Conditional: {
			yo: "empacaría",
			tú: "empacarías",
			Ud: "empacaría",
			nosotros: "empacaríamos",
			vosotros: "empacaríais",
			Uds: "empacarían",
		},
		Future: {
			yo: "empacaré",
			tú: "empacarás",
			Ud: "empacará",
			nosotros: "empacaremos",
			vosotros: "empacaréis",
			Uds: "empacarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "empaque",
			tú: "empaques",
			Ud: "empaque",
			nosotros: "empaquemos",
			vosotros: "empaquéis",
			Uds: "empaquen",
		},
		Imperfect: {
			yo: "empacara",
			tú: "empacaras",
			Ud: "empacara",
			nosotros: "empacáramos",
			vosotros: "empacarais",
			Uds: "empacaran",
		},
		Imperfect2: {
			yo: "empacase",
			tú: "empacases",
			Ud: "empacase",
			nosotros: "empacásemos",
			vosotros: "empacaseis",
			Uds: "empacasen",
		},
		Future: {
			yo: "empacare",
			tú: "empacares",
			Ud: "empacare",
			nosotros: "empacáremos",
			vosotros: "empacareis",
			Uds: "empacaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "empaca",
			Ud: "empaque",
			nosotros: "empaquemos",
			vosotros: "empacad",
			Uds: "empaquen",
		},
		Negative: {
			tú: "no empaques",
			Ud: "no empaque",
			nosotros: "no empaquemos",
			vosotros: "no empaquéis",
			Uds: "no empaquen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy empacando",
			tú: "estás empacando",
			Ud: "está empacando",
			nosotros: "estamos empacando",
			vosotros: "estáis empacando",
			Uds: "están empacando",
		},
		Preterite: {
			yo: "estuve empacando",
			tú: "estuviste empacando",
			Ud: "estuvo empacando",
			nosotros: "estuvimos empacando",
			vosotros: "estuvisteis empacando",
			Uds: "estuvieron empacando",
		},
		Imperfect: {
			Uds: "estaban empacando",
			yo: "estaba empacando",
			tú: "estabas empacando",
			Ud: "estaba empacando",
			nosotros: "estábamos empacando",
			vosotros: "estabais empacando",
		},
		Conditional: {
			yo: "estaría empacando",
			tú: "estarías empacando",
			Ud: "estaría empacando",
			nosotros: "estaríamos empacando",
			vosotros: "estaríais empacando",
			Uds: "estarían empacando",
		},
		Future: {
			yo: "estaré empacando",
			tú: "estarás empacando",
			Ud: "estará empacando",
			nosotros: "estaremos empacando",
			vosotros: "estaréis empacando",
			Uds: "estarán empacando",
		},
	},
	Perfect: {
		Present: {
			yo: "he empacado",
			tú: "has empacado",
			Ud: "ha empacado",
			nosotros: "hemos empacado",
			vosotros: "habéis empacado",
			Uds: "han empacado",
		},
		Preterite: {
			yo: "hube empacado",
			tú: "hubiste empacado",
			Ud: "hubo empacado",
			nosotros: "hubimos empacado",
			vosotros: "hubisteis empacado",
			Uds: "hubieron empacado",
		},
		Past: {
			yo: "había empacado",
			tú: "habías empacado",
			Ud: "había empacado",
			nosotros: "habíamos empacado",
			vosotros: "habíais empacado",
			Uds: "habían empacado",
		},
		Conditional: {
			yo: "habría empacado",
			tú: "habrías empacado",
			Ud: "habría empacado",
			nosotros: "habríamos empacado",
			vosotros: "habríais empacado",
			Uds: "habrían empacado",
		},
		Future: {
			yo: "habré empacado",
			tú: "habrás empacado",
			Ud: "habrá empacado",
			nosotros: "habremos empacado",
			vosotros: "habréis empacado",
			Uds: "habrán empacado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya empacado",
			tú: "hayas empacado",
			Ud: "haya empacado",
			nosotros: "hayamos empacado",
			vosotros: "hayáis empacado",
			Uds: "hayan empacado",
		},
		Past: {
			yo: "hubiera empacado",
			tú: "hubieras empacado",
			Ud: "hubiera empacado",
			nosotros: "hubiéramos empacado",
			vosotros: "hubierais empacado",
			Uds: "hubieran empacado",
		},
		Future: {
			yo: "hubiere empacado",
			tú: "hubieres empacado",
			Ud: "hubiere empacado",
			nosotros: "hubiéremos empacado",
			vosotros: "hubiereis empacado",
			Uds: "hubieren empacado",
		},
	},
}
