var empastar = {
	Indicative: {
		Present: {
			yo: "empasto",
			tú: "empastas",
			Ud: "empasta",
			nosotros: "empastamos",
			vosotros: "empastáis",
			Uds: "empastan",
		},
		Preterite: {
			yo: "empasté",
			tú: "empastaste",
			Ud: "empastó",
			nosotros: "empastamos",
			vosotros: "empastasteis",
			Uds: "empastaron",
		},
		Imperfect: {
			yo: "empastaba",
			tú: "empastabas",
			Ud: "empastaba",
			nosotros: "empastábamos",
			vosotros: "empastabais",
			Uds: "empastaban",
		},
		Conditional: {
			yo: "empastaría",
			tú: "empastarías",
			Ud: "empastaría",
			nosotros: "empastaríamos",
			vosotros: "empastaríais",
			Uds: "empastarían",
		},
		Future: {
			yo: "empastaré",
			tú: "empastarás",
			Ud: "empastará",
			nosotros: "empastaremos",
			vosotros: "empastaréis",
			Uds: "empastarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "empaste",
			tú: "empastes",
			Ud: "empaste",
			nosotros: "empastemos",
			vosotros: "empastéis",
			Uds: "empasten",
		},
		Imperfect: {
			yo: "empastara",
			tú: "empastaras",
			Ud: "empastara",
			nosotros: "empastáramos",
			vosotros: "empastarais",
			Uds: "empastaran",
		},
		Imperfect2: {
			yo: "empastase",
			tú: "empastases",
			Ud: "empastase",
			nosotros: "empastásemos",
			vosotros: "empastaseis",
			Uds: "empastasen",
		},
		Future: {
			yo: "empastare",
			tú: "empastares",
			Ud: "empastare",
			nosotros: "empastáremos",
			vosotros: "empastareis",
			Uds: "empastaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "empasta",
			Ud: "empaste",
			nosotros: "empastemos",
			vosotros: "empastad",
			Uds: "empasten",
		},
		Negative: {
			tú: "no empastes",
			Ud: "no empaste",
			nosotros: "no empastemos",
			vosotros: "no empastéis",
			Uds: "no empasten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy empastando",
			tú: "estás empastando",
			Ud: "está empastando",
			nosotros: "estamos empastando",
			vosotros: "estáis empastando",
			Uds: "están empastando",
		},
		Preterite: {
			yo: "estuve empastando",
			tú: "estuviste empastando",
			Ud: "estuvo empastando",
			nosotros: "estuvimos empastando",
			vosotros: "estuvisteis empastando",
			Uds: "estuvieron empastando",
		},
		Imperfect: {
			Uds: "estaban empastando",
			yo: "estaba empastando",
			tú: "estabas empastando",
			Ud: "estaba empastando",
			nosotros: "estábamos empastando",
			vosotros: "estabais empastando",
		},
		Conditional: {
			yo: "estaría empastando",
			tú: "estarías empastando",
			Ud: "estaría empastando",
			nosotros: "estaríamos empastando",
			vosotros: "estaríais empastando",
			Uds: "estarían empastando",
		},
		Future: {
			yo: "estaré empastando",
			tú: "estarás empastando",
			Ud: "estará empastando",
			nosotros: "estaremos empastando",
			vosotros: "estaréis empastando",
			Uds: "estarán empastando",
		},
	},
	Perfect: {
		Present: {
			yo: "he empastado",
			tú: "has empastado",
			Ud: "ha empastado",
			nosotros: "hemos empastado",
			vosotros: "habéis empastado",
			Uds: "han empastado",
		},
		Preterite: {
			yo: "hube empastado",
			tú: "hubiste empastado",
			Ud: "hubo empastado",
			nosotros: "hubimos empastado",
			vosotros: "hubisteis empastado",
			Uds: "hubieron empastado",
		},
		Past: {
			yo: "había empastado",
			tú: "habías empastado",
			Ud: "había empastado",
			nosotros: "habíamos empastado",
			vosotros: "habíais empastado",
			Uds: "habían empastado",
		},
		Conditional: {
			yo: "habría empastado",
			tú: "habrías empastado",
			Ud: "habría empastado",
			nosotros: "habríamos empastado",
			vosotros: "habríais empastado",
			Uds: "habrían empastado",
		},
		Future: {
			yo: "habré empastado",
			tú: "habrás empastado",
			Ud: "habrá empastado",
			nosotros: "habremos empastado",
			vosotros: "habréis empastado",
			Uds: "habrán empastado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya empastado",
			tú: "hayas empastado",
			Ud: "haya empastado",
			nosotros: "hayamos empastado",
			vosotros: "hayáis empastado",
			Uds: "hayan empastado",
		},
		Past: {
			yo: "hubiera empastado",
			tú: "hubieras empastado",
			Ud: "hubiera empastado",
			nosotros: "hubiéramos empastado",
			vosotros: "hubierais empastado",
			Uds: "hubieran empastado",
		},
		Future: {
			yo: "hubiere empastado",
			tú: "hubieres empastado",
			Ud: "hubiere empastado",
			nosotros: "hubiéremos empastado",
			vosotros: "hubiereis empastado",
			Uds: "hubieren empastado",
		},
	},
}
