var empalmar = {
	Indicative: {
		Present: {
			yo: "empalmo",
			tú: "empalmas",
			Ud: "empalma",
			nosotros: "empalmamos",
			vosotros: "empalmáis",
			Uds: "empalman",
		},
		Preterite: {
			yo: "empalmé",
			tú: "empalmaste",
			Ud: "empalmó",
			nosotros: "empalmamos",
			vosotros: "empalmasteis",
			Uds: "empalmaron",
		},
		Imperfect: {
			yo: "empalmaba",
			tú: "empalmabas",
			Ud: "empalmaba",
			nosotros: "empalmábamos",
			vosotros: "empalmabais",
			Uds: "empalmaban",
		},
		Conditional: {
			yo: "empalmaría",
			tú: "empalmarías",
			Ud: "empalmaría",
			nosotros: "empalmaríamos",
			vosotros: "empalmaríais",
			Uds: "empalmarían",
		},
		Future: {
			yo: "empalmaré",
			tú: "empalmarás",
			Ud: "empalmará",
			nosotros: "empalmaremos",
			vosotros: "empalmaréis",
			Uds: "empalmarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "empalme",
			tú: "empalmes",
			Ud: "empalme",
			nosotros: "empalmemos",
			vosotros: "empalméis",
			Uds: "empalmen",
		},
		Imperfect: {
			yo: "empalmara",
			tú: "empalmaras",
			Ud: "empalmara",
			nosotros: "empalmáramos",
			vosotros: "empalmarais",
			Uds: "empalmaran",
		},
		Imperfect2: {
			yo: "empalmase",
			tú: "empalmases",
			Ud: "empalmase",
			nosotros: "empalmásemos",
			vosotros: "empalmaseis",
			Uds: "empalmasen",
		},
		Future: {
			yo: "empalmare",
			tú: "empalmares",
			Ud: "empalmare",
			nosotros: "empalmáremos",
			vosotros: "empalmareis",
			Uds: "empalmaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "empalma",
			Ud: "empalme",
			nosotros: "empalmemos",
			vosotros: "empalmad",
			Uds: "empalmen",
		},
		Negative: {
			tú: "no empalmes",
			Ud: "no empalme",
			nosotros: "no empalmemos",
			vosotros: "no empalméis",
			Uds: "no empalmen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy empalmando",
			tú: "estás empalmando",
			Ud: "está empalmando",
			nosotros: "estamos empalmando",
			vosotros: "estáis empalmando",
			Uds: "están empalmando",
		},
		Preterite: {
			yo: "estuve empalmando",
			tú: "estuviste empalmando",
			Ud: "estuvo empalmando",
			nosotros: "estuvimos empalmando",
			vosotros: "estuvisteis empalmando",
			Uds: "estuvieron empalmando",
		},
		Imperfect: {
			Uds: "estaban empalmando",
			yo: "estaba empalmando",
			tú: "estabas empalmando",
			Ud: "estaba empalmando",
			nosotros: "estábamos empalmando",
			vosotros: "estabais empalmando",
		},
		Conditional: {
			yo: "estaría empalmando",
			tú: "estarías empalmando",
			Ud: "estaría empalmando",
			nosotros: "estaríamos empalmando",
			vosotros: "estaríais empalmando",
			Uds: "estarían empalmando",
		},
		Future: {
			yo: "estaré empalmando",
			tú: "estarás empalmando",
			Ud: "estará empalmando",
			nosotros: "estaremos empalmando",
			vosotros: "estaréis empalmando",
			Uds: "estarán empalmando",
		},
	},
	Perfect: {
		Present: {
			yo: "he empalmado",
			tú: "has empalmado",
			Ud: "ha empalmado",
			nosotros: "hemos empalmado",
			vosotros: "habéis empalmado",
			Uds: "han empalmado",
		},
		Preterite: {
			yo: "hube empalmado",
			tú: "hubiste empalmado",
			Ud: "hubo empalmado",
			nosotros: "hubimos empalmado",
			vosotros: "hubisteis empalmado",
			Uds: "hubieron empalmado",
		},
		Past: {
			yo: "había empalmado",
			tú: "habías empalmado",
			Ud: "había empalmado",
			nosotros: "habíamos empalmado",
			vosotros: "habíais empalmado",
			Uds: "habían empalmado",
		},
		Conditional: {
			yo: "habría empalmado",
			tú: "habrías empalmado",
			Ud: "habría empalmado",
			nosotros: "habríamos empalmado",
			vosotros: "habríais empalmado",
			Uds: "habrían empalmado",
		},
		Future: {
			yo: "habré empalmado",
			tú: "habrás empalmado",
			Ud: "habrá empalmado",
			nosotros: "habremos empalmado",
			vosotros: "habréis empalmado",
			Uds: "habrán empalmado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya empalmado",
			tú: "hayas empalmado",
			Ud: "haya empalmado",
			nosotros: "hayamos empalmado",
			vosotros: "hayáis empalmado",
			Uds: "hayan empalmado",
		},
		Past: {
			yo: "hubiera empalmado",
			tú: "hubieras empalmado",
			Ud: "hubiera empalmado",
			nosotros: "hubiéramos empalmado",
			vosotros: "hubierais empalmado",
			Uds: "hubieran empalmado",
		},
		Future: {
			yo: "hubiere empalmado",
			tú: "hubieres empalmado",
			Ud: "hubiere empalmado",
			nosotros: "hubiéremos empalmado",
			vosotros: "hubiereis empalmado",
			Uds: "hubieren empalmado",
		},
	},
}
