var empedernir = {
	Indicative: {
		Present: {
			yo: "empedernezco",
			tú: "empedernes",
			Ud: "empederne",
			nosotros: "empedernimos",
			vosotros: "empedernís",
			Uds: "empedernen",
		},
		Preterite: {
			yo: "empederní",
			tú: "empederniste",
			Ud: "empedernió",
			nosotros: "empedernimos",
			vosotros: "empedernisteis",
			Uds: "empedernieron",
		},
		Imperfect: {
			yo: "empedernía",
			tú: "empedernías",
			Ud: "empedernía",
			nosotros: "empederníamos",
			vosotros: "empederníais",
			Uds: "empedernían",
		},
		Conditional: {
			yo: "empederniría",
			tú: "empedernirías",
			Ud: "empederniría",
			nosotros: "empederniríamos",
			vosotros: "empederniríais",
			Uds: "empedernirían",
		},
		Future: {
			yo: "empederniré",
			tú: "empedernirás",
			Ud: "empedernirá",
			nosotros: "empederniremos",
			vosotros: "empederniréis",
			Uds: "empedernirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "empedernezca",
			tú: "empedernezcas",
			Ud: "empedernezca",
			nosotros: "empedernezcamos",
			vosotros: "empedernezcáis",
			Uds: "empedernezcan",
		},
		Imperfect: {
			yo: "empederniera",
			tú: "empedernieras",
			Ud: "empederniera",
			nosotros: "empederniéramos",
			vosotros: "empedernierais",
			Uds: "empedernieran",
		},
		Imperfect2: {
			yo: "empederniese",
			tú: "empedernieses",
			Ud: "empederniese",
			nosotros: "empederniésemos",
			vosotros: "empedernieseis",
			Uds: "empederniesen",
		},
		Future: {
			yo: "empederniere",
			tú: "empedernieres",
			Ud: "empederniere",
			nosotros: "empederniéremos",
			vosotros: "empederniereis",
			Uds: "empedernieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "empedernece",
			Ud: "empedernezca",
			nosotros: "empedernezcamos",
			vosotros: "empedernid",
			Uds: "empedernezcan",
		},
		Negative: {
			tú: "no empedernezcas",
			Ud: "no empedernezca",
			nosotros: "no empedernezcamos",
			vosotros: "no empedernezcáis",
			Uds: "no empedernezcan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy empederniendo",
			tú: "estás empederniendo",
			Ud: "está empederniendo",
			nosotros: "estamos empederniendo",
			vosotros: "estáis empederniendo",
			Uds: "están empederniendo",
		},
		Preterite: {
			yo: "estuve empederniendo",
			tú: "estuviste empederniendo",
			Ud: "estuvo empederniendo",
			nosotros: "estuvimos empederniendo",
			vosotros: "estuvisteis empederniendo",
			Uds: "estuvieron empederniendo",
		},
		Imperfect: {
			Uds: "estaban empederniendo",
			yo: "estaba empederniendo",
			tú: "estabas empederniendo",
			Ud: "estaba empederniendo",
			nosotros: "estábamos empederniendo",
			vosotros: "estabais empederniendo",
		},
		Conditional: {
			yo: "estaría empederniendo",
			tú: "estarías empederniendo",
			Ud: "estaría empederniendo",
			nosotros: "estaríamos empederniendo",
			vosotros: "estaríais empederniendo",
			Uds: "estarían empederniendo",
		},
		Future: {
			yo: "estaré empederniendo",
			tú: "estarás empederniendo",
			Ud: "estará empederniendo",
			nosotros: "estaremos empederniendo",
			vosotros: "estaréis empederniendo",
			Uds: "estarán empederniendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he empedernido",
			tú: "has empedernido",
			Ud: "ha empedernido",
			nosotros: "hemos empedernido",
			vosotros: "habéis empedernido",
			Uds: "han empedernido",
		},
		Preterite: {
			yo: "hube empedernido",
			tú: "hubiste empedernido",
			Ud: "hubo empedernido",
			nosotros: "hubimos empedernido",
			vosotros: "hubisteis empedernido",
			Uds: "hubieron empedernido",
		},
		Past: {
			yo: "había empedernido",
			tú: "habías empedernido",
			Ud: "había empedernido",
			nosotros: "habíamos empedernido",
			vosotros: "habíais empedernido",
			Uds: "habían empedernido",
		},
		Conditional: {
			yo: "habría empedernido",
			tú: "habrías empedernido",
			Ud: "habría empedernido",
			nosotros: "habríamos empedernido",
			vosotros: "habríais empedernido",
			Uds: "habrían empedernido",
		},
		Future: {
			yo: "habré empedernido",
			tú: "habrás empedernido",
			Ud: "habrá empedernido",
			nosotros: "habremos empedernido",
			vosotros: "habréis empedernido",
			Uds: "habrán empedernido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya empedernido",
			tú: "hayas empedernido",
			Ud: "haya empedernido",
			nosotros: "hayamos empedernido",
			vosotros: "hayáis empedernido",
			Uds: "hayan empedernido",
		},
		Past: {
			yo: "hubiera empedernido",
			tú: "hubieras empedernido",
			Ud: "hubiera empedernido",
			nosotros: "hubiéramos empedernido",
			vosotros: "hubierais empedernido",
			Uds: "hubieran empedernido",
		},
		Future: {
			yo: "hubiere empedernido",
			tú: "hubieres empedernido",
			Ud: "hubiere empedernido",
			nosotros: "hubiéremos empedernido",
			vosotros: "hubiereis empedernido",
			Uds: "hubieren empedernido",
		},
	},
}
