var empeorar = {
	Indicative: {
		Present: {
			yo: "empeoro",
			tú: "empeoras",
			Ud: "empeora",
			nosotros: "empeoramos",
			vosotros: "empeoráis",
			Uds: "empeoran",
		},
		Preterite: {
			yo: "empeoré",
			tú: "empeoraste",
			Ud: "empeoró",
			nosotros: "empeoramos",
			vosotros: "empeorasteis",
			Uds: "empeoraron",
		},
		Imperfect: {
			yo: "empeoraba",
			tú: "empeorabas",
			Ud: "empeoraba",
			nosotros: "empeorábamos",
			vosotros: "empeorabais",
			Uds: "empeoraban",
		},
		Conditional: {
			yo: "empeoraría",
			tú: "empeorarías",
			Ud: "empeoraría",
			nosotros: "empeoraríamos",
			vosotros: "empeoraríais",
			Uds: "empeorarían",
		},
		Future: {
			yo: "empeoraré",
			tú: "empeorarás",
			Ud: "empeorará",
			nosotros: "empeoraremos",
			vosotros: "empeoraréis",
			Uds: "empeorarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "empeore",
			tú: "empeores",
			Ud: "empeore",
			nosotros: "empeoremos",
			vosotros: "empeoréis",
			Uds: "empeoren",
		},
		Imperfect: {
			yo: "empeorara",
			tú: "empeoraras",
			Ud: "empeorara",
			nosotros: "empeoráramos",
			vosotros: "empeorarais",
			Uds: "empeoraran",
		},
		Imperfect2: {
			yo: "empeorase",
			tú: "empeorases",
			Ud: "empeorase",
			nosotros: "empeorásemos",
			vosotros: "empeoraseis",
			Uds: "empeorasen",
		},
		Future: {
			yo: "empeorare",
			tú: "empeorares",
			Ud: "empeorare",
			nosotros: "empeoráremos",
			vosotros: "empeorareis",
			Uds: "empeoraren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "empeora",
			Ud: "empeore",
			nosotros: "empeoremos",
			vosotros: "empeorad",
			Uds: "empeoren",
		},
		Negative: {
			tú: "no empeores",
			Ud: "no empeore",
			nosotros: "no empeoremos",
			vosotros: "no empeoréis",
			Uds: "no empeoren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy empeorando",
			tú: "estás empeorando",
			Ud: "está empeorando",
			nosotros: "estamos empeorando",
			vosotros: "estáis empeorando",
			Uds: "están empeorando",
		},
		Preterite: {
			yo: "estuve empeorando",
			tú: "estuviste empeorando",
			Ud: "estuvo empeorando",
			nosotros: "estuvimos empeorando",
			vosotros: "estuvisteis empeorando",
			Uds: "estuvieron empeorando",
		},
		Imperfect: {
			Uds: "estaban empeorando",
			yo: "estaba empeorando",
			tú: "estabas empeorando",
			Ud: "estaba empeorando",
			nosotros: "estábamos empeorando",
			vosotros: "estabais empeorando",
		},
		Conditional: {
			yo: "estaría empeorando",
			tú: "estarías empeorando",
			Ud: "estaría empeorando",
			nosotros: "estaríamos empeorando",
			vosotros: "estaríais empeorando",
			Uds: "estarían empeorando",
		},
		Future: {
			yo: "estaré empeorando",
			tú: "estarás empeorando",
			Ud: "estará empeorando",
			nosotros: "estaremos empeorando",
			vosotros: "estaréis empeorando",
			Uds: "estarán empeorando",
		},
	},
	Perfect: {
		Present: {
			yo: "he empeorado",
			tú: "has empeorado",
			Ud: "ha empeorado",
			nosotros: "hemos empeorado",
			vosotros: "habéis empeorado",
			Uds: "han empeorado",
		},
		Preterite: {
			yo: "hube empeorado",
			tú: "hubiste empeorado",
			Ud: "hubo empeorado",
			nosotros: "hubimos empeorado",
			vosotros: "hubisteis empeorado",
			Uds: "hubieron empeorado",
		},
		Past: {
			yo: "había empeorado",
			tú: "habías empeorado",
			Ud: "había empeorado",
			nosotros: "habíamos empeorado",
			vosotros: "habíais empeorado",
			Uds: "habían empeorado",
		},
		Conditional: {
			yo: "habría empeorado",
			tú: "habrías empeorado",
			Ud: "habría empeorado",
			nosotros: "habríamos empeorado",
			vosotros: "habríais empeorado",
			Uds: "habrían empeorado",
		},
		Future: {
			yo: "habré empeorado",
			tú: "habrás empeorado",
			Ud: "habrá empeorado",
			nosotros: "habremos empeorado",
			vosotros: "habréis empeorado",
			Uds: "habrán empeorado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya empeorado",
			tú: "hayas empeorado",
			Ud: "haya empeorado",
			nosotros: "hayamos empeorado",
			vosotros: "hayáis empeorado",
			Uds: "hayan empeorado",
		},
		Past: {
			yo: "hubiera empeorado",
			tú: "hubieras empeorado",
			Ud: "hubiera empeorado",
			nosotros: "hubiéramos empeorado",
			vosotros: "hubierais empeorado",
			Uds: "hubieran empeorado",
		},
		Future: {
			yo: "hubiere empeorado",
			tú: "hubieres empeorado",
			Ud: "hubiere empeorado",
			nosotros: "hubiéremos empeorado",
			vosotros: "hubiereis empeorado",
			Uds: "hubieren empeorado",
		},
	},
}
