var empezar = {
	Indicative: {
		Present: {
			yo: "empiezo",
			tú: "empiezas",
			Ud: "empieza",
			nosotros: "empezamos",
			vosotros: "empezáis",
			Uds: "empiezan",
		},
		Preterite: {
			yo: "empecé",
			tú: "empezaste",
			Ud: "empezó",
			nosotros: "empezamos",
			vosotros: "empezasteis",
			Uds: "empezaron",
		},
		Imperfect: {
			yo: "empezaba",
			tú: "empezabas",
			Ud: "empezaba",
			nosotros: "empezábamos",
			vosotros: "empezabais",
			Uds: "empezaban",
		},
		Conditional: {
			yo: "empezaría",
			tú: "empezarías",
			Ud: "empezaría",
			nosotros: "empezaríamos",
			vosotros: "empezaríais",
			Uds: "empezarían",
		},
		Future: {
			yo: "empezaré",
			tú: "empezarás",
			Ud: "empezará",
			nosotros: "empezaremos",
			vosotros: "empezaréis",
			Uds: "empezarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "empiece",
			tú: "empieces",
			Ud: "empiece",
			nosotros: "empecemos",
			vosotros: "empecéis",
			Uds: "empiecen",
		},
		Imperfect: {
			yo: "empezara",
			tú: "empezaras",
			Ud: "empezara",
			nosotros: "empezáramos",
			vosotros: "empezarais",
			Uds: "empezaran",
		},
		Imperfect2: {
			yo: "empezase",
			tú: "empezases",
			Ud: "empezase",
			nosotros: "empezásemos",
			vosotros: "empezaseis",
			Uds: "empezasen",
		},
		Future: {
			yo: "empezare",
			tú: "empezares",
			Ud: "empezare",
			nosotros: "empezáremos",
			vosotros: "empezareis",
			Uds: "empezaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "empieza",
			Ud: "empiece",
			nosotros: "empecemos",
			vosotros: "empezad",
			Uds: "empiecen",
		},
		Negative: {
			tú: "no empieces",
			Ud: "no empiece",
			nosotros: "no empecemos",
			vosotros: "no empecéis",
			Uds: "no empiecen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy empezando",
			tú: "estás empezando",
			Ud: "está empezando",
			nosotros: "estamos empezando",
			vosotros: "estáis empezando",
			Uds: "están empezando",
		},
		Preterite: {
			yo: "estuve empezando",
			tú: "estuviste empezando",
			Ud: "estuvo empezando",
			nosotros: "estuvimos empezando",
			vosotros: "estuvisteis empezando",
			Uds: "estuvieron empezando",
		},
		Imperfect: {
			Uds: "estaban empezando",
			yo: "estaba empezando",
			tú: "estabas empezando",
			Ud: "estaba empezando",
			nosotros: "estábamos empezando",
			vosotros: "estabais empezando",
		},
		Conditional: {
			yo: "estaría empezando",
			tú: "estarías empezando",
			Ud: "estaría empezando",
			nosotros: "estaríamos empezando",
			vosotros: "estaríais empezando",
			Uds: "estarían empezando",
		},
		Future: {
			yo: "estaré empezando",
			tú: "estarás empezando",
			Ud: "estará empezando",
			nosotros: "estaremos empezando",
			vosotros: "estaréis empezando",
			Uds: "estarán empezando",
		},
	},
	Perfect: {
		Present: {
			yo: "he empezado",
			tú: "has empezado",
			Ud: "ha empezado",
			nosotros: "hemos empezado",
			vosotros: "habéis empezado",
			Uds: "han empezado",
		},
		Preterite: {
			yo: "hube empezado",
			tú: "hubiste empezado",
			Ud: "hubo empezado",
			nosotros: "hubimos empezado",
			vosotros: "hubisteis empezado",
			Uds: "hubieron empezado",
		},
		Past: {
			yo: "había empezado",
			tú: "habías empezado",
			Ud: "había empezado",
			nosotros: "habíamos empezado",
			vosotros: "habíais empezado",
			Uds: "habían empezado",
		},
		Conditional: {
			yo: "habría empezado",
			tú: "habrías empezado",
			Ud: "habría empezado",
			nosotros: "habríamos empezado",
			vosotros: "habríais empezado",
			Uds: "habrían empezado",
		},
		Future: {
			yo: "habré empezado",
			tú: "habrás empezado",
			Ud: "habrá empezado",
			nosotros: "habremos empezado",
			vosotros: "habréis empezado",
			Uds: "habrán empezado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya empezado",
			tú: "hayas empezado",
			Ud: "haya empezado",
			nosotros: "hayamos empezado",
			vosotros: "hayáis empezado",
			Uds: "hayan empezado",
		},
		Past: {
			yo: "hubiera empezado",
			tú: "hubieras empezado",
			Ud: "hubiera empezado",
			nosotros: "hubiéramos empezado",
			vosotros: "hubierais empezado",
			Uds: "hubieran empezado",
		},
		Future: {
			yo: "hubiere empezado",
			tú: "hubieres empezado",
			Ud: "hubiere empezado",
			nosotros: "hubiéremos empezado",
			vosotros: "hubiereis empezado",
			Uds: "hubieren empezado",
		},
	},
}
