var encantar = {
	Indicative: {
		Present: {
			yo: "encanto",
			tú: "encantas",
			Ud: "encanta",
			nosotros: "encantamos",
			vosotros: "encantáis",
			Uds: "encantan",
		},
		Preterite: {
			yo: "encanté",
			tú: "encantaste",
			Ud: "encantó",
			nosotros: "encantamos",
			vosotros: "encantasteis",
			Uds: "encantaron",
		},
		Imperfect: {
			yo: "encantaba",
			tú: "encantabas",
			Ud: "encantaba",
			nosotros: "encantábamos",
			vosotros: "encantabais",
			Uds: "encantaban",
		},
		Conditional: {
			yo: "encantaría",
			tú: "encantarías",
			Ud: "encantaría",
			nosotros: "encantaríamos",
			vosotros: "encantaríais",
			Uds: "encantarían",
		},
		Future: {
			yo: "encantaré",
			tú: "encantarás",
			Ud: "encantará",
			nosotros: "encantaremos",
			vosotros: "encantaréis",
			Uds: "encantarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "encante",
			tú: "encantes",
			Ud: "encante",
			nosotros: "encantemos",
			vosotros: "encantéis",
			Uds: "encanten",
		},
		Imperfect: {
			yo: "encantara",
			tú: "encantaras",
			Ud: "encantara",
			nosotros: "encantáramos",
			vosotros: "encantarais",
			Uds: "encantaran",
		},
		Imperfect2: {
			yo: "encantase",
			tú: "encantases",
			Ud: "encantase",
			nosotros: "encantásemos",
			vosotros: "encantaseis",
			Uds: "encantasen",
		},
		Future: {
			yo: "encantare",
			tú: "encantares",
			Ud: "encantare",
			nosotros: "encantáremos",
			vosotros: "encantareis",
			Uds: "encantaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "encanta",
			Ud: "encante",
			nosotros: "encantemos",
			vosotros: "encantad",
			Uds: "encanten",
		},
		Negative: {
			tú: "no encantes",
			Ud: "no encante",
			nosotros: "no encantemos",
			vosotros: "no encantéis",
			Uds: "no encanten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy encantando",
			tú: "estás encantando",
			Ud: "está encantando",
			nosotros: "estamos encantando",
			vosotros: "estáis encantando",
			Uds: "están encantando",
		},
		Preterite: {
			yo: "estuve encantando",
			tú: "estuviste encantando",
			Ud: "estuvo encantando",
			nosotros: "estuvimos encantando",
			vosotros: "estuvisteis encantando",
			Uds: "estuvieron encantando",
		},
		Imperfect: {
			Uds: "estaban encantando",
			yo: "estaba encantando",
			tú: "estabas encantando",
			Ud: "estaba encantando",
			nosotros: "estábamos encantando",
			vosotros: "estabais encantando",
		},
		Conditional: {
			yo: "estaría encantando",
			tú: "estarías encantando",
			Ud: "estaría encantando",
			nosotros: "estaríamos encantando",
			vosotros: "estaríais encantando",
			Uds: "estarían encantando",
		},
		Future: {
			yo: "estaré encantando",
			tú: "estarás encantando",
			Ud: "estará encantando",
			nosotros: "estaremos encantando",
			vosotros: "estaréis encantando",
			Uds: "estarán encantando",
		},
	},
	Perfect: {
		Present: {
			yo: "he encantado",
			tú: "has encantado",
			Ud: "ha encantado",
			nosotros: "hemos encantado",
			vosotros: "habéis encantado",
			Uds: "han encantado",
		},
		Preterite: {
			yo: "hube encantado",
			tú: "hubiste encantado",
			Ud: "hubo encantado",
			nosotros: "hubimos encantado",
			vosotros: "hubisteis encantado",
			Uds: "hubieron encantado",
		},
		Past: {
			yo: "había encantado",
			tú: "habías encantado",
			Ud: "había encantado",
			nosotros: "habíamos encantado",
			vosotros: "habíais encantado",
			Uds: "habían encantado",
		},
		Conditional: {
			yo: "habría encantado",
			tú: "habrías encantado",
			Ud: "habría encantado",
			nosotros: "habríamos encantado",
			vosotros: "habríais encantado",
			Uds: "habrían encantado",
		},
		Future: {
			yo: "habré encantado",
			tú: "habrás encantado",
			Ud: "habrá encantado",
			nosotros: "habremos encantado",
			vosotros: "habréis encantado",
			Uds: "habrán encantado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya encantado",
			tú: "hayas encantado",
			Ud: "haya encantado",
			nosotros: "hayamos encantado",
			vosotros: "hayáis encantado",
			Uds: "hayan encantado",
		},
		Past: {
			yo: "hubiera encantado",
			tú: "hubieras encantado",
			Ud: "hubiera encantado",
			nosotros: "hubiéramos encantado",
			vosotros: "hubierais encantado",
			Uds: "hubieran encantado",
		},
		Future: {
			yo: "hubiere encantado",
			tú: "hubieres encantado",
			Ud: "hubiere encantado",
			nosotros: "hubiéremos encantado",
			vosotros: "hubiereis encantado",
			Uds: "hubieren encantado",
		},
	},
}
