var encandilar = {
	Indicative: {
		Present: {
			yo: "encandilo",
			tú: "encandilas",
			Ud: "encandila",
			nosotros: "encandilamos",
			vosotros: "encandiláis",
			Uds: "encandilan",
		},
		Preterite: {
			yo: "encandilé",
			tú: "encandilaste",
			Ud: "encandiló",
			nosotros: "encandilamos",
			vosotros: "encandilasteis",
			Uds: "encandilaron",
		},
		Imperfect: {
			yo: "encandilaba",
			tú: "encandilabas",
			Ud: "encandilaba",
			nosotros: "encandilábamos",
			vosotros: "encandilabais",
			Uds: "encandilaban",
		},
		Conditional: {
			yo: "encandilaría",
			tú: "encandilarías",
			Ud: "encandilaría",
			nosotros: "encandilaríamos",
			vosotros: "encandilaríais",
			Uds: "encandilarían",
		},
		Future: {
			yo: "encandilaré",
			tú: "encandilarás",
			Ud: "encandilará",
			nosotros: "encandilaremos",
			vosotros: "encandilaréis",
			Uds: "encandilarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "encandile",
			tú: "encandiles",
			Ud: "encandile",
			nosotros: "encandilemos",
			vosotros: "encandiléis",
			Uds: "encandilen",
		},
		Imperfect: {
			yo: "encandilara",
			tú: "encandilaras",
			Ud: "encandilara",
			nosotros: "encandiláramos",
			vosotros: "encandilarais",
			Uds: "encandilaran",
		},
		Imperfect2: {
			yo: "encandilase",
			tú: "encandilases",
			Ud: "encandilase",
			nosotros: "encandilásemos",
			vosotros: "encandilaseis",
			Uds: "encandilasen",
		},
		Future: {
			yo: "encandilare",
			tú: "encandilares",
			Ud: "encandilare",
			nosotros: "encandiláremos",
			vosotros: "encandilareis",
			Uds: "encandilaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "encandila",
			Ud: "encandile",
			nosotros: "encandilemos",
			vosotros: "encandilad",
			Uds: "encandilen",
		},
		Negative: {
			tú: "no encandiles",
			Ud: "no encandile",
			nosotros: "no encandilemos",
			vosotros: "no encandiléis",
			Uds: "no encandilen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy encandilando",
			tú: "estás encandilando",
			Ud: "está encandilando",
			nosotros: "estamos encandilando",
			vosotros: "estáis encandilando",
			Uds: "están encandilando",
		},
		Preterite: {
			yo: "estuve encandilando",
			tú: "estuviste encandilando",
			Ud: "estuvo encandilando",
			nosotros: "estuvimos encandilando",
			vosotros: "estuvisteis encandilando",
			Uds: "estuvieron encandilando",
		},
		Imperfect: {
			Uds: "estaban encandilando",
			yo: "estaba encandilando",
			tú: "estabas encandilando",
			Ud: "estaba encandilando",
			nosotros: "estábamos encandilando",
			vosotros: "estabais encandilando",
		},
		Conditional: {
			yo: "estaría encandilando",
			tú: "estarías encandilando",
			Ud: "estaría encandilando",
			nosotros: "estaríamos encandilando",
			vosotros: "estaríais encandilando",
			Uds: "estarían encandilando",
		},
		Future: {
			yo: "estaré encandilando",
			tú: "estarás encandilando",
			Ud: "estará encandilando",
			nosotros: "estaremos encandilando",
			vosotros: "estaréis encandilando",
			Uds: "estarán encandilando",
		},
	},
	Perfect: {
		Present: {
			yo: "he encandilado",
			tú: "has encandilado",
			Ud: "ha encandilado",
			nosotros: "hemos encandilado",
			vosotros: "habéis encandilado",
			Uds: "han encandilado",
		},
		Preterite: {
			yo: "hube encandilado",
			tú: "hubiste encandilado",
			Ud: "hubo encandilado",
			nosotros: "hubimos encandilado",
			vosotros: "hubisteis encandilado",
			Uds: "hubieron encandilado",
		},
		Past: {
			yo: "había encandilado",
			tú: "habías encandilado",
			Ud: "había encandilado",
			nosotros: "habíamos encandilado",
			vosotros: "habíais encandilado",
			Uds: "habían encandilado",
		},
		Conditional: {
			yo: "habría encandilado",
			tú: "habrías encandilado",
			Ud: "habría encandilado",
			nosotros: "habríamos encandilado",
			vosotros: "habríais encandilado",
			Uds: "habrían encandilado",
		},
		Future: {
			yo: "habré encandilado",
			tú: "habrás encandilado",
			Ud: "habrá encandilado",
			nosotros: "habremos encandilado",
			vosotros: "habréis encandilado",
			Uds: "habrán encandilado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya encandilado",
			tú: "hayas encandilado",
			Ud: "haya encandilado",
			nosotros: "hayamos encandilado",
			vosotros: "hayáis encandilado",
			Uds: "hayan encandilado",
		},
		Past: {
			yo: "hubiera encandilado",
			tú: "hubieras encandilado",
			Ud: "hubiera encandilado",
			nosotros: "hubiéramos encandilado",
			vosotros: "hubierais encandilado",
			Uds: "hubieran encandilado",
		},
		Future: {
			yo: "hubiere encandilado",
			tú: "hubieres encandilado",
			Ud: "hubiere encandilado",
			nosotros: "hubiéremos encandilado",
			vosotros: "hubiereis encandilado",
			Uds: "hubieren encandilado",
		},
	},
}
