var encerrar = {
	Indicative: {
		Present: {
			yo: "encierro",
			tú: "encierras",
			Ud: "encierra",
			nosotros: "encerramos",
			vosotros: "encerráis",
			Uds: "encierran",
		},
		Preterite: {
			yo: "encerré",
			tú: "encerraste",
			Ud: "encerró",
			nosotros: "encerramos",
			vosotros: "encerrasteis",
			Uds: "encerraron",
		},
		Imperfect: {
			yo: "encerraba",
			tú: "encerrabas",
			Ud: "encerraba",
			nosotros: "encerrábamos",
			vosotros: "encerrabais",
			Uds: "encerraban",
		},
		Conditional: {
			yo: "encerraría",
			tú: "encerrarías",
			Ud: "encerraría",
			nosotros: "encerraríamos",
			vosotros: "encerraríais",
			Uds: "encerrarían",
		},
		Future: {
			yo: "encerraré",
			tú: "encerrarás",
			Ud: "encerrará",
			nosotros: "encerraremos",
			vosotros: "encerraréis",
			Uds: "encerrarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "encierre",
			tú: "encierres",
			Ud: "encierre",
			nosotros: "encerremos",
			vosotros: "encerréis",
			Uds: "encierren",
		},
		Imperfect: {
			yo: "encerrara",
			tú: "encerraras",
			Ud: "encerrara",
			nosotros: "encerráramos",
			vosotros: "encerrarais",
			Uds: "encerraran",
		},
		Imperfect2: {
			yo: "encerrase",
			tú: "encerrases",
			Ud: "encerrase",
			nosotros: "encerrásemos",
			vosotros: "encerraseis",
			Uds: "encerrasen",
		},
		Future: {
			yo: "encerrare",
			tú: "encerrares",
			Ud: "encerrare",
			nosotros: "encerráremos",
			vosotros: "encerrareis",
			Uds: "encerraren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "encierra",
			Ud: "encierre",
			nosotros: "encerremos",
			vosotros: "encerrad",
			Uds: "encierren",
		},
		Negative: {
			tú: "no encierres",
			Ud: "no encierre",
			nosotros: "no encerremos",
			vosotros: "no encerréis",
			Uds: "no encierren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy encerrando",
			tú: "estás encerrando",
			Ud: "está encerrando",
			nosotros: "estamos encerrando",
			vosotros: "estáis encerrando",
			Uds: "están encerrando",
		},
		Preterite: {
			yo: "estuve encerrando",
			tú: "estuviste encerrando",
			Ud: "estuvo encerrando",
			nosotros: "estuvimos encerrando",
			vosotros: "estuvisteis encerrando",
			Uds: "estuvieron encerrando",
		},
		Imperfect: {
			Uds: "estaban encerrando",
			yo: "estaba encerrando",
			tú: "estabas encerrando",
			Ud: "estaba encerrando",
			nosotros: "estábamos encerrando",
			vosotros: "estabais encerrando",
		},
		Conditional: {
			yo: "estaría encerrando",
			tú: "estarías encerrando",
			Ud: "estaría encerrando",
			nosotros: "estaríamos encerrando",
			vosotros: "estaríais encerrando",
			Uds: "estarían encerrando",
		},
		Future: {
			yo: "estaré encerrando",
			tú: "estarás encerrando",
			Ud: "estará encerrando",
			nosotros: "estaremos encerrando",
			vosotros: "estaréis encerrando",
			Uds: "estarán encerrando",
		},
	},
	Perfect: {
		Present: {
			yo: "he encerrado",
			tú: "has encerrado",
			Ud: "ha encerrado",
			nosotros: "hemos encerrado",
			vosotros: "habéis encerrado",
			Uds: "han encerrado",
		},
		Preterite: {
			yo: "hube encerrado",
			tú: "hubiste encerrado",
			Ud: "hubo encerrado",
			nosotros: "hubimos encerrado",
			vosotros: "hubisteis encerrado",
			Uds: "hubieron encerrado",
		},
		Past: {
			yo: "había encerrado",
			tú: "habías encerrado",
			Ud: "había encerrado",
			nosotros: "habíamos encerrado",
			vosotros: "habíais encerrado",
			Uds: "habían encerrado",
		},
		Conditional: {
			yo: "habría encerrado",
			tú: "habrías encerrado",
			Ud: "habría encerrado",
			nosotros: "habríamos encerrado",
			vosotros: "habríais encerrado",
			Uds: "habrían encerrado",
		},
		Future: {
			yo: "habré encerrado",
			tú: "habrás encerrado",
			Ud: "habrá encerrado",
			nosotros: "habremos encerrado",
			vosotros: "habréis encerrado",
			Uds: "habrán encerrado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya encerrado",
			tú: "hayas encerrado",
			Ud: "haya encerrado",
			nosotros: "hayamos encerrado",
			vosotros: "hayáis encerrado",
			Uds: "hayan encerrado",
		},
		Past: {
			yo: "hubiera encerrado",
			tú: "hubieras encerrado",
			Ud: "hubiera encerrado",
			nosotros: "hubiéramos encerrado",
			vosotros: "hubierais encerrado",
			Uds: "hubieran encerrado",
		},
		Future: {
			yo: "hubiere encerrado",
			tú: "hubieres encerrado",
			Ud: "hubiere encerrado",
			nosotros: "hubiéremos encerrado",
			vosotros: "hubiereis encerrado",
			Uds: "hubieren encerrado",
		},
	},
}
