var encolar = {
	Indicative: {
		Present: {
			yo: "encolo",
			tú: "encolas",
			Ud: "encola",
			nosotros: "encolamos",
			vosotros: "encoláis",
			Uds: "encolan",
		},
		Preterite: {
			yo: "encolé",
			tú: "encolaste",
			Ud: "encoló",
			nosotros: "encolamos",
			vosotros: "encolasteis",
			Uds: "encolaron",
		},
		Imperfect: {
			yo: "encolaba",
			tú: "encolabas",
			Ud: "encolaba",
			nosotros: "encolábamos",
			vosotros: "encolabais",
			Uds: "encolaban",
		},
		Conditional: {
			yo: "encolaría",
			tú: "encolarías",
			Ud: "encolaría",
			nosotros: "encolaríamos",
			vosotros: "encolaríais",
			Uds: "encolarían",
		},
		Future: {
			yo: "encolaré",
			tú: "encolarás",
			Ud: "encolará",
			nosotros: "encolaremos",
			vosotros: "encolaréis",
			Uds: "encolarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "encole",
			tú: "encoles",
			Ud: "encole",
			nosotros: "encolemos",
			vosotros: "encoléis",
			Uds: "encolen",
		},
		Imperfect: {
			yo: "encolara",
			tú: "encolaras",
			Ud: "encolara",
			nosotros: "encoláramos",
			vosotros: "encolarais",
			Uds: "encolaran",
		},
		Imperfect2: {
			yo: "encolase",
			tú: "encolases",
			Ud: "encolase",
			nosotros: "encolásemos",
			vosotros: "encolaseis",
			Uds: "encolasen",
		},
		Future: {
			yo: "encolare",
			tú: "encolares",
			Ud: "encolare",
			nosotros: "encoláremos",
			vosotros: "encolareis",
			Uds: "encolaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "encola",
			Ud: "encole",
			nosotros: "encolemos",
			vosotros: "encolad",
			Uds: "encolen",
		},
		Negative: {
			tú: "no encoles",
			Ud: "no encole",
			nosotros: "no encolemos",
			vosotros: "no encoléis",
			Uds: "no encolen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy encolando",
			tú: "estás encolando",
			Ud: "está encolando",
			nosotros: "estamos encolando",
			vosotros: "estáis encolando",
			Uds: "están encolando",
		},
		Preterite: {
			yo: "estuve encolando",
			tú: "estuviste encolando",
			Ud: "estuvo encolando",
			nosotros: "estuvimos encolando",
			vosotros: "estuvisteis encolando",
			Uds: "estuvieron encolando",
		},
		Imperfect: {
			Uds: "estaban encolando",
			yo: "estaba encolando",
			tú: "estabas encolando",
			Ud: "estaba encolando",
			nosotros: "estábamos encolando",
			vosotros: "estabais encolando",
		},
		Conditional: {
			yo: "estaría encolando",
			tú: "estarías encolando",
			Ud: "estaría encolando",
			nosotros: "estaríamos encolando",
			vosotros: "estaríais encolando",
			Uds: "estarían encolando",
		},
		Future: {
			yo: "estaré encolando",
			tú: "estarás encolando",
			Ud: "estará encolando",
			nosotros: "estaremos encolando",
			vosotros: "estaréis encolando",
			Uds: "estarán encolando",
		},
	},
	Perfect: {
		Present: {
			yo: "he encolado",
			tú: "has encolado",
			Ud: "ha encolado",
			nosotros: "hemos encolado",
			vosotros: "habéis encolado",
			Uds: "han encolado",
		},
		Preterite: {
			yo: "hube encolado",
			tú: "hubiste encolado",
			Ud: "hubo encolado",
			nosotros: "hubimos encolado",
			vosotros: "hubisteis encolado",
			Uds: "hubieron encolado",
		},
		Past: {
			yo: "había encolado",
			tú: "habías encolado",
			Ud: "había encolado",
			nosotros: "habíamos encolado",
			vosotros: "habíais encolado",
			Uds: "habían encolado",
		},
		Conditional: {
			yo: "habría encolado",
			tú: "habrías encolado",
			Ud: "habría encolado",
			nosotros: "habríamos encolado",
			vosotros: "habríais encolado",
			Uds: "habrían encolado",
		},
		Future: {
			yo: "habré encolado",
			tú: "habrás encolado",
			Ud: "habrá encolado",
			nosotros: "habremos encolado",
			vosotros: "habréis encolado",
			Uds: "habrán encolado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya encolado",
			tú: "hayas encolado",
			Ud: "haya encolado",
			nosotros: "hayamos encolado",
			vosotros: "hayáis encolado",
			Uds: "hayan encolado",
		},
		Past: {
			yo: "hubiera encolado",
			tú: "hubieras encolado",
			Ud: "hubiera encolado",
			nosotros: "hubiéramos encolado",
			vosotros: "hubierais encolado",
			Uds: "hubieran encolado",
		},
		Future: {
			yo: "hubiere encolado",
			tú: "hubieres encolado",
			Ud: "hubiere encolado",
			nosotros: "hubiéremos encolado",
			vosotros: "hubiereis encolado",
			Uds: "hubieren encolado",
		},
	},
}
