var encuadrar = {
	Indicative: {
		Present: {
			yo: "encuadro",
			tú: "encuadras",
			Ud: "encuadra",
			nosotros: "encuadramos",
			vosotros: "encuadráis",
			Uds: "encuadran",
		},
		Preterite: {
			yo: "encuadré",
			tú: "encuadraste",
			Ud: "encuadró",
			nosotros: "encuadramos",
			vosotros: "encuadrasteis",
			Uds: "encuadraron",
		},
		Imperfect: {
			yo: "encuadraba",
			tú: "encuadrabas",
			Ud: "encuadraba",
			nosotros: "encuadrábamos",
			vosotros: "encuadrabais",
			Uds: "encuadraban",
		},
		Conditional: {
			yo: "encuadraría",
			tú: "encuadrarías",
			Ud: "encuadraría",
			nosotros: "encuadraríamos",
			vosotros: "encuadraríais",
			Uds: "encuadrarían",
		},
		Future: {
			yo: "encuadraré",
			tú: "encuadrarás",
			Ud: "encuadrará",
			nosotros: "encuadraremos",
			vosotros: "encuadraréis",
			Uds: "encuadrarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "encuadre",
			tú: "encuadres",
			Ud: "encuadre",
			nosotros: "encuadremos",
			vosotros: "encuadréis",
			Uds: "encuadren",
		},
		Imperfect: {
			yo: "encuadrara",
			tú: "encuadraras",
			Ud: "encuadrara",
			nosotros: "encuadráramos",
			vosotros: "encuadrarais",
			Uds: "encuadraran",
		},
		Imperfect2: {
			yo: "encuadrase",
			tú: "encuadrases",
			Ud: "encuadrase",
			nosotros: "encuadrásemos",
			vosotros: "encuadraseis",
			Uds: "encuadrasen",
		},
		Future: {
			yo: "encuadrare",
			tú: "encuadrares",
			Ud: "encuadrare",
			nosotros: "encuadráremos",
			vosotros: "encuadrareis",
			Uds: "encuadraren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "encuadra",
			Ud: "encuadre",
			nosotros: "encuadremos",
			vosotros: "encuadrad",
			Uds: "encuadren",
		},
		Negative: {
			tú: "no encuadres",
			Ud: "no encuadre",
			nosotros: "no encuadremos",
			vosotros: "no encuadréis",
			Uds: "no encuadren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy encuadrando",
			tú: "estás encuadrando",
			Ud: "está encuadrando",
			nosotros: "estamos encuadrando",
			vosotros: "estáis encuadrando",
			Uds: "están encuadrando",
		},
		Preterite: {
			yo: "estuve encuadrando",
			tú: "estuviste encuadrando",
			Ud: "estuvo encuadrando",
			nosotros: "estuvimos encuadrando",
			vosotros: "estuvisteis encuadrando",
			Uds: "estuvieron encuadrando",
		},
		Imperfect: {
			Uds: "estaban encuadrando",
			yo: "estaba encuadrando",
			tú: "estabas encuadrando",
			Ud: "estaba encuadrando",
			nosotros: "estábamos encuadrando",
			vosotros: "estabais encuadrando",
		},
		Conditional: {
			yo: "estaría encuadrando",
			tú: "estarías encuadrando",
			Ud: "estaría encuadrando",
			nosotros: "estaríamos encuadrando",
			vosotros: "estaríais encuadrando",
			Uds: "estarían encuadrando",
		},
		Future: {
			yo: "estaré encuadrando",
			tú: "estarás encuadrando",
			Ud: "estará encuadrando",
			nosotros: "estaremos encuadrando",
			vosotros: "estaréis encuadrando",
			Uds: "estarán encuadrando",
		},
	},
	Perfect: {
		Present: {
			yo: "he encuadrado",
			tú: "has encuadrado",
			Ud: "ha encuadrado",
			nosotros: "hemos encuadrado",
			vosotros: "habéis encuadrado",
			Uds: "han encuadrado",
		},
		Preterite: {
			yo: "hube encuadrado",
			tú: "hubiste encuadrado",
			Ud: "hubo encuadrado",
			nosotros: "hubimos encuadrado",
			vosotros: "hubisteis encuadrado",
			Uds: "hubieron encuadrado",
		},
		Past: {
			yo: "había encuadrado",
			tú: "habías encuadrado",
			Ud: "había encuadrado",
			nosotros: "habíamos encuadrado",
			vosotros: "habíais encuadrado",
			Uds: "habían encuadrado",
		},
		Conditional: {
			yo: "habría encuadrado",
			tú: "habrías encuadrado",
			Ud: "habría encuadrado",
			nosotros: "habríamos encuadrado",
			vosotros: "habríais encuadrado",
			Uds: "habrían encuadrado",
		},
		Future: {
			yo: "habré encuadrado",
			tú: "habrás encuadrado",
			Ud: "habrá encuadrado",
			nosotros: "habremos encuadrado",
			vosotros: "habréis encuadrado",
			Uds: "habrán encuadrado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya encuadrado",
			tú: "hayas encuadrado",
			Ud: "haya encuadrado",
			nosotros: "hayamos encuadrado",
			vosotros: "hayáis encuadrado",
			Uds: "hayan encuadrado",
		},
		Past: {
			yo: "hubiera encuadrado",
			tú: "hubieras encuadrado",
			Ud: "hubiera encuadrado",
			nosotros: "hubiéramos encuadrado",
			vosotros: "hubierais encuadrado",
			Uds: "hubieran encuadrado",
		},
		Future: {
			yo: "hubiere encuadrado",
			tú: "hubieres encuadrado",
			Ud: "hubiere encuadrado",
			nosotros: "hubiéremos encuadrado",
			vosotros: "hubiereis encuadrado",
			Uds: "hubieren encuadrado",
		},
	},
}
