var endulzar = {
	Indicative: {
		Present: {
			yo: "endulzo",
			tú: "endulzas",
			Ud: "endulza",
			nosotros: "endulzamos",
			vosotros: "endulzáis",
			Uds: "endulzan",
		},
		Preterite: {
			yo: "endulcé",
			tú: "endulzaste",
			Ud: "endulzó",
			nosotros: "endulzamos",
			vosotros: "endulzasteis",
			Uds: "endulzaron",
		},
		Imperfect: {
			yo: "endulzaba",
			tú: "endulzabas",
			Ud: "endulzaba",
			nosotros: "endulzábamos",
			vosotros: "endulzabais",
			Uds: "endulzaban",
		},
		Conditional: {
			yo: "endulzaría",
			tú: "endulzarías",
			Ud: "endulzaría",
			nosotros: "endulzaríamos",
			vosotros: "endulzaríais",
			Uds: "endulzarían",
		},
		Future: {
			yo: "endulzaré",
			tú: "endulzarás",
			Ud: "endulzará",
			nosotros: "endulzaremos",
			vosotros: "endulzaréis",
			Uds: "endulzarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "endulce",
			tú: "endulces",
			Ud: "endulce",
			nosotros: "endulcemos",
			vosotros: "endulcéis",
			Uds: "endulcen",
		},
		Imperfect: {
			yo: "endulzara",
			tú: "endulzaras",
			Ud: "endulzara",
			nosotros: "endulzáramos",
			vosotros: "endulzarais",
			Uds: "endulzaran",
		},
		Imperfect2: {
			yo: "endulzase",
			tú: "endulzases",
			Ud: "endulzase",
			nosotros: "endulzásemos",
			vosotros: "endulzaseis",
			Uds: "endulzasen",
		},
		Future: {
			yo: "endulzare",
			tú: "endulzares",
			Ud: "endulzare",
			nosotros: "endulzáremos",
			vosotros: "endulzareis",
			Uds: "endulzaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "endulza",
			Ud: "endulce",
			nosotros: "endulcemos",
			vosotros: "endulzad",
			Uds: "endulcen",
		},
		Negative: {
			tú: "no endulces",
			Ud: "no endulce",
			nosotros: "no endulcemos",
			vosotros: "no endulcéis",
			Uds: "no endulcen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy endulzando",
			tú: "estás endulzando",
			Ud: "está endulzando",
			nosotros: "estamos endulzando",
			vosotros: "estáis endulzando",
			Uds: "están endulzando",
		},
		Preterite: {
			yo: "estuve endulzando",
			tú: "estuviste endulzando",
			Ud: "estuvo endulzando",
			nosotros: "estuvimos endulzando",
			vosotros: "estuvisteis endulzando",
			Uds: "estuvieron endulzando",
		},
		Imperfect: {
			Uds: "estaban endulzando",
			yo: "estaba endulzando",
			tú: "estabas endulzando",
			Ud: "estaba endulzando",
			nosotros: "estábamos endulzando",
			vosotros: "estabais endulzando",
		},
		Conditional: {
			yo: "estaría endulzando",
			tú: "estarías endulzando",
			Ud: "estaría endulzando",
			nosotros: "estaríamos endulzando",
			vosotros: "estaríais endulzando",
			Uds: "estarían endulzando",
		},
		Future: {
			yo: "estaré endulzando",
			tú: "estarás endulzando",
			Ud: "estará endulzando",
			nosotros: "estaremos endulzando",
			vosotros: "estaréis endulzando",
			Uds: "estarán endulzando",
		},
	},
	Perfect: {
		Present: {
			yo: "he endulzado",
			tú: "has endulzado",
			Ud: "ha endulzado",
			nosotros: "hemos endulzado",
			vosotros: "habéis endulzado",
			Uds: "han endulzado",
		},
		Preterite: {
			yo: "hube endulzado",
			tú: "hubiste endulzado",
			Ud: "hubo endulzado",
			nosotros: "hubimos endulzado",
			vosotros: "hubisteis endulzado",
			Uds: "hubieron endulzado",
		},
		Past: {
			yo: "había endulzado",
			tú: "habías endulzado",
			Ud: "había endulzado",
			nosotros: "habíamos endulzado",
			vosotros: "habíais endulzado",
			Uds: "habían endulzado",
		},
		Conditional: {
			yo: "habría endulzado",
			tú: "habrías endulzado",
			Ud: "habría endulzado",
			nosotros: "habríamos endulzado",
			vosotros: "habríais endulzado",
			Uds: "habrían endulzado",
		},
		Future: {
			yo: "habré endulzado",
			tú: "habrás endulzado",
			Ud: "habrá endulzado",
			nosotros: "habremos endulzado",
			vosotros: "habréis endulzado",
			Uds: "habrán endulzado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya endulzado",
			tú: "hayas endulzado",
			Ud: "haya endulzado",
			nosotros: "hayamos endulzado",
			vosotros: "hayáis endulzado",
			Uds: "hayan endulzado",
		},
		Past: {
			yo: "hubiera endulzado",
			tú: "hubieras endulzado",
			Ud: "hubiera endulzado",
			nosotros: "hubiéramos endulzado",
			vosotros: "hubierais endulzado",
			Uds: "hubieran endulzado",
		},
		Future: {
			yo: "hubiere endulzado",
			tú: "hubieres endulzado",
			Ud: "hubiere endulzado",
			nosotros: "hubiéremos endulzado",
			vosotros: "hubiereis endulzado",
			Uds: "hubieren endulzado",
		},
	},
}
