var enfadar = {
	Indicative: {
		Present: {
			yo: "enfado",
			tú: "enfadas",
			Ud: "enfada",
			nosotros: "enfadamos",
			vosotros: "enfadáis",
			Uds: "enfadan",
		},
		Preterite: {
			yo: "enfadé",
			tú: "enfadaste",
			Ud: "enfadó",
			nosotros: "enfadamos",
			vosotros: "enfadasteis",
			Uds: "enfadaron",
		},
		Imperfect: {
			yo: "enfadaba",
			tú: "enfadabas",
			Ud: "enfadaba",
			nosotros: "enfadábamos",
			vosotros: "enfadabais",
			Uds: "enfadaban",
		},
		Conditional: {
			yo: "enfadaría",
			tú: "enfadarías",
			Ud: "enfadaría",
			nosotros: "enfadaríamos",
			vosotros: "enfadaríais",
			Uds: "enfadarían",
		},
		Future: {
			yo: "enfadaré",
			tú: "enfadarás",
			Ud: "enfadará",
			nosotros: "enfadaremos",
			vosotros: "enfadaréis",
			Uds: "enfadarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "enfade",
			tú: "enfades",
			Ud: "enfade",
			nosotros: "enfademos",
			vosotros: "enfadéis",
			Uds: "enfaden",
		},
		Imperfect: {
			yo: "enfadara",
			tú: "enfadaras",
			Ud: "enfadara",
			nosotros: "enfadáramos",
			vosotros: "enfadarais",
			Uds: "enfadaran",
		},
		Imperfect2: {
			yo: "enfadase",
			tú: "enfadases",
			Ud: "enfadase",
			nosotros: "enfadásemos",
			vosotros: "enfadaseis",
			Uds: "enfadasen",
		},
		Future: {
			yo: "enfadare",
			tú: "enfadares",
			Ud: "enfadare",
			nosotros: "enfadáremos",
			vosotros: "enfadareis",
			Uds: "enfadaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "enfada",
			Ud: "enfade",
			nosotros: "enfademos",
			vosotros: "enfadad",
			Uds: "enfaden",
		},
		Negative: {
			tú: "no enfades",
			Ud: "no enfade",
			nosotros: "no enfademos",
			vosotros: "no enfadéis",
			Uds: "no enfaden",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy enfadando",
			tú: "estás enfadando",
			Ud: "está enfadando",
			nosotros: "estamos enfadando",
			vosotros: "estáis enfadando",
			Uds: "están enfadando",
		},
		Preterite: {
			yo: "estuve enfadando",
			tú: "estuviste enfadando",
			Ud: "estuvo enfadando",
			nosotros: "estuvimos enfadando",
			vosotros: "estuvisteis enfadando",
			Uds: "estuvieron enfadando",
		},
		Imperfect: {
			Uds: "estaban enfadando",
			yo: "estaba enfadando",
			tú: "estabas enfadando",
			Ud: "estaba enfadando",
			nosotros: "estábamos enfadando",
			vosotros: "estabais enfadando",
		},
		Conditional: {
			yo: "estaría enfadando",
			tú: "estarías enfadando",
			Ud: "estaría enfadando",
			nosotros: "estaríamos enfadando",
			vosotros: "estaríais enfadando",
			Uds: "estarían enfadando",
		},
		Future: {
			yo: "estaré enfadando",
			tú: "estarás enfadando",
			Ud: "estará enfadando",
			nosotros: "estaremos enfadando",
			vosotros: "estaréis enfadando",
			Uds: "estarán enfadando",
		},
	},
	Perfect: {
		Present: {
			yo: "he enfadado",
			tú: "has enfadado",
			Ud: "ha enfadado",
			nosotros: "hemos enfadado",
			vosotros: "habéis enfadado",
			Uds: "han enfadado",
		},
		Preterite: {
			yo: "hube enfadado",
			tú: "hubiste enfadado",
			Ud: "hubo enfadado",
			nosotros: "hubimos enfadado",
			vosotros: "hubisteis enfadado",
			Uds: "hubieron enfadado",
		},
		Past: {
			yo: "había enfadado",
			tú: "habías enfadado",
			Ud: "había enfadado",
			nosotros: "habíamos enfadado",
			vosotros: "habíais enfadado",
			Uds: "habían enfadado",
		},
		Conditional: {
			yo: "habría enfadado",
			tú: "habrías enfadado",
			Ud: "habría enfadado",
			nosotros: "habríamos enfadado",
			vosotros: "habríais enfadado",
			Uds: "habrían enfadado",
		},
		Future: {
			yo: "habré enfadado",
			tú: "habrás enfadado",
			Ud: "habrá enfadado",
			nosotros: "habremos enfadado",
			vosotros: "habréis enfadado",
			Uds: "habrán enfadado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya enfadado",
			tú: "hayas enfadado",
			Ud: "haya enfadado",
			nosotros: "hayamos enfadado",
			vosotros: "hayáis enfadado",
			Uds: "hayan enfadado",
		},
		Past: {
			yo: "hubiera enfadado",
			tú: "hubieras enfadado",
			Ud: "hubiera enfadado",
			nosotros: "hubiéramos enfadado",
			vosotros: "hubierais enfadado",
			Uds: "hubieran enfadado",
		},
		Future: {
			yo: "hubiere enfadado",
			tú: "hubieres enfadado",
			Ud: "hubiere enfadado",
			nosotros: "hubiéremos enfadado",
			vosotros: "hubiereis enfadado",
			Uds: "hubieren enfadado",
		},
	},
}
