var enfermar = {
	Indicative: {
		Present: {
			yo: "enfermo",
			tú: "enfermas",
			Ud: "enferma",
			nosotros: "enfermamos",
			vosotros: "enfermáis",
			Uds: "enferman",
		},
		Preterite: {
			yo: "enfermé",
			tú: "enfermaste",
			Ud: "enfermó",
			nosotros: "enfermamos",
			vosotros: "enfermasteis",
			Uds: "enfermaron",
		},
		Imperfect: {
			yo: "enfermaba",
			tú: "enfermabas",
			Ud: "enfermaba",
			nosotros: "enfermábamos",
			vosotros: "enfermabais",
			Uds: "enfermaban",
		},
		Conditional: {
			yo: "enfermaría",
			tú: "enfermarías",
			Ud: "enfermaría",
			nosotros: "enfermaríamos",
			vosotros: "enfermaríais",
			Uds: "enfermarían",
		},
		Future: {
			yo: "enfermaré",
			tú: "enfermarás",
			Ud: "enfermará",
			nosotros: "enfermaremos",
			vosotros: "enfermaréis",
			Uds: "enfermarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "enferme",
			tú: "enfermes",
			Ud: "enferme",
			nosotros: "enfermemos",
			vosotros: "enferméis",
			Uds: "enfermen",
		},
		Imperfect: {
			yo: "enfermara",
			tú: "enfermaras",
			Ud: "enfermara",
			nosotros: "enfermáramos",
			vosotros: "enfermarais",
			Uds: "enfermaran",
		},
		Imperfect2: {
			yo: "enfermase",
			tú: "enfermases",
			Ud: "enfermase",
			nosotros: "enfermásemos",
			vosotros: "enfermaseis",
			Uds: "enfermasen",
		},
		Future: {
			yo: "enfermare",
			tú: "enfermares",
			Ud: "enfermare",
			nosotros: "enfermáremos",
			vosotros: "enfermareis",
			Uds: "enfermaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "enferma",
			Ud: "enferme",
			nosotros: "enfermemos",
			vosotros: "enfermad",
			Uds: "enfermen",
		},
		Negative: {
			tú: "no enfermes",
			Ud: "no enferme",
			nosotros: "no enfermemos",
			vosotros: "no enferméis",
			Uds: "no enfermen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy enfermando",
			tú: "estás enfermando",
			Ud: "está enfermando",
			nosotros: "estamos enfermando",
			vosotros: "estáis enfermando",
			Uds: "están enfermando",
		},
		Preterite: {
			yo: "estuve enfermando",
			tú: "estuviste enfermando",
			Ud: "estuvo enfermando",
			nosotros: "estuvimos enfermando",
			vosotros: "estuvisteis enfermando",
			Uds: "estuvieron enfermando",
		},
		Imperfect: {
			Uds: "estaban enfermando",
			yo: "estaba enfermando",
			tú: "estabas enfermando",
			Ud: "estaba enfermando",
			nosotros: "estábamos enfermando",
			vosotros: "estabais enfermando",
		},
		Conditional: {
			yo: "estaría enfermando",
			tú: "estarías enfermando",
			Ud: "estaría enfermando",
			nosotros: "estaríamos enfermando",
			vosotros: "estaríais enfermando",
			Uds: "estarían enfermando",
		},
		Future: {
			yo: "estaré enfermando",
			tú: "estarás enfermando",
			Ud: "estará enfermando",
			nosotros: "estaremos enfermando",
			vosotros: "estaréis enfermando",
			Uds: "estarán enfermando",
		},
	},
	Perfect: {
		Present: {
			yo: "he enfermado",
			tú: "has enfermado",
			Ud: "ha enfermado",
			nosotros: "hemos enfermado",
			vosotros: "habéis enfermado",
			Uds: "han enfermado",
		},
		Preterite: {
			yo: "hube enfermado",
			tú: "hubiste enfermado",
			Ud: "hubo enfermado",
			nosotros: "hubimos enfermado",
			vosotros: "hubisteis enfermado",
			Uds: "hubieron enfermado",
		},
		Past: {
			yo: "había enfermado",
			tú: "habías enfermado",
			Ud: "había enfermado",
			nosotros: "habíamos enfermado",
			vosotros: "habíais enfermado",
			Uds: "habían enfermado",
		},
		Conditional: {
			yo: "habría enfermado",
			tú: "habrías enfermado",
			Ud: "habría enfermado",
			nosotros: "habríamos enfermado",
			vosotros: "habríais enfermado",
			Uds: "habrían enfermado",
		},
		Future: {
			yo: "habré enfermado",
			tú: "habrás enfermado",
			Ud: "habrá enfermado",
			nosotros: "habremos enfermado",
			vosotros: "habréis enfermado",
			Uds: "habrán enfermado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya enfermado",
			tú: "hayas enfermado",
			Ud: "haya enfermado",
			nosotros: "hayamos enfermado",
			vosotros: "hayáis enfermado",
			Uds: "hayan enfermado",
		},
		Past: {
			yo: "hubiera enfermado",
			tú: "hubieras enfermado",
			Ud: "hubiera enfermado",
			nosotros: "hubiéramos enfermado",
			vosotros: "hubierais enfermado",
			Uds: "hubieran enfermado",
		},
		Future: {
			yo: "hubiere enfermado",
			tú: "hubieres enfermado",
			Ud: "hubiere enfermado",
			nosotros: "hubiéremos enfermado",
			vosotros: "hubiereis enfermado",
			Uds: "hubieren enfermado",
		},
	},
}
