var enfriar = {
	Indicative: {
		Present: {
			yo: "enfrío",
			tú: "enfrías",
			Ud: "enfría",
			nosotros: "enfriamos",
			vosotros: "enfriáis",
			Uds: "enfrían",
		},
		Preterite: {
			yo: "enfrié",
			tú: "enfriaste",
			Ud: "enfrió",
			nosotros: "enfriamos",
			vosotros: "enfriasteis",
			Uds: "enfriaron",
		},
		Imperfect: {
			yo: "enfriaba",
			tú: "enfriabas",
			Ud: "enfriaba",
			nosotros: "enfriábamos",
			vosotros: "enfriabais",
			Uds: "enfriaban",
		},
		Conditional: {
			yo: "enfriaría",
			tú: "enfriarías",
			Ud: "enfriaría",
			nosotros: "enfriaríamos",
			vosotros: "enfriaríais",
			Uds: "enfriarían",
		},
		Future: {
			yo: "enfriaré",
			tú: "enfriarás",
			Ud: "enfriará",
			nosotros: "enfriaremos",
			vosotros: "enfriaréis",
			Uds: "enfriarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "enfríe",
			tú: "enfríes",
			Ud: "enfríe",
			nosotros: "enfriemos",
			vosotros: "enfriéis",
			Uds: "enfríen",
		},
		Imperfect: {
			yo: "enfriara",
			tú: "enfriaras",
			Ud: "enfriara",
			nosotros: "enfriáramos",
			vosotros: "enfriarais",
			Uds: "enfriaran",
		},
		Imperfect2: {
			yo: "enfriase",
			tú: "enfriases",
			Ud: "enfriase",
			nosotros: "enfriásemos",
			vosotros: "enfriaseis",
			Uds: "enfriasen",
		},
		Future: {
			yo: "enfriare",
			tú: "enfriares",
			Ud: "enfriare",
			nosotros: "enfriáremos",
			vosotros: "enfriareis",
			Uds: "enfriaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "enfría",
			Ud: "enfríe",
			nosotros: "enfriemos",
			vosotros: "enfriad",
			Uds: "enfríen",
		},
		Negative: {
			tú: "no enfríes",
			Ud: "no enfríe",
			nosotros: "no enfriemos",
			vosotros: "no enfriéis",
			Uds: "no enfríen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy enfriando",
			tú: "estás enfriando",
			Ud: "está enfriando",
			nosotros: "estamos enfriando",
			vosotros: "estáis enfriando",
			Uds: "están enfriando",
		},
		Preterite: {
			yo: "estuve enfriando",
			tú: "estuviste enfriando",
			Ud: "estuvo enfriando",
			nosotros: "estuvimos enfriando",
			vosotros: "estuvisteis enfriando",
			Uds: "estuvieron enfriando",
		},
		Imperfect: {
			Uds: "estaban enfriando",
			yo: "estaba enfriando",
			tú: "estabas enfriando",
			Ud: "estaba enfriando",
			nosotros: "estábamos enfriando",
			vosotros: "estabais enfriando",
		},
		Conditional: {
			yo: "estaría enfriando",
			tú: "estarías enfriando",
			Ud: "estaría enfriando",
			nosotros: "estaríamos enfriando",
			vosotros: "estaríais enfriando",
			Uds: "estarían enfriando",
		},
		Future: {
			yo: "estaré enfriando",
			tú: "estarás enfriando",
			Ud: "estará enfriando",
			nosotros: "estaremos enfriando",
			vosotros: "estaréis enfriando",
			Uds: "estarán enfriando",
		},
	},
	Perfect: {
		Present: {
			yo: "he enfriado",
			tú: "has enfriado",
			Ud: "ha enfriado",
			nosotros: "hemos enfriado",
			vosotros: "habéis enfriado",
			Uds: "han enfriado",
		},
		Preterite: {
			yo: "hube enfriado",
			tú: "hubiste enfriado",
			Ud: "hubo enfriado",
			nosotros: "hubimos enfriado",
			vosotros: "hubisteis enfriado",
			Uds: "hubieron enfriado",
		},
		Past: {
			yo: "había enfriado",
			tú: "habías enfriado",
			Ud: "había enfriado",
			nosotros: "habíamos enfriado",
			vosotros: "habíais enfriado",
			Uds: "habían enfriado",
		},
		Conditional: {
			yo: "habría enfriado",
			tú: "habrías enfriado",
			Ud: "habría enfriado",
			nosotros: "habríamos enfriado",
			vosotros: "habríais enfriado",
			Uds: "habrían enfriado",
		},
		Future: {
			yo: "habré enfriado",
			tú: "habrás enfriado",
			Ud: "habrá enfriado",
			nosotros: "habremos enfriado",
			vosotros: "habréis enfriado",
			Uds: "habrán enfriado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya enfriado",
			tú: "hayas enfriado",
			Ud: "haya enfriado",
			nosotros: "hayamos enfriado",
			vosotros: "hayáis enfriado",
			Uds: "hayan enfriado",
		},
		Past: {
			yo: "hubiera enfriado",
			tú: "hubieras enfriado",
			Ud: "hubiera enfriado",
			nosotros: "hubiéramos enfriado",
			vosotros: "hubierais enfriado",
			Uds: "hubieran enfriado",
		},
		Future: {
			yo: "hubiere enfriado",
			tú: "hubieres enfriado",
			Ud: "hubiere enfriado",
			nosotros: "hubiéremos enfriado",
			vosotros: "hubiereis enfriado",
			Uds: "hubieren enfriado",
		},
	},
}
