var enharinar = {
	Indicative: {
		Present: {
			yo: "enharino",
			tú: "enharinas",
			Ud: "enharina",
			nosotros: "enharinamos",
			vosotros: "enharináis",
			Uds: "enharinan",
		},
		Preterite: {
			yo: "enhariné",
			tú: "enharinaste",
			Ud: "enharinó",
			nosotros: "enharinamos",
			vosotros: "enharinasteis",
			Uds: "enharinaron",
		},
		Imperfect: {
			yo: "enharinaba",
			tú: "enharinabas",
			Ud: "enharinaba",
			nosotros: "enharinábamos",
			vosotros: "enharinabais",
			Uds: "enharinaban",
		},
		Conditional: {
			yo: "enharinaría",
			tú: "enharinarías",
			Ud: "enharinaría",
			nosotros: "enharinaríamos",
			vosotros: "enharinaríais",
			Uds: "enharinarían",
		},
		Future: {
			yo: "enharinaré",
			tú: "enharinarás",
			Ud: "enharinará",
			nosotros: "enharinaremos",
			vosotros: "enharinaréis",
			Uds: "enharinarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "enharine",
			tú: "enharines",
			Ud: "enharine",
			nosotros: "enharinemos",
			vosotros: "enharinéis",
			Uds: "enharinen",
		},
		Imperfect: {
			yo: "enharinara",
			tú: "enharinaras",
			Ud: "enharinara",
			nosotros: "enharináramos",
			vosotros: "enharinarais",
			Uds: "enharinaran",
		},
		Imperfect2: {
			yo: "enharinase",
			tú: "enharinases",
			Ud: "enharinase",
			nosotros: "enharinásemos",
			vosotros: "enharinaseis",
			Uds: "enharinasen",
		},
		Future: {
			yo: "enharinare",
			tú: "enharinares",
			Ud: "enharinare",
			nosotros: "enharináremos",
			vosotros: "enharinareis",
			Uds: "enharinaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "enharina",
			Ud: "enharine",
			nosotros: "enharinemos",
			vosotros: "enharinad",
			Uds: "enharinen",
		},
		Negative: {
			tú: "no enharines",
			Ud: "no enharine",
			nosotros: "no enharinemos",
			vosotros: "no enharinéis",
			Uds: "no enharinen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy enharinando",
			tú: "estás enharinando",
			Ud: "está enharinando",
			nosotros: "estamos enharinando",
			vosotros: "estáis enharinando",
			Uds: "están enharinando",
		},
		Preterite: {
			yo: "estuve enharinando",
			tú: "estuviste enharinando",
			Ud: "estuvo enharinando",
			nosotros: "estuvimos enharinando",
			vosotros: "estuvisteis enharinando",
			Uds: "estuvieron enharinando",
		},
		Imperfect: {
			Uds: "estaban enharinando",
			yo: "estaba enharinando",
			tú: "estabas enharinando",
			Ud: "estaba enharinando",
			nosotros: "estábamos enharinando",
			vosotros: "estabais enharinando",
		},
		Conditional: {
			yo: "estaría enharinando",
			tú: "estarías enharinando",
			Ud: "estaría enharinando",
			nosotros: "estaríamos enharinando",
			vosotros: "estaríais enharinando",
			Uds: "estarían enharinando",
		},
		Future: {
			yo: "estaré enharinando",
			tú: "estarás enharinando",
			Ud: "estará enharinando",
			nosotros: "estaremos enharinando",
			vosotros: "estaréis enharinando",
			Uds: "estarán enharinando",
		},
	},
	Perfect: {
		Present: {
			yo: "he enharinado",
			tú: "has enharinado",
			Ud: "ha enharinado",
			nosotros: "hemos enharinado",
			vosotros: "habéis enharinado",
			Uds: "han enharinado",
		},
		Preterite: {
			yo: "hube enharinado",
			tú: "hubiste enharinado",
			Ud: "hubo enharinado",
			nosotros: "hubimos enharinado",
			vosotros: "hubisteis enharinado",
			Uds: "hubieron enharinado",
		},
		Past: {
			yo: "había enharinado",
			tú: "habías enharinado",
			Ud: "había enharinado",
			nosotros: "habíamos enharinado",
			vosotros: "habíais enharinado",
			Uds: "habían enharinado",
		},
		Conditional: {
			yo: "habría enharinado",
			tú: "habrías enharinado",
			Ud: "habría enharinado",
			nosotros: "habríamos enharinado",
			vosotros: "habríais enharinado",
			Uds: "habrían enharinado",
		},
		Future: {
			yo: "habré enharinado",
			tú: "habrás enharinado",
			Ud: "habrá enharinado",
			nosotros: "habremos enharinado",
			vosotros: "habréis enharinado",
			Uds: "habrán enharinado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya enharinado",
			tú: "hayas enharinado",
			Ud: "haya enharinado",
			nosotros: "hayamos enharinado",
			vosotros: "hayáis enharinado",
			Uds: "hayan enharinado",
		},
		Past: {
			yo: "hubiera enharinado",
			tú: "hubieras enharinado",
			Ud: "hubiera enharinado",
			nosotros: "hubiéramos enharinado",
			vosotros: "hubierais enharinado",
			Uds: "hubieran enharinado",
		},
		Future: {
			yo: "hubiere enharinado",
			tú: "hubieres enharinado",
			Ud: "hubiere enharinado",
			nosotros: "hubiéremos enharinado",
			vosotros: "hubiereis enharinado",
			Uds: "hubieren enharinado",
		},
	},
}
