var enojar = {
	Indicative: {
		Present: {
			yo: "enojo",
			tú: "enojas",
			Ud: "enoja",
			nosotros: "enojamos",
			vosotros: "enojáis",
			Uds: "enojan",
		},
		Preterite: {
			yo: "enojé",
			tú: "enojaste",
			Ud: "enojó",
			nosotros: "enojamos",
			vosotros: "enojasteis",
			Uds: "enojaron",
		},
		Imperfect: {
			yo: "enojaba",
			tú: "enojabas",
			Ud: "enojaba",
			nosotros: "enojábamos",
			vosotros: "enojabais",
			Uds: "enojaban",
		},
		Conditional: {
			yo: "enojaría",
			tú: "enojarías",
			Ud: "enojaría",
			nosotros: "enojaríamos",
			vosotros: "enojaríais",
			Uds: "enojarían",
		},
		Future: {
			yo: "enojaré",
			tú: "enojarás",
			Ud: "enojará",
			nosotros: "enojaremos",
			vosotros: "enojaréis",
			Uds: "enojarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "enoje",
			tú: "enojes",
			Ud: "enoje",
			nosotros: "enojemos",
			vosotros: "enojéis",
			Uds: "enojen",
		},
		Imperfect: {
			yo: "enojara",
			tú: "enojaras",
			Ud: "enojara",
			nosotros: "enojáramos",
			vosotros: "enojarais",
			Uds: "enojaran",
		},
		Imperfect2: {
			yo: "enojase",
			tú: "enojases",
			Ud: "enojase",
			nosotros: "enojásemos",
			vosotros: "enojaseis",
			Uds: "enojasen",
		},
		Future: {
			yo: "enojare",
			tú: "enojares",
			Ud: "enojare",
			nosotros: "enojáremos",
			vosotros: "enojareis",
			Uds: "enojaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "enoja",
			Ud: "enoje",
			nosotros: "enojemos",
			vosotros: "enojad",
			Uds: "enojen",
		},
		Negative: {
			tú: "no enojes",
			Ud: "no enoje",
			nosotros: "no enojemos",
			vosotros: "no enojéis",
			Uds: "no enojen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy enojando",
			tú: "estás enojando",
			Ud: "está enojando",
			nosotros: "estamos enojando",
			vosotros: "estáis enojando",
			Uds: "están enojando",
		},
		Preterite: {
			yo: "estuve enojando",
			tú: "estuviste enojando",
			Ud: "estuvo enojando",
			nosotros: "estuvimos enojando",
			vosotros: "estuvisteis enojando",
			Uds: "estuvieron enojando",
		},
		Imperfect: {
			Uds: "estaban enojando",
			yo: "estaba enojando",
			tú: "estabas enojando",
			Ud: "estaba enojando",
			nosotros: "estábamos enojando",
			vosotros: "estabais enojando",
		},
		Conditional: {
			yo: "estaría enojando",
			tú: "estarías enojando",
			Ud: "estaría enojando",
			nosotros: "estaríamos enojando",
			vosotros: "estaríais enojando",
			Uds: "estarían enojando",
		},
		Future: {
			yo: "estaré enojando",
			tú: "estarás enojando",
			Ud: "estará enojando",
			nosotros: "estaremos enojando",
			vosotros: "estaréis enojando",
			Uds: "estarán enojando",
		},
	},
	Perfect: {
		Present: {
			yo: "he enojado",
			tú: "has enojado",
			Ud: "ha enojado",
			nosotros: "hemos enojado",
			vosotros: "habéis enojado",
			Uds: "han enojado",
		},
		Preterite: {
			yo: "hube enojado",
			tú: "hubiste enojado",
			Ud: "hubo enojado",
			nosotros: "hubimos enojado",
			vosotros: "hubisteis enojado",
			Uds: "hubieron enojado",
		},
		Past: {
			yo: "había enojado",
			tú: "habías enojado",
			Ud: "había enojado",
			nosotros: "habíamos enojado",
			vosotros: "habíais enojado",
			Uds: "habían enojado",
		},
		Conditional: {
			yo: "habría enojado",
			tú: "habrías enojado",
			Ud: "habría enojado",
			nosotros: "habríamos enojado",
			vosotros: "habríais enojado",
			Uds: "habrían enojado",
		},
		Future: {
			yo: "habré enojado",
			tú: "habrás enojado",
			Ud: "habrá enojado",
			nosotros: "habremos enojado",
			vosotros: "habréis enojado",
			Uds: "habrán enojado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya enojado",
			tú: "hayas enojado",
			Ud: "haya enojado",
			nosotros: "hayamos enojado",
			vosotros: "hayáis enojado",
			Uds: "hayan enojado",
		},
		Past: {
			yo: "hubiera enojado",
			tú: "hubieras enojado",
			Ud: "hubiera enojado",
			nosotros: "hubiéramos enojado",
			vosotros: "hubierais enojado",
			Uds: "hubieran enojado",
		},
		Future: {
			yo: "hubiere enojado",
			tú: "hubieres enojado",
			Ud: "hubiere enojado",
			nosotros: "hubiéremos enojado",
			vosotros: "hubiereis enojado",
			Uds: "hubieren enojado",
		},
	},
}
