var ensayar = {
	Indicative: {
		Present: {
			yo: "ensayo",
			tú: "ensayas",
			Ud: "ensaya",
			nosotros: "ensayamos",
			vosotros: "ensayáis",
			Uds: "ensayan",
		},
		Preterite: {
			yo: "ensayé",
			tú: "ensayaste",
			Ud: "ensayó",
			nosotros: "ensayamos",
			vosotros: "ensayasteis",
			Uds: "ensayaron",
		},
		Imperfect: {
			yo: "ensayaba",
			tú: "ensayabas",
			Ud: "ensayaba",
			nosotros: "ensayábamos",
			vosotros: "ensayabais",
			Uds: "ensayaban",
		},
		Conditional: {
			yo: "ensayaría",
			tú: "ensayarías",
			Ud: "ensayaría",
			nosotros: "ensayaríamos",
			vosotros: "ensayaríais",
			Uds: "ensayarían",
		},
		Future: {
			yo: "ensayaré",
			tú: "ensayarás",
			Ud: "ensayará",
			nosotros: "ensayaremos",
			vosotros: "ensayaréis",
			Uds: "ensayarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "ensaye",
			tú: "ensayes",
			Ud: "ensaye",
			nosotros: "ensayemos",
			vosotros: "ensayéis",
			Uds: "ensayen",
		},
		Imperfect: {
			yo: "ensayara",
			tú: "ensayaras",
			Ud: "ensayara",
			nosotros: "ensayáramos",
			vosotros: "ensayarais",
			Uds: "ensayaran",
		},
		Imperfect2: {
			yo: "ensayase",
			tú: "ensayases",
			Ud: "ensayase",
			nosotros: "ensayásemos",
			vosotros: "ensayaseis",
			Uds: "ensayasen",
		},
		Future: {
			yo: "ensayare",
			tú: "ensayares",
			Ud: "ensayare",
			nosotros: "ensayáremos",
			vosotros: "ensayareis",
			Uds: "ensayaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "ensaya",
			Ud: "ensaye",
			nosotros: "ensayemos",
			vosotros: "ensayad",
			Uds: "ensayen",
		},
		Negative: {
			tú: "no ensayes",
			Ud: "no ensaye",
			nosotros: "no ensayemos",
			vosotros: "no ensayéis",
			Uds: "no ensayen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy ensayando",
			tú: "estás ensayando",
			Ud: "está ensayando",
			nosotros: "estamos ensayando",
			vosotros: "estáis ensayando",
			Uds: "están ensayando",
		},
		Preterite: {
			yo: "estuve ensayando",
			tú: "estuviste ensayando",
			Ud: "estuvo ensayando",
			nosotros: "estuvimos ensayando",
			vosotros: "estuvisteis ensayando",
			Uds: "estuvieron ensayando",
		},
		Imperfect: {
			Uds: "estaban ensayando",
			yo: "estaba ensayando",
			tú: "estabas ensayando",
			Ud: "estaba ensayando",
			nosotros: "estábamos ensayando",
			vosotros: "estabais ensayando",
		},
		Conditional: {
			yo: "estaría ensayando",
			tú: "estarías ensayando",
			Ud: "estaría ensayando",
			nosotros: "estaríamos ensayando",
			vosotros: "estaríais ensayando",
			Uds: "estarían ensayando",
		},
		Future: {
			yo: "estaré ensayando",
			tú: "estarás ensayando",
			Ud: "estará ensayando",
			nosotros: "estaremos ensayando",
			vosotros: "estaréis ensayando",
			Uds: "estarán ensayando",
		},
	},
	Perfect: {
		Present: {
			yo: "he ensayado",
			tú: "has ensayado",
			Ud: "ha ensayado",
			nosotros: "hemos ensayado",
			vosotros: "habéis ensayado",
			Uds: "han ensayado",
		},
		Preterite: {
			yo: "hube ensayado",
			tú: "hubiste ensayado",
			Ud: "hubo ensayado",
			nosotros: "hubimos ensayado",
			vosotros: "hubisteis ensayado",
			Uds: "hubieron ensayado",
		},
		Past: {
			yo: "había ensayado",
			tú: "habías ensayado",
			Ud: "había ensayado",
			nosotros: "habíamos ensayado",
			vosotros: "habíais ensayado",
			Uds: "habían ensayado",
		},
		Conditional: {
			yo: "habría ensayado",
			tú: "habrías ensayado",
			Ud: "habría ensayado",
			nosotros: "habríamos ensayado",
			vosotros: "habríais ensayado",
			Uds: "habrían ensayado",
		},
		Future: {
			yo: "habré ensayado",
			tú: "habrás ensayado",
			Ud: "habrá ensayado",
			nosotros: "habremos ensayado",
			vosotros: "habréis ensayado",
			Uds: "habrán ensayado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya ensayado",
			tú: "hayas ensayado",
			Ud: "haya ensayado",
			nosotros: "hayamos ensayado",
			vosotros: "hayáis ensayado",
			Uds: "hayan ensayado",
		},
		Past: {
			yo: "hubiera ensayado",
			tú: "hubieras ensayado",
			Ud: "hubiera ensayado",
			nosotros: "hubiéramos ensayado",
			vosotros: "hubierais ensayado",
			Uds: "hubieran ensayado",
		},
		Future: {
			yo: "hubiere ensayado",
			tú: "hubieres ensayado",
			Ud: "hubiere ensayado",
			nosotros: "hubiéremos ensayado",
			vosotros: "hubiereis ensayado",
			Uds: "hubieren ensayado",
		},
	},
}
