var entablillar = {
	Indicative: {
		Present: {
			yo: "entablillo",
			tú: "entablillas",
			Ud: "entablilla",
			nosotros: "entablillamos",
			vosotros: "entablilláis",
			Uds: "entablillan",
		},
		Preterite: {
			yo: "entablillé",
			tú: "entablillaste",
			Ud: "entablilló",
			nosotros: "entablillamos",
			vosotros: "entablillasteis",
			Uds: "entablillaron",
		},
		Imperfect: {
			yo: "entablillaba",
			tú: "entablillabas",
			Ud: "entablillaba",
			nosotros: "entablillábamos",
			vosotros: "entablillabais",
			Uds: "entablillaban",
		},
		Conditional: {
			yo: "entablillaría",
			tú: "entablillarías",
			Ud: "entablillaría",
			nosotros: "entablillaríamos",
			vosotros: "entablillaríais",
			Uds: "entablillarían",
		},
		Future: {
			yo: "entablillaré",
			tú: "entablillarás",
			Ud: "entablillará",
			nosotros: "entablillaremos",
			vosotros: "entablillaréis",
			Uds: "entablillarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "entablille",
			tú: "entablilles",
			Ud: "entablille",
			nosotros: "entablillemos",
			vosotros: "entablilléis",
			Uds: "entablillen",
		},
		Imperfect: {
			yo: "entablillara",
			tú: "entablillaras",
			Ud: "entablillara",
			nosotros: "entablilláramos",
			vosotros: "entablillarais",
			Uds: "entablillaran",
		},
		Imperfect2: {
			yo: "entablillase",
			tú: "entablillases",
			Ud: "entablillase",
			nosotros: "entablillásemos",
			vosotros: "entablillaseis",
			Uds: "entablillasen",
		},
		Future: {
			yo: "entablillare",
			tú: "entablillares",
			Ud: "entablillare",
			nosotros: "entablilláremos",
			vosotros: "entablillareis",
			Uds: "entablillaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "entablilla",
			Ud: "entablille",
			nosotros: "entablillemos",
			vosotros: "entablillad",
			Uds: "entablillen",
		},
		Negative: {
			tú: "no entablilles",
			Ud: "no entablille",
			nosotros: "no entablillemos",
			vosotros: "no entablilléis",
			Uds: "no entablillen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy entablillando",
			tú: "estás entablillando",
			Ud: "está entablillando",
			nosotros: "estamos entablillando",
			vosotros: "estáis entablillando",
			Uds: "están entablillando",
		},
		Preterite: {
			yo: "estuve entablillando",
			tú: "estuviste entablillando",
			Ud: "estuvo entablillando",
			nosotros: "estuvimos entablillando",
			vosotros: "estuvisteis entablillando",
			Uds: "estuvieron entablillando",
		},
		Imperfect: {
			Uds: "estaban entablillando",
			yo: "estaba entablillando",
			tú: "estabas entablillando",
			Ud: "estaba entablillando",
			nosotros: "estábamos entablillando",
			vosotros: "estabais entablillando",
		},
		Conditional: {
			yo: "estaría entablillando",
			tú: "estarías entablillando",
			Ud: "estaría entablillando",
			nosotros: "estaríamos entablillando",
			vosotros: "estaríais entablillando",
			Uds: "estarían entablillando",
		},
		Future: {
			yo: "estaré entablillando",
			tú: "estarás entablillando",
			Ud: "estará entablillando",
			nosotros: "estaremos entablillando",
			vosotros: "estaréis entablillando",
			Uds: "estarán entablillando",
		},
	},
	Perfect: {
		Present: {
			yo: "he entablillado",
			tú: "has entablillado",
			Ud: "ha entablillado",
			nosotros: "hemos entablillado",
			vosotros: "habéis entablillado",
			Uds: "han entablillado",
		},
		Preterite: {
			yo: "hube entablillado",
			tú: "hubiste entablillado",
			Ud: "hubo entablillado",
			nosotros: "hubimos entablillado",
			vosotros: "hubisteis entablillado",
			Uds: "hubieron entablillado",
		},
		Past: {
			yo: "había entablillado",
			tú: "habías entablillado",
			Ud: "había entablillado",
			nosotros: "habíamos entablillado",
			vosotros: "habíais entablillado",
			Uds: "habían entablillado",
		},
		Conditional: {
			yo: "habría entablillado",
			tú: "habrías entablillado",
			Ud: "habría entablillado",
			nosotros: "habríamos entablillado",
			vosotros: "habríais entablillado",
			Uds: "habrían entablillado",
		},
		Future: {
			yo: "habré entablillado",
			tú: "habrás entablillado",
			Ud: "habrá entablillado",
			nosotros: "habremos entablillado",
			vosotros: "habréis entablillado",
			Uds: "habrán entablillado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya entablillado",
			tú: "hayas entablillado",
			Ud: "haya entablillado",
			nosotros: "hayamos entablillado",
			vosotros: "hayáis entablillado",
			Uds: "hayan entablillado",
		},
		Past: {
			yo: "hubiera entablillado",
			tú: "hubieras entablillado",
			Ud: "hubiera entablillado",
			nosotros: "hubiéramos entablillado",
			vosotros: "hubierais entablillado",
			Uds: "hubieran entablillado",
		},
		Future: {
			yo: "hubiere entablillado",
			tú: "hubieres entablillado",
			Ud: "hubiere entablillado",
			nosotros: "hubiéremos entablillado",
			vosotros: "hubiereis entablillado",
			Uds: "hubieren entablillado",
		},
	},
}
