var entrever = {
	Indicative: {
		Present: {
			yo: "entreveo",
			tú: "entrevés",
			Ud: "entrevé",
			nosotros: "entrevemos",
			vosotros: "entrevéis",
			Uds: "entrevén",
		},
		Preterite: {
			yo: "entreví",
			tú: "entreviste",
			Ud: "entrevió",
			nosotros: "entrevimos",
			vosotros: "entrevisteis",
			Uds: "entrevieron",
		},
		Imperfect: {
			yo: "entreveía",
			tú: "entreveías",
			Ud: "entreveía",
			nosotros: "entreveíamos",
			vosotros: "entreveíais",
			Uds: "entreveían",
		},
		Conditional: {
			yo: "entrevería",
			tú: "entreverías",
			Ud: "entrevería",
			nosotros: "entreveríamos",
			vosotros: "entreveríais",
			Uds: "entreverían",
		},
		Future: {
			yo: "entreveré",
			tú: "entreverás",
			Ud: "entreverá",
			nosotros: "entreveremos",
			vosotros: "entreveréis",
			Uds: "entreverán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "entrevea",
			tú: "entreveas",
			Ud: "entrevea",
			nosotros: "entreveamos",
			vosotros: "entreveáis",
			Uds: "entrevean",
		},
		Imperfect: {
			yo: "entreviera",
			tú: "entrevieras",
			Ud: "entreviera",
			nosotros: "entreviéramos",
			vosotros: "entrevierais",
			Uds: "entrevieran",
		},
		Imperfect2: {
			yo: "entreviese",
			tú: "entrevieses",
			Ud: "entreviese",
			nosotros: "entreviésemos",
			vosotros: "entrevieseis",
			Uds: "entreviesen",
		},
		Future: {
			yo: "entreviere",
			tú: "entrevieres",
			Ud: "entreviere",
			nosotros: "entreviéremos",
			vosotros: "entreviereis",
			Uds: "entrevieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "entrevé",
			Ud: "entrevea",
			nosotros: "entreveamos",
			vosotros: "entreved",
			Uds: "entrevean",
		},
		Negative: {
			tú: "no entreveas",
			Ud: "no entrevea",
			nosotros: "no entreveamos",
			vosotros: "no entreveáis",
			Uds: "no entrevean",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy entreviendo",
			tú: "estás entreviendo",
			Ud: "está entreviendo",
			nosotros: "estamos entreviendo",
			vosotros: "estáis entreviendo",
			Uds: "están entreviendo",
		},
		Preterite: {
			yo: "estuve entreviendo",
			tú: "estuviste entreviendo",
			Ud: "estuvo entreviendo",
			nosotros: "estuvimos entreviendo",
			vosotros: "estuvisteis entreviendo",
			Uds: "estuvieron entreviendo",
		},
		Imperfect: {
			Uds: "estaban entreviendo",
			yo: "estaba entreviendo",
			tú: "estabas entreviendo",
			Ud: "estaba entreviendo",
			nosotros: "estábamos entreviendo",
			vosotros: "estabais entreviendo",
		},
		Conditional: {
			yo: "estaría entreviendo",
			tú: "estarías entreviendo",
			Ud: "estaría entreviendo",
			nosotros: "estaríamos entreviendo",
			vosotros: "estaríais entreviendo",
			Uds: "estarían entreviendo",
		},
		Future: {
			yo: "estaré entreviendo",
			tú: "estarás entreviendo",
			Ud: "estará entreviendo",
			nosotros: "estaremos entreviendo",
			vosotros: "estaréis entreviendo",
			Uds: "estarán entreviendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he entrevisto",
			tú: "has entrevisto",
			Ud: "ha entrevisto",
			nosotros: "hemos entrevisto",
			vosotros: "habéis entrevisto",
			Uds: "han entrevisto",
		},
		Preterite: {
			yo: "hube entrevisto",
			tú: "hubiste entrevisto",
			Ud: "hubo entrevisto",
			nosotros: "hubimos entrevisto",
			vosotros: "hubisteis entrevisto",
			Uds: "hubieron entrevisto",
		},
		Past: {
			yo: "había entrevisto",
			tú: "habías entrevisto",
			Ud: "había entrevisto",
			nosotros: "habíamos entrevisto",
			vosotros: "habíais entrevisto",
			Uds: "habían entrevisto",
		},
		Conditional: {
			yo: "habría entrevisto",
			tú: "habrías entrevisto",
			Ud: "habría entrevisto",
			nosotros: "habríamos entrevisto",
			vosotros: "habríais entrevisto",
			Uds: "habrían entrevisto",
		},
		Future: {
			yo: "habré entrevisto",
			tú: "habrás entrevisto",
			Ud: "habrá entrevisto",
			nosotros: "habremos entrevisto",
			vosotros: "habréis entrevisto",
			Uds: "habrán entrevisto",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya entrevisto",
			tú: "hayas entrevisto",
			Ud: "haya entrevisto",
			nosotros: "hayamos entrevisto",
			vosotros: "hayáis entrevisto",
			Uds: "hayan entrevisto",
		},
		Past: {
			yo: "hubiera entrevisto",
			tú: "hubieras entrevisto",
			Ud: "hubiera entrevisto",
			nosotros: "hubiéramos entrevisto",
			vosotros: "hubierais entrevisto",
			Uds: "hubieran entrevisto",
		},
		Future: {
			yo: "hubiere entrevisto",
			tú: "hubieres entrevisto",
			Ud: "hubiere entrevisto",
			nosotros: "hubiéremos entrevisto",
			vosotros: "hubiereis entrevisto",
			Uds: "hubieren entrevisto",
		},
	},
}
