var entretejer = {
	Indicative: {
		Present: {
			yo: "entretejo",
			tú: "entretejes",
			Ud: "entreteje",
			nosotros: "entretejemos",
			vosotros: "entretejéis",
			Uds: "entretejen",
		},
		Preterite: {
			yo: "entretejí",
			tú: "entretejiste",
			Ud: "entretejió",
			nosotros: "entretejimos",
			vosotros: "entretejisteis",
			Uds: "entretejieron",
		},
		Imperfect: {
			yo: "entretejía",
			tú: "entretejías",
			Ud: "entretejía",
			nosotros: "entretejíamos",
			vosotros: "entretejíais",
			Uds: "entretejían",
		},
		Conditional: {
			yo: "entretejería",
			tú: "entretejerías",
			Ud: "entretejería",
			nosotros: "entretejeríamos",
			vosotros: "entretejeríais",
			Uds: "entretejerían",
		},
		Future: {
			yo: "entretejeré",
			tú: "entretejerás",
			Ud: "entretejerá",
			nosotros: "entretejeremos",
			vosotros: "entretejeréis",
			Uds: "entretejerán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "entreteja",
			tú: "entretejas",
			Ud: "entreteja",
			nosotros: "entretejamos",
			vosotros: "entretejáis",
			Uds: "entretejan",
		},
		Imperfect: {
			yo: "entretejiera",
			tú: "entretejieras",
			Ud: "entretejiera",
			nosotros: "entretejiéramos",
			vosotros: "entretejierais",
			Uds: "entretejieran",
		},
		Imperfect2: {
			yo: "entretejiese",
			tú: "entretejieses",
			Ud: "entretejiese",
			nosotros: "entretejiésemos",
			vosotros: "entretejieseis",
			Uds: "entretejiesen",
		},
		Future: {
			yo: "entretejiere",
			tú: "entretejieres",
			Ud: "entretejiere",
			nosotros: "entretejiéremos",
			vosotros: "entretejiereis",
			Uds: "entretejieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "entreteje",
			Ud: "entreteja",
			nosotros: "entretejamos",
			vosotros: "entretejed",
			Uds: "entretejan",
		},
		Negative: {
			tú: "no entretejas",
			Ud: "no entreteja",
			nosotros: "no entretejamos",
			vosotros: "no entretejáis",
			Uds: "no entretejan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy entretejiendo",
			tú: "estás entretejiendo",
			Ud: "está entretejiendo",
			nosotros: "estamos entretejiendo",
			vosotros: "estáis entretejiendo",
			Uds: "están entretejiendo",
		},
		Preterite: {
			yo: "estuve entretejiendo",
			tú: "estuviste entretejiendo",
			Ud: "estuvo entretejiendo",
			nosotros: "estuvimos entretejiendo",
			vosotros: "estuvisteis entretejiendo",
			Uds: "estuvieron entretejiendo",
		},
		Imperfect: {
			Uds: "estaban entretejiendo",
			yo: "estaba entretejiendo",
			tú: "estabas entretejiendo",
			Ud: "estaba entretejiendo",
			nosotros: "estábamos entretejiendo",
			vosotros: "estabais entretejiendo",
		},
		Conditional: {
			yo: "estaría entretejiendo",
			tú: "estarías entretejiendo",
			Ud: "estaría entretejiendo",
			nosotros: "estaríamos entretejiendo",
			vosotros: "estaríais entretejiendo",
			Uds: "estarían entretejiendo",
		},
		Future: {
			yo: "estaré entretejiendo",
			tú: "estarás entretejiendo",
			Ud: "estará entretejiendo",
			nosotros: "estaremos entretejiendo",
			vosotros: "estaréis entretejiendo",
			Uds: "estarán entretejiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he entretejido",
			tú: "has entretejido",
			Ud: "ha entretejido",
			nosotros: "hemos entretejido",
			vosotros: "habéis entretejido",
			Uds: "han entretejido",
		},
		Preterite: {
			yo: "hube entretejido",
			tú: "hubiste entretejido",
			Ud: "hubo entretejido",
			nosotros: "hubimos entretejido",
			vosotros: "hubisteis entretejido",
			Uds: "hubieron entretejido",
		},
		Past: {
			yo: "había entretejido",
			tú: "habías entretejido",
			Ud: "había entretejido",
			nosotros: "habíamos entretejido",
			vosotros: "habíais entretejido",
			Uds: "habían entretejido",
		},
		Conditional: {
			yo: "habría entretejido",
			tú: "habrías entretejido",
			Ud: "habría entretejido",
			nosotros: "habríamos entretejido",
			vosotros: "habríais entretejido",
			Uds: "habrían entretejido",
		},
		Future: {
			yo: "habré entretejido",
			tú: "habrás entretejido",
			Ud: "habrá entretejido",
			nosotros: "habremos entretejido",
			vosotros: "habréis entretejido",
			Uds: "habrán entretejido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya entretejido",
			tú: "hayas entretejido",
			Ud: "haya entretejido",
			nosotros: "hayamos entretejido",
			vosotros: "hayáis entretejido",
			Uds: "hayan entretejido",
		},
		Past: {
			yo: "hubiera entretejido",
			tú: "hubieras entretejido",
			Ud: "hubiera entretejido",
			nosotros: "hubiéramos entretejido",
			vosotros: "hubierais entretejido",
			Uds: "hubieran entretejido",
		},
		Future: {
			yo: "hubiere entretejido",
			tú: "hubieres entretejido",
			Ud: "hubiere entretejido",
			nosotros: "hubiéremos entretejido",
			vosotros: "hubiereis entretejido",
			Uds: "hubieren entretejido",
		},
	},
}
