var entretener = {
	Indicative: {
		Present: {
			yo: "entretengo",
			tú: "entretienes",
			Ud: "entretiene",
			nosotros: "entretenemos",
			vosotros: "entretenéis",
			Uds: "entretienen",
		},
		Preterite: {
			yo: "entretuve",
			tú: "entretuviste",
			Ud: "entretuvo",
			nosotros: "entretuvimos",
			vosotros: "entretuvisteis",
			Uds: "entretuvieron",
		},
		Imperfect: {
			yo: "entretenía",
			tú: "entretenías",
			Ud: "entretenía",
			nosotros: "entreteníamos",
			vosotros: "entreteníais",
			Uds: "entretenían",
		},
		Conditional: {
			yo: "entretendría",
			tú: "entretendrías",
			Ud: "entretendría",
			nosotros: "entretendríamos",
			vosotros: "entretendríais",
			Uds: "entretendrían",
		},
		Future: {
			yo: "entretendré",
			tú: "entretendrás",
			Ud: "entretendrá",
			nosotros: "entretendremos",
			vosotros: "entretendréis",
			Uds: "entretendrán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "entretenga",
			tú: "entretengas",
			Ud: "entretenga",
			nosotros: "entretengamos",
			vosotros: "entretengáis",
			Uds: "entretengan",
		},
		Imperfect: {
			yo: "entretuviera",
			tú: "entretuvieras",
			Ud: "entretuviera",
			nosotros: "entretuviéramos",
			vosotros: "entretuvierais",
			Uds: "entretuvieran",
		},
		Imperfect2: {
			yo: "entretuviese",
			tú: "entretuvieses",
			Ud: "entretuviese",
			nosotros: "entretuviésemos",
			vosotros: "entretuvieseis",
			Uds: "entretuviesen",
		},
		Future: {
			yo: "entretuviere",
			tú: "entretuvieres",
			Ud: "entretuviere",
			nosotros: "entretuviéremos",
			vosotros: "entretuviereis",
			Uds: "entretuvieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "entretén",
			Ud: "entretenga",
			nosotros: "entretengamos",
			vosotros: "entretened",
			Uds: "entretengan",
		},
		Negative: {
			tú: "no entretengas",
			Ud: "no entretenga",
			nosotros: "no entretengamos",
			vosotros: "no entretengáis",
			Uds: "no entretengan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy entreteniendo",
			tú: "estás entreteniendo",
			Ud: "está entreteniendo",
			nosotros: "estamos entreteniendo",
			vosotros: "estáis entreteniendo",
			Uds: "están entreteniendo",
		},
		Preterite: {
			yo: "estuve entreteniendo",
			tú: "estuviste entreteniendo",
			Ud: "estuvo entreteniendo",
			nosotros: "estuvimos entreteniendo",
			vosotros: "estuvisteis entreteniendo",
			Uds: "estuvieron entreteniendo",
		},
		Imperfect: {
			Uds: "estaban entreteniendo",
			yo: "estaba entreteniendo",
			tú: "estabas entreteniendo",
			Ud: "estaba entreteniendo",
			nosotros: "estábamos entreteniendo",
			vosotros: "estabais entreteniendo",
		},
		Conditional: {
			yo: "estaría entreteniendo",
			tú: "estarías entreteniendo",
			Ud: "estaría entreteniendo",
			nosotros: "estaríamos entreteniendo",
			vosotros: "estaríais entreteniendo",
			Uds: "estarían entreteniendo",
		},
		Future: {
			yo: "estaré entreteniendo",
			tú: "estarás entreteniendo",
			Ud: "estará entreteniendo",
			nosotros: "estaremos entreteniendo",
			vosotros: "estaréis entreteniendo",
			Uds: "estarán entreteniendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he entretenido",
			tú: "has entretenido",
			Ud: "ha entretenido",
			nosotros: "hemos entretenido",
			vosotros: "habéis entretenido",
			Uds: "han entretenido",
		},
		Preterite: {
			yo: "hube entretenido",
			tú: "hubiste entretenido",
			Ud: "hubo entretenido",
			nosotros: "hubimos entretenido",
			vosotros: "hubisteis entretenido",
			Uds: "hubieron entretenido",
		},
		Past: {
			yo: "había entretenido",
			tú: "habías entretenido",
			Ud: "había entretenido",
			nosotros: "habíamos entretenido",
			vosotros: "habíais entretenido",
			Uds: "habían entretenido",
		},
		Conditional: {
			yo: "habría entretenido",
			tú: "habrías entretenido",
			Ud: "habría entretenido",
			nosotros: "habríamos entretenido",
			vosotros: "habríais entretenido",
			Uds: "habrían entretenido",
		},
		Future: {
			yo: "habré entretenido",
			tú: "habrás entretenido",
			Ud: "habrá entretenido",
			nosotros: "habremos entretenido",
			vosotros: "habréis entretenido",
			Uds: "habrán entretenido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya entretenido",
			tú: "hayas entretenido",
			Ud: "haya entretenido",
			nosotros: "hayamos entretenido",
			vosotros: "hayáis entretenido",
			Uds: "hayan entretenido",
		},
		Past: {
			yo: "hubiera entretenido",
			tú: "hubieras entretenido",
			Ud: "hubiera entretenido",
			nosotros: "hubiéramos entretenido",
			vosotros: "hubierais entretenido",
			Uds: "hubieran entretenido",
		},
		Future: {
			yo: "hubiere entretenido",
			tú: "hubieres entretenido",
			Ud: "hubiere entretenido",
			nosotros: "hubiéremos entretenido",
			vosotros: "hubiereis entretenido",
			Uds: "hubieren entretenido",
		},
	},
}
