var envejecer = {
	Indicative: {
		Present: {
			yo: "envejezco",
			tú: "envejeces",
			Ud: "envejece",
			nosotros: "envejecemos",
			vosotros: "envejecéis",
			Uds: "envejecen",
		},
		Preterite: {
			yo: "envejecí",
			tú: "envejeciste",
			Ud: "envejeció",
			nosotros: "envejecimos",
			vosotros: "envejecisteis",
			Uds: "envejecieron",
		},
		Imperfect: {
			yo: "envejecía",
			tú: "envejecías",
			Ud: "envejecía",
			nosotros: "envejecíamos",
			vosotros: "envejecíais",
			Uds: "envejecían",
		},
		Conditional: {
			yo: "envejecería",
			tú: "envejecerías",
			Ud: "envejecería",
			nosotros: "envejeceríamos",
			vosotros: "envejeceríais",
			Uds: "envejecerían",
		},
		Future: {
			yo: "envejeceré",
			tú: "envejecerás",
			Ud: "envejecerá",
			nosotros: "envejeceremos",
			vosotros: "envejeceréis",
			Uds: "envejecerán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "envejezca",
			tú: "envejezcas",
			Ud: "envejezca",
			nosotros: "envejezcamos",
			vosotros: "envejezcáis",
			Uds: "envejezcan",
		},
		Imperfect: {
			yo: "envejeciera",
			tú: "envejecieras",
			Ud: "envejeciera",
			nosotros: "envejeciéramos",
			vosotros: "envejecierais",
			Uds: "envejecieran",
		},
		Imperfect2: {
			yo: "envejeciese",
			tú: "envejecieses",
			Ud: "envejeciese",
			nosotros: "envejeciésemos",
			vosotros: "envejecieseis",
			Uds: "envejeciesen",
		},
		Future: {
			yo: "envejeciere",
			tú: "envejecieres",
			Ud: "envejeciere",
			nosotros: "envejeciéremos",
			vosotros: "envejeciereis",
			Uds: "envejecieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "envejece",
			Ud: "envejezca",
			nosotros: "envejezcamos",
			vosotros: "envejeced",
			Uds: "envejezcan",
		},
		Negative: {
			tú: "no envejezcas",
			Ud: "no envejezca",
			nosotros: "no envejezcamos",
			vosotros: "no envejezcáis",
			Uds: "no envejezcan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy envejeciendo",
			tú: "estás envejeciendo",
			Ud: "está envejeciendo",
			nosotros: "estamos envejeciendo",
			vosotros: "estáis envejeciendo",
			Uds: "están envejeciendo",
		},
		Preterite: {
			yo: "estuve envejeciendo",
			tú: "estuviste envejeciendo",
			Ud: "estuvo envejeciendo",
			nosotros: "estuvimos envejeciendo",
			vosotros: "estuvisteis envejeciendo",
			Uds: "estuvieron envejeciendo",
		},
		Imperfect: {
			Uds: "estaban envejeciendo",
			yo: "estaba envejeciendo",
			tú: "estabas envejeciendo",
			Ud: "estaba envejeciendo",
			nosotros: "estábamos envejeciendo",
			vosotros: "estabais envejeciendo",
		},
		Conditional: {
			yo: "estaría envejeciendo",
			tú: "estarías envejeciendo",
			Ud: "estaría envejeciendo",
			nosotros: "estaríamos envejeciendo",
			vosotros: "estaríais envejeciendo",
			Uds: "estarían envejeciendo",
		},
		Future: {
			yo: "estaré envejeciendo",
			tú: "estarás envejeciendo",
			Ud: "estará envejeciendo",
			nosotros: "estaremos envejeciendo",
			vosotros: "estaréis envejeciendo",
			Uds: "estarán envejeciendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he envejecido",
			tú: "has envejecido",
			Ud: "ha envejecido",
			nosotros: "hemos envejecido",
			vosotros: "habéis envejecido",
			Uds: "han envejecido",
		},
		Preterite: {
			yo: "hube envejecido",
			tú: "hubiste envejecido",
			Ud: "hubo envejecido",
			nosotros: "hubimos envejecido",
			vosotros: "hubisteis envejecido",
			Uds: "hubieron envejecido",
		},
		Past: {
			yo: "había envejecido",
			tú: "habías envejecido",
			Ud: "había envejecido",
			nosotros: "habíamos envejecido",
			vosotros: "habíais envejecido",
			Uds: "habían envejecido",
		},
		Conditional: {
			yo: "habría envejecido",
			tú: "habrías envejecido",
			Ud: "habría envejecido",
			nosotros: "habríamos envejecido",
			vosotros: "habríais envejecido",
			Uds: "habrían envejecido",
		},
		Future: {
			yo: "habré envejecido",
			tú: "habrás envejecido",
			Ud: "habrá envejecido",
			nosotros: "habremos envejecido",
			vosotros: "habréis envejecido",
			Uds: "habrán envejecido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya envejecido",
			tú: "hayas envejecido",
			Ud: "haya envejecido",
			nosotros: "hayamos envejecido",
			vosotros: "hayáis envejecido",
			Uds: "hayan envejecido",
		},
		Past: {
			yo: "hubiera envejecido",
			tú: "hubieras envejecido",
			Ud: "hubiera envejecido",
			nosotros: "hubiéramos envejecido",
			vosotros: "hubierais envejecido",
			Uds: "hubieran envejecido",
		},
		Future: {
			yo: "hubiere envejecido",
			tú: "hubieres envejecido",
			Ud: "hubiere envejecido",
			nosotros: "hubiéremos envejecido",
			vosotros: "hubiereis envejecido",
			Uds: "hubieren envejecido",
		},
	},
}
