var enviar = {
	Indicative: {
		Present: {
			yo: "envío",
			tú: "envías",
			Ud: "envía",
			nosotros: "enviamos",
			vosotros: "enviáis",
			Uds: "envían",
		},
		Preterite: {
			yo: "envié",
			tú: "enviaste",
			Ud: "envió",
			nosotros: "enviamos",
			vosotros: "enviasteis",
			Uds: "enviaron",
		},
		Imperfect: {
			yo: "enviaba",
			tú: "enviabas",
			Ud: "enviaba",
			nosotros: "enviábamos",
			vosotros: "enviabais",
			Uds: "enviaban",
		},
		Conditional: {
			yo: "enviaría",
			tú: "enviarías",
			Ud: "enviaría",
			nosotros: "enviaríamos",
			vosotros: "enviaríais",
			Uds: "enviarían",
		},
		Future: {
			yo: "enviaré",
			tú: "enviarás",
			Ud: "enviará",
			nosotros: "enviaremos",
			vosotros: "enviaréis",
			Uds: "enviarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "envíe",
			tú: "envíes",
			Ud: "envíe",
			nosotros: "enviemos",
			vosotros: "enviéis",
			Uds: "envíen",
		},
		Imperfect: {
			yo: "enviara",
			tú: "enviaras",
			Ud: "enviara",
			nosotros: "enviáramos",
			vosotros: "enviarais",
			Uds: "enviaran",
		},
		Imperfect2: {
			yo: "enviase",
			tú: "enviases",
			Ud: "enviase",
			nosotros: "enviásemos",
			vosotros: "enviaseis",
			Uds: "enviasen",
		},
		Future: {
			yo: "enviare",
			tú: "enviares",
			Ud: "enviare",
			nosotros: "enviáremos",
			vosotros: "enviareis",
			Uds: "enviaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "envía",
			Ud: "envíe",
			nosotros: "enviemos",
			vosotros: "enviad",
			Uds: "envíen",
		},
		Negative: {
			tú: "no envíes",
			Ud: "no envíe",
			nosotros: "no enviemos",
			vosotros: "no enviéis",
			Uds: "no envíen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy enviando",
			tú: "estás enviando",
			Ud: "está enviando",
			nosotros: "estamos enviando",
			vosotros: "estáis enviando",
			Uds: "están enviando",
		},
		Preterite: {
			yo: "estuve enviando",
			tú: "estuviste enviando",
			Ud: "estuvo enviando",
			nosotros: "estuvimos enviando",
			vosotros: "estuvisteis enviando",
			Uds: "estuvieron enviando",
		},
		Imperfect: {
			Uds: "estaban enviando",
			yo: "estaba enviando",
			tú: "estabas enviando",
			Ud: "estaba enviando",
			nosotros: "estábamos enviando",
			vosotros: "estabais enviando",
		},
		Conditional: {
			yo: "estaría enviando",
			tú: "estarías enviando",
			Ud: "estaría enviando",
			nosotros: "estaríamos enviando",
			vosotros: "estaríais enviando",
			Uds: "estarían enviando",
		},
		Future: {
			yo: "estaré enviando",
			tú: "estarás enviando",
			Ud: "estará enviando",
			nosotros: "estaremos enviando",
			vosotros: "estaréis enviando",
			Uds: "estarán enviando",
		},
	},
	Perfect: {
		Present: {
			yo: "he enviado",
			tú: "has enviado",
			Ud: "ha enviado",
			nosotros: "hemos enviado",
			vosotros: "habéis enviado",
			Uds: "han enviado",
		},
		Preterite: {
			yo: "hube enviado",
			tú: "hubiste enviado",
			Ud: "hubo enviado",
			nosotros: "hubimos enviado",
			vosotros: "hubisteis enviado",
			Uds: "hubieron enviado",
		},
		Past: {
			yo: "había enviado",
			tú: "habías enviado",
			Ud: "había enviado",
			nosotros: "habíamos enviado",
			vosotros: "habíais enviado",
			Uds: "habían enviado",
		},
		Conditional: {
			yo: "habría enviado",
			tú: "habrías enviado",
			Ud: "habría enviado",
			nosotros: "habríamos enviado",
			vosotros: "habríais enviado",
			Uds: "habrían enviado",
		},
		Future: {
			yo: "habré enviado",
			tú: "habrás enviado",
			Ud: "habrá enviado",
			nosotros: "habremos enviado",
			vosotros: "habréis enviado",
			Uds: "habrán enviado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya enviado",
			tú: "hayas enviado",
			Ud: "haya enviado",
			nosotros: "hayamos enviado",
			vosotros: "hayáis enviado",
			Uds: "hayan enviado",
		},
		Past: {
			yo: "hubiera enviado",
			tú: "hubieras enviado",
			Ud: "hubiera enviado",
			nosotros: "hubiéramos enviado",
			vosotros: "hubierais enviado",
			Uds: "hubieran enviado",
		},
		Future: {
			yo: "hubiere enviado",
			tú: "hubieres enviado",
			Ud: "hubiere enviado",
			nosotros: "hubiéremos enviado",
			vosotros: "hubiereis enviado",
			Uds: "hubieren enviado",
		},
	},
}
