var enyesar = {
	Indicative: {
		Present: {
			yo: "enyeso",
			tú: "enyesas",
			Ud: "enyesa",
			nosotros: "enyesamos",
			vosotros: "enyesáis",
			Uds: "enyesan",
		},
		Preterite: {
			yo: "enyesé",
			tú: "enyesaste",
			Ud: "enyesó",
			nosotros: "enyesamos",
			vosotros: "enyesasteis",
			Uds: "enyesaron",
		},
		Imperfect: {
			yo: "enyesaba",
			tú: "enyesabas",
			Ud: "enyesaba",
			nosotros: "enyesábamos",
			vosotros: "enyesabais",
			Uds: "enyesaban",
		},
		Conditional: {
			yo: "enyesaría",
			tú: "enyesarías",
			Ud: "enyesaría",
			nosotros: "enyesaríamos",
			vosotros: "enyesaríais",
			Uds: "enyesarían",
		},
		Future: {
			yo: "enyesaré",
			tú: "enyesarás",
			Ud: "enyesará",
			nosotros: "enyesaremos",
			vosotros: "enyesaréis",
			Uds: "enyesarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "enyese",
			tú: "enyeses",
			Ud: "enyese",
			nosotros: "enyesemos",
			vosotros: "enyeséis",
			Uds: "enyesen",
		},
		Imperfect: {
			yo: "enyesara",
			tú: "enyesaras",
			Ud: "enyesara",
			nosotros: "enyesáramos",
			vosotros: "enyesarais",
			Uds: "enyesaran",
		},
		Imperfect2: {
			yo: "enyesase",
			tú: "enyesases",
			Ud: "enyesase",
			nosotros: "enyesásemos",
			vosotros: "enyesaseis",
			Uds: "enyesasen",
		},
		Future: {
			yo: "enyesare",
			tú: "enyesares",
			Ud: "enyesare",
			nosotros: "enyesáremos",
			vosotros: "enyesareis",
			Uds: "enyesaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "enyesa",
			Ud: "enyese",
			nosotros: "enyesemos",
			vosotros: "enyesad",
			Uds: "enyesen",
		},
		Negative: {
			tú: "no enyeses",
			Ud: "no enyese",
			nosotros: "no enyesemos",
			vosotros: "no enyeséis",
			Uds: "no enyesen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy enyesando",
			tú: "estás enyesando",
			Ud: "está enyesando",
			nosotros: "estamos enyesando",
			vosotros: "estáis enyesando",
			Uds: "están enyesando",
		},
		Preterite: {
			yo: "estuve enyesando",
			tú: "estuviste enyesando",
			Ud: "estuvo enyesando",
			nosotros: "estuvimos enyesando",
			vosotros: "estuvisteis enyesando",
			Uds: "estuvieron enyesando",
		},
		Imperfect: {
			Uds: "estaban enyesando",
			yo: "estaba enyesando",
			tú: "estabas enyesando",
			Ud: "estaba enyesando",
			nosotros: "estábamos enyesando",
			vosotros: "estabais enyesando",
		},
		Conditional: {
			yo: "estaría enyesando",
			tú: "estarías enyesando",
			Ud: "estaría enyesando",
			nosotros: "estaríamos enyesando",
			vosotros: "estaríais enyesando",
			Uds: "estarían enyesando",
		},
		Future: {
			yo: "estaré enyesando",
			tú: "estarás enyesando",
			Ud: "estará enyesando",
			nosotros: "estaremos enyesando",
			vosotros: "estaréis enyesando",
			Uds: "estarán enyesando",
		},
	},
	Perfect: {
		Present: {
			yo: "he enyesado",
			tú: "has enyesado",
			Ud: "ha enyesado",
			nosotros: "hemos enyesado",
			vosotros: "habéis enyesado",
			Uds: "han enyesado",
		},
		Preterite: {
			yo: "hube enyesado",
			tú: "hubiste enyesado",
			Ud: "hubo enyesado",
			nosotros: "hubimos enyesado",
			vosotros: "hubisteis enyesado",
			Uds: "hubieron enyesado",
		},
		Past: {
			yo: "había enyesado",
			tú: "habías enyesado",
			Ud: "había enyesado",
			nosotros: "habíamos enyesado",
			vosotros: "habíais enyesado",
			Uds: "habían enyesado",
		},
		Conditional: {
			yo: "habría enyesado",
			tú: "habrías enyesado",
			Ud: "habría enyesado",
			nosotros: "habríamos enyesado",
			vosotros: "habríais enyesado",
			Uds: "habrían enyesado",
		},
		Future: {
			yo: "habré enyesado",
			tú: "habrás enyesado",
			Ud: "habrá enyesado",
			nosotros: "habremos enyesado",
			vosotros: "habréis enyesado",
			Uds: "habrán enyesado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya enyesado",
			tú: "hayas enyesado",
			Ud: "haya enyesado",
			nosotros: "hayamos enyesado",
			vosotros: "hayáis enyesado",
			Uds: "hayan enyesado",
		},
		Past: {
			yo: "hubiera enyesado",
			tú: "hubieras enyesado",
			Ud: "hubiera enyesado",
			nosotros: "hubiéramos enyesado",
			vosotros: "hubierais enyesado",
			Uds: "hubieran enyesado",
		},
		Future: {
			yo: "hubiere enyesado",
			tú: "hubieres enyesado",
			Ud: "hubiere enyesado",
			nosotros: "hubiéremos enyesado",
			vosotros: "hubiereis enyesado",
			Uds: "hubieren enyesado",
		},
	},
}
