var errar = {
	Indicative: {
		Present: {
			yo: "yerro,erro",
			tú: "yerras,erras",
			Ud: "yerra,erra",
			nosotros: "erramos",
			vosotros: "erráis",
			Uds: "yerran,erran",
		},
		Preterite: {
			yo: "erré",
			tú: "erraste",
			Ud: "erró",
			nosotros: "erramos",
			vosotros: "errasteis",
			Uds: "erraron",
		},
		Imperfect: {
			yo: "erraba",
			tú: "errabas",
			Ud: "erraba",
			nosotros: "errábamos",
			vosotros: "errabais",
			Uds: "erraban",
		},
		Conditional: {
			yo: "erraría",
			tú: "errarías",
			Ud: "erraría",
			nosotros: "erraríamos",
			vosotros: "erraríais",
			Uds: "errarían",
		},
		Future: {
			yo: "erraré",
			tú: "errarás",
			Ud: "errará",
			nosotros: "erraremos",
			vosotros: "erraréis",
			Uds: "errarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "yerre,erre",
			tú: "yerres,erres",
			Ud: "yerre,erre",
			nosotros: "erremos",
			vosotros: "erréis",
			Uds: "yerren,erren",
		},
		Imperfect: {
			yo: "errara",
			tú: "erraras",
			Ud: "errara",
			nosotros: "erráramos",
			vosotros: "errarais",
			Uds: "erraran",
		},
		Imperfect2: {
			yo: "errase",
			tú: "errases",
			Ud: "errase",
			nosotros: "errásemos",
			vosotros: "erraseis",
			Uds: "errasen",
		},
		Future: {
			yo: "errare",
			tú: "errares",
			Ud: "errare",
			nosotros: "erráremos",
			vosotros: "errareis",
			Uds: "erraren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "yerra,erra",
			Ud: "yerre,erre",
			nosotros: "erremos",
			vosotros: "errad",
			Uds: "yerren,erren",
		},
		Negative: {
			tú: "no yerres,erres",
			Ud: "no yerre,erre",
			nosotros: "no erremos",
			vosotros: "no erréis",
			Uds: "no yerren,erren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy errando",
			tú: "estás errando",
			Ud: "está errando",
			nosotros: "estamos errando",
			vosotros: "estáis errando",
			Uds: "están errando",
		},
		Preterite: {
			yo: "estuve errando",
			tú: "estuviste errando",
			Ud: "estuvo errando",
			nosotros: "estuvimos errando",
			vosotros: "estuvisteis errando",
			Uds: "estuvieron errando",
		},
		Imperfect: {
			Uds: "estaban errando",
			yo: "estaba errando",
			tú: "estabas errando",
			Ud: "estaba errando",
			nosotros: "estábamos errando",
			vosotros: "estabais errando",
		},
		Conditional: {
			yo: "estaría errando",
			tú: "estarías errando",
			Ud: "estaría errando",
			nosotros: "estaríamos errando",
			vosotros: "estaríais errando",
			Uds: "estarían errando",
		},
		Future: {
			yo: "estaré errando",
			tú: "estarás errando",
			Ud: "estará errando",
			nosotros: "estaremos errando",
			vosotros: "estaréis errando",
			Uds: "estarán errando",
		},
	},
	Perfect: {
		Present: {
			yo: "he errado",
			tú: "has errado",
			Ud: "ha errado",
			nosotros: "hemos errado",
			vosotros: "habéis errado",
			Uds: "han errado",
		},
		Preterite: {
			yo: "hube errado",
			tú: "hubiste errado",
			Ud: "hubo errado",
			nosotros: "hubimos errado",
			vosotros: "hubisteis errado",
			Uds: "hubieron errado",
		},
		Past: {
			yo: "había errado",
			tú: "habías errado",
			Ud: "había errado",
			nosotros: "habíamos errado",
			vosotros: "habíais errado",
			Uds: "habían errado",
		},
		Conditional: {
			yo: "habría errado",
			tú: "habrías errado",
			Ud: "habría errado",
			nosotros: "habríamos errado",
			vosotros: "habríais errado",
			Uds: "habrían errado",
		},
		Future: {
			yo: "habré errado",
			tú: "habrás errado",
			Ud: "habrá errado",
			nosotros: "habremos errado",
			vosotros: "habréis errado",
			Uds: "habrán errado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya errado",
			tú: "hayas errado",
			Ud: "haya errado",
			nosotros: "hayamos errado",
			vosotros: "hayáis errado",
			Uds: "hayan errado",
		},
		Past: {
			yo: "hubiera errado",
			tú: "hubieras errado",
			Ud: "hubiera errado",
			nosotros: "hubiéramos errado",
			vosotros: "hubierais errado",
			Uds: "hubieran errado",
		},
		Future: {
			yo: "hubiere errado",
			tú: "hubieres errado",
			Ud: "hubiere errado",
			nosotros: "hubiéremos errado",
			vosotros: "hubiereis errado",
			Uds: "hubieren errado",
		},
	},
}
