var escalonar = {
	Indicative: {
		Present: {
			yo: "escalono",
			tú: "escalonas",
			Ud: "escalona",
			nosotros: "escalonamos",
			vosotros: "escalonáis",
			Uds: "escalonan",
		},
		Preterite: {
			yo: "escaloné",
			tú: "escalonaste",
			Ud: "escalonó",
			nosotros: "escalonamos",
			vosotros: "escalonasteis",
			Uds: "escalonaron",
		},
		Imperfect: {
			yo: "escalonaba",
			tú: "escalonabas",
			Ud: "escalonaba",
			nosotros: "escalonábamos",
			vosotros: "escalonabais",
			Uds: "escalonaban",
		},
		Conditional: {
			yo: "escalonaría",
			tú: "escalonarías",
			Ud: "escalonaría",
			nosotros: "escalonaríamos",
			vosotros: "escalonaríais",
			Uds: "escalonarían",
		},
		Future: {
			yo: "escalonaré",
			tú: "escalonarás",
			Ud: "escalonará",
			nosotros: "escalonaremos",
			vosotros: "escalonaréis",
			Uds: "escalonarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "escalone",
			tú: "escalones",
			Ud: "escalone",
			nosotros: "escalonemos",
			vosotros: "escalonéis",
			Uds: "escalonen",
		},
		Imperfect: {
			yo: "escalonara",
			tú: "escalonaras",
			Ud: "escalonara",
			nosotros: "escalonáramos",
			vosotros: "escalonarais",
			Uds: "escalonaran",
		},
		Imperfect2: {
			yo: "escalonase",
			tú: "escalonases",
			Ud: "escalonase",
			nosotros: "escalonásemos",
			vosotros: "escalonaseis",
			Uds: "escalonasen",
		},
		Future: {
			yo: "escalonare",
			tú: "escalonares",
			Ud: "escalonare",
			nosotros: "escalonáremos",
			vosotros: "escalonareis",
			Uds: "escalonaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "escalona",
			Ud: "escalone",
			nosotros: "escalonemos",
			vosotros: "escalonad",
			Uds: "escalonen",
		},
		Negative: {
			tú: "no escalones",
			Ud: "no escalone",
			nosotros: "no escalonemos",
			vosotros: "no escalonéis",
			Uds: "no escalonen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy escalonando",
			tú: "estás escalonando",
			Ud: "está escalonando",
			nosotros: "estamos escalonando",
			vosotros: "estáis escalonando",
			Uds: "están escalonando",
		},
		Preterite: {
			yo: "estuve escalonando",
			tú: "estuviste escalonando",
			Ud: "estuvo escalonando",
			nosotros: "estuvimos escalonando",
			vosotros: "estuvisteis escalonando",
			Uds: "estuvieron escalonando",
		},
		Imperfect: {
			Uds: "estaban escalonando",
			yo: "estaba escalonando",
			tú: "estabas escalonando",
			Ud: "estaba escalonando",
			nosotros: "estábamos escalonando",
			vosotros: "estabais escalonando",
		},
		Conditional: {
			yo: "estaría escalonando",
			tú: "estarías escalonando",
			Ud: "estaría escalonando",
			nosotros: "estaríamos escalonando",
			vosotros: "estaríais escalonando",
			Uds: "estarían escalonando",
		},
		Future: {
			yo: "estaré escalonando",
			tú: "estarás escalonando",
			Ud: "estará escalonando",
			nosotros: "estaremos escalonando",
			vosotros: "estaréis escalonando",
			Uds: "estarán escalonando",
		},
	},
	Perfect: {
		Present: {
			yo: "he escalonado",
			tú: "has escalonado",
			Ud: "ha escalonado",
			nosotros: "hemos escalonado",
			vosotros: "habéis escalonado",
			Uds: "han escalonado",
		},
		Preterite: {
			yo: "hube escalonado",
			tú: "hubiste escalonado",
			Ud: "hubo escalonado",
			nosotros: "hubimos escalonado",
			vosotros: "hubisteis escalonado",
			Uds: "hubieron escalonado",
		},
		Past: {
			yo: "había escalonado",
			tú: "habías escalonado",
			Ud: "había escalonado",
			nosotros: "habíamos escalonado",
			vosotros: "habíais escalonado",
			Uds: "habían escalonado",
		},
		Conditional: {
			yo: "habría escalonado",
			tú: "habrías escalonado",
			Ud: "habría escalonado",
			nosotros: "habríamos escalonado",
			vosotros: "habríais escalonado",
			Uds: "habrían escalonado",
		},
		Future: {
			yo: "habré escalonado",
			tú: "habrás escalonado",
			Ud: "habrá escalonado",
			nosotros: "habremos escalonado",
			vosotros: "habréis escalonado",
			Uds: "habrán escalonado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya escalonado",
			tú: "hayas escalonado",
			Ud: "haya escalonado",
			nosotros: "hayamos escalonado",
			vosotros: "hayáis escalonado",
			Uds: "hayan escalonado",
		},
		Past: {
			yo: "hubiera escalonado",
			tú: "hubieras escalonado",
			Ud: "hubiera escalonado",
			nosotros: "hubiéramos escalonado",
			vosotros: "hubierais escalonado",
			Uds: "hubieran escalonado",
		},
		Future: {
			yo: "hubiere escalonado",
			tú: "hubieres escalonado",
			Ud: "hubiere escalonado",
			nosotros: "hubiéremos escalonado",
			vosotros: "hubiereis escalonado",
			Uds: "hubieren escalonado",
		},
	},
}
