var escamotear = {
	Indicative: {
		Present: {
			yo: "escamoteo",
			tú: "escamoteas",
			Ud: "escamotea",
			nosotros: "escamoteamos",
			vosotros: "escamoteáis",
			Uds: "escamotean",
		},
		Preterite: {
			yo: "escamoteé",
			tú: "escamoteaste",
			Ud: "escamoteó",
			nosotros: "escamoteamos",
			vosotros: "escamoteasteis",
			Uds: "escamotearon",
		},
		Imperfect: {
			yo: "escamoteaba",
			tú: "escamoteabas",
			Ud: "escamoteaba",
			nosotros: "escamoteábamos",
			vosotros: "escamoteabais",
			Uds: "escamoteaban",
		},
		Conditional: {
			yo: "escamotearía",
			tú: "escamotearías",
			Ud: "escamotearía",
			nosotros: "escamotearíamos",
			vosotros: "escamotearíais",
			Uds: "escamotearían",
		},
		Future: {
			yo: "escamotearé",
			tú: "escamotearás",
			Ud: "escamoteará",
			nosotros: "escamotearemos",
			vosotros: "escamotearéis",
			Uds: "escamotearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "escamotee",
			tú: "escamotees",
			Ud: "escamotee",
			nosotros: "escamoteemos",
			vosotros: "escamoteéis",
			Uds: "escamoteen",
		},
		Imperfect: {
			yo: "escamoteara",
			tú: "escamotearas",
			Ud: "escamoteara",
			nosotros: "escamoteáramos",
			vosotros: "escamotearais",
			Uds: "escamotearan",
		},
		Imperfect2: {
			yo: "escamotease",
			tú: "escamoteases",
			Ud: "escamotease",
			nosotros: "escamoteásemos",
			vosotros: "escamoteaseis",
			Uds: "escamoteasen",
		},
		Future: {
			yo: "escamoteare",
			tú: "escamoteares",
			Ud: "escamoteare",
			nosotros: "escamoteáremos",
			vosotros: "escamoteareis",
			Uds: "escamotearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "escamotea",
			Ud: "escamotee",
			nosotros: "escamoteemos",
			vosotros: "escamotead",
			Uds: "escamoteen",
		},
		Negative: {
			tú: "no escamotees",
			Ud: "no escamotee",
			nosotros: "no escamoteemos",
			vosotros: "no escamoteéis",
			Uds: "no escamoteen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy escamoteando",
			tú: "estás escamoteando",
			Ud: "está escamoteando",
			nosotros: "estamos escamoteando",
			vosotros: "estáis escamoteando",
			Uds: "están escamoteando",
		},
		Preterite: {
			yo: "estuve escamoteando",
			tú: "estuviste escamoteando",
			Ud: "estuvo escamoteando",
			nosotros: "estuvimos escamoteando",
			vosotros: "estuvisteis escamoteando",
			Uds: "estuvieron escamoteando",
		},
		Imperfect: {
			Uds: "estaban escamoteando",
			yo: "estaba escamoteando",
			tú: "estabas escamoteando",
			Ud: "estaba escamoteando",
			nosotros: "estábamos escamoteando",
			vosotros: "estabais escamoteando",
		},
		Conditional: {
			yo: "estaría escamoteando",
			tú: "estarías escamoteando",
			Ud: "estaría escamoteando",
			nosotros: "estaríamos escamoteando",
			vosotros: "estaríais escamoteando",
			Uds: "estarían escamoteando",
		},
		Future: {
			yo: "estaré escamoteando",
			tú: "estarás escamoteando",
			Ud: "estará escamoteando",
			nosotros: "estaremos escamoteando",
			vosotros: "estaréis escamoteando",
			Uds: "estarán escamoteando",
		},
	},
	Perfect: {
		Present: {
			yo: "he escamoteado",
			tú: "has escamoteado",
			Ud: "ha escamoteado",
			nosotros: "hemos escamoteado",
			vosotros: "habéis escamoteado",
			Uds: "han escamoteado",
		},
		Preterite: {
			yo: "hube escamoteado",
			tú: "hubiste escamoteado",
			Ud: "hubo escamoteado",
			nosotros: "hubimos escamoteado",
			vosotros: "hubisteis escamoteado",
			Uds: "hubieron escamoteado",
		},
		Past: {
			yo: "había escamoteado",
			tú: "habías escamoteado",
			Ud: "había escamoteado",
			nosotros: "habíamos escamoteado",
			vosotros: "habíais escamoteado",
			Uds: "habían escamoteado",
		},
		Conditional: {
			yo: "habría escamoteado",
			tú: "habrías escamoteado",
			Ud: "habría escamoteado",
			nosotros: "habríamos escamoteado",
			vosotros: "habríais escamoteado",
			Uds: "habrían escamoteado",
		},
		Future: {
			yo: "habré escamoteado",
			tú: "habrás escamoteado",
			Ud: "habrá escamoteado",
			nosotros: "habremos escamoteado",
			vosotros: "habréis escamoteado",
			Uds: "habrán escamoteado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya escamoteado",
			tú: "hayas escamoteado",
			Ud: "haya escamoteado",
			nosotros: "hayamos escamoteado",
			vosotros: "hayáis escamoteado",
			Uds: "hayan escamoteado",
		},
		Past: {
			yo: "hubiera escamoteado",
			tú: "hubieras escamoteado",
			Ud: "hubiera escamoteado",
			nosotros: "hubiéramos escamoteado",
			vosotros: "hubierais escamoteado",
			Uds: "hubieran escamoteado",
		},
		Future: {
			yo: "hubiere escamoteado",
			tú: "hubieres escamoteado",
			Ud: "hubiere escamoteado",
			nosotros: "hubiéremos escamoteado",
			vosotros: "hubiereis escamoteado",
			Uds: "hubieren escamoteado",
		},
	},
}
