var escampar = {
	Indicative: {
		Present: {
			yo: "escampo",
			tú: "escampas",
			Ud: "escampa",
			nosotros: "escampamos",
			vosotros: "escampáis",
			Uds: "escampan",
		},
		Preterite: {
			yo: "escampé",
			tú: "escampaste",
			Ud: "escampó",
			nosotros: "escampamos",
			vosotros: "escampasteis",
			Uds: "escamparon",
		},
		Imperfect: {
			yo: "escampaba",
			tú: "escampabas",
			Ud: "escampaba",
			nosotros: "escampábamos",
			vosotros: "escampabais",
			Uds: "escampaban",
		},
		Conditional: {
			yo: "escamparía",
			tú: "escamparías",
			Ud: "escamparía",
			nosotros: "escamparíamos",
			vosotros: "escamparíais",
			Uds: "escamparían",
		},
		Future: {
			yo: "escamparé",
			tú: "escamparás",
			Ud: "escampará",
			nosotros: "escamparemos",
			vosotros: "escamparéis",
			Uds: "escamparán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "escampe",
			tú: "escampes",
			Ud: "escampe",
			nosotros: "escampemos",
			vosotros: "escampéis",
			Uds: "escampen",
		},
		Imperfect: {
			yo: "escampara",
			tú: "escamparas",
			Ud: "escampara",
			nosotros: "escampáramos",
			vosotros: "escamparais",
			Uds: "escamparan",
		},
		Imperfect2: {
			yo: "escampase",
			tú: "escampases",
			Ud: "escampase",
			nosotros: "escampásemos",
			vosotros: "escampaseis",
			Uds: "escampasen",
		},
		Future: {
			yo: "escampare",
			tú: "escampares",
			Ud: "escampare",
			nosotros: "escampáremos",
			vosotros: "escampareis",
			Uds: "escamparen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "escampa",
			Ud: "escampe",
			nosotros: "escampemos",
			vosotros: "escampad",
			Uds: "escampen",
		},
		Negative: {
			tú: "no escampes",
			Ud: "no escampe",
			nosotros: "no escampemos",
			vosotros: "no escampéis",
			Uds: "no escampen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy escampando",
			tú: "estás escampando",
			Ud: "está escampando",
			nosotros: "estamos escampando",
			vosotros: "estáis escampando",
			Uds: "están escampando",
		},
		Preterite: {
			yo: "estuve escampando",
			tú: "estuviste escampando",
			Ud: "estuvo escampando",
			nosotros: "estuvimos escampando",
			vosotros: "estuvisteis escampando",
			Uds: "estuvieron escampando",
		},
		Imperfect: {
			Uds: "estaban escampando",
			yo: "estaba escampando",
			tú: "estabas escampando",
			Ud: "estaba escampando",
			nosotros: "estábamos escampando",
			vosotros: "estabais escampando",
		},
		Conditional: {
			yo: "estaría escampando",
			tú: "estarías escampando",
			Ud: "estaría escampando",
			nosotros: "estaríamos escampando",
			vosotros: "estaríais escampando",
			Uds: "estarían escampando",
		},
		Future: {
			yo: "estaré escampando",
			tú: "estarás escampando",
			Ud: "estará escampando",
			nosotros: "estaremos escampando",
			vosotros: "estaréis escampando",
			Uds: "estarán escampando",
		},
	},
	Perfect: {
		Present: {
			yo: "he escampado",
			tú: "has escampado",
			Ud: "ha escampado",
			nosotros: "hemos escampado",
			vosotros: "habéis escampado",
			Uds: "han escampado",
		},
		Preterite: {
			yo: "hube escampado",
			tú: "hubiste escampado",
			Ud: "hubo escampado",
			nosotros: "hubimos escampado",
			vosotros: "hubisteis escampado",
			Uds: "hubieron escampado",
		},
		Past: {
			yo: "había escampado",
			tú: "habías escampado",
			Ud: "había escampado",
			nosotros: "habíamos escampado",
			vosotros: "habíais escampado",
			Uds: "habían escampado",
		},
		Conditional: {
			yo: "habría escampado",
			tú: "habrías escampado",
			Ud: "habría escampado",
			nosotros: "habríamos escampado",
			vosotros: "habríais escampado",
			Uds: "habrían escampado",
		},
		Future: {
			yo: "habré escampado",
			tú: "habrás escampado",
			Ud: "habrá escampado",
			nosotros: "habremos escampado",
			vosotros: "habréis escampado",
			Uds: "habrán escampado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya escampado",
			tú: "hayas escampado",
			Ud: "haya escampado",
			nosotros: "hayamos escampado",
			vosotros: "hayáis escampado",
			Uds: "hayan escampado",
		},
		Past: {
			yo: "hubiera escampado",
			tú: "hubieras escampado",
			Ud: "hubiera escampado",
			nosotros: "hubiéramos escampado",
			vosotros: "hubierais escampado",
			Uds: "hubieran escampado",
		},
		Future: {
			yo: "hubiere escampado",
			tú: "hubieres escampado",
			Ud: "hubiere escampado",
			nosotros: "hubiéremos escampado",
			vosotros: "hubiereis escampado",
			Uds: "hubieren escampado",
		},
	},
}
