var escandir = {
	Indicative: {
		Present: {
			yo: "escando",
			tú: "escandes",
			Ud: "escande",
			nosotros: "escandimos",
			vosotros: "escandís",
			Uds: "escanden",
		},
		Preterite: {
			yo: "escandí",
			tú: "escandiste",
			Ud: "escandió",
			nosotros: "escandimos",
			vosotros: "escandisteis",
			Uds: "escandieron",
		},
		Imperfect: {
			yo: "escandía",
			tú: "escandías",
			Ud: "escandía",
			nosotros: "escandíamos",
			vosotros: "escandíais",
			Uds: "escandían",
		},
		Conditional: {
			yo: "escandiría",
			tú: "escandirías",
			Ud: "escandiría",
			nosotros: "escandiríamos",
			vosotros: "escandiríais",
			Uds: "escandirían",
		},
		Future: {
			yo: "escandiré",
			tú: "escandirás",
			Ud: "escandirá",
			nosotros: "escandiremos",
			vosotros: "escandiréis",
			Uds: "escandirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "escanda",
			tú: "escandas",
			Ud: "escanda",
			nosotros: "escandamos",
			vosotros: "escandáis",
			Uds: "escandan",
		},
		Imperfect: {
			yo: "escandiera",
			tú: "escandieras",
			Ud: "escandiera",
			nosotros: "escandiéramos",
			vosotros: "escandierais",
			Uds: "escandieran",
		},
		Imperfect2: {
			yo: "escandiese",
			tú: "escandieses",
			Ud: "escandiese",
			nosotros: "escandiésemos",
			vosotros: "escandieseis",
			Uds: "escandiesen",
		},
		Future: {
			yo: "escandiere",
			tú: "escandieres",
			Ud: "escandiere",
			nosotros: "escandiéremos",
			vosotros: "escandiereis",
			Uds: "escandieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "escande",
			Ud: "escanda",
			nosotros: "escandamos",
			vosotros: "escandid",
			Uds: "escandan",
		},
		Negative: {
			tú: "no escandas",
			Ud: "no escanda",
			nosotros: "no escandamos",
			vosotros: "no escandáis",
			Uds: "no escandan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy escandiendo",
			tú: "estás escandiendo",
			Ud: "está escandiendo",
			nosotros: "estamos escandiendo",
			vosotros: "estáis escandiendo",
			Uds: "están escandiendo",
		},
		Preterite: {
			yo: "estuve escandiendo",
			tú: "estuviste escandiendo",
			Ud: "estuvo escandiendo",
			nosotros: "estuvimos escandiendo",
			vosotros: "estuvisteis escandiendo",
			Uds: "estuvieron escandiendo",
		},
		Imperfect: {
			Uds: "estaban escandiendo",
			yo: "estaba escandiendo",
			tú: "estabas escandiendo",
			Ud: "estaba escandiendo",
			nosotros: "estábamos escandiendo",
			vosotros: "estabais escandiendo",
		},
		Conditional: {
			yo: "estaría escandiendo",
			tú: "estarías escandiendo",
			Ud: "estaría escandiendo",
			nosotros: "estaríamos escandiendo",
			vosotros: "estaríais escandiendo",
			Uds: "estarían escandiendo",
		},
		Future: {
			yo: "estaré escandiendo",
			tú: "estarás escandiendo",
			Ud: "estará escandiendo",
			nosotros: "estaremos escandiendo",
			vosotros: "estaréis escandiendo",
			Uds: "estarán escandiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he escandido",
			tú: "has escandido",
			Ud: "ha escandido",
			nosotros: "hemos escandido",
			vosotros: "habéis escandido",
			Uds: "han escandido",
		},
		Preterite: {
			yo: "hube escandido",
			tú: "hubiste escandido",
			Ud: "hubo escandido",
			nosotros: "hubimos escandido",
			vosotros: "hubisteis escandido",
			Uds: "hubieron escandido",
		},
		Past: {
			yo: "había escandido",
			tú: "habías escandido",
			Ud: "había escandido",
			nosotros: "habíamos escandido",
			vosotros: "habíais escandido",
			Uds: "habían escandido",
		},
		Conditional: {
			yo: "habría escandido",
			tú: "habrías escandido",
			Ud: "habría escandido",
			nosotros: "habríamos escandido",
			vosotros: "habríais escandido",
			Uds: "habrían escandido",
		},
		Future: {
			yo: "habré escandido",
			tú: "habrás escandido",
			Ud: "habrá escandido",
			nosotros: "habremos escandido",
			vosotros: "habréis escandido",
			Uds: "habrán escandido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya escandido",
			tú: "hayas escandido",
			Ud: "haya escandido",
			nosotros: "hayamos escandido",
			vosotros: "hayáis escandido",
			Uds: "hayan escandido",
		},
		Past: {
			yo: "hubiera escandido",
			tú: "hubieras escandido",
			Ud: "hubiera escandido",
			nosotros: "hubiéramos escandido",
			vosotros: "hubierais escandido",
			Uds: "hubieran escandido",
		},
		Future: {
			yo: "hubiere escandido",
			tú: "hubieres escandido",
			Ud: "hubiere escandido",
			nosotros: "hubiéremos escandido",
			vosotros: "hubiereis escandido",
			Uds: "hubieren escandido",
		},
	},
}
