var escapar = {
	Indicative: {
		Present: {
			yo: "escapo",
			tú: "escapas",
			Ud: "escapa",
			nosotros: "escapamos",
			vosotros: "escapáis",
			Uds: "escapan",
		},
		Preterite: {
			yo: "escapé",
			tú: "escapaste",
			Ud: "escapó",
			nosotros: "escapamos",
			vosotros: "escapasteis",
			Uds: "escaparon",
		},
		Imperfect: {
			yo: "escapaba",
			tú: "escapabas",
			Ud: "escapaba",
			nosotros: "escapábamos",
			vosotros: "escapabais",
			Uds: "escapaban",
		},
		Conditional: {
			yo: "escaparía",
			tú: "escaparías",
			Ud: "escaparía",
			nosotros: "escaparíamos",
			vosotros: "escaparíais",
			Uds: "escaparían",
		},
		Future: {
			yo: "escaparé",
			tú: "escaparás",
			Ud: "escapará",
			nosotros: "escaparemos",
			vosotros: "escaparéis",
			Uds: "escaparán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "escape",
			tú: "escapes",
			Ud: "escape",
			nosotros: "escapemos",
			vosotros: "escapéis",
			Uds: "escapen",
		},
		Imperfect: {
			yo: "escapara",
			tú: "escaparas",
			Ud: "escapara",
			nosotros: "escapáramos",
			vosotros: "escaparais",
			Uds: "escaparan",
		},
		Imperfect2: {
			yo: "escapase",
			tú: "escapases",
			Ud: "escapase",
			nosotros: "escapásemos",
			vosotros: "escapaseis",
			Uds: "escapasen",
		},
		Future: {
			yo: "escapare",
			tú: "escapares",
			Ud: "escapare",
			nosotros: "escapáremos",
			vosotros: "escapareis",
			Uds: "escaparen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "escapa",
			Ud: "escape",
			nosotros: "escapemos",
			vosotros: "escapad",
			Uds: "escapen",
		},
		Negative: {
			tú: "no escapes",
			Ud: "no escape",
			nosotros: "no escapemos",
			vosotros: "no escapéis",
			Uds: "no escapen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy escapando",
			tú: "estás escapando",
			Ud: "está escapando",
			nosotros: "estamos escapando",
			vosotros: "estáis escapando",
			Uds: "están escapando",
		},
		Preterite: {
			yo: "estuve escapando",
			tú: "estuviste escapando",
			Ud: "estuvo escapando",
			nosotros: "estuvimos escapando",
			vosotros: "estuvisteis escapando",
			Uds: "estuvieron escapando",
		},
		Imperfect: {
			Uds: "estaban escapando",
			yo: "estaba escapando",
			tú: "estabas escapando",
			Ud: "estaba escapando",
			nosotros: "estábamos escapando",
			vosotros: "estabais escapando",
		},
		Conditional: {
			yo: "estaría escapando",
			tú: "estarías escapando",
			Ud: "estaría escapando",
			nosotros: "estaríamos escapando",
			vosotros: "estaríais escapando",
			Uds: "estarían escapando",
		},
		Future: {
			yo: "estaré escapando",
			tú: "estarás escapando",
			Ud: "estará escapando",
			nosotros: "estaremos escapando",
			vosotros: "estaréis escapando",
			Uds: "estarán escapando",
		},
	},
	Perfect: {
		Present: {
			yo: "he escapado",
			tú: "has escapado",
			Ud: "ha escapado",
			nosotros: "hemos escapado",
			vosotros: "habéis escapado",
			Uds: "han escapado",
		},
		Preterite: {
			yo: "hube escapado",
			tú: "hubiste escapado",
			Ud: "hubo escapado",
			nosotros: "hubimos escapado",
			vosotros: "hubisteis escapado",
			Uds: "hubieron escapado",
		},
		Past: {
			yo: "había escapado",
			tú: "habías escapado",
			Ud: "había escapado",
			nosotros: "habíamos escapado",
			vosotros: "habíais escapado",
			Uds: "habían escapado",
		},
		Conditional: {
			yo: "habría escapado",
			tú: "habrías escapado",
			Ud: "habría escapado",
			nosotros: "habríamos escapado",
			vosotros: "habríais escapado",
			Uds: "habrían escapado",
		},
		Future: {
			yo: "habré escapado",
			tú: "habrás escapado",
			Ud: "habrá escapado",
			nosotros: "habremos escapado",
			vosotros: "habréis escapado",
			Uds: "habrán escapado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya escapado",
			tú: "hayas escapado",
			Ud: "haya escapado",
			nosotros: "hayamos escapado",
			vosotros: "hayáis escapado",
			Uds: "hayan escapado",
		},
		Past: {
			yo: "hubiera escapado",
			tú: "hubieras escapado",
			Ud: "hubiera escapado",
			nosotros: "hubiéramos escapado",
			vosotros: "hubierais escapado",
			Uds: "hubieran escapado",
		},
		Future: {
			yo: "hubiere escapado",
			tú: "hubieres escapado",
			Ud: "hubiere escapado",
			nosotros: "hubiéremos escapado",
			vosotros: "hubiereis escapado",
			Uds: "hubieren escapado",
		},
	},
}
