var escalar = {
	Indicative: {
		Present: {
			yo: "escalo",
			tú: "escalas",
			Ud: "escala",
			nosotros: "escalamos",
			vosotros: "escaláis",
			Uds: "escalan",
		},
		Preterite: {
			yo: "escalé",
			tú: "escalaste",
			Ud: "escaló",
			nosotros: "escalamos",
			vosotros: "escalasteis",
			Uds: "escalaron",
		},
		Imperfect: {
			yo: "escalaba",
			tú: "escalabas",
			Ud: "escalaba",
			nosotros: "escalábamos",
			vosotros: "escalabais",
			Uds: "escalaban",
		},
		Conditional: {
			yo: "escalaría",
			tú: "escalarías",
			Ud: "escalaría",
			nosotros: "escalaríamos",
			vosotros: "escalaríais",
			Uds: "escalarían",
		},
		Future: {
			yo: "escalaré",
			tú: "escalarás",
			Ud: "escalará",
			nosotros: "escalaremos",
			vosotros: "escalaréis",
			Uds: "escalarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "escale",
			tú: "escales",
			Ud: "escale",
			nosotros: "escalemos",
			vosotros: "escaléis",
			Uds: "escalen",
		},
		Imperfect: {
			yo: "escalara",
			tú: "escalaras",
			Ud: "escalara",
			nosotros: "escaláramos",
			vosotros: "escalarais",
			Uds: "escalaran",
		},
		Imperfect2: {
			yo: "escalase",
			tú: "escalases",
			Ud: "escalase",
			nosotros: "escalásemos",
			vosotros: "escalaseis",
			Uds: "escalasen",
		},
		Future: {
			yo: "escalare",
			tú: "escalares",
			Ud: "escalare",
			nosotros: "escaláremos",
			vosotros: "escalareis",
			Uds: "escalaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "escala",
			Ud: "escale",
			nosotros: "escalemos",
			vosotros: "escalad",
			Uds: "escalen",
		},
		Negative: {
			tú: "no escales",
			Ud: "no escale",
			nosotros: "no escalemos",
			vosotros: "no escaléis",
			Uds: "no escalen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy escalando",
			tú: "estás escalando",
			Ud: "está escalando",
			nosotros: "estamos escalando",
			vosotros: "estáis escalando",
			Uds: "están escalando",
		},
		Preterite: {
			yo: "estuve escalando",
			tú: "estuviste escalando",
			Ud: "estuvo escalando",
			nosotros: "estuvimos escalando",
			vosotros: "estuvisteis escalando",
			Uds: "estuvieron escalando",
		},
		Imperfect: {
			Uds: "estaban escalando",
			yo: "estaba escalando",
			tú: "estabas escalando",
			Ud: "estaba escalando",
			nosotros: "estábamos escalando",
			vosotros: "estabais escalando",
		},
		Conditional: {
			yo: "estaría escalando",
			tú: "estarías escalando",
			Ud: "estaría escalando",
			nosotros: "estaríamos escalando",
			vosotros: "estaríais escalando",
			Uds: "estarían escalando",
		},
		Future: {
			yo: "estaré escalando",
			tú: "estarás escalando",
			Ud: "estará escalando",
			nosotros: "estaremos escalando",
			vosotros: "estaréis escalando",
			Uds: "estarán escalando",
		},
	},
	Perfect: {
		Present: {
			yo: "he escalado",
			tú: "has escalado",
			Ud: "ha escalado",
			nosotros: "hemos escalado",
			vosotros: "habéis escalado",
			Uds: "han escalado",
		},
		Preterite: {
			yo: "hube escalado",
			tú: "hubiste escalado",
			Ud: "hubo escalado",
			nosotros: "hubimos escalado",
			vosotros: "hubisteis escalado",
			Uds: "hubieron escalado",
		},
		Past: {
			yo: "había escalado",
			tú: "habías escalado",
			Ud: "había escalado",
			nosotros: "habíamos escalado",
			vosotros: "habíais escalado",
			Uds: "habían escalado",
		},
		Conditional: {
			yo: "habría escalado",
			tú: "habrías escalado",
			Ud: "habría escalado",
			nosotros: "habríamos escalado",
			vosotros: "habríais escalado",
			Uds: "habrían escalado",
		},
		Future: {
			yo: "habré escalado",
			tú: "habrás escalado",
			Ud: "habrá escalado",
			nosotros: "habremos escalado",
			vosotros: "habréis escalado",
			Uds: "habrán escalado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya escalado",
			tú: "hayas escalado",
			Ud: "haya escalado",
			nosotros: "hayamos escalado",
			vosotros: "hayáis escalado",
			Uds: "hayan escalado",
		},
		Past: {
			yo: "hubiera escalado",
			tú: "hubieras escalado",
			Ud: "hubiera escalado",
			nosotros: "hubiéramos escalado",
			vosotros: "hubierais escalado",
			Uds: "hubieran escalado",
		},
		Future: {
			yo: "hubiere escalado",
			tú: "hubieres escalado",
			Ud: "hubiere escalado",
			nosotros: "hubiéremos escalado",
			vosotros: "hubiereis escalado",
			Uds: "hubieren escalado",
		},
	},
}
