var escoger = {
	Indicative: {
		Present: {
			yo: "escojo",
			tú: "escoges",
			Ud: "escoge",
			nosotros: "escogemos",
			vosotros: "escogéis",
			Uds: "escogen",
		},
		Preterite: {
			yo: "escogí",
			tú: "escogiste",
			Ud: "escogió",
			nosotros: "escogimos",
			vosotros: "escogisteis",
			Uds: "escogieron",
		},
		Imperfect: {
			yo: "escogía",
			tú: "escogías",
			Ud: "escogía",
			nosotros: "escogíamos",
			vosotros: "escogíais",
			Uds: "escogían",
		},
		Conditional: {
			yo: "escogería",
			tú: "escogerías",
			Ud: "escogería",
			nosotros: "escogeríamos",
			vosotros: "escogeríais",
			Uds: "escogerían",
		},
		Future: {
			yo: "escogeré",
			tú: "escogerás",
			Ud: "escogerá",
			nosotros: "escogeremos",
			vosotros: "escogeréis",
			Uds: "escogerán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "escoja",
			tú: "escojas",
			Ud: "escoja",
			nosotros: "escojamos",
			vosotros: "escojáis",
			Uds: "escojan",
		},
		Imperfect: {
			yo: "escogiera",
			tú: "escogieras",
			Ud: "escogiera",
			nosotros: "escogiéramos",
			vosotros: "escogierais",
			Uds: "escogieran",
		},
		Imperfect2: {
			yo: "escogiese",
			tú: "escogieses",
			Ud: "escogiese",
			nosotros: "escogiésemos",
			vosotros: "escogieseis",
			Uds: "escogiesen",
		},
		Future: {
			yo: "escogiere",
			tú: "escogieres",
			Ud: "escogiere",
			nosotros: "escogiéremos",
			vosotros: "escogiereis",
			Uds: "escogieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "escoge",
			Ud: "escoja",
			nosotros: "escojamos",
			vosotros: "escoged",
			Uds: "escojan",
		},
		Negative: {
			tú: "no escojas",
			Ud: "no escoja",
			nosotros: "no escojamos",
			vosotros: "no escojáis",
			Uds: "no escojan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy escogiendo",
			tú: "estás escogiendo",
			Ud: "está escogiendo",
			nosotros: "estamos escogiendo",
			vosotros: "estáis escogiendo",
			Uds: "están escogiendo",
		},
		Preterite: {
			yo: "estuve escogiendo",
			tú: "estuviste escogiendo",
			Ud: "estuvo escogiendo",
			nosotros: "estuvimos escogiendo",
			vosotros: "estuvisteis escogiendo",
			Uds: "estuvieron escogiendo",
		},
		Imperfect: {
			Uds: "estaban escogiendo",
			yo: "estaba escogiendo",
			tú: "estabas escogiendo",
			Ud: "estaba escogiendo",
			nosotros: "estábamos escogiendo",
			vosotros: "estabais escogiendo",
		},
		Conditional: {
			yo: "estaría escogiendo",
			tú: "estarías escogiendo",
			Ud: "estaría escogiendo",
			nosotros: "estaríamos escogiendo",
			vosotros: "estaríais escogiendo",
			Uds: "estarían escogiendo",
		},
		Future: {
			yo: "estaré escogiendo",
			tú: "estarás escogiendo",
			Ud: "estará escogiendo",
			nosotros: "estaremos escogiendo",
			vosotros: "estaréis escogiendo",
			Uds: "estarán escogiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he escogido",
			tú: "has escogido",
			Ud: "ha escogido",
			nosotros: "hemos escogido",
			vosotros: "habéis escogido",
			Uds: "han escogido",
		},
		Preterite: {
			yo: "hube escogido",
			tú: "hubiste escogido",
			Ud: "hubo escogido",
			nosotros: "hubimos escogido",
			vosotros: "hubisteis escogido",
			Uds: "hubieron escogido",
		},
		Past: {
			yo: "había escogido",
			tú: "habías escogido",
			Ud: "había escogido",
			nosotros: "habíamos escogido",
			vosotros: "habíais escogido",
			Uds: "habían escogido",
		},
		Conditional: {
			yo: "habría escogido",
			tú: "habrías escogido",
			Ud: "habría escogido",
			nosotros: "habríamos escogido",
			vosotros: "habríais escogido",
			Uds: "habrían escogido",
		},
		Future: {
			yo: "habré escogido",
			tú: "habrás escogido",
			Ud: "habrá escogido",
			nosotros: "habremos escogido",
			vosotros: "habréis escogido",
			Uds: "habrán escogido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya escogido",
			tú: "hayas escogido",
			Ud: "haya escogido",
			nosotros: "hayamos escogido",
			vosotros: "hayáis escogido",
			Uds: "hayan escogido",
		},
		Past: {
			yo: "hubiera escogido",
			tú: "hubieras escogido",
			Ud: "hubiera escogido",
			nosotros: "hubiéramos escogido",
			vosotros: "hubierais escogido",
			Uds: "hubieran escogido",
		},
		Future: {
			yo: "hubiere escogido",
			tú: "hubieres escogido",
			Ud: "hubiere escogido",
			nosotros: "hubiéremos escogido",
			vosotros: "hubiereis escogido",
			Uds: "hubieren escogido",
		},
	},
}
