var escoltar = {
	Indicative: {
		Present: {
			yo: "escolto",
			tú: "escoltas",
			Ud: "escolta",
			nosotros: "escoltamos",
			vosotros: "escoltáis",
			Uds: "escoltan",
		},
		Preterite: {
			yo: "escolté",
			tú: "escoltaste",
			Ud: "escoltó",
			nosotros: "escoltamos",
			vosotros: "escoltasteis",
			Uds: "escoltaron",
		},
		Imperfect: {
			yo: "escoltaba",
			tú: "escoltabas",
			Ud: "escoltaba",
			nosotros: "escoltábamos",
			vosotros: "escoltabais",
			Uds: "escoltaban",
		},
		Conditional: {
			yo: "escoltaría",
			tú: "escoltarías",
			Ud: "escoltaría",
			nosotros: "escoltaríamos",
			vosotros: "escoltaríais",
			Uds: "escoltarían",
		},
		Future: {
			yo: "escoltaré",
			tú: "escoltarás",
			Ud: "escoltará",
			nosotros: "escoltaremos",
			vosotros: "escoltaréis",
			Uds: "escoltarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "escolte",
			tú: "escoltes",
			Ud: "escolte",
			nosotros: "escoltemos",
			vosotros: "escoltéis",
			Uds: "escolten",
		},
		Imperfect: {
			yo: "escoltara",
			tú: "escoltaras",
			Ud: "escoltara",
			nosotros: "escoltáramos",
			vosotros: "escoltarais",
			Uds: "escoltaran",
		},
		Imperfect2: {
			yo: "escoltase",
			tú: "escoltases",
			Ud: "escoltase",
			nosotros: "escoltásemos",
			vosotros: "escoltaseis",
			Uds: "escoltasen",
		},
		Future: {
			yo: "escoltare",
			tú: "escoltares",
			Ud: "escoltare",
			nosotros: "escoltáremos",
			vosotros: "escoltareis",
			Uds: "escoltaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "escolta",
			Ud: "escolte",
			nosotros: "escoltemos",
			vosotros: "escoltad",
			Uds: "escolten",
		},
		Negative: {
			tú: "no escoltes",
			Ud: "no escolte",
			nosotros: "no escoltemos",
			vosotros: "no escoltéis",
			Uds: "no escolten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy escoltando",
			tú: "estás escoltando",
			Ud: "está escoltando",
			nosotros: "estamos escoltando",
			vosotros: "estáis escoltando",
			Uds: "están escoltando",
		},
		Preterite: {
			yo: "estuve escoltando",
			tú: "estuviste escoltando",
			Ud: "estuvo escoltando",
			nosotros: "estuvimos escoltando",
			vosotros: "estuvisteis escoltando",
			Uds: "estuvieron escoltando",
		},
		Imperfect: {
			Uds: "estaban escoltando",
			yo: "estaba escoltando",
			tú: "estabas escoltando",
			Ud: "estaba escoltando",
			nosotros: "estábamos escoltando",
			vosotros: "estabais escoltando",
		},
		Conditional: {
			yo: "estaría escoltando",
			tú: "estarías escoltando",
			Ud: "estaría escoltando",
			nosotros: "estaríamos escoltando",
			vosotros: "estaríais escoltando",
			Uds: "estarían escoltando",
		},
		Future: {
			yo: "estaré escoltando",
			tú: "estarás escoltando",
			Ud: "estará escoltando",
			nosotros: "estaremos escoltando",
			vosotros: "estaréis escoltando",
			Uds: "estarán escoltando",
		},
	},
	Perfect: {
		Present: {
			yo: "he escoltado",
			tú: "has escoltado",
			Ud: "ha escoltado",
			nosotros: "hemos escoltado",
			vosotros: "habéis escoltado",
			Uds: "han escoltado",
		},
		Preterite: {
			yo: "hube escoltado",
			tú: "hubiste escoltado",
			Ud: "hubo escoltado",
			nosotros: "hubimos escoltado",
			vosotros: "hubisteis escoltado",
			Uds: "hubieron escoltado",
		},
		Past: {
			yo: "había escoltado",
			tú: "habías escoltado",
			Ud: "había escoltado",
			nosotros: "habíamos escoltado",
			vosotros: "habíais escoltado",
			Uds: "habían escoltado",
		},
		Conditional: {
			yo: "habría escoltado",
			tú: "habrías escoltado",
			Ud: "habría escoltado",
			nosotros: "habríamos escoltado",
			vosotros: "habríais escoltado",
			Uds: "habrían escoltado",
		},
		Future: {
			yo: "habré escoltado",
			tú: "habrás escoltado",
			Ud: "habrá escoltado",
			nosotros: "habremos escoltado",
			vosotros: "habréis escoltado",
			Uds: "habrán escoltado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya escoltado",
			tú: "hayas escoltado",
			Ud: "haya escoltado",
			nosotros: "hayamos escoltado",
			vosotros: "hayáis escoltado",
			Uds: "hayan escoltado",
		},
		Past: {
			yo: "hubiera escoltado",
			tú: "hubieras escoltado",
			Ud: "hubiera escoltado",
			nosotros: "hubiéramos escoltado",
			vosotros: "hubierais escoltado",
			Uds: "hubieran escoltado",
		},
		Future: {
			yo: "hubiere escoltado",
			tú: "hubieres escoltado",
			Ud: "hubiere escoltado",
			nosotros: "hubiéremos escoltado",
			vosotros: "hubiereis escoltado",
			Uds: "hubieren escoltado",
		},
	},
}
