var escurrir = {
	Indicative: {
		Present: {
			yo: "escurro",
			tú: "escurres",
			Ud: "escurre",
			nosotros: "escurrimos",
			vosotros: "escurrís",
			Uds: "escurren",
		},
		Preterite: {
			yo: "escurrí",
			tú: "escurriste",
			Ud: "escurrió",
			nosotros: "escurrimos",
			vosotros: "escurristeis",
			Uds: "escurrieron",
		},
		Imperfect: {
			yo: "escurría",
			tú: "escurrías",
			Ud: "escurría",
			nosotros: "escurríamos",
			vosotros: "escurríais",
			Uds: "escurrían",
		},
		Conditional: {
			yo: "escurriría",
			tú: "escurrirías",
			Ud: "escurriría",
			nosotros: "escurriríamos",
			vosotros: "escurriríais",
			Uds: "escurrirían",
		},
		Future: {
			yo: "escurriré",
			tú: "escurrirás",
			Ud: "escurrirá",
			nosotros: "escurriremos",
			vosotros: "escurriréis",
			Uds: "escurrirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "escurra",
			tú: "escurras",
			Ud: "escurra",
			nosotros: "escurramos",
			vosotros: "escurráis",
			Uds: "escurran",
		},
		Imperfect: {
			yo: "escurriera",
			tú: "escurrieras",
			Ud: "escurriera",
			nosotros: "escurriéramos",
			vosotros: "escurrierais",
			Uds: "escurrieran",
		},
		Imperfect2: {
			yo: "escurriese",
			tú: "escurrieses",
			Ud: "escurriese",
			nosotros: "escurriésemos",
			vosotros: "escurrieseis",
			Uds: "escurriesen",
		},
		Future: {
			yo: "escurriere",
			tú: "escurrieres",
			Ud: "escurriere",
			nosotros: "escurriéremos",
			vosotros: "escurriereis",
			Uds: "escurrieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "escurre",
			Ud: "escurra",
			nosotros: "escurramos",
			vosotros: "escurrid",
			Uds: "escurran",
		},
		Negative: {
			tú: "no escurras",
			Ud: "no escurra",
			nosotros: "no escurramos",
			vosotros: "no escurráis",
			Uds: "no escurran",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy escurriendo",
			tú: "estás escurriendo",
			Ud: "está escurriendo",
			nosotros: "estamos escurriendo",
			vosotros: "estáis escurriendo",
			Uds: "están escurriendo",
		},
		Preterite: {
			yo: "estuve escurriendo",
			tú: "estuviste escurriendo",
			Ud: "estuvo escurriendo",
			nosotros: "estuvimos escurriendo",
			vosotros: "estuvisteis escurriendo",
			Uds: "estuvieron escurriendo",
		},
		Imperfect: {
			Uds: "estaban escurriendo",
			yo: "estaba escurriendo",
			tú: "estabas escurriendo",
			Ud: "estaba escurriendo",
			nosotros: "estábamos escurriendo",
			vosotros: "estabais escurriendo",
		},
		Conditional: {
			yo: "estaría escurriendo",
			tú: "estarías escurriendo",
			Ud: "estaría escurriendo",
			nosotros: "estaríamos escurriendo",
			vosotros: "estaríais escurriendo",
			Uds: "estarían escurriendo",
		},
		Future: {
			yo: "estaré escurriendo",
			tú: "estarás escurriendo",
			Ud: "estará escurriendo",
			nosotros: "estaremos escurriendo",
			vosotros: "estaréis escurriendo",
			Uds: "estarán escurriendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he escurrido",
			tú: "has escurrido",
			Ud: "ha escurrido",
			nosotros: "hemos escurrido",
			vosotros: "habéis escurrido",
			Uds: "han escurrido",
		},
		Preterite: {
			yo: "hube escurrido",
			tú: "hubiste escurrido",
			Ud: "hubo escurrido",
			nosotros: "hubimos escurrido",
			vosotros: "hubisteis escurrido",
			Uds: "hubieron escurrido",
		},
		Past: {
			yo: "había escurrido",
			tú: "habías escurrido",
			Ud: "había escurrido",
			nosotros: "habíamos escurrido",
			vosotros: "habíais escurrido",
			Uds: "habían escurrido",
		},
		Conditional: {
			yo: "habría escurrido",
			tú: "habrías escurrido",
			Ud: "habría escurrido",
			nosotros: "habríamos escurrido",
			vosotros: "habríais escurrido",
			Uds: "habrían escurrido",
		},
		Future: {
			yo: "habré escurrido",
			tú: "habrás escurrido",
			Ud: "habrá escurrido",
			nosotros: "habremos escurrido",
			vosotros: "habréis escurrido",
			Uds: "habrán escurrido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya escurrido",
			tú: "hayas escurrido",
			Ud: "haya escurrido",
			nosotros: "hayamos escurrido",
			vosotros: "hayáis escurrido",
			Uds: "hayan escurrido",
		},
		Past: {
			yo: "hubiera escurrido",
			tú: "hubieras escurrido",
			Ud: "hubiera escurrido",
			nosotros: "hubiéramos escurrido",
			vosotros: "hubierais escurrido",
			Uds: "hubieran escurrido",
		},
		Future: {
			yo: "hubiere escurrido",
			tú: "hubieres escurrido",
			Ud: "hubiere escurrido",
			nosotros: "hubiéremos escurrido",
			vosotros: "hubiereis escurrido",
			Uds: "hubieren escurrido",
		},
	},
}
