var espetar = {
	Indicative: {
		Present: {
			yo: "espeto",
			tú: "espetas",
			Ud: "espeta",
			nosotros: "espetamos",
			vosotros: "espetáis",
			Uds: "espetan",
		},
		Preterite: {
			yo: "espeté",
			tú: "espetaste",
			Ud: "espetó",
			nosotros: "espetamos",
			vosotros: "espetasteis",
			Uds: "espetaron",
		},
		Imperfect: {
			yo: "espetaba",
			tú: "espetabas",
			Ud: "espetaba",
			nosotros: "espetábamos",
			vosotros: "espetabais",
			Uds: "espetaban",
		},
		Conditional: {
			yo: "espetaría",
			tú: "espetarías",
			Ud: "espetaría",
			nosotros: "espetaríamos",
			vosotros: "espetaríais",
			Uds: "espetarían",
		},
		Future: {
			yo: "espetaré",
			tú: "espetarás",
			Ud: "espetará",
			nosotros: "espetaremos",
			vosotros: "espetaréis",
			Uds: "espetarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "espete",
			tú: "espetes",
			Ud: "espete",
			nosotros: "espetemos",
			vosotros: "espetéis",
			Uds: "espeten",
		},
		Imperfect: {
			yo: "espetara",
			tú: "espetaras",
			Ud: "espetara",
			nosotros: "espetáramos",
			vosotros: "espetarais",
			Uds: "espetaran",
		},
		Imperfect2: {
			yo: "espetase",
			tú: "espetases",
			Ud: "espetase",
			nosotros: "espetásemos",
			vosotros: "espetaseis",
			Uds: "espetasen",
		},
		Future: {
			yo: "espetare",
			tú: "espetares",
			Ud: "espetare",
			nosotros: "espetáremos",
			vosotros: "espetareis",
			Uds: "espetaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "espeta",
			Ud: "espete",
			nosotros: "espetemos",
			vosotros: "espetad",
			Uds: "espeten",
		},
		Negative: {
			tú: "no espetes",
			Ud: "no espete",
			nosotros: "no espetemos",
			vosotros: "no espetéis",
			Uds: "no espeten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy espetando",
			tú: "estás espetando",
			Ud: "está espetando",
			nosotros: "estamos espetando",
			vosotros: "estáis espetando",
			Uds: "están espetando",
		},
		Preterite: {
			yo: "estuve espetando",
			tú: "estuviste espetando",
			Ud: "estuvo espetando",
			nosotros: "estuvimos espetando",
			vosotros: "estuvisteis espetando",
			Uds: "estuvieron espetando",
		},
		Imperfect: {
			Uds: "estaban espetando",
			yo: "estaba espetando",
			tú: "estabas espetando",
			Ud: "estaba espetando",
			nosotros: "estábamos espetando",
			vosotros: "estabais espetando",
		},
		Conditional: {
			yo: "estaría espetando",
			tú: "estarías espetando",
			Ud: "estaría espetando",
			nosotros: "estaríamos espetando",
			vosotros: "estaríais espetando",
			Uds: "estarían espetando",
		},
		Future: {
			yo: "estaré espetando",
			tú: "estarás espetando",
			Ud: "estará espetando",
			nosotros: "estaremos espetando",
			vosotros: "estaréis espetando",
			Uds: "estarán espetando",
		},
	},
	Perfect: {
		Present: {
			yo: "he espetado",
			tú: "has espetado",
			Ud: "ha espetado",
			nosotros: "hemos espetado",
			vosotros: "habéis espetado",
			Uds: "han espetado",
		},
		Preterite: {
			yo: "hube espetado",
			tú: "hubiste espetado",
			Ud: "hubo espetado",
			nosotros: "hubimos espetado",
			vosotros: "hubisteis espetado",
			Uds: "hubieron espetado",
		},
		Past: {
			yo: "había espetado",
			tú: "habías espetado",
			Ud: "había espetado",
			nosotros: "habíamos espetado",
			vosotros: "habíais espetado",
			Uds: "habían espetado",
		},
		Conditional: {
			yo: "habría espetado",
			tú: "habrías espetado",
			Ud: "habría espetado",
			nosotros: "habríamos espetado",
			vosotros: "habríais espetado",
			Uds: "habrían espetado",
		},
		Future: {
			yo: "habré espetado",
			tú: "habrás espetado",
			Ud: "habrá espetado",
			nosotros: "habremos espetado",
			vosotros: "habréis espetado",
			Uds: "habrán espetado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya espetado",
			tú: "hayas espetado",
			Ud: "haya espetado",
			nosotros: "hayamos espetado",
			vosotros: "hayáis espetado",
			Uds: "hayan espetado",
		},
		Past: {
			yo: "hubiera espetado",
			tú: "hubieras espetado",
			Ud: "hubiera espetado",
			nosotros: "hubiéramos espetado",
			vosotros: "hubierais espetado",
			Uds: "hubieran espetado",
		},
		Future: {
			yo: "hubiere espetado",
			tú: "hubieres espetado",
			Ud: "hubiere espetado",
			nosotros: "hubiéremos espetado",
			vosotros: "hubiereis espetado",
			Uds: "hubieren espetado",
		},
	},
}
