var esperar = {
	Indicative: {
		Present: {
			yo: "espero",
			tú: "esperas",
			Ud: "espera",
			nosotros: "esperamos",
			vosotros: "esperáis",
			Uds: "esperan",
		},
		Preterite: {
			yo: "esperé",
			tú: "esperaste",
			Ud: "esperó",
			nosotros: "esperamos",
			vosotros: "esperasteis",
			Uds: "esperaron",
		},
		Imperfect: {
			yo: "esperaba",
			tú: "esperabas",
			Ud: "esperaba",
			nosotros: "esperábamos",
			vosotros: "esperabais",
			Uds: "esperaban",
		},
		Conditional: {
			yo: "esperaría",
			tú: "esperarías",
			Ud: "esperaría",
			nosotros: "esperaríamos",
			vosotros: "esperaríais",
			Uds: "esperarían",
		},
		Future: {
			yo: "esperaré",
			tú: "esperarás",
			Ud: "esperará",
			nosotros: "esperaremos",
			vosotros: "esperaréis",
			Uds: "esperarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "espere",
			tú: "esperes",
			Ud: "espere",
			nosotros: "esperemos",
			vosotros: "esperéis",
			Uds: "esperen",
		},
		Imperfect: {
			yo: "esperara",
			tú: "esperaras",
			Ud: "esperara",
			nosotros: "esperáramos",
			vosotros: "esperarais",
			Uds: "esperaran",
		},
		Imperfect2: {
			yo: "esperase",
			tú: "esperases",
			Ud: "esperase",
			nosotros: "esperásemos",
			vosotros: "esperaseis",
			Uds: "esperasen",
		},
		Future: {
			yo: "esperare",
			tú: "esperares",
			Ud: "esperare",
			nosotros: "esperáremos",
			vosotros: "esperareis",
			Uds: "esperaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "espera",
			Ud: "espere",
			nosotros: "esperemos",
			vosotros: "esperad",
			Uds: "esperen",
		},
		Negative: {
			tú: "no esperes",
			Ud: "no espere",
			nosotros: "no esperemos",
			vosotros: "no esperéis",
			Uds: "no esperen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy esperando",
			tú: "estás esperando",
			Ud: "está esperando",
			nosotros: "estamos esperando",
			vosotros: "estáis esperando",
			Uds: "están esperando",
		},
		Preterite: {
			yo: "estuve esperando",
			tú: "estuviste esperando",
			Ud: "estuvo esperando",
			nosotros: "estuvimos esperando",
			vosotros: "estuvisteis esperando",
			Uds: "estuvieron esperando",
		},
		Imperfect: {
			Uds: "estaban esperando",
			yo: "estaba esperando",
			tú: "estabas esperando",
			Ud: "estaba esperando",
			nosotros: "estábamos esperando",
			vosotros: "estabais esperando",
		},
		Conditional: {
			yo: "estaría esperando",
			tú: "estarías esperando",
			Ud: "estaría esperando",
			nosotros: "estaríamos esperando",
			vosotros: "estaríais esperando",
			Uds: "estarían esperando",
		},
		Future: {
			yo: "estaré esperando",
			tú: "estarás esperando",
			Ud: "estará esperando",
			nosotros: "estaremos esperando",
			vosotros: "estaréis esperando",
			Uds: "estarán esperando",
		},
	},
	Perfect: {
		Present: {
			yo: "he esperado",
			tú: "has esperado",
			Ud: "ha esperado",
			nosotros: "hemos esperado",
			vosotros: "habéis esperado",
			Uds: "han esperado",
		},
		Preterite: {
			yo: "hube esperado",
			tú: "hubiste esperado",
			Ud: "hubo esperado",
			nosotros: "hubimos esperado",
			vosotros: "hubisteis esperado",
			Uds: "hubieron esperado",
		},
		Past: {
			yo: "había esperado",
			tú: "habías esperado",
			Ud: "había esperado",
			nosotros: "habíamos esperado",
			vosotros: "habíais esperado",
			Uds: "habían esperado",
		},
		Conditional: {
			yo: "habría esperado",
			tú: "habrías esperado",
			Ud: "habría esperado",
			nosotros: "habríamos esperado",
			vosotros: "habríais esperado",
			Uds: "habrían esperado",
		},
		Future: {
			yo: "habré esperado",
			tú: "habrás esperado",
			Ud: "habrá esperado",
			nosotros: "habremos esperado",
			vosotros: "habréis esperado",
			Uds: "habrán esperado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya esperado",
			tú: "hayas esperado",
			Ud: "haya esperado",
			nosotros: "hayamos esperado",
			vosotros: "hayáis esperado",
			Uds: "hayan esperado",
		},
		Past: {
			yo: "hubiera esperado",
			tú: "hubieras esperado",
			Ud: "hubiera esperado",
			nosotros: "hubiéramos esperado",
			vosotros: "hubierais esperado",
			Uds: "hubieran esperado",
		},
		Future: {
			yo: "hubiere esperado",
			tú: "hubieres esperado",
			Ud: "hubiere esperado",
			nosotros: "hubiéremos esperado",
			vosotros: "hubiereis esperado",
			Uds: "hubieren esperado",
		},
	},
}
