var especular = {
	Indicative: {
		Present: {
			yo: "especulo",
			tú: "especulas",
			Ud: "especula",
			nosotros: "especulamos",
			vosotros: "especuláis",
			Uds: "especulan",
		},
		Preterite: {
			yo: "especulé",
			tú: "especulaste",
			Ud: "especuló",
			nosotros: "especulamos",
			vosotros: "especulasteis",
			Uds: "especularon",
		},
		Imperfect: {
			yo: "especulaba",
			tú: "especulabas",
			Ud: "especulaba",
			nosotros: "especulábamos",
			vosotros: "especulabais",
			Uds: "especulaban",
		},
		Conditional: {
			yo: "especularía",
			tú: "especularías",
			Ud: "especularía",
			nosotros: "especularíamos",
			vosotros: "especularíais",
			Uds: "especularían",
		},
		Future: {
			yo: "especularé",
			tú: "especularás",
			Ud: "especulará",
			nosotros: "especularemos",
			vosotros: "especularéis",
			Uds: "especularán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "especule",
			tú: "especules",
			Ud: "especule",
			nosotros: "especulemos",
			vosotros: "especuléis",
			Uds: "especulen",
		},
		Imperfect: {
			yo: "especulara",
			tú: "especularas",
			Ud: "especulara",
			nosotros: "especuláramos",
			vosotros: "especularais",
			Uds: "especularan",
		},
		Imperfect2: {
			yo: "especulase",
			tú: "especulases",
			Ud: "especulase",
			nosotros: "especulásemos",
			vosotros: "especulaseis",
			Uds: "especulasen",
		},
		Future: {
			yo: "especulare",
			tú: "especulares",
			Ud: "especulare",
			nosotros: "especuláremos",
			vosotros: "especulareis",
			Uds: "especularen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "especula",
			Ud: "especule",
			nosotros: "especulemos",
			vosotros: "especulad",
			Uds: "especulen",
		},
		Negative: {
			tú: "no especules",
			Ud: "no especule",
			nosotros: "no especulemos",
			vosotros: "no especuléis",
			Uds: "no especulen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy especulando",
			tú: "estás especulando",
			Ud: "está especulando",
			nosotros: "estamos especulando",
			vosotros: "estáis especulando",
			Uds: "están especulando",
		},
		Preterite: {
			yo: "estuve especulando",
			tú: "estuviste especulando",
			Ud: "estuvo especulando",
			nosotros: "estuvimos especulando",
			vosotros: "estuvisteis especulando",
			Uds: "estuvieron especulando",
		},
		Imperfect: {
			Uds: "estaban especulando",
			yo: "estaba especulando",
			tú: "estabas especulando",
			Ud: "estaba especulando",
			nosotros: "estábamos especulando",
			vosotros: "estabais especulando",
		},
		Conditional: {
			yo: "estaría especulando",
			tú: "estarías especulando",
			Ud: "estaría especulando",
			nosotros: "estaríamos especulando",
			vosotros: "estaríais especulando",
			Uds: "estarían especulando",
		},
		Future: {
			yo: "estaré especulando",
			tú: "estarás especulando",
			Ud: "estará especulando",
			nosotros: "estaremos especulando",
			vosotros: "estaréis especulando",
			Uds: "estarán especulando",
		},
	},
	Perfect: {
		Present: {
			yo: "he especulado",
			tú: "has especulado",
			Ud: "ha especulado",
			nosotros: "hemos especulado",
			vosotros: "habéis especulado",
			Uds: "han especulado",
		},
		Preterite: {
			yo: "hube especulado",
			tú: "hubiste especulado",
			Ud: "hubo especulado",
			nosotros: "hubimos especulado",
			vosotros: "hubisteis especulado",
			Uds: "hubieron especulado",
		},
		Past: {
			yo: "había especulado",
			tú: "habías especulado",
			Ud: "había especulado",
			nosotros: "habíamos especulado",
			vosotros: "habíais especulado",
			Uds: "habían especulado",
		},
		Conditional: {
			yo: "habría especulado",
			tú: "habrías especulado",
			Ud: "habría especulado",
			nosotros: "habríamos especulado",
			vosotros: "habríais especulado",
			Uds: "habrían especulado",
		},
		Future: {
			yo: "habré especulado",
			tú: "habrás especulado",
			Ud: "habrá especulado",
			nosotros: "habremos especulado",
			vosotros: "habréis especulado",
			Uds: "habrán especulado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya especulado",
			tú: "hayas especulado",
			Ud: "haya especulado",
			nosotros: "hayamos especulado",
			vosotros: "hayáis especulado",
			Uds: "hayan especulado",
		},
		Past: {
			yo: "hubiera especulado",
			tú: "hubieras especulado",
			Ud: "hubiera especulado",
			nosotros: "hubiéramos especulado",
			vosotros: "hubierais especulado",
			Uds: "hubieran especulado",
		},
		Future: {
			yo: "hubiere especulado",
			tú: "hubieres especulado",
			Ud: "hubiere especulado",
			nosotros: "hubiéremos especulado",
			vosotros: "hubiereis especulado",
			Uds: "hubieren especulado",
		},
	},
}
