var esposar = {
	Indicative: {
		Present: {
			yo: "esposo",
			tú: "esposas",
			Ud: "esposa",
			nosotros: "esposamos",
			vosotros: "esposáis",
			Uds: "esposan",
		},
		Preterite: {
			yo: "esposé",
			tú: "esposaste",
			Ud: "esposó",
			nosotros: "esposamos",
			vosotros: "esposasteis",
			Uds: "esposaron",
		},
		Imperfect: {
			yo: "esposaba",
			tú: "esposabas",
			Ud: "esposaba",
			nosotros: "esposábamos",
			vosotros: "esposabais",
			Uds: "esposaban",
		},
		Conditional: {
			yo: "esposaría",
			tú: "esposarías",
			Ud: "esposaría",
			nosotros: "esposaríamos",
			vosotros: "esposaríais",
			Uds: "esposarían",
		},
		Future: {
			yo: "esposaré",
			tú: "esposarás",
			Ud: "esposará",
			nosotros: "esposaremos",
			vosotros: "esposaréis",
			Uds: "esposarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "espose",
			tú: "esposes",
			Ud: "espose",
			nosotros: "esposemos",
			vosotros: "esposéis",
			Uds: "esposen",
		},
		Imperfect: {
			yo: "esposara",
			tú: "esposaras",
			Ud: "esposara",
			nosotros: "esposáramos",
			vosotros: "esposarais",
			Uds: "esposaran",
		},
		Imperfect2: {
			yo: "esposase",
			tú: "esposases",
			Ud: "esposase",
			nosotros: "esposásemos",
			vosotros: "esposaseis",
			Uds: "esposasen",
		},
		Future: {
			yo: "esposare",
			tú: "esposares",
			Ud: "esposare",
			nosotros: "esposáremos",
			vosotros: "esposareis",
			Uds: "esposaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "esposa",
			Ud: "espose",
			nosotros: "esposemos",
			vosotros: "esposad",
			Uds: "esposen",
		},
		Negative: {
			tú: "no esposes",
			Ud: "no espose",
			nosotros: "no esposemos",
			vosotros: "no esposéis",
			Uds: "no esposen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy esposando",
			tú: "estás esposando",
			Ud: "está esposando",
			nosotros: "estamos esposando",
			vosotros: "estáis esposando",
			Uds: "están esposando",
		},
		Preterite: {
			yo: "estuve esposando",
			tú: "estuviste esposando",
			Ud: "estuvo esposando",
			nosotros: "estuvimos esposando",
			vosotros: "estuvisteis esposando",
			Uds: "estuvieron esposando",
		},
		Imperfect: {
			Uds: "estaban esposando",
			yo: "estaba esposando",
			tú: "estabas esposando",
			Ud: "estaba esposando",
			nosotros: "estábamos esposando",
			vosotros: "estabais esposando",
		},
		Conditional: {
			yo: "estaría esposando",
			tú: "estarías esposando",
			Ud: "estaría esposando",
			nosotros: "estaríamos esposando",
			vosotros: "estaríais esposando",
			Uds: "estarían esposando",
		},
		Future: {
			yo: "estaré esposando",
			tú: "estarás esposando",
			Ud: "estará esposando",
			nosotros: "estaremos esposando",
			vosotros: "estaréis esposando",
			Uds: "estarán esposando",
		},
	},
	Perfect: {
		Present: {
			yo: "he esposado",
			tú: "has esposado",
			Ud: "ha esposado",
			nosotros: "hemos esposado",
			vosotros: "habéis esposado",
			Uds: "han esposado",
		},
		Preterite: {
			yo: "hube esposado",
			tú: "hubiste esposado",
			Ud: "hubo esposado",
			nosotros: "hubimos esposado",
			vosotros: "hubisteis esposado",
			Uds: "hubieron esposado",
		},
		Past: {
			yo: "había esposado",
			tú: "habías esposado",
			Ud: "había esposado",
			nosotros: "habíamos esposado",
			vosotros: "habíais esposado",
			Uds: "habían esposado",
		},
		Conditional: {
			yo: "habría esposado",
			tú: "habrías esposado",
			Ud: "habría esposado",
			nosotros: "habríamos esposado",
			vosotros: "habríais esposado",
			Uds: "habrían esposado",
		},
		Future: {
			yo: "habré esposado",
			tú: "habrás esposado",
			Ud: "habrá esposado",
			nosotros: "habremos esposado",
			vosotros: "habréis esposado",
			Uds: "habrán esposado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya esposado",
			tú: "hayas esposado",
			Ud: "haya esposado",
			nosotros: "hayamos esposado",
			vosotros: "hayáis esposado",
			Uds: "hayan esposado",
		},
		Past: {
			yo: "hubiera esposado",
			tú: "hubieras esposado",
			Ud: "hubiera esposado",
			nosotros: "hubiéramos esposado",
			vosotros: "hubierais esposado",
			Uds: "hubieran esposado",
		},
		Future: {
			yo: "hubiere esposado",
			tú: "hubieres esposado",
			Ud: "hubiere esposado",
			nosotros: "hubiéremos esposado",
			vosotros: "hubiereis esposado",
			Uds: "hubieren esposado",
		},
	},
}
