var espolvorear = {
	Indicative: {
		Present: {
			yo: "espolvoreo",
			tú: "espolvoreas",
			Ud: "espolvorea",
			nosotros: "espolvoreamos",
			vosotros: "espolvoreáis",
			Uds: "espolvorean",
		},
		Preterite: {
			yo: "espolvoreé",
			tú: "espolvoreaste",
			Ud: "espolvoreó",
			nosotros: "espolvoreamos",
			vosotros: "espolvoreasteis",
			Uds: "espolvorearon",
		},
		Imperfect: {
			yo: "espolvoreaba",
			tú: "espolvoreabas",
			Ud: "espolvoreaba",
			nosotros: "espolvoreábamos",
			vosotros: "espolvoreabais",
			Uds: "espolvoreaban",
		},
		Conditional: {
			yo: "espolvorearía",
			tú: "espolvorearías",
			Ud: "espolvorearía",
			nosotros: "espolvorearíamos",
			vosotros: "espolvorearíais",
			Uds: "espolvorearían",
		},
		Future: {
			yo: "espolvorearé",
			tú: "espolvorearás",
			Ud: "espolvoreará",
			nosotros: "espolvorearemos",
			vosotros: "espolvorearéis",
			Uds: "espolvorearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "espolvoree",
			tú: "espolvorees",
			Ud: "espolvoree",
			nosotros: "espolvoreemos",
			vosotros: "espolvoreéis",
			Uds: "espolvoreen",
		},
		Imperfect: {
			yo: "espolvoreara",
			tú: "espolvorearas",
			Ud: "espolvoreara",
			nosotros: "espolvoreáramos",
			vosotros: "espolvorearais",
			Uds: "espolvorearan",
		},
		Imperfect2: {
			yo: "espolvorease",
			tú: "espolvoreases",
			Ud: "espolvorease",
			nosotros: "espolvoreásemos",
			vosotros: "espolvoreaseis",
			Uds: "espolvoreasen",
		},
		Future: {
			yo: "espolvoreare",
			tú: "espolvoreares",
			Ud: "espolvoreare",
			nosotros: "espolvoreáremos",
			vosotros: "espolvoreareis",
			Uds: "espolvorearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "espolvorea",
			Ud: "espolvoree",
			nosotros: "espolvoreemos",
			vosotros: "espolvoread",
			Uds: "espolvoreen",
		},
		Negative: {
			tú: "no espolvorees",
			Ud: "no espolvoree",
			nosotros: "no espolvoreemos",
			vosotros: "no espolvoreéis",
			Uds: "no espolvoreen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy espolvoreando",
			tú: "estás espolvoreando",
			Ud: "está espolvoreando",
			nosotros: "estamos espolvoreando",
			vosotros: "estáis espolvoreando",
			Uds: "están espolvoreando",
		},
		Preterite: {
			yo: "estuve espolvoreando",
			tú: "estuviste espolvoreando",
			Ud: "estuvo espolvoreando",
			nosotros: "estuvimos espolvoreando",
			vosotros: "estuvisteis espolvoreando",
			Uds: "estuvieron espolvoreando",
		},
		Imperfect: {
			Uds: "estaban espolvoreando",
			yo: "estaba espolvoreando",
			tú: "estabas espolvoreando",
			Ud: "estaba espolvoreando",
			nosotros: "estábamos espolvoreando",
			vosotros: "estabais espolvoreando",
		},
		Conditional: {
			yo: "estaría espolvoreando",
			tú: "estarías espolvoreando",
			Ud: "estaría espolvoreando",
			nosotros: "estaríamos espolvoreando",
			vosotros: "estaríais espolvoreando",
			Uds: "estarían espolvoreando",
		},
		Future: {
			yo: "estaré espolvoreando",
			tú: "estarás espolvoreando",
			Ud: "estará espolvoreando",
			nosotros: "estaremos espolvoreando",
			vosotros: "estaréis espolvoreando",
			Uds: "estarán espolvoreando",
		},
	},
	Perfect: {
		Present: {
			yo: "he espolvoreado",
			tú: "has espolvoreado",
			Ud: "ha espolvoreado",
			nosotros: "hemos espolvoreado",
			vosotros: "habéis espolvoreado",
			Uds: "han espolvoreado",
		},
		Preterite: {
			yo: "hube espolvoreado",
			tú: "hubiste espolvoreado",
			Ud: "hubo espolvoreado",
			nosotros: "hubimos espolvoreado",
			vosotros: "hubisteis espolvoreado",
			Uds: "hubieron espolvoreado",
		},
		Past: {
			yo: "había espolvoreado",
			tú: "habías espolvoreado",
			Ud: "había espolvoreado",
			nosotros: "habíamos espolvoreado",
			vosotros: "habíais espolvoreado",
			Uds: "habían espolvoreado",
		},
		Conditional: {
			yo: "habría espolvoreado",
			tú: "habrías espolvoreado",
			Ud: "habría espolvoreado",
			nosotros: "habríamos espolvoreado",
			vosotros: "habríais espolvoreado",
			Uds: "habrían espolvoreado",
		},
		Future: {
			yo: "habré espolvoreado",
			tú: "habrás espolvoreado",
			Ud: "habrá espolvoreado",
			nosotros: "habremos espolvoreado",
			vosotros: "habréis espolvoreado",
			Uds: "habrán espolvoreado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya espolvoreado",
			tú: "hayas espolvoreado",
			Ud: "haya espolvoreado",
			nosotros: "hayamos espolvoreado",
			vosotros: "hayáis espolvoreado",
			Uds: "hayan espolvoreado",
		},
		Past: {
			yo: "hubiera espolvoreado",
			tú: "hubieras espolvoreado",
			Ud: "hubiera espolvoreado",
			nosotros: "hubiéramos espolvoreado",
			vosotros: "hubierais espolvoreado",
			Uds: "hubieran espolvoreado",
		},
		Future: {
			yo: "hubiere espolvoreado",
			tú: "hubieres espolvoreado",
			Ud: "hubiere espolvoreado",
			nosotros: "hubiéremos espolvoreado",
			vosotros: "hubiereis espolvoreado",
			Uds: "hubieren espolvoreado",
		},
	},
}
