var esquilar = {
	Indicative: {
		Present: {
			yo: "esquilo",
			tú: "esquilas",
			Ud: "esquila",
			nosotros: "esquilamos",
			vosotros: "esquiláis",
			Uds: "esquilan",
		},
		Preterite: {
			yo: "esquilé",
			tú: "esquilaste",
			Ud: "esquiló",
			nosotros: "esquilamos",
			vosotros: "esquilasteis",
			Uds: "esquilaron",
		},
		Imperfect: {
			yo: "esquilaba",
			tú: "esquilabas",
			Ud: "esquilaba",
			nosotros: "esquilábamos",
			vosotros: "esquilabais",
			Uds: "esquilaban",
		},
		Conditional: {
			yo: "esquilaría",
			tú: "esquilarías",
			Ud: "esquilaría",
			nosotros: "esquilaríamos",
			vosotros: "esquilaríais",
			Uds: "esquilarían",
		},
		Future: {
			yo: "esquilaré",
			tú: "esquilarás",
			Ud: "esquilará",
			nosotros: "esquilaremos",
			vosotros: "esquilaréis",
			Uds: "esquilarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "esquile",
			tú: "esquiles",
			Ud: "esquile",
			nosotros: "esquilemos",
			vosotros: "esquiléis",
			Uds: "esquilen",
		},
		Imperfect: {
			yo: "esquilara",
			tú: "esquilaras",
			Ud: "esquilara",
			nosotros: "esquiláramos",
			vosotros: "esquilarais",
			Uds: "esquilaran",
		},
		Imperfect2: {
			yo: "esquilase",
			tú: "esquilases",
			Ud: "esquilase",
			nosotros: "esquilásemos",
			vosotros: "esquilaseis",
			Uds: "esquilasen",
		},
		Future: {
			yo: "esquilare",
			tú: "esquilares",
			Ud: "esquilare",
			nosotros: "esquiláremos",
			vosotros: "esquilareis",
			Uds: "esquilaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "esquila",
			Ud: "esquile",
			nosotros: "esquilemos",
			vosotros: "esquilad",
			Uds: "esquilen",
		},
		Negative: {
			tú: "no esquiles",
			Ud: "no esquile",
			nosotros: "no esquilemos",
			vosotros: "no esquiléis",
			Uds: "no esquilen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy esquilando",
			tú: "estás esquilando",
			Ud: "está esquilando",
			nosotros: "estamos esquilando",
			vosotros: "estáis esquilando",
			Uds: "están esquilando",
		},
		Preterite: {
			yo: "estuve esquilando",
			tú: "estuviste esquilando",
			Ud: "estuvo esquilando",
			nosotros: "estuvimos esquilando",
			vosotros: "estuvisteis esquilando",
			Uds: "estuvieron esquilando",
		},
		Imperfect: {
			Uds: "estaban esquilando",
			yo: "estaba esquilando",
			tú: "estabas esquilando",
			Ud: "estaba esquilando",
			nosotros: "estábamos esquilando",
			vosotros: "estabais esquilando",
		},
		Conditional: {
			yo: "estaría esquilando",
			tú: "estarías esquilando",
			Ud: "estaría esquilando",
			nosotros: "estaríamos esquilando",
			vosotros: "estaríais esquilando",
			Uds: "estarían esquilando",
		},
		Future: {
			yo: "estaré esquilando",
			tú: "estarás esquilando",
			Ud: "estará esquilando",
			nosotros: "estaremos esquilando",
			vosotros: "estaréis esquilando",
			Uds: "estarán esquilando",
		},
	},
	Perfect: {
		Present: {
			yo: "he esquilado",
			tú: "has esquilado",
			Ud: "ha esquilado",
			nosotros: "hemos esquilado",
			vosotros: "habéis esquilado",
			Uds: "han esquilado",
		},
		Preterite: {
			yo: "hube esquilado",
			tú: "hubiste esquilado",
			Ud: "hubo esquilado",
			nosotros: "hubimos esquilado",
			vosotros: "hubisteis esquilado",
			Uds: "hubieron esquilado",
		},
		Past: {
			yo: "había esquilado",
			tú: "habías esquilado",
			Ud: "había esquilado",
			nosotros: "habíamos esquilado",
			vosotros: "habíais esquilado",
			Uds: "habían esquilado",
		},
		Conditional: {
			yo: "habría esquilado",
			tú: "habrías esquilado",
			Ud: "habría esquilado",
			nosotros: "habríamos esquilado",
			vosotros: "habríais esquilado",
			Uds: "habrían esquilado",
		},
		Future: {
			yo: "habré esquilado",
			tú: "habrás esquilado",
			Ud: "habrá esquilado",
			nosotros: "habremos esquilado",
			vosotros: "habréis esquilado",
			Uds: "habrán esquilado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya esquilado",
			tú: "hayas esquilado",
			Ud: "haya esquilado",
			nosotros: "hayamos esquilado",
			vosotros: "hayáis esquilado",
			Uds: "hayan esquilado",
		},
		Past: {
			yo: "hubiera esquilado",
			tú: "hubieras esquilado",
			Ud: "hubiera esquilado",
			nosotros: "hubiéramos esquilado",
			vosotros: "hubierais esquilado",
			Uds: "hubieran esquilado",
		},
		Future: {
			yo: "hubiere esquilado",
			tú: "hubieres esquilado",
			Ud: "hubiere esquilado",
			nosotros: "hubiéremos esquilado",
			vosotros: "hubiereis esquilado",
			Uds: "hubieren esquilado",
		},
	},
}
