var estacionar = {
	Indicative: {
		Present: {
			yo: "estaciono",
			tú: "estacionas",
			Ud: "estaciona",
			nosotros: "estacionamos",
			vosotros: "estacionáis",
			Uds: "estacionan",
		},
		Preterite: {
			yo: "estacioné",
			tú: "estacionaste",
			Ud: "estacionó",
			nosotros: "estacionamos",
			vosotros: "estacionasteis",
			Uds: "estacionaron",
		},
		Imperfect: {
			yo: "estacionaba",
			tú: "estacionabas",
			Ud: "estacionaba",
			nosotros: "estacionábamos",
			vosotros: "estacionabais",
			Uds: "estacionaban",
		},
		Conditional: {
			yo: "estacionaría",
			tú: "estacionarías",
			Ud: "estacionaría",
			nosotros: "estacionaríamos",
			vosotros: "estacionaríais",
			Uds: "estacionarían",
		},
		Future: {
			yo: "estacionaré",
			tú: "estacionarás",
			Ud: "estacionará",
			nosotros: "estacionaremos",
			vosotros: "estacionaréis",
			Uds: "estacionarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "estacione",
			tú: "estaciones",
			Ud: "estacione",
			nosotros: "estacionemos",
			vosotros: "estacionéis",
			Uds: "estacionen",
		},
		Imperfect: {
			yo: "estacionara",
			tú: "estacionaras",
			Ud: "estacionara",
			nosotros: "estacionáramos",
			vosotros: "estacionarais",
			Uds: "estacionaran",
		},
		Imperfect2: {
			yo: "estacionase",
			tú: "estacionases",
			Ud: "estacionase",
			nosotros: "estacionásemos",
			vosotros: "estacionaseis",
			Uds: "estacionasen",
		},
		Future: {
			yo: "estacionare",
			tú: "estacionares",
			Ud: "estacionare",
			nosotros: "estacionáremos",
			vosotros: "estacionareis",
			Uds: "estacionaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "estaciona",
			Ud: "estacione",
			nosotros: "estacionemos",
			vosotros: "estacionad",
			Uds: "estacionen",
		},
		Negative: {
			tú: "no estaciones",
			Ud: "no estacione",
			nosotros: "no estacionemos",
			vosotros: "no estacionéis",
			Uds: "no estacionen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy estacionando",
			tú: "estás estacionando",
			Ud: "está estacionando",
			nosotros: "estamos estacionando",
			vosotros: "estáis estacionando",
			Uds: "están estacionando",
		},
		Preterite: {
			yo: "estuve estacionando",
			tú: "estuviste estacionando",
			Ud: "estuvo estacionando",
			nosotros: "estuvimos estacionando",
			vosotros: "estuvisteis estacionando",
			Uds: "estuvieron estacionando",
		},
		Imperfect: {
			Uds: "estaban estacionando",
			yo: "estaba estacionando",
			tú: "estabas estacionando",
			Ud: "estaba estacionando",
			nosotros: "estábamos estacionando",
			vosotros: "estabais estacionando",
		},
		Conditional: {
			yo: "estaría estacionando",
			tú: "estarías estacionando",
			Ud: "estaría estacionando",
			nosotros: "estaríamos estacionando",
			vosotros: "estaríais estacionando",
			Uds: "estarían estacionando",
		},
		Future: {
			yo: "estaré estacionando",
			tú: "estarás estacionando",
			Ud: "estará estacionando",
			nosotros: "estaremos estacionando",
			vosotros: "estaréis estacionando",
			Uds: "estarán estacionando",
		},
	},
	Perfect: {
		Present: {
			yo: "he estacionado",
			tú: "has estacionado",
			Ud: "ha estacionado",
			nosotros: "hemos estacionado",
			vosotros: "habéis estacionado",
			Uds: "han estacionado",
		},
		Preterite: {
			yo: "hube estacionado",
			tú: "hubiste estacionado",
			Ud: "hubo estacionado",
			nosotros: "hubimos estacionado",
			vosotros: "hubisteis estacionado",
			Uds: "hubieron estacionado",
		},
		Past: {
			yo: "había estacionado",
			tú: "habías estacionado",
			Ud: "había estacionado",
			nosotros: "habíamos estacionado",
			vosotros: "habíais estacionado",
			Uds: "habían estacionado",
		},
		Conditional: {
			yo: "habría estacionado",
			tú: "habrías estacionado",
			Ud: "habría estacionado",
			nosotros: "habríamos estacionado",
			vosotros: "habríais estacionado",
			Uds: "habrían estacionado",
		},
		Future: {
			yo: "habré estacionado",
			tú: "habrás estacionado",
			Ud: "habrá estacionado",
			nosotros: "habremos estacionado",
			vosotros: "habréis estacionado",
			Uds: "habrán estacionado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya estacionado",
			tú: "hayas estacionado",
			Ud: "haya estacionado",
			nosotros: "hayamos estacionado",
			vosotros: "hayáis estacionado",
			Uds: "hayan estacionado",
		},
		Past: {
			yo: "hubiera estacionado",
			tú: "hubieras estacionado",
			Ud: "hubiera estacionado",
			nosotros: "hubiéramos estacionado",
			vosotros: "hubierais estacionado",
			Uds: "hubieran estacionado",
		},
		Future: {
			yo: "hubiere estacionado",
			tú: "hubieres estacionado",
			Ud: "hubiere estacionado",
			nosotros: "hubiéremos estacionado",
			vosotros: "hubiereis estacionado",
			Uds: "hubieren estacionado",
		},
	},
}
