var estampar = {
	Indicative: {
		Present: {
			yo: "estampo",
			tú: "estampas",
			Ud: "estampa",
			nosotros: "estampamos",
			vosotros: "estampáis",
			Uds: "estampan",
		},
		Preterite: {
			yo: "estampé",
			tú: "estampaste",
			Ud: "estampó",
			nosotros: "estampamos",
			vosotros: "estampasteis",
			Uds: "estamparon",
		},
		Imperfect: {
			yo: "estampaba",
			tú: "estampabas",
			Ud: "estampaba",
			nosotros: "estampábamos",
			vosotros: "estampabais",
			Uds: "estampaban",
		},
		Conditional: {
			yo: "estamparía",
			tú: "estamparías",
			Ud: "estamparía",
			nosotros: "estamparíamos",
			vosotros: "estamparíais",
			Uds: "estamparían",
		},
		Future: {
			yo: "estamparé",
			tú: "estamparás",
			Ud: "estampará",
			nosotros: "estamparemos",
			vosotros: "estamparéis",
			Uds: "estamparán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "estampe",
			tú: "estampes",
			Ud: "estampe",
			nosotros: "estampemos",
			vosotros: "estampéis",
			Uds: "estampen",
		},
		Imperfect: {
			yo: "estampara",
			tú: "estamparas",
			Ud: "estampara",
			nosotros: "estampáramos",
			vosotros: "estamparais",
			Uds: "estamparan",
		},
		Imperfect2: {
			yo: "estampase",
			tú: "estampases",
			Ud: "estampase",
			nosotros: "estampásemos",
			vosotros: "estampaseis",
			Uds: "estampasen",
		},
		Future: {
			yo: "estampare",
			tú: "estampares",
			Ud: "estampare",
			nosotros: "estampáremos",
			vosotros: "estampareis",
			Uds: "estamparen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "estampa",
			Ud: "estampe",
			nosotros: "estampemos",
			vosotros: "estampad",
			Uds: "estampen",
		},
		Negative: {
			tú: "no estampes",
			Ud: "no estampe",
			nosotros: "no estampemos",
			vosotros: "no estampéis",
			Uds: "no estampen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy estampando",
			tú: "estás estampando",
			Ud: "está estampando",
			nosotros: "estamos estampando",
			vosotros: "estáis estampando",
			Uds: "están estampando",
		},
		Preterite: {
			yo: "estuve estampando",
			tú: "estuviste estampando",
			Ud: "estuvo estampando",
			nosotros: "estuvimos estampando",
			vosotros: "estuvisteis estampando",
			Uds: "estuvieron estampando",
		},
		Imperfect: {
			Uds: "estaban estampando",
			yo: "estaba estampando",
			tú: "estabas estampando",
			Ud: "estaba estampando",
			nosotros: "estábamos estampando",
			vosotros: "estabais estampando",
		},
		Conditional: {
			yo: "estaría estampando",
			tú: "estarías estampando",
			Ud: "estaría estampando",
			nosotros: "estaríamos estampando",
			vosotros: "estaríais estampando",
			Uds: "estarían estampando",
		},
		Future: {
			yo: "estaré estampando",
			tú: "estarás estampando",
			Ud: "estará estampando",
			nosotros: "estaremos estampando",
			vosotros: "estaréis estampando",
			Uds: "estarán estampando",
		},
	},
	Perfect: {
		Present: {
			yo: "he estampado",
			tú: "has estampado",
			Ud: "ha estampado",
			nosotros: "hemos estampado",
			vosotros: "habéis estampado",
			Uds: "han estampado",
		},
		Preterite: {
			yo: "hube estampado",
			tú: "hubiste estampado",
			Ud: "hubo estampado",
			nosotros: "hubimos estampado",
			vosotros: "hubisteis estampado",
			Uds: "hubieron estampado",
		},
		Past: {
			yo: "había estampado",
			tú: "habías estampado",
			Ud: "había estampado",
			nosotros: "habíamos estampado",
			vosotros: "habíais estampado",
			Uds: "habían estampado",
		},
		Conditional: {
			yo: "habría estampado",
			tú: "habrías estampado",
			Ud: "habría estampado",
			nosotros: "habríamos estampado",
			vosotros: "habríais estampado",
			Uds: "habrían estampado",
		},
		Future: {
			yo: "habré estampado",
			tú: "habrás estampado",
			Ud: "habrá estampado",
			nosotros: "habremos estampado",
			vosotros: "habréis estampado",
			Uds: "habrán estampado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya estampado",
			tú: "hayas estampado",
			Ud: "haya estampado",
			nosotros: "hayamos estampado",
			vosotros: "hayáis estampado",
			Uds: "hayan estampado",
		},
		Past: {
			yo: "hubiera estampado",
			tú: "hubieras estampado",
			Ud: "hubiera estampado",
			nosotros: "hubiéramos estampado",
			vosotros: "hubierais estampado",
			Uds: "hubieran estampado",
		},
		Future: {
			yo: "hubiere estampado",
			tú: "hubieres estampado",
			Ud: "hubiere estampado",
			nosotros: "hubiéremos estampado",
			vosotros: "hubiereis estampado",
			Uds: "hubieren estampado",
		},
	},
}
