var estimar = {
	Indicative: {
		Present: {
			yo: "estimo",
			tú: "estimas",
			Ud: "estima",
			nosotros: "estimamos",
			vosotros: "estimáis",
			Uds: "estiman",
		},
		Preterite: {
			yo: "estimé",
			tú: "estimaste",
			Ud: "estimó",
			nosotros: "estimamos",
			vosotros: "estimasteis",
			Uds: "estimaron",
		},
		Imperfect: {
			yo: "estimaba",
			tú: "estimabas",
			Ud: "estimaba",
			nosotros: "estimábamos",
			vosotros: "estimabais",
			Uds: "estimaban",
		},
		Conditional: {
			yo: "estimaría",
			tú: "estimarías",
			Ud: "estimaría",
			nosotros: "estimaríamos",
			vosotros: "estimaríais",
			Uds: "estimarían",
		},
		Future: {
			yo: "estimaré",
			tú: "estimarás",
			Ud: "estimará",
			nosotros: "estimaremos",
			vosotros: "estimaréis",
			Uds: "estimarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "estime",
			tú: "estimes",
			Ud: "estime",
			nosotros: "estimemos",
			vosotros: "estiméis",
			Uds: "estimen",
		},
		Imperfect: {
			yo: "estimara",
			tú: "estimaras",
			Ud: "estimara",
			nosotros: "estimáramos",
			vosotros: "estimarais",
			Uds: "estimaran",
		},
		Imperfect2: {
			yo: "estimase",
			tú: "estimases",
			Ud: "estimase",
			nosotros: "estimásemos",
			vosotros: "estimaseis",
			Uds: "estimasen",
		},
		Future: {
			yo: "estimare",
			tú: "estimares",
			Ud: "estimare",
			nosotros: "estimáremos",
			vosotros: "estimareis",
			Uds: "estimaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "estima",
			Ud: "estime",
			nosotros: "estimemos",
			vosotros: "estimad",
			Uds: "estimen",
		},
		Negative: {
			tú: "no estimes",
			Ud: "no estime",
			nosotros: "no estimemos",
			vosotros: "no estiméis",
			Uds: "no estimen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy estimando",
			tú: "estás estimando",
			Ud: "está estimando",
			nosotros: "estamos estimando",
			vosotros: "estáis estimando",
			Uds: "están estimando",
		},
		Preterite: {
			yo: "estuve estimando",
			tú: "estuviste estimando",
			Ud: "estuvo estimando",
			nosotros: "estuvimos estimando",
			vosotros: "estuvisteis estimando",
			Uds: "estuvieron estimando",
		},
		Imperfect: {
			Uds: "estaban estimando",
			yo: "estaba estimando",
			tú: "estabas estimando",
			Ud: "estaba estimando",
			nosotros: "estábamos estimando",
			vosotros: "estabais estimando",
		},
		Conditional: {
			yo: "estaría estimando",
			tú: "estarías estimando",
			Ud: "estaría estimando",
			nosotros: "estaríamos estimando",
			vosotros: "estaríais estimando",
			Uds: "estarían estimando",
		},
		Future: {
			yo: "estaré estimando",
			tú: "estarás estimando",
			Ud: "estará estimando",
			nosotros: "estaremos estimando",
			vosotros: "estaréis estimando",
			Uds: "estarán estimando",
		},
	},
	Perfect: {
		Present: {
			yo: "he estimado",
			tú: "has estimado",
			Ud: "ha estimado",
			nosotros: "hemos estimado",
			vosotros: "habéis estimado",
			Uds: "han estimado",
		},
		Preterite: {
			yo: "hube estimado",
			tú: "hubiste estimado",
			Ud: "hubo estimado",
			nosotros: "hubimos estimado",
			vosotros: "hubisteis estimado",
			Uds: "hubieron estimado",
		},
		Past: {
			yo: "había estimado",
			tú: "habías estimado",
			Ud: "había estimado",
			nosotros: "habíamos estimado",
			vosotros: "habíais estimado",
			Uds: "habían estimado",
		},
		Conditional: {
			yo: "habría estimado",
			tú: "habrías estimado",
			Ud: "habría estimado",
			nosotros: "habríamos estimado",
			vosotros: "habríais estimado",
			Uds: "habrían estimado",
		},
		Future: {
			yo: "habré estimado",
			tú: "habrás estimado",
			Ud: "habrá estimado",
			nosotros: "habremos estimado",
			vosotros: "habréis estimado",
			Uds: "habrán estimado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya estimado",
			tú: "hayas estimado",
			Ud: "haya estimado",
			nosotros: "hayamos estimado",
			vosotros: "hayáis estimado",
			Uds: "hayan estimado",
		},
		Past: {
			yo: "hubiera estimado",
			tú: "hubieras estimado",
			Ud: "hubiera estimado",
			nosotros: "hubiéramos estimado",
			vosotros: "hubierais estimado",
			Uds: "hubieran estimado",
		},
		Future: {
			yo: "hubiere estimado",
			tú: "hubieres estimado",
			Ud: "hubiere estimado",
			nosotros: "hubiéremos estimado",
			vosotros: "hubiereis estimado",
			Uds: "hubieren estimado",
		},
	},
}
