var estirar = {
	Indicative: {
		Present: {
			yo: "estiro",
			tú: "estiras",
			Ud: "estira",
			nosotros: "estiramos",
			vosotros: "estiráis",
			Uds: "estiran",
		},
		Preterite: {
			yo: "estiré",
			tú: "estiraste",
			Ud: "estiró",
			nosotros: "estiramos",
			vosotros: "estirasteis",
			Uds: "estiraron",
		},
		Imperfect: {
			yo: "estiraba",
			tú: "estirabas",
			Ud: "estiraba",
			nosotros: "estirábamos",
			vosotros: "estirabais",
			Uds: "estiraban",
		},
		Conditional: {
			yo: "estiraría",
			tú: "estirarías",
			Ud: "estiraría",
			nosotros: "estiraríamos",
			vosotros: "estiraríais",
			Uds: "estirarían",
		},
		Future: {
			yo: "estiraré",
			tú: "estirarás",
			Ud: "estirará",
			nosotros: "estiraremos",
			vosotros: "estiraréis",
			Uds: "estirarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "estire",
			tú: "estires",
			Ud: "estire",
			nosotros: "estiremos",
			vosotros: "estiréis",
			Uds: "estiren",
		},
		Imperfect: {
			yo: "estirara",
			tú: "estiraras",
			Ud: "estirara",
			nosotros: "estiráramos",
			vosotros: "estirarais",
			Uds: "estiraran",
		},
		Imperfect2: {
			yo: "estirase",
			tú: "estirases",
			Ud: "estirase",
			nosotros: "estirásemos",
			vosotros: "estiraseis",
			Uds: "estirasen",
		},
		Future: {
			yo: "estirare",
			tú: "estirares",
			Ud: "estirare",
			nosotros: "estiráremos",
			vosotros: "estirareis",
			Uds: "estiraren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "estira",
			Ud: "estire",
			nosotros: "estiremos",
			vosotros: "estirad",
			Uds: "estiren",
		},
		Negative: {
			tú: "no estires",
			Ud: "no estire",
			nosotros: "no estiremos",
			vosotros: "no estiréis",
			Uds: "no estiren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy estirando",
			tú: "estás estirando",
			Ud: "está estirando",
			nosotros: "estamos estirando",
			vosotros: "estáis estirando",
			Uds: "están estirando",
		},
		Preterite: {
			yo: "estuve estirando",
			tú: "estuviste estirando",
			Ud: "estuvo estirando",
			nosotros: "estuvimos estirando",
			vosotros: "estuvisteis estirando",
			Uds: "estuvieron estirando",
		},
		Imperfect: {
			Uds: "estaban estirando",
			yo: "estaba estirando",
			tú: "estabas estirando",
			Ud: "estaba estirando",
			nosotros: "estábamos estirando",
			vosotros: "estabais estirando",
		},
		Conditional: {
			yo: "estaría estirando",
			tú: "estarías estirando",
			Ud: "estaría estirando",
			nosotros: "estaríamos estirando",
			vosotros: "estaríais estirando",
			Uds: "estarían estirando",
		},
		Future: {
			yo: "estaré estirando",
			tú: "estarás estirando",
			Ud: "estará estirando",
			nosotros: "estaremos estirando",
			vosotros: "estaréis estirando",
			Uds: "estarán estirando",
		},
	},
	Perfect: {
		Present: {
			yo: "he estirado",
			tú: "has estirado",
			Ud: "ha estirado",
			nosotros: "hemos estirado",
			vosotros: "habéis estirado",
			Uds: "han estirado",
		},
		Preterite: {
			yo: "hube estirado",
			tú: "hubiste estirado",
			Ud: "hubo estirado",
			nosotros: "hubimos estirado",
			vosotros: "hubisteis estirado",
			Uds: "hubieron estirado",
		},
		Past: {
			yo: "había estirado",
			tú: "habías estirado",
			Ud: "había estirado",
			nosotros: "habíamos estirado",
			vosotros: "habíais estirado",
			Uds: "habían estirado",
		},
		Conditional: {
			yo: "habría estirado",
			tú: "habrías estirado",
			Ud: "habría estirado",
			nosotros: "habríamos estirado",
			vosotros: "habríais estirado",
			Uds: "habrían estirado",
		},
		Future: {
			yo: "habré estirado",
			tú: "habrás estirado",
			Ud: "habrá estirado",
			nosotros: "habremos estirado",
			vosotros: "habréis estirado",
			Uds: "habrán estirado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya estirado",
			tú: "hayas estirado",
			Ud: "haya estirado",
			nosotros: "hayamos estirado",
			vosotros: "hayáis estirado",
			Uds: "hayan estirado",
		},
		Past: {
			yo: "hubiera estirado",
			tú: "hubieras estirado",
			Ud: "hubiera estirado",
			nosotros: "hubiéramos estirado",
			vosotros: "hubierais estirado",
			Uds: "hubieran estirado",
		},
		Future: {
			yo: "hubiere estirado",
			tú: "hubieres estirado",
			Ud: "hubiere estirado",
			nosotros: "hubiéremos estirado",
			vosotros: "hubiereis estirado",
			Uds: "hubieren estirado",
		},
	},
}
