var estofar = {
	Indicative: {
		Present: {
			yo: "estofo",
			tú: "estofas",
			Ud: "estofa",
			nosotros: "estofamos",
			vosotros: "estofáis",
			Uds: "estofan",
		},
		Preterite: {
			yo: "estofé",
			tú: "estofaste",
			Ud: "estofó",
			nosotros: "estofamos",
			vosotros: "estofasteis",
			Uds: "estofaron",
		},
		Imperfect: {
			yo: "estofaba",
			tú: "estofabas",
			Ud: "estofaba",
			nosotros: "estofábamos",
			vosotros: "estofabais",
			Uds: "estofaban",
		},
		Conditional: {
			yo: "estofaría",
			tú: "estofarías",
			Ud: "estofaría",
			nosotros: "estofaríamos",
			vosotros: "estofaríais",
			Uds: "estofarían",
		},
		Future: {
			yo: "estofaré",
			tú: "estofarás",
			Ud: "estofará",
			nosotros: "estofaremos",
			vosotros: "estofaréis",
			Uds: "estofarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "estofe",
			tú: "estofes",
			Ud: "estofe",
			nosotros: "estofemos",
			vosotros: "estoféis",
			Uds: "estofen",
		},
		Imperfect: {
			yo: "estofara",
			tú: "estofaras",
			Ud: "estofara",
			nosotros: "estofáramos",
			vosotros: "estofarais",
			Uds: "estofaran",
		},
		Imperfect2: {
			yo: "estofase",
			tú: "estofases",
			Ud: "estofase",
			nosotros: "estofásemos",
			vosotros: "estofaseis",
			Uds: "estofasen",
		},
		Future: {
			yo: "estofare",
			tú: "estofares",
			Ud: "estofare",
			nosotros: "estofáremos",
			vosotros: "estofareis",
			Uds: "estofaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "estofa",
			Ud: "estofe",
			nosotros: "estofemos",
			vosotros: "estofad",
			Uds: "estofen",
		},
		Negative: {
			tú: "no estofes",
			Ud: "no estofe",
			nosotros: "no estofemos",
			vosotros: "no estoféis",
			Uds: "no estofen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy estofando",
			tú: "estás estofando",
			Ud: "está estofando",
			nosotros: "estamos estofando",
			vosotros: "estáis estofando",
			Uds: "están estofando",
		},
		Preterite: {
			yo: "estuve estofando",
			tú: "estuviste estofando",
			Ud: "estuvo estofando",
			nosotros: "estuvimos estofando",
			vosotros: "estuvisteis estofando",
			Uds: "estuvieron estofando",
		},
		Imperfect: {
			Uds: "estaban estofando",
			yo: "estaba estofando",
			tú: "estabas estofando",
			Ud: "estaba estofando",
			nosotros: "estábamos estofando",
			vosotros: "estabais estofando",
		},
		Conditional: {
			yo: "estaría estofando",
			tú: "estarías estofando",
			Ud: "estaría estofando",
			nosotros: "estaríamos estofando",
			vosotros: "estaríais estofando",
			Uds: "estarían estofando",
		},
		Future: {
			yo: "estaré estofando",
			tú: "estarás estofando",
			Ud: "estará estofando",
			nosotros: "estaremos estofando",
			vosotros: "estaréis estofando",
			Uds: "estarán estofando",
		},
	},
	Perfect: {
		Present: {
			yo: "he estofado",
			tú: "has estofado",
			Ud: "ha estofado",
			nosotros: "hemos estofado",
			vosotros: "habéis estofado",
			Uds: "han estofado",
		},
		Preterite: {
			yo: "hube estofado",
			tú: "hubiste estofado",
			Ud: "hubo estofado",
			nosotros: "hubimos estofado",
			vosotros: "hubisteis estofado",
			Uds: "hubieron estofado",
		},
		Past: {
			yo: "había estofado",
			tú: "habías estofado",
			Ud: "había estofado",
			nosotros: "habíamos estofado",
			vosotros: "habíais estofado",
			Uds: "habían estofado",
		},
		Conditional: {
			yo: "habría estofado",
			tú: "habrías estofado",
			Ud: "habría estofado",
			nosotros: "habríamos estofado",
			vosotros: "habríais estofado",
			Uds: "habrían estofado",
		},
		Future: {
			yo: "habré estofado",
			tú: "habrás estofado",
			Ud: "habrá estofado",
			nosotros: "habremos estofado",
			vosotros: "habréis estofado",
			Uds: "habrán estofado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya estofado",
			tú: "hayas estofado",
			Ud: "haya estofado",
			nosotros: "hayamos estofado",
			vosotros: "hayáis estofado",
			Uds: "hayan estofado",
		},
		Past: {
			yo: "hubiera estofado",
			tú: "hubieras estofado",
			Ud: "hubiera estofado",
			nosotros: "hubiéramos estofado",
			vosotros: "hubierais estofado",
			Uds: "hubieran estofado",
		},
		Future: {
			yo: "hubiere estofado",
			tú: "hubieres estofado",
			Ud: "hubiere estofado",
			nosotros: "hubiéremos estofado",
			vosotros: "hubiereis estofado",
			Uds: "hubieren estofado",
		},
	},
}
