var estrellar = {
	Indicative: {
		Present: {
			yo: "estrello",
			tú: "estrellas",
			Ud: "estrella",
			nosotros: "estrellamos",
			vosotros: "estrelláis",
			Uds: "estrellan",
		},
		Preterite: {
			yo: "estrellé",
			tú: "estrellaste",
			Ud: "estrelló",
			nosotros: "estrellamos",
			vosotros: "estrellasteis",
			Uds: "estrellaron",
		},
		Imperfect: {
			yo: "estrellaba",
			tú: "estrellabas",
			Ud: "estrellaba",
			nosotros: "estrellábamos",
			vosotros: "estrellabais",
			Uds: "estrellaban",
		},
		Conditional: {
			yo: "estrellaría",
			tú: "estrellarías",
			Ud: "estrellaría",
			nosotros: "estrellaríamos",
			vosotros: "estrellaríais",
			Uds: "estrellarían",
		},
		Future: {
			yo: "estrellaré",
			tú: "estrellarás",
			Ud: "estrellará",
			nosotros: "estrellaremos",
			vosotros: "estrellaréis",
			Uds: "estrellarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "estrelle",
			tú: "estrelles",
			Ud: "estrelle",
			nosotros: "estrellemos",
			vosotros: "estrelléis",
			Uds: "estrellen",
		},
		Imperfect: {
			yo: "estrellara",
			tú: "estrellaras",
			Ud: "estrellara",
			nosotros: "estrelláramos",
			vosotros: "estrellarais",
			Uds: "estrellaran",
		},
		Imperfect2: {
			yo: "estrellase",
			tú: "estrellases",
			Ud: "estrellase",
			nosotros: "estrellásemos",
			vosotros: "estrellaseis",
			Uds: "estrellasen",
		},
		Future: {
			yo: "estrellare",
			tú: "estrellares",
			Ud: "estrellare",
			nosotros: "estrelláremos",
			vosotros: "estrellareis",
			Uds: "estrellaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "estrella",
			Ud: "estrelle",
			nosotros: "estrellemos",
			vosotros: "estrellad",
			Uds: "estrellen",
		},
		Negative: {
			tú: "no estrelles",
			Ud: "no estrelle",
			nosotros: "no estrellemos",
			vosotros: "no estrelléis",
			Uds: "no estrellen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy estrellando",
			tú: "estás estrellando",
			Ud: "está estrellando",
			nosotros: "estamos estrellando",
			vosotros: "estáis estrellando",
			Uds: "están estrellando",
		},
		Preterite: {
			yo: "estuve estrellando",
			tú: "estuviste estrellando",
			Ud: "estuvo estrellando",
			nosotros: "estuvimos estrellando",
			vosotros: "estuvisteis estrellando",
			Uds: "estuvieron estrellando",
		},
		Imperfect: {
			Uds: "estaban estrellando",
			yo: "estaba estrellando",
			tú: "estabas estrellando",
			Ud: "estaba estrellando",
			nosotros: "estábamos estrellando",
			vosotros: "estabais estrellando",
		},
		Conditional: {
			yo: "estaría estrellando",
			tú: "estarías estrellando",
			Ud: "estaría estrellando",
			nosotros: "estaríamos estrellando",
			vosotros: "estaríais estrellando",
			Uds: "estarían estrellando",
		},
		Future: {
			yo: "estaré estrellando",
			tú: "estarás estrellando",
			Ud: "estará estrellando",
			nosotros: "estaremos estrellando",
			vosotros: "estaréis estrellando",
			Uds: "estarán estrellando",
		},
	},
	Perfect: {
		Present: {
			yo: "he estrellado",
			tú: "has estrellado",
			Ud: "ha estrellado",
			nosotros: "hemos estrellado",
			vosotros: "habéis estrellado",
			Uds: "han estrellado",
		},
		Preterite: {
			yo: "hube estrellado",
			tú: "hubiste estrellado",
			Ud: "hubo estrellado",
			nosotros: "hubimos estrellado",
			vosotros: "hubisteis estrellado",
			Uds: "hubieron estrellado",
		},
		Past: {
			yo: "había estrellado",
			tú: "habías estrellado",
			Ud: "había estrellado",
			nosotros: "habíamos estrellado",
			vosotros: "habíais estrellado",
			Uds: "habían estrellado",
		},
		Conditional: {
			yo: "habría estrellado",
			tú: "habrías estrellado",
			Ud: "habría estrellado",
			nosotros: "habríamos estrellado",
			vosotros: "habríais estrellado",
			Uds: "habrían estrellado",
		},
		Future: {
			yo: "habré estrellado",
			tú: "habrás estrellado",
			Ud: "habrá estrellado",
			nosotros: "habremos estrellado",
			vosotros: "habréis estrellado",
			Uds: "habrán estrellado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya estrellado",
			tú: "hayas estrellado",
			Ud: "haya estrellado",
			nosotros: "hayamos estrellado",
			vosotros: "hayáis estrellado",
			Uds: "hayan estrellado",
		},
		Past: {
			yo: "hubiera estrellado",
			tú: "hubieras estrellado",
			Ud: "hubiera estrellado",
			nosotros: "hubiéramos estrellado",
			vosotros: "hubierais estrellado",
			Uds: "hubieran estrellado",
		},
		Future: {
			yo: "hubiere estrellado",
			tú: "hubieres estrellado",
			Ud: "hubiere estrellado",
			nosotros: "hubiéremos estrellado",
			vosotros: "hubiereis estrellado",
			Uds: "hubieren estrellado",
		},
	},
}
