var estructurar = {
	Indicative: {
		Present: {
			yo: "estructuro",
			tú: "estructuras",
			Ud: "estructura",
			nosotros: "estructuramos",
			vosotros: "estructuráis",
			Uds: "estructuran",
		},
		Preterite: {
			yo: "estructuré",
			tú: "estructuraste",
			Ud: "estructuró",
			nosotros: "estructuramos",
			vosotros: "estructurasteis",
			Uds: "estructuraron",
		},
		Imperfect: {
			yo: "estructuraba",
			tú: "estructurabas",
			Ud: "estructuraba",
			nosotros: "estructurábamos",
			vosotros: "estructurabais",
			Uds: "estructuraban",
		},
		Conditional: {
			yo: "estructuraría",
			tú: "estructurarías",
			Ud: "estructuraría",
			nosotros: "estructuraríamos",
			vosotros: "estructuraríais",
			Uds: "estructurarían",
		},
		Future: {
			yo: "estructuraré",
			tú: "estructurarás",
			Ud: "estructurará",
			nosotros: "estructuraremos",
			vosotros: "estructuraréis",
			Uds: "estructurarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "estructure",
			tú: "estructures",
			Ud: "estructure",
			nosotros: "estructuremos",
			vosotros: "estructuréis",
			Uds: "estructuren",
		},
		Imperfect: {
			yo: "estructurara",
			tú: "estructuraras",
			Ud: "estructurara",
			nosotros: "estructuráramos",
			vosotros: "estructurarais",
			Uds: "estructuraran",
		},
		Imperfect2: {
			yo: "estructurase",
			tú: "estructurases",
			Ud: "estructurase",
			nosotros: "estructurásemos",
			vosotros: "estructuraseis",
			Uds: "estructurasen",
		},
		Future: {
			yo: "estructurare",
			tú: "estructurares",
			Ud: "estructurare",
			nosotros: "estructuráremos",
			vosotros: "estructurareis",
			Uds: "estructuraren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "estructura",
			Ud: "estructure",
			nosotros: "estructuremos",
			vosotros: "estructurad",
			Uds: "estructuren",
		},
		Negative: {
			tú: "no estructures",
			Ud: "no estructure",
			nosotros: "no estructuremos",
			vosotros: "no estructuréis",
			Uds: "no estructuren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy estructurando",
			tú: "estás estructurando",
			Ud: "está estructurando",
			nosotros: "estamos estructurando",
			vosotros: "estáis estructurando",
			Uds: "están estructurando",
		},
		Preterite: {
			yo: "estuve estructurando",
			tú: "estuviste estructurando",
			Ud: "estuvo estructurando",
			nosotros: "estuvimos estructurando",
			vosotros: "estuvisteis estructurando",
			Uds: "estuvieron estructurando",
		},
		Imperfect: {
			Uds: "estaban estructurando",
			yo: "estaba estructurando",
			tú: "estabas estructurando",
			Ud: "estaba estructurando",
			nosotros: "estábamos estructurando",
			vosotros: "estabais estructurando",
		},
		Conditional: {
			yo: "estaría estructurando",
			tú: "estarías estructurando",
			Ud: "estaría estructurando",
			nosotros: "estaríamos estructurando",
			vosotros: "estaríais estructurando",
			Uds: "estarían estructurando",
		},
		Future: {
			yo: "estaré estructurando",
			tú: "estarás estructurando",
			Ud: "estará estructurando",
			nosotros: "estaremos estructurando",
			vosotros: "estaréis estructurando",
			Uds: "estarán estructurando",
		},
	},
	Perfect: {
		Present: {
			yo: "he estructurado",
			tú: "has estructurado",
			Ud: "ha estructurado",
			nosotros: "hemos estructurado",
			vosotros: "habéis estructurado",
			Uds: "han estructurado",
		},
		Preterite: {
			yo: "hube estructurado",
			tú: "hubiste estructurado",
			Ud: "hubo estructurado",
			nosotros: "hubimos estructurado",
			vosotros: "hubisteis estructurado",
			Uds: "hubieron estructurado",
		},
		Past: {
			yo: "había estructurado",
			tú: "habías estructurado",
			Ud: "había estructurado",
			nosotros: "habíamos estructurado",
			vosotros: "habíais estructurado",
			Uds: "habían estructurado",
		},
		Conditional: {
			yo: "habría estructurado",
			tú: "habrías estructurado",
			Ud: "habría estructurado",
			nosotros: "habríamos estructurado",
			vosotros: "habríais estructurado",
			Uds: "habrían estructurado",
		},
		Future: {
			yo: "habré estructurado",
			tú: "habrás estructurado",
			Ud: "habrá estructurado",
			nosotros: "habremos estructurado",
			vosotros: "habréis estructurado",
			Uds: "habrán estructurado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya estructurado",
			tú: "hayas estructurado",
			Ud: "haya estructurado",
			nosotros: "hayamos estructurado",
			vosotros: "hayáis estructurado",
			Uds: "hayan estructurado",
		},
		Past: {
			yo: "hubiera estructurado",
			tú: "hubieras estructurado",
			Ud: "hubiera estructurado",
			nosotros: "hubiéramos estructurado",
			vosotros: "hubierais estructurado",
			Uds: "hubieran estructurado",
		},
		Future: {
			yo: "hubiere estructurado",
			tú: "hubieres estructurado",
			Ud: "hubiere estructurado",
			nosotros: "hubiéremos estructurado",
			vosotros: "hubiereis estructurado",
			Uds: "hubieren estructurado",
		},
	},
}
