var etiquetar = {
	Indicative: {
		Present: {
			yo: "etiqueto",
			tú: "etiquetas",
			Ud: "etiqueta",
			nosotros: "etiquetamos",
			vosotros: "etiquetáis",
			Uds: "etiquetan",
		},
		Preterite: {
			yo: "etiqueté",
			tú: "etiquetaste",
			Ud: "etiquetó",
			nosotros: "etiquetamos",
			vosotros: "etiquetasteis",
			Uds: "etiquetaron",
		},
		Imperfect: {
			yo: "etiquetaba",
			tú: "etiquetabas",
			Ud: "etiquetaba",
			nosotros: "etiquetábamos",
			vosotros: "etiquetabais",
			Uds: "etiquetaban",
		},
		Conditional: {
			yo: "etiquetaría",
			tú: "etiquetarías",
			Ud: "etiquetaría",
			nosotros: "etiquetaríamos",
			vosotros: "etiquetaríais",
			Uds: "etiquetarían",
		},
		Future: {
			yo: "etiquetaré",
			tú: "etiquetarás",
			Ud: "etiquetará",
			nosotros: "etiquetaremos",
			vosotros: "etiquetaréis",
			Uds: "etiquetarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "etiquete",
			tú: "etiquetes",
			Ud: "etiquete",
			nosotros: "etiquetemos",
			vosotros: "etiquetéis",
			Uds: "etiqueten",
		},
		Imperfect: {
			yo: "etiquetara",
			tú: "etiquetaras",
			Ud: "etiquetara",
			nosotros: "etiquetáramos",
			vosotros: "etiquetarais",
			Uds: "etiquetaran",
		},
		Imperfect2: {
			yo: "etiquetase",
			tú: "etiquetases",
			Ud: "etiquetase",
			nosotros: "etiquetásemos",
			vosotros: "etiquetaseis",
			Uds: "etiquetasen",
		},
		Future: {
			yo: "etiquetare",
			tú: "etiquetares",
			Ud: "etiquetare",
			nosotros: "etiquetáremos",
			vosotros: "etiquetareis",
			Uds: "etiquetaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "etiqueta",
			Ud: "etiquete",
			nosotros: "etiquetemos",
			vosotros: "etiquetad",
			Uds: "etiqueten",
		},
		Negative: {
			tú: "no etiquetes",
			Ud: "no etiquete",
			nosotros: "no etiquetemos",
			vosotros: "no etiquetéis",
			Uds: "no etiqueten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy etiquetando",
			tú: "estás etiquetando",
			Ud: "está etiquetando",
			nosotros: "estamos etiquetando",
			vosotros: "estáis etiquetando",
			Uds: "están etiquetando",
		},
		Preterite: {
			yo: "estuve etiquetando",
			tú: "estuviste etiquetando",
			Ud: "estuvo etiquetando",
			nosotros: "estuvimos etiquetando",
			vosotros: "estuvisteis etiquetando",
			Uds: "estuvieron etiquetando",
		},
		Imperfect: {
			Uds: "estaban etiquetando",
			yo: "estaba etiquetando",
			tú: "estabas etiquetando",
			Ud: "estaba etiquetando",
			nosotros: "estábamos etiquetando",
			vosotros: "estabais etiquetando",
		},
		Conditional: {
			yo: "estaría etiquetando",
			tú: "estarías etiquetando",
			Ud: "estaría etiquetando",
			nosotros: "estaríamos etiquetando",
			vosotros: "estaríais etiquetando",
			Uds: "estarían etiquetando",
		},
		Future: {
			yo: "estaré etiquetando",
			tú: "estarás etiquetando",
			Ud: "estará etiquetando",
			nosotros: "estaremos etiquetando",
			vosotros: "estaréis etiquetando",
			Uds: "estarán etiquetando",
		},
	},
	Perfect: {
		Present: {
			yo: "he etiquetado",
			tú: "has etiquetado",
			Ud: "ha etiquetado",
			nosotros: "hemos etiquetado",
			vosotros: "habéis etiquetado",
			Uds: "han etiquetado",
		},
		Preterite: {
			yo: "hube etiquetado",
			tú: "hubiste etiquetado",
			Ud: "hubo etiquetado",
			nosotros: "hubimos etiquetado",
			vosotros: "hubisteis etiquetado",
			Uds: "hubieron etiquetado",
		},
		Past: {
			yo: "había etiquetado",
			tú: "habías etiquetado",
			Ud: "había etiquetado",
			nosotros: "habíamos etiquetado",
			vosotros: "habíais etiquetado",
			Uds: "habían etiquetado",
		},
		Conditional: {
			yo: "habría etiquetado",
			tú: "habrías etiquetado",
			Ud: "habría etiquetado",
			nosotros: "habríamos etiquetado",
			vosotros: "habríais etiquetado",
			Uds: "habrían etiquetado",
		},
		Future: {
			yo: "habré etiquetado",
			tú: "habrás etiquetado",
			Ud: "habrá etiquetado",
			nosotros: "habremos etiquetado",
			vosotros: "habréis etiquetado",
			Uds: "habrán etiquetado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya etiquetado",
			tú: "hayas etiquetado",
			Ud: "haya etiquetado",
			nosotros: "hayamos etiquetado",
			vosotros: "hayáis etiquetado",
			Uds: "hayan etiquetado",
		},
		Past: {
			yo: "hubiera etiquetado",
			tú: "hubieras etiquetado",
			Ud: "hubiera etiquetado",
			nosotros: "hubiéramos etiquetado",
			vosotros: "hubierais etiquetado",
			Uds: "hubieran etiquetado",
		},
		Future: {
			yo: "hubiere etiquetado",
			tú: "hubieres etiquetado",
			Ud: "hubiere etiquetado",
			nosotros: "hubiéremos etiquetado",
			vosotros: "hubiereis etiquetado",
			Uds: "hubieren etiquetado",
		},
	},
}
