var exacerbar = {
	Indicative: {
		Present: {
			yo: "exacerbo",
			tú: "exacerbas",
			Ud: "exacerba",
			nosotros: "exacerbamos",
			vosotros: "exacerbáis",
			Uds: "exacerban",
		},
		Preterite: {
			yo: "exacerbé",
			tú: "exacerbaste",
			Ud: "exacerbó",
			nosotros: "exacerbamos",
			vosotros: "exacerbasteis",
			Uds: "exacerbaron",
		},
		Imperfect: {
			yo: "exacerbaba",
			tú: "exacerbabas",
			Ud: "exacerbaba",
			nosotros: "exacerbábamos",
			vosotros: "exacerbabais",
			Uds: "exacerbaban",
		},
		Conditional: {
			yo: "exacerbaría",
			tú: "exacerbarías",
			Ud: "exacerbaría",
			nosotros: "exacerbaríamos",
			vosotros: "exacerbaríais",
			Uds: "exacerbarían",
		},
		Future: {
			yo: "exacerbaré",
			tú: "exacerbarás",
			Ud: "exacerbará",
			nosotros: "exacerbaremos",
			vosotros: "exacerbaréis",
			Uds: "exacerbarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "exacerbe",
			tú: "exacerbes",
			Ud: "exacerbe",
			nosotros: "exacerbemos",
			vosotros: "exacerbéis",
			Uds: "exacerben",
		},
		Imperfect: {
			yo: "exacerbara",
			tú: "exacerbaras",
			Ud: "exacerbara",
			nosotros: "exacerbáramos",
			vosotros: "exacerbarais",
			Uds: "exacerbaran",
		},
		Imperfect2: {
			yo: "exacerbase",
			tú: "exacerbases",
			Ud: "exacerbase",
			nosotros: "exacerbásemos",
			vosotros: "exacerbaseis",
			Uds: "exacerbasen",
		},
		Future: {
			yo: "exacerbare",
			tú: "exacerbares",
			Ud: "exacerbare",
			nosotros: "exacerbáremos",
			vosotros: "exacerbareis",
			Uds: "exacerbaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "exacerba",
			Ud: "exacerbe",
			nosotros: "exacerbemos",
			vosotros: "exacerbad",
			Uds: "exacerben",
		},
		Negative: {
			tú: "no exacerbes",
			Ud: "no exacerbe",
			nosotros: "no exacerbemos",
			vosotros: "no exacerbéis",
			Uds: "no exacerben",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy exacerbando",
			tú: "estás exacerbando",
			Ud: "está exacerbando",
			nosotros: "estamos exacerbando",
			vosotros: "estáis exacerbando",
			Uds: "están exacerbando",
		},
		Preterite: {
			yo: "estuve exacerbando",
			tú: "estuviste exacerbando",
			Ud: "estuvo exacerbando",
			nosotros: "estuvimos exacerbando",
			vosotros: "estuvisteis exacerbando",
			Uds: "estuvieron exacerbando",
		},
		Imperfect: {
			Uds: "estaban exacerbando",
			yo: "estaba exacerbando",
			tú: "estabas exacerbando",
			Ud: "estaba exacerbando",
			nosotros: "estábamos exacerbando",
			vosotros: "estabais exacerbando",
		},
		Conditional: {
			yo: "estaría exacerbando",
			tú: "estarías exacerbando",
			Ud: "estaría exacerbando",
			nosotros: "estaríamos exacerbando",
			vosotros: "estaríais exacerbando",
			Uds: "estarían exacerbando",
		},
		Future: {
			yo: "estaré exacerbando",
			tú: "estarás exacerbando",
			Ud: "estará exacerbando",
			nosotros: "estaremos exacerbando",
			vosotros: "estaréis exacerbando",
			Uds: "estarán exacerbando",
		},
	},
	Perfect: {
		Present: {
			yo: "he exacerbado",
			tú: "has exacerbado",
			Ud: "ha exacerbado",
			nosotros: "hemos exacerbado",
			vosotros: "habéis exacerbado",
			Uds: "han exacerbado",
		},
		Preterite: {
			yo: "hube exacerbado",
			tú: "hubiste exacerbado",
			Ud: "hubo exacerbado",
			nosotros: "hubimos exacerbado",
			vosotros: "hubisteis exacerbado",
			Uds: "hubieron exacerbado",
		},
		Past: {
			yo: "había exacerbado",
			tú: "habías exacerbado",
			Ud: "había exacerbado",
			nosotros: "habíamos exacerbado",
			vosotros: "habíais exacerbado",
			Uds: "habían exacerbado",
		},
		Conditional: {
			yo: "habría exacerbado",
			tú: "habrías exacerbado",
			Ud: "habría exacerbado",
			nosotros: "habríamos exacerbado",
			vosotros: "habríais exacerbado",
			Uds: "habrían exacerbado",
		},
		Future: {
			yo: "habré exacerbado",
			tú: "habrás exacerbado",
			Ud: "habrá exacerbado",
			nosotros: "habremos exacerbado",
			vosotros: "habréis exacerbado",
			Uds: "habrán exacerbado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya exacerbado",
			tú: "hayas exacerbado",
			Ud: "haya exacerbado",
			nosotros: "hayamos exacerbado",
			vosotros: "hayáis exacerbado",
			Uds: "hayan exacerbado",
		},
		Past: {
			yo: "hubiera exacerbado",
			tú: "hubieras exacerbado",
			Ud: "hubiera exacerbado",
			nosotros: "hubiéramos exacerbado",
			vosotros: "hubierais exacerbado",
			Uds: "hubieran exacerbado",
		},
		Future: {
			yo: "hubiere exacerbado",
			tú: "hubieres exacerbado",
			Ud: "hubiere exacerbado",
			nosotros: "hubiéremos exacerbado",
			vosotros: "hubiereis exacerbado",
			Uds: "hubieren exacerbado",
		},
	},
}
