var exagerar = {
	Indicative: {
		Present: {
			yo: "exagero",
			tú: "exageras",
			Ud: "exagera",
			nosotros: "exageramos",
			vosotros: "exageráis",
			Uds: "exageran",
		},
		Preterite: {
			yo: "exageré",
			tú: "exageraste",
			Ud: "exageró",
			nosotros: "exageramos",
			vosotros: "exagerasteis",
			Uds: "exageraron",
		},
		Imperfect: {
			yo: "exageraba",
			tú: "exagerabas",
			Ud: "exageraba",
			nosotros: "exagerábamos",
			vosotros: "exagerabais",
			Uds: "exageraban",
		},
		Conditional: {
			yo: "exageraría",
			tú: "exagerarías",
			Ud: "exageraría",
			nosotros: "exageraríamos",
			vosotros: "exageraríais",
			Uds: "exagerarían",
		},
		Future: {
			yo: "exageraré",
			tú: "exagerarás",
			Ud: "exagerará",
			nosotros: "exageraremos",
			vosotros: "exageraréis",
			Uds: "exagerarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "exagere",
			tú: "exageres",
			Ud: "exagere",
			nosotros: "exageremos",
			vosotros: "exageréis",
			Uds: "exageren",
		},
		Imperfect: {
			yo: "exagerara",
			tú: "exageraras",
			Ud: "exagerara",
			nosotros: "exageráramos",
			vosotros: "exagerarais",
			Uds: "exageraran",
		},
		Imperfect2: {
			yo: "exagerase",
			tú: "exagerases",
			Ud: "exagerase",
			nosotros: "exagerásemos",
			vosotros: "exageraseis",
			Uds: "exagerasen",
		},
		Future: {
			yo: "exagerare",
			tú: "exagerares",
			Ud: "exagerare",
			nosotros: "exageráremos",
			vosotros: "exagerareis",
			Uds: "exageraren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "exagera",
			Ud: "exagere",
			nosotros: "exageremos",
			vosotros: "exagerad",
			Uds: "exageren",
		},
		Negative: {
			tú: "no exageres",
			Ud: "no exagere",
			nosotros: "no exageremos",
			vosotros: "no exageréis",
			Uds: "no exageren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy exagerando",
			tú: "estás exagerando",
			Ud: "está exagerando",
			nosotros: "estamos exagerando",
			vosotros: "estáis exagerando",
			Uds: "están exagerando",
		},
		Preterite: {
			yo: "estuve exagerando",
			tú: "estuviste exagerando",
			Ud: "estuvo exagerando",
			nosotros: "estuvimos exagerando",
			vosotros: "estuvisteis exagerando",
			Uds: "estuvieron exagerando",
		},
		Imperfect: {
			Uds: "estaban exagerando",
			yo: "estaba exagerando",
			tú: "estabas exagerando",
			Ud: "estaba exagerando",
			nosotros: "estábamos exagerando",
			vosotros: "estabais exagerando",
		},
		Conditional: {
			yo: "estaría exagerando",
			tú: "estarías exagerando",
			Ud: "estaría exagerando",
			nosotros: "estaríamos exagerando",
			vosotros: "estaríais exagerando",
			Uds: "estarían exagerando",
		},
		Future: {
			yo: "estaré exagerando",
			tú: "estarás exagerando",
			Ud: "estará exagerando",
			nosotros: "estaremos exagerando",
			vosotros: "estaréis exagerando",
			Uds: "estarán exagerando",
		},
	},
	Perfect: {
		Present: {
			yo: "he exagerado",
			tú: "has exagerado",
			Ud: "ha exagerado",
			nosotros: "hemos exagerado",
			vosotros: "habéis exagerado",
			Uds: "han exagerado",
		},
		Preterite: {
			yo: "hube exagerado",
			tú: "hubiste exagerado",
			Ud: "hubo exagerado",
			nosotros: "hubimos exagerado",
			vosotros: "hubisteis exagerado",
			Uds: "hubieron exagerado",
		},
		Past: {
			yo: "había exagerado",
			tú: "habías exagerado",
			Ud: "había exagerado",
			nosotros: "habíamos exagerado",
			vosotros: "habíais exagerado",
			Uds: "habían exagerado",
		},
		Conditional: {
			yo: "habría exagerado",
			tú: "habrías exagerado",
			Ud: "habría exagerado",
			nosotros: "habríamos exagerado",
			vosotros: "habríais exagerado",
			Uds: "habrían exagerado",
		},
		Future: {
			yo: "habré exagerado",
			tú: "habrás exagerado",
			Ud: "habrá exagerado",
			nosotros: "habremos exagerado",
			vosotros: "habréis exagerado",
			Uds: "habrán exagerado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya exagerado",
			tú: "hayas exagerado",
			Ud: "haya exagerado",
			nosotros: "hayamos exagerado",
			vosotros: "hayáis exagerado",
			Uds: "hayan exagerado",
		},
		Past: {
			yo: "hubiera exagerado",
			tú: "hubieras exagerado",
			Ud: "hubiera exagerado",
			nosotros: "hubiéramos exagerado",
			vosotros: "hubierais exagerado",
			Uds: "hubieran exagerado",
		},
		Future: {
			yo: "hubiere exagerado",
			tú: "hubieres exagerado",
			Ud: "hubiere exagerado",
			nosotros: "hubiéremos exagerado",
			vosotros: "hubiereis exagerado",
			Uds: "hubieren exagerado",
		},
	},
}
