var exaltar = {
	Indicative: {
		Present: {
			yo: "exalto",
			tú: "exaltas",
			Ud: "exalta",
			nosotros: "exaltamos",
			vosotros: "exaltáis",
			Uds: "exaltan",
		},
		Preterite: {
			yo: "exalté",
			tú: "exaltaste",
			Ud: "exaltó",
			nosotros: "exaltamos",
			vosotros: "exaltasteis",
			Uds: "exaltaron",
		},
		Imperfect: {
			yo: "exaltaba",
			tú: "exaltabas",
			Ud: "exaltaba",
			nosotros: "exaltábamos",
			vosotros: "exaltabais",
			Uds: "exaltaban",
		},
		Conditional: {
			yo: "exaltaría",
			tú: "exaltarías",
			Ud: "exaltaría",
			nosotros: "exaltaríamos",
			vosotros: "exaltaríais",
			Uds: "exaltarían",
		},
		Future: {
			yo: "exaltaré",
			tú: "exaltarás",
			Ud: "exaltará",
			nosotros: "exaltaremos",
			vosotros: "exaltaréis",
			Uds: "exaltarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "exalte",
			tú: "exaltes",
			Ud: "exalte",
			nosotros: "exaltemos",
			vosotros: "exaltéis",
			Uds: "exalten",
		},
		Imperfect: {
			yo: "exaltara",
			tú: "exaltaras",
			Ud: "exaltara",
			nosotros: "exaltáramos",
			vosotros: "exaltarais",
			Uds: "exaltaran",
		},
		Imperfect2: {
			yo: "exaltase",
			tú: "exaltases",
			Ud: "exaltase",
			nosotros: "exaltásemos",
			vosotros: "exaltaseis",
			Uds: "exaltasen",
		},
		Future: {
			yo: "exaltare",
			tú: "exaltares",
			Ud: "exaltare",
			nosotros: "exaltáremos",
			vosotros: "exaltareis",
			Uds: "exaltaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "exalta",
			Ud: "exalte",
			nosotros: "exaltemos",
			vosotros: "exaltad",
			Uds: "exalten",
		},
		Negative: {
			tú: "no exaltes",
			Ud: "no exalte",
			nosotros: "no exaltemos",
			vosotros: "no exaltéis",
			Uds: "no exalten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy exaltando",
			tú: "estás exaltando",
			Ud: "está exaltando",
			nosotros: "estamos exaltando",
			vosotros: "estáis exaltando",
			Uds: "están exaltando",
		},
		Preterite: {
			yo: "estuve exaltando",
			tú: "estuviste exaltando",
			Ud: "estuvo exaltando",
			nosotros: "estuvimos exaltando",
			vosotros: "estuvisteis exaltando",
			Uds: "estuvieron exaltando",
		},
		Imperfect: {
			Uds: "estaban exaltando",
			yo: "estaba exaltando",
			tú: "estabas exaltando",
			Ud: "estaba exaltando",
			nosotros: "estábamos exaltando",
			vosotros: "estabais exaltando",
		},
		Conditional: {
			yo: "estaría exaltando",
			tú: "estarías exaltando",
			Ud: "estaría exaltando",
			nosotros: "estaríamos exaltando",
			vosotros: "estaríais exaltando",
			Uds: "estarían exaltando",
		},
		Future: {
			yo: "estaré exaltando",
			tú: "estarás exaltando",
			Ud: "estará exaltando",
			nosotros: "estaremos exaltando",
			vosotros: "estaréis exaltando",
			Uds: "estarán exaltando",
		},
	},
	Perfect: {
		Present: {
			yo: "he exaltado",
			tú: "has exaltado",
			Ud: "ha exaltado",
			nosotros: "hemos exaltado",
			vosotros: "habéis exaltado",
			Uds: "han exaltado",
		},
		Preterite: {
			yo: "hube exaltado",
			tú: "hubiste exaltado",
			Ud: "hubo exaltado",
			nosotros: "hubimos exaltado",
			vosotros: "hubisteis exaltado",
			Uds: "hubieron exaltado",
		},
		Past: {
			yo: "había exaltado",
			tú: "habías exaltado",
			Ud: "había exaltado",
			nosotros: "habíamos exaltado",
			vosotros: "habíais exaltado",
			Uds: "habían exaltado",
		},
		Conditional: {
			yo: "habría exaltado",
			tú: "habrías exaltado",
			Ud: "habría exaltado",
			nosotros: "habríamos exaltado",
			vosotros: "habríais exaltado",
			Uds: "habrían exaltado",
		},
		Future: {
			yo: "habré exaltado",
			tú: "habrás exaltado",
			Ud: "habrá exaltado",
			nosotros: "habremos exaltado",
			vosotros: "habréis exaltado",
			Uds: "habrán exaltado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya exaltado",
			tú: "hayas exaltado",
			Ud: "haya exaltado",
			nosotros: "hayamos exaltado",
			vosotros: "hayáis exaltado",
			Uds: "hayan exaltado",
		},
		Past: {
			yo: "hubiera exaltado",
			tú: "hubieras exaltado",
			Ud: "hubiera exaltado",
			nosotros: "hubiéramos exaltado",
			vosotros: "hubierais exaltado",
			Uds: "hubieran exaltado",
		},
		Future: {
			yo: "hubiere exaltado",
			tú: "hubieres exaltado",
			Ud: "hubiere exaltado",
			nosotros: "hubiéremos exaltado",
			vosotros: "hubiereis exaltado",
			Uds: "hubieren exaltado",
		},
	},
}
