var examinar = {
	Indicative: {
		Present: {
			yo: "examino",
			tú: "examinas",
			Ud: "examina",
			nosotros: "examinamos",
			vosotros: "examináis",
			Uds: "examinan",
		},
		Preterite: {
			yo: "examiné",
			tú: "examinaste",
			Ud: "examinó",
			nosotros: "examinamos",
			vosotros: "examinasteis",
			Uds: "examinaron",
		},
		Imperfect: {
			yo: "examinaba",
			tú: "examinabas",
			Ud: "examinaba",
			nosotros: "examinábamos",
			vosotros: "examinabais",
			Uds: "examinaban",
		},
		Conditional: {
			yo: "examinaría",
			tú: "examinarías",
			Ud: "examinaría",
			nosotros: "examinaríamos",
			vosotros: "examinaríais",
			Uds: "examinarían",
		},
		Future: {
			yo: "examinaré",
			tú: "examinarás",
			Ud: "examinará",
			nosotros: "examinaremos",
			vosotros: "examinaréis",
			Uds: "examinarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "examine",
			tú: "examines",
			Ud: "examine",
			nosotros: "examinemos",
			vosotros: "examinéis",
			Uds: "examinen",
		},
		Imperfect: {
			yo: "examinara",
			tú: "examinaras",
			Ud: "examinara",
			nosotros: "examináramos",
			vosotros: "examinarais",
			Uds: "examinaran",
		},
		Imperfect2: {
			yo: "examinase",
			tú: "examinases",
			Ud: "examinase",
			nosotros: "examinásemos",
			vosotros: "examinaseis",
			Uds: "examinasen",
		},
		Future: {
			yo: "examinare",
			tú: "examinares",
			Ud: "examinare",
			nosotros: "examináremos",
			vosotros: "examinareis",
			Uds: "examinaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "examina",
			Ud: "examine",
			nosotros: "examinemos",
			vosotros: "examinad",
			Uds: "examinen",
		},
		Negative: {
			tú: "no examines",
			Ud: "no examine",
			nosotros: "no examinemos",
			vosotros: "no examinéis",
			Uds: "no examinen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy examinando",
			tú: "estás examinando",
			Ud: "está examinando",
			nosotros: "estamos examinando",
			vosotros: "estáis examinando",
			Uds: "están examinando",
		},
		Preterite: {
			yo: "estuve examinando",
			tú: "estuviste examinando",
			Ud: "estuvo examinando",
			nosotros: "estuvimos examinando",
			vosotros: "estuvisteis examinando",
			Uds: "estuvieron examinando",
		},
		Imperfect: {
			Uds: "estaban examinando",
			yo: "estaba examinando",
			tú: "estabas examinando",
			Ud: "estaba examinando",
			nosotros: "estábamos examinando",
			vosotros: "estabais examinando",
		},
		Conditional: {
			yo: "estaría examinando",
			tú: "estarías examinando",
			Ud: "estaría examinando",
			nosotros: "estaríamos examinando",
			vosotros: "estaríais examinando",
			Uds: "estarían examinando",
		},
		Future: {
			yo: "estaré examinando",
			tú: "estarás examinando",
			Ud: "estará examinando",
			nosotros: "estaremos examinando",
			vosotros: "estaréis examinando",
			Uds: "estarán examinando",
		},
	},
	Perfect: {
		Present: {
			yo: "he examinado",
			tú: "has examinado",
			Ud: "ha examinado",
			nosotros: "hemos examinado",
			vosotros: "habéis examinado",
			Uds: "han examinado",
		},
		Preterite: {
			yo: "hube examinado",
			tú: "hubiste examinado",
			Ud: "hubo examinado",
			nosotros: "hubimos examinado",
			vosotros: "hubisteis examinado",
			Uds: "hubieron examinado",
		},
		Past: {
			yo: "había examinado",
			tú: "habías examinado",
			Ud: "había examinado",
			nosotros: "habíamos examinado",
			vosotros: "habíais examinado",
			Uds: "habían examinado",
		},
		Conditional: {
			yo: "habría examinado",
			tú: "habrías examinado",
			Ud: "habría examinado",
			nosotros: "habríamos examinado",
			vosotros: "habríais examinado",
			Uds: "habrían examinado",
		},
		Future: {
			yo: "habré examinado",
			tú: "habrás examinado",
			Ud: "habrá examinado",
			nosotros: "habremos examinado",
			vosotros: "habréis examinado",
			Uds: "habrán examinado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya examinado",
			tú: "hayas examinado",
			Ud: "haya examinado",
			nosotros: "hayamos examinado",
			vosotros: "hayáis examinado",
			Uds: "hayan examinado",
		},
		Past: {
			yo: "hubiera examinado",
			tú: "hubieras examinado",
			Ud: "hubiera examinado",
			nosotros: "hubiéramos examinado",
			vosotros: "hubierais examinado",
			Uds: "hubieran examinado",
		},
		Future: {
			yo: "hubiere examinado",
			tú: "hubieres examinado",
			Ud: "hubiere examinado",
			nosotros: "hubiéremos examinado",
			vosotros: "hubiereis examinado",
			Uds: "hubieren examinado",
		},
	},
}
