var excavar = {
	Indicative: {
		Present: {
			yo: "excavo",
			tú: "excavas",
			Ud: "excava",
			nosotros: "excavamos",
			vosotros: "excaváis",
			Uds: "excavan",
		},
		Preterite: {
			yo: "excavé",
			tú: "excavaste",
			Ud: "excavó",
			nosotros: "excavamos",
			vosotros: "excavasteis",
			Uds: "excavaron",
		},
		Imperfect: {
			yo: "excavaba",
			tú: "excavabas",
			Ud: "excavaba",
			nosotros: "excavábamos",
			vosotros: "excavabais",
			Uds: "excavaban",
		},
		Conditional: {
			yo: "excavaría",
			tú: "excavarías",
			Ud: "excavaría",
			nosotros: "excavaríamos",
			vosotros: "excavaríais",
			Uds: "excavarían",
		},
		Future: {
			yo: "excavaré",
			tú: "excavarás",
			Ud: "excavará",
			nosotros: "excavaremos",
			vosotros: "excavaréis",
			Uds: "excavarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "excave",
			tú: "excaves",
			Ud: "excave",
			nosotros: "excavemos",
			vosotros: "excavéis",
			Uds: "excaven",
		},
		Imperfect: {
			yo: "excavara",
			tú: "excavaras",
			Ud: "excavara",
			nosotros: "excaváramos",
			vosotros: "excavarais",
			Uds: "excavaran",
		},
		Imperfect2: {
			yo: "excavase",
			tú: "excavases",
			Ud: "excavase",
			nosotros: "excavásemos",
			vosotros: "excavaseis",
			Uds: "excavasen",
		},
		Future: {
			yo: "excavare",
			tú: "excavares",
			Ud: "excavare",
			nosotros: "excaváremos",
			vosotros: "excavareis",
			Uds: "excavaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "excava",
			Ud: "excave",
			nosotros: "excavemos",
			vosotros: "excavad",
			Uds: "excaven",
		},
		Negative: {
			tú: "no excaves",
			Ud: "no excave",
			nosotros: "no excavemos",
			vosotros: "no excavéis",
			Uds: "no excaven",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy excavando",
			tú: "estás excavando",
			Ud: "está excavando",
			nosotros: "estamos excavando",
			vosotros: "estáis excavando",
			Uds: "están excavando",
		},
		Preterite: {
			yo: "estuve excavando",
			tú: "estuviste excavando",
			Ud: "estuvo excavando",
			nosotros: "estuvimos excavando",
			vosotros: "estuvisteis excavando",
			Uds: "estuvieron excavando",
		},
		Imperfect: {
			Uds: "estaban excavando",
			yo: "estaba excavando",
			tú: "estabas excavando",
			Ud: "estaba excavando",
			nosotros: "estábamos excavando",
			vosotros: "estabais excavando",
		},
		Conditional: {
			yo: "estaría excavando",
			tú: "estarías excavando",
			Ud: "estaría excavando",
			nosotros: "estaríamos excavando",
			vosotros: "estaríais excavando",
			Uds: "estarían excavando",
		},
		Future: {
			yo: "estaré excavando",
			tú: "estarás excavando",
			Ud: "estará excavando",
			nosotros: "estaremos excavando",
			vosotros: "estaréis excavando",
			Uds: "estarán excavando",
		},
	},
	Perfect: {
		Present: {
			yo: "he excavado",
			tú: "has excavado",
			Ud: "ha excavado",
			nosotros: "hemos excavado",
			vosotros: "habéis excavado",
			Uds: "han excavado",
		},
		Preterite: {
			yo: "hube excavado",
			tú: "hubiste excavado",
			Ud: "hubo excavado",
			nosotros: "hubimos excavado",
			vosotros: "hubisteis excavado",
			Uds: "hubieron excavado",
		},
		Past: {
			yo: "había excavado",
			tú: "habías excavado",
			Ud: "había excavado",
			nosotros: "habíamos excavado",
			vosotros: "habíais excavado",
			Uds: "habían excavado",
		},
		Conditional: {
			yo: "habría excavado",
			tú: "habrías excavado",
			Ud: "habría excavado",
			nosotros: "habríamos excavado",
			vosotros: "habríais excavado",
			Uds: "habrían excavado",
		},
		Future: {
			yo: "habré excavado",
			tú: "habrás excavado",
			Ud: "habrá excavado",
			nosotros: "habremos excavado",
			vosotros: "habréis excavado",
			Uds: "habrán excavado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya excavado",
			tú: "hayas excavado",
			Ud: "haya excavado",
			nosotros: "hayamos excavado",
			vosotros: "hayáis excavado",
			Uds: "hayan excavado",
		},
		Past: {
			yo: "hubiera excavado",
			tú: "hubieras excavado",
			Ud: "hubiera excavado",
			nosotros: "hubiéramos excavado",
			vosotros: "hubierais excavado",
			Uds: "hubieran excavado",
		},
		Future: {
			yo: "hubiere excavado",
			tú: "hubieres excavado",
			Ud: "hubiere excavado",
			nosotros: "hubiéremos excavado",
			vosotros: "hubiereis excavado",
			Uds: "hubieren excavado",
		},
	},
}
