var exhibir = {
	Indicative: {
		Present: {
			yo: "exhibo",
			tú: "exhibes",
			Ud: "exhibe",
			nosotros: "exhibimos",
			vosotros: "exhibís",
			Uds: "exhiben",
		},
		Preterite: {
			yo: "exhibí",
			tú: "exhibiste",
			Ud: "exhibió",
			nosotros: "exhibimos",
			vosotros: "exhibisteis",
			Uds: "exhibieron",
		},
		Imperfect: {
			yo: "exhibía",
			tú: "exhibías",
			Ud: "exhibía",
			nosotros: "exhibíamos",
			vosotros: "exhibíais",
			Uds: "exhibían",
		},
		Conditional: {
			yo: "exhibiría",
			tú: "exhibirías",
			Ud: "exhibiría",
			nosotros: "exhibiríamos",
			vosotros: "exhibiríais",
			Uds: "exhibirían",
		},
		Future: {
			yo: "exhibiré",
			tú: "exhibirás",
			Ud: "exhibirá",
			nosotros: "exhibiremos",
			vosotros: "exhibiréis",
			Uds: "exhibirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "exhiba",
			tú: "exhibas",
			Ud: "exhiba",
			nosotros: "exhibamos",
			vosotros: "exhibáis",
			Uds: "exhiban",
		},
		Imperfect: {
			yo: "exhibiera",
			tú: "exhibieras",
			Ud: "exhibiera",
			nosotros: "exhibiéramos",
			vosotros: "exhibierais",
			Uds: "exhibieran",
		},
		Imperfect2: {
			yo: "exhibiese",
			tú: "exhibieses",
			Ud: "exhibiese",
			nosotros: "exhibiésemos",
			vosotros: "exhibieseis",
			Uds: "exhibiesen",
		},
		Future: {
			yo: "exhibiere",
			tú: "exhibieres",
			Ud: "exhibiere",
			nosotros: "exhibiéremos",
			vosotros: "exhibiereis",
			Uds: "exhibieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "exhibe",
			Ud: "exhiba",
			nosotros: "exhibamos",
			vosotros: "exhibid",
			Uds: "exhiban",
		},
		Negative: {
			tú: "no exhibas",
			Ud: "no exhiba",
			nosotros: "no exhibamos",
			vosotros: "no exhibáis",
			Uds: "no exhiban",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy exhibiendo",
			tú: "estás exhibiendo",
			Ud: "está exhibiendo",
			nosotros: "estamos exhibiendo",
			vosotros: "estáis exhibiendo",
			Uds: "están exhibiendo",
		},
		Preterite: {
			yo: "estuve exhibiendo",
			tú: "estuviste exhibiendo",
			Ud: "estuvo exhibiendo",
			nosotros: "estuvimos exhibiendo",
			vosotros: "estuvisteis exhibiendo",
			Uds: "estuvieron exhibiendo",
		},
		Imperfect: {
			Uds: "estaban exhibiendo",
			yo: "estaba exhibiendo",
			tú: "estabas exhibiendo",
			Ud: "estaba exhibiendo",
			nosotros: "estábamos exhibiendo",
			vosotros: "estabais exhibiendo",
		},
		Conditional: {
			yo: "estaría exhibiendo",
			tú: "estarías exhibiendo",
			Ud: "estaría exhibiendo",
			nosotros: "estaríamos exhibiendo",
			vosotros: "estaríais exhibiendo",
			Uds: "estarían exhibiendo",
		},
		Future: {
			yo: "estaré exhibiendo",
			tú: "estarás exhibiendo",
			Ud: "estará exhibiendo",
			nosotros: "estaremos exhibiendo",
			vosotros: "estaréis exhibiendo",
			Uds: "estarán exhibiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he exhibido",
			tú: "has exhibido",
			Ud: "ha exhibido",
			nosotros: "hemos exhibido",
			vosotros: "habéis exhibido",
			Uds: "han exhibido",
		},
		Preterite: {
			yo: "hube exhibido",
			tú: "hubiste exhibido",
			Ud: "hubo exhibido",
			nosotros: "hubimos exhibido",
			vosotros: "hubisteis exhibido",
			Uds: "hubieron exhibido",
		},
		Past: {
			yo: "había exhibido",
			tú: "habías exhibido",
			Ud: "había exhibido",
			nosotros: "habíamos exhibido",
			vosotros: "habíais exhibido",
			Uds: "habían exhibido",
		},
		Conditional: {
			yo: "habría exhibido",
			tú: "habrías exhibido",
			Ud: "habría exhibido",
			nosotros: "habríamos exhibido",
			vosotros: "habríais exhibido",
			Uds: "habrían exhibido",
		},
		Future: {
			yo: "habré exhibido",
			tú: "habrás exhibido",
			Ud: "habrá exhibido",
			nosotros: "habremos exhibido",
			vosotros: "habréis exhibido",
			Uds: "habrán exhibido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya exhibido",
			tú: "hayas exhibido",
			Ud: "haya exhibido",
			nosotros: "hayamos exhibido",
			vosotros: "hayáis exhibido",
			Uds: "hayan exhibido",
		},
		Past: {
			yo: "hubiera exhibido",
			tú: "hubieras exhibido",
			Ud: "hubiera exhibido",
			nosotros: "hubiéramos exhibido",
			vosotros: "hubierais exhibido",
			Uds: "hubieran exhibido",
		},
		Future: {
			yo: "hubiere exhibido",
			tú: "hubieres exhibido",
			Ud: "hubiere exhibido",
			nosotros: "hubiéremos exhibido",
			vosotros: "hubiereis exhibido",
			Uds: "hubieren exhibido",
		},
	},
}
