var exhumar = {
	Indicative: {
		Present: {
			yo: "exhumo",
			tú: "exhumas",
			Ud: "exhuma",
			nosotros: "exhumamos",
			vosotros: "exhumáis",
			Uds: "exhuman",
		},
		Preterite: {
			yo: "exhumé",
			tú: "exhumaste",
			Ud: "exhumó",
			nosotros: "exhumamos",
			vosotros: "exhumasteis",
			Uds: "exhumaron",
		},
		Imperfect: {
			yo: "exhumaba",
			tú: "exhumabas",
			Ud: "exhumaba",
			nosotros: "exhumábamos",
			vosotros: "exhumabais",
			Uds: "exhumaban",
		},
		Conditional: {
			yo: "exhumaría",
			tú: "exhumarías",
			Ud: "exhumaría",
			nosotros: "exhumaríamos",
			vosotros: "exhumaríais",
			Uds: "exhumarían",
		},
		Future: {
			yo: "exhumaré",
			tú: "exhumarás",
			Ud: "exhumará",
			nosotros: "exhumaremos",
			vosotros: "exhumaréis",
			Uds: "exhumarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "exhume",
			tú: "exhumes",
			Ud: "exhume",
			nosotros: "exhumemos",
			vosotros: "exhuméis",
			Uds: "exhumen",
		},
		Imperfect: {
			yo: "exhumara",
			tú: "exhumaras",
			Ud: "exhumara",
			nosotros: "exhumáramos",
			vosotros: "exhumarais",
			Uds: "exhumaran",
		},
		Imperfect2: {
			yo: "exhumase",
			tú: "exhumases",
			Ud: "exhumase",
			nosotros: "exhumásemos",
			vosotros: "exhumaseis",
			Uds: "exhumasen",
		},
		Future: {
			yo: "exhumare",
			tú: "exhumares",
			Ud: "exhumare",
			nosotros: "exhumáremos",
			vosotros: "exhumareis",
			Uds: "exhumaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "exhuma",
			Ud: "exhume",
			nosotros: "exhumemos",
			vosotros: "exhumad",
			Uds: "exhumen",
		},
		Negative: {
			tú: "no exhumes",
			Ud: "no exhume",
			nosotros: "no exhumemos",
			vosotros: "no exhuméis",
			Uds: "no exhumen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy exhumando",
			tú: "estás exhumando",
			Ud: "está exhumando",
			nosotros: "estamos exhumando",
			vosotros: "estáis exhumando",
			Uds: "están exhumando",
		},
		Preterite: {
			yo: "estuve exhumando",
			tú: "estuviste exhumando",
			Ud: "estuvo exhumando",
			nosotros: "estuvimos exhumando",
			vosotros: "estuvisteis exhumando",
			Uds: "estuvieron exhumando",
		},
		Imperfect: {
			Uds: "estaban exhumando",
			yo: "estaba exhumando",
			tú: "estabas exhumando",
			Ud: "estaba exhumando",
			nosotros: "estábamos exhumando",
			vosotros: "estabais exhumando",
		},
		Conditional: {
			yo: "estaría exhumando",
			tú: "estarías exhumando",
			Ud: "estaría exhumando",
			nosotros: "estaríamos exhumando",
			vosotros: "estaríais exhumando",
			Uds: "estarían exhumando",
		},
		Future: {
			yo: "estaré exhumando",
			tú: "estarás exhumando",
			Ud: "estará exhumando",
			nosotros: "estaremos exhumando",
			vosotros: "estaréis exhumando",
			Uds: "estarán exhumando",
		},
	},
	Perfect: {
		Present: {
			yo: "he exhumado",
			tú: "has exhumado",
			Ud: "ha exhumado",
			nosotros: "hemos exhumado",
			vosotros: "habéis exhumado",
			Uds: "han exhumado",
		},
		Preterite: {
			yo: "hube exhumado",
			tú: "hubiste exhumado",
			Ud: "hubo exhumado",
			nosotros: "hubimos exhumado",
			vosotros: "hubisteis exhumado",
			Uds: "hubieron exhumado",
		},
		Past: {
			yo: "había exhumado",
			tú: "habías exhumado",
			Ud: "había exhumado",
			nosotros: "habíamos exhumado",
			vosotros: "habíais exhumado",
			Uds: "habían exhumado",
		},
		Conditional: {
			yo: "habría exhumado",
			tú: "habrías exhumado",
			Ud: "habría exhumado",
			nosotros: "habríamos exhumado",
			vosotros: "habríais exhumado",
			Uds: "habrían exhumado",
		},
		Future: {
			yo: "habré exhumado",
			tú: "habrás exhumado",
			Ud: "habrá exhumado",
			nosotros: "habremos exhumado",
			vosotros: "habréis exhumado",
			Uds: "habrán exhumado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya exhumado",
			tú: "hayas exhumado",
			Ud: "haya exhumado",
			nosotros: "hayamos exhumado",
			vosotros: "hayáis exhumado",
			Uds: "hayan exhumado",
		},
		Past: {
			yo: "hubiera exhumado",
			tú: "hubieras exhumado",
			Ud: "hubiera exhumado",
			nosotros: "hubiéramos exhumado",
			vosotros: "hubierais exhumado",
			Uds: "hubieran exhumado",
		},
		Future: {
			yo: "hubiere exhumado",
			tú: "hubieres exhumado",
			Ud: "hubiere exhumado",
			nosotros: "hubiéremos exhumado",
			vosotros: "hubiereis exhumado",
			Uds: "hubieren exhumado",
		},
	},
}
