var exiliar = {
	Indicative: {
		Present: {
			yo: "exilio",
			tú: "exilias",
			Ud: "exilia",
			nosotros: "exiliamos",
			vosotros: "exiliáis",
			Uds: "exilian",
		},
		Preterite: {
			yo: "exilié",
			tú: "exiliaste",
			Ud: "exilió",
			nosotros: "exiliamos",
			vosotros: "exiliasteis",
			Uds: "exiliaron",
		},
		Imperfect: {
			yo: "exiliaba",
			tú: "exiliabas",
			Ud: "exiliaba",
			nosotros: "exiliábamos",
			vosotros: "exiliabais",
			Uds: "exiliaban",
		},
		Conditional: {
			yo: "exiliaría",
			tú: "exiliarías",
			Ud: "exiliaría",
			nosotros: "exiliaríamos",
			vosotros: "exiliaríais",
			Uds: "exiliarían",
		},
		Future: {
			yo: "exiliaré",
			tú: "exiliarás",
			Ud: "exiliará",
			nosotros: "exiliaremos",
			vosotros: "exiliaréis",
			Uds: "exiliarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "exilie",
			tú: "exilies",
			Ud: "exilie",
			nosotros: "exiliemos",
			vosotros: "exiliéis",
			Uds: "exilien",
		},
		Imperfect: {
			yo: "exiliara",
			tú: "exiliaras",
			Ud: "exiliara",
			nosotros: "exiliáramos",
			vosotros: "exiliarais",
			Uds: "exiliaran",
		},
		Imperfect2: {
			yo: "exiliase",
			tú: "exiliases",
			Ud: "exiliase",
			nosotros: "exiliásemos",
			vosotros: "exiliaseis",
			Uds: "exiliasen",
		},
		Future: {
			yo: "exiliare",
			tú: "exiliares",
			Ud: "exiliare",
			nosotros: "exiliáremos",
			vosotros: "exiliareis",
			Uds: "exiliaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "exilia",
			Ud: "exilie",
			nosotros: "exiliemos",
			vosotros: "exiliad",
			Uds: "exilien",
		},
		Negative: {
			tú: "no exilies",
			Ud: "no exilie",
			nosotros: "no exiliemos",
			vosotros: "no exiliéis",
			Uds: "no exilien",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy exiliando",
			tú: "estás exiliando",
			Ud: "está exiliando",
			nosotros: "estamos exiliando",
			vosotros: "estáis exiliando",
			Uds: "están exiliando",
		},
		Preterite: {
			yo: "estuve exiliando",
			tú: "estuviste exiliando",
			Ud: "estuvo exiliando",
			nosotros: "estuvimos exiliando",
			vosotros: "estuvisteis exiliando",
			Uds: "estuvieron exiliando",
		},
		Imperfect: {
			Uds: "estaban exiliando",
			yo: "estaba exiliando",
			tú: "estabas exiliando",
			Ud: "estaba exiliando",
			nosotros: "estábamos exiliando",
			vosotros: "estabais exiliando",
		},
		Conditional: {
			yo: "estaría exiliando",
			tú: "estarías exiliando",
			Ud: "estaría exiliando",
			nosotros: "estaríamos exiliando",
			vosotros: "estaríais exiliando",
			Uds: "estarían exiliando",
		},
		Future: {
			yo: "estaré exiliando",
			tú: "estarás exiliando",
			Ud: "estará exiliando",
			nosotros: "estaremos exiliando",
			vosotros: "estaréis exiliando",
			Uds: "estarán exiliando",
		},
	},
	Perfect: {
		Present: {
			yo: "he exiliado",
			tú: "has exiliado",
			Ud: "ha exiliado",
			nosotros: "hemos exiliado",
			vosotros: "habéis exiliado",
			Uds: "han exiliado",
		},
		Preterite: {
			yo: "hube exiliado",
			tú: "hubiste exiliado",
			Ud: "hubo exiliado",
			nosotros: "hubimos exiliado",
			vosotros: "hubisteis exiliado",
			Uds: "hubieron exiliado",
		},
		Past: {
			yo: "había exiliado",
			tú: "habías exiliado",
			Ud: "había exiliado",
			nosotros: "habíamos exiliado",
			vosotros: "habíais exiliado",
			Uds: "habían exiliado",
		},
		Conditional: {
			yo: "habría exiliado",
			tú: "habrías exiliado",
			Ud: "habría exiliado",
			nosotros: "habríamos exiliado",
			vosotros: "habríais exiliado",
			Uds: "habrían exiliado",
		},
		Future: {
			yo: "habré exiliado",
			tú: "habrás exiliado",
			Ud: "habrá exiliado",
			nosotros: "habremos exiliado",
			vosotros: "habréis exiliado",
			Uds: "habrán exiliado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya exiliado",
			tú: "hayas exiliado",
			Ud: "haya exiliado",
			nosotros: "hayamos exiliado",
			vosotros: "hayáis exiliado",
			Uds: "hayan exiliado",
		},
		Past: {
			yo: "hubiera exiliado",
			tú: "hubieras exiliado",
			Ud: "hubiera exiliado",
			nosotros: "hubiéramos exiliado",
			vosotros: "hubierais exiliado",
			Uds: "hubieran exiliado",
		},
		Future: {
			yo: "hubiere exiliado",
			tú: "hubieres exiliado",
			Ud: "hubiere exiliado",
			nosotros: "hubiéremos exiliado",
			vosotros: "hubiereis exiliado",
			Uds: "hubieren exiliado",
		},
	},
}
