var existir = {
	Indicative: {
		Present: {
			yo: "existo",
			tú: "existes",
			Ud: "existe",
			nosotros: "existimos",
			vosotros: "existís",
			Uds: "existen",
		},
		Preterite: {
			yo: "existí",
			tú: "exististe",
			Ud: "existió",
			nosotros: "existimos",
			vosotros: "exististeis",
			Uds: "existieron",
		},
		Imperfect: {
			yo: "existía",
			tú: "existías",
			Ud: "existía",
			nosotros: "existíamos",
			vosotros: "existíais",
			Uds: "existían",
		},
		Conditional: {
			yo: "existiría",
			tú: "existirías",
			Ud: "existiría",
			nosotros: "existiríamos",
			vosotros: "existiríais",
			Uds: "existirían",
		},
		Future: {
			yo: "existiré",
			tú: "existirás",
			Ud: "existirá",
			nosotros: "existiremos",
			vosotros: "existiréis",
			Uds: "existirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "exista",
			tú: "existas",
			Ud: "exista",
			nosotros: "existamos",
			vosotros: "existáis",
			Uds: "existan",
		},
		Imperfect: {
			yo: "existiera",
			tú: "existieras",
			Ud: "existiera",
			nosotros: "existiéramos",
			vosotros: "existierais",
			Uds: "existieran",
		},
		Imperfect2: {
			yo: "existiese",
			tú: "existieses",
			Ud: "existiese",
			nosotros: "existiésemos",
			vosotros: "existieseis",
			Uds: "existiesen",
		},
		Future: {
			yo: "existiere",
			tú: "existieres",
			Ud: "existiere",
			nosotros: "existiéremos",
			vosotros: "existiereis",
			Uds: "existieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "existe",
			Ud: "exista",
			nosotros: "existamos",
			vosotros: "existid",
			Uds: "existan",
		},
		Negative: {
			tú: "no existas",
			Ud: "no exista",
			nosotros: "no existamos",
			vosotros: "no existáis",
			Uds: "no existan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy existiendo",
			tú: "estás existiendo",
			Ud: "está existiendo",
			nosotros: "estamos existiendo",
			vosotros: "estáis existiendo",
			Uds: "están existiendo",
		},
		Preterite: {
			yo: "estuve existiendo",
			tú: "estuviste existiendo",
			Ud: "estuvo existiendo",
			nosotros: "estuvimos existiendo",
			vosotros: "estuvisteis existiendo",
			Uds: "estuvieron existiendo",
		},
		Imperfect: {
			Uds: "estaban existiendo",
			yo: "estaba existiendo",
			tú: "estabas existiendo",
			Ud: "estaba existiendo",
			nosotros: "estábamos existiendo",
			vosotros: "estabais existiendo",
		},
		Conditional: {
			yo: "estaría existiendo",
			tú: "estarías existiendo",
			Ud: "estaría existiendo",
			nosotros: "estaríamos existiendo",
			vosotros: "estaríais existiendo",
			Uds: "estarían existiendo",
		},
		Future: {
			yo: "estaré existiendo",
			tú: "estarás existiendo",
			Ud: "estará existiendo",
			nosotros: "estaremos existiendo",
			vosotros: "estaréis existiendo",
			Uds: "estarán existiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he existido",
			tú: "has existido",
			Ud: "ha existido",
			nosotros: "hemos existido",
			vosotros: "habéis existido",
			Uds: "han existido",
		},
		Preterite: {
			yo: "hube existido",
			tú: "hubiste existido",
			Ud: "hubo existido",
			nosotros: "hubimos existido",
			vosotros: "hubisteis existido",
			Uds: "hubieron existido",
		},
		Past: {
			yo: "había existido",
			tú: "habías existido",
			Ud: "había existido",
			nosotros: "habíamos existido",
			vosotros: "habíais existido",
			Uds: "habían existido",
		},
		Conditional: {
			yo: "habría existido",
			tú: "habrías existido",
			Ud: "habría existido",
			nosotros: "habríamos existido",
			vosotros: "habríais existido",
			Uds: "habrían existido",
		},
		Future: {
			yo: "habré existido",
			tú: "habrás existido",
			Ud: "habrá existido",
			nosotros: "habremos existido",
			vosotros: "habréis existido",
			Uds: "habrán existido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya existido",
			tú: "hayas existido",
			Ud: "haya existido",
			nosotros: "hayamos existido",
			vosotros: "hayáis existido",
			Uds: "hayan existido",
		},
		Past: {
			yo: "hubiera existido",
			tú: "hubieras existido",
			Ud: "hubiera existido",
			nosotros: "hubiéramos existido",
			vosotros: "hubierais existido",
			Uds: "hubieran existido",
		},
		Future: {
			yo: "hubiere existido",
			tú: "hubieres existido",
			Ud: "hubiere existido",
			nosotros: "hubiéremos existido",
			vosotros: "hubiereis existido",
			Uds: "hubieren existido",
		},
	},
}
