var experimentar = {
	Indicative: {
		Present: {
			yo: "experimento",
			tú: "experimentas",
			Ud: "experimenta",
			nosotros: "experimentamos",
			vosotros: "experimentáis",
			Uds: "experimentan",
		},
		Preterite: {
			yo: "experimenté",
			tú: "experimentaste",
			Ud: "experimentó",
			nosotros: "experimentamos",
			vosotros: "experimentasteis",
			Uds: "experimentaron",
		},
		Imperfect: {
			yo: "experimentaba",
			tú: "experimentabas",
			Ud: "experimentaba",
			nosotros: "experimentábamos",
			vosotros: "experimentabais",
			Uds: "experimentaban",
		},
		Conditional: {
			yo: "experimentaría",
			tú: "experimentarías",
			Ud: "experimentaría",
			nosotros: "experimentaríamos",
			vosotros: "experimentaríais",
			Uds: "experimentarían",
		},
		Future: {
			yo: "experimentaré",
			tú: "experimentarás",
			Ud: "experimentará",
			nosotros: "experimentaremos",
			vosotros: "experimentaréis",
			Uds: "experimentarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "experimente",
			tú: "experimentes",
			Ud: "experimente",
			nosotros: "experimentemos",
			vosotros: "experimentéis",
			Uds: "experimenten",
		},
		Imperfect: {
			yo: "experimentara",
			tú: "experimentaras",
			Ud: "experimentara",
			nosotros: "experimentáramos",
			vosotros: "experimentarais",
			Uds: "experimentaran",
		},
		Imperfect2: {
			yo: "experimentase",
			tú: "experimentases",
			Ud: "experimentase",
			nosotros: "experimentásemos",
			vosotros: "experimentaseis",
			Uds: "experimentasen",
		},
		Future: {
			yo: "experimentare",
			tú: "experimentares",
			Ud: "experimentare",
			nosotros: "experimentáremos",
			vosotros: "experimentareis",
			Uds: "experimentaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "experimenta",
			Ud: "experimente",
			nosotros: "experimentemos",
			vosotros: "experimentad",
			Uds: "experimenten",
		},
		Negative: {
			tú: "no experimentes",
			Ud: "no experimente",
			nosotros: "no experimentemos",
			vosotros: "no experimentéis",
			Uds: "no experimenten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy experimentando",
			tú: "estás experimentando",
			Ud: "está experimentando",
			nosotros: "estamos experimentando",
			vosotros: "estáis experimentando",
			Uds: "están experimentando",
		},
		Preterite: {
			yo: "estuve experimentando",
			tú: "estuviste experimentando",
			Ud: "estuvo experimentando",
			nosotros: "estuvimos experimentando",
			vosotros: "estuvisteis experimentando",
			Uds: "estuvieron experimentando",
		},
		Imperfect: {
			Uds: "estaban experimentando",
			yo: "estaba experimentando",
			tú: "estabas experimentando",
			Ud: "estaba experimentando",
			nosotros: "estábamos experimentando",
			vosotros: "estabais experimentando",
		},
		Conditional: {
			yo: "estaría experimentando",
			tú: "estarías experimentando",
			Ud: "estaría experimentando",
			nosotros: "estaríamos experimentando",
			vosotros: "estaríais experimentando",
			Uds: "estarían experimentando",
		},
		Future: {
			yo: "estaré experimentando",
			tú: "estarás experimentando",
			Ud: "estará experimentando",
			nosotros: "estaremos experimentando",
			vosotros: "estaréis experimentando",
			Uds: "estarán experimentando",
		},
	},
	Perfect: {
		Present: {
			yo: "he experimentado",
			tú: "has experimentado",
			Ud: "ha experimentado",
			nosotros: "hemos experimentado",
			vosotros: "habéis experimentado",
			Uds: "han experimentado",
		},
		Preterite: {
			yo: "hube experimentado",
			tú: "hubiste experimentado",
			Ud: "hubo experimentado",
			nosotros: "hubimos experimentado",
			vosotros: "hubisteis experimentado",
			Uds: "hubieron experimentado",
		},
		Past: {
			yo: "había experimentado",
			tú: "habías experimentado",
			Ud: "había experimentado",
			nosotros: "habíamos experimentado",
			vosotros: "habíais experimentado",
			Uds: "habían experimentado",
		},
		Conditional: {
			yo: "habría experimentado",
			tú: "habrías experimentado",
			Ud: "habría experimentado",
			nosotros: "habríamos experimentado",
			vosotros: "habríais experimentado",
			Uds: "habrían experimentado",
		},
		Future: {
			yo: "habré experimentado",
			tú: "habrás experimentado",
			Ud: "habrá experimentado",
			nosotros: "habremos experimentado",
			vosotros: "habréis experimentado",
			Uds: "habrán experimentado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya experimentado",
			tú: "hayas experimentado",
			Ud: "haya experimentado",
			nosotros: "hayamos experimentado",
			vosotros: "hayáis experimentado",
			Uds: "hayan experimentado",
		},
		Past: {
			yo: "hubiera experimentado",
			tú: "hubieras experimentado",
			Ud: "hubiera experimentado",
			nosotros: "hubiéramos experimentado",
			vosotros: "hubierais experimentado",
			Uds: "hubieran experimentado",
		},
		Future: {
			yo: "hubiere experimentado",
			tú: "hubieres experimentado",
			Ud: "hubiere experimentado",
			nosotros: "hubiéremos experimentado",
			vosotros: "hubiereis experimentado",
			Uds: "hubieren experimentado",
		},
	},
}
