var explotar = {
	Indicative: {
		Present: {
			yo: "exploto",
			tú: "explotas",
			Ud: "explota",
			nosotros: "explotamos",
			vosotros: "explotáis",
			Uds: "explotan",
		},
		Preterite: {
			yo: "exploté",
			tú: "explotaste",
			Ud: "explotó",
			nosotros: "explotamos",
			vosotros: "explotasteis",
			Uds: "explotaron",
		},
		Imperfect: {
			yo: "explotaba",
			tú: "explotabas",
			Ud: "explotaba",
			nosotros: "explotábamos",
			vosotros: "explotabais",
			Uds: "explotaban",
		},
		Conditional: {
			yo: "explotaría",
			tú: "explotarías",
			Ud: "explotaría",
			nosotros: "explotaríamos",
			vosotros: "explotaríais",
			Uds: "explotarían",
		},
		Future: {
			yo: "explotaré",
			tú: "explotarás",
			Ud: "explotará",
			nosotros: "explotaremos",
			vosotros: "explotaréis",
			Uds: "explotarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "explote",
			tú: "explotes",
			Ud: "explote",
			nosotros: "explotemos",
			vosotros: "explotéis",
			Uds: "exploten",
		},
		Imperfect: {
			yo: "explotara",
			tú: "explotaras",
			Ud: "explotara",
			nosotros: "explotáramos",
			vosotros: "explotarais",
			Uds: "explotaran",
		},
		Imperfect2: {
			yo: "explotase",
			tú: "explotases",
			Ud: "explotase",
			nosotros: "explotásemos",
			vosotros: "explotaseis",
			Uds: "explotasen",
		},
		Future: {
			yo: "explotare",
			tú: "explotares",
			Ud: "explotare",
			nosotros: "explotáremos",
			vosotros: "explotareis",
			Uds: "explotaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "explota",
			Ud: "explote",
			nosotros: "explotemos",
			vosotros: "explotad",
			Uds: "exploten",
		},
		Negative: {
			tú: "no explotes",
			Ud: "no explote",
			nosotros: "no explotemos",
			vosotros: "no explotéis",
			Uds: "no exploten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy explotando",
			tú: "estás explotando",
			Ud: "está explotando",
			nosotros: "estamos explotando",
			vosotros: "estáis explotando",
			Uds: "están explotando",
		},
		Preterite: {
			yo: "estuve explotando",
			tú: "estuviste explotando",
			Ud: "estuvo explotando",
			nosotros: "estuvimos explotando",
			vosotros: "estuvisteis explotando",
			Uds: "estuvieron explotando",
		},
		Imperfect: {
			Uds: "estaban explotando",
			yo: "estaba explotando",
			tú: "estabas explotando",
			Ud: "estaba explotando",
			nosotros: "estábamos explotando",
			vosotros: "estabais explotando",
		},
		Conditional: {
			yo: "estaría explotando",
			tú: "estarías explotando",
			Ud: "estaría explotando",
			nosotros: "estaríamos explotando",
			vosotros: "estaríais explotando",
			Uds: "estarían explotando",
		},
		Future: {
			yo: "estaré explotando",
			tú: "estarás explotando",
			Ud: "estará explotando",
			nosotros: "estaremos explotando",
			vosotros: "estaréis explotando",
			Uds: "estarán explotando",
		},
	},
	Perfect: {
		Present: {
			yo: "he explotado",
			tú: "has explotado",
			Ud: "ha explotado",
			nosotros: "hemos explotado",
			vosotros: "habéis explotado",
			Uds: "han explotado",
		},
		Preterite: {
			yo: "hube explotado",
			tú: "hubiste explotado",
			Ud: "hubo explotado",
			nosotros: "hubimos explotado",
			vosotros: "hubisteis explotado",
			Uds: "hubieron explotado",
		},
		Past: {
			yo: "había explotado",
			tú: "habías explotado",
			Ud: "había explotado",
			nosotros: "habíamos explotado",
			vosotros: "habíais explotado",
			Uds: "habían explotado",
		},
		Conditional: {
			yo: "habría explotado",
			tú: "habrías explotado",
			Ud: "habría explotado",
			nosotros: "habríamos explotado",
			vosotros: "habríais explotado",
			Uds: "habrían explotado",
		},
		Future: {
			yo: "habré explotado",
			tú: "habrás explotado",
			Ud: "habrá explotado",
			nosotros: "habremos explotado",
			vosotros: "habréis explotado",
			Uds: "habrán explotado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya explotado",
			tú: "hayas explotado",
			Ud: "haya explotado",
			nosotros: "hayamos explotado",
			vosotros: "hayáis explotado",
			Uds: "hayan explotado",
		},
		Past: {
			yo: "hubiera explotado",
			tú: "hubieras explotado",
			Ud: "hubiera explotado",
			nosotros: "hubiéramos explotado",
			vosotros: "hubierais explotado",
			Uds: "hubieran explotado",
		},
		Future: {
			yo: "hubiere explotado",
			tú: "hubieres explotado",
			Ud: "hubiere explotado",
			nosotros: "hubiéremos explotado",
			vosotros: "hubiereis explotado",
			Uds: "hubieren explotado",
		},
	},
}
