var extenuar = {
	Indicative: {
		Present: {
			yo: "extenúo",
			tú: "extenúas",
			Ud: "extenúa",
			nosotros: "extenuamos",
			vosotros: "extenuáis",
			Uds: "extenúan",
		},
		Preterite: {
			yo: "extenué",
			tú: "extenuaste",
			Ud: "extenuó",
			nosotros: "extenuamos",
			vosotros: "extenuasteis",
			Uds: "extenuaron",
		},
		Imperfect: {
			yo: "extenuaba",
			tú: "extenuabas",
			Ud: "extenuaba",
			nosotros: "extenuábamos",
			vosotros: "extenuabais",
			Uds: "extenuaban",
		},
		Conditional: {
			yo: "extenuaría",
			tú: "extenuarías",
			Ud: "extenuaría",
			nosotros: "extenuaríamos",
			vosotros: "extenuaríais",
			Uds: "extenuarían",
		},
		Future: {
			yo: "extenuaré",
			tú: "extenuarás",
			Ud: "extenuará",
			nosotros: "extenuaremos",
			vosotros: "extenuaréis",
			Uds: "extenuarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "extenúe",
			tú: "extenúes",
			Ud: "extenúe",
			nosotros: "extenuemos",
			vosotros: "extenuéis",
			Uds: "extenúen",
		},
		Imperfect: {
			yo: "extenuara",
			tú: "extenuaras",
			Ud: "extenuara",
			nosotros: "extenuáramos",
			vosotros: "extenuarais",
			Uds: "extenuaran",
		},
		Imperfect2: {
			yo: "extenuase",
			tú: "extenuases",
			Ud: "extenuase",
			nosotros: "extenuásemos",
			vosotros: "extenuaseis",
			Uds: "extenuasen",
		},
		Future: {
			yo: "extenuare",
			tú: "extenuares",
			Ud: "extenuare",
			nosotros: "extenuáremos",
			vosotros: "extenuareis",
			Uds: "extenuaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "extenúa",
			Ud: "extenúe",
			nosotros: "extenuemos",
			vosotros: "extenuad",
			Uds: "extenúen",
		},
		Negative: {
			tú: "no extenúes",
			Ud: "no extenúe",
			nosotros: "no extenuemos",
			vosotros: "no extenuéis",
			Uds: "no extenúen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy extenuando",
			tú: "estás extenuando",
			Ud: "está extenuando",
			nosotros: "estamos extenuando",
			vosotros: "estáis extenuando",
			Uds: "están extenuando",
		},
		Preterite: {
			yo: "estuve extenuando",
			tú: "estuviste extenuando",
			Ud: "estuvo extenuando",
			nosotros: "estuvimos extenuando",
			vosotros: "estuvisteis extenuando",
			Uds: "estuvieron extenuando",
		},
		Imperfect: {
			Uds: "estaban extenuando",
			yo: "estaba extenuando",
			tú: "estabas extenuando",
			Ud: "estaba extenuando",
			nosotros: "estábamos extenuando",
			vosotros: "estabais extenuando",
		},
		Conditional: {
			yo: "estaría extenuando",
			tú: "estarías extenuando",
			Ud: "estaría extenuando",
			nosotros: "estaríamos extenuando",
			vosotros: "estaríais extenuando",
			Uds: "estarían extenuando",
		},
		Future: {
			yo: "estaré extenuando",
			tú: "estarás extenuando",
			Ud: "estará extenuando",
			nosotros: "estaremos extenuando",
			vosotros: "estaréis extenuando",
			Uds: "estarán extenuando",
		},
	},
	Perfect: {
		Present: {
			yo: "he extenuado",
			tú: "has extenuado",
			Ud: "ha extenuado",
			nosotros: "hemos extenuado",
			vosotros: "habéis extenuado",
			Uds: "han extenuado",
		},
		Preterite: {
			yo: "hube extenuado",
			tú: "hubiste extenuado",
			Ud: "hubo extenuado",
			nosotros: "hubimos extenuado",
			vosotros: "hubisteis extenuado",
			Uds: "hubieron extenuado",
		},
		Past: {
			yo: "había extenuado",
			tú: "habías extenuado",
			Ud: "había extenuado",
			nosotros: "habíamos extenuado",
			vosotros: "habíais extenuado",
			Uds: "habían extenuado",
		},
		Conditional: {
			yo: "habría extenuado",
			tú: "habrías extenuado",
			Ud: "habría extenuado",
			nosotros: "habríamos extenuado",
			vosotros: "habríais extenuado",
			Uds: "habrían extenuado",
		},
		Future: {
			yo: "habré extenuado",
			tú: "habrás extenuado",
			Ud: "habrá extenuado",
			nosotros: "habremos extenuado",
			vosotros: "habréis extenuado",
			Uds: "habrán extenuado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya extenuado",
			tú: "hayas extenuado",
			Ud: "haya extenuado",
			nosotros: "hayamos extenuado",
			vosotros: "hayáis extenuado",
			Uds: "hayan extenuado",
		},
		Past: {
			yo: "hubiera extenuado",
			tú: "hubieras extenuado",
			Ud: "hubiera extenuado",
			nosotros: "hubiéramos extenuado",
			vosotros: "hubierais extenuado",
			Uds: "hubieran extenuado",
		},
		Future: {
			yo: "hubiere extenuado",
			tú: "hubieres extenuado",
			Ud: "hubiere extenuado",
			nosotros: "hubiéremos extenuado",
			vosotros: "hubiereis extenuado",
			Uds: "hubieren extenuado",
		},
	},
}
