var facturar = {
	Indicative: {
		Present: {
			yo: "facturo",
			tú: "facturas",
			Ud: "factura",
			nosotros: "facturamos",
			vosotros: "facturáis",
			Uds: "facturan",
		},
		Preterite: {
			yo: "facturé",
			tú: "facturaste",
			Ud: "facturó",
			nosotros: "facturamos",
			vosotros: "facturasteis",
			Uds: "facturaron",
		},
		Imperfect: {
			yo: "facturaba",
			tú: "facturabas",
			Ud: "facturaba",
			nosotros: "facturábamos",
			vosotros: "facturabais",
			Uds: "facturaban",
		},
		Conditional: {
			yo: "facturaría",
			tú: "facturarías",
			Ud: "facturaría",
			nosotros: "facturaríamos",
			vosotros: "facturaríais",
			Uds: "facturarían",
		},
		Future: {
			yo: "facturaré",
			tú: "facturarás",
			Ud: "facturará",
			nosotros: "facturaremos",
			vosotros: "facturaréis",
			Uds: "facturarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "facture",
			tú: "factures",
			Ud: "facture",
			nosotros: "facturemos",
			vosotros: "facturéis",
			Uds: "facturen",
		},
		Imperfect: {
			yo: "facturara",
			tú: "facturaras",
			Ud: "facturara",
			nosotros: "facturáramos",
			vosotros: "facturarais",
			Uds: "facturaran",
		},
		Imperfect2: {
			yo: "facturase",
			tú: "facturases",
			Ud: "facturase",
			nosotros: "facturásemos",
			vosotros: "facturaseis",
			Uds: "facturasen",
		},
		Future: {
			yo: "facturare",
			tú: "facturares",
			Ud: "facturare",
			nosotros: "facturáremos",
			vosotros: "facturareis",
			Uds: "facturaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "factura",
			Ud: "facture",
			nosotros: "facturemos",
			vosotros: "facturad",
			Uds: "facturen",
		},
		Negative: {
			tú: "no factures",
			Ud: "no facture",
			nosotros: "no facturemos",
			vosotros: "no facturéis",
			Uds: "no facturen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy facturando",
			tú: "estás facturando",
			Ud: "está facturando",
			nosotros: "estamos facturando",
			vosotros: "estáis facturando",
			Uds: "están facturando",
		},
		Preterite: {
			yo: "estuve facturando",
			tú: "estuviste facturando",
			Ud: "estuvo facturando",
			nosotros: "estuvimos facturando",
			vosotros: "estuvisteis facturando",
			Uds: "estuvieron facturando",
		},
		Imperfect: {
			Uds: "estaban facturando",
			yo: "estaba facturando",
			tú: "estabas facturando",
			Ud: "estaba facturando",
			nosotros: "estábamos facturando",
			vosotros: "estabais facturando",
		},
		Conditional: {
			yo: "estaría facturando",
			tú: "estarías facturando",
			Ud: "estaría facturando",
			nosotros: "estaríamos facturando",
			vosotros: "estaríais facturando",
			Uds: "estarían facturando",
		},
		Future: {
			yo: "estaré facturando",
			tú: "estarás facturando",
			Ud: "estará facturando",
			nosotros: "estaremos facturando",
			vosotros: "estaréis facturando",
			Uds: "estarán facturando",
		},
	},
	Perfect: {
		Present: {
			yo: "he facturado",
			tú: "has facturado",
			Ud: "ha facturado",
			nosotros: "hemos facturado",
			vosotros: "habéis facturado",
			Uds: "han facturado",
		},
		Preterite: {
			yo: "hube facturado",
			tú: "hubiste facturado",
			Ud: "hubo facturado",
			nosotros: "hubimos facturado",
			vosotros: "hubisteis facturado",
			Uds: "hubieron facturado",
		},
		Past: {
			yo: "había facturado",
			tú: "habías facturado",
			Ud: "había facturado",
			nosotros: "habíamos facturado",
			vosotros: "habíais facturado",
			Uds: "habían facturado",
		},
		Conditional: {
			yo: "habría facturado",
			tú: "habrías facturado",
			Ud: "habría facturado",
			nosotros: "habríamos facturado",
			vosotros: "habríais facturado",
			Uds: "habrían facturado",
		},
		Future: {
			yo: "habré facturado",
			tú: "habrás facturado",
			Ud: "habrá facturado",
			nosotros: "habremos facturado",
			vosotros: "habréis facturado",
			Uds: "habrán facturado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya facturado",
			tú: "hayas facturado",
			Ud: "haya facturado",
			nosotros: "hayamos facturado",
			vosotros: "hayáis facturado",
			Uds: "hayan facturado",
		},
		Past: {
			yo: "hubiera facturado",
			tú: "hubieras facturado",
			Ud: "hubiera facturado",
			nosotros: "hubiéramos facturado",
			vosotros: "hubierais facturado",
			Uds: "hubieran facturado",
		},
		Future: {
			yo: "hubiere facturado",
			tú: "hubieres facturado",
			Ud: "hubiere facturado",
			nosotros: "hubiéremos facturado",
			vosotros: "hubiereis facturado",
			Uds: "hubieren facturado",
		},
	},
}
