var faltar = {
	Indicative: {
		Present: {
			yo: "falto",
			tú: "faltas",
			Ud: "falta",
			nosotros: "faltamos",
			vosotros: "faltáis",
			Uds: "faltan",
		},
		Preterite: {
			yo: "falté",
			tú: "faltaste",
			Ud: "faltó",
			nosotros: "faltamos",
			vosotros: "faltasteis",
			Uds: "faltaron",
		},
		Imperfect: {
			yo: "faltaba",
			tú: "faltabas",
			Ud: "faltaba",
			nosotros: "faltábamos",
			vosotros: "faltabais",
			Uds: "faltaban",
		},
		Conditional: {
			yo: "faltaría",
			tú: "faltarías",
			Ud: "faltaría",
			nosotros: "faltaríamos",
			vosotros: "faltaríais",
			Uds: "faltarían",
		},
		Future: {
			yo: "faltaré",
			tú: "faltarás",
			Ud: "faltará",
			nosotros: "faltaremos",
			vosotros: "faltaréis",
			Uds: "faltarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "falte",
			tú: "faltes",
			Ud: "falte",
			nosotros: "faltemos",
			vosotros: "faltéis",
			Uds: "falten",
		},
		Imperfect: {
			yo: "faltara",
			tú: "faltaras",
			Ud: "faltara",
			nosotros: "faltáramos",
			vosotros: "faltarais",
			Uds: "faltaran",
		},
		Imperfect2: {
			yo: "faltase",
			tú: "faltases",
			Ud: "faltase",
			nosotros: "faltásemos",
			vosotros: "faltaseis",
			Uds: "faltasen",
		},
		Future: {
			yo: "faltare",
			tú: "faltares",
			Ud: "faltare",
			nosotros: "faltáremos",
			vosotros: "faltareis",
			Uds: "faltaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "falta",
			Ud: "falte",
			nosotros: "faltemos",
			vosotros: "faltad",
			Uds: "falten",
		},
		Negative: {
			tú: "no faltes",
			Ud: "no falte",
			nosotros: "no faltemos",
			vosotros: "no faltéis",
			Uds: "no falten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy faltando",
			tú: "estás faltando",
			Ud: "está faltando",
			nosotros: "estamos faltando",
			vosotros: "estáis faltando",
			Uds: "están faltando",
		},
		Preterite: {
			yo: "estuve faltando",
			tú: "estuviste faltando",
			Ud: "estuvo faltando",
			nosotros: "estuvimos faltando",
			vosotros: "estuvisteis faltando",
			Uds: "estuvieron faltando",
		},
		Imperfect: {
			Uds: "estaban faltando",
			yo: "estaba faltando",
			tú: "estabas faltando",
			Ud: "estaba faltando",
			nosotros: "estábamos faltando",
			vosotros: "estabais faltando",
		},
		Conditional: {
			yo: "estaría faltando",
			tú: "estarías faltando",
			Ud: "estaría faltando",
			nosotros: "estaríamos faltando",
			vosotros: "estaríais faltando",
			Uds: "estarían faltando",
		},
		Future: {
			yo: "estaré faltando",
			tú: "estarás faltando",
			Ud: "estará faltando",
			nosotros: "estaremos faltando",
			vosotros: "estaréis faltando",
			Uds: "estarán faltando",
		},
	},
	Perfect: {
		Present: {
			yo: "he faltado",
			tú: "has faltado",
			Ud: "ha faltado",
			nosotros: "hemos faltado",
			vosotros: "habéis faltado",
			Uds: "han faltado",
		},
		Preterite: {
			yo: "hube faltado",
			tú: "hubiste faltado",
			Ud: "hubo faltado",
			nosotros: "hubimos faltado",
			vosotros: "hubisteis faltado",
			Uds: "hubieron faltado",
		},
		Past: {
			yo: "había faltado",
			tú: "habías faltado",
			Ud: "había faltado",
			nosotros: "habíamos faltado",
			vosotros: "habíais faltado",
			Uds: "habían faltado",
		},
		Conditional: {
			yo: "habría faltado",
			tú: "habrías faltado",
			Ud: "habría faltado",
			nosotros: "habríamos faltado",
			vosotros: "habríais faltado",
			Uds: "habrían faltado",
		},
		Future: {
			yo: "habré faltado",
			tú: "habrás faltado",
			Ud: "habrá faltado",
			nosotros: "habremos faltado",
			vosotros: "habréis faltado",
			Uds: "habrán faltado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya faltado",
			tú: "hayas faltado",
			Ud: "haya faltado",
			nosotros: "hayamos faltado",
			vosotros: "hayáis faltado",
			Uds: "hayan faltado",
		},
		Past: {
			yo: "hubiera faltado",
			tú: "hubieras faltado",
			Ud: "hubiera faltado",
			nosotros: "hubiéramos faltado",
			vosotros: "hubierais faltado",
			Uds: "hubieran faltado",
		},
		Future: {
			yo: "hubiere faltado",
			tú: "hubieres faltado",
			Ud: "hubiere faltado",
			nosotros: "hubiéremos faltado",
			vosotros: "hubiereis faltado",
			Uds: "hubieren faltado",
		},
	},
}
