var fanfarronear = {
	Indicative: {
		Present: {
			yo: "fanfarroneo",
			tú: "fanfarroneas",
			Ud: "fanfarronea",
			nosotros: "fanfarroneamos",
			vosotros: "fanfarroneáis",
			Uds: "fanfarronean",
		},
		Preterite: {
			yo: "fanfarroneé",
			tú: "fanfarroneaste",
			Ud: "fanfarroneó",
			nosotros: "fanfarroneamos",
			vosotros: "fanfarroneasteis",
			Uds: "fanfarronearon",
		},
		Imperfect: {
			yo: "fanfarroneaba",
			tú: "fanfarroneabas",
			Ud: "fanfarroneaba",
			nosotros: "fanfarroneábamos",
			vosotros: "fanfarroneabais",
			Uds: "fanfarroneaban",
		},
		Conditional: {
			yo: "fanfarronearía",
			tú: "fanfarronearías",
			Ud: "fanfarronearía",
			nosotros: "fanfarronearíamos",
			vosotros: "fanfarronearíais",
			Uds: "fanfarronearían",
		},
		Future: {
			yo: "fanfarronearé",
			tú: "fanfarronearás",
			Ud: "fanfarroneará",
			nosotros: "fanfarronearemos",
			vosotros: "fanfarronearéis",
			Uds: "fanfarronearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "fanfarronee",
			tú: "fanfarronees",
			Ud: "fanfarronee",
			nosotros: "fanfarroneemos",
			vosotros: "fanfarroneéis",
			Uds: "fanfarroneen",
		},
		Imperfect: {
			yo: "fanfarroneara",
			tú: "fanfarronearas",
			Ud: "fanfarroneara",
			nosotros: "fanfarroneáramos",
			vosotros: "fanfarronearais",
			Uds: "fanfarronearan",
		},
		Imperfect2: {
			yo: "fanfarronease",
			tú: "fanfarroneases",
			Ud: "fanfarronease",
			nosotros: "fanfarroneásemos",
			vosotros: "fanfarroneaseis",
			Uds: "fanfarroneasen",
		},
		Future: {
			yo: "fanfarroneare",
			tú: "fanfarroneares",
			Ud: "fanfarroneare",
			nosotros: "fanfarroneáremos",
			vosotros: "fanfarroneareis",
			Uds: "fanfarronearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "fanfarronea",
			Ud: "fanfarronee",
			nosotros: "fanfarroneemos",
			vosotros: "fanfarronead",
			Uds: "fanfarroneen",
		},
		Negative: {
			tú: "no fanfarronees",
			Ud: "no fanfarronee",
			nosotros: "no fanfarroneemos",
			vosotros: "no fanfarroneéis",
			Uds: "no fanfarroneen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy fanfarroneando",
			tú: "estás fanfarroneando",
			Ud: "está fanfarroneando",
			nosotros: "estamos fanfarroneando",
			vosotros: "estáis fanfarroneando",
			Uds: "están fanfarroneando",
		},
		Preterite: {
			yo: "estuve fanfarroneando",
			tú: "estuviste fanfarroneando",
			Ud: "estuvo fanfarroneando",
			nosotros: "estuvimos fanfarroneando",
			vosotros: "estuvisteis fanfarroneando",
			Uds: "estuvieron fanfarroneando",
		},
		Imperfect: {
			Uds: "estaban fanfarroneando",
			yo: "estaba fanfarroneando",
			tú: "estabas fanfarroneando",
			Ud: "estaba fanfarroneando",
			nosotros: "estábamos fanfarroneando",
			vosotros: "estabais fanfarroneando",
		},
		Conditional: {
			yo: "estaría fanfarroneando",
			tú: "estarías fanfarroneando",
			Ud: "estaría fanfarroneando",
			nosotros: "estaríamos fanfarroneando",
			vosotros: "estaríais fanfarroneando",
			Uds: "estarían fanfarroneando",
		},
		Future: {
			yo: "estaré fanfarroneando",
			tú: "estarás fanfarroneando",
			Ud: "estará fanfarroneando",
			nosotros: "estaremos fanfarroneando",
			vosotros: "estaréis fanfarroneando",
			Uds: "estarán fanfarroneando",
		},
	},
	Perfect: {
		Present: {
			yo: "he fanfarroneado",
			tú: "has fanfarroneado",
			Ud: "ha fanfarroneado",
			nosotros: "hemos fanfarroneado",
			vosotros: "habéis fanfarroneado",
			Uds: "han fanfarroneado",
		},
		Preterite: {
			yo: "hube fanfarroneado",
			tú: "hubiste fanfarroneado",
			Ud: "hubo fanfarroneado",
			nosotros: "hubimos fanfarroneado",
			vosotros: "hubisteis fanfarroneado",
			Uds: "hubieron fanfarroneado",
		},
		Past: {
			yo: "había fanfarroneado",
			tú: "habías fanfarroneado",
			Ud: "había fanfarroneado",
			nosotros: "habíamos fanfarroneado",
			vosotros: "habíais fanfarroneado",
			Uds: "habían fanfarroneado",
		},
		Conditional: {
			yo: "habría fanfarroneado",
			tú: "habrías fanfarroneado",
			Ud: "habría fanfarroneado",
			nosotros: "habríamos fanfarroneado",
			vosotros: "habríais fanfarroneado",
			Uds: "habrían fanfarroneado",
		},
		Future: {
			yo: "habré fanfarroneado",
			tú: "habrás fanfarroneado",
			Ud: "habrá fanfarroneado",
			nosotros: "habremos fanfarroneado",
			vosotros: "habréis fanfarroneado",
			Uds: "habrán fanfarroneado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya fanfarroneado",
			tú: "hayas fanfarroneado",
			Ud: "haya fanfarroneado",
			nosotros: "hayamos fanfarroneado",
			vosotros: "hayáis fanfarroneado",
			Uds: "hayan fanfarroneado",
		},
		Past: {
			yo: "hubiera fanfarroneado",
			tú: "hubieras fanfarroneado",
			Ud: "hubiera fanfarroneado",
			nosotros: "hubiéramos fanfarroneado",
			vosotros: "hubierais fanfarroneado",
			Uds: "hubieran fanfarroneado",
		},
		Future: {
			yo: "hubiere fanfarroneado",
			tú: "hubieres fanfarroneado",
			Ud: "hubiere fanfarroneado",
			nosotros: "hubiéremos fanfarroneado",
			vosotros: "hubiereis fanfarroneado",
			Uds: "hubieren fanfarroneado",
		},
	},
}
