var fastidiar = {
	Indicative: {
		Present: {
			yo: "fastidio",
			tú: "fastidias",
			Ud: "fastidia",
			nosotros: "fastidiamos",
			vosotros: "fastidiáis",
			Uds: "fastidian",
		},
		Preterite: {
			yo: "fastidié",
			tú: "fastidiaste",
			Ud: "fastidió",
			nosotros: "fastidiamos",
			vosotros: "fastidiasteis",
			Uds: "fastidiaron",
		},
		Imperfect: {
			yo: "fastidiaba",
			tú: "fastidiabas",
			Ud: "fastidiaba",
			nosotros: "fastidiábamos",
			vosotros: "fastidiabais",
			Uds: "fastidiaban",
		},
		Conditional: {
			yo: "fastidiaría",
			tú: "fastidiarías",
			Ud: "fastidiaría",
			nosotros: "fastidiaríamos",
			vosotros: "fastidiaríais",
			Uds: "fastidiarían",
		},
		Future: {
			yo: "fastidiaré",
			tú: "fastidiarás",
			Ud: "fastidiará",
			nosotros: "fastidiaremos",
			vosotros: "fastidiaréis",
			Uds: "fastidiarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "fastidie",
			tú: "fastidies",
			Ud: "fastidie",
			nosotros: "fastidiemos",
			vosotros: "fastidiéis",
			Uds: "fastidien",
		},
		Imperfect: {
			yo: "fastidiara",
			tú: "fastidiaras",
			Ud: "fastidiara",
			nosotros: "fastidiáramos",
			vosotros: "fastidiarais",
			Uds: "fastidiaran",
		},
		Imperfect2: {
			yo: "fastidiase",
			tú: "fastidiases",
			Ud: "fastidiase",
			nosotros: "fastidiásemos",
			vosotros: "fastidiaseis",
			Uds: "fastidiasen",
		},
		Future: {
			yo: "fastidiare",
			tú: "fastidiares",
			Ud: "fastidiare",
			nosotros: "fastidiáremos",
			vosotros: "fastidiareis",
			Uds: "fastidiaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "fastidia",
			Ud: "fastidie",
			nosotros: "fastidiemos",
			vosotros: "fastidiad",
			Uds: "fastidien",
		},
		Negative: {
			tú: "no fastidies",
			Ud: "no fastidie",
			nosotros: "no fastidiemos",
			vosotros: "no fastidiéis",
			Uds: "no fastidien",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy fastidiando",
			tú: "estás fastidiando",
			Ud: "está fastidiando",
			nosotros: "estamos fastidiando",
			vosotros: "estáis fastidiando",
			Uds: "están fastidiando",
		},
		Preterite: {
			yo: "estuve fastidiando",
			tú: "estuviste fastidiando",
			Ud: "estuvo fastidiando",
			nosotros: "estuvimos fastidiando",
			vosotros: "estuvisteis fastidiando",
			Uds: "estuvieron fastidiando",
		},
		Imperfect: {
			Uds: "estaban fastidiando",
			yo: "estaba fastidiando",
			tú: "estabas fastidiando",
			Ud: "estaba fastidiando",
			nosotros: "estábamos fastidiando",
			vosotros: "estabais fastidiando",
		},
		Conditional: {
			yo: "estaría fastidiando",
			tú: "estarías fastidiando",
			Ud: "estaría fastidiando",
			nosotros: "estaríamos fastidiando",
			vosotros: "estaríais fastidiando",
			Uds: "estarían fastidiando",
		},
		Future: {
			yo: "estaré fastidiando",
			tú: "estarás fastidiando",
			Ud: "estará fastidiando",
			nosotros: "estaremos fastidiando",
			vosotros: "estaréis fastidiando",
			Uds: "estarán fastidiando",
		},
	},
	Perfect: {
		Present: {
			yo: "he fastidiado",
			tú: "has fastidiado",
			Ud: "ha fastidiado",
			nosotros: "hemos fastidiado",
			vosotros: "habéis fastidiado",
			Uds: "han fastidiado",
		},
		Preterite: {
			yo: "hube fastidiado",
			tú: "hubiste fastidiado",
			Ud: "hubo fastidiado",
			nosotros: "hubimos fastidiado",
			vosotros: "hubisteis fastidiado",
			Uds: "hubieron fastidiado",
		},
		Past: {
			yo: "había fastidiado",
			tú: "habías fastidiado",
			Ud: "había fastidiado",
			nosotros: "habíamos fastidiado",
			vosotros: "habíais fastidiado",
			Uds: "habían fastidiado",
		},
		Conditional: {
			yo: "habría fastidiado",
			tú: "habrías fastidiado",
			Ud: "habría fastidiado",
			nosotros: "habríamos fastidiado",
			vosotros: "habríais fastidiado",
			Uds: "habrían fastidiado",
		},
		Future: {
			yo: "habré fastidiado",
			tú: "habrás fastidiado",
			Ud: "habrá fastidiado",
			nosotros: "habremos fastidiado",
			vosotros: "habréis fastidiado",
			Uds: "habrán fastidiado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya fastidiado",
			tú: "hayas fastidiado",
			Ud: "haya fastidiado",
			nosotros: "hayamos fastidiado",
			vosotros: "hayáis fastidiado",
			Uds: "hayan fastidiado",
		},
		Past: {
			yo: "hubiera fastidiado",
			tú: "hubieras fastidiado",
			Ud: "hubiera fastidiado",
			nosotros: "hubiéramos fastidiado",
			vosotros: "hubierais fastidiado",
			Uds: "hubieran fastidiado",
		},
		Future: {
			yo: "hubiere fastidiado",
			tú: "hubieres fastidiado",
			Ud: "hubiere fastidiado",
			nosotros: "hubiéremos fastidiado",
			vosotros: "hubiereis fastidiado",
			Uds: "hubieren fastidiado",
		},
	},
}
