var filosofar = {
	Indicative: {
		Present: {
			yo: "filosofo",
			tú: "filosofas",
			Ud: "filosofa",
			nosotros: "filosofamos",
			vosotros: "filosofáis",
			Uds: "filosofan",
		},
		Preterite: {
			yo: "filosofé",
			tú: "filosofaste",
			Ud: "filosofó",
			nosotros: "filosofamos",
			vosotros: "filosofasteis",
			Uds: "filosofaron",
		},
		Imperfect: {
			yo: "filosofaba",
			tú: "filosofabas",
			Ud: "filosofaba",
			nosotros: "filosofábamos",
			vosotros: "filosofabais",
			Uds: "filosofaban",
		},
		Conditional: {
			yo: "filosofaría",
			tú: "filosofarías",
			Ud: "filosofaría",
			nosotros: "filosofaríamos",
			vosotros: "filosofaríais",
			Uds: "filosofarían",
		},
		Future: {
			yo: "filosofaré",
			tú: "filosofarás",
			Ud: "filosofará",
			nosotros: "filosofaremos",
			vosotros: "filosofaréis",
			Uds: "filosofarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "filosofe",
			tú: "filosofes",
			Ud: "filosofe",
			nosotros: "filosofemos",
			vosotros: "filosoféis",
			Uds: "filosofen",
		},
		Imperfect: {
			yo: "filosofara",
			tú: "filosofaras",
			Ud: "filosofara",
			nosotros: "filosofáramos",
			vosotros: "filosofarais",
			Uds: "filosofaran",
		},
		Imperfect2: {
			yo: "filosofase",
			tú: "filosofases",
			Ud: "filosofase",
			nosotros: "filosofásemos",
			vosotros: "filosofaseis",
			Uds: "filosofasen",
		},
		Future: {
			yo: "filosofare",
			tú: "filosofares",
			Ud: "filosofare",
			nosotros: "filosofáremos",
			vosotros: "filosofareis",
			Uds: "filosofaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "filosofa",
			Ud: "filosofe",
			nosotros: "filosofemos",
			vosotros: "filosofad",
			Uds: "filosofen",
		},
		Negative: {
			tú: "no filosofes",
			Ud: "no filosofe",
			nosotros: "no filosofemos",
			vosotros: "no filosoféis",
			Uds: "no filosofen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy filosofando",
			tú: "estás filosofando",
			Ud: "está filosofando",
			nosotros: "estamos filosofando",
			vosotros: "estáis filosofando",
			Uds: "están filosofando",
		},
		Preterite: {
			yo: "estuve filosofando",
			tú: "estuviste filosofando",
			Ud: "estuvo filosofando",
			nosotros: "estuvimos filosofando",
			vosotros: "estuvisteis filosofando",
			Uds: "estuvieron filosofando",
		},
		Imperfect: {
			Uds: "estaban filosofando",
			yo: "estaba filosofando",
			tú: "estabas filosofando",
			Ud: "estaba filosofando",
			nosotros: "estábamos filosofando",
			vosotros: "estabais filosofando",
		},
		Conditional: {
			yo: "estaría filosofando",
			tú: "estarías filosofando",
			Ud: "estaría filosofando",
			nosotros: "estaríamos filosofando",
			vosotros: "estaríais filosofando",
			Uds: "estarían filosofando",
		},
		Future: {
			yo: "estaré filosofando",
			tú: "estarás filosofando",
			Ud: "estará filosofando",
			nosotros: "estaremos filosofando",
			vosotros: "estaréis filosofando",
			Uds: "estarán filosofando",
		},
	},
	Perfect: {
		Present: {
			yo: "he filosofado",
			tú: "has filosofado",
			Ud: "ha filosofado",
			nosotros: "hemos filosofado",
			vosotros: "habéis filosofado",
			Uds: "han filosofado",
		},
		Preterite: {
			yo: "hube filosofado",
			tú: "hubiste filosofado",
			Ud: "hubo filosofado",
			nosotros: "hubimos filosofado",
			vosotros: "hubisteis filosofado",
			Uds: "hubieron filosofado",
		},
		Past: {
			yo: "había filosofado",
			tú: "habías filosofado",
			Ud: "había filosofado",
			nosotros: "habíamos filosofado",
			vosotros: "habíais filosofado",
			Uds: "habían filosofado",
		},
		Conditional: {
			yo: "habría filosofado",
			tú: "habrías filosofado",
			Ud: "habría filosofado",
			nosotros: "habríamos filosofado",
			vosotros: "habríais filosofado",
			Uds: "habrían filosofado",
		},
		Future: {
			yo: "habré filosofado",
			tú: "habrás filosofado",
			Ud: "habrá filosofado",
			nosotros: "habremos filosofado",
			vosotros: "habréis filosofado",
			Uds: "habrán filosofado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya filosofado",
			tú: "hayas filosofado",
			Ud: "haya filosofado",
			nosotros: "hayamos filosofado",
			vosotros: "hayáis filosofado",
			Uds: "hayan filosofado",
		},
		Past: {
			yo: "hubiera filosofado",
			tú: "hubieras filosofado",
			Ud: "hubiera filosofado",
			nosotros: "hubiéramos filosofado",
			vosotros: "hubierais filosofado",
			Uds: "hubieran filosofado",
		},
		Future: {
			yo: "hubiere filosofado",
			tú: "hubieres filosofado",
			Ud: "hubiere filosofado",
			nosotros: "hubiéremos filosofado",
			vosotros: "hubiereis filosofado",
			Uds: "hubieren filosofado",
		},
	},
}
