var filtrar = {
	Indicative: {
		Present: {
			yo: "filtro",
			tú: "filtras",
			Ud: "filtra",
			nosotros: "filtramos",
			vosotros: "filtráis",
			Uds: "filtran",
		},
		Preterite: {
			yo: "filtré",
			tú: "filtraste",
			Ud: "filtró",
			nosotros: "filtramos",
			vosotros: "filtrasteis",
			Uds: "filtraron",
		},
		Imperfect: {
			yo: "filtraba",
			tú: "filtrabas",
			Ud: "filtraba",
			nosotros: "filtrábamos",
			vosotros: "filtrabais",
			Uds: "filtraban",
		},
		Conditional: {
			yo: "filtraría",
			tú: "filtrarías",
			Ud: "filtraría",
			nosotros: "filtraríamos",
			vosotros: "filtraríais",
			Uds: "filtrarían",
		},
		Future: {
			yo: "filtraré",
			tú: "filtrarás",
			Ud: "filtrará",
			nosotros: "filtraremos",
			vosotros: "filtraréis",
			Uds: "filtrarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "filtre",
			tú: "filtres",
			Ud: "filtre",
			nosotros: "filtremos",
			vosotros: "filtréis",
			Uds: "filtren",
		},
		Imperfect: {
			yo: "filtrara",
			tú: "filtraras",
			Ud: "filtrara",
			nosotros: "filtráramos",
			vosotros: "filtrarais",
			Uds: "filtraran",
		},
		Imperfect2: {
			yo: "filtrase",
			tú: "filtrases",
			Ud: "filtrase",
			nosotros: "filtrásemos",
			vosotros: "filtraseis",
			Uds: "filtrasen",
		},
		Future: {
			yo: "filtrare",
			tú: "filtrares",
			Ud: "filtrare",
			nosotros: "filtráremos",
			vosotros: "filtrareis",
			Uds: "filtraren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "filtra",
			Ud: "filtre",
			nosotros: "filtremos",
			vosotros: "filtrad",
			Uds: "filtren",
		},
		Negative: {
			tú: "no filtres",
			Ud: "no filtre",
			nosotros: "no filtremos",
			vosotros: "no filtréis",
			Uds: "no filtren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy filtrando",
			tú: "estás filtrando",
			Ud: "está filtrando",
			nosotros: "estamos filtrando",
			vosotros: "estáis filtrando",
			Uds: "están filtrando",
		},
		Preterite: {
			yo: "estuve filtrando",
			tú: "estuviste filtrando",
			Ud: "estuvo filtrando",
			nosotros: "estuvimos filtrando",
			vosotros: "estuvisteis filtrando",
			Uds: "estuvieron filtrando",
		},
		Imperfect: {
			Uds: "estaban filtrando",
			yo: "estaba filtrando",
			tú: "estabas filtrando",
			Ud: "estaba filtrando",
			nosotros: "estábamos filtrando",
			vosotros: "estabais filtrando",
		},
		Conditional: {
			yo: "estaría filtrando",
			tú: "estarías filtrando",
			Ud: "estaría filtrando",
			nosotros: "estaríamos filtrando",
			vosotros: "estaríais filtrando",
			Uds: "estarían filtrando",
		},
		Future: {
			yo: "estaré filtrando",
			tú: "estarás filtrando",
			Ud: "estará filtrando",
			nosotros: "estaremos filtrando",
			vosotros: "estaréis filtrando",
			Uds: "estarán filtrando",
		},
	},
	Perfect: {
		Present: {
			yo: "he filtrado",
			tú: "has filtrado",
			Ud: "ha filtrado",
			nosotros: "hemos filtrado",
			vosotros: "habéis filtrado",
			Uds: "han filtrado",
		},
		Preterite: {
			yo: "hube filtrado",
			tú: "hubiste filtrado",
			Ud: "hubo filtrado",
			nosotros: "hubimos filtrado",
			vosotros: "hubisteis filtrado",
			Uds: "hubieron filtrado",
		},
		Past: {
			yo: "había filtrado",
			tú: "habías filtrado",
			Ud: "había filtrado",
			nosotros: "habíamos filtrado",
			vosotros: "habíais filtrado",
			Uds: "habían filtrado",
		},
		Conditional: {
			yo: "habría filtrado",
			tú: "habrías filtrado",
			Ud: "habría filtrado",
			nosotros: "habríamos filtrado",
			vosotros: "habríais filtrado",
			Uds: "habrían filtrado",
		},
		Future: {
			yo: "habré filtrado",
			tú: "habrás filtrado",
			Ud: "habrá filtrado",
			nosotros: "habremos filtrado",
			vosotros: "habréis filtrado",
			Uds: "habrán filtrado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya filtrado",
			tú: "hayas filtrado",
			Ud: "haya filtrado",
			nosotros: "hayamos filtrado",
			vosotros: "hayáis filtrado",
			Uds: "hayan filtrado",
		},
		Past: {
			yo: "hubiera filtrado",
			tú: "hubieras filtrado",
			Ud: "hubiera filtrado",
			nosotros: "hubiéramos filtrado",
			vosotros: "hubierais filtrado",
			Uds: "hubieran filtrado",
		},
		Future: {
			yo: "hubiere filtrado",
			tú: "hubieres filtrado",
			Ud: "hubiere filtrado",
			nosotros: "hubiéremos filtrado",
			vosotros: "hubiereis filtrado",
			Uds: "hubieren filtrado",
		},
	},
}
