var fisgonear = {
	Indicative: {
		Present: {
			yo: "fisgoneo",
			tú: "fisgoneas",
			Ud: "fisgonea",
			nosotros: "fisgoneamos",
			vosotros: "fisgoneáis",
			Uds: "fisgonean",
		},
		Preterite: {
			yo: "fisgoneé",
			tú: "fisgoneaste",
			Ud: "fisgoneó",
			nosotros: "fisgoneamos",
			vosotros: "fisgoneasteis",
			Uds: "fisgonearon",
		},
		Imperfect: {
			yo: "fisgoneaba",
			tú: "fisgoneabas",
			Ud: "fisgoneaba",
			nosotros: "fisgoneábamos",
			vosotros: "fisgoneabais",
			Uds: "fisgoneaban",
		},
		Conditional: {
			yo: "fisgonearía",
			tú: "fisgonearías",
			Ud: "fisgonearía",
			nosotros: "fisgonearíamos",
			vosotros: "fisgonearíais",
			Uds: "fisgonearían",
		},
		Future: {
			yo: "fisgonearé",
			tú: "fisgonearás",
			Ud: "fisgoneará",
			nosotros: "fisgonearemos",
			vosotros: "fisgonearéis",
			Uds: "fisgonearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "fisgonee",
			tú: "fisgonees",
			Ud: "fisgonee",
			nosotros: "fisgoneemos",
			vosotros: "fisgoneéis",
			Uds: "fisgoneen",
		},
		Imperfect: {
			yo: "fisgoneara",
			tú: "fisgonearas",
			Ud: "fisgoneara",
			nosotros: "fisgoneáramos",
			vosotros: "fisgonearais",
			Uds: "fisgonearan",
		},
		Imperfect2: {
			yo: "fisgonease",
			tú: "fisgoneases",
			Ud: "fisgonease",
			nosotros: "fisgoneásemos",
			vosotros: "fisgoneaseis",
			Uds: "fisgoneasen",
		},
		Future: {
			yo: "fisgoneare",
			tú: "fisgoneares",
			Ud: "fisgoneare",
			nosotros: "fisgoneáremos",
			vosotros: "fisgoneareis",
			Uds: "fisgonearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "fisgonea",
			Ud: "fisgonee",
			nosotros: "fisgoneemos",
			vosotros: "fisgonead",
			Uds: "fisgoneen",
		},
		Negative: {
			tú: "no fisgonees",
			Ud: "no fisgonee",
			nosotros: "no fisgoneemos",
			vosotros: "no fisgoneéis",
			Uds: "no fisgoneen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy fisgoneando",
			tú: "estás fisgoneando",
			Ud: "está fisgoneando",
			nosotros: "estamos fisgoneando",
			vosotros: "estáis fisgoneando",
			Uds: "están fisgoneando",
		},
		Preterite: {
			yo: "estuve fisgoneando",
			tú: "estuviste fisgoneando",
			Ud: "estuvo fisgoneando",
			nosotros: "estuvimos fisgoneando",
			vosotros: "estuvisteis fisgoneando",
			Uds: "estuvieron fisgoneando",
		},
		Imperfect: {
			Uds: "estaban fisgoneando",
			yo: "estaba fisgoneando",
			tú: "estabas fisgoneando",
			Ud: "estaba fisgoneando",
			nosotros: "estábamos fisgoneando",
			vosotros: "estabais fisgoneando",
		},
		Conditional: {
			yo: "estaría fisgoneando",
			tú: "estarías fisgoneando",
			Ud: "estaría fisgoneando",
			nosotros: "estaríamos fisgoneando",
			vosotros: "estaríais fisgoneando",
			Uds: "estarían fisgoneando",
		},
		Future: {
			yo: "estaré fisgoneando",
			tú: "estarás fisgoneando",
			Ud: "estará fisgoneando",
			nosotros: "estaremos fisgoneando",
			vosotros: "estaréis fisgoneando",
			Uds: "estarán fisgoneando",
		},
	},
	Perfect: {
		Present: {
			yo: "he fisgoneado",
			tú: "has fisgoneado",
			Ud: "ha fisgoneado",
			nosotros: "hemos fisgoneado",
			vosotros: "habéis fisgoneado",
			Uds: "han fisgoneado",
		},
		Preterite: {
			yo: "hube fisgoneado",
			tú: "hubiste fisgoneado",
			Ud: "hubo fisgoneado",
			nosotros: "hubimos fisgoneado",
			vosotros: "hubisteis fisgoneado",
			Uds: "hubieron fisgoneado",
		},
		Past: {
			yo: "había fisgoneado",
			tú: "habías fisgoneado",
			Ud: "había fisgoneado",
			nosotros: "habíamos fisgoneado",
			vosotros: "habíais fisgoneado",
			Uds: "habían fisgoneado",
		},
		Conditional: {
			yo: "habría fisgoneado",
			tú: "habrías fisgoneado",
			Ud: "habría fisgoneado",
			nosotros: "habríamos fisgoneado",
			vosotros: "habríais fisgoneado",
			Uds: "habrían fisgoneado",
		},
		Future: {
			yo: "habré fisgoneado",
			tú: "habrás fisgoneado",
			Ud: "habrá fisgoneado",
			nosotros: "habremos fisgoneado",
			vosotros: "habréis fisgoneado",
			Uds: "habrán fisgoneado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya fisgoneado",
			tú: "hayas fisgoneado",
			Ud: "haya fisgoneado",
			nosotros: "hayamos fisgoneado",
			vosotros: "hayáis fisgoneado",
			Uds: "hayan fisgoneado",
		},
		Past: {
			yo: "hubiera fisgoneado",
			tú: "hubieras fisgoneado",
			Ud: "hubiera fisgoneado",
			nosotros: "hubiéramos fisgoneado",
			vosotros: "hubierais fisgoneado",
			Uds: "hubieran fisgoneado",
		},
		Future: {
			yo: "hubiere fisgoneado",
			tú: "hubieres fisgoneado",
			Ud: "hubiere fisgoneado",
			nosotros: "hubiéremos fisgoneado",
			vosotros: "hubiereis fisgoneado",
			Uds: "hubieren fisgoneado",
		},
	},
}
