var flagelar = {
	Indicative: {
		Present: {
			yo: "flagelo",
			tú: "flagelas",
			Ud: "flagela",
			nosotros: "flagelamos",
			vosotros: "flageláis",
			Uds: "flagelan",
		},
		Preterite: {
			yo: "flagelé",
			tú: "flagelaste",
			Ud: "flageló",
			nosotros: "flagelamos",
			vosotros: "flagelasteis",
			Uds: "flagelaron",
		},
		Imperfect: {
			yo: "flagelaba",
			tú: "flagelabas",
			Ud: "flagelaba",
			nosotros: "flagelábamos",
			vosotros: "flagelabais",
			Uds: "flagelaban",
		},
		Conditional: {
			yo: "flagelaría",
			tú: "flagelarías",
			Ud: "flagelaría",
			nosotros: "flagelaríamos",
			vosotros: "flagelaríais",
			Uds: "flagelarían",
		},
		Future: {
			yo: "flagelaré",
			tú: "flagelarás",
			Ud: "flagelará",
			nosotros: "flagelaremos",
			vosotros: "flagelaréis",
			Uds: "flagelarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "flagele",
			tú: "flageles",
			Ud: "flagele",
			nosotros: "flagelemos",
			vosotros: "flageléis",
			Uds: "flagelen",
		},
		Imperfect: {
			yo: "flagelara",
			tú: "flagelaras",
			Ud: "flagelara",
			nosotros: "flageláramos",
			vosotros: "flagelarais",
			Uds: "flagelaran",
		},
		Imperfect2: {
			yo: "flagelase",
			tú: "flagelases",
			Ud: "flagelase",
			nosotros: "flagelásemos",
			vosotros: "flagelaseis",
			Uds: "flagelasen",
		},
		Future: {
			yo: "flagelare",
			tú: "flagelares",
			Ud: "flagelare",
			nosotros: "flageláremos",
			vosotros: "flagelareis",
			Uds: "flagelaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "flagela",
			Ud: "flagele",
			nosotros: "flagelemos",
			vosotros: "flagelad",
			Uds: "flagelen",
		},
		Negative: {
			tú: "no flageles",
			Ud: "no flagele",
			nosotros: "no flagelemos",
			vosotros: "no flageléis",
			Uds: "no flagelen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy flagelando",
			tú: "estás flagelando",
			Ud: "está flagelando",
			nosotros: "estamos flagelando",
			vosotros: "estáis flagelando",
			Uds: "están flagelando",
		},
		Preterite: {
			yo: "estuve flagelando",
			tú: "estuviste flagelando",
			Ud: "estuvo flagelando",
			nosotros: "estuvimos flagelando",
			vosotros: "estuvisteis flagelando",
			Uds: "estuvieron flagelando",
		},
		Imperfect: {
			Uds: "estaban flagelando",
			yo: "estaba flagelando",
			tú: "estabas flagelando",
			Ud: "estaba flagelando",
			nosotros: "estábamos flagelando",
			vosotros: "estabais flagelando",
		},
		Conditional: {
			yo: "estaría flagelando",
			tú: "estarías flagelando",
			Ud: "estaría flagelando",
			nosotros: "estaríamos flagelando",
			vosotros: "estaríais flagelando",
			Uds: "estarían flagelando",
		},
		Future: {
			yo: "estaré flagelando",
			tú: "estarás flagelando",
			Ud: "estará flagelando",
			nosotros: "estaremos flagelando",
			vosotros: "estaréis flagelando",
			Uds: "estarán flagelando",
		},
	},
	Perfect: {
		Present: {
			yo: "he flagelado",
			tú: "has flagelado",
			Ud: "ha flagelado",
			nosotros: "hemos flagelado",
			vosotros: "habéis flagelado",
			Uds: "han flagelado",
		},
		Preterite: {
			yo: "hube flagelado",
			tú: "hubiste flagelado",
			Ud: "hubo flagelado",
			nosotros: "hubimos flagelado",
			vosotros: "hubisteis flagelado",
			Uds: "hubieron flagelado",
		},
		Past: {
			yo: "había flagelado",
			tú: "habías flagelado",
			Ud: "había flagelado",
			nosotros: "habíamos flagelado",
			vosotros: "habíais flagelado",
			Uds: "habían flagelado",
		},
		Conditional: {
			yo: "habría flagelado",
			tú: "habrías flagelado",
			Ud: "habría flagelado",
			nosotros: "habríamos flagelado",
			vosotros: "habríais flagelado",
			Uds: "habrían flagelado",
		},
		Future: {
			yo: "habré flagelado",
			tú: "habrás flagelado",
			Ud: "habrá flagelado",
			nosotros: "habremos flagelado",
			vosotros: "habréis flagelado",
			Uds: "habrán flagelado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya flagelado",
			tú: "hayas flagelado",
			Ud: "haya flagelado",
			nosotros: "hayamos flagelado",
			vosotros: "hayáis flagelado",
			Uds: "hayan flagelado",
		},
		Past: {
			yo: "hubiera flagelado",
			tú: "hubieras flagelado",
			Ud: "hubiera flagelado",
			nosotros: "hubiéramos flagelado",
			vosotros: "hubierais flagelado",
			Uds: "hubieran flagelado",
		},
		Future: {
			yo: "hubiere flagelado",
			tú: "hubieres flagelado",
			Ud: "hubiere flagelado",
			nosotros: "hubiéremos flagelado",
			vosotros: "hubiereis flagelado",
			Uds: "hubieren flagelado",
		},
	},
}
