var flexionar = {
	Indicative: {
		Present: {
			yo: "flexiono",
			tú: "flexionas",
			Ud: "flexiona",
			nosotros: "flexionamos",
			vosotros: "flexionáis",
			Uds: "flexionan",
		},
		Preterite: {
			yo: "flexioné",
			tú: "flexionaste",
			Ud: "flexionó",
			nosotros: "flexionamos",
			vosotros: "flexionasteis",
			Uds: "flexionaron",
		},
		Imperfect: {
			yo: "flexionaba",
			tú: "flexionabas",
			Ud: "flexionaba",
			nosotros: "flexionábamos",
			vosotros: "flexionabais",
			Uds: "flexionaban",
		},
		Conditional: {
			yo: "flexionaría",
			tú: "flexionarías",
			Ud: "flexionaría",
			nosotros: "flexionaríamos",
			vosotros: "flexionaríais",
			Uds: "flexionarían",
		},
		Future: {
			yo: "flexionaré",
			tú: "flexionarás",
			Ud: "flexionará",
			nosotros: "flexionaremos",
			vosotros: "flexionaréis",
			Uds: "flexionarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "flexione",
			tú: "flexiones",
			Ud: "flexione",
			nosotros: "flexionemos",
			vosotros: "flexionéis",
			Uds: "flexionen",
		},
		Imperfect: {
			yo: "flexionara",
			tú: "flexionaras",
			Ud: "flexionara",
			nosotros: "flexionáramos",
			vosotros: "flexionarais",
			Uds: "flexionaran",
		},
		Imperfect2: {
			yo: "flexionase",
			tú: "flexionases",
			Ud: "flexionase",
			nosotros: "flexionásemos",
			vosotros: "flexionaseis",
			Uds: "flexionasen",
		},
		Future: {
			yo: "flexionare",
			tú: "flexionares",
			Ud: "flexionare",
			nosotros: "flexionáremos",
			vosotros: "flexionareis",
			Uds: "flexionaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "flexiona",
			Ud: "flexione",
			nosotros: "flexionemos",
			vosotros: "flexionad",
			Uds: "flexionen",
		},
		Negative: {
			tú: "no flexiones",
			Ud: "no flexione",
			nosotros: "no flexionemos",
			vosotros: "no flexionéis",
			Uds: "no flexionen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy flexionando",
			tú: "estás flexionando",
			Ud: "está flexionando",
			nosotros: "estamos flexionando",
			vosotros: "estáis flexionando",
			Uds: "están flexionando",
		},
		Preterite: {
			yo: "estuve flexionando",
			tú: "estuviste flexionando",
			Ud: "estuvo flexionando",
			nosotros: "estuvimos flexionando",
			vosotros: "estuvisteis flexionando",
			Uds: "estuvieron flexionando",
		},
		Imperfect: {
			Uds: "estaban flexionando",
			yo: "estaba flexionando",
			tú: "estabas flexionando",
			Ud: "estaba flexionando",
			nosotros: "estábamos flexionando",
			vosotros: "estabais flexionando",
		},
		Conditional: {
			yo: "estaría flexionando",
			tú: "estarías flexionando",
			Ud: "estaría flexionando",
			nosotros: "estaríamos flexionando",
			vosotros: "estaríais flexionando",
			Uds: "estarían flexionando",
		},
		Future: {
			yo: "estaré flexionando",
			tú: "estarás flexionando",
			Ud: "estará flexionando",
			nosotros: "estaremos flexionando",
			vosotros: "estaréis flexionando",
			Uds: "estarán flexionando",
		},
	},
	Perfect: {
		Present: {
			yo: "he flexionado",
			tú: "has flexionado",
			Ud: "ha flexionado",
			nosotros: "hemos flexionado",
			vosotros: "habéis flexionado",
			Uds: "han flexionado",
		},
		Preterite: {
			yo: "hube flexionado",
			tú: "hubiste flexionado",
			Ud: "hubo flexionado",
			nosotros: "hubimos flexionado",
			vosotros: "hubisteis flexionado",
			Uds: "hubieron flexionado",
		},
		Past: {
			yo: "había flexionado",
			tú: "habías flexionado",
			Ud: "había flexionado",
			nosotros: "habíamos flexionado",
			vosotros: "habíais flexionado",
			Uds: "habían flexionado",
		},
		Conditional: {
			yo: "habría flexionado",
			tú: "habrías flexionado",
			Ud: "habría flexionado",
			nosotros: "habríamos flexionado",
			vosotros: "habríais flexionado",
			Uds: "habrían flexionado",
		},
		Future: {
			yo: "habré flexionado",
			tú: "habrás flexionado",
			Ud: "habrá flexionado",
			nosotros: "habremos flexionado",
			vosotros: "habréis flexionado",
			Uds: "habrán flexionado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya flexionado",
			tú: "hayas flexionado",
			Ud: "haya flexionado",
			nosotros: "hayamos flexionado",
			vosotros: "hayáis flexionado",
			Uds: "hayan flexionado",
		},
		Past: {
			yo: "hubiera flexionado",
			tú: "hubieras flexionado",
			Ud: "hubiera flexionado",
			nosotros: "hubiéramos flexionado",
			vosotros: "hubierais flexionado",
			Uds: "hubieran flexionado",
		},
		Future: {
			yo: "hubiere flexionado",
			tú: "hubieres flexionado",
			Ud: "hubiere flexionado",
			nosotros: "hubiéremos flexionado",
			vosotros: "hubiereis flexionado",
			Uds: "hubieren flexionado",
		},
	},
}
