var formar = {
	Indicative: {
		Present: {
			yo: "formo",
			tú: "formas",
			Ud: "forma",
			nosotros: "formamos",
			vosotros: "formáis",
			Uds: "forman",
		},
		Preterite: {
			yo: "formé",
			tú: "formaste",
			Ud: "formó",
			nosotros: "formamos",
			vosotros: "formasteis",
			Uds: "formaron",
		},
		Imperfect: {
			yo: "formaba",
			tú: "formabas",
			Ud: "formaba",
			nosotros: "formábamos",
			vosotros: "formabais",
			Uds: "formaban",
		},
		Conditional: {
			yo: "formaría",
			tú: "formarías",
			Ud: "formaría",
			nosotros: "formaríamos",
			vosotros: "formaríais",
			Uds: "formarían",
		},
		Future: {
			yo: "formaré",
			tú: "formarás",
			Ud: "formará",
			nosotros: "formaremos",
			vosotros: "formaréis",
			Uds: "formarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "forme",
			tú: "formes",
			Ud: "forme",
			nosotros: "formemos",
			vosotros: "forméis",
			Uds: "formen",
		},
		Imperfect: {
			yo: "formara",
			tú: "formaras",
			Ud: "formara",
			nosotros: "formáramos",
			vosotros: "formarais",
			Uds: "formaran",
		},
		Imperfect2: {
			yo: "formase",
			tú: "formases",
			Ud: "formase",
			nosotros: "formásemos",
			vosotros: "formaseis",
			Uds: "formasen",
		},
		Future: {
			yo: "formare",
			tú: "formares",
			Ud: "formare",
			nosotros: "formáremos",
			vosotros: "formareis",
			Uds: "formaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "forma",
			Ud: "forme",
			nosotros: "formemos",
			vosotros: "formad",
			Uds: "formen",
		},
		Negative: {
			tú: "no formes",
			Ud: "no forme",
			nosotros: "no formemos",
			vosotros: "no forméis",
			Uds: "no formen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy formando",
			tú: "estás formando",
			Ud: "está formando",
			nosotros: "estamos formando",
			vosotros: "estáis formando",
			Uds: "están formando",
		},
		Preterite: {
			yo: "estuve formando",
			tú: "estuviste formando",
			Ud: "estuvo formando",
			nosotros: "estuvimos formando",
			vosotros: "estuvisteis formando",
			Uds: "estuvieron formando",
		},
		Imperfect: {
			Uds: "estaban formando",
			yo: "estaba formando",
			tú: "estabas formando",
			Ud: "estaba formando",
			nosotros: "estábamos formando",
			vosotros: "estabais formando",
		},
		Conditional: {
			yo: "estaría formando",
			tú: "estarías formando",
			Ud: "estaría formando",
			nosotros: "estaríamos formando",
			vosotros: "estaríais formando",
			Uds: "estarían formando",
		},
		Future: {
			yo: "estaré formando",
			tú: "estarás formando",
			Ud: "estará formando",
			nosotros: "estaremos formando",
			vosotros: "estaréis formando",
			Uds: "estarán formando",
		},
	},
	Perfect: {
		Present: {
			yo: "he formado",
			tú: "has formado",
			Ud: "ha formado",
			nosotros: "hemos formado",
			vosotros: "habéis formado",
			Uds: "han formado",
		},
		Preterite: {
			yo: "hube formado",
			tú: "hubiste formado",
			Ud: "hubo formado",
			nosotros: "hubimos formado",
			vosotros: "hubisteis formado",
			Uds: "hubieron formado",
		},
		Past: {
			yo: "había formado",
			tú: "habías formado",
			Ud: "había formado",
			nosotros: "habíamos formado",
			vosotros: "habíais formado",
			Uds: "habían formado",
		},
		Conditional: {
			yo: "habría formado",
			tú: "habrías formado",
			Ud: "habría formado",
			nosotros: "habríamos formado",
			vosotros: "habríais formado",
			Uds: "habrían formado",
		},
		Future: {
			yo: "habré formado",
			tú: "habrás formado",
			Ud: "habrá formado",
			nosotros: "habremos formado",
			vosotros: "habréis formado",
			Uds: "habrán formado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya formado",
			tú: "hayas formado",
			Ud: "haya formado",
			nosotros: "hayamos formado",
			vosotros: "hayáis formado",
			Uds: "hayan formado",
		},
		Past: {
			yo: "hubiera formado",
			tú: "hubieras formado",
			Ud: "hubiera formado",
			nosotros: "hubiéramos formado",
			vosotros: "hubierais formado",
			Uds: "hubieran formado",
		},
		Future: {
			yo: "hubiere formado",
			tú: "hubieres formado",
			Ud: "hubiere formado",
			nosotros: "hubiéremos formado",
			vosotros: "hubiereis formado",
			Uds: "hubieren formado",
		},
	},
}
