var forrajear = {
	Indicative: {
		Present: {
			yo: "forrajeo",
			tú: "forrajeas",
			Ud: "forrajea",
			nosotros: "forrajeamos",
			vosotros: "forrajeáis",
			Uds: "forrajean",
		},
		Preterite: {
			yo: "forrajeé",
			tú: "forrajeaste",
			Ud: "forrajeó",
			nosotros: "forrajeamos",
			vosotros: "forrajeasteis",
			Uds: "forrajearon",
		},
		Imperfect: {
			yo: "forrajeaba",
			tú: "forrajeabas",
			Ud: "forrajeaba",
			nosotros: "forrajeábamos",
			vosotros: "forrajeabais",
			Uds: "forrajeaban",
		},
		Conditional: {
			yo: "forrajearía",
			tú: "forrajearías",
			Ud: "forrajearía",
			nosotros: "forrajearíamos",
			vosotros: "forrajearíais",
			Uds: "forrajearían",
		},
		Future: {
			yo: "forrajearé",
			tú: "forrajearás",
			Ud: "forrajeará",
			nosotros: "forrajearemos",
			vosotros: "forrajearéis",
			Uds: "forrajearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "forrajee",
			tú: "forrajees",
			Ud: "forrajee",
			nosotros: "forrajeemos",
			vosotros: "forrajeéis",
			Uds: "forrajeen",
		},
		Imperfect: {
			yo: "forrajeara",
			tú: "forrajearas",
			Ud: "forrajeara",
			nosotros: "forrajeáramos",
			vosotros: "forrajearais",
			Uds: "forrajearan",
		},
		Imperfect2: {
			yo: "forrajease",
			tú: "forrajeases",
			Ud: "forrajease",
			nosotros: "forrajeásemos",
			vosotros: "forrajeaseis",
			Uds: "forrajeasen",
		},
		Future: {
			yo: "forrajeare",
			tú: "forrajeares",
			Ud: "forrajeare",
			nosotros: "forrajeáremos",
			vosotros: "forrajeareis",
			Uds: "forrajearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "forrajea",
			Ud: "forrajee",
			nosotros: "forrajeemos",
			vosotros: "forrajead",
			Uds: "forrajeen",
		},
		Negative: {
			tú: "no forrajees",
			Ud: "no forrajee",
			nosotros: "no forrajeemos",
			vosotros: "no forrajeéis",
			Uds: "no forrajeen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy forrajeando",
			tú: "estás forrajeando",
			Ud: "está forrajeando",
			nosotros: "estamos forrajeando",
			vosotros: "estáis forrajeando",
			Uds: "están forrajeando",
		},
		Preterite: {
			yo: "estuve forrajeando",
			tú: "estuviste forrajeando",
			Ud: "estuvo forrajeando",
			nosotros: "estuvimos forrajeando",
			vosotros: "estuvisteis forrajeando",
			Uds: "estuvieron forrajeando",
		},
		Imperfect: {
			Uds: "estaban forrajeando",
			yo: "estaba forrajeando",
			tú: "estabas forrajeando",
			Ud: "estaba forrajeando",
			nosotros: "estábamos forrajeando",
			vosotros: "estabais forrajeando",
		},
		Conditional: {
			yo: "estaría forrajeando",
			tú: "estarías forrajeando",
			Ud: "estaría forrajeando",
			nosotros: "estaríamos forrajeando",
			vosotros: "estaríais forrajeando",
			Uds: "estarían forrajeando",
		},
		Future: {
			yo: "estaré forrajeando",
			tú: "estarás forrajeando",
			Ud: "estará forrajeando",
			nosotros: "estaremos forrajeando",
			vosotros: "estaréis forrajeando",
			Uds: "estarán forrajeando",
		},
	},
	Perfect: {
		Present: {
			yo: "he forrajeado",
			tú: "has forrajeado",
			Ud: "ha forrajeado",
			nosotros: "hemos forrajeado",
			vosotros: "habéis forrajeado",
			Uds: "han forrajeado",
		},
		Preterite: {
			yo: "hube forrajeado",
			tú: "hubiste forrajeado",
			Ud: "hubo forrajeado",
			nosotros: "hubimos forrajeado",
			vosotros: "hubisteis forrajeado",
			Uds: "hubieron forrajeado",
		},
		Past: {
			yo: "había forrajeado",
			tú: "habías forrajeado",
			Ud: "había forrajeado",
			nosotros: "habíamos forrajeado",
			vosotros: "habíais forrajeado",
			Uds: "habían forrajeado",
		},
		Conditional: {
			yo: "habría forrajeado",
			tú: "habrías forrajeado",
			Ud: "habría forrajeado",
			nosotros: "habríamos forrajeado",
			vosotros: "habríais forrajeado",
			Uds: "habrían forrajeado",
		},
		Future: {
			yo: "habré forrajeado",
			tú: "habrás forrajeado",
			Ud: "habrá forrajeado",
			nosotros: "habremos forrajeado",
			vosotros: "habréis forrajeado",
			Uds: "habrán forrajeado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya forrajeado",
			tú: "hayas forrajeado",
			Ud: "haya forrajeado",
			nosotros: "hayamos forrajeado",
			vosotros: "hayáis forrajeado",
			Uds: "hayan forrajeado",
		},
		Past: {
			yo: "hubiera forrajeado",
			tú: "hubieras forrajeado",
			Ud: "hubiera forrajeado",
			nosotros: "hubiéramos forrajeado",
			vosotros: "hubierais forrajeado",
			Uds: "hubieran forrajeado",
		},
		Future: {
			yo: "hubiere forrajeado",
			tú: "hubieres forrajeado",
			Ud: "hubiere forrajeado",
			nosotros: "hubiéremos forrajeado",
			vosotros: "hubiereis forrajeado",
			Uds: "hubieren forrajeado",
		},
	},
}
