var frecuentar = {
	Indicative: {
		Present: {
			yo: "frecuento",
			tú: "frecuentas",
			Ud: "frecuenta",
			nosotros: "frecuentamos",
			vosotros: "frecuentáis",
			Uds: "frecuentan",
		},
		Preterite: {
			yo: "frecuenté",
			tú: "frecuentaste",
			Ud: "frecuentó",
			nosotros: "frecuentamos",
			vosotros: "frecuentasteis",
			Uds: "frecuentaron",
		},
		Imperfect: {
			yo: "frecuentaba",
			tú: "frecuentabas",
			Ud: "frecuentaba",
			nosotros: "frecuentábamos",
			vosotros: "frecuentabais",
			Uds: "frecuentaban",
		},
		Conditional: {
			yo: "frecuentaría",
			tú: "frecuentarías",
			Ud: "frecuentaría",
			nosotros: "frecuentaríamos",
			vosotros: "frecuentaríais",
			Uds: "frecuentarían",
		},
		Future: {
			yo: "frecuentaré",
			tú: "frecuentarás",
			Ud: "frecuentará",
			nosotros: "frecuentaremos",
			vosotros: "frecuentaréis",
			Uds: "frecuentarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "frecuente",
			tú: "frecuentes",
			Ud: "frecuente",
			nosotros: "frecuentemos",
			vosotros: "frecuentéis",
			Uds: "frecuenten",
		},
		Imperfect: {
			yo: "frecuentara",
			tú: "frecuentaras",
			Ud: "frecuentara",
			nosotros: "frecuentáramos",
			vosotros: "frecuentarais",
			Uds: "frecuentaran",
		},
		Imperfect2: {
			yo: "frecuentase",
			tú: "frecuentases",
			Ud: "frecuentase",
			nosotros: "frecuentásemos",
			vosotros: "frecuentaseis",
			Uds: "frecuentasen",
		},
		Future: {
			yo: "frecuentare",
			tú: "frecuentares",
			Ud: "frecuentare",
			nosotros: "frecuentáremos",
			vosotros: "frecuentareis",
			Uds: "frecuentaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "frecuenta",
			Ud: "frecuente",
			nosotros: "frecuentemos",
			vosotros: "frecuentad",
			Uds: "frecuenten",
		},
		Negative: {
			tú: "no frecuentes",
			Ud: "no frecuente",
			nosotros: "no frecuentemos",
			vosotros: "no frecuentéis",
			Uds: "no frecuenten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy frecuentando",
			tú: "estás frecuentando",
			Ud: "está frecuentando",
			nosotros: "estamos frecuentando",
			vosotros: "estáis frecuentando",
			Uds: "están frecuentando",
		},
		Preterite: {
			yo: "estuve frecuentando",
			tú: "estuviste frecuentando",
			Ud: "estuvo frecuentando",
			nosotros: "estuvimos frecuentando",
			vosotros: "estuvisteis frecuentando",
			Uds: "estuvieron frecuentando",
		},
		Imperfect: {
			Uds: "estaban frecuentando",
			yo: "estaba frecuentando",
			tú: "estabas frecuentando",
			Ud: "estaba frecuentando",
			nosotros: "estábamos frecuentando",
			vosotros: "estabais frecuentando",
		},
		Conditional: {
			yo: "estaría frecuentando",
			tú: "estarías frecuentando",
			Ud: "estaría frecuentando",
			nosotros: "estaríamos frecuentando",
			vosotros: "estaríais frecuentando",
			Uds: "estarían frecuentando",
		},
		Future: {
			yo: "estaré frecuentando",
			tú: "estarás frecuentando",
			Ud: "estará frecuentando",
			nosotros: "estaremos frecuentando",
			vosotros: "estaréis frecuentando",
			Uds: "estarán frecuentando",
		},
	},
	Perfect: {
		Present: {
			yo: "he frecuentado",
			tú: "has frecuentado",
			Ud: "ha frecuentado",
			nosotros: "hemos frecuentado",
			vosotros: "habéis frecuentado",
			Uds: "han frecuentado",
		},
		Preterite: {
			yo: "hube frecuentado",
			tú: "hubiste frecuentado",
			Ud: "hubo frecuentado",
			nosotros: "hubimos frecuentado",
			vosotros: "hubisteis frecuentado",
			Uds: "hubieron frecuentado",
		},
		Past: {
			yo: "había frecuentado",
			tú: "habías frecuentado",
			Ud: "había frecuentado",
			nosotros: "habíamos frecuentado",
			vosotros: "habíais frecuentado",
			Uds: "habían frecuentado",
		},
		Conditional: {
			yo: "habría frecuentado",
			tú: "habrías frecuentado",
			Ud: "habría frecuentado",
			nosotros: "habríamos frecuentado",
			vosotros: "habríais frecuentado",
			Uds: "habrían frecuentado",
		},
		Future: {
			yo: "habré frecuentado",
			tú: "habrás frecuentado",
			Ud: "habrá frecuentado",
			nosotros: "habremos frecuentado",
			vosotros: "habréis frecuentado",
			Uds: "habrán frecuentado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya frecuentado",
			tú: "hayas frecuentado",
			Ud: "haya frecuentado",
			nosotros: "hayamos frecuentado",
			vosotros: "hayáis frecuentado",
			Uds: "hayan frecuentado",
		},
		Past: {
			yo: "hubiera frecuentado",
			tú: "hubieras frecuentado",
			Ud: "hubiera frecuentado",
			nosotros: "hubiéramos frecuentado",
			vosotros: "hubierais frecuentado",
			Uds: "hubieran frecuentado",
		},
		Future: {
			yo: "hubiere frecuentado",
			tú: "hubieres frecuentado",
			Ud: "hubiere frecuentado",
			nosotros: "hubiéremos frecuentado",
			vosotros: "hubiereis frecuentado",
			Uds: "hubieren frecuentado",
		},
	},
}
