var frotar = {
	Indicative: {
		Present: {
			yo: "froto",
			tú: "frotas",
			Ud: "frota",
			nosotros: "frotamos",
			vosotros: "frotáis",
			Uds: "frotan",
		},
		Preterite: {
			yo: "froté",
			tú: "frotaste",
			Ud: "frotó",
			nosotros: "frotamos",
			vosotros: "frotasteis",
			Uds: "frotaron",
		},
		Imperfect: {
			yo: "frotaba",
			tú: "frotabas",
			Ud: "frotaba",
			nosotros: "frotábamos",
			vosotros: "frotabais",
			Uds: "frotaban",
		},
		Conditional: {
			yo: "frotaría",
			tú: "frotarías",
			Ud: "frotaría",
			nosotros: "frotaríamos",
			vosotros: "frotaríais",
			Uds: "frotarían",
		},
		Future: {
			yo: "frotaré",
			tú: "frotarás",
			Ud: "frotará",
			nosotros: "frotaremos",
			vosotros: "frotaréis",
			Uds: "frotarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "frote",
			tú: "frotes",
			Ud: "frote",
			nosotros: "frotemos",
			vosotros: "frotéis",
			Uds: "froten",
		},
		Imperfect: {
			yo: "frotara",
			tú: "frotaras",
			Ud: "frotara",
			nosotros: "frotáramos",
			vosotros: "frotarais",
			Uds: "frotaran",
		},
		Imperfect2: {
			yo: "frotase",
			tú: "frotases",
			Ud: "frotase",
			nosotros: "frotásemos",
			vosotros: "frotaseis",
			Uds: "frotasen",
		},
		Future: {
			yo: "frotare",
			tú: "frotares",
			Ud: "frotare",
			nosotros: "frotáremos",
			vosotros: "frotareis",
			Uds: "frotaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "frota",
			Ud: "frote",
			nosotros: "frotemos",
			vosotros: "frotad",
			Uds: "froten",
		},
		Negative: {
			tú: "no frotes",
			Ud: "no frote",
			nosotros: "no frotemos",
			vosotros: "no frotéis",
			Uds: "no froten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy frotando",
			tú: "estás frotando",
			Ud: "está frotando",
			nosotros: "estamos frotando",
			vosotros: "estáis frotando",
			Uds: "están frotando",
		},
		Preterite: {
			yo: "estuve frotando",
			tú: "estuviste frotando",
			Ud: "estuvo frotando",
			nosotros: "estuvimos frotando",
			vosotros: "estuvisteis frotando",
			Uds: "estuvieron frotando",
		},
		Imperfect: {
			Uds: "estaban frotando",
			yo: "estaba frotando",
			tú: "estabas frotando",
			Ud: "estaba frotando",
			nosotros: "estábamos frotando",
			vosotros: "estabais frotando",
		},
		Conditional: {
			yo: "estaría frotando",
			tú: "estarías frotando",
			Ud: "estaría frotando",
			nosotros: "estaríamos frotando",
			vosotros: "estaríais frotando",
			Uds: "estarían frotando",
		},
		Future: {
			yo: "estaré frotando",
			tú: "estarás frotando",
			Ud: "estará frotando",
			nosotros: "estaremos frotando",
			vosotros: "estaréis frotando",
			Uds: "estarán frotando",
		},
	},
	Perfect: {
		Present: {
			yo: "he frotado",
			tú: "has frotado",
			Ud: "ha frotado",
			nosotros: "hemos frotado",
			vosotros: "habéis frotado",
			Uds: "han frotado",
		},
		Preterite: {
			yo: "hube frotado",
			tú: "hubiste frotado",
			Ud: "hubo frotado",
			nosotros: "hubimos frotado",
			vosotros: "hubisteis frotado",
			Uds: "hubieron frotado",
		},
		Past: {
			yo: "había frotado",
			tú: "habías frotado",
			Ud: "había frotado",
			nosotros: "habíamos frotado",
			vosotros: "habíais frotado",
			Uds: "habían frotado",
		},
		Conditional: {
			yo: "habría frotado",
			tú: "habrías frotado",
			Ud: "habría frotado",
			nosotros: "habríamos frotado",
			vosotros: "habríais frotado",
			Uds: "habrían frotado",
		},
		Future: {
			yo: "habré frotado",
			tú: "habrás frotado",
			Ud: "habrá frotado",
			nosotros: "habremos frotado",
			vosotros: "habréis frotado",
			Uds: "habrán frotado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya frotado",
			tú: "hayas frotado",
			Ud: "haya frotado",
			nosotros: "hayamos frotado",
			vosotros: "hayáis frotado",
			Uds: "hayan frotado",
		},
		Past: {
			yo: "hubiera frotado",
			tú: "hubieras frotado",
			Ud: "hubiera frotado",
			nosotros: "hubiéramos frotado",
			vosotros: "hubierais frotado",
			Uds: "hubieran frotado",
		},
		Future: {
			yo: "hubiere frotado",
			tú: "hubieres frotado",
			Ud: "hubiere frotado",
			nosotros: "hubiéremos frotado",
			vosotros: "hubiereis frotado",
			Uds: "hubieren frotado",
		},
	},
}
