var fumar = {
	Indicative: {
		Present: {
			yo: "fumo",
			tú: "fumas",
			Ud: "fuma",
			nosotros: "fumamos",
			vosotros: "fumáis",
			Uds: "fuman",
		},
		Preterite: {
			yo: "fumé",
			tú: "fumaste",
			Ud: "fumó",
			nosotros: "fumamos",
			vosotros: "fumasteis",
			Uds: "fumaron",
		},
		Imperfect: {
			yo: "fumaba",
			tú: "fumabas",
			Ud: "fumaba",
			nosotros: "fumábamos",
			vosotros: "fumabais",
			Uds: "fumaban",
		},
		Conditional: {
			yo: "fumaría",
			tú: "fumarías",
			Ud: "fumaría",
			nosotros: "fumaríamos",
			vosotros: "fumaríais",
			Uds: "fumarían",
		},
		Future: {
			yo: "fumaré",
			tú: "fumarás",
			Ud: "fumará",
			nosotros: "fumaremos",
			vosotros: "fumaréis",
			Uds: "fumarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "fume",
			tú: "fumes",
			Ud: "fume",
			nosotros: "fumemos",
			vosotros: "fuméis",
			Uds: "fumen",
		},
		Imperfect: {
			yo: "fumara",
			tú: "fumaras",
			Ud: "fumara",
			nosotros: "fumáramos",
			vosotros: "fumarais",
			Uds: "fumaran",
		},
		Imperfect2: {
			yo: "fumase",
			tú: "fumases",
			Ud: "fumase",
			nosotros: "fumásemos",
			vosotros: "fumaseis",
			Uds: "fumasen",
		},
		Future: {
			yo: "fumare",
			tú: "fumares",
			Ud: "fumare",
			nosotros: "fumáremos",
			vosotros: "fumareis",
			Uds: "fumaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "fuma",
			Ud: "fume",
			nosotros: "fumemos",
			vosotros: "fumad",
			Uds: "fumen",
		},
		Negative: {
			tú: "no fumes",
			Ud: "no fume",
			nosotros: "no fumemos",
			vosotros: "no fuméis",
			Uds: "no fumen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy fumando",
			tú: "estás fumando",
			Ud: "está fumando",
			nosotros: "estamos fumando",
			vosotros: "estáis fumando",
			Uds: "están fumando",
		},
		Preterite: {
			yo: "estuve fumando",
			tú: "estuviste fumando",
			Ud: "estuvo fumando",
			nosotros: "estuvimos fumando",
			vosotros: "estuvisteis fumando",
			Uds: "estuvieron fumando",
		},
		Imperfect: {
			Uds: "estaban fumando",
			yo: "estaba fumando",
			tú: "estabas fumando",
			Ud: "estaba fumando",
			nosotros: "estábamos fumando",
			vosotros: "estabais fumando",
		},
		Conditional: {
			yo: "estaría fumando",
			tú: "estarías fumando",
			Ud: "estaría fumando",
			nosotros: "estaríamos fumando",
			vosotros: "estaríais fumando",
			Uds: "estarían fumando",
		},
		Future: {
			yo: "estaré fumando",
			tú: "estarás fumando",
			Ud: "estará fumando",
			nosotros: "estaremos fumando",
			vosotros: "estaréis fumando",
			Uds: "estarán fumando",
		},
	},
	Perfect: {
		Present: {
			yo: "he fumado",
			tú: "has fumado",
			Ud: "ha fumado",
			nosotros: "hemos fumado",
			vosotros: "habéis fumado",
			Uds: "han fumado",
		},
		Preterite: {
			yo: "hube fumado",
			tú: "hubiste fumado",
			Ud: "hubo fumado",
			nosotros: "hubimos fumado",
			vosotros: "hubisteis fumado",
			Uds: "hubieron fumado",
		},
		Past: {
			yo: "había fumado",
			tú: "habías fumado",
			Ud: "había fumado",
			nosotros: "habíamos fumado",
			vosotros: "habíais fumado",
			Uds: "habían fumado",
		},
		Conditional: {
			yo: "habría fumado",
			tú: "habrías fumado",
			Ud: "habría fumado",
			nosotros: "habríamos fumado",
			vosotros: "habríais fumado",
			Uds: "habrían fumado",
		},
		Future: {
			yo: "habré fumado",
			tú: "habrás fumado",
			Ud: "habrá fumado",
			nosotros: "habremos fumado",
			vosotros: "habréis fumado",
			Uds: "habrán fumado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya fumado",
			tú: "hayas fumado",
			Ud: "haya fumado",
			nosotros: "hayamos fumado",
			vosotros: "hayáis fumado",
			Uds: "hayan fumado",
		},
		Past: {
			yo: "hubiera fumado",
			tú: "hubieras fumado",
			Ud: "hubiera fumado",
			nosotros: "hubiéramos fumado",
			vosotros: "hubierais fumado",
			Uds: "hubieran fumado",
		},
		Future: {
			yo: "hubiere fumado",
			tú: "hubieres fumado",
			Ud: "hubiere fumado",
			nosotros: "hubiéremos fumado",
			vosotros: "hubiereis fumado",
			Uds: "hubieren fumado",
		},
	},
}
