var gasear = {
	Indicative: {
		Present: {
			yo: "gaseo",
			tú: "gaseas",
			Ud: "gasea",
			nosotros: "gaseamos",
			vosotros: "gaseáis",
			Uds: "gasean",
		},
		Preterite: {
			yo: "gaseé",
			tú: "gaseaste",
			Ud: "gaseó",
			nosotros: "gaseamos",
			vosotros: "gaseasteis",
			Uds: "gasearon",
		},
		Imperfect: {
			yo: "gaseaba",
			tú: "gaseabas",
			Ud: "gaseaba",
			nosotros: "gaseábamos",
			vosotros: "gaseabais",
			Uds: "gaseaban",
		},
		Conditional: {
			yo: "gasearía",
			tú: "gasearías",
			Ud: "gasearía",
			nosotros: "gasearíamos",
			vosotros: "gasearíais",
			Uds: "gasearían",
		},
		Future: {
			yo: "gasearé",
			tú: "gasearás",
			Ud: "gaseará",
			nosotros: "gasearemos",
			vosotros: "gasearéis",
			Uds: "gasearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "gasee",
			tú: "gasees",
			Ud: "gasee",
			nosotros: "gaseemos",
			vosotros: "gaseéis",
			Uds: "gaseen",
		},
		Imperfect: {
			yo: "gaseara",
			tú: "gasearas",
			Ud: "gaseara",
			nosotros: "gaseáramos",
			vosotros: "gasearais",
			Uds: "gasearan",
		},
		Imperfect2: {
			yo: "gasease",
			tú: "gaseases",
			Ud: "gasease",
			nosotros: "gaseásemos",
			vosotros: "gaseaseis",
			Uds: "gaseasen",
		},
		Future: {
			yo: "gaseare",
			tú: "gaseares",
			Ud: "gaseare",
			nosotros: "gaseáremos",
			vosotros: "gaseareis",
			Uds: "gasearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "gasea",
			Ud: "gasee",
			nosotros: "gaseemos",
			vosotros: "gasead",
			Uds: "gaseen",
		},
		Negative: {
			tú: "no gasees",
			Ud: "no gasee",
			nosotros: "no gaseemos",
			vosotros: "no gaseéis",
			Uds: "no gaseen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy gaseando",
			tú: "estás gaseando",
			Ud: "está gaseando",
			nosotros: "estamos gaseando",
			vosotros: "estáis gaseando",
			Uds: "están gaseando",
		},
		Preterite: {
			yo: "estuve gaseando",
			tú: "estuviste gaseando",
			Ud: "estuvo gaseando",
			nosotros: "estuvimos gaseando",
			vosotros: "estuvisteis gaseando",
			Uds: "estuvieron gaseando",
		},
		Imperfect: {
			Uds: "estaban gaseando",
			yo: "estaba gaseando",
			tú: "estabas gaseando",
			Ud: "estaba gaseando",
			nosotros: "estábamos gaseando",
			vosotros: "estabais gaseando",
		},
		Conditional: {
			yo: "estaría gaseando",
			tú: "estarías gaseando",
			Ud: "estaría gaseando",
			nosotros: "estaríamos gaseando",
			vosotros: "estaríais gaseando",
			Uds: "estarían gaseando",
		},
		Future: {
			yo: "estaré gaseando",
			tú: "estarás gaseando",
			Ud: "estará gaseando",
			nosotros: "estaremos gaseando",
			vosotros: "estaréis gaseando",
			Uds: "estarán gaseando",
		},
	},
	Perfect: {
		Present: {
			yo: "he gaseado",
			tú: "has gaseado",
			Ud: "ha gaseado",
			nosotros: "hemos gaseado",
			vosotros: "habéis gaseado",
			Uds: "han gaseado",
		},
		Preterite: {
			yo: "hube gaseado",
			tú: "hubiste gaseado",
			Ud: "hubo gaseado",
			nosotros: "hubimos gaseado",
			vosotros: "hubisteis gaseado",
			Uds: "hubieron gaseado",
		},
		Past: {
			yo: "había gaseado",
			tú: "habías gaseado",
			Ud: "había gaseado",
			nosotros: "habíamos gaseado",
			vosotros: "habíais gaseado",
			Uds: "habían gaseado",
		},
		Conditional: {
			yo: "habría gaseado",
			tú: "habrías gaseado",
			Ud: "habría gaseado",
			nosotros: "habríamos gaseado",
			vosotros: "habríais gaseado",
			Uds: "habrían gaseado",
		},
		Future: {
			yo: "habré gaseado",
			tú: "habrás gaseado",
			Ud: "habrá gaseado",
			nosotros: "habremos gaseado",
			vosotros: "habréis gaseado",
			Uds: "habrán gaseado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya gaseado",
			tú: "hayas gaseado",
			Ud: "haya gaseado",
			nosotros: "hayamos gaseado",
			vosotros: "hayáis gaseado",
			Uds: "hayan gaseado",
		},
		Past: {
			yo: "hubiera gaseado",
			tú: "hubieras gaseado",
			Ud: "hubiera gaseado",
			nosotros: "hubiéramos gaseado",
			vosotros: "hubierais gaseado",
			Uds: "hubieran gaseado",
		},
		Future: {
			yo: "hubiere gaseado",
			tú: "hubieres gaseado",
			Ud: "hubiere gaseado",
			nosotros: "hubiéremos gaseado",
			vosotros: "hubiereis gaseado",
			Uds: "hubieren gaseado",
		},
	},
}
