var gestionar = {
	Indicative: {
		Present: {
			yo: "gestiono",
			tú: "gestionas",
			Ud: "gestiona",
			nosotros: "gestionamos",
			vosotros: "gestionáis",
			Uds: "gestionan",
		},
		Preterite: {
			yo: "gestioné",
			tú: "gestionaste",
			Ud: "gestionó",
			nosotros: "gestionamos",
			vosotros: "gestionasteis",
			Uds: "gestionaron",
		},
		Imperfect: {
			yo: "gestionaba",
			tú: "gestionabas",
			Ud: "gestionaba",
			nosotros: "gestionábamos",
			vosotros: "gestionabais",
			Uds: "gestionaban",
		},
		Conditional: {
			yo: "gestionaría",
			tú: "gestionarías",
			Ud: "gestionaría",
			nosotros: "gestionaríamos",
			vosotros: "gestionaríais",
			Uds: "gestionarían",
		},
		Future: {
			yo: "gestionaré",
			tú: "gestionarás",
			Ud: "gestionará",
			nosotros: "gestionaremos",
			vosotros: "gestionaréis",
			Uds: "gestionarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "gestione",
			tú: "gestiones",
			Ud: "gestione",
			nosotros: "gestionemos",
			vosotros: "gestionéis",
			Uds: "gestionen",
		},
		Imperfect: {
			yo: "gestionara",
			tú: "gestionaras",
			Ud: "gestionara",
			nosotros: "gestionáramos",
			vosotros: "gestionarais",
			Uds: "gestionaran",
		},
		Imperfect2: {
			yo: "gestionase",
			tú: "gestionases",
			Ud: "gestionase",
			nosotros: "gestionásemos",
			vosotros: "gestionaseis",
			Uds: "gestionasen",
		},
		Future: {
			yo: "gestionare",
			tú: "gestionares",
			Ud: "gestionare",
			nosotros: "gestionáremos",
			vosotros: "gestionareis",
			Uds: "gestionaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "gestiona",
			Ud: "gestione",
			nosotros: "gestionemos",
			vosotros: "gestionad",
			Uds: "gestionen",
		},
		Negative: {
			tú: "no gestiones",
			Ud: "no gestione",
			nosotros: "no gestionemos",
			vosotros: "no gestionéis",
			Uds: "no gestionen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy gestionando",
			tú: "estás gestionando",
			Ud: "está gestionando",
			nosotros: "estamos gestionando",
			vosotros: "estáis gestionando",
			Uds: "están gestionando",
		},
		Preterite: {
			yo: "estuve gestionando",
			tú: "estuviste gestionando",
			Ud: "estuvo gestionando",
			nosotros: "estuvimos gestionando",
			vosotros: "estuvisteis gestionando",
			Uds: "estuvieron gestionando",
		},
		Imperfect: {
			Uds: "estaban gestionando",
			yo: "estaba gestionando",
			tú: "estabas gestionando",
			Ud: "estaba gestionando",
			nosotros: "estábamos gestionando",
			vosotros: "estabais gestionando",
		},
		Conditional: {
			yo: "estaría gestionando",
			tú: "estarías gestionando",
			Ud: "estaría gestionando",
			nosotros: "estaríamos gestionando",
			vosotros: "estaríais gestionando",
			Uds: "estarían gestionando",
		},
		Future: {
			yo: "estaré gestionando",
			tú: "estarás gestionando",
			Ud: "estará gestionando",
			nosotros: "estaremos gestionando",
			vosotros: "estaréis gestionando",
			Uds: "estarán gestionando",
		},
	},
	Perfect: {
		Present: {
			yo: "he gestionado",
			tú: "has gestionado",
			Ud: "ha gestionado",
			nosotros: "hemos gestionado",
			vosotros: "habéis gestionado",
			Uds: "han gestionado",
		},
		Preterite: {
			yo: "hube gestionado",
			tú: "hubiste gestionado",
			Ud: "hubo gestionado",
			nosotros: "hubimos gestionado",
			vosotros: "hubisteis gestionado",
			Uds: "hubieron gestionado",
		},
		Past: {
			yo: "había gestionado",
			tú: "habías gestionado",
			Ud: "había gestionado",
			nosotros: "habíamos gestionado",
			vosotros: "habíais gestionado",
			Uds: "habían gestionado",
		},
		Conditional: {
			yo: "habría gestionado",
			tú: "habrías gestionado",
			Ud: "habría gestionado",
			nosotros: "habríamos gestionado",
			vosotros: "habríais gestionado",
			Uds: "habrían gestionado",
		},
		Future: {
			yo: "habré gestionado",
			tú: "habrás gestionado",
			Ud: "habrá gestionado",
			nosotros: "habremos gestionado",
			vosotros: "habréis gestionado",
			Uds: "habrán gestionado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya gestionado",
			tú: "hayas gestionado",
			Ud: "haya gestionado",
			nosotros: "hayamos gestionado",
			vosotros: "hayáis gestionado",
			Uds: "hayan gestionado",
		},
		Past: {
			yo: "hubiera gestionado",
			tú: "hubieras gestionado",
			Ud: "hubiera gestionado",
			nosotros: "hubiéramos gestionado",
			vosotros: "hubierais gestionado",
			Uds: "hubieran gestionado",
		},
		Future: {
			yo: "hubiere gestionado",
			tú: "hubieres gestionado",
			Ud: "hubiere gestionado",
			nosotros: "hubiéremos gestionado",
			vosotros: "hubiereis gestionado",
			Uds: "hubieren gestionado",
		},
	},
}
