var glorificar = {
	Indicative: {
		Present: {
			yo: "glorifico",
			tú: "glorificas",
			Ud: "glorifica",
			nosotros: "glorificamos",
			vosotros: "glorificáis",
			Uds: "glorifican",
		},
		Preterite: {
			yo: "glorifiqué",
			tú: "glorificaste",
			Ud: "glorificó",
			nosotros: "glorificamos",
			vosotros: "glorificasteis",
			Uds: "glorificaron",
		},
		Imperfect: {
			yo: "glorificaba",
			tú: "glorificabas",
			Ud: "glorificaba",
			nosotros: "glorificábamos",
			vosotros: "glorificabais",
			Uds: "glorificaban",
		},
		Conditional: {
			yo: "glorificaría",
			tú: "glorificarías",
			Ud: "glorificaría",
			nosotros: "glorificaríamos",
			vosotros: "glorificaríais",
			Uds: "glorificarían",
		},
		Future: {
			yo: "glorificaré",
			tú: "glorificarás",
			Ud: "glorificará",
			nosotros: "glorificaremos",
			vosotros: "glorificaréis",
			Uds: "glorificarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "glorifique",
			tú: "glorifiques",
			Ud: "glorifique",
			nosotros: "glorifiquemos",
			vosotros: "glorifiquéis",
			Uds: "glorifiquen",
		},
		Imperfect: {
			yo: "glorificara",
			tú: "glorificaras",
			Ud: "glorificara",
			nosotros: "glorificáramos",
			vosotros: "glorificarais",
			Uds: "glorificaran",
		},
		Imperfect2: {
			yo: "glorificase",
			tú: "glorificases",
			Ud: "glorificase",
			nosotros: "glorificásemos",
			vosotros: "glorificaseis",
			Uds: "glorificasen",
		},
		Future: {
			yo: "glorificare",
			tú: "glorificares",
			Ud: "glorificare",
			nosotros: "glorificáremos",
			vosotros: "glorificareis",
			Uds: "glorificaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "glorifica",
			Ud: "glorifique",
			nosotros: "glorifiquemos",
			vosotros: "glorificad",
			Uds: "glorifiquen",
		},
		Negative: {
			tú: "no glorifiques",
			Ud: "no glorifique",
			nosotros: "no glorifiquemos",
			vosotros: "no glorifiquéis",
			Uds: "no glorifiquen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy glorificando",
			tú: "estás glorificando",
			Ud: "está glorificando",
			nosotros: "estamos glorificando",
			vosotros: "estáis glorificando",
			Uds: "están glorificando",
		},
		Preterite: {
			yo: "estuve glorificando",
			tú: "estuviste glorificando",
			Ud: "estuvo glorificando",
			nosotros: "estuvimos glorificando",
			vosotros: "estuvisteis glorificando",
			Uds: "estuvieron glorificando",
		},
		Imperfect: {
			Uds: "estaban glorificando",
			yo: "estaba glorificando",
			tú: "estabas glorificando",
			Ud: "estaba glorificando",
			nosotros: "estábamos glorificando",
			vosotros: "estabais glorificando",
		},
		Conditional: {
			yo: "estaría glorificando",
			tú: "estarías glorificando",
			Ud: "estaría glorificando",
			nosotros: "estaríamos glorificando",
			vosotros: "estaríais glorificando",
			Uds: "estarían glorificando",
		},
		Future: {
			yo: "estaré glorificando",
			tú: "estarás glorificando",
			Ud: "estará glorificando",
			nosotros: "estaremos glorificando",
			vosotros: "estaréis glorificando",
			Uds: "estarán glorificando",
		},
	},
	Perfect: {
		Present: {
			yo: "he glorificado",
			tú: "has glorificado",
			Ud: "ha glorificado",
			nosotros: "hemos glorificado",
			vosotros: "habéis glorificado",
			Uds: "han glorificado",
		},
		Preterite: {
			yo: "hube glorificado",
			tú: "hubiste glorificado",
			Ud: "hubo glorificado",
			nosotros: "hubimos glorificado",
			vosotros: "hubisteis glorificado",
			Uds: "hubieron glorificado",
		},
		Past: {
			yo: "había glorificado",
			tú: "habías glorificado",
			Ud: "había glorificado",
			nosotros: "habíamos glorificado",
			vosotros: "habíais glorificado",
			Uds: "habían glorificado",
		},
		Conditional: {
			yo: "habría glorificado",
			tú: "habrías glorificado",
			Ud: "habría glorificado",
			nosotros: "habríamos glorificado",
			vosotros: "habríais glorificado",
			Uds: "habrían glorificado",
		},
		Future: {
			yo: "habré glorificado",
			tú: "habrás glorificado",
			Ud: "habrá glorificado",
			nosotros: "habremos glorificado",
			vosotros: "habréis glorificado",
			Uds: "habrán glorificado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya glorificado",
			tú: "hayas glorificado",
			Ud: "haya glorificado",
			nosotros: "hayamos glorificado",
			vosotros: "hayáis glorificado",
			Uds: "hayan glorificado",
		},
		Past: {
			yo: "hubiera glorificado",
			tú: "hubieras glorificado",
			Ud: "hubiera glorificado",
			nosotros: "hubiéramos glorificado",
			vosotros: "hubierais glorificado",
			Uds: "hubieran glorificado",
		},
		Future: {
			yo: "hubiere glorificado",
			tú: "hubieres glorificado",
			Ud: "hubiere glorificado",
			nosotros: "hubiéremos glorificado",
			vosotros: "hubiereis glorificado",
			Uds: "hubieren glorificado",
		},
	},
}
