var gorronear = {
	Indicative: {
		Present: {
			yo: "gorroneo",
			tú: "gorroneas",
			Ud: "gorronea",
			nosotros: "gorroneamos",
			vosotros: "gorroneáis",
			Uds: "gorronean",
		},
		Preterite: {
			yo: "gorroneé",
			tú: "gorroneaste",
			Ud: "gorroneó",
			nosotros: "gorroneamos",
			vosotros: "gorroneasteis",
			Uds: "gorronearon",
		},
		Imperfect: {
			yo: "gorroneaba",
			tú: "gorroneabas",
			Ud: "gorroneaba",
			nosotros: "gorroneábamos",
			vosotros: "gorroneabais",
			Uds: "gorroneaban",
		},
		Conditional: {
			yo: "gorronearía",
			tú: "gorronearías",
			Ud: "gorronearía",
			nosotros: "gorronearíamos",
			vosotros: "gorronearíais",
			Uds: "gorronearían",
		},
		Future: {
			yo: "gorronearé",
			tú: "gorronearás",
			Ud: "gorroneará",
			nosotros: "gorronearemos",
			vosotros: "gorronearéis",
			Uds: "gorronearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "gorronee",
			tú: "gorronees",
			Ud: "gorronee",
			nosotros: "gorroneemos",
			vosotros: "gorroneéis",
			Uds: "gorroneen",
		},
		Imperfect: {
			yo: "gorroneara",
			tú: "gorronearas",
			Ud: "gorroneara",
			nosotros: "gorroneáramos",
			vosotros: "gorronearais",
			Uds: "gorronearan",
		},
		Imperfect2: {
			yo: "gorronease",
			tú: "gorroneases",
			Ud: "gorronease",
			nosotros: "gorroneásemos",
			vosotros: "gorroneaseis",
			Uds: "gorroneasen",
		},
		Future: {
			yo: "gorroneare",
			tú: "gorroneares",
			Ud: "gorroneare",
			nosotros: "gorroneáremos",
			vosotros: "gorroneareis",
			Uds: "gorronearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "gorronea",
			Ud: "gorronee",
			nosotros: "gorroneemos",
			vosotros: "gorronead",
			Uds: "gorroneen",
		},
		Negative: {
			tú: "no gorronees",
			Ud: "no gorronee",
			nosotros: "no gorroneemos",
			vosotros: "no gorroneéis",
			Uds: "no gorroneen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy gorroneando",
			tú: "estás gorroneando",
			Ud: "está gorroneando",
			nosotros: "estamos gorroneando",
			vosotros: "estáis gorroneando",
			Uds: "están gorroneando",
		},
		Preterite: {
			yo: "estuve gorroneando",
			tú: "estuviste gorroneando",
			Ud: "estuvo gorroneando",
			nosotros: "estuvimos gorroneando",
			vosotros: "estuvisteis gorroneando",
			Uds: "estuvieron gorroneando",
		},
		Imperfect: {
			Uds: "estaban gorroneando",
			yo: "estaba gorroneando",
			tú: "estabas gorroneando",
			Ud: "estaba gorroneando",
			nosotros: "estábamos gorroneando",
			vosotros: "estabais gorroneando",
		},
		Conditional: {
			yo: "estaría gorroneando",
			tú: "estarías gorroneando",
			Ud: "estaría gorroneando",
			nosotros: "estaríamos gorroneando",
			vosotros: "estaríais gorroneando",
			Uds: "estarían gorroneando",
		},
		Future: {
			yo: "estaré gorroneando",
			tú: "estarás gorroneando",
			Ud: "estará gorroneando",
			nosotros: "estaremos gorroneando",
			vosotros: "estaréis gorroneando",
			Uds: "estarán gorroneando",
		},
	},
	Perfect: {
		Present: {
			yo: "he gorroneado",
			tú: "has gorroneado",
			Ud: "ha gorroneado",
			nosotros: "hemos gorroneado",
			vosotros: "habéis gorroneado",
			Uds: "han gorroneado",
		},
		Preterite: {
			yo: "hube gorroneado",
			tú: "hubiste gorroneado",
			Ud: "hubo gorroneado",
			nosotros: "hubimos gorroneado",
			vosotros: "hubisteis gorroneado",
			Uds: "hubieron gorroneado",
		},
		Past: {
			yo: "había gorroneado",
			tú: "habías gorroneado",
			Ud: "había gorroneado",
			nosotros: "habíamos gorroneado",
			vosotros: "habíais gorroneado",
			Uds: "habían gorroneado",
		},
		Conditional: {
			yo: "habría gorroneado",
			tú: "habrías gorroneado",
			Ud: "habría gorroneado",
			nosotros: "habríamos gorroneado",
			vosotros: "habríais gorroneado",
			Uds: "habrían gorroneado",
		},
		Future: {
			yo: "habré gorroneado",
			tú: "habrás gorroneado",
			Ud: "habrá gorroneado",
			nosotros: "habremos gorroneado",
			vosotros: "habréis gorroneado",
			Uds: "habrán gorroneado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya gorroneado",
			tú: "hayas gorroneado",
			Ud: "haya gorroneado",
			nosotros: "hayamos gorroneado",
			vosotros: "hayáis gorroneado",
			Uds: "hayan gorroneado",
		},
		Past: {
			yo: "hubiera gorroneado",
			tú: "hubieras gorroneado",
			Ud: "hubiera gorroneado",
			nosotros: "hubiéramos gorroneado",
			vosotros: "hubierais gorroneado",
			Uds: "hubieran gorroneado",
		},
		Future: {
			yo: "hubiere gorroneado",
			tú: "hubieres gorroneado",
			Ud: "hubiere gorroneado",
			nosotros: "hubiéremos gorroneado",
			vosotros: "hubiereis gorroneado",
			Uds: "hubieren gorroneado",
		},
	},
}
