var grabar = {
	Indicative: {
		Present: {
			yo: "grabo",
			tú: "grabas",
			Ud: "graba",
			nosotros: "grabamos",
			vosotros: "grabáis",
			Uds: "graban",
		},
		Preterite: {
			yo: "grabé",
			tú: "grabaste",
			Ud: "grabó",
			nosotros: "grabamos",
			vosotros: "grabasteis",
			Uds: "grabaron",
		},
		Imperfect: {
			yo: "grababa",
			tú: "grababas",
			Ud: "grababa",
			nosotros: "grabábamos",
			vosotros: "grababais",
			Uds: "grababan",
		},
		Conditional: {
			yo: "grabaría",
			tú: "grabarías",
			Ud: "grabaría",
			nosotros: "grabaríamos",
			vosotros: "grabaríais",
			Uds: "grabarían",
		},
		Future: {
			yo: "grabaré",
			tú: "grabarás",
			Ud: "grabará",
			nosotros: "grabaremos",
			vosotros: "grabaréis",
			Uds: "grabarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "grabe",
			tú: "grabes",
			Ud: "grabe",
			nosotros: "grabemos",
			vosotros: "grabéis",
			Uds: "graben",
		},
		Imperfect: {
			yo: "grabara",
			tú: "grabaras",
			Ud: "grabara",
			nosotros: "grabáramos",
			vosotros: "grabarais",
			Uds: "grabaran",
		},
		Imperfect2: {
			yo: "grabase",
			tú: "grabases",
			Ud: "grabase",
			nosotros: "grabásemos",
			vosotros: "grabaseis",
			Uds: "grabasen",
		},
		Future: {
			yo: "grabare",
			tú: "grabares",
			Ud: "grabare",
			nosotros: "grabáremos",
			vosotros: "grabareis",
			Uds: "grabaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "graba",
			Ud: "grabe",
			nosotros: "grabemos",
			vosotros: "grabad",
			Uds: "graben",
		},
		Negative: {
			tú: "no grabes",
			Ud: "no grabe",
			nosotros: "no grabemos",
			vosotros: "no grabéis",
			Uds: "no graben",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy grabando",
			tú: "estás grabando",
			Ud: "está grabando",
			nosotros: "estamos grabando",
			vosotros: "estáis grabando",
			Uds: "están grabando",
		},
		Preterite: {
			yo: "estuve grabando",
			tú: "estuviste grabando",
			Ud: "estuvo grabando",
			nosotros: "estuvimos grabando",
			vosotros: "estuvisteis grabando",
			Uds: "estuvieron grabando",
		},
		Imperfect: {
			Uds: "estaban grabando",
			yo: "estaba grabando",
			tú: "estabas grabando",
			Ud: "estaba grabando",
			nosotros: "estábamos grabando",
			vosotros: "estabais grabando",
		},
		Conditional: {
			yo: "estaría grabando",
			tú: "estarías grabando",
			Ud: "estaría grabando",
			nosotros: "estaríamos grabando",
			vosotros: "estaríais grabando",
			Uds: "estarían grabando",
		},
		Future: {
			yo: "estaré grabando",
			tú: "estarás grabando",
			Ud: "estará grabando",
			nosotros: "estaremos grabando",
			vosotros: "estaréis grabando",
			Uds: "estarán grabando",
		},
	},
	Perfect: {
		Present: {
			yo: "he grabado",
			tú: "has grabado",
			Ud: "ha grabado",
			nosotros: "hemos grabado",
			vosotros: "habéis grabado",
			Uds: "han grabado",
		},
		Preterite: {
			yo: "hube grabado",
			tú: "hubiste grabado",
			Ud: "hubo grabado",
			nosotros: "hubimos grabado",
			vosotros: "hubisteis grabado",
			Uds: "hubieron grabado",
		},
		Past: {
			yo: "había grabado",
			tú: "habías grabado",
			Ud: "había grabado",
			nosotros: "habíamos grabado",
			vosotros: "habíais grabado",
			Uds: "habían grabado",
		},
		Conditional: {
			yo: "habría grabado",
			tú: "habrías grabado",
			Ud: "habría grabado",
			nosotros: "habríamos grabado",
			vosotros: "habríais grabado",
			Uds: "habrían grabado",
		},
		Future: {
			yo: "habré grabado",
			tú: "habrás grabado",
			Ud: "habrá grabado",
			nosotros: "habremos grabado",
			vosotros: "habréis grabado",
			Uds: "habrán grabado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya grabado",
			tú: "hayas grabado",
			Ud: "haya grabado",
			nosotros: "hayamos grabado",
			vosotros: "hayáis grabado",
			Uds: "hayan grabado",
		},
		Past: {
			yo: "hubiera grabado",
			tú: "hubieras grabado",
			Ud: "hubiera grabado",
			nosotros: "hubiéramos grabado",
			vosotros: "hubierais grabado",
			Uds: "hubieran grabado",
		},
		Future: {
			yo: "hubiere grabado",
			tú: "hubieres grabado",
			Ud: "hubiere grabado",
			nosotros: "hubiéremos grabado",
			vosotros: "hubiereis grabado",
			Uds: "hubieren grabado",
		},
	},
}
