var graduar = {
	Indicative: {
		Present: {
			yo: "gradúo",
			tú: "gradúas",
			Ud: "gradúa",
			nosotros: "graduamos",
			vosotros: "graduáis",
			Uds: "gradúan",
		},
		Preterite: {
			yo: "gradué",
			tú: "graduaste",
			Ud: "graduó",
			nosotros: "graduamos",
			vosotros: "graduasteis",
			Uds: "graduaron",
		},
		Imperfect: {
			yo: "graduaba",
			tú: "graduabas",
			Ud: "graduaba",
			nosotros: "graduábamos",
			vosotros: "graduabais",
			Uds: "graduaban",
		},
		Conditional: {
			yo: "graduaría",
			tú: "graduarías",
			Ud: "graduaría",
			nosotros: "graduaríamos",
			vosotros: "graduaríais",
			Uds: "graduarían",
		},
		Future: {
			yo: "graduaré",
			tú: "graduarás",
			Ud: "graduará",
			nosotros: "graduaremos",
			vosotros: "graduaréis",
			Uds: "graduarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "gradúe",
			tú: "gradúes",
			Ud: "gradúe",
			nosotros: "graduemos",
			vosotros: "graduéis",
			Uds: "gradúen",
		},
		Imperfect: {
			yo: "graduara",
			tú: "graduaras",
			Ud: "graduara",
			nosotros: "graduáramos",
			vosotros: "graduarais",
			Uds: "graduaran",
		},
		Imperfect2: {
			yo: "graduase",
			tú: "graduases",
			Ud: "graduase",
			nosotros: "graduásemos",
			vosotros: "graduaseis",
			Uds: "graduasen",
		},
		Future: {
			yo: "graduare",
			tú: "graduares",
			Ud: "graduare",
			nosotros: "graduáremos",
			vosotros: "graduareis",
			Uds: "graduaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "gradúa",
			Ud: "gradúe",
			nosotros: "graduemos",
			vosotros: "graduad",
			Uds: "gradúen",
		},
		Negative: {
			tú: "no gradúes",
			Ud: "no gradúe",
			nosotros: "no graduemos",
			vosotros: "no graduéis",
			Uds: "no gradúen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy graduando",
			tú: "estás graduando",
			Ud: "está graduando",
			nosotros: "estamos graduando",
			vosotros: "estáis graduando",
			Uds: "están graduando",
		},
		Preterite: {
			yo: "estuve graduando",
			tú: "estuviste graduando",
			Ud: "estuvo graduando",
			nosotros: "estuvimos graduando",
			vosotros: "estuvisteis graduando",
			Uds: "estuvieron graduando",
		},
		Imperfect: {
			Uds: "estaban graduando",
			yo: "estaba graduando",
			tú: "estabas graduando",
			Ud: "estaba graduando",
			nosotros: "estábamos graduando",
			vosotros: "estabais graduando",
		},
		Conditional: {
			yo: "estaría graduando",
			tú: "estarías graduando",
			Ud: "estaría graduando",
			nosotros: "estaríamos graduando",
			vosotros: "estaríais graduando",
			Uds: "estarían graduando",
		},
		Future: {
			yo: "estaré graduando",
			tú: "estarás graduando",
			Ud: "estará graduando",
			nosotros: "estaremos graduando",
			vosotros: "estaréis graduando",
			Uds: "estarán graduando",
		},
	},
	Perfect: {
		Present: {
			yo: "he graduado",
			tú: "has graduado",
			Ud: "ha graduado",
			nosotros: "hemos graduado",
			vosotros: "habéis graduado",
			Uds: "han graduado",
		},
		Preterite: {
			yo: "hube graduado",
			tú: "hubiste graduado",
			Ud: "hubo graduado",
			nosotros: "hubimos graduado",
			vosotros: "hubisteis graduado",
			Uds: "hubieron graduado",
		},
		Past: {
			yo: "había graduado",
			tú: "habías graduado",
			Ud: "había graduado",
			nosotros: "habíamos graduado",
			vosotros: "habíais graduado",
			Uds: "habían graduado",
		},
		Conditional: {
			yo: "habría graduado",
			tú: "habrías graduado",
			Ud: "habría graduado",
			nosotros: "habríamos graduado",
			vosotros: "habríais graduado",
			Uds: "habrían graduado",
		},
		Future: {
			yo: "habré graduado",
			tú: "habrás graduado",
			Ud: "habrá graduado",
			nosotros: "habremos graduado",
			vosotros: "habréis graduado",
			Uds: "habrán graduado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya graduado",
			tú: "hayas graduado",
			Ud: "haya graduado",
			nosotros: "hayamos graduado",
			vosotros: "hayáis graduado",
			Uds: "hayan graduado",
		},
		Past: {
			yo: "hubiera graduado",
			tú: "hubieras graduado",
			Ud: "hubiera graduado",
			nosotros: "hubiéramos graduado",
			vosotros: "hubierais graduado",
			Uds: "hubieran graduado",
		},
		Future: {
			yo: "hubiere graduado",
			tú: "hubieres graduado",
			Ud: "hubiere graduado",
			nosotros: "hubiéremos graduado",
			vosotros: "hubiereis graduado",
			Uds: "hubieren graduado",
		},
	},
}
