var graznar = {
	Indicative: {
		Present: {
			yo: "grazno",
			tú: "graznas",
			Ud: "grazna",
			nosotros: "graznamos",
			vosotros: "graznáis",
			Uds: "graznan",
		},
		Preterite: {
			yo: "grazné",
			tú: "graznaste",
			Ud: "graznó",
			nosotros: "graznamos",
			vosotros: "graznasteis",
			Uds: "graznaron",
		},
		Imperfect: {
			yo: "graznaba",
			tú: "graznabas",
			Ud: "graznaba",
			nosotros: "graznábamos",
			vosotros: "graznabais",
			Uds: "graznaban",
		},
		Conditional: {
			yo: "graznaría",
			tú: "graznarías",
			Ud: "graznaría",
			nosotros: "graznaríamos",
			vosotros: "graznaríais",
			Uds: "graznarían",
		},
		Future: {
			yo: "graznaré",
			tú: "graznarás",
			Ud: "graznará",
			nosotros: "graznaremos",
			vosotros: "graznaréis",
			Uds: "graznarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "grazne",
			tú: "graznes",
			Ud: "grazne",
			nosotros: "graznemos",
			vosotros: "graznéis",
			Uds: "graznen",
		},
		Imperfect: {
			yo: "graznara",
			tú: "graznaras",
			Ud: "graznara",
			nosotros: "graznáramos",
			vosotros: "graznarais",
			Uds: "graznaran",
		},
		Imperfect2: {
			yo: "graznase",
			tú: "graznases",
			Ud: "graznase",
			nosotros: "graznásemos",
			vosotros: "graznaseis",
			Uds: "graznasen",
		},
		Future: {
			yo: "graznare",
			tú: "graznares",
			Ud: "graznare",
			nosotros: "graznáremos",
			vosotros: "graznareis",
			Uds: "graznaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "grazna",
			Ud: "grazne",
			nosotros: "graznemos",
			vosotros: "graznad",
			Uds: "graznen",
		},
		Negative: {
			tú: "no graznes",
			Ud: "no grazne",
			nosotros: "no graznemos",
			vosotros: "no graznéis",
			Uds: "no graznen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy graznando",
			tú: "estás graznando",
			Ud: "está graznando",
			nosotros: "estamos graznando",
			vosotros: "estáis graznando",
			Uds: "están graznando",
		},
		Preterite: {
			yo: "estuve graznando",
			tú: "estuviste graznando",
			Ud: "estuvo graznando",
			nosotros: "estuvimos graznando",
			vosotros: "estuvisteis graznando",
			Uds: "estuvieron graznando",
		},
		Imperfect: {
			Uds: "estaban graznando",
			yo: "estaba graznando",
			tú: "estabas graznando",
			Ud: "estaba graznando",
			nosotros: "estábamos graznando",
			vosotros: "estabais graznando",
		},
		Conditional: {
			yo: "estaría graznando",
			tú: "estarías graznando",
			Ud: "estaría graznando",
			nosotros: "estaríamos graznando",
			vosotros: "estaríais graznando",
			Uds: "estarían graznando",
		},
		Future: {
			yo: "estaré graznando",
			tú: "estarás graznando",
			Ud: "estará graznando",
			nosotros: "estaremos graznando",
			vosotros: "estaréis graznando",
			Uds: "estarán graznando",
		},
	},
	Perfect: {
		Present: {
			yo: "he graznado",
			tú: "has graznado",
			Ud: "ha graznado",
			nosotros: "hemos graznado",
			vosotros: "habéis graznado",
			Uds: "han graznado",
		},
		Preterite: {
			yo: "hube graznado",
			tú: "hubiste graznado",
			Ud: "hubo graznado",
			nosotros: "hubimos graznado",
			vosotros: "hubisteis graznado",
			Uds: "hubieron graznado",
		},
		Past: {
			yo: "había graznado",
			tú: "habías graznado",
			Ud: "había graznado",
			nosotros: "habíamos graznado",
			vosotros: "habíais graznado",
			Uds: "habían graznado",
		},
		Conditional: {
			yo: "habría graznado",
			tú: "habrías graznado",
			Ud: "habría graznado",
			nosotros: "habríamos graznado",
			vosotros: "habríais graznado",
			Uds: "habrían graznado",
		},
		Future: {
			yo: "habré graznado",
			tú: "habrás graznado",
			Ud: "habrá graznado",
			nosotros: "habremos graznado",
			vosotros: "habréis graznado",
			Uds: "habrán graznado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya graznado",
			tú: "hayas graznado",
			Ud: "haya graznado",
			nosotros: "hayamos graznado",
			vosotros: "hayáis graznado",
			Uds: "hayan graznado",
		},
		Past: {
			yo: "hubiera graznado",
			tú: "hubieras graznado",
			Ud: "hubiera graznado",
			nosotros: "hubiéramos graznado",
			vosotros: "hubierais graznado",
			Uds: "hubieran graznado",
		},
		Future: {
			yo: "hubiere graznado",
			tú: "hubieres graznado",
			Ud: "hubiere graznado",
			nosotros: "hubiéremos graznado",
			vosotros: "hubiereis graznado",
			Uds: "hubieren graznado",
		},
	},
}
