var gruñir = {
	Indicative: {
		Present: {
			yo: "gruño",
			tú: "gruñes",
			Ud: "gruñe",
			nosotros: "gruñimos",
			vosotros: "gruñís",
			Uds: "gruñen",
		},
		Preterite: {
			yo: "gruñí",
			tú: "gruñiste",
			Ud: "gruñó",
			nosotros: "gruñimos",
			vosotros: "gruñisteis",
			Uds: "gruñeron",
		},
		Imperfect: {
			yo: "gruñía",
			tú: "gruñías",
			Ud: "gruñía",
			nosotros: "gruñíamos",
			vosotros: "gruñíais",
			Uds: "gruñían",
		},
		Conditional: {
			yo: "gruñiría",
			tú: "gruñirías",
			Ud: "gruñiría",
			nosotros: "gruñiríamos",
			vosotros: "gruñiríais",
			Uds: "gruñirían",
		},
		Future: {
			yo: "gruñiré",
			tú: "gruñirás",
			Ud: "gruñirá",
			nosotros: "gruñiremos",
			vosotros: "gruñiréis",
			Uds: "gruñirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "gruña",
			tú: "gruñas",
			Ud: "gruña",
			nosotros: "gruñamos",
			vosotros: "gruñáis",
			Uds: "gruñan",
		},
		Imperfect: {
			yo: "gruñera",
			tú: "gruñeras",
			Ud: "gruñera",
			nosotros: "gruñéramos",
			vosotros: "gruñerais",
			Uds: "gruñeran",
		},
		Imperfect2: {
			yo: "gruñese",
			tú: "gruñeses",
			Ud: "gruñese",
			nosotros: "gruñésemos",
			vosotros: "gruñeseis",
			Uds: "gruñesen",
		},
		Future: {
			yo: "gruñere",
			tú: "gruñeres",
			Ud: "gruñere",
			nosotros: "gruñéremos",
			vosotros: "gruñereis",
			Uds: "gruñeren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "gruñe",
			Ud: "gruña",
			nosotros: "gruñamos",
			vosotros: "gruñid",
			Uds: "gruñan",
		},
		Negative: {
			tú: "no gruñas",
			Ud: "no gruña",
			nosotros: "no gruñamos",
			vosotros: "no gruñáis",
			Uds: "no gruñan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy gruñendo",
			tú: "estás gruñendo",
			Ud: "está gruñendo",
			nosotros: "estamos gruñendo",
			vosotros: "estáis gruñendo",
			Uds: "están gruñendo",
		},
		Preterite: {
			yo: "estuve gruñendo",
			tú: "estuviste gruñendo",
			Ud: "estuvo gruñendo",
			nosotros: "estuvimos gruñendo",
			vosotros: "estuvisteis gruñendo",
			Uds: "estuvieron gruñendo",
		},
		Imperfect: {
			Uds: "estaban gruñendo",
			yo: "estaba gruñendo",
			tú: "estabas gruñendo",
			Ud: "estaba gruñendo",
			nosotros: "estábamos gruñendo",
			vosotros: "estabais gruñendo",
		},
		Conditional: {
			yo: "estaría gruñendo",
			tú: "estarías gruñendo",
			Ud: "estaría gruñendo",
			nosotros: "estaríamos gruñendo",
			vosotros: "estaríais gruñendo",
			Uds: "estarían gruñendo",
		},
		Future: {
			yo: "estaré gruñendo",
			tú: "estarás gruñendo",
			Ud: "estará gruñendo",
			nosotros: "estaremos gruñendo",
			vosotros: "estaréis gruñendo",
			Uds: "estarán gruñendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he gruñido",
			tú: "has gruñido",
			Ud: "ha gruñido",
			nosotros: "hemos gruñido",
			vosotros: "habéis gruñido",
			Uds: "han gruñido",
		},
		Preterite: {
			yo: "hube gruñido",
			tú: "hubiste gruñido",
			Ud: "hubo gruñido",
			nosotros: "hubimos gruñido",
			vosotros: "hubisteis gruñido",
			Uds: "hubieron gruñido",
		},
		Past: {
			yo: "había gruñido",
			tú: "habías gruñido",
			Ud: "había gruñido",
			nosotros: "habíamos gruñido",
			vosotros: "habíais gruñido",
			Uds: "habían gruñido",
		},
		Conditional: {
			yo: "habría gruñido",
			tú: "habrías gruñido",
			Ud: "habría gruñido",
			nosotros: "habríamos gruñido",
			vosotros: "habríais gruñido",
			Uds: "habrían gruñido",
		},
		Future: {
			yo: "habré gruñido",
			tú: "habrás gruñido",
			Ud: "habrá gruñido",
			nosotros: "habremos gruñido",
			vosotros: "habréis gruñido",
			Uds: "habrán gruñido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya gruñido",
			tú: "hayas gruñido",
			Ud: "haya gruñido",
			nosotros: "hayamos gruñido",
			vosotros: "hayáis gruñido",
			Uds: "hayan gruñido",
		},
		Past: {
			yo: "hubiera gruñido",
			tú: "hubieras gruñido",
			Ud: "hubiera gruñido",
			nosotros: "hubiéramos gruñido",
			vosotros: "hubierais gruñido",
			Uds: "hubieran gruñido",
		},
		Future: {
			yo: "hubiere gruñido",
			tú: "hubieres gruñido",
			Ud: "hubiere gruñido",
			nosotros: "hubiéremos gruñido",
			vosotros: "hubiereis gruñido",
			Uds: "hubieren gruñido",
		},
	},
}
