var hacer = {
	Indicative: {
		Present: {
			yo: "hago",
			tú: "haces",
			Ud: "hace",
			nosotros: "hacemos",
			vosotros: "hacéis",
			Uds: "hacen",
		},
		Preterite: {
			yo: "hice",
			tú: "hiciste",
			Ud: "hizo",
			nosotros: "hicimos",
			vosotros: "hicisteis",
			Uds: "hicieron",
		},
		Imperfect: {
			yo: "hacía",
			tú: "hacías",
			Ud: "hacía",
			nosotros: "hacíamos",
			vosotros: "hacíais",
			Uds: "hacían",
		},
		Conditional: {
			yo: "haría",
			tú: "harías",
			Ud: "haría",
			nosotros: "haríamos",
			vosotros: "haríais",
			Uds: "harían",
		},
		Future: {
			yo: "haré",
			tú: "harás",
			Ud: "hará",
			nosotros: "haremos",
			vosotros: "haréis",
			Uds: "harán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "haga",
			tú: "hagas",
			Ud: "haga",
			nosotros: "hagamos",
			vosotros: "hagáis",
			Uds: "hagan",
		},
		Imperfect: {
			yo: "hiciera",
			tú: "hicieras",
			Ud: "hiciera",
			nosotros: "hiciéramos",
			vosotros: "hicierais",
			Uds: "hicieran",
		},
		Imperfect2: {
			yo: "hiciese",
			tú: "hicieses",
			Ud: "hiciese",
			nosotros: "hiciésemos",
			vosotros: "hicieseis",
			Uds: "hiciesen",
		},
		Future: {
			yo: "hiciere",
			tú: "hicieres",
			Ud: "hiciere",
			nosotros: "hiciéremos",
			vosotros: "hiciereis",
			Uds: "hicieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "haz",
			Ud: "haga",
			nosotros: "hagamos",
			vosotros: "haced",
			Uds: "hagan",
		},
		Negative: {
			tú: "no hagas",
			Ud: "no haga",
			nosotros: "no hagamos",
			vosotros: "no hagáis",
			Uds: "no hagan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy haciendo",
			tú: "estás haciendo",
			Ud: "está haciendo",
			nosotros: "estamos haciendo",
			vosotros: "estáis haciendo",
			Uds: "están haciendo",
		},
		Preterite: {
			yo: "estuve haciendo",
			tú: "estuviste haciendo",
			Ud: "estuvo haciendo",
			nosotros: "estuvimos haciendo",
			vosotros: "estuvisteis haciendo",
			Uds: "estuvieron haciendo",
		},
		Imperfect: {
			Uds: "estaban haciendo",
			yo: "estaba haciendo",
			tú: "estabas haciendo",
			Ud: "estaba haciendo",
			nosotros: "estábamos haciendo",
			vosotros: "estabais haciendo",
		},
		Conditional: {
			yo: "estaría haciendo",
			tú: "estarías haciendo",
			Ud: "estaría haciendo",
			nosotros: "estaríamos haciendo",
			vosotros: "estaríais haciendo",
			Uds: "estarían haciendo",
		},
		Future: {
			yo: "estaré haciendo",
			tú: "estarás haciendo",
			Ud: "estará haciendo",
			nosotros: "estaremos haciendo",
			vosotros: "estaréis haciendo",
			Uds: "estarán haciendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he hecho",
			tú: "has hecho",
			Ud: "ha hecho",
			nosotros: "hemos hecho",
			vosotros: "habéis hecho",
			Uds: "han hecho",
		},
		Preterite: {
			yo: "hube hecho",
			tú: "hubiste hecho",
			Ud: "hubo hecho",
			nosotros: "hubimos hecho",
			vosotros: "hubisteis hecho",
			Uds: "hubieron hecho",
		},
		Past: {
			yo: "había hecho",
			tú: "habías hecho",
			Ud: "había hecho",
			nosotros: "habíamos hecho",
			vosotros: "habíais hecho",
			Uds: "habían hecho",
		},
		Conditional: {
			yo: "habría hecho",
			tú: "habrías hecho",
			Ud: "habría hecho",
			nosotros: "habríamos hecho",
			vosotros: "habríais hecho",
			Uds: "habrían hecho",
		},
		Future: {
			yo: "habré hecho",
			tú: "habrás hecho",
			Ud: "habrá hecho",
			nosotros: "habremos hecho",
			vosotros: "habréis hecho",
			Uds: "habrán hecho",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya hecho",
			tú: "hayas hecho",
			Ud: "haya hecho",
			nosotros: "hayamos hecho",
			vosotros: "hayáis hecho",
			Uds: "hayan hecho",
		},
		Past: {
			yo: "hubiera hecho",
			tú: "hubieras hecho",
			Ud: "hubiera hecho",
			nosotros: "hubiéramos hecho",
			vosotros: "hubierais hecho",
			Uds: "hubieran hecho",
		},
		Future: {
			yo: "hubiere hecho",
			tú: "hubieres hecho",
			Ud: "hubiere hecho",
			nosotros: "hubiéremos hecho",
			vosotros: "hubiereis hecho",
			Uds: "hubieren hecho",
		},
	},
}
