var hermanar = {
	Indicative: {
		Present: {
			yo: "hermano",
			tú: "hermanas",
			Ud: "hermana",
			nosotros: "hermanamos",
			vosotros: "hermanáis",
			Uds: "hermanan",
		},
		Preterite: {
			yo: "hermané",
			tú: "hermanaste",
			Ud: "hermanó",
			nosotros: "hermanamos",
			vosotros: "hermanasteis",
			Uds: "hermanaron",
		},
		Imperfect: {
			yo: "hermanaba",
			tú: "hermanabas",
			Ud: "hermanaba",
			nosotros: "hermanábamos",
			vosotros: "hermanabais",
			Uds: "hermanaban",
		},
		Conditional: {
			yo: "hermanaría",
			tú: "hermanarías",
			Ud: "hermanaría",
			nosotros: "hermanaríamos",
			vosotros: "hermanaríais",
			Uds: "hermanarían",
		},
		Future: {
			yo: "hermanaré",
			tú: "hermanarás",
			Ud: "hermanará",
			nosotros: "hermanaremos",
			vosotros: "hermanaréis",
			Uds: "hermanarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "hermane",
			tú: "hermanes",
			Ud: "hermane",
			nosotros: "hermanemos",
			vosotros: "hermanéis",
			Uds: "hermanen",
		},
		Imperfect: {
			yo: "hermanara",
			tú: "hermanaras",
			Ud: "hermanara",
			nosotros: "hermanáramos",
			vosotros: "hermanarais",
			Uds: "hermanaran",
		},
		Imperfect2: {
			yo: "hermanase",
			tú: "hermanases",
			Ud: "hermanase",
			nosotros: "hermanásemos",
			vosotros: "hermanaseis",
			Uds: "hermanasen",
		},
		Future: {
			yo: "hermanare",
			tú: "hermanares",
			Ud: "hermanare",
			nosotros: "hermanáremos",
			vosotros: "hermanareis",
			Uds: "hermanaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "hermana",
			Ud: "hermane",
			nosotros: "hermanemos",
			vosotros: "hermanad",
			Uds: "hermanen",
		},
		Negative: {
			tú: "no hermanes",
			Ud: "no hermane",
			nosotros: "no hermanemos",
			vosotros: "no hermanéis",
			Uds: "no hermanen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy hermanando",
			tú: "estás hermanando",
			Ud: "está hermanando",
			nosotros: "estamos hermanando",
			vosotros: "estáis hermanando",
			Uds: "están hermanando",
		},
		Preterite: {
			yo: "estuve hermanando",
			tú: "estuviste hermanando",
			Ud: "estuvo hermanando",
			nosotros: "estuvimos hermanando",
			vosotros: "estuvisteis hermanando",
			Uds: "estuvieron hermanando",
		},
		Imperfect: {
			Uds: "estaban hermanando",
			yo: "estaba hermanando",
			tú: "estabas hermanando",
			Ud: "estaba hermanando",
			nosotros: "estábamos hermanando",
			vosotros: "estabais hermanando",
		},
		Conditional: {
			yo: "estaría hermanando",
			tú: "estarías hermanando",
			Ud: "estaría hermanando",
			nosotros: "estaríamos hermanando",
			vosotros: "estaríais hermanando",
			Uds: "estarían hermanando",
		},
		Future: {
			yo: "estaré hermanando",
			tú: "estarás hermanando",
			Ud: "estará hermanando",
			nosotros: "estaremos hermanando",
			vosotros: "estaréis hermanando",
			Uds: "estarán hermanando",
		},
	},
	Perfect: {
		Present: {
			yo: "he hermanado",
			tú: "has hermanado",
			Ud: "ha hermanado",
			nosotros: "hemos hermanado",
			vosotros: "habéis hermanado",
			Uds: "han hermanado",
		},
		Preterite: {
			yo: "hube hermanado",
			tú: "hubiste hermanado",
			Ud: "hubo hermanado",
			nosotros: "hubimos hermanado",
			vosotros: "hubisteis hermanado",
			Uds: "hubieron hermanado",
		},
		Past: {
			yo: "había hermanado",
			tú: "habías hermanado",
			Ud: "había hermanado",
			nosotros: "habíamos hermanado",
			vosotros: "habíais hermanado",
			Uds: "habían hermanado",
		},
		Conditional: {
			yo: "habría hermanado",
			tú: "habrías hermanado",
			Ud: "habría hermanado",
			nosotros: "habríamos hermanado",
			vosotros: "habríais hermanado",
			Uds: "habrían hermanado",
		},
		Future: {
			yo: "habré hermanado",
			tú: "habrás hermanado",
			Ud: "habrá hermanado",
			nosotros: "habremos hermanado",
			vosotros: "habréis hermanado",
			Uds: "habrán hermanado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya hermanado",
			tú: "hayas hermanado",
			Ud: "haya hermanado",
			nosotros: "hayamos hermanado",
			vosotros: "hayáis hermanado",
			Uds: "hayan hermanado",
		},
		Past: {
			yo: "hubiera hermanado",
			tú: "hubieras hermanado",
			Ud: "hubiera hermanado",
			nosotros: "hubiéramos hermanado",
			vosotros: "hubierais hermanado",
			Uds: "hubieran hermanado",
		},
		Future: {
			yo: "hubiere hermanado",
			tú: "hubieres hermanado",
			Ud: "hubiere hermanado",
			nosotros: "hubiéremos hermanado",
			vosotros: "hubiereis hermanado",
			Uds: "hubieren hermanado",
		},
	},
}
