var herrar = {
	Indicative: {
		Present: {
			yo: "hierro",
			tú: "hierras",
			Ud: "hierra",
			nosotros: "herramos",
			vosotros: "herráis",
			Uds: "hierran",
		},
		Preterite: {
			yo: "herré",
			tú: "herraste",
			Ud: "herró",
			nosotros: "herramos",
			vosotros: "herrasteis",
			Uds: "herraron",
		},
		Imperfect: {
			yo: "herraba",
			tú: "herrabas",
			Ud: "herraba",
			nosotros: "herrábamos",
			vosotros: "herrabais",
			Uds: "herraban",
		},
		Conditional: {
			yo: "herraría",
			tú: "herrarías",
			Ud: "herraría",
			nosotros: "herraríamos",
			vosotros: "herraríais",
			Uds: "herrarían",
		},
		Future: {
			yo: "herraré",
			tú: "herrarás",
			Ud: "herrará",
			nosotros: "herraremos",
			vosotros: "herraréis",
			Uds: "herrarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "hierre",
			tú: "hierres",
			Ud: "hierre",
			nosotros: "herremos",
			vosotros: "herréis",
			Uds: "hierren",
		},
		Imperfect: {
			yo: "herrara",
			tú: "herraras",
			Ud: "herrara",
			nosotros: "herráramos",
			vosotros: "herrarais",
			Uds: "herraran",
		},
		Imperfect2: {
			yo: "herrase",
			tú: "herrases",
			Ud: "herrase",
			nosotros: "herrásemos",
			vosotros: "herraseis",
			Uds: "herrasen",
		},
		Future: {
			yo: "herrare",
			tú: "herrares",
			Ud: "herrare",
			nosotros: "herráremos",
			vosotros: "herrareis",
			Uds: "herraren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "hierra",
			Ud: "hierre",
			nosotros: "herremos",
			vosotros: "herrad",
			Uds: "hierren",
		},
		Negative: {
			tú: "no hierres",
			Ud: "no hierre",
			nosotros: "no herremos",
			vosotros: "no herréis",
			Uds: "no hierren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy herrando",
			tú: "estás herrando",
			Ud: "está herrando",
			nosotros: "estamos herrando",
			vosotros: "estáis herrando",
			Uds: "están herrando",
		},
		Preterite: {
			yo: "estuve herrando",
			tú: "estuviste herrando",
			Ud: "estuvo herrando",
			nosotros: "estuvimos herrando",
			vosotros: "estuvisteis herrando",
			Uds: "estuvieron herrando",
		},
		Imperfect: {
			Uds: "estaban herrando",
			yo: "estaba herrando",
			tú: "estabas herrando",
			Ud: "estaba herrando",
			nosotros: "estábamos herrando",
			vosotros: "estabais herrando",
		},
		Conditional: {
			yo: "estaría herrando",
			tú: "estarías herrando",
			Ud: "estaría herrando",
			nosotros: "estaríamos herrando",
			vosotros: "estaríais herrando",
			Uds: "estarían herrando",
		},
		Future: {
			yo: "estaré herrando",
			tú: "estarás herrando",
			Ud: "estará herrando",
			nosotros: "estaremos herrando",
			vosotros: "estaréis herrando",
			Uds: "estarán herrando",
		},
	},
	Perfect: {
		Present: {
			yo: "he herrado",
			tú: "has herrado",
			Ud: "ha herrado",
			nosotros: "hemos herrado",
			vosotros: "habéis herrado",
			Uds: "han herrado",
		},
		Preterite: {
			yo: "hube herrado",
			tú: "hubiste herrado",
			Ud: "hubo herrado",
			nosotros: "hubimos herrado",
			vosotros: "hubisteis herrado",
			Uds: "hubieron herrado",
		},
		Past: {
			yo: "había herrado",
			tú: "habías herrado",
			Ud: "había herrado",
			nosotros: "habíamos herrado",
			vosotros: "habíais herrado",
			Uds: "habían herrado",
		},
		Conditional: {
			yo: "habría herrado",
			tú: "habrías herrado",
			Ud: "habría herrado",
			nosotros: "habríamos herrado",
			vosotros: "habríais herrado",
			Uds: "habrían herrado",
		},
		Future: {
			yo: "habré herrado",
			tú: "habrás herrado",
			Ud: "habrá herrado",
			nosotros: "habremos herrado",
			vosotros: "habréis herrado",
			Uds: "habrán herrado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya herrado",
			tú: "hayas herrado",
			Ud: "haya herrado",
			nosotros: "hayamos herrado",
			vosotros: "hayáis herrado",
			Uds: "hayan herrado",
		},
		Past: {
			yo: "hubiera herrado",
			tú: "hubieras herrado",
			Ud: "hubiera herrado",
			nosotros: "hubiéramos herrado",
			vosotros: "hubierais herrado",
			Uds: "hubieran herrado",
		},
		Future: {
			yo: "hubiere herrado",
			tú: "hubieres herrado",
			Ud: "hubiere herrado",
			nosotros: "hubiéremos herrado",
			vosotros: "hubiereis herrado",
			Uds: "hubieren herrado",
		},
	},
}
