var hilvanar = {
	Indicative: {
		Present: {
			yo: "hilvano",
			tú: "hilvanas",
			Ud: "hilvana",
			nosotros: "hilvanamos",
			vosotros: "hilvanáis",
			Uds: "hilvanan",
		},
		Preterite: {
			yo: "hilvané",
			tú: "hilvanaste",
			Ud: "hilvanó",
			nosotros: "hilvanamos",
			vosotros: "hilvanasteis",
			Uds: "hilvanaron",
		},
		Imperfect: {
			yo: "hilvanaba",
			tú: "hilvanabas",
			Ud: "hilvanaba",
			nosotros: "hilvanábamos",
			vosotros: "hilvanabais",
			Uds: "hilvanaban",
		},
		Conditional: {
			yo: "hilvanaría",
			tú: "hilvanarías",
			Ud: "hilvanaría",
			nosotros: "hilvanaríamos",
			vosotros: "hilvanaríais",
			Uds: "hilvanarían",
		},
		Future: {
			yo: "hilvanaré",
			tú: "hilvanarás",
			Ud: "hilvanará",
			nosotros: "hilvanaremos",
			vosotros: "hilvanaréis",
			Uds: "hilvanarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "hilvane",
			tú: "hilvanes",
			Ud: "hilvane",
			nosotros: "hilvanemos",
			vosotros: "hilvanéis",
			Uds: "hilvanen",
		},
		Imperfect: {
			yo: "hilvanara",
			tú: "hilvanaras",
			Ud: "hilvanara",
			nosotros: "hilvanáramos",
			vosotros: "hilvanarais",
			Uds: "hilvanaran",
		},
		Imperfect2: {
			yo: "hilvanase",
			tú: "hilvanases",
			Ud: "hilvanase",
			nosotros: "hilvanásemos",
			vosotros: "hilvanaseis",
			Uds: "hilvanasen",
		},
		Future: {
			yo: "hilvanare",
			tú: "hilvanares",
			Ud: "hilvanare",
			nosotros: "hilvanáremos",
			vosotros: "hilvanareis",
			Uds: "hilvanaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "hilvana",
			Ud: "hilvane",
			nosotros: "hilvanemos",
			vosotros: "hilvanad",
			Uds: "hilvanen",
		},
		Negative: {
			tú: "no hilvanes",
			Ud: "no hilvane",
			nosotros: "no hilvanemos",
			vosotros: "no hilvanéis",
			Uds: "no hilvanen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy hilvanando",
			tú: "estás hilvanando",
			Ud: "está hilvanando",
			nosotros: "estamos hilvanando",
			vosotros: "estáis hilvanando",
			Uds: "están hilvanando",
		},
		Preterite: {
			yo: "estuve hilvanando",
			tú: "estuviste hilvanando",
			Ud: "estuvo hilvanando",
			nosotros: "estuvimos hilvanando",
			vosotros: "estuvisteis hilvanando",
			Uds: "estuvieron hilvanando",
		},
		Imperfect: {
			Uds: "estaban hilvanando",
			yo: "estaba hilvanando",
			tú: "estabas hilvanando",
			Ud: "estaba hilvanando",
			nosotros: "estábamos hilvanando",
			vosotros: "estabais hilvanando",
		},
		Conditional: {
			yo: "estaría hilvanando",
			tú: "estarías hilvanando",
			Ud: "estaría hilvanando",
			nosotros: "estaríamos hilvanando",
			vosotros: "estaríais hilvanando",
			Uds: "estarían hilvanando",
		},
		Future: {
			yo: "estaré hilvanando",
			tú: "estarás hilvanando",
			Ud: "estará hilvanando",
			nosotros: "estaremos hilvanando",
			vosotros: "estaréis hilvanando",
			Uds: "estarán hilvanando",
		},
	},
	Perfect: {
		Present: {
			yo: "he hilvanado",
			tú: "has hilvanado",
			Ud: "ha hilvanado",
			nosotros: "hemos hilvanado",
			vosotros: "habéis hilvanado",
			Uds: "han hilvanado",
		},
		Preterite: {
			yo: "hube hilvanado",
			tú: "hubiste hilvanado",
			Ud: "hubo hilvanado",
			nosotros: "hubimos hilvanado",
			vosotros: "hubisteis hilvanado",
			Uds: "hubieron hilvanado",
		},
		Past: {
			yo: "había hilvanado",
			tú: "habías hilvanado",
			Ud: "había hilvanado",
			nosotros: "habíamos hilvanado",
			vosotros: "habíais hilvanado",
			Uds: "habían hilvanado",
		},
		Conditional: {
			yo: "habría hilvanado",
			tú: "habrías hilvanado",
			Ud: "habría hilvanado",
			nosotros: "habríamos hilvanado",
			vosotros: "habríais hilvanado",
			Uds: "habrían hilvanado",
		},
		Future: {
			yo: "habré hilvanado",
			tú: "habrás hilvanado",
			Ud: "habrá hilvanado",
			nosotros: "habremos hilvanado",
			vosotros: "habréis hilvanado",
			Uds: "habrán hilvanado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya hilvanado",
			tú: "hayas hilvanado",
			Ud: "haya hilvanado",
			nosotros: "hayamos hilvanado",
			vosotros: "hayáis hilvanado",
			Uds: "hayan hilvanado",
		},
		Past: {
			yo: "hubiera hilvanado",
			tú: "hubieras hilvanado",
			Ud: "hubiera hilvanado",
			nosotros: "hubiéramos hilvanado",
			vosotros: "hubierais hilvanado",
			Uds: "hubieran hilvanado",
		},
		Future: {
			yo: "hubiere hilvanado",
			tú: "hubieres hilvanado",
			Ud: "hubiere hilvanado",
			nosotros: "hubiéremos hilvanado",
			vosotros: "hubiereis hilvanado",
			Uds: "hubieren hilvanado",
		},
	},
}
