var hojear = {
	Indicative: {
		Present: {
			yo: "hojeo",
			tú: "hojeas",
			Ud: "hojea",
			nosotros: "hojeamos",
			vosotros: "hojeáis",
			Uds: "hojean",
		},
		Preterite: {
			yo: "hojeé",
			tú: "hojeaste",
			Ud: "hojeó",
			nosotros: "hojeamos",
			vosotros: "hojeasteis",
			Uds: "hojearon",
		},
		Imperfect: {
			yo: "hojeaba",
			tú: "hojeabas",
			Ud: "hojeaba",
			nosotros: "hojeábamos",
			vosotros: "hojeabais",
			Uds: "hojeaban",
		},
		Conditional: {
			yo: "hojearía",
			tú: "hojearías",
			Ud: "hojearía",
			nosotros: "hojearíamos",
			vosotros: "hojearíais",
			Uds: "hojearían",
		},
		Future: {
			yo: "hojearé",
			tú: "hojearás",
			Ud: "hojeará",
			nosotros: "hojearemos",
			vosotros: "hojearéis",
			Uds: "hojearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "hojee",
			tú: "hojees",
			Ud: "hojee",
			nosotros: "hojeemos",
			vosotros: "hojeéis",
			Uds: "hojeen",
		},
		Imperfect: {
			yo: "hojeara",
			tú: "hojearas",
			Ud: "hojeara",
			nosotros: "hojeáramos",
			vosotros: "hojearais",
			Uds: "hojearan",
		},
		Imperfect2: {
			yo: "hojease",
			tú: "hojeases",
			Ud: "hojease",
			nosotros: "hojeásemos",
			vosotros: "hojeaseis",
			Uds: "hojeasen",
		},
		Future: {
			yo: "hojeare",
			tú: "hojeares",
			Ud: "hojeare",
			nosotros: "hojeáremos",
			vosotros: "hojeareis",
			Uds: "hojearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "hojea",
			Ud: "hojee",
			nosotros: "hojeemos",
			vosotros: "hojead",
			Uds: "hojeen",
		},
		Negative: {
			tú: "no hojees",
			Ud: "no hojee",
			nosotros: "no hojeemos",
			vosotros: "no hojeéis",
			Uds: "no hojeen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy hojeando",
			tú: "estás hojeando",
			Ud: "está hojeando",
			nosotros: "estamos hojeando",
			vosotros: "estáis hojeando",
			Uds: "están hojeando",
		},
		Preterite: {
			yo: "estuve hojeando",
			tú: "estuviste hojeando",
			Ud: "estuvo hojeando",
			nosotros: "estuvimos hojeando",
			vosotros: "estuvisteis hojeando",
			Uds: "estuvieron hojeando",
		},
		Imperfect: {
			Uds: "estaban hojeando",
			yo: "estaba hojeando",
			tú: "estabas hojeando",
			Ud: "estaba hojeando",
			nosotros: "estábamos hojeando",
			vosotros: "estabais hojeando",
		},
		Conditional: {
			yo: "estaría hojeando",
			tú: "estarías hojeando",
			Ud: "estaría hojeando",
			nosotros: "estaríamos hojeando",
			vosotros: "estaríais hojeando",
			Uds: "estarían hojeando",
		},
		Future: {
			yo: "estaré hojeando",
			tú: "estarás hojeando",
			Ud: "estará hojeando",
			nosotros: "estaremos hojeando",
			vosotros: "estaréis hojeando",
			Uds: "estarán hojeando",
		},
	},
	Perfect: {
		Present: {
			yo: "he hojeado",
			tú: "has hojeado",
			Ud: "ha hojeado",
			nosotros: "hemos hojeado",
			vosotros: "habéis hojeado",
			Uds: "han hojeado",
		},
		Preterite: {
			yo: "hube hojeado",
			tú: "hubiste hojeado",
			Ud: "hubo hojeado",
			nosotros: "hubimos hojeado",
			vosotros: "hubisteis hojeado",
			Uds: "hubieron hojeado",
		},
		Past: {
			yo: "había hojeado",
			tú: "habías hojeado",
			Ud: "había hojeado",
			nosotros: "habíamos hojeado",
			vosotros: "habíais hojeado",
			Uds: "habían hojeado",
		},
		Conditional: {
			yo: "habría hojeado",
			tú: "habrías hojeado",
			Ud: "habría hojeado",
			nosotros: "habríamos hojeado",
			vosotros: "habríais hojeado",
			Uds: "habrían hojeado",
		},
		Future: {
			yo: "habré hojeado",
			tú: "habrás hojeado",
			Ud: "habrá hojeado",
			nosotros: "habremos hojeado",
			vosotros: "habréis hojeado",
			Uds: "habrán hojeado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya hojeado",
			tú: "hayas hojeado",
			Ud: "haya hojeado",
			nosotros: "hayamos hojeado",
			vosotros: "hayáis hojeado",
			Uds: "hayan hojeado",
		},
		Past: {
			yo: "hubiera hojeado",
			tú: "hubieras hojeado",
			Ud: "hubiera hojeado",
			nosotros: "hubiéramos hojeado",
			vosotros: "hubierais hojeado",
			Uds: "hubieran hojeado",
		},
		Future: {
			yo: "hubiere hojeado",
			tú: "hubieres hojeado",
			Ud: "hubiere hojeado",
			nosotros: "hubiéremos hojeado",
			vosotros: "hubiereis hojeado",
			Uds: "hubieren hojeado",
		},
	},
}
