var humillar = {
	Indicative: {
		Present: {
			yo: "humillo",
			tú: "humillas",
			Ud: "humilla",
			nosotros: "humillamos",
			vosotros: "humilláis",
			Uds: "humillan",
		},
		Preterite: {
			yo: "humillé",
			tú: "humillaste",
			Ud: "humilló",
			nosotros: "humillamos",
			vosotros: "humillasteis",
			Uds: "humillaron",
		},
		Imperfect: {
			yo: "humillaba",
			tú: "humillabas",
			Ud: "humillaba",
			nosotros: "humillábamos",
			vosotros: "humillabais",
			Uds: "humillaban",
		},
		Conditional: {
			yo: "humillaría",
			tú: "humillarías",
			Ud: "humillaría",
			nosotros: "humillaríamos",
			vosotros: "humillaríais",
			Uds: "humillarían",
		},
		Future: {
			yo: "humillaré",
			tú: "humillarás",
			Ud: "humillará",
			nosotros: "humillaremos",
			vosotros: "humillaréis",
			Uds: "humillarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "humille",
			tú: "humilles",
			Ud: "humille",
			nosotros: "humillemos",
			vosotros: "humilléis",
			Uds: "humillen",
		},
		Imperfect: {
			yo: "humillara",
			tú: "humillaras",
			Ud: "humillara",
			nosotros: "humilláramos",
			vosotros: "humillarais",
			Uds: "humillaran",
		},
		Imperfect2: {
			yo: "humillase",
			tú: "humillases",
			Ud: "humillase",
			nosotros: "humillásemos",
			vosotros: "humillaseis",
			Uds: "humillasen",
		},
		Future: {
			yo: "humillare",
			tú: "humillares",
			Ud: "humillare",
			nosotros: "humilláremos",
			vosotros: "humillareis",
			Uds: "humillaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "humilla",
			Ud: "humille",
			nosotros: "humillemos",
			vosotros: "humillad",
			Uds: "humillen",
		},
		Negative: {
			tú: "no humilles",
			Ud: "no humille",
			nosotros: "no humillemos",
			vosotros: "no humilléis",
			Uds: "no humillen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy humillando",
			tú: "estás humillando",
			Ud: "está humillando",
			nosotros: "estamos humillando",
			vosotros: "estáis humillando",
			Uds: "están humillando",
		},
		Preterite: {
			yo: "estuve humillando",
			tú: "estuviste humillando",
			Ud: "estuvo humillando",
			nosotros: "estuvimos humillando",
			vosotros: "estuvisteis humillando",
			Uds: "estuvieron humillando",
		},
		Imperfect: {
			Uds: "estaban humillando",
			yo: "estaba humillando",
			tú: "estabas humillando",
			Ud: "estaba humillando",
			nosotros: "estábamos humillando",
			vosotros: "estabais humillando",
		},
		Conditional: {
			yo: "estaría humillando",
			tú: "estarías humillando",
			Ud: "estaría humillando",
			nosotros: "estaríamos humillando",
			vosotros: "estaríais humillando",
			Uds: "estarían humillando",
		},
		Future: {
			yo: "estaré humillando",
			tú: "estarás humillando",
			Ud: "estará humillando",
			nosotros: "estaremos humillando",
			vosotros: "estaréis humillando",
			Uds: "estarán humillando",
		},
	},
	Perfect: {
		Present: {
			yo: "he humillado",
			tú: "has humillado",
			Ud: "ha humillado",
			nosotros: "hemos humillado",
			vosotros: "habéis humillado",
			Uds: "han humillado",
		},
		Preterite: {
			yo: "hube humillado",
			tú: "hubiste humillado",
			Ud: "hubo humillado",
			nosotros: "hubimos humillado",
			vosotros: "hubisteis humillado",
			Uds: "hubieron humillado",
		},
		Past: {
			yo: "había humillado",
			tú: "habías humillado",
			Ud: "había humillado",
			nosotros: "habíamos humillado",
			vosotros: "habíais humillado",
			Uds: "habían humillado",
		},
		Conditional: {
			yo: "habría humillado",
			tú: "habrías humillado",
			Ud: "habría humillado",
			nosotros: "habríamos humillado",
			vosotros: "habríais humillado",
			Uds: "habrían humillado",
		},
		Future: {
			yo: "habré humillado",
			tú: "habrás humillado",
			Ud: "habrá humillado",
			nosotros: "habremos humillado",
			vosotros: "habréis humillado",
			Uds: "habrán humillado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya humillado",
			tú: "hayas humillado",
			Ud: "haya humillado",
			nosotros: "hayamos humillado",
			vosotros: "hayáis humillado",
			Uds: "hayan humillado",
		},
		Past: {
			yo: "hubiera humillado",
			tú: "hubieras humillado",
			Ud: "hubiera humillado",
			nosotros: "hubiéramos humillado",
			vosotros: "hubierais humillado",
			Uds: "hubieran humillado",
		},
		Future: {
			yo: "hubiere humillado",
			tú: "hubieres humillado",
			Ud: "hubiere humillado",
			nosotros: "hubiéremos humillado",
			vosotros: "hubiereis humillado",
			Uds: "hubieren humillado",
		},
	},
}
