var idear = {
	Indicative: {
		Present: {
			yo: "ideo",
			tú: "ideas",
			Ud: "idea",
			nosotros: "ideamos",
			vosotros: "ideáis",
			Uds: "idean",
		},
		Preterite: {
			yo: "ideé",
			tú: "ideaste",
			Ud: "ideó",
			nosotros: "ideamos",
			vosotros: "ideasteis",
			Uds: "idearon",
		},
		Imperfect: {
			yo: "ideaba",
			tú: "ideabas",
			Ud: "ideaba",
			nosotros: "ideábamos",
			vosotros: "ideabais",
			Uds: "ideaban",
		},
		Conditional: {
			yo: "idearía",
			tú: "idearías",
			Ud: "idearía",
			nosotros: "idearíamos",
			vosotros: "idearíais",
			Uds: "idearían",
		},
		Future: {
			yo: "idearé",
			tú: "idearás",
			Ud: "ideará",
			nosotros: "idearemos",
			vosotros: "idearéis",
			Uds: "idearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "idee",
			tú: "idees",
			Ud: "idee",
			nosotros: "ideemos",
			vosotros: "ideéis",
			Uds: "ideen",
		},
		Imperfect: {
			yo: "ideara",
			tú: "idearas",
			Ud: "ideara",
			nosotros: "ideáramos",
			vosotros: "idearais",
			Uds: "idearan",
		},
		Imperfect2: {
			yo: "idease",
			tú: "ideases",
			Ud: "idease",
			nosotros: "ideásemos",
			vosotros: "ideaseis",
			Uds: "ideasen",
		},
		Future: {
			yo: "ideare",
			tú: "ideares",
			Ud: "ideare",
			nosotros: "ideáremos",
			vosotros: "ideareis",
			Uds: "idearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "idea",
			Ud: "idee",
			nosotros: "ideemos",
			vosotros: "idead",
			Uds: "ideen",
		},
		Negative: {
			tú: "no idees",
			Ud: "no idee",
			nosotros: "no ideemos",
			vosotros: "no ideéis",
			Uds: "no ideen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy ideando",
			tú: "estás ideando",
			Ud: "está ideando",
			nosotros: "estamos ideando",
			vosotros: "estáis ideando",
			Uds: "están ideando",
		},
		Preterite: {
			yo: "estuve ideando",
			tú: "estuviste ideando",
			Ud: "estuvo ideando",
			nosotros: "estuvimos ideando",
			vosotros: "estuvisteis ideando",
			Uds: "estuvieron ideando",
		},
		Imperfect: {
			Uds: "estaban ideando",
			yo: "estaba ideando",
			tú: "estabas ideando",
			Ud: "estaba ideando",
			nosotros: "estábamos ideando",
			vosotros: "estabais ideando",
		},
		Conditional: {
			yo: "estaría ideando",
			tú: "estarías ideando",
			Ud: "estaría ideando",
			nosotros: "estaríamos ideando",
			vosotros: "estaríais ideando",
			Uds: "estarían ideando",
		},
		Future: {
			yo: "estaré ideando",
			tú: "estarás ideando",
			Ud: "estará ideando",
			nosotros: "estaremos ideando",
			vosotros: "estaréis ideando",
			Uds: "estarán ideando",
		},
	},
	Perfect: {
		Present: {
			yo: "he ideado",
			tú: "has ideado",
			Ud: "ha ideado",
			nosotros: "hemos ideado",
			vosotros: "habéis ideado",
			Uds: "han ideado",
		},
		Preterite: {
			yo: "hube ideado",
			tú: "hubiste ideado",
			Ud: "hubo ideado",
			nosotros: "hubimos ideado",
			vosotros: "hubisteis ideado",
			Uds: "hubieron ideado",
		},
		Past: {
			yo: "había ideado",
			tú: "habías ideado",
			Ud: "había ideado",
			nosotros: "habíamos ideado",
			vosotros: "habíais ideado",
			Uds: "habían ideado",
		},
		Conditional: {
			yo: "habría ideado",
			tú: "habrías ideado",
			Ud: "habría ideado",
			nosotros: "habríamos ideado",
			vosotros: "habríais ideado",
			Uds: "habrían ideado",
		},
		Future: {
			yo: "habré ideado",
			tú: "habrás ideado",
			Ud: "habrá ideado",
			nosotros: "habremos ideado",
			vosotros: "habréis ideado",
			Uds: "habrán ideado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya ideado",
			tú: "hayas ideado",
			Ud: "haya ideado",
			nosotros: "hayamos ideado",
			vosotros: "hayáis ideado",
			Uds: "hayan ideado",
		},
		Past: {
			yo: "hubiera ideado",
			tú: "hubieras ideado",
			Ud: "hubiera ideado",
			nosotros: "hubiéramos ideado",
			vosotros: "hubierais ideado",
			Uds: "hubieran ideado",
		},
		Future: {
			yo: "hubiere ideado",
			tú: "hubieres ideado",
			Ud: "hubiere ideado",
			nosotros: "hubiéremos ideado",
			vosotros: "hubiereis ideado",
			Uds: "hubieren ideado",
		},
	},
}
