var imbuir = {
	Indicative: {
		Present: {
			yo: "imbuyo",
			tú: "imbuyes",
			Ud: "imbuye",
			nosotros: "imbuimos",
			vosotros: "imbuís",
			Uds: "imbuyen",
		},
		Preterite: {
			yo: "imbuí",
			tú: "imbuiste",
			Ud: "imbuyó",
			nosotros: "imbuimos",
			vosotros: "imbuisteis",
			Uds: "imbuyeron",
		},
		Imperfect: {
			yo: "imbuía",
			tú: "imbuías",
			Ud: "imbuía",
			nosotros: "imbuíamos",
			vosotros: "imbuíais",
			Uds: "imbuían",
		},
		Conditional: {
			yo: "imbuiría",
			tú: "imbuirías",
			Ud: "imbuiría",
			nosotros: "imbuiríamos",
			vosotros: "imbuiríais",
			Uds: "imbuirían",
		},
		Future: {
			yo: "imbuiré",
			tú: "imbuirás",
			Ud: "imbuirá",
			nosotros: "imbuiremos",
			vosotros: "imbuiréis",
			Uds: "imbuirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "imbuya",
			tú: "imbuyas",
			Ud: "imbuya",
			nosotros: "imbuyamos",
			vosotros: "imbuyáis",
			Uds: "imbuyan",
		},
		Imperfect: {
			yo: "imbuyera",
			tú: "imbuyeras",
			Ud: "imbuyera",
			nosotros: "imbuyéramos",
			vosotros: "imbuyerais",
			Uds: "imbuyeran",
		},
		Imperfect2: {
			yo: "imbuyese",
			tú: "imbuyeses",
			Ud: "imbuyese",
			nosotros: "imbuyésemos",
			vosotros: "imbuyeseis",
			Uds: "imbuyesen",
		},
		Future: {
			yo: "imbuyere",
			tú: "imbuyeres",
			Ud: "imbuyere",
			nosotros: "imbuyéremos",
			vosotros: "imbuyereis",
			Uds: "imbuyeren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "imbuye",
			Ud: "imbuya",
			nosotros: "imbuyamos",
			vosotros: "imbuid",
			Uds: "imbuyan",
		},
		Negative: {
			tú: "no imbuyas",
			Ud: "no imbuya",
			nosotros: "no imbuyamos",
			vosotros: "no imbuyáis",
			Uds: "no imbuyan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy imbuyendo",
			tú: "estás imbuyendo",
			Ud: "está imbuyendo",
			nosotros: "estamos imbuyendo",
			vosotros: "estáis imbuyendo",
			Uds: "están imbuyendo",
		},
		Preterite: {
			yo: "estuve imbuyendo",
			tú: "estuviste imbuyendo",
			Ud: "estuvo imbuyendo",
			nosotros: "estuvimos imbuyendo",
			vosotros: "estuvisteis imbuyendo",
			Uds: "estuvieron imbuyendo",
		},
		Imperfect: {
			Uds: "estaban imbuyendo",
			yo: "estaba imbuyendo",
			tú: "estabas imbuyendo",
			Ud: "estaba imbuyendo",
			nosotros: "estábamos imbuyendo",
			vosotros: "estabais imbuyendo",
		},
		Conditional: {
			yo: "estaría imbuyendo",
			tú: "estarías imbuyendo",
			Ud: "estaría imbuyendo",
			nosotros: "estaríamos imbuyendo",
			vosotros: "estaríais imbuyendo",
			Uds: "estarían imbuyendo",
		},
		Future: {
			yo: "estaré imbuyendo",
			tú: "estarás imbuyendo",
			Ud: "estará imbuyendo",
			nosotros: "estaremos imbuyendo",
			vosotros: "estaréis imbuyendo",
			Uds: "estarán imbuyendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he imbuido",
			tú: "has imbuido",
			Ud: "ha imbuido",
			nosotros: "hemos imbuido",
			vosotros: "habéis imbuido",
			Uds: "han imbuido",
		},
		Preterite: {
			yo: "hube imbuido",
			tú: "hubiste imbuido",
			Ud: "hubo imbuido",
			nosotros: "hubimos imbuido",
			vosotros: "hubisteis imbuido",
			Uds: "hubieron imbuido",
		},
		Past: {
			yo: "había imbuido",
			tú: "habías imbuido",
			Ud: "había imbuido",
			nosotros: "habíamos imbuido",
			vosotros: "habíais imbuido",
			Uds: "habían imbuido",
		},
		Conditional: {
			yo: "habría imbuido",
			tú: "habrías imbuido",
			Ud: "habría imbuido",
			nosotros: "habríamos imbuido",
			vosotros: "habríais imbuido",
			Uds: "habrían imbuido",
		},
		Future: {
			yo: "habré imbuido",
			tú: "habrás imbuido",
			Ud: "habrá imbuido",
			nosotros: "habremos imbuido",
			vosotros: "habréis imbuido",
			Uds: "habrán imbuido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya imbuido",
			tú: "hayas imbuido",
			Ud: "haya imbuido",
			nosotros: "hayamos imbuido",
			vosotros: "hayáis imbuido",
			Uds: "hayan imbuido",
		},
		Past: {
			yo: "hubiera imbuido",
			tú: "hubieras imbuido",
			Ud: "hubiera imbuido",
			nosotros: "hubiéramos imbuido",
			vosotros: "hubierais imbuido",
			Uds: "hubieran imbuido",
		},
		Future: {
			yo: "hubiere imbuido",
			tú: "hubieres imbuido",
			Ud: "hubiere imbuido",
			nosotros: "hubiéremos imbuido",
			vosotros: "hubiereis imbuido",
			Uds: "hubieren imbuido",
		},
	},
}
