var impeler = {
	Indicative: {
		Present: {
			yo: "impelo",
			tú: "impeles",
			Ud: "impele",
			nosotros: "impelemos",
			vosotros: "impeléis",
			Uds: "impelen",
		},
		Preterite: {
			yo: "impelí",
			tú: "impeliste",
			Ud: "impelió",
			nosotros: "impelimos",
			vosotros: "impelisteis",
			Uds: "impelieron",
		},
		Imperfect: {
			yo: "impelía",
			tú: "impelías",
			Ud: "impelía",
			nosotros: "impelíamos",
			vosotros: "impelíais",
			Uds: "impelían",
		},
		Conditional: {
			yo: "impelería",
			tú: "impelerías",
			Ud: "impelería",
			nosotros: "impeleríamos",
			vosotros: "impeleríais",
			Uds: "impelerían",
		},
		Future: {
			yo: "impeleré",
			tú: "impelerás",
			Ud: "impelerá",
			nosotros: "impeleremos",
			vosotros: "impeleréis",
			Uds: "impelerán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "impela",
			tú: "impelas",
			Ud: "impela",
			nosotros: "impelamos",
			vosotros: "impeláis",
			Uds: "impelan",
		},
		Imperfect: {
			yo: "impeliera",
			tú: "impelieras",
			Ud: "impeliera",
			nosotros: "impeliéramos",
			vosotros: "impelierais",
			Uds: "impelieran",
		},
		Imperfect2: {
			yo: "impeliese",
			tú: "impelieses",
			Ud: "impeliese",
			nosotros: "impeliésemos",
			vosotros: "impelieseis",
			Uds: "impeliesen",
		},
		Future: {
			yo: "impeliere",
			tú: "impelieres",
			Ud: "impeliere",
			nosotros: "impeliéremos",
			vosotros: "impeliereis",
			Uds: "impelieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "impele",
			Ud: "impela",
			nosotros: "impelamos",
			vosotros: "impeled",
			Uds: "impelan",
		},
		Negative: {
			tú: "no impelas",
			Ud: "no impela",
			nosotros: "no impelamos",
			vosotros: "no impeláis",
			Uds: "no impelan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy impeliendo",
			tú: "estás impeliendo",
			Ud: "está impeliendo",
			nosotros: "estamos impeliendo",
			vosotros: "estáis impeliendo",
			Uds: "están impeliendo",
		},
		Preterite: {
			yo: "estuve impeliendo",
			tú: "estuviste impeliendo",
			Ud: "estuvo impeliendo",
			nosotros: "estuvimos impeliendo",
			vosotros: "estuvisteis impeliendo",
			Uds: "estuvieron impeliendo",
		},
		Imperfect: {
			Uds: "estaban impeliendo",
			yo: "estaba impeliendo",
			tú: "estabas impeliendo",
			Ud: "estaba impeliendo",
			nosotros: "estábamos impeliendo",
			vosotros: "estabais impeliendo",
		},
		Conditional: {
			yo: "estaría impeliendo",
			tú: "estarías impeliendo",
			Ud: "estaría impeliendo",
			nosotros: "estaríamos impeliendo",
			vosotros: "estaríais impeliendo",
			Uds: "estarían impeliendo",
		},
		Future: {
			yo: "estaré impeliendo",
			tú: "estarás impeliendo",
			Ud: "estará impeliendo",
			nosotros: "estaremos impeliendo",
			vosotros: "estaréis impeliendo",
			Uds: "estarán impeliendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he impelido",
			tú: "has impelido",
			Ud: "ha impelido",
			nosotros: "hemos impelido",
			vosotros: "habéis impelido",
			Uds: "han impelido",
		},
		Preterite: {
			yo: "hube impelido",
			tú: "hubiste impelido",
			Ud: "hubo impelido",
			nosotros: "hubimos impelido",
			vosotros: "hubisteis impelido",
			Uds: "hubieron impelido",
		},
		Past: {
			yo: "había impelido",
			tú: "habías impelido",
			Ud: "había impelido",
			nosotros: "habíamos impelido",
			vosotros: "habíais impelido",
			Uds: "habían impelido",
		},
		Conditional: {
			yo: "habría impelido",
			tú: "habrías impelido",
			Ud: "habría impelido",
			nosotros: "habríamos impelido",
			vosotros: "habríais impelido",
			Uds: "habrían impelido",
		},
		Future: {
			yo: "habré impelido",
			tú: "habrás impelido",
			Ud: "habrá impelido",
			nosotros: "habremos impelido",
			vosotros: "habréis impelido",
			Uds: "habrán impelido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya impelido",
			tú: "hayas impelido",
			Ud: "haya impelido",
			nosotros: "hayamos impelido",
			vosotros: "hayáis impelido",
			Uds: "hayan impelido",
		},
		Past: {
			yo: "hubiera impelido",
			tú: "hubieras impelido",
			Ud: "hubiera impelido",
			nosotros: "hubiéramos impelido",
			vosotros: "hubierais impelido",
			Uds: "hubieran impelido",
		},
		Future: {
			yo: "hubiere impelido",
			tú: "hubieres impelido",
			Ud: "hubiere impelido",
			nosotros: "hubiéremos impelido",
			vosotros: "hubiereis impelido",
			Uds: "hubieren impelido",
		},
	},
}
