var imperar = {
	Indicative: {
		Present: {
			yo: "impero",
			tú: "imperas",
			Ud: "impera",
			nosotros: "imperamos",
			vosotros: "imperáis",
			Uds: "imperan",
		},
		Preterite: {
			yo: "imperé",
			tú: "imperaste",
			Ud: "imperó",
			nosotros: "imperamos",
			vosotros: "imperasteis",
			Uds: "imperaron",
		},
		Imperfect: {
			yo: "imperaba",
			tú: "imperabas",
			Ud: "imperaba",
			nosotros: "imperábamos",
			vosotros: "imperabais",
			Uds: "imperaban",
		},
		Conditional: {
			yo: "imperaría",
			tú: "imperarías",
			Ud: "imperaría",
			nosotros: "imperaríamos",
			vosotros: "imperaríais",
			Uds: "imperarían",
		},
		Future: {
			yo: "imperaré",
			tú: "imperarás",
			Ud: "imperará",
			nosotros: "imperaremos",
			vosotros: "imperaréis",
			Uds: "imperarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "impere",
			tú: "imperes",
			Ud: "impere",
			nosotros: "imperemos",
			vosotros: "imperéis",
			Uds: "imperen",
		},
		Imperfect: {
			yo: "imperara",
			tú: "imperaras",
			Ud: "imperara",
			nosotros: "imperáramos",
			vosotros: "imperarais",
			Uds: "imperaran",
		},
		Imperfect2: {
			yo: "imperase",
			tú: "imperases",
			Ud: "imperase",
			nosotros: "imperásemos",
			vosotros: "imperaseis",
			Uds: "imperasen",
		},
		Future: {
			yo: "imperare",
			tú: "imperares",
			Ud: "imperare",
			nosotros: "imperáremos",
			vosotros: "imperareis",
			Uds: "imperaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "impera",
			Ud: "impere",
			nosotros: "imperemos",
			vosotros: "imperad",
			Uds: "imperen",
		},
		Negative: {
			tú: "no imperes",
			Ud: "no impere",
			nosotros: "no imperemos",
			vosotros: "no imperéis",
			Uds: "no imperen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy imperando",
			tú: "estás imperando",
			Ud: "está imperando",
			nosotros: "estamos imperando",
			vosotros: "estáis imperando",
			Uds: "están imperando",
		},
		Preterite: {
			yo: "estuve imperando",
			tú: "estuviste imperando",
			Ud: "estuvo imperando",
			nosotros: "estuvimos imperando",
			vosotros: "estuvisteis imperando",
			Uds: "estuvieron imperando",
		},
		Imperfect: {
			Uds: "estaban imperando",
			yo: "estaba imperando",
			tú: "estabas imperando",
			Ud: "estaba imperando",
			nosotros: "estábamos imperando",
			vosotros: "estabais imperando",
		},
		Conditional: {
			yo: "estaría imperando",
			tú: "estarías imperando",
			Ud: "estaría imperando",
			nosotros: "estaríamos imperando",
			vosotros: "estaríais imperando",
			Uds: "estarían imperando",
		},
		Future: {
			yo: "estaré imperando",
			tú: "estarás imperando",
			Ud: "estará imperando",
			nosotros: "estaremos imperando",
			vosotros: "estaréis imperando",
			Uds: "estarán imperando",
		},
	},
	Perfect: {
		Present: {
			yo: "he imperado",
			tú: "has imperado",
			Ud: "ha imperado",
			nosotros: "hemos imperado",
			vosotros: "habéis imperado",
			Uds: "han imperado",
		},
		Preterite: {
			yo: "hube imperado",
			tú: "hubiste imperado",
			Ud: "hubo imperado",
			nosotros: "hubimos imperado",
			vosotros: "hubisteis imperado",
			Uds: "hubieron imperado",
		},
		Past: {
			yo: "había imperado",
			tú: "habías imperado",
			Ud: "había imperado",
			nosotros: "habíamos imperado",
			vosotros: "habíais imperado",
			Uds: "habían imperado",
		},
		Conditional: {
			yo: "habría imperado",
			tú: "habrías imperado",
			Ud: "habría imperado",
			nosotros: "habríamos imperado",
			vosotros: "habríais imperado",
			Uds: "habrían imperado",
		},
		Future: {
			yo: "habré imperado",
			tú: "habrás imperado",
			Ud: "habrá imperado",
			nosotros: "habremos imperado",
			vosotros: "habréis imperado",
			Uds: "habrán imperado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya imperado",
			tú: "hayas imperado",
			Ud: "haya imperado",
			nosotros: "hayamos imperado",
			vosotros: "hayáis imperado",
			Uds: "hayan imperado",
		},
		Past: {
			yo: "hubiera imperado",
			tú: "hubieras imperado",
			Ud: "hubiera imperado",
			nosotros: "hubiéramos imperado",
			vosotros: "hubierais imperado",
			Uds: "hubieran imperado",
		},
		Future: {
			yo: "hubiere imperado",
			tú: "hubieres imperado",
			Ud: "hubiere imperado",
			nosotros: "hubiéremos imperado",
			vosotros: "hubiereis imperado",
			Uds: "hubieren imperado",
		},
	},
}
