var implorar = {
	Indicative: {
		Present: {
			yo: "imploro",
			tú: "imploras",
			Ud: "implora",
			nosotros: "imploramos",
			vosotros: "imploráis",
			Uds: "imploran",
		},
		Preterite: {
			yo: "imploré",
			tú: "imploraste",
			Ud: "imploró",
			nosotros: "imploramos",
			vosotros: "implorasteis",
			Uds: "imploraron",
		},
		Imperfect: {
			yo: "imploraba",
			tú: "implorabas",
			Ud: "imploraba",
			nosotros: "implorábamos",
			vosotros: "implorabais",
			Uds: "imploraban",
		},
		Conditional: {
			yo: "imploraría",
			tú: "implorarías",
			Ud: "imploraría",
			nosotros: "imploraríamos",
			vosotros: "imploraríais",
			Uds: "implorarían",
		},
		Future: {
			yo: "imploraré",
			tú: "implorarás",
			Ud: "implorará",
			nosotros: "imploraremos",
			vosotros: "imploraréis",
			Uds: "implorarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "implore",
			tú: "implores",
			Ud: "implore",
			nosotros: "imploremos",
			vosotros: "imploréis",
			Uds: "imploren",
		},
		Imperfect: {
			yo: "implorara",
			tú: "imploraras",
			Ud: "implorara",
			nosotros: "imploráramos",
			vosotros: "implorarais",
			Uds: "imploraran",
		},
		Imperfect2: {
			yo: "implorase",
			tú: "implorases",
			Ud: "implorase",
			nosotros: "implorásemos",
			vosotros: "imploraseis",
			Uds: "implorasen",
		},
		Future: {
			yo: "implorare",
			tú: "implorares",
			Ud: "implorare",
			nosotros: "imploráremos",
			vosotros: "implorareis",
			Uds: "imploraren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "implora",
			Ud: "implore",
			nosotros: "imploremos",
			vosotros: "implorad",
			Uds: "imploren",
		},
		Negative: {
			tú: "no implores",
			Ud: "no implore",
			nosotros: "no imploremos",
			vosotros: "no imploréis",
			Uds: "no imploren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy implorando",
			tú: "estás implorando",
			Ud: "está implorando",
			nosotros: "estamos implorando",
			vosotros: "estáis implorando",
			Uds: "están implorando",
		},
		Preterite: {
			yo: "estuve implorando",
			tú: "estuviste implorando",
			Ud: "estuvo implorando",
			nosotros: "estuvimos implorando",
			vosotros: "estuvisteis implorando",
			Uds: "estuvieron implorando",
		},
		Imperfect: {
			Uds: "estaban implorando",
			yo: "estaba implorando",
			tú: "estabas implorando",
			Ud: "estaba implorando",
			nosotros: "estábamos implorando",
			vosotros: "estabais implorando",
		},
		Conditional: {
			yo: "estaría implorando",
			tú: "estarías implorando",
			Ud: "estaría implorando",
			nosotros: "estaríamos implorando",
			vosotros: "estaríais implorando",
			Uds: "estarían implorando",
		},
		Future: {
			yo: "estaré implorando",
			tú: "estarás implorando",
			Ud: "estará implorando",
			nosotros: "estaremos implorando",
			vosotros: "estaréis implorando",
			Uds: "estarán implorando",
		},
	},
	Perfect: {
		Present: {
			yo: "he implorado",
			tú: "has implorado",
			Ud: "ha implorado",
			nosotros: "hemos implorado",
			vosotros: "habéis implorado",
			Uds: "han implorado",
		},
		Preterite: {
			yo: "hube implorado",
			tú: "hubiste implorado",
			Ud: "hubo implorado",
			nosotros: "hubimos implorado",
			vosotros: "hubisteis implorado",
			Uds: "hubieron implorado",
		},
		Past: {
			yo: "había implorado",
			tú: "habías implorado",
			Ud: "había implorado",
			nosotros: "habíamos implorado",
			vosotros: "habíais implorado",
			Uds: "habían implorado",
		},
		Conditional: {
			yo: "habría implorado",
			tú: "habrías implorado",
			Ud: "habría implorado",
			nosotros: "habríamos implorado",
			vosotros: "habríais implorado",
			Uds: "habrían implorado",
		},
		Future: {
			yo: "habré implorado",
			tú: "habrás implorado",
			Ud: "habrá implorado",
			nosotros: "habremos implorado",
			vosotros: "habréis implorado",
			Uds: "habrán implorado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya implorado",
			tú: "hayas implorado",
			Ud: "haya implorado",
			nosotros: "hayamos implorado",
			vosotros: "hayáis implorado",
			Uds: "hayan implorado",
		},
		Past: {
			yo: "hubiera implorado",
			tú: "hubieras implorado",
			Ud: "hubiera implorado",
			nosotros: "hubiéramos implorado",
			vosotros: "hubierais implorado",
			Uds: "hubieran implorado",
		},
		Future: {
			yo: "hubiere implorado",
			tú: "hubieres implorado",
			Ud: "hubiere implorado",
			nosotros: "hubiéremos implorado",
			vosotros: "hubiereis implorado",
			Uds: "hubieren implorado",
		},
	},
}
