var implicar = {
	Indicative: {
		Present: {
			yo: "implico",
			tú: "implicas",
			Ud: "implica",
			nosotros: "implicamos",
			vosotros: "implicáis",
			Uds: "implican",
		},
		Preterite: {
			yo: "impliqué",
			tú: "implicaste",
			Ud: "implicó",
			nosotros: "implicamos",
			vosotros: "implicasteis",
			Uds: "implicaron",
		},
		Imperfect: {
			yo: "implicaba",
			tú: "implicabas",
			Ud: "implicaba",
			nosotros: "implicábamos",
			vosotros: "implicabais",
			Uds: "implicaban",
		},
		Conditional: {
			yo: "implicaría",
			tú: "implicarías",
			Ud: "implicaría",
			nosotros: "implicaríamos",
			vosotros: "implicaríais",
			Uds: "implicarían",
		},
		Future: {
			yo: "implicaré",
			tú: "implicarás",
			Ud: "implicará",
			nosotros: "implicaremos",
			vosotros: "implicaréis",
			Uds: "implicarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "implique",
			tú: "impliques",
			Ud: "implique",
			nosotros: "impliquemos",
			vosotros: "impliquéis",
			Uds: "impliquen",
		},
		Imperfect: {
			yo: "implicara",
			tú: "implicaras",
			Ud: "implicara",
			nosotros: "implicáramos",
			vosotros: "implicarais",
			Uds: "implicaran",
		},
		Imperfect2: {
			yo: "implicase",
			tú: "implicases",
			Ud: "implicase",
			nosotros: "implicásemos",
			vosotros: "implicaseis",
			Uds: "implicasen",
		},
		Future: {
			yo: "implicare",
			tú: "implicares",
			Ud: "implicare",
			nosotros: "implicáremos",
			vosotros: "implicareis",
			Uds: "implicaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "implica",
			Ud: "implique",
			nosotros: "impliquemos",
			vosotros: "implicad",
			Uds: "impliquen",
		},
		Negative: {
			tú: "no impliques",
			Ud: "no implique",
			nosotros: "no impliquemos",
			vosotros: "no impliquéis",
			Uds: "no impliquen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy implicando",
			tú: "estás implicando",
			Ud: "está implicando",
			nosotros: "estamos implicando",
			vosotros: "estáis implicando",
			Uds: "están implicando",
		},
		Preterite: {
			yo: "estuve implicando",
			tú: "estuviste implicando",
			Ud: "estuvo implicando",
			nosotros: "estuvimos implicando",
			vosotros: "estuvisteis implicando",
			Uds: "estuvieron implicando",
		},
		Imperfect: {
			Uds: "estaban implicando",
			yo: "estaba implicando",
			tú: "estabas implicando",
			Ud: "estaba implicando",
			nosotros: "estábamos implicando",
			vosotros: "estabais implicando",
		},
		Conditional: {
			yo: "estaría implicando",
			tú: "estarías implicando",
			Ud: "estaría implicando",
			nosotros: "estaríamos implicando",
			vosotros: "estaríais implicando",
			Uds: "estarían implicando",
		},
		Future: {
			yo: "estaré implicando",
			tú: "estarás implicando",
			Ud: "estará implicando",
			nosotros: "estaremos implicando",
			vosotros: "estaréis implicando",
			Uds: "estarán implicando",
		},
	},
	Perfect: {
		Present: {
			yo: "he implicado",
			tú: "has implicado",
			Ud: "ha implicado",
			nosotros: "hemos implicado",
			vosotros: "habéis implicado",
			Uds: "han implicado",
		},
		Preterite: {
			yo: "hube implicado",
			tú: "hubiste implicado",
			Ud: "hubo implicado",
			nosotros: "hubimos implicado",
			vosotros: "hubisteis implicado",
			Uds: "hubieron implicado",
		},
		Past: {
			yo: "había implicado",
			tú: "habías implicado",
			Ud: "había implicado",
			nosotros: "habíamos implicado",
			vosotros: "habíais implicado",
			Uds: "habían implicado",
		},
		Conditional: {
			yo: "habría implicado",
			tú: "habrías implicado",
			Ud: "habría implicado",
			nosotros: "habríamos implicado",
			vosotros: "habríais implicado",
			Uds: "habrían implicado",
		},
		Future: {
			yo: "habré implicado",
			tú: "habrás implicado",
			Ud: "habrá implicado",
			nosotros: "habremos implicado",
			vosotros: "habréis implicado",
			Uds: "habrán implicado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya implicado",
			tú: "hayas implicado",
			Ud: "haya implicado",
			nosotros: "hayamos implicado",
			vosotros: "hayáis implicado",
			Uds: "hayan implicado",
		},
		Past: {
			yo: "hubiera implicado",
			tú: "hubieras implicado",
			Ud: "hubiera implicado",
			nosotros: "hubiéramos implicado",
			vosotros: "hubierais implicado",
			Uds: "hubieran implicado",
		},
		Future: {
			yo: "hubiere implicado",
			tú: "hubieres implicado",
			Ud: "hubiere implicado",
			nosotros: "hubiéremos implicado",
			vosotros: "hubiereis implicado",
			Uds: "hubieren implicado",
		},
	},
}
