var imponer = {
	Indicative: {
		Present: {
			yo: "impongo",
			tú: "impones",
			Ud: "impone",
			nosotros: "imponemos",
			vosotros: "imponéis",
			Uds: "imponen",
		},
		Preterite: {
			yo: "impuse",
			tú: "impusiste",
			Ud: "impuso",
			nosotros: "impusimos",
			vosotros: "impusisteis",
			Uds: "impusieron",
		},
		Imperfect: {
			yo: "imponía",
			tú: "imponías",
			Ud: "imponía",
			nosotros: "imponíamos",
			vosotros: "imponíais",
			Uds: "imponían",
		},
		Conditional: {
			yo: "impondría",
			tú: "impondrías",
			Ud: "impondría",
			nosotros: "impondríamos",
			vosotros: "impondríais",
			Uds: "impondrían",
		},
		Future: {
			yo: "impondré",
			tú: "impondrás",
			Ud: "impondrá",
			nosotros: "impondremos",
			vosotros: "impondréis",
			Uds: "impondrán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "imponga",
			tú: "impongas",
			Ud: "imponga",
			nosotros: "impongamos",
			vosotros: "impongáis",
			Uds: "impongan",
		},
		Imperfect: {
			yo: "impusiera",
			tú: "impusieras",
			Ud: "impusiera",
			nosotros: "impusiéramos",
			vosotros: "impusierais",
			Uds: "impusieran",
		},
		Imperfect2: {
			yo: "impusiese",
			tú: "impusieses",
			Ud: "impusiese",
			nosotros: "impusiésemos",
			vosotros: "impusieseis",
			Uds: "impusiesen",
		},
		Future: {
			yo: "impusiere",
			tú: "impusieres",
			Ud: "impusiere",
			nosotros: "impusiéremos",
			vosotros: "impusiereis",
			Uds: "impusieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "impón",
			Ud: "imponga",
			nosotros: "impongamos",
			vosotros: "imponed",
			Uds: "impongan",
		},
		Negative: {
			tú: "no impongas",
			Ud: "no imponga",
			nosotros: "no impongamos",
			vosotros: "no impongáis",
			Uds: "no impongan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy imponiendo",
			tú: "estás imponiendo",
			Ud: "está imponiendo",
			nosotros: "estamos imponiendo",
			vosotros: "estáis imponiendo",
			Uds: "están imponiendo",
		},
		Preterite: {
			yo: "estuve imponiendo",
			tú: "estuviste imponiendo",
			Ud: "estuvo imponiendo",
			nosotros: "estuvimos imponiendo",
			vosotros: "estuvisteis imponiendo",
			Uds: "estuvieron imponiendo",
		},
		Imperfect: {
			Uds: "estaban imponiendo",
			yo: "estaba imponiendo",
			tú: "estabas imponiendo",
			Ud: "estaba imponiendo",
			nosotros: "estábamos imponiendo",
			vosotros: "estabais imponiendo",
		},
		Conditional: {
			yo: "estaría imponiendo",
			tú: "estarías imponiendo",
			Ud: "estaría imponiendo",
			nosotros: "estaríamos imponiendo",
			vosotros: "estaríais imponiendo",
			Uds: "estarían imponiendo",
		},
		Future: {
			yo: "estaré imponiendo",
			tú: "estarás imponiendo",
			Ud: "estará imponiendo",
			nosotros: "estaremos imponiendo",
			vosotros: "estaréis imponiendo",
			Uds: "estarán imponiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he impuesto",
			tú: "has impuesto",
			Ud: "ha impuesto",
			nosotros: "hemos impuesto",
			vosotros: "habéis impuesto",
			Uds: "han impuesto",
		},
		Preterite: {
			yo: "hube impuesto",
			tú: "hubiste impuesto",
			Ud: "hubo impuesto",
			nosotros: "hubimos impuesto",
			vosotros: "hubisteis impuesto",
			Uds: "hubieron impuesto",
		},
		Past: {
			yo: "había impuesto",
			tú: "habías impuesto",
			Ud: "había impuesto",
			nosotros: "habíamos impuesto",
			vosotros: "habíais impuesto",
			Uds: "habían impuesto",
		},
		Conditional: {
			yo: "habría impuesto",
			tú: "habrías impuesto",
			Ud: "habría impuesto",
			nosotros: "habríamos impuesto",
			vosotros: "habríais impuesto",
			Uds: "habrían impuesto",
		},
		Future: {
			yo: "habré impuesto",
			tú: "habrás impuesto",
			Ud: "habrá impuesto",
			nosotros: "habremos impuesto",
			vosotros: "habréis impuesto",
			Uds: "habrán impuesto",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya impuesto",
			tú: "hayas impuesto",
			Ud: "haya impuesto",
			nosotros: "hayamos impuesto",
			vosotros: "hayáis impuesto",
			Uds: "hayan impuesto",
		},
		Past: {
			yo: "hubiera impuesto",
			tú: "hubieras impuesto",
			Ud: "hubiera impuesto",
			nosotros: "hubiéramos impuesto",
			vosotros: "hubierais impuesto",
			Uds: "hubieran impuesto",
		},
		Future: {
			yo: "hubiere impuesto",
			tú: "hubieres impuesto",
			Ud: "hubiere impuesto",
			nosotros: "hubiéremos impuesto",
			vosotros: "hubiereis impuesto",
			Uds: "hubieren impuesto",
		},
	},
}
