var impresionar = {
	Indicative: {
		Present: {
			yo: "impresiono",
			tú: "impresionas",
			Ud: "impresiona",
			nosotros: "impresionamos",
			vosotros: "impresionáis",
			Uds: "impresionan",
		},
		Preterite: {
			yo: "impresioné",
			tú: "impresionaste",
			Ud: "impresionó",
			nosotros: "impresionamos",
			vosotros: "impresionasteis",
			Uds: "impresionaron",
		},
		Imperfect: {
			yo: "impresionaba",
			tú: "impresionabas",
			Ud: "impresionaba",
			nosotros: "impresionábamos",
			vosotros: "impresionabais",
			Uds: "impresionaban",
		},
		Conditional: {
			yo: "impresionaría",
			tú: "impresionarías",
			Ud: "impresionaría",
			nosotros: "impresionaríamos",
			vosotros: "impresionaríais",
			Uds: "impresionarían",
		},
		Future: {
			yo: "impresionaré",
			tú: "impresionarás",
			Ud: "impresionará",
			nosotros: "impresionaremos",
			vosotros: "impresionaréis",
			Uds: "impresionarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "impresione",
			tú: "impresiones",
			Ud: "impresione",
			nosotros: "impresionemos",
			vosotros: "impresionéis",
			Uds: "impresionen",
		},
		Imperfect: {
			yo: "impresionara",
			tú: "impresionaras",
			Ud: "impresionara",
			nosotros: "impresionáramos",
			vosotros: "impresionarais",
			Uds: "impresionaran",
		},
		Imperfect2: {
			yo: "impresionase",
			tú: "impresionases",
			Ud: "impresionase",
			nosotros: "impresionásemos",
			vosotros: "impresionaseis",
			Uds: "impresionasen",
		},
		Future: {
			yo: "impresionare",
			tú: "impresionares",
			Ud: "impresionare",
			nosotros: "impresionáremos",
			vosotros: "impresionareis",
			Uds: "impresionaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "impresiona",
			Ud: "impresione",
			nosotros: "impresionemos",
			vosotros: "impresionad",
			Uds: "impresionen",
		},
		Negative: {
			tú: "no impresiones",
			Ud: "no impresione",
			nosotros: "no impresionemos",
			vosotros: "no impresionéis",
			Uds: "no impresionen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy impresionando",
			tú: "estás impresionando",
			Ud: "está impresionando",
			nosotros: "estamos impresionando",
			vosotros: "estáis impresionando",
			Uds: "están impresionando",
		},
		Preterite: {
			yo: "estuve impresionando",
			tú: "estuviste impresionando",
			Ud: "estuvo impresionando",
			nosotros: "estuvimos impresionando",
			vosotros: "estuvisteis impresionando",
			Uds: "estuvieron impresionando",
		},
		Imperfect: {
			Uds: "estaban impresionando",
			yo: "estaba impresionando",
			tú: "estabas impresionando",
			Ud: "estaba impresionando",
			nosotros: "estábamos impresionando",
			vosotros: "estabais impresionando",
		},
		Conditional: {
			yo: "estaría impresionando",
			tú: "estarías impresionando",
			Ud: "estaría impresionando",
			nosotros: "estaríamos impresionando",
			vosotros: "estaríais impresionando",
			Uds: "estarían impresionando",
		},
		Future: {
			yo: "estaré impresionando",
			tú: "estarás impresionando",
			Ud: "estará impresionando",
			nosotros: "estaremos impresionando",
			vosotros: "estaréis impresionando",
			Uds: "estarán impresionando",
		},
	},
	Perfect: {
		Present: {
			yo: "he impresionado",
			tú: "has impresionado",
			Ud: "ha impresionado",
			nosotros: "hemos impresionado",
			vosotros: "habéis impresionado",
			Uds: "han impresionado",
		},
		Preterite: {
			yo: "hube impresionado",
			tú: "hubiste impresionado",
			Ud: "hubo impresionado",
			nosotros: "hubimos impresionado",
			vosotros: "hubisteis impresionado",
			Uds: "hubieron impresionado",
		},
		Past: {
			yo: "había impresionado",
			tú: "habías impresionado",
			Ud: "había impresionado",
			nosotros: "habíamos impresionado",
			vosotros: "habíais impresionado",
			Uds: "habían impresionado",
		},
		Conditional: {
			yo: "habría impresionado",
			tú: "habrías impresionado",
			Ud: "habría impresionado",
			nosotros: "habríamos impresionado",
			vosotros: "habríais impresionado",
			Uds: "habrían impresionado",
		},
		Future: {
			yo: "habré impresionado",
			tú: "habrás impresionado",
			Ud: "habrá impresionado",
			nosotros: "habremos impresionado",
			vosotros: "habréis impresionado",
			Uds: "habrán impresionado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya impresionado",
			tú: "hayas impresionado",
			Ud: "haya impresionado",
			nosotros: "hayamos impresionado",
			vosotros: "hayáis impresionado",
			Uds: "hayan impresionado",
		},
		Past: {
			yo: "hubiera impresionado",
			tú: "hubieras impresionado",
			Ud: "hubiera impresionado",
			nosotros: "hubiéramos impresionado",
			vosotros: "hubierais impresionado",
			Uds: "hubieran impresionado",
		},
		Future: {
			yo: "hubiere impresionado",
			tú: "hubieres impresionado",
			Ud: "hubiere impresionado",
			nosotros: "hubiéremos impresionado",
			vosotros: "hubiereis impresionado",
			Uds: "hubieren impresionado",
		},
	},
}
