var impugnar = {
	Indicative: {
		Present: {
			yo: "impugno",
			tú: "impugnas",
			Ud: "impugna",
			nosotros: "impugnamos",
			vosotros: "impugnáis",
			Uds: "impugnan",
		},
		Preterite: {
			yo: "impugné",
			tú: "impugnaste",
			Ud: "impugnó",
			nosotros: "impugnamos",
			vosotros: "impugnasteis",
			Uds: "impugnaron",
		},
		Imperfect: {
			yo: "impugnaba",
			tú: "impugnabas",
			Ud: "impugnaba",
			nosotros: "impugnábamos",
			vosotros: "impugnabais",
			Uds: "impugnaban",
		},
		Conditional: {
			yo: "impugnaría",
			tú: "impugnarías",
			Ud: "impugnaría",
			nosotros: "impugnaríamos",
			vosotros: "impugnaríais",
			Uds: "impugnarían",
		},
		Future: {
			yo: "impugnaré",
			tú: "impugnarás",
			Ud: "impugnará",
			nosotros: "impugnaremos",
			vosotros: "impugnaréis",
			Uds: "impugnarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "impugne",
			tú: "impugnes",
			Ud: "impugne",
			nosotros: "impugnemos",
			vosotros: "impugnéis",
			Uds: "impugnen",
		},
		Imperfect: {
			yo: "impugnara",
			tú: "impugnaras",
			Ud: "impugnara",
			nosotros: "impugnáramos",
			vosotros: "impugnarais",
			Uds: "impugnaran",
		},
		Imperfect2: {
			yo: "impugnase",
			tú: "impugnases",
			Ud: "impugnase",
			nosotros: "impugnásemos",
			vosotros: "impugnaseis",
			Uds: "impugnasen",
		},
		Future: {
			yo: "impugnare",
			tú: "impugnares",
			Ud: "impugnare",
			nosotros: "impugnáremos",
			vosotros: "impugnareis",
			Uds: "impugnaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "impugna",
			Ud: "impugne",
			nosotros: "impugnemos",
			vosotros: "impugnad",
			Uds: "impugnen",
		},
		Negative: {
			tú: "no impugnes",
			Ud: "no impugne",
			nosotros: "no impugnemos",
			vosotros: "no impugnéis",
			Uds: "no impugnen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy impugnando",
			tú: "estás impugnando",
			Ud: "está impugnando",
			nosotros: "estamos impugnando",
			vosotros: "estáis impugnando",
			Uds: "están impugnando",
		},
		Preterite: {
			yo: "estuve impugnando",
			tú: "estuviste impugnando",
			Ud: "estuvo impugnando",
			nosotros: "estuvimos impugnando",
			vosotros: "estuvisteis impugnando",
			Uds: "estuvieron impugnando",
		},
		Imperfect: {
			Uds: "estaban impugnando",
			yo: "estaba impugnando",
			tú: "estabas impugnando",
			Ud: "estaba impugnando",
			nosotros: "estábamos impugnando",
			vosotros: "estabais impugnando",
		},
		Conditional: {
			yo: "estaría impugnando",
			tú: "estarías impugnando",
			Ud: "estaría impugnando",
			nosotros: "estaríamos impugnando",
			vosotros: "estaríais impugnando",
			Uds: "estarían impugnando",
		},
		Future: {
			yo: "estaré impugnando",
			tú: "estarás impugnando",
			Ud: "estará impugnando",
			nosotros: "estaremos impugnando",
			vosotros: "estaréis impugnando",
			Uds: "estarán impugnando",
		},
	},
	Perfect: {
		Present: {
			yo: "he impugnado",
			tú: "has impugnado",
			Ud: "ha impugnado",
			nosotros: "hemos impugnado",
			vosotros: "habéis impugnado",
			Uds: "han impugnado",
		},
		Preterite: {
			yo: "hube impugnado",
			tú: "hubiste impugnado",
			Ud: "hubo impugnado",
			nosotros: "hubimos impugnado",
			vosotros: "hubisteis impugnado",
			Uds: "hubieron impugnado",
		},
		Past: {
			yo: "había impugnado",
			tú: "habías impugnado",
			Ud: "había impugnado",
			nosotros: "habíamos impugnado",
			vosotros: "habíais impugnado",
			Uds: "habían impugnado",
		},
		Conditional: {
			yo: "habría impugnado",
			tú: "habrías impugnado",
			Ud: "habría impugnado",
			nosotros: "habríamos impugnado",
			vosotros: "habríais impugnado",
			Uds: "habrían impugnado",
		},
		Future: {
			yo: "habré impugnado",
			tú: "habrás impugnado",
			Ud: "habrá impugnado",
			nosotros: "habremos impugnado",
			vosotros: "habréis impugnado",
			Uds: "habrán impugnado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya impugnado",
			tú: "hayas impugnado",
			Ud: "haya impugnado",
			nosotros: "hayamos impugnado",
			vosotros: "hayáis impugnado",
			Uds: "hayan impugnado",
		},
		Past: {
			yo: "hubiera impugnado",
			tú: "hubieras impugnado",
			Ud: "hubiera impugnado",
			nosotros: "hubiéramos impugnado",
			vosotros: "hubierais impugnado",
			Uds: "hubieran impugnado",
		},
		Future: {
			yo: "hubiere impugnado",
			tú: "hubieres impugnado",
			Ud: "hubiere impugnado",
			nosotros: "hubiéremos impugnado",
			vosotros: "hubiereis impugnado",
			Uds: "hubieren impugnado",
		},
	},
}
