var inaugurar = {
	Indicative: {
		Present: {
			yo: "inauguro",
			tú: "inauguras",
			Ud: "inaugura",
			nosotros: "inauguramos",
			vosotros: "inauguráis",
			Uds: "inauguran",
		},
		Preterite: {
			yo: "inauguré",
			tú: "inauguraste",
			Ud: "inauguró",
			nosotros: "inauguramos",
			vosotros: "inaugurasteis",
			Uds: "inauguraron",
		},
		Imperfect: {
			yo: "inauguraba",
			tú: "inaugurabas",
			Ud: "inauguraba",
			nosotros: "inaugurábamos",
			vosotros: "inaugurabais",
			Uds: "inauguraban",
		},
		Conditional: {
			yo: "inauguraría",
			tú: "inaugurarías",
			Ud: "inauguraría",
			nosotros: "inauguraríamos",
			vosotros: "inauguraríais",
			Uds: "inaugurarían",
		},
		Future: {
			yo: "inauguraré",
			tú: "inaugurarás",
			Ud: "inaugurará",
			nosotros: "inauguraremos",
			vosotros: "inauguraréis",
			Uds: "inaugurarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "inaugure",
			tú: "inaugures",
			Ud: "inaugure",
			nosotros: "inauguremos",
			vosotros: "inauguréis",
			Uds: "inauguren",
		},
		Imperfect: {
			yo: "inaugurara",
			tú: "inauguraras",
			Ud: "inaugurara",
			nosotros: "inauguráramos",
			vosotros: "inaugurarais",
			Uds: "inauguraran",
		},
		Imperfect2: {
			yo: "inaugurase",
			tú: "inaugurases",
			Ud: "inaugurase",
			nosotros: "inaugurásemos",
			vosotros: "inauguraseis",
			Uds: "inaugurasen",
		},
		Future: {
			yo: "inaugurare",
			tú: "inaugurares",
			Ud: "inaugurare",
			nosotros: "inauguráremos",
			vosotros: "inaugurareis",
			Uds: "inauguraren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "inaugura",
			Ud: "inaugure",
			nosotros: "inauguremos",
			vosotros: "inaugurad",
			Uds: "inauguren",
		},
		Negative: {
			tú: "no inaugures",
			Ud: "no inaugure",
			nosotros: "no inauguremos",
			vosotros: "no inauguréis",
			Uds: "no inauguren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy inaugurando",
			tú: "estás inaugurando",
			Ud: "está inaugurando",
			nosotros: "estamos inaugurando",
			vosotros: "estáis inaugurando",
			Uds: "están inaugurando",
		},
		Preterite: {
			yo: "estuve inaugurando",
			tú: "estuviste inaugurando",
			Ud: "estuvo inaugurando",
			nosotros: "estuvimos inaugurando",
			vosotros: "estuvisteis inaugurando",
			Uds: "estuvieron inaugurando",
		},
		Imperfect: {
			Uds: "estaban inaugurando",
			yo: "estaba inaugurando",
			tú: "estabas inaugurando",
			Ud: "estaba inaugurando",
			nosotros: "estábamos inaugurando",
			vosotros: "estabais inaugurando",
		},
		Conditional: {
			yo: "estaría inaugurando",
			tú: "estarías inaugurando",
			Ud: "estaría inaugurando",
			nosotros: "estaríamos inaugurando",
			vosotros: "estaríais inaugurando",
			Uds: "estarían inaugurando",
		},
		Future: {
			yo: "estaré inaugurando",
			tú: "estarás inaugurando",
			Ud: "estará inaugurando",
			nosotros: "estaremos inaugurando",
			vosotros: "estaréis inaugurando",
			Uds: "estarán inaugurando",
		},
	},
	Perfect: {
		Present: {
			yo: "he inaugurado",
			tú: "has inaugurado",
			Ud: "ha inaugurado",
			nosotros: "hemos inaugurado",
			vosotros: "habéis inaugurado",
			Uds: "han inaugurado",
		},
		Preterite: {
			yo: "hube inaugurado",
			tú: "hubiste inaugurado",
			Ud: "hubo inaugurado",
			nosotros: "hubimos inaugurado",
			vosotros: "hubisteis inaugurado",
			Uds: "hubieron inaugurado",
		},
		Past: {
			yo: "había inaugurado",
			tú: "habías inaugurado",
			Ud: "había inaugurado",
			nosotros: "habíamos inaugurado",
			vosotros: "habíais inaugurado",
			Uds: "habían inaugurado",
		},
		Conditional: {
			yo: "habría inaugurado",
			tú: "habrías inaugurado",
			Ud: "habría inaugurado",
			nosotros: "habríamos inaugurado",
			vosotros: "habríais inaugurado",
			Uds: "habrían inaugurado",
		},
		Future: {
			yo: "habré inaugurado",
			tú: "habrás inaugurado",
			Ud: "habrá inaugurado",
			nosotros: "habremos inaugurado",
			vosotros: "habréis inaugurado",
			Uds: "habrán inaugurado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya inaugurado",
			tú: "hayas inaugurado",
			Ud: "haya inaugurado",
			nosotros: "hayamos inaugurado",
			vosotros: "hayáis inaugurado",
			Uds: "hayan inaugurado",
		},
		Past: {
			yo: "hubiera inaugurado",
			tú: "hubieras inaugurado",
			Ud: "hubiera inaugurado",
			nosotros: "hubiéramos inaugurado",
			vosotros: "hubierais inaugurado",
			Uds: "hubieran inaugurado",
		},
		Future: {
			yo: "hubiere inaugurado",
			tú: "hubieres inaugurado",
			Ud: "hubiere inaugurado",
			nosotros: "hubiéremos inaugurado",
			vosotros: "hubiereis inaugurado",
			Uds: "hubieren inaugurado",
		},
	},
}
