var incitar = {
	Indicative: {
		Present: {
			yo: "incito",
			tú: "incitas",
			Ud: "incita",
			nosotros: "incitamos",
			vosotros: "incitáis",
			Uds: "incitan",
		},
		Preterite: {
			yo: "incité",
			tú: "incitaste",
			Ud: "incitó",
			nosotros: "incitamos",
			vosotros: "incitasteis",
			Uds: "incitaron",
		},
		Imperfect: {
			yo: "incitaba",
			tú: "incitabas",
			Ud: "incitaba",
			nosotros: "incitábamos",
			vosotros: "incitabais",
			Uds: "incitaban",
		},
		Conditional: {
			yo: "incitaría",
			tú: "incitarías",
			Ud: "incitaría",
			nosotros: "incitaríamos",
			vosotros: "incitaríais",
			Uds: "incitarían",
		},
		Future: {
			yo: "incitaré",
			tú: "incitarás",
			Ud: "incitará",
			nosotros: "incitaremos",
			vosotros: "incitaréis",
			Uds: "incitarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "incite",
			tú: "incites",
			Ud: "incite",
			nosotros: "incitemos",
			vosotros: "incitéis",
			Uds: "inciten",
		},
		Imperfect: {
			yo: "incitara",
			tú: "incitaras",
			Ud: "incitara",
			nosotros: "incitáramos",
			vosotros: "incitarais",
			Uds: "incitaran",
		},
		Imperfect2: {
			yo: "incitase",
			tú: "incitases",
			Ud: "incitase",
			nosotros: "incitásemos",
			vosotros: "incitaseis",
			Uds: "incitasen",
		},
		Future: {
			yo: "incitare",
			tú: "incitares",
			Ud: "incitare",
			nosotros: "incitáremos",
			vosotros: "incitareis",
			Uds: "incitaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "incita",
			Ud: "incite",
			nosotros: "incitemos",
			vosotros: "incitad",
			Uds: "inciten",
		},
		Negative: {
			tú: "no incites",
			Ud: "no incite",
			nosotros: "no incitemos",
			vosotros: "no incitéis",
			Uds: "no inciten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy incitando",
			tú: "estás incitando",
			Ud: "está incitando",
			nosotros: "estamos incitando",
			vosotros: "estáis incitando",
			Uds: "están incitando",
		},
		Preterite: {
			yo: "estuve incitando",
			tú: "estuviste incitando",
			Ud: "estuvo incitando",
			nosotros: "estuvimos incitando",
			vosotros: "estuvisteis incitando",
			Uds: "estuvieron incitando",
		},
		Imperfect: {
			Uds: "estaban incitando",
			yo: "estaba incitando",
			tú: "estabas incitando",
			Ud: "estaba incitando",
			nosotros: "estábamos incitando",
			vosotros: "estabais incitando",
		},
		Conditional: {
			yo: "estaría incitando",
			tú: "estarías incitando",
			Ud: "estaría incitando",
			nosotros: "estaríamos incitando",
			vosotros: "estaríais incitando",
			Uds: "estarían incitando",
		},
		Future: {
			yo: "estaré incitando",
			tú: "estarás incitando",
			Ud: "estará incitando",
			nosotros: "estaremos incitando",
			vosotros: "estaréis incitando",
			Uds: "estarán incitando",
		},
	},
	Perfect: {
		Present: {
			yo: "he incitado",
			tú: "has incitado",
			Ud: "ha incitado",
			nosotros: "hemos incitado",
			vosotros: "habéis incitado",
			Uds: "han incitado",
		},
		Preterite: {
			yo: "hube incitado",
			tú: "hubiste incitado",
			Ud: "hubo incitado",
			nosotros: "hubimos incitado",
			vosotros: "hubisteis incitado",
			Uds: "hubieron incitado",
		},
		Past: {
			yo: "había incitado",
			tú: "habías incitado",
			Ud: "había incitado",
			nosotros: "habíamos incitado",
			vosotros: "habíais incitado",
			Uds: "habían incitado",
		},
		Conditional: {
			yo: "habría incitado",
			tú: "habrías incitado",
			Ud: "habría incitado",
			nosotros: "habríamos incitado",
			vosotros: "habríais incitado",
			Uds: "habrían incitado",
		},
		Future: {
			yo: "habré incitado",
			tú: "habrás incitado",
			Ud: "habrá incitado",
			nosotros: "habremos incitado",
			vosotros: "habréis incitado",
			Uds: "habrán incitado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya incitado",
			tú: "hayas incitado",
			Ud: "haya incitado",
			nosotros: "hayamos incitado",
			vosotros: "hayáis incitado",
			Uds: "hayan incitado",
		},
		Past: {
			yo: "hubiera incitado",
			tú: "hubieras incitado",
			Ud: "hubiera incitado",
			nosotros: "hubiéramos incitado",
			vosotros: "hubierais incitado",
			Uds: "hubieran incitado",
		},
		Future: {
			yo: "hubiere incitado",
			tú: "hubieres incitado",
			Ud: "hubiere incitado",
			nosotros: "hubiéremos incitado",
			vosotros: "hubiereis incitado",
			Uds: "hubieren incitado",
		},
	},
}
