var incomodar = {
	Indicative: {
		Present: {
			yo: "incomodo",
			tú: "incomodas",
			Ud: "incomoda",
			nosotros: "incomodamos",
			vosotros: "incomodáis",
			Uds: "incomodan",
		},
		Preterite: {
			yo: "incomodé",
			tú: "incomodaste",
			Ud: "incomodó",
			nosotros: "incomodamos",
			vosotros: "incomodasteis",
			Uds: "incomodaron",
		},
		Imperfect: {
			yo: "incomodaba",
			tú: "incomodabas",
			Ud: "incomodaba",
			nosotros: "incomodábamos",
			vosotros: "incomodabais",
			Uds: "incomodaban",
		},
		Conditional: {
			yo: "incomodaría",
			tú: "incomodarías",
			Ud: "incomodaría",
			nosotros: "incomodaríamos",
			vosotros: "incomodaríais",
			Uds: "incomodarían",
		},
		Future: {
			yo: "incomodaré",
			tú: "incomodarás",
			Ud: "incomodará",
			nosotros: "incomodaremos",
			vosotros: "incomodaréis",
			Uds: "incomodarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "incomode",
			tú: "incomodes",
			Ud: "incomode",
			nosotros: "incomodemos",
			vosotros: "incomodéis",
			Uds: "incomoden",
		},
		Imperfect: {
			yo: "incomodara",
			tú: "incomodaras",
			Ud: "incomodara",
			nosotros: "incomodáramos",
			vosotros: "incomodarais",
			Uds: "incomodaran",
		},
		Imperfect2: {
			yo: "incomodase",
			tú: "incomodases",
			Ud: "incomodase",
			nosotros: "incomodásemos",
			vosotros: "incomodaseis",
			Uds: "incomodasen",
		},
		Future: {
			yo: "incomodare",
			tú: "incomodares",
			Ud: "incomodare",
			nosotros: "incomodáremos",
			vosotros: "incomodareis",
			Uds: "incomodaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "incomoda",
			Ud: "incomode",
			nosotros: "incomodemos",
			vosotros: "incomodad",
			Uds: "incomoden",
		},
		Negative: {
			tú: "no incomodes",
			Ud: "no incomode",
			nosotros: "no incomodemos",
			vosotros: "no incomodéis",
			Uds: "no incomoden",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy incomodando",
			tú: "estás incomodando",
			Ud: "está incomodando",
			nosotros: "estamos incomodando",
			vosotros: "estáis incomodando",
			Uds: "están incomodando",
		},
		Preterite: {
			yo: "estuve incomodando",
			tú: "estuviste incomodando",
			Ud: "estuvo incomodando",
			nosotros: "estuvimos incomodando",
			vosotros: "estuvisteis incomodando",
			Uds: "estuvieron incomodando",
		},
		Imperfect: {
			Uds: "estaban incomodando",
			yo: "estaba incomodando",
			tú: "estabas incomodando",
			Ud: "estaba incomodando",
			nosotros: "estábamos incomodando",
			vosotros: "estabais incomodando",
		},
		Conditional: {
			yo: "estaría incomodando",
			tú: "estarías incomodando",
			Ud: "estaría incomodando",
			nosotros: "estaríamos incomodando",
			vosotros: "estaríais incomodando",
			Uds: "estarían incomodando",
		},
		Future: {
			yo: "estaré incomodando",
			tú: "estarás incomodando",
			Ud: "estará incomodando",
			nosotros: "estaremos incomodando",
			vosotros: "estaréis incomodando",
			Uds: "estarán incomodando",
		},
	},
	Perfect: {
		Present: {
			yo: "he incomodado",
			tú: "has incomodado",
			Ud: "ha incomodado",
			nosotros: "hemos incomodado",
			vosotros: "habéis incomodado",
			Uds: "han incomodado",
		},
		Preterite: {
			yo: "hube incomodado",
			tú: "hubiste incomodado",
			Ud: "hubo incomodado",
			nosotros: "hubimos incomodado",
			vosotros: "hubisteis incomodado",
			Uds: "hubieron incomodado",
		},
		Past: {
			yo: "había incomodado",
			tú: "habías incomodado",
			Ud: "había incomodado",
			nosotros: "habíamos incomodado",
			vosotros: "habíais incomodado",
			Uds: "habían incomodado",
		},
		Conditional: {
			yo: "habría incomodado",
			tú: "habrías incomodado",
			Ud: "habría incomodado",
			nosotros: "habríamos incomodado",
			vosotros: "habríais incomodado",
			Uds: "habrían incomodado",
		},
		Future: {
			yo: "habré incomodado",
			tú: "habrás incomodado",
			Ud: "habrá incomodado",
			nosotros: "habremos incomodado",
			vosotros: "habréis incomodado",
			Uds: "habrán incomodado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya incomodado",
			tú: "hayas incomodado",
			Ud: "haya incomodado",
			nosotros: "hayamos incomodado",
			vosotros: "hayáis incomodado",
			Uds: "hayan incomodado",
		},
		Past: {
			yo: "hubiera incomodado",
			tú: "hubieras incomodado",
			Ud: "hubiera incomodado",
			nosotros: "hubiéramos incomodado",
			vosotros: "hubierais incomodado",
			Uds: "hubieran incomodado",
		},
		Future: {
			yo: "hubiere incomodado",
			tú: "hubieres incomodado",
			Ud: "hubiere incomodado",
			nosotros: "hubiéremos incomodado",
			vosotros: "hubiereis incomodado",
			Uds: "hubieren incomodado",
		},
	},
}
