var incrementar = {
	Indicative: {
		Present: {
			yo: "incremento",
			tú: "incrementas",
			Ud: "incrementa",
			nosotros: "incrementamos",
			vosotros: "incrementáis",
			Uds: "incrementan",
		},
		Preterite: {
			yo: "incrementé",
			tú: "incrementaste",
			Ud: "incrementó",
			nosotros: "incrementamos",
			vosotros: "incrementasteis",
			Uds: "incrementaron",
		},
		Imperfect: {
			yo: "incrementaba",
			tú: "incrementabas",
			Ud: "incrementaba",
			nosotros: "incrementábamos",
			vosotros: "incrementabais",
			Uds: "incrementaban",
		},
		Conditional: {
			yo: "incrementaría",
			tú: "incrementarías",
			Ud: "incrementaría",
			nosotros: "incrementaríamos",
			vosotros: "incrementaríais",
			Uds: "incrementarían",
		},
		Future: {
			yo: "incrementaré",
			tú: "incrementarás",
			Ud: "incrementará",
			nosotros: "incrementaremos",
			vosotros: "incrementaréis",
			Uds: "incrementarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "incremente",
			tú: "incrementes",
			Ud: "incremente",
			nosotros: "incrementemos",
			vosotros: "incrementéis",
			Uds: "incrementen",
		},
		Imperfect: {
			yo: "incrementara",
			tú: "incrementaras",
			Ud: "incrementara",
			nosotros: "incrementáramos",
			vosotros: "incrementarais",
			Uds: "incrementaran",
		},
		Imperfect2: {
			yo: "incrementase",
			tú: "incrementases",
			Ud: "incrementase",
			nosotros: "incrementásemos",
			vosotros: "incrementaseis",
			Uds: "incrementasen",
		},
		Future: {
			yo: "incrementare",
			tú: "incrementares",
			Ud: "incrementare",
			nosotros: "incrementáremos",
			vosotros: "incrementareis",
			Uds: "incrementaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "incrementa",
			Ud: "incremente",
			nosotros: "incrementemos",
			vosotros: "incrementad",
			Uds: "incrementen",
		},
		Negative: {
			tú: "no incrementes",
			Ud: "no incremente",
			nosotros: "no incrementemos",
			vosotros: "no incrementéis",
			Uds: "no incrementen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy incrementando",
			tú: "estás incrementando",
			Ud: "está incrementando",
			nosotros: "estamos incrementando",
			vosotros: "estáis incrementando",
			Uds: "están incrementando",
		},
		Preterite: {
			yo: "estuve incrementando",
			tú: "estuviste incrementando",
			Ud: "estuvo incrementando",
			nosotros: "estuvimos incrementando",
			vosotros: "estuvisteis incrementando",
			Uds: "estuvieron incrementando",
		},
		Imperfect: {
			Uds: "estaban incrementando",
			yo: "estaba incrementando",
			tú: "estabas incrementando",
			Ud: "estaba incrementando",
			nosotros: "estábamos incrementando",
			vosotros: "estabais incrementando",
		},
		Conditional: {
			yo: "estaría incrementando",
			tú: "estarías incrementando",
			Ud: "estaría incrementando",
			nosotros: "estaríamos incrementando",
			vosotros: "estaríais incrementando",
			Uds: "estarían incrementando",
		},
		Future: {
			yo: "estaré incrementando",
			tú: "estarás incrementando",
			Ud: "estará incrementando",
			nosotros: "estaremos incrementando",
			vosotros: "estaréis incrementando",
			Uds: "estarán incrementando",
		},
	},
	Perfect: {
		Present: {
			yo: "he incrementado",
			tú: "has incrementado",
			Ud: "ha incrementado",
			nosotros: "hemos incrementado",
			vosotros: "habéis incrementado",
			Uds: "han incrementado",
		},
		Preterite: {
			yo: "hube incrementado",
			tú: "hubiste incrementado",
			Ud: "hubo incrementado",
			nosotros: "hubimos incrementado",
			vosotros: "hubisteis incrementado",
			Uds: "hubieron incrementado",
		},
		Past: {
			yo: "había incrementado",
			tú: "habías incrementado",
			Ud: "había incrementado",
			nosotros: "habíamos incrementado",
			vosotros: "habíais incrementado",
			Uds: "habían incrementado",
		},
		Conditional: {
			yo: "habría incrementado",
			tú: "habrías incrementado",
			Ud: "habría incrementado",
			nosotros: "habríamos incrementado",
			vosotros: "habríais incrementado",
			Uds: "habrían incrementado",
		},
		Future: {
			yo: "habré incrementado",
			tú: "habrás incrementado",
			Ud: "habrá incrementado",
			nosotros: "habremos incrementado",
			vosotros: "habréis incrementado",
			Uds: "habrán incrementado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya incrementado",
			tú: "hayas incrementado",
			Ud: "haya incrementado",
			nosotros: "hayamos incrementado",
			vosotros: "hayáis incrementado",
			Uds: "hayan incrementado",
		},
		Past: {
			yo: "hubiera incrementado",
			tú: "hubieras incrementado",
			Ud: "hubiera incrementado",
			nosotros: "hubiéramos incrementado",
			vosotros: "hubierais incrementado",
			Uds: "hubieran incrementado",
		},
		Future: {
			yo: "hubiere incrementado",
			tú: "hubieres incrementado",
			Ud: "hubiere incrementado",
			nosotros: "hubiéremos incrementado",
			vosotros: "hubiereis incrementado",
			Uds: "hubieren incrementado",
		},
	},
}
