var inculpar = {
	Indicative: {
		Present: {
			yo: "inculpo",
			tú: "inculpas",
			Ud: "inculpa",
			nosotros: "inculpamos",
			vosotros: "inculpáis",
			Uds: "inculpan",
		},
		Preterite: {
			yo: "inculpé",
			tú: "inculpaste",
			Ud: "inculpó",
			nosotros: "inculpamos",
			vosotros: "inculpasteis",
			Uds: "inculparon",
		},
		Imperfect: {
			yo: "inculpaba",
			tú: "inculpabas",
			Ud: "inculpaba",
			nosotros: "inculpábamos",
			vosotros: "inculpabais",
			Uds: "inculpaban",
		},
		Conditional: {
			yo: "inculparía",
			tú: "inculparías",
			Ud: "inculparía",
			nosotros: "inculparíamos",
			vosotros: "inculparíais",
			Uds: "inculparían",
		},
		Future: {
			yo: "inculparé",
			tú: "inculparás",
			Ud: "inculpará",
			nosotros: "inculparemos",
			vosotros: "inculparéis",
			Uds: "inculparán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "inculpe",
			tú: "inculpes",
			Ud: "inculpe",
			nosotros: "inculpemos",
			vosotros: "inculpéis",
			Uds: "inculpen",
		},
		Imperfect: {
			yo: "inculpara",
			tú: "inculparas",
			Ud: "inculpara",
			nosotros: "inculpáramos",
			vosotros: "inculparais",
			Uds: "inculparan",
		},
		Imperfect2: {
			yo: "inculpase",
			tú: "inculpases",
			Ud: "inculpase",
			nosotros: "inculpásemos",
			vosotros: "inculpaseis",
			Uds: "inculpasen",
		},
		Future: {
			yo: "inculpare",
			tú: "inculpares",
			Ud: "inculpare",
			nosotros: "inculpáremos",
			vosotros: "inculpareis",
			Uds: "inculparen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "inculpa",
			Ud: "inculpe",
			nosotros: "inculpemos",
			vosotros: "inculpad",
			Uds: "inculpen",
		},
		Negative: {
			tú: "no inculpes",
			Ud: "no inculpe",
			nosotros: "no inculpemos",
			vosotros: "no inculpéis",
			Uds: "no inculpen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy inculpando",
			tú: "estás inculpando",
			Ud: "está inculpando",
			nosotros: "estamos inculpando",
			vosotros: "estáis inculpando",
			Uds: "están inculpando",
		},
		Preterite: {
			yo: "estuve inculpando",
			tú: "estuviste inculpando",
			Ud: "estuvo inculpando",
			nosotros: "estuvimos inculpando",
			vosotros: "estuvisteis inculpando",
			Uds: "estuvieron inculpando",
		},
		Imperfect: {
			Uds: "estaban inculpando",
			yo: "estaba inculpando",
			tú: "estabas inculpando",
			Ud: "estaba inculpando",
			nosotros: "estábamos inculpando",
			vosotros: "estabais inculpando",
		},
		Conditional: {
			yo: "estaría inculpando",
			tú: "estarías inculpando",
			Ud: "estaría inculpando",
			nosotros: "estaríamos inculpando",
			vosotros: "estaríais inculpando",
			Uds: "estarían inculpando",
		},
		Future: {
			yo: "estaré inculpando",
			tú: "estarás inculpando",
			Ud: "estará inculpando",
			nosotros: "estaremos inculpando",
			vosotros: "estaréis inculpando",
			Uds: "estarán inculpando",
		},
	},
	Perfect: {
		Present: {
			yo: "he inculpado",
			tú: "has inculpado",
			Ud: "ha inculpado",
			nosotros: "hemos inculpado",
			vosotros: "habéis inculpado",
			Uds: "han inculpado",
		},
		Preterite: {
			yo: "hube inculpado",
			tú: "hubiste inculpado",
			Ud: "hubo inculpado",
			nosotros: "hubimos inculpado",
			vosotros: "hubisteis inculpado",
			Uds: "hubieron inculpado",
		},
		Past: {
			yo: "había inculpado",
			tú: "habías inculpado",
			Ud: "había inculpado",
			nosotros: "habíamos inculpado",
			vosotros: "habíais inculpado",
			Uds: "habían inculpado",
		},
		Conditional: {
			yo: "habría inculpado",
			tú: "habrías inculpado",
			Ud: "habría inculpado",
			nosotros: "habríamos inculpado",
			vosotros: "habríais inculpado",
			Uds: "habrían inculpado",
		},
		Future: {
			yo: "habré inculpado",
			tú: "habrás inculpado",
			Ud: "habrá inculpado",
			nosotros: "habremos inculpado",
			vosotros: "habréis inculpado",
			Uds: "habrán inculpado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya inculpado",
			tú: "hayas inculpado",
			Ud: "haya inculpado",
			nosotros: "hayamos inculpado",
			vosotros: "hayáis inculpado",
			Uds: "hayan inculpado",
		},
		Past: {
			yo: "hubiera inculpado",
			tú: "hubieras inculpado",
			Ud: "hubiera inculpado",
			nosotros: "hubiéramos inculpado",
			vosotros: "hubierais inculpado",
			Uds: "hubieran inculpado",
		},
		Future: {
			yo: "hubiere inculpado",
			tú: "hubieres inculpado",
			Ud: "hubiere inculpado",
			nosotros: "hubiéremos inculpado",
			vosotros: "hubiereis inculpado",
			Uds: "hubieren inculpado",
		},
	},
}
