var infestar = {
	Indicative: {
		Present: {
			yo: "infesto",
			tú: "infestas",
			Ud: "infesta",
			nosotros: "infestamos",
			vosotros: "infestáis",
			Uds: "infestan",
		},
		Preterite: {
			yo: "infesté",
			tú: "infestaste",
			Ud: "infestó",
			nosotros: "infestamos",
			vosotros: "infestasteis",
			Uds: "infestaron",
		},
		Imperfect: {
			yo: "infestaba",
			tú: "infestabas",
			Ud: "infestaba",
			nosotros: "infestábamos",
			vosotros: "infestabais",
			Uds: "infestaban",
		},
		Conditional: {
			yo: "infestaría",
			tú: "infestarías",
			Ud: "infestaría",
			nosotros: "infestaríamos",
			vosotros: "infestaríais",
			Uds: "infestarían",
		},
		Future: {
			yo: "infestaré",
			tú: "infestarás",
			Ud: "infestará",
			nosotros: "infestaremos",
			vosotros: "infestaréis",
			Uds: "infestarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "infeste",
			tú: "infestes",
			Ud: "infeste",
			nosotros: "infestemos",
			vosotros: "infestéis",
			Uds: "infesten",
		},
		Imperfect: {
			yo: "infestara",
			tú: "infestaras",
			Ud: "infestara",
			nosotros: "infestáramos",
			vosotros: "infestarais",
			Uds: "infestaran",
		},
		Imperfect2: {
			yo: "infestase",
			tú: "infestases",
			Ud: "infestase",
			nosotros: "infestásemos",
			vosotros: "infestaseis",
			Uds: "infestasen",
		},
		Future: {
			yo: "infestare",
			tú: "infestares",
			Ud: "infestare",
			nosotros: "infestáremos",
			vosotros: "infestareis",
			Uds: "infestaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "infesta",
			Ud: "infeste",
			nosotros: "infestemos",
			vosotros: "infestad",
			Uds: "infesten",
		},
		Negative: {
			tú: "no infestes",
			Ud: "no infeste",
			nosotros: "no infestemos",
			vosotros: "no infestéis",
			Uds: "no infesten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy infestando",
			tú: "estás infestando",
			Ud: "está infestando",
			nosotros: "estamos infestando",
			vosotros: "estáis infestando",
			Uds: "están infestando",
		},
		Preterite: {
			yo: "estuve infestando",
			tú: "estuviste infestando",
			Ud: "estuvo infestando",
			nosotros: "estuvimos infestando",
			vosotros: "estuvisteis infestando",
			Uds: "estuvieron infestando",
		},
		Imperfect: {
			Uds: "estaban infestando",
			yo: "estaba infestando",
			tú: "estabas infestando",
			Ud: "estaba infestando",
			nosotros: "estábamos infestando",
			vosotros: "estabais infestando",
		},
		Conditional: {
			yo: "estaría infestando",
			tú: "estarías infestando",
			Ud: "estaría infestando",
			nosotros: "estaríamos infestando",
			vosotros: "estaríais infestando",
			Uds: "estarían infestando",
		},
		Future: {
			yo: "estaré infestando",
			tú: "estarás infestando",
			Ud: "estará infestando",
			nosotros: "estaremos infestando",
			vosotros: "estaréis infestando",
			Uds: "estarán infestando",
		},
	},
	Perfect: {
		Present: {
			yo: "he infestado",
			tú: "has infestado",
			Ud: "ha infestado",
			nosotros: "hemos infestado",
			vosotros: "habéis infestado",
			Uds: "han infestado",
		},
		Preterite: {
			yo: "hube infestado",
			tú: "hubiste infestado",
			Ud: "hubo infestado",
			nosotros: "hubimos infestado",
			vosotros: "hubisteis infestado",
			Uds: "hubieron infestado",
		},
		Past: {
			yo: "había infestado",
			tú: "habías infestado",
			Ud: "había infestado",
			nosotros: "habíamos infestado",
			vosotros: "habíais infestado",
			Uds: "habían infestado",
		},
		Conditional: {
			yo: "habría infestado",
			tú: "habrías infestado",
			Ud: "habría infestado",
			nosotros: "habríamos infestado",
			vosotros: "habríais infestado",
			Uds: "habrían infestado",
		},
		Future: {
			yo: "habré infestado",
			tú: "habrás infestado",
			Ud: "habrá infestado",
			nosotros: "habremos infestado",
			vosotros: "habréis infestado",
			Uds: "habrán infestado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya infestado",
			tú: "hayas infestado",
			Ud: "haya infestado",
			nosotros: "hayamos infestado",
			vosotros: "hayáis infestado",
			Uds: "hayan infestado",
		},
		Past: {
			yo: "hubiera infestado",
			tú: "hubieras infestado",
			Ud: "hubiera infestado",
			nosotros: "hubiéramos infestado",
			vosotros: "hubierais infestado",
			Uds: "hubieran infestado",
		},
		Future: {
			yo: "hubiere infestado",
			tú: "hubieres infestado",
			Ud: "hubiere infestado",
			nosotros: "hubiéremos infestado",
			vosotros: "hubiereis infestado",
			Uds: "hubieren infestado",
		},
	},
}
