var ingerir = {
	Indicative: {
		Present: {
			yo: "ingiero",
			tú: "ingieres",
			Ud: "ingiere",
			nosotros: "ingerimos",
			vosotros: "ingerís",
			Uds: "ingieren",
		},
		Preterite: {
			yo: "ingerí",
			tú: "ingeriste",
			Ud: "ingirió",
			nosotros: "ingerimos",
			vosotros: "ingeristeis",
			Uds: "ingirieron",
		},
		Imperfect: {
			yo: "ingería",
			tú: "ingerías",
			Ud: "ingería",
			nosotros: "ingeríamos",
			vosotros: "ingeríais",
			Uds: "ingerían",
		},
		Conditional: {
			yo: "ingeriría",
			tú: "ingerirías",
			Ud: "ingeriría",
			nosotros: "ingeriríamos",
			vosotros: "ingeriríais",
			Uds: "ingerirían",
		},
		Future: {
			yo: "ingeriré",
			tú: "ingerirás",
			Ud: "ingerirá",
			nosotros: "ingeriremos",
			vosotros: "ingeriréis",
			Uds: "ingerirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "ingiera",
			tú: "ingieras",
			Ud: "ingiera",
			nosotros: "ingiramos",
			vosotros: "ingiráis",
			Uds: "ingieran",
		},
		Imperfect: {
			yo: "ingiriera",
			tú: "ingirieras",
			Ud: "ingiriera",
			nosotros: "ingiriéramos",
			vosotros: "ingirierais",
			Uds: "ingirieran",
		},
		Imperfect2: {
			yo: "ingiriese",
			tú: "ingirieses",
			Ud: "ingiriese",
			nosotros: "ingiriésemos",
			vosotros: "ingirieseis",
			Uds: "ingiriesen",
		},
		Future: {
			yo: "ingiriere",
			tú: "ingirieres",
			Ud: "ingiriere",
			nosotros: "ingiriéremos",
			vosotros: "ingiriereis",
			Uds: "ingirieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "ingiere",
			Ud: "ingiera",
			nosotros: "ingiramos",
			vosotros: "ingerid",
			Uds: "ingieran",
		},
		Negative: {
			tú: "no ingieras",
			Ud: "no ingiera",
			nosotros: "no ingiramos",
			vosotros: "no ingiráis",
			Uds: "no ingieran",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy ingiriendo",
			tú: "estás ingiriendo",
			Ud: "está ingiriendo",
			nosotros: "estamos ingiriendo",
			vosotros: "estáis ingiriendo",
			Uds: "están ingiriendo",
		},
		Preterite: {
			yo: "estuve ingiriendo",
			tú: "estuviste ingiriendo",
			Ud: "estuvo ingiriendo",
			nosotros: "estuvimos ingiriendo",
			vosotros: "estuvisteis ingiriendo",
			Uds: "estuvieron ingiriendo",
		},
		Imperfect: {
			Uds: "estaban ingiriendo",
			yo: "estaba ingiriendo",
			tú: "estabas ingiriendo",
			Ud: "estaba ingiriendo",
			nosotros: "estábamos ingiriendo",
			vosotros: "estabais ingiriendo",
		},
		Conditional: {
			yo: "estaría ingiriendo",
			tú: "estarías ingiriendo",
			Ud: "estaría ingiriendo",
			nosotros: "estaríamos ingiriendo",
			vosotros: "estaríais ingiriendo",
			Uds: "estarían ingiriendo",
		},
		Future: {
			yo: "estaré ingiriendo",
			tú: "estarás ingiriendo",
			Ud: "estará ingiriendo",
			nosotros: "estaremos ingiriendo",
			vosotros: "estaréis ingiriendo",
			Uds: "estarán ingiriendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he ingerido",
			tú: "has ingerido",
			Ud: "ha ingerido",
			nosotros: "hemos ingerido",
			vosotros: "habéis ingerido",
			Uds: "han ingerido",
		},
		Preterite: {
			yo: "hube ingerido",
			tú: "hubiste ingerido",
			Ud: "hubo ingerido",
			nosotros: "hubimos ingerido",
			vosotros: "hubisteis ingerido",
			Uds: "hubieron ingerido",
		},
		Past: {
			yo: "había ingerido",
			tú: "habías ingerido",
			Ud: "había ingerido",
			nosotros: "habíamos ingerido",
			vosotros: "habíais ingerido",
			Uds: "habían ingerido",
		},
		Conditional: {
			yo: "habría ingerido",
			tú: "habrías ingerido",
			Ud: "habría ingerido",
			nosotros: "habríamos ingerido",
			vosotros: "habríais ingerido",
			Uds: "habrían ingerido",
		},
		Future: {
			yo: "habré ingerido",
			tú: "habrás ingerido",
			Ud: "habrá ingerido",
			nosotros: "habremos ingerido",
			vosotros: "habréis ingerido",
			Uds: "habrán ingerido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya ingerido",
			tú: "hayas ingerido",
			Ud: "haya ingerido",
			nosotros: "hayamos ingerido",
			vosotros: "hayáis ingerido",
			Uds: "hayan ingerido",
		},
		Past: {
			yo: "hubiera ingerido",
			tú: "hubieras ingerido",
			Ud: "hubiera ingerido",
			nosotros: "hubiéramos ingerido",
			vosotros: "hubierais ingerido",
			Uds: "hubieran ingerido",
		},
		Future: {
			yo: "hubiere ingerido",
			tú: "hubieres ingerido",
			Ud: "hubiere ingerido",
			nosotros: "hubiéremos ingerido",
			vosotros: "hubiereis ingerido",
			Uds: "hubieren ingerido",
		},
	},
}
