var ingresar = {
	Indicative: {
		Present: {
			yo: "ingreso",
			tú: "ingresas",
			Ud: "ingresa",
			nosotros: "ingresamos",
			vosotros: "ingresáis",
			Uds: "ingresan",
		},
		Preterite: {
			yo: "ingresé",
			tú: "ingresaste",
			Ud: "ingresó",
			nosotros: "ingresamos",
			vosotros: "ingresasteis",
			Uds: "ingresaron",
		},
		Imperfect: {
			yo: "ingresaba",
			tú: "ingresabas",
			Ud: "ingresaba",
			nosotros: "ingresábamos",
			vosotros: "ingresabais",
			Uds: "ingresaban",
		},
		Conditional: {
			yo: "ingresaría",
			tú: "ingresarías",
			Ud: "ingresaría",
			nosotros: "ingresaríamos",
			vosotros: "ingresaríais",
			Uds: "ingresarían",
		},
		Future: {
			yo: "ingresaré",
			tú: "ingresarás",
			Ud: "ingresará",
			nosotros: "ingresaremos",
			vosotros: "ingresaréis",
			Uds: "ingresarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "ingrese",
			tú: "ingreses",
			Ud: "ingrese",
			nosotros: "ingresemos",
			vosotros: "ingreséis",
			Uds: "ingresen",
		},
		Imperfect: {
			yo: "ingresara",
			tú: "ingresaras",
			Ud: "ingresara",
			nosotros: "ingresáramos",
			vosotros: "ingresarais",
			Uds: "ingresaran",
		},
		Imperfect2: {
			yo: "ingresase",
			tú: "ingresases",
			Ud: "ingresase",
			nosotros: "ingresásemos",
			vosotros: "ingresaseis",
			Uds: "ingresasen",
		},
		Future: {
			yo: "ingresare",
			tú: "ingresares",
			Ud: "ingresare",
			nosotros: "ingresáremos",
			vosotros: "ingresareis",
			Uds: "ingresaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "ingresa",
			Ud: "ingrese",
			nosotros: "ingresemos",
			vosotros: "ingresad",
			Uds: "ingresen",
		},
		Negative: {
			tú: "no ingreses",
			Ud: "no ingrese",
			nosotros: "no ingresemos",
			vosotros: "no ingreséis",
			Uds: "no ingresen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy ingresando",
			tú: "estás ingresando",
			Ud: "está ingresando",
			nosotros: "estamos ingresando",
			vosotros: "estáis ingresando",
			Uds: "están ingresando",
		},
		Preterite: {
			yo: "estuve ingresando",
			tú: "estuviste ingresando",
			Ud: "estuvo ingresando",
			nosotros: "estuvimos ingresando",
			vosotros: "estuvisteis ingresando",
			Uds: "estuvieron ingresando",
		},
		Imperfect: {
			Uds: "estaban ingresando",
			yo: "estaba ingresando",
			tú: "estabas ingresando",
			Ud: "estaba ingresando",
			nosotros: "estábamos ingresando",
			vosotros: "estabais ingresando",
		},
		Conditional: {
			yo: "estaría ingresando",
			tú: "estarías ingresando",
			Ud: "estaría ingresando",
			nosotros: "estaríamos ingresando",
			vosotros: "estaríais ingresando",
			Uds: "estarían ingresando",
		},
		Future: {
			yo: "estaré ingresando",
			tú: "estarás ingresando",
			Ud: "estará ingresando",
			nosotros: "estaremos ingresando",
			vosotros: "estaréis ingresando",
			Uds: "estarán ingresando",
		},
	},
	Perfect: {
		Present: {
			yo: "he ingresado",
			tú: "has ingresado",
			Ud: "ha ingresado",
			nosotros: "hemos ingresado",
			vosotros: "habéis ingresado",
			Uds: "han ingresado",
		},
		Preterite: {
			yo: "hube ingresado",
			tú: "hubiste ingresado",
			Ud: "hubo ingresado",
			nosotros: "hubimos ingresado",
			vosotros: "hubisteis ingresado",
			Uds: "hubieron ingresado",
		},
		Past: {
			yo: "había ingresado",
			tú: "habías ingresado",
			Ud: "había ingresado",
			nosotros: "habíamos ingresado",
			vosotros: "habíais ingresado",
			Uds: "habían ingresado",
		},
		Conditional: {
			yo: "habría ingresado",
			tú: "habrías ingresado",
			Ud: "habría ingresado",
			nosotros: "habríamos ingresado",
			vosotros: "habríais ingresado",
			Uds: "habrían ingresado",
		},
		Future: {
			yo: "habré ingresado",
			tú: "habrás ingresado",
			Ud: "habrá ingresado",
			nosotros: "habremos ingresado",
			vosotros: "habréis ingresado",
			Uds: "habrán ingresado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya ingresado",
			tú: "hayas ingresado",
			Ud: "haya ingresado",
			nosotros: "hayamos ingresado",
			vosotros: "hayáis ingresado",
			Uds: "hayan ingresado",
		},
		Past: {
			yo: "hubiera ingresado",
			tú: "hubieras ingresado",
			Ud: "hubiera ingresado",
			nosotros: "hubiéramos ingresado",
			vosotros: "hubierais ingresado",
			Uds: "hubieran ingresado",
		},
		Future: {
			yo: "hubiere ingresado",
			tú: "hubieres ingresado",
			Ud: "hubiere ingresado",
			nosotros: "hubiéremos ingresado",
			vosotros: "hubiereis ingresado",
			Uds: "hubieren ingresado",
		},
	},
}
