var inhalar = {
	Indicative: {
		Present: {
			yo: "inhalo",
			tú: "inhalas",
			Ud: "inhala",
			nosotros: "inhalamos",
			vosotros: "inhaláis",
			Uds: "inhalan",
		},
		Preterite: {
			yo: "inhalé",
			tú: "inhalaste",
			Ud: "inhaló",
			nosotros: "inhalamos",
			vosotros: "inhalasteis",
			Uds: "inhalaron",
		},
		Imperfect: {
			yo: "inhalaba",
			tú: "inhalabas",
			Ud: "inhalaba",
			nosotros: "inhalábamos",
			vosotros: "inhalabais",
			Uds: "inhalaban",
		},
		Conditional: {
			yo: "inhalaría",
			tú: "inhalarías",
			Ud: "inhalaría",
			nosotros: "inhalaríamos",
			vosotros: "inhalaríais",
			Uds: "inhalarían",
		},
		Future: {
			yo: "inhalaré",
			tú: "inhalarás",
			Ud: "inhalará",
			nosotros: "inhalaremos",
			vosotros: "inhalaréis",
			Uds: "inhalarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "inhale",
			tú: "inhales",
			Ud: "inhale",
			nosotros: "inhalemos",
			vosotros: "inhaléis",
			Uds: "inhalen",
		},
		Imperfect: {
			yo: "inhalara",
			tú: "inhalaras",
			Ud: "inhalara",
			nosotros: "inhaláramos",
			vosotros: "inhalarais",
			Uds: "inhalaran",
		},
		Imperfect2: {
			yo: "inhalase",
			tú: "inhalases",
			Ud: "inhalase",
			nosotros: "inhalásemos",
			vosotros: "inhalaseis",
			Uds: "inhalasen",
		},
		Future: {
			yo: "inhalare",
			tú: "inhalares",
			Ud: "inhalare",
			nosotros: "inhaláremos",
			vosotros: "inhalareis",
			Uds: "inhalaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "inhala",
			Ud: "inhale",
			nosotros: "inhalemos",
			vosotros: "inhalad",
			Uds: "inhalen",
		},
		Negative: {
			tú: "no inhales",
			Ud: "no inhale",
			nosotros: "no inhalemos",
			vosotros: "no inhaléis",
			Uds: "no inhalen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy inhalando",
			tú: "estás inhalando",
			Ud: "está inhalando",
			nosotros: "estamos inhalando",
			vosotros: "estáis inhalando",
			Uds: "están inhalando",
		},
		Preterite: {
			yo: "estuve inhalando",
			tú: "estuviste inhalando",
			Ud: "estuvo inhalando",
			nosotros: "estuvimos inhalando",
			vosotros: "estuvisteis inhalando",
			Uds: "estuvieron inhalando",
		},
		Imperfect: {
			Uds: "estaban inhalando",
			yo: "estaba inhalando",
			tú: "estabas inhalando",
			Ud: "estaba inhalando",
			nosotros: "estábamos inhalando",
			vosotros: "estabais inhalando",
		},
		Conditional: {
			yo: "estaría inhalando",
			tú: "estarías inhalando",
			Ud: "estaría inhalando",
			nosotros: "estaríamos inhalando",
			vosotros: "estaríais inhalando",
			Uds: "estarían inhalando",
		},
		Future: {
			yo: "estaré inhalando",
			tú: "estarás inhalando",
			Ud: "estará inhalando",
			nosotros: "estaremos inhalando",
			vosotros: "estaréis inhalando",
			Uds: "estarán inhalando",
		},
	},
	Perfect: {
		Present: {
			yo: "he inhalado",
			tú: "has inhalado",
			Ud: "ha inhalado",
			nosotros: "hemos inhalado",
			vosotros: "habéis inhalado",
			Uds: "han inhalado",
		},
		Preterite: {
			yo: "hube inhalado",
			tú: "hubiste inhalado",
			Ud: "hubo inhalado",
			nosotros: "hubimos inhalado",
			vosotros: "hubisteis inhalado",
			Uds: "hubieron inhalado",
		},
		Past: {
			yo: "había inhalado",
			tú: "habías inhalado",
			Ud: "había inhalado",
			nosotros: "habíamos inhalado",
			vosotros: "habíais inhalado",
			Uds: "habían inhalado",
		},
		Conditional: {
			yo: "habría inhalado",
			tú: "habrías inhalado",
			Ud: "habría inhalado",
			nosotros: "habríamos inhalado",
			vosotros: "habríais inhalado",
			Uds: "habrían inhalado",
		},
		Future: {
			yo: "habré inhalado",
			tú: "habrás inhalado",
			Ud: "habrá inhalado",
			nosotros: "habremos inhalado",
			vosotros: "habréis inhalado",
			Uds: "habrán inhalado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya inhalado",
			tú: "hayas inhalado",
			Ud: "haya inhalado",
			nosotros: "hayamos inhalado",
			vosotros: "hayáis inhalado",
			Uds: "hayan inhalado",
		},
		Past: {
			yo: "hubiera inhalado",
			tú: "hubieras inhalado",
			Ud: "hubiera inhalado",
			nosotros: "hubiéramos inhalado",
			vosotros: "hubierais inhalado",
			Uds: "hubieran inhalado",
		},
		Future: {
			yo: "hubiere inhalado",
			tú: "hubieres inhalado",
			Ud: "hubiere inhalado",
			nosotros: "hubiéremos inhalado",
			vosotros: "hubiereis inhalado",
			Uds: "hubieren inhalado",
		},
	},
}
