var inhibir = {
	Indicative: {
		Present: {
			yo: "inhibo",
			tú: "inhibes",
			Ud: "inhibe",
			nosotros: "inhibimos",
			vosotros: "inhibís",
			Uds: "inhiben",
		},
		Preterite: {
			yo: "inhibí",
			tú: "inhibiste",
			Ud: "inhibió",
			nosotros: "inhibimos",
			vosotros: "inhibisteis",
			Uds: "inhibieron",
		},
		Imperfect: {
			yo: "inhibía",
			tú: "inhibías",
			Ud: "inhibía",
			nosotros: "inhibíamos",
			vosotros: "inhibíais",
			Uds: "inhibían",
		},
		Conditional: {
			yo: "inhibiría",
			tú: "inhibirías",
			Ud: "inhibiría",
			nosotros: "inhibiríamos",
			vosotros: "inhibiríais",
			Uds: "inhibirían",
		},
		Future: {
			yo: "inhibiré",
			tú: "inhibirás",
			Ud: "inhibirá",
			nosotros: "inhibiremos",
			vosotros: "inhibiréis",
			Uds: "inhibirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "inhiba",
			tú: "inhibas",
			Ud: "inhiba",
			nosotros: "inhibamos",
			vosotros: "inhibáis",
			Uds: "inhiban",
		},
		Imperfect: {
			yo: "inhibiera",
			tú: "inhibieras",
			Ud: "inhibiera",
			nosotros: "inhibiéramos",
			vosotros: "inhibierais",
			Uds: "inhibieran",
		},
		Imperfect2: {
			yo: "inhibiese",
			tú: "inhibieses",
			Ud: "inhibiese",
			nosotros: "inhibiésemos",
			vosotros: "inhibieseis",
			Uds: "inhibiesen",
		},
		Future: {
			yo: "inhibiere",
			tú: "inhibieres",
			Ud: "inhibiere",
			nosotros: "inhibiéremos",
			vosotros: "inhibiereis",
			Uds: "inhibieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "inhibe",
			Ud: "inhiba",
			nosotros: "inhibamos",
			vosotros: "inhibid",
			Uds: "inhiban",
		},
		Negative: {
			tú: "no inhibas",
			Ud: "no inhiba",
			nosotros: "no inhibamos",
			vosotros: "no inhibáis",
			Uds: "no inhiban",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy inhibiendo",
			tú: "estás inhibiendo",
			Ud: "está inhibiendo",
			nosotros: "estamos inhibiendo",
			vosotros: "estáis inhibiendo",
			Uds: "están inhibiendo",
		},
		Preterite: {
			yo: "estuve inhibiendo",
			tú: "estuviste inhibiendo",
			Ud: "estuvo inhibiendo",
			nosotros: "estuvimos inhibiendo",
			vosotros: "estuvisteis inhibiendo",
			Uds: "estuvieron inhibiendo",
		},
		Imperfect: {
			Uds: "estaban inhibiendo",
			yo: "estaba inhibiendo",
			tú: "estabas inhibiendo",
			Ud: "estaba inhibiendo",
			nosotros: "estábamos inhibiendo",
			vosotros: "estabais inhibiendo",
		},
		Conditional: {
			yo: "estaría inhibiendo",
			tú: "estarías inhibiendo",
			Ud: "estaría inhibiendo",
			nosotros: "estaríamos inhibiendo",
			vosotros: "estaríais inhibiendo",
			Uds: "estarían inhibiendo",
		},
		Future: {
			yo: "estaré inhibiendo",
			tú: "estarás inhibiendo",
			Ud: "estará inhibiendo",
			nosotros: "estaremos inhibiendo",
			vosotros: "estaréis inhibiendo",
			Uds: "estarán inhibiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he inhibido",
			tú: "has inhibido",
			Ud: "ha inhibido",
			nosotros: "hemos inhibido",
			vosotros: "habéis inhibido",
			Uds: "han inhibido",
		},
		Preterite: {
			yo: "hube inhibido",
			tú: "hubiste inhibido",
			Ud: "hubo inhibido",
			nosotros: "hubimos inhibido",
			vosotros: "hubisteis inhibido",
			Uds: "hubieron inhibido",
		},
		Past: {
			yo: "había inhibido",
			tú: "habías inhibido",
			Ud: "había inhibido",
			nosotros: "habíamos inhibido",
			vosotros: "habíais inhibido",
			Uds: "habían inhibido",
		},
		Conditional: {
			yo: "habría inhibido",
			tú: "habrías inhibido",
			Ud: "habría inhibido",
			nosotros: "habríamos inhibido",
			vosotros: "habríais inhibido",
			Uds: "habrían inhibido",
		},
		Future: {
			yo: "habré inhibido",
			tú: "habrás inhibido",
			Ud: "habrá inhibido",
			nosotros: "habremos inhibido",
			vosotros: "habréis inhibido",
			Uds: "habrán inhibido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya inhibido",
			tú: "hayas inhibido",
			Ud: "haya inhibido",
			nosotros: "hayamos inhibido",
			vosotros: "hayáis inhibido",
			Uds: "hayan inhibido",
		},
		Past: {
			yo: "hubiera inhibido",
			tú: "hubieras inhibido",
			Ud: "hubiera inhibido",
			nosotros: "hubiéramos inhibido",
			vosotros: "hubierais inhibido",
			Uds: "hubieran inhibido",
		},
		Future: {
			yo: "hubiere inhibido",
			tú: "hubieres inhibido",
			Ud: "hubiere inhibido",
			nosotros: "hubiéremos inhibido",
			vosotros: "hubiereis inhibido",
			Uds: "hubieren inhibido",
		},
	},
}
