var iniciar = {
	Indicative: {
		Present: {
			yo: "inicio",
			tú: "inicias",
			Ud: "inicia",
			nosotros: "iniciamos",
			vosotros: "iniciáis",
			Uds: "inician",
		},
		Preterite: {
			yo: "inicié",
			tú: "iniciaste",
			Ud: "inició",
			nosotros: "iniciamos",
			vosotros: "iniciasteis",
			Uds: "iniciaron",
		},
		Imperfect: {
			yo: "iniciaba",
			tú: "iniciabas",
			Ud: "iniciaba",
			nosotros: "iniciábamos",
			vosotros: "iniciabais",
			Uds: "iniciaban",
		},
		Conditional: {
			yo: "iniciaría",
			tú: "iniciarías",
			Ud: "iniciaría",
			nosotros: "iniciaríamos",
			vosotros: "iniciaríais",
			Uds: "iniciarían",
		},
		Future: {
			yo: "iniciaré",
			tú: "iniciarás",
			Ud: "iniciará",
			nosotros: "iniciaremos",
			vosotros: "iniciaréis",
			Uds: "iniciarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "inicie",
			tú: "inicies",
			Ud: "inicie",
			nosotros: "iniciemos",
			vosotros: "iniciéis",
			Uds: "inicien",
		},
		Imperfect: {
			yo: "iniciara",
			tú: "iniciaras",
			Ud: "iniciara",
			nosotros: "iniciáramos",
			vosotros: "iniciarais",
			Uds: "iniciaran",
		},
		Imperfect2: {
			yo: "iniciase",
			tú: "iniciases",
			Ud: "iniciase",
			nosotros: "iniciásemos",
			vosotros: "iniciaseis",
			Uds: "iniciasen",
		},
		Future: {
			yo: "iniciare",
			tú: "iniciares",
			Ud: "iniciare",
			nosotros: "iniciáremos",
			vosotros: "iniciareis",
			Uds: "iniciaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "inicia",
			Ud: "inicie",
			nosotros: "iniciemos",
			vosotros: "iniciad",
			Uds: "inicien",
		},
		Negative: {
			tú: "no inicies",
			Ud: "no inicie",
			nosotros: "no iniciemos",
			vosotros: "no iniciéis",
			Uds: "no inicien",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy iniciando",
			tú: "estás iniciando",
			Ud: "está iniciando",
			nosotros: "estamos iniciando",
			vosotros: "estáis iniciando",
			Uds: "están iniciando",
		},
		Preterite: {
			yo: "estuve iniciando",
			tú: "estuviste iniciando",
			Ud: "estuvo iniciando",
			nosotros: "estuvimos iniciando",
			vosotros: "estuvisteis iniciando",
			Uds: "estuvieron iniciando",
		},
		Imperfect: {
			Uds: "estaban iniciando",
			yo: "estaba iniciando",
			tú: "estabas iniciando",
			Ud: "estaba iniciando",
			nosotros: "estábamos iniciando",
			vosotros: "estabais iniciando",
		},
		Conditional: {
			yo: "estaría iniciando",
			tú: "estarías iniciando",
			Ud: "estaría iniciando",
			nosotros: "estaríamos iniciando",
			vosotros: "estaríais iniciando",
			Uds: "estarían iniciando",
		},
		Future: {
			yo: "estaré iniciando",
			tú: "estarás iniciando",
			Ud: "estará iniciando",
			nosotros: "estaremos iniciando",
			vosotros: "estaréis iniciando",
			Uds: "estarán iniciando",
		},
	},
	Perfect: {
		Present: {
			yo: "he iniciado",
			tú: "has iniciado",
			Ud: "ha iniciado",
			nosotros: "hemos iniciado",
			vosotros: "habéis iniciado",
			Uds: "han iniciado",
		},
		Preterite: {
			yo: "hube iniciado",
			tú: "hubiste iniciado",
			Ud: "hubo iniciado",
			nosotros: "hubimos iniciado",
			vosotros: "hubisteis iniciado",
			Uds: "hubieron iniciado",
		},
		Past: {
			yo: "había iniciado",
			tú: "habías iniciado",
			Ud: "había iniciado",
			nosotros: "habíamos iniciado",
			vosotros: "habíais iniciado",
			Uds: "habían iniciado",
		},
		Conditional: {
			yo: "habría iniciado",
			tú: "habrías iniciado",
			Ud: "habría iniciado",
			nosotros: "habríamos iniciado",
			vosotros: "habríais iniciado",
			Uds: "habrían iniciado",
		},
		Future: {
			yo: "habré iniciado",
			tú: "habrás iniciado",
			Ud: "habrá iniciado",
			nosotros: "habremos iniciado",
			vosotros: "habréis iniciado",
			Uds: "habrán iniciado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya iniciado",
			tú: "hayas iniciado",
			Ud: "haya iniciado",
			nosotros: "hayamos iniciado",
			vosotros: "hayáis iniciado",
			Uds: "hayan iniciado",
		},
		Past: {
			yo: "hubiera iniciado",
			tú: "hubieras iniciado",
			Ud: "hubiera iniciado",
			nosotros: "hubiéramos iniciado",
			vosotros: "hubierais iniciado",
			Uds: "hubieran iniciado",
		},
		Future: {
			yo: "hubiere iniciado",
			tú: "hubieres iniciado",
			Ud: "hubiere iniciado",
			nosotros: "hubiéremos iniciado",
			vosotros: "hubiereis iniciado",
			Uds: "hubieren iniciado",
		},
	},
}
