var inquietar = {
	Indicative: {
		Present: {
			yo: "inquieto",
			tú: "inquietas",
			Ud: "inquieta",
			nosotros: "inquietamos",
			vosotros: "inquietáis",
			Uds: "inquietan",
		},
		Preterite: {
			yo: "inquieté",
			tú: "inquietaste",
			Ud: "inquietó",
			nosotros: "inquietamos",
			vosotros: "inquietasteis",
			Uds: "inquietaron",
		},
		Imperfect: {
			yo: "inquietaba",
			tú: "inquietabas",
			Ud: "inquietaba",
			nosotros: "inquietábamos",
			vosotros: "inquietabais",
			Uds: "inquietaban",
		},
		Conditional: {
			yo: "inquietaría",
			tú: "inquietarías",
			Ud: "inquietaría",
			nosotros: "inquietaríamos",
			vosotros: "inquietaríais",
			Uds: "inquietarían",
		},
		Future: {
			yo: "inquietaré",
			tú: "inquietarás",
			Ud: "inquietará",
			nosotros: "inquietaremos",
			vosotros: "inquietaréis",
			Uds: "inquietarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "inquiete",
			tú: "inquietes",
			Ud: "inquiete",
			nosotros: "inquietemos",
			vosotros: "inquietéis",
			Uds: "inquieten",
		},
		Imperfect: {
			yo: "inquietara",
			tú: "inquietaras",
			Ud: "inquietara",
			nosotros: "inquietáramos",
			vosotros: "inquietarais",
			Uds: "inquietaran",
		},
		Imperfect2: {
			yo: "inquietase",
			tú: "inquietases",
			Ud: "inquietase",
			nosotros: "inquietásemos",
			vosotros: "inquietaseis",
			Uds: "inquietasen",
		},
		Future: {
			yo: "inquietare",
			tú: "inquietares",
			Ud: "inquietare",
			nosotros: "inquietáremos",
			vosotros: "inquietareis",
			Uds: "inquietaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "inquieta",
			Ud: "inquiete",
			nosotros: "inquietemos",
			vosotros: "inquietad",
			Uds: "inquieten",
		},
		Negative: {
			tú: "no inquietes",
			Ud: "no inquiete",
			nosotros: "no inquietemos",
			vosotros: "no inquietéis",
			Uds: "no inquieten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy inquietando",
			tú: "estás inquietando",
			Ud: "está inquietando",
			nosotros: "estamos inquietando",
			vosotros: "estáis inquietando",
			Uds: "están inquietando",
		},
		Preterite: {
			yo: "estuve inquietando",
			tú: "estuviste inquietando",
			Ud: "estuvo inquietando",
			nosotros: "estuvimos inquietando",
			vosotros: "estuvisteis inquietando",
			Uds: "estuvieron inquietando",
		},
		Imperfect: {
			Uds: "estaban inquietando",
			yo: "estaba inquietando",
			tú: "estabas inquietando",
			Ud: "estaba inquietando",
			nosotros: "estábamos inquietando",
			vosotros: "estabais inquietando",
		},
		Conditional: {
			yo: "estaría inquietando",
			tú: "estarías inquietando",
			Ud: "estaría inquietando",
			nosotros: "estaríamos inquietando",
			vosotros: "estaríais inquietando",
			Uds: "estarían inquietando",
		},
		Future: {
			yo: "estaré inquietando",
			tú: "estarás inquietando",
			Ud: "estará inquietando",
			nosotros: "estaremos inquietando",
			vosotros: "estaréis inquietando",
			Uds: "estarán inquietando",
		},
	},
	Perfect: {
		Present: {
			yo: "he inquietado",
			tú: "has inquietado",
			Ud: "ha inquietado",
			nosotros: "hemos inquietado",
			vosotros: "habéis inquietado",
			Uds: "han inquietado",
		},
		Preterite: {
			yo: "hube inquietado",
			tú: "hubiste inquietado",
			Ud: "hubo inquietado",
			nosotros: "hubimos inquietado",
			vosotros: "hubisteis inquietado",
			Uds: "hubieron inquietado",
		},
		Past: {
			yo: "había inquietado",
			tú: "habías inquietado",
			Ud: "había inquietado",
			nosotros: "habíamos inquietado",
			vosotros: "habíais inquietado",
			Uds: "habían inquietado",
		},
		Conditional: {
			yo: "habría inquietado",
			tú: "habrías inquietado",
			Ud: "habría inquietado",
			nosotros: "habríamos inquietado",
			vosotros: "habríais inquietado",
			Uds: "habrían inquietado",
		},
		Future: {
			yo: "habré inquietado",
			tú: "habrás inquietado",
			Ud: "habrá inquietado",
			nosotros: "habremos inquietado",
			vosotros: "habréis inquietado",
			Uds: "habrán inquietado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya inquietado",
			tú: "hayas inquietado",
			Ud: "haya inquietado",
			nosotros: "hayamos inquietado",
			vosotros: "hayáis inquietado",
			Uds: "hayan inquietado",
		},
		Past: {
			yo: "hubiera inquietado",
			tú: "hubieras inquietado",
			Ud: "hubiera inquietado",
			nosotros: "hubiéramos inquietado",
			vosotros: "hubierais inquietado",
			Uds: "hubieran inquietado",
		},
		Future: {
			yo: "hubiere inquietado",
			tú: "hubieres inquietado",
			Ud: "hubiere inquietado",
			nosotros: "hubiéremos inquietado",
			vosotros: "hubiereis inquietado",
			Uds: "hubieren inquietado",
		},
	},
}
