var inspeccionar = {
	Indicative: {
		Present: {
			yo: "inspecciono",
			tú: "inspeccionas",
			Ud: "inspecciona",
			nosotros: "inspeccionamos",
			vosotros: "inspeccionáis",
			Uds: "inspeccionan",
		},
		Preterite: {
			yo: "inspeccioné",
			tú: "inspeccionaste",
			Ud: "inspeccionó",
			nosotros: "inspeccionamos",
			vosotros: "inspeccionasteis",
			Uds: "inspeccionaron",
		},
		Imperfect: {
			yo: "inspeccionaba",
			tú: "inspeccionabas",
			Ud: "inspeccionaba",
			nosotros: "inspeccionábamos",
			vosotros: "inspeccionabais",
			Uds: "inspeccionaban",
		},
		Conditional: {
			yo: "inspeccionaría",
			tú: "inspeccionarías",
			Ud: "inspeccionaría",
			nosotros: "inspeccionaríamos",
			vosotros: "inspeccionaríais",
			Uds: "inspeccionarían",
		},
		Future: {
			yo: "inspeccionaré",
			tú: "inspeccionarás",
			Ud: "inspeccionará",
			nosotros: "inspeccionaremos",
			vosotros: "inspeccionaréis",
			Uds: "inspeccionarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "inspeccione",
			tú: "inspecciones",
			Ud: "inspeccione",
			nosotros: "inspeccionemos",
			vosotros: "inspeccionéis",
			Uds: "inspeccionen",
		},
		Imperfect: {
			yo: "inspeccionara",
			tú: "inspeccionaras",
			Ud: "inspeccionara",
			nosotros: "inspeccionáramos",
			vosotros: "inspeccionarais",
			Uds: "inspeccionaran",
		},
		Imperfect2: {
			yo: "inspeccionase",
			tú: "inspeccionases",
			Ud: "inspeccionase",
			nosotros: "inspeccionásemos",
			vosotros: "inspeccionaseis",
			Uds: "inspeccionasen",
		},
		Future: {
			yo: "inspeccionare",
			tú: "inspeccionares",
			Ud: "inspeccionare",
			nosotros: "inspeccionáremos",
			vosotros: "inspeccionareis",
			Uds: "inspeccionaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "inspecciona",
			Ud: "inspeccione",
			nosotros: "inspeccionemos",
			vosotros: "inspeccionad",
			Uds: "inspeccionen",
		},
		Negative: {
			tú: "no inspecciones",
			Ud: "no inspeccione",
			nosotros: "no inspeccionemos",
			vosotros: "no inspeccionéis",
			Uds: "no inspeccionen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy inspeccionando",
			tú: "estás inspeccionando",
			Ud: "está inspeccionando",
			nosotros: "estamos inspeccionando",
			vosotros: "estáis inspeccionando",
			Uds: "están inspeccionando",
		},
		Preterite: {
			yo: "estuve inspeccionando",
			tú: "estuviste inspeccionando",
			Ud: "estuvo inspeccionando",
			nosotros: "estuvimos inspeccionando",
			vosotros: "estuvisteis inspeccionando",
			Uds: "estuvieron inspeccionando",
		},
		Imperfect: {
			Uds: "estaban inspeccionando",
			yo: "estaba inspeccionando",
			tú: "estabas inspeccionando",
			Ud: "estaba inspeccionando",
			nosotros: "estábamos inspeccionando",
			vosotros: "estabais inspeccionando",
		},
		Conditional: {
			yo: "estaría inspeccionando",
			tú: "estarías inspeccionando",
			Ud: "estaría inspeccionando",
			nosotros: "estaríamos inspeccionando",
			vosotros: "estaríais inspeccionando",
			Uds: "estarían inspeccionando",
		},
		Future: {
			yo: "estaré inspeccionando",
			tú: "estarás inspeccionando",
			Ud: "estará inspeccionando",
			nosotros: "estaremos inspeccionando",
			vosotros: "estaréis inspeccionando",
			Uds: "estarán inspeccionando",
		},
	},
	Perfect: {
		Present: {
			yo: "he inspeccionado",
			tú: "has inspeccionado",
			Ud: "ha inspeccionado",
			nosotros: "hemos inspeccionado",
			vosotros: "habéis inspeccionado",
			Uds: "han inspeccionado",
		},
		Preterite: {
			yo: "hube inspeccionado",
			tú: "hubiste inspeccionado",
			Ud: "hubo inspeccionado",
			nosotros: "hubimos inspeccionado",
			vosotros: "hubisteis inspeccionado",
			Uds: "hubieron inspeccionado",
		},
		Past: {
			yo: "había inspeccionado",
			tú: "habías inspeccionado",
			Ud: "había inspeccionado",
			nosotros: "habíamos inspeccionado",
			vosotros: "habíais inspeccionado",
			Uds: "habían inspeccionado",
		},
		Conditional: {
			yo: "habría inspeccionado",
			tú: "habrías inspeccionado",
			Ud: "habría inspeccionado",
			nosotros: "habríamos inspeccionado",
			vosotros: "habríais inspeccionado",
			Uds: "habrían inspeccionado",
		},
		Future: {
			yo: "habré inspeccionado",
			tú: "habrás inspeccionado",
			Ud: "habrá inspeccionado",
			nosotros: "habremos inspeccionado",
			vosotros: "habréis inspeccionado",
			Uds: "habrán inspeccionado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya inspeccionado",
			tú: "hayas inspeccionado",
			Ud: "haya inspeccionado",
			nosotros: "hayamos inspeccionado",
			vosotros: "hayáis inspeccionado",
			Uds: "hayan inspeccionado",
		},
		Past: {
			yo: "hubiera inspeccionado",
			tú: "hubieras inspeccionado",
			Ud: "hubiera inspeccionado",
			nosotros: "hubiéramos inspeccionado",
			vosotros: "hubierais inspeccionado",
			Uds: "hubieran inspeccionado",
		},
		Future: {
			yo: "hubiere inspeccionado",
			tú: "hubieres inspeccionado",
			Ud: "hubiere inspeccionado",
			nosotros: "hubiéremos inspeccionado",
			vosotros: "hubiereis inspeccionado",
			Uds: "hubieren inspeccionado",
		},
	},
}
