var instaurar = {
	Indicative: {
		Present: {
			yo: "instauro",
			tú: "instauras",
			Ud: "instaura",
			nosotros: "instauramos",
			vosotros: "instauráis",
			Uds: "instauran",
		},
		Preterite: {
			yo: "instauré",
			tú: "instauraste",
			Ud: "instauró",
			nosotros: "instauramos",
			vosotros: "instaurasteis",
			Uds: "instauraron",
		},
		Imperfect: {
			yo: "instauraba",
			tú: "instaurabas",
			Ud: "instauraba",
			nosotros: "instaurábamos",
			vosotros: "instaurabais",
			Uds: "instauraban",
		},
		Conditional: {
			yo: "instauraría",
			tú: "instaurarías",
			Ud: "instauraría",
			nosotros: "instauraríamos",
			vosotros: "instauraríais",
			Uds: "instaurarían",
		},
		Future: {
			yo: "instauraré",
			tú: "instaurarás",
			Ud: "instaurará",
			nosotros: "instauraremos",
			vosotros: "instauraréis",
			Uds: "instaurarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "instaure",
			tú: "instaures",
			Ud: "instaure",
			nosotros: "instauremos",
			vosotros: "instauréis",
			Uds: "instauren",
		},
		Imperfect: {
			yo: "instaurara",
			tú: "instauraras",
			Ud: "instaurara",
			nosotros: "instauráramos",
			vosotros: "instaurarais",
			Uds: "instauraran",
		},
		Imperfect2: {
			yo: "instaurase",
			tú: "instaurases",
			Ud: "instaurase",
			nosotros: "instaurásemos",
			vosotros: "instauraseis",
			Uds: "instaurasen",
		},
		Future: {
			yo: "instaurare",
			tú: "instaurares",
			Ud: "instaurare",
			nosotros: "instauráremos",
			vosotros: "instaurareis",
			Uds: "instauraren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "instaura",
			Ud: "instaure",
			nosotros: "instauremos",
			vosotros: "instaurad",
			Uds: "instauren",
		},
		Negative: {
			tú: "no instaures",
			Ud: "no instaure",
			nosotros: "no instauremos",
			vosotros: "no instauréis",
			Uds: "no instauren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy instaurando",
			tú: "estás instaurando",
			Ud: "está instaurando",
			nosotros: "estamos instaurando",
			vosotros: "estáis instaurando",
			Uds: "están instaurando",
		},
		Preterite: {
			yo: "estuve instaurando",
			tú: "estuviste instaurando",
			Ud: "estuvo instaurando",
			nosotros: "estuvimos instaurando",
			vosotros: "estuvisteis instaurando",
			Uds: "estuvieron instaurando",
		},
		Imperfect: {
			Uds: "estaban instaurando",
			yo: "estaba instaurando",
			tú: "estabas instaurando",
			Ud: "estaba instaurando",
			nosotros: "estábamos instaurando",
			vosotros: "estabais instaurando",
		},
		Conditional: {
			yo: "estaría instaurando",
			tú: "estarías instaurando",
			Ud: "estaría instaurando",
			nosotros: "estaríamos instaurando",
			vosotros: "estaríais instaurando",
			Uds: "estarían instaurando",
		},
		Future: {
			yo: "estaré instaurando",
			tú: "estarás instaurando",
			Ud: "estará instaurando",
			nosotros: "estaremos instaurando",
			vosotros: "estaréis instaurando",
			Uds: "estarán instaurando",
		},
	},
	Perfect: {
		Present: {
			yo: "he instaurado",
			tú: "has instaurado",
			Ud: "ha instaurado",
			nosotros: "hemos instaurado",
			vosotros: "habéis instaurado",
			Uds: "han instaurado",
		},
		Preterite: {
			yo: "hube instaurado",
			tú: "hubiste instaurado",
			Ud: "hubo instaurado",
			nosotros: "hubimos instaurado",
			vosotros: "hubisteis instaurado",
			Uds: "hubieron instaurado",
		},
		Past: {
			yo: "había instaurado",
			tú: "habías instaurado",
			Ud: "había instaurado",
			nosotros: "habíamos instaurado",
			vosotros: "habíais instaurado",
			Uds: "habían instaurado",
		},
		Conditional: {
			yo: "habría instaurado",
			tú: "habrías instaurado",
			Ud: "habría instaurado",
			nosotros: "habríamos instaurado",
			vosotros: "habríais instaurado",
			Uds: "habrían instaurado",
		},
		Future: {
			yo: "habré instaurado",
			tú: "habrás instaurado",
			Ud: "habrá instaurado",
			nosotros: "habremos instaurado",
			vosotros: "habréis instaurado",
			Uds: "habrán instaurado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya instaurado",
			tú: "hayas instaurado",
			Ud: "haya instaurado",
			nosotros: "hayamos instaurado",
			vosotros: "hayáis instaurado",
			Uds: "hayan instaurado",
		},
		Past: {
			yo: "hubiera instaurado",
			tú: "hubieras instaurado",
			Ud: "hubiera instaurado",
			nosotros: "hubiéramos instaurado",
			vosotros: "hubierais instaurado",
			Uds: "hubieran instaurado",
		},
		Future: {
			yo: "hubiere instaurado",
			tú: "hubieres instaurado",
			Ud: "hubiere instaurado",
			nosotros: "hubiéremos instaurado",
			vosotros: "hubiereis instaurado",
			Uds: "hubieren instaurado",
		},
	},
}
