var interpolar = {
	Indicative: {
		Present: {
			yo: "interpolo",
			tú: "interpolas",
			Ud: "interpola",
			nosotros: "interpolamos",
			vosotros: "interpoláis",
			Uds: "interpolan",
		},
		Preterite: {
			yo: "interpolé",
			tú: "interpolaste",
			Ud: "interpoló",
			nosotros: "interpolamos",
			vosotros: "interpolasteis",
			Uds: "interpolaron",
		},
		Imperfect: {
			yo: "interpolaba",
			tú: "interpolabas",
			Ud: "interpolaba",
			nosotros: "interpolábamos",
			vosotros: "interpolabais",
			Uds: "interpolaban",
		},
		Conditional: {
			yo: "interpolaría",
			tú: "interpolarías",
			Ud: "interpolaría",
			nosotros: "interpolaríamos",
			vosotros: "interpolaríais",
			Uds: "interpolarían",
		},
		Future: {
			yo: "interpolaré",
			tú: "interpolarás",
			Ud: "interpolará",
			nosotros: "interpolaremos",
			vosotros: "interpolaréis",
			Uds: "interpolarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "interpole",
			tú: "interpoles",
			Ud: "interpole",
			nosotros: "interpolemos",
			vosotros: "interpoléis",
			Uds: "interpolen",
		},
		Imperfect: {
			yo: "interpolara",
			tú: "interpolaras",
			Ud: "interpolara",
			nosotros: "interpoláramos",
			vosotros: "interpolarais",
			Uds: "interpolaran",
		},
		Imperfect2: {
			yo: "interpolase",
			tú: "interpolases",
			Ud: "interpolase",
			nosotros: "interpolásemos",
			vosotros: "interpolaseis",
			Uds: "interpolasen",
		},
		Future: {
			yo: "interpolare",
			tú: "interpolares",
			Ud: "interpolare",
			nosotros: "interpoláremos",
			vosotros: "interpolareis",
			Uds: "interpolaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "interpola",
			Ud: "interpole",
			nosotros: "interpolemos",
			vosotros: "interpolad",
			Uds: "interpolen",
		},
		Negative: {
			tú: "no interpoles",
			Ud: "no interpole",
			nosotros: "no interpolemos",
			vosotros: "no interpoléis",
			Uds: "no interpolen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy interpolando",
			tú: "estás interpolando",
			Ud: "está interpolando",
			nosotros: "estamos interpolando",
			vosotros: "estáis interpolando",
			Uds: "están interpolando",
		},
		Preterite: {
			yo: "estuve interpolando",
			tú: "estuviste interpolando",
			Ud: "estuvo interpolando",
			nosotros: "estuvimos interpolando",
			vosotros: "estuvisteis interpolando",
			Uds: "estuvieron interpolando",
		},
		Imperfect: {
			Uds: "estaban interpolando",
			yo: "estaba interpolando",
			tú: "estabas interpolando",
			Ud: "estaba interpolando",
			nosotros: "estábamos interpolando",
			vosotros: "estabais interpolando",
		},
		Conditional: {
			yo: "estaría interpolando",
			tú: "estarías interpolando",
			Ud: "estaría interpolando",
			nosotros: "estaríamos interpolando",
			vosotros: "estaríais interpolando",
			Uds: "estarían interpolando",
		},
		Future: {
			yo: "estaré interpolando",
			tú: "estarás interpolando",
			Ud: "estará interpolando",
			nosotros: "estaremos interpolando",
			vosotros: "estaréis interpolando",
			Uds: "estarán interpolando",
		},
	},
	Perfect: {
		Present: {
			yo: "he interpolado",
			tú: "has interpolado",
			Ud: "ha interpolado",
			nosotros: "hemos interpolado",
			vosotros: "habéis interpolado",
			Uds: "han interpolado",
		},
		Preterite: {
			yo: "hube interpolado",
			tú: "hubiste interpolado",
			Ud: "hubo interpolado",
			nosotros: "hubimos interpolado",
			vosotros: "hubisteis interpolado",
			Uds: "hubieron interpolado",
		},
		Past: {
			yo: "había interpolado",
			tú: "habías interpolado",
			Ud: "había interpolado",
			nosotros: "habíamos interpolado",
			vosotros: "habíais interpolado",
			Uds: "habían interpolado",
		},
		Conditional: {
			yo: "habría interpolado",
			tú: "habrías interpolado",
			Ud: "habría interpolado",
			nosotros: "habríamos interpolado",
			vosotros: "habríais interpolado",
			Uds: "habrían interpolado",
		},
		Future: {
			yo: "habré interpolado",
			tú: "habrás interpolado",
			Ud: "habrá interpolado",
			nosotros: "habremos interpolado",
			vosotros: "habréis interpolado",
			Uds: "habrán interpolado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya interpolado",
			tú: "hayas interpolado",
			Ud: "haya interpolado",
			nosotros: "hayamos interpolado",
			vosotros: "hayáis interpolado",
			Uds: "hayan interpolado",
		},
		Past: {
			yo: "hubiera interpolado",
			tú: "hubieras interpolado",
			Ud: "hubiera interpolado",
			nosotros: "hubiéramos interpolado",
			vosotros: "hubierais interpolado",
			Uds: "hubieran interpolado",
		},
		Future: {
			yo: "hubiere interpolado",
			tú: "hubieres interpolado",
			Ud: "hubiere interpolado",
			nosotros: "hubiéremos interpolado",
			vosotros: "hubiereis interpolado",
			Uds: "hubieren interpolado",
		},
	},
}
