var intentar = {
	Indicative: {
		Present: {
			yo: "intento",
			tú: "intentas",
			Ud: "intenta",
			nosotros: "intentamos",
			vosotros: "intentáis",
			Uds: "intentan",
		},
		Preterite: {
			yo: "intenté",
			tú: "intentaste",
			Ud: "intentó",
			nosotros: "intentamos",
			vosotros: "intentasteis",
			Uds: "intentaron",
		},
		Imperfect: {
			yo: "intentaba",
			tú: "intentabas",
			Ud: "intentaba",
			nosotros: "intentábamos",
			vosotros: "intentabais",
			Uds: "intentaban",
		},
		Conditional: {
			yo: "intentaría",
			tú: "intentarías",
			Ud: "intentaría",
			nosotros: "intentaríamos",
			vosotros: "intentaríais",
			Uds: "intentarían",
		},
		Future: {
			yo: "intentaré",
			tú: "intentarás",
			Ud: "intentará",
			nosotros: "intentaremos",
			vosotros: "intentaréis",
			Uds: "intentarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "intente",
			tú: "intentes",
			Ud: "intente",
			nosotros: "intentemos",
			vosotros: "intentéis",
			Uds: "intenten",
		},
		Imperfect: {
			yo: "intentara",
			tú: "intentaras",
			Ud: "intentara",
			nosotros: "intentáramos",
			vosotros: "intentarais",
			Uds: "intentaran",
		},
		Imperfect2: {
			yo: "intentase",
			tú: "intentases",
			Ud: "intentase",
			nosotros: "intentásemos",
			vosotros: "intentaseis",
			Uds: "intentasen",
		},
		Future: {
			yo: "intentare",
			tú: "intentares",
			Ud: "intentare",
			nosotros: "intentáremos",
			vosotros: "intentareis",
			Uds: "intentaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "intenta",
			Ud: "intente",
			nosotros: "intentemos",
			vosotros: "intentad",
			Uds: "intenten",
		},
		Negative: {
			tú: "no intentes",
			Ud: "no intente",
			nosotros: "no intentemos",
			vosotros: "no intentéis",
			Uds: "no intenten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy intentando",
			tú: "estás intentando",
			Ud: "está intentando",
			nosotros: "estamos intentando",
			vosotros: "estáis intentando",
			Uds: "están intentando",
		},
		Preterite: {
			yo: "estuve intentando",
			tú: "estuviste intentando",
			Ud: "estuvo intentando",
			nosotros: "estuvimos intentando",
			vosotros: "estuvisteis intentando",
			Uds: "estuvieron intentando",
		},
		Imperfect: {
			Uds: "estaban intentando",
			yo: "estaba intentando",
			tú: "estabas intentando",
			Ud: "estaba intentando",
			nosotros: "estábamos intentando",
			vosotros: "estabais intentando",
		},
		Conditional: {
			yo: "estaría intentando",
			tú: "estarías intentando",
			Ud: "estaría intentando",
			nosotros: "estaríamos intentando",
			vosotros: "estaríais intentando",
			Uds: "estarían intentando",
		},
		Future: {
			yo: "estaré intentando",
			tú: "estarás intentando",
			Ud: "estará intentando",
			nosotros: "estaremos intentando",
			vosotros: "estaréis intentando",
			Uds: "estarán intentando",
		},
	},
	Perfect: {
		Present: {
			yo: "he intentado",
			tú: "has intentado",
			Ud: "ha intentado",
			nosotros: "hemos intentado",
			vosotros: "habéis intentado",
			Uds: "han intentado",
		},
		Preterite: {
			yo: "hube intentado",
			tú: "hubiste intentado",
			Ud: "hubo intentado",
			nosotros: "hubimos intentado",
			vosotros: "hubisteis intentado",
			Uds: "hubieron intentado",
		},
		Past: {
			yo: "había intentado",
			tú: "habías intentado",
			Ud: "había intentado",
			nosotros: "habíamos intentado",
			vosotros: "habíais intentado",
			Uds: "habían intentado",
		},
		Conditional: {
			yo: "habría intentado",
			tú: "habrías intentado",
			Ud: "habría intentado",
			nosotros: "habríamos intentado",
			vosotros: "habríais intentado",
			Uds: "habrían intentado",
		},
		Future: {
			yo: "habré intentado",
			tú: "habrás intentado",
			Ud: "habrá intentado",
			nosotros: "habremos intentado",
			vosotros: "habréis intentado",
			Uds: "habrán intentado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya intentado",
			tú: "hayas intentado",
			Ud: "haya intentado",
			nosotros: "hayamos intentado",
			vosotros: "hayáis intentado",
			Uds: "hayan intentado",
		},
		Past: {
			yo: "hubiera intentado",
			tú: "hubieras intentado",
			Ud: "hubiera intentado",
			nosotros: "hubiéramos intentado",
			vosotros: "hubierais intentado",
			Uds: "hubieran intentado",
		},
		Future: {
			yo: "hubiere intentado",
			tú: "hubieres intentado",
			Ud: "hubiere intentado",
			nosotros: "hubiéremos intentado",
			vosotros: "hubiereis intentado",
			Uds: "hubieren intentado",
		},
	},
}
