var introducir = {
	Indicative: {
		Present: {
			yo: "introduzco",
			tú: "introduces",
			Ud: "introduce",
			nosotros: "introducimos",
			vosotros: "introducís",
			Uds: "introducen",
		},
		Preterite: {
			yo: "introduje",
			tú: "introdujiste",
			Ud: "introdujo",
			nosotros: "introdujimos",
			vosotros: "introdujisteis",
			Uds: "introdujeron",
		},
		Imperfect: {
			yo: "introducía",
			tú: "introducías",
			Ud: "introducía",
			nosotros: "introducíamos",
			vosotros: "introducíais",
			Uds: "introducían",
		},
		Conditional: {
			yo: "introduciría",
			tú: "introducirías",
			Ud: "introduciría",
			nosotros: "introduciríamos",
			vosotros: "introduciríais",
			Uds: "introducirían",
		},
		Future: {
			yo: "introduciré",
			tú: "introducirás",
			Ud: "introducirá",
			nosotros: "introduciremos",
			vosotros: "introduciréis",
			Uds: "introducirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "introduzca",
			tú: "introduzcas",
			Ud: "introduzca",
			nosotros: "introduzcamos",
			vosotros: "introduzcáis",
			Uds: "introduzcan",
		},
		Imperfect: {
			yo: "introdujera",
			tú: "introdujeras",
			Ud: "introdujera",
			nosotros: "introdujéramos",
			vosotros: "introdujerais",
			Uds: "introdujeran",
		},
		Imperfect2: {
			yo: "introdujese",
			tú: "introdujeses",
			Ud: "introdujese",
			nosotros: "introdujésemos",
			vosotros: "introdujeseis",
			Uds: "introdujesen",
		},
		Future: {
			yo: "introdujere",
			tú: "introdujeres",
			Ud: "introdujere",
			nosotros: "introdujéremos",
			vosotros: "introdujereis",
			Uds: "introdujeren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "introduce",
			Ud: "introduzca",
			nosotros: "introduzcamos",
			vosotros: "introducid",
			Uds: "introduzcan",
		},
		Negative: {
			tú: "no introduzcas",
			Ud: "no introduzca",
			nosotros: "no introduzcamos",
			vosotros: "no introduzcáis",
			Uds: "no introduzcan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy introduciendo",
			tú: "estás introduciendo",
			Ud: "está introduciendo",
			nosotros: "estamos introduciendo",
			vosotros: "estáis introduciendo",
			Uds: "están introduciendo",
		},
		Preterite: {
			yo: "estuve introduciendo",
			tú: "estuviste introduciendo",
			Ud: "estuvo introduciendo",
			nosotros: "estuvimos introduciendo",
			vosotros: "estuvisteis introduciendo",
			Uds: "estuvieron introduciendo",
		},
		Imperfect: {
			Uds: "estaban introduciendo",
			yo: "estaba introduciendo",
			tú: "estabas introduciendo",
			Ud: "estaba introduciendo",
			nosotros: "estábamos introduciendo",
			vosotros: "estabais introduciendo",
		},
		Conditional: {
			yo: "estaría introduciendo",
			tú: "estarías introduciendo",
			Ud: "estaría introduciendo",
			nosotros: "estaríamos introduciendo",
			vosotros: "estaríais introduciendo",
			Uds: "estarían introduciendo",
		},
		Future: {
			yo: "estaré introduciendo",
			tú: "estarás introduciendo",
			Ud: "estará introduciendo",
			nosotros: "estaremos introduciendo",
			vosotros: "estaréis introduciendo",
			Uds: "estarán introduciendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he introducido",
			tú: "has introducido",
			Ud: "ha introducido",
			nosotros: "hemos introducido",
			vosotros: "habéis introducido",
			Uds: "han introducido",
		},
		Preterite: {
			yo: "hube introducido",
			tú: "hubiste introducido",
			Ud: "hubo introducido",
			nosotros: "hubimos introducido",
			vosotros: "hubisteis introducido",
			Uds: "hubieron introducido",
		},
		Past: {
			yo: "había introducido",
			tú: "habías introducido",
			Ud: "había introducido",
			nosotros: "habíamos introducido",
			vosotros: "habíais introducido",
			Uds: "habían introducido",
		},
		Conditional: {
			yo: "habría introducido",
			tú: "habrías introducido",
			Ud: "habría introducido",
			nosotros: "habríamos introducido",
			vosotros: "habríais introducido",
			Uds: "habrían introducido",
		},
		Future: {
			yo: "habré introducido",
			tú: "habrás introducido",
			Ud: "habrá introducido",
			nosotros: "habremos introducido",
			vosotros: "habréis introducido",
			Uds: "habrán introducido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya introducido",
			tú: "hayas introducido",
			Ud: "haya introducido",
			nosotros: "hayamos introducido",
			vosotros: "hayáis introducido",
			Uds: "hayan introducido",
		},
		Past: {
			yo: "hubiera introducido",
			tú: "hubieras introducido",
			Ud: "hubiera introducido",
			nosotros: "hubiéramos introducido",
			vosotros: "hubierais introducido",
			Uds: "hubieran introducido",
		},
		Future: {
			yo: "hubiere introducido",
			tú: "hubieres introducido",
			Ud: "hubiere introducido",
			nosotros: "hubiéremos introducido",
			vosotros: "hubiereis introducido",
			Uds: "hubieren introducido",
		},
	},
}
