var involucrar = {
	Indicative: {
		Present: {
			yo: "involucro",
			tú: "involucras",
			Ud: "involucra",
			nosotros: "involucramos",
			vosotros: "involucráis",
			Uds: "involucran",
		},
		Preterite: {
			yo: "involucré",
			tú: "involucraste",
			Ud: "involucró",
			nosotros: "involucramos",
			vosotros: "involucrasteis",
			Uds: "involucraron",
		},
		Imperfect: {
			yo: "involucraba",
			tú: "involucrabas",
			Ud: "involucraba",
			nosotros: "involucrábamos",
			vosotros: "involucrabais",
			Uds: "involucraban",
		},
		Conditional: {
			yo: "involucraría",
			tú: "involucrarías",
			Ud: "involucraría",
			nosotros: "involucraríamos",
			vosotros: "involucraríais",
			Uds: "involucrarían",
		},
		Future: {
			yo: "involucraré",
			tú: "involucrarás",
			Ud: "involucrará",
			nosotros: "involucraremos",
			vosotros: "involucraréis",
			Uds: "involucrarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "involucre",
			tú: "involucres",
			Ud: "involucre",
			nosotros: "involucremos",
			vosotros: "involucréis",
			Uds: "involucren",
		},
		Imperfect: {
			yo: "involucrara",
			tú: "involucraras",
			Ud: "involucrara",
			nosotros: "involucráramos",
			vosotros: "involucrarais",
			Uds: "involucraran",
		},
		Imperfect2: {
			yo: "involucrase",
			tú: "involucrases",
			Ud: "involucrase",
			nosotros: "involucrásemos",
			vosotros: "involucraseis",
			Uds: "involucrasen",
		},
		Future: {
			yo: "involucrare",
			tú: "involucrares",
			Ud: "involucrare",
			nosotros: "involucráremos",
			vosotros: "involucrareis",
			Uds: "involucraren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "involucra",
			Ud: "involucre",
			nosotros: "involucremos",
			vosotros: "involucrad",
			Uds: "involucren",
		},
		Negative: {
			tú: "no involucres",
			Ud: "no involucre",
			nosotros: "no involucremos",
			vosotros: "no involucréis",
			Uds: "no involucren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy involucrando",
			tú: "estás involucrando",
			Ud: "está involucrando",
			nosotros: "estamos involucrando",
			vosotros: "estáis involucrando",
			Uds: "están involucrando",
		},
		Preterite: {
			yo: "estuve involucrando",
			tú: "estuviste involucrando",
			Ud: "estuvo involucrando",
			nosotros: "estuvimos involucrando",
			vosotros: "estuvisteis involucrando",
			Uds: "estuvieron involucrando",
		},
		Imperfect: {
			Uds: "estaban involucrando",
			yo: "estaba involucrando",
			tú: "estabas involucrando",
			Ud: "estaba involucrando",
			nosotros: "estábamos involucrando",
			vosotros: "estabais involucrando",
		},
		Conditional: {
			yo: "estaría involucrando",
			tú: "estarías involucrando",
			Ud: "estaría involucrando",
			nosotros: "estaríamos involucrando",
			vosotros: "estaríais involucrando",
			Uds: "estarían involucrando",
		},
		Future: {
			yo: "estaré involucrando",
			tú: "estarás involucrando",
			Ud: "estará involucrando",
			nosotros: "estaremos involucrando",
			vosotros: "estaréis involucrando",
			Uds: "estarán involucrando",
		},
	},
	Perfect: {
		Present: {
			yo: "he involucrado",
			tú: "has involucrado",
			Ud: "ha involucrado",
			nosotros: "hemos involucrado",
			vosotros: "habéis involucrado",
			Uds: "han involucrado",
		},
		Preterite: {
			yo: "hube involucrado",
			tú: "hubiste involucrado",
			Ud: "hubo involucrado",
			nosotros: "hubimos involucrado",
			vosotros: "hubisteis involucrado",
			Uds: "hubieron involucrado",
		},
		Past: {
			yo: "había involucrado",
			tú: "habías involucrado",
			Ud: "había involucrado",
			nosotros: "habíamos involucrado",
			vosotros: "habíais involucrado",
			Uds: "habían involucrado",
		},
		Conditional: {
			yo: "habría involucrado",
			tú: "habrías involucrado",
			Ud: "habría involucrado",
			nosotros: "habríamos involucrado",
			vosotros: "habríais involucrado",
			Uds: "habrían involucrado",
		},
		Future: {
			yo: "habré involucrado",
			tú: "habrás involucrado",
			Ud: "habrá involucrado",
			nosotros: "habremos involucrado",
			vosotros: "habréis involucrado",
			Uds: "habrán involucrado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya involucrado",
			tú: "hayas involucrado",
			Ud: "haya involucrado",
			nosotros: "hayamos involucrado",
			vosotros: "hayáis involucrado",
			Uds: "hayan involucrado",
		},
		Past: {
			yo: "hubiera involucrado",
			tú: "hubieras involucrado",
			Ud: "hubiera involucrado",
			nosotros: "hubiéramos involucrado",
			vosotros: "hubierais involucrado",
			Uds: "hubieran involucrado",
		},
		Future: {
			yo: "hubiere involucrado",
			tú: "hubieres involucrado",
			Ud: "hubiere involucrado",
			nosotros: "hubiéremos involucrado",
			vosotros: "hubiereis involucrado",
			Uds: "hubieren involucrado",
		},
	},
}
