var inyectar = {
	Indicative: {
		Present: {
			yo: "inyecto",
			tú: "inyectas",
			Ud: "inyecta",
			nosotros: "inyectamos",
			vosotros: "inyectáis",
			Uds: "inyectan",
		},
		Preterite: {
			yo: "inyecté",
			tú: "inyectaste",
			Ud: "inyectó",
			nosotros: "inyectamos",
			vosotros: "inyectasteis",
			Uds: "inyectaron",
		},
		Imperfect: {
			yo: "inyectaba",
			tú: "inyectabas",
			Ud: "inyectaba",
			nosotros: "inyectábamos",
			vosotros: "inyectabais",
			Uds: "inyectaban",
		},
		Conditional: {
			yo: "inyectaría",
			tú: "inyectarías",
			Ud: "inyectaría",
			nosotros: "inyectaríamos",
			vosotros: "inyectaríais",
			Uds: "inyectarían",
		},
		Future: {
			yo: "inyectaré",
			tú: "inyectarás",
			Ud: "inyectará",
			nosotros: "inyectaremos",
			vosotros: "inyectaréis",
			Uds: "inyectarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "inyecte",
			tú: "inyectes",
			Ud: "inyecte",
			nosotros: "inyectemos",
			vosotros: "inyectéis",
			Uds: "inyecten",
		},
		Imperfect: {
			yo: "inyectara",
			tú: "inyectaras",
			Ud: "inyectara",
			nosotros: "inyectáramos",
			vosotros: "inyectarais",
			Uds: "inyectaran",
		},
		Imperfect2: {
			yo: "inyectase",
			tú: "inyectases",
			Ud: "inyectase",
			nosotros: "inyectásemos",
			vosotros: "inyectaseis",
			Uds: "inyectasen",
		},
		Future: {
			yo: "inyectare",
			tú: "inyectares",
			Ud: "inyectare",
			nosotros: "inyectáremos",
			vosotros: "inyectareis",
			Uds: "inyectaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "inyecta",
			Ud: "inyecte",
			nosotros: "inyectemos",
			vosotros: "inyectad",
			Uds: "inyecten",
		},
		Negative: {
			tú: "no inyectes",
			Ud: "no inyecte",
			nosotros: "no inyectemos",
			vosotros: "no inyectéis",
			Uds: "no inyecten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy inyectando",
			tú: "estás inyectando",
			Ud: "está inyectando",
			nosotros: "estamos inyectando",
			vosotros: "estáis inyectando",
			Uds: "están inyectando",
		},
		Preterite: {
			yo: "estuve inyectando",
			tú: "estuviste inyectando",
			Ud: "estuvo inyectando",
			nosotros: "estuvimos inyectando",
			vosotros: "estuvisteis inyectando",
			Uds: "estuvieron inyectando",
		},
		Imperfect: {
			Uds: "estaban inyectando",
			yo: "estaba inyectando",
			tú: "estabas inyectando",
			Ud: "estaba inyectando",
			nosotros: "estábamos inyectando",
			vosotros: "estabais inyectando",
		},
		Conditional: {
			yo: "estaría inyectando",
			tú: "estarías inyectando",
			Ud: "estaría inyectando",
			nosotros: "estaríamos inyectando",
			vosotros: "estaríais inyectando",
			Uds: "estarían inyectando",
		},
		Future: {
			yo: "estaré inyectando",
			tú: "estarás inyectando",
			Ud: "estará inyectando",
			nosotros: "estaremos inyectando",
			vosotros: "estaréis inyectando",
			Uds: "estarán inyectando",
		},
	},
	Perfect: {
		Present: {
			yo: "he inyectado",
			tú: "has inyectado",
			Ud: "ha inyectado",
			nosotros: "hemos inyectado",
			vosotros: "habéis inyectado",
			Uds: "han inyectado",
		},
		Preterite: {
			yo: "hube inyectado",
			tú: "hubiste inyectado",
			Ud: "hubo inyectado",
			nosotros: "hubimos inyectado",
			vosotros: "hubisteis inyectado",
			Uds: "hubieron inyectado",
		},
		Past: {
			yo: "había inyectado",
			tú: "habías inyectado",
			Ud: "había inyectado",
			nosotros: "habíamos inyectado",
			vosotros: "habíais inyectado",
			Uds: "habían inyectado",
		},
		Conditional: {
			yo: "habría inyectado",
			tú: "habrías inyectado",
			Ud: "habría inyectado",
			nosotros: "habríamos inyectado",
			vosotros: "habríais inyectado",
			Uds: "habrían inyectado",
		},
		Future: {
			yo: "habré inyectado",
			tú: "habrás inyectado",
			Ud: "habrá inyectado",
			nosotros: "habremos inyectado",
			vosotros: "habréis inyectado",
			Uds: "habrán inyectado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya inyectado",
			tú: "hayas inyectado",
			Ud: "haya inyectado",
			nosotros: "hayamos inyectado",
			vosotros: "hayáis inyectado",
			Uds: "hayan inyectado",
		},
		Past: {
			yo: "hubiera inyectado",
			tú: "hubieras inyectado",
			Ud: "hubiera inyectado",
			nosotros: "hubiéramos inyectado",
			vosotros: "hubierais inyectado",
			Uds: "hubieran inyectado",
		},
		Future: {
			yo: "hubiere inyectado",
			tú: "hubieres inyectado",
			Ud: "hubiere inyectado",
			nosotros: "hubiéremos inyectado",
			vosotros: "hubiereis inyectado",
			Uds: "hubieren inyectado",
		},
	},
}
