var jadear = {
	Indicative: {
		Present: {
			yo: "jadeo",
			tú: "jadeas",
			Ud: "jadea",
			nosotros: "jadeamos",
			vosotros: "jadeáis",
			Uds: "jadean",
		},
		Preterite: {
			yo: "jadeé",
			tú: "jadeaste",
			Ud: "jadeó",
			nosotros: "jadeamos",
			vosotros: "jadeasteis",
			Uds: "jadearon",
		},
		Imperfect: {
			yo: "jadeaba",
			tú: "jadeabas",
			Ud: "jadeaba",
			nosotros: "jadeábamos",
			vosotros: "jadeabais",
			Uds: "jadeaban",
		},
		Conditional: {
			yo: "jadearía",
			tú: "jadearías",
			Ud: "jadearía",
			nosotros: "jadearíamos",
			vosotros: "jadearíais",
			Uds: "jadearían",
		},
		Future: {
			yo: "jadearé",
			tú: "jadearás",
			Ud: "jadeará",
			nosotros: "jadearemos",
			vosotros: "jadearéis",
			Uds: "jadearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "jadee",
			tú: "jadees",
			Ud: "jadee",
			nosotros: "jadeemos",
			vosotros: "jadeéis",
			Uds: "jadeen",
		},
		Imperfect: {
			yo: "jadeara",
			tú: "jadearas",
			Ud: "jadeara",
			nosotros: "jadeáramos",
			vosotros: "jadearais",
			Uds: "jadearan",
		},
		Imperfect2: {
			yo: "jadease",
			tú: "jadeases",
			Ud: "jadease",
			nosotros: "jadeásemos",
			vosotros: "jadeaseis",
			Uds: "jadeasen",
		},
		Future: {
			yo: "jadeare",
			tú: "jadeares",
			Ud: "jadeare",
			nosotros: "jadeáremos",
			vosotros: "jadeareis",
			Uds: "jadearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "jadea",
			Ud: "jadee",
			nosotros: "jadeemos",
			vosotros: "jadead",
			Uds: "jadeen",
		},
		Negative: {
			tú: "no jadees",
			Ud: "no jadee",
			nosotros: "no jadeemos",
			vosotros: "no jadeéis",
			Uds: "no jadeen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy jadeando",
			tú: "estás jadeando",
			Ud: "está jadeando",
			nosotros: "estamos jadeando",
			vosotros: "estáis jadeando",
			Uds: "están jadeando",
		},
		Preterite: {
			yo: "estuve jadeando",
			tú: "estuviste jadeando",
			Ud: "estuvo jadeando",
			nosotros: "estuvimos jadeando",
			vosotros: "estuvisteis jadeando",
			Uds: "estuvieron jadeando",
		},
		Imperfect: {
			Uds: "estaban jadeando",
			yo: "estaba jadeando",
			tú: "estabas jadeando",
			Ud: "estaba jadeando",
			nosotros: "estábamos jadeando",
			vosotros: "estabais jadeando",
		},
		Conditional: {
			yo: "estaría jadeando",
			tú: "estarías jadeando",
			Ud: "estaría jadeando",
			nosotros: "estaríamos jadeando",
			vosotros: "estaríais jadeando",
			Uds: "estarían jadeando",
		},
		Future: {
			yo: "estaré jadeando",
			tú: "estarás jadeando",
			Ud: "estará jadeando",
			nosotros: "estaremos jadeando",
			vosotros: "estaréis jadeando",
			Uds: "estarán jadeando",
		},
	},
	Perfect: {
		Present: {
			yo: "he jadeado",
			tú: "has jadeado",
			Ud: "ha jadeado",
			nosotros: "hemos jadeado",
			vosotros: "habéis jadeado",
			Uds: "han jadeado",
		},
		Preterite: {
			yo: "hube jadeado",
			tú: "hubiste jadeado",
			Ud: "hubo jadeado",
			nosotros: "hubimos jadeado",
			vosotros: "hubisteis jadeado",
			Uds: "hubieron jadeado",
		},
		Past: {
			yo: "había jadeado",
			tú: "habías jadeado",
			Ud: "había jadeado",
			nosotros: "habíamos jadeado",
			vosotros: "habíais jadeado",
			Uds: "habían jadeado",
		},
		Conditional: {
			yo: "habría jadeado",
			tú: "habrías jadeado",
			Ud: "habría jadeado",
			nosotros: "habríamos jadeado",
			vosotros: "habríais jadeado",
			Uds: "habrían jadeado",
		},
		Future: {
			yo: "habré jadeado",
			tú: "habrás jadeado",
			Ud: "habrá jadeado",
			nosotros: "habremos jadeado",
			vosotros: "habréis jadeado",
			Uds: "habrán jadeado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya jadeado",
			tú: "hayas jadeado",
			Ud: "haya jadeado",
			nosotros: "hayamos jadeado",
			vosotros: "hayáis jadeado",
			Uds: "hayan jadeado",
		},
		Past: {
			yo: "hubiera jadeado",
			tú: "hubieras jadeado",
			Ud: "hubiera jadeado",
			nosotros: "hubiéramos jadeado",
			vosotros: "hubierais jadeado",
			Uds: "hubieran jadeado",
		},
		Future: {
			yo: "hubiere jadeado",
			tú: "hubieres jadeado",
			Ud: "hubiere jadeado",
			nosotros: "hubiéremos jadeado",
			vosotros: "hubiereis jadeado",
			Uds: "hubieren jadeado",
		},
	},
}
