var juntar = {
	Indicative: {
		Present: {
			yo: "junto",
			tú: "juntas",
			Ud: "junta",
			nosotros: "juntamos",
			vosotros: "juntáis",
			Uds: "juntan",
		},
		Preterite: {
			yo: "junté",
			tú: "juntaste",
			Ud: "juntó",
			nosotros: "juntamos",
			vosotros: "juntasteis",
			Uds: "juntaron",
		},
		Imperfect: {
			yo: "juntaba",
			tú: "juntabas",
			Ud: "juntaba",
			nosotros: "juntábamos",
			vosotros: "juntabais",
			Uds: "juntaban",
		},
		Conditional: {
			yo: "juntaría",
			tú: "juntarías",
			Ud: "juntaría",
			nosotros: "juntaríamos",
			vosotros: "juntaríais",
			Uds: "juntarían",
		},
		Future: {
			yo: "juntaré",
			tú: "juntarás",
			Ud: "juntará",
			nosotros: "juntaremos",
			vosotros: "juntaréis",
			Uds: "juntarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "junte",
			tú: "juntes",
			Ud: "junte",
			nosotros: "juntemos",
			vosotros: "juntéis",
			Uds: "junten",
		},
		Imperfect: {
			yo: "juntara",
			tú: "juntaras",
			Ud: "juntara",
			nosotros: "juntáramos",
			vosotros: "juntarais",
			Uds: "juntaran",
		},
		Imperfect2: {
			yo: "juntase",
			tú: "juntases",
			Ud: "juntase",
			nosotros: "juntásemos",
			vosotros: "juntaseis",
			Uds: "juntasen",
		},
		Future: {
			yo: "juntare",
			tú: "juntares",
			Ud: "juntare",
			nosotros: "juntáremos",
			vosotros: "juntareis",
			Uds: "juntaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "junta",
			Ud: "junte",
			nosotros: "juntemos",
			vosotros: "juntad",
			Uds: "junten",
		},
		Negative: {
			tú: "no juntes",
			Ud: "no junte",
			nosotros: "no juntemos",
			vosotros: "no juntéis",
			Uds: "no junten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy juntando",
			tú: "estás juntando",
			Ud: "está juntando",
			nosotros: "estamos juntando",
			vosotros: "estáis juntando",
			Uds: "están juntando",
		},
		Preterite: {
			yo: "estuve juntando",
			tú: "estuviste juntando",
			Ud: "estuvo juntando",
			nosotros: "estuvimos juntando",
			vosotros: "estuvisteis juntando",
			Uds: "estuvieron juntando",
		},
		Imperfect: {
			Uds: "estaban juntando",
			yo: "estaba juntando",
			tú: "estabas juntando",
			Ud: "estaba juntando",
			nosotros: "estábamos juntando",
			vosotros: "estabais juntando",
		},
		Conditional: {
			yo: "estaría juntando",
			tú: "estarías juntando",
			Ud: "estaría juntando",
			nosotros: "estaríamos juntando",
			vosotros: "estaríais juntando",
			Uds: "estarían juntando",
		},
		Future: {
			yo: "estaré juntando",
			tú: "estarás juntando",
			Ud: "estará juntando",
			nosotros: "estaremos juntando",
			vosotros: "estaréis juntando",
			Uds: "estarán juntando",
		},
	},
	Perfect: {
		Present: {
			yo: "he juntado",
			tú: "has juntado",
			Ud: "ha juntado",
			nosotros: "hemos juntado",
			vosotros: "habéis juntado",
			Uds: "han juntado",
		},
		Preterite: {
			yo: "hube juntado",
			tú: "hubiste juntado",
			Ud: "hubo juntado",
			nosotros: "hubimos juntado",
			vosotros: "hubisteis juntado",
			Uds: "hubieron juntado",
		},
		Past: {
			yo: "había juntado",
			tú: "habías juntado",
			Ud: "había juntado",
			nosotros: "habíamos juntado",
			vosotros: "habíais juntado",
			Uds: "habían juntado",
		},
		Conditional: {
			yo: "habría juntado",
			tú: "habrías juntado",
			Ud: "habría juntado",
			nosotros: "habríamos juntado",
			vosotros: "habríais juntado",
			Uds: "habrían juntado",
		},
		Future: {
			yo: "habré juntado",
			tú: "habrás juntado",
			Ud: "habrá juntado",
			nosotros: "habremos juntado",
			vosotros: "habréis juntado",
			Uds: "habrán juntado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya juntado",
			tú: "hayas juntado",
			Ud: "haya juntado",
			nosotros: "hayamos juntado",
			vosotros: "hayáis juntado",
			Uds: "hayan juntado",
		},
		Past: {
			yo: "hubiera juntado",
			tú: "hubieras juntado",
			Ud: "hubiera juntado",
			nosotros: "hubiéramos juntado",
			vosotros: "hubierais juntado",
			Uds: "hubieran juntado",
		},
		Future: {
			yo: "hubiere juntado",
			tú: "hubieres juntado",
			Ud: "hubiere juntado",
			nosotros: "hubiéremos juntado",
			vosotros: "hubiereis juntado",
			Uds: "hubieren juntado",
		},
	},
}
