var justificar = {
	Indicative: {
		Present: {
			yo: "justifico",
			tú: "justificas",
			Ud: "justifica",
			nosotros: "justificamos",
			vosotros: "justificáis",
			Uds: "justifican",
		},
		Preterite: {
			yo: "justifiqué",
			tú: "justificaste",
			Ud: "justificó",
			nosotros: "justificamos",
			vosotros: "justificasteis",
			Uds: "justificaron",
		},
		Imperfect: {
			yo: "justificaba",
			tú: "justificabas",
			Ud: "justificaba",
			nosotros: "justificábamos",
			vosotros: "justificabais",
			Uds: "justificaban",
		},
		Conditional: {
			yo: "justificaría",
			tú: "justificarías",
			Ud: "justificaría",
			nosotros: "justificaríamos",
			vosotros: "justificaríais",
			Uds: "justificarían",
		},
		Future: {
			yo: "justificaré",
			tú: "justificarás",
			Ud: "justificará",
			nosotros: "justificaremos",
			vosotros: "justificaréis",
			Uds: "justificarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "justifique",
			tú: "justifiques",
			Ud: "justifique",
			nosotros: "justifiquemos",
			vosotros: "justifiquéis",
			Uds: "justifiquen",
		},
		Imperfect: {
			yo: "justificara",
			tú: "justificaras",
			Ud: "justificara",
			nosotros: "justificáramos",
			vosotros: "justificarais",
			Uds: "justificaran",
		},
		Imperfect2: {
			yo: "justificase",
			tú: "justificases",
			Ud: "justificase",
			nosotros: "justificásemos",
			vosotros: "justificaseis",
			Uds: "justificasen",
		},
		Future: {
			yo: "justificare",
			tú: "justificares",
			Ud: "justificare",
			nosotros: "justificáremos",
			vosotros: "justificareis",
			Uds: "justificaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "justifica",
			Ud: "justifique",
			nosotros: "justifiquemos",
			vosotros: "justificad",
			Uds: "justifiquen",
		},
		Negative: {
			tú: "no justifiques",
			Ud: "no justifique",
			nosotros: "no justifiquemos",
			vosotros: "no justifiquéis",
			Uds: "no justifiquen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy justificando",
			tú: "estás justificando",
			Ud: "está justificando",
			nosotros: "estamos justificando",
			vosotros: "estáis justificando",
			Uds: "están justificando",
		},
		Preterite: {
			yo: "estuve justificando",
			tú: "estuviste justificando",
			Ud: "estuvo justificando",
			nosotros: "estuvimos justificando",
			vosotros: "estuvisteis justificando",
			Uds: "estuvieron justificando",
		},
		Imperfect: {
			Uds: "estaban justificando",
			yo: "estaba justificando",
			tú: "estabas justificando",
			Ud: "estaba justificando",
			nosotros: "estábamos justificando",
			vosotros: "estabais justificando",
		},
		Conditional: {
			yo: "estaría justificando",
			tú: "estarías justificando",
			Ud: "estaría justificando",
			nosotros: "estaríamos justificando",
			vosotros: "estaríais justificando",
			Uds: "estarían justificando",
		},
		Future: {
			yo: "estaré justificando",
			tú: "estarás justificando",
			Ud: "estará justificando",
			nosotros: "estaremos justificando",
			vosotros: "estaréis justificando",
			Uds: "estarán justificando",
		},
	},
	Perfect: {
		Present: {
			yo: "he justificado",
			tú: "has justificado",
			Ud: "ha justificado",
			nosotros: "hemos justificado",
			vosotros: "habéis justificado",
			Uds: "han justificado",
		},
		Preterite: {
			yo: "hube justificado",
			tú: "hubiste justificado",
			Ud: "hubo justificado",
			nosotros: "hubimos justificado",
			vosotros: "hubisteis justificado",
			Uds: "hubieron justificado",
		},
		Past: {
			yo: "había justificado",
			tú: "habías justificado",
			Ud: "había justificado",
			nosotros: "habíamos justificado",
			vosotros: "habíais justificado",
			Uds: "habían justificado",
		},
		Conditional: {
			yo: "habría justificado",
			tú: "habrías justificado",
			Ud: "habría justificado",
			nosotros: "habríamos justificado",
			vosotros: "habríais justificado",
			Uds: "habrían justificado",
		},
		Future: {
			yo: "habré justificado",
			tú: "habrás justificado",
			Ud: "habrá justificado",
			nosotros: "habremos justificado",
			vosotros: "habréis justificado",
			Uds: "habrán justificado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya justificado",
			tú: "hayas justificado",
			Ud: "haya justificado",
			nosotros: "hayamos justificado",
			vosotros: "hayáis justificado",
			Uds: "hayan justificado",
		},
		Past: {
			yo: "hubiera justificado",
			tú: "hubieras justificado",
			Ud: "hubiera justificado",
			nosotros: "hubiéramos justificado",
			vosotros: "hubierais justificado",
			Uds: "hubieran justificado",
		},
		Future: {
			yo: "hubiere justificado",
			tú: "hubieres justificado",
			Ud: "hubiere justificado",
			nosotros: "hubiéremos justificado",
			vosotros: "hubiereis justificado",
			Uds: "hubieren justificado",
		},
	},
}
