var ladrar = {
	Indicative: {
		Present: {
			yo: "ladro",
			tú: "ladras",
			Ud: "ladra",
			nosotros: "ladramos",
			vosotros: "ladráis",
			Uds: "ladran",
		},
		Preterite: {
			yo: "ladré",
			tú: "ladraste",
			Ud: "ladró",
			nosotros: "ladramos",
			vosotros: "ladrasteis",
			Uds: "ladraron",
		},
		Imperfect: {
			yo: "ladraba",
			tú: "ladrabas",
			Ud: "ladraba",
			nosotros: "ladrábamos",
			vosotros: "ladrabais",
			Uds: "ladraban",
		},
		Conditional: {
			yo: "ladraría",
			tú: "ladrarías",
			Ud: "ladraría",
			nosotros: "ladraríamos",
			vosotros: "ladraríais",
			Uds: "ladrarían",
		},
		Future: {
			yo: "ladraré",
			tú: "ladrarás",
			Ud: "ladrará",
			nosotros: "ladraremos",
			vosotros: "ladraréis",
			Uds: "ladrarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "ladre",
			tú: "ladres",
			Ud: "ladre",
			nosotros: "ladremos",
			vosotros: "ladréis",
			Uds: "ladren",
		},
		Imperfect: {
			yo: "ladrara",
			tú: "ladraras",
			Ud: "ladrara",
			nosotros: "ladráramos",
			vosotros: "ladrarais",
			Uds: "ladraran",
		},
		Imperfect2: {
			yo: "ladrase",
			tú: "ladrases",
			Ud: "ladrase",
			nosotros: "ladrásemos",
			vosotros: "ladraseis",
			Uds: "ladrasen",
		},
		Future: {
			yo: "ladrare",
			tú: "ladrares",
			Ud: "ladrare",
			nosotros: "ladráremos",
			vosotros: "ladrareis",
			Uds: "ladraren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "ladra",
			Ud: "ladre",
			nosotros: "ladremos",
			vosotros: "ladrad",
			Uds: "ladren",
		},
		Negative: {
			tú: "no ladres",
			Ud: "no ladre",
			nosotros: "no ladremos",
			vosotros: "no ladréis",
			Uds: "no ladren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy ladrando",
			tú: "estás ladrando",
			Ud: "está ladrando",
			nosotros: "estamos ladrando",
			vosotros: "estáis ladrando",
			Uds: "están ladrando",
		},
		Preterite: {
			yo: "estuve ladrando",
			tú: "estuviste ladrando",
			Ud: "estuvo ladrando",
			nosotros: "estuvimos ladrando",
			vosotros: "estuvisteis ladrando",
			Uds: "estuvieron ladrando",
		},
		Imperfect: {
			Uds: "estaban ladrando",
			yo: "estaba ladrando",
			tú: "estabas ladrando",
			Ud: "estaba ladrando",
			nosotros: "estábamos ladrando",
			vosotros: "estabais ladrando",
		},
		Conditional: {
			yo: "estaría ladrando",
			tú: "estarías ladrando",
			Ud: "estaría ladrando",
			nosotros: "estaríamos ladrando",
			vosotros: "estaríais ladrando",
			Uds: "estarían ladrando",
		},
		Future: {
			yo: "estaré ladrando",
			tú: "estarás ladrando",
			Ud: "estará ladrando",
			nosotros: "estaremos ladrando",
			vosotros: "estaréis ladrando",
			Uds: "estarán ladrando",
		},
	},
	Perfect: {
		Present: {
			yo: "he ladrado",
			tú: "has ladrado",
			Ud: "ha ladrado",
			nosotros: "hemos ladrado",
			vosotros: "habéis ladrado",
			Uds: "han ladrado",
		},
		Preterite: {
			yo: "hube ladrado",
			tú: "hubiste ladrado",
			Ud: "hubo ladrado",
			nosotros: "hubimos ladrado",
			vosotros: "hubisteis ladrado",
			Uds: "hubieron ladrado",
		},
		Past: {
			yo: "había ladrado",
			tú: "habías ladrado",
			Ud: "había ladrado",
			nosotros: "habíamos ladrado",
			vosotros: "habíais ladrado",
			Uds: "habían ladrado",
		},
		Conditional: {
			yo: "habría ladrado",
			tú: "habrías ladrado",
			Ud: "habría ladrado",
			nosotros: "habríamos ladrado",
			vosotros: "habríais ladrado",
			Uds: "habrían ladrado",
		},
		Future: {
			yo: "habré ladrado",
			tú: "habrás ladrado",
			Ud: "habrá ladrado",
			nosotros: "habremos ladrado",
			vosotros: "habréis ladrado",
			Uds: "habrán ladrado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya ladrado",
			tú: "hayas ladrado",
			Ud: "haya ladrado",
			nosotros: "hayamos ladrado",
			vosotros: "hayáis ladrado",
			Uds: "hayan ladrado",
		},
		Past: {
			yo: "hubiera ladrado",
			tú: "hubieras ladrado",
			Ud: "hubiera ladrado",
			nosotros: "hubiéramos ladrado",
			vosotros: "hubierais ladrado",
			Uds: "hubieran ladrado",
		},
		Future: {
			yo: "hubiere ladrado",
			tú: "hubieres ladrado",
			Ud: "hubiere ladrado",
			nosotros: "hubiéremos ladrado",
			vosotros: "hubiereis ladrado",
			Uds: "hubieren ladrado",
		},
	},
}
