var legislar = {
	Indicative: {
		Present: {
			yo: "legislo",
			tú: "legislas",
			Ud: "legisla",
			nosotros: "legislamos",
			vosotros: "legisláis",
			Uds: "legislan",
		},
		Preterite: {
			yo: "legislé",
			tú: "legislaste",
			Ud: "legisló",
			nosotros: "legislamos",
			vosotros: "legislasteis",
			Uds: "legislaron",
		},
		Imperfect: {
			yo: "legislaba",
			tú: "legislabas",
			Ud: "legislaba",
			nosotros: "legislábamos",
			vosotros: "legislabais",
			Uds: "legislaban",
		},
		Conditional: {
			yo: "legislaría",
			tú: "legislarías",
			Ud: "legislaría",
			nosotros: "legislaríamos",
			vosotros: "legislaríais",
			Uds: "legislarían",
		},
		Future: {
			yo: "legislaré",
			tú: "legislarás",
			Ud: "legislará",
			nosotros: "legislaremos",
			vosotros: "legislaréis",
			Uds: "legislarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "legisle",
			tú: "legisles",
			Ud: "legisle",
			nosotros: "legislemos",
			vosotros: "legisléis",
			Uds: "legislen",
		},
		Imperfect: {
			yo: "legislara",
			tú: "legislaras",
			Ud: "legislara",
			nosotros: "legisláramos",
			vosotros: "legislarais",
			Uds: "legislaran",
		},
		Imperfect2: {
			yo: "legislase",
			tú: "legislases",
			Ud: "legislase",
			nosotros: "legislásemos",
			vosotros: "legislaseis",
			Uds: "legislasen",
		},
		Future: {
			yo: "legislare",
			tú: "legislares",
			Ud: "legislare",
			nosotros: "legisláremos",
			vosotros: "legislareis",
			Uds: "legislaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "legisla",
			Ud: "legisle",
			nosotros: "legislemos",
			vosotros: "legislad",
			Uds: "legislen",
		},
		Negative: {
			tú: "no legisles",
			Ud: "no legisle",
			nosotros: "no legislemos",
			vosotros: "no legisléis",
			Uds: "no legislen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy legislando",
			tú: "estás legislando",
			Ud: "está legislando",
			nosotros: "estamos legislando",
			vosotros: "estáis legislando",
			Uds: "están legislando",
		},
		Preterite: {
			yo: "estuve legislando",
			tú: "estuviste legislando",
			Ud: "estuvo legislando",
			nosotros: "estuvimos legislando",
			vosotros: "estuvisteis legislando",
			Uds: "estuvieron legislando",
		},
		Imperfect: {
			Uds: "estaban legislando",
			yo: "estaba legislando",
			tú: "estabas legislando",
			Ud: "estaba legislando",
			nosotros: "estábamos legislando",
			vosotros: "estabais legislando",
		},
		Conditional: {
			yo: "estaría legislando",
			tú: "estarías legislando",
			Ud: "estaría legislando",
			nosotros: "estaríamos legislando",
			vosotros: "estaríais legislando",
			Uds: "estarían legislando",
		},
		Future: {
			yo: "estaré legislando",
			tú: "estarás legislando",
			Ud: "estará legislando",
			nosotros: "estaremos legislando",
			vosotros: "estaréis legislando",
			Uds: "estarán legislando",
		},
	},
	Perfect: {
		Present: {
			yo: "he legislado",
			tú: "has legislado",
			Ud: "ha legislado",
			nosotros: "hemos legislado",
			vosotros: "habéis legislado",
			Uds: "han legislado",
		},
		Preterite: {
			yo: "hube legislado",
			tú: "hubiste legislado",
			Ud: "hubo legislado",
			nosotros: "hubimos legislado",
			vosotros: "hubisteis legislado",
			Uds: "hubieron legislado",
		},
		Past: {
			yo: "había legislado",
			tú: "habías legislado",
			Ud: "había legislado",
			nosotros: "habíamos legislado",
			vosotros: "habíais legislado",
			Uds: "habían legislado",
		},
		Conditional: {
			yo: "habría legislado",
			tú: "habrías legislado",
			Ud: "habría legislado",
			nosotros: "habríamos legislado",
			vosotros: "habríais legislado",
			Uds: "habrían legislado",
		},
		Future: {
			yo: "habré legislado",
			tú: "habrás legislado",
			Ud: "habrá legislado",
			nosotros: "habremos legislado",
			vosotros: "habréis legislado",
			Uds: "habrán legislado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya legislado",
			tú: "hayas legislado",
			Ud: "haya legislado",
			nosotros: "hayamos legislado",
			vosotros: "hayáis legislado",
			Uds: "hayan legislado",
		},
		Past: {
			yo: "hubiera legislado",
			tú: "hubieras legislado",
			Ud: "hubiera legislado",
			nosotros: "hubiéramos legislado",
			vosotros: "hubierais legislado",
			Uds: "hubieran legislado",
		},
		Future: {
			yo: "hubiere legislado",
			tú: "hubieres legislado",
			Ud: "hubiere legislado",
			nosotros: "hubiéremos legislado",
			vosotros: "hubiereis legislado",
			Uds: "hubieren legislado",
		},
	},
}
