var lijar = {
	Indicative: {
		Present: {
			yo: "lijo",
			tú: "lijas",
			Ud: "lija",
			nosotros: "lijamos",
			vosotros: "lijáis",
			Uds: "lijan",
		},
		Preterite: {
			yo: "lijé",
			tú: "lijaste",
			Ud: "lijó",
			nosotros: "lijamos",
			vosotros: "lijasteis",
			Uds: "lijaron",
		},
		Imperfect: {
			yo: "lijaba",
			tú: "lijabas",
			Ud: "lijaba",
			nosotros: "lijábamos",
			vosotros: "lijabais",
			Uds: "lijaban",
		},
		Conditional: {
			yo: "lijaría",
			tú: "lijarías",
			Ud: "lijaría",
			nosotros: "lijaríamos",
			vosotros: "lijaríais",
			Uds: "lijarían",
		},
		Future: {
			yo: "lijaré",
			tú: "lijarás",
			Ud: "lijará",
			nosotros: "lijaremos",
			vosotros: "lijaréis",
			Uds: "lijarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "lije",
			tú: "lijes",
			Ud: "lije",
			nosotros: "lijemos",
			vosotros: "lijéis",
			Uds: "lijen",
		},
		Imperfect: {
			yo: "lijara",
			tú: "lijaras",
			Ud: "lijara",
			nosotros: "lijáramos",
			vosotros: "lijarais",
			Uds: "lijaran",
		},
		Imperfect2: {
			yo: "lijase",
			tú: "lijases",
			Ud: "lijase",
			nosotros: "lijásemos",
			vosotros: "lijaseis",
			Uds: "lijasen",
		},
		Future: {
			yo: "lijare",
			tú: "lijares",
			Ud: "lijare",
			nosotros: "lijáremos",
			vosotros: "lijareis",
			Uds: "lijaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "lija",
			Ud: "lije",
			nosotros: "lijemos",
			vosotros: "lijad",
			Uds: "lijen",
		},
		Negative: {
			tú: "no lijes",
			Ud: "no lije",
			nosotros: "no lijemos",
			vosotros: "no lijéis",
			Uds: "no lijen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy lijando",
			tú: "estás lijando",
			Ud: "está lijando",
			nosotros: "estamos lijando",
			vosotros: "estáis lijando",
			Uds: "están lijando",
		},
		Preterite: {
			yo: "estuve lijando",
			tú: "estuviste lijando",
			Ud: "estuvo lijando",
			nosotros: "estuvimos lijando",
			vosotros: "estuvisteis lijando",
			Uds: "estuvieron lijando",
		},
		Imperfect: {
			Uds: "estaban lijando",
			yo: "estaba lijando",
			tú: "estabas lijando",
			Ud: "estaba lijando",
			nosotros: "estábamos lijando",
			vosotros: "estabais lijando",
		},
		Conditional: {
			yo: "estaría lijando",
			tú: "estarías lijando",
			Ud: "estaría lijando",
			nosotros: "estaríamos lijando",
			vosotros: "estaríais lijando",
			Uds: "estarían lijando",
		},
		Future: {
			yo: "estaré lijando",
			tú: "estarás lijando",
			Ud: "estará lijando",
			nosotros: "estaremos lijando",
			vosotros: "estaréis lijando",
			Uds: "estarán lijando",
		},
	},
	Perfect: {
		Present: {
			yo: "he lijado",
			tú: "has lijado",
			Ud: "ha lijado",
			nosotros: "hemos lijado",
			vosotros: "habéis lijado",
			Uds: "han lijado",
		},
		Preterite: {
			yo: "hube lijado",
			tú: "hubiste lijado",
			Ud: "hubo lijado",
			nosotros: "hubimos lijado",
			vosotros: "hubisteis lijado",
			Uds: "hubieron lijado",
		},
		Past: {
			yo: "había lijado",
			tú: "habías lijado",
			Ud: "había lijado",
			nosotros: "habíamos lijado",
			vosotros: "habíais lijado",
			Uds: "habían lijado",
		},
		Conditional: {
			yo: "habría lijado",
			tú: "habrías lijado",
			Ud: "habría lijado",
			nosotros: "habríamos lijado",
			vosotros: "habríais lijado",
			Uds: "habrían lijado",
		},
		Future: {
			yo: "habré lijado",
			tú: "habrás lijado",
			Ud: "habrá lijado",
			nosotros: "habremos lijado",
			vosotros: "habréis lijado",
			Uds: "habrán lijado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya lijado",
			tú: "hayas lijado",
			Ud: "haya lijado",
			nosotros: "hayamos lijado",
			vosotros: "hayáis lijado",
			Uds: "hayan lijado",
		},
		Past: {
			yo: "hubiera lijado",
			tú: "hubieras lijado",
			Ud: "hubiera lijado",
			nosotros: "hubiéramos lijado",
			vosotros: "hubierais lijado",
			Uds: "hubieran lijado",
		},
		Future: {
			yo: "hubiere lijado",
			tú: "hubieres lijado",
			Ud: "hubiere lijado",
			nosotros: "hubiéremos lijado",
			vosotros: "hubiereis lijado",
			Uds: "hubieren lijado",
		},
	},
}
