var limar = {
	Indicative: {
		Present: {
			yo: "limo",
			tú: "limas",
			Ud: "lima",
			nosotros: "limamos",
			vosotros: "limáis",
			Uds: "liman",
		},
		Preterite: {
			yo: "limé",
			tú: "limaste",
			Ud: "limó",
			nosotros: "limamos",
			vosotros: "limasteis",
			Uds: "limaron",
		},
		Imperfect: {
			yo: "limaba",
			tú: "limabas",
			Ud: "limaba",
			nosotros: "limábamos",
			vosotros: "limabais",
			Uds: "limaban",
		},
		Conditional: {
			yo: "limaría",
			tú: "limarías",
			Ud: "limaría",
			nosotros: "limaríamos",
			vosotros: "limaríais",
			Uds: "limarían",
		},
		Future: {
			yo: "limaré",
			tú: "limarás",
			Ud: "limará",
			nosotros: "limaremos",
			vosotros: "limaréis",
			Uds: "limarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "lime",
			tú: "limes",
			Ud: "lime",
			nosotros: "limemos",
			vosotros: "liméis",
			Uds: "limen",
		},
		Imperfect: {
			yo: "limara",
			tú: "limaras",
			Ud: "limara",
			nosotros: "limáramos",
			vosotros: "limarais",
			Uds: "limaran",
		},
		Imperfect2: {
			yo: "limase",
			tú: "limases",
			Ud: "limase",
			nosotros: "limásemos",
			vosotros: "limaseis",
			Uds: "limasen",
		},
		Future: {
			yo: "limare",
			tú: "limares",
			Ud: "limare",
			nosotros: "limáremos",
			vosotros: "limareis",
			Uds: "limaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "lima",
			Ud: "lime",
			nosotros: "limemos",
			vosotros: "limad",
			Uds: "limen",
		},
		Negative: {
			tú: "no limes",
			Ud: "no lime",
			nosotros: "no limemos",
			vosotros: "no liméis",
			Uds: "no limen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy limando",
			tú: "estás limando",
			Ud: "está limando",
			nosotros: "estamos limando",
			vosotros: "estáis limando",
			Uds: "están limando",
		},
		Preterite: {
			yo: "estuve limando",
			tú: "estuviste limando",
			Ud: "estuvo limando",
			nosotros: "estuvimos limando",
			vosotros: "estuvisteis limando",
			Uds: "estuvieron limando",
		},
		Imperfect: {
			Uds: "estaban limando",
			yo: "estaba limando",
			tú: "estabas limando",
			Ud: "estaba limando",
			nosotros: "estábamos limando",
			vosotros: "estabais limando",
		},
		Conditional: {
			yo: "estaría limando",
			tú: "estarías limando",
			Ud: "estaría limando",
			nosotros: "estaríamos limando",
			vosotros: "estaríais limando",
			Uds: "estarían limando",
		},
		Future: {
			yo: "estaré limando",
			tú: "estarás limando",
			Ud: "estará limando",
			nosotros: "estaremos limando",
			vosotros: "estaréis limando",
			Uds: "estarán limando",
		},
	},
	Perfect: {
		Present: {
			yo: "he limado",
			tú: "has limado",
			Ud: "ha limado",
			nosotros: "hemos limado",
			vosotros: "habéis limado",
			Uds: "han limado",
		},
		Preterite: {
			yo: "hube limado",
			tú: "hubiste limado",
			Ud: "hubo limado",
			nosotros: "hubimos limado",
			vosotros: "hubisteis limado",
			Uds: "hubieron limado",
		},
		Past: {
			yo: "había limado",
			tú: "habías limado",
			Ud: "había limado",
			nosotros: "habíamos limado",
			vosotros: "habíais limado",
			Uds: "habían limado",
		},
		Conditional: {
			yo: "habría limado",
			tú: "habrías limado",
			Ud: "habría limado",
			nosotros: "habríamos limado",
			vosotros: "habríais limado",
			Uds: "habrían limado",
		},
		Future: {
			yo: "habré limado",
			tú: "habrás limado",
			Ud: "habrá limado",
			nosotros: "habremos limado",
			vosotros: "habréis limado",
			Uds: "habrán limado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya limado",
			tú: "hayas limado",
			Ud: "haya limado",
			nosotros: "hayamos limado",
			vosotros: "hayáis limado",
			Uds: "hayan limado",
		},
		Past: {
			yo: "hubiera limado",
			tú: "hubieras limado",
			Ud: "hubiera limado",
			nosotros: "hubiéramos limado",
			vosotros: "hubierais limado",
			Uds: "hubieran limado",
		},
		Future: {
			yo: "hubiere limado",
			tú: "hubieres limado",
			Ud: "hubiere limado",
			nosotros: "hubiéremos limado",
			vosotros: "hubiereis limado",
			Uds: "hubieren limado",
		},
	},
}
