var limpiar = {
	Indicative: {
		Present: {
			yo: "limpio",
			tú: "limpias",
			Ud: "limpia",
			nosotros: "limpiamos",
			vosotros: "limpiáis",
			Uds: "limpian",
		},
		Preterite: {
			yo: "limpié",
			tú: "limpiaste",
			Ud: "limpió",
			nosotros: "limpiamos",
			vosotros: "limpiasteis",
			Uds: "limpiaron",
		},
		Imperfect: {
			yo: "limpiaba",
			tú: "limpiabas",
			Ud: "limpiaba",
			nosotros: "limpiábamos",
			vosotros: "limpiabais",
			Uds: "limpiaban",
		},
		Conditional: {
			yo: "limpiaría",
			tú: "limpiarías",
			Ud: "limpiaría",
			nosotros: "limpiaríamos",
			vosotros: "limpiaríais",
			Uds: "limpiarían",
		},
		Future: {
			yo: "limpiaré",
			tú: "limpiarás",
			Ud: "limpiará",
			nosotros: "limpiaremos",
			vosotros: "limpiaréis",
			Uds: "limpiarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "limpie",
			tú: "limpies",
			Ud: "limpie",
			nosotros: "limpiemos",
			vosotros: "limpiéis",
			Uds: "limpien",
		},
		Imperfect: {
			yo: "limpiara",
			tú: "limpiaras",
			Ud: "limpiara",
			nosotros: "limpiáramos",
			vosotros: "limpiarais",
			Uds: "limpiaran",
		},
		Imperfect2: {
			yo: "limpiase",
			tú: "limpiases",
			Ud: "limpiase",
			nosotros: "limpiásemos",
			vosotros: "limpiaseis",
			Uds: "limpiasen",
		},
		Future: {
			yo: "limpiare",
			tú: "limpiares",
			Ud: "limpiare",
			nosotros: "limpiáremos",
			vosotros: "limpiareis",
			Uds: "limpiaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "limpia",
			Ud: "limpie",
			nosotros: "limpiemos",
			vosotros: "limpiad",
			Uds: "limpien",
		},
		Negative: {
			tú: "no limpies",
			Ud: "no limpie",
			nosotros: "no limpiemos",
			vosotros: "no limpiéis",
			Uds: "no limpien",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy limpiando",
			tú: "estás limpiando",
			Ud: "está limpiando",
			nosotros: "estamos limpiando",
			vosotros: "estáis limpiando",
			Uds: "están limpiando",
		},
		Preterite: {
			yo: "estuve limpiando",
			tú: "estuviste limpiando",
			Ud: "estuvo limpiando",
			nosotros: "estuvimos limpiando",
			vosotros: "estuvisteis limpiando",
			Uds: "estuvieron limpiando",
		},
		Imperfect: {
			Uds: "estaban limpiando",
			yo: "estaba limpiando",
			tú: "estabas limpiando",
			Ud: "estaba limpiando",
			nosotros: "estábamos limpiando",
			vosotros: "estabais limpiando",
		},
		Conditional: {
			yo: "estaría limpiando",
			tú: "estarías limpiando",
			Ud: "estaría limpiando",
			nosotros: "estaríamos limpiando",
			vosotros: "estaríais limpiando",
			Uds: "estarían limpiando",
		},
		Future: {
			yo: "estaré limpiando",
			tú: "estarás limpiando",
			Ud: "estará limpiando",
			nosotros: "estaremos limpiando",
			vosotros: "estaréis limpiando",
			Uds: "estarán limpiando",
		},
	},
	Perfect: {
		Present: {
			yo: "he limpiado",
			tú: "has limpiado",
			Ud: "ha limpiado",
			nosotros: "hemos limpiado",
			vosotros: "habéis limpiado",
			Uds: "han limpiado",
		},
		Preterite: {
			yo: "hube limpiado",
			tú: "hubiste limpiado",
			Ud: "hubo limpiado",
			nosotros: "hubimos limpiado",
			vosotros: "hubisteis limpiado",
			Uds: "hubieron limpiado",
		},
		Past: {
			yo: "había limpiado",
			tú: "habías limpiado",
			Ud: "había limpiado",
			nosotros: "habíamos limpiado",
			vosotros: "habíais limpiado",
			Uds: "habían limpiado",
		},
		Conditional: {
			yo: "habría limpiado",
			tú: "habrías limpiado",
			Ud: "habría limpiado",
			nosotros: "habríamos limpiado",
			vosotros: "habríais limpiado",
			Uds: "habrían limpiado",
		},
		Future: {
			yo: "habré limpiado",
			tú: "habrás limpiado",
			Ud: "habrá limpiado",
			nosotros: "habremos limpiado",
			vosotros: "habréis limpiado",
			Uds: "habrán limpiado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya limpiado",
			tú: "hayas limpiado",
			Ud: "haya limpiado",
			nosotros: "hayamos limpiado",
			vosotros: "hayáis limpiado",
			Uds: "hayan limpiado",
		},
		Past: {
			yo: "hubiera limpiado",
			tú: "hubieras limpiado",
			Ud: "hubiera limpiado",
			nosotros: "hubiéramos limpiado",
			vosotros: "hubierais limpiado",
			Uds: "hubieran limpiado",
		},
		Future: {
			yo: "hubiere limpiado",
			tú: "hubieres limpiado",
			Ud: "hubiere limpiado",
			nosotros: "hubiéremos limpiado",
			vosotros: "hubiereis limpiado",
			Uds: "hubieren limpiado",
		},
	},
}
