var linchar = {
	Indicative: {
		Present: {
			yo: "lincho",
			tú: "linchas",
			Ud: "lincha",
			nosotros: "linchamos",
			vosotros: "lincháis",
			Uds: "linchan",
		},
		Preterite: {
			yo: "linché",
			tú: "linchaste",
			Ud: "linchó",
			nosotros: "linchamos",
			vosotros: "linchasteis",
			Uds: "lincharon",
		},
		Imperfect: {
			yo: "linchaba",
			tú: "linchabas",
			Ud: "linchaba",
			nosotros: "linchábamos",
			vosotros: "linchabais",
			Uds: "linchaban",
		},
		Conditional: {
			yo: "lincharía",
			tú: "lincharías",
			Ud: "lincharía",
			nosotros: "lincharíamos",
			vosotros: "lincharíais",
			Uds: "lincharían",
		},
		Future: {
			yo: "lincharé",
			tú: "lincharás",
			Ud: "linchará",
			nosotros: "lincharemos",
			vosotros: "lincharéis",
			Uds: "lincharán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "linche",
			tú: "linches",
			Ud: "linche",
			nosotros: "linchemos",
			vosotros: "linchéis",
			Uds: "linchen",
		},
		Imperfect: {
			yo: "linchara",
			tú: "lincharas",
			Ud: "linchara",
			nosotros: "lincháramos",
			vosotros: "lincharais",
			Uds: "lincharan",
		},
		Imperfect2: {
			yo: "linchase",
			tú: "linchases",
			Ud: "linchase",
			nosotros: "linchásemos",
			vosotros: "linchaseis",
			Uds: "linchasen",
		},
		Future: {
			yo: "linchare",
			tú: "linchares",
			Ud: "linchare",
			nosotros: "lincháremos",
			vosotros: "linchareis",
			Uds: "lincharen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "lincha",
			Ud: "linche",
			nosotros: "linchemos",
			vosotros: "linchad",
			Uds: "linchen",
		},
		Negative: {
			tú: "no linches",
			Ud: "no linche",
			nosotros: "no linchemos",
			vosotros: "no linchéis",
			Uds: "no linchen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy linchando",
			tú: "estás linchando",
			Ud: "está linchando",
			nosotros: "estamos linchando",
			vosotros: "estáis linchando",
			Uds: "están linchando",
		},
		Preterite: {
			yo: "estuve linchando",
			tú: "estuviste linchando",
			Ud: "estuvo linchando",
			nosotros: "estuvimos linchando",
			vosotros: "estuvisteis linchando",
			Uds: "estuvieron linchando",
		},
		Imperfect: {
			Uds: "estaban linchando",
			yo: "estaba linchando",
			tú: "estabas linchando",
			Ud: "estaba linchando",
			nosotros: "estábamos linchando",
			vosotros: "estabais linchando",
		},
		Conditional: {
			yo: "estaría linchando",
			tú: "estarías linchando",
			Ud: "estaría linchando",
			nosotros: "estaríamos linchando",
			vosotros: "estaríais linchando",
			Uds: "estarían linchando",
		},
		Future: {
			yo: "estaré linchando",
			tú: "estarás linchando",
			Ud: "estará linchando",
			nosotros: "estaremos linchando",
			vosotros: "estaréis linchando",
			Uds: "estarán linchando",
		},
	},
	Perfect: {
		Present: {
			yo: "he linchado",
			tú: "has linchado",
			Ud: "ha linchado",
			nosotros: "hemos linchado",
			vosotros: "habéis linchado",
			Uds: "han linchado",
		},
		Preterite: {
			yo: "hube linchado",
			tú: "hubiste linchado",
			Ud: "hubo linchado",
			nosotros: "hubimos linchado",
			vosotros: "hubisteis linchado",
			Uds: "hubieron linchado",
		},
		Past: {
			yo: "había linchado",
			tú: "habías linchado",
			Ud: "había linchado",
			nosotros: "habíamos linchado",
			vosotros: "habíais linchado",
			Uds: "habían linchado",
		},
		Conditional: {
			yo: "habría linchado",
			tú: "habrías linchado",
			Ud: "habría linchado",
			nosotros: "habríamos linchado",
			vosotros: "habríais linchado",
			Uds: "habrían linchado",
		},
		Future: {
			yo: "habré linchado",
			tú: "habrás linchado",
			Ud: "habrá linchado",
			nosotros: "habremos linchado",
			vosotros: "habréis linchado",
			Uds: "habrán linchado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya linchado",
			tú: "hayas linchado",
			Ud: "haya linchado",
			nosotros: "hayamos linchado",
			vosotros: "hayáis linchado",
			Uds: "hayan linchado",
		},
		Past: {
			yo: "hubiera linchado",
			tú: "hubieras linchado",
			Ud: "hubiera linchado",
			nosotros: "hubiéramos linchado",
			vosotros: "hubierais linchado",
			Uds: "hubieran linchado",
		},
		Future: {
			yo: "hubiere linchado",
			tú: "hubieres linchado",
			Ud: "hubiere linchado",
			nosotros: "hubiéremos linchado",
			vosotros: "hubiereis linchado",
			Uds: "hubieren linchado",
		},
	},
}
