var lisiar = {
	Indicative: {
		Present: {
			yo: "lisio",
			tú: "lisias",
			Ud: "lisia",
			nosotros: "lisiamos",
			vosotros: "lisiáis",
			Uds: "lisian",
		},
		Preterite: {
			yo: "lisié",
			tú: "lisiaste",
			Ud: "lisió",
			nosotros: "lisiamos",
			vosotros: "lisiasteis",
			Uds: "lisiaron",
		},
		Imperfect: {
			yo: "lisiaba",
			tú: "lisiabas",
			Ud: "lisiaba",
			nosotros: "lisiábamos",
			vosotros: "lisiabais",
			Uds: "lisiaban",
		},
		Conditional: {
			yo: "lisiaría",
			tú: "lisiarías",
			Ud: "lisiaría",
			nosotros: "lisiaríamos",
			vosotros: "lisiaríais",
			Uds: "lisiarían",
		},
		Future: {
			yo: "lisiaré",
			tú: "lisiarás",
			Ud: "lisiará",
			nosotros: "lisiaremos",
			vosotros: "lisiaréis",
			Uds: "lisiarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "lisie",
			tú: "lisies",
			Ud: "lisie",
			nosotros: "lisiemos",
			vosotros: "lisiéis",
			Uds: "lisien",
		},
		Imperfect: {
			yo: "lisiara",
			tú: "lisiaras",
			Ud: "lisiara",
			nosotros: "lisiáramos",
			vosotros: "lisiarais",
			Uds: "lisiaran",
		},
		Imperfect2: {
			yo: "lisiase",
			tú: "lisiases",
			Ud: "lisiase",
			nosotros: "lisiásemos",
			vosotros: "lisiaseis",
			Uds: "lisiasen",
		},
		Future: {
			yo: "lisiare",
			tú: "lisiares",
			Ud: "lisiare",
			nosotros: "lisiáremos",
			vosotros: "lisiareis",
			Uds: "lisiaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "lisia",
			Ud: "lisie",
			nosotros: "lisiemos",
			vosotros: "lisiad",
			Uds: "lisien",
		},
		Negative: {
			tú: "no lisies",
			Ud: "no lisie",
			nosotros: "no lisiemos",
			vosotros: "no lisiéis",
			Uds: "no lisien",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy lisiando",
			tú: "estás lisiando",
			Ud: "está lisiando",
			nosotros: "estamos lisiando",
			vosotros: "estáis lisiando",
			Uds: "están lisiando",
		},
		Preterite: {
			yo: "estuve lisiando",
			tú: "estuviste lisiando",
			Ud: "estuvo lisiando",
			nosotros: "estuvimos lisiando",
			vosotros: "estuvisteis lisiando",
			Uds: "estuvieron lisiando",
		},
		Imperfect: {
			Uds: "estaban lisiando",
			yo: "estaba lisiando",
			tú: "estabas lisiando",
			Ud: "estaba lisiando",
			nosotros: "estábamos lisiando",
			vosotros: "estabais lisiando",
		},
		Conditional: {
			yo: "estaría lisiando",
			tú: "estarías lisiando",
			Ud: "estaría lisiando",
			nosotros: "estaríamos lisiando",
			vosotros: "estaríais lisiando",
			Uds: "estarían lisiando",
		},
		Future: {
			yo: "estaré lisiando",
			tú: "estarás lisiando",
			Ud: "estará lisiando",
			nosotros: "estaremos lisiando",
			vosotros: "estaréis lisiando",
			Uds: "estarán lisiando",
		},
	},
	Perfect: {
		Present: {
			yo: "he lisiado",
			tú: "has lisiado",
			Ud: "ha lisiado",
			nosotros: "hemos lisiado",
			vosotros: "habéis lisiado",
			Uds: "han lisiado",
		},
		Preterite: {
			yo: "hube lisiado",
			tú: "hubiste lisiado",
			Ud: "hubo lisiado",
			nosotros: "hubimos lisiado",
			vosotros: "hubisteis lisiado",
			Uds: "hubieron lisiado",
		},
		Past: {
			yo: "había lisiado",
			tú: "habías lisiado",
			Ud: "había lisiado",
			nosotros: "habíamos lisiado",
			vosotros: "habíais lisiado",
			Uds: "habían lisiado",
		},
		Conditional: {
			yo: "habría lisiado",
			tú: "habrías lisiado",
			Ud: "habría lisiado",
			nosotros: "habríamos lisiado",
			vosotros: "habríais lisiado",
			Uds: "habrían lisiado",
		},
		Future: {
			yo: "habré lisiado",
			tú: "habrás lisiado",
			Ud: "habrá lisiado",
			nosotros: "habremos lisiado",
			vosotros: "habréis lisiado",
			Uds: "habrán lisiado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya lisiado",
			tú: "hayas lisiado",
			Ud: "haya lisiado",
			nosotros: "hayamos lisiado",
			vosotros: "hayáis lisiado",
			Uds: "hayan lisiado",
		},
		Past: {
			yo: "hubiera lisiado",
			tú: "hubieras lisiado",
			Ud: "hubiera lisiado",
			nosotros: "hubiéramos lisiado",
			vosotros: "hubierais lisiado",
			Uds: "hubieran lisiado",
		},
		Future: {
			yo: "hubiere lisiado",
			tú: "hubieres lisiado",
			Ud: "hubiere lisiado",
			nosotros: "hubiéremos lisiado",
			vosotros: "hubiereis lisiado",
			Uds: "hubieren lisiado",
		},
	},
}
