var lisonjear = {
	Indicative: {
		Present: {
			yo: "lisonjeo",
			tú: "lisonjeas",
			Ud: "lisonjea",
			nosotros: "lisonjeamos",
			vosotros: "lisonjeáis",
			Uds: "lisonjean",
		},
		Preterite: {
			yo: "lisonjeé",
			tú: "lisonjeaste",
			Ud: "lisonjeó",
			nosotros: "lisonjeamos",
			vosotros: "lisonjeasteis",
			Uds: "lisonjearon",
		},
		Imperfect: {
			yo: "lisonjeaba",
			tú: "lisonjeabas",
			Ud: "lisonjeaba",
			nosotros: "lisonjeábamos",
			vosotros: "lisonjeabais",
			Uds: "lisonjeaban",
		},
		Conditional: {
			yo: "lisonjearía",
			tú: "lisonjearías",
			Ud: "lisonjearía",
			nosotros: "lisonjearíamos",
			vosotros: "lisonjearíais",
			Uds: "lisonjearían",
		},
		Future: {
			yo: "lisonjearé",
			tú: "lisonjearás",
			Ud: "lisonjeará",
			nosotros: "lisonjearemos",
			vosotros: "lisonjearéis",
			Uds: "lisonjearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "lisonjee",
			tú: "lisonjees",
			Ud: "lisonjee",
			nosotros: "lisonjeemos",
			vosotros: "lisonjeéis",
			Uds: "lisonjeen",
		},
		Imperfect: {
			yo: "lisonjeara",
			tú: "lisonjearas",
			Ud: "lisonjeara",
			nosotros: "lisonjeáramos",
			vosotros: "lisonjearais",
			Uds: "lisonjearan",
		},
		Imperfect2: {
			yo: "lisonjease",
			tú: "lisonjeases",
			Ud: "lisonjease",
			nosotros: "lisonjeásemos",
			vosotros: "lisonjeaseis",
			Uds: "lisonjeasen",
		},
		Future: {
			yo: "lisonjeare",
			tú: "lisonjeares",
			Ud: "lisonjeare",
			nosotros: "lisonjeáremos",
			vosotros: "lisonjeareis",
			Uds: "lisonjearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "lisonjea",
			Ud: "lisonjee",
			nosotros: "lisonjeemos",
			vosotros: "lisonjead",
			Uds: "lisonjeen",
		},
		Negative: {
			tú: "no lisonjees",
			Ud: "no lisonjee",
			nosotros: "no lisonjeemos",
			vosotros: "no lisonjeéis",
			Uds: "no lisonjeen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy lisonjeando",
			tú: "estás lisonjeando",
			Ud: "está lisonjeando",
			nosotros: "estamos lisonjeando",
			vosotros: "estáis lisonjeando",
			Uds: "están lisonjeando",
		},
		Preterite: {
			yo: "estuve lisonjeando",
			tú: "estuviste lisonjeando",
			Ud: "estuvo lisonjeando",
			nosotros: "estuvimos lisonjeando",
			vosotros: "estuvisteis lisonjeando",
			Uds: "estuvieron lisonjeando",
		},
		Imperfect: {
			Uds: "estaban lisonjeando",
			yo: "estaba lisonjeando",
			tú: "estabas lisonjeando",
			Ud: "estaba lisonjeando",
			nosotros: "estábamos lisonjeando",
			vosotros: "estabais lisonjeando",
		},
		Conditional: {
			yo: "estaría lisonjeando",
			tú: "estarías lisonjeando",
			Ud: "estaría lisonjeando",
			nosotros: "estaríamos lisonjeando",
			vosotros: "estaríais lisonjeando",
			Uds: "estarían lisonjeando",
		},
		Future: {
			yo: "estaré lisonjeando",
			tú: "estarás lisonjeando",
			Ud: "estará lisonjeando",
			nosotros: "estaremos lisonjeando",
			vosotros: "estaréis lisonjeando",
			Uds: "estarán lisonjeando",
		},
	},
	Perfect: {
		Present: {
			yo: "he lisonjeado",
			tú: "has lisonjeado",
			Ud: "ha lisonjeado",
			nosotros: "hemos lisonjeado",
			vosotros: "habéis lisonjeado",
			Uds: "han lisonjeado",
		},
		Preterite: {
			yo: "hube lisonjeado",
			tú: "hubiste lisonjeado",
			Ud: "hubo lisonjeado",
			nosotros: "hubimos lisonjeado",
			vosotros: "hubisteis lisonjeado",
			Uds: "hubieron lisonjeado",
		},
		Past: {
			yo: "había lisonjeado",
			tú: "habías lisonjeado",
			Ud: "había lisonjeado",
			nosotros: "habíamos lisonjeado",
			vosotros: "habíais lisonjeado",
			Uds: "habían lisonjeado",
		},
		Conditional: {
			yo: "habría lisonjeado",
			tú: "habrías lisonjeado",
			Ud: "habría lisonjeado",
			nosotros: "habríamos lisonjeado",
			vosotros: "habríais lisonjeado",
			Uds: "habrían lisonjeado",
		},
		Future: {
			yo: "habré lisonjeado",
			tú: "habrás lisonjeado",
			Ud: "habrá lisonjeado",
			nosotros: "habremos lisonjeado",
			vosotros: "habréis lisonjeado",
			Uds: "habrán lisonjeado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya lisonjeado",
			tú: "hayas lisonjeado",
			Ud: "haya lisonjeado",
			nosotros: "hayamos lisonjeado",
			vosotros: "hayáis lisonjeado",
			Uds: "hayan lisonjeado",
		},
		Past: {
			yo: "hubiera lisonjeado",
			tú: "hubieras lisonjeado",
			Ud: "hubiera lisonjeado",
			nosotros: "hubiéramos lisonjeado",
			vosotros: "hubierais lisonjeado",
			Uds: "hubieran lisonjeado",
		},
		Future: {
			yo: "hubiere lisonjeado",
			tú: "hubieres lisonjeado",
			Ud: "hubiere lisonjeado",
			nosotros: "hubiéremos lisonjeado",
			vosotros: "hubiereis lisonjeado",
			Uds: "hubieren lisonjeado",
		},
	},
}
