var llenar = {
	Indicative: {
		Present: {
			yo: "lleno",
			tú: "llenas",
			Ud: "llena",
			nosotros: "llenamos",
			vosotros: "llenáis",
			Uds: "llenan",
		},
		Preterite: {
			yo: "llené",
			tú: "llenaste",
			Ud: "llenó",
			nosotros: "llenamos",
			vosotros: "llenasteis",
			Uds: "llenaron",
		},
		Imperfect: {
			yo: "llenaba",
			tú: "llenabas",
			Ud: "llenaba",
			nosotros: "llenábamos",
			vosotros: "llenabais",
			Uds: "llenaban",
		},
		Conditional: {
			yo: "llenaría",
			tú: "llenarías",
			Ud: "llenaría",
			nosotros: "llenaríamos",
			vosotros: "llenaríais",
			Uds: "llenarían",
		},
		Future: {
			yo: "llenaré",
			tú: "llenarás",
			Ud: "llenará",
			nosotros: "llenaremos",
			vosotros: "llenaréis",
			Uds: "llenarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "llene",
			tú: "llenes",
			Ud: "llene",
			nosotros: "llenemos",
			vosotros: "llenéis",
			Uds: "llenen",
		},
		Imperfect: {
			yo: "llenara",
			tú: "llenaras",
			Ud: "llenara",
			nosotros: "llenáramos",
			vosotros: "llenarais",
			Uds: "llenaran",
		},
		Imperfect2: {
			yo: "llenase",
			tú: "llenases",
			Ud: "llenase",
			nosotros: "llenásemos",
			vosotros: "llenaseis",
			Uds: "llenasen",
		},
		Future: {
			yo: "llenare",
			tú: "llenares",
			Ud: "llenare",
			nosotros: "llenáremos",
			vosotros: "llenareis",
			Uds: "llenaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "llena",
			Ud: "llene",
			nosotros: "llenemos",
			vosotros: "llenad",
			Uds: "llenen",
		},
		Negative: {
			tú: "no llenes",
			Ud: "no llene",
			nosotros: "no llenemos",
			vosotros: "no llenéis",
			Uds: "no llenen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy llenando",
			tú: "estás llenando",
			Ud: "está llenando",
			nosotros: "estamos llenando",
			vosotros: "estáis llenando",
			Uds: "están llenando",
		},
		Preterite: {
			yo: "estuve llenando",
			tú: "estuviste llenando",
			Ud: "estuvo llenando",
			nosotros: "estuvimos llenando",
			vosotros: "estuvisteis llenando",
			Uds: "estuvieron llenando",
		},
		Imperfect: {
			Uds: "estaban llenando",
			yo: "estaba llenando",
			tú: "estabas llenando",
			Ud: "estaba llenando",
			nosotros: "estábamos llenando",
			vosotros: "estabais llenando",
		},
		Conditional: {
			yo: "estaría llenando",
			tú: "estarías llenando",
			Ud: "estaría llenando",
			nosotros: "estaríamos llenando",
			vosotros: "estaríais llenando",
			Uds: "estarían llenando",
		},
		Future: {
			yo: "estaré llenando",
			tú: "estarás llenando",
			Ud: "estará llenando",
			nosotros: "estaremos llenando",
			vosotros: "estaréis llenando",
			Uds: "estarán llenando",
		},
	},
	Perfect: {
		Present: {
			yo: "he llenado",
			tú: "has llenado",
			Ud: "ha llenado",
			nosotros: "hemos llenado",
			vosotros: "habéis llenado",
			Uds: "han llenado",
		},
		Preterite: {
			yo: "hube llenado",
			tú: "hubiste llenado",
			Ud: "hubo llenado",
			nosotros: "hubimos llenado",
			vosotros: "hubisteis llenado",
			Uds: "hubieron llenado",
		},
		Past: {
			yo: "había llenado",
			tú: "habías llenado",
			Ud: "había llenado",
			nosotros: "habíamos llenado",
			vosotros: "habíais llenado",
			Uds: "habían llenado",
		},
		Conditional: {
			yo: "habría llenado",
			tú: "habrías llenado",
			Ud: "habría llenado",
			nosotros: "habríamos llenado",
			vosotros: "habríais llenado",
			Uds: "habrían llenado",
		},
		Future: {
			yo: "habré llenado",
			tú: "habrás llenado",
			Ud: "habrá llenado",
			nosotros: "habremos llenado",
			vosotros: "habréis llenado",
			Uds: "habrán llenado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya llenado",
			tú: "hayas llenado",
			Ud: "haya llenado",
			nosotros: "hayamos llenado",
			vosotros: "hayáis llenado",
			Uds: "hayan llenado",
		},
		Past: {
			yo: "hubiera llenado",
			tú: "hubieras llenado",
			Ud: "hubiera llenado",
			nosotros: "hubiéramos llenado",
			vosotros: "hubierais llenado",
			Uds: "hubieran llenado",
		},
		Future: {
			yo: "hubiere llenado",
			tú: "hubieres llenado",
			Ud: "hubiere llenado",
			nosotros: "hubiéremos llenado",
			vosotros: "hubiereis llenado",
			Uds: "hubieren llenado",
		},
	},
}
