var lustrar = {
	Indicative: {
		Present: {
			yo: "lustro",
			tú: "lustras",
			Ud: "lustra",
			nosotros: "lustramos",
			vosotros: "lustráis",
			Uds: "lustran",
		},
		Preterite: {
			yo: "lustré",
			tú: "lustraste",
			Ud: "lustró",
			nosotros: "lustramos",
			vosotros: "lustrasteis",
			Uds: "lustraron",
		},
		Imperfect: {
			yo: "lustraba",
			tú: "lustrabas",
			Ud: "lustraba",
			nosotros: "lustrábamos",
			vosotros: "lustrabais",
			Uds: "lustraban",
		},
		Conditional: {
			yo: "lustraría",
			tú: "lustrarías",
			Ud: "lustraría",
			nosotros: "lustraríamos",
			vosotros: "lustraríais",
			Uds: "lustrarían",
		},
		Future: {
			yo: "lustraré",
			tú: "lustrarás",
			Ud: "lustrará",
			nosotros: "lustraremos",
			vosotros: "lustraréis",
			Uds: "lustrarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "lustre",
			tú: "lustres",
			Ud: "lustre",
			nosotros: "lustremos",
			vosotros: "lustréis",
			Uds: "lustren",
		},
		Imperfect: {
			yo: "lustrara",
			tú: "lustraras",
			Ud: "lustrara",
			nosotros: "lustráramos",
			vosotros: "lustrarais",
			Uds: "lustraran",
		},
		Imperfect2: {
			yo: "lustrase",
			tú: "lustrases",
			Ud: "lustrase",
			nosotros: "lustrásemos",
			vosotros: "lustraseis",
			Uds: "lustrasen",
		},
		Future: {
			yo: "lustrare",
			tú: "lustrares",
			Ud: "lustrare",
			nosotros: "lustráremos",
			vosotros: "lustrareis",
			Uds: "lustraren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "lustra",
			Ud: "lustre",
			nosotros: "lustremos",
			vosotros: "lustrad",
			Uds: "lustren",
		},
		Negative: {
			tú: "no lustres",
			Ud: "no lustre",
			nosotros: "no lustremos",
			vosotros: "no lustréis",
			Uds: "no lustren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy lustrando",
			tú: "estás lustrando",
			Ud: "está lustrando",
			nosotros: "estamos lustrando",
			vosotros: "estáis lustrando",
			Uds: "están lustrando",
		},
		Preterite: {
			yo: "estuve lustrando",
			tú: "estuviste lustrando",
			Ud: "estuvo lustrando",
			nosotros: "estuvimos lustrando",
			vosotros: "estuvisteis lustrando",
			Uds: "estuvieron lustrando",
		},
		Imperfect: {
			Uds: "estaban lustrando",
			yo: "estaba lustrando",
			tú: "estabas lustrando",
			Ud: "estaba lustrando",
			nosotros: "estábamos lustrando",
			vosotros: "estabais lustrando",
		},
		Conditional: {
			yo: "estaría lustrando",
			tú: "estarías lustrando",
			Ud: "estaría lustrando",
			nosotros: "estaríamos lustrando",
			vosotros: "estaríais lustrando",
			Uds: "estarían lustrando",
		},
		Future: {
			yo: "estaré lustrando",
			tú: "estarás lustrando",
			Ud: "estará lustrando",
			nosotros: "estaremos lustrando",
			vosotros: "estaréis lustrando",
			Uds: "estarán lustrando",
		},
	},
	Perfect: {
		Present: {
			yo: "he lustrado",
			tú: "has lustrado",
			Ud: "ha lustrado",
			nosotros: "hemos lustrado",
			vosotros: "habéis lustrado",
			Uds: "han lustrado",
		},
		Preterite: {
			yo: "hube lustrado",
			tú: "hubiste lustrado",
			Ud: "hubo lustrado",
			nosotros: "hubimos lustrado",
			vosotros: "hubisteis lustrado",
			Uds: "hubieron lustrado",
		},
		Past: {
			yo: "había lustrado",
			tú: "habías lustrado",
			Ud: "había lustrado",
			nosotros: "habíamos lustrado",
			vosotros: "habíais lustrado",
			Uds: "habían lustrado",
		},
		Conditional: {
			yo: "habría lustrado",
			tú: "habrías lustrado",
			Ud: "habría lustrado",
			nosotros: "habríamos lustrado",
			vosotros: "habríais lustrado",
			Uds: "habrían lustrado",
		},
		Future: {
			yo: "habré lustrado",
			tú: "habrás lustrado",
			Ud: "habrá lustrado",
			nosotros: "habremos lustrado",
			vosotros: "habréis lustrado",
			Uds: "habrán lustrado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya lustrado",
			tú: "hayas lustrado",
			Ud: "haya lustrado",
			nosotros: "hayamos lustrado",
			vosotros: "hayáis lustrado",
			Uds: "hayan lustrado",
		},
		Past: {
			yo: "hubiera lustrado",
			tú: "hubieras lustrado",
			Ud: "hubiera lustrado",
			nosotros: "hubiéramos lustrado",
			vosotros: "hubierais lustrado",
			Uds: "hubieran lustrado",
		},
		Future: {
			yo: "hubiere lustrado",
			tú: "hubieres lustrado",
			Ud: "hubiere lustrado",
			nosotros: "hubiéremos lustrado",
			vosotros: "hubiereis lustrado",
			Uds: "hubieren lustrado",
		},
	},
}
