var madrugar = {
	Indicative: {
		Present: {
			yo: "madrugo",
			tú: "madrugas",
			Ud: "madruga",
			nosotros: "madrugamos",
			vosotros: "madrugáis",
			Uds: "madrugan",
		},
		Preterite: {
			yo: "madrugué",
			tú: "madrugaste",
			Ud: "madrugó",
			nosotros: "madrugamos",
			vosotros: "madrugasteis",
			Uds: "madrugaron",
		},
		Imperfect: {
			yo: "madrugaba",
			tú: "madrugabas",
			Ud: "madrugaba",
			nosotros: "madrugábamos",
			vosotros: "madrugabais",
			Uds: "madrugaban",
		},
		Conditional: {
			yo: "madrugaría",
			tú: "madrugarías",
			Ud: "madrugaría",
			nosotros: "madrugaríamos",
			vosotros: "madrugaríais",
			Uds: "madrugarían",
		},
		Future: {
			yo: "madrugaré",
			tú: "madrugarás",
			Ud: "madrugará",
			nosotros: "madrugaremos",
			vosotros: "madrugaréis",
			Uds: "madrugarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "madrugue",
			tú: "madrugues",
			Ud: "madrugue",
			nosotros: "madruguemos",
			vosotros: "madruguéis",
			Uds: "madruguen",
		},
		Imperfect: {
			yo: "madrugara",
			tú: "madrugaras",
			Ud: "madrugara",
			nosotros: "madrugáramos",
			vosotros: "madrugarais",
			Uds: "madrugaran",
		},
		Imperfect2: {
			yo: "madrugase",
			tú: "madrugases",
			Ud: "madrugase",
			nosotros: "madrugásemos",
			vosotros: "madrugaseis",
			Uds: "madrugasen",
		},
		Future: {
			yo: "madrugare",
			tú: "madrugares",
			Ud: "madrugare",
			nosotros: "madrugáremos",
			vosotros: "madrugareis",
			Uds: "madrugaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "madruga",
			Ud: "madrugue",
			nosotros: "madruguemos",
			vosotros: "madrugad",
			Uds: "madruguen",
		},
		Negative: {
			tú: "no madrugues",
			Ud: "no madrugue",
			nosotros: "no madruguemos",
			vosotros: "no madruguéis",
			Uds: "no madruguen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy madrugando",
			tú: "estás madrugando",
			Ud: "está madrugando",
			nosotros: "estamos madrugando",
			vosotros: "estáis madrugando",
			Uds: "están madrugando",
		},
		Preterite: {
			yo: "estuve madrugando",
			tú: "estuviste madrugando",
			Ud: "estuvo madrugando",
			nosotros: "estuvimos madrugando",
			vosotros: "estuvisteis madrugando",
			Uds: "estuvieron madrugando",
		},
		Imperfect: {
			Uds: "estaban madrugando",
			yo: "estaba madrugando",
			tú: "estabas madrugando",
			Ud: "estaba madrugando",
			nosotros: "estábamos madrugando",
			vosotros: "estabais madrugando",
		},
		Conditional: {
			yo: "estaría madrugando",
			tú: "estarías madrugando",
			Ud: "estaría madrugando",
			nosotros: "estaríamos madrugando",
			vosotros: "estaríais madrugando",
			Uds: "estarían madrugando",
		},
		Future: {
			yo: "estaré madrugando",
			tú: "estarás madrugando",
			Ud: "estará madrugando",
			nosotros: "estaremos madrugando",
			vosotros: "estaréis madrugando",
			Uds: "estarán madrugando",
		},
	},
	Perfect: {
		Present: {
			yo: "he madrugado",
			tú: "has madrugado",
			Ud: "ha madrugado",
			nosotros: "hemos madrugado",
			vosotros: "habéis madrugado",
			Uds: "han madrugado",
		},
		Preterite: {
			yo: "hube madrugado",
			tú: "hubiste madrugado",
			Ud: "hubo madrugado",
			nosotros: "hubimos madrugado",
			vosotros: "hubisteis madrugado",
			Uds: "hubieron madrugado",
		},
		Past: {
			yo: "había madrugado",
			tú: "habías madrugado",
			Ud: "había madrugado",
			nosotros: "habíamos madrugado",
			vosotros: "habíais madrugado",
			Uds: "habían madrugado",
		},
		Conditional: {
			yo: "habría madrugado",
			tú: "habrías madrugado",
			Ud: "habría madrugado",
			nosotros: "habríamos madrugado",
			vosotros: "habríais madrugado",
			Uds: "habrían madrugado",
		},
		Future: {
			yo: "habré madrugado",
			tú: "habrás madrugado",
			Ud: "habrá madrugado",
			nosotros: "habremos madrugado",
			vosotros: "habréis madrugado",
			Uds: "habrán madrugado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya madrugado",
			tú: "hayas madrugado",
			Ud: "haya madrugado",
			nosotros: "hayamos madrugado",
			vosotros: "hayáis madrugado",
			Uds: "hayan madrugado",
		},
		Past: {
			yo: "hubiera madrugado",
			tú: "hubieras madrugado",
			Ud: "hubiera madrugado",
			nosotros: "hubiéramos madrugado",
			vosotros: "hubierais madrugado",
			Uds: "hubieran madrugado",
		},
		Future: {
			yo: "hubiere madrugado",
			tú: "hubieres madrugado",
			Ud: "hubiere madrugado",
			nosotros: "hubiéremos madrugado",
			vosotros: "hubiereis madrugado",
			Uds: "hubieren madrugado",
		},
	},
}
