var madurar = {
	Indicative: {
		Present: {
			yo: "maduro",
			tú: "maduras",
			Ud: "madura",
			nosotros: "maduramos",
			vosotros: "maduráis",
			Uds: "maduran",
		},
		Preterite: {
			yo: "maduré",
			tú: "maduraste",
			Ud: "maduró",
			nosotros: "maduramos",
			vosotros: "madurasteis",
			Uds: "maduraron",
		},
		Imperfect: {
			yo: "maduraba",
			tú: "madurabas",
			Ud: "maduraba",
			nosotros: "madurábamos",
			vosotros: "madurabais",
			Uds: "maduraban",
		},
		Conditional: {
			yo: "maduraría",
			tú: "madurarías",
			Ud: "maduraría",
			nosotros: "maduraríamos",
			vosotros: "maduraríais",
			Uds: "madurarían",
		},
		Future: {
			yo: "maduraré",
			tú: "madurarás",
			Ud: "madurará",
			nosotros: "maduraremos",
			vosotros: "maduraréis",
			Uds: "madurarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "madure",
			tú: "madures",
			Ud: "madure",
			nosotros: "maduremos",
			vosotros: "maduréis",
			Uds: "maduren",
		},
		Imperfect: {
			yo: "madurara",
			tú: "maduraras",
			Ud: "madurara",
			nosotros: "maduráramos",
			vosotros: "madurarais",
			Uds: "maduraran",
		},
		Imperfect2: {
			yo: "madurase",
			tú: "madurases",
			Ud: "madurase",
			nosotros: "madurásemos",
			vosotros: "maduraseis",
			Uds: "madurasen",
		},
		Future: {
			yo: "madurare",
			tú: "madurares",
			Ud: "madurare",
			nosotros: "maduráremos",
			vosotros: "madurareis",
			Uds: "maduraren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "madura",
			Ud: "madure",
			nosotros: "maduremos",
			vosotros: "madurad",
			Uds: "maduren",
		},
		Negative: {
			tú: "no madures",
			Ud: "no madure",
			nosotros: "no maduremos",
			vosotros: "no maduréis",
			Uds: "no maduren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy madurando",
			tú: "estás madurando",
			Ud: "está madurando",
			nosotros: "estamos madurando",
			vosotros: "estáis madurando",
			Uds: "están madurando",
		},
		Preterite: {
			yo: "estuve madurando",
			tú: "estuviste madurando",
			Ud: "estuvo madurando",
			nosotros: "estuvimos madurando",
			vosotros: "estuvisteis madurando",
			Uds: "estuvieron madurando",
		},
		Imperfect: {
			Uds: "estaban madurando",
			yo: "estaba madurando",
			tú: "estabas madurando",
			Ud: "estaba madurando",
			nosotros: "estábamos madurando",
			vosotros: "estabais madurando",
		},
		Conditional: {
			yo: "estaría madurando",
			tú: "estarías madurando",
			Ud: "estaría madurando",
			nosotros: "estaríamos madurando",
			vosotros: "estaríais madurando",
			Uds: "estarían madurando",
		},
		Future: {
			yo: "estaré madurando",
			tú: "estarás madurando",
			Ud: "estará madurando",
			nosotros: "estaremos madurando",
			vosotros: "estaréis madurando",
			Uds: "estarán madurando",
		},
	},
	Perfect: {
		Present: {
			yo: "he madurado",
			tú: "has madurado",
			Ud: "ha madurado",
			nosotros: "hemos madurado",
			vosotros: "habéis madurado",
			Uds: "han madurado",
		},
		Preterite: {
			yo: "hube madurado",
			tú: "hubiste madurado",
			Ud: "hubo madurado",
			nosotros: "hubimos madurado",
			vosotros: "hubisteis madurado",
			Uds: "hubieron madurado",
		},
		Past: {
			yo: "había madurado",
			tú: "habías madurado",
			Ud: "había madurado",
			nosotros: "habíamos madurado",
			vosotros: "habíais madurado",
			Uds: "habían madurado",
		},
		Conditional: {
			yo: "habría madurado",
			tú: "habrías madurado",
			Ud: "habría madurado",
			nosotros: "habríamos madurado",
			vosotros: "habríais madurado",
			Uds: "habrían madurado",
		},
		Future: {
			yo: "habré madurado",
			tú: "habrás madurado",
			Ud: "habrá madurado",
			nosotros: "habremos madurado",
			vosotros: "habréis madurado",
			Uds: "habrán madurado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya madurado",
			tú: "hayas madurado",
			Ud: "haya madurado",
			nosotros: "hayamos madurado",
			vosotros: "hayáis madurado",
			Uds: "hayan madurado",
		},
		Past: {
			yo: "hubiera madurado",
			tú: "hubieras madurado",
			Ud: "hubiera madurado",
			nosotros: "hubiéramos madurado",
			vosotros: "hubierais madurado",
			Uds: "hubieran madurado",
		},
		Future: {
			yo: "hubiere madurado",
			tú: "hubieres madurado",
			Ud: "hubiere madurado",
			nosotros: "hubiéremos madurado",
			vosotros: "hubiereis madurado",
			Uds: "hubieren madurado",
		},
	},
}
