var manufacturar = {
	Indicative: {
		Present: {
			yo: "manufacturo",
			tú: "manufacturas",
			Ud: "manufactura",
			nosotros: "manufacturamos",
			vosotros: "manufacturáis",
			Uds: "manufacturan",
		},
		Preterite: {
			yo: "manufacturé",
			tú: "manufacturaste",
			Ud: "manufacturó",
			nosotros: "manufacturamos",
			vosotros: "manufacturasteis",
			Uds: "manufacturaron",
		},
		Imperfect: {
			yo: "manufacturaba",
			tú: "manufacturabas",
			Ud: "manufacturaba",
			nosotros: "manufacturábamos",
			vosotros: "manufacturabais",
			Uds: "manufacturaban",
		},
		Conditional: {
			yo: "manufacturaría",
			tú: "manufacturarías",
			Ud: "manufacturaría",
			nosotros: "manufacturaríamos",
			vosotros: "manufacturaríais",
			Uds: "manufacturarían",
		},
		Future: {
			yo: "manufacturaré",
			tú: "manufacturarás",
			Ud: "manufacturará",
			nosotros: "manufacturaremos",
			vosotros: "manufacturaréis",
			Uds: "manufacturarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "manufacture",
			tú: "manufactures",
			Ud: "manufacture",
			nosotros: "manufacturemos",
			vosotros: "manufacturéis",
			Uds: "manufacturen",
		},
		Imperfect: {
			yo: "manufacturara",
			tú: "manufacturaras",
			Ud: "manufacturara",
			nosotros: "manufacturáramos",
			vosotros: "manufacturarais",
			Uds: "manufacturaran",
		},
		Imperfect2: {
			yo: "manufacturase",
			tú: "manufacturases",
			Ud: "manufacturase",
			nosotros: "manufacturásemos",
			vosotros: "manufacturaseis",
			Uds: "manufacturasen",
		},
		Future: {
			yo: "manufacturare",
			tú: "manufacturares",
			Ud: "manufacturare",
			nosotros: "manufacturáremos",
			vosotros: "manufacturareis",
			Uds: "manufacturaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "manufactura",
			Ud: "manufacture",
			nosotros: "manufacturemos",
			vosotros: "manufacturad",
			Uds: "manufacturen",
		},
		Negative: {
			tú: "no manufactures",
			Ud: "no manufacture",
			nosotros: "no manufacturemos",
			vosotros: "no manufacturéis",
			Uds: "no manufacturen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy manufacturando",
			tú: "estás manufacturando",
			Ud: "está manufacturando",
			nosotros: "estamos manufacturando",
			vosotros: "estáis manufacturando",
			Uds: "están manufacturando",
		},
		Preterite: {
			yo: "estuve manufacturando",
			tú: "estuviste manufacturando",
			Ud: "estuvo manufacturando",
			nosotros: "estuvimos manufacturando",
			vosotros: "estuvisteis manufacturando",
			Uds: "estuvieron manufacturando",
		},
		Imperfect: {
			Uds: "estaban manufacturando",
			yo: "estaba manufacturando",
			tú: "estabas manufacturando",
			Ud: "estaba manufacturando",
			nosotros: "estábamos manufacturando",
			vosotros: "estabais manufacturando",
		},
		Conditional: {
			yo: "estaría manufacturando",
			tú: "estarías manufacturando",
			Ud: "estaría manufacturando",
			nosotros: "estaríamos manufacturando",
			vosotros: "estaríais manufacturando",
			Uds: "estarían manufacturando",
		},
		Future: {
			yo: "estaré manufacturando",
			tú: "estarás manufacturando",
			Ud: "estará manufacturando",
			nosotros: "estaremos manufacturando",
			vosotros: "estaréis manufacturando",
			Uds: "estarán manufacturando",
		},
	},
	Perfect: {
		Present: {
			yo: "he manufacturado",
			tú: "has manufacturado",
			Ud: "ha manufacturado",
			nosotros: "hemos manufacturado",
			vosotros: "habéis manufacturado",
			Uds: "han manufacturado",
		},
		Preterite: {
			yo: "hube manufacturado",
			tú: "hubiste manufacturado",
			Ud: "hubo manufacturado",
			nosotros: "hubimos manufacturado",
			vosotros: "hubisteis manufacturado",
			Uds: "hubieron manufacturado",
		},
		Past: {
			yo: "había manufacturado",
			tú: "habías manufacturado",
			Ud: "había manufacturado",
			nosotros: "habíamos manufacturado",
			vosotros: "habíais manufacturado",
			Uds: "habían manufacturado",
		},
		Conditional: {
			yo: "habría manufacturado",
			tú: "habrías manufacturado",
			Ud: "habría manufacturado",
			nosotros: "habríamos manufacturado",
			vosotros: "habríais manufacturado",
			Uds: "habrían manufacturado",
		},
		Future: {
			yo: "habré manufacturado",
			tú: "habrás manufacturado",
			Ud: "habrá manufacturado",
			nosotros: "habremos manufacturado",
			vosotros: "habréis manufacturado",
			Uds: "habrán manufacturado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya manufacturado",
			tú: "hayas manufacturado",
			Ud: "haya manufacturado",
			nosotros: "hayamos manufacturado",
			vosotros: "hayáis manufacturado",
			Uds: "hayan manufacturado",
		},
		Past: {
			yo: "hubiera manufacturado",
			tú: "hubieras manufacturado",
			Ud: "hubiera manufacturado",
			nosotros: "hubiéramos manufacturado",
			vosotros: "hubierais manufacturado",
			Uds: "hubieran manufacturado",
		},
		Future: {
			yo: "hubiere manufacturado",
			tú: "hubieres manufacturado",
			Ud: "hubiere manufacturado",
			nosotros: "hubiéremos manufacturado",
			vosotros: "hubiereis manufacturado",
			Uds: "hubieren manufacturado",
		},
	},
}
