var marear = {
	Indicative: {
		Present: {
			yo: "mareo",
			tú: "mareas",
			Ud: "marea",
			nosotros: "mareamos",
			vosotros: "mareáis",
			Uds: "marean",
		},
		Preterite: {
			yo: "mareé",
			tú: "mareaste",
			Ud: "mareó",
			nosotros: "mareamos",
			vosotros: "mareasteis",
			Uds: "marearon",
		},
		Imperfect: {
			yo: "mareaba",
			tú: "mareabas",
			Ud: "mareaba",
			nosotros: "mareábamos",
			vosotros: "mareabais",
			Uds: "mareaban",
		},
		Conditional: {
			yo: "marearía",
			tú: "marearías",
			Ud: "marearía",
			nosotros: "marearíamos",
			vosotros: "marearíais",
			Uds: "marearían",
		},
		Future: {
			yo: "marearé",
			tú: "marearás",
			Ud: "mareará",
			nosotros: "marearemos",
			vosotros: "marearéis",
			Uds: "marearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "maree",
			tú: "marees",
			Ud: "maree",
			nosotros: "mareemos",
			vosotros: "mareéis",
			Uds: "mareen",
		},
		Imperfect: {
			yo: "mareara",
			tú: "marearas",
			Ud: "mareara",
			nosotros: "mareáramos",
			vosotros: "marearais",
			Uds: "marearan",
		},
		Imperfect2: {
			yo: "marease",
			tú: "mareases",
			Ud: "marease",
			nosotros: "mareásemos",
			vosotros: "mareaseis",
			Uds: "mareasen",
		},
		Future: {
			yo: "mareare",
			tú: "mareares",
			Ud: "mareare",
			nosotros: "mareáremos",
			vosotros: "mareareis",
			Uds: "marearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "marea",
			Ud: "maree",
			nosotros: "mareemos",
			vosotros: "maread",
			Uds: "mareen",
		},
		Negative: {
			tú: "no marees",
			Ud: "no maree",
			nosotros: "no mareemos",
			vosotros: "no mareéis",
			Uds: "no mareen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy mareando",
			tú: "estás mareando",
			Ud: "está mareando",
			nosotros: "estamos mareando",
			vosotros: "estáis mareando",
			Uds: "están mareando",
		},
		Preterite: {
			yo: "estuve mareando",
			tú: "estuviste mareando",
			Ud: "estuvo mareando",
			nosotros: "estuvimos mareando",
			vosotros: "estuvisteis mareando",
			Uds: "estuvieron mareando",
		},
		Imperfect: {
			Uds: "estaban mareando",
			yo: "estaba mareando",
			tú: "estabas mareando",
			Ud: "estaba mareando",
			nosotros: "estábamos mareando",
			vosotros: "estabais mareando",
		},
		Conditional: {
			yo: "estaría mareando",
			tú: "estarías mareando",
			Ud: "estaría mareando",
			nosotros: "estaríamos mareando",
			vosotros: "estaríais mareando",
			Uds: "estarían mareando",
		},
		Future: {
			yo: "estaré mareando",
			tú: "estarás mareando",
			Ud: "estará mareando",
			nosotros: "estaremos mareando",
			vosotros: "estaréis mareando",
			Uds: "estarán mareando",
		},
	},
	Perfect: {
		Present: {
			yo: "he mareado",
			tú: "has mareado",
			Ud: "ha mareado",
			nosotros: "hemos mareado",
			vosotros: "habéis mareado",
			Uds: "han mareado",
		},
		Preterite: {
			yo: "hube mareado",
			tú: "hubiste mareado",
			Ud: "hubo mareado",
			nosotros: "hubimos mareado",
			vosotros: "hubisteis mareado",
			Uds: "hubieron mareado",
		},
		Past: {
			yo: "había mareado",
			tú: "habías mareado",
			Ud: "había mareado",
			nosotros: "habíamos mareado",
			vosotros: "habíais mareado",
			Uds: "habían mareado",
		},
		Conditional: {
			yo: "habría mareado",
			tú: "habrías mareado",
			Ud: "habría mareado",
			nosotros: "habríamos mareado",
			vosotros: "habríais mareado",
			Uds: "habrían mareado",
		},
		Future: {
			yo: "habré mareado",
			tú: "habrás mareado",
			Ud: "habrá mareado",
			nosotros: "habremos mareado",
			vosotros: "habréis mareado",
			Uds: "habrán mareado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya mareado",
			tú: "hayas mareado",
			Ud: "haya mareado",
			nosotros: "hayamos mareado",
			vosotros: "hayáis mareado",
			Uds: "hayan mareado",
		},
		Past: {
			yo: "hubiera mareado",
			tú: "hubieras mareado",
			Ud: "hubiera mareado",
			nosotros: "hubiéramos mareado",
			vosotros: "hubierais mareado",
			Uds: "hubieran mareado",
		},
		Future: {
			yo: "hubiere mareado",
			tú: "hubieres mareado",
			Ud: "hubiere mareado",
			nosotros: "hubiéremos mareado",
			vosotros: "hubiereis mareado",
			Uds: "hubieren mareado",
		},
	},
}
