var matar = {
	Indicative: {
		Present: {
			yo: "mato",
			tú: "matas",
			Ud: "mata",
			nosotros: "matamos",
			vosotros: "matáis",
			Uds: "matan",
		},
		Preterite: {
			yo: "maté",
			tú: "mataste",
			Ud: "mató",
			nosotros: "matamos",
			vosotros: "matasteis",
			Uds: "mataron",
		},
		Imperfect: {
			yo: "mataba",
			tú: "matabas",
			Ud: "mataba",
			nosotros: "matábamos",
			vosotros: "matabais",
			Uds: "mataban",
		},
		Conditional: {
			yo: "mataría",
			tú: "matarías",
			Ud: "mataría",
			nosotros: "mataríamos",
			vosotros: "mataríais",
			Uds: "matarían",
		},
		Future: {
			yo: "mataré",
			tú: "matarás",
			Ud: "matará",
			nosotros: "mataremos",
			vosotros: "mataréis",
			Uds: "matarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "mate",
			tú: "mates",
			Ud: "mate",
			nosotros: "matemos",
			vosotros: "matéis",
			Uds: "maten",
		},
		Imperfect: {
			yo: "matara",
			tú: "mataras",
			Ud: "matara",
			nosotros: "matáramos",
			vosotros: "matarais",
			Uds: "mataran",
		},
		Imperfect2: {
			yo: "matase",
			tú: "matases",
			Ud: "matase",
			nosotros: "matásemos",
			vosotros: "mataseis",
			Uds: "matasen",
		},
		Future: {
			yo: "matare",
			tú: "matares",
			Ud: "matare",
			nosotros: "matáremos",
			vosotros: "matareis",
			Uds: "mataren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "mata",
			Ud: "mate",
			nosotros: "matemos",
			vosotros: "matad",
			Uds: "maten",
		},
		Negative: {
			tú: "no mates",
			Ud: "no mate",
			nosotros: "no matemos",
			vosotros: "no matéis",
			Uds: "no maten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy matando",
			tú: "estás matando",
			Ud: "está matando",
			nosotros: "estamos matando",
			vosotros: "estáis matando",
			Uds: "están matando",
		},
		Preterite: {
			yo: "estuve matando",
			tú: "estuviste matando",
			Ud: "estuvo matando",
			nosotros: "estuvimos matando",
			vosotros: "estuvisteis matando",
			Uds: "estuvieron matando",
		},
		Imperfect: {
			Uds: "estaban matando",
			yo: "estaba matando",
			tú: "estabas matando",
			Ud: "estaba matando",
			nosotros: "estábamos matando",
			vosotros: "estabais matando",
		},
		Conditional: {
			yo: "estaría matando",
			tú: "estarías matando",
			Ud: "estaría matando",
			nosotros: "estaríamos matando",
			vosotros: "estaríais matando",
			Uds: "estarían matando",
		},
		Future: {
			yo: "estaré matando",
			tú: "estarás matando",
			Ud: "estará matando",
			nosotros: "estaremos matando",
			vosotros: "estaréis matando",
			Uds: "estarán matando",
		},
	},
	Perfect: {
		Present: {
			yo: "he matado",
			tú: "has matado",
			Ud: "ha matado",
			nosotros: "hemos matado",
			vosotros: "habéis matado",
			Uds: "han matado",
		},
		Preterite: {
			yo: "hube matado",
			tú: "hubiste matado",
			Ud: "hubo matado",
			nosotros: "hubimos matado",
			vosotros: "hubisteis matado",
			Uds: "hubieron matado",
		},
		Past: {
			yo: "había matado",
			tú: "habías matado",
			Ud: "había matado",
			nosotros: "habíamos matado",
			vosotros: "habíais matado",
			Uds: "habían matado",
		},
		Conditional: {
			yo: "habría matado",
			tú: "habrías matado",
			Ud: "habría matado",
			nosotros: "habríamos matado",
			vosotros: "habríais matado",
			Uds: "habrían matado",
		},
		Future: {
			yo: "habré matado",
			tú: "habrás matado",
			Ud: "habrá matado",
			nosotros: "habremos matado",
			vosotros: "habréis matado",
			Uds: "habrán matado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya matado",
			tú: "hayas matado",
			Ud: "haya matado",
			nosotros: "hayamos matado",
			vosotros: "hayáis matado",
			Uds: "hayan matado",
		},
		Past: {
			yo: "hubiera matado",
			tú: "hubieras matado",
			Ud: "hubiera matado",
			nosotros: "hubiéramos matado",
			vosotros: "hubierais matado",
			Uds: "hubieran matado",
		},
		Future: {
			yo: "hubiere matado",
			tú: "hubieres matado",
			Ud: "hubiere matado",
			nosotros: "hubiéremos matado",
			vosotros: "hubiereis matado",
			Uds: "hubieren matado",
		},
	},
}
