var matricular = {
	Indicative: {
		Present: {
			yo: "matriculo",
			tú: "matriculas",
			Ud: "matricula",
			nosotros: "matriculamos",
			vosotros: "matriculáis",
			Uds: "matriculan",
		},
		Preterite: {
			yo: "matriculé",
			tú: "matriculaste",
			Ud: "matriculó",
			nosotros: "matriculamos",
			vosotros: "matriculasteis",
			Uds: "matricularon",
		},
		Imperfect: {
			yo: "matriculaba",
			tú: "matriculabas",
			Ud: "matriculaba",
			nosotros: "matriculábamos",
			vosotros: "matriculabais",
			Uds: "matriculaban",
		},
		Conditional: {
			yo: "matricularía",
			tú: "matricularías",
			Ud: "matricularía",
			nosotros: "matricularíamos",
			vosotros: "matricularíais",
			Uds: "matricularían",
		},
		Future: {
			yo: "matricularé",
			tú: "matricularás",
			Ud: "matriculará",
			nosotros: "matricularemos",
			vosotros: "matricularéis",
			Uds: "matricularán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "matricule",
			tú: "matricules",
			Ud: "matricule",
			nosotros: "matriculemos",
			vosotros: "matriculéis",
			Uds: "matriculen",
		},
		Imperfect: {
			yo: "matriculara",
			tú: "matricularas",
			Ud: "matriculara",
			nosotros: "matriculáramos",
			vosotros: "matricularais",
			Uds: "matricularan",
		},
		Imperfect2: {
			yo: "matriculase",
			tú: "matriculases",
			Ud: "matriculase",
			nosotros: "matriculásemos",
			vosotros: "matriculaseis",
			Uds: "matriculasen",
		},
		Future: {
			yo: "matriculare",
			tú: "matriculares",
			Ud: "matriculare",
			nosotros: "matriculáremos",
			vosotros: "matriculareis",
			Uds: "matricularen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "matricula",
			Ud: "matricule",
			nosotros: "matriculemos",
			vosotros: "matriculad",
			Uds: "matriculen",
		},
		Negative: {
			tú: "no matricules",
			Ud: "no matricule",
			nosotros: "no matriculemos",
			vosotros: "no matriculéis",
			Uds: "no matriculen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy matriculando",
			tú: "estás matriculando",
			Ud: "está matriculando",
			nosotros: "estamos matriculando",
			vosotros: "estáis matriculando",
			Uds: "están matriculando",
		},
		Preterite: {
			yo: "estuve matriculando",
			tú: "estuviste matriculando",
			Ud: "estuvo matriculando",
			nosotros: "estuvimos matriculando",
			vosotros: "estuvisteis matriculando",
			Uds: "estuvieron matriculando",
		},
		Imperfect: {
			Uds: "estaban matriculando",
			yo: "estaba matriculando",
			tú: "estabas matriculando",
			Ud: "estaba matriculando",
			nosotros: "estábamos matriculando",
			vosotros: "estabais matriculando",
		},
		Conditional: {
			yo: "estaría matriculando",
			tú: "estarías matriculando",
			Ud: "estaría matriculando",
			nosotros: "estaríamos matriculando",
			vosotros: "estaríais matriculando",
			Uds: "estarían matriculando",
		},
		Future: {
			yo: "estaré matriculando",
			tú: "estarás matriculando",
			Ud: "estará matriculando",
			nosotros: "estaremos matriculando",
			vosotros: "estaréis matriculando",
			Uds: "estarán matriculando",
		},
	},
	Perfect: {
		Present: {
			yo: "he matriculado",
			tú: "has matriculado",
			Ud: "ha matriculado",
			nosotros: "hemos matriculado",
			vosotros: "habéis matriculado",
			Uds: "han matriculado",
		},
		Preterite: {
			yo: "hube matriculado",
			tú: "hubiste matriculado",
			Ud: "hubo matriculado",
			nosotros: "hubimos matriculado",
			vosotros: "hubisteis matriculado",
			Uds: "hubieron matriculado",
		},
		Past: {
			yo: "había matriculado",
			tú: "habías matriculado",
			Ud: "había matriculado",
			nosotros: "habíamos matriculado",
			vosotros: "habíais matriculado",
			Uds: "habían matriculado",
		},
		Conditional: {
			yo: "habría matriculado",
			tú: "habrías matriculado",
			Ud: "habría matriculado",
			nosotros: "habríamos matriculado",
			vosotros: "habríais matriculado",
			Uds: "habrían matriculado",
		},
		Future: {
			yo: "habré matriculado",
			tú: "habrás matriculado",
			Ud: "habrá matriculado",
			nosotros: "habremos matriculado",
			vosotros: "habréis matriculado",
			Uds: "habrán matriculado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya matriculado",
			tú: "hayas matriculado",
			Ud: "haya matriculado",
			nosotros: "hayamos matriculado",
			vosotros: "hayáis matriculado",
			Uds: "hayan matriculado",
		},
		Past: {
			yo: "hubiera matriculado",
			tú: "hubieras matriculado",
			Ud: "hubiera matriculado",
			nosotros: "hubiéramos matriculado",
			vosotros: "hubierais matriculado",
			Uds: "hubieran matriculado",
		},
		Future: {
			yo: "hubiere matriculado",
			tú: "hubieres matriculado",
			Ud: "hubiere matriculado",
			nosotros: "hubiéremos matriculado",
			vosotros: "hubiereis matriculado",
			Uds: "hubieren matriculado",
		},
	},
}
