var mendigar = {
	Indicative: {
		Present: {
			yo: "mendigo",
			tú: "mendigas",
			Ud: "mendiga",
			nosotros: "mendigamos",
			vosotros: "mendigáis",
			Uds: "mendigan",
		},
		Preterite: {
			yo: "mendigué",
			tú: "mendigaste",
			Ud: "mendigó",
			nosotros: "mendigamos",
			vosotros: "mendigasteis",
			Uds: "mendigaron",
		},
		Imperfect: {
			yo: "mendigaba",
			tú: "mendigabas",
			Ud: "mendigaba",
			nosotros: "mendigábamos",
			vosotros: "mendigabais",
			Uds: "mendigaban",
		},
		Conditional: {
			yo: "mendigaría",
			tú: "mendigarías",
			Ud: "mendigaría",
			nosotros: "mendigaríamos",
			vosotros: "mendigaríais",
			Uds: "mendigarían",
		},
		Future: {
			yo: "mendigaré",
			tú: "mendigarás",
			Ud: "mendigará",
			nosotros: "mendigaremos",
			vosotros: "mendigaréis",
			Uds: "mendigarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "mendigue",
			tú: "mendigues",
			Ud: "mendigue",
			nosotros: "mendiguemos",
			vosotros: "mendiguéis",
			Uds: "mendiguen",
		},
		Imperfect: {
			yo: "mendigara",
			tú: "mendigaras",
			Ud: "mendigara",
			nosotros: "mendigáramos",
			vosotros: "mendigarais",
			Uds: "mendigaran",
		},
		Imperfect2: {
			yo: "mendigase",
			tú: "mendigases",
			Ud: "mendigase",
			nosotros: "mendigásemos",
			vosotros: "mendigaseis",
			Uds: "mendigasen",
		},
		Future: {
			yo: "mendigare",
			tú: "mendigares",
			Ud: "mendigare",
			nosotros: "mendigáremos",
			vosotros: "mendigareis",
			Uds: "mendigaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "mendiga",
			Ud: "mendigue",
			nosotros: "mendiguemos",
			vosotros: "mendigad",
			Uds: "mendiguen",
		},
		Negative: {
			tú: "no mendigues",
			Ud: "no mendigue",
			nosotros: "no mendiguemos",
			vosotros: "no mendiguéis",
			Uds: "no mendiguen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy mendigando",
			tú: "estás mendigando",
			Ud: "está mendigando",
			nosotros: "estamos mendigando",
			vosotros: "estáis mendigando",
			Uds: "están mendigando",
		},
		Preterite: {
			yo: "estuve mendigando",
			tú: "estuviste mendigando",
			Ud: "estuvo mendigando",
			nosotros: "estuvimos mendigando",
			vosotros: "estuvisteis mendigando",
			Uds: "estuvieron mendigando",
		},
		Imperfect: {
			Uds: "estaban mendigando",
			yo: "estaba mendigando",
			tú: "estabas mendigando",
			Ud: "estaba mendigando",
			nosotros: "estábamos mendigando",
			vosotros: "estabais mendigando",
		},
		Conditional: {
			yo: "estaría mendigando",
			tú: "estarías mendigando",
			Ud: "estaría mendigando",
			nosotros: "estaríamos mendigando",
			vosotros: "estaríais mendigando",
			Uds: "estarían mendigando",
		},
		Future: {
			yo: "estaré mendigando",
			tú: "estarás mendigando",
			Ud: "estará mendigando",
			nosotros: "estaremos mendigando",
			vosotros: "estaréis mendigando",
			Uds: "estarán mendigando",
		},
	},
	Perfect: {
		Present: {
			yo: "he mendigado",
			tú: "has mendigado",
			Ud: "ha mendigado",
			nosotros: "hemos mendigado",
			vosotros: "habéis mendigado",
			Uds: "han mendigado",
		},
		Preterite: {
			yo: "hube mendigado",
			tú: "hubiste mendigado",
			Ud: "hubo mendigado",
			nosotros: "hubimos mendigado",
			vosotros: "hubisteis mendigado",
			Uds: "hubieron mendigado",
		},
		Past: {
			yo: "había mendigado",
			tú: "habías mendigado",
			Ud: "había mendigado",
			nosotros: "habíamos mendigado",
			vosotros: "habíais mendigado",
			Uds: "habían mendigado",
		},
		Conditional: {
			yo: "habría mendigado",
			tú: "habrías mendigado",
			Ud: "habría mendigado",
			nosotros: "habríamos mendigado",
			vosotros: "habríais mendigado",
			Uds: "habrían mendigado",
		},
		Future: {
			yo: "habré mendigado",
			tú: "habrás mendigado",
			Ud: "habrá mendigado",
			nosotros: "habremos mendigado",
			vosotros: "habréis mendigado",
			Uds: "habrán mendigado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya mendigado",
			tú: "hayas mendigado",
			Ud: "haya mendigado",
			nosotros: "hayamos mendigado",
			vosotros: "hayáis mendigado",
			Uds: "hayan mendigado",
		},
		Past: {
			yo: "hubiera mendigado",
			tú: "hubieras mendigado",
			Ud: "hubiera mendigado",
			nosotros: "hubiéramos mendigado",
			vosotros: "hubierais mendigado",
			Uds: "hubieran mendigado",
		},
		Future: {
			yo: "hubiere mendigado",
			tú: "hubieres mendigado",
			Ud: "hubiere mendigado",
			nosotros: "hubiéremos mendigado",
			vosotros: "hubiereis mendigado",
			Uds: "hubieren mendigado",
		},
	},
}
