var mentar = {
	Indicative: {
		Present: {
			yo: "miento",
			tú: "mientas",
			Ud: "mienta",
			nosotros: "mentamos",
			vosotros: "mentáis",
			Uds: "mientan",
		},
		Preterite: {
			yo: "menté",
			tú: "mentaste",
			Ud: "mentó",
			nosotros: "mentamos",
			vosotros: "mentasteis",
			Uds: "mentaron",
		},
		Imperfect: {
			yo: "mentaba",
			tú: "mentabas",
			Ud: "mentaba",
			nosotros: "mentábamos",
			vosotros: "mentabais",
			Uds: "mentaban",
		},
		Conditional: {
			yo: "mentaría",
			tú: "mentarías",
			Ud: "mentaría",
			nosotros: "mentaríamos",
			vosotros: "mentaríais",
			Uds: "mentarían",
		},
		Future: {
			yo: "mentaré",
			tú: "mentarás",
			Ud: "mentará",
			nosotros: "mentaremos",
			vosotros: "mentaréis",
			Uds: "mentarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "miente",
			tú: "mientes",
			Ud: "miente",
			nosotros: "mentemos",
			vosotros: "mentéis",
			Uds: "mienten",
		},
		Imperfect: {
			yo: "mentara",
			tú: "mentaras",
			Ud: "mentara",
			nosotros: "mentáramos",
			vosotros: "mentarais",
			Uds: "mentaran",
		},
		Imperfect2: {
			yo: "mentase",
			tú: "mentases",
			Ud: "mentase",
			nosotros: "mentásemos",
			vosotros: "mentaseis",
			Uds: "mentasen",
		},
		Future: {
			yo: "mentare",
			tú: "mentares",
			Ud: "mentare",
			nosotros: "mentáremos",
			vosotros: "mentareis",
			Uds: "mentaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "mienta",
			Ud: "miente",
			nosotros: "mentemos",
			vosotros: "mentad",
			Uds: "mienten",
		},
		Negative: {
			tú: "no mientes",
			Ud: "no miente",
			nosotros: "no mentemos",
			vosotros: "no mentéis",
			Uds: "no mienten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy mentando",
			tú: "estás mentando",
			Ud: "está mentando",
			nosotros: "estamos mentando",
			vosotros: "estáis mentando",
			Uds: "están mentando",
		},
		Preterite: {
			yo: "estuve mentando",
			tú: "estuviste mentando",
			Ud: "estuvo mentando",
			nosotros: "estuvimos mentando",
			vosotros: "estuvisteis mentando",
			Uds: "estuvieron mentando",
		},
		Imperfect: {
			Uds: "estaban mentando",
			yo: "estaba mentando",
			tú: "estabas mentando",
			Ud: "estaba mentando",
			nosotros: "estábamos mentando",
			vosotros: "estabais mentando",
		},
		Conditional: {
			yo: "estaría mentando",
			tú: "estarías mentando",
			Ud: "estaría mentando",
			nosotros: "estaríamos mentando",
			vosotros: "estaríais mentando",
			Uds: "estarían mentando",
		},
		Future: {
			yo: "estaré mentando",
			tú: "estarás mentando",
			Ud: "estará mentando",
			nosotros: "estaremos mentando",
			vosotros: "estaréis mentando",
			Uds: "estarán mentando",
		},
	},
	Perfect: {
		Present: {
			yo: "he mentado",
			tú: "has mentado",
			Ud: "ha mentado",
			nosotros: "hemos mentado",
			vosotros: "habéis mentado",
			Uds: "han mentado",
		},
		Preterite: {
			yo: "hube mentado",
			tú: "hubiste mentado",
			Ud: "hubo mentado",
			nosotros: "hubimos mentado",
			vosotros: "hubisteis mentado",
			Uds: "hubieron mentado",
		},
		Past: {
			yo: "había mentado",
			tú: "habías mentado",
			Ud: "había mentado",
			nosotros: "habíamos mentado",
			vosotros: "habíais mentado",
			Uds: "habían mentado",
		},
		Conditional: {
			yo: "habría mentado",
			tú: "habrías mentado",
			Ud: "habría mentado",
			nosotros: "habríamos mentado",
			vosotros: "habríais mentado",
			Uds: "habrían mentado",
		},
		Future: {
			yo: "habré mentado",
			tú: "habrás mentado",
			Ud: "habrá mentado",
			nosotros: "habremos mentado",
			vosotros: "habréis mentado",
			Uds: "habrán mentado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya mentado",
			tú: "hayas mentado",
			Ud: "haya mentado",
			nosotros: "hayamos mentado",
			vosotros: "hayáis mentado",
			Uds: "hayan mentado",
		},
		Past: {
			yo: "hubiera mentado",
			tú: "hubieras mentado",
			Ud: "hubiera mentado",
			nosotros: "hubiéramos mentado",
			vosotros: "hubierais mentado",
			Uds: "hubieran mentado",
		},
		Future: {
			yo: "hubiere mentado",
			tú: "hubieres mentado",
			Ud: "hubiere mentado",
			nosotros: "hubiéremos mentado",
			vosotros: "hubiereis mentado",
			Uds: "hubieren mentado",
		},
	},
}
