var merodear = {
	Indicative: {
		Present: {
			yo: "merodeo",
			tú: "merodeas",
			Ud: "merodea",
			nosotros: "merodeamos",
			vosotros: "merodeáis",
			Uds: "merodean",
		},
		Preterite: {
			yo: "merodeé",
			tú: "merodeaste",
			Ud: "merodeó",
			nosotros: "merodeamos",
			vosotros: "merodeasteis",
			Uds: "merodearon",
		},
		Imperfect: {
			yo: "merodeaba",
			tú: "merodeabas",
			Ud: "merodeaba",
			nosotros: "merodeábamos",
			vosotros: "merodeabais",
			Uds: "merodeaban",
		},
		Conditional: {
			yo: "merodearía",
			tú: "merodearías",
			Ud: "merodearía",
			nosotros: "merodearíamos",
			vosotros: "merodearíais",
			Uds: "merodearían",
		},
		Future: {
			yo: "merodearé",
			tú: "merodearás",
			Ud: "merodeará",
			nosotros: "merodearemos",
			vosotros: "merodearéis",
			Uds: "merodearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "merodee",
			tú: "merodees",
			Ud: "merodee",
			nosotros: "merodeemos",
			vosotros: "merodeéis",
			Uds: "merodeen",
		},
		Imperfect: {
			yo: "merodeara",
			tú: "merodearas",
			Ud: "merodeara",
			nosotros: "merodeáramos",
			vosotros: "merodearais",
			Uds: "merodearan",
		},
		Imperfect2: {
			yo: "merodease",
			tú: "merodeases",
			Ud: "merodease",
			nosotros: "merodeásemos",
			vosotros: "merodeaseis",
			Uds: "merodeasen",
		},
		Future: {
			yo: "merodeare",
			tú: "merodeares",
			Ud: "merodeare",
			nosotros: "merodeáremos",
			vosotros: "merodeareis",
			Uds: "merodearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "merodea",
			Ud: "merodee",
			nosotros: "merodeemos",
			vosotros: "merodead",
			Uds: "merodeen",
		},
		Negative: {
			tú: "no merodees",
			Ud: "no merodee",
			nosotros: "no merodeemos",
			vosotros: "no merodeéis",
			Uds: "no merodeen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy merodeando",
			tú: "estás merodeando",
			Ud: "está merodeando",
			nosotros: "estamos merodeando",
			vosotros: "estáis merodeando",
			Uds: "están merodeando",
		},
		Preterite: {
			yo: "estuve merodeando",
			tú: "estuviste merodeando",
			Ud: "estuvo merodeando",
			nosotros: "estuvimos merodeando",
			vosotros: "estuvisteis merodeando",
			Uds: "estuvieron merodeando",
		},
		Imperfect: {
			Uds: "estaban merodeando",
			yo: "estaba merodeando",
			tú: "estabas merodeando",
			Ud: "estaba merodeando",
			nosotros: "estábamos merodeando",
			vosotros: "estabais merodeando",
		},
		Conditional: {
			yo: "estaría merodeando",
			tú: "estarías merodeando",
			Ud: "estaría merodeando",
			nosotros: "estaríamos merodeando",
			vosotros: "estaríais merodeando",
			Uds: "estarían merodeando",
		},
		Future: {
			yo: "estaré merodeando",
			tú: "estarás merodeando",
			Ud: "estará merodeando",
			nosotros: "estaremos merodeando",
			vosotros: "estaréis merodeando",
			Uds: "estarán merodeando",
		},
	},
	Perfect: {
		Present: {
			yo: "he merodeado",
			tú: "has merodeado",
			Ud: "ha merodeado",
			nosotros: "hemos merodeado",
			vosotros: "habéis merodeado",
			Uds: "han merodeado",
		},
		Preterite: {
			yo: "hube merodeado",
			tú: "hubiste merodeado",
			Ud: "hubo merodeado",
			nosotros: "hubimos merodeado",
			vosotros: "hubisteis merodeado",
			Uds: "hubieron merodeado",
		},
		Past: {
			yo: "había merodeado",
			tú: "habías merodeado",
			Ud: "había merodeado",
			nosotros: "habíamos merodeado",
			vosotros: "habíais merodeado",
			Uds: "habían merodeado",
		},
		Conditional: {
			yo: "habría merodeado",
			tú: "habrías merodeado",
			Ud: "habría merodeado",
			nosotros: "habríamos merodeado",
			vosotros: "habríais merodeado",
			Uds: "habrían merodeado",
		},
		Future: {
			yo: "habré merodeado",
			tú: "habrás merodeado",
			Ud: "habrá merodeado",
			nosotros: "habremos merodeado",
			vosotros: "habréis merodeado",
			Uds: "habrán merodeado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya merodeado",
			tú: "hayas merodeado",
			Ud: "haya merodeado",
			nosotros: "hayamos merodeado",
			vosotros: "hayáis merodeado",
			Uds: "hayan merodeado",
		},
		Past: {
			yo: "hubiera merodeado",
			tú: "hubieras merodeado",
			Ud: "hubiera merodeado",
			nosotros: "hubiéramos merodeado",
			vosotros: "hubierais merodeado",
			Uds: "hubieran merodeado",
		},
		Future: {
			yo: "hubiere merodeado",
			tú: "hubieres merodeado",
			Ud: "hubiere merodeado",
			nosotros: "hubiéremos merodeado",
			vosotros: "hubiereis merodeado",
			Uds: "hubieren merodeado",
		},
	},
}
