var mirar = {
	Indicative: {
		Present: {
			yo: "miro",
			tú: "miras",
			Ud: "mira",
			nosotros: "miramos",
			vosotros: "miráis",
			Uds: "miran",
		},
		Preterite: {
			yo: "miré",
			tú: "miraste",
			Ud: "miró",
			nosotros: "miramos",
			vosotros: "mirasteis",
			Uds: "miraron",
		},
		Imperfect: {
			yo: "miraba",
			tú: "mirabas",
			Ud: "miraba",
			nosotros: "mirábamos",
			vosotros: "mirabais",
			Uds: "miraban",
		},
		Conditional: {
			yo: "miraría",
			tú: "mirarías",
			Ud: "miraría",
			nosotros: "miraríamos",
			vosotros: "miraríais",
			Uds: "mirarían",
		},
		Future: {
			yo: "miraré",
			tú: "mirarás",
			Ud: "mirará",
			nosotros: "miraremos",
			vosotros: "miraréis",
			Uds: "mirarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "mire",
			tú: "mires",
			Ud: "mire",
			nosotros: "miremos",
			vosotros: "miréis",
			Uds: "miren",
		},
		Imperfect: {
			yo: "mirara",
			tú: "miraras",
			Ud: "mirara",
			nosotros: "miráramos",
			vosotros: "mirarais",
			Uds: "miraran",
		},
		Imperfect2: {
			yo: "mirase",
			tú: "mirases",
			Ud: "mirase",
			nosotros: "mirásemos",
			vosotros: "miraseis",
			Uds: "mirasen",
		},
		Future: {
			yo: "mirare",
			tú: "mirares",
			Ud: "mirare",
			nosotros: "miráremos",
			vosotros: "mirareis",
			Uds: "miraren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "mira",
			Ud: "mire",
			nosotros: "miremos",
			vosotros: "mirad",
			Uds: "miren",
		},
		Negative: {
			tú: "no mires",
			Ud: "no mire",
			nosotros: "no miremos",
			vosotros: "no miréis",
			Uds: "no miren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy mirando",
			tú: "estás mirando",
			Ud: "está mirando",
			nosotros: "estamos mirando",
			vosotros: "estáis mirando",
			Uds: "están mirando",
		},
		Preterite: {
			yo: "estuve mirando",
			tú: "estuviste mirando",
			Ud: "estuvo mirando",
			nosotros: "estuvimos mirando",
			vosotros: "estuvisteis mirando",
			Uds: "estuvieron mirando",
		},
		Imperfect: {
			Uds: "estaban mirando",
			yo: "estaba mirando",
			tú: "estabas mirando",
			Ud: "estaba mirando",
			nosotros: "estábamos mirando",
			vosotros: "estabais mirando",
		},
		Conditional: {
			yo: "estaría mirando",
			tú: "estarías mirando",
			Ud: "estaría mirando",
			nosotros: "estaríamos mirando",
			vosotros: "estaríais mirando",
			Uds: "estarían mirando",
		},
		Future: {
			yo: "estaré mirando",
			tú: "estarás mirando",
			Ud: "estará mirando",
			nosotros: "estaremos mirando",
			vosotros: "estaréis mirando",
			Uds: "estarán mirando",
		},
	},
	Perfect: {
		Present: {
			yo: "he mirado",
			tú: "has mirado",
			Ud: "ha mirado",
			nosotros: "hemos mirado",
			vosotros: "habéis mirado",
			Uds: "han mirado",
		},
		Preterite: {
			yo: "hube mirado",
			tú: "hubiste mirado",
			Ud: "hubo mirado",
			nosotros: "hubimos mirado",
			vosotros: "hubisteis mirado",
			Uds: "hubieron mirado",
		},
		Past: {
			yo: "había mirado",
			tú: "habías mirado",
			Ud: "había mirado",
			nosotros: "habíamos mirado",
			vosotros: "habíais mirado",
			Uds: "habían mirado",
		},
		Conditional: {
			yo: "habría mirado",
			tú: "habrías mirado",
			Ud: "habría mirado",
			nosotros: "habríamos mirado",
			vosotros: "habríais mirado",
			Uds: "habrían mirado",
		},
		Future: {
			yo: "habré mirado",
			tú: "habrás mirado",
			Ud: "habrá mirado",
			nosotros: "habremos mirado",
			vosotros: "habréis mirado",
			Uds: "habrán mirado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya mirado",
			tú: "hayas mirado",
			Ud: "haya mirado",
			nosotros: "hayamos mirado",
			vosotros: "hayáis mirado",
			Uds: "hayan mirado",
		},
		Past: {
			yo: "hubiera mirado",
			tú: "hubieras mirado",
			Ud: "hubiera mirado",
			nosotros: "hubiéramos mirado",
			vosotros: "hubierais mirado",
			Uds: "hubieran mirado",
		},
		Future: {
			yo: "hubiere mirado",
			tú: "hubieres mirado",
			Ud: "hubiere mirado",
			nosotros: "hubiéremos mirado",
			vosotros: "hubiereis mirado",
			Uds: "hubieren mirado",
		},
	},
}
