var modelar = {
	Indicative: {
		Present: {
			yo: "modelo",
			tú: "modelas",
			Ud: "modela",
			nosotros: "modelamos",
			vosotros: "modeláis",
			Uds: "modelan",
		},
		Preterite: {
			yo: "modelé",
			tú: "modelaste",
			Ud: "modeló",
			nosotros: "modelamos",
			vosotros: "modelasteis",
			Uds: "modelaron",
		},
		Imperfect: {
			yo: "modelaba",
			tú: "modelabas",
			Ud: "modelaba",
			nosotros: "modelábamos",
			vosotros: "modelabais",
			Uds: "modelaban",
		},
		Conditional: {
			yo: "modelaría",
			tú: "modelarías",
			Ud: "modelaría",
			nosotros: "modelaríamos",
			vosotros: "modelaríais",
			Uds: "modelarían",
		},
		Future: {
			yo: "modelaré",
			tú: "modelarás",
			Ud: "modelará",
			nosotros: "modelaremos",
			vosotros: "modelaréis",
			Uds: "modelarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "modele",
			tú: "modeles",
			Ud: "modele",
			nosotros: "modelemos",
			vosotros: "modeléis",
			Uds: "modelen",
		},
		Imperfect: {
			yo: "modelara",
			tú: "modelaras",
			Ud: "modelara",
			nosotros: "modeláramos",
			vosotros: "modelarais",
			Uds: "modelaran",
		},
		Imperfect2: {
			yo: "modelase",
			tú: "modelases",
			Ud: "modelase",
			nosotros: "modelásemos",
			vosotros: "modelaseis",
			Uds: "modelasen",
		},
		Future: {
			yo: "modelare",
			tú: "modelares",
			Ud: "modelare",
			nosotros: "modeláremos",
			vosotros: "modelareis",
			Uds: "modelaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "modela",
			Ud: "modele",
			nosotros: "modelemos",
			vosotros: "modelad",
			Uds: "modelen",
		},
		Negative: {
			tú: "no modeles",
			Ud: "no modele",
			nosotros: "no modelemos",
			vosotros: "no modeléis",
			Uds: "no modelen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy modelando",
			tú: "estás modelando",
			Ud: "está modelando",
			nosotros: "estamos modelando",
			vosotros: "estáis modelando",
			Uds: "están modelando",
		},
		Preterite: {
			yo: "estuve modelando",
			tú: "estuviste modelando",
			Ud: "estuvo modelando",
			nosotros: "estuvimos modelando",
			vosotros: "estuvisteis modelando",
			Uds: "estuvieron modelando",
		},
		Imperfect: {
			Uds: "estaban modelando",
			yo: "estaba modelando",
			tú: "estabas modelando",
			Ud: "estaba modelando",
			nosotros: "estábamos modelando",
			vosotros: "estabais modelando",
		},
		Conditional: {
			yo: "estaría modelando",
			tú: "estarías modelando",
			Ud: "estaría modelando",
			nosotros: "estaríamos modelando",
			vosotros: "estaríais modelando",
			Uds: "estarían modelando",
		},
		Future: {
			yo: "estaré modelando",
			tú: "estarás modelando",
			Ud: "estará modelando",
			nosotros: "estaremos modelando",
			vosotros: "estaréis modelando",
			Uds: "estarán modelando",
		},
	},
	Perfect: {
		Present: {
			yo: "he modelado",
			tú: "has modelado",
			Ud: "ha modelado",
			nosotros: "hemos modelado",
			vosotros: "habéis modelado",
			Uds: "han modelado",
		},
		Preterite: {
			yo: "hube modelado",
			tú: "hubiste modelado",
			Ud: "hubo modelado",
			nosotros: "hubimos modelado",
			vosotros: "hubisteis modelado",
			Uds: "hubieron modelado",
		},
		Past: {
			yo: "había modelado",
			tú: "habías modelado",
			Ud: "había modelado",
			nosotros: "habíamos modelado",
			vosotros: "habíais modelado",
			Uds: "habían modelado",
		},
		Conditional: {
			yo: "habría modelado",
			tú: "habrías modelado",
			Ud: "habría modelado",
			nosotros: "habríamos modelado",
			vosotros: "habríais modelado",
			Uds: "habrían modelado",
		},
		Future: {
			yo: "habré modelado",
			tú: "habrás modelado",
			Ud: "habrá modelado",
			nosotros: "habremos modelado",
			vosotros: "habréis modelado",
			Uds: "habrán modelado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya modelado",
			tú: "hayas modelado",
			Ud: "haya modelado",
			nosotros: "hayamos modelado",
			vosotros: "hayáis modelado",
			Uds: "hayan modelado",
		},
		Past: {
			yo: "hubiera modelado",
			tú: "hubieras modelado",
			Ud: "hubiera modelado",
			nosotros: "hubiéramos modelado",
			vosotros: "hubierais modelado",
			Uds: "hubieran modelado",
		},
		Future: {
			yo: "hubiere modelado",
			tú: "hubieres modelado",
			Ud: "hubiere modelado",
			nosotros: "hubiéremos modelado",
			vosotros: "hubiereis modelado",
			Uds: "hubieren modelado",
		},
	},
}
