var moler = {
	Indicative: {
		Present: {
			yo: "muelo",
			tú: "mueles",
			Ud: "muele",
			nosotros: "molemos",
			vosotros: "moléis",
			Uds: "muelen",
		},
		Preterite: {
			yo: "molí",
			tú: "moliste",
			Ud: "molió",
			nosotros: "molimos",
			vosotros: "molisteis",
			Uds: "molieron",
		},
		Imperfect: {
			yo: "molía",
			tú: "molías",
			Ud: "molía",
			nosotros: "molíamos",
			vosotros: "molíais",
			Uds: "molían",
		},
		Conditional: {
			yo: "molería",
			tú: "molerías",
			Ud: "molería",
			nosotros: "moleríamos",
			vosotros: "moleríais",
			Uds: "molerían",
		},
		Future: {
			yo: "moleré",
			tú: "molerás",
			Ud: "molerá",
			nosotros: "moleremos",
			vosotros: "moleréis",
			Uds: "molerán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "muela",
			tú: "muelas",
			Ud: "muela",
			nosotros: "molamos",
			vosotros: "moláis",
			Uds: "muelan",
		},
		Imperfect: {
			yo: "moliera",
			tú: "molieras",
			Ud: "moliera",
			nosotros: "moliéramos",
			vosotros: "molierais",
			Uds: "molieran",
		},
		Imperfect2: {
			yo: "moliese",
			tú: "molieses",
			Ud: "moliese",
			nosotros: "moliésemos",
			vosotros: "molieseis",
			Uds: "moliesen",
		},
		Future: {
			yo: "moliere",
			tú: "molieres",
			Ud: "moliere",
			nosotros: "moliéremos",
			vosotros: "moliereis",
			Uds: "molieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "muele",
			Ud: "muela",
			nosotros: "molamos",
			vosotros: "moled",
			Uds: "muelan",
		},
		Negative: {
			tú: "no muelas",
			Ud: "no muela",
			nosotros: "no molamos",
			vosotros: "no moláis",
			Uds: "no muelan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy moliendo",
			tú: "estás moliendo",
			Ud: "está moliendo",
			nosotros: "estamos moliendo",
			vosotros: "estáis moliendo",
			Uds: "están moliendo",
		},
		Preterite: {
			yo: "estuve moliendo",
			tú: "estuviste moliendo",
			Ud: "estuvo moliendo",
			nosotros: "estuvimos moliendo",
			vosotros: "estuvisteis moliendo",
			Uds: "estuvieron moliendo",
		},
		Imperfect: {
			Uds: "estaban moliendo",
			yo: "estaba moliendo",
			tú: "estabas moliendo",
			Ud: "estaba moliendo",
			nosotros: "estábamos moliendo",
			vosotros: "estabais moliendo",
		},
		Conditional: {
			yo: "estaría moliendo",
			tú: "estarías moliendo",
			Ud: "estaría moliendo",
			nosotros: "estaríamos moliendo",
			vosotros: "estaríais moliendo",
			Uds: "estarían moliendo",
		},
		Future: {
			yo: "estaré moliendo",
			tú: "estarás moliendo",
			Ud: "estará moliendo",
			nosotros: "estaremos moliendo",
			vosotros: "estaréis moliendo",
			Uds: "estarán moliendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he molido",
			tú: "has molido",
			Ud: "ha molido",
			nosotros: "hemos molido",
			vosotros: "habéis molido",
			Uds: "han molido",
		},
		Preterite: {
			yo: "hube molido",
			tú: "hubiste molido",
			Ud: "hubo molido",
			nosotros: "hubimos molido",
			vosotros: "hubisteis molido",
			Uds: "hubieron molido",
		},
		Past: {
			yo: "había molido",
			tú: "habías molido",
			Ud: "había molido",
			nosotros: "habíamos molido",
			vosotros: "habíais molido",
			Uds: "habían molido",
		},
		Conditional: {
			yo: "habría molido",
			tú: "habrías molido",
			Ud: "habría molido",
			nosotros: "habríamos molido",
			vosotros: "habríais molido",
			Uds: "habrían molido",
		},
		Future: {
			yo: "habré molido",
			tú: "habrás molido",
			Ud: "habrá molido",
			nosotros: "habremos molido",
			vosotros: "habréis molido",
			Uds: "habrán molido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya molido",
			tú: "hayas molido",
			Ud: "haya molido",
			nosotros: "hayamos molido",
			vosotros: "hayáis molido",
			Uds: "hayan molido",
		},
		Past: {
			yo: "hubiera molido",
			tú: "hubieras molido",
			Ud: "hubiera molido",
			nosotros: "hubiéramos molido",
			vosotros: "hubierais molido",
			Uds: "hubieran molido",
		},
		Future: {
			yo: "hubiere molido",
			tú: "hubieres molido",
			Ud: "hubiere molido",
			nosotros: "hubiéremos molido",
			vosotros: "hubiereis molido",
			Uds: "hubieren molido",
		},
	},
}
