var molestar = {
	Indicative: {
		Present: {
			yo: "molesto",
			tú: "molestas",
			Ud: "molesta",
			nosotros: "molestamos",
			vosotros: "molestáis",
			Uds: "molestan",
		},
		Preterite: {
			yo: "molesté",
			tú: "molestaste",
			Ud: "molestó",
			nosotros: "molestamos",
			vosotros: "molestasteis",
			Uds: "molestaron",
		},
		Imperfect: {
			yo: "molestaba",
			tú: "molestabas",
			Ud: "molestaba",
			nosotros: "molestábamos",
			vosotros: "molestabais",
			Uds: "molestaban",
		},
		Conditional: {
			yo: "molestaría",
			tú: "molestarías",
			Ud: "molestaría",
			nosotros: "molestaríamos",
			vosotros: "molestaríais",
			Uds: "molestarían",
		},
		Future: {
			yo: "molestaré",
			tú: "molestarás",
			Ud: "molestará",
			nosotros: "molestaremos",
			vosotros: "molestaréis",
			Uds: "molestarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "moleste",
			tú: "molestes",
			Ud: "moleste",
			nosotros: "molestemos",
			vosotros: "molestéis",
			Uds: "molesten",
		},
		Imperfect: {
			yo: "molestara",
			tú: "molestaras",
			Ud: "molestara",
			nosotros: "molestáramos",
			vosotros: "molestarais",
			Uds: "molestaran",
		},
		Imperfect2: {
			yo: "molestase",
			tú: "molestases",
			Ud: "molestase",
			nosotros: "molestásemos",
			vosotros: "molestaseis",
			Uds: "molestasen",
		},
		Future: {
			yo: "molestare",
			tú: "molestares",
			Ud: "molestare",
			nosotros: "molestáremos",
			vosotros: "molestareis",
			Uds: "molestaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "molesta",
			Ud: "moleste",
			nosotros: "molestemos",
			vosotros: "molestad",
			Uds: "molesten",
		},
		Negative: {
			tú: "no molestes",
			Ud: "no moleste",
			nosotros: "no molestemos",
			vosotros: "no molestéis",
			Uds: "no molesten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy molestando",
			tú: "estás molestando",
			Ud: "está molestando",
			nosotros: "estamos molestando",
			vosotros: "estáis molestando",
			Uds: "están molestando",
		},
		Preterite: {
			yo: "estuve molestando",
			tú: "estuviste molestando",
			Ud: "estuvo molestando",
			nosotros: "estuvimos molestando",
			vosotros: "estuvisteis molestando",
			Uds: "estuvieron molestando",
		},
		Imperfect: {
			Uds: "estaban molestando",
			yo: "estaba molestando",
			tú: "estabas molestando",
			Ud: "estaba molestando",
			nosotros: "estábamos molestando",
			vosotros: "estabais molestando",
		},
		Conditional: {
			yo: "estaría molestando",
			tú: "estarías molestando",
			Ud: "estaría molestando",
			nosotros: "estaríamos molestando",
			vosotros: "estaríais molestando",
			Uds: "estarían molestando",
		},
		Future: {
			yo: "estaré molestando",
			tú: "estarás molestando",
			Ud: "estará molestando",
			nosotros: "estaremos molestando",
			vosotros: "estaréis molestando",
			Uds: "estarán molestando",
		},
	},
	Perfect: {
		Present: {
			yo: "he molestado",
			tú: "has molestado",
			Ud: "ha molestado",
			nosotros: "hemos molestado",
			vosotros: "habéis molestado",
			Uds: "han molestado",
		},
		Preterite: {
			yo: "hube molestado",
			tú: "hubiste molestado",
			Ud: "hubo molestado",
			nosotros: "hubimos molestado",
			vosotros: "hubisteis molestado",
			Uds: "hubieron molestado",
		},
		Past: {
			yo: "había molestado",
			tú: "habías molestado",
			Ud: "había molestado",
			nosotros: "habíamos molestado",
			vosotros: "habíais molestado",
			Uds: "habían molestado",
		},
		Conditional: {
			yo: "habría molestado",
			tú: "habrías molestado",
			Ud: "habría molestado",
			nosotros: "habríamos molestado",
			vosotros: "habríais molestado",
			Uds: "habrían molestado",
		},
		Future: {
			yo: "habré molestado",
			tú: "habrás molestado",
			Ud: "habrá molestado",
			nosotros: "habremos molestado",
			vosotros: "habréis molestado",
			Uds: "habrán molestado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya molestado",
			tú: "hayas molestado",
			Ud: "haya molestado",
			nosotros: "hayamos molestado",
			vosotros: "hayáis molestado",
			Uds: "hayan molestado",
		},
		Past: {
			yo: "hubiera molestado",
			tú: "hubieras molestado",
			Ud: "hubiera molestado",
			nosotros: "hubiéramos molestado",
			vosotros: "hubierais molestado",
			Uds: "hubieran molestado",
		},
		Future: {
			yo: "hubiere molestado",
			tú: "hubieres molestado",
			Ud: "hubiere molestado",
			nosotros: "hubiéremos molestado",
			vosotros: "hubiereis molestado",
			Uds: "hubieren molestado",
		},
	},
}
