var montar = {
	Indicative: {
		Present: {
			yo: "monto",
			tú: "montas",
			Ud: "monta",
			nosotros: "montamos",
			vosotros: "montáis",
			Uds: "montan",
		},
		Preterite: {
			yo: "monté",
			tú: "montaste",
			Ud: "montó",
			nosotros: "montamos",
			vosotros: "montasteis",
			Uds: "montaron",
		},
		Imperfect: {
			yo: "montaba",
			tú: "montabas",
			Ud: "montaba",
			nosotros: "montábamos",
			vosotros: "montabais",
			Uds: "montaban",
		},
		Conditional: {
			yo: "montaría",
			tú: "montarías",
			Ud: "montaría",
			nosotros: "montaríamos",
			vosotros: "montaríais",
			Uds: "montarían",
		},
		Future: {
			yo: "montaré",
			tú: "montarás",
			Ud: "montará",
			nosotros: "montaremos",
			vosotros: "montaréis",
			Uds: "montarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "monte",
			tú: "montes",
			Ud: "monte",
			nosotros: "montemos",
			vosotros: "montéis",
			Uds: "monten",
		},
		Imperfect: {
			yo: "montara",
			tú: "montaras",
			Ud: "montara",
			nosotros: "montáramos",
			vosotros: "montarais",
			Uds: "montaran",
		},
		Imperfect2: {
			yo: "montase",
			tú: "montases",
			Ud: "montase",
			nosotros: "montásemos",
			vosotros: "montaseis",
			Uds: "montasen",
		},
		Future: {
			yo: "montare",
			tú: "montares",
			Ud: "montare",
			nosotros: "montáremos",
			vosotros: "montareis",
			Uds: "montaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "monta",
			Ud: "monte",
			nosotros: "montemos",
			vosotros: "montad",
			Uds: "monten",
		},
		Negative: {
			tú: "no montes",
			Ud: "no monte",
			nosotros: "no montemos",
			vosotros: "no montéis",
			Uds: "no monten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy montando",
			tú: "estás montando",
			Ud: "está montando",
			nosotros: "estamos montando",
			vosotros: "estáis montando",
			Uds: "están montando",
		},
		Preterite: {
			yo: "estuve montando",
			tú: "estuviste montando",
			Ud: "estuvo montando",
			nosotros: "estuvimos montando",
			vosotros: "estuvisteis montando",
			Uds: "estuvieron montando",
		},
		Imperfect: {
			Uds: "estaban montando",
			yo: "estaba montando",
			tú: "estabas montando",
			Ud: "estaba montando",
			nosotros: "estábamos montando",
			vosotros: "estabais montando",
		},
		Conditional: {
			yo: "estaría montando",
			tú: "estarías montando",
			Ud: "estaría montando",
			nosotros: "estaríamos montando",
			vosotros: "estaríais montando",
			Uds: "estarían montando",
		},
		Future: {
			yo: "estaré montando",
			tú: "estarás montando",
			Ud: "estará montando",
			nosotros: "estaremos montando",
			vosotros: "estaréis montando",
			Uds: "estarán montando",
		},
	},
	Perfect: {
		Present: {
			yo: "he montado",
			tú: "has montado",
			Ud: "ha montado",
			nosotros: "hemos montado",
			vosotros: "habéis montado",
			Uds: "han montado",
		},
		Preterite: {
			yo: "hube montado",
			tú: "hubiste montado",
			Ud: "hubo montado",
			nosotros: "hubimos montado",
			vosotros: "hubisteis montado",
			Uds: "hubieron montado",
		},
		Past: {
			yo: "había montado",
			tú: "habías montado",
			Ud: "había montado",
			nosotros: "habíamos montado",
			vosotros: "habíais montado",
			Uds: "habían montado",
		},
		Conditional: {
			yo: "habría montado",
			tú: "habrías montado",
			Ud: "habría montado",
			nosotros: "habríamos montado",
			vosotros: "habríais montado",
			Uds: "habrían montado",
		},
		Future: {
			yo: "habré montado",
			tú: "habrás montado",
			Ud: "habrá montado",
			nosotros: "habremos montado",
			vosotros: "habréis montado",
			Uds: "habrán montado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya montado",
			tú: "hayas montado",
			Ud: "haya montado",
			nosotros: "hayamos montado",
			vosotros: "hayáis montado",
			Uds: "hayan montado",
		},
		Past: {
			yo: "hubiera montado",
			tú: "hubieras montado",
			Ud: "hubiera montado",
			nosotros: "hubiéramos montado",
			vosotros: "hubierais montado",
			Uds: "hubieran montado",
		},
		Future: {
			yo: "hubiere montado",
			tú: "hubieres montado",
			Ud: "hubiere montado",
			nosotros: "hubiéremos montado",
			vosotros: "hubiereis montado",
			Uds: "hubieren montado",
		},
	},
}
