var mostrar = {
	Indicative: {
		Present: {
			yo: "muestro",
			tú: "muestras",
			Ud: "muestra",
			nosotros: "mostramos",
			vosotros: "mostráis",
			Uds: "muestran",
		},
		Preterite: {
			yo: "mostré",
			tú: "mostraste",
			Ud: "mostró",
			nosotros: "mostramos",
			vosotros: "mostrasteis",
			Uds: "mostraron",
		},
		Imperfect: {
			yo: "mostraba",
			tú: "mostrabas",
			Ud: "mostraba",
			nosotros: "mostrábamos",
			vosotros: "mostrabais",
			Uds: "mostraban",
		},
		Conditional: {
			yo: "mostraría",
			tú: "mostrarías",
			Ud: "mostraría",
			nosotros: "mostraríamos",
			vosotros: "mostraríais",
			Uds: "mostrarían",
		},
		Future: {
			yo: "mostraré",
			tú: "mostrarás",
			Ud: "mostrará",
			nosotros: "mostraremos",
			vosotros: "mostraréis",
			Uds: "mostrarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "muestre",
			tú: "muestres",
			Ud: "muestre",
			nosotros: "mostremos",
			vosotros: "mostréis",
			Uds: "muestren",
		},
		Imperfect: {
			yo: "mostrara",
			tú: "mostraras",
			Ud: "mostrara",
			nosotros: "mostráramos",
			vosotros: "mostrarais",
			Uds: "mostraran",
		},
		Imperfect2: {
			yo: "mostrase",
			tú: "mostrases",
			Ud: "mostrase",
			nosotros: "mostrásemos",
			vosotros: "mostraseis",
			Uds: "mostrasen",
		},
		Future: {
			yo: "mostrare",
			tú: "mostrares",
			Ud: "mostrare",
			nosotros: "mostráremos",
			vosotros: "mostrareis",
			Uds: "mostraren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "muestra",
			Ud: "muestre",
			nosotros: "mostremos",
			vosotros: "mostrad",
			Uds: "muestren",
		},
		Negative: {
			tú: "no muestres",
			Ud: "no muestre",
			nosotros: "no mostremos",
			vosotros: "no mostréis",
			Uds: "no muestren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy mostrando",
			tú: "estás mostrando",
			Ud: "está mostrando",
			nosotros: "estamos mostrando",
			vosotros: "estáis mostrando",
			Uds: "están mostrando",
		},
		Preterite: {
			yo: "estuve mostrando",
			tú: "estuviste mostrando",
			Ud: "estuvo mostrando",
			nosotros: "estuvimos mostrando",
			vosotros: "estuvisteis mostrando",
			Uds: "estuvieron mostrando",
		},
		Imperfect: {
			Uds: "estaban mostrando",
			yo: "estaba mostrando",
			tú: "estabas mostrando",
			Ud: "estaba mostrando",
			nosotros: "estábamos mostrando",
			vosotros: "estabais mostrando",
		},
		Conditional: {
			yo: "estaría mostrando",
			tú: "estarías mostrando",
			Ud: "estaría mostrando",
			nosotros: "estaríamos mostrando",
			vosotros: "estaríais mostrando",
			Uds: "estarían mostrando",
		},
		Future: {
			yo: "estaré mostrando",
			tú: "estarás mostrando",
			Ud: "estará mostrando",
			nosotros: "estaremos mostrando",
			vosotros: "estaréis mostrando",
			Uds: "estarán mostrando",
		},
	},
	Perfect: {
		Present: {
			yo: "he mostrado",
			tú: "has mostrado",
			Ud: "ha mostrado",
			nosotros: "hemos mostrado",
			vosotros: "habéis mostrado",
			Uds: "han mostrado",
		},
		Preterite: {
			yo: "hube mostrado",
			tú: "hubiste mostrado",
			Ud: "hubo mostrado",
			nosotros: "hubimos mostrado",
			vosotros: "hubisteis mostrado",
			Uds: "hubieron mostrado",
		},
		Past: {
			yo: "había mostrado",
			tú: "habías mostrado",
			Ud: "había mostrado",
			nosotros: "habíamos mostrado",
			vosotros: "habíais mostrado",
			Uds: "habían mostrado",
		},
		Conditional: {
			yo: "habría mostrado",
			tú: "habrías mostrado",
			Ud: "habría mostrado",
			nosotros: "habríamos mostrado",
			vosotros: "habríais mostrado",
			Uds: "habrían mostrado",
		},
		Future: {
			yo: "habré mostrado",
			tú: "habrás mostrado",
			Ud: "habrá mostrado",
			nosotros: "habremos mostrado",
			vosotros: "habréis mostrado",
			Uds: "habrán mostrado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya mostrado",
			tú: "hayas mostrado",
			Ud: "haya mostrado",
			nosotros: "hayamos mostrado",
			vosotros: "hayáis mostrado",
			Uds: "hayan mostrado",
		},
		Past: {
			yo: "hubiera mostrado",
			tú: "hubieras mostrado",
			Ud: "hubiera mostrado",
			nosotros: "hubiéramos mostrado",
			vosotros: "hubierais mostrado",
			Uds: "hubieran mostrado",
		},
		Future: {
			yo: "hubiere mostrado",
			tú: "hubieres mostrado",
			Ud: "hubiere mostrado",
			nosotros: "hubiéremos mostrado",
			vosotros: "hubiereis mostrado",
			Uds: "hubieren mostrado",
		},
	},
}
