var mover = {
	Indicative: {
		Present: {
			yo: "muevo",
			tú: "mueves",
			Ud: "mueve",
			nosotros: "movemos",
			vosotros: "movéis",
			Uds: "mueven",
		},
		Preterite: {
			yo: "moví",
			tú: "moviste",
			Ud: "movió",
			nosotros: "movimos",
			vosotros: "movisteis",
			Uds: "movieron",
		},
		Imperfect: {
			yo: "movía",
			tú: "movías",
			Ud: "movía",
			nosotros: "movíamos",
			vosotros: "movíais",
			Uds: "movían",
		},
		Conditional: {
			yo: "movería",
			tú: "moverías",
			Ud: "movería",
			nosotros: "moveríamos",
			vosotros: "moveríais",
			Uds: "moverían",
		},
		Future: {
			yo: "moveré",
			tú: "moverás",
			Ud: "moverá",
			nosotros: "moveremos",
			vosotros: "moveréis",
			Uds: "moverán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "mueva",
			tú: "muevas",
			Ud: "mueva",
			nosotros: "movamos",
			vosotros: "mováis",
			Uds: "muevan",
		},
		Imperfect: {
			yo: "moviera",
			tú: "movieras",
			Ud: "moviera",
			nosotros: "moviéramos",
			vosotros: "movierais",
			Uds: "movieran",
		},
		Imperfect2: {
			yo: "moviese",
			tú: "movieses",
			Ud: "moviese",
			nosotros: "moviésemos",
			vosotros: "movieseis",
			Uds: "moviesen",
		},
		Future: {
			yo: "moviere",
			tú: "movieres",
			Ud: "moviere",
			nosotros: "moviéremos",
			vosotros: "moviereis",
			Uds: "movieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "mueve",
			Ud: "mueva",
			nosotros: "movamos",
			vosotros: "moved",
			Uds: "muevan",
		},
		Negative: {
			tú: "no muevas",
			Ud: "no mueva",
			nosotros: "no movamos",
			vosotros: "no mováis",
			Uds: "no muevan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy moviendo",
			tú: "estás moviendo",
			Ud: "está moviendo",
			nosotros: "estamos moviendo",
			vosotros: "estáis moviendo",
			Uds: "están moviendo",
		},
		Preterite: {
			yo: "estuve moviendo",
			tú: "estuviste moviendo",
			Ud: "estuvo moviendo",
			nosotros: "estuvimos moviendo",
			vosotros: "estuvisteis moviendo",
			Uds: "estuvieron moviendo",
		},
		Imperfect: {
			Uds: "estaban moviendo",
			yo: "estaba moviendo",
			tú: "estabas moviendo",
			Ud: "estaba moviendo",
			nosotros: "estábamos moviendo",
			vosotros: "estabais moviendo",
		},
		Conditional: {
			yo: "estaría moviendo",
			tú: "estarías moviendo",
			Ud: "estaría moviendo",
			nosotros: "estaríamos moviendo",
			vosotros: "estaríais moviendo",
			Uds: "estarían moviendo",
		},
		Future: {
			yo: "estaré moviendo",
			tú: "estarás moviendo",
			Ud: "estará moviendo",
			nosotros: "estaremos moviendo",
			vosotros: "estaréis moviendo",
			Uds: "estarán moviendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he movido",
			tú: "has movido",
			Ud: "ha movido",
			nosotros: "hemos movido",
			vosotros: "habéis movido",
			Uds: "han movido",
		},
		Preterite: {
			yo: "hube movido",
			tú: "hubiste movido",
			Ud: "hubo movido",
			nosotros: "hubimos movido",
			vosotros: "hubisteis movido",
			Uds: "hubieron movido",
		},
		Past: {
			yo: "había movido",
			tú: "habías movido",
			Ud: "había movido",
			nosotros: "habíamos movido",
			vosotros: "habíais movido",
			Uds: "habían movido",
		},
		Conditional: {
			yo: "habría movido",
			tú: "habrías movido",
			Ud: "habría movido",
			nosotros: "habríamos movido",
			vosotros: "habríais movido",
			Uds: "habrían movido",
		},
		Future: {
			yo: "habré movido",
			tú: "habrás movido",
			Ud: "habrá movido",
			nosotros: "habremos movido",
			vosotros: "habréis movido",
			Uds: "habrán movido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya movido",
			tú: "hayas movido",
			Ud: "haya movido",
			nosotros: "hayamos movido",
			vosotros: "hayáis movido",
			Uds: "hayan movido",
		},
		Past: {
			yo: "hubiera movido",
			tú: "hubieras movido",
			Ud: "hubiera movido",
			nosotros: "hubiéramos movido",
			vosotros: "hubierais movido",
			Uds: "hubieran movido",
		},
		Future: {
			yo: "hubiere movido",
			tú: "hubieres movido",
			Ud: "hubiere movido",
			nosotros: "hubiéremos movido",
			vosotros: "hubiereis movido",
			Uds: "hubieren movido",
		},
	},
}
