var nadar = {
	Indicative: {
		Present: {
			yo: "nado",
			tú: "nadas",
			Ud: "nada",
			nosotros: "nadamos",
			vosotros: "nadáis",
			Uds: "nadan",
		},
		Preterite: {
			yo: "nadé",
			tú: "nadaste",
			Ud: "nadó",
			nosotros: "nadamos",
			vosotros: "nadasteis",
			Uds: "nadaron",
		},
		Imperfect: {
			yo: "nadaba",
			tú: "nadabas",
			Ud: "nadaba",
			nosotros: "nadábamos",
			vosotros: "nadabais",
			Uds: "nadaban",
		},
		Conditional: {
			yo: "nadaría",
			tú: "nadarías",
			Ud: "nadaría",
			nosotros: "nadaríamos",
			vosotros: "nadaríais",
			Uds: "nadarían",
		},
		Future: {
			yo: "nadaré",
			tú: "nadarás",
			Ud: "nadará",
			nosotros: "nadaremos",
			vosotros: "nadaréis",
			Uds: "nadarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "nade",
			tú: "nades",
			Ud: "nade",
			nosotros: "nademos",
			vosotros: "nadéis",
			Uds: "naden",
		},
		Imperfect: {
			yo: "nadara",
			tú: "nadaras",
			Ud: "nadara",
			nosotros: "nadáramos",
			vosotros: "nadarais",
			Uds: "nadaran",
		},
		Imperfect2: {
			yo: "nadase",
			tú: "nadases",
			Ud: "nadase",
			nosotros: "nadásemos",
			vosotros: "nadaseis",
			Uds: "nadasen",
		},
		Future: {
			yo: "nadare",
			tú: "nadares",
			Ud: "nadare",
			nosotros: "nadáremos",
			vosotros: "nadareis",
			Uds: "nadaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "nada",
			Ud: "nade",
			nosotros: "nademos",
			vosotros: "nadad",
			Uds: "naden",
		},
		Negative: {
			tú: "no nades",
			Ud: "no nade",
			nosotros: "no nademos",
			vosotros: "no nadéis",
			Uds: "no naden",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy nadando",
			tú: "estás nadando",
			Ud: "está nadando",
			nosotros: "estamos nadando",
			vosotros: "estáis nadando",
			Uds: "están nadando",
		},
		Preterite: {
			yo: "estuve nadando",
			tú: "estuviste nadando",
			Ud: "estuvo nadando",
			nosotros: "estuvimos nadando",
			vosotros: "estuvisteis nadando",
			Uds: "estuvieron nadando",
		},
		Imperfect: {
			Uds: "estaban nadando",
			yo: "estaba nadando",
			tú: "estabas nadando",
			Ud: "estaba nadando",
			nosotros: "estábamos nadando",
			vosotros: "estabais nadando",
		},
		Conditional: {
			yo: "estaría nadando",
			tú: "estarías nadando",
			Ud: "estaría nadando",
			nosotros: "estaríamos nadando",
			vosotros: "estaríais nadando",
			Uds: "estarían nadando",
		},
		Future: {
			yo: "estaré nadando",
			tú: "estarás nadando",
			Ud: "estará nadando",
			nosotros: "estaremos nadando",
			vosotros: "estaréis nadando",
			Uds: "estarán nadando",
		},
	},
	Perfect: {
		Present: {
			yo: "he nadado",
			tú: "has nadado",
			Ud: "ha nadado",
			nosotros: "hemos nadado",
			vosotros: "habéis nadado",
			Uds: "han nadado",
		},
		Preterite: {
			yo: "hube nadado",
			tú: "hubiste nadado",
			Ud: "hubo nadado",
			nosotros: "hubimos nadado",
			vosotros: "hubisteis nadado",
			Uds: "hubieron nadado",
		},
		Past: {
			yo: "había nadado",
			tú: "habías nadado",
			Ud: "había nadado",
			nosotros: "habíamos nadado",
			vosotros: "habíais nadado",
			Uds: "habían nadado",
		},
		Conditional: {
			yo: "habría nadado",
			tú: "habrías nadado",
			Ud: "habría nadado",
			nosotros: "habríamos nadado",
			vosotros: "habríais nadado",
			Uds: "habrían nadado",
		},
		Future: {
			yo: "habré nadado",
			tú: "habrás nadado",
			Ud: "habrá nadado",
			nosotros: "habremos nadado",
			vosotros: "habréis nadado",
			Uds: "habrán nadado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya nadado",
			tú: "hayas nadado",
			Ud: "haya nadado",
			nosotros: "hayamos nadado",
			vosotros: "hayáis nadado",
			Uds: "hayan nadado",
		},
		Past: {
			yo: "hubiera nadado",
			tú: "hubieras nadado",
			Ud: "hubiera nadado",
			nosotros: "hubiéramos nadado",
			vosotros: "hubierais nadado",
			Uds: "hubieran nadado",
		},
		Future: {
			yo: "hubiere nadado",
			tú: "hubieres nadado",
			Ud: "hubiere nadado",
			nosotros: "hubiéremos nadado",
			vosotros: "hubiereis nadado",
			Uds: "hubieren nadado",
		},
	},
}
