var necesitar = {
	Indicative: {
		Present: {
			yo: "necesito",
			tú: "necesitas",
			Ud: "necesita",
			nosotros: "necesitamos",
			vosotros: "necesitáis",
			Uds: "necesitan",
		},
		Preterite: {
			yo: "necesité",
			tú: "necesitaste",
			Ud: "necesitó",
			nosotros: "necesitamos",
			vosotros: "necesitasteis",
			Uds: "necesitaron",
		},
		Imperfect: {
			yo: "necesitaba",
			tú: "necesitabas",
			Ud: "necesitaba",
			nosotros: "necesitábamos",
			vosotros: "necesitabais",
			Uds: "necesitaban",
		},
		Conditional: {
			yo: "necesitaría",
			tú: "necesitarías",
			Ud: "necesitaría",
			nosotros: "necesitaríamos",
			vosotros: "necesitaríais",
			Uds: "necesitarían",
		},
		Future: {
			yo: "necesitaré",
			tú: "necesitarás",
			Ud: "necesitará",
			nosotros: "necesitaremos",
			vosotros: "necesitaréis",
			Uds: "necesitarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "necesite",
			tú: "necesites",
			Ud: "necesite",
			nosotros: "necesitemos",
			vosotros: "necesitéis",
			Uds: "necesiten",
		},
		Imperfect: {
			yo: "necesitara",
			tú: "necesitaras",
			Ud: "necesitara",
			nosotros: "necesitáramos",
			vosotros: "necesitarais",
			Uds: "necesitaran",
		},
		Imperfect2: {
			yo: "necesitase",
			tú: "necesitases",
			Ud: "necesitase",
			nosotros: "necesitásemos",
			vosotros: "necesitaseis",
			Uds: "necesitasen",
		},
		Future: {
			yo: "necesitare",
			tú: "necesitares",
			Ud: "necesitare",
			nosotros: "necesitáremos",
			vosotros: "necesitareis",
			Uds: "necesitaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "necesita",
			Ud: "necesite",
			nosotros: "necesitemos",
			vosotros: "necesitad",
			Uds: "necesiten",
		},
		Negative: {
			tú: "no necesites",
			Ud: "no necesite",
			nosotros: "no necesitemos",
			vosotros: "no necesitéis",
			Uds: "no necesiten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy necesitando",
			tú: "estás necesitando",
			Ud: "está necesitando",
			nosotros: "estamos necesitando",
			vosotros: "estáis necesitando",
			Uds: "están necesitando",
		},
		Preterite: {
			yo: "estuve necesitando",
			tú: "estuviste necesitando",
			Ud: "estuvo necesitando",
			nosotros: "estuvimos necesitando",
			vosotros: "estuvisteis necesitando",
			Uds: "estuvieron necesitando",
		},
		Imperfect: {
			Uds: "estaban necesitando",
			yo: "estaba necesitando",
			tú: "estabas necesitando",
			Ud: "estaba necesitando",
			nosotros: "estábamos necesitando",
			vosotros: "estabais necesitando",
		},
		Conditional: {
			yo: "estaría necesitando",
			tú: "estarías necesitando",
			Ud: "estaría necesitando",
			nosotros: "estaríamos necesitando",
			vosotros: "estaríais necesitando",
			Uds: "estarían necesitando",
		},
		Future: {
			yo: "estaré necesitando",
			tú: "estarás necesitando",
			Ud: "estará necesitando",
			nosotros: "estaremos necesitando",
			vosotros: "estaréis necesitando",
			Uds: "estarán necesitando",
		},
	},
	Perfect: {
		Present: {
			yo: "he necesitado",
			tú: "has necesitado",
			Ud: "ha necesitado",
			nosotros: "hemos necesitado",
			vosotros: "habéis necesitado",
			Uds: "han necesitado",
		},
		Preterite: {
			yo: "hube necesitado",
			tú: "hubiste necesitado",
			Ud: "hubo necesitado",
			nosotros: "hubimos necesitado",
			vosotros: "hubisteis necesitado",
			Uds: "hubieron necesitado",
		},
		Past: {
			yo: "había necesitado",
			tú: "habías necesitado",
			Ud: "había necesitado",
			nosotros: "habíamos necesitado",
			vosotros: "habíais necesitado",
			Uds: "habían necesitado",
		},
		Conditional: {
			yo: "habría necesitado",
			tú: "habrías necesitado",
			Ud: "habría necesitado",
			nosotros: "habríamos necesitado",
			vosotros: "habríais necesitado",
			Uds: "habrían necesitado",
		},
		Future: {
			yo: "habré necesitado",
			tú: "habrás necesitado",
			Ud: "habrá necesitado",
			nosotros: "habremos necesitado",
			vosotros: "habréis necesitado",
			Uds: "habrán necesitado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya necesitado",
			tú: "hayas necesitado",
			Ud: "haya necesitado",
			nosotros: "hayamos necesitado",
			vosotros: "hayáis necesitado",
			Uds: "hayan necesitado",
		},
		Past: {
			yo: "hubiera necesitado",
			tú: "hubieras necesitado",
			Ud: "hubiera necesitado",
			nosotros: "hubiéramos necesitado",
			vosotros: "hubierais necesitado",
			Uds: "hubieran necesitado",
		},
		Future: {
			yo: "hubiere necesitado",
			tú: "hubieres necesitado",
			Ud: "hubiere necesitado",
			nosotros: "hubiéremos necesitado",
			vosotros: "hubiereis necesitado",
			Uds: "hubieren necesitado",
		},
	},
}
