var notar = {
	Indicative: {
		Present: {
			yo: "noto",
			tú: "notas",
			Ud: "nota",
			nosotros: "notamos",
			vosotros: "notáis",
			Uds: "notan",
		},
		Preterite: {
			yo: "noté",
			tú: "notaste",
			Ud: "notó",
			nosotros: "notamos",
			vosotros: "notasteis",
			Uds: "notaron",
		},
		Imperfect: {
			yo: "notaba",
			tú: "notabas",
			Ud: "notaba",
			nosotros: "notábamos",
			vosotros: "notabais",
			Uds: "notaban",
		},
		Conditional: {
			yo: "notaría",
			tú: "notarías",
			Ud: "notaría",
			nosotros: "notaríamos",
			vosotros: "notaríais",
			Uds: "notarían",
		},
		Future: {
			yo: "notaré",
			tú: "notarás",
			Ud: "notará",
			nosotros: "notaremos",
			vosotros: "notaréis",
			Uds: "notarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "note",
			tú: "notes",
			Ud: "note",
			nosotros: "notemos",
			vosotros: "notéis",
			Uds: "noten",
		},
		Imperfect: {
			yo: "notara",
			tú: "notaras",
			Ud: "notara",
			nosotros: "notáramos",
			vosotros: "notarais",
			Uds: "notaran",
		},
		Imperfect2: {
			yo: "notase",
			tú: "notases",
			Ud: "notase",
			nosotros: "notásemos",
			vosotros: "notaseis",
			Uds: "notasen",
		},
		Future: {
			yo: "notare",
			tú: "notares",
			Ud: "notare",
			nosotros: "notáremos",
			vosotros: "notareis",
			Uds: "notaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "nota",
			Ud: "note",
			nosotros: "notemos",
			vosotros: "notad",
			Uds: "noten",
		},
		Negative: {
			tú: "no notes",
			Ud: "no note",
			nosotros: "no notemos",
			vosotros: "no notéis",
			Uds: "no noten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy notando",
			tú: "estás notando",
			Ud: "está notando",
			nosotros: "estamos notando",
			vosotros: "estáis notando",
			Uds: "están notando",
		},
		Preterite: {
			yo: "estuve notando",
			tú: "estuviste notando",
			Ud: "estuvo notando",
			nosotros: "estuvimos notando",
			vosotros: "estuvisteis notando",
			Uds: "estuvieron notando",
		},
		Imperfect: {
			Uds: "estaban notando",
			yo: "estaba notando",
			tú: "estabas notando",
			Ud: "estaba notando",
			nosotros: "estábamos notando",
			vosotros: "estabais notando",
		},
		Conditional: {
			yo: "estaría notando",
			tú: "estarías notando",
			Ud: "estaría notando",
			nosotros: "estaríamos notando",
			vosotros: "estaríais notando",
			Uds: "estarían notando",
		},
		Future: {
			yo: "estaré notando",
			tú: "estarás notando",
			Ud: "estará notando",
			nosotros: "estaremos notando",
			vosotros: "estaréis notando",
			Uds: "estarán notando",
		},
	},
	Perfect: {
		Present: {
			yo: "he notado",
			tú: "has notado",
			Ud: "ha notado",
			nosotros: "hemos notado",
			vosotros: "habéis notado",
			Uds: "han notado",
		},
		Preterite: {
			yo: "hube notado",
			tú: "hubiste notado",
			Ud: "hubo notado",
			nosotros: "hubimos notado",
			vosotros: "hubisteis notado",
			Uds: "hubieron notado",
		},
		Past: {
			yo: "había notado",
			tú: "habías notado",
			Ud: "había notado",
			nosotros: "habíamos notado",
			vosotros: "habíais notado",
			Uds: "habían notado",
		},
		Conditional: {
			yo: "habría notado",
			tú: "habrías notado",
			Ud: "habría notado",
			nosotros: "habríamos notado",
			vosotros: "habríais notado",
			Uds: "habrían notado",
		},
		Future: {
			yo: "habré notado",
			tú: "habrás notado",
			Ud: "habrá notado",
			nosotros: "habremos notado",
			vosotros: "habréis notado",
			Uds: "habrán notado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya notado",
			tú: "hayas notado",
			Ud: "haya notado",
			nosotros: "hayamos notado",
			vosotros: "hayáis notado",
			Uds: "hayan notado",
		},
		Past: {
			yo: "hubiera notado",
			tú: "hubieras notado",
			Ud: "hubiera notado",
			nosotros: "hubiéramos notado",
			vosotros: "hubierais notado",
			Uds: "hubieran notado",
		},
		Future: {
			yo: "hubiere notado",
			tú: "hubieres notado",
			Ud: "hubiere notado",
			nosotros: "hubiéremos notado",
			vosotros: "hubiereis notado",
			Uds: "hubieren notado",
		},
	},
}
