var notificar = {
	Indicative: {
		Present: {
			yo: "notifico",
			tú: "notificas",
			Ud: "notifica",
			nosotros: "notificamos",
			vosotros: "notificáis",
			Uds: "notifican",
		},
		Preterite: {
			yo: "notifiqué",
			tú: "notificaste",
			Ud: "notificó",
			nosotros: "notificamos",
			vosotros: "notificasteis",
			Uds: "notificaron",
		},
		Imperfect: {
			yo: "notificaba",
			tú: "notificabas",
			Ud: "notificaba",
			nosotros: "notificábamos",
			vosotros: "notificabais",
			Uds: "notificaban",
		},
		Conditional: {
			yo: "notificaría",
			tú: "notificarías",
			Ud: "notificaría",
			nosotros: "notificaríamos",
			vosotros: "notificaríais",
			Uds: "notificarían",
		},
		Future: {
			yo: "notificaré",
			tú: "notificarás",
			Ud: "notificará",
			nosotros: "notificaremos",
			vosotros: "notificaréis",
			Uds: "notificarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "notifique",
			tú: "notifiques",
			Ud: "notifique",
			nosotros: "notifiquemos",
			vosotros: "notifiquéis",
			Uds: "notifiquen",
		},
		Imperfect: {
			yo: "notificara",
			tú: "notificaras",
			Ud: "notificara",
			nosotros: "notificáramos",
			vosotros: "notificarais",
			Uds: "notificaran",
		},
		Imperfect2: {
			yo: "notificase",
			tú: "notificases",
			Ud: "notificase",
			nosotros: "notificásemos",
			vosotros: "notificaseis",
			Uds: "notificasen",
		},
		Future: {
			yo: "notificare",
			tú: "notificares",
			Ud: "notificare",
			nosotros: "notificáremos",
			vosotros: "notificareis",
			Uds: "notificaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "notifica",
			Ud: "notifique",
			nosotros: "notifiquemos",
			vosotros: "notificad",
			Uds: "notifiquen",
		},
		Negative: {
			tú: "no notifiques",
			Ud: "no notifique",
			nosotros: "no notifiquemos",
			vosotros: "no notifiquéis",
			Uds: "no notifiquen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy notificando",
			tú: "estás notificando",
			Ud: "está notificando",
			nosotros: "estamos notificando",
			vosotros: "estáis notificando",
			Uds: "están notificando",
		},
		Preterite: {
			yo: "estuve notificando",
			tú: "estuviste notificando",
			Ud: "estuvo notificando",
			nosotros: "estuvimos notificando",
			vosotros: "estuvisteis notificando",
			Uds: "estuvieron notificando",
		},
		Imperfect: {
			Uds: "estaban notificando",
			yo: "estaba notificando",
			tú: "estabas notificando",
			Ud: "estaba notificando",
			nosotros: "estábamos notificando",
			vosotros: "estabais notificando",
		},
		Conditional: {
			yo: "estaría notificando",
			tú: "estarías notificando",
			Ud: "estaría notificando",
			nosotros: "estaríamos notificando",
			vosotros: "estaríais notificando",
			Uds: "estarían notificando",
		},
		Future: {
			yo: "estaré notificando",
			tú: "estarás notificando",
			Ud: "estará notificando",
			nosotros: "estaremos notificando",
			vosotros: "estaréis notificando",
			Uds: "estarán notificando",
		},
	},
	Perfect: {
		Present: {
			yo: "he notificado",
			tú: "has notificado",
			Ud: "ha notificado",
			nosotros: "hemos notificado",
			vosotros: "habéis notificado",
			Uds: "han notificado",
		},
		Preterite: {
			yo: "hube notificado",
			tú: "hubiste notificado",
			Ud: "hubo notificado",
			nosotros: "hubimos notificado",
			vosotros: "hubisteis notificado",
			Uds: "hubieron notificado",
		},
		Past: {
			yo: "había notificado",
			tú: "habías notificado",
			Ud: "había notificado",
			nosotros: "habíamos notificado",
			vosotros: "habíais notificado",
			Uds: "habían notificado",
		},
		Conditional: {
			yo: "habría notificado",
			tú: "habrías notificado",
			Ud: "habría notificado",
			nosotros: "habríamos notificado",
			vosotros: "habríais notificado",
			Uds: "habrían notificado",
		},
		Future: {
			yo: "habré notificado",
			tú: "habrás notificado",
			Ud: "habrá notificado",
			nosotros: "habremos notificado",
			vosotros: "habréis notificado",
			Uds: "habrán notificado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya notificado",
			tú: "hayas notificado",
			Ud: "haya notificado",
			nosotros: "hayamos notificado",
			vosotros: "hayáis notificado",
			Uds: "hayan notificado",
		},
		Past: {
			yo: "hubiera notificado",
			tú: "hubieras notificado",
			Ud: "hubiera notificado",
			nosotros: "hubiéramos notificado",
			vosotros: "hubierais notificado",
			Uds: "hubieran notificado",
		},
		Future: {
			yo: "hubiere notificado",
			tú: "hubieres notificado",
			Ud: "hubiere notificado",
			nosotros: "hubiéremos notificado",
			vosotros: "hubiereis notificado",
			Uds: "hubieren notificado",
		},
	},
}
