var observar = {
	Indicative: {
		Present: {
			yo: "observo",
			tú: "observas",
			Ud: "observa",
			nosotros: "observamos",
			vosotros: "observáis",
			Uds: "observan",
		},
		Preterite: {
			yo: "observé",
			tú: "observaste",
			Ud: "observó",
			nosotros: "observamos",
			vosotros: "observasteis",
			Uds: "observaron",
		},
		Imperfect: {
			yo: "observaba",
			tú: "observabas",
			Ud: "observaba",
			nosotros: "observábamos",
			vosotros: "observabais",
			Uds: "observaban",
		},
		Conditional: {
			yo: "observaría",
			tú: "observarías",
			Ud: "observaría",
			nosotros: "observaríamos",
			vosotros: "observaríais",
			Uds: "observarían",
		},
		Future: {
			yo: "observaré",
			tú: "observarás",
			Ud: "observará",
			nosotros: "observaremos",
			vosotros: "observaréis",
			Uds: "observarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "observe",
			tú: "observes",
			Ud: "observe",
			nosotros: "observemos",
			vosotros: "observéis",
			Uds: "observen",
		},
		Imperfect: {
			yo: "observara",
			tú: "observaras",
			Ud: "observara",
			nosotros: "observáramos",
			vosotros: "observarais",
			Uds: "observaran",
		},
		Imperfect2: {
			yo: "observase",
			tú: "observases",
			Ud: "observase",
			nosotros: "observásemos",
			vosotros: "observaseis",
			Uds: "observasen",
		},
		Future: {
			yo: "observare",
			tú: "observares",
			Ud: "observare",
			nosotros: "observáremos",
			vosotros: "observareis",
			Uds: "observaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "observa",
			Ud: "observe",
			nosotros: "observemos",
			vosotros: "observad",
			Uds: "observen",
		},
		Negative: {
			tú: "no observes",
			Ud: "no observe",
			nosotros: "no observemos",
			vosotros: "no observéis",
			Uds: "no observen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy observando",
			tú: "estás observando",
			Ud: "está observando",
			nosotros: "estamos observando",
			vosotros: "estáis observando",
			Uds: "están observando",
		},
		Preterite: {
			yo: "estuve observando",
			tú: "estuviste observando",
			Ud: "estuvo observando",
			nosotros: "estuvimos observando",
			vosotros: "estuvisteis observando",
			Uds: "estuvieron observando",
		},
		Imperfect: {
			Uds: "estaban observando",
			yo: "estaba observando",
			tú: "estabas observando",
			Ud: "estaba observando",
			nosotros: "estábamos observando",
			vosotros: "estabais observando",
		},
		Conditional: {
			yo: "estaría observando",
			tú: "estarías observando",
			Ud: "estaría observando",
			nosotros: "estaríamos observando",
			vosotros: "estaríais observando",
			Uds: "estarían observando",
		},
		Future: {
			yo: "estaré observando",
			tú: "estarás observando",
			Ud: "estará observando",
			nosotros: "estaremos observando",
			vosotros: "estaréis observando",
			Uds: "estarán observando",
		},
	},
	Perfect: {
		Present: {
			yo: "he observado",
			tú: "has observado",
			Ud: "ha observado",
			nosotros: "hemos observado",
			vosotros: "habéis observado",
			Uds: "han observado",
		},
		Preterite: {
			yo: "hube observado",
			tú: "hubiste observado",
			Ud: "hubo observado",
			nosotros: "hubimos observado",
			vosotros: "hubisteis observado",
			Uds: "hubieron observado",
		},
		Past: {
			yo: "había observado",
			tú: "habías observado",
			Ud: "había observado",
			nosotros: "habíamos observado",
			vosotros: "habíais observado",
			Uds: "habían observado",
		},
		Conditional: {
			yo: "habría observado",
			tú: "habrías observado",
			Ud: "habría observado",
			nosotros: "habríamos observado",
			vosotros: "habríais observado",
			Uds: "habrían observado",
		},
		Future: {
			yo: "habré observado",
			tú: "habrás observado",
			Ud: "habrá observado",
			nosotros: "habremos observado",
			vosotros: "habréis observado",
			Uds: "habrán observado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya observado",
			tú: "hayas observado",
			Ud: "haya observado",
			nosotros: "hayamos observado",
			vosotros: "hayáis observado",
			Uds: "hayan observado",
		},
		Past: {
			yo: "hubiera observado",
			tú: "hubieras observado",
			Ud: "hubiera observado",
			nosotros: "hubiéramos observado",
			vosotros: "hubierais observado",
			Uds: "hubieran observado",
		},
		Future: {
			yo: "hubiere observado",
			tú: "hubieres observado",
			Ud: "hubiere observado",
			nosotros: "hubiéremos observado",
			vosotros: "hubiereis observado",
			Uds: "hubieren observado",
		},
	},
}
