var obviar = {
	Indicative: {
		Present: {
			yo: "obvio",
			tú: "obvias",
			Ud: "obvia",
			nosotros: "obviamos",
			vosotros: "obviáis",
			Uds: "obvian",
		},
		Preterite: {
			yo: "obvié",
			tú: "obviaste",
			Ud: "obvió",
			nosotros: "obviamos",
			vosotros: "obviasteis",
			Uds: "obviaron",
		},
		Imperfect: {
			yo: "obviaba",
			tú: "obviabas",
			Ud: "obviaba",
			nosotros: "obviábamos",
			vosotros: "obviabais",
			Uds: "obviaban",
		},
		Conditional: {
			yo: "obviaría",
			tú: "obviarías",
			Ud: "obviaría",
			nosotros: "obviaríamos",
			vosotros: "obviaríais",
			Uds: "obviarían",
		},
		Future: {
			yo: "obviaré",
			tú: "obviarás",
			Ud: "obviará",
			nosotros: "obviaremos",
			vosotros: "obviaréis",
			Uds: "obviarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "obvie",
			tú: "obvies",
			Ud: "obvie",
			nosotros: "obviemos",
			vosotros: "obviéis",
			Uds: "obvien",
		},
		Imperfect: {
			yo: "obviara",
			tú: "obviaras",
			Ud: "obviara",
			nosotros: "obviáramos",
			vosotros: "obviarais",
			Uds: "obviaran",
		},
		Imperfect2: {
			yo: "obviase",
			tú: "obviases",
			Ud: "obviase",
			nosotros: "obviásemos",
			vosotros: "obviaseis",
			Uds: "obviasen",
		},
		Future: {
			yo: "obviare",
			tú: "obviares",
			Ud: "obviare",
			nosotros: "obviáremos",
			vosotros: "obviareis",
			Uds: "obviaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "obvia",
			Ud: "obvie",
			nosotros: "obviemos",
			vosotros: "obviad",
			Uds: "obvien",
		},
		Negative: {
			tú: "no obvies",
			Ud: "no obvie",
			nosotros: "no obviemos",
			vosotros: "no obviéis",
			Uds: "no obvien",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy obviando",
			tú: "estás obviando",
			Ud: "está obviando",
			nosotros: "estamos obviando",
			vosotros: "estáis obviando",
			Uds: "están obviando",
		},
		Preterite: {
			yo: "estuve obviando",
			tú: "estuviste obviando",
			Ud: "estuvo obviando",
			nosotros: "estuvimos obviando",
			vosotros: "estuvisteis obviando",
			Uds: "estuvieron obviando",
		},
		Imperfect: {
			Uds: "estaban obviando",
			yo: "estaba obviando",
			tú: "estabas obviando",
			Ud: "estaba obviando",
			nosotros: "estábamos obviando",
			vosotros: "estabais obviando",
		},
		Conditional: {
			yo: "estaría obviando",
			tú: "estarías obviando",
			Ud: "estaría obviando",
			nosotros: "estaríamos obviando",
			vosotros: "estaríais obviando",
			Uds: "estarían obviando",
		},
		Future: {
			yo: "estaré obviando",
			tú: "estarás obviando",
			Ud: "estará obviando",
			nosotros: "estaremos obviando",
			vosotros: "estaréis obviando",
			Uds: "estarán obviando",
		},
	},
	Perfect: {
		Present: {
			yo: "he obviado",
			tú: "has obviado",
			Ud: "ha obviado",
			nosotros: "hemos obviado",
			vosotros: "habéis obviado",
			Uds: "han obviado",
		},
		Preterite: {
			yo: "hube obviado",
			tú: "hubiste obviado",
			Ud: "hubo obviado",
			nosotros: "hubimos obviado",
			vosotros: "hubisteis obviado",
			Uds: "hubieron obviado",
		},
		Past: {
			yo: "había obviado",
			tú: "habías obviado",
			Ud: "había obviado",
			nosotros: "habíamos obviado",
			vosotros: "habíais obviado",
			Uds: "habían obviado",
		},
		Conditional: {
			yo: "habría obviado",
			tú: "habrías obviado",
			Ud: "habría obviado",
			nosotros: "habríamos obviado",
			vosotros: "habríais obviado",
			Uds: "habrían obviado",
		},
		Future: {
			yo: "habré obviado",
			tú: "habrás obviado",
			Ud: "habrá obviado",
			nosotros: "habremos obviado",
			vosotros: "habréis obviado",
			Uds: "habrán obviado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya obviado",
			tú: "hayas obviado",
			Ud: "haya obviado",
			nosotros: "hayamos obviado",
			vosotros: "hayáis obviado",
			Uds: "hayan obviado",
		},
		Past: {
			yo: "hubiera obviado",
			tú: "hubieras obviado",
			Ud: "hubiera obviado",
			nosotros: "hubiéramos obviado",
			vosotros: "hubierais obviado",
			Uds: "hubieran obviado",
		},
		Future: {
			yo: "hubiere obviado",
			tú: "hubieres obviado",
			Ud: "hubiere obviado",
			nosotros: "hubiéremos obviado",
			vosotros: "hubiereis obviado",
			Uds: "hubieren obviado",
		},
	},
}
