var ocupar = {
	Indicative: {
		Present: {
			yo: "ocupo",
			tú: "ocupas",
			Ud: "ocupa",
			nosotros: "ocupamos",
			vosotros: "ocupáis",
			Uds: "ocupan",
		},
		Preterite: {
			yo: "ocupé",
			tú: "ocupaste",
			Ud: "ocupó",
			nosotros: "ocupamos",
			vosotros: "ocupasteis",
			Uds: "ocuparon",
		},
		Imperfect: {
			yo: "ocupaba",
			tú: "ocupabas",
			Ud: "ocupaba",
			nosotros: "ocupábamos",
			vosotros: "ocupabais",
			Uds: "ocupaban",
		},
		Conditional: {
			yo: "ocuparía",
			tú: "ocuparías",
			Ud: "ocuparía",
			nosotros: "ocuparíamos",
			vosotros: "ocuparíais",
			Uds: "ocuparían",
		},
		Future: {
			yo: "ocuparé",
			tú: "ocuparás",
			Ud: "ocupará",
			nosotros: "ocuparemos",
			vosotros: "ocuparéis",
			Uds: "ocuparán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "ocupe",
			tú: "ocupes",
			Ud: "ocupe",
			nosotros: "ocupemos",
			vosotros: "ocupéis",
			Uds: "ocupen",
		},
		Imperfect: {
			yo: "ocupara",
			tú: "ocuparas",
			Ud: "ocupara",
			nosotros: "ocupáramos",
			vosotros: "ocuparais",
			Uds: "ocuparan",
		},
		Imperfect2: {
			yo: "ocupase",
			tú: "ocupases",
			Ud: "ocupase",
			nosotros: "ocupásemos",
			vosotros: "ocupaseis",
			Uds: "ocupasen",
		},
		Future: {
			yo: "ocupare",
			tú: "ocupares",
			Ud: "ocupare",
			nosotros: "ocupáremos",
			vosotros: "ocupareis",
			Uds: "ocuparen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "ocupa",
			Ud: "ocupe",
			nosotros: "ocupemos",
			vosotros: "ocupad",
			Uds: "ocupen",
		},
		Negative: {
			tú: "no ocupes",
			Ud: "no ocupe",
			nosotros: "no ocupemos",
			vosotros: "no ocupéis",
			Uds: "no ocupen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy ocupando",
			tú: "estás ocupando",
			Ud: "está ocupando",
			nosotros: "estamos ocupando",
			vosotros: "estáis ocupando",
			Uds: "están ocupando",
		},
		Preterite: {
			yo: "estuve ocupando",
			tú: "estuviste ocupando",
			Ud: "estuvo ocupando",
			nosotros: "estuvimos ocupando",
			vosotros: "estuvisteis ocupando",
			Uds: "estuvieron ocupando",
		},
		Imperfect: {
			Uds: "estaban ocupando",
			yo: "estaba ocupando",
			tú: "estabas ocupando",
			Ud: "estaba ocupando",
			nosotros: "estábamos ocupando",
			vosotros: "estabais ocupando",
		},
		Conditional: {
			yo: "estaría ocupando",
			tú: "estarías ocupando",
			Ud: "estaría ocupando",
			nosotros: "estaríamos ocupando",
			vosotros: "estaríais ocupando",
			Uds: "estarían ocupando",
		},
		Future: {
			yo: "estaré ocupando",
			tú: "estarás ocupando",
			Ud: "estará ocupando",
			nosotros: "estaremos ocupando",
			vosotros: "estaréis ocupando",
			Uds: "estarán ocupando",
		},
	},
	Perfect: {
		Present: {
			yo: "he ocupado",
			tú: "has ocupado",
			Ud: "ha ocupado",
			nosotros: "hemos ocupado",
			vosotros: "habéis ocupado",
			Uds: "han ocupado",
		},
		Preterite: {
			yo: "hube ocupado",
			tú: "hubiste ocupado",
			Ud: "hubo ocupado",
			nosotros: "hubimos ocupado",
			vosotros: "hubisteis ocupado",
			Uds: "hubieron ocupado",
		},
		Past: {
			yo: "había ocupado",
			tú: "habías ocupado",
			Ud: "había ocupado",
			nosotros: "habíamos ocupado",
			vosotros: "habíais ocupado",
			Uds: "habían ocupado",
		},
		Conditional: {
			yo: "habría ocupado",
			tú: "habrías ocupado",
			Ud: "habría ocupado",
			nosotros: "habríamos ocupado",
			vosotros: "habríais ocupado",
			Uds: "habrían ocupado",
		},
		Future: {
			yo: "habré ocupado",
			tú: "habrás ocupado",
			Ud: "habrá ocupado",
			nosotros: "habremos ocupado",
			vosotros: "habréis ocupado",
			Uds: "habrán ocupado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya ocupado",
			tú: "hayas ocupado",
			Ud: "haya ocupado",
			nosotros: "hayamos ocupado",
			vosotros: "hayáis ocupado",
			Uds: "hayan ocupado",
		},
		Past: {
			yo: "hubiera ocupado",
			tú: "hubieras ocupado",
			Ud: "hubiera ocupado",
			nosotros: "hubiéramos ocupado",
			vosotros: "hubierais ocupado",
			Uds: "hubieran ocupado",
		},
		Future: {
			yo: "hubiere ocupado",
			tú: "hubieres ocupado",
			Ud: "hubiere ocupado",
			nosotros: "hubiéremos ocupado",
			vosotros: "hubiereis ocupado",
			Uds: "hubieren ocupado",
		},
	},
}
