var olfatear = {
	Indicative: {
		Present: {
			yo: "olfateo",
			tú: "olfateas",
			Ud: "olfatea",
			nosotros: "olfateamos",
			vosotros: "olfateáis",
			Uds: "olfatean",
		},
		Preterite: {
			yo: "olfateé",
			tú: "olfateaste",
			Ud: "olfateó",
			nosotros: "olfateamos",
			vosotros: "olfateasteis",
			Uds: "olfatearon",
		},
		Imperfect: {
			yo: "olfateaba",
			tú: "olfateabas",
			Ud: "olfateaba",
			nosotros: "olfateábamos",
			vosotros: "olfateabais",
			Uds: "olfateaban",
		},
		Conditional: {
			yo: "olfatearía",
			tú: "olfatearías",
			Ud: "olfatearía",
			nosotros: "olfatearíamos",
			vosotros: "olfatearíais",
			Uds: "olfatearían",
		},
		Future: {
			yo: "olfatearé",
			tú: "olfatearás",
			Ud: "olfateará",
			nosotros: "olfatearemos",
			vosotros: "olfatearéis",
			Uds: "olfatearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "olfatee",
			tú: "olfatees",
			Ud: "olfatee",
			nosotros: "olfateemos",
			vosotros: "olfateéis",
			Uds: "olfateen",
		},
		Imperfect: {
			yo: "olfateara",
			tú: "olfatearas",
			Ud: "olfateara",
			nosotros: "olfateáramos",
			vosotros: "olfatearais",
			Uds: "olfatearan",
		},
		Imperfect2: {
			yo: "olfatease",
			tú: "olfateases",
			Ud: "olfatease",
			nosotros: "olfateásemos",
			vosotros: "olfateaseis",
			Uds: "olfateasen",
		},
		Future: {
			yo: "olfateare",
			tú: "olfateares",
			Ud: "olfateare",
			nosotros: "olfateáremos",
			vosotros: "olfateareis",
			Uds: "olfatearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "olfatea",
			Ud: "olfatee",
			nosotros: "olfateemos",
			vosotros: "olfatead",
			Uds: "olfateen",
		},
		Negative: {
			tú: "no olfatees",
			Ud: "no olfatee",
			nosotros: "no olfateemos",
			vosotros: "no olfateéis",
			Uds: "no olfateen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy olfateando",
			tú: "estás olfateando",
			Ud: "está olfateando",
			nosotros: "estamos olfateando",
			vosotros: "estáis olfateando",
			Uds: "están olfateando",
		},
		Preterite: {
			yo: "estuve olfateando",
			tú: "estuviste olfateando",
			Ud: "estuvo olfateando",
			nosotros: "estuvimos olfateando",
			vosotros: "estuvisteis olfateando",
			Uds: "estuvieron olfateando",
		},
		Imperfect: {
			Uds: "estaban olfateando",
			yo: "estaba olfateando",
			tú: "estabas olfateando",
			Ud: "estaba olfateando",
			nosotros: "estábamos olfateando",
			vosotros: "estabais olfateando",
		},
		Conditional: {
			yo: "estaría olfateando",
			tú: "estarías olfateando",
			Ud: "estaría olfateando",
			nosotros: "estaríamos olfateando",
			vosotros: "estaríais olfateando",
			Uds: "estarían olfateando",
		},
		Future: {
			yo: "estaré olfateando",
			tú: "estarás olfateando",
			Ud: "estará olfateando",
			nosotros: "estaremos olfateando",
			vosotros: "estaréis olfateando",
			Uds: "estarán olfateando",
		},
	},
	Perfect: {
		Present: {
			yo: "he olfateado",
			tú: "has olfateado",
			Ud: "ha olfateado",
			nosotros: "hemos olfateado",
			vosotros: "habéis olfateado",
			Uds: "han olfateado",
		},
		Preterite: {
			yo: "hube olfateado",
			tú: "hubiste olfateado",
			Ud: "hubo olfateado",
			nosotros: "hubimos olfateado",
			vosotros: "hubisteis olfateado",
			Uds: "hubieron olfateado",
		},
		Past: {
			yo: "había olfateado",
			tú: "habías olfateado",
			Ud: "había olfateado",
			nosotros: "habíamos olfateado",
			vosotros: "habíais olfateado",
			Uds: "habían olfateado",
		},
		Conditional: {
			yo: "habría olfateado",
			tú: "habrías olfateado",
			Ud: "habría olfateado",
			nosotros: "habríamos olfateado",
			vosotros: "habríais olfateado",
			Uds: "habrían olfateado",
		},
		Future: {
			yo: "habré olfateado",
			tú: "habrás olfateado",
			Ud: "habrá olfateado",
			nosotros: "habremos olfateado",
			vosotros: "habréis olfateado",
			Uds: "habrán olfateado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya olfateado",
			tú: "hayas olfateado",
			Ud: "haya olfateado",
			nosotros: "hayamos olfateado",
			vosotros: "hayáis olfateado",
			Uds: "hayan olfateado",
		},
		Past: {
			yo: "hubiera olfateado",
			tú: "hubieras olfateado",
			Ud: "hubiera olfateado",
			nosotros: "hubiéramos olfateado",
			vosotros: "hubierais olfateado",
			Uds: "hubieran olfateado",
		},
		Future: {
			yo: "hubiere olfateado",
			tú: "hubieres olfateado",
			Ud: "hubiere olfateado",
			nosotros: "hubiéremos olfateado",
			vosotros: "hubiereis olfateado",
			Uds: "hubieren olfateado",
		},
	},
}
