var omitir = {
	Indicative: {
		Present: {
			yo: "omito",
			tú: "omites",
			Ud: "omite",
			nosotros: "omitimos",
			vosotros: "omitís",
			Uds: "omiten",
		},
		Preterite: {
			yo: "omití",
			tú: "omitiste",
			Ud: "omitió",
			nosotros: "omitimos",
			vosotros: "omitisteis",
			Uds: "omitieron",
		},
		Imperfect: {
			yo: "omitía",
			tú: "omitías",
			Ud: "omitía",
			nosotros: "omitíamos",
			vosotros: "omitíais",
			Uds: "omitían",
		},
		Conditional: {
			yo: "omitiría",
			tú: "omitirías",
			Ud: "omitiría",
			nosotros: "omitiríamos",
			vosotros: "omitiríais",
			Uds: "omitirían",
		},
		Future: {
			yo: "omitiré",
			tú: "omitirás",
			Ud: "omitirá",
			nosotros: "omitiremos",
			vosotros: "omitiréis",
			Uds: "omitirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "omita",
			tú: "omitas",
			Ud: "omita",
			nosotros: "omitamos",
			vosotros: "omitáis",
			Uds: "omitan",
		},
		Imperfect: {
			yo: "omitiera",
			tú: "omitieras",
			Ud: "omitiera",
			nosotros: "omitiéramos",
			vosotros: "omitierais",
			Uds: "omitieran",
		},
		Imperfect2: {
			yo: "omitiese",
			tú: "omitieses",
			Ud: "omitiese",
			nosotros: "omitiésemos",
			vosotros: "omitieseis",
			Uds: "omitiesen",
		},
		Future: {
			yo: "omitiere",
			tú: "omitieres",
			Ud: "omitiere",
			nosotros: "omitiéremos",
			vosotros: "omitiereis",
			Uds: "omitieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "omite",
			Ud: "omita",
			nosotros: "omitamos",
			vosotros: "omitid",
			Uds: "omitan",
		},
		Negative: {
			tú: "no omitas",
			Ud: "no omita",
			nosotros: "no omitamos",
			vosotros: "no omitáis",
			Uds: "no omitan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy omitiendo",
			tú: "estás omitiendo",
			Ud: "está omitiendo",
			nosotros: "estamos omitiendo",
			vosotros: "estáis omitiendo",
			Uds: "están omitiendo",
		},
		Preterite: {
			yo: "estuve omitiendo",
			tú: "estuviste omitiendo",
			Ud: "estuvo omitiendo",
			nosotros: "estuvimos omitiendo",
			vosotros: "estuvisteis omitiendo",
			Uds: "estuvieron omitiendo",
		},
		Imperfect: {
			Uds: "estaban omitiendo",
			yo: "estaba omitiendo",
			tú: "estabas omitiendo",
			Ud: "estaba omitiendo",
			nosotros: "estábamos omitiendo",
			vosotros: "estabais omitiendo",
		},
		Conditional: {
			yo: "estaría omitiendo",
			tú: "estarías omitiendo",
			Ud: "estaría omitiendo",
			nosotros: "estaríamos omitiendo",
			vosotros: "estaríais omitiendo",
			Uds: "estarían omitiendo",
		},
		Future: {
			yo: "estaré omitiendo",
			tú: "estarás omitiendo",
			Ud: "estará omitiendo",
			nosotros: "estaremos omitiendo",
			vosotros: "estaréis omitiendo",
			Uds: "estarán omitiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he omitido,omiso",
			tú: "has omitido,omiso",
			Ud: "ha omitido,omiso",
			nosotros: "hemos omitido,omiso",
			vosotros: "habéis omitido,omiso",
			Uds: "han omitido,omiso",
		},
		Preterite: {
			yo: "hube omitido,omiso",
			tú: "hubiste omitido,omiso",
			Ud: "hubo omitido,omiso",
			nosotros: "hubimos omitido,omiso",
			vosotros: "hubisteis omitido,omiso",
			Uds: "hubieron omitido,omiso",
		},
		Past: {
			yo: "había omitido,omiso",
			tú: "habías omitido,omiso",
			Ud: "había omitido,omiso",
			nosotros: "habíamos omitido,omiso",
			vosotros: "habíais omitido,omiso",
			Uds: "habían omitido,omiso",
		},
		Conditional: {
			yo: "habría omitido,omiso",
			tú: "habrías omitido,omiso",
			Ud: "habría omitido,omiso",
			nosotros: "habríamos omitido,omiso",
			vosotros: "habríais omitido,omiso",
			Uds: "habrían omitido,omiso",
		},
		Future: {
			yo: "habré omitido,omiso",
			tú: "habrás omitido,omiso",
			Ud: "habrá omitido,omiso",
			nosotros: "habremos omitido,omiso",
			vosotros: "habréis omitido,omiso",
			Uds: "habrán omitido,omiso",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya omitido,omiso",
			tú: "hayas omitido,omiso",
			Ud: "haya omitido,omiso",
			nosotros: "hayamos omitido,omiso",
			vosotros: "hayáis omitido,omiso",
			Uds: "hayan omitido,omiso",
		},
		Past: {
			yo: "hubiera omitido,omiso",
			tú: "hubieras omitido,omiso",
			Ud: "hubiera omitido,omiso",
			nosotros: "hubiéramos omitido,omiso",
			vosotros: "hubierais omitido,omiso",
			Uds: "hubieran omitido,omiso",
		},
		Future: {
			yo: "hubiere omitido,omiso",
			tú: "hubieres omitido,omiso",
			Ud: "hubiere omitido,omiso",
			nosotros: "hubiéremos omitido,omiso",
			vosotros: "hubiereis omitido,omiso",
			Uds: "hubieren omitido,omiso",
		},
	},
}
