var oponer = {
	Indicative: {
		Present: {
			yo: "opongo",
			tú: "opones",
			Ud: "opone",
			nosotros: "oponemos",
			vosotros: "oponéis",
			Uds: "oponen",
		},
		Preterite: {
			yo: "opuse",
			tú: "opusiste",
			Ud: "opuso",
			nosotros: "opusimos",
			vosotros: "opusisteis",
			Uds: "opusieron",
		},
		Imperfect: {
			yo: "oponía",
			tú: "oponías",
			Ud: "oponía",
			nosotros: "oponíamos",
			vosotros: "oponíais",
			Uds: "oponían",
		},
		Conditional: {
			yo: "opondría",
			tú: "opondrías",
			Ud: "opondría",
			nosotros: "opondríamos",
			vosotros: "opondríais",
			Uds: "opondrían",
		},
		Future: {
			yo: "opondré",
			tú: "opondrás",
			Ud: "opondrá",
			nosotros: "opondremos",
			vosotros: "opondréis",
			Uds: "opondrán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "oponga",
			tú: "opongas",
			Ud: "oponga",
			nosotros: "opongamos",
			vosotros: "opongáis",
			Uds: "opongan",
		},
		Imperfect: {
			yo: "opusiera",
			tú: "opusieras",
			Ud: "opusiera",
			nosotros: "opusiéramos",
			vosotros: "opusierais",
			Uds: "opusieran",
		},
		Imperfect2: {
			yo: "opusiese",
			tú: "opusieses",
			Ud: "opusiese",
			nosotros: "opusiésemos",
			vosotros: "opusieseis",
			Uds: "opusiesen",
		},
		Future: {
			yo: "opusiere",
			tú: "opusieres",
			Ud: "opusiere",
			nosotros: "opusiéremos",
			vosotros: "opusiereis",
			Uds: "opusieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "opón",
			Ud: "oponga",
			nosotros: "opongamos",
			vosotros: "oponed",
			Uds: "opongan",
		},
		Negative: {
			tú: "no opongas",
			Ud: "no oponga",
			nosotros: "no opongamos",
			vosotros: "no opongáis",
			Uds: "no opongan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy oponiendo",
			tú: "estás oponiendo",
			Ud: "está oponiendo",
			nosotros: "estamos oponiendo",
			vosotros: "estáis oponiendo",
			Uds: "están oponiendo",
		},
		Preterite: {
			yo: "estuve oponiendo",
			tú: "estuviste oponiendo",
			Ud: "estuvo oponiendo",
			nosotros: "estuvimos oponiendo",
			vosotros: "estuvisteis oponiendo",
			Uds: "estuvieron oponiendo",
		},
		Imperfect: {
			Uds: "estaban oponiendo",
			yo: "estaba oponiendo",
			tú: "estabas oponiendo",
			Ud: "estaba oponiendo",
			nosotros: "estábamos oponiendo",
			vosotros: "estabais oponiendo",
		},
		Conditional: {
			yo: "estaría oponiendo",
			tú: "estarías oponiendo",
			Ud: "estaría oponiendo",
			nosotros: "estaríamos oponiendo",
			vosotros: "estaríais oponiendo",
			Uds: "estarían oponiendo",
		},
		Future: {
			yo: "estaré oponiendo",
			tú: "estarás oponiendo",
			Ud: "estará oponiendo",
			nosotros: "estaremos oponiendo",
			vosotros: "estaréis oponiendo",
			Uds: "estarán oponiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he opuesto",
			tú: "has opuesto",
			Ud: "ha opuesto",
			nosotros: "hemos opuesto",
			vosotros: "habéis opuesto",
			Uds: "han opuesto",
		},
		Preterite: {
			yo: "hube opuesto",
			tú: "hubiste opuesto",
			Ud: "hubo opuesto",
			nosotros: "hubimos opuesto",
			vosotros: "hubisteis opuesto",
			Uds: "hubieron opuesto",
		},
		Past: {
			yo: "había opuesto",
			tú: "habías opuesto",
			Ud: "había opuesto",
			nosotros: "habíamos opuesto",
			vosotros: "habíais opuesto",
			Uds: "habían opuesto",
		},
		Conditional: {
			yo: "habría opuesto",
			tú: "habrías opuesto",
			Ud: "habría opuesto",
			nosotros: "habríamos opuesto",
			vosotros: "habríais opuesto",
			Uds: "habrían opuesto",
		},
		Future: {
			yo: "habré opuesto",
			tú: "habrás opuesto",
			Ud: "habrá opuesto",
			nosotros: "habremos opuesto",
			vosotros: "habréis opuesto",
			Uds: "habrán opuesto",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya opuesto",
			tú: "hayas opuesto",
			Ud: "haya opuesto",
			nosotros: "hayamos opuesto",
			vosotros: "hayáis opuesto",
			Uds: "hayan opuesto",
		},
		Past: {
			yo: "hubiera opuesto",
			tú: "hubieras opuesto",
			Ud: "hubiera opuesto",
			nosotros: "hubiéramos opuesto",
			vosotros: "hubierais opuesto",
			Uds: "hubieran opuesto",
		},
		Future: {
			yo: "hubiere opuesto",
			tú: "hubieres opuesto",
			Ud: "hubiere opuesto",
			nosotros: "hubiéremos opuesto",
			vosotros: "hubiereis opuesto",
			Uds: "hubieren opuesto",
		},
	},
}
