var organizar = {
	Indicative: {
		Present: {
			yo: "organizo",
			tú: "organizas",
			Ud: "organiza",
			nosotros: "organizamos",
			vosotros: "organizáis",
			Uds: "organizan",
		},
		Preterite: {
			yo: "organicé",
			tú: "organizaste",
			Ud: "organizó",
			nosotros: "organizamos",
			vosotros: "organizasteis",
			Uds: "organizaron",
		},
		Imperfect: {
			yo: "organizaba",
			tú: "organizabas",
			Ud: "organizaba",
			nosotros: "organizábamos",
			vosotros: "organizabais",
			Uds: "organizaban",
		},
		Conditional: {
			yo: "organizaría",
			tú: "organizarías",
			Ud: "organizaría",
			nosotros: "organizaríamos",
			vosotros: "organizaríais",
			Uds: "organizarían",
		},
		Future: {
			yo: "organizaré",
			tú: "organizarás",
			Ud: "organizará",
			nosotros: "organizaremos",
			vosotros: "organizaréis",
			Uds: "organizarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "organice",
			tú: "organices",
			Ud: "organice",
			nosotros: "organicemos",
			vosotros: "organicéis",
			Uds: "organicen",
		},
		Imperfect: {
			yo: "organizara",
			tú: "organizaras",
			Ud: "organizara",
			nosotros: "organizáramos",
			vosotros: "organizarais",
			Uds: "organizaran",
		},
		Imperfect2: {
			yo: "organizase",
			tú: "organizases",
			Ud: "organizase",
			nosotros: "organizásemos",
			vosotros: "organizaseis",
			Uds: "organizasen",
		},
		Future: {
			yo: "organizare",
			tú: "organizares",
			Ud: "organizare",
			nosotros: "organizáremos",
			vosotros: "organizareis",
			Uds: "organizaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "organiza",
			Ud: "organice",
			nosotros: "organicemos",
			vosotros: "organizad",
			Uds: "organicen",
		},
		Negative: {
			tú: "no organices",
			Ud: "no organice",
			nosotros: "no organicemos",
			vosotros: "no organicéis",
			Uds: "no organicen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy organizando",
			tú: "estás organizando",
			Ud: "está organizando",
			nosotros: "estamos organizando",
			vosotros: "estáis organizando",
			Uds: "están organizando",
		},
		Preterite: {
			yo: "estuve organizando",
			tú: "estuviste organizando",
			Ud: "estuvo organizando",
			nosotros: "estuvimos organizando",
			vosotros: "estuvisteis organizando",
			Uds: "estuvieron organizando",
		},
		Imperfect: {
			Uds: "estaban organizando",
			yo: "estaba organizando",
			tú: "estabas organizando",
			Ud: "estaba organizando",
			nosotros: "estábamos organizando",
			vosotros: "estabais organizando",
		},
		Conditional: {
			yo: "estaría organizando",
			tú: "estarías organizando",
			Ud: "estaría organizando",
			nosotros: "estaríamos organizando",
			vosotros: "estaríais organizando",
			Uds: "estarían organizando",
		},
		Future: {
			yo: "estaré organizando",
			tú: "estarás organizando",
			Ud: "estará organizando",
			nosotros: "estaremos organizando",
			vosotros: "estaréis organizando",
			Uds: "estarán organizando",
		},
	},
	Perfect: {
		Present: {
			yo: "he organizado",
			tú: "has organizado",
			Ud: "ha organizado",
			nosotros: "hemos organizado",
			vosotros: "habéis organizado",
			Uds: "han organizado",
		},
		Preterite: {
			yo: "hube organizado",
			tú: "hubiste organizado",
			Ud: "hubo organizado",
			nosotros: "hubimos organizado",
			vosotros: "hubisteis organizado",
			Uds: "hubieron organizado",
		},
		Past: {
			yo: "había organizado",
			tú: "habías organizado",
			Ud: "había organizado",
			nosotros: "habíamos organizado",
			vosotros: "habíais organizado",
			Uds: "habían organizado",
		},
		Conditional: {
			yo: "habría organizado",
			tú: "habrías organizado",
			Ud: "habría organizado",
			nosotros: "habríamos organizado",
			vosotros: "habríais organizado",
			Uds: "habrían organizado",
		},
		Future: {
			yo: "habré organizado",
			tú: "habrás organizado",
			Ud: "habrá organizado",
			nosotros: "habremos organizado",
			vosotros: "habréis organizado",
			Uds: "habrán organizado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya organizado",
			tú: "hayas organizado",
			Ud: "haya organizado",
			nosotros: "hayamos organizado",
			vosotros: "hayáis organizado",
			Uds: "hayan organizado",
		},
		Past: {
			yo: "hubiera organizado",
			tú: "hubieras organizado",
			Ud: "hubiera organizado",
			nosotros: "hubiéramos organizado",
			vosotros: "hubierais organizado",
			Uds: "hubieran organizado",
		},
		Future: {
			yo: "hubiere organizado",
			tú: "hubieres organizado",
			Ud: "hubiere organizado",
			nosotros: "hubiéremos organizado",
			vosotros: "hubiereis organizado",
			Uds: "hubieren organizado",
		},
	},
}
