var orientar = {
	Indicative: {
		Present: {
			yo: "oriento",
			tú: "orientas",
			Ud: "orienta",
			nosotros: "orientamos",
			vosotros: "orientáis",
			Uds: "orientan",
		},
		Preterite: {
			yo: "orienté",
			tú: "orientaste",
			Ud: "orientó",
			nosotros: "orientamos",
			vosotros: "orientasteis",
			Uds: "orientaron",
		},
		Imperfect: {
			yo: "orientaba",
			tú: "orientabas",
			Ud: "orientaba",
			nosotros: "orientábamos",
			vosotros: "orientabais",
			Uds: "orientaban",
		},
		Conditional: {
			yo: "orientaría",
			tú: "orientarías",
			Ud: "orientaría",
			nosotros: "orientaríamos",
			vosotros: "orientaríais",
			Uds: "orientarían",
		},
		Future: {
			yo: "orientaré",
			tú: "orientarás",
			Ud: "orientará",
			nosotros: "orientaremos",
			vosotros: "orientaréis",
			Uds: "orientarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "oriente",
			tú: "orientes",
			Ud: "oriente",
			nosotros: "orientemos",
			vosotros: "orientéis",
			Uds: "orienten",
		},
		Imperfect: {
			yo: "orientara",
			tú: "orientaras",
			Ud: "orientara",
			nosotros: "orientáramos",
			vosotros: "orientarais",
			Uds: "orientaran",
		},
		Imperfect2: {
			yo: "orientase",
			tú: "orientases",
			Ud: "orientase",
			nosotros: "orientásemos",
			vosotros: "orientaseis",
			Uds: "orientasen",
		},
		Future: {
			yo: "orientare",
			tú: "orientares",
			Ud: "orientare",
			nosotros: "orientáremos",
			vosotros: "orientareis",
			Uds: "orientaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "orienta",
			Ud: "oriente",
			nosotros: "orientemos",
			vosotros: "orientad",
			Uds: "orienten",
		},
		Negative: {
			tú: "no orientes",
			Ud: "no oriente",
			nosotros: "no orientemos",
			vosotros: "no orientéis",
			Uds: "no orienten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy orientando",
			tú: "estás orientando",
			Ud: "está orientando",
			nosotros: "estamos orientando",
			vosotros: "estáis orientando",
			Uds: "están orientando",
		},
		Preterite: {
			yo: "estuve orientando",
			tú: "estuviste orientando",
			Ud: "estuvo orientando",
			nosotros: "estuvimos orientando",
			vosotros: "estuvisteis orientando",
			Uds: "estuvieron orientando",
		},
		Imperfect: {
			Uds: "estaban orientando",
			yo: "estaba orientando",
			tú: "estabas orientando",
			Ud: "estaba orientando",
			nosotros: "estábamos orientando",
			vosotros: "estabais orientando",
		},
		Conditional: {
			yo: "estaría orientando",
			tú: "estarías orientando",
			Ud: "estaría orientando",
			nosotros: "estaríamos orientando",
			vosotros: "estaríais orientando",
			Uds: "estarían orientando",
		},
		Future: {
			yo: "estaré orientando",
			tú: "estarás orientando",
			Ud: "estará orientando",
			nosotros: "estaremos orientando",
			vosotros: "estaréis orientando",
			Uds: "estarán orientando",
		},
	},
	Perfect: {
		Present: {
			yo: "he orientado",
			tú: "has orientado",
			Ud: "ha orientado",
			nosotros: "hemos orientado",
			vosotros: "habéis orientado",
			Uds: "han orientado",
		},
		Preterite: {
			yo: "hube orientado",
			tú: "hubiste orientado",
			Ud: "hubo orientado",
			nosotros: "hubimos orientado",
			vosotros: "hubisteis orientado",
			Uds: "hubieron orientado",
		},
		Past: {
			yo: "había orientado",
			tú: "habías orientado",
			Ud: "había orientado",
			nosotros: "habíamos orientado",
			vosotros: "habíais orientado",
			Uds: "habían orientado",
		},
		Conditional: {
			yo: "habría orientado",
			tú: "habrías orientado",
			Ud: "habría orientado",
			nosotros: "habríamos orientado",
			vosotros: "habríais orientado",
			Uds: "habrían orientado",
		},
		Future: {
			yo: "habré orientado",
			tú: "habrás orientado",
			Ud: "habrá orientado",
			nosotros: "habremos orientado",
			vosotros: "habréis orientado",
			Uds: "habrán orientado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya orientado",
			tú: "hayas orientado",
			Ud: "haya orientado",
			nosotros: "hayamos orientado",
			vosotros: "hayáis orientado",
			Uds: "hayan orientado",
		},
		Past: {
			yo: "hubiera orientado",
			tú: "hubieras orientado",
			Ud: "hubiera orientado",
			nosotros: "hubiéramos orientado",
			vosotros: "hubierais orientado",
			Uds: "hubieran orientado",
		},
		Future: {
			yo: "hubiere orientado",
			tú: "hubieres orientado",
			Ud: "hubiere orientado",
			nosotros: "hubiéremos orientado",
			vosotros: "hubiereis orientado",
			Uds: "hubieren orientado",
		},
	},
}
