var ornar = {
	Indicative: {
		Present: {
			yo: "orno",
			tú: "ornas",
			Ud: "orna",
			nosotros: "ornamos",
			vosotros: "ornáis",
			Uds: "ornan",
		},
		Preterite: {
			yo: "orné",
			tú: "ornaste",
			Ud: "ornó",
			nosotros: "ornamos",
			vosotros: "ornasteis",
			Uds: "ornaron",
		},
		Imperfect: {
			yo: "ornaba",
			tú: "ornabas",
			Ud: "ornaba",
			nosotros: "ornábamos",
			vosotros: "ornabais",
			Uds: "ornaban",
		},
		Conditional: {
			yo: "ornaría",
			tú: "ornarías",
			Ud: "ornaría",
			nosotros: "ornaríamos",
			vosotros: "ornaríais",
			Uds: "ornarían",
		},
		Future: {
			yo: "ornaré",
			tú: "ornarás",
			Ud: "ornará",
			nosotros: "ornaremos",
			vosotros: "ornaréis",
			Uds: "ornarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "orne",
			tú: "ornes",
			Ud: "orne",
			nosotros: "ornemos",
			vosotros: "ornéis",
			Uds: "ornen",
		},
		Imperfect: {
			yo: "ornara",
			tú: "ornaras",
			Ud: "ornara",
			nosotros: "ornáramos",
			vosotros: "ornarais",
			Uds: "ornaran",
		},
		Imperfect2: {
			yo: "ornase",
			tú: "ornases",
			Ud: "ornase",
			nosotros: "ornásemos",
			vosotros: "ornaseis",
			Uds: "ornasen",
		},
		Future: {
			yo: "ornare",
			tú: "ornares",
			Ud: "ornare",
			nosotros: "ornáremos",
			vosotros: "ornareis",
			Uds: "ornaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "orna",
			Ud: "orne",
			nosotros: "ornemos",
			vosotros: "ornad",
			Uds: "ornen",
		},
		Negative: {
			tú: "no ornes",
			Ud: "no orne",
			nosotros: "no ornemos",
			vosotros: "no ornéis",
			Uds: "no ornen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy ornando",
			tú: "estás ornando",
			Ud: "está ornando",
			nosotros: "estamos ornando",
			vosotros: "estáis ornando",
			Uds: "están ornando",
		},
		Preterite: {
			yo: "estuve ornando",
			tú: "estuviste ornando",
			Ud: "estuvo ornando",
			nosotros: "estuvimos ornando",
			vosotros: "estuvisteis ornando",
			Uds: "estuvieron ornando",
		},
		Imperfect: {
			Uds: "estaban ornando",
			yo: "estaba ornando",
			tú: "estabas ornando",
			Ud: "estaba ornando",
			nosotros: "estábamos ornando",
			vosotros: "estabais ornando",
		},
		Conditional: {
			yo: "estaría ornando",
			tú: "estarías ornando",
			Ud: "estaría ornando",
			nosotros: "estaríamos ornando",
			vosotros: "estaríais ornando",
			Uds: "estarían ornando",
		},
		Future: {
			yo: "estaré ornando",
			tú: "estarás ornando",
			Ud: "estará ornando",
			nosotros: "estaremos ornando",
			vosotros: "estaréis ornando",
			Uds: "estarán ornando",
		},
	},
	Perfect: {
		Present: {
			yo: "he ornado",
			tú: "has ornado",
			Ud: "ha ornado",
			nosotros: "hemos ornado",
			vosotros: "habéis ornado",
			Uds: "han ornado",
		},
		Preterite: {
			yo: "hube ornado",
			tú: "hubiste ornado",
			Ud: "hubo ornado",
			nosotros: "hubimos ornado",
			vosotros: "hubisteis ornado",
			Uds: "hubieron ornado",
		},
		Past: {
			yo: "había ornado",
			tú: "habías ornado",
			Ud: "había ornado",
			nosotros: "habíamos ornado",
			vosotros: "habíais ornado",
			Uds: "habían ornado",
		},
		Conditional: {
			yo: "habría ornado",
			tú: "habrías ornado",
			Ud: "habría ornado",
			nosotros: "habríamos ornado",
			vosotros: "habríais ornado",
			Uds: "habrían ornado",
		},
		Future: {
			yo: "habré ornado",
			tú: "habrás ornado",
			Ud: "habrá ornado",
			nosotros: "habremos ornado",
			vosotros: "habréis ornado",
			Uds: "habrán ornado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya ornado",
			tú: "hayas ornado",
			Ud: "haya ornado",
			nosotros: "hayamos ornado",
			vosotros: "hayáis ornado",
			Uds: "hayan ornado",
		},
		Past: {
			yo: "hubiera ornado",
			tú: "hubieras ornado",
			Ud: "hubiera ornado",
			nosotros: "hubiéramos ornado",
			vosotros: "hubierais ornado",
			Uds: "hubieran ornado",
		},
		Future: {
			yo: "hubiere ornado",
			tú: "hubieres ornado",
			Ud: "hubiere ornado",
			nosotros: "hubiéremos ornado",
			vosotros: "hubiereis ornado",
			Uds: "hubieren ornado",
		},
	},
}
