var oscurecer = {
	Indicative: {
		Present: {
			yo: "oscurezco",
			tú: "oscureces",
			Ud: "oscurece",
			nosotros: "oscurecemos",
			vosotros: "oscurecéis",
			Uds: "oscurecen",
		},
		Preterite: {
			yo: "oscurecí",
			tú: "oscureciste",
			Ud: "oscureció",
			nosotros: "oscurecimos",
			vosotros: "oscurecisteis",
			Uds: "oscurecieron",
		},
		Imperfect: {
			yo: "oscurecía",
			tú: "oscurecías",
			Ud: "oscurecía",
			nosotros: "oscurecíamos",
			vosotros: "oscurecíais",
			Uds: "oscurecían",
		},
		Conditional: {
			yo: "oscurecería",
			tú: "oscurecerías",
			Ud: "oscurecería",
			nosotros: "oscureceríamos",
			vosotros: "oscureceríais",
			Uds: "oscurecerían",
		},
		Future: {
			yo: "oscureceré",
			tú: "oscurecerás",
			Ud: "oscurecerá",
			nosotros: "oscureceremos",
			vosotros: "oscureceréis",
			Uds: "oscurecerán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "oscurezca",
			tú: "oscurezcas",
			Ud: "oscurezca",
			nosotros: "oscurezcamos",
			vosotros: "oscurezcáis",
			Uds: "oscurezcan",
		},
		Imperfect: {
			yo: "oscureciera",
			tú: "oscurecieras",
			Ud: "oscureciera",
			nosotros: "oscureciéramos",
			vosotros: "oscurecierais",
			Uds: "oscurecieran",
		},
		Imperfect2: {
			yo: "oscureciese",
			tú: "oscurecieses",
			Ud: "oscureciese",
			nosotros: "oscureciésemos",
			vosotros: "oscurecieseis",
			Uds: "oscureciesen",
		},
		Future: {
			yo: "oscureciere",
			tú: "oscurecieres",
			Ud: "oscureciere",
			nosotros: "oscureciéremos",
			vosotros: "oscureciereis",
			Uds: "oscurecieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "oscurece",
			Ud: "oscurezca",
			nosotros: "oscurezcamos",
			vosotros: "oscureced",
			Uds: "oscurezcan",
		},
		Negative: {
			tú: "no oscurezcas",
			Ud: "no oscurezca",
			nosotros: "no oscurezcamos",
			vosotros: "no oscurezcáis",
			Uds: "no oscurezcan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy oscureciendo",
			tú: "estás oscureciendo",
			Ud: "está oscureciendo",
			nosotros: "estamos oscureciendo",
			vosotros: "estáis oscureciendo",
			Uds: "están oscureciendo",
		},
		Preterite: {
			yo: "estuve oscureciendo",
			tú: "estuviste oscureciendo",
			Ud: "estuvo oscureciendo",
			nosotros: "estuvimos oscureciendo",
			vosotros: "estuvisteis oscureciendo",
			Uds: "estuvieron oscureciendo",
		},
		Imperfect: {
			Uds: "estaban oscureciendo",
			yo: "estaba oscureciendo",
			tú: "estabas oscureciendo",
			Ud: "estaba oscureciendo",
			nosotros: "estábamos oscureciendo",
			vosotros: "estabais oscureciendo",
		},
		Conditional: {
			yo: "estaría oscureciendo",
			tú: "estarías oscureciendo",
			Ud: "estaría oscureciendo",
			nosotros: "estaríamos oscureciendo",
			vosotros: "estaríais oscureciendo",
			Uds: "estarían oscureciendo",
		},
		Future: {
			yo: "estaré oscureciendo",
			tú: "estarás oscureciendo",
			Ud: "estará oscureciendo",
			nosotros: "estaremos oscureciendo",
			vosotros: "estaréis oscureciendo",
			Uds: "estarán oscureciendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he oscurecido",
			tú: "has oscurecido",
			Ud: "ha oscurecido",
			nosotros: "hemos oscurecido",
			vosotros: "habéis oscurecido",
			Uds: "han oscurecido",
		},
		Preterite: {
			yo: "hube oscurecido",
			tú: "hubiste oscurecido",
			Ud: "hubo oscurecido",
			nosotros: "hubimos oscurecido",
			vosotros: "hubisteis oscurecido",
			Uds: "hubieron oscurecido",
		},
		Past: {
			yo: "había oscurecido",
			tú: "habías oscurecido",
			Ud: "había oscurecido",
			nosotros: "habíamos oscurecido",
			vosotros: "habíais oscurecido",
			Uds: "habían oscurecido",
		},
		Conditional: {
			yo: "habría oscurecido",
			tú: "habrías oscurecido",
			Ud: "habría oscurecido",
			nosotros: "habríamos oscurecido",
			vosotros: "habríais oscurecido",
			Uds: "habrían oscurecido",
		},
		Future: {
			yo: "habré oscurecido",
			tú: "habrás oscurecido",
			Ud: "habrá oscurecido",
			nosotros: "habremos oscurecido",
			vosotros: "habréis oscurecido",
			Uds: "habrán oscurecido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya oscurecido",
			tú: "hayas oscurecido",
			Ud: "haya oscurecido",
			nosotros: "hayamos oscurecido",
			vosotros: "hayáis oscurecido",
			Uds: "hayan oscurecido",
		},
		Past: {
			yo: "hubiera oscurecido",
			tú: "hubieras oscurecido",
			Ud: "hubiera oscurecido",
			nosotros: "hubiéramos oscurecido",
			vosotros: "hubierais oscurecido",
			Uds: "hubieran oscurecido",
		},
		Future: {
			yo: "hubiere oscurecido",
			tú: "hubieres oscurecido",
			Ud: "hubiere oscurecido",
			nosotros: "hubiéremos oscurecido",
			vosotros: "hubiereis oscurecido",
			Uds: "hubieren oscurecido",
		},
	},
}
