var palpar = {
	Indicative: {
		Present: {
			yo: "palpo",
			tú: "palpas",
			Ud: "palpa",
			nosotros: "palpamos",
			vosotros: "palpáis",
			Uds: "palpan",
		},
		Preterite: {
			yo: "palpé",
			tú: "palpaste",
			Ud: "palpó",
			nosotros: "palpamos",
			vosotros: "palpasteis",
			Uds: "palparon",
		},
		Imperfect: {
			yo: "palpaba",
			tú: "palpabas",
			Ud: "palpaba",
			nosotros: "palpábamos",
			vosotros: "palpabais",
			Uds: "palpaban",
		},
		Conditional: {
			yo: "palparía",
			tú: "palparías",
			Ud: "palparía",
			nosotros: "palparíamos",
			vosotros: "palparíais",
			Uds: "palparían",
		},
		Future: {
			yo: "palparé",
			tú: "palparás",
			Ud: "palpará",
			nosotros: "palparemos",
			vosotros: "palparéis",
			Uds: "palparán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "palpe",
			tú: "palpes",
			Ud: "palpe",
			nosotros: "palpemos",
			vosotros: "palpéis",
			Uds: "palpen",
		},
		Imperfect: {
			yo: "palpara",
			tú: "palparas",
			Ud: "palpara",
			nosotros: "palpáramos",
			vosotros: "palparais",
			Uds: "palparan",
		},
		Imperfect2: {
			yo: "palpase",
			tú: "palpases",
			Ud: "palpase",
			nosotros: "palpásemos",
			vosotros: "palpaseis",
			Uds: "palpasen",
		},
		Future: {
			yo: "palpare",
			tú: "palpares",
			Ud: "palpare",
			nosotros: "palpáremos",
			vosotros: "palpareis",
			Uds: "palparen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "palpa",
			Ud: "palpe",
			nosotros: "palpemos",
			vosotros: "palpad",
			Uds: "palpen",
		},
		Negative: {
			tú: "no palpes",
			Ud: "no palpe",
			nosotros: "no palpemos",
			vosotros: "no palpéis",
			Uds: "no palpen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy palpando",
			tú: "estás palpando",
			Ud: "está palpando",
			nosotros: "estamos palpando",
			vosotros: "estáis palpando",
			Uds: "están palpando",
		},
		Preterite: {
			yo: "estuve palpando",
			tú: "estuviste palpando",
			Ud: "estuvo palpando",
			nosotros: "estuvimos palpando",
			vosotros: "estuvisteis palpando",
			Uds: "estuvieron palpando",
		},
		Imperfect: {
			Uds: "estaban palpando",
			yo: "estaba palpando",
			tú: "estabas palpando",
			Ud: "estaba palpando",
			nosotros: "estábamos palpando",
			vosotros: "estabais palpando",
		},
		Conditional: {
			yo: "estaría palpando",
			tú: "estarías palpando",
			Ud: "estaría palpando",
			nosotros: "estaríamos palpando",
			vosotros: "estaríais palpando",
			Uds: "estarían palpando",
		},
		Future: {
			yo: "estaré palpando",
			tú: "estarás palpando",
			Ud: "estará palpando",
			nosotros: "estaremos palpando",
			vosotros: "estaréis palpando",
			Uds: "estarán palpando",
		},
	},
	Perfect: {
		Present: {
			yo: "he palpado",
			tú: "has palpado",
			Ud: "ha palpado",
			nosotros: "hemos palpado",
			vosotros: "habéis palpado",
			Uds: "han palpado",
		},
		Preterite: {
			yo: "hube palpado",
			tú: "hubiste palpado",
			Ud: "hubo palpado",
			nosotros: "hubimos palpado",
			vosotros: "hubisteis palpado",
			Uds: "hubieron palpado",
		},
		Past: {
			yo: "había palpado",
			tú: "habías palpado",
			Ud: "había palpado",
			nosotros: "habíamos palpado",
			vosotros: "habíais palpado",
			Uds: "habían palpado",
		},
		Conditional: {
			yo: "habría palpado",
			tú: "habrías palpado",
			Ud: "habría palpado",
			nosotros: "habríamos palpado",
			vosotros: "habríais palpado",
			Uds: "habrían palpado",
		},
		Future: {
			yo: "habré palpado",
			tú: "habrás palpado",
			Ud: "habrá palpado",
			nosotros: "habremos palpado",
			vosotros: "habréis palpado",
			Uds: "habrán palpado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya palpado",
			tú: "hayas palpado",
			Ud: "haya palpado",
			nosotros: "hayamos palpado",
			vosotros: "hayáis palpado",
			Uds: "hayan palpado",
		},
		Past: {
			yo: "hubiera palpado",
			tú: "hubieras palpado",
			Ud: "hubiera palpado",
			nosotros: "hubiéramos palpado",
			vosotros: "hubierais palpado",
			Uds: "hubieran palpado",
		},
		Future: {
			yo: "hubiere palpado",
			tú: "hubieres palpado",
			Ud: "hubiere palpado",
			nosotros: "hubiéremos palpado",
			vosotros: "hubiereis palpado",
			Uds: "hubieren palpado",
		},
	},
}
