var parar = {
	Indicative: {
		Present: {
			yo: "paro",
			tú: "paras",
			Ud: "para",
			nosotros: "paramos",
			vosotros: "paráis",
			Uds: "paran",
		},
		Preterite: {
			yo: "paré",
			tú: "paraste",
			Ud: "paró",
			nosotros: "paramos",
			vosotros: "parasteis",
			Uds: "pararon",
		},
		Imperfect: {
			yo: "paraba",
			tú: "parabas",
			Ud: "paraba",
			nosotros: "parábamos",
			vosotros: "parabais",
			Uds: "paraban",
		},
		Conditional: {
			yo: "pararía",
			tú: "pararías",
			Ud: "pararía",
			nosotros: "pararíamos",
			vosotros: "pararíais",
			Uds: "pararían",
		},
		Future: {
			yo: "pararé",
			tú: "pararás",
			Ud: "parará",
			nosotros: "pararemos",
			vosotros: "pararéis",
			Uds: "pararán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "pare",
			tú: "pares",
			Ud: "pare",
			nosotros: "paremos",
			vosotros: "paréis",
			Uds: "paren",
		},
		Imperfect: {
			yo: "parara",
			tú: "pararas",
			Ud: "parara",
			nosotros: "paráramos",
			vosotros: "pararais",
			Uds: "pararan",
		},
		Imperfect2: {
			yo: "parase",
			tú: "parases",
			Ud: "parase",
			nosotros: "parásemos",
			vosotros: "paraseis",
			Uds: "parasen",
		},
		Future: {
			yo: "parare",
			tú: "parares",
			Ud: "parare",
			nosotros: "paráremos",
			vosotros: "parareis",
			Uds: "pararen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "para",
			Ud: "pare",
			nosotros: "paremos",
			vosotros: "parad",
			Uds: "paren",
		},
		Negative: {
			tú: "no pares",
			Ud: "no pare",
			nosotros: "no paremos",
			vosotros: "no paréis",
			Uds: "no paren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy parando",
			tú: "estás parando",
			Ud: "está parando",
			nosotros: "estamos parando",
			vosotros: "estáis parando",
			Uds: "están parando",
		},
		Preterite: {
			yo: "estuve parando",
			tú: "estuviste parando",
			Ud: "estuvo parando",
			nosotros: "estuvimos parando",
			vosotros: "estuvisteis parando",
			Uds: "estuvieron parando",
		},
		Imperfect: {
			Uds: "estaban parando",
			yo: "estaba parando",
			tú: "estabas parando",
			Ud: "estaba parando",
			nosotros: "estábamos parando",
			vosotros: "estabais parando",
		},
		Conditional: {
			yo: "estaría parando",
			tú: "estarías parando",
			Ud: "estaría parando",
			nosotros: "estaríamos parando",
			vosotros: "estaríais parando",
			Uds: "estarían parando",
		},
		Future: {
			yo: "estaré parando",
			tú: "estarás parando",
			Ud: "estará parando",
			nosotros: "estaremos parando",
			vosotros: "estaréis parando",
			Uds: "estarán parando",
		},
	},
	Perfect: {
		Present: {
			yo: "he parado",
			tú: "has parado",
			Ud: "ha parado",
			nosotros: "hemos parado",
			vosotros: "habéis parado",
			Uds: "han parado",
		},
		Preterite: {
			yo: "hube parado",
			tú: "hubiste parado",
			Ud: "hubo parado",
			nosotros: "hubimos parado",
			vosotros: "hubisteis parado",
			Uds: "hubieron parado",
		},
		Past: {
			yo: "había parado",
			tú: "habías parado",
			Ud: "había parado",
			nosotros: "habíamos parado",
			vosotros: "habíais parado",
			Uds: "habían parado",
		},
		Conditional: {
			yo: "habría parado",
			tú: "habrías parado",
			Ud: "habría parado",
			nosotros: "habríamos parado",
			vosotros: "habríais parado",
			Uds: "habrían parado",
		},
		Future: {
			yo: "habré parado",
			tú: "habrás parado",
			Ud: "habrá parado",
			nosotros: "habremos parado",
			vosotros: "habréis parado",
			Uds: "habrán parado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya parado",
			tú: "hayas parado",
			Ud: "haya parado",
			nosotros: "hayamos parado",
			vosotros: "hayáis parado",
			Uds: "hayan parado",
		},
		Past: {
			yo: "hubiera parado",
			tú: "hubieras parado",
			Ud: "hubiera parado",
			nosotros: "hubiéramos parado",
			vosotros: "hubierais parado",
			Uds: "hubieran parado",
		},
		Future: {
			yo: "hubiere parado",
			tú: "hubieres parado",
			Ud: "hubiere parado",
			nosotros: "hubiéremos parado",
			vosotros: "hubiereis parado",
			Uds: "hubieren parado",
		},
	},
}
