var parlamentar = {
	Indicative: {
		Present: {
			yo: "parlamento",
			tú: "parlamentas",
			Ud: "parlamenta",
			nosotros: "parlamentamos",
			vosotros: "parlamentáis",
			Uds: "parlamentan",
		},
		Preterite: {
			yo: "parlamenté",
			tú: "parlamentaste",
			Ud: "parlamentó",
			nosotros: "parlamentamos",
			vosotros: "parlamentasteis",
			Uds: "parlamentaron",
		},
		Imperfect: {
			yo: "parlamentaba",
			tú: "parlamentabas",
			Ud: "parlamentaba",
			nosotros: "parlamentábamos",
			vosotros: "parlamentabais",
			Uds: "parlamentaban",
		},
		Conditional: {
			yo: "parlamentaría",
			tú: "parlamentarías",
			Ud: "parlamentaría",
			nosotros: "parlamentaríamos",
			vosotros: "parlamentaríais",
			Uds: "parlamentarían",
		},
		Future: {
			yo: "parlamentaré",
			tú: "parlamentarás",
			Ud: "parlamentará",
			nosotros: "parlamentaremos",
			vosotros: "parlamentaréis",
			Uds: "parlamentarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "parlamente",
			tú: "parlamentes",
			Ud: "parlamente",
			nosotros: "parlamentemos",
			vosotros: "parlamentéis",
			Uds: "parlamenten",
		},
		Imperfect: {
			yo: "parlamentara",
			tú: "parlamentaras",
			Ud: "parlamentara",
			nosotros: "parlamentáramos",
			vosotros: "parlamentarais",
			Uds: "parlamentaran",
		},
		Imperfect2: {
			yo: "parlamentase",
			tú: "parlamentases",
			Ud: "parlamentase",
			nosotros: "parlamentásemos",
			vosotros: "parlamentaseis",
			Uds: "parlamentasen",
		},
		Future: {
			yo: "parlamentare",
			tú: "parlamentares",
			Ud: "parlamentare",
			nosotros: "parlamentáremos",
			vosotros: "parlamentareis",
			Uds: "parlamentaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "parlamenta",
			Ud: "parlamente",
			nosotros: "parlamentemos",
			vosotros: "parlamentad",
			Uds: "parlamenten",
		},
		Negative: {
			tú: "no parlamentes",
			Ud: "no parlamente",
			nosotros: "no parlamentemos",
			vosotros: "no parlamentéis",
			Uds: "no parlamenten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy parlamentando",
			tú: "estás parlamentando",
			Ud: "está parlamentando",
			nosotros: "estamos parlamentando",
			vosotros: "estáis parlamentando",
			Uds: "están parlamentando",
		},
		Preterite: {
			yo: "estuve parlamentando",
			tú: "estuviste parlamentando",
			Ud: "estuvo parlamentando",
			nosotros: "estuvimos parlamentando",
			vosotros: "estuvisteis parlamentando",
			Uds: "estuvieron parlamentando",
		},
		Imperfect: {
			Uds: "estaban parlamentando",
			yo: "estaba parlamentando",
			tú: "estabas parlamentando",
			Ud: "estaba parlamentando",
			nosotros: "estábamos parlamentando",
			vosotros: "estabais parlamentando",
		},
		Conditional: {
			yo: "estaría parlamentando",
			tú: "estarías parlamentando",
			Ud: "estaría parlamentando",
			nosotros: "estaríamos parlamentando",
			vosotros: "estaríais parlamentando",
			Uds: "estarían parlamentando",
		},
		Future: {
			yo: "estaré parlamentando",
			tú: "estarás parlamentando",
			Ud: "estará parlamentando",
			nosotros: "estaremos parlamentando",
			vosotros: "estaréis parlamentando",
			Uds: "estarán parlamentando",
		},
	},
	Perfect: {
		Present: {
			yo: "he parlamentado",
			tú: "has parlamentado",
			Ud: "ha parlamentado",
			nosotros: "hemos parlamentado",
			vosotros: "habéis parlamentado",
			Uds: "han parlamentado",
		},
		Preterite: {
			yo: "hube parlamentado",
			tú: "hubiste parlamentado",
			Ud: "hubo parlamentado",
			nosotros: "hubimos parlamentado",
			vosotros: "hubisteis parlamentado",
			Uds: "hubieron parlamentado",
		},
		Past: {
			yo: "había parlamentado",
			tú: "habías parlamentado",
			Ud: "había parlamentado",
			nosotros: "habíamos parlamentado",
			vosotros: "habíais parlamentado",
			Uds: "habían parlamentado",
		},
		Conditional: {
			yo: "habría parlamentado",
			tú: "habrías parlamentado",
			Ud: "habría parlamentado",
			nosotros: "habríamos parlamentado",
			vosotros: "habríais parlamentado",
			Uds: "habrían parlamentado",
		},
		Future: {
			yo: "habré parlamentado",
			tú: "habrás parlamentado",
			Ud: "habrá parlamentado",
			nosotros: "habremos parlamentado",
			vosotros: "habréis parlamentado",
			Uds: "habrán parlamentado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya parlamentado",
			tú: "hayas parlamentado",
			Ud: "haya parlamentado",
			nosotros: "hayamos parlamentado",
			vosotros: "hayáis parlamentado",
			Uds: "hayan parlamentado",
		},
		Past: {
			yo: "hubiera parlamentado",
			tú: "hubieras parlamentado",
			Ud: "hubiera parlamentado",
			nosotros: "hubiéramos parlamentado",
			vosotros: "hubierais parlamentado",
			Uds: "hubieran parlamentado",
		},
		Future: {
			yo: "hubiere parlamentado",
			tú: "hubieres parlamentado",
			Ud: "hubiere parlamentado",
			nosotros: "hubiéremos parlamentado",
			vosotros: "hubiereis parlamentado",
			Uds: "hubieren parlamentado",
		},
	},
}
