var pasmar = {
	Indicative: {
		Present: {
			yo: "pasmo",
			tú: "pasmas",
			Ud: "pasma",
			nosotros: "pasmamos",
			vosotros: "pasmáis",
			Uds: "pasman",
		},
		Preterite: {
			yo: "pasmé",
			tú: "pasmaste",
			Ud: "pasmó",
			nosotros: "pasmamos",
			vosotros: "pasmasteis",
			Uds: "pasmaron",
		},
		Imperfect: {
			yo: "pasmaba",
			tú: "pasmabas",
			Ud: "pasmaba",
			nosotros: "pasmábamos",
			vosotros: "pasmabais",
			Uds: "pasmaban",
		},
		Conditional: {
			yo: "pasmaría",
			tú: "pasmarías",
			Ud: "pasmaría",
			nosotros: "pasmaríamos",
			vosotros: "pasmaríais",
			Uds: "pasmarían",
		},
		Future: {
			yo: "pasmaré",
			tú: "pasmarás",
			Ud: "pasmará",
			nosotros: "pasmaremos",
			vosotros: "pasmaréis",
			Uds: "pasmarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "pasme",
			tú: "pasmes",
			Ud: "pasme",
			nosotros: "pasmemos",
			vosotros: "pasméis",
			Uds: "pasmen",
		},
		Imperfect: {
			yo: "pasmara",
			tú: "pasmaras",
			Ud: "pasmara",
			nosotros: "pasmáramos",
			vosotros: "pasmarais",
			Uds: "pasmaran",
		},
		Imperfect2: {
			yo: "pasmase",
			tú: "pasmases",
			Ud: "pasmase",
			nosotros: "pasmásemos",
			vosotros: "pasmaseis",
			Uds: "pasmasen",
		},
		Future: {
			yo: "pasmare",
			tú: "pasmares",
			Ud: "pasmare",
			nosotros: "pasmáremos",
			vosotros: "pasmareis",
			Uds: "pasmaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "pasma",
			Ud: "pasme",
			nosotros: "pasmemos",
			vosotros: "pasmad",
			Uds: "pasmen",
		},
		Negative: {
			tú: "no pasmes",
			Ud: "no pasme",
			nosotros: "no pasmemos",
			vosotros: "no pasméis",
			Uds: "no pasmen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy pasmando",
			tú: "estás pasmando",
			Ud: "está pasmando",
			nosotros: "estamos pasmando",
			vosotros: "estáis pasmando",
			Uds: "están pasmando",
		},
		Preterite: {
			yo: "estuve pasmando",
			tú: "estuviste pasmando",
			Ud: "estuvo pasmando",
			nosotros: "estuvimos pasmando",
			vosotros: "estuvisteis pasmando",
			Uds: "estuvieron pasmando",
		},
		Imperfect: {
			Uds: "estaban pasmando",
			yo: "estaba pasmando",
			tú: "estabas pasmando",
			Ud: "estaba pasmando",
			nosotros: "estábamos pasmando",
			vosotros: "estabais pasmando",
		},
		Conditional: {
			yo: "estaría pasmando",
			tú: "estarías pasmando",
			Ud: "estaría pasmando",
			nosotros: "estaríamos pasmando",
			vosotros: "estaríais pasmando",
			Uds: "estarían pasmando",
		},
		Future: {
			yo: "estaré pasmando",
			tú: "estarás pasmando",
			Ud: "estará pasmando",
			nosotros: "estaremos pasmando",
			vosotros: "estaréis pasmando",
			Uds: "estarán pasmando",
		},
	},
	Perfect: {
		Present: {
			yo: "he pasmado",
			tú: "has pasmado",
			Ud: "ha pasmado",
			nosotros: "hemos pasmado",
			vosotros: "habéis pasmado",
			Uds: "han pasmado",
		},
		Preterite: {
			yo: "hube pasmado",
			tú: "hubiste pasmado",
			Ud: "hubo pasmado",
			nosotros: "hubimos pasmado",
			vosotros: "hubisteis pasmado",
			Uds: "hubieron pasmado",
		},
		Past: {
			yo: "había pasmado",
			tú: "habías pasmado",
			Ud: "había pasmado",
			nosotros: "habíamos pasmado",
			vosotros: "habíais pasmado",
			Uds: "habían pasmado",
		},
		Conditional: {
			yo: "habría pasmado",
			tú: "habrías pasmado",
			Ud: "habría pasmado",
			nosotros: "habríamos pasmado",
			vosotros: "habríais pasmado",
			Uds: "habrían pasmado",
		},
		Future: {
			yo: "habré pasmado",
			tú: "habrás pasmado",
			Ud: "habrá pasmado",
			nosotros: "habremos pasmado",
			vosotros: "habréis pasmado",
			Uds: "habrán pasmado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya pasmado",
			tú: "hayas pasmado",
			Ud: "haya pasmado",
			nosotros: "hayamos pasmado",
			vosotros: "hayáis pasmado",
			Uds: "hayan pasmado",
		},
		Past: {
			yo: "hubiera pasmado",
			tú: "hubieras pasmado",
			Ud: "hubiera pasmado",
			nosotros: "hubiéramos pasmado",
			vosotros: "hubierais pasmado",
			Uds: "hubieran pasmado",
		},
		Future: {
			yo: "hubiere pasmado",
			tú: "hubieres pasmado",
			Ud: "hubiere pasmado",
			nosotros: "hubiéremos pasmado",
			vosotros: "hubiereis pasmado",
			Uds: "hubieren pasmado",
		},
	},
}
