var patentar = {
	Indicative: {
		Present: {
			yo: "patento",
			tú: "patentas",
			Ud: "patenta",
			nosotros: "patentamos",
			vosotros: "patentáis",
			Uds: "patentan",
		},
		Preterite: {
			yo: "patenté",
			tú: "patentaste",
			Ud: "patentó",
			nosotros: "patentamos",
			vosotros: "patentasteis",
			Uds: "patentaron",
		},
		Imperfect: {
			yo: "patentaba",
			tú: "patentabas",
			Ud: "patentaba",
			nosotros: "patentábamos",
			vosotros: "patentabais",
			Uds: "patentaban",
		},
		Conditional: {
			yo: "patentaría",
			tú: "patentarías",
			Ud: "patentaría",
			nosotros: "patentaríamos",
			vosotros: "patentaríais",
			Uds: "patentarían",
		},
		Future: {
			yo: "patentaré",
			tú: "patentarás",
			Ud: "patentará",
			nosotros: "patentaremos",
			vosotros: "patentaréis",
			Uds: "patentarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "patente",
			tú: "patentes",
			Ud: "patente",
			nosotros: "patentemos",
			vosotros: "patentéis",
			Uds: "patenten",
		},
		Imperfect: {
			yo: "patentara",
			tú: "patentaras",
			Ud: "patentara",
			nosotros: "patentáramos",
			vosotros: "patentarais",
			Uds: "patentaran",
		},
		Imperfect2: {
			yo: "patentase",
			tú: "patentases",
			Ud: "patentase",
			nosotros: "patentásemos",
			vosotros: "patentaseis",
			Uds: "patentasen",
		},
		Future: {
			yo: "patentare",
			tú: "patentares",
			Ud: "patentare",
			nosotros: "patentáremos",
			vosotros: "patentareis",
			Uds: "patentaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "patenta",
			Ud: "patente",
			nosotros: "patentemos",
			vosotros: "patentad",
			Uds: "patenten",
		},
		Negative: {
			tú: "no patentes",
			Ud: "no patente",
			nosotros: "no patentemos",
			vosotros: "no patentéis",
			Uds: "no patenten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy patentando",
			tú: "estás patentando",
			Ud: "está patentando",
			nosotros: "estamos patentando",
			vosotros: "estáis patentando",
			Uds: "están patentando",
		},
		Preterite: {
			yo: "estuve patentando",
			tú: "estuviste patentando",
			Ud: "estuvo patentando",
			nosotros: "estuvimos patentando",
			vosotros: "estuvisteis patentando",
			Uds: "estuvieron patentando",
		},
		Imperfect: {
			Uds: "estaban patentando",
			yo: "estaba patentando",
			tú: "estabas patentando",
			Ud: "estaba patentando",
			nosotros: "estábamos patentando",
			vosotros: "estabais patentando",
		},
		Conditional: {
			yo: "estaría patentando",
			tú: "estarías patentando",
			Ud: "estaría patentando",
			nosotros: "estaríamos patentando",
			vosotros: "estaríais patentando",
			Uds: "estarían patentando",
		},
		Future: {
			yo: "estaré patentando",
			tú: "estarás patentando",
			Ud: "estará patentando",
			nosotros: "estaremos patentando",
			vosotros: "estaréis patentando",
			Uds: "estarán patentando",
		},
	},
	Perfect: {
		Present: {
			yo: "he patentado",
			tú: "has patentado",
			Ud: "ha patentado",
			nosotros: "hemos patentado",
			vosotros: "habéis patentado",
			Uds: "han patentado",
		},
		Preterite: {
			yo: "hube patentado",
			tú: "hubiste patentado",
			Ud: "hubo patentado",
			nosotros: "hubimos patentado",
			vosotros: "hubisteis patentado",
			Uds: "hubieron patentado",
		},
		Past: {
			yo: "había patentado",
			tú: "habías patentado",
			Ud: "había patentado",
			nosotros: "habíamos patentado",
			vosotros: "habíais patentado",
			Uds: "habían patentado",
		},
		Conditional: {
			yo: "habría patentado",
			tú: "habrías patentado",
			Ud: "habría patentado",
			nosotros: "habríamos patentado",
			vosotros: "habríais patentado",
			Uds: "habrían patentado",
		},
		Future: {
			yo: "habré patentado",
			tú: "habrás patentado",
			Ud: "habrá patentado",
			nosotros: "habremos patentado",
			vosotros: "habréis patentado",
			Uds: "habrán patentado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya patentado",
			tú: "hayas patentado",
			Ud: "haya patentado",
			nosotros: "hayamos patentado",
			vosotros: "hayáis patentado",
			Uds: "hayan patentado",
		},
		Past: {
			yo: "hubiera patentado",
			tú: "hubieras patentado",
			Ud: "hubiera patentado",
			nosotros: "hubiéramos patentado",
			vosotros: "hubierais patentado",
			Uds: "hubieran patentado",
		},
		Future: {
			yo: "hubiere patentado",
			tú: "hubieres patentado",
			Ud: "hubiere patentado",
			nosotros: "hubiéremos patentado",
			vosotros: "hubiereis patentado",
			Uds: "hubieren patentado",
		},
	},
}
