var pausar = {
	Indicative: {
		Present: {
			yo: "pauso",
			tú: "pausas",
			Ud: "pausa",
			nosotros: "pausamos",
			vosotros: "pausáis",
			Uds: "pausan",
		},
		Preterite: {
			yo: "pausé",
			tú: "pausaste",
			Ud: "pausó",
			nosotros: "pausamos",
			vosotros: "pausasteis",
			Uds: "pausaron",
		},
		Imperfect: {
			yo: "pausaba",
			tú: "pausabas",
			Ud: "pausaba",
			nosotros: "pausábamos",
			vosotros: "pausabais",
			Uds: "pausaban",
		},
		Conditional: {
			yo: "pausaría",
			tú: "pausarías",
			Ud: "pausaría",
			nosotros: "pausaríamos",
			vosotros: "pausaríais",
			Uds: "pausarían",
		},
		Future: {
			yo: "pausaré",
			tú: "pausarás",
			Ud: "pausará",
			nosotros: "pausaremos",
			vosotros: "pausaréis",
			Uds: "pausarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "pause",
			tú: "pauses",
			Ud: "pause",
			nosotros: "pausemos",
			vosotros: "pauséis",
			Uds: "pausen",
		},
		Imperfect: {
			yo: "pausara",
			tú: "pausaras",
			Ud: "pausara",
			nosotros: "pausáramos",
			vosotros: "pausarais",
			Uds: "pausaran",
		},
		Imperfect2: {
			yo: "pausase",
			tú: "pausases",
			Ud: "pausase",
			nosotros: "pausásemos",
			vosotros: "pausaseis",
			Uds: "pausasen",
		},
		Future: {
			yo: "pausare",
			tú: "pausares",
			Ud: "pausare",
			nosotros: "pausáremos",
			vosotros: "pausareis",
			Uds: "pausaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "pausa",
			Ud: "pause",
			nosotros: "pausemos",
			vosotros: "pausad",
			Uds: "pausen",
		},
		Negative: {
			tú: "no pauses",
			Ud: "no pause",
			nosotros: "no pausemos",
			vosotros: "no pauséis",
			Uds: "no pausen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy pausando",
			tú: "estás pausando",
			Ud: "está pausando",
			nosotros: "estamos pausando",
			vosotros: "estáis pausando",
			Uds: "están pausando",
		},
		Preterite: {
			yo: "estuve pausando",
			tú: "estuviste pausando",
			Ud: "estuvo pausando",
			nosotros: "estuvimos pausando",
			vosotros: "estuvisteis pausando",
			Uds: "estuvieron pausando",
		},
		Imperfect: {
			Uds: "estaban pausando",
			yo: "estaba pausando",
			tú: "estabas pausando",
			Ud: "estaba pausando",
			nosotros: "estábamos pausando",
			vosotros: "estabais pausando",
		},
		Conditional: {
			yo: "estaría pausando",
			tú: "estarías pausando",
			Ud: "estaría pausando",
			nosotros: "estaríamos pausando",
			vosotros: "estaríais pausando",
			Uds: "estarían pausando",
		},
		Future: {
			yo: "estaré pausando",
			tú: "estarás pausando",
			Ud: "estará pausando",
			nosotros: "estaremos pausando",
			vosotros: "estaréis pausando",
			Uds: "estarán pausando",
		},
	},
	Perfect: {
		Present: {
			yo: "he pausado",
			tú: "has pausado",
			Ud: "ha pausado",
			nosotros: "hemos pausado",
			vosotros: "habéis pausado",
			Uds: "han pausado",
		},
		Preterite: {
			yo: "hube pausado",
			tú: "hubiste pausado",
			Ud: "hubo pausado",
			nosotros: "hubimos pausado",
			vosotros: "hubisteis pausado",
			Uds: "hubieron pausado",
		},
		Past: {
			yo: "había pausado",
			tú: "habías pausado",
			Ud: "había pausado",
			nosotros: "habíamos pausado",
			vosotros: "habíais pausado",
			Uds: "habían pausado",
		},
		Conditional: {
			yo: "habría pausado",
			tú: "habrías pausado",
			Ud: "habría pausado",
			nosotros: "habríamos pausado",
			vosotros: "habríais pausado",
			Uds: "habrían pausado",
		},
		Future: {
			yo: "habré pausado",
			tú: "habrás pausado",
			Ud: "habrá pausado",
			nosotros: "habremos pausado",
			vosotros: "habréis pausado",
			Uds: "habrán pausado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya pausado",
			tú: "hayas pausado",
			Ud: "haya pausado",
			nosotros: "hayamos pausado",
			vosotros: "hayáis pausado",
			Uds: "hayan pausado",
		},
		Past: {
			yo: "hubiera pausado",
			tú: "hubieras pausado",
			Ud: "hubiera pausado",
			nosotros: "hubiéramos pausado",
			vosotros: "hubierais pausado",
			Uds: "hubieran pausado",
		},
		Future: {
			yo: "hubiere pausado",
			tú: "hubieres pausado",
			Ud: "hubiere pausado",
			nosotros: "hubiéremos pausado",
			vosotros: "hubiereis pausado",
			Uds: "hubieren pausado",
		},
	},
}
