var pedalear = {
	Indicative: {
		Present: {
			yo: "pedaleo",
			tú: "pedaleas",
			Ud: "pedalea",
			nosotros: "pedaleamos",
			vosotros: "pedaleáis",
			Uds: "pedalean",
		},
		Preterite: {
			yo: "pedaleé",
			tú: "pedaleaste",
			Ud: "pedaleó",
			nosotros: "pedaleamos",
			vosotros: "pedaleasteis",
			Uds: "pedalearon",
		},
		Imperfect: {
			yo: "pedaleaba",
			tú: "pedaleabas",
			Ud: "pedaleaba",
			nosotros: "pedaleábamos",
			vosotros: "pedaleabais",
			Uds: "pedaleaban",
		},
		Conditional: {
			yo: "pedalearía",
			tú: "pedalearías",
			Ud: "pedalearía",
			nosotros: "pedalearíamos",
			vosotros: "pedalearíais",
			Uds: "pedalearían",
		},
		Future: {
			yo: "pedalearé",
			tú: "pedalearás",
			Ud: "pedaleará",
			nosotros: "pedalearemos",
			vosotros: "pedalearéis",
			Uds: "pedalearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "pedalee",
			tú: "pedalees",
			Ud: "pedalee",
			nosotros: "pedaleemos",
			vosotros: "pedaleéis",
			Uds: "pedaleen",
		},
		Imperfect: {
			yo: "pedaleara",
			tú: "pedalearas",
			Ud: "pedaleara",
			nosotros: "pedaleáramos",
			vosotros: "pedalearais",
			Uds: "pedalearan",
		},
		Imperfect2: {
			yo: "pedalease",
			tú: "pedaleases",
			Ud: "pedalease",
			nosotros: "pedaleásemos",
			vosotros: "pedaleaseis",
			Uds: "pedaleasen",
		},
		Future: {
			yo: "pedaleare",
			tú: "pedaleares",
			Ud: "pedaleare",
			nosotros: "pedaleáremos",
			vosotros: "pedaleareis",
			Uds: "pedalearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "pedalea",
			Ud: "pedalee",
			nosotros: "pedaleemos",
			vosotros: "pedalead",
			Uds: "pedaleen",
		},
		Negative: {
			tú: "no pedalees",
			Ud: "no pedalee",
			nosotros: "no pedaleemos",
			vosotros: "no pedaleéis",
			Uds: "no pedaleen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy pedaleando",
			tú: "estás pedaleando",
			Ud: "está pedaleando",
			nosotros: "estamos pedaleando",
			vosotros: "estáis pedaleando",
			Uds: "están pedaleando",
		},
		Preterite: {
			yo: "estuve pedaleando",
			tú: "estuviste pedaleando",
			Ud: "estuvo pedaleando",
			nosotros: "estuvimos pedaleando",
			vosotros: "estuvisteis pedaleando",
			Uds: "estuvieron pedaleando",
		},
		Imperfect: {
			Uds: "estaban pedaleando",
			yo: "estaba pedaleando",
			tú: "estabas pedaleando",
			Ud: "estaba pedaleando",
			nosotros: "estábamos pedaleando",
			vosotros: "estabais pedaleando",
		},
		Conditional: {
			yo: "estaría pedaleando",
			tú: "estarías pedaleando",
			Ud: "estaría pedaleando",
			nosotros: "estaríamos pedaleando",
			vosotros: "estaríais pedaleando",
			Uds: "estarían pedaleando",
		},
		Future: {
			yo: "estaré pedaleando",
			tú: "estarás pedaleando",
			Ud: "estará pedaleando",
			nosotros: "estaremos pedaleando",
			vosotros: "estaréis pedaleando",
			Uds: "estarán pedaleando",
		},
	},
	Perfect: {
		Present: {
			yo: "he pedaleado",
			tú: "has pedaleado",
			Ud: "ha pedaleado",
			nosotros: "hemos pedaleado",
			vosotros: "habéis pedaleado",
			Uds: "han pedaleado",
		},
		Preterite: {
			yo: "hube pedaleado",
			tú: "hubiste pedaleado",
			Ud: "hubo pedaleado",
			nosotros: "hubimos pedaleado",
			vosotros: "hubisteis pedaleado",
			Uds: "hubieron pedaleado",
		},
		Past: {
			yo: "había pedaleado",
			tú: "habías pedaleado",
			Ud: "había pedaleado",
			nosotros: "habíamos pedaleado",
			vosotros: "habíais pedaleado",
			Uds: "habían pedaleado",
		},
		Conditional: {
			yo: "habría pedaleado",
			tú: "habrías pedaleado",
			Ud: "habría pedaleado",
			nosotros: "habríamos pedaleado",
			vosotros: "habríais pedaleado",
			Uds: "habrían pedaleado",
		},
		Future: {
			yo: "habré pedaleado",
			tú: "habrás pedaleado",
			Ud: "habrá pedaleado",
			nosotros: "habremos pedaleado",
			vosotros: "habréis pedaleado",
			Uds: "habrán pedaleado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya pedaleado",
			tú: "hayas pedaleado",
			Ud: "haya pedaleado",
			nosotros: "hayamos pedaleado",
			vosotros: "hayáis pedaleado",
			Uds: "hayan pedaleado",
		},
		Past: {
			yo: "hubiera pedaleado",
			tú: "hubieras pedaleado",
			Ud: "hubiera pedaleado",
			nosotros: "hubiéramos pedaleado",
			vosotros: "hubierais pedaleado",
			Uds: "hubieran pedaleado",
		},
		Future: {
			yo: "hubiere pedaleado",
			tú: "hubieres pedaleado",
			Ud: "hubiere pedaleado",
			nosotros: "hubiéremos pedaleado",
			vosotros: "hubiereis pedaleado",
			Uds: "hubieren pedaleado",
		},
	},
}
