var perfumar = {
	Indicative: {
		Present: {
			yo: "perfumo",
			tú: "perfumas",
			Ud: "perfuma",
			nosotros: "perfumamos",
			vosotros: "perfumáis",
			Uds: "perfuman",
		},
		Preterite: {
			yo: "perfumé",
			tú: "perfumaste",
			Ud: "perfumó",
			nosotros: "perfumamos",
			vosotros: "perfumasteis",
			Uds: "perfumaron",
		},
		Imperfect: {
			yo: "perfumaba",
			tú: "perfumabas",
			Ud: "perfumaba",
			nosotros: "perfumábamos",
			vosotros: "perfumabais",
			Uds: "perfumaban",
		},
		Conditional: {
			yo: "perfumaría",
			tú: "perfumarías",
			Ud: "perfumaría",
			nosotros: "perfumaríamos",
			vosotros: "perfumaríais",
			Uds: "perfumarían",
		},
		Future: {
			yo: "perfumaré",
			tú: "perfumarás",
			Ud: "perfumará",
			nosotros: "perfumaremos",
			vosotros: "perfumaréis",
			Uds: "perfumarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "perfume",
			tú: "perfumes",
			Ud: "perfume",
			nosotros: "perfumemos",
			vosotros: "perfuméis",
			Uds: "perfumen",
		},
		Imperfect: {
			yo: "perfumara",
			tú: "perfumaras",
			Ud: "perfumara",
			nosotros: "perfumáramos",
			vosotros: "perfumarais",
			Uds: "perfumaran",
		},
		Imperfect2: {
			yo: "perfumase",
			tú: "perfumases",
			Ud: "perfumase",
			nosotros: "perfumásemos",
			vosotros: "perfumaseis",
			Uds: "perfumasen",
		},
		Future: {
			yo: "perfumare",
			tú: "perfumares",
			Ud: "perfumare",
			nosotros: "perfumáremos",
			vosotros: "perfumareis",
			Uds: "perfumaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "perfuma",
			Ud: "perfume",
			nosotros: "perfumemos",
			vosotros: "perfumad",
			Uds: "perfumen",
		},
		Negative: {
			tú: "no perfumes",
			Ud: "no perfume",
			nosotros: "no perfumemos",
			vosotros: "no perfuméis",
			Uds: "no perfumen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy perfumando",
			tú: "estás perfumando",
			Ud: "está perfumando",
			nosotros: "estamos perfumando",
			vosotros: "estáis perfumando",
			Uds: "están perfumando",
		},
		Preterite: {
			yo: "estuve perfumando",
			tú: "estuviste perfumando",
			Ud: "estuvo perfumando",
			nosotros: "estuvimos perfumando",
			vosotros: "estuvisteis perfumando",
			Uds: "estuvieron perfumando",
		},
		Imperfect: {
			Uds: "estaban perfumando",
			yo: "estaba perfumando",
			tú: "estabas perfumando",
			Ud: "estaba perfumando",
			nosotros: "estábamos perfumando",
			vosotros: "estabais perfumando",
		},
		Conditional: {
			yo: "estaría perfumando",
			tú: "estarías perfumando",
			Ud: "estaría perfumando",
			nosotros: "estaríamos perfumando",
			vosotros: "estaríais perfumando",
			Uds: "estarían perfumando",
		},
		Future: {
			yo: "estaré perfumando",
			tú: "estarás perfumando",
			Ud: "estará perfumando",
			nosotros: "estaremos perfumando",
			vosotros: "estaréis perfumando",
			Uds: "estarán perfumando",
		},
	},
	Perfect: {
		Present: {
			yo: "he perfumado",
			tú: "has perfumado",
			Ud: "ha perfumado",
			nosotros: "hemos perfumado",
			vosotros: "habéis perfumado",
			Uds: "han perfumado",
		},
		Preterite: {
			yo: "hube perfumado",
			tú: "hubiste perfumado",
			Ud: "hubo perfumado",
			nosotros: "hubimos perfumado",
			vosotros: "hubisteis perfumado",
			Uds: "hubieron perfumado",
		},
		Past: {
			yo: "había perfumado",
			tú: "habías perfumado",
			Ud: "había perfumado",
			nosotros: "habíamos perfumado",
			vosotros: "habíais perfumado",
			Uds: "habían perfumado",
		},
		Conditional: {
			yo: "habría perfumado",
			tú: "habrías perfumado",
			Ud: "habría perfumado",
			nosotros: "habríamos perfumado",
			vosotros: "habríais perfumado",
			Uds: "habrían perfumado",
		},
		Future: {
			yo: "habré perfumado",
			tú: "habrás perfumado",
			Ud: "habrá perfumado",
			nosotros: "habremos perfumado",
			vosotros: "habréis perfumado",
			Uds: "habrán perfumado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya perfumado",
			tú: "hayas perfumado",
			Ud: "haya perfumado",
			nosotros: "hayamos perfumado",
			vosotros: "hayáis perfumado",
			Uds: "hayan perfumado",
		},
		Past: {
			yo: "hubiera perfumado",
			tú: "hubieras perfumado",
			Ud: "hubiera perfumado",
			nosotros: "hubiéramos perfumado",
			vosotros: "hubierais perfumado",
			Uds: "hubieran perfumado",
		},
		Future: {
			yo: "hubiere perfumado",
			tú: "hubieres perfumado",
			Ud: "hubiere perfumado",
			nosotros: "hubiéremos perfumado",
			vosotros: "hubiereis perfumado",
			Uds: "hubieren perfumado",
		},
	},
}
