var perfeccionar = {
	Indicative: {
		Present: {
			yo: "perfecciono",
			tú: "perfeccionas",
			Ud: "perfecciona",
			nosotros: "perfeccionamos",
			vosotros: "perfeccionáis",
			Uds: "perfeccionan",
		},
		Preterite: {
			yo: "perfeccioné",
			tú: "perfeccionaste",
			Ud: "perfeccionó",
			nosotros: "perfeccionamos",
			vosotros: "perfeccionasteis",
			Uds: "perfeccionaron",
		},
		Imperfect: {
			yo: "perfeccionaba",
			tú: "perfeccionabas",
			Ud: "perfeccionaba",
			nosotros: "perfeccionábamos",
			vosotros: "perfeccionabais",
			Uds: "perfeccionaban",
		},
		Conditional: {
			yo: "perfeccionaría",
			tú: "perfeccionarías",
			Ud: "perfeccionaría",
			nosotros: "perfeccionaríamos",
			vosotros: "perfeccionaríais",
			Uds: "perfeccionarían",
		},
		Future: {
			yo: "perfeccionaré",
			tú: "perfeccionarás",
			Ud: "perfeccionará",
			nosotros: "perfeccionaremos",
			vosotros: "perfeccionaréis",
			Uds: "perfeccionarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "perfeccione",
			tú: "perfecciones",
			Ud: "perfeccione",
			nosotros: "perfeccionemos",
			vosotros: "perfeccionéis",
			Uds: "perfeccionen",
		},
		Imperfect: {
			yo: "perfeccionara",
			tú: "perfeccionaras",
			Ud: "perfeccionara",
			nosotros: "perfeccionáramos",
			vosotros: "perfeccionarais",
			Uds: "perfeccionaran",
		},
		Imperfect2: {
			yo: "perfeccionase",
			tú: "perfeccionases",
			Ud: "perfeccionase",
			nosotros: "perfeccionásemos",
			vosotros: "perfeccionaseis",
			Uds: "perfeccionasen",
		},
		Future: {
			yo: "perfeccionare",
			tú: "perfeccionares",
			Ud: "perfeccionare",
			nosotros: "perfeccionáremos",
			vosotros: "perfeccionareis",
			Uds: "perfeccionaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "perfecciona",
			Ud: "perfeccione",
			nosotros: "perfeccionemos",
			vosotros: "perfeccionad",
			Uds: "perfeccionen",
		},
		Negative: {
			tú: "no perfecciones",
			Ud: "no perfeccione",
			nosotros: "no perfeccionemos",
			vosotros: "no perfeccionéis",
			Uds: "no perfeccionen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy perfeccionando",
			tú: "estás perfeccionando",
			Ud: "está perfeccionando",
			nosotros: "estamos perfeccionando",
			vosotros: "estáis perfeccionando",
			Uds: "están perfeccionando",
		},
		Preterite: {
			yo: "estuve perfeccionando",
			tú: "estuviste perfeccionando",
			Ud: "estuvo perfeccionando",
			nosotros: "estuvimos perfeccionando",
			vosotros: "estuvisteis perfeccionando",
			Uds: "estuvieron perfeccionando",
		},
		Imperfect: {
			Uds: "estaban perfeccionando",
			yo: "estaba perfeccionando",
			tú: "estabas perfeccionando",
			Ud: "estaba perfeccionando",
			nosotros: "estábamos perfeccionando",
			vosotros: "estabais perfeccionando",
		},
		Conditional: {
			yo: "estaría perfeccionando",
			tú: "estarías perfeccionando",
			Ud: "estaría perfeccionando",
			nosotros: "estaríamos perfeccionando",
			vosotros: "estaríais perfeccionando",
			Uds: "estarían perfeccionando",
		},
		Future: {
			yo: "estaré perfeccionando",
			tú: "estarás perfeccionando",
			Ud: "estará perfeccionando",
			nosotros: "estaremos perfeccionando",
			vosotros: "estaréis perfeccionando",
			Uds: "estarán perfeccionando",
		},
	},
	Perfect: {
		Present: {
			yo: "he perfeccionado",
			tú: "has perfeccionado",
			Ud: "ha perfeccionado",
			nosotros: "hemos perfeccionado",
			vosotros: "habéis perfeccionado",
			Uds: "han perfeccionado",
		},
		Preterite: {
			yo: "hube perfeccionado",
			tú: "hubiste perfeccionado",
			Ud: "hubo perfeccionado",
			nosotros: "hubimos perfeccionado",
			vosotros: "hubisteis perfeccionado",
			Uds: "hubieron perfeccionado",
		},
		Past: {
			yo: "había perfeccionado",
			tú: "habías perfeccionado",
			Ud: "había perfeccionado",
			nosotros: "habíamos perfeccionado",
			vosotros: "habíais perfeccionado",
			Uds: "habían perfeccionado",
		},
		Conditional: {
			yo: "habría perfeccionado",
			tú: "habrías perfeccionado",
			Ud: "habría perfeccionado",
			nosotros: "habríamos perfeccionado",
			vosotros: "habríais perfeccionado",
			Uds: "habrían perfeccionado",
		},
		Future: {
			yo: "habré perfeccionado",
			tú: "habrás perfeccionado",
			Ud: "habrá perfeccionado",
			nosotros: "habremos perfeccionado",
			vosotros: "habréis perfeccionado",
			Uds: "habrán perfeccionado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya perfeccionado",
			tú: "hayas perfeccionado",
			Ud: "haya perfeccionado",
			nosotros: "hayamos perfeccionado",
			vosotros: "hayáis perfeccionado",
			Uds: "hayan perfeccionado",
		},
		Past: {
			yo: "hubiera perfeccionado",
			tú: "hubieras perfeccionado",
			Ud: "hubiera perfeccionado",
			nosotros: "hubiéramos perfeccionado",
			vosotros: "hubierais perfeccionado",
			Uds: "hubieran perfeccionado",
		},
		Future: {
			yo: "hubiere perfeccionado",
			tú: "hubieres perfeccionado",
			Ud: "hubiere perfeccionado",
			nosotros: "hubiéremos perfeccionado",
			vosotros: "hubiereis perfeccionado",
			Uds: "hubieren perfeccionado",
		},
	},
}
