var permanecer = {
	Indicative: {
		Present: {
			yo: "permanezco",
			tú: "permaneces",
			Ud: "permanece",
			nosotros: "permanecemos",
			vosotros: "permanecéis",
			Uds: "permanecen",
		},
		Preterite: {
			yo: "permanecí",
			tú: "permaneciste",
			Ud: "permaneció",
			nosotros: "permanecimos",
			vosotros: "permanecisteis",
			Uds: "permanecieron",
		},
		Imperfect: {
			yo: "permanecía",
			tú: "permanecías",
			Ud: "permanecía",
			nosotros: "permanecíamos",
			vosotros: "permanecíais",
			Uds: "permanecían",
		},
		Conditional: {
			yo: "permanecería",
			tú: "permanecerías",
			Ud: "permanecería",
			nosotros: "permaneceríamos",
			vosotros: "permaneceríais",
			Uds: "permanecerían",
		},
		Future: {
			yo: "permaneceré",
			tú: "permanecerás",
			Ud: "permanecerá",
			nosotros: "permaneceremos",
			vosotros: "permaneceréis",
			Uds: "permanecerán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "permanezca",
			tú: "permanezcas",
			Ud: "permanezca",
			nosotros: "permanezcamos",
			vosotros: "permanezcáis",
			Uds: "permanezcan",
		},
		Imperfect: {
			yo: "permaneciera",
			tú: "permanecieras",
			Ud: "permaneciera",
			nosotros: "permaneciéramos",
			vosotros: "permanecierais",
			Uds: "permanecieran",
		},
		Imperfect2: {
			yo: "permaneciese",
			tú: "permanecieses",
			Ud: "permaneciese",
			nosotros: "permaneciésemos",
			vosotros: "permanecieseis",
			Uds: "permaneciesen",
		},
		Future: {
			yo: "permaneciere",
			tú: "permanecieres",
			Ud: "permaneciere",
			nosotros: "permaneciéremos",
			vosotros: "permaneciereis",
			Uds: "permanecieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "permanece",
			Ud: "permanezca",
			nosotros: "permanezcamos",
			vosotros: "permaneced",
			Uds: "permanezcan",
		},
		Negative: {
			tú: "no permanezcas",
			Ud: "no permanezca",
			nosotros: "no permanezcamos",
			vosotros: "no permanezcáis",
			Uds: "no permanezcan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy permaneciendo",
			tú: "estás permaneciendo",
			Ud: "está permaneciendo",
			nosotros: "estamos permaneciendo",
			vosotros: "estáis permaneciendo",
			Uds: "están permaneciendo",
		},
		Preterite: {
			yo: "estuve permaneciendo",
			tú: "estuviste permaneciendo",
			Ud: "estuvo permaneciendo",
			nosotros: "estuvimos permaneciendo",
			vosotros: "estuvisteis permaneciendo",
			Uds: "estuvieron permaneciendo",
		},
		Imperfect: {
			Uds: "estaban permaneciendo",
			yo: "estaba permaneciendo",
			tú: "estabas permaneciendo",
			Ud: "estaba permaneciendo",
			nosotros: "estábamos permaneciendo",
			vosotros: "estabais permaneciendo",
		},
		Conditional: {
			yo: "estaría permaneciendo",
			tú: "estarías permaneciendo",
			Ud: "estaría permaneciendo",
			nosotros: "estaríamos permaneciendo",
			vosotros: "estaríais permaneciendo",
			Uds: "estarían permaneciendo",
		},
		Future: {
			yo: "estaré permaneciendo",
			tú: "estarás permaneciendo",
			Ud: "estará permaneciendo",
			nosotros: "estaremos permaneciendo",
			vosotros: "estaréis permaneciendo",
			Uds: "estarán permaneciendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he permanecido",
			tú: "has permanecido",
			Ud: "ha permanecido",
			nosotros: "hemos permanecido",
			vosotros: "habéis permanecido",
			Uds: "han permanecido",
		},
		Preterite: {
			yo: "hube permanecido",
			tú: "hubiste permanecido",
			Ud: "hubo permanecido",
			nosotros: "hubimos permanecido",
			vosotros: "hubisteis permanecido",
			Uds: "hubieron permanecido",
		},
		Past: {
			yo: "había permanecido",
			tú: "habías permanecido",
			Ud: "había permanecido",
			nosotros: "habíamos permanecido",
			vosotros: "habíais permanecido",
			Uds: "habían permanecido",
		},
		Conditional: {
			yo: "habría permanecido",
			tú: "habrías permanecido",
			Ud: "habría permanecido",
			nosotros: "habríamos permanecido",
			vosotros: "habríais permanecido",
			Uds: "habrían permanecido",
		},
		Future: {
			yo: "habré permanecido",
			tú: "habrás permanecido",
			Ud: "habrá permanecido",
			nosotros: "habremos permanecido",
			vosotros: "habréis permanecido",
			Uds: "habrán permanecido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya permanecido",
			tú: "hayas permanecido",
			Ud: "haya permanecido",
			nosotros: "hayamos permanecido",
			vosotros: "hayáis permanecido",
			Uds: "hayan permanecido",
		},
		Past: {
			yo: "hubiera permanecido",
			tú: "hubieras permanecido",
			Ud: "hubiera permanecido",
			nosotros: "hubiéramos permanecido",
			vosotros: "hubierais permanecido",
			Uds: "hubieran permanecido",
		},
		Future: {
			yo: "hubiere permanecido",
			tú: "hubieres permanecido",
			Ud: "hubiere permanecido",
			nosotros: "hubiéremos permanecido",
			vosotros: "hubiereis permanecido",
			Uds: "hubieren permanecido",
		},
	},
}
