var perseverar = {
	Indicative: {
		Present: {
			yo: "persevero",
			tú: "perseveras",
			Ud: "persevera",
			nosotros: "perseveramos",
			vosotros: "perseveráis",
			Uds: "perseveran",
		},
		Preterite: {
			yo: "perseveré",
			tú: "perseveraste",
			Ud: "perseveró",
			nosotros: "perseveramos",
			vosotros: "perseverasteis",
			Uds: "perseveraron",
		},
		Imperfect: {
			yo: "perseveraba",
			tú: "perseverabas",
			Ud: "perseveraba",
			nosotros: "perseverábamos",
			vosotros: "perseverabais",
			Uds: "perseveraban",
		},
		Conditional: {
			yo: "perseveraría",
			tú: "perseverarías",
			Ud: "perseveraría",
			nosotros: "perseveraríamos",
			vosotros: "perseveraríais",
			Uds: "perseverarían",
		},
		Future: {
			yo: "perseveraré",
			tú: "perseverarás",
			Ud: "perseverará",
			nosotros: "perseveraremos",
			vosotros: "perseveraréis",
			Uds: "perseverarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "persevere",
			tú: "perseveres",
			Ud: "persevere",
			nosotros: "perseveremos",
			vosotros: "perseveréis",
			Uds: "perseveren",
		},
		Imperfect: {
			yo: "perseverara",
			tú: "perseveraras",
			Ud: "perseverara",
			nosotros: "perseveráramos",
			vosotros: "perseverarais",
			Uds: "perseveraran",
		},
		Imperfect2: {
			yo: "perseverase",
			tú: "perseverases",
			Ud: "perseverase",
			nosotros: "perseverásemos",
			vosotros: "perseveraseis",
			Uds: "perseverasen",
		},
		Future: {
			yo: "perseverare",
			tú: "perseverares",
			Ud: "perseverare",
			nosotros: "perseveráremos",
			vosotros: "perseverareis",
			Uds: "perseveraren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "persevera",
			Ud: "persevere",
			nosotros: "perseveremos",
			vosotros: "perseverad",
			Uds: "perseveren",
		},
		Negative: {
			tú: "no perseveres",
			Ud: "no persevere",
			nosotros: "no perseveremos",
			vosotros: "no perseveréis",
			Uds: "no perseveren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy perseverando",
			tú: "estás perseverando",
			Ud: "está perseverando",
			nosotros: "estamos perseverando",
			vosotros: "estáis perseverando",
			Uds: "están perseverando",
		},
		Preterite: {
			yo: "estuve perseverando",
			tú: "estuviste perseverando",
			Ud: "estuvo perseverando",
			nosotros: "estuvimos perseverando",
			vosotros: "estuvisteis perseverando",
			Uds: "estuvieron perseverando",
		},
		Imperfect: {
			Uds: "estaban perseverando",
			yo: "estaba perseverando",
			tú: "estabas perseverando",
			Ud: "estaba perseverando",
			nosotros: "estábamos perseverando",
			vosotros: "estabais perseverando",
		},
		Conditional: {
			yo: "estaría perseverando",
			tú: "estarías perseverando",
			Ud: "estaría perseverando",
			nosotros: "estaríamos perseverando",
			vosotros: "estaríais perseverando",
			Uds: "estarían perseverando",
		},
		Future: {
			yo: "estaré perseverando",
			tú: "estarás perseverando",
			Ud: "estará perseverando",
			nosotros: "estaremos perseverando",
			vosotros: "estaréis perseverando",
			Uds: "estarán perseverando",
		},
	},
	Perfect: {
		Present: {
			yo: "he perseverado",
			tú: "has perseverado",
			Ud: "ha perseverado",
			nosotros: "hemos perseverado",
			vosotros: "habéis perseverado",
			Uds: "han perseverado",
		},
		Preterite: {
			yo: "hube perseverado",
			tú: "hubiste perseverado",
			Ud: "hubo perseverado",
			nosotros: "hubimos perseverado",
			vosotros: "hubisteis perseverado",
			Uds: "hubieron perseverado",
		},
		Past: {
			yo: "había perseverado",
			tú: "habías perseverado",
			Ud: "había perseverado",
			nosotros: "habíamos perseverado",
			vosotros: "habíais perseverado",
			Uds: "habían perseverado",
		},
		Conditional: {
			yo: "habría perseverado",
			tú: "habrías perseverado",
			Ud: "habría perseverado",
			nosotros: "habríamos perseverado",
			vosotros: "habríais perseverado",
			Uds: "habrían perseverado",
		},
		Future: {
			yo: "habré perseverado",
			tú: "habrás perseverado",
			Ud: "habrá perseverado",
			nosotros: "habremos perseverado",
			vosotros: "habréis perseverado",
			Uds: "habrán perseverado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya perseverado",
			tú: "hayas perseverado",
			Ud: "haya perseverado",
			nosotros: "hayamos perseverado",
			vosotros: "hayáis perseverado",
			Uds: "hayan perseverado",
		},
		Past: {
			yo: "hubiera perseverado",
			tú: "hubieras perseverado",
			Ud: "hubiera perseverado",
			nosotros: "hubiéramos perseverado",
			vosotros: "hubierais perseverado",
			Uds: "hubieran perseverado",
		},
		Future: {
			yo: "hubiere perseverado",
			tú: "hubieres perseverado",
			Ud: "hubiere perseverado",
			nosotros: "hubiéremos perseverado",
			vosotros: "hubiereis perseverado",
			Uds: "hubieren perseverado",
		},
	},
}
