var pestañear = {
	Indicative: {
		Present: {
			yo: "pestañeo",
			tú: "pestañeas",
			Ud: "pestañea",
			nosotros: "pestañeamos",
			vosotros: "pestañeáis",
			Uds: "pestañean",
		},
		Preterite: {
			yo: "pestañeé",
			tú: "pestañeaste",
			Ud: "pestañeó",
			nosotros: "pestañeamos",
			vosotros: "pestañeasteis",
			Uds: "pestañearon",
		},
		Imperfect: {
			yo: "pestañeaba",
			tú: "pestañeabas",
			Ud: "pestañeaba",
			nosotros: "pestañeábamos",
			vosotros: "pestañeabais",
			Uds: "pestañeaban",
		},
		Conditional: {
			yo: "pestañearía",
			tú: "pestañearías",
			Ud: "pestañearía",
			nosotros: "pestañearíamos",
			vosotros: "pestañearíais",
			Uds: "pestañearían",
		},
		Future: {
			yo: "pestañearé",
			tú: "pestañearás",
			Ud: "pestañeará",
			nosotros: "pestañearemos",
			vosotros: "pestañearéis",
			Uds: "pestañearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "pestañee",
			tú: "pestañees",
			Ud: "pestañee",
			nosotros: "pestañeemos",
			vosotros: "pestañeéis",
			Uds: "pestañeen",
		},
		Imperfect: {
			yo: "pestañeara",
			tú: "pestañearas",
			Ud: "pestañeara",
			nosotros: "pestañeáramos",
			vosotros: "pestañearais",
			Uds: "pestañearan",
		},
		Imperfect2: {
			yo: "pestañease",
			tú: "pestañeases",
			Ud: "pestañease",
			nosotros: "pestañeásemos",
			vosotros: "pestañeaseis",
			Uds: "pestañeasen",
		},
		Future: {
			yo: "pestañeare",
			tú: "pestañeares",
			Ud: "pestañeare",
			nosotros: "pestañeáremos",
			vosotros: "pestañeareis",
			Uds: "pestañearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "pestañea",
			Ud: "pestañee",
			nosotros: "pestañeemos",
			vosotros: "pestañead",
			Uds: "pestañeen",
		},
		Negative: {
			tú: "no pestañees",
			Ud: "no pestañee",
			nosotros: "no pestañeemos",
			vosotros: "no pestañeéis",
			Uds: "no pestañeen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy pestañeando",
			tú: "estás pestañeando",
			Ud: "está pestañeando",
			nosotros: "estamos pestañeando",
			vosotros: "estáis pestañeando",
			Uds: "están pestañeando",
		},
		Preterite: {
			yo: "estuve pestañeando",
			tú: "estuviste pestañeando",
			Ud: "estuvo pestañeando",
			nosotros: "estuvimos pestañeando",
			vosotros: "estuvisteis pestañeando",
			Uds: "estuvieron pestañeando",
		},
		Imperfect: {
			Uds: "estaban pestañeando",
			yo: "estaba pestañeando",
			tú: "estabas pestañeando",
			Ud: "estaba pestañeando",
			nosotros: "estábamos pestañeando",
			vosotros: "estabais pestañeando",
		},
		Conditional: {
			yo: "estaría pestañeando",
			tú: "estarías pestañeando",
			Ud: "estaría pestañeando",
			nosotros: "estaríamos pestañeando",
			vosotros: "estaríais pestañeando",
			Uds: "estarían pestañeando",
		},
		Future: {
			yo: "estaré pestañeando",
			tú: "estarás pestañeando",
			Ud: "estará pestañeando",
			nosotros: "estaremos pestañeando",
			vosotros: "estaréis pestañeando",
			Uds: "estarán pestañeando",
		},
	},
	Perfect: {
		Present: {
			yo: "he pestañeado",
			tú: "has pestañeado",
			Ud: "ha pestañeado",
			nosotros: "hemos pestañeado",
			vosotros: "habéis pestañeado",
			Uds: "han pestañeado",
		},
		Preterite: {
			yo: "hube pestañeado",
			tú: "hubiste pestañeado",
			Ud: "hubo pestañeado",
			nosotros: "hubimos pestañeado",
			vosotros: "hubisteis pestañeado",
			Uds: "hubieron pestañeado",
		},
		Past: {
			yo: "había pestañeado",
			tú: "habías pestañeado",
			Ud: "había pestañeado",
			nosotros: "habíamos pestañeado",
			vosotros: "habíais pestañeado",
			Uds: "habían pestañeado",
		},
		Conditional: {
			yo: "habría pestañeado",
			tú: "habrías pestañeado",
			Ud: "habría pestañeado",
			nosotros: "habríamos pestañeado",
			vosotros: "habríais pestañeado",
			Uds: "habrían pestañeado",
		},
		Future: {
			yo: "habré pestañeado",
			tú: "habrás pestañeado",
			Ud: "habrá pestañeado",
			nosotros: "habremos pestañeado",
			vosotros: "habréis pestañeado",
			Uds: "habrán pestañeado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya pestañeado",
			tú: "hayas pestañeado",
			Ud: "haya pestañeado",
			nosotros: "hayamos pestañeado",
			vosotros: "hayáis pestañeado",
			Uds: "hayan pestañeado",
		},
		Past: {
			yo: "hubiera pestañeado",
			tú: "hubieras pestañeado",
			Ud: "hubiera pestañeado",
			nosotros: "hubiéramos pestañeado",
			vosotros: "hubierais pestañeado",
			Uds: "hubieran pestañeado",
		},
		Future: {
			yo: "hubiere pestañeado",
			tú: "hubieres pestañeado",
			Ud: "hubiere pestañeado",
			nosotros: "hubiéremos pestañeado",
			vosotros: "hubiereis pestañeado",
			Uds: "hubieren pestañeado",
		},
	},
}
