var picotear = {
	Indicative: {
		Present: {
			yo: "picoteo",
			tú: "picoteas",
			Ud: "picotea",
			nosotros: "picoteamos",
			vosotros: "picoteáis",
			Uds: "picotean",
		},
		Preterite: {
			yo: "picoteé",
			tú: "picoteaste",
			Ud: "picoteó",
			nosotros: "picoteamos",
			vosotros: "picoteasteis",
			Uds: "picotearon",
		},
		Imperfect: {
			yo: "picoteaba",
			tú: "picoteabas",
			Ud: "picoteaba",
			nosotros: "picoteábamos",
			vosotros: "picoteabais",
			Uds: "picoteaban",
		},
		Conditional: {
			yo: "picotearía",
			tú: "picotearías",
			Ud: "picotearía",
			nosotros: "picotearíamos",
			vosotros: "picotearíais",
			Uds: "picotearían",
		},
		Future: {
			yo: "picotearé",
			tú: "picotearás",
			Ud: "picoteará",
			nosotros: "picotearemos",
			vosotros: "picotearéis",
			Uds: "picotearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "picotee",
			tú: "picotees",
			Ud: "picotee",
			nosotros: "picoteemos",
			vosotros: "picoteéis",
			Uds: "picoteen",
		},
		Imperfect: {
			yo: "picoteara",
			tú: "picotearas",
			Ud: "picoteara",
			nosotros: "picoteáramos",
			vosotros: "picotearais",
			Uds: "picotearan",
		},
		Imperfect2: {
			yo: "picotease",
			tú: "picoteases",
			Ud: "picotease",
			nosotros: "picoteásemos",
			vosotros: "picoteaseis",
			Uds: "picoteasen",
		},
		Future: {
			yo: "picoteare",
			tú: "picoteares",
			Ud: "picoteare",
			nosotros: "picoteáremos",
			vosotros: "picoteareis",
			Uds: "picotearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "picotea",
			Ud: "picotee",
			nosotros: "picoteemos",
			vosotros: "picotead",
			Uds: "picoteen",
		},
		Negative: {
			tú: "no picotees",
			Ud: "no picotee",
			nosotros: "no picoteemos",
			vosotros: "no picoteéis",
			Uds: "no picoteen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy picoteando",
			tú: "estás picoteando",
			Ud: "está picoteando",
			nosotros: "estamos picoteando",
			vosotros: "estáis picoteando",
			Uds: "están picoteando",
		},
		Preterite: {
			yo: "estuve picoteando",
			tú: "estuviste picoteando",
			Ud: "estuvo picoteando",
			nosotros: "estuvimos picoteando",
			vosotros: "estuvisteis picoteando",
			Uds: "estuvieron picoteando",
		},
		Imperfect: {
			Uds: "estaban picoteando",
			yo: "estaba picoteando",
			tú: "estabas picoteando",
			Ud: "estaba picoteando",
			nosotros: "estábamos picoteando",
			vosotros: "estabais picoteando",
		},
		Conditional: {
			yo: "estaría picoteando",
			tú: "estarías picoteando",
			Ud: "estaría picoteando",
			nosotros: "estaríamos picoteando",
			vosotros: "estaríais picoteando",
			Uds: "estarían picoteando",
		},
		Future: {
			yo: "estaré picoteando",
			tú: "estarás picoteando",
			Ud: "estará picoteando",
			nosotros: "estaremos picoteando",
			vosotros: "estaréis picoteando",
			Uds: "estarán picoteando",
		},
	},
	Perfect: {
		Present: {
			yo: "he picoteado",
			tú: "has picoteado",
			Ud: "ha picoteado",
			nosotros: "hemos picoteado",
			vosotros: "habéis picoteado",
			Uds: "han picoteado",
		},
		Preterite: {
			yo: "hube picoteado",
			tú: "hubiste picoteado",
			Ud: "hubo picoteado",
			nosotros: "hubimos picoteado",
			vosotros: "hubisteis picoteado",
			Uds: "hubieron picoteado",
		},
		Past: {
			yo: "había picoteado",
			tú: "habías picoteado",
			Ud: "había picoteado",
			nosotros: "habíamos picoteado",
			vosotros: "habíais picoteado",
			Uds: "habían picoteado",
		},
		Conditional: {
			yo: "habría picoteado",
			tú: "habrías picoteado",
			Ud: "habría picoteado",
			nosotros: "habríamos picoteado",
			vosotros: "habríais picoteado",
			Uds: "habrían picoteado",
		},
		Future: {
			yo: "habré picoteado",
			tú: "habrás picoteado",
			Ud: "habrá picoteado",
			nosotros: "habremos picoteado",
			vosotros: "habréis picoteado",
			Uds: "habrán picoteado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya picoteado",
			tú: "hayas picoteado",
			Ud: "haya picoteado",
			nosotros: "hayamos picoteado",
			vosotros: "hayáis picoteado",
			Uds: "hayan picoteado",
		},
		Past: {
			yo: "hubiera picoteado",
			tú: "hubieras picoteado",
			Ud: "hubiera picoteado",
			nosotros: "hubiéramos picoteado",
			vosotros: "hubierais picoteado",
			Uds: "hubieran picoteado",
		},
		Future: {
			yo: "hubiere picoteado",
			tú: "hubieres picoteado",
			Ud: "hubiere picoteado",
			nosotros: "hubiéremos picoteado",
			vosotros: "hubiereis picoteado",
			Uds: "hubieren picoteado",
		},
	},
}
