var pillar = {
	Indicative: {
		Present: {
			yo: "pillo",
			tú: "pillas",
			Ud: "pilla",
			nosotros: "pillamos",
			vosotros: "pilláis",
			Uds: "pillan",
		},
		Preterite: {
			yo: "pillé",
			tú: "pillaste",
			Ud: "pilló",
			nosotros: "pillamos",
			vosotros: "pillasteis",
			Uds: "pillaron",
		},
		Imperfect: {
			yo: "pillaba",
			tú: "pillabas",
			Ud: "pillaba",
			nosotros: "pillábamos",
			vosotros: "pillabais",
			Uds: "pillaban",
		},
		Conditional: {
			yo: "pillaría",
			tú: "pillarías",
			Ud: "pillaría",
			nosotros: "pillaríamos",
			vosotros: "pillaríais",
			Uds: "pillarían",
		},
		Future: {
			yo: "pillaré",
			tú: "pillarás",
			Ud: "pillará",
			nosotros: "pillaremos",
			vosotros: "pillaréis",
			Uds: "pillarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "pille",
			tú: "pilles",
			Ud: "pille",
			nosotros: "pillemos",
			vosotros: "pilléis",
			Uds: "pillen",
		},
		Imperfect: {
			yo: "pillara",
			tú: "pillaras",
			Ud: "pillara",
			nosotros: "pilláramos",
			vosotros: "pillarais",
			Uds: "pillaran",
		},
		Imperfect2: {
			yo: "pillase",
			tú: "pillases",
			Ud: "pillase",
			nosotros: "pillásemos",
			vosotros: "pillaseis",
			Uds: "pillasen",
		},
		Future: {
			yo: "pillare",
			tú: "pillares",
			Ud: "pillare",
			nosotros: "pilláremos",
			vosotros: "pillareis",
			Uds: "pillaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "pilla",
			Ud: "pille",
			nosotros: "pillemos",
			vosotros: "pillad",
			Uds: "pillen",
		},
		Negative: {
			tú: "no pilles",
			Ud: "no pille",
			nosotros: "no pillemos",
			vosotros: "no pilléis",
			Uds: "no pillen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy pillando",
			tú: "estás pillando",
			Ud: "está pillando",
			nosotros: "estamos pillando",
			vosotros: "estáis pillando",
			Uds: "están pillando",
		},
		Preterite: {
			yo: "estuve pillando",
			tú: "estuviste pillando",
			Ud: "estuvo pillando",
			nosotros: "estuvimos pillando",
			vosotros: "estuvisteis pillando",
			Uds: "estuvieron pillando",
		},
		Imperfect: {
			Uds: "estaban pillando",
			yo: "estaba pillando",
			tú: "estabas pillando",
			Ud: "estaba pillando",
			nosotros: "estábamos pillando",
			vosotros: "estabais pillando",
		},
		Conditional: {
			yo: "estaría pillando",
			tú: "estarías pillando",
			Ud: "estaría pillando",
			nosotros: "estaríamos pillando",
			vosotros: "estaríais pillando",
			Uds: "estarían pillando",
		},
		Future: {
			yo: "estaré pillando",
			tú: "estarás pillando",
			Ud: "estará pillando",
			nosotros: "estaremos pillando",
			vosotros: "estaréis pillando",
			Uds: "estarán pillando",
		},
	},
	Perfect: {
		Present: {
			yo: "he pillado",
			tú: "has pillado",
			Ud: "ha pillado",
			nosotros: "hemos pillado",
			vosotros: "habéis pillado",
			Uds: "han pillado",
		},
		Preterite: {
			yo: "hube pillado",
			tú: "hubiste pillado",
			Ud: "hubo pillado",
			nosotros: "hubimos pillado",
			vosotros: "hubisteis pillado",
			Uds: "hubieron pillado",
		},
		Past: {
			yo: "había pillado",
			tú: "habías pillado",
			Ud: "había pillado",
			nosotros: "habíamos pillado",
			vosotros: "habíais pillado",
			Uds: "habían pillado",
		},
		Conditional: {
			yo: "habría pillado",
			tú: "habrías pillado",
			Ud: "habría pillado",
			nosotros: "habríamos pillado",
			vosotros: "habríais pillado",
			Uds: "habrían pillado",
		},
		Future: {
			yo: "habré pillado",
			tú: "habrás pillado",
			Ud: "habrá pillado",
			nosotros: "habremos pillado",
			vosotros: "habréis pillado",
			Uds: "habrán pillado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya pillado",
			tú: "hayas pillado",
			Ud: "haya pillado",
			nosotros: "hayamos pillado",
			vosotros: "hayáis pillado",
			Uds: "hayan pillado",
		},
		Past: {
			yo: "hubiera pillado",
			tú: "hubieras pillado",
			Ud: "hubiera pillado",
			nosotros: "hubiéramos pillado",
			vosotros: "hubierais pillado",
			Uds: "hubieran pillado",
		},
		Future: {
			yo: "hubiere pillado",
			tú: "hubieres pillado",
			Ud: "hubiere pillado",
			nosotros: "hubiéremos pillado",
			vosotros: "hubiereis pillado",
			Uds: "hubieren pillado",
		},
	},
}
