var pilotear = {
	Indicative: {
		Present: {
			yo: "piloteo",
			tú: "piloteas",
			Ud: "pilotea",
			nosotros: "piloteamos",
			vosotros: "piloteáis",
			Uds: "pilotean",
		},
		Preterite: {
			yo: "piloteé",
			tú: "piloteaste",
			Ud: "piloteó",
			nosotros: "piloteamos",
			vosotros: "piloteasteis",
			Uds: "pilotearon",
		},
		Imperfect: {
			yo: "piloteaba",
			tú: "piloteabas",
			Ud: "piloteaba",
			nosotros: "piloteábamos",
			vosotros: "piloteabais",
			Uds: "piloteaban",
		},
		Conditional: {
			yo: "pilotearía",
			tú: "pilotearías",
			Ud: "pilotearía",
			nosotros: "pilotearíamos",
			vosotros: "pilotearíais",
			Uds: "pilotearían",
		},
		Future: {
			yo: "pilotearé",
			tú: "pilotearás",
			Ud: "piloteará",
			nosotros: "pilotearemos",
			vosotros: "pilotearéis",
			Uds: "pilotearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "pilotee",
			tú: "pilotees",
			Ud: "pilotee",
			nosotros: "piloteemos",
			vosotros: "piloteéis",
			Uds: "piloteen",
		},
		Imperfect: {
			yo: "piloteara",
			tú: "pilotearas",
			Ud: "piloteara",
			nosotros: "piloteáramos",
			vosotros: "pilotearais",
			Uds: "pilotearan",
		},
		Imperfect2: {
			yo: "pilotease",
			tú: "piloteases",
			Ud: "pilotease",
			nosotros: "piloteásemos",
			vosotros: "piloteaseis",
			Uds: "piloteasen",
		},
		Future: {
			yo: "piloteare",
			tú: "piloteares",
			Ud: "piloteare",
			nosotros: "piloteáremos",
			vosotros: "piloteareis",
			Uds: "pilotearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "pilotea",
			Ud: "pilotee",
			nosotros: "piloteemos",
			vosotros: "pilotead",
			Uds: "piloteen",
		},
		Negative: {
			tú: "no pilotees",
			Ud: "no pilotee",
			nosotros: "no piloteemos",
			vosotros: "no piloteéis",
			Uds: "no piloteen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy piloteando",
			tú: "estás piloteando",
			Ud: "está piloteando",
			nosotros: "estamos piloteando",
			vosotros: "estáis piloteando",
			Uds: "están piloteando",
		},
		Preterite: {
			yo: "estuve piloteando",
			tú: "estuviste piloteando",
			Ud: "estuvo piloteando",
			nosotros: "estuvimos piloteando",
			vosotros: "estuvisteis piloteando",
			Uds: "estuvieron piloteando",
		},
		Imperfect: {
			Uds: "estaban piloteando",
			yo: "estaba piloteando",
			tú: "estabas piloteando",
			Ud: "estaba piloteando",
			nosotros: "estábamos piloteando",
			vosotros: "estabais piloteando",
		},
		Conditional: {
			yo: "estaría piloteando",
			tú: "estarías piloteando",
			Ud: "estaría piloteando",
			nosotros: "estaríamos piloteando",
			vosotros: "estaríais piloteando",
			Uds: "estarían piloteando",
		},
		Future: {
			yo: "estaré piloteando",
			tú: "estarás piloteando",
			Ud: "estará piloteando",
			nosotros: "estaremos piloteando",
			vosotros: "estaréis piloteando",
			Uds: "estarán piloteando",
		},
	},
	Perfect: {
		Present: {
			yo: "he piloteado",
			tú: "has piloteado",
			Ud: "ha piloteado",
			nosotros: "hemos piloteado",
			vosotros: "habéis piloteado",
			Uds: "han piloteado",
		},
		Preterite: {
			yo: "hube piloteado",
			tú: "hubiste piloteado",
			Ud: "hubo piloteado",
			nosotros: "hubimos piloteado",
			vosotros: "hubisteis piloteado",
			Uds: "hubieron piloteado",
		},
		Past: {
			yo: "había piloteado",
			tú: "habías piloteado",
			Ud: "había piloteado",
			nosotros: "habíamos piloteado",
			vosotros: "habíais piloteado",
			Uds: "habían piloteado",
		},
		Conditional: {
			yo: "habría piloteado",
			tú: "habrías piloteado",
			Ud: "habría piloteado",
			nosotros: "habríamos piloteado",
			vosotros: "habríais piloteado",
			Uds: "habrían piloteado",
		},
		Future: {
			yo: "habré piloteado",
			tú: "habrás piloteado",
			Ud: "habrá piloteado",
			nosotros: "habremos piloteado",
			vosotros: "habréis piloteado",
			Uds: "habrán piloteado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya piloteado",
			tú: "hayas piloteado",
			Ud: "haya piloteado",
			nosotros: "hayamos piloteado",
			vosotros: "hayáis piloteado",
			Uds: "hayan piloteado",
		},
		Past: {
			yo: "hubiera piloteado",
			tú: "hubieras piloteado",
			Ud: "hubiera piloteado",
			nosotros: "hubiéramos piloteado",
			vosotros: "hubierais piloteado",
			Uds: "hubieran piloteado",
		},
		Future: {
			yo: "hubiere piloteado",
			tú: "hubieres piloteado",
			Ud: "hubiere piloteado",
			nosotros: "hubiéremos piloteado",
			vosotros: "hubiereis piloteado",
			Uds: "hubieren piloteado",
		},
	},
}
