var piratear = {
	Indicative: {
		Present: {
			yo: "pirateo",
			tú: "pirateas",
			Ud: "piratea",
			nosotros: "pirateamos",
			vosotros: "pirateáis",
			Uds: "piratean",
		},
		Preterite: {
			yo: "pirateé",
			tú: "pirateaste",
			Ud: "pirateó",
			nosotros: "pirateamos",
			vosotros: "pirateasteis",
			Uds: "piratearon",
		},
		Imperfect: {
			yo: "pirateaba",
			tú: "pirateabas",
			Ud: "pirateaba",
			nosotros: "pirateábamos",
			vosotros: "pirateabais",
			Uds: "pirateaban",
		},
		Conditional: {
			yo: "piratearía",
			tú: "piratearías",
			Ud: "piratearía",
			nosotros: "piratearíamos",
			vosotros: "piratearíais",
			Uds: "piratearían",
		},
		Future: {
			yo: "piratearé",
			tú: "piratearás",
			Ud: "pirateará",
			nosotros: "piratearemos",
			vosotros: "piratearéis",
			Uds: "piratearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "piratee",
			tú: "piratees",
			Ud: "piratee",
			nosotros: "pirateemos",
			vosotros: "pirateéis",
			Uds: "pirateen",
		},
		Imperfect: {
			yo: "pirateara",
			tú: "piratearas",
			Ud: "pirateara",
			nosotros: "pirateáramos",
			vosotros: "piratearais",
			Uds: "piratearan",
		},
		Imperfect2: {
			yo: "piratease",
			tú: "pirateases",
			Ud: "piratease",
			nosotros: "pirateásemos",
			vosotros: "pirateaseis",
			Uds: "pirateasen",
		},
		Future: {
			yo: "pirateare",
			tú: "pirateares",
			Ud: "pirateare",
			nosotros: "pirateáremos",
			vosotros: "pirateareis",
			Uds: "piratearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "piratea",
			Ud: "piratee",
			nosotros: "pirateemos",
			vosotros: "piratead",
			Uds: "pirateen",
		},
		Negative: {
			tú: "no piratees",
			Ud: "no piratee",
			nosotros: "no pirateemos",
			vosotros: "no pirateéis",
			Uds: "no pirateen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy pirateando",
			tú: "estás pirateando",
			Ud: "está pirateando",
			nosotros: "estamos pirateando",
			vosotros: "estáis pirateando",
			Uds: "están pirateando",
		},
		Preterite: {
			yo: "estuve pirateando",
			tú: "estuviste pirateando",
			Ud: "estuvo pirateando",
			nosotros: "estuvimos pirateando",
			vosotros: "estuvisteis pirateando",
			Uds: "estuvieron pirateando",
		},
		Imperfect: {
			Uds: "estaban pirateando",
			yo: "estaba pirateando",
			tú: "estabas pirateando",
			Ud: "estaba pirateando",
			nosotros: "estábamos pirateando",
			vosotros: "estabais pirateando",
		},
		Conditional: {
			yo: "estaría pirateando",
			tú: "estarías pirateando",
			Ud: "estaría pirateando",
			nosotros: "estaríamos pirateando",
			vosotros: "estaríais pirateando",
			Uds: "estarían pirateando",
		},
		Future: {
			yo: "estaré pirateando",
			tú: "estarás pirateando",
			Ud: "estará pirateando",
			nosotros: "estaremos pirateando",
			vosotros: "estaréis pirateando",
			Uds: "estarán pirateando",
		},
	},
	Perfect: {
		Present: {
			yo: "he pirateado",
			tú: "has pirateado",
			Ud: "ha pirateado",
			nosotros: "hemos pirateado",
			vosotros: "habéis pirateado",
			Uds: "han pirateado",
		},
		Preterite: {
			yo: "hube pirateado",
			tú: "hubiste pirateado",
			Ud: "hubo pirateado",
			nosotros: "hubimos pirateado",
			vosotros: "hubisteis pirateado",
			Uds: "hubieron pirateado",
		},
		Past: {
			yo: "había pirateado",
			tú: "habías pirateado",
			Ud: "había pirateado",
			nosotros: "habíamos pirateado",
			vosotros: "habíais pirateado",
			Uds: "habían pirateado",
		},
		Conditional: {
			yo: "habría pirateado",
			tú: "habrías pirateado",
			Ud: "habría pirateado",
			nosotros: "habríamos pirateado",
			vosotros: "habríais pirateado",
			Uds: "habrían pirateado",
		},
		Future: {
			yo: "habré pirateado",
			tú: "habrás pirateado",
			Ud: "habrá pirateado",
			nosotros: "habremos pirateado",
			vosotros: "habréis pirateado",
			Uds: "habrán pirateado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya pirateado",
			tú: "hayas pirateado",
			Ud: "haya pirateado",
			nosotros: "hayamos pirateado",
			vosotros: "hayáis pirateado",
			Uds: "hayan pirateado",
		},
		Past: {
			yo: "hubiera pirateado",
			tú: "hubieras pirateado",
			Ud: "hubiera pirateado",
			nosotros: "hubiéramos pirateado",
			vosotros: "hubierais pirateado",
			Uds: "hubieran pirateado",
		},
		Future: {
			yo: "hubiere pirateado",
			tú: "hubieres pirateado",
			Ud: "hubiere pirateado",
			nosotros: "hubiéremos pirateado",
			vosotros: "hubiereis pirateado",
			Uds: "hubieren pirateado",
		},
	},
}
