var pisotear = {
	Indicative: {
		Present: {
			yo: "pisoteo",
			tú: "pisoteas",
			Ud: "pisotea",
			nosotros: "pisoteamos",
			vosotros: "pisoteáis",
			Uds: "pisotean",
		},
		Preterite: {
			yo: "pisoteé",
			tú: "pisoteaste",
			Ud: "pisoteó",
			nosotros: "pisoteamos",
			vosotros: "pisoteasteis",
			Uds: "pisotearon",
		},
		Imperfect: {
			yo: "pisoteaba",
			tú: "pisoteabas",
			Ud: "pisoteaba",
			nosotros: "pisoteábamos",
			vosotros: "pisoteabais",
			Uds: "pisoteaban",
		},
		Conditional: {
			yo: "pisotearía",
			tú: "pisotearías",
			Ud: "pisotearía",
			nosotros: "pisotearíamos",
			vosotros: "pisotearíais",
			Uds: "pisotearían",
		},
		Future: {
			yo: "pisotearé",
			tú: "pisotearás",
			Ud: "pisoteará",
			nosotros: "pisotearemos",
			vosotros: "pisotearéis",
			Uds: "pisotearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "pisotee",
			tú: "pisotees",
			Ud: "pisotee",
			nosotros: "pisoteemos",
			vosotros: "pisoteéis",
			Uds: "pisoteen",
		},
		Imperfect: {
			yo: "pisoteara",
			tú: "pisotearas",
			Ud: "pisoteara",
			nosotros: "pisoteáramos",
			vosotros: "pisotearais",
			Uds: "pisotearan",
		},
		Imperfect2: {
			yo: "pisotease",
			tú: "pisoteases",
			Ud: "pisotease",
			nosotros: "pisoteásemos",
			vosotros: "pisoteaseis",
			Uds: "pisoteasen",
		},
		Future: {
			yo: "pisoteare",
			tú: "pisoteares",
			Ud: "pisoteare",
			nosotros: "pisoteáremos",
			vosotros: "pisoteareis",
			Uds: "pisotearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "pisotea",
			Ud: "pisotee",
			nosotros: "pisoteemos",
			vosotros: "pisotead",
			Uds: "pisoteen",
		},
		Negative: {
			tú: "no pisotees",
			Ud: "no pisotee",
			nosotros: "no pisoteemos",
			vosotros: "no pisoteéis",
			Uds: "no pisoteen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy pisoteando",
			tú: "estás pisoteando",
			Ud: "está pisoteando",
			nosotros: "estamos pisoteando",
			vosotros: "estáis pisoteando",
			Uds: "están pisoteando",
		},
		Preterite: {
			yo: "estuve pisoteando",
			tú: "estuviste pisoteando",
			Ud: "estuvo pisoteando",
			nosotros: "estuvimos pisoteando",
			vosotros: "estuvisteis pisoteando",
			Uds: "estuvieron pisoteando",
		},
		Imperfect: {
			Uds: "estaban pisoteando",
			yo: "estaba pisoteando",
			tú: "estabas pisoteando",
			Ud: "estaba pisoteando",
			nosotros: "estábamos pisoteando",
			vosotros: "estabais pisoteando",
		},
		Conditional: {
			yo: "estaría pisoteando",
			tú: "estarías pisoteando",
			Ud: "estaría pisoteando",
			nosotros: "estaríamos pisoteando",
			vosotros: "estaríais pisoteando",
			Uds: "estarían pisoteando",
		},
		Future: {
			yo: "estaré pisoteando",
			tú: "estarás pisoteando",
			Ud: "estará pisoteando",
			nosotros: "estaremos pisoteando",
			vosotros: "estaréis pisoteando",
			Uds: "estarán pisoteando",
		},
	},
	Perfect: {
		Present: {
			yo: "he pisoteado",
			tú: "has pisoteado",
			Ud: "ha pisoteado",
			nosotros: "hemos pisoteado",
			vosotros: "habéis pisoteado",
			Uds: "han pisoteado",
		},
		Preterite: {
			yo: "hube pisoteado",
			tú: "hubiste pisoteado",
			Ud: "hubo pisoteado",
			nosotros: "hubimos pisoteado",
			vosotros: "hubisteis pisoteado",
			Uds: "hubieron pisoteado",
		},
		Past: {
			yo: "había pisoteado",
			tú: "habías pisoteado",
			Ud: "había pisoteado",
			nosotros: "habíamos pisoteado",
			vosotros: "habíais pisoteado",
			Uds: "habían pisoteado",
		},
		Conditional: {
			yo: "habría pisoteado",
			tú: "habrías pisoteado",
			Ud: "habría pisoteado",
			nosotros: "habríamos pisoteado",
			vosotros: "habríais pisoteado",
			Uds: "habrían pisoteado",
		},
		Future: {
			yo: "habré pisoteado",
			tú: "habrás pisoteado",
			Ud: "habrá pisoteado",
			nosotros: "habremos pisoteado",
			vosotros: "habréis pisoteado",
			Uds: "habrán pisoteado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya pisoteado",
			tú: "hayas pisoteado",
			Ud: "haya pisoteado",
			nosotros: "hayamos pisoteado",
			vosotros: "hayáis pisoteado",
			Uds: "hayan pisoteado",
		},
		Past: {
			yo: "hubiera pisoteado",
			tú: "hubieras pisoteado",
			Ud: "hubiera pisoteado",
			nosotros: "hubiéramos pisoteado",
			vosotros: "hubierais pisoteado",
			Uds: "hubieran pisoteado",
		},
		Future: {
			yo: "hubiere pisoteado",
			tú: "hubieres pisoteado",
			Ud: "hubiere pisoteado",
			nosotros: "hubiéremos pisoteado",
			vosotros: "hubiereis pisoteado",
			Uds: "hubieren pisoteado",
		},
	},
}
