var plagar = {
	Indicative: {
		Present: {
			yo: "plago",
			tú: "plagas",
			Ud: "plaga",
			nosotros: "plagamos",
			vosotros: "plagáis",
			Uds: "plagan",
		},
		Preterite: {
			yo: "plagué",
			tú: "plagaste",
			Ud: "plagó",
			nosotros: "plagamos",
			vosotros: "plagasteis",
			Uds: "plagaron",
		},
		Imperfect: {
			yo: "plagaba",
			tú: "plagabas",
			Ud: "plagaba",
			nosotros: "plagábamos",
			vosotros: "plagabais",
			Uds: "plagaban",
		},
		Conditional: {
			yo: "plagaría",
			tú: "plagarías",
			Ud: "plagaría",
			nosotros: "plagaríamos",
			vosotros: "plagaríais",
			Uds: "plagarían",
		},
		Future: {
			yo: "plagaré",
			tú: "plagarás",
			Ud: "plagará",
			nosotros: "plagaremos",
			vosotros: "plagaréis",
			Uds: "plagarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "plague",
			tú: "plagues",
			Ud: "plague",
			nosotros: "plaguemos",
			vosotros: "plaguéis",
			Uds: "plaguen",
		},
		Imperfect: {
			yo: "plagara",
			tú: "plagaras",
			Ud: "plagara",
			nosotros: "plagáramos",
			vosotros: "plagarais",
			Uds: "plagaran",
		},
		Imperfect2: {
			yo: "plagase",
			tú: "plagases",
			Ud: "plagase",
			nosotros: "plagásemos",
			vosotros: "plagaseis",
			Uds: "plagasen",
		},
		Future: {
			yo: "plagare",
			tú: "plagares",
			Ud: "plagare",
			nosotros: "plagáremos",
			vosotros: "plagareis",
			Uds: "plagaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "plaga",
			Ud: "plague",
			nosotros: "plaguemos",
			vosotros: "plagad",
			Uds: "plaguen",
		},
		Negative: {
			tú: "no plagues",
			Ud: "no plague",
			nosotros: "no plaguemos",
			vosotros: "no plaguéis",
			Uds: "no plaguen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy plagando",
			tú: "estás plagando",
			Ud: "está plagando",
			nosotros: "estamos plagando",
			vosotros: "estáis plagando",
			Uds: "están plagando",
		},
		Preterite: {
			yo: "estuve plagando",
			tú: "estuviste plagando",
			Ud: "estuvo plagando",
			nosotros: "estuvimos plagando",
			vosotros: "estuvisteis plagando",
			Uds: "estuvieron plagando",
		},
		Imperfect: {
			Uds: "estaban plagando",
			yo: "estaba plagando",
			tú: "estabas plagando",
			Ud: "estaba plagando",
			nosotros: "estábamos plagando",
			vosotros: "estabais plagando",
		},
		Conditional: {
			yo: "estaría plagando",
			tú: "estarías plagando",
			Ud: "estaría plagando",
			nosotros: "estaríamos plagando",
			vosotros: "estaríais plagando",
			Uds: "estarían plagando",
		},
		Future: {
			yo: "estaré plagando",
			tú: "estarás plagando",
			Ud: "estará plagando",
			nosotros: "estaremos plagando",
			vosotros: "estaréis plagando",
			Uds: "estarán plagando",
		},
	},
	Perfect: {
		Present: {
			yo: "he plagado",
			tú: "has plagado",
			Ud: "ha plagado",
			nosotros: "hemos plagado",
			vosotros: "habéis plagado",
			Uds: "han plagado",
		},
		Preterite: {
			yo: "hube plagado",
			tú: "hubiste plagado",
			Ud: "hubo plagado",
			nosotros: "hubimos plagado",
			vosotros: "hubisteis plagado",
			Uds: "hubieron plagado",
		},
		Past: {
			yo: "había plagado",
			tú: "habías plagado",
			Ud: "había plagado",
			nosotros: "habíamos plagado",
			vosotros: "habíais plagado",
			Uds: "habían plagado",
		},
		Conditional: {
			yo: "habría plagado",
			tú: "habrías plagado",
			Ud: "habría plagado",
			nosotros: "habríamos plagado",
			vosotros: "habríais plagado",
			Uds: "habrían plagado",
		},
		Future: {
			yo: "habré plagado",
			tú: "habrás plagado",
			Ud: "habrá plagado",
			nosotros: "habremos plagado",
			vosotros: "habréis plagado",
			Uds: "habrán plagado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya plagado",
			tú: "hayas plagado",
			Ud: "haya plagado",
			nosotros: "hayamos plagado",
			vosotros: "hayáis plagado",
			Uds: "hayan plagado",
		},
		Past: {
			yo: "hubiera plagado",
			tú: "hubieras plagado",
			Ud: "hubiera plagado",
			nosotros: "hubiéramos plagado",
			vosotros: "hubierais plagado",
			Uds: "hubieran plagado",
		},
		Future: {
			yo: "hubiere plagado",
			tú: "hubieres plagado",
			Ud: "hubiere plagado",
			nosotros: "hubiéremos plagado",
			vosotros: "hubiereis plagado",
			Uds: "hubieren plagado",
		},
	},
}
