var planear = {
	Indicative: {
		Present: {
			yo: "planeo",
			tú: "planeas",
			Ud: "planea",
			nosotros: "planeamos",
			vosotros: "planeáis",
			Uds: "planean",
		},
		Preterite: {
			yo: "planeé",
			tú: "planeaste",
			Ud: "planeó",
			nosotros: "planeamos",
			vosotros: "planeasteis",
			Uds: "planearon",
		},
		Imperfect: {
			yo: "planeaba",
			tú: "planeabas",
			Ud: "planeaba",
			nosotros: "planeábamos",
			vosotros: "planeabais",
			Uds: "planeaban",
		},
		Conditional: {
			yo: "planearía",
			tú: "planearías",
			Ud: "planearía",
			nosotros: "planearíamos",
			vosotros: "planearíais",
			Uds: "planearían",
		},
		Future: {
			yo: "planearé",
			tú: "planearás",
			Ud: "planeará",
			nosotros: "planearemos",
			vosotros: "planearéis",
			Uds: "planearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "planee",
			tú: "planees",
			Ud: "planee",
			nosotros: "planeemos",
			vosotros: "planeéis",
			Uds: "planeen",
		},
		Imperfect: {
			yo: "planeara",
			tú: "planearas",
			Ud: "planeara",
			nosotros: "planeáramos",
			vosotros: "planearais",
			Uds: "planearan",
		},
		Imperfect2: {
			yo: "planease",
			tú: "planeases",
			Ud: "planease",
			nosotros: "planeásemos",
			vosotros: "planeaseis",
			Uds: "planeasen",
		},
		Future: {
			yo: "planeare",
			tú: "planeares",
			Ud: "planeare",
			nosotros: "planeáremos",
			vosotros: "planeareis",
			Uds: "planearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "planea",
			Ud: "planee",
			nosotros: "planeemos",
			vosotros: "planead",
			Uds: "planeen",
		},
		Negative: {
			tú: "no planees",
			Ud: "no planee",
			nosotros: "no planeemos",
			vosotros: "no planeéis",
			Uds: "no planeen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy planeando",
			tú: "estás planeando",
			Ud: "está planeando",
			nosotros: "estamos planeando",
			vosotros: "estáis planeando",
			Uds: "están planeando",
		},
		Preterite: {
			yo: "estuve planeando",
			tú: "estuviste planeando",
			Ud: "estuvo planeando",
			nosotros: "estuvimos planeando",
			vosotros: "estuvisteis planeando",
			Uds: "estuvieron planeando",
		},
		Imperfect: {
			Uds: "estaban planeando",
			yo: "estaba planeando",
			tú: "estabas planeando",
			Ud: "estaba planeando",
			nosotros: "estábamos planeando",
			vosotros: "estabais planeando",
		},
		Conditional: {
			yo: "estaría planeando",
			tú: "estarías planeando",
			Ud: "estaría planeando",
			nosotros: "estaríamos planeando",
			vosotros: "estaríais planeando",
			Uds: "estarían planeando",
		},
		Future: {
			yo: "estaré planeando",
			tú: "estarás planeando",
			Ud: "estará planeando",
			nosotros: "estaremos planeando",
			vosotros: "estaréis planeando",
			Uds: "estarán planeando",
		},
	},
	Perfect: {
		Present: {
			yo: "he planeado",
			tú: "has planeado",
			Ud: "ha planeado",
			nosotros: "hemos planeado",
			vosotros: "habéis planeado",
			Uds: "han planeado",
		},
		Preterite: {
			yo: "hube planeado",
			tú: "hubiste planeado",
			Ud: "hubo planeado",
			nosotros: "hubimos planeado",
			vosotros: "hubisteis planeado",
			Uds: "hubieron planeado",
		},
		Past: {
			yo: "había planeado",
			tú: "habías planeado",
			Ud: "había planeado",
			nosotros: "habíamos planeado",
			vosotros: "habíais planeado",
			Uds: "habían planeado",
		},
		Conditional: {
			yo: "habría planeado",
			tú: "habrías planeado",
			Ud: "habría planeado",
			nosotros: "habríamos planeado",
			vosotros: "habríais planeado",
			Uds: "habrían planeado",
		},
		Future: {
			yo: "habré planeado",
			tú: "habrás planeado",
			Ud: "habrá planeado",
			nosotros: "habremos planeado",
			vosotros: "habréis planeado",
			Uds: "habrán planeado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya planeado",
			tú: "hayas planeado",
			Ud: "haya planeado",
			nosotros: "hayamos planeado",
			vosotros: "hayáis planeado",
			Uds: "hayan planeado",
		},
		Past: {
			yo: "hubiera planeado",
			tú: "hubieras planeado",
			Ud: "hubiera planeado",
			nosotros: "hubiéramos planeado",
			vosotros: "hubierais planeado",
			Uds: "hubieran planeado",
		},
		Future: {
			yo: "hubiere planeado",
			tú: "hubieres planeado",
			Ud: "hubiere planeado",
			nosotros: "hubiéremos planeado",
			vosotros: "hubiereis planeado",
			Uds: "hubieren planeado",
		},
	},
}
