var plegar = {
	Indicative: {
		Present: {
			yo: "pliego",
			tú: "pliegas",
			Ud: "pliega",
			nosotros: "plegamos",
			vosotros: "plegáis",
			Uds: "pliegan",
		},
		Preterite: {
			yo: "plegué",
			tú: "plegaste",
			Ud: "plegó",
			nosotros: "plegamos",
			vosotros: "plegasteis",
			Uds: "plegaron",
		},
		Imperfect: {
			yo: "plegaba",
			tú: "plegabas",
			Ud: "plegaba",
			nosotros: "plegábamos",
			vosotros: "plegabais",
			Uds: "plegaban",
		},
		Conditional: {
			yo: "plegaría",
			tú: "plegarías",
			Ud: "plegaría",
			nosotros: "plegaríamos",
			vosotros: "plegaríais",
			Uds: "plegarían",
		},
		Future: {
			yo: "plegaré",
			tú: "plegarás",
			Ud: "plegará",
			nosotros: "plegaremos",
			vosotros: "plegaréis",
			Uds: "plegarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "pliegue",
			tú: "pliegues",
			Ud: "pliegue",
			nosotros: "pleguemos",
			vosotros: "pleguéis",
			Uds: "plieguen",
		},
		Imperfect: {
			yo: "plegara",
			tú: "plegaras",
			Ud: "plegara",
			nosotros: "plegáramos",
			vosotros: "plegarais",
			Uds: "plegaran",
		},
		Imperfect2: {
			yo: "plegase",
			tú: "plegases",
			Ud: "plegase",
			nosotros: "plegásemos",
			vosotros: "plegaseis",
			Uds: "plegasen",
		},
		Future: {
			yo: "plegare",
			tú: "plegares",
			Ud: "plegare",
			nosotros: "plegáremos",
			vosotros: "plegareis",
			Uds: "plegaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "pliega",
			Ud: "pliegue",
			nosotros: "pleguemos",
			vosotros: "plegad",
			Uds: "plieguen",
		},
		Negative: {
			tú: "no pliegues",
			Ud: "no pliegue",
			nosotros: "no pleguemos",
			vosotros: "no pleguéis",
			Uds: "no plieguen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy plegando",
			tú: "estás plegando",
			Ud: "está plegando",
			nosotros: "estamos plegando",
			vosotros: "estáis plegando",
			Uds: "están plegando",
		},
		Preterite: {
			yo: "estuve plegando",
			tú: "estuviste plegando",
			Ud: "estuvo plegando",
			nosotros: "estuvimos plegando",
			vosotros: "estuvisteis plegando",
			Uds: "estuvieron plegando",
		},
		Imperfect: {
			Uds: "estaban plegando",
			yo: "estaba plegando",
			tú: "estabas plegando",
			Ud: "estaba plegando",
			nosotros: "estábamos plegando",
			vosotros: "estabais plegando",
		},
		Conditional: {
			yo: "estaría plegando",
			tú: "estarías plegando",
			Ud: "estaría plegando",
			nosotros: "estaríamos plegando",
			vosotros: "estaríais plegando",
			Uds: "estarían plegando",
		},
		Future: {
			yo: "estaré plegando",
			tú: "estarás plegando",
			Ud: "estará plegando",
			nosotros: "estaremos plegando",
			vosotros: "estaréis plegando",
			Uds: "estarán plegando",
		},
	},
	Perfect: {
		Present: {
			yo: "he plegado",
			tú: "has plegado",
			Ud: "ha plegado",
			nosotros: "hemos plegado",
			vosotros: "habéis plegado",
			Uds: "han plegado",
		},
		Preterite: {
			yo: "hube plegado",
			tú: "hubiste plegado",
			Ud: "hubo plegado",
			nosotros: "hubimos plegado",
			vosotros: "hubisteis plegado",
			Uds: "hubieron plegado",
		},
		Past: {
			yo: "había plegado",
			tú: "habías plegado",
			Ud: "había plegado",
			nosotros: "habíamos plegado",
			vosotros: "habíais plegado",
			Uds: "habían plegado",
		},
		Conditional: {
			yo: "habría plegado",
			tú: "habrías plegado",
			Ud: "habría plegado",
			nosotros: "habríamos plegado",
			vosotros: "habríais plegado",
			Uds: "habrían plegado",
		},
		Future: {
			yo: "habré plegado",
			tú: "habrás plegado",
			Ud: "habrá plegado",
			nosotros: "habremos plegado",
			vosotros: "habréis plegado",
			Uds: "habrán plegado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya plegado",
			tú: "hayas plegado",
			Ud: "haya plegado",
			nosotros: "hayamos plegado",
			vosotros: "hayáis plegado",
			Uds: "hayan plegado",
		},
		Past: {
			yo: "hubiera plegado",
			tú: "hubieras plegado",
			Ud: "hubiera plegado",
			nosotros: "hubiéramos plegado",
			vosotros: "hubierais plegado",
			Uds: "hubieran plegado",
		},
		Future: {
			yo: "hubiere plegado",
			tú: "hubieres plegado",
			Ud: "hubiere plegado",
			nosotros: "hubiéremos plegado",
			vosotros: "hubiereis plegado",
			Uds: "hubieren plegado",
		},
	},
}
