var plisar = {
	Indicative: {
		Present: {
			yo: "pliso",
			tú: "plisas",
			Ud: "plisa",
			nosotros: "plisamos",
			vosotros: "plisáis",
			Uds: "plisan",
		},
		Preterite: {
			yo: "plisé",
			tú: "plisaste",
			Ud: "plisó",
			nosotros: "plisamos",
			vosotros: "plisasteis",
			Uds: "plisaron",
		},
		Imperfect: {
			yo: "plisaba",
			tú: "plisabas",
			Ud: "plisaba",
			nosotros: "plisábamos",
			vosotros: "plisabais",
			Uds: "plisaban",
		},
		Conditional: {
			yo: "plisaría",
			tú: "plisarías",
			Ud: "plisaría",
			nosotros: "plisaríamos",
			vosotros: "plisaríais",
			Uds: "plisarían",
		},
		Future: {
			yo: "plisaré",
			tú: "plisarás",
			Ud: "plisará",
			nosotros: "plisaremos",
			vosotros: "plisaréis",
			Uds: "plisarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "plise",
			tú: "plises",
			Ud: "plise",
			nosotros: "plisemos",
			vosotros: "pliséis",
			Uds: "plisen",
		},
		Imperfect: {
			yo: "plisara",
			tú: "plisaras",
			Ud: "plisara",
			nosotros: "plisáramos",
			vosotros: "plisarais",
			Uds: "plisaran",
		},
		Imperfect2: {
			yo: "plisase",
			tú: "plisases",
			Ud: "plisase",
			nosotros: "plisásemos",
			vosotros: "plisaseis",
			Uds: "plisasen",
		},
		Future: {
			yo: "plisare",
			tú: "plisares",
			Ud: "plisare",
			nosotros: "plisáremos",
			vosotros: "plisareis",
			Uds: "plisaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "plisa",
			Ud: "plise",
			nosotros: "plisemos",
			vosotros: "plisad",
			Uds: "plisen",
		},
		Negative: {
			tú: "no plises",
			Ud: "no plise",
			nosotros: "no plisemos",
			vosotros: "no pliséis",
			Uds: "no plisen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy plisando",
			tú: "estás plisando",
			Ud: "está plisando",
			nosotros: "estamos plisando",
			vosotros: "estáis plisando",
			Uds: "están plisando",
		},
		Preterite: {
			yo: "estuve plisando",
			tú: "estuviste plisando",
			Ud: "estuvo plisando",
			nosotros: "estuvimos plisando",
			vosotros: "estuvisteis plisando",
			Uds: "estuvieron plisando",
		},
		Imperfect: {
			Uds: "estaban plisando",
			yo: "estaba plisando",
			tú: "estabas plisando",
			Ud: "estaba plisando",
			nosotros: "estábamos plisando",
			vosotros: "estabais plisando",
		},
		Conditional: {
			yo: "estaría plisando",
			tú: "estarías plisando",
			Ud: "estaría plisando",
			nosotros: "estaríamos plisando",
			vosotros: "estaríais plisando",
			Uds: "estarían plisando",
		},
		Future: {
			yo: "estaré plisando",
			tú: "estarás plisando",
			Ud: "estará plisando",
			nosotros: "estaremos plisando",
			vosotros: "estaréis plisando",
			Uds: "estarán plisando",
		},
	},
	Perfect: {
		Present: {
			yo: "he plisado",
			tú: "has plisado",
			Ud: "ha plisado",
			nosotros: "hemos plisado",
			vosotros: "habéis plisado",
			Uds: "han plisado",
		},
		Preterite: {
			yo: "hube plisado",
			tú: "hubiste plisado",
			Ud: "hubo plisado",
			nosotros: "hubimos plisado",
			vosotros: "hubisteis plisado",
			Uds: "hubieron plisado",
		},
		Past: {
			yo: "había plisado",
			tú: "habías plisado",
			Ud: "había plisado",
			nosotros: "habíamos plisado",
			vosotros: "habíais plisado",
			Uds: "habían plisado",
		},
		Conditional: {
			yo: "habría plisado",
			tú: "habrías plisado",
			Ud: "habría plisado",
			nosotros: "habríamos plisado",
			vosotros: "habríais plisado",
			Uds: "habrían plisado",
		},
		Future: {
			yo: "habré plisado",
			tú: "habrás plisado",
			Ud: "habrá plisado",
			nosotros: "habremos plisado",
			vosotros: "habréis plisado",
			Uds: "habrán plisado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya plisado",
			tú: "hayas plisado",
			Ud: "haya plisado",
			nosotros: "hayamos plisado",
			vosotros: "hayáis plisado",
			Uds: "hayan plisado",
		},
		Past: {
			yo: "hubiera plisado",
			tú: "hubieras plisado",
			Ud: "hubiera plisado",
			nosotros: "hubiéramos plisado",
			vosotros: "hubierais plisado",
			Uds: "hubieran plisado",
		},
		Future: {
			yo: "hubiere plisado",
			tú: "hubieres plisado",
			Ud: "hubiere plisado",
			nosotros: "hubiéremos plisado",
			vosotros: "hubiereis plisado",
			Uds: "hubieren plisado",
		},
	},
}
