var posponer = {
	Indicative: {
		Present: {
			yo: "pospongo",
			tú: "pospones",
			Ud: "pospone",
			nosotros: "posponemos",
			vosotros: "posponéis",
			Uds: "posponen",
		},
		Preterite: {
			yo: "pospuse",
			tú: "pospusiste",
			Ud: "pospuso",
			nosotros: "pospusimos",
			vosotros: "pospusisteis",
			Uds: "pospusieron",
		},
		Imperfect: {
			yo: "posponía",
			tú: "posponías",
			Ud: "posponía",
			nosotros: "posponíamos",
			vosotros: "posponíais",
			Uds: "posponían",
		},
		Conditional: {
			yo: "pospondría",
			tú: "pospondrías",
			Ud: "pospondría",
			nosotros: "pospondríamos",
			vosotros: "pospondríais",
			Uds: "pospondrían",
		},
		Future: {
			yo: "pospondré",
			tú: "pospondrás",
			Ud: "pospondrá",
			nosotros: "pospondremos",
			vosotros: "pospondréis",
			Uds: "pospondrán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "posponga",
			tú: "pospongas",
			Ud: "posponga",
			nosotros: "pospongamos",
			vosotros: "pospongáis",
			Uds: "pospongan",
		},
		Imperfect: {
			yo: "pospusiera",
			tú: "pospusieras",
			Ud: "pospusiera",
			nosotros: "pospusiéramos",
			vosotros: "pospusierais",
			Uds: "pospusieran",
		},
		Imperfect2: {
			yo: "pospusiese",
			tú: "pospusieses",
			Ud: "pospusiese",
			nosotros: "pospusiésemos",
			vosotros: "pospusieseis",
			Uds: "pospusiesen",
		},
		Future: {
			yo: "pospusiere",
			tú: "pospusieres",
			Ud: "pospusiere",
			nosotros: "pospusiéremos",
			vosotros: "pospusiereis",
			Uds: "pospusieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "pospón",
			Ud: "posponga",
			nosotros: "pospongamos",
			vosotros: "posponed",
			Uds: "pospongan",
		},
		Negative: {
			tú: "no pospongas",
			Ud: "no posponga",
			nosotros: "no pospongamos",
			vosotros: "no pospongáis",
			Uds: "no pospongan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy posponiendo",
			tú: "estás posponiendo",
			Ud: "está posponiendo",
			nosotros: "estamos posponiendo",
			vosotros: "estáis posponiendo",
			Uds: "están posponiendo",
		},
		Preterite: {
			yo: "estuve posponiendo",
			tú: "estuviste posponiendo",
			Ud: "estuvo posponiendo",
			nosotros: "estuvimos posponiendo",
			vosotros: "estuvisteis posponiendo",
			Uds: "estuvieron posponiendo",
		},
		Imperfect: {
			Uds: "estaban posponiendo",
			yo: "estaba posponiendo",
			tú: "estabas posponiendo",
			Ud: "estaba posponiendo",
			nosotros: "estábamos posponiendo",
			vosotros: "estabais posponiendo",
		},
		Conditional: {
			yo: "estaría posponiendo",
			tú: "estarías posponiendo",
			Ud: "estaría posponiendo",
			nosotros: "estaríamos posponiendo",
			vosotros: "estaríais posponiendo",
			Uds: "estarían posponiendo",
		},
		Future: {
			yo: "estaré posponiendo",
			tú: "estarás posponiendo",
			Ud: "estará posponiendo",
			nosotros: "estaremos posponiendo",
			vosotros: "estaréis posponiendo",
			Uds: "estarán posponiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he pospuesto",
			tú: "has pospuesto",
			Ud: "ha pospuesto",
			nosotros: "hemos pospuesto",
			vosotros: "habéis pospuesto",
			Uds: "han pospuesto",
		},
		Preterite: {
			yo: "hube pospuesto",
			tú: "hubiste pospuesto",
			Ud: "hubo pospuesto",
			nosotros: "hubimos pospuesto",
			vosotros: "hubisteis pospuesto",
			Uds: "hubieron pospuesto",
		},
		Past: {
			yo: "había pospuesto",
			tú: "habías pospuesto",
			Ud: "había pospuesto",
			nosotros: "habíamos pospuesto",
			vosotros: "habíais pospuesto",
			Uds: "habían pospuesto",
		},
		Conditional: {
			yo: "habría pospuesto",
			tú: "habrías pospuesto",
			Ud: "habría pospuesto",
			nosotros: "habríamos pospuesto",
			vosotros: "habríais pospuesto",
			Uds: "habrían pospuesto",
		},
		Future: {
			yo: "habré pospuesto",
			tú: "habrás pospuesto",
			Ud: "habrá pospuesto",
			nosotros: "habremos pospuesto",
			vosotros: "habréis pospuesto",
			Uds: "habrán pospuesto",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya pospuesto",
			tú: "hayas pospuesto",
			Ud: "haya pospuesto",
			nosotros: "hayamos pospuesto",
			vosotros: "hayáis pospuesto",
			Uds: "hayan pospuesto",
		},
		Past: {
			yo: "hubiera pospuesto",
			tú: "hubieras pospuesto",
			Ud: "hubiera pospuesto",
			nosotros: "hubiéramos pospuesto",
			vosotros: "hubierais pospuesto",
			Uds: "hubieran pospuesto",
		},
		Future: {
			yo: "hubiere pospuesto",
			tú: "hubieres pospuesto",
			Ud: "hubiere pospuesto",
			nosotros: "hubiéremos pospuesto",
			vosotros: "hubiereis pospuesto",
			Uds: "hubieren pospuesto",
		},
	},
}
