var precaver = {
	Indicative: {
		Present: {
			yo: "precavo",
			tú: "precaves",
			Ud: "precave",
			nosotros: "precavemos",
			vosotros: "precavéis",
			Uds: "precaven",
		},
		Preterite: {
			yo: "precaví",
			tú: "precaviste",
			Ud: "precavió",
			nosotros: "precavimos",
			vosotros: "precavisteis",
			Uds: "precavieron",
		},
		Imperfect: {
			yo: "precavía",
			tú: "precavías",
			Ud: "precavía",
			nosotros: "precavíamos",
			vosotros: "precavíais",
			Uds: "precavían",
		},
		Conditional: {
			yo: "precavería",
			tú: "precaverías",
			Ud: "precavería",
			nosotros: "precaveríamos",
			vosotros: "precaveríais",
			Uds: "precaverían",
		},
		Future: {
			yo: "precaveré",
			tú: "precaverás",
			Ud: "precaverá",
			nosotros: "precaveremos",
			vosotros: "precaveréis",
			Uds: "precaverán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "precava",
			tú: "precavas",
			Ud: "precava",
			nosotros: "precavamos",
			vosotros: "precaváis",
			Uds: "precavan",
		},
		Imperfect: {
			yo: "precaviera",
			tú: "precavieras",
			Ud: "precaviera",
			nosotros: "precaviéramos",
			vosotros: "precavierais",
			Uds: "precavieran",
		},
		Imperfect2: {
			yo: "precaviese",
			tú: "precavieses",
			Ud: "precaviese",
			nosotros: "precaviésemos",
			vosotros: "precavieseis",
			Uds: "precaviesen",
		},
		Future: {
			yo: "precaviere",
			tú: "precavieres",
			Ud: "precaviere",
			nosotros: "precaviéremos",
			vosotros: "precaviereis",
			Uds: "precavieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "precave",
			Ud: "precava",
			nosotros: "precavamos",
			vosotros: "precaved",
			Uds: "precavan",
		},
		Negative: {
			tú: "no precavas",
			Ud: "no precava",
			nosotros: "no precavamos",
			vosotros: "no precaváis",
			Uds: "no precavan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy precaviendo",
			tú: "estás precaviendo",
			Ud: "está precaviendo",
			nosotros: "estamos precaviendo",
			vosotros: "estáis precaviendo",
			Uds: "están precaviendo",
		},
		Preterite: {
			yo: "estuve precaviendo",
			tú: "estuviste precaviendo",
			Ud: "estuvo precaviendo",
			nosotros: "estuvimos precaviendo",
			vosotros: "estuvisteis precaviendo",
			Uds: "estuvieron precaviendo",
		},
		Imperfect: {
			Uds: "estaban precaviendo",
			yo: "estaba precaviendo",
			tú: "estabas precaviendo",
			Ud: "estaba precaviendo",
			nosotros: "estábamos precaviendo",
			vosotros: "estabais precaviendo",
		},
		Conditional: {
			yo: "estaría precaviendo",
			tú: "estarías precaviendo",
			Ud: "estaría precaviendo",
			nosotros: "estaríamos precaviendo",
			vosotros: "estaríais precaviendo",
			Uds: "estarían precaviendo",
		},
		Future: {
			yo: "estaré precaviendo",
			tú: "estarás precaviendo",
			Ud: "estará precaviendo",
			nosotros: "estaremos precaviendo",
			vosotros: "estaréis precaviendo",
			Uds: "estarán precaviendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he precavido",
			tú: "has precavido",
			Ud: "ha precavido",
			nosotros: "hemos precavido",
			vosotros: "habéis precavido",
			Uds: "han precavido",
		},
		Preterite: {
			yo: "hube precavido",
			tú: "hubiste precavido",
			Ud: "hubo precavido",
			nosotros: "hubimos precavido",
			vosotros: "hubisteis precavido",
			Uds: "hubieron precavido",
		},
		Past: {
			yo: "había precavido",
			tú: "habías precavido",
			Ud: "había precavido",
			nosotros: "habíamos precavido",
			vosotros: "habíais precavido",
			Uds: "habían precavido",
		},
		Conditional: {
			yo: "habría precavido",
			tú: "habrías precavido",
			Ud: "habría precavido",
			nosotros: "habríamos precavido",
			vosotros: "habríais precavido",
			Uds: "habrían precavido",
		},
		Future: {
			yo: "habré precavido",
			tú: "habrás precavido",
			Ud: "habrá precavido",
			nosotros: "habremos precavido",
			vosotros: "habréis precavido",
			Uds: "habrán precavido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya precavido",
			tú: "hayas precavido",
			Ud: "haya precavido",
			nosotros: "hayamos precavido",
			vosotros: "hayáis precavido",
			Uds: "hayan precavido",
		},
		Past: {
			yo: "hubiera precavido",
			tú: "hubieras precavido",
			Ud: "hubiera precavido",
			nosotros: "hubiéramos precavido",
			vosotros: "hubierais precavido",
			Uds: "hubieran precavido",
		},
		Future: {
			yo: "hubiere precavido",
			tú: "hubieres precavido",
			Ud: "hubiere precavido",
			nosotros: "hubiéremos precavido",
			vosotros: "hubiereis precavido",
			Uds: "hubieren precavido",
		},
	},
}
