var prevenir = {
	Indicative: {
		Present: {
			yo: "prevengo",
			tú: "previenes",
			Ud: "previene",
			nosotros: "prevenimos",
			vosotros: "prevenís",
			Uds: "previenen",
		},
		Preterite: {
			yo: "previne",
			tú: "previniste",
			Ud: "previno",
			nosotros: "previnimos",
			vosotros: "previnisteis",
			Uds: "previnieron",
		},
		Imperfect: {
			yo: "prevenía",
			tú: "prevenías",
			Ud: "prevenía",
			nosotros: "preveníamos",
			vosotros: "preveníais",
			Uds: "prevenían",
		},
		Conditional: {
			yo: "prevendría",
			tú: "prevendrías",
			Ud: "prevendría",
			nosotros: "prevendríamos",
			vosotros: "prevendríais",
			Uds: "prevendrían",
		},
		Future: {
			yo: "prevendré",
			tú: "prevendrás",
			Ud: "prevendrá",
			nosotros: "prevendremos",
			vosotros: "prevendréis",
			Uds: "prevendrán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "prevenga",
			tú: "prevengas",
			Ud: "prevenga",
			nosotros: "prevengamos",
			vosotros: "prevengáis",
			Uds: "prevengan",
		},
		Imperfect: {
			yo: "previniera",
			tú: "previnieras",
			Ud: "previniera",
			nosotros: "previniéramos",
			vosotros: "previnierais",
			Uds: "previnieran",
		},
		Imperfect2: {
			yo: "previniese",
			tú: "previnieses",
			Ud: "previniese",
			nosotros: "previniésemos",
			vosotros: "previnieseis",
			Uds: "previniesen",
		},
		Future: {
			yo: "previniere",
			tú: "previnieres",
			Ud: "previniere",
			nosotros: "previniéremos",
			vosotros: "previniereis",
			Uds: "previnieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "prevén",
			Ud: "prevenga",
			nosotros: "prevengamos",
			vosotros: "prevenid",
			Uds: "prevengan",
		},
		Negative: {
			tú: "no prevengas",
			Ud: "no prevenga",
			nosotros: "no prevengamos",
			vosotros: "no prevengáis",
			Uds: "no prevengan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy previniendo",
			tú: "estás previniendo",
			Ud: "está previniendo",
			nosotros: "estamos previniendo",
			vosotros: "estáis previniendo",
			Uds: "están previniendo",
		},
		Preterite: {
			yo: "estuve previniendo",
			tú: "estuviste previniendo",
			Ud: "estuvo previniendo",
			nosotros: "estuvimos previniendo",
			vosotros: "estuvisteis previniendo",
			Uds: "estuvieron previniendo",
		},
		Imperfect: {
			Uds: "estaban previniendo",
			yo: "estaba previniendo",
			tú: "estabas previniendo",
			Ud: "estaba previniendo",
			nosotros: "estábamos previniendo",
			vosotros: "estabais previniendo",
		},
		Conditional: {
			yo: "estaría previniendo",
			tú: "estarías previniendo",
			Ud: "estaría previniendo",
			nosotros: "estaríamos previniendo",
			vosotros: "estaríais previniendo",
			Uds: "estarían previniendo",
		},
		Future: {
			yo: "estaré previniendo",
			tú: "estarás previniendo",
			Ud: "estará previniendo",
			nosotros: "estaremos previniendo",
			vosotros: "estaréis previniendo",
			Uds: "estarán previniendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he prevenido",
			tú: "has prevenido",
			Ud: "ha prevenido",
			nosotros: "hemos prevenido",
			vosotros: "habéis prevenido",
			Uds: "han prevenido",
		},
		Preterite: {
			yo: "hube prevenido",
			tú: "hubiste prevenido",
			Ud: "hubo prevenido",
			nosotros: "hubimos prevenido",
			vosotros: "hubisteis prevenido",
			Uds: "hubieron prevenido",
		},
		Past: {
			yo: "había prevenido",
			tú: "habías prevenido",
			Ud: "había prevenido",
			nosotros: "habíamos prevenido",
			vosotros: "habíais prevenido",
			Uds: "habían prevenido",
		},
		Conditional: {
			yo: "habría prevenido",
			tú: "habrías prevenido",
			Ud: "habría prevenido",
			nosotros: "habríamos prevenido",
			vosotros: "habríais prevenido",
			Uds: "habrían prevenido",
		},
		Future: {
			yo: "habré prevenido",
			tú: "habrás prevenido",
			Ud: "habrá prevenido",
			nosotros: "habremos prevenido",
			vosotros: "habréis prevenido",
			Uds: "habrán prevenido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya prevenido",
			tú: "hayas prevenido",
			Ud: "haya prevenido",
			nosotros: "hayamos prevenido",
			vosotros: "hayáis prevenido",
			Uds: "hayan prevenido",
		},
		Past: {
			yo: "hubiera prevenido",
			tú: "hubieras prevenido",
			Ud: "hubiera prevenido",
			nosotros: "hubiéramos prevenido",
			vosotros: "hubierais prevenido",
			Uds: "hubieran prevenido",
		},
		Future: {
			yo: "hubiere prevenido",
			tú: "hubieres prevenido",
			Ud: "hubiere prevenido",
			nosotros: "hubiéremos prevenido",
			vosotros: "hubiereis prevenido",
			Uds: "hubieren prevenido",
		},
	},
}
