var probar = {
	Indicative: {
		Present: {
			yo: "pruebo",
			tú: "pruebas",
			Ud: "prueba",
			nosotros: "probamos",
			vosotros: "probáis",
			Uds: "prueban",
		},
		Preterite: {
			yo: "probé",
			tú: "probaste",
			Ud: "probó",
			nosotros: "probamos",
			vosotros: "probasteis",
			Uds: "probaron",
		},
		Imperfect: {
			yo: "probaba",
			tú: "probabas",
			Ud: "probaba",
			nosotros: "probábamos",
			vosotros: "probabais",
			Uds: "probaban",
		},
		Conditional: {
			yo: "probaría",
			tú: "probarías",
			Ud: "probaría",
			nosotros: "probaríamos",
			vosotros: "probaríais",
			Uds: "probarían",
		},
		Future: {
			yo: "probaré",
			tú: "probarás",
			Ud: "probará",
			nosotros: "probaremos",
			vosotros: "probaréis",
			Uds: "probarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "pruebe",
			tú: "pruebes",
			Ud: "pruebe",
			nosotros: "probemos",
			vosotros: "probéis",
			Uds: "prueben",
		},
		Imperfect: {
			yo: "probara",
			tú: "probaras",
			Ud: "probara",
			nosotros: "probáramos",
			vosotros: "probarais",
			Uds: "probaran",
		},
		Imperfect2: {
			yo: "probase",
			tú: "probases",
			Ud: "probase",
			nosotros: "probásemos",
			vosotros: "probaseis",
			Uds: "probasen",
		},
		Future: {
			yo: "probare",
			tú: "probares",
			Ud: "probare",
			nosotros: "probáremos",
			vosotros: "probareis",
			Uds: "probaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "prueba",
			Ud: "pruebe",
			nosotros: "probemos",
			vosotros: "probad",
			Uds: "prueben",
		},
		Negative: {
			tú: "no pruebes",
			Ud: "no pruebe",
			nosotros: "no probemos",
			vosotros: "no probéis",
			Uds: "no prueben",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy probando",
			tú: "estás probando",
			Ud: "está probando",
			nosotros: "estamos probando",
			vosotros: "estáis probando",
			Uds: "están probando",
		},
		Preterite: {
			yo: "estuve probando",
			tú: "estuviste probando",
			Ud: "estuvo probando",
			nosotros: "estuvimos probando",
			vosotros: "estuvisteis probando",
			Uds: "estuvieron probando",
		},
		Imperfect: {
			Uds: "estaban probando",
			yo: "estaba probando",
			tú: "estabas probando",
			Ud: "estaba probando",
			nosotros: "estábamos probando",
			vosotros: "estabais probando",
		},
		Conditional: {
			yo: "estaría probando",
			tú: "estarías probando",
			Ud: "estaría probando",
			nosotros: "estaríamos probando",
			vosotros: "estaríais probando",
			Uds: "estarían probando",
		},
		Future: {
			yo: "estaré probando",
			tú: "estarás probando",
			Ud: "estará probando",
			nosotros: "estaremos probando",
			vosotros: "estaréis probando",
			Uds: "estarán probando",
		},
	},
	Perfect: {
		Present: {
			yo: "he probado",
			tú: "has probado",
			Ud: "ha probado",
			nosotros: "hemos probado",
			vosotros: "habéis probado",
			Uds: "han probado",
		},
		Preterite: {
			yo: "hube probado",
			tú: "hubiste probado",
			Ud: "hubo probado",
			nosotros: "hubimos probado",
			vosotros: "hubisteis probado",
			Uds: "hubieron probado",
		},
		Past: {
			yo: "había probado",
			tú: "habías probado",
			Ud: "había probado",
			nosotros: "habíamos probado",
			vosotros: "habíais probado",
			Uds: "habían probado",
		},
		Conditional: {
			yo: "habría probado",
			tú: "habrías probado",
			Ud: "habría probado",
			nosotros: "habríamos probado",
			vosotros: "habríais probado",
			Uds: "habrían probado",
		},
		Future: {
			yo: "habré probado",
			tú: "habrás probado",
			Ud: "habrá probado",
			nosotros: "habremos probado",
			vosotros: "habréis probado",
			Uds: "habrán probado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya probado",
			tú: "hayas probado",
			Ud: "haya probado",
			nosotros: "hayamos probado",
			vosotros: "hayáis probado",
			Uds: "hayan probado",
		},
		Past: {
			yo: "hubiera probado",
			tú: "hubieras probado",
			Ud: "hubiera probado",
			nosotros: "hubiéramos probado",
			vosotros: "hubierais probado",
			Uds: "hubieran probado",
		},
		Future: {
			yo: "hubiere probado",
			tú: "hubieres probado",
			Ud: "hubiere probado",
			nosotros: "hubiéremos probado",
			vosotros: "hubiereis probado",
			Uds: "hubieren probado",
		},
	},
}
