var proceder = {
	Indicative: {
		Present: {
			yo: "procedo",
			tú: "procedes",
			Ud: "procede",
			nosotros: "procedemos",
			vosotros: "procedéis",
			Uds: "proceden",
		},
		Preterite: {
			yo: "procedí",
			tú: "procediste",
			Ud: "procedió",
			nosotros: "procedimos",
			vosotros: "procedisteis",
			Uds: "procedieron",
		},
		Imperfect: {
			yo: "procedía",
			tú: "procedías",
			Ud: "procedía",
			nosotros: "procedíamos",
			vosotros: "procedíais",
			Uds: "procedían",
		},
		Conditional: {
			yo: "procedería",
			tú: "procederías",
			Ud: "procedería",
			nosotros: "procederíamos",
			vosotros: "procederíais",
			Uds: "procederían",
		},
		Future: {
			yo: "procederé",
			tú: "procederás",
			Ud: "procederá",
			nosotros: "procederemos",
			vosotros: "procederéis",
			Uds: "procederán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "proceda",
			tú: "procedas",
			Ud: "proceda",
			nosotros: "procedamos",
			vosotros: "procedáis",
			Uds: "procedan",
		},
		Imperfect: {
			yo: "procediera",
			tú: "procedieras",
			Ud: "procediera",
			nosotros: "procediéramos",
			vosotros: "procedierais",
			Uds: "procedieran",
		},
		Imperfect2: {
			yo: "procediese",
			tú: "procedieses",
			Ud: "procediese",
			nosotros: "procediésemos",
			vosotros: "procedieseis",
			Uds: "procediesen",
		},
		Future: {
			yo: "procediere",
			tú: "procedieres",
			Ud: "procediere",
			nosotros: "procediéremos",
			vosotros: "procediereis",
			Uds: "procedieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "procede",
			Ud: "proceda",
			nosotros: "procedamos",
			vosotros: "proceded",
			Uds: "procedan",
		},
		Negative: {
			tú: "no procedas",
			Ud: "no proceda",
			nosotros: "no procedamos",
			vosotros: "no procedáis",
			Uds: "no procedan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy procediendo",
			tú: "estás procediendo",
			Ud: "está procediendo",
			nosotros: "estamos procediendo",
			vosotros: "estáis procediendo",
			Uds: "están procediendo",
		},
		Preterite: {
			yo: "estuve procediendo",
			tú: "estuviste procediendo",
			Ud: "estuvo procediendo",
			nosotros: "estuvimos procediendo",
			vosotros: "estuvisteis procediendo",
			Uds: "estuvieron procediendo",
		},
		Imperfect: {
			Uds: "estaban procediendo",
			yo: "estaba procediendo",
			tú: "estabas procediendo",
			Ud: "estaba procediendo",
			nosotros: "estábamos procediendo",
			vosotros: "estabais procediendo",
		},
		Conditional: {
			yo: "estaría procediendo",
			tú: "estarías procediendo",
			Ud: "estaría procediendo",
			nosotros: "estaríamos procediendo",
			vosotros: "estaríais procediendo",
			Uds: "estarían procediendo",
		},
		Future: {
			yo: "estaré procediendo",
			tú: "estarás procediendo",
			Ud: "estará procediendo",
			nosotros: "estaremos procediendo",
			vosotros: "estaréis procediendo",
			Uds: "estarán procediendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he procedido",
			tú: "has procedido",
			Ud: "ha procedido",
			nosotros: "hemos procedido",
			vosotros: "habéis procedido",
			Uds: "han procedido",
		},
		Preterite: {
			yo: "hube procedido",
			tú: "hubiste procedido",
			Ud: "hubo procedido",
			nosotros: "hubimos procedido",
			vosotros: "hubisteis procedido",
			Uds: "hubieron procedido",
		},
		Past: {
			yo: "había procedido",
			tú: "habías procedido",
			Ud: "había procedido",
			nosotros: "habíamos procedido",
			vosotros: "habíais procedido",
			Uds: "habían procedido",
		},
		Conditional: {
			yo: "habría procedido",
			tú: "habrías procedido",
			Ud: "habría procedido",
			nosotros: "habríamos procedido",
			vosotros: "habríais procedido",
			Uds: "habrían procedido",
		},
		Future: {
			yo: "habré procedido",
			tú: "habrás procedido",
			Ud: "habrá procedido",
			nosotros: "habremos procedido",
			vosotros: "habréis procedido",
			Uds: "habrán procedido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya procedido",
			tú: "hayas procedido",
			Ud: "haya procedido",
			nosotros: "hayamos procedido",
			vosotros: "hayáis procedido",
			Uds: "hayan procedido",
		},
		Past: {
			yo: "hubiera procedido",
			tú: "hubieras procedido",
			Ud: "hubiera procedido",
			nosotros: "hubiéramos procedido",
			vosotros: "hubierais procedido",
			Uds: "hubieran procedido",
		},
		Future: {
			yo: "hubiere procedido",
			tú: "hubieres procedido",
			Ud: "hubiere procedido",
			nosotros: "hubiéremos procedido",
			vosotros: "hubiereis procedido",
			Uds: "hubieren procedido",
		},
	},
}
