var progresar = {
	Indicative: {
		Present: {
			yo: "progreso",
			tú: "progresas",
			Ud: "progresa",
			nosotros: "progresamos",
			vosotros: "progresáis",
			Uds: "progresan",
		},
		Preterite: {
			yo: "progresé",
			tú: "progresaste",
			Ud: "progresó",
			nosotros: "progresamos",
			vosotros: "progresasteis",
			Uds: "progresaron",
		},
		Imperfect: {
			yo: "progresaba",
			tú: "progresabas",
			Ud: "progresaba",
			nosotros: "progresábamos",
			vosotros: "progresabais",
			Uds: "progresaban",
		},
		Conditional: {
			yo: "progresaría",
			tú: "progresarías",
			Ud: "progresaría",
			nosotros: "progresaríamos",
			vosotros: "progresaríais",
			Uds: "progresarían",
		},
		Future: {
			yo: "progresaré",
			tú: "progresarás",
			Ud: "progresará",
			nosotros: "progresaremos",
			vosotros: "progresaréis",
			Uds: "progresarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "progrese",
			tú: "progreses",
			Ud: "progrese",
			nosotros: "progresemos",
			vosotros: "progreséis",
			Uds: "progresen",
		},
		Imperfect: {
			yo: "progresara",
			tú: "progresaras",
			Ud: "progresara",
			nosotros: "progresáramos",
			vosotros: "progresarais",
			Uds: "progresaran",
		},
		Imperfect2: {
			yo: "progresase",
			tú: "progresases",
			Ud: "progresase",
			nosotros: "progresásemos",
			vosotros: "progresaseis",
			Uds: "progresasen",
		},
		Future: {
			yo: "progresare",
			tú: "progresares",
			Ud: "progresare",
			nosotros: "progresáremos",
			vosotros: "progresareis",
			Uds: "progresaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "progresa",
			Ud: "progrese",
			nosotros: "progresemos",
			vosotros: "progresad",
			Uds: "progresen",
		},
		Negative: {
			tú: "no progreses",
			Ud: "no progrese",
			nosotros: "no progresemos",
			vosotros: "no progreséis",
			Uds: "no progresen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy progresando",
			tú: "estás progresando",
			Ud: "está progresando",
			nosotros: "estamos progresando",
			vosotros: "estáis progresando",
			Uds: "están progresando",
		},
		Preterite: {
			yo: "estuve progresando",
			tú: "estuviste progresando",
			Ud: "estuvo progresando",
			nosotros: "estuvimos progresando",
			vosotros: "estuvisteis progresando",
			Uds: "estuvieron progresando",
		},
		Imperfect: {
			Uds: "estaban progresando",
			yo: "estaba progresando",
			tú: "estabas progresando",
			Ud: "estaba progresando",
			nosotros: "estábamos progresando",
			vosotros: "estabais progresando",
		},
		Conditional: {
			yo: "estaría progresando",
			tú: "estarías progresando",
			Ud: "estaría progresando",
			nosotros: "estaríamos progresando",
			vosotros: "estaríais progresando",
			Uds: "estarían progresando",
		},
		Future: {
			yo: "estaré progresando",
			tú: "estarás progresando",
			Ud: "estará progresando",
			nosotros: "estaremos progresando",
			vosotros: "estaréis progresando",
			Uds: "estarán progresando",
		},
	},
	Perfect: {
		Present: {
			yo: "he progresado",
			tú: "has progresado",
			Ud: "ha progresado",
			nosotros: "hemos progresado",
			vosotros: "habéis progresado",
			Uds: "han progresado",
		},
		Preterite: {
			yo: "hube progresado",
			tú: "hubiste progresado",
			Ud: "hubo progresado",
			nosotros: "hubimos progresado",
			vosotros: "hubisteis progresado",
			Uds: "hubieron progresado",
		},
		Past: {
			yo: "había progresado",
			tú: "habías progresado",
			Ud: "había progresado",
			nosotros: "habíamos progresado",
			vosotros: "habíais progresado",
			Uds: "habían progresado",
		},
		Conditional: {
			yo: "habría progresado",
			tú: "habrías progresado",
			Ud: "habría progresado",
			nosotros: "habríamos progresado",
			vosotros: "habríais progresado",
			Uds: "habrían progresado",
		},
		Future: {
			yo: "habré progresado",
			tú: "habrás progresado",
			Ud: "habrá progresado",
			nosotros: "habremos progresado",
			vosotros: "habréis progresado",
			Uds: "habrán progresado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya progresado",
			tú: "hayas progresado",
			Ud: "haya progresado",
			nosotros: "hayamos progresado",
			vosotros: "hayáis progresado",
			Uds: "hayan progresado",
		},
		Past: {
			yo: "hubiera progresado",
			tú: "hubieras progresado",
			Ud: "hubiera progresado",
			nosotros: "hubiéramos progresado",
			vosotros: "hubierais progresado",
			Uds: "hubieran progresado",
		},
		Future: {
			yo: "hubiere progresado",
			tú: "hubieres progresado",
			Ud: "hubiere progresado",
			nosotros: "hubiéremos progresado",
			vosotros: "hubiereis progresado",
			Uds: "hubieren progresado",
		},
	},
}
