var propulsar = {
	Indicative: {
		Present: {
			yo: "propulso",
			tú: "propulsas",
			Ud: "propulsa",
			nosotros: "propulsamos",
			vosotros: "propulsáis",
			Uds: "propulsan",
		},
		Preterite: {
			yo: "propulsé",
			tú: "propulsaste",
			Ud: "propulsó",
			nosotros: "propulsamos",
			vosotros: "propulsasteis",
			Uds: "propulsaron",
		},
		Imperfect: {
			yo: "propulsaba",
			tú: "propulsabas",
			Ud: "propulsaba",
			nosotros: "propulsábamos",
			vosotros: "propulsabais",
			Uds: "propulsaban",
		},
		Conditional: {
			yo: "propulsaría",
			tú: "propulsarías",
			Ud: "propulsaría",
			nosotros: "propulsaríamos",
			vosotros: "propulsaríais",
			Uds: "propulsarían",
		},
		Future: {
			yo: "propulsaré",
			tú: "propulsarás",
			Ud: "propulsará",
			nosotros: "propulsaremos",
			vosotros: "propulsaréis",
			Uds: "propulsarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "propulse",
			tú: "propulses",
			Ud: "propulse",
			nosotros: "propulsemos",
			vosotros: "propulséis",
			Uds: "propulsen",
		},
		Imperfect: {
			yo: "propulsara",
			tú: "propulsaras",
			Ud: "propulsara",
			nosotros: "propulsáramos",
			vosotros: "propulsarais",
			Uds: "propulsaran",
		},
		Imperfect2: {
			yo: "propulsase",
			tú: "propulsases",
			Ud: "propulsase",
			nosotros: "propulsásemos",
			vosotros: "propulsaseis",
			Uds: "propulsasen",
		},
		Future: {
			yo: "propulsare",
			tú: "propulsares",
			Ud: "propulsare",
			nosotros: "propulsáremos",
			vosotros: "propulsareis",
			Uds: "propulsaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "propulsa",
			Ud: "propulse",
			nosotros: "propulsemos",
			vosotros: "propulsad",
			Uds: "propulsen",
		},
		Negative: {
			tú: "no propulses",
			Ud: "no propulse",
			nosotros: "no propulsemos",
			vosotros: "no propulséis",
			Uds: "no propulsen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy propulsando",
			tú: "estás propulsando",
			Ud: "está propulsando",
			nosotros: "estamos propulsando",
			vosotros: "estáis propulsando",
			Uds: "están propulsando",
		},
		Preterite: {
			yo: "estuve propulsando",
			tú: "estuviste propulsando",
			Ud: "estuvo propulsando",
			nosotros: "estuvimos propulsando",
			vosotros: "estuvisteis propulsando",
			Uds: "estuvieron propulsando",
		},
		Imperfect: {
			Uds: "estaban propulsando",
			yo: "estaba propulsando",
			tú: "estabas propulsando",
			Ud: "estaba propulsando",
			nosotros: "estábamos propulsando",
			vosotros: "estabais propulsando",
		},
		Conditional: {
			yo: "estaría propulsando",
			tú: "estarías propulsando",
			Ud: "estaría propulsando",
			nosotros: "estaríamos propulsando",
			vosotros: "estaríais propulsando",
			Uds: "estarían propulsando",
		},
		Future: {
			yo: "estaré propulsando",
			tú: "estarás propulsando",
			Ud: "estará propulsando",
			nosotros: "estaremos propulsando",
			vosotros: "estaréis propulsando",
			Uds: "estarán propulsando",
		},
	},
	Perfect: {
		Present: {
			yo: "he propulsado",
			tú: "has propulsado",
			Ud: "ha propulsado",
			nosotros: "hemos propulsado",
			vosotros: "habéis propulsado",
			Uds: "han propulsado",
		},
		Preterite: {
			yo: "hube propulsado",
			tú: "hubiste propulsado",
			Ud: "hubo propulsado",
			nosotros: "hubimos propulsado",
			vosotros: "hubisteis propulsado",
			Uds: "hubieron propulsado",
		},
		Past: {
			yo: "había propulsado",
			tú: "habías propulsado",
			Ud: "había propulsado",
			nosotros: "habíamos propulsado",
			vosotros: "habíais propulsado",
			Uds: "habían propulsado",
		},
		Conditional: {
			yo: "habría propulsado",
			tú: "habrías propulsado",
			Ud: "habría propulsado",
			nosotros: "habríamos propulsado",
			vosotros: "habríais propulsado",
			Uds: "habrían propulsado",
		},
		Future: {
			yo: "habré propulsado",
			tú: "habrás propulsado",
			Ud: "habrá propulsado",
			nosotros: "habremos propulsado",
			vosotros: "habréis propulsado",
			Uds: "habrán propulsado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya propulsado",
			tú: "hayas propulsado",
			Ud: "haya propulsado",
			nosotros: "hayamos propulsado",
			vosotros: "hayáis propulsado",
			Uds: "hayan propulsado",
		},
		Past: {
			yo: "hubiera propulsado",
			tú: "hubieras propulsado",
			Ud: "hubiera propulsado",
			nosotros: "hubiéramos propulsado",
			vosotros: "hubierais propulsado",
			Uds: "hubieran propulsado",
		},
		Future: {
			yo: "hubiere propulsado",
			tú: "hubieres propulsado",
			Ud: "hubiere propulsado",
			nosotros: "hubiéremos propulsado",
			vosotros: "hubiereis propulsado",
			Uds: "hubieren propulsado",
		},
	},
}
