var proseguir = {
	Indicative: {
		Present: {
			yo: "prosigo",
			tú: "prosigues",
			Ud: "prosigue",
			nosotros: "proseguimos",
			vosotros: "proseguís",
			Uds: "prosiguen",
		},
		Preterite: {
			yo: "proseguí",
			tú: "proseguiste",
			Ud: "prosiguió",
			nosotros: "proseguimos",
			vosotros: "proseguisteis",
			Uds: "prosiguieron",
		},
		Imperfect: {
			yo: "proseguía",
			tú: "proseguías",
			Ud: "proseguía",
			nosotros: "proseguíamos",
			vosotros: "proseguíais",
			Uds: "proseguían",
		},
		Conditional: {
			yo: "proseguiría",
			tú: "proseguirías",
			Ud: "proseguiría",
			nosotros: "proseguiríamos",
			vosotros: "proseguiríais",
			Uds: "proseguirían",
		},
		Future: {
			yo: "proseguiré",
			tú: "proseguirás",
			Ud: "proseguirá",
			nosotros: "proseguiremos",
			vosotros: "proseguiréis",
			Uds: "proseguirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "prosiga",
			tú: "prosigas",
			Ud: "prosiga",
			nosotros: "prosigamos",
			vosotros: "prosigáis",
			Uds: "prosigan",
		},
		Imperfect: {
			yo: "prosiguiera",
			tú: "prosiguieras",
			Ud: "prosiguiera",
			nosotros: "prosiguiéramos",
			vosotros: "prosiguierais",
			Uds: "prosiguieran",
		},
		Imperfect2: {
			yo: "prosiguiese",
			tú: "prosiguieses",
			Ud: "prosiguiese",
			nosotros: "prosiguiésemos",
			vosotros: "prosiguieseis",
			Uds: "prosiguiesen",
		},
		Future: {
			yo: "prosiguiere",
			tú: "prosiguieres",
			Ud: "prosiguiere",
			nosotros: "prosiguiéremos",
			vosotros: "prosiguiereis",
			Uds: "prosiguieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "prosigue",
			Ud: "prosiga",
			nosotros: "prosigamos",
			vosotros: "proseguid",
			Uds: "prosigan",
		},
		Negative: {
			tú: "no prosigas",
			Ud: "no prosiga",
			nosotros: "no prosigamos",
			vosotros: "no prosigáis",
			Uds: "no prosigan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy prosiguiendo",
			tú: "estás prosiguiendo",
			Ud: "está prosiguiendo",
			nosotros: "estamos prosiguiendo",
			vosotros: "estáis prosiguiendo",
			Uds: "están prosiguiendo",
		},
		Preterite: {
			yo: "estuve prosiguiendo",
			tú: "estuviste prosiguiendo",
			Ud: "estuvo prosiguiendo",
			nosotros: "estuvimos prosiguiendo",
			vosotros: "estuvisteis prosiguiendo",
			Uds: "estuvieron prosiguiendo",
		},
		Imperfect: {
			Uds: "estaban prosiguiendo",
			yo: "estaba prosiguiendo",
			tú: "estabas prosiguiendo",
			Ud: "estaba prosiguiendo",
			nosotros: "estábamos prosiguiendo",
			vosotros: "estabais prosiguiendo",
		},
		Conditional: {
			yo: "estaría prosiguiendo",
			tú: "estarías prosiguiendo",
			Ud: "estaría prosiguiendo",
			nosotros: "estaríamos prosiguiendo",
			vosotros: "estaríais prosiguiendo",
			Uds: "estarían prosiguiendo",
		},
		Future: {
			yo: "estaré prosiguiendo",
			tú: "estarás prosiguiendo",
			Ud: "estará prosiguiendo",
			nosotros: "estaremos prosiguiendo",
			vosotros: "estaréis prosiguiendo",
			Uds: "estarán prosiguiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he proseguido",
			tú: "has proseguido",
			Ud: "ha proseguido",
			nosotros: "hemos proseguido",
			vosotros: "habéis proseguido",
			Uds: "han proseguido",
		},
		Preterite: {
			yo: "hube proseguido",
			tú: "hubiste proseguido",
			Ud: "hubo proseguido",
			nosotros: "hubimos proseguido",
			vosotros: "hubisteis proseguido",
			Uds: "hubieron proseguido",
		},
		Past: {
			yo: "había proseguido",
			tú: "habías proseguido",
			Ud: "había proseguido",
			nosotros: "habíamos proseguido",
			vosotros: "habíais proseguido",
			Uds: "habían proseguido",
		},
		Conditional: {
			yo: "habría proseguido",
			tú: "habrías proseguido",
			Ud: "habría proseguido",
			nosotros: "habríamos proseguido",
			vosotros: "habríais proseguido",
			Uds: "habrían proseguido",
		},
		Future: {
			yo: "habré proseguido",
			tú: "habrás proseguido",
			Ud: "habrá proseguido",
			nosotros: "habremos proseguido",
			vosotros: "habréis proseguido",
			Uds: "habrán proseguido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya proseguido",
			tú: "hayas proseguido",
			Ud: "haya proseguido",
			nosotros: "hayamos proseguido",
			vosotros: "hayáis proseguido",
			Uds: "hayan proseguido",
		},
		Past: {
			yo: "hubiera proseguido",
			tú: "hubieras proseguido",
			Ud: "hubiera proseguido",
			nosotros: "hubiéramos proseguido",
			vosotros: "hubierais proseguido",
			Uds: "hubieran proseguido",
		},
		Future: {
			yo: "hubiere proseguido",
			tú: "hubieres proseguido",
			Ud: "hubiere proseguido",
			nosotros: "hubiéremos proseguido",
			vosotros: "hubiereis proseguido",
			Uds: "hubieren proseguido",
		},
	},
}
