var prosperar = {
	Indicative: {
		Present: {
			yo: "prospero",
			tú: "prosperas",
			Ud: "prospera",
			nosotros: "prosperamos",
			vosotros: "prosperáis",
			Uds: "prosperan",
		},
		Preterite: {
			yo: "prosperé",
			tú: "prosperaste",
			Ud: "prosperó",
			nosotros: "prosperamos",
			vosotros: "prosperasteis",
			Uds: "prosperaron",
		},
		Imperfect: {
			yo: "prosperaba",
			tú: "prosperabas",
			Ud: "prosperaba",
			nosotros: "prosperábamos",
			vosotros: "prosperabais",
			Uds: "prosperaban",
		},
		Conditional: {
			yo: "prosperaría",
			tú: "prosperarías",
			Ud: "prosperaría",
			nosotros: "prosperaríamos",
			vosotros: "prosperaríais",
			Uds: "prosperarían",
		},
		Future: {
			yo: "prosperaré",
			tú: "prosperarás",
			Ud: "prosperará",
			nosotros: "prosperaremos",
			vosotros: "prosperaréis",
			Uds: "prosperarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "prospere",
			tú: "prosperes",
			Ud: "prospere",
			nosotros: "prosperemos",
			vosotros: "prosperéis",
			Uds: "prosperen",
		},
		Imperfect: {
			yo: "prosperara",
			tú: "prosperaras",
			Ud: "prosperara",
			nosotros: "prosperáramos",
			vosotros: "prosperarais",
			Uds: "prosperaran",
		},
		Imperfect2: {
			yo: "prosperase",
			tú: "prosperases",
			Ud: "prosperase",
			nosotros: "prosperásemos",
			vosotros: "prosperaseis",
			Uds: "prosperasen",
		},
		Future: {
			yo: "prosperare",
			tú: "prosperares",
			Ud: "prosperare",
			nosotros: "prosperáremos",
			vosotros: "prosperareis",
			Uds: "prosperaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "prospera",
			Ud: "prospere",
			nosotros: "prosperemos",
			vosotros: "prosperad",
			Uds: "prosperen",
		},
		Negative: {
			tú: "no prosperes",
			Ud: "no prospere",
			nosotros: "no prosperemos",
			vosotros: "no prosperéis",
			Uds: "no prosperen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy prosperando",
			tú: "estás prosperando",
			Ud: "está prosperando",
			nosotros: "estamos prosperando",
			vosotros: "estáis prosperando",
			Uds: "están prosperando",
		},
		Preterite: {
			yo: "estuve prosperando",
			tú: "estuviste prosperando",
			Ud: "estuvo prosperando",
			nosotros: "estuvimos prosperando",
			vosotros: "estuvisteis prosperando",
			Uds: "estuvieron prosperando",
		},
		Imperfect: {
			Uds: "estaban prosperando",
			yo: "estaba prosperando",
			tú: "estabas prosperando",
			Ud: "estaba prosperando",
			nosotros: "estábamos prosperando",
			vosotros: "estabais prosperando",
		},
		Conditional: {
			yo: "estaría prosperando",
			tú: "estarías prosperando",
			Ud: "estaría prosperando",
			nosotros: "estaríamos prosperando",
			vosotros: "estaríais prosperando",
			Uds: "estarían prosperando",
		},
		Future: {
			yo: "estaré prosperando",
			tú: "estarás prosperando",
			Ud: "estará prosperando",
			nosotros: "estaremos prosperando",
			vosotros: "estaréis prosperando",
			Uds: "estarán prosperando",
		},
	},
	Perfect: {
		Present: {
			yo: "he prosperado",
			tú: "has prosperado",
			Ud: "ha prosperado",
			nosotros: "hemos prosperado",
			vosotros: "habéis prosperado",
			Uds: "han prosperado",
		},
		Preterite: {
			yo: "hube prosperado",
			tú: "hubiste prosperado",
			Ud: "hubo prosperado",
			nosotros: "hubimos prosperado",
			vosotros: "hubisteis prosperado",
			Uds: "hubieron prosperado",
		},
		Past: {
			yo: "había prosperado",
			tú: "habías prosperado",
			Ud: "había prosperado",
			nosotros: "habíamos prosperado",
			vosotros: "habíais prosperado",
			Uds: "habían prosperado",
		},
		Conditional: {
			yo: "habría prosperado",
			tú: "habrías prosperado",
			Ud: "habría prosperado",
			nosotros: "habríamos prosperado",
			vosotros: "habríais prosperado",
			Uds: "habrían prosperado",
		},
		Future: {
			yo: "habré prosperado",
			tú: "habrás prosperado",
			Ud: "habrá prosperado",
			nosotros: "habremos prosperado",
			vosotros: "habréis prosperado",
			Uds: "habrán prosperado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya prosperado",
			tú: "hayas prosperado",
			Ud: "haya prosperado",
			nosotros: "hayamos prosperado",
			vosotros: "hayáis prosperado",
			Uds: "hayan prosperado",
		},
		Past: {
			yo: "hubiera prosperado",
			tú: "hubieras prosperado",
			Ud: "hubiera prosperado",
			nosotros: "hubiéramos prosperado",
			vosotros: "hubierais prosperado",
			Uds: "hubieran prosperado",
		},
		Future: {
			yo: "hubiere prosperado",
			tú: "hubieres prosperado",
			Ud: "hubiere prosperado",
			nosotros: "hubiéremos prosperado",
			vosotros: "hubiereis prosperado",
			Uds: "hubieren prosperado",
		},
	},
}
