var protagonizar = {
	Indicative: {
		Present: {
			yo: "protagonizo",
			tú: "protagonizas",
			Ud: "protagoniza",
			nosotros: "protagonizamos",
			vosotros: "protagonizáis",
			Uds: "protagonizan",
		},
		Preterite: {
			yo: "protagonicé",
			tú: "protagonizaste",
			Ud: "protagonizó",
			nosotros: "protagonizamos",
			vosotros: "protagonizasteis",
			Uds: "protagonizaron",
		},
		Imperfect: {
			yo: "protagonizaba",
			tú: "protagonizabas",
			Ud: "protagonizaba",
			nosotros: "protagonizábamos",
			vosotros: "protagonizabais",
			Uds: "protagonizaban",
		},
		Conditional: {
			yo: "protagonizaría",
			tú: "protagonizarías",
			Ud: "protagonizaría",
			nosotros: "protagonizaríamos",
			vosotros: "protagonizaríais",
			Uds: "protagonizarían",
		},
		Future: {
			yo: "protagonizaré",
			tú: "protagonizarás",
			Ud: "protagonizará",
			nosotros: "protagonizaremos",
			vosotros: "protagonizaréis",
			Uds: "protagonizarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "protagonice",
			tú: "protagonices",
			Ud: "protagonice",
			nosotros: "protagonicemos",
			vosotros: "protagonicéis",
			Uds: "protagonicen",
		},
		Imperfect: {
			yo: "protagonizara",
			tú: "protagonizaras",
			Ud: "protagonizara",
			nosotros: "protagonizáramos",
			vosotros: "protagonizarais",
			Uds: "protagonizaran",
		},
		Imperfect2: {
			yo: "protagonizase",
			tú: "protagonizases",
			Ud: "protagonizase",
			nosotros: "protagonizásemos",
			vosotros: "protagonizaseis",
			Uds: "protagonizasen",
		},
		Future: {
			yo: "protagonizare",
			tú: "protagonizares",
			Ud: "protagonizare",
			nosotros: "protagonizáremos",
			vosotros: "protagonizareis",
			Uds: "protagonizaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "protagoniza",
			Ud: "protagonice",
			nosotros: "protagonicemos",
			vosotros: "protagonizad",
			Uds: "protagonicen",
		},
		Negative: {
			tú: "no protagonices",
			Ud: "no protagonice",
			nosotros: "no protagonicemos",
			vosotros: "no protagonicéis",
			Uds: "no protagonicen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy protagonizando",
			tú: "estás protagonizando",
			Ud: "está protagonizando",
			nosotros: "estamos protagonizando",
			vosotros: "estáis protagonizando",
			Uds: "están protagonizando",
		},
		Preterite: {
			yo: "estuve protagonizando",
			tú: "estuviste protagonizando",
			Ud: "estuvo protagonizando",
			nosotros: "estuvimos protagonizando",
			vosotros: "estuvisteis protagonizando",
			Uds: "estuvieron protagonizando",
		},
		Imperfect: {
			Uds: "estaban protagonizando",
			yo: "estaba protagonizando",
			tú: "estabas protagonizando",
			Ud: "estaba protagonizando",
			nosotros: "estábamos protagonizando",
			vosotros: "estabais protagonizando",
		},
		Conditional: {
			yo: "estaría protagonizando",
			tú: "estarías protagonizando",
			Ud: "estaría protagonizando",
			nosotros: "estaríamos protagonizando",
			vosotros: "estaríais protagonizando",
			Uds: "estarían protagonizando",
		},
		Future: {
			yo: "estaré protagonizando",
			tú: "estarás protagonizando",
			Ud: "estará protagonizando",
			nosotros: "estaremos protagonizando",
			vosotros: "estaréis protagonizando",
			Uds: "estarán protagonizando",
		},
	},
	Perfect: {
		Present: {
			yo: "he protagonizado",
			tú: "has protagonizado",
			Ud: "ha protagonizado",
			nosotros: "hemos protagonizado",
			vosotros: "habéis protagonizado",
			Uds: "han protagonizado",
		},
		Preterite: {
			yo: "hube protagonizado",
			tú: "hubiste protagonizado",
			Ud: "hubo protagonizado",
			nosotros: "hubimos protagonizado",
			vosotros: "hubisteis protagonizado",
			Uds: "hubieron protagonizado",
		},
		Past: {
			yo: "había protagonizado",
			tú: "habías protagonizado",
			Ud: "había protagonizado",
			nosotros: "habíamos protagonizado",
			vosotros: "habíais protagonizado",
			Uds: "habían protagonizado",
		},
		Conditional: {
			yo: "habría protagonizado",
			tú: "habrías protagonizado",
			Ud: "habría protagonizado",
			nosotros: "habríamos protagonizado",
			vosotros: "habríais protagonizado",
			Uds: "habrían protagonizado",
		},
		Future: {
			yo: "habré protagonizado",
			tú: "habrás protagonizado",
			Ud: "habrá protagonizado",
			nosotros: "habremos protagonizado",
			vosotros: "habréis protagonizado",
			Uds: "habrán protagonizado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya protagonizado",
			tú: "hayas protagonizado",
			Ud: "haya protagonizado",
			nosotros: "hayamos protagonizado",
			vosotros: "hayáis protagonizado",
			Uds: "hayan protagonizado",
		},
		Past: {
			yo: "hubiera protagonizado",
			tú: "hubieras protagonizado",
			Ud: "hubiera protagonizado",
			nosotros: "hubiéramos protagonizado",
			vosotros: "hubierais protagonizado",
			Uds: "hubieran protagonizado",
		},
		Future: {
			yo: "hubiere protagonizado",
			tú: "hubieres protagonizado",
			Ud: "hubiere protagonizado",
			nosotros: "hubiéremos protagonizado",
			vosotros: "hubiereis protagonizado",
			Uds: "hubieren protagonizado",
		},
	},
}
