var publicar = {
	Indicative: {
		Present: {
			yo: "publico",
			tú: "publicas",
			Ud: "publica",
			nosotros: "publicamos",
			vosotros: "publicáis",
			Uds: "publican",
		},
		Preterite: {
			yo: "publiqué",
			tú: "publicaste",
			Ud: "publicó",
			nosotros: "publicamos",
			vosotros: "publicasteis",
			Uds: "publicaron",
		},
		Imperfect: {
			yo: "publicaba",
			tú: "publicabas",
			Ud: "publicaba",
			nosotros: "publicábamos",
			vosotros: "publicabais",
			Uds: "publicaban",
		},
		Conditional: {
			yo: "publicaría",
			tú: "publicarías",
			Ud: "publicaría",
			nosotros: "publicaríamos",
			vosotros: "publicaríais",
			Uds: "publicarían",
		},
		Future: {
			yo: "publicaré",
			tú: "publicarás",
			Ud: "publicará",
			nosotros: "publicaremos",
			vosotros: "publicaréis",
			Uds: "publicarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "publique",
			tú: "publiques",
			Ud: "publique",
			nosotros: "publiquemos",
			vosotros: "publiquéis",
			Uds: "publiquen",
		},
		Imperfect: {
			yo: "publicara",
			tú: "publicaras",
			Ud: "publicara",
			nosotros: "publicáramos",
			vosotros: "publicarais",
			Uds: "publicaran",
		},
		Imperfect2: {
			yo: "publicase",
			tú: "publicases",
			Ud: "publicase",
			nosotros: "publicásemos",
			vosotros: "publicaseis",
			Uds: "publicasen",
		},
		Future: {
			yo: "publicare",
			tú: "publicares",
			Ud: "publicare",
			nosotros: "publicáremos",
			vosotros: "publicareis",
			Uds: "publicaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "publica",
			Ud: "publique",
			nosotros: "publiquemos",
			vosotros: "publicad",
			Uds: "publiquen",
		},
		Negative: {
			tú: "no publiques",
			Ud: "no publique",
			nosotros: "no publiquemos",
			vosotros: "no publiquéis",
			Uds: "no publiquen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy publicando",
			tú: "estás publicando",
			Ud: "está publicando",
			nosotros: "estamos publicando",
			vosotros: "estáis publicando",
			Uds: "están publicando",
		},
		Preterite: {
			yo: "estuve publicando",
			tú: "estuviste publicando",
			Ud: "estuvo publicando",
			nosotros: "estuvimos publicando",
			vosotros: "estuvisteis publicando",
			Uds: "estuvieron publicando",
		},
		Imperfect: {
			Uds: "estaban publicando",
			yo: "estaba publicando",
			tú: "estabas publicando",
			Ud: "estaba publicando",
			nosotros: "estábamos publicando",
			vosotros: "estabais publicando",
		},
		Conditional: {
			yo: "estaría publicando",
			tú: "estarías publicando",
			Ud: "estaría publicando",
			nosotros: "estaríamos publicando",
			vosotros: "estaríais publicando",
			Uds: "estarían publicando",
		},
		Future: {
			yo: "estaré publicando",
			tú: "estarás publicando",
			Ud: "estará publicando",
			nosotros: "estaremos publicando",
			vosotros: "estaréis publicando",
			Uds: "estarán publicando",
		},
	},
	Perfect: {
		Present: {
			yo: "he publicado",
			tú: "has publicado",
			Ud: "ha publicado",
			nosotros: "hemos publicado",
			vosotros: "habéis publicado",
			Uds: "han publicado",
		},
		Preterite: {
			yo: "hube publicado",
			tú: "hubiste publicado",
			Ud: "hubo publicado",
			nosotros: "hubimos publicado",
			vosotros: "hubisteis publicado",
			Uds: "hubieron publicado",
		},
		Past: {
			yo: "había publicado",
			tú: "habías publicado",
			Ud: "había publicado",
			nosotros: "habíamos publicado",
			vosotros: "habíais publicado",
			Uds: "habían publicado",
		},
		Conditional: {
			yo: "habría publicado",
			tú: "habrías publicado",
			Ud: "habría publicado",
			nosotros: "habríamos publicado",
			vosotros: "habríais publicado",
			Uds: "habrían publicado",
		},
		Future: {
			yo: "habré publicado",
			tú: "habrás publicado",
			Ud: "habrá publicado",
			nosotros: "habremos publicado",
			vosotros: "habréis publicado",
			Uds: "habrán publicado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya publicado",
			tú: "hayas publicado",
			Ud: "haya publicado",
			nosotros: "hayamos publicado",
			vosotros: "hayáis publicado",
			Uds: "hayan publicado",
		},
		Past: {
			yo: "hubiera publicado",
			tú: "hubieras publicado",
			Ud: "hubiera publicado",
			nosotros: "hubiéramos publicado",
			vosotros: "hubierais publicado",
			Uds: "hubieran publicado",
		},
		Future: {
			yo: "hubiere publicado",
			tú: "hubieres publicado",
			Ud: "hubiere publicado",
			nosotros: "hubiéremos publicado",
			vosotros: "hubiereis publicado",
			Uds: "hubieren publicado",
		},
	},
}
