var pudrir = {
	Indicative: {
		Present: {
			yo: "pudro",
			tú: "pudres",
			Ud: "pudre",
			nosotros: "pudrimos",
			vosotros: "pudrís",
			Uds: "pudren",
		},
		Preterite: {
			yo: "pudrí",
			tú: "pudriste",
			Ud: "pudrió",
			nosotros: "pudrimos",
			vosotros: "pudristeis",
			Uds: "pudrieron",
		},
		Imperfect: {
			yo: "pudría",
			tú: "pudrías",
			Ud: "pudría",
			nosotros: "pudríamos",
			vosotros: "pudríais",
			Uds: "pudrían",
		},
		Conditional: {
			yo: "pudriría",
			tú: "pudrirías",
			Ud: "pudriría",
			nosotros: "pudriríamos",
			vosotros: "pudriríais",
			Uds: "pudrirían",
		},
		Future: {
			yo: "pudriré",
			tú: "pudrirás",
			Ud: "pudrirá",
			nosotros: "pudriremos",
			vosotros: "pudriréis",
			Uds: "pudrirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "pudra",
			tú: "pudras",
			Ud: "pudra",
			nosotros: "pudramos",
			vosotros: "pudráis",
			Uds: "pudran",
		},
		Imperfect: {
			yo: "pudriera",
			tú: "pudrieras",
			Ud: "pudriera",
			nosotros: "pudriéramos",
			vosotros: "pudrierais",
			Uds: "pudrieran",
		},
		Imperfect2: {
			yo: "pudriese",
			tú: "pudrieses",
			Ud: "pudriese",
			nosotros: "pudriésemos",
			vosotros: "pudrieseis",
			Uds: "pudriesen",
		},
		Future: {
			yo: "pudriere",
			tú: "pudrieres",
			Ud: "pudriere",
			nosotros: "pudriéremos",
			vosotros: "pudriereis",
			Uds: "pudrieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "pudre",
			Ud: "pudra",
			nosotros: "pudramos",
			vosotros: "pudrid",
			Uds: "pudran",
		},
		Negative: {
			tú: "no pudras",
			Ud: "no pudra",
			nosotros: "no pudramos",
			vosotros: "no pudráis",
			Uds: "no pudran",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy pudriendo",
			tú: "estás pudriendo",
			Ud: "está pudriendo",
			nosotros: "estamos pudriendo",
			vosotros: "estáis pudriendo",
			Uds: "están pudriendo",
		},
		Preterite: {
			yo: "estuve pudriendo",
			tú: "estuviste pudriendo",
			Ud: "estuvo pudriendo",
			nosotros: "estuvimos pudriendo",
			vosotros: "estuvisteis pudriendo",
			Uds: "estuvieron pudriendo",
		},
		Imperfect: {
			Uds: "estaban pudriendo",
			yo: "estaba pudriendo",
			tú: "estabas pudriendo",
			Ud: "estaba pudriendo",
			nosotros: "estábamos pudriendo",
			vosotros: "estabais pudriendo",
		},
		Conditional: {
			yo: "estaría pudriendo",
			tú: "estarías pudriendo",
			Ud: "estaría pudriendo",
			nosotros: "estaríamos pudriendo",
			vosotros: "estaríais pudriendo",
			Uds: "estarían pudriendo",
		},
		Future: {
			yo: "estaré pudriendo",
			tú: "estarás pudriendo",
			Ud: "estará pudriendo",
			nosotros: "estaremos pudriendo",
			vosotros: "estaréis pudriendo",
			Uds: "estarán pudriendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he podrido",
			tú: "has podrido",
			Ud: "ha podrido",
			nosotros: "hemos podrido",
			vosotros: "habéis podrido",
			Uds: "han podrido",
		},
		Preterite: {
			yo: "hube podrido",
			tú: "hubiste podrido",
			Ud: "hubo podrido",
			nosotros: "hubimos podrido",
			vosotros: "hubisteis podrido",
			Uds: "hubieron podrido",
		},
		Past: {
			yo: "había podrido",
			tú: "habías podrido",
			Ud: "había podrido",
			nosotros: "habíamos podrido",
			vosotros: "habíais podrido",
			Uds: "habían podrido",
		},
		Conditional: {
			yo: "habría podrido",
			tú: "habrías podrido",
			Ud: "habría podrido",
			nosotros: "habríamos podrido",
			vosotros: "habríais podrido",
			Uds: "habrían podrido",
		},
		Future: {
			yo: "habré podrido",
			tú: "habrás podrido",
			Ud: "habrá podrido",
			nosotros: "habremos podrido",
			vosotros: "habréis podrido",
			Uds: "habrán podrido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya podrido",
			tú: "hayas podrido",
			Ud: "haya podrido",
			nosotros: "hayamos podrido",
			vosotros: "hayáis podrido",
			Uds: "hayan podrido",
		},
		Past: {
			yo: "hubiera podrido",
			tú: "hubieras podrido",
			Ud: "hubiera podrido",
			nosotros: "hubiéramos podrido",
			vosotros: "hubierais podrido",
			Uds: "hubieran podrido",
		},
		Future: {
			yo: "hubiere podrido",
			tú: "hubieres podrido",
			Ud: "hubiere podrido",
			nosotros: "hubiéremos podrido",
			vosotros: "hubiereis podrido",
			Uds: "hubieren podrido",
		},
	},
}
