var pugnar = {
	Indicative: {
		Present: {
			yo: "pugno",
			tú: "pugnas",
			Ud: "pugna",
			nosotros: "pugnamos",
			vosotros: "pugnáis",
			Uds: "pugnan",
		},
		Preterite: {
			yo: "pugné",
			tú: "pugnaste",
			Ud: "pugnó",
			nosotros: "pugnamos",
			vosotros: "pugnasteis",
			Uds: "pugnaron",
		},
		Imperfect: {
			yo: "pugnaba",
			tú: "pugnabas",
			Ud: "pugnaba",
			nosotros: "pugnábamos",
			vosotros: "pugnabais",
			Uds: "pugnaban",
		},
		Conditional: {
			yo: "pugnaría",
			tú: "pugnarías",
			Ud: "pugnaría",
			nosotros: "pugnaríamos",
			vosotros: "pugnaríais",
			Uds: "pugnarían",
		},
		Future: {
			yo: "pugnaré",
			tú: "pugnarás",
			Ud: "pugnará",
			nosotros: "pugnaremos",
			vosotros: "pugnaréis",
			Uds: "pugnarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "pugne",
			tú: "pugnes",
			Ud: "pugne",
			nosotros: "pugnemos",
			vosotros: "pugnéis",
			Uds: "pugnen",
		},
		Imperfect: {
			yo: "pugnara",
			tú: "pugnaras",
			Ud: "pugnara",
			nosotros: "pugnáramos",
			vosotros: "pugnarais",
			Uds: "pugnaran",
		},
		Imperfect2: {
			yo: "pugnase",
			tú: "pugnases",
			Ud: "pugnase",
			nosotros: "pugnásemos",
			vosotros: "pugnaseis",
			Uds: "pugnasen",
		},
		Future: {
			yo: "pugnare",
			tú: "pugnares",
			Ud: "pugnare",
			nosotros: "pugnáremos",
			vosotros: "pugnareis",
			Uds: "pugnaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "pugna",
			Ud: "pugne",
			nosotros: "pugnemos",
			vosotros: "pugnad",
			Uds: "pugnen",
		},
		Negative: {
			tú: "no pugnes",
			Ud: "no pugne",
			nosotros: "no pugnemos",
			vosotros: "no pugnéis",
			Uds: "no pugnen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy pugnando",
			tú: "estás pugnando",
			Ud: "está pugnando",
			nosotros: "estamos pugnando",
			vosotros: "estáis pugnando",
			Uds: "están pugnando",
		},
		Preterite: {
			yo: "estuve pugnando",
			tú: "estuviste pugnando",
			Ud: "estuvo pugnando",
			nosotros: "estuvimos pugnando",
			vosotros: "estuvisteis pugnando",
			Uds: "estuvieron pugnando",
		},
		Imperfect: {
			Uds: "estaban pugnando",
			yo: "estaba pugnando",
			tú: "estabas pugnando",
			Ud: "estaba pugnando",
			nosotros: "estábamos pugnando",
			vosotros: "estabais pugnando",
		},
		Conditional: {
			yo: "estaría pugnando",
			tú: "estarías pugnando",
			Ud: "estaría pugnando",
			nosotros: "estaríamos pugnando",
			vosotros: "estaríais pugnando",
			Uds: "estarían pugnando",
		},
		Future: {
			yo: "estaré pugnando",
			tú: "estarás pugnando",
			Ud: "estará pugnando",
			nosotros: "estaremos pugnando",
			vosotros: "estaréis pugnando",
			Uds: "estarán pugnando",
		},
	},
	Perfect: {
		Present: {
			yo: "he pugnado",
			tú: "has pugnado",
			Ud: "ha pugnado",
			nosotros: "hemos pugnado",
			vosotros: "habéis pugnado",
			Uds: "han pugnado",
		},
		Preterite: {
			yo: "hube pugnado",
			tú: "hubiste pugnado",
			Ud: "hubo pugnado",
			nosotros: "hubimos pugnado",
			vosotros: "hubisteis pugnado",
			Uds: "hubieron pugnado",
		},
		Past: {
			yo: "había pugnado",
			tú: "habías pugnado",
			Ud: "había pugnado",
			nosotros: "habíamos pugnado",
			vosotros: "habíais pugnado",
			Uds: "habían pugnado",
		},
		Conditional: {
			yo: "habría pugnado",
			tú: "habrías pugnado",
			Ud: "habría pugnado",
			nosotros: "habríamos pugnado",
			vosotros: "habríais pugnado",
			Uds: "habrían pugnado",
		},
		Future: {
			yo: "habré pugnado",
			tú: "habrás pugnado",
			Ud: "habrá pugnado",
			nosotros: "habremos pugnado",
			vosotros: "habréis pugnado",
			Uds: "habrán pugnado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya pugnado",
			tú: "hayas pugnado",
			Ud: "haya pugnado",
			nosotros: "hayamos pugnado",
			vosotros: "hayáis pugnado",
			Uds: "hayan pugnado",
		},
		Past: {
			yo: "hubiera pugnado",
			tú: "hubieras pugnado",
			Ud: "hubiera pugnado",
			nosotros: "hubiéramos pugnado",
			vosotros: "hubierais pugnado",
			Uds: "hubieran pugnado",
		},
		Future: {
			yo: "hubiere pugnado",
			tú: "hubieres pugnado",
			Ud: "hubiere pugnado",
			nosotros: "hubiéremos pugnado",
			vosotros: "hubiereis pugnado",
			Uds: "hubieren pugnado",
		},
	},
}
