var pulsar = {
	Indicative: {
		Present: {
			yo: "pulso",
			tú: "pulsas",
			Ud: "pulsa",
			nosotros: "pulsamos",
			vosotros: "pulsáis",
			Uds: "pulsan",
		},
		Preterite: {
			yo: "pulsé",
			tú: "pulsaste",
			Ud: "pulsó",
			nosotros: "pulsamos",
			vosotros: "pulsasteis",
			Uds: "pulsaron",
		},
		Imperfect: {
			yo: "pulsaba",
			tú: "pulsabas",
			Ud: "pulsaba",
			nosotros: "pulsábamos",
			vosotros: "pulsabais",
			Uds: "pulsaban",
		},
		Conditional: {
			yo: "pulsaría",
			tú: "pulsarías",
			Ud: "pulsaría",
			nosotros: "pulsaríamos",
			vosotros: "pulsaríais",
			Uds: "pulsarían",
		},
		Future: {
			yo: "pulsaré",
			tú: "pulsarás",
			Ud: "pulsará",
			nosotros: "pulsaremos",
			vosotros: "pulsaréis",
			Uds: "pulsarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "pulse",
			tú: "pulses",
			Ud: "pulse",
			nosotros: "pulsemos",
			vosotros: "pulséis",
			Uds: "pulsen",
		},
		Imperfect: {
			yo: "pulsara",
			tú: "pulsaras",
			Ud: "pulsara",
			nosotros: "pulsáramos",
			vosotros: "pulsarais",
			Uds: "pulsaran",
		},
		Imperfect2: {
			yo: "pulsase",
			tú: "pulsases",
			Ud: "pulsase",
			nosotros: "pulsásemos",
			vosotros: "pulsaseis",
			Uds: "pulsasen",
		},
		Future: {
			yo: "pulsare",
			tú: "pulsares",
			Ud: "pulsare",
			nosotros: "pulsáremos",
			vosotros: "pulsareis",
			Uds: "pulsaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "pulsa",
			Ud: "pulse",
			nosotros: "pulsemos",
			vosotros: "pulsad",
			Uds: "pulsen",
		},
		Negative: {
			tú: "no pulses",
			Ud: "no pulse",
			nosotros: "no pulsemos",
			vosotros: "no pulséis",
			Uds: "no pulsen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy pulsando",
			tú: "estás pulsando",
			Ud: "está pulsando",
			nosotros: "estamos pulsando",
			vosotros: "estáis pulsando",
			Uds: "están pulsando",
		},
		Preterite: {
			yo: "estuve pulsando",
			tú: "estuviste pulsando",
			Ud: "estuvo pulsando",
			nosotros: "estuvimos pulsando",
			vosotros: "estuvisteis pulsando",
			Uds: "estuvieron pulsando",
		},
		Imperfect: {
			Uds: "estaban pulsando",
			yo: "estaba pulsando",
			tú: "estabas pulsando",
			Ud: "estaba pulsando",
			nosotros: "estábamos pulsando",
			vosotros: "estabais pulsando",
		},
		Conditional: {
			yo: "estaría pulsando",
			tú: "estarías pulsando",
			Ud: "estaría pulsando",
			nosotros: "estaríamos pulsando",
			vosotros: "estaríais pulsando",
			Uds: "estarían pulsando",
		},
		Future: {
			yo: "estaré pulsando",
			tú: "estarás pulsando",
			Ud: "estará pulsando",
			nosotros: "estaremos pulsando",
			vosotros: "estaréis pulsando",
			Uds: "estarán pulsando",
		},
	},
	Perfect: {
		Present: {
			yo: "he pulsado",
			tú: "has pulsado",
			Ud: "ha pulsado",
			nosotros: "hemos pulsado",
			vosotros: "habéis pulsado",
			Uds: "han pulsado",
		},
		Preterite: {
			yo: "hube pulsado",
			tú: "hubiste pulsado",
			Ud: "hubo pulsado",
			nosotros: "hubimos pulsado",
			vosotros: "hubisteis pulsado",
			Uds: "hubieron pulsado",
		},
		Past: {
			yo: "había pulsado",
			tú: "habías pulsado",
			Ud: "había pulsado",
			nosotros: "habíamos pulsado",
			vosotros: "habíais pulsado",
			Uds: "habían pulsado",
		},
		Conditional: {
			yo: "habría pulsado",
			tú: "habrías pulsado",
			Ud: "habría pulsado",
			nosotros: "habríamos pulsado",
			vosotros: "habríais pulsado",
			Uds: "habrían pulsado",
		},
		Future: {
			yo: "habré pulsado",
			tú: "habrás pulsado",
			Ud: "habrá pulsado",
			nosotros: "habremos pulsado",
			vosotros: "habréis pulsado",
			Uds: "habrán pulsado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya pulsado",
			tú: "hayas pulsado",
			Ud: "haya pulsado",
			nosotros: "hayamos pulsado",
			vosotros: "hayáis pulsado",
			Uds: "hayan pulsado",
		},
		Past: {
			yo: "hubiera pulsado",
			tú: "hubieras pulsado",
			Ud: "hubiera pulsado",
			nosotros: "hubiéramos pulsado",
			vosotros: "hubierais pulsado",
			Uds: "hubieran pulsado",
		},
		Future: {
			yo: "hubiere pulsado",
			tú: "hubieres pulsado",
			Ud: "hubiere pulsado",
			nosotros: "hubiéremos pulsado",
			vosotros: "hubiereis pulsado",
			Uds: "hubieren pulsado",
		},
	},
}
