var quedar = {
	Indicative: {
		Present: {
			yo: "quedo",
			tú: "quedas",
			Ud: "queda",
			nosotros: "quedamos",
			vosotros: "quedáis",
			Uds: "quedan",
		},
		Preterite: {
			yo: "quedé",
			tú: "quedaste",
			Ud: "quedó",
			nosotros: "quedamos",
			vosotros: "quedasteis",
			Uds: "quedaron",
		},
		Imperfect: {
			yo: "quedaba",
			tú: "quedabas",
			Ud: "quedaba",
			nosotros: "quedábamos",
			vosotros: "quedabais",
			Uds: "quedaban",
		},
		Conditional: {
			yo: "quedaría",
			tú: "quedarías",
			Ud: "quedaría",
			nosotros: "quedaríamos",
			vosotros: "quedaríais",
			Uds: "quedarían",
		},
		Future: {
			yo: "quedaré",
			tú: "quedarás",
			Ud: "quedará",
			nosotros: "quedaremos",
			vosotros: "quedaréis",
			Uds: "quedarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "quede",
			tú: "quedes",
			Ud: "quede",
			nosotros: "quedemos",
			vosotros: "quedéis",
			Uds: "queden",
		},
		Imperfect: {
			yo: "quedara",
			tú: "quedaras",
			Ud: "quedara",
			nosotros: "quedáramos",
			vosotros: "quedarais",
			Uds: "quedaran",
		},
		Imperfect2: {
			yo: "quedase",
			tú: "quedases",
			Ud: "quedase",
			nosotros: "quedásemos",
			vosotros: "quedaseis",
			Uds: "quedasen",
		},
		Future: {
			yo: "quedare",
			tú: "quedares",
			Ud: "quedare",
			nosotros: "quedáremos",
			vosotros: "quedareis",
			Uds: "quedaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "queda",
			Ud: "quede",
			nosotros: "quedemos",
			vosotros: "quedad",
			Uds: "queden",
		},
		Negative: {
			tú: "no quedes",
			Ud: "no quede",
			nosotros: "no quedemos",
			vosotros: "no quedéis",
			Uds: "no queden",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy quedando",
			tú: "estás quedando",
			Ud: "está quedando",
			nosotros: "estamos quedando",
			vosotros: "estáis quedando",
			Uds: "están quedando",
		},
		Preterite: {
			yo: "estuve quedando",
			tú: "estuviste quedando",
			Ud: "estuvo quedando",
			nosotros: "estuvimos quedando",
			vosotros: "estuvisteis quedando",
			Uds: "estuvieron quedando",
		},
		Imperfect: {
			Uds: "estaban quedando",
			yo: "estaba quedando",
			tú: "estabas quedando",
			Ud: "estaba quedando",
			nosotros: "estábamos quedando",
			vosotros: "estabais quedando",
		},
		Conditional: {
			yo: "estaría quedando",
			tú: "estarías quedando",
			Ud: "estaría quedando",
			nosotros: "estaríamos quedando",
			vosotros: "estaríais quedando",
			Uds: "estarían quedando",
		},
		Future: {
			yo: "estaré quedando",
			tú: "estarás quedando",
			Ud: "estará quedando",
			nosotros: "estaremos quedando",
			vosotros: "estaréis quedando",
			Uds: "estarán quedando",
		},
	},
	Perfect: {
		Present: {
			yo: "he quedado",
			tú: "has quedado",
			Ud: "ha quedado",
			nosotros: "hemos quedado",
			vosotros: "habéis quedado",
			Uds: "han quedado",
		},
		Preterite: {
			yo: "hube quedado",
			tú: "hubiste quedado",
			Ud: "hubo quedado",
			nosotros: "hubimos quedado",
			vosotros: "hubisteis quedado",
			Uds: "hubieron quedado",
		},
		Past: {
			yo: "había quedado",
			tú: "habías quedado",
			Ud: "había quedado",
			nosotros: "habíamos quedado",
			vosotros: "habíais quedado",
			Uds: "habían quedado",
		},
		Conditional: {
			yo: "habría quedado",
			tú: "habrías quedado",
			Ud: "habría quedado",
			nosotros: "habríamos quedado",
			vosotros: "habríais quedado",
			Uds: "habrían quedado",
		},
		Future: {
			yo: "habré quedado",
			tú: "habrás quedado",
			Ud: "habrá quedado",
			nosotros: "habremos quedado",
			vosotros: "habréis quedado",
			Uds: "habrán quedado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya quedado",
			tú: "hayas quedado",
			Ud: "haya quedado",
			nosotros: "hayamos quedado",
			vosotros: "hayáis quedado",
			Uds: "hayan quedado",
		},
		Past: {
			yo: "hubiera quedado",
			tú: "hubieras quedado",
			Ud: "hubiera quedado",
			nosotros: "hubiéramos quedado",
			vosotros: "hubierais quedado",
			Uds: "hubieran quedado",
		},
		Future: {
			yo: "hubiere quedado",
			tú: "hubieres quedado",
			Ud: "hubiere quedado",
			nosotros: "hubiéremos quedado",
			vosotros: "hubiereis quedado",
			Uds: "hubieren quedado",
		},
	},
}
