var rascar = {
	Indicative: {
		Present: {
			yo: "rasco",
			tú: "rascas",
			Ud: "rasca",
			nosotros: "rascamos",
			vosotros: "rascáis",
			Uds: "rascan",
		},
		Preterite: {
			yo: "rasqué",
			tú: "rascaste",
			Ud: "rascó",
			nosotros: "rascamos",
			vosotros: "rascasteis",
			Uds: "rascaron",
		},
		Imperfect: {
			yo: "rascaba",
			tú: "rascabas",
			Ud: "rascaba",
			nosotros: "rascábamos",
			vosotros: "rascabais",
			Uds: "rascaban",
		},
		Conditional: {
			yo: "rascaría",
			tú: "rascarías",
			Ud: "rascaría",
			nosotros: "rascaríamos",
			vosotros: "rascaríais",
			Uds: "rascarían",
		},
		Future: {
			yo: "rascaré",
			tú: "rascarás",
			Ud: "rascará",
			nosotros: "rascaremos",
			vosotros: "rascaréis",
			Uds: "rascarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "rasque",
			tú: "rasques",
			Ud: "rasque",
			nosotros: "rasquemos",
			vosotros: "rasquéis",
			Uds: "rasquen",
		},
		Imperfect: {
			yo: "rascara",
			tú: "rascaras",
			Ud: "rascara",
			nosotros: "rascáramos",
			vosotros: "rascarais",
			Uds: "rascaran",
		},
		Imperfect2: {
			yo: "rascase",
			tú: "rascases",
			Ud: "rascase",
			nosotros: "rascásemos",
			vosotros: "rascaseis",
			Uds: "rascasen",
		},
		Future: {
			yo: "rascare",
			tú: "rascares",
			Ud: "rascare",
			nosotros: "rascáremos",
			vosotros: "rascareis",
			Uds: "rascaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "rasca",
			Ud: "rasque",
			nosotros: "rasquemos",
			vosotros: "rascad",
			Uds: "rasquen",
		},
		Negative: {
			tú: "no rasques",
			Ud: "no rasque",
			nosotros: "no rasquemos",
			vosotros: "no rasquéis",
			Uds: "no rasquen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy rascando",
			tú: "estás rascando",
			Ud: "está rascando",
			nosotros: "estamos rascando",
			vosotros: "estáis rascando",
			Uds: "están rascando",
		},
		Preterite: {
			yo: "estuve rascando",
			tú: "estuviste rascando",
			Ud: "estuvo rascando",
			nosotros: "estuvimos rascando",
			vosotros: "estuvisteis rascando",
			Uds: "estuvieron rascando",
		},
		Imperfect: {
			Uds: "estaban rascando",
			yo: "estaba rascando",
			tú: "estabas rascando",
			Ud: "estaba rascando",
			nosotros: "estábamos rascando",
			vosotros: "estabais rascando",
		},
		Conditional: {
			yo: "estaría rascando",
			tú: "estarías rascando",
			Ud: "estaría rascando",
			nosotros: "estaríamos rascando",
			vosotros: "estaríais rascando",
			Uds: "estarían rascando",
		},
		Future: {
			yo: "estaré rascando",
			tú: "estarás rascando",
			Ud: "estará rascando",
			nosotros: "estaremos rascando",
			vosotros: "estaréis rascando",
			Uds: "estarán rascando",
		},
	},
	Perfect: {
		Present: {
			yo: "he rascado",
			tú: "has rascado",
			Ud: "ha rascado",
			nosotros: "hemos rascado",
			vosotros: "habéis rascado",
			Uds: "han rascado",
		},
		Preterite: {
			yo: "hube rascado",
			tú: "hubiste rascado",
			Ud: "hubo rascado",
			nosotros: "hubimos rascado",
			vosotros: "hubisteis rascado",
			Uds: "hubieron rascado",
		},
		Past: {
			yo: "había rascado",
			tú: "habías rascado",
			Ud: "había rascado",
			nosotros: "habíamos rascado",
			vosotros: "habíais rascado",
			Uds: "habían rascado",
		},
		Conditional: {
			yo: "habría rascado",
			tú: "habrías rascado",
			Ud: "habría rascado",
			nosotros: "habríamos rascado",
			vosotros: "habríais rascado",
			Uds: "habrían rascado",
		},
		Future: {
			yo: "habré rascado",
			tú: "habrás rascado",
			Ud: "habrá rascado",
			nosotros: "habremos rascado",
			vosotros: "habréis rascado",
			Uds: "habrán rascado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya rascado",
			tú: "hayas rascado",
			Ud: "haya rascado",
			nosotros: "hayamos rascado",
			vosotros: "hayáis rascado",
			Uds: "hayan rascado",
		},
		Past: {
			yo: "hubiera rascado",
			tú: "hubieras rascado",
			Ud: "hubiera rascado",
			nosotros: "hubiéramos rascado",
			vosotros: "hubierais rascado",
			Uds: "hubieran rascado",
		},
		Future: {
			yo: "hubiere rascado",
			tú: "hubieres rascado",
			Ud: "hubiere rascado",
			nosotros: "hubiéremos rascado",
			vosotros: "hubiereis rascado",
			Uds: "hubieren rascado",
		},
	},
}
