var raspar = {
	Indicative: {
		Present: {
			yo: "raspo",
			tú: "raspas",
			Ud: "raspa",
			nosotros: "raspamos",
			vosotros: "raspáis",
			Uds: "raspan",
		},
		Preterite: {
			yo: "raspé",
			tú: "raspaste",
			Ud: "raspó",
			nosotros: "raspamos",
			vosotros: "raspasteis",
			Uds: "rasparon",
		},
		Imperfect: {
			yo: "raspaba",
			tú: "raspabas",
			Ud: "raspaba",
			nosotros: "raspábamos",
			vosotros: "raspabais",
			Uds: "raspaban",
		},
		Conditional: {
			yo: "rasparía",
			tú: "rasparías",
			Ud: "rasparía",
			nosotros: "rasparíamos",
			vosotros: "rasparíais",
			Uds: "rasparían",
		},
		Future: {
			yo: "rasparé",
			tú: "rasparás",
			Ud: "raspará",
			nosotros: "rasparemos",
			vosotros: "rasparéis",
			Uds: "rasparán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "raspe",
			tú: "raspes",
			Ud: "raspe",
			nosotros: "raspemos",
			vosotros: "raspéis",
			Uds: "raspen",
		},
		Imperfect: {
			yo: "raspara",
			tú: "rasparas",
			Ud: "raspara",
			nosotros: "raspáramos",
			vosotros: "rasparais",
			Uds: "rasparan",
		},
		Imperfect2: {
			yo: "raspase",
			tú: "raspases",
			Ud: "raspase",
			nosotros: "raspásemos",
			vosotros: "raspaseis",
			Uds: "raspasen",
		},
		Future: {
			yo: "raspare",
			tú: "raspares",
			Ud: "raspare",
			nosotros: "raspáremos",
			vosotros: "raspareis",
			Uds: "rasparen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "raspa",
			Ud: "raspe",
			nosotros: "raspemos",
			vosotros: "raspad",
			Uds: "raspen",
		},
		Negative: {
			tú: "no raspes",
			Ud: "no raspe",
			nosotros: "no raspemos",
			vosotros: "no raspéis",
			Uds: "no raspen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy raspando",
			tú: "estás raspando",
			Ud: "está raspando",
			nosotros: "estamos raspando",
			vosotros: "estáis raspando",
			Uds: "están raspando",
		},
		Preterite: {
			yo: "estuve raspando",
			tú: "estuviste raspando",
			Ud: "estuvo raspando",
			nosotros: "estuvimos raspando",
			vosotros: "estuvisteis raspando",
			Uds: "estuvieron raspando",
		},
		Imperfect: {
			Uds: "estaban raspando",
			yo: "estaba raspando",
			tú: "estabas raspando",
			Ud: "estaba raspando",
			nosotros: "estábamos raspando",
			vosotros: "estabais raspando",
		},
		Conditional: {
			yo: "estaría raspando",
			tú: "estarías raspando",
			Ud: "estaría raspando",
			nosotros: "estaríamos raspando",
			vosotros: "estaríais raspando",
			Uds: "estarían raspando",
		},
		Future: {
			yo: "estaré raspando",
			tú: "estarás raspando",
			Ud: "estará raspando",
			nosotros: "estaremos raspando",
			vosotros: "estaréis raspando",
			Uds: "estarán raspando",
		},
	},
	Perfect: {
		Present: {
			yo: "he raspado",
			tú: "has raspado",
			Ud: "ha raspado",
			nosotros: "hemos raspado",
			vosotros: "habéis raspado",
			Uds: "han raspado",
		},
		Preterite: {
			yo: "hube raspado",
			tú: "hubiste raspado",
			Ud: "hubo raspado",
			nosotros: "hubimos raspado",
			vosotros: "hubisteis raspado",
			Uds: "hubieron raspado",
		},
		Past: {
			yo: "había raspado",
			tú: "habías raspado",
			Ud: "había raspado",
			nosotros: "habíamos raspado",
			vosotros: "habíais raspado",
			Uds: "habían raspado",
		},
		Conditional: {
			yo: "habría raspado",
			tú: "habrías raspado",
			Ud: "habría raspado",
			nosotros: "habríamos raspado",
			vosotros: "habríais raspado",
			Uds: "habrían raspado",
		},
		Future: {
			yo: "habré raspado",
			tú: "habrás raspado",
			Ud: "habrá raspado",
			nosotros: "habremos raspado",
			vosotros: "habréis raspado",
			Uds: "habrán raspado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya raspado",
			tú: "hayas raspado",
			Ud: "haya raspado",
			nosotros: "hayamos raspado",
			vosotros: "hayáis raspado",
			Uds: "hayan raspado",
		},
		Past: {
			yo: "hubiera raspado",
			tú: "hubieras raspado",
			Ud: "hubiera raspado",
			nosotros: "hubiéramos raspado",
			vosotros: "hubierais raspado",
			Uds: "hubieran raspado",
		},
		Future: {
			yo: "hubiere raspado",
			tú: "hubieres raspado",
			Ud: "hubiere raspado",
			nosotros: "hubiéremos raspado",
			vosotros: "hubiereis raspado",
			Uds: "hubieren raspado",
		},
	},
}
