var reafirmar = {
	Indicative: {
		Present: {
			yo: "reafirmo",
			tú: "reafirmas",
			Ud: "reafirma",
			nosotros: "reafirmamos",
			vosotros: "reafirmáis",
			Uds: "reafirman",
		},
		Preterite: {
			yo: "reafirmé",
			tú: "reafirmaste",
			Ud: "reafirmó",
			nosotros: "reafirmamos",
			vosotros: "reafirmasteis",
			Uds: "reafirmaron",
		},
		Imperfect: {
			yo: "reafirmaba",
			tú: "reafirmabas",
			Ud: "reafirmaba",
			nosotros: "reafirmábamos",
			vosotros: "reafirmabais",
			Uds: "reafirmaban",
		},
		Conditional: {
			yo: "reafirmaría",
			tú: "reafirmarías",
			Ud: "reafirmaría",
			nosotros: "reafirmaríamos",
			vosotros: "reafirmaríais",
			Uds: "reafirmarían",
		},
		Future: {
			yo: "reafirmaré",
			tú: "reafirmarás",
			Ud: "reafirmará",
			nosotros: "reafirmaremos",
			vosotros: "reafirmaréis",
			Uds: "reafirmarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "reafirme",
			tú: "reafirmes",
			Ud: "reafirme",
			nosotros: "reafirmemos",
			vosotros: "reafirméis",
			Uds: "reafirmen",
		},
		Imperfect: {
			yo: "reafirmara",
			tú: "reafirmaras",
			Ud: "reafirmara",
			nosotros: "reafirmáramos",
			vosotros: "reafirmarais",
			Uds: "reafirmaran",
		},
		Imperfect2: {
			yo: "reafirmase",
			tú: "reafirmases",
			Ud: "reafirmase",
			nosotros: "reafirmásemos",
			vosotros: "reafirmaseis",
			Uds: "reafirmasen",
		},
		Future: {
			yo: "reafirmare",
			tú: "reafirmares",
			Ud: "reafirmare",
			nosotros: "reafirmáremos",
			vosotros: "reafirmareis",
			Uds: "reafirmaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "reafirma",
			Ud: "reafirme",
			nosotros: "reafirmemos",
			vosotros: "reafirmad",
			Uds: "reafirmen",
		},
		Negative: {
			tú: "no reafirmes",
			Ud: "no reafirme",
			nosotros: "no reafirmemos",
			vosotros: "no reafirméis",
			Uds: "no reafirmen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy reafirmando",
			tú: "estás reafirmando",
			Ud: "está reafirmando",
			nosotros: "estamos reafirmando",
			vosotros: "estáis reafirmando",
			Uds: "están reafirmando",
		},
		Preterite: {
			yo: "estuve reafirmando",
			tú: "estuviste reafirmando",
			Ud: "estuvo reafirmando",
			nosotros: "estuvimos reafirmando",
			vosotros: "estuvisteis reafirmando",
			Uds: "estuvieron reafirmando",
		},
		Imperfect: {
			Uds: "estaban reafirmando",
			yo: "estaba reafirmando",
			tú: "estabas reafirmando",
			Ud: "estaba reafirmando",
			nosotros: "estábamos reafirmando",
			vosotros: "estabais reafirmando",
		},
		Conditional: {
			yo: "estaría reafirmando",
			tú: "estarías reafirmando",
			Ud: "estaría reafirmando",
			nosotros: "estaríamos reafirmando",
			vosotros: "estaríais reafirmando",
			Uds: "estarían reafirmando",
		},
		Future: {
			yo: "estaré reafirmando",
			tú: "estarás reafirmando",
			Ud: "estará reafirmando",
			nosotros: "estaremos reafirmando",
			vosotros: "estaréis reafirmando",
			Uds: "estarán reafirmando",
		},
	},
	Perfect: {
		Present: {
			yo: "he reafirmado",
			tú: "has reafirmado",
			Ud: "ha reafirmado",
			nosotros: "hemos reafirmado",
			vosotros: "habéis reafirmado",
			Uds: "han reafirmado",
		},
		Preterite: {
			yo: "hube reafirmado",
			tú: "hubiste reafirmado",
			Ud: "hubo reafirmado",
			nosotros: "hubimos reafirmado",
			vosotros: "hubisteis reafirmado",
			Uds: "hubieron reafirmado",
		},
		Past: {
			yo: "había reafirmado",
			tú: "habías reafirmado",
			Ud: "había reafirmado",
			nosotros: "habíamos reafirmado",
			vosotros: "habíais reafirmado",
			Uds: "habían reafirmado",
		},
		Conditional: {
			yo: "habría reafirmado",
			tú: "habrías reafirmado",
			Ud: "habría reafirmado",
			nosotros: "habríamos reafirmado",
			vosotros: "habríais reafirmado",
			Uds: "habrían reafirmado",
		},
		Future: {
			yo: "habré reafirmado",
			tú: "habrás reafirmado",
			Ud: "habrá reafirmado",
			nosotros: "habremos reafirmado",
			vosotros: "habréis reafirmado",
			Uds: "habrán reafirmado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya reafirmado",
			tú: "hayas reafirmado",
			Ud: "haya reafirmado",
			nosotros: "hayamos reafirmado",
			vosotros: "hayáis reafirmado",
			Uds: "hayan reafirmado",
		},
		Past: {
			yo: "hubiera reafirmado",
			tú: "hubieras reafirmado",
			Ud: "hubiera reafirmado",
			nosotros: "hubiéramos reafirmado",
			vosotros: "hubierais reafirmado",
			Uds: "hubieran reafirmado",
		},
		Future: {
			yo: "hubiere reafirmado",
			tú: "hubieres reafirmado",
			Ud: "hubiere reafirmado",
			nosotros: "hubiéremos reafirmado",
			vosotros: "hubiereis reafirmado",
			Uds: "hubieren reafirmado",
		},
	},
}
