var rebatir = {
	Indicative: {
		Present: {
			yo: "rebato",
			tú: "rebates",
			Ud: "rebate",
			nosotros: "rebatimos",
			vosotros: "rebatís",
			Uds: "rebaten",
		},
		Preterite: {
			yo: "rebatí",
			tú: "rebatiste",
			Ud: "rebatió",
			nosotros: "rebatimos",
			vosotros: "rebatisteis",
			Uds: "rebatieron",
		},
		Imperfect: {
			yo: "rebatía",
			tú: "rebatías",
			Ud: "rebatía",
			nosotros: "rebatíamos",
			vosotros: "rebatíais",
			Uds: "rebatían",
		},
		Conditional: {
			yo: "rebatiría",
			tú: "rebatirías",
			Ud: "rebatiría",
			nosotros: "rebatiríamos",
			vosotros: "rebatiríais",
			Uds: "rebatirían",
		},
		Future: {
			yo: "rebatiré",
			tú: "rebatirás",
			Ud: "rebatirá",
			nosotros: "rebatiremos",
			vosotros: "rebatiréis",
			Uds: "rebatirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "rebata",
			tú: "rebatas",
			Ud: "rebata",
			nosotros: "rebatamos",
			vosotros: "rebatáis",
			Uds: "rebatan",
		},
		Imperfect: {
			yo: "rebatiera",
			tú: "rebatieras",
			Ud: "rebatiera",
			nosotros: "rebatiéramos",
			vosotros: "rebatierais",
			Uds: "rebatieran",
		},
		Imperfect2: {
			yo: "rebatiese",
			tú: "rebatieses",
			Ud: "rebatiese",
			nosotros: "rebatiésemos",
			vosotros: "rebatieseis",
			Uds: "rebatiesen",
		},
		Future: {
			yo: "rebatiere",
			tú: "rebatieres",
			Ud: "rebatiere",
			nosotros: "rebatiéremos",
			vosotros: "rebatiereis",
			Uds: "rebatieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "rebate",
			Ud: "rebata",
			nosotros: "rebatamos",
			vosotros: "rebatid",
			Uds: "rebatan",
		},
		Negative: {
			tú: "no rebatas",
			Ud: "no rebata",
			nosotros: "no rebatamos",
			vosotros: "no rebatáis",
			Uds: "no rebatan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy rebatiendo",
			tú: "estás rebatiendo",
			Ud: "está rebatiendo",
			nosotros: "estamos rebatiendo",
			vosotros: "estáis rebatiendo",
			Uds: "están rebatiendo",
		},
		Preterite: {
			yo: "estuve rebatiendo",
			tú: "estuviste rebatiendo",
			Ud: "estuvo rebatiendo",
			nosotros: "estuvimos rebatiendo",
			vosotros: "estuvisteis rebatiendo",
			Uds: "estuvieron rebatiendo",
		},
		Imperfect: {
			Uds: "estaban rebatiendo",
			yo: "estaba rebatiendo",
			tú: "estabas rebatiendo",
			Ud: "estaba rebatiendo",
			nosotros: "estábamos rebatiendo",
			vosotros: "estabais rebatiendo",
		},
		Conditional: {
			yo: "estaría rebatiendo",
			tú: "estarías rebatiendo",
			Ud: "estaría rebatiendo",
			nosotros: "estaríamos rebatiendo",
			vosotros: "estaríais rebatiendo",
			Uds: "estarían rebatiendo",
		},
		Future: {
			yo: "estaré rebatiendo",
			tú: "estarás rebatiendo",
			Ud: "estará rebatiendo",
			nosotros: "estaremos rebatiendo",
			vosotros: "estaréis rebatiendo",
			Uds: "estarán rebatiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he rebatido",
			tú: "has rebatido",
			Ud: "ha rebatido",
			nosotros: "hemos rebatido",
			vosotros: "habéis rebatido",
			Uds: "han rebatido",
		},
		Preterite: {
			yo: "hube rebatido",
			tú: "hubiste rebatido",
			Ud: "hubo rebatido",
			nosotros: "hubimos rebatido",
			vosotros: "hubisteis rebatido",
			Uds: "hubieron rebatido",
		},
		Past: {
			yo: "había rebatido",
			tú: "habías rebatido",
			Ud: "había rebatido",
			nosotros: "habíamos rebatido",
			vosotros: "habíais rebatido",
			Uds: "habían rebatido",
		},
		Conditional: {
			yo: "habría rebatido",
			tú: "habrías rebatido",
			Ud: "habría rebatido",
			nosotros: "habríamos rebatido",
			vosotros: "habríais rebatido",
			Uds: "habrían rebatido",
		},
		Future: {
			yo: "habré rebatido",
			tú: "habrás rebatido",
			Ud: "habrá rebatido",
			nosotros: "habremos rebatido",
			vosotros: "habréis rebatido",
			Uds: "habrán rebatido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya rebatido",
			tú: "hayas rebatido",
			Ud: "haya rebatido",
			nosotros: "hayamos rebatido",
			vosotros: "hayáis rebatido",
			Uds: "hayan rebatido",
		},
		Past: {
			yo: "hubiera rebatido",
			tú: "hubieras rebatido",
			Ud: "hubiera rebatido",
			nosotros: "hubiéramos rebatido",
			vosotros: "hubierais rebatido",
			Uds: "hubieran rebatido",
		},
		Future: {
			yo: "hubiere rebatido",
			tú: "hubieres rebatido",
			Ud: "hubiere rebatido",
			nosotros: "hubiéremos rebatido",
			vosotros: "hubiereis rebatido",
			Uds: "hubieren rebatido",
		},
	},
}
