var rebajar = {
	Indicative: {
		Present: {
			yo: "rebajo",
			tú: "rebajas",
			Ud: "rebaja",
			nosotros: "rebajamos",
			vosotros: "rebajáis",
			Uds: "rebajan",
		},
		Preterite: {
			yo: "rebajé",
			tú: "rebajaste",
			Ud: "rebajó",
			nosotros: "rebajamos",
			vosotros: "rebajasteis",
			Uds: "rebajaron",
		},
		Imperfect: {
			yo: "rebajaba",
			tú: "rebajabas",
			Ud: "rebajaba",
			nosotros: "rebajábamos",
			vosotros: "rebajabais",
			Uds: "rebajaban",
		},
		Conditional: {
			yo: "rebajaría",
			tú: "rebajarías",
			Ud: "rebajaría",
			nosotros: "rebajaríamos",
			vosotros: "rebajaríais",
			Uds: "rebajarían",
		},
		Future: {
			yo: "rebajaré",
			tú: "rebajarás",
			Ud: "rebajará",
			nosotros: "rebajaremos",
			vosotros: "rebajaréis",
			Uds: "rebajarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "rebaje",
			tú: "rebajes",
			Ud: "rebaje",
			nosotros: "rebajemos",
			vosotros: "rebajéis",
			Uds: "rebajen",
		},
		Imperfect: {
			yo: "rebajara",
			tú: "rebajaras",
			Ud: "rebajara",
			nosotros: "rebajáramos",
			vosotros: "rebajarais",
			Uds: "rebajaran",
		},
		Imperfect2: {
			yo: "rebajase",
			tú: "rebajases",
			Ud: "rebajase",
			nosotros: "rebajásemos",
			vosotros: "rebajaseis",
			Uds: "rebajasen",
		},
		Future: {
			yo: "rebajare",
			tú: "rebajares",
			Ud: "rebajare",
			nosotros: "rebajáremos",
			vosotros: "rebajareis",
			Uds: "rebajaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "rebaja",
			Ud: "rebaje",
			nosotros: "rebajemos",
			vosotros: "rebajad",
			Uds: "rebajen",
		},
		Negative: {
			tú: "no rebajes",
			Ud: "no rebaje",
			nosotros: "no rebajemos",
			vosotros: "no rebajéis",
			Uds: "no rebajen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy rebajando",
			tú: "estás rebajando",
			Ud: "está rebajando",
			nosotros: "estamos rebajando",
			vosotros: "estáis rebajando",
			Uds: "están rebajando",
		},
		Preterite: {
			yo: "estuve rebajando",
			tú: "estuviste rebajando",
			Ud: "estuvo rebajando",
			nosotros: "estuvimos rebajando",
			vosotros: "estuvisteis rebajando",
			Uds: "estuvieron rebajando",
		},
		Imperfect: {
			Uds: "estaban rebajando",
			yo: "estaba rebajando",
			tú: "estabas rebajando",
			Ud: "estaba rebajando",
			nosotros: "estábamos rebajando",
			vosotros: "estabais rebajando",
		},
		Conditional: {
			yo: "estaría rebajando",
			tú: "estarías rebajando",
			Ud: "estaría rebajando",
			nosotros: "estaríamos rebajando",
			vosotros: "estaríais rebajando",
			Uds: "estarían rebajando",
		},
		Future: {
			yo: "estaré rebajando",
			tú: "estarás rebajando",
			Ud: "estará rebajando",
			nosotros: "estaremos rebajando",
			vosotros: "estaréis rebajando",
			Uds: "estarán rebajando",
		},
	},
	Perfect: {
		Present: {
			yo: "he rebajado",
			tú: "has rebajado",
			Ud: "ha rebajado",
			nosotros: "hemos rebajado",
			vosotros: "habéis rebajado",
			Uds: "han rebajado",
		},
		Preterite: {
			yo: "hube rebajado",
			tú: "hubiste rebajado",
			Ud: "hubo rebajado",
			nosotros: "hubimos rebajado",
			vosotros: "hubisteis rebajado",
			Uds: "hubieron rebajado",
		},
		Past: {
			yo: "había rebajado",
			tú: "habías rebajado",
			Ud: "había rebajado",
			nosotros: "habíamos rebajado",
			vosotros: "habíais rebajado",
			Uds: "habían rebajado",
		},
		Conditional: {
			yo: "habría rebajado",
			tú: "habrías rebajado",
			Ud: "habría rebajado",
			nosotros: "habríamos rebajado",
			vosotros: "habríais rebajado",
			Uds: "habrían rebajado",
		},
		Future: {
			yo: "habré rebajado",
			tú: "habrás rebajado",
			Ud: "habrá rebajado",
			nosotros: "habremos rebajado",
			vosotros: "habréis rebajado",
			Uds: "habrán rebajado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya rebajado",
			tú: "hayas rebajado",
			Ud: "haya rebajado",
			nosotros: "hayamos rebajado",
			vosotros: "hayáis rebajado",
			Uds: "hayan rebajado",
		},
		Past: {
			yo: "hubiera rebajado",
			tú: "hubieras rebajado",
			Ud: "hubiera rebajado",
			nosotros: "hubiéramos rebajado",
			vosotros: "hubierais rebajado",
			Uds: "hubieran rebajado",
		},
		Future: {
			yo: "hubiere rebajado",
			tú: "hubieres rebajado",
			Ud: "hubiere rebajado",
			nosotros: "hubiéremos rebajado",
			vosotros: "hubiereis rebajado",
			Uds: "hubieren rebajado",
		},
	},
}
