var rebobinar = {
	Indicative: {
		Present: {
			yo: "rebobino",
			tú: "rebobinas",
			Ud: "rebobina",
			nosotros: "rebobinamos",
			vosotros: "rebobináis",
			Uds: "rebobinan",
		},
		Preterite: {
			yo: "rebobiné",
			tú: "rebobinaste",
			Ud: "rebobinó",
			nosotros: "rebobinamos",
			vosotros: "rebobinasteis",
			Uds: "rebobinaron",
		},
		Imperfect: {
			yo: "rebobinaba",
			tú: "rebobinabas",
			Ud: "rebobinaba",
			nosotros: "rebobinábamos",
			vosotros: "rebobinabais",
			Uds: "rebobinaban",
		},
		Conditional: {
			yo: "rebobinaría",
			tú: "rebobinarías",
			Ud: "rebobinaría",
			nosotros: "rebobinaríamos",
			vosotros: "rebobinaríais",
			Uds: "rebobinarían",
		},
		Future: {
			yo: "rebobinaré",
			tú: "rebobinarás",
			Ud: "rebobinará",
			nosotros: "rebobinaremos",
			vosotros: "rebobinaréis",
			Uds: "rebobinarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "rebobine",
			tú: "rebobines",
			Ud: "rebobine",
			nosotros: "rebobinemos",
			vosotros: "rebobinéis",
			Uds: "rebobinen",
		},
		Imperfect: {
			yo: "rebobinara",
			tú: "rebobinaras",
			Ud: "rebobinara",
			nosotros: "rebobináramos",
			vosotros: "rebobinarais",
			Uds: "rebobinaran",
		},
		Imperfect2: {
			yo: "rebobinase",
			tú: "rebobinases",
			Ud: "rebobinase",
			nosotros: "rebobinásemos",
			vosotros: "rebobinaseis",
			Uds: "rebobinasen",
		},
		Future: {
			yo: "rebobinare",
			tú: "rebobinares",
			Ud: "rebobinare",
			nosotros: "rebobináremos",
			vosotros: "rebobinareis",
			Uds: "rebobinaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "rebobina",
			Ud: "rebobine",
			nosotros: "rebobinemos",
			vosotros: "rebobinad",
			Uds: "rebobinen",
		},
		Negative: {
			tú: "no rebobines",
			Ud: "no rebobine",
			nosotros: "no rebobinemos",
			vosotros: "no rebobinéis",
			Uds: "no rebobinen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy rebobinando",
			tú: "estás rebobinando",
			Ud: "está rebobinando",
			nosotros: "estamos rebobinando",
			vosotros: "estáis rebobinando",
			Uds: "están rebobinando",
		},
		Preterite: {
			yo: "estuve rebobinando",
			tú: "estuviste rebobinando",
			Ud: "estuvo rebobinando",
			nosotros: "estuvimos rebobinando",
			vosotros: "estuvisteis rebobinando",
			Uds: "estuvieron rebobinando",
		},
		Imperfect: {
			Uds: "estaban rebobinando",
			yo: "estaba rebobinando",
			tú: "estabas rebobinando",
			Ud: "estaba rebobinando",
			nosotros: "estábamos rebobinando",
			vosotros: "estabais rebobinando",
		},
		Conditional: {
			yo: "estaría rebobinando",
			tú: "estarías rebobinando",
			Ud: "estaría rebobinando",
			nosotros: "estaríamos rebobinando",
			vosotros: "estaríais rebobinando",
			Uds: "estarían rebobinando",
		},
		Future: {
			yo: "estaré rebobinando",
			tú: "estarás rebobinando",
			Ud: "estará rebobinando",
			nosotros: "estaremos rebobinando",
			vosotros: "estaréis rebobinando",
			Uds: "estarán rebobinando",
		},
	},
	Perfect: {
		Present: {
			yo: "he rebobinado",
			tú: "has rebobinado",
			Ud: "ha rebobinado",
			nosotros: "hemos rebobinado",
			vosotros: "habéis rebobinado",
			Uds: "han rebobinado",
		},
		Preterite: {
			yo: "hube rebobinado",
			tú: "hubiste rebobinado",
			Ud: "hubo rebobinado",
			nosotros: "hubimos rebobinado",
			vosotros: "hubisteis rebobinado",
			Uds: "hubieron rebobinado",
		},
		Past: {
			yo: "había rebobinado",
			tú: "habías rebobinado",
			Ud: "había rebobinado",
			nosotros: "habíamos rebobinado",
			vosotros: "habíais rebobinado",
			Uds: "habían rebobinado",
		},
		Conditional: {
			yo: "habría rebobinado",
			tú: "habrías rebobinado",
			Ud: "habría rebobinado",
			nosotros: "habríamos rebobinado",
			vosotros: "habríais rebobinado",
			Uds: "habrían rebobinado",
		},
		Future: {
			yo: "habré rebobinado",
			tú: "habrás rebobinado",
			Ud: "habrá rebobinado",
			nosotros: "habremos rebobinado",
			vosotros: "habréis rebobinado",
			Uds: "habrán rebobinado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya rebobinado",
			tú: "hayas rebobinado",
			Ud: "haya rebobinado",
			nosotros: "hayamos rebobinado",
			vosotros: "hayáis rebobinado",
			Uds: "hayan rebobinado",
		},
		Past: {
			yo: "hubiera rebobinado",
			tú: "hubieras rebobinado",
			Ud: "hubiera rebobinado",
			nosotros: "hubiéramos rebobinado",
			vosotros: "hubierais rebobinado",
			Uds: "hubieran rebobinado",
		},
		Future: {
			yo: "hubiere rebobinado",
			tú: "hubieres rebobinado",
			Ud: "hubiere rebobinado",
			nosotros: "hubiéremos rebobinado",
			vosotros: "hubiereis rebobinado",
			Uds: "hubieren rebobinado",
		},
	},
}
