var rebuznar = {
	Indicative: {
		Present: {
			yo: "rebuzno",
			tú: "rebuznas",
			Ud: "rebuzna",
			nosotros: "rebuznamos",
			vosotros: "rebuznáis",
			Uds: "rebuznan",
		},
		Preterite: {
			yo: "rebuzné",
			tú: "rebuznaste",
			Ud: "rebuznó",
			nosotros: "rebuznamos",
			vosotros: "rebuznasteis",
			Uds: "rebuznaron",
		},
		Imperfect: {
			yo: "rebuznaba",
			tú: "rebuznabas",
			Ud: "rebuznaba",
			nosotros: "rebuznábamos",
			vosotros: "rebuznabais",
			Uds: "rebuznaban",
		},
		Conditional: {
			yo: "rebuznaría",
			tú: "rebuznarías",
			Ud: "rebuznaría",
			nosotros: "rebuznaríamos",
			vosotros: "rebuznaríais",
			Uds: "rebuznarían",
		},
		Future: {
			yo: "rebuznaré",
			tú: "rebuznarás",
			Ud: "rebuznará",
			nosotros: "rebuznaremos",
			vosotros: "rebuznaréis",
			Uds: "rebuznarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "rebuzne",
			tú: "rebuznes",
			Ud: "rebuzne",
			nosotros: "rebuznemos",
			vosotros: "rebuznéis",
			Uds: "rebuznen",
		},
		Imperfect: {
			yo: "rebuznara",
			tú: "rebuznaras",
			Ud: "rebuznara",
			nosotros: "rebuznáramos",
			vosotros: "rebuznarais",
			Uds: "rebuznaran",
		},
		Imperfect2: {
			yo: "rebuznase",
			tú: "rebuznases",
			Ud: "rebuznase",
			nosotros: "rebuznásemos",
			vosotros: "rebuznaseis",
			Uds: "rebuznasen",
		},
		Future: {
			yo: "rebuznare",
			tú: "rebuznares",
			Ud: "rebuznare",
			nosotros: "rebuznáremos",
			vosotros: "rebuznareis",
			Uds: "rebuznaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "rebuzna",
			Ud: "rebuzne",
			nosotros: "rebuznemos",
			vosotros: "rebuznad",
			Uds: "rebuznen",
		},
		Negative: {
			tú: "no rebuznes",
			Ud: "no rebuzne",
			nosotros: "no rebuznemos",
			vosotros: "no rebuznéis",
			Uds: "no rebuznen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy rebuznando",
			tú: "estás rebuznando",
			Ud: "está rebuznando",
			nosotros: "estamos rebuznando",
			vosotros: "estáis rebuznando",
			Uds: "están rebuznando",
		},
		Preterite: {
			yo: "estuve rebuznando",
			tú: "estuviste rebuznando",
			Ud: "estuvo rebuznando",
			nosotros: "estuvimos rebuznando",
			vosotros: "estuvisteis rebuznando",
			Uds: "estuvieron rebuznando",
		},
		Imperfect: {
			Uds: "estaban rebuznando",
			yo: "estaba rebuznando",
			tú: "estabas rebuznando",
			Ud: "estaba rebuznando",
			nosotros: "estábamos rebuznando",
			vosotros: "estabais rebuznando",
		},
		Conditional: {
			yo: "estaría rebuznando",
			tú: "estarías rebuznando",
			Ud: "estaría rebuznando",
			nosotros: "estaríamos rebuznando",
			vosotros: "estaríais rebuznando",
			Uds: "estarían rebuznando",
		},
		Future: {
			yo: "estaré rebuznando",
			tú: "estarás rebuznando",
			Ud: "estará rebuznando",
			nosotros: "estaremos rebuznando",
			vosotros: "estaréis rebuznando",
			Uds: "estarán rebuznando",
		},
	},
	Perfect: {
		Present: {
			yo: "he rebuznado",
			tú: "has rebuznado",
			Ud: "ha rebuznado",
			nosotros: "hemos rebuznado",
			vosotros: "habéis rebuznado",
			Uds: "han rebuznado",
		},
		Preterite: {
			yo: "hube rebuznado",
			tú: "hubiste rebuznado",
			Ud: "hubo rebuznado",
			nosotros: "hubimos rebuznado",
			vosotros: "hubisteis rebuznado",
			Uds: "hubieron rebuznado",
		},
		Past: {
			yo: "había rebuznado",
			tú: "habías rebuznado",
			Ud: "había rebuznado",
			nosotros: "habíamos rebuznado",
			vosotros: "habíais rebuznado",
			Uds: "habían rebuznado",
		},
		Conditional: {
			yo: "habría rebuznado",
			tú: "habrías rebuznado",
			Ud: "habría rebuznado",
			nosotros: "habríamos rebuznado",
			vosotros: "habríais rebuznado",
			Uds: "habrían rebuznado",
		},
		Future: {
			yo: "habré rebuznado",
			tú: "habrás rebuznado",
			Ud: "habrá rebuznado",
			nosotros: "habremos rebuznado",
			vosotros: "habréis rebuznado",
			Uds: "habrán rebuznado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya rebuznado",
			tú: "hayas rebuznado",
			Ud: "haya rebuznado",
			nosotros: "hayamos rebuznado",
			vosotros: "hayáis rebuznado",
			Uds: "hayan rebuznado",
		},
		Past: {
			yo: "hubiera rebuznado",
			tú: "hubieras rebuznado",
			Ud: "hubiera rebuznado",
			nosotros: "hubiéramos rebuznado",
			vosotros: "hubierais rebuznado",
			Uds: "hubieran rebuznado",
		},
		Future: {
			yo: "hubiere rebuznado",
			tú: "hubieres rebuznado",
			Ud: "hubiere rebuznado",
			nosotros: "hubiéremos rebuznado",
			vosotros: "hubiereis rebuznado",
			Uds: "hubieren rebuznado",
		},
	},
}
