var recomendar = {
	Indicative: {
		Present: {
			yo: "recojo",
			tú: "recoges",
			Ud: "recoge",
			nosotros: "recogemos",
			vosotros: "recogéis",
			Uds: "recogen",
		},
		Preterite: {
			yo: "recogí",
			tú: "recogiste",
			Ud: "recogió",
			nosotros: "recogimos",
			vosotros: "recogisteis",
			Uds: "recogieron",
		},
		Imperfect: {
			yo: "recogía",
			tú: "recogías",
			Ud: "recogía",
			nosotros: "recogíamos",
			vosotros: "recogíais",
			Uds: "recogían",
		},
		Conditional: {
			yo: "recogería",
			tú: "recogerías",
			Ud: "recogería",
			nosotros: "recogeríamos",
			vosotros: "recogeríais",
			Uds: "recogerían",
		},
		Future: {
			yo: "recogeré",
			tú: "recogerás",
			Ud: "recogerá",
			nosotros: "recogeremos",
			vosotros: "recogeréis",
			Uds: "recogerán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "recoja",
			tú: "recojas",
			Ud: "recoja",
			nosotros: "recojamos",
			vosotros: "recojáis",
			Uds: "recojan",
		},
		Imperfect: {
			yo: "recogiera",
			tú: "recogieras",
			Ud: "recogiera",
			nosotros: "recogiéramos",
			vosotros: "recogierais",
			Uds: "recogieran",
		},
		Imperfect2: {
			yo: "recogiese",
			tú: "recogieses",
			Ud: "recogiese",
			nosotros: "recogiésemos",
			vosotros: "recogieseis",
			Uds: "recogiesen",
		},
		Future: {
			yo: "recogiere",
			tú: "recogieres",
			Ud: "recogiere",
			nosotros: "recogiéremos",
			vosotros: "recogiereis",
			Uds: "recogieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "recoge",
			Ud: "recoja",
			nosotros: "recojamos",
			vosotros: "recoged",
			Uds: "recojan",
		},
		Negative: {
			tú: "no recojas",
			Ud: "no recoja",
			nosotros: "no recojamos",
			vosotros: "no recojáis",
			Uds: "no recojan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy recogiendo",
			tú: "estás recogiendo",
			Ud: "está recogiendo",
			nosotros: "estamos recogiendo",
			vosotros: "estáis recogiendo",
			Uds: "están recogiendo",
		},
		Preterite: {
			yo: "estuve recogiendo",
			tú: "estuviste recogiendo",
			Ud: "estuvo recogiendo",
			nosotros: "estuvimos recogiendo",
			vosotros: "estuvisteis recogiendo",
			Uds: "estuvieron recogiendo",
		},
		Imperfect: {
			Uds: "estaban recogiendo",
			yo: "estaba recogiendo",
			tú: "estabas recogiendo",
			Ud: "estaba recogiendo",
			nosotros: "estábamos recogiendo",
			vosotros: "estabais recogiendo",
		},
		Conditional: {
			yo: "estaría recogiendo",
			tú: "estarías recogiendo",
			Ud: "estaría recogiendo",
			nosotros: "estaríamos recogiendo",
			vosotros: "estaríais recogiendo",
			Uds: "estarían recogiendo",
		},
		Future: {
			yo: "estaré recogiendo",
			tú: "estarás recogiendo",
			Ud: "estará recogiendo",
			nosotros: "estaremos recogiendo",
			vosotros: "estaréis recogiendo",
			Uds: "estarán recogiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he recogido",
			tú: "has recogido",
			Ud: "ha recogido",
			nosotros: "hemos recogido",
			vosotros: "habéis recogido",
			Uds: "han recogido",
		},
		Preterite: {
			yo: "hube recogido",
			tú: "hubiste recogido",
			Ud: "hubo recogido",
			nosotros: "hubimos recogido",
			vosotros: "hubisteis recogido",
			Uds: "hubieron recogido",
		},
		Past: {
			yo: "había recogido",
			tú: "habías recogido",
			Ud: "había recogido",
			nosotros: "habíamos recogido",
			vosotros: "habíais recogido",
			Uds: "habían recogido",
		},
		Conditional: {
			yo: "habría recogido",
			tú: "habrías recogido",
			Ud: "habría recogido",
			nosotros: "habríamos recogido",
			vosotros: "habríais recogido",
			Uds: "habrían recogido",
		},
		Future: {
			yo: "habré recogido",
			tú: "habrás recogido",
			Ud: "habrá recogido",
			nosotros: "habremos recogido",
			vosotros: "habréis recogido",
			Uds: "habrán recogido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya recogido",
			tú: "hayas recogido",
			Ud: "haya recogido",
			nosotros: "hayamos recogido",
			vosotros: "hayáis recogido",
			Uds: "hayan recogido",
		},
		Past: {
			yo: "hubiera recogido",
			tú: "hubieras recogido",
			Ud: "hubiera recogido",
			nosotros: "hubiéramos recogido",
			vosotros: "hubierais recogido",
			Uds: "hubieran recogido",
		},
		Future: {
			yo: "hubiere recogido",
			tú: "hubieres recogido",
			Ud: "hubiere recogido",
			nosotros: "hubiéremos recogido",
			vosotros: "hubiereis recogido",
			Uds: "hubieren recogido",
		},
	},
}
