var recorrer = {
	Indicative: {
		Present: {
			yo: "recorro",
			tú: "recorres",
			Ud: "recorre",
			nosotros: "recorremos",
			vosotros: "recorréis",
			Uds: "recorren",
		},
		Preterite: {
			yo: "recorrí",
			tú: "recorriste",
			Ud: "recorrió",
			nosotros: "recorrimos",
			vosotros: "recorristeis",
			Uds: "recorrieron",
		},
		Imperfect: {
			yo: "recorría",
			tú: "recorrías",
			Ud: "recorría",
			nosotros: "recorríamos",
			vosotros: "recorríais",
			Uds: "recorrían",
		},
		Conditional: {
			yo: "recorrería",
			tú: "recorrerías",
			Ud: "recorrería",
			nosotros: "recorreríamos",
			vosotros: "recorreríais",
			Uds: "recorrerían",
		},
		Future: {
			yo: "recorreré",
			tú: "recorrerás",
			Ud: "recorrerá",
			nosotros: "recorreremos",
			vosotros: "recorreréis",
			Uds: "recorrerán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "recorra",
			tú: "recorras",
			Ud: "recorra",
			nosotros: "recorramos",
			vosotros: "recorráis",
			Uds: "recorran",
		},
		Imperfect: {
			yo: "recorriera",
			tú: "recorrieras",
			Ud: "recorriera",
			nosotros: "recorriéramos",
			vosotros: "recorrierais",
			Uds: "recorrieran",
		},
		Imperfect2: {
			yo: "recorriese",
			tú: "recorrieses",
			Ud: "recorriese",
			nosotros: "recorriésemos",
			vosotros: "recorrieseis",
			Uds: "recorriesen",
		},
		Future: {
			yo: "recorriere",
			tú: "recorrieres",
			Ud: "recorriere",
			nosotros: "recorriéremos",
			vosotros: "recorriereis",
			Uds: "recorrieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "recorre",
			Ud: "recorra",
			nosotros: "recorramos",
			vosotros: "recorred",
			Uds: "recorran",
		},
		Negative: {
			tú: "no recorras",
			Ud: "no recorra",
			nosotros: "no recorramos",
			vosotros: "no recorráis",
			Uds: "no recorran",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy recorriendo",
			tú: "estás recorriendo",
			Ud: "está recorriendo",
			nosotros: "estamos recorriendo",
			vosotros: "estáis recorriendo",
			Uds: "están recorriendo",
		},
		Preterite: {
			yo: "estuve recorriendo",
			tú: "estuviste recorriendo",
			Ud: "estuvo recorriendo",
			nosotros: "estuvimos recorriendo",
			vosotros: "estuvisteis recorriendo",
			Uds: "estuvieron recorriendo",
		},
		Imperfect: {
			Uds: "estaban recorriendo",
			yo: "estaba recorriendo",
			tú: "estabas recorriendo",
			Ud: "estaba recorriendo",
			nosotros: "estábamos recorriendo",
			vosotros: "estabais recorriendo",
		},
		Conditional: {
			yo: "estaría recorriendo",
			tú: "estarías recorriendo",
			Ud: "estaría recorriendo",
			nosotros: "estaríamos recorriendo",
			vosotros: "estaríais recorriendo",
			Uds: "estarían recorriendo",
		},
		Future: {
			yo: "estaré recorriendo",
			tú: "estarás recorriendo",
			Ud: "estará recorriendo",
			nosotros: "estaremos recorriendo",
			vosotros: "estaréis recorriendo",
			Uds: "estarán recorriendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he recorrido",
			tú: "has recorrido",
			Ud: "ha recorrido",
			nosotros: "hemos recorrido",
			vosotros: "habéis recorrido",
			Uds: "han recorrido",
		},
		Preterite: {
			yo: "hube recorrido",
			tú: "hubiste recorrido",
			Ud: "hubo recorrido",
			nosotros: "hubimos recorrido",
			vosotros: "hubisteis recorrido",
			Uds: "hubieron recorrido",
		},
		Past: {
			yo: "había recorrido",
			tú: "habías recorrido",
			Ud: "había recorrido",
			nosotros: "habíamos recorrido",
			vosotros: "habíais recorrido",
			Uds: "habían recorrido",
		},
		Conditional: {
			yo: "habría recorrido",
			tú: "habrías recorrido",
			Ud: "habría recorrido",
			nosotros: "habríamos recorrido",
			vosotros: "habríais recorrido",
			Uds: "habrían recorrido",
		},
		Future: {
			yo: "habré recorrido",
			tú: "habrás recorrido",
			Ud: "habrá recorrido",
			nosotros: "habremos recorrido",
			vosotros: "habréis recorrido",
			Uds: "habrán recorrido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya recorrido",
			tú: "hayas recorrido",
			Ud: "haya recorrido",
			nosotros: "hayamos recorrido",
			vosotros: "hayáis recorrido",
			Uds: "hayan recorrido",
		},
		Past: {
			yo: "hubiera recorrido",
			tú: "hubieras recorrido",
			Ud: "hubiera recorrido",
			nosotros: "hubiéramos recorrido",
			vosotros: "hubierais recorrido",
			Uds: "hubieran recorrido",
		},
		Future: {
			yo: "hubiere recorrido",
			tú: "hubieres recorrido",
			Ud: "hubiere recorrido",
			nosotros: "hubiéremos recorrido",
			vosotros: "hubiereis recorrido",
			Uds: "hubieren recorrido",
		},
	},
}
