var reconciliar = {
	Indicative: {
		Present: {
			yo: "reconcilio",
			tú: "reconcilias",
			Ud: "reconcilia",
			nosotros: "reconciliamos",
			vosotros: "reconciliáis",
			Uds: "reconcilian",
		},
		Preterite: {
			yo: "reconcilié",
			tú: "reconciliaste",
			Ud: "reconcilió",
			nosotros: "reconciliamos",
			vosotros: "reconciliasteis",
			Uds: "reconciliaron",
		},
		Imperfect: {
			yo: "reconciliaba",
			tú: "reconciliabas",
			Ud: "reconciliaba",
			nosotros: "reconciliábamos",
			vosotros: "reconciliabais",
			Uds: "reconciliaban",
		},
		Conditional: {
			yo: "reconciliaría",
			tú: "reconciliarías",
			Ud: "reconciliaría",
			nosotros: "reconciliaríamos",
			vosotros: "reconciliaríais",
			Uds: "reconciliarían",
		},
		Future: {
			yo: "reconciliaré",
			tú: "reconciliarás",
			Ud: "reconciliará",
			nosotros: "reconciliaremos",
			vosotros: "reconciliaréis",
			Uds: "reconciliarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "reconcilie",
			tú: "reconcilies",
			Ud: "reconcilie",
			nosotros: "reconciliemos",
			vosotros: "reconciliéis",
			Uds: "reconcilien",
		},
		Imperfect: {
			yo: "reconciliara",
			tú: "reconciliaras",
			Ud: "reconciliara",
			nosotros: "reconciliáramos",
			vosotros: "reconciliarais",
			Uds: "reconciliaran",
		},
		Imperfect2: {
			yo: "reconciliase",
			tú: "reconciliases",
			Ud: "reconciliase",
			nosotros: "reconciliásemos",
			vosotros: "reconciliaseis",
			Uds: "reconciliasen",
		},
		Future: {
			yo: "reconciliare",
			tú: "reconciliares",
			Ud: "reconciliare",
			nosotros: "reconciliáremos",
			vosotros: "reconciliareis",
			Uds: "reconciliaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "reconcilia",
			Ud: "reconcilie",
			nosotros: "reconciliemos",
			vosotros: "reconciliad",
			Uds: "reconcilien",
		},
		Negative: {
			tú: "no reconcilies",
			Ud: "no reconcilie",
			nosotros: "no reconciliemos",
			vosotros: "no reconciliéis",
			Uds: "no reconcilien",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy reconciliando",
			tú: "estás reconciliando",
			Ud: "está reconciliando",
			nosotros: "estamos reconciliando",
			vosotros: "estáis reconciliando",
			Uds: "están reconciliando",
		},
		Preterite: {
			yo: "estuve reconciliando",
			tú: "estuviste reconciliando",
			Ud: "estuvo reconciliando",
			nosotros: "estuvimos reconciliando",
			vosotros: "estuvisteis reconciliando",
			Uds: "estuvieron reconciliando",
		},
		Imperfect: {
			Uds: "estaban reconciliando",
			yo: "estaba reconciliando",
			tú: "estabas reconciliando",
			Ud: "estaba reconciliando",
			nosotros: "estábamos reconciliando",
			vosotros: "estabais reconciliando",
		},
		Conditional: {
			yo: "estaría reconciliando",
			tú: "estarías reconciliando",
			Ud: "estaría reconciliando",
			nosotros: "estaríamos reconciliando",
			vosotros: "estaríais reconciliando",
			Uds: "estarían reconciliando",
		},
		Future: {
			yo: "estaré reconciliando",
			tú: "estarás reconciliando",
			Ud: "estará reconciliando",
			nosotros: "estaremos reconciliando",
			vosotros: "estaréis reconciliando",
			Uds: "estarán reconciliando",
		},
	},
	Perfect: {
		Present: {
			yo: "he reconciliado",
			tú: "has reconciliado",
			Ud: "ha reconciliado",
			nosotros: "hemos reconciliado",
			vosotros: "habéis reconciliado",
			Uds: "han reconciliado",
		},
		Preterite: {
			yo: "hube reconciliado",
			tú: "hubiste reconciliado",
			Ud: "hubo reconciliado",
			nosotros: "hubimos reconciliado",
			vosotros: "hubisteis reconciliado",
			Uds: "hubieron reconciliado",
		},
		Past: {
			yo: "había reconciliado",
			tú: "habías reconciliado",
			Ud: "había reconciliado",
			nosotros: "habíamos reconciliado",
			vosotros: "habíais reconciliado",
			Uds: "habían reconciliado",
		},
		Conditional: {
			yo: "habría reconciliado",
			tú: "habrías reconciliado",
			Ud: "habría reconciliado",
			nosotros: "habríamos reconciliado",
			vosotros: "habríais reconciliado",
			Uds: "habrían reconciliado",
		},
		Future: {
			yo: "habré reconciliado",
			tú: "habrás reconciliado",
			Ud: "habrá reconciliado",
			nosotros: "habremos reconciliado",
			vosotros: "habréis reconciliado",
			Uds: "habrán reconciliado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya reconciliado",
			tú: "hayas reconciliado",
			Ud: "haya reconciliado",
			nosotros: "hayamos reconciliado",
			vosotros: "hayáis reconciliado",
			Uds: "hayan reconciliado",
		},
		Past: {
			yo: "hubiera reconciliado",
			tú: "hubieras reconciliado",
			Ud: "hubiera reconciliado",
			nosotros: "hubiéramos reconciliado",
			vosotros: "hubierais reconciliado",
			Uds: "hubieran reconciliado",
		},
		Future: {
			yo: "hubiere reconciliado",
			tú: "hubieres reconciliado",
			Ud: "hubiere reconciliado",
			nosotros: "hubiéremos reconciliado",
			vosotros: "hubiereis reconciliado",
			Uds: "hubieren reconciliado",
		},
	},
}
