var recriminar = {
	Indicative: {
		Present: {
			yo: "recrimino",
			tú: "recriminas",
			Ud: "recrimina",
			nosotros: "recriminamos",
			vosotros: "recrimináis",
			Uds: "recriminan",
		},
		Preterite: {
			yo: "recriminé",
			tú: "recriminaste",
			Ud: "recriminó",
			nosotros: "recriminamos",
			vosotros: "recriminasteis",
			Uds: "recriminaron",
		},
		Imperfect: {
			yo: "recriminaba",
			tú: "recriminabas",
			Ud: "recriminaba",
			nosotros: "recriminábamos",
			vosotros: "recriminabais",
			Uds: "recriminaban",
		},
		Conditional: {
			yo: "recriminaría",
			tú: "recriminarías",
			Ud: "recriminaría",
			nosotros: "recriminaríamos",
			vosotros: "recriminaríais",
			Uds: "recriminarían",
		},
		Future: {
			yo: "recriminaré",
			tú: "recriminarás",
			Ud: "recriminará",
			nosotros: "recriminaremos",
			vosotros: "recriminaréis",
			Uds: "recriminarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "recrimine",
			tú: "recrimines",
			Ud: "recrimine",
			nosotros: "recriminemos",
			vosotros: "recriminéis",
			Uds: "recriminen",
		},
		Imperfect: {
			yo: "recriminara",
			tú: "recriminaras",
			Ud: "recriminara",
			nosotros: "recrimináramos",
			vosotros: "recriminarais",
			Uds: "recriminaran",
		},
		Imperfect2: {
			yo: "recriminase",
			tú: "recriminases",
			Ud: "recriminase",
			nosotros: "recriminásemos",
			vosotros: "recriminaseis",
			Uds: "recriminasen",
		},
		Future: {
			yo: "recriminare",
			tú: "recriminares",
			Ud: "recriminare",
			nosotros: "recrimináremos",
			vosotros: "recriminareis",
			Uds: "recriminaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "recrimina",
			Ud: "recrimine",
			nosotros: "recriminemos",
			vosotros: "recriminad",
			Uds: "recriminen",
		},
		Negative: {
			tú: "no recrimines",
			Ud: "no recrimine",
			nosotros: "no recriminemos",
			vosotros: "no recriminéis",
			Uds: "no recriminen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy recriminando",
			tú: "estás recriminando",
			Ud: "está recriminando",
			nosotros: "estamos recriminando",
			vosotros: "estáis recriminando",
			Uds: "están recriminando",
		},
		Preterite: {
			yo: "estuve recriminando",
			tú: "estuviste recriminando",
			Ud: "estuvo recriminando",
			nosotros: "estuvimos recriminando",
			vosotros: "estuvisteis recriminando",
			Uds: "estuvieron recriminando",
		},
		Imperfect: {
			Uds: "estaban recriminando",
			yo: "estaba recriminando",
			tú: "estabas recriminando",
			Ud: "estaba recriminando",
			nosotros: "estábamos recriminando",
			vosotros: "estabais recriminando",
		},
		Conditional: {
			yo: "estaría recriminando",
			tú: "estarías recriminando",
			Ud: "estaría recriminando",
			nosotros: "estaríamos recriminando",
			vosotros: "estaríais recriminando",
			Uds: "estarían recriminando",
		},
		Future: {
			yo: "estaré recriminando",
			tú: "estarás recriminando",
			Ud: "estará recriminando",
			nosotros: "estaremos recriminando",
			vosotros: "estaréis recriminando",
			Uds: "estarán recriminando",
		},
	},
	Perfect: {
		Present: {
			yo: "he recriminado",
			tú: "has recriminado",
			Ud: "ha recriminado",
			nosotros: "hemos recriminado",
			vosotros: "habéis recriminado",
			Uds: "han recriminado",
		},
		Preterite: {
			yo: "hube recriminado",
			tú: "hubiste recriminado",
			Ud: "hubo recriminado",
			nosotros: "hubimos recriminado",
			vosotros: "hubisteis recriminado",
			Uds: "hubieron recriminado",
		},
		Past: {
			yo: "había recriminado",
			tú: "habías recriminado",
			Ud: "había recriminado",
			nosotros: "habíamos recriminado",
			vosotros: "habíais recriminado",
			Uds: "habían recriminado",
		},
		Conditional: {
			yo: "habría recriminado",
			tú: "habrías recriminado",
			Ud: "habría recriminado",
			nosotros: "habríamos recriminado",
			vosotros: "habríais recriminado",
			Uds: "habrían recriminado",
		},
		Future: {
			yo: "habré recriminado",
			tú: "habrás recriminado",
			Ud: "habrá recriminado",
			nosotros: "habremos recriminado",
			vosotros: "habréis recriminado",
			Uds: "habrán recriminado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya recriminado",
			tú: "hayas recriminado",
			Ud: "haya recriminado",
			nosotros: "hayamos recriminado",
			vosotros: "hayáis recriminado",
			Uds: "hayan recriminado",
		},
		Past: {
			yo: "hubiera recriminado",
			tú: "hubieras recriminado",
			Ud: "hubiera recriminado",
			nosotros: "hubiéramos recriminado",
			vosotros: "hubierais recriminado",
			Uds: "hubieran recriminado",
		},
		Future: {
			yo: "hubiere recriminado",
			tú: "hubieres recriminado",
			Ud: "hubiere recriminado",
			nosotros: "hubiéremos recriminado",
			vosotros: "hubiereis recriminado",
			Uds: "hubieren recriminado",
		},
	},
}
