var reembolsar = {
	Indicative: {
		Present: {
			yo: "reembolso",
			tú: "reembolsas",
			Ud: "reembolsa",
			nosotros: "reembolsamos",
			vosotros: "reembolsáis",
			Uds: "reembolsan",
		},
		Preterite: {
			yo: "reembolsé",
			tú: "reembolsaste",
			Ud: "reembolsó",
			nosotros: "reembolsamos",
			vosotros: "reembolsasteis",
			Uds: "reembolsaron",
		},
		Imperfect: {
			yo: "reembolsaba",
			tú: "reembolsabas",
			Ud: "reembolsaba",
			nosotros: "reembolsábamos",
			vosotros: "reembolsabais",
			Uds: "reembolsaban",
		},
		Conditional: {
			yo: "reembolsaría",
			tú: "reembolsarías",
			Ud: "reembolsaría",
			nosotros: "reembolsaríamos",
			vosotros: "reembolsaríais",
			Uds: "reembolsarían",
		},
		Future: {
			yo: "reembolsaré",
			tú: "reembolsarás",
			Ud: "reembolsará",
			nosotros: "reembolsaremos",
			vosotros: "reembolsaréis",
			Uds: "reembolsarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "reembolse",
			tú: "reembolses",
			Ud: "reembolse",
			nosotros: "reembolsemos",
			vosotros: "reembolséis",
			Uds: "reembolsen",
		},
		Imperfect: {
			yo: "reembolsara",
			tú: "reembolsaras",
			Ud: "reembolsara",
			nosotros: "reembolsáramos",
			vosotros: "reembolsarais",
			Uds: "reembolsaran",
		},
		Imperfect2: {
			yo: "reembolsase",
			tú: "reembolsases",
			Ud: "reembolsase",
			nosotros: "reembolsásemos",
			vosotros: "reembolsaseis",
			Uds: "reembolsasen",
		},
		Future: {
			yo: "reembolsare",
			tú: "reembolsares",
			Ud: "reembolsare",
			nosotros: "reembolsáremos",
			vosotros: "reembolsareis",
			Uds: "reembolsaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "reembolsa",
			Ud: "reembolse",
			nosotros: "reembolsemos",
			vosotros: "reembolsad",
			Uds: "reembolsen",
		},
		Negative: {
			tú: "no reembolses",
			Ud: "no reembolse",
			nosotros: "no reembolsemos",
			vosotros: "no reembolséis",
			Uds: "no reembolsen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy reembolsando",
			tú: "estás reembolsando",
			Ud: "está reembolsando",
			nosotros: "estamos reembolsando",
			vosotros: "estáis reembolsando",
			Uds: "están reembolsando",
		},
		Preterite: {
			yo: "estuve reembolsando",
			tú: "estuviste reembolsando",
			Ud: "estuvo reembolsando",
			nosotros: "estuvimos reembolsando",
			vosotros: "estuvisteis reembolsando",
			Uds: "estuvieron reembolsando",
		},
		Imperfect: {
			Uds: "estaban reembolsando",
			yo: "estaba reembolsando",
			tú: "estabas reembolsando",
			Ud: "estaba reembolsando",
			nosotros: "estábamos reembolsando",
			vosotros: "estabais reembolsando",
		},
		Conditional: {
			yo: "estaría reembolsando",
			tú: "estarías reembolsando",
			Ud: "estaría reembolsando",
			nosotros: "estaríamos reembolsando",
			vosotros: "estaríais reembolsando",
			Uds: "estarían reembolsando",
		},
		Future: {
			yo: "estaré reembolsando",
			tú: "estarás reembolsando",
			Ud: "estará reembolsando",
			nosotros: "estaremos reembolsando",
			vosotros: "estaréis reembolsando",
			Uds: "estarán reembolsando",
		},
	},
	Perfect: {
		Present: {
			yo: "he reembolsado",
			tú: "has reembolsado",
			Ud: "ha reembolsado",
			nosotros: "hemos reembolsado",
			vosotros: "habéis reembolsado",
			Uds: "han reembolsado",
		},
		Preterite: {
			yo: "hube reembolsado",
			tú: "hubiste reembolsado",
			Ud: "hubo reembolsado",
			nosotros: "hubimos reembolsado",
			vosotros: "hubisteis reembolsado",
			Uds: "hubieron reembolsado",
		},
		Past: {
			yo: "había reembolsado",
			tú: "habías reembolsado",
			Ud: "había reembolsado",
			nosotros: "habíamos reembolsado",
			vosotros: "habíais reembolsado",
			Uds: "habían reembolsado",
		},
		Conditional: {
			yo: "habría reembolsado",
			tú: "habrías reembolsado",
			Ud: "habría reembolsado",
			nosotros: "habríamos reembolsado",
			vosotros: "habríais reembolsado",
			Uds: "habrían reembolsado",
		},
		Future: {
			yo: "habré reembolsado",
			tú: "habrás reembolsado",
			Ud: "habrá reembolsado",
			nosotros: "habremos reembolsado",
			vosotros: "habréis reembolsado",
			Uds: "habrán reembolsado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya reembolsado",
			tú: "hayas reembolsado",
			Ud: "haya reembolsado",
			nosotros: "hayamos reembolsado",
			vosotros: "hayáis reembolsado",
			Uds: "hayan reembolsado",
		},
		Past: {
			yo: "hubiera reembolsado",
			tú: "hubieras reembolsado",
			Ud: "hubiera reembolsado",
			nosotros: "hubiéramos reembolsado",
			vosotros: "hubierais reembolsado",
			Uds: "hubieran reembolsado",
		},
		Future: {
			yo: "hubiere reembolsado",
			tú: "hubieres reembolsado",
			Ud: "hubiere reembolsado",
			nosotros: "hubiéremos reembolsado",
			vosotros: "hubiereis reembolsado",
			Uds: "hubieren reembolsado",
		},
	},
}
