var refrendar = {
	Indicative: {
		Present: {
			yo: "refrendo",
			tú: "refrendas",
			Ud: "refrenda",
			nosotros: "refrendamos",
			vosotros: "refrendáis",
			Uds: "refrendan",
		},
		Preterite: {
			yo: "refrendé",
			tú: "refrendaste",
			Ud: "refrendó",
			nosotros: "refrendamos",
			vosotros: "refrendasteis",
			Uds: "refrendaron",
		},
		Imperfect: {
			yo: "refrendaba",
			tú: "refrendabas",
			Ud: "refrendaba",
			nosotros: "refrendábamos",
			vosotros: "refrendabais",
			Uds: "refrendaban",
		},
		Conditional: {
			yo: "refrendaría",
			tú: "refrendarías",
			Ud: "refrendaría",
			nosotros: "refrendaríamos",
			vosotros: "refrendaríais",
			Uds: "refrendarían",
		},
		Future: {
			yo: "refrendaré",
			tú: "refrendarás",
			Ud: "refrendará",
			nosotros: "refrendaremos",
			vosotros: "refrendaréis",
			Uds: "refrendarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "refrende",
			tú: "refrendes",
			Ud: "refrende",
			nosotros: "refrendemos",
			vosotros: "refrendéis",
			Uds: "refrenden",
		},
		Imperfect: {
			yo: "refrendara",
			tú: "refrendaras",
			Ud: "refrendara",
			nosotros: "refrendáramos",
			vosotros: "refrendarais",
			Uds: "refrendaran",
		},
		Imperfect2: {
			yo: "refrendase",
			tú: "refrendases",
			Ud: "refrendase",
			nosotros: "refrendásemos",
			vosotros: "refrendaseis",
			Uds: "refrendasen",
		},
		Future: {
			yo: "refrendare",
			tú: "refrendares",
			Ud: "refrendare",
			nosotros: "refrendáremos",
			vosotros: "refrendareis",
			Uds: "refrendaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "refrenda",
			Ud: "refrende",
			nosotros: "refrendemos",
			vosotros: "refrendad",
			Uds: "refrenden",
		},
		Negative: {
			tú: "no refrendes",
			Ud: "no refrende",
			nosotros: "no refrendemos",
			vosotros: "no refrendéis",
			Uds: "no refrenden",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy refrendando",
			tú: "estás refrendando",
			Ud: "está refrendando",
			nosotros: "estamos refrendando",
			vosotros: "estáis refrendando",
			Uds: "están refrendando",
		},
		Preterite: {
			yo: "estuve refrendando",
			tú: "estuviste refrendando",
			Ud: "estuvo refrendando",
			nosotros: "estuvimos refrendando",
			vosotros: "estuvisteis refrendando",
			Uds: "estuvieron refrendando",
		},
		Imperfect: {
			Uds: "estaban refrendando",
			yo: "estaba refrendando",
			tú: "estabas refrendando",
			Ud: "estaba refrendando",
			nosotros: "estábamos refrendando",
			vosotros: "estabais refrendando",
		},
		Conditional: {
			yo: "estaría refrendando",
			tú: "estarías refrendando",
			Ud: "estaría refrendando",
			nosotros: "estaríamos refrendando",
			vosotros: "estaríais refrendando",
			Uds: "estarían refrendando",
		},
		Future: {
			yo: "estaré refrendando",
			tú: "estarás refrendando",
			Ud: "estará refrendando",
			nosotros: "estaremos refrendando",
			vosotros: "estaréis refrendando",
			Uds: "estarán refrendando",
		},
	},
	Perfect: {
		Present: {
			yo: "he refrendado",
			tú: "has refrendado",
			Ud: "ha refrendado",
			nosotros: "hemos refrendado",
			vosotros: "habéis refrendado",
			Uds: "han refrendado",
		},
		Preterite: {
			yo: "hube refrendado",
			tú: "hubiste refrendado",
			Ud: "hubo refrendado",
			nosotros: "hubimos refrendado",
			vosotros: "hubisteis refrendado",
			Uds: "hubieron refrendado",
		},
		Past: {
			yo: "había refrendado",
			tú: "habías refrendado",
			Ud: "había refrendado",
			nosotros: "habíamos refrendado",
			vosotros: "habíais refrendado",
			Uds: "habían refrendado",
		},
		Conditional: {
			yo: "habría refrendado",
			tú: "habrías refrendado",
			Ud: "habría refrendado",
			nosotros: "habríamos refrendado",
			vosotros: "habríais refrendado",
			Uds: "habrían refrendado",
		},
		Future: {
			yo: "habré refrendado",
			tú: "habrás refrendado",
			Ud: "habrá refrendado",
			nosotros: "habremos refrendado",
			vosotros: "habréis refrendado",
			Uds: "habrán refrendado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya refrendado",
			tú: "hayas refrendado",
			Ud: "haya refrendado",
			nosotros: "hayamos refrendado",
			vosotros: "hayáis refrendado",
			Uds: "hayan refrendado",
		},
		Past: {
			yo: "hubiera refrendado",
			tú: "hubieras refrendado",
			Ud: "hubiera refrendado",
			nosotros: "hubiéramos refrendado",
			vosotros: "hubierais refrendado",
			Uds: "hubieran refrendado",
		},
		Future: {
			yo: "hubiere refrendado",
			tú: "hubieres refrendado",
			Ud: "hubiere refrendado",
			nosotros: "hubiéremos refrendado",
			vosotros: "hubiereis refrendado",
			Uds: "hubieren refrendado",
		},
	},
}
