var refrigerar = {
	Indicative: {
		Present: {
			yo: "refrigero",
			tú: "refrigeras",
			Ud: "refrigera",
			nosotros: "refrigeramos",
			vosotros: "refrigeráis",
			Uds: "refrigeran",
		},
		Preterite: {
			yo: "refrigeré",
			tú: "refrigeraste",
			Ud: "refrigeró",
			nosotros: "refrigeramos",
			vosotros: "refrigerasteis",
			Uds: "refrigeraron",
		},
		Imperfect: {
			yo: "refrigeraba",
			tú: "refrigerabas",
			Ud: "refrigeraba",
			nosotros: "refrigerábamos",
			vosotros: "refrigerabais",
			Uds: "refrigeraban",
		},
		Conditional: {
			yo: "refrigeraría",
			tú: "refrigerarías",
			Ud: "refrigeraría",
			nosotros: "refrigeraríamos",
			vosotros: "refrigeraríais",
			Uds: "refrigerarían",
		},
		Future: {
			yo: "refrigeraré",
			tú: "refrigerarás",
			Ud: "refrigerará",
			nosotros: "refrigeraremos",
			vosotros: "refrigeraréis",
			Uds: "refrigerarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "refrigere",
			tú: "refrigeres",
			Ud: "refrigere",
			nosotros: "refrigeremos",
			vosotros: "refrigeréis",
			Uds: "refrigeren",
		},
		Imperfect: {
			yo: "refrigerara",
			tú: "refrigeraras",
			Ud: "refrigerara",
			nosotros: "refrigeráramos",
			vosotros: "refrigerarais",
			Uds: "refrigeraran",
		},
		Imperfect2: {
			yo: "refrigerase",
			tú: "refrigerases",
			Ud: "refrigerase",
			nosotros: "refrigerásemos",
			vosotros: "refrigeraseis",
			Uds: "refrigerasen",
		},
		Future: {
			yo: "refrigerare",
			tú: "refrigerares",
			Ud: "refrigerare",
			nosotros: "refrigeráremos",
			vosotros: "refrigerareis",
			Uds: "refrigeraren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "refrigera",
			Ud: "refrigere",
			nosotros: "refrigeremos",
			vosotros: "refrigerad",
			Uds: "refrigeren",
		},
		Negative: {
			tú: "no refrigeres",
			Ud: "no refrigere",
			nosotros: "no refrigeremos",
			vosotros: "no refrigeréis",
			Uds: "no refrigeren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy refrigerando",
			tú: "estás refrigerando",
			Ud: "está refrigerando",
			nosotros: "estamos refrigerando",
			vosotros: "estáis refrigerando",
			Uds: "están refrigerando",
		},
		Preterite: {
			yo: "estuve refrigerando",
			tú: "estuviste refrigerando",
			Ud: "estuvo refrigerando",
			nosotros: "estuvimos refrigerando",
			vosotros: "estuvisteis refrigerando",
			Uds: "estuvieron refrigerando",
		},
		Imperfect: {
			Uds: "estaban refrigerando",
			yo: "estaba refrigerando",
			tú: "estabas refrigerando",
			Ud: "estaba refrigerando",
			nosotros: "estábamos refrigerando",
			vosotros: "estabais refrigerando",
		},
		Conditional: {
			yo: "estaría refrigerando",
			tú: "estarías refrigerando",
			Ud: "estaría refrigerando",
			nosotros: "estaríamos refrigerando",
			vosotros: "estaríais refrigerando",
			Uds: "estarían refrigerando",
		},
		Future: {
			yo: "estaré refrigerando",
			tú: "estarás refrigerando",
			Ud: "estará refrigerando",
			nosotros: "estaremos refrigerando",
			vosotros: "estaréis refrigerando",
			Uds: "estarán refrigerando",
		},
	},
	Perfect: {
		Present: {
			yo: "he refrigerado",
			tú: "has refrigerado",
			Ud: "ha refrigerado",
			nosotros: "hemos refrigerado",
			vosotros: "habéis refrigerado",
			Uds: "han refrigerado",
		},
		Preterite: {
			yo: "hube refrigerado",
			tú: "hubiste refrigerado",
			Ud: "hubo refrigerado",
			nosotros: "hubimos refrigerado",
			vosotros: "hubisteis refrigerado",
			Uds: "hubieron refrigerado",
		},
		Past: {
			yo: "había refrigerado",
			tú: "habías refrigerado",
			Ud: "había refrigerado",
			nosotros: "habíamos refrigerado",
			vosotros: "habíais refrigerado",
			Uds: "habían refrigerado",
		},
		Conditional: {
			yo: "habría refrigerado",
			tú: "habrías refrigerado",
			Ud: "habría refrigerado",
			nosotros: "habríamos refrigerado",
			vosotros: "habríais refrigerado",
			Uds: "habrían refrigerado",
		},
		Future: {
			yo: "habré refrigerado",
			tú: "habrás refrigerado",
			Ud: "habrá refrigerado",
			nosotros: "habremos refrigerado",
			vosotros: "habréis refrigerado",
			Uds: "habrán refrigerado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya refrigerado",
			tú: "hayas refrigerado",
			Ud: "haya refrigerado",
			nosotros: "hayamos refrigerado",
			vosotros: "hayáis refrigerado",
			Uds: "hayan refrigerado",
		},
		Past: {
			yo: "hubiera refrigerado",
			tú: "hubieras refrigerado",
			Ud: "hubiera refrigerado",
			nosotros: "hubiéramos refrigerado",
			vosotros: "hubierais refrigerado",
			Uds: "hubieran refrigerado",
		},
		Future: {
			yo: "hubiere refrigerado",
			tú: "hubieres refrigerado",
			Ud: "hubiere refrigerado",
			nosotros: "hubiéremos refrigerado",
			vosotros: "hubiereis refrigerado",
			Uds: "hubieren refrigerado",
		},
	},
}
