var rehusar = {
	Indicative: {
		Present: {
			yo: "rehúso",
			tú: "rehúsas",
			Ud: "rehúsa",
			nosotros: "rehusamos",
			vosotros: "rehusáis",
			Uds: "rehúsan",
		},
		Preterite: {
			yo: "rehusé",
			tú: "rehusaste",
			Ud: "rehusó",
			nosotros: "rehusamos",
			vosotros: "rehusasteis",
			Uds: "rehusaron",
		},
		Imperfect: {
			yo: "rehusaba",
			tú: "rehusabas",
			Ud: "rehusaba",
			nosotros: "rehusábamos",
			vosotros: "rehusabais",
			Uds: "rehusaban",
		},
		Conditional: {
			yo: "rehusaría",
			tú: "rehusarías",
			Ud: "rehusaría",
			nosotros: "rehusaríamos",
			vosotros: "rehusaríais",
			Uds: "rehusarían",
		},
		Future: {
			yo: "rehusaré",
			tú: "rehusarás",
			Ud: "rehusará",
			nosotros: "rehusaremos",
			vosotros: "rehusaréis",
			Uds: "rehusarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "rehúse",
			tú: "rehúses",
			Ud: "rehúse",
			nosotros: "rehusemos",
			vosotros: "rehuséis",
			Uds: "rehúsen",
		},
		Imperfect: {
			yo: "rehusara",
			tú: "rehusaras",
			Ud: "rehusara",
			nosotros: "rehusáramos",
			vosotros: "rehusarais",
			Uds: "rehusaran",
		},
		Imperfect2: {
			yo: "rehusase",
			tú: "rehusases",
			Ud: "rehusase",
			nosotros: "rehusásemos",
			vosotros: "rehusaseis",
			Uds: "rehusasen",
		},
		Future: {
			yo: "rehusare",
			tú: "rehusares",
			Ud: "rehusare",
			nosotros: "rehusáremos",
			vosotros: "rehusareis",
			Uds: "rehusaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "rehúsa",
			Ud: "rehúse",
			nosotros: "rehusemos",
			vosotros: "rehusad",
			Uds: "rehúsen",
		},
		Negative: {
			tú: "no rehúses",
			Ud: "no rehúse",
			nosotros: "no rehusemos",
			vosotros: "no rehuséis",
			Uds: "no rehúsen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy rehusando",
			tú: "estás rehusando",
			Ud: "está rehusando",
			nosotros: "estamos rehusando",
			vosotros: "estáis rehusando",
			Uds: "están rehusando",
		},
		Preterite: {
			yo: "estuve rehusando",
			tú: "estuviste rehusando",
			Ud: "estuvo rehusando",
			nosotros: "estuvimos rehusando",
			vosotros: "estuvisteis rehusando",
			Uds: "estuvieron rehusando",
		},
		Imperfect: {
			Uds: "estaban rehusando",
			yo: "estaba rehusando",
			tú: "estabas rehusando",
			Ud: "estaba rehusando",
			nosotros: "estábamos rehusando",
			vosotros: "estabais rehusando",
		},
		Conditional: {
			yo: "estaría rehusando",
			tú: "estarías rehusando",
			Ud: "estaría rehusando",
			nosotros: "estaríamos rehusando",
			vosotros: "estaríais rehusando",
			Uds: "estarían rehusando",
		},
		Future: {
			yo: "estaré rehusando",
			tú: "estarás rehusando",
			Ud: "estará rehusando",
			nosotros: "estaremos rehusando",
			vosotros: "estaréis rehusando",
			Uds: "estarán rehusando",
		},
	},
	Perfect: {
		Present: {
			yo: "he rehusado",
			tú: "has rehusado",
			Ud: "ha rehusado",
			nosotros: "hemos rehusado",
			vosotros: "habéis rehusado",
			Uds: "han rehusado",
		},
		Preterite: {
			yo: "hube rehusado",
			tú: "hubiste rehusado",
			Ud: "hubo rehusado",
			nosotros: "hubimos rehusado",
			vosotros: "hubisteis rehusado",
			Uds: "hubieron rehusado",
		},
		Past: {
			yo: "había rehusado",
			tú: "habías rehusado",
			Ud: "había rehusado",
			nosotros: "habíamos rehusado",
			vosotros: "habíais rehusado",
			Uds: "habían rehusado",
		},
		Conditional: {
			yo: "habría rehusado",
			tú: "habrías rehusado",
			Ud: "habría rehusado",
			nosotros: "habríamos rehusado",
			vosotros: "habríais rehusado",
			Uds: "habrían rehusado",
		},
		Future: {
			yo: "habré rehusado",
			tú: "habrás rehusado",
			Ud: "habrá rehusado",
			nosotros: "habremos rehusado",
			vosotros: "habréis rehusado",
			Uds: "habrán rehusado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya rehusado",
			tú: "hayas rehusado",
			Ud: "haya rehusado",
			nosotros: "hayamos rehusado",
			vosotros: "hayáis rehusado",
			Uds: "hayan rehusado",
		},
		Past: {
			yo: "hubiera rehusado",
			tú: "hubieras rehusado",
			Ud: "hubiera rehusado",
			nosotros: "hubiéramos rehusado",
			vosotros: "hubierais rehusado",
			Uds: "hubieran rehusado",
		},
		Future: {
			yo: "hubiere rehusado",
			tú: "hubieres rehusado",
			Ud: "hubiere rehusado",
			nosotros: "hubiéremos rehusado",
			vosotros: "hubiereis rehusado",
			Uds: "hubieren rehusado",
		},
	},
}
