var reincorporar = {
	Indicative: {
		Present: {
			yo: "reincorporo",
			tú: "reincorporas",
			Ud: "reincorpora",
			nosotros: "reincorporamos",
			vosotros: "reincorporáis",
			Uds: "reincorporan",
		},
		Preterite: {
			yo: "reincorporé",
			tú: "reincorporaste",
			Ud: "reincorporó",
			nosotros: "reincorporamos",
			vosotros: "reincorporasteis",
			Uds: "reincorporaron",
		},
		Imperfect: {
			yo: "reincorporaba",
			tú: "reincorporabas",
			Ud: "reincorporaba",
			nosotros: "reincorporábamos",
			vosotros: "reincorporabais",
			Uds: "reincorporaban",
		},
		Conditional: {
			yo: "reincorporaría",
			tú: "reincorporarías",
			Ud: "reincorporaría",
			nosotros: "reincorporaríamos",
			vosotros: "reincorporaríais",
			Uds: "reincorporarían",
		},
		Future: {
			yo: "reincorporaré",
			tú: "reincorporarás",
			Ud: "reincorporará",
			nosotros: "reincorporaremos",
			vosotros: "reincorporaréis",
			Uds: "reincorporarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "reincorpore",
			tú: "reincorpores",
			Ud: "reincorpore",
			nosotros: "reincorporemos",
			vosotros: "reincorporéis",
			Uds: "reincorporen",
		},
		Imperfect: {
			yo: "reincorporara",
			tú: "reincorporaras",
			Ud: "reincorporara",
			nosotros: "reincorporáramos",
			vosotros: "reincorporarais",
			Uds: "reincorporaran",
		},
		Imperfect2: {
			yo: "reincorporase",
			tú: "reincorporases",
			Ud: "reincorporase",
			nosotros: "reincorporásemos",
			vosotros: "reincorporaseis",
			Uds: "reincorporasen",
		},
		Future: {
			yo: "reincorporare",
			tú: "reincorporares",
			Ud: "reincorporare",
			nosotros: "reincorporáremos",
			vosotros: "reincorporareis",
			Uds: "reincorporaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "reincorpora",
			Ud: "reincorpore",
			nosotros: "reincorporemos",
			vosotros: "reincorporad",
			Uds: "reincorporen",
		},
		Negative: {
			tú: "no reincorpores",
			Ud: "no reincorpore",
			nosotros: "no reincorporemos",
			vosotros: "no reincorporéis",
			Uds: "no reincorporen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy reincorporando",
			tú: "estás reincorporando",
			Ud: "está reincorporando",
			nosotros: "estamos reincorporando",
			vosotros: "estáis reincorporando",
			Uds: "están reincorporando",
		},
		Preterite: {
			yo: "estuve reincorporando",
			tú: "estuviste reincorporando",
			Ud: "estuvo reincorporando",
			nosotros: "estuvimos reincorporando",
			vosotros: "estuvisteis reincorporando",
			Uds: "estuvieron reincorporando",
		},
		Imperfect: {
			Uds: "estaban reincorporando",
			yo: "estaba reincorporando",
			tú: "estabas reincorporando",
			Ud: "estaba reincorporando",
			nosotros: "estábamos reincorporando",
			vosotros: "estabais reincorporando",
		},
		Conditional: {
			yo: "estaría reincorporando",
			tú: "estarías reincorporando",
			Ud: "estaría reincorporando",
			nosotros: "estaríamos reincorporando",
			vosotros: "estaríais reincorporando",
			Uds: "estarían reincorporando",
		},
		Future: {
			yo: "estaré reincorporando",
			tú: "estarás reincorporando",
			Ud: "estará reincorporando",
			nosotros: "estaremos reincorporando",
			vosotros: "estaréis reincorporando",
			Uds: "estarán reincorporando",
		},
	},
	Perfect: {
		Present: {
			yo: "he reincorporado",
			tú: "has reincorporado",
			Ud: "ha reincorporado",
			nosotros: "hemos reincorporado",
			vosotros: "habéis reincorporado",
			Uds: "han reincorporado",
		},
		Preterite: {
			yo: "hube reincorporado",
			tú: "hubiste reincorporado",
			Ud: "hubo reincorporado",
			nosotros: "hubimos reincorporado",
			vosotros: "hubisteis reincorporado",
			Uds: "hubieron reincorporado",
		},
		Past: {
			yo: "había reincorporado",
			tú: "habías reincorporado",
			Ud: "había reincorporado",
			nosotros: "habíamos reincorporado",
			vosotros: "habíais reincorporado",
			Uds: "habían reincorporado",
		},
		Conditional: {
			yo: "habría reincorporado",
			tú: "habrías reincorporado",
			Ud: "habría reincorporado",
			nosotros: "habríamos reincorporado",
			vosotros: "habríais reincorporado",
			Uds: "habrían reincorporado",
		},
		Future: {
			yo: "habré reincorporado",
			tú: "habrás reincorporado",
			Ud: "habrá reincorporado",
			nosotros: "habremos reincorporado",
			vosotros: "habréis reincorporado",
			Uds: "habrán reincorporado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya reincorporado",
			tú: "hayas reincorporado",
			Ud: "haya reincorporado",
			nosotros: "hayamos reincorporado",
			vosotros: "hayáis reincorporado",
			Uds: "hayan reincorporado",
		},
		Past: {
			yo: "hubiera reincorporado",
			tú: "hubieras reincorporado",
			Ud: "hubiera reincorporado",
			nosotros: "hubiéramos reincorporado",
			vosotros: "hubierais reincorporado",
			Uds: "hubieran reincorporado",
		},
		Future: {
			yo: "hubiere reincorporado",
			tú: "hubieres reincorporado",
			Ud: "hubiere reincorporado",
			nosotros: "hubiéremos reincorporado",
			vosotros: "hubiereis reincorporado",
			Uds: "hubieren reincorporado",
		},
	},
}
