var relatar = {
	Indicative: {
		Present: {
			yo: "relato",
			tú: "relatas",
			Ud: "relata",
			nosotros: "relatamos",
			vosotros: "relatáis",
			Uds: "relatan",
		},
		Preterite: {
			yo: "relaté",
			tú: "relataste",
			Ud: "relató",
			nosotros: "relatamos",
			vosotros: "relatasteis",
			Uds: "relataron",
		},
		Imperfect: {
			yo: "relataba",
			tú: "relatabas",
			Ud: "relataba",
			nosotros: "relatábamos",
			vosotros: "relatabais",
			Uds: "relataban",
		},
		Conditional: {
			yo: "relataría",
			tú: "relatarías",
			Ud: "relataría",
			nosotros: "relataríamos",
			vosotros: "relataríais",
			Uds: "relatarían",
		},
		Future: {
			yo: "relataré",
			tú: "relatarás",
			Ud: "relatará",
			nosotros: "relataremos",
			vosotros: "relataréis",
			Uds: "relatarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "relate",
			tú: "relates",
			Ud: "relate",
			nosotros: "relatemos",
			vosotros: "relatéis",
			Uds: "relaten",
		},
		Imperfect: {
			yo: "relatara",
			tú: "relataras",
			Ud: "relatara",
			nosotros: "relatáramos",
			vosotros: "relatarais",
			Uds: "relataran",
		},
		Imperfect2: {
			yo: "relatase",
			tú: "relatases",
			Ud: "relatase",
			nosotros: "relatásemos",
			vosotros: "relataseis",
			Uds: "relatasen",
		},
		Future: {
			yo: "relatare",
			tú: "relatares",
			Ud: "relatare",
			nosotros: "relatáremos",
			vosotros: "relatareis",
			Uds: "relataren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "relata",
			Ud: "relate",
			nosotros: "relatemos",
			vosotros: "relatad",
			Uds: "relaten",
		},
		Negative: {
			tú: "no relates",
			Ud: "no relate",
			nosotros: "no relatemos",
			vosotros: "no relatéis",
			Uds: "no relaten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy relatando",
			tú: "estás relatando",
			Ud: "está relatando",
			nosotros: "estamos relatando",
			vosotros: "estáis relatando",
			Uds: "están relatando",
		},
		Preterite: {
			yo: "estuve relatando",
			tú: "estuviste relatando",
			Ud: "estuvo relatando",
			nosotros: "estuvimos relatando",
			vosotros: "estuvisteis relatando",
			Uds: "estuvieron relatando",
		},
		Imperfect: {
			Uds: "estaban relatando",
			yo: "estaba relatando",
			tú: "estabas relatando",
			Ud: "estaba relatando",
			nosotros: "estábamos relatando",
			vosotros: "estabais relatando",
		},
		Conditional: {
			yo: "estaría relatando",
			tú: "estarías relatando",
			Ud: "estaría relatando",
			nosotros: "estaríamos relatando",
			vosotros: "estaríais relatando",
			Uds: "estarían relatando",
		},
		Future: {
			yo: "estaré relatando",
			tú: "estarás relatando",
			Ud: "estará relatando",
			nosotros: "estaremos relatando",
			vosotros: "estaréis relatando",
			Uds: "estarán relatando",
		},
	},
	Perfect: {
		Present: {
			yo: "he relatado",
			tú: "has relatado",
			Ud: "ha relatado",
			nosotros: "hemos relatado",
			vosotros: "habéis relatado",
			Uds: "han relatado",
		},
		Preterite: {
			yo: "hube relatado",
			tú: "hubiste relatado",
			Ud: "hubo relatado",
			nosotros: "hubimos relatado",
			vosotros: "hubisteis relatado",
			Uds: "hubieron relatado",
		},
		Past: {
			yo: "había relatado",
			tú: "habías relatado",
			Ud: "había relatado",
			nosotros: "habíamos relatado",
			vosotros: "habíais relatado",
			Uds: "habían relatado",
		},
		Conditional: {
			yo: "habría relatado",
			tú: "habrías relatado",
			Ud: "habría relatado",
			nosotros: "habríamos relatado",
			vosotros: "habríais relatado",
			Uds: "habrían relatado",
		},
		Future: {
			yo: "habré relatado",
			tú: "habrás relatado",
			Ud: "habrá relatado",
			nosotros: "habremos relatado",
			vosotros: "habréis relatado",
			Uds: "habrán relatado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya relatado",
			tú: "hayas relatado",
			Ud: "haya relatado",
			nosotros: "hayamos relatado",
			vosotros: "hayáis relatado",
			Uds: "hayan relatado",
		},
		Past: {
			yo: "hubiera relatado",
			tú: "hubieras relatado",
			Ud: "hubiera relatado",
			nosotros: "hubiéramos relatado",
			vosotros: "hubierais relatado",
			Uds: "hubieran relatado",
		},
		Future: {
			yo: "hubiere relatado",
			tú: "hubieres relatado",
			Ud: "hubiere relatado",
			nosotros: "hubiéremos relatado",
			vosotros: "hubiereis relatado",
			Uds: "hubieren relatado",
		},
	},
}
