var relinchar = {
	Indicative: {
		Present: {
			yo: "relincho",
			tú: "relinchas",
			Ud: "relincha",
			nosotros: "relinchamos",
			vosotros: "relincháis",
			Uds: "relinchan",
		},
		Preterite: {
			yo: "relinché",
			tú: "relinchaste",
			Ud: "relinchó",
			nosotros: "relinchamos",
			vosotros: "relinchasteis",
			Uds: "relincharon",
		},
		Imperfect: {
			yo: "relinchaba",
			tú: "relinchabas",
			Ud: "relinchaba",
			nosotros: "relinchábamos",
			vosotros: "relinchabais",
			Uds: "relinchaban",
		},
		Conditional: {
			yo: "relincharía",
			tú: "relincharías",
			Ud: "relincharía",
			nosotros: "relincharíamos",
			vosotros: "relincharíais",
			Uds: "relincharían",
		},
		Future: {
			yo: "relincharé",
			tú: "relincharás",
			Ud: "relinchará",
			nosotros: "relincharemos",
			vosotros: "relincharéis",
			Uds: "relincharán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "relinche",
			tú: "relinches",
			Ud: "relinche",
			nosotros: "relinchemos",
			vosotros: "relinchéis",
			Uds: "relinchen",
		},
		Imperfect: {
			yo: "relinchara",
			tú: "relincharas",
			Ud: "relinchara",
			nosotros: "relincháramos",
			vosotros: "relincharais",
			Uds: "relincharan",
		},
		Imperfect2: {
			yo: "relinchase",
			tú: "relinchases",
			Ud: "relinchase",
			nosotros: "relinchásemos",
			vosotros: "relinchaseis",
			Uds: "relinchasen",
		},
		Future: {
			yo: "relinchare",
			tú: "relinchares",
			Ud: "relinchare",
			nosotros: "relincháremos",
			vosotros: "relinchareis",
			Uds: "relincharen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "relincha",
			Ud: "relinche",
			nosotros: "relinchemos",
			vosotros: "relinchad",
			Uds: "relinchen",
		},
		Negative: {
			tú: "no relinches",
			Ud: "no relinche",
			nosotros: "no relinchemos",
			vosotros: "no relinchéis",
			Uds: "no relinchen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy relinchando",
			tú: "estás relinchando",
			Ud: "está relinchando",
			nosotros: "estamos relinchando",
			vosotros: "estáis relinchando",
			Uds: "están relinchando",
		},
		Preterite: {
			yo: "estuve relinchando",
			tú: "estuviste relinchando",
			Ud: "estuvo relinchando",
			nosotros: "estuvimos relinchando",
			vosotros: "estuvisteis relinchando",
			Uds: "estuvieron relinchando",
		},
		Imperfect: {
			Uds: "estaban relinchando",
			yo: "estaba relinchando",
			tú: "estabas relinchando",
			Ud: "estaba relinchando",
			nosotros: "estábamos relinchando",
			vosotros: "estabais relinchando",
		},
		Conditional: {
			yo: "estaría relinchando",
			tú: "estarías relinchando",
			Ud: "estaría relinchando",
			nosotros: "estaríamos relinchando",
			vosotros: "estaríais relinchando",
			Uds: "estarían relinchando",
		},
		Future: {
			yo: "estaré relinchando",
			tú: "estarás relinchando",
			Ud: "estará relinchando",
			nosotros: "estaremos relinchando",
			vosotros: "estaréis relinchando",
			Uds: "estarán relinchando",
		},
	},
	Perfect: {
		Present: {
			yo: "he relinchado",
			tú: "has relinchado",
			Ud: "ha relinchado",
			nosotros: "hemos relinchado",
			vosotros: "habéis relinchado",
			Uds: "han relinchado",
		},
		Preterite: {
			yo: "hube relinchado",
			tú: "hubiste relinchado",
			Ud: "hubo relinchado",
			nosotros: "hubimos relinchado",
			vosotros: "hubisteis relinchado",
			Uds: "hubieron relinchado",
		},
		Past: {
			yo: "había relinchado",
			tú: "habías relinchado",
			Ud: "había relinchado",
			nosotros: "habíamos relinchado",
			vosotros: "habíais relinchado",
			Uds: "habían relinchado",
		},
		Conditional: {
			yo: "habría relinchado",
			tú: "habrías relinchado",
			Ud: "habría relinchado",
			nosotros: "habríamos relinchado",
			vosotros: "habríais relinchado",
			Uds: "habrían relinchado",
		},
		Future: {
			yo: "habré relinchado",
			tú: "habrás relinchado",
			Ud: "habrá relinchado",
			nosotros: "habremos relinchado",
			vosotros: "habréis relinchado",
			Uds: "habrán relinchado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya relinchado",
			tú: "hayas relinchado",
			Ud: "haya relinchado",
			nosotros: "hayamos relinchado",
			vosotros: "hayáis relinchado",
			Uds: "hayan relinchado",
		},
		Past: {
			yo: "hubiera relinchado",
			tú: "hubieras relinchado",
			Ud: "hubiera relinchado",
			nosotros: "hubiéramos relinchado",
			vosotros: "hubierais relinchado",
			Uds: "hubieran relinchado",
		},
		Future: {
			yo: "hubiere relinchado",
			tú: "hubieres relinchado",
			Ud: "hubiere relinchado",
			nosotros: "hubiéremos relinchado",
			vosotros: "hubiereis relinchado",
			Uds: "hubieren relinchado",
		},
	},
}
