var rellenar = {
	Indicative: {
		Present: {
			yo: "relleno",
			tú: "rellenas",
			Ud: "rellena",
			nosotros: "rellenamos",
			vosotros: "rellenáis",
			Uds: "rellenan",
		},
		Preterite: {
			yo: "rellené",
			tú: "rellenaste",
			Ud: "rellenó",
			nosotros: "rellenamos",
			vosotros: "rellenasteis",
			Uds: "rellenaron",
		},
		Imperfect: {
			yo: "rellenaba",
			tú: "rellenabas",
			Ud: "rellenaba",
			nosotros: "rellenábamos",
			vosotros: "rellenabais",
			Uds: "rellenaban",
		},
		Conditional: {
			yo: "rellenaría",
			tú: "rellenarías",
			Ud: "rellenaría",
			nosotros: "rellenaríamos",
			vosotros: "rellenaríais",
			Uds: "rellenarían",
		},
		Future: {
			yo: "rellenaré",
			tú: "rellenarás",
			Ud: "rellenará",
			nosotros: "rellenaremos",
			vosotros: "rellenaréis",
			Uds: "rellenarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "rellene",
			tú: "rellenes",
			Ud: "rellene",
			nosotros: "rellenemos",
			vosotros: "rellenéis",
			Uds: "rellenen",
		},
		Imperfect: {
			yo: "rellenara",
			tú: "rellenaras",
			Ud: "rellenara",
			nosotros: "rellenáramos",
			vosotros: "rellenarais",
			Uds: "rellenaran",
		},
		Imperfect2: {
			yo: "rellenase",
			tú: "rellenases",
			Ud: "rellenase",
			nosotros: "rellenásemos",
			vosotros: "rellenaseis",
			Uds: "rellenasen",
		},
		Future: {
			yo: "rellenare",
			tú: "rellenares",
			Ud: "rellenare",
			nosotros: "rellenáremos",
			vosotros: "rellenareis",
			Uds: "rellenaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "rellena",
			Ud: "rellene",
			nosotros: "rellenemos",
			vosotros: "rellenad",
			Uds: "rellenen",
		},
		Negative: {
			tú: "no rellenes",
			Ud: "no rellene",
			nosotros: "no rellenemos",
			vosotros: "no rellenéis",
			Uds: "no rellenen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy rellenando",
			tú: "estás rellenando",
			Ud: "está rellenando",
			nosotros: "estamos rellenando",
			vosotros: "estáis rellenando",
			Uds: "están rellenando",
		},
		Preterite: {
			yo: "estuve rellenando",
			tú: "estuviste rellenando",
			Ud: "estuvo rellenando",
			nosotros: "estuvimos rellenando",
			vosotros: "estuvisteis rellenando",
			Uds: "estuvieron rellenando",
		},
		Imperfect: {
			Uds: "estaban rellenando",
			yo: "estaba rellenando",
			tú: "estabas rellenando",
			Ud: "estaba rellenando",
			nosotros: "estábamos rellenando",
			vosotros: "estabais rellenando",
		},
		Conditional: {
			yo: "estaría rellenando",
			tú: "estarías rellenando",
			Ud: "estaría rellenando",
			nosotros: "estaríamos rellenando",
			vosotros: "estaríais rellenando",
			Uds: "estarían rellenando",
		},
		Future: {
			yo: "estaré rellenando",
			tú: "estarás rellenando",
			Ud: "estará rellenando",
			nosotros: "estaremos rellenando",
			vosotros: "estaréis rellenando",
			Uds: "estarán rellenando",
		},
	},
	Perfect: {
		Present: {
			yo: "he rellenado",
			tú: "has rellenado",
			Ud: "ha rellenado",
			nosotros: "hemos rellenado",
			vosotros: "habéis rellenado",
			Uds: "han rellenado",
		},
		Preterite: {
			yo: "hube rellenado",
			tú: "hubiste rellenado",
			Ud: "hubo rellenado",
			nosotros: "hubimos rellenado",
			vosotros: "hubisteis rellenado",
			Uds: "hubieron rellenado",
		},
		Past: {
			yo: "había rellenado",
			tú: "habías rellenado",
			Ud: "había rellenado",
			nosotros: "habíamos rellenado",
			vosotros: "habíais rellenado",
			Uds: "habían rellenado",
		},
		Conditional: {
			yo: "habría rellenado",
			tú: "habrías rellenado",
			Ud: "habría rellenado",
			nosotros: "habríamos rellenado",
			vosotros: "habríais rellenado",
			Uds: "habrían rellenado",
		},
		Future: {
			yo: "habré rellenado",
			tú: "habrás rellenado",
			Ud: "habrá rellenado",
			nosotros: "habremos rellenado",
			vosotros: "habréis rellenado",
			Uds: "habrán rellenado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya rellenado",
			tú: "hayas rellenado",
			Ud: "haya rellenado",
			nosotros: "hayamos rellenado",
			vosotros: "hayáis rellenado",
			Uds: "hayan rellenado",
		},
		Past: {
			yo: "hubiera rellenado",
			tú: "hubieras rellenado",
			Ud: "hubiera rellenado",
			nosotros: "hubiéramos rellenado",
			vosotros: "hubierais rellenado",
			Uds: "hubieran rellenado",
		},
		Future: {
			yo: "hubiere rellenado",
			tú: "hubieres rellenado",
			Ud: "hubiere rellenado",
			nosotros: "hubiéremos rellenado",
			vosotros: "hubiereis rellenado",
			Uds: "hubieren rellenado",
		},
	},
}
