var remover = {
	Indicative: {
		Present: {
			yo: "remuevo",
			tú: "remueves",
			Ud: "remueve",
			nosotros: "removemos",
			vosotros: "removéis",
			Uds: "remueven",
		},
		Preterite: {
			yo: "removí",
			tú: "removiste",
			Ud: "removió",
			nosotros: "removimos",
			vosotros: "removisteis",
			Uds: "removieron",
		},
		Imperfect: {
			yo: "removía",
			tú: "removías",
			Ud: "removía",
			nosotros: "removíamos",
			vosotros: "removíais",
			Uds: "removían",
		},
		Conditional: {
			yo: "removería",
			tú: "removerías",
			Ud: "removería",
			nosotros: "removeríamos",
			vosotros: "removeríais",
			Uds: "removerían",
		},
		Future: {
			yo: "removeré",
			tú: "removerás",
			Ud: "removerá",
			nosotros: "removeremos",
			vosotros: "removeréis",
			Uds: "removerán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "remueva",
			tú: "remuevas",
			Ud: "remueva",
			nosotros: "removamos",
			vosotros: "remováis",
			Uds: "remuevan",
		},
		Imperfect: {
			yo: "removiera",
			tú: "removieras",
			Ud: "removiera",
			nosotros: "removiéramos",
			vosotros: "removierais",
			Uds: "removieran",
		},
		Imperfect2: {
			yo: "removiese",
			tú: "removieses",
			Ud: "removiese",
			nosotros: "removiésemos",
			vosotros: "removieseis",
			Uds: "removiesen",
		},
		Future: {
			yo: "removiere",
			tú: "removieres",
			Ud: "removiere",
			nosotros: "removiéremos",
			vosotros: "removiereis",
			Uds: "removieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "remueve",
			Ud: "remueva",
			nosotros: "removamos",
			vosotros: "removed",
			Uds: "remuevan",
		},
		Negative: {
			tú: "no remuevas",
			Ud: "no remueva",
			nosotros: "no removamos",
			vosotros: "no remováis",
			Uds: "no remuevan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy removiendo",
			tú: "estás removiendo",
			Ud: "está removiendo",
			nosotros: "estamos removiendo",
			vosotros: "estáis removiendo",
			Uds: "están removiendo",
		},
		Preterite: {
			yo: "estuve removiendo",
			tú: "estuviste removiendo",
			Ud: "estuvo removiendo",
			nosotros: "estuvimos removiendo",
			vosotros: "estuvisteis removiendo",
			Uds: "estuvieron removiendo",
		},
		Imperfect: {
			Uds: "estaban removiendo",
			yo: "estaba removiendo",
			tú: "estabas removiendo",
			Ud: "estaba removiendo",
			nosotros: "estábamos removiendo",
			vosotros: "estabais removiendo",
		},
		Conditional: {
			yo: "estaría removiendo",
			tú: "estarías removiendo",
			Ud: "estaría removiendo",
			nosotros: "estaríamos removiendo",
			vosotros: "estaríais removiendo",
			Uds: "estarían removiendo",
		},
		Future: {
			yo: "estaré removiendo",
			tú: "estarás removiendo",
			Ud: "estará removiendo",
			nosotros: "estaremos removiendo",
			vosotros: "estaréis removiendo",
			Uds: "estarán removiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he removido",
			tú: "has removido",
			Ud: "ha removido",
			nosotros: "hemos removido",
			vosotros: "habéis removido",
			Uds: "han removido",
		},
		Preterite: {
			yo: "hube removido",
			tú: "hubiste removido",
			Ud: "hubo removido",
			nosotros: "hubimos removido",
			vosotros: "hubisteis removido",
			Uds: "hubieron removido",
		},
		Past: {
			yo: "había removido",
			tú: "habías removido",
			Ud: "había removido",
			nosotros: "habíamos removido",
			vosotros: "habíais removido",
			Uds: "habían removido",
		},
		Conditional: {
			yo: "habría removido",
			tú: "habrías removido",
			Ud: "habría removido",
			nosotros: "habríamos removido",
			vosotros: "habríais removido",
			Uds: "habrían removido",
		},
		Future: {
			yo: "habré removido",
			tú: "habrás removido",
			Ud: "habrá removido",
			nosotros: "habremos removido",
			vosotros: "habréis removido",
			Uds: "habrán removido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya removido",
			tú: "hayas removido",
			Ud: "haya removido",
			nosotros: "hayamos removido",
			vosotros: "hayáis removido",
			Uds: "hayan removido",
		},
		Past: {
			yo: "hubiera removido",
			tú: "hubieras removido",
			Ud: "hubiera removido",
			nosotros: "hubiéramos removido",
			vosotros: "hubierais removido",
			Uds: "hubieran removido",
		},
		Future: {
			yo: "hubiere removido",
			tú: "hubieres removido",
			Ud: "hubiere removido",
			nosotros: "hubiéremos removido",
			vosotros: "hubiereis removido",
			Uds: "hubieren removido",
		},
	},
}
