var reparar = {
	Indicative: {
		Present: {
			yo: "reparo",
			tú: "reparas",
			Ud: "repara",
			nosotros: "reparamos",
			vosotros: "reparáis",
			Uds: "reparan",
		},
		Preterite: {
			yo: "reparé",
			tú: "reparaste",
			Ud: "reparó",
			nosotros: "reparamos",
			vosotros: "reparasteis",
			Uds: "repararon",
		},
		Imperfect: {
			yo: "reparaba",
			tú: "reparabas",
			Ud: "reparaba",
			nosotros: "reparábamos",
			vosotros: "reparabais",
			Uds: "reparaban",
		},
		Conditional: {
			yo: "repararía",
			tú: "repararías",
			Ud: "repararía",
			nosotros: "repararíamos",
			vosotros: "repararíais",
			Uds: "repararían",
		},
		Future: {
			yo: "repararé",
			tú: "repararás",
			Ud: "reparará",
			nosotros: "repararemos",
			vosotros: "repararéis",
			Uds: "repararán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "repare",
			tú: "repares",
			Ud: "repare",
			nosotros: "reparemos",
			vosotros: "reparéis",
			Uds: "reparen",
		},
		Imperfect: {
			yo: "reparara",
			tú: "repararas",
			Ud: "reparara",
			nosotros: "reparáramos",
			vosotros: "repararais",
			Uds: "repararan",
		},
		Imperfect2: {
			yo: "reparase",
			tú: "reparases",
			Ud: "reparase",
			nosotros: "reparásemos",
			vosotros: "reparaseis",
			Uds: "reparasen",
		},
		Future: {
			yo: "reparare",
			tú: "reparares",
			Ud: "reparare",
			nosotros: "reparáremos",
			vosotros: "reparareis",
			Uds: "repararen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "repara",
			Ud: "repare",
			nosotros: "reparemos",
			vosotros: "reparad",
			Uds: "reparen",
		},
		Negative: {
			tú: "no repares",
			Ud: "no repare",
			nosotros: "no reparemos",
			vosotros: "no reparéis",
			Uds: "no reparen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy reparando",
			tú: "estás reparando",
			Ud: "está reparando",
			nosotros: "estamos reparando",
			vosotros: "estáis reparando",
			Uds: "están reparando",
		},
		Preterite: {
			yo: "estuve reparando",
			tú: "estuviste reparando",
			Ud: "estuvo reparando",
			nosotros: "estuvimos reparando",
			vosotros: "estuvisteis reparando",
			Uds: "estuvieron reparando",
		},
		Imperfect: {
			Uds: "estaban reparando",
			yo: "estaba reparando",
			tú: "estabas reparando",
			Ud: "estaba reparando",
			nosotros: "estábamos reparando",
			vosotros: "estabais reparando",
		},
		Conditional: {
			yo: "estaría reparando",
			tú: "estarías reparando",
			Ud: "estaría reparando",
			nosotros: "estaríamos reparando",
			vosotros: "estaríais reparando",
			Uds: "estarían reparando",
		},
		Future: {
			yo: "estaré reparando",
			tú: "estarás reparando",
			Ud: "estará reparando",
			nosotros: "estaremos reparando",
			vosotros: "estaréis reparando",
			Uds: "estarán reparando",
		},
	},
	Perfect: {
		Present: {
			yo: "he reparado",
			tú: "has reparado",
			Ud: "ha reparado",
			nosotros: "hemos reparado",
			vosotros: "habéis reparado",
			Uds: "han reparado",
		},
		Preterite: {
			yo: "hube reparado",
			tú: "hubiste reparado",
			Ud: "hubo reparado",
			nosotros: "hubimos reparado",
			vosotros: "hubisteis reparado",
			Uds: "hubieron reparado",
		},
		Past: {
			yo: "había reparado",
			tú: "habías reparado",
			Ud: "había reparado",
			nosotros: "habíamos reparado",
			vosotros: "habíais reparado",
			Uds: "habían reparado",
		},
		Conditional: {
			yo: "habría reparado",
			tú: "habrías reparado",
			Ud: "habría reparado",
			nosotros: "habríamos reparado",
			vosotros: "habríais reparado",
			Uds: "habrían reparado",
		},
		Future: {
			yo: "habré reparado",
			tú: "habrás reparado",
			Ud: "habrá reparado",
			nosotros: "habremos reparado",
			vosotros: "habréis reparado",
			Uds: "habrán reparado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya reparado",
			tú: "hayas reparado",
			Ud: "haya reparado",
			nosotros: "hayamos reparado",
			vosotros: "hayáis reparado",
			Uds: "hayan reparado",
		},
		Past: {
			yo: "hubiera reparado",
			tú: "hubieras reparado",
			Ud: "hubiera reparado",
			nosotros: "hubiéramos reparado",
			vosotros: "hubierais reparado",
			Uds: "hubieran reparado",
		},
		Future: {
			yo: "hubiere reparado",
			tú: "hubieres reparado",
			Ud: "hubiere reparado",
			nosotros: "hubiéremos reparado",
			vosotros: "hubiereis reparado",
			Uds: "hubieren reparado",
		},
	},
}
