var repeler = {
	Indicative: {
		Present: {
			yo: "repelo",
			tú: "repeles",
			Ud: "repele",
			nosotros: "repelemos",
			vosotros: "repeléis",
			Uds: "repelen",
		},
		Preterite: {
			yo: "repelí",
			tú: "repeliste",
			Ud: "repelió",
			nosotros: "repelimos",
			vosotros: "repelisteis",
			Uds: "repelieron",
		},
		Imperfect: {
			yo: "repelía",
			tú: "repelías",
			Ud: "repelía",
			nosotros: "repelíamos",
			vosotros: "repelíais",
			Uds: "repelían",
		},
		Conditional: {
			yo: "repelería",
			tú: "repelerías",
			Ud: "repelería",
			nosotros: "repeleríamos",
			vosotros: "repeleríais",
			Uds: "repelerían",
		},
		Future: {
			yo: "repeleré",
			tú: "repelerás",
			Ud: "repelerá",
			nosotros: "repeleremos",
			vosotros: "repeleréis",
			Uds: "repelerán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "repela",
			tú: "repelas",
			Ud: "repela",
			nosotros: "repelamos",
			vosotros: "repeláis",
			Uds: "repelan",
		},
		Imperfect: {
			yo: "repeliera",
			tú: "repelieras",
			Ud: "repeliera",
			nosotros: "repeliéramos",
			vosotros: "repelierais",
			Uds: "repelieran",
		},
		Imperfect2: {
			yo: "repeliese",
			tú: "repelieses",
			Ud: "repeliese",
			nosotros: "repeliésemos",
			vosotros: "repelieseis",
			Uds: "repeliesen",
		},
		Future: {
			yo: "repeliere",
			tú: "repelieres",
			Ud: "repeliere",
			nosotros: "repeliéremos",
			vosotros: "repeliereis",
			Uds: "repelieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "repele",
			Ud: "repela",
			nosotros: "repelamos",
			vosotros: "repeled",
			Uds: "repelan",
		},
		Negative: {
			tú: "no repelas",
			Ud: "no repela",
			nosotros: "no repelamos",
			vosotros: "no repeláis",
			Uds: "no repelan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy repeliendo",
			tú: "estás repeliendo",
			Ud: "está repeliendo",
			nosotros: "estamos repeliendo",
			vosotros: "estáis repeliendo",
			Uds: "están repeliendo",
		},
		Preterite: {
			yo: "estuve repeliendo",
			tú: "estuviste repeliendo",
			Ud: "estuvo repeliendo",
			nosotros: "estuvimos repeliendo",
			vosotros: "estuvisteis repeliendo",
			Uds: "estuvieron repeliendo",
		},
		Imperfect: {
			Uds: "estaban repeliendo",
			yo: "estaba repeliendo",
			tú: "estabas repeliendo",
			Ud: "estaba repeliendo",
			nosotros: "estábamos repeliendo",
			vosotros: "estabais repeliendo",
		},
		Conditional: {
			yo: "estaría repeliendo",
			tú: "estarías repeliendo",
			Ud: "estaría repeliendo",
			nosotros: "estaríamos repeliendo",
			vosotros: "estaríais repeliendo",
			Uds: "estarían repeliendo",
		},
		Future: {
			yo: "estaré repeliendo",
			tú: "estarás repeliendo",
			Ud: "estará repeliendo",
			nosotros: "estaremos repeliendo",
			vosotros: "estaréis repeliendo",
			Uds: "estarán repeliendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he repelido",
			tú: "has repelido",
			Ud: "ha repelido",
			nosotros: "hemos repelido",
			vosotros: "habéis repelido",
			Uds: "han repelido",
		},
		Preterite: {
			yo: "hube repelido",
			tú: "hubiste repelido",
			Ud: "hubo repelido",
			nosotros: "hubimos repelido",
			vosotros: "hubisteis repelido",
			Uds: "hubieron repelido",
		},
		Past: {
			yo: "había repelido",
			tú: "habías repelido",
			Ud: "había repelido",
			nosotros: "habíamos repelido",
			vosotros: "habíais repelido",
			Uds: "habían repelido",
		},
		Conditional: {
			yo: "habría repelido",
			tú: "habrías repelido",
			Ud: "habría repelido",
			nosotros: "habríamos repelido",
			vosotros: "habríais repelido",
			Uds: "habrían repelido",
		},
		Future: {
			yo: "habré repelido",
			tú: "habrás repelido",
			Ud: "habrá repelido",
			nosotros: "habremos repelido",
			vosotros: "habréis repelido",
			Uds: "habrán repelido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya repelido",
			tú: "hayas repelido",
			Ud: "haya repelido",
			nosotros: "hayamos repelido",
			vosotros: "hayáis repelido",
			Uds: "hayan repelido",
		},
		Past: {
			yo: "hubiera repelido",
			tú: "hubieras repelido",
			Ud: "hubiera repelido",
			nosotros: "hubiéramos repelido",
			vosotros: "hubierais repelido",
			Uds: "hubieran repelido",
		},
		Future: {
			yo: "hubiere repelido",
			tú: "hubieres repelido",
			Ud: "hubiere repelido",
			nosotros: "hubiéremos repelido",
			vosotros: "hubiereis repelido",
			Uds: "hubieren repelido",
		},
	},
}
