var repercutir = {
	Indicative: {
		Present: {
			yo: "repercuto",
			tú: "repercutes",
			Ud: "repercute",
			nosotros: "repercutimos",
			vosotros: "repercutís",
			Uds: "repercuten",
		},
		Preterite: {
			yo: "repercutí",
			tú: "repercutiste",
			Ud: "repercutió",
			nosotros: "repercutimos",
			vosotros: "repercutisteis",
			Uds: "repercutieron",
		},
		Imperfect: {
			yo: "repercutía",
			tú: "repercutías",
			Ud: "repercutía",
			nosotros: "repercutíamos",
			vosotros: "repercutíais",
			Uds: "repercutían",
		},
		Conditional: {
			yo: "repercutiría",
			tú: "repercutirías",
			Ud: "repercutiría",
			nosotros: "repercutiríamos",
			vosotros: "repercutiríais",
			Uds: "repercutirían",
		},
		Future: {
			yo: "repercutiré",
			tú: "repercutirás",
			Ud: "repercutirá",
			nosotros: "repercutiremos",
			vosotros: "repercutiréis",
			Uds: "repercutirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "repercuta",
			tú: "repercutas",
			Ud: "repercuta",
			nosotros: "repercutamos",
			vosotros: "repercutáis",
			Uds: "repercutan",
		},
		Imperfect: {
			yo: "repercutiera",
			tú: "repercutieras",
			Ud: "repercutiera",
			nosotros: "repercutiéramos",
			vosotros: "repercutierais",
			Uds: "repercutieran",
		},
		Imperfect2: {
			yo: "repercutiese",
			tú: "repercutieses",
			Ud: "repercutiese",
			nosotros: "repercutiésemos",
			vosotros: "repercutieseis",
			Uds: "repercutiesen",
		},
		Future: {
			yo: "repercutiere",
			tú: "repercutieres",
			Ud: "repercutiere",
			nosotros: "repercutiéremos",
			vosotros: "repercutiereis",
			Uds: "repercutieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "repercute",
			Ud: "repercuta",
			nosotros: "repercutamos",
			vosotros: "repercutid",
			Uds: "repercutan",
		},
		Negative: {
			tú: "no repercutas",
			Ud: "no repercuta",
			nosotros: "no repercutamos",
			vosotros: "no repercutáis",
			Uds: "no repercutan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy repercutiendo",
			tú: "estás repercutiendo",
			Ud: "está repercutiendo",
			nosotros: "estamos repercutiendo",
			vosotros: "estáis repercutiendo",
			Uds: "están repercutiendo",
		},
		Preterite: {
			yo: "estuve repercutiendo",
			tú: "estuviste repercutiendo",
			Ud: "estuvo repercutiendo",
			nosotros: "estuvimos repercutiendo",
			vosotros: "estuvisteis repercutiendo",
			Uds: "estuvieron repercutiendo",
		},
		Imperfect: {
			Uds: "estaban repercutiendo",
			yo: "estaba repercutiendo",
			tú: "estabas repercutiendo",
			Ud: "estaba repercutiendo",
			nosotros: "estábamos repercutiendo",
			vosotros: "estabais repercutiendo",
		},
		Conditional: {
			yo: "estaría repercutiendo",
			tú: "estarías repercutiendo",
			Ud: "estaría repercutiendo",
			nosotros: "estaríamos repercutiendo",
			vosotros: "estaríais repercutiendo",
			Uds: "estarían repercutiendo",
		},
		Future: {
			yo: "estaré repercutiendo",
			tú: "estarás repercutiendo",
			Ud: "estará repercutiendo",
			nosotros: "estaremos repercutiendo",
			vosotros: "estaréis repercutiendo",
			Uds: "estarán repercutiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he repercutido",
			tú: "has repercutido",
			Ud: "ha repercutido",
			nosotros: "hemos repercutido",
			vosotros: "habéis repercutido",
			Uds: "han repercutido",
		},
		Preterite: {
			yo: "hube repercutido",
			tú: "hubiste repercutido",
			Ud: "hubo repercutido",
			nosotros: "hubimos repercutido",
			vosotros: "hubisteis repercutido",
			Uds: "hubieron repercutido",
		},
		Past: {
			yo: "había repercutido",
			tú: "habías repercutido",
			Ud: "había repercutido",
			nosotros: "habíamos repercutido",
			vosotros: "habíais repercutido",
			Uds: "habían repercutido",
		},
		Conditional: {
			yo: "habría repercutido",
			tú: "habrías repercutido",
			Ud: "habría repercutido",
			nosotros: "habríamos repercutido",
			vosotros: "habríais repercutido",
			Uds: "habrían repercutido",
		},
		Future: {
			yo: "habré repercutido",
			tú: "habrás repercutido",
			Ud: "habrá repercutido",
			nosotros: "habremos repercutido",
			vosotros: "habréis repercutido",
			Uds: "habrán repercutido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya repercutido",
			tú: "hayas repercutido",
			Ud: "haya repercutido",
			nosotros: "hayamos repercutido",
			vosotros: "hayáis repercutido",
			Uds: "hayan repercutido",
		},
		Past: {
			yo: "hubiera repercutido",
			tú: "hubieras repercutido",
			Ud: "hubiera repercutido",
			nosotros: "hubiéramos repercutido",
			vosotros: "hubierais repercutido",
			Uds: "hubieran repercutido",
		},
		Future: {
			yo: "hubiere repercutido",
			tú: "hubieres repercutido",
			Ud: "hubiere repercutido",
			nosotros: "hubiéremos repercutido",
			vosotros: "hubiereis repercutido",
			Uds: "hubieren repercutido",
		},
	},
}
