var repetir = {
	Indicative: {
		Present: {
			yo: "repito",
			tú: "repites",
			Ud: "repite",
			nosotros: "repetimos",
			vosotros: "repetís",
			Uds: "repiten",
		},
		Preterite: {
			yo: "repetí",
			tú: "repetiste",
			Ud: "repitió",
			nosotros: "repetimos",
			vosotros: "repetisteis",
			Uds: "repitieron",
		},
		Imperfect: {
			yo: "repetía",
			tú: "repetías",
			Ud: "repetía",
			nosotros: "repetíamos",
			vosotros: "repetíais",
			Uds: "repetían",
		},
		Conditional: {
			yo: "repetiría",
			tú: "repetirías",
			Ud: "repetiría",
			nosotros: "repetiríamos",
			vosotros: "repetiríais",
			Uds: "repetirían",
		},
		Future: {
			yo: "repetiré",
			tú: "repetirás",
			Ud: "repetirá",
			nosotros: "repetiremos",
			vosotros: "repetiréis",
			Uds: "repetirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "repita",
			tú: "repitas",
			Ud: "repita",
			nosotros: "repitamos",
			vosotros: "repitáis",
			Uds: "repitan",
		},
		Imperfect: {
			yo: "repitiera",
			tú: "repitieras",
			Ud: "repitiera",
			nosotros: "repitiéramos",
			vosotros: "repitierais",
			Uds: "repitieran",
		},
		Imperfect2: {
			yo: "repitiese",
			tú: "repitieses",
			Ud: "repitiese",
			nosotros: "repitiésemos",
			vosotros: "repitieseis",
			Uds: "repitiesen",
		},
		Future: {
			yo: "repitiere",
			tú: "repitieres",
			Ud: "repitiere",
			nosotros: "repitiéremos",
			vosotros: "repitiereis",
			Uds: "repitieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "repite",
			Ud: "repita",
			nosotros: "repitamos",
			vosotros: "repetid",
			Uds: "repitan",
		},
		Negative: {
			tú: "no repitas",
			Ud: "no repita",
			nosotros: "no repitamos",
			vosotros: "no repitáis",
			Uds: "no repitan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy repitiendo",
			tú: "estás repitiendo",
			Ud: "está repitiendo",
			nosotros: "estamos repitiendo",
			vosotros: "estáis repitiendo",
			Uds: "están repitiendo",
		},
		Preterite: {
			yo: "estuve repitiendo",
			tú: "estuviste repitiendo",
			Ud: "estuvo repitiendo",
			nosotros: "estuvimos repitiendo",
			vosotros: "estuvisteis repitiendo",
			Uds: "estuvieron repitiendo",
		},
		Imperfect: {
			Uds: "estaban repitiendo",
			yo: "estaba repitiendo",
			tú: "estabas repitiendo",
			Ud: "estaba repitiendo",
			nosotros: "estábamos repitiendo",
			vosotros: "estabais repitiendo",
		},
		Conditional: {
			yo: "estaría repitiendo",
			tú: "estarías repitiendo",
			Ud: "estaría repitiendo",
			nosotros: "estaríamos repitiendo",
			vosotros: "estaríais repitiendo",
			Uds: "estarían repitiendo",
		},
		Future: {
			yo: "estaré repitiendo",
			tú: "estarás repitiendo",
			Ud: "estará repitiendo",
			nosotros: "estaremos repitiendo",
			vosotros: "estaréis repitiendo",
			Uds: "estarán repitiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he repetido",
			tú: "has repetido",
			Ud: "ha repetido",
			nosotros: "hemos repetido",
			vosotros: "habéis repetido",
			Uds: "han repetido",
		},
		Preterite: {
			yo: "hube repetido",
			tú: "hubiste repetido",
			Ud: "hubo repetido",
			nosotros: "hubimos repetido",
			vosotros: "hubisteis repetido",
			Uds: "hubieron repetido",
		},
		Past: {
			yo: "había repetido",
			tú: "habías repetido",
			Ud: "había repetido",
			nosotros: "habíamos repetido",
			vosotros: "habíais repetido",
			Uds: "habían repetido",
		},
		Conditional: {
			yo: "habría repetido",
			tú: "habrías repetido",
			Ud: "habría repetido",
			nosotros: "habríamos repetido",
			vosotros: "habríais repetido",
			Uds: "habrían repetido",
		},
		Future: {
			yo: "habré repetido",
			tú: "habrás repetido",
			Ud: "habrá repetido",
			nosotros: "habremos repetido",
			vosotros: "habréis repetido",
			Uds: "habrán repetido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya repetido",
			tú: "hayas repetido",
			Ud: "haya repetido",
			nosotros: "hayamos repetido",
			vosotros: "hayáis repetido",
			Uds: "hayan repetido",
		},
		Past: {
			yo: "hubiera repetido",
			tú: "hubieras repetido",
			Ud: "hubiera repetido",
			nosotros: "hubiéramos repetido",
			vosotros: "hubierais repetido",
			Uds: "hubieran repetido",
		},
		Future: {
			yo: "hubiere repetido",
			tú: "hubieres repetido",
			Ud: "hubiere repetido",
			nosotros: "hubiéremos repetido",
			vosotros: "hubiereis repetido",
			Uds: "hubieren repetido",
		},
	},
}
