var reproducir = {
	Indicative: {
		Present: {
			yo: "reproduzco",
			tú: "reproduces",
			Ud: "reproduce",
			nosotros: "reproducimos",
			vosotros: "reproducís",
			Uds: "reproducen",
		},
		Preterite: {
			yo: "reproduje",
			tú: "reprodujiste",
			Ud: "reprodujo",
			nosotros: "reprodujimos",
			vosotros: "reprodujisteis",
			Uds: "reprodujeron",
		},
		Imperfect: {
			yo: "reproducía",
			tú: "reproducías",
			Ud: "reproducía",
			nosotros: "reproducíamos",
			vosotros: "reproducíais",
			Uds: "reproducían",
		},
		Conditional: {
			yo: "reproduciría",
			tú: "reproducirías",
			Ud: "reproduciría",
			nosotros: "reproduciríamos",
			vosotros: "reproduciríais",
			Uds: "reproducirían",
		},
		Future: {
			yo: "reproduciré",
			tú: "reproducirás",
			Ud: "reproducirá",
			nosotros: "reproduciremos",
			vosotros: "reproduciréis",
			Uds: "reproducirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "reproduzca",
			tú: "reproduzcas",
			Ud: "reproduzca",
			nosotros: "reproduzcamos",
			vosotros: "reproduzcáis",
			Uds: "reproduzcan",
		},
		Imperfect: {
			yo: "reprodujera",
			tú: "reprodujeras",
			Ud: "reprodujera",
			nosotros: "reprodujéramos",
			vosotros: "reprodujerais",
			Uds: "reprodujeran",
		},
		Imperfect2: {
			yo: "reprodujese",
			tú: "reprodujeses",
			Ud: "reprodujese",
			nosotros: "reprodujésemos",
			vosotros: "reprodujeseis",
			Uds: "reprodujesen",
		},
		Future: {
			yo: "reprodujere",
			tú: "reprodujeres",
			Ud: "reprodujere",
			nosotros: "reprodujéremos",
			vosotros: "reprodujereis",
			Uds: "reprodujeren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "reproduce",
			Ud: "reproduzca",
			nosotros: "reproduzcamos",
			vosotros: "reproducid",
			Uds: "reproduzcan",
		},
		Negative: {
			tú: "no reproduzcas",
			Ud: "no reproduzca",
			nosotros: "no reproduzcamos",
			vosotros: "no reproduzcáis",
			Uds: "no reproduzcan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy reproduciendo",
			tú: "estás reproduciendo",
			Ud: "está reproduciendo",
			nosotros: "estamos reproduciendo",
			vosotros: "estáis reproduciendo",
			Uds: "están reproduciendo",
		},
		Preterite: {
			yo: "estuve reproduciendo",
			tú: "estuviste reproduciendo",
			Ud: "estuvo reproduciendo",
			nosotros: "estuvimos reproduciendo",
			vosotros: "estuvisteis reproduciendo",
			Uds: "estuvieron reproduciendo",
		},
		Imperfect: {
			Uds: "estaban reproduciendo",
			yo: "estaba reproduciendo",
			tú: "estabas reproduciendo",
			Ud: "estaba reproduciendo",
			nosotros: "estábamos reproduciendo",
			vosotros: "estabais reproduciendo",
		},
		Conditional: {
			yo: "estaría reproduciendo",
			tú: "estarías reproduciendo",
			Ud: "estaría reproduciendo",
			nosotros: "estaríamos reproduciendo",
			vosotros: "estaríais reproduciendo",
			Uds: "estarían reproduciendo",
		},
		Future: {
			yo: "estaré reproduciendo",
			tú: "estarás reproduciendo",
			Ud: "estará reproduciendo",
			nosotros: "estaremos reproduciendo",
			vosotros: "estaréis reproduciendo",
			Uds: "estarán reproduciendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he reproducido",
			tú: "has reproducido",
			Ud: "ha reproducido",
			nosotros: "hemos reproducido",
			vosotros: "habéis reproducido",
			Uds: "han reproducido",
		},
		Preterite: {
			yo: "hube reproducido",
			tú: "hubiste reproducido",
			Ud: "hubo reproducido",
			nosotros: "hubimos reproducido",
			vosotros: "hubisteis reproducido",
			Uds: "hubieron reproducido",
		},
		Past: {
			yo: "había reproducido",
			tú: "habías reproducido",
			Ud: "había reproducido",
			nosotros: "habíamos reproducido",
			vosotros: "habíais reproducido",
			Uds: "habían reproducido",
		},
		Conditional: {
			yo: "habría reproducido",
			tú: "habrías reproducido",
			Ud: "habría reproducido",
			nosotros: "habríamos reproducido",
			vosotros: "habríais reproducido",
			Uds: "habrían reproducido",
		},
		Future: {
			yo: "habré reproducido",
			tú: "habrás reproducido",
			Ud: "habrá reproducido",
			nosotros: "habremos reproducido",
			vosotros: "habréis reproducido",
			Uds: "habrán reproducido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya reproducido",
			tú: "hayas reproducido",
			Ud: "haya reproducido",
			nosotros: "hayamos reproducido",
			vosotros: "hayáis reproducido",
			Uds: "hayan reproducido",
		},
		Past: {
			yo: "hubiera reproducido",
			tú: "hubieras reproducido",
			Ud: "hubiera reproducido",
			nosotros: "hubiéramos reproducido",
			vosotros: "hubierais reproducido",
			Uds: "hubieran reproducido",
		},
		Future: {
			yo: "hubiere reproducido",
			tú: "hubieres reproducido",
			Ud: "hubiere reproducido",
			nosotros: "hubiéremos reproducido",
			vosotros: "hubiereis reproducido",
			Uds: "hubieren reproducido",
		},
	},
}
