var reprochar = {
	Indicative: {
		Present: {
			yo: "reprocho",
			tú: "reprochas",
			Ud: "reprocha",
			nosotros: "reprochamos",
			vosotros: "reprocháis",
			Uds: "reprochan",
		},
		Preterite: {
			yo: "reproché",
			tú: "reprochaste",
			Ud: "reprochó",
			nosotros: "reprochamos",
			vosotros: "reprochasteis",
			Uds: "reprocharon",
		},
		Imperfect: {
			yo: "reprochaba",
			tú: "reprochabas",
			Ud: "reprochaba",
			nosotros: "reprochábamos",
			vosotros: "reprochabais",
			Uds: "reprochaban",
		},
		Conditional: {
			yo: "reprocharía",
			tú: "reprocharías",
			Ud: "reprocharía",
			nosotros: "reprocharíamos",
			vosotros: "reprocharíais",
			Uds: "reprocharían",
		},
		Future: {
			yo: "reprocharé",
			tú: "reprocharás",
			Ud: "reprochará",
			nosotros: "reprocharemos",
			vosotros: "reprocharéis",
			Uds: "reprocharán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "reproche",
			tú: "reproches",
			Ud: "reproche",
			nosotros: "reprochemos",
			vosotros: "reprochéis",
			Uds: "reprochen",
		},
		Imperfect: {
			yo: "reprochara",
			tú: "reprocharas",
			Ud: "reprochara",
			nosotros: "reprocháramos",
			vosotros: "reprocharais",
			Uds: "reprocharan",
		},
		Imperfect2: {
			yo: "reprochase",
			tú: "reprochases",
			Ud: "reprochase",
			nosotros: "reprochásemos",
			vosotros: "reprochaseis",
			Uds: "reprochasen",
		},
		Future: {
			yo: "reprochare",
			tú: "reprochares",
			Ud: "reprochare",
			nosotros: "reprocháremos",
			vosotros: "reprochareis",
			Uds: "reprocharen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "reprocha",
			Ud: "reproche",
			nosotros: "reprochemos",
			vosotros: "reprochad",
			Uds: "reprochen",
		},
		Negative: {
			tú: "no reproches",
			Ud: "no reproche",
			nosotros: "no reprochemos",
			vosotros: "no reprochéis",
			Uds: "no reprochen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy reprochando",
			tú: "estás reprochando",
			Ud: "está reprochando",
			nosotros: "estamos reprochando",
			vosotros: "estáis reprochando",
			Uds: "están reprochando",
		},
		Preterite: {
			yo: "estuve reprochando",
			tú: "estuviste reprochando",
			Ud: "estuvo reprochando",
			nosotros: "estuvimos reprochando",
			vosotros: "estuvisteis reprochando",
			Uds: "estuvieron reprochando",
		},
		Imperfect: {
			Uds: "estaban reprochando",
			yo: "estaba reprochando",
			tú: "estabas reprochando",
			Ud: "estaba reprochando",
			nosotros: "estábamos reprochando",
			vosotros: "estabais reprochando",
		},
		Conditional: {
			yo: "estaría reprochando",
			tú: "estarías reprochando",
			Ud: "estaría reprochando",
			nosotros: "estaríamos reprochando",
			vosotros: "estaríais reprochando",
			Uds: "estarían reprochando",
		},
		Future: {
			yo: "estaré reprochando",
			tú: "estarás reprochando",
			Ud: "estará reprochando",
			nosotros: "estaremos reprochando",
			vosotros: "estaréis reprochando",
			Uds: "estarán reprochando",
		},
	},
	Perfect: {
		Present: {
			yo: "he reprochado",
			tú: "has reprochado",
			Ud: "ha reprochado",
			nosotros: "hemos reprochado",
			vosotros: "habéis reprochado",
			Uds: "han reprochado",
		},
		Preterite: {
			yo: "hube reprochado",
			tú: "hubiste reprochado",
			Ud: "hubo reprochado",
			nosotros: "hubimos reprochado",
			vosotros: "hubisteis reprochado",
			Uds: "hubieron reprochado",
		},
		Past: {
			yo: "había reprochado",
			tú: "habías reprochado",
			Ud: "había reprochado",
			nosotros: "habíamos reprochado",
			vosotros: "habíais reprochado",
			Uds: "habían reprochado",
		},
		Conditional: {
			yo: "habría reprochado",
			tú: "habrías reprochado",
			Ud: "habría reprochado",
			nosotros: "habríamos reprochado",
			vosotros: "habríais reprochado",
			Uds: "habrían reprochado",
		},
		Future: {
			yo: "habré reprochado",
			tú: "habrás reprochado",
			Ud: "habrá reprochado",
			nosotros: "habremos reprochado",
			vosotros: "habréis reprochado",
			Uds: "habrán reprochado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya reprochado",
			tú: "hayas reprochado",
			Ud: "haya reprochado",
			nosotros: "hayamos reprochado",
			vosotros: "hayáis reprochado",
			Uds: "hayan reprochado",
		},
		Past: {
			yo: "hubiera reprochado",
			tú: "hubieras reprochado",
			Ud: "hubiera reprochado",
			nosotros: "hubiéramos reprochado",
			vosotros: "hubierais reprochado",
			Uds: "hubieran reprochado",
		},
		Future: {
			yo: "hubiere reprochado",
			tú: "hubieres reprochado",
			Ud: "hubiere reprochado",
			nosotros: "hubiéremos reprochado",
			vosotros: "hubiereis reprochado",
			Uds: "hubieren reprochado",
		},
	},
}
