var representar = {
	Indicative: {
		Present: {
			yo: "represento",
			tú: "representas",
			Ud: "representa",
			nosotros: "representamos",
			vosotros: "representáis",
			Uds: "representan",
		},
		Preterite: {
			yo: "representé",
			tú: "representaste",
			Ud: "representó",
			nosotros: "representamos",
			vosotros: "representasteis",
			Uds: "representaron",
		},
		Imperfect: {
			yo: "representaba",
			tú: "representabas",
			Ud: "representaba",
			nosotros: "representábamos",
			vosotros: "representabais",
			Uds: "representaban",
		},
		Conditional: {
			yo: "representaría",
			tú: "representarías",
			Ud: "representaría",
			nosotros: "representaríamos",
			vosotros: "representaríais",
			Uds: "representarían",
		},
		Future: {
			yo: "representaré",
			tú: "representarás",
			Ud: "representará",
			nosotros: "representaremos",
			vosotros: "representaréis",
			Uds: "representarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "represente",
			tú: "representes",
			Ud: "represente",
			nosotros: "representemos",
			vosotros: "representéis",
			Uds: "representen",
		},
		Imperfect: {
			yo: "representara",
			tú: "representaras",
			Ud: "representara",
			nosotros: "representáramos",
			vosotros: "representarais",
			Uds: "representaran",
		},
		Imperfect2: {
			yo: "representase",
			tú: "representases",
			Ud: "representase",
			nosotros: "representásemos",
			vosotros: "representaseis",
			Uds: "representasen",
		},
		Future: {
			yo: "representare",
			tú: "representares",
			Ud: "representare",
			nosotros: "representáremos",
			vosotros: "representareis",
			Uds: "representaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "representa",
			Ud: "represente",
			nosotros: "representemos",
			vosotros: "representad",
			Uds: "representen",
		},
		Negative: {
			tú: "no representes",
			Ud: "no represente",
			nosotros: "no representemos",
			vosotros: "no representéis",
			Uds: "no representen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy representando",
			tú: "estás representando",
			Ud: "está representando",
			nosotros: "estamos representando",
			vosotros: "estáis representando",
			Uds: "están representando",
		},
		Preterite: {
			yo: "estuve representando",
			tú: "estuviste representando",
			Ud: "estuvo representando",
			nosotros: "estuvimos representando",
			vosotros: "estuvisteis representando",
			Uds: "estuvieron representando",
		},
		Imperfect: {
			Uds: "estaban representando",
			yo: "estaba representando",
			tú: "estabas representando",
			Ud: "estaba representando",
			nosotros: "estábamos representando",
			vosotros: "estabais representando",
		},
		Conditional: {
			yo: "estaría representando",
			tú: "estarías representando",
			Ud: "estaría representando",
			nosotros: "estaríamos representando",
			vosotros: "estaríais representando",
			Uds: "estarían representando",
		},
		Future: {
			yo: "estaré representando",
			tú: "estarás representando",
			Ud: "estará representando",
			nosotros: "estaremos representando",
			vosotros: "estaréis representando",
			Uds: "estarán representando",
		},
	},
	Perfect: {
		Present: {
			yo: "he representado",
			tú: "has representado",
			Ud: "ha representado",
			nosotros: "hemos representado",
			vosotros: "habéis representado",
			Uds: "han representado",
		},
		Preterite: {
			yo: "hube representado",
			tú: "hubiste representado",
			Ud: "hubo representado",
			nosotros: "hubimos representado",
			vosotros: "hubisteis representado",
			Uds: "hubieron representado",
		},
		Past: {
			yo: "había representado",
			tú: "habías representado",
			Ud: "había representado",
			nosotros: "habíamos representado",
			vosotros: "habíais representado",
			Uds: "habían representado",
		},
		Conditional: {
			yo: "habría representado",
			tú: "habrías representado",
			Ud: "habría representado",
			nosotros: "habríamos representado",
			vosotros: "habríais representado",
			Uds: "habrían representado",
		},
		Future: {
			yo: "habré representado",
			tú: "habrás representado",
			Ud: "habrá representado",
			nosotros: "habremos representado",
			vosotros: "habréis representado",
			Uds: "habrán representado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya representado",
			tú: "hayas representado",
			Ud: "haya representado",
			nosotros: "hayamos representado",
			vosotros: "hayáis representado",
			Uds: "hayan representado",
		},
		Past: {
			yo: "hubiera representado",
			tú: "hubieras representado",
			Ud: "hubiera representado",
			nosotros: "hubiéramos representado",
			vosotros: "hubierais representado",
			Uds: "hubieran representado",
		},
		Future: {
			yo: "hubiere representado",
			tú: "hubieres representado",
			Ud: "hubiere representado",
			nosotros: "hubiéremos representado",
			vosotros: "hubiereis representado",
			Uds: "hubieren representado",
		},
	},
}
