var reprimir = {
	Indicative: {
		Present: {
			yo: "reprimo",
			tú: "reprimes",
			Ud: "reprime",
			nosotros: "reprimimos",
			vosotros: "reprimís",
			Uds: "reprimen",
		},
		Preterite: {
			yo: "reprimí",
			tú: "reprimiste",
			Ud: "reprimió",
			nosotros: "reprimimos",
			vosotros: "reprimisteis",
			Uds: "reprimieron",
		},
		Imperfect: {
			yo: "reprimía",
			tú: "reprimías",
			Ud: "reprimía",
			nosotros: "reprimíamos",
			vosotros: "reprimíais",
			Uds: "reprimían",
		},
		Conditional: {
			yo: "reprimiría",
			tú: "reprimirías",
			Ud: "reprimiría",
			nosotros: "reprimiríamos",
			vosotros: "reprimiríais",
			Uds: "reprimirían",
		},
		Future: {
			yo: "reprimiré",
			tú: "reprimirás",
			Ud: "reprimirá",
			nosotros: "reprimiremos",
			vosotros: "reprimiréis",
			Uds: "reprimirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "reprima",
			tú: "reprimas",
			Ud: "reprima",
			nosotros: "reprimamos",
			vosotros: "reprimáis",
			Uds: "repriman",
		},
		Imperfect: {
			yo: "reprimiera",
			tú: "reprimieras",
			Ud: "reprimiera",
			nosotros: "reprimiéramos",
			vosotros: "reprimierais",
			Uds: "reprimieran",
		},
		Imperfect2: {
			yo: "reprimiese",
			tú: "reprimieses",
			Ud: "reprimiese",
			nosotros: "reprimiésemos",
			vosotros: "reprimieseis",
			Uds: "reprimiesen",
		},
		Future: {
			yo: "reprimiere",
			tú: "reprimieres",
			Ud: "reprimiere",
			nosotros: "reprimiéremos",
			vosotros: "reprimiereis",
			Uds: "reprimieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "reprime",
			Ud: "reprima",
			nosotros: "reprimamos",
			vosotros: "reprimid",
			Uds: "repriman",
		},
		Negative: {
			tú: "no reprimas",
			Ud: "no reprima",
			nosotros: "no reprimamos",
			vosotros: "no reprimáis",
			Uds: "no repriman",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy reprimiendo",
			tú: "estás reprimiendo",
			Ud: "está reprimiendo",
			nosotros: "estamos reprimiendo",
			vosotros: "estáis reprimiendo",
			Uds: "están reprimiendo",
		},
		Preterite: {
			yo: "estuve reprimiendo",
			tú: "estuviste reprimiendo",
			Ud: "estuvo reprimiendo",
			nosotros: "estuvimos reprimiendo",
			vosotros: "estuvisteis reprimiendo",
			Uds: "estuvieron reprimiendo",
		},
		Imperfect: {
			Uds: "estaban reprimiendo",
			yo: "estaba reprimiendo",
			tú: "estabas reprimiendo",
			Ud: "estaba reprimiendo",
			nosotros: "estábamos reprimiendo",
			vosotros: "estabais reprimiendo",
		},
		Conditional: {
			yo: "estaría reprimiendo",
			tú: "estarías reprimiendo",
			Ud: "estaría reprimiendo",
			nosotros: "estaríamos reprimiendo",
			vosotros: "estaríais reprimiendo",
			Uds: "estarían reprimiendo",
		},
		Future: {
			yo: "estaré reprimiendo",
			tú: "estarás reprimiendo",
			Ud: "estará reprimiendo",
			nosotros: "estaremos reprimiendo",
			vosotros: "estaréis reprimiendo",
			Uds: "estarán reprimiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he reprimido",
			tú: "has reprimido",
			Ud: "ha reprimido",
			nosotros: "hemos reprimido",
			vosotros: "habéis reprimido",
			Uds: "han reprimido",
		},
		Preterite: {
			yo: "hube reprimido",
			tú: "hubiste reprimido",
			Ud: "hubo reprimido",
			nosotros: "hubimos reprimido",
			vosotros: "hubisteis reprimido",
			Uds: "hubieron reprimido",
		},
		Past: {
			yo: "había reprimido",
			tú: "habías reprimido",
			Ud: "había reprimido",
			nosotros: "habíamos reprimido",
			vosotros: "habíais reprimido",
			Uds: "habían reprimido",
		},
		Conditional: {
			yo: "habría reprimido",
			tú: "habrías reprimido",
			Ud: "habría reprimido",
			nosotros: "habríamos reprimido",
			vosotros: "habríais reprimido",
			Uds: "habrían reprimido",
		},
		Future: {
			yo: "habré reprimido",
			tú: "habrás reprimido",
			Ud: "habrá reprimido",
			nosotros: "habremos reprimido",
			vosotros: "habréis reprimido",
			Uds: "habrán reprimido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya reprimido",
			tú: "hayas reprimido",
			Ud: "haya reprimido",
			nosotros: "hayamos reprimido",
			vosotros: "hayáis reprimido",
			Uds: "hayan reprimido",
		},
		Past: {
			yo: "hubiera reprimido",
			tú: "hubieras reprimido",
			Ud: "hubiera reprimido",
			nosotros: "hubiéramos reprimido",
			vosotros: "hubierais reprimido",
			Uds: "hubieran reprimido",
		},
		Future: {
			yo: "hubiere reprimido",
			tú: "hubieres reprimido",
			Ud: "hubiere reprimido",
			nosotros: "hubiéremos reprimido",
			vosotros: "hubiereis reprimido",
			Uds: "hubieren reprimido",
		},
	},
}
