var rescatar = {
	Indicative: {
		Present: {
			yo: "rescato",
			tú: "rescatas",
			Ud: "rescata",
			nosotros: "rescatamos",
			vosotros: "rescatáis",
			Uds: "rescatan",
		},
		Preterite: {
			yo: "rescaté",
			tú: "rescataste",
			Ud: "rescató",
			nosotros: "rescatamos",
			vosotros: "rescatasteis",
			Uds: "rescataron",
		},
		Imperfect: {
			yo: "rescataba",
			tú: "rescatabas",
			Ud: "rescataba",
			nosotros: "rescatábamos",
			vosotros: "rescatabais",
			Uds: "rescataban",
		},
		Conditional: {
			yo: "rescataría",
			tú: "rescatarías",
			Ud: "rescataría",
			nosotros: "rescataríamos",
			vosotros: "rescataríais",
			Uds: "rescatarían",
		},
		Future: {
			yo: "rescataré",
			tú: "rescatarás",
			Ud: "rescatará",
			nosotros: "rescataremos",
			vosotros: "rescataréis",
			Uds: "rescatarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "rescate",
			tú: "rescates",
			Ud: "rescate",
			nosotros: "rescatemos",
			vosotros: "rescatéis",
			Uds: "rescaten",
		},
		Imperfect: {
			yo: "rescatara",
			tú: "rescataras",
			Ud: "rescatara",
			nosotros: "rescatáramos",
			vosotros: "rescatarais",
			Uds: "rescataran",
		},
		Imperfect2: {
			yo: "rescatase",
			tú: "rescatases",
			Ud: "rescatase",
			nosotros: "rescatásemos",
			vosotros: "rescataseis",
			Uds: "rescatasen",
		},
		Future: {
			yo: "rescatare",
			tú: "rescatares",
			Ud: "rescatare",
			nosotros: "rescatáremos",
			vosotros: "rescatareis",
			Uds: "rescataren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "rescata",
			Ud: "rescate",
			nosotros: "rescatemos",
			vosotros: "rescatad",
			Uds: "rescaten",
		},
		Negative: {
			tú: "no rescates",
			Ud: "no rescate",
			nosotros: "no rescatemos",
			vosotros: "no rescatéis",
			Uds: "no rescaten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy rescatando",
			tú: "estás rescatando",
			Ud: "está rescatando",
			nosotros: "estamos rescatando",
			vosotros: "estáis rescatando",
			Uds: "están rescatando",
		},
		Preterite: {
			yo: "estuve rescatando",
			tú: "estuviste rescatando",
			Ud: "estuvo rescatando",
			nosotros: "estuvimos rescatando",
			vosotros: "estuvisteis rescatando",
			Uds: "estuvieron rescatando",
		},
		Imperfect: {
			Uds: "estaban rescatando",
			yo: "estaba rescatando",
			tú: "estabas rescatando",
			Ud: "estaba rescatando",
			nosotros: "estábamos rescatando",
			vosotros: "estabais rescatando",
		},
		Conditional: {
			yo: "estaría rescatando",
			tú: "estarías rescatando",
			Ud: "estaría rescatando",
			nosotros: "estaríamos rescatando",
			vosotros: "estaríais rescatando",
			Uds: "estarían rescatando",
		},
		Future: {
			yo: "estaré rescatando",
			tú: "estarás rescatando",
			Ud: "estará rescatando",
			nosotros: "estaremos rescatando",
			vosotros: "estaréis rescatando",
			Uds: "estarán rescatando",
		},
	},
	Perfect: {
		Present: {
			yo: "he rescatado",
			tú: "has rescatado",
			Ud: "ha rescatado",
			nosotros: "hemos rescatado",
			vosotros: "habéis rescatado",
			Uds: "han rescatado",
		},
		Preterite: {
			yo: "hube rescatado",
			tú: "hubiste rescatado",
			Ud: "hubo rescatado",
			nosotros: "hubimos rescatado",
			vosotros: "hubisteis rescatado",
			Uds: "hubieron rescatado",
		},
		Past: {
			yo: "había rescatado",
			tú: "habías rescatado",
			Ud: "había rescatado",
			nosotros: "habíamos rescatado",
			vosotros: "habíais rescatado",
			Uds: "habían rescatado",
		},
		Conditional: {
			yo: "habría rescatado",
			tú: "habrías rescatado",
			Ud: "habría rescatado",
			nosotros: "habríamos rescatado",
			vosotros: "habríais rescatado",
			Uds: "habrían rescatado",
		},
		Future: {
			yo: "habré rescatado",
			tú: "habrás rescatado",
			Ud: "habrá rescatado",
			nosotros: "habremos rescatado",
			vosotros: "habréis rescatado",
			Uds: "habrán rescatado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya rescatado",
			tú: "hayas rescatado",
			Ud: "haya rescatado",
			nosotros: "hayamos rescatado",
			vosotros: "hayáis rescatado",
			Uds: "hayan rescatado",
		},
		Past: {
			yo: "hubiera rescatado",
			tú: "hubieras rescatado",
			Ud: "hubiera rescatado",
			nosotros: "hubiéramos rescatado",
			vosotros: "hubierais rescatado",
			Uds: "hubieran rescatado",
		},
		Future: {
			yo: "hubiere rescatado",
			tú: "hubieres rescatado",
			Ud: "hubiere rescatado",
			nosotros: "hubiéremos rescatado",
			vosotros: "hubiereis rescatado",
			Uds: "hubieren rescatado",
		},
	},
}
