var reservar = {
	Indicative: {
		Present: {
			yo: "reservo",
			tú: "reservas",
			Ud: "reserva",
			nosotros: "reservamos",
			vosotros: "reserváis",
			Uds: "reservan",
		},
		Preterite: {
			yo: "reservé",
			tú: "reservaste",
			Ud: "reservó",
			nosotros: "reservamos",
			vosotros: "reservasteis",
			Uds: "reservaron",
		},
		Imperfect: {
			yo: "reservaba",
			tú: "reservabas",
			Ud: "reservaba",
			nosotros: "reservábamos",
			vosotros: "reservabais",
			Uds: "reservaban",
		},
		Conditional: {
			yo: "reservaría",
			tú: "reservarías",
			Ud: "reservaría",
			nosotros: "reservaríamos",
			vosotros: "reservaríais",
			Uds: "reservarían",
		},
		Future: {
			yo: "reservaré",
			tú: "reservarás",
			Ud: "reservará",
			nosotros: "reservaremos",
			vosotros: "reservaréis",
			Uds: "reservarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "reserve",
			tú: "reserves",
			Ud: "reserve",
			nosotros: "reservemos",
			vosotros: "reservéis",
			Uds: "reserven",
		},
		Imperfect: {
			yo: "reservara",
			tú: "reservaras",
			Ud: "reservara",
			nosotros: "reserváramos",
			vosotros: "reservarais",
			Uds: "reservaran",
		},
		Imperfect2: {
			yo: "reservase",
			tú: "reservases",
			Ud: "reservase",
			nosotros: "reservásemos",
			vosotros: "reservaseis",
			Uds: "reservasen",
		},
		Future: {
			yo: "reservare",
			tú: "reservares",
			Ud: "reservare",
			nosotros: "reserváremos",
			vosotros: "reservareis",
			Uds: "reservaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "reserva",
			Ud: "reserve",
			nosotros: "reservemos",
			vosotros: "reservad",
			Uds: "reserven",
		},
		Negative: {
			tú: "no reserves",
			Ud: "no reserve",
			nosotros: "no reservemos",
			vosotros: "no reservéis",
			Uds: "no reserven",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy reservando",
			tú: "estás reservando",
			Ud: "está reservando",
			nosotros: "estamos reservando",
			vosotros: "estáis reservando",
			Uds: "están reservando",
		},
		Preterite: {
			yo: "estuve reservando",
			tú: "estuviste reservando",
			Ud: "estuvo reservando",
			nosotros: "estuvimos reservando",
			vosotros: "estuvisteis reservando",
			Uds: "estuvieron reservando",
		},
		Imperfect: {
			Uds: "estaban reservando",
			yo: "estaba reservando",
			tú: "estabas reservando",
			Ud: "estaba reservando",
			nosotros: "estábamos reservando",
			vosotros: "estabais reservando",
		},
		Conditional: {
			yo: "estaría reservando",
			tú: "estarías reservando",
			Ud: "estaría reservando",
			nosotros: "estaríamos reservando",
			vosotros: "estaríais reservando",
			Uds: "estarían reservando",
		},
		Future: {
			yo: "estaré reservando",
			tú: "estarás reservando",
			Ud: "estará reservando",
			nosotros: "estaremos reservando",
			vosotros: "estaréis reservando",
			Uds: "estarán reservando",
		},
	},
	Perfect: {
		Present: {
			yo: "he reservado",
			tú: "has reservado",
			Ud: "ha reservado",
			nosotros: "hemos reservado",
			vosotros: "habéis reservado",
			Uds: "han reservado",
		},
		Preterite: {
			yo: "hube reservado",
			tú: "hubiste reservado",
			Ud: "hubo reservado",
			nosotros: "hubimos reservado",
			vosotros: "hubisteis reservado",
			Uds: "hubieron reservado",
		},
		Past: {
			yo: "había reservado",
			tú: "habías reservado",
			Ud: "había reservado",
			nosotros: "habíamos reservado",
			vosotros: "habíais reservado",
			Uds: "habían reservado",
		},
		Conditional: {
			yo: "habría reservado",
			tú: "habrías reservado",
			Ud: "habría reservado",
			nosotros: "habríamos reservado",
			vosotros: "habríais reservado",
			Uds: "habrían reservado",
		},
		Future: {
			yo: "habré reservado",
			tú: "habrás reservado",
			Ud: "habrá reservado",
			nosotros: "habremos reservado",
			vosotros: "habréis reservado",
			Uds: "habrán reservado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya reservado",
			tú: "hayas reservado",
			Ud: "haya reservado",
			nosotros: "hayamos reservado",
			vosotros: "hayáis reservado",
			Uds: "hayan reservado",
		},
		Past: {
			yo: "hubiera reservado",
			tú: "hubieras reservado",
			Ud: "hubiera reservado",
			nosotros: "hubiéramos reservado",
			vosotros: "hubierais reservado",
			Uds: "hubieran reservado",
		},
		Future: {
			yo: "hubiere reservado",
			tú: "hubieres reservado",
			Ud: "hubiere reservado",
			nosotros: "hubiéremos reservado",
			vosotros: "hubiereis reservado",
			Uds: "hubieren reservado",
		},
	},
}
