var resistir = {
	Indicative: {
		Present: {
			yo: "resisto",
			tú: "resistes",
			Ud: "resiste",
			nosotros: "resistimos",
			vosotros: "resistís",
			Uds: "resisten",
		},
		Preterite: {
			yo: "resistí",
			tú: "resististe",
			Ud: "resistió",
			nosotros: "resistimos",
			vosotros: "resististeis",
			Uds: "resistieron",
		},
		Imperfect: {
			yo: "resistía",
			tú: "resistías",
			Ud: "resistía",
			nosotros: "resistíamos",
			vosotros: "resistíais",
			Uds: "resistían",
		},
		Conditional: {
			yo: "resistiría",
			tú: "resistirías",
			Ud: "resistiría",
			nosotros: "resistiríamos",
			vosotros: "resistiríais",
			Uds: "resistirían",
		},
		Future: {
			yo: "resistiré",
			tú: "resistirás",
			Ud: "resistirá",
			nosotros: "resistiremos",
			vosotros: "resistiréis",
			Uds: "resistirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "resista",
			tú: "resistas",
			Ud: "resista",
			nosotros: "resistamos",
			vosotros: "resistáis",
			Uds: "resistan",
		},
		Imperfect: {
			yo: "resistiera",
			tú: "resistieras",
			Ud: "resistiera",
			nosotros: "resistiéramos",
			vosotros: "resistierais",
			Uds: "resistieran",
		},
		Imperfect2: {
			yo: "resistiese",
			tú: "resistieses",
			Ud: "resistiese",
			nosotros: "resistiésemos",
			vosotros: "resistieseis",
			Uds: "resistiesen",
		},
		Future: {
			yo: "resistiere",
			tú: "resistieres",
			Ud: "resistiere",
			nosotros: "resistiéremos",
			vosotros: "resistiereis",
			Uds: "resistieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "resiste",
			Ud: "resista",
			nosotros: "resistamos",
			vosotros: "resistid",
			Uds: "resistan",
		},
		Negative: {
			tú: "no resistas",
			Ud: "no resista",
			nosotros: "no resistamos",
			vosotros: "no resistáis",
			Uds: "no resistan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy resistiendo",
			tú: "estás resistiendo",
			Ud: "está resistiendo",
			nosotros: "estamos resistiendo",
			vosotros: "estáis resistiendo",
			Uds: "están resistiendo",
		},
		Preterite: {
			yo: "estuve resistiendo",
			tú: "estuviste resistiendo",
			Ud: "estuvo resistiendo",
			nosotros: "estuvimos resistiendo",
			vosotros: "estuvisteis resistiendo",
			Uds: "estuvieron resistiendo",
		},
		Imperfect: {
			Uds: "estaban resistiendo",
			yo: "estaba resistiendo",
			tú: "estabas resistiendo",
			Ud: "estaba resistiendo",
			nosotros: "estábamos resistiendo",
			vosotros: "estabais resistiendo",
		},
		Conditional: {
			yo: "estaría resistiendo",
			tú: "estarías resistiendo",
			Ud: "estaría resistiendo",
			nosotros: "estaríamos resistiendo",
			vosotros: "estaríais resistiendo",
			Uds: "estarían resistiendo",
		},
		Future: {
			yo: "estaré resistiendo",
			tú: "estarás resistiendo",
			Ud: "estará resistiendo",
			nosotros: "estaremos resistiendo",
			vosotros: "estaréis resistiendo",
			Uds: "estarán resistiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he resistido",
			tú: "has resistido",
			Ud: "ha resistido",
			nosotros: "hemos resistido",
			vosotros: "habéis resistido",
			Uds: "han resistido",
		},
		Preterite: {
			yo: "hube resistido",
			tú: "hubiste resistido",
			Ud: "hubo resistido",
			nosotros: "hubimos resistido",
			vosotros: "hubisteis resistido",
			Uds: "hubieron resistido",
		},
		Past: {
			yo: "había resistido",
			tú: "habías resistido",
			Ud: "había resistido",
			nosotros: "habíamos resistido",
			vosotros: "habíais resistido",
			Uds: "habían resistido",
		},
		Conditional: {
			yo: "habría resistido",
			tú: "habrías resistido",
			Ud: "habría resistido",
			nosotros: "habríamos resistido",
			vosotros: "habríais resistido",
			Uds: "habrían resistido",
		},
		Future: {
			yo: "habré resistido",
			tú: "habrás resistido",
			Ud: "habrá resistido",
			nosotros: "habremos resistido",
			vosotros: "habréis resistido",
			Uds: "habrán resistido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya resistido",
			tú: "hayas resistido",
			Ud: "haya resistido",
			nosotros: "hayamos resistido",
			vosotros: "hayáis resistido",
			Uds: "hayan resistido",
		},
		Past: {
			yo: "hubiera resistido",
			tú: "hubieras resistido",
			Ud: "hubiera resistido",
			nosotros: "hubiéramos resistido",
			vosotros: "hubierais resistido",
			Uds: "hubieran resistido",
		},
		Future: {
			yo: "hubiere resistido",
			tú: "hubieres resistido",
			Ud: "hubiere resistido",
			nosotros: "hubiéremos resistido",
			vosotros: "hubiereis resistido",
			Uds: "hubieren resistido",
		},
	},
}
