var responder = {
	Indicative: {
		Present: {
			yo: "respondo",
			tú: "respondes",
			Ud: "responde",
			nosotros: "respondemos",
			vosotros: "respondéis",
			Uds: "responden",
		},
		Preterite: {
			yo: "respondí,repuse",
			tú: "respondiste,repusiste",
			Ud: "respondió,repuso",
			nosotros: "respondimos,repusimos",
			vosotros: "respondisteis,repusisteis",
			Uds: "respondieron,repusieron",
		},
		Imperfect: {
			yo: "respondía",
			tú: "respondías",
			Ud: "respondía",
			nosotros: "respondíamos",
			vosotros: "respondíais",
			Uds: "respondían",
		},
		Conditional: {
			yo: "respondería",
			tú: "responderías",
			Ud: "respondería",
			nosotros: "responderíamos",
			vosotros: "responderíais",
			Uds: "responderían",
		},
		Future: {
			yo: "responderé",
			tú: "responderás",
			Ud: "responderá",
			nosotros: "responderemos",
			vosotros: "responderéis",
			Uds: "responderán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "responda",
			tú: "respondas",
			Ud: "responda",
			nosotros: "respondamos",
			vosotros: "respondáis",
			Uds: "respondan",
		},
		Imperfect: {
			yo: "respondiera",
			tú: "respondieras",
			Ud: "respondiera",
			nosotros: "respondiéramos",
			vosotros: "respondierais",
			Uds: "respondieran",
		},
		Imperfect2: {
			yo: "respondiese",
			tú: "respondieses",
			Ud: "respondiese",
			nosotros: "respondiésemos",
			vosotros: "respondieseis",
			Uds: "respondiesen",
		},
		Future: {
			yo: "respondiere",
			tú: "respondieres",
			Ud: "respondiere",
			nosotros: "respondiéremos",
			vosotros: "respondiereis",
			Uds: "respondieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "responde",
			Ud: "responda",
			nosotros: "respondamos",
			vosotros: "responded",
			Uds: "respondan",
		},
		Negative: {
			tú: "no respondas",
			Ud: "no responda",
			nosotros: "no respondamos",
			vosotros: "no respondáis",
			Uds: "no respondan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy respondiendo",
			tú: "estás respondiendo",
			Ud: "está respondiendo",
			nosotros: "estamos respondiendo",
			vosotros: "estáis respondiendo",
			Uds: "están respondiendo",
		},
		Preterite: {
			yo: "estuve respondiendo",
			tú: "estuviste respondiendo",
			Ud: "estuvo respondiendo",
			nosotros: "estuvimos respondiendo",
			vosotros: "estuvisteis respondiendo",
			Uds: "estuvieron respondiendo",
		},
		Imperfect: {
			Uds: "estaban respondiendo",
			yo: "estaba respondiendo",
			tú: "estabas respondiendo",
			Ud: "estaba respondiendo",
			nosotros: "estábamos respondiendo",
			vosotros: "estabais respondiendo",
		},
		Conditional: {
			yo: "estaría respondiendo",
			tú: "estarías respondiendo",
			Ud: "estaría respondiendo",
			nosotros: "estaríamos respondiendo",
			vosotros: "estaríais respondiendo",
			Uds: "estarían respondiendo",
		},
		Future: {
			yo: "estaré respondiendo",
			tú: "estarás respondiendo",
			Ud: "estará respondiendo",
			nosotros: "estaremos respondiendo",
			vosotros: "estaréis respondiendo",
			Uds: "estarán respondiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he respondido",
			tú: "has respondido",
			Ud: "ha respondido",
			nosotros: "hemos respondido",
			vosotros: "habéis respondido",
			Uds: "han respondido",
		},
		Preterite: {
			yo: "hube respondido",
			tú: "hubiste respondido",
			Ud: "hubo respondido",
			nosotros: "hubimos respondido",
			vosotros: "hubisteis respondido",
			Uds: "hubieron respondido",
		},
		Past: {
			yo: "había respondido",
			tú: "habías respondido",
			Ud: "había respondido",
			nosotros: "habíamos respondido",
			vosotros: "habíais respondido",
			Uds: "habían respondido",
		},
		Conditional: {
			yo: "habría respondido",
			tú: "habrías respondido",
			Ud: "habría respondido",
			nosotros: "habríamos respondido",
			vosotros: "habríais respondido",
			Uds: "habrían respondido",
		},
		Future: {
			yo: "habré respondido",
			tú: "habrás respondido",
			Ud: "habrá respondido",
			nosotros: "habremos respondido",
			vosotros: "habréis respondido",
			Uds: "habrán respondido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya respondido",
			tú: "hayas respondido",
			Ud: "haya respondido",
			nosotros: "hayamos respondido",
			vosotros: "hayáis respondido",
			Uds: "hayan respondido",
		},
		Past: {
			yo: "hubiera respondido",
			tú: "hubieras respondido",
			Ud: "hubiera respondido",
			nosotros: "hubiéramos respondido",
			vosotros: "hubierais respondido",
			Uds: "hubieran respondido",
		},
		Future: {
			yo: "hubiere respondido",
			tú: "hubieres respondido",
			Ud: "hubiere respondido",
			nosotros: "hubiéremos respondido",
			vosotros: "hubiereis respondido",
			Uds: "hubieren respondido",
		},
	},
}
