var resquebrajar = {
	Indicative: {
		Present: {
			yo: "resquebrajo",
			tú: "resquebrajas",
			Ud: "resquebraja",
			nosotros: "resquebrajamos",
			vosotros: "resquebrajáis",
			Uds: "resquebrajan",
		},
		Preterite: {
			yo: "resquebrajé",
			tú: "resquebrajaste",
			Ud: "resquebrajó",
			nosotros: "resquebrajamos",
			vosotros: "resquebrajasteis",
			Uds: "resquebrajaron",
		},
		Imperfect: {
			yo: "resquebrajaba",
			tú: "resquebrajabas",
			Ud: "resquebrajaba",
			nosotros: "resquebrajábamos",
			vosotros: "resquebrajabais",
			Uds: "resquebrajaban",
		},
		Conditional: {
			yo: "resquebrajaría",
			tú: "resquebrajarías",
			Ud: "resquebrajaría",
			nosotros: "resquebrajaríamos",
			vosotros: "resquebrajaríais",
			Uds: "resquebrajarían",
		},
		Future: {
			yo: "resquebrajaré",
			tú: "resquebrajarás",
			Ud: "resquebrajará",
			nosotros: "resquebrajaremos",
			vosotros: "resquebrajaréis",
			Uds: "resquebrajarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "resquebraje",
			tú: "resquebrajes",
			Ud: "resquebraje",
			nosotros: "resquebrajemos",
			vosotros: "resquebrajéis",
			Uds: "resquebrajen",
		},
		Imperfect: {
			yo: "resquebrajara",
			tú: "resquebrajaras",
			Ud: "resquebrajara",
			nosotros: "resquebrajáramos",
			vosotros: "resquebrajarais",
			Uds: "resquebrajaran",
		},
		Imperfect2: {
			yo: "resquebrajase",
			tú: "resquebrajases",
			Ud: "resquebrajase",
			nosotros: "resquebrajásemos",
			vosotros: "resquebrajaseis",
			Uds: "resquebrajasen",
		},
		Future: {
			yo: "resquebrajare",
			tú: "resquebrajares",
			Ud: "resquebrajare",
			nosotros: "resquebrajáremos",
			vosotros: "resquebrajareis",
			Uds: "resquebrajaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "resquebraja",
			Ud: "resquebraje",
			nosotros: "resquebrajemos",
			vosotros: "resquebrajad",
			Uds: "resquebrajen",
		},
		Negative: {
			tú: "no resquebrajes",
			Ud: "no resquebraje",
			nosotros: "no resquebrajemos",
			vosotros: "no resquebrajéis",
			Uds: "no resquebrajen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy resquebrajando",
			tú: "estás resquebrajando",
			Ud: "está resquebrajando",
			nosotros: "estamos resquebrajando",
			vosotros: "estáis resquebrajando",
			Uds: "están resquebrajando",
		},
		Preterite: {
			yo: "estuve resquebrajando",
			tú: "estuviste resquebrajando",
			Ud: "estuvo resquebrajando",
			nosotros: "estuvimos resquebrajando",
			vosotros: "estuvisteis resquebrajando",
			Uds: "estuvieron resquebrajando",
		},
		Imperfect: {
			Uds: "estaban resquebrajando",
			yo: "estaba resquebrajando",
			tú: "estabas resquebrajando",
			Ud: "estaba resquebrajando",
			nosotros: "estábamos resquebrajando",
			vosotros: "estabais resquebrajando",
		},
		Conditional: {
			yo: "estaría resquebrajando",
			tú: "estarías resquebrajando",
			Ud: "estaría resquebrajando",
			nosotros: "estaríamos resquebrajando",
			vosotros: "estaríais resquebrajando",
			Uds: "estarían resquebrajando",
		},
		Future: {
			yo: "estaré resquebrajando",
			tú: "estarás resquebrajando",
			Ud: "estará resquebrajando",
			nosotros: "estaremos resquebrajando",
			vosotros: "estaréis resquebrajando",
			Uds: "estarán resquebrajando",
		},
	},
	Perfect: {
		Present: {
			yo: "he resquebrajado",
			tú: "has resquebrajado",
			Ud: "ha resquebrajado",
			nosotros: "hemos resquebrajado",
			vosotros: "habéis resquebrajado",
			Uds: "han resquebrajado",
		},
		Preterite: {
			yo: "hube resquebrajado",
			tú: "hubiste resquebrajado",
			Ud: "hubo resquebrajado",
			nosotros: "hubimos resquebrajado",
			vosotros: "hubisteis resquebrajado",
			Uds: "hubieron resquebrajado",
		},
		Past: {
			yo: "había resquebrajado",
			tú: "habías resquebrajado",
			Ud: "había resquebrajado",
			nosotros: "habíamos resquebrajado",
			vosotros: "habíais resquebrajado",
			Uds: "habían resquebrajado",
		},
		Conditional: {
			yo: "habría resquebrajado",
			tú: "habrías resquebrajado",
			Ud: "habría resquebrajado",
			nosotros: "habríamos resquebrajado",
			vosotros: "habríais resquebrajado",
			Uds: "habrían resquebrajado",
		},
		Future: {
			yo: "habré resquebrajado",
			tú: "habrás resquebrajado",
			Ud: "habrá resquebrajado",
			nosotros: "habremos resquebrajado",
			vosotros: "habréis resquebrajado",
			Uds: "habrán resquebrajado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya resquebrajado",
			tú: "hayas resquebrajado",
			Ud: "haya resquebrajado",
			nosotros: "hayamos resquebrajado",
			vosotros: "hayáis resquebrajado",
			Uds: "hayan resquebrajado",
		},
		Past: {
			yo: "hubiera resquebrajado",
			tú: "hubieras resquebrajado",
			Ud: "hubiera resquebrajado",
			nosotros: "hubiéramos resquebrajado",
			vosotros: "hubierais resquebrajado",
			Uds: "hubieran resquebrajado",
		},
		Future: {
			yo: "hubiere resquebrajado",
			tú: "hubieres resquebrajado",
			Ud: "hubiere resquebrajado",
			nosotros: "hubiéremos resquebrajado",
			vosotros: "hubiereis resquebrajado",
			Uds: "hubieren resquebrajado",
		},
	},
}
