var restaurar = {
	Indicative: {
		Present: {
			yo: "resto",
			tú: "restas",
			Ud: "resta",
			nosotros: "restamos",
			vosotros: "restáis",
			Uds: "restan",
		},
		Preterite: {
			yo: "resté",
			tú: "restaste",
			Ud: "restó",
			nosotros: "restamos",
			vosotros: "restasteis",
			Uds: "restaron",
		},
		Imperfect: {
			yo: "restaba",
			tú: "restabas",
			Ud: "restaba",
			nosotros: "restábamos",
			vosotros: "restabais",
			Uds: "restaban",
		},
		Conditional: {
			yo: "restaría",
			tú: "restarías",
			Ud: "restaría",
			nosotros: "restaríamos",
			vosotros: "restaríais",
			Uds: "restarían",
		},
		Future: {
			yo: "restaré",
			tú: "restarás",
			Ud: "restará",
			nosotros: "restaremos",
			vosotros: "restaréis",
			Uds: "restarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "reste",
			tú: "restes",
			Ud: "reste",
			nosotros: "restemos",
			vosotros: "restéis",
			Uds: "resten",
		},
		Imperfect: {
			yo: "restara",
			tú: "restaras",
			Ud: "restara",
			nosotros: "restáramos",
			vosotros: "restarais",
			Uds: "restaran",
		},
		Imperfect2: {
			yo: "restase",
			tú: "restases",
			Ud: "restase",
			nosotros: "restásemos",
			vosotros: "restaseis",
			Uds: "restasen",
		},
		Future: {
			yo: "restare",
			tú: "restares",
			Ud: "restare",
			nosotros: "restáremos",
			vosotros: "restareis",
			Uds: "restaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "resta",
			Ud: "reste",
			nosotros: "restemos",
			vosotros: "restad",
			Uds: "resten",
		},
		Negative: {
			tú: "no restes",
			Ud: "no reste",
			nosotros: "no restemos",
			vosotros: "no restéis",
			Uds: "no resten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy restando",
			tú: "estás restando",
			Ud: "está restando",
			nosotros: "estamos restando",
			vosotros: "estáis restando",
			Uds: "están restando",
		},
		Preterite: {
			yo: "estuve restando",
			tú: "estuviste restando",
			Ud: "estuvo restando",
			nosotros: "estuvimos restando",
			vosotros: "estuvisteis restando",
			Uds: "estuvieron restando",
		},
		Imperfect: {
			Uds: "estaban restando",
			yo: "estaba restando",
			tú: "estabas restando",
			Ud: "estaba restando",
			nosotros: "estábamos restando",
			vosotros: "estabais restando",
		},
		Conditional: {
			yo: "estaría restando",
			tú: "estarías restando",
			Ud: "estaría restando",
			nosotros: "estaríamos restando",
			vosotros: "estaríais restando",
			Uds: "estarían restando",
		},
		Future: {
			yo: "estaré restando",
			tú: "estarás restando",
			Ud: "estará restando",
			nosotros: "estaremos restando",
			vosotros: "estaréis restando",
			Uds: "estarán restando",
		},
	},
	Perfect: {
		Present: {
			yo: "he restado",
			tú: "has restado",
			Ud: "ha restado",
			nosotros: "hemos restado",
			vosotros: "habéis restado",
			Uds: "han restado",
		},
		Preterite: {
			yo: "hube restado",
			tú: "hubiste restado",
			Ud: "hubo restado",
			nosotros: "hubimos restado",
			vosotros: "hubisteis restado",
			Uds: "hubieron restado",
		},
		Past: {
			yo: "había restado",
			tú: "habías restado",
			Ud: "había restado",
			nosotros: "habíamos restado",
			vosotros: "habíais restado",
			Uds: "habían restado",
		},
		Conditional: {
			yo: "habría restado",
			tú: "habrías restado",
			Ud: "habría restado",
			nosotros: "habríamos restado",
			vosotros: "habríais restado",
			Uds: "habrían restado",
		},
		Future: {
			yo: "habré restado",
			tú: "habrás restado",
			Ud: "habrá restado",
			nosotros: "habremos restado",
			vosotros: "habréis restado",
			Uds: "habrán restado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya restado",
			tú: "hayas restado",
			Ud: "haya restado",
			nosotros: "hayamos restado",
			vosotros: "hayáis restado",
			Uds: "hayan restado",
		},
		Past: {
			yo: "hubiera restado",
			tú: "hubieras restado",
			Ud: "hubiera restado",
			nosotros: "hubiéramos restado",
			vosotros: "hubierais restado",
			Uds: "hubieran restado",
		},
		Future: {
			yo: "hubiere restado",
			tú: "hubieres restado",
			Ud: "hubiere restado",
			nosotros: "hubiéremos restado",
			vosotros: "hubiereis restado",
			Uds: "hubieren restado",
		},
	},
}
