var resumir = {
	Indicative: {
		Present: {
			yo: "resumo",
			tú: "resumes",
			Ud: "resume",
			nosotros: "resumimos",
			vosotros: "resumís",
			Uds: "resumen",
		},
		Preterite: {
			yo: "resumí",
			tú: "resumiste",
			Ud: "resumió",
			nosotros: "resumimos",
			vosotros: "resumisteis",
			Uds: "resumieron",
		},
		Imperfect: {
			yo: "resumía",
			tú: "resumías",
			Ud: "resumía",
			nosotros: "resumíamos",
			vosotros: "resumíais",
			Uds: "resumían",
		},
		Conditional: {
			yo: "resumiría",
			tú: "resumirías",
			Ud: "resumiría",
			nosotros: "resumiríamos",
			vosotros: "resumiríais",
			Uds: "resumirían",
		},
		Future: {
			yo: "resumiré",
			tú: "resumirás",
			Ud: "resumirá",
			nosotros: "resumiremos",
			vosotros: "resumiréis",
			Uds: "resumirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "resuma",
			tú: "resumas",
			Ud: "resuma",
			nosotros: "resumamos",
			vosotros: "resumáis",
			Uds: "resuman",
		},
		Imperfect: {
			yo: "resumiera",
			tú: "resumieras",
			Ud: "resumiera",
			nosotros: "resumiéramos",
			vosotros: "resumierais",
			Uds: "resumieran",
		},
		Imperfect2: {
			yo: "resumiese",
			tú: "resumieses",
			Ud: "resumiese",
			nosotros: "resumiésemos",
			vosotros: "resumieseis",
			Uds: "resumiesen",
		},
		Future: {
			yo: "resumiere",
			tú: "resumieres",
			Ud: "resumiere",
			nosotros: "resumiéremos",
			vosotros: "resumiereis",
			Uds: "resumieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "resume",
			Ud: "resuma",
			nosotros: "resumamos",
			vosotros: "resumid",
			Uds: "resuman",
		},
		Negative: {
			tú: "no resumas",
			Ud: "no resuma",
			nosotros: "no resumamos",
			vosotros: "no resumáis",
			Uds: "no resuman",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy resumiendo",
			tú: "estás resumiendo",
			Ud: "está resumiendo",
			nosotros: "estamos resumiendo",
			vosotros: "estáis resumiendo",
			Uds: "están resumiendo",
		},
		Preterite: {
			yo: "estuve resumiendo",
			tú: "estuviste resumiendo",
			Ud: "estuvo resumiendo",
			nosotros: "estuvimos resumiendo",
			vosotros: "estuvisteis resumiendo",
			Uds: "estuvieron resumiendo",
		},
		Imperfect: {
			Uds: "estaban resumiendo",
			yo: "estaba resumiendo",
			tú: "estabas resumiendo",
			Ud: "estaba resumiendo",
			nosotros: "estábamos resumiendo",
			vosotros: "estabais resumiendo",
		},
		Conditional: {
			yo: "estaría resumiendo",
			tú: "estarías resumiendo",
			Ud: "estaría resumiendo",
			nosotros: "estaríamos resumiendo",
			vosotros: "estaríais resumiendo",
			Uds: "estarían resumiendo",
		},
		Future: {
			yo: "estaré resumiendo",
			tú: "estarás resumiendo",
			Ud: "estará resumiendo",
			nosotros: "estaremos resumiendo",
			vosotros: "estaréis resumiendo",
			Uds: "estarán resumiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he resumido",
			tú: "has resumido",
			Ud: "ha resumido",
			nosotros: "hemos resumido",
			vosotros: "habéis resumido",
			Uds: "han resumido",
		},
		Preterite: {
			yo: "hube resumido",
			tú: "hubiste resumido",
			Ud: "hubo resumido",
			nosotros: "hubimos resumido",
			vosotros: "hubisteis resumido",
			Uds: "hubieron resumido",
		},
		Past: {
			yo: "había resumido",
			tú: "habías resumido",
			Ud: "había resumido",
			nosotros: "habíamos resumido",
			vosotros: "habíais resumido",
			Uds: "habían resumido",
		},
		Conditional: {
			yo: "habría resumido",
			tú: "habrías resumido",
			Ud: "habría resumido",
			nosotros: "habríamos resumido",
			vosotros: "habríais resumido",
			Uds: "habrían resumido",
		},
		Future: {
			yo: "habré resumido",
			tú: "habrás resumido",
			Ud: "habrá resumido",
			nosotros: "habremos resumido",
			vosotros: "habréis resumido",
			Uds: "habrán resumido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya resumido",
			tú: "hayas resumido",
			Ud: "haya resumido",
			nosotros: "hayamos resumido",
			vosotros: "hayáis resumido",
			Uds: "hayan resumido",
		},
		Past: {
			yo: "hubiera resumido",
			tú: "hubieras resumido",
			Ud: "hubiera resumido",
			nosotros: "hubiéramos resumido",
			vosotros: "hubierais resumido",
			Uds: "hubieran resumido",
		},
		Future: {
			yo: "hubiere resumido",
			tú: "hubieres resumido",
			Ud: "hubiere resumido",
			nosotros: "hubiéremos resumido",
			vosotros: "hubiereis resumido",
			Uds: "hubieren resumido",
		},
	},
}
