var retroceder = {
	Indicative: {
		Present: {
			yo: "retrocedo",
			tú: "retrocedes",
			Ud: "retrocede",
			nosotros: "retrocedemos",
			vosotros: "retrocedéis",
			Uds: "retroceden",
		},
		Preterite: {
			yo: "retrocedí",
			tú: "retrocediste",
			Ud: "retrocedió",
			nosotros: "retrocedimos",
			vosotros: "retrocedisteis",
			Uds: "retrocedieron",
		},
		Imperfect: {
			yo: "retrocedía",
			tú: "retrocedías",
			Ud: "retrocedía",
			nosotros: "retrocedíamos",
			vosotros: "retrocedíais",
			Uds: "retrocedían",
		},
		Conditional: {
			yo: "retrocedería",
			tú: "retrocederías",
			Ud: "retrocedería",
			nosotros: "retrocederíamos",
			vosotros: "retrocederíais",
			Uds: "retrocederían",
		},
		Future: {
			yo: "retrocederé",
			tú: "retrocederás",
			Ud: "retrocederá",
			nosotros: "retrocederemos",
			vosotros: "retrocederéis",
			Uds: "retrocederán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "retroceda",
			tú: "retrocedas",
			Ud: "retroceda",
			nosotros: "retrocedamos",
			vosotros: "retrocedáis",
			Uds: "retrocedan",
		},
		Imperfect: {
			yo: "retrocediera",
			tú: "retrocedieras",
			Ud: "retrocediera",
			nosotros: "retrocediéramos",
			vosotros: "retrocedierais",
			Uds: "retrocedieran",
		},
		Imperfect2: {
			yo: "retrocediese",
			tú: "retrocedieses",
			Ud: "retrocediese",
			nosotros: "retrocediésemos",
			vosotros: "retrocedieseis",
			Uds: "retrocediesen",
		},
		Future: {
			yo: "retrocediere",
			tú: "retrocedieres",
			Ud: "retrocediere",
			nosotros: "retrocediéremos",
			vosotros: "retrocediereis",
			Uds: "retrocedieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "retrocede",
			Ud: "retroceda",
			nosotros: "retrocedamos",
			vosotros: "retroceded",
			Uds: "retrocedan",
		},
		Negative: {
			tú: "no retrocedas",
			Ud: "no retroceda",
			nosotros: "no retrocedamos",
			vosotros: "no retrocedáis",
			Uds: "no retrocedan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy retrocediendo",
			tú: "estás retrocediendo",
			Ud: "está retrocediendo",
			nosotros: "estamos retrocediendo",
			vosotros: "estáis retrocediendo",
			Uds: "están retrocediendo",
		},
		Preterite: {
			yo: "estuve retrocediendo",
			tú: "estuviste retrocediendo",
			Ud: "estuvo retrocediendo",
			nosotros: "estuvimos retrocediendo",
			vosotros: "estuvisteis retrocediendo",
			Uds: "estuvieron retrocediendo",
		},
		Imperfect: {
			Uds: "estaban retrocediendo",
			yo: "estaba retrocediendo",
			tú: "estabas retrocediendo",
			Ud: "estaba retrocediendo",
			nosotros: "estábamos retrocediendo",
			vosotros: "estabais retrocediendo",
		},
		Conditional: {
			yo: "estaría retrocediendo",
			tú: "estarías retrocediendo",
			Ud: "estaría retrocediendo",
			nosotros: "estaríamos retrocediendo",
			vosotros: "estaríais retrocediendo",
			Uds: "estarían retrocediendo",
		},
		Future: {
			yo: "estaré retrocediendo",
			tú: "estarás retrocediendo",
			Ud: "estará retrocediendo",
			nosotros: "estaremos retrocediendo",
			vosotros: "estaréis retrocediendo",
			Uds: "estarán retrocediendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he retrocedido",
			tú: "has retrocedido",
			Ud: "ha retrocedido",
			nosotros: "hemos retrocedido",
			vosotros: "habéis retrocedido",
			Uds: "han retrocedido",
		},
		Preterite: {
			yo: "hube retrocedido",
			tú: "hubiste retrocedido",
			Ud: "hubo retrocedido",
			nosotros: "hubimos retrocedido",
			vosotros: "hubisteis retrocedido",
			Uds: "hubieron retrocedido",
		},
		Past: {
			yo: "había retrocedido",
			tú: "habías retrocedido",
			Ud: "había retrocedido",
			nosotros: "habíamos retrocedido",
			vosotros: "habíais retrocedido",
			Uds: "habían retrocedido",
		},
		Conditional: {
			yo: "habría retrocedido",
			tú: "habrías retrocedido",
			Ud: "habría retrocedido",
			nosotros: "habríamos retrocedido",
			vosotros: "habríais retrocedido",
			Uds: "habrían retrocedido",
		},
		Future: {
			yo: "habré retrocedido",
			tú: "habrás retrocedido",
			Ud: "habrá retrocedido",
			nosotros: "habremos retrocedido",
			vosotros: "habréis retrocedido",
			Uds: "habrán retrocedido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya retrocedido",
			tú: "hayas retrocedido",
			Ud: "haya retrocedido",
			nosotros: "hayamos retrocedido",
			vosotros: "hayáis retrocedido",
			Uds: "hayan retrocedido",
		},
		Past: {
			yo: "hubiera retrocedido",
			tú: "hubieras retrocedido",
			Ud: "hubiera retrocedido",
			nosotros: "hubiéramos retrocedido",
			vosotros: "hubierais retrocedido",
			Uds: "hubieran retrocedido",
		},
		Future: {
			yo: "hubiere retrocedido",
			tú: "hubieres retrocedido",
			Ud: "hubiere retrocedido",
			nosotros: "hubiéremos retrocedido",
			vosotros: "hubiereis retrocedido",
			Uds: "hubieren retrocedido",
		},
	},
}
