var reunir = {
	Indicative: {
		Present: {
			yo: "reúno",
			tú: "reúnes",
			Ud: "reúne",
			nosotros: "reunimos",
			vosotros: "reunís",
			Uds: "reúnen",
		},
		Preterite: {
			yo: "reuní",
			tú: "reuniste",
			Ud: "reunió",
			nosotros: "reunimos",
			vosotros: "reunisteis",
			Uds: "reunieron",
		},
		Imperfect: {
			yo: "reunía",
			tú: "reunías",
			Ud: "reunía",
			nosotros: "reuníamos",
			vosotros: "reuníais",
			Uds: "reunían",
		},
		Conditional: {
			yo: "reuniría",
			tú: "reunirías",
			Ud: "reuniría",
			nosotros: "reuniríamos",
			vosotros: "reuniríais",
			Uds: "reunirían",
		},
		Future: {
			yo: "reuniré",
			tú: "reunirás",
			Ud: "reunirá",
			nosotros: "reuniremos",
			vosotros: "reuniréis",
			Uds: "reunirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "reúna",
			tú: "reúnas",
			Ud: "reúna",
			nosotros: "reunamos",
			vosotros: "reunáis",
			Uds: "reúnan",
		},
		Imperfect: {
			yo: "reuniera",
			tú: "reunieras",
			Ud: "reuniera",
			nosotros: "reuniéramos",
			vosotros: "reunierais",
			Uds: "reunieran",
		},
		Imperfect2: {
			yo: "reuniese",
			tú: "reunieses",
			Ud: "reuniese",
			nosotros: "reuniésemos",
			vosotros: "reunieseis",
			Uds: "reuniesen",
		},
		Future: {
			yo: "reuniere",
			tú: "reunieres",
			Ud: "reuniere",
			nosotros: "reuniéremos",
			vosotros: "reuniereis",
			Uds: "reunieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "reúne",
			Ud: "reúna",
			nosotros: "reunamos",
			vosotros: "reunid",
			Uds: "reúnan",
		},
		Negative: {
			tú: "no reúnas",
			Ud: "no reúna",
			nosotros: "no reunamos",
			vosotros: "no reunáis",
			Uds: "no reúnan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy reuniendo",
			tú: "estás reuniendo",
			Ud: "está reuniendo",
			nosotros: "estamos reuniendo",
			vosotros: "estáis reuniendo",
			Uds: "están reuniendo",
		},
		Preterite: {
			yo: "estuve reuniendo",
			tú: "estuviste reuniendo",
			Ud: "estuvo reuniendo",
			nosotros: "estuvimos reuniendo",
			vosotros: "estuvisteis reuniendo",
			Uds: "estuvieron reuniendo",
		},
		Imperfect: {
			Uds: "estaban reuniendo",
			yo: "estaba reuniendo",
			tú: "estabas reuniendo",
			Ud: "estaba reuniendo",
			nosotros: "estábamos reuniendo",
			vosotros: "estabais reuniendo",
		},
		Conditional: {
			yo: "estaría reuniendo",
			tú: "estarías reuniendo",
			Ud: "estaría reuniendo",
			nosotros: "estaríamos reuniendo",
			vosotros: "estaríais reuniendo",
			Uds: "estarían reuniendo",
		},
		Future: {
			yo: "estaré reuniendo",
			tú: "estarás reuniendo",
			Ud: "estará reuniendo",
			nosotros: "estaremos reuniendo",
			vosotros: "estaréis reuniendo",
			Uds: "estarán reuniendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he reunido",
			tú: "has reunido",
			Ud: "ha reunido",
			nosotros: "hemos reunido",
			vosotros: "habéis reunido",
			Uds: "han reunido",
		},
		Preterite: {
			yo: "hube reunido",
			tú: "hubiste reunido",
			Ud: "hubo reunido",
			nosotros: "hubimos reunido",
			vosotros: "hubisteis reunido",
			Uds: "hubieron reunido",
		},
		Past: {
			yo: "había reunido",
			tú: "habías reunido",
			Ud: "había reunido",
			nosotros: "habíamos reunido",
			vosotros: "habíais reunido",
			Uds: "habían reunido",
		},
		Conditional: {
			yo: "habría reunido",
			tú: "habrías reunido",
			Ud: "habría reunido",
			nosotros: "habríamos reunido",
			vosotros: "habríais reunido",
			Uds: "habrían reunido",
		},
		Future: {
			yo: "habré reunido",
			tú: "habrás reunido",
			Ud: "habrá reunido",
			nosotros: "habremos reunido",
			vosotros: "habréis reunido",
			Uds: "habrán reunido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya reunido",
			tú: "hayas reunido",
			Ud: "haya reunido",
			nosotros: "hayamos reunido",
			vosotros: "hayáis reunido",
			Uds: "hayan reunido",
		},
		Past: {
			yo: "hubiera reunido",
			tú: "hubieras reunido",
			Ud: "hubiera reunido",
			nosotros: "hubiéramos reunido",
			vosotros: "hubierais reunido",
			Uds: "hubieran reunido",
		},
		Future: {
			yo: "hubiere reunido",
			tú: "hubieres reunido",
			Ud: "hubiere reunido",
			nosotros: "hubiéremos reunido",
			vosotros: "hubiereis reunido",
			Uds: "hubieren reunido",
		},
	},
}
