var reverberar = {
	Indicative: {
		Present: {
			yo: "reverbero",
			tú: "reverberas",
			Ud: "reverbera",
			nosotros: "reverberamos",
			vosotros: "reverberáis",
			Uds: "reverberan",
		},
		Preterite: {
			yo: "reverberé",
			tú: "reverberaste",
			Ud: "reverberó",
			nosotros: "reverberamos",
			vosotros: "reverberasteis",
			Uds: "reverberaron",
		},
		Imperfect: {
			yo: "reverberaba",
			tú: "reverberabas",
			Ud: "reverberaba",
			nosotros: "reverberábamos",
			vosotros: "reverberabais",
			Uds: "reverberaban",
		},
		Conditional: {
			yo: "reverberaría",
			tú: "reverberarías",
			Ud: "reverberaría",
			nosotros: "reverberaríamos",
			vosotros: "reverberaríais",
			Uds: "reverberarían",
		},
		Future: {
			yo: "reverberaré",
			tú: "reverberarás",
			Ud: "reverberará",
			nosotros: "reverberaremos",
			vosotros: "reverberaréis",
			Uds: "reverberarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "reverbere",
			tú: "reverberes",
			Ud: "reverbere",
			nosotros: "reverberemos",
			vosotros: "reverberéis",
			Uds: "reverberen",
		},
		Imperfect: {
			yo: "reverberara",
			tú: "reverberaras",
			Ud: "reverberara",
			nosotros: "reverberáramos",
			vosotros: "reverberarais",
			Uds: "reverberaran",
		},
		Imperfect2: {
			yo: "reverberase",
			tú: "reverberases",
			Ud: "reverberase",
			nosotros: "reverberásemos",
			vosotros: "reverberaseis",
			Uds: "reverberasen",
		},
		Future: {
			yo: "reverberare",
			tú: "reverberares",
			Ud: "reverberare",
			nosotros: "reverberáremos",
			vosotros: "reverberareis",
			Uds: "reverberaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "reverbera",
			Ud: "reverbere",
			nosotros: "reverberemos",
			vosotros: "reverberad",
			Uds: "reverberen",
		},
		Negative: {
			tú: "no reverberes",
			Ud: "no reverbere",
			nosotros: "no reverberemos",
			vosotros: "no reverberéis",
			Uds: "no reverberen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy reverberando",
			tú: "estás reverberando",
			Ud: "está reverberando",
			nosotros: "estamos reverberando",
			vosotros: "estáis reverberando",
			Uds: "están reverberando",
		},
		Preterite: {
			yo: "estuve reverberando",
			tú: "estuviste reverberando",
			Ud: "estuvo reverberando",
			nosotros: "estuvimos reverberando",
			vosotros: "estuvisteis reverberando",
			Uds: "estuvieron reverberando",
		},
		Imperfect: {
			Uds: "estaban reverberando",
			yo: "estaba reverberando",
			tú: "estabas reverberando",
			Ud: "estaba reverberando",
			nosotros: "estábamos reverberando",
			vosotros: "estabais reverberando",
		},
		Conditional: {
			yo: "estaría reverberando",
			tú: "estarías reverberando",
			Ud: "estaría reverberando",
			nosotros: "estaríamos reverberando",
			vosotros: "estaríais reverberando",
			Uds: "estarían reverberando",
		},
		Future: {
			yo: "estaré reverberando",
			tú: "estarás reverberando",
			Ud: "estará reverberando",
			nosotros: "estaremos reverberando",
			vosotros: "estaréis reverberando",
			Uds: "estarán reverberando",
		},
	},
	Perfect: {
		Present: {
			yo: "he reverberado",
			tú: "has reverberado",
			Ud: "ha reverberado",
			nosotros: "hemos reverberado",
			vosotros: "habéis reverberado",
			Uds: "han reverberado",
		},
		Preterite: {
			yo: "hube reverberado",
			tú: "hubiste reverberado",
			Ud: "hubo reverberado",
			nosotros: "hubimos reverberado",
			vosotros: "hubisteis reverberado",
			Uds: "hubieron reverberado",
		},
		Past: {
			yo: "había reverberado",
			tú: "habías reverberado",
			Ud: "había reverberado",
			nosotros: "habíamos reverberado",
			vosotros: "habíais reverberado",
			Uds: "habían reverberado",
		},
		Conditional: {
			yo: "habría reverberado",
			tú: "habrías reverberado",
			Ud: "habría reverberado",
			nosotros: "habríamos reverberado",
			vosotros: "habríais reverberado",
			Uds: "habrían reverberado",
		},
		Future: {
			yo: "habré reverberado",
			tú: "habrás reverberado",
			Ud: "habrá reverberado",
			nosotros: "habremos reverberado",
			vosotros: "habréis reverberado",
			Uds: "habrán reverberado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya reverberado",
			tú: "hayas reverberado",
			Ud: "haya reverberado",
			nosotros: "hayamos reverberado",
			vosotros: "hayáis reverberado",
			Uds: "hayan reverberado",
		},
		Past: {
			yo: "hubiera reverberado",
			tú: "hubieras reverberado",
			Ud: "hubiera reverberado",
			nosotros: "hubiéramos reverberado",
			vosotros: "hubierais reverberado",
			Uds: "hubieran reverberado",
		},
		Future: {
			yo: "hubiere reverberado",
			tú: "hubieres reverberado",
			Ud: "hubiere reverberado",
			nosotros: "hubiéremos reverberado",
			vosotros: "hubiereis reverberado",
			Uds: "hubieren reverberado",
		},
	},
}
