var revolucionar = {
	Indicative: {
		Present: {
			yo: "revoluciono",
			tú: "revolucionas",
			Ud: "revoluciona",
			nosotros: "revolucionamos",
			vosotros: "revolucionáis",
			Uds: "revolucionan",
		},
		Preterite: {
			yo: "revolucioné",
			tú: "revolucionaste",
			Ud: "revolucionó",
			nosotros: "revolucionamos",
			vosotros: "revolucionasteis",
			Uds: "revolucionaron",
		},
		Imperfect: {
			yo: "revolucionaba",
			tú: "revolucionabas",
			Ud: "revolucionaba",
			nosotros: "revolucionábamos",
			vosotros: "revolucionabais",
			Uds: "revolucionaban",
		},
		Conditional: {
			yo: "revolucionaría",
			tú: "revolucionarías",
			Ud: "revolucionaría",
			nosotros: "revolucionaríamos",
			vosotros: "revolucionaríais",
			Uds: "revolucionarían",
		},
		Future: {
			yo: "revolucionaré",
			tú: "revolucionarás",
			Ud: "revolucionará",
			nosotros: "revolucionaremos",
			vosotros: "revolucionaréis",
			Uds: "revolucionarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "revolucione",
			tú: "revoluciones",
			Ud: "revolucione",
			nosotros: "revolucionemos",
			vosotros: "revolucionéis",
			Uds: "revolucionen",
		},
		Imperfect: {
			yo: "revolucionara",
			tú: "revolucionaras",
			Ud: "revolucionara",
			nosotros: "revolucionáramos",
			vosotros: "revolucionarais",
			Uds: "revolucionaran",
		},
		Imperfect2: {
			yo: "revolucionase",
			tú: "revolucionases",
			Ud: "revolucionase",
			nosotros: "revolucionásemos",
			vosotros: "revolucionaseis",
			Uds: "revolucionasen",
		},
		Future: {
			yo: "revolucionare",
			tú: "revolucionares",
			Ud: "revolucionare",
			nosotros: "revolucionáremos",
			vosotros: "revolucionareis",
			Uds: "revolucionaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "revoluciona",
			Ud: "revolucione",
			nosotros: "revolucionemos",
			vosotros: "revolucionad",
			Uds: "revolucionen",
		},
		Negative: {
			tú: "no revoluciones",
			Ud: "no revolucione",
			nosotros: "no revolucionemos",
			vosotros: "no revolucionéis",
			Uds: "no revolucionen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy revolucionando",
			tú: "estás revolucionando",
			Ud: "está revolucionando",
			nosotros: "estamos revolucionando",
			vosotros: "estáis revolucionando",
			Uds: "están revolucionando",
		},
		Preterite: {
			yo: "estuve revolucionando",
			tú: "estuviste revolucionando",
			Ud: "estuvo revolucionando",
			nosotros: "estuvimos revolucionando",
			vosotros: "estuvisteis revolucionando",
			Uds: "estuvieron revolucionando",
		},
		Imperfect: {
			Uds: "estaban revolucionando",
			yo: "estaba revolucionando",
			tú: "estabas revolucionando",
			Ud: "estaba revolucionando",
			nosotros: "estábamos revolucionando",
			vosotros: "estabais revolucionando",
		},
		Conditional: {
			yo: "estaría revolucionando",
			tú: "estarías revolucionando",
			Ud: "estaría revolucionando",
			nosotros: "estaríamos revolucionando",
			vosotros: "estaríais revolucionando",
			Uds: "estarían revolucionando",
		},
		Future: {
			yo: "estaré revolucionando",
			tú: "estarás revolucionando",
			Ud: "estará revolucionando",
			nosotros: "estaremos revolucionando",
			vosotros: "estaréis revolucionando",
			Uds: "estarán revolucionando",
		},
	},
	Perfect: {
		Present: {
			yo: "he revolucionado",
			tú: "has revolucionado",
			Ud: "ha revolucionado",
			nosotros: "hemos revolucionado",
			vosotros: "habéis revolucionado",
			Uds: "han revolucionado",
		},
		Preterite: {
			yo: "hube revolucionado",
			tú: "hubiste revolucionado",
			Ud: "hubo revolucionado",
			nosotros: "hubimos revolucionado",
			vosotros: "hubisteis revolucionado",
			Uds: "hubieron revolucionado",
		},
		Past: {
			yo: "había revolucionado",
			tú: "habías revolucionado",
			Ud: "había revolucionado",
			nosotros: "habíamos revolucionado",
			vosotros: "habíais revolucionado",
			Uds: "habían revolucionado",
		},
		Conditional: {
			yo: "habría revolucionado",
			tú: "habrías revolucionado",
			Ud: "habría revolucionado",
			nosotros: "habríamos revolucionado",
			vosotros: "habríais revolucionado",
			Uds: "habrían revolucionado",
		},
		Future: {
			yo: "habré revolucionado",
			tú: "habrás revolucionado",
			Ud: "habrá revolucionado",
			nosotros: "habremos revolucionado",
			vosotros: "habréis revolucionado",
			Uds: "habrán revolucionado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya revolucionado",
			tú: "hayas revolucionado",
			Ud: "haya revolucionado",
			nosotros: "hayamos revolucionado",
			vosotros: "hayáis revolucionado",
			Uds: "hayan revolucionado",
		},
		Past: {
			yo: "hubiera revolucionado",
			tú: "hubieras revolucionado",
			Ud: "hubiera revolucionado",
			nosotros: "hubiéramos revolucionado",
			vosotros: "hubierais revolucionado",
			Uds: "hubieran revolucionado",
		},
		Future: {
			yo: "hubiere revolucionado",
			tú: "hubieres revolucionado",
			Ud: "hubiere revolucionado",
			nosotros: "hubiéremos revolucionado",
			vosotros: "hubiereis revolucionado",
			Uds: "hubieren revolucionado",
		},
	},
}
