var roer = {
	Indicative: {
		Present: {
			yo: "roo,roigo,royo",
			tú: "roes",
			Ud: "roe",
			nosotros: "roemos",
			vosotros: "roéis",
			Uds: "roen",
		},
		Preterite: {
			yo: "roí",
			tú: "roíste",
			Ud: "royó",
			nosotros: "roímos",
			vosotros: "roísteis",
			Uds: "royeron",
		},
		Imperfect: {
			yo: "roía",
			tú: "roías",
			Ud: "roía",
			nosotros: "roíamos",
			vosotros: "roíais",
			Uds: "roían",
		},
		Conditional: {
			yo: "roería",
			tú: "roerías",
			Ud: "roería",
			nosotros: "roeríamos",
			vosotros: "roeríais",
			Uds: "roerían",
		},
		Future: {
			yo: "roeré",
			tú: "roerás",
			Ud: "roerá",
			nosotros: "roeremos",
			vosotros: "roeréis",
			Uds: "roerán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "roa,roiga,roya",
			tú: "roas,roigas,royas",
			Ud: "roa,roiga",
			nosotros: "roamos,roigamos",
			vosotros: "roáis,roigáis,royáis",
			Uds: "roan,roigan,royan",
		},
		Imperfect: {
			yo: "royera",
			tú: "royeras",
			Ud: "royera",
			nosotros: "royéramos",
			vosotros: "royerais",
			Uds: "royeran",
		},
		Imperfect2: {
			yo: "royese",
			tú: "royeses",
			Ud: "royese",
			nosotros: "royésemos",
			vosotros: "royeseis",
			Uds: "royesen",
		},
		Future: {
			yo: "royere",
			tú: "royeres",
			Ud: "royere",
			nosotros: "royéremos",
			vosotros: "royereis",
			Uds: "royeren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "roe",
			Ud: "roa,roiga",
			nosotros: "roamos,roigamos",
			vosotros: "roed",
			Uds: "roan,roigan,royan",
		},
		Negative: {
			tú: "no roas,roigas,royas",
			Ud: "no roa,roiga",
			nosotros: "no roamos,roigamos",
			vosotros: "no roáis,roigáis,royáis",
			Uds: "no roan,roigan,royan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy royendo",
			tú: "estás royendo",
			Ud: "está royendo",
			nosotros: "estamos royendo",
			vosotros: "estáis royendo",
			Uds: "están royendo",
		},
		Preterite: {
			yo: "estuve royendo",
			tú: "estuviste royendo",
			Ud: "estuvo royendo",
			nosotros: "estuvimos royendo",
			vosotros: "estuvisteis royendo",
			Uds: "estuvieron royendo",
		},
		Imperfect: {
			Uds: "estaban royendo",
			yo: "estaba royendo",
			tú: "estabas royendo",
			Ud: "estaba royendo",
			nosotros: "estábamos royendo",
			vosotros: "estabais royendo",
		},
		Conditional: {
			yo: "estaría royendo",
			tú: "estarías royendo",
			Ud: "estaría royendo",
			nosotros: "estaríamos royendo",
			vosotros: "estaríais royendo",
			Uds: "estarían royendo",
		},
		Future: {
			yo: "estaré royendo",
			tú: "estarás royendo",
			Ud: "estará royendo",
			nosotros: "estaremos royendo",
			vosotros: "estaréis royendo",
			Uds: "estarán royendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he roído",
			tú: "has roído",
			Ud: "ha roído",
			nosotros: "hemos roído",
			vosotros: "habéis roído",
			Uds: "han roído",
		},
		Preterite: {
			yo: "hube roído",
			tú: "hubiste roído",
			Ud: "hubo roído",
			nosotros: "hubimos roído",
			vosotros: "hubisteis roído",
			Uds: "hubieron roído",
		},
		Past: {
			yo: "había roído",
			tú: "habías roído",
			Ud: "había roído",
			nosotros: "habíamos roído",
			vosotros: "habíais roído",
			Uds: "habían roído",
		},
		Conditional: {
			yo: "habría roído",
			tú: "habrías roído",
			Ud: "habría roído",
			nosotros: "habríamos roído",
			vosotros: "habríais roído",
			Uds: "habrían roído",
		},
		Future: {
			yo: "habré roído",
			tú: "habrás roído",
			Ud: "habrá roído",
			nosotros: "habremos roído",
			vosotros: "habréis roído",
			Uds: "habrán roído",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya roído",
			tú: "hayas roído",
			Ud: "haya roído",
			nosotros: "hayamos roído",
			vosotros: "hayáis roído",
			Uds: "hayan roído",
		},
		Past: {
			yo: "hubiera roído",
			tú: "hubieras roído",
			Ud: "hubiera roído",
			nosotros: "hubiéramos roído",
			vosotros: "hubierais roído",
			Uds: "hubieran roído",
		},
		Future: {
			yo: "hubiere roído",
			tú: "hubieres roído",
			Ud: "hubiere roído",
			nosotros: "hubiéremos roído",
			vosotros: "hubiereis roído",
			Uds: "hubieren roído",
		},
	},
}
