var saborear = {
	Indicative: {
		Present: {
			yo: "saboreo",
			tú: "saboreas",
			Ud: "saborea",
			nosotros: "saboreamos",
			vosotros: "saboreáis",
			Uds: "saborean",
		},
		Preterite: {
			yo: "saboreé",
			tú: "saboreaste",
			Ud: "saboreó",
			nosotros: "saboreamos",
			vosotros: "saboreasteis",
			Uds: "saborearon",
		},
		Imperfect: {
			yo: "saboreaba",
			tú: "saboreabas",
			Ud: "saboreaba",
			nosotros: "saboreábamos",
			vosotros: "saboreabais",
			Uds: "saboreaban",
		},
		Conditional: {
			yo: "saborearía",
			tú: "saborearías",
			Ud: "saborearía",
			nosotros: "saborearíamos",
			vosotros: "saborearíais",
			Uds: "saborearían",
		},
		Future: {
			yo: "saborearé",
			tú: "saborearás",
			Ud: "saboreará",
			nosotros: "saborearemos",
			vosotros: "saborearéis",
			Uds: "saborearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "saboree",
			tú: "saborees",
			Ud: "saboree",
			nosotros: "saboreemos",
			vosotros: "saboreéis",
			Uds: "saboreen",
		},
		Imperfect: {
			yo: "saboreara",
			tú: "saborearas",
			Ud: "saboreara",
			nosotros: "saboreáramos",
			vosotros: "saborearais",
			Uds: "saborearan",
		},
		Imperfect2: {
			yo: "saborease",
			tú: "saboreases",
			Ud: "saborease",
			nosotros: "saboreásemos",
			vosotros: "saboreaseis",
			Uds: "saboreasen",
		},
		Future: {
			yo: "saboreare",
			tú: "saboreares",
			Ud: "saboreare",
			nosotros: "saboreáremos",
			vosotros: "saboreareis",
			Uds: "saborearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "saborea",
			Ud: "saboree",
			nosotros: "saboreemos",
			vosotros: "saboread",
			Uds: "saboreen",
		},
		Negative: {
			tú: "no saborees",
			Ud: "no saboree",
			nosotros: "no saboreemos",
			vosotros: "no saboreéis",
			Uds: "no saboreen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy saboreando",
			tú: "estás saboreando",
			Ud: "está saboreando",
			nosotros: "estamos saboreando",
			vosotros: "estáis saboreando",
			Uds: "están saboreando",
		},
		Preterite: {
			yo: "estuve saboreando",
			tú: "estuviste saboreando",
			Ud: "estuvo saboreando",
			nosotros: "estuvimos saboreando",
			vosotros: "estuvisteis saboreando",
			Uds: "estuvieron saboreando",
		},
		Imperfect: {
			Uds: "estaban saboreando",
			yo: "estaba saboreando",
			tú: "estabas saboreando",
			Ud: "estaba saboreando",
			nosotros: "estábamos saboreando",
			vosotros: "estabais saboreando",
		},
		Conditional: {
			yo: "estaría saboreando",
			tú: "estarías saboreando",
			Ud: "estaría saboreando",
			nosotros: "estaríamos saboreando",
			vosotros: "estaríais saboreando",
			Uds: "estarían saboreando",
		},
		Future: {
			yo: "estaré saboreando",
			tú: "estarás saboreando",
			Ud: "estará saboreando",
			nosotros: "estaremos saboreando",
			vosotros: "estaréis saboreando",
			Uds: "estarán saboreando",
		},
	},
	Perfect: {
		Present: {
			yo: "he saboreado",
			tú: "has saboreado",
			Ud: "ha saboreado",
			nosotros: "hemos saboreado",
			vosotros: "habéis saboreado",
			Uds: "han saboreado",
		},
		Preterite: {
			yo: "hube saboreado",
			tú: "hubiste saboreado",
			Ud: "hubo saboreado",
			nosotros: "hubimos saboreado",
			vosotros: "hubisteis saboreado",
			Uds: "hubieron saboreado",
		},
		Past: {
			yo: "había saboreado",
			tú: "habías saboreado",
			Ud: "había saboreado",
			nosotros: "habíamos saboreado",
			vosotros: "habíais saboreado",
			Uds: "habían saboreado",
		},
		Conditional: {
			yo: "habría saboreado",
			tú: "habrías saboreado",
			Ud: "habría saboreado",
			nosotros: "habríamos saboreado",
			vosotros: "habríais saboreado",
			Uds: "habrían saboreado",
		},
		Future: {
			yo: "habré saboreado",
			tú: "habrás saboreado",
			Ud: "habrá saboreado",
			nosotros: "habremos saboreado",
			vosotros: "habréis saboreado",
			Uds: "habrán saboreado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya saboreado",
			tú: "hayas saboreado",
			Ud: "haya saboreado",
			nosotros: "hayamos saboreado",
			vosotros: "hayáis saboreado",
			Uds: "hayan saboreado",
		},
		Past: {
			yo: "hubiera saboreado",
			tú: "hubieras saboreado",
			Ud: "hubiera saboreado",
			nosotros: "hubiéramos saboreado",
			vosotros: "hubierais saboreado",
			Uds: "hubieran saboreado",
		},
		Future: {
			yo: "hubiere saboreado",
			tú: "hubieres saboreado",
			Ud: "hubiere saboreado",
			nosotros: "hubiéremos saboreado",
			vosotros: "hubiereis saboreado",
			Uds: "hubieren saboreado",
		},
	},
}
