var sancionar = {
	Indicative: {
		Present: {
			yo: "sanciono",
			tú: "sancionas",
			Ud: "sanciona",
			nosotros: "sancionamos",
			vosotros: "sancionáis",
			Uds: "sancionan",
		},
		Preterite: {
			yo: "sancioné",
			tú: "sancionaste",
			Ud: "sancionó",
			nosotros: "sancionamos",
			vosotros: "sancionasteis",
			Uds: "sancionaron",
		},
		Imperfect: {
			yo: "sancionaba",
			tú: "sancionabas",
			Ud: "sancionaba",
			nosotros: "sancionábamos",
			vosotros: "sancionabais",
			Uds: "sancionaban",
		},
		Conditional: {
			yo: "sancionaría",
			tú: "sancionarías",
			Ud: "sancionaría",
			nosotros: "sancionaríamos",
			vosotros: "sancionaríais",
			Uds: "sancionarían",
		},
		Future: {
			yo: "sancionaré",
			tú: "sancionarás",
			Ud: "sancionará",
			nosotros: "sancionaremos",
			vosotros: "sancionaréis",
			Uds: "sancionarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "sancione",
			tú: "sanciones",
			Ud: "sancione",
			nosotros: "sancionemos",
			vosotros: "sancionéis",
			Uds: "sancionen",
		},
		Imperfect: {
			yo: "sancionara",
			tú: "sancionaras",
			Ud: "sancionara",
			nosotros: "sancionáramos",
			vosotros: "sancionarais",
			Uds: "sancionaran",
		},
		Imperfect2: {
			yo: "sancionase",
			tú: "sancionases",
			Ud: "sancionase",
			nosotros: "sancionásemos",
			vosotros: "sancionaseis",
			Uds: "sancionasen",
		},
		Future: {
			yo: "sancionare",
			tú: "sancionares",
			Ud: "sancionare",
			nosotros: "sancionáremos",
			vosotros: "sancionareis",
			Uds: "sancionaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "sanciona",
			Ud: "sancione",
			nosotros: "sancionemos",
			vosotros: "sancionad",
			Uds: "sancionen",
		},
		Negative: {
			tú: "no sanciones",
			Ud: "no sancione",
			nosotros: "no sancionemos",
			vosotros: "no sancionéis",
			Uds: "no sancionen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy sancionando",
			tú: "estás sancionando",
			Ud: "está sancionando",
			nosotros: "estamos sancionando",
			vosotros: "estáis sancionando",
			Uds: "están sancionando",
		},
		Preterite: {
			yo: "estuve sancionando",
			tú: "estuviste sancionando",
			Ud: "estuvo sancionando",
			nosotros: "estuvimos sancionando",
			vosotros: "estuvisteis sancionando",
			Uds: "estuvieron sancionando",
		},
		Imperfect: {
			Uds: "estaban sancionando",
			yo: "estaba sancionando",
			tú: "estabas sancionando",
			Ud: "estaba sancionando",
			nosotros: "estábamos sancionando",
			vosotros: "estabais sancionando",
		},
		Conditional: {
			yo: "estaría sancionando",
			tú: "estarías sancionando",
			Ud: "estaría sancionando",
			nosotros: "estaríamos sancionando",
			vosotros: "estaríais sancionando",
			Uds: "estarían sancionando",
		},
		Future: {
			yo: "estaré sancionando",
			tú: "estarás sancionando",
			Ud: "estará sancionando",
			nosotros: "estaremos sancionando",
			vosotros: "estaréis sancionando",
			Uds: "estarán sancionando",
		},
	},
	Perfect: {
		Present: {
			yo: "he sancionado",
			tú: "has sancionado",
			Ud: "ha sancionado",
			nosotros: "hemos sancionado",
			vosotros: "habéis sancionado",
			Uds: "han sancionado",
		},
		Preterite: {
			yo: "hube sancionado",
			tú: "hubiste sancionado",
			Ud: "hubo sancionado",
			nosotros: "hubimos sancionado",
			vosotros: "hubisteis sancionado",
			Uds: "hubieron sancionado",
		},
		Past: {
			yo: "había sancionado",
			tú: "habías sancionado",
			Ud: "había sancionado",
			nosotros: "habíamos sancionado",
			vosotros: "habíais sancionado",
			Uds: "habían sancionado",
		},
		Conditional: {
			yo: "habría sancionado",
			tú: "habrías sancionado",
			Ud: "habría sancionado",
			nosotros: "habríamos sancionado",
			vosotros: "habríais sancionado",
			Uds: "habrían sancionado",
		},
		Future: {
			yo: "habré sancionado",
			tú: "habrás sancionado",
			Ud: "habrá sancionado",
			nosotros: "habremos sancionado",
			vosotros: "habréis sancionado",
			Uds: "habrán sancionado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya sancionado",
			tú: "hayas sancionado",
			Ud: "haya sancionado",
			nosotros: "hayamos sancionado",
			vosotros: "hayáis sancionado",
			Uds: "hayan sancionado",
		},
		Past: {
			yo: "hubiera sancionado",
			tú: "hubieras sancionado",
			Ud: "hubiera sancionado",
			nosotros: "hubiéramos sancionado",
			vosotros: "hubierais sancionado",
			Uds: "hubieran sancionado",
		},
		Future: {
			yo: "hubiere sancionado",
			tú: "hubieres sancionado",
			Ud: "hubiere sancionado",
			nosotros: "hubiéremos sancionado",
			vosotros: "hubiereis sancionado",
			Uds: "hubieren sancionado",
		},
	},
}
