var secretar = {
	Indicative: {
		Present: {
			yo: "secreto",
			tú: "secretas",
			Ud: "secreta",
			nosotros: "secretamos",
			vosotros: "secretáis",
			Uds: "secretan",
		},
		Preterite: {
			yo: "secreté",
			tú: "secretaste",
			Ud: "secretó",
			nosotros: "secretamos",
			vosotros: "secretasteis",
			Uds: "secretaron",
		},
		Imperfect: {
			yo: "secretaba",
			tú: "secretabas",
			Ud: "secretaba",
			nosotros: "secretábamos",
			vosotros: "secretabais",
			Uds: "secretaban",
		},
		Conditional: {
			yo: "secretaría",
			tú: "secretarías",
			Ud: "secretaría",
			nosotros: "secretaríamos",
			vosotros: "secretaríais",
			Uds: "secretarían",
		},
		Future: {
			yo: "secretaré",
			tú: "secretarás",
			Ud: "secretará",
			nosotros: "secretaremos",
			vosotros: "secretaréis",
			Uds: "secretarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "secrete",
			tú: "secretes",
			Ud: "secrete",
			nosotros: "secretemos",
			vosotros: "secretéis",
			Uds: "secreten",
		},
		Imperfect: {
			yo: "secretara",
			tú: "secretaras",
			Ud: "secretara",
			nosotros: "secretáramos",
			vosotros: "secretarais",
			Uds: "secretaran",
		},
		Imperfect2: {
			yo: "secretase",
			tú: "secretases",
			Ud: "secretase",
			nosotros: "secretásemos",
			vosotros: "secretaseis",
			Uds: "secretasen",
		},
		Future: {
			yo: "secretare",
			tú: "secretares",
			Ud: "secretare",
			nosotros: "secretáremos",
			vosotros: "secretareis",
			Uds: "secretaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "secreta",
			Ud: "secrete",
			nosotros: "secretemos",
			vosotros: "secretad",
			Uds: "secreten",
		},
		Negative: {
			tú: "no secretes",
			Ud: "no secrete",
			nosotros: "no secretemos",
			vosotros: "no secretéis",
			Uds: "no secreten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy secretando",
			tú: "estás secretando",
			Ud: "está secretando",
			nosotros: "estamos secretando",
			vosotros: "estáis secretando",
			Uds: "están secretando",
		},
		Preterite: {
			yo: "estuve secretando",
			tú: "estuviste secretando",
			Ud: "estuvo secretando",
			nosotros: "estuvimos secretando",
			vosotros: "estuvisteis secretando",
			Uds: "estuvieron secretando",
		},
		Imperfect: {
			Uds: "estaban secretando",
			yo: "estaba secretando",
			tú: "estabas secretando",
			Ud: "estaba secretando",
			nosotros: "estábamos secretando",
			vosotros: "estabais secretando",
		},
		Conditional: {
			yo: "estaría secretando",
			tú: "estarías secretando",
			Ud: "estaría secretando",
			nosotros: "estaríamos secretando",
			vosotros: "estaríais secretando",
			Uds: "estarían secretando",
		},
		Future: {
			yo: "estaré secretando",
			tú: "estarás secretando",
			Ud: "estará secretando",
			nosotros: "estaremos secretando",
			vosotros: "estaréis secretando",
			Uds: "estarán secretando",
		},
	},
	Perfect: {
		Present: {
			yo: "he secretado",
			tú: "has secretado",
			Ud: "ha secretado",
			nosotros: "hemos secretado",
			vosotros: "habéis secretado",
			Uds: "han secretado",
		},
		Preterite: {
			yo: "hube secretado",
			tú: "hubiste secretado",
			Ud: "hubo secretado",
			nosotros: "hubimos secretado",
			vosotros: "hubisteis secretado",
			Uds: "hubieron secretado",
		},
		Past: {
			yo: "había secretado",
			tú: "habías secretado",
			Ud: "había secretado",
			nosotros: "habíamos secretado",
			vosotros: "habíais secretado",
			Uds: "habían secretado",
		},
		Conditional: {
			yo: "habría secretado",
			tú: "habrías secretado",
			Ud: "habría secretado",
			nosotros: "habríamos secretado",
			vosotros: "habríais secretado",
			Uds: "habrían secretado",
		},
		Future: {
			yo: "habré secretado",
			tú: "habrás secretado",
			Ud: "habrá secretado",
			nosotros: "habremos secretado",
			vosotros: "habréis secretado",
			Uds: "habrán secretado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya secretado",
			tú: "hayas secretado",
			Ud: "haya secretado",
			nosotros: "hayamos secretado",
			vosotros: "hayáis secretado",
			Uds: "hayan secretado",
		},
		Past: {
			yo: "hubiera secretado",
			tú: "hubieras secretado",
			Ud: "hubiera secretado",
			nosotros: "hubiéramos secretado",
			vosotros: "hubierais secretado",
			Uds: "hubieran secretado",
		},
		Future: {
			yo: "hubiere secretado",
			tú: "hubieres secretado",
			Ud: "hubiere secretado",
			nosotros: "hubiéremos secretado",
			vosotros: "hubiereis secretado",
			Uds: "hubieren secretado",
		},
	},
}
