var secuestrar = {
	Indicative: {
		Present: {
			yo: "secuestro",
			tú: "secuestras",
			Ud: "secuestra",
			nosotros: "secuestramos",
			vosotros: "secuestráis",
			Uds: "secuestran",
		},
		Preterite: {
			yo: "secuestré",
			tú: "secuestraste",
			Ud: "secuestró",
			nosotros: "secuestramos",
			vosotros: "secuestrasteis",
			Uds: "secuestraron",
		},
		Imperfect: {
			yo: "secuestraba",
			tú: "secuestrabas",
			Ud: "secuestraba",
			nosotros: "secuestrábamos",
			vosotros: "secuestrabais",
			Uds: "secuestraban",
		},
		Conditional: {
			yo: "secuestraría",
			tú: "secuestrarías",
			Ud: "secuestraría",
			nosotros: "secuestraríamos",
			vosotros: "secuestraríais",
			Uds: "secuestrarían",
		},
		Future: {
			yo: "secuestraré",
			tú: "secuestrarás",
			Ud: "secuestrará",
			nosotros: "secuestraremos",
			vosotros: "secuestraréis",
			Uds: "secuestrarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "secuestre",
			tú: "secuestres",
			Ud: "secuestre",
			nosotros: "secuestremos",
			vosotros: "secuestréis",
			Uds: "secuestren",
		},
		Imperfect: {
			yo: "secuestrara",
			tú: "secuestraras",
			Ud: "secuestrara",
			nosotros: "secuestráramos",
			vosotros: "secuestrarais",
			Uds: "secuestraran",
		},
		Imperfect2: {
			yo: "secuestrase",
			tú: "secuestrases",
			Ud: "secuestrase",
			nosotros: "secuestrásemos",
			vosotros: "secuestraseis",
			Uds: "secuestrasen",
		},
		Future: {
			yo: "secuestrare",
			tú: "secuestrares",
			Ud: "secuestrare",
			nosotros: "secuestráremos",
			vosotros: "secuestrareis",
			Uds: "secuestraren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "secuestra",
			Ud: "secuestre",
			nosotros: "secuestremos",
			vosotros: "secuestrad",
			Uds: "secuestren",
		},
		Negative: {
			tú: "no secuestres",
			Ud: "no secuestre",
			nosotros: "no secuestremos",
			vosotros: "no secuestréis",
			Uds: "no secuestren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy secuestrando",
			tú: "estás secuestrando",
			Ud: "está secuestrando",
			nosotros: "estamos secuestrando",
			vosotros: "estáis secuestrando",
			Uds: "están secuestrando",
		},
		Preterite: {
			yo: "estuve secuestrando",
			tú: "estuviste secuestrando",
			Ud: "estuvo secuestrando",
			nosotros: "estuvimos secuestrando",
			vosotros: "estuvisteis secuestrando",
			Uds: "estuvieron secuestrando",
		},
		Imperfect: {
			Uds: "estaban secuestrando",
			yo: "estaba secuestrando",
			tú: "estabas secuestrando",
			Ud: "estaba secuestrando",
			nosotros: "estábamos secuestrando",
			vosotros: "estabais secuestrando",
		},
		Conditional: {
			yo: "estaría secuestrando",
			tú: "estarías secuestrando",
			Ud: "estaría secuestrando",
			nosotros: "estaríamos secuestrando",
			vosotros: "estaríais secuestrando",
			Uds: "estarían secuestrando",
		},
		Future: {
			yo: "estaré secuestrando",
			tú: "estarás secuestrando",
			Ud: "estará secuestrando",
			nosotros: "estaremos secuestrando",
			vosotros: "estaréis secuestrando",
			Uds: "estarán secuestrando",
		},
	},
	Perfect: {
		Present: {
			yo: "he secuestrado",
			tú: "has secuestrado",
			Ud: "ha secuestrado",
			nosotros: "hemos secuestrado",
			vosotros: "habéis secuestrado",
			Uds: "han secuestrado",
		},
		Preterite: {
			yo: "hube secuestrado",
			tú: "hubiste secuestrado",
			Ud: "hubo secuestrado",
			nosotros: "hubimos secuestrado",
			vosotros: "hubisteis secuestrado",
			Uds: "hubieron secuestrado",
		},
		Past: {
			yo: "había secuestrado",
			tú: "habías secuestrado",
			Ud: "había secuestrado",
			nosotros: "habíamos secuestrado",
			vosotros: "habíais secuestrado",
			Uds: "habían secuestrado",
		},
		Conditional: {
			yo: "habría secuestrado",
			tú: "habrías secuestrado",
			Ud: "habría secuestrado",
			nosotros: "habríamos secuestrado",
			vosotros: "habríais secuestrado",
			Uds: "habrían secuestrado",
		},
		Future: {
			yo: "habré secuestrado",
			tú: "habrás secuestrado",
			Ud: "habrá secuestrado",
			nosotros: "habremos secuestrado",
			vosotros: "habréis secuestrado",
			Uds: "habrán secuestrado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya secuestrado",
			tú: "hayas secuestrado",
			Ud: "haya secuestrado",
			nosotros: "hayamos secuestrado",
			vosotros: "hayáis secuestrado",
			Uds: "hayan secuestrado",
		},
		Past: {
			yo: "hubiera secuestrado",
			tú: "hubieras secuestrado",
			Ud: "hubiera secuestrado",
			nosotros: "hubiéramos secuestrado",
			vosotros: "hubierais secuestrado",
			Uds: "hubieran secuestrado",
		},
		Future: {
			yo: "hubiere secuestrado",
			tú: "hubieres secuestrado",
			Ud: "hubiere secuestrado",
			nosotros: "hubiéremos secuestrado",
			vosotros: "hubiereis secuestrado",
			Uds: "hubieren secuestrado",
		},
	},
}
