var sentir = {
	Indicative: {
		Present: {
			yo: "siento",
			tú: "sientes",
			Ud: "siente",
			nosotros: "sentimos",
			vosotros: "sentís",
			Uds: "sienten",
		},
		Preterite: {
			yo: "sentí",
			tú: "sentiste",
			Ud: "sintió",
			nosotros: "sentimos",
			vosotros: "sentisteis",
			Uds: "sintieron",
		},
		Imperfect: {
			yo: "sentía",
			tú: "sentías",
			Ud: "sentía",
			nosotros: "sentíamos",
			vosotros: "sentíais",
			Uds: "sentían",
		},
		Conditional: {
			yo: "sentiría",
			tú: "sentirías",
			Ud: "sentiría",
			nosotros: "sentiríamos",
			vosotros: "sentiríais",
			Uds: "sentirían",
		},
		Future: {
			yo: "sentiré",
			tú: "sentirás",
			Ud: "sentirá",
			nosotros: "sentiremos",
			vosotros: "sentiréis",
			Uds: "sentirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "sienta",
			tú: "sientas",
			Ud: "sienta",
			nosotros: "sintamos",
			vosotros: "sintáis",
			Uds: "sientan",
		},
		Imperfect: {
			yo: "sintiera",
			tú: "sintieras",
			Ud: "sintiera",
			nosotros: "sintiéramos",
			vosotros: "sintierais",
			Uds: "sintieran",
		},
		Imperfect2: {
			yo: "sintiese",
			tú: "sintieses",
			Ud: "sintiese",
			nosotros: "sintiésemos",
			vosotros: "sintieseis",
			Uds: "sintiesen",
		},
		Future: {
			yo: "sintiere",
			tú: "sintieres",
			Ud: "sintiere",
			nosotros: "sintiéremos",
			vosotros: "sintiereis",
			Uds: "sintieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "siente",
			Ud: "sienta",
			nosotros: "sintamos",
			vosotros: "sentid",
			Uds: "sientan",
		},
		Negative: {
			tú: "no sientas",
			Ud: "no sienta",
			nosotros: "no sintamos",
			vosotros: "no sintáis",
			Uds: "no sientan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy sintiendo",
			tú: "estás sintiendo",
			Ud: "está sintiendo",
			nosotros: "estamos sintiendo",
			vosotros: "estáis sintiendo",
			Uds: "están sintiendo",
		},
		Preterite: {
			yo: "estuve sintiendo",
			tú: "estuviste sintiendo",
			Ud: "estuvo sintiendo",
			nosotros: "estuvimos sintiendo",
			vosotros: "estuvisteis sintiendo",
			Uds: "estuvieron sintiendo",
		},
		Imperfect: {
			Uds: "estaban sintiendo",
			yo: "estaba sintiendo",
			tú: "estabas sintiendo",
			Ud: "estaba sintiendo",
			nosotros: "estábamos sintiendo",
			vosotros: "estabais sintiendo",
		},
		Conditional: {
			yo: "estaría sintiendo",
			tú: "estarías sintiendo",
			Ud: "estaría sintiendo",
			nosotros: "estaríamos sintiendo",
			vosotros: "estaríais sintiendo",
			Uds: "estarían sintiendo",
		},
		Future: {
			yo: "estaré sintiendo",
			tú: "estarás sintiendo",
			Ud: "estará sintiendo",
			nosotros: "estaremos sintiendo",
			vosotros: "estaréis sintiendo",
			Uds: "estarán sintiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he sentido",
			tú: "has sentido",
			Ud: "ha sentido",
			nosotros: "hemos sentido",
			vosotros: "habéis sentido",
			Uds: "han sentido",
		},
		Preterite: {
			yo: "hube sentido",
			tú: "hubiste sentido",
			Ud: "hubo sentido",
			nosotros: "hubimos sentido",
			vosotros: "hubisteis sentido",
			Uds: "hubieron sentido",
		},
		Past: {
			yo: "había sentido",
			tú: "habías sentido",
			Ud: "había sentido",
			nosotros: "habíamos sentido",
			vosotros: "habíais sentido",
			Uds: "habían sentido",
		},
		Conditional: {
			yo: "habría sentido",
			tú: "habrías sentido",
			Ud: "habría sentido",
			nosotros: "habríamos sentido",
			vosotros: "habríais sentido",
			Uds: "habrían sentido",
		},
		Future: {
			yo: "habré sentido",
			tú: "habrás sentido",
			Ud: "habrá sentido",
			nosotros: "habremos sentido",
			vosotros: "habréis sentido",
			Uds: "habrán sentido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya sentido",
			tú: "hayas sentido",
			Ud: "haya sentido",
			nosotros: "hayamos sentido",
			vosotros: "hayáis sentido",
			Uds: "hayan sentido",
		},
		Past: {
			yo: "hubiera sentido",
			tú: "hubieras sentido",
			Ud: "hubiera sentido",
			nosotros: "hubiéramos sentido",
			vosotros: "hubierais sentido",
			Uds: "hubieran sentido",
		},
		Future: {
			yo: "hubiere sentido",
			tú: "hubieres sentido",
			Ud: "hubiere sentido",
			nosotros: "hubiéremos sentido",
			vosotros: "hubiereis sentido",
			Uds: "hubieren sentido",
		},
	},
}
