var sentar = {
	Indicative: {
		Present: {
			yo: "siento",
			tú: "sientas",
			Ud: "sienta",
			nosotros: "sentamos",
			vosotros: "sentáis",
			Uds: "sientan",
		},
		Preterite: {
			yo: "senté",
			tú: "sentaste",
			Ud: "sentó",
			nosotros: "sentamos",
			vosotros: "sentasteis",
			Uds: "sentaron",
		},
		Imperfect: {
			yo: "sentaba",
			tú: "sentabas",
			Ud: "sentaba",
			nosotros: "sentábamos",
			vosotros: "sentabais",
			Uds: "sentaban",
		},
		Conditional: {
			yo: "sentaría",
			tú: "sentarías",
			Ud: "sentaría",
			nosotros: "sentaríamos",
			vosotros: "sentaríais",
			Uds: "sentarían",
		},
		Future: {
			yo: "sentaré",
			tú: "sentarás",
			Ud: "sentará",
			nosotros: "sentaremos",
			vosotros: "sentaréis",
			Uds: "sentarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "siente",
			tú: "sientes",
			Ud: "siente",
			nosotros: "sentemos",
			vosotros: "sentéis",
			Uds: "sienten",
		},
		Imperfect: {
			yo: "sentara",
			tú: "sentaras",
			Ud: "sentara",
			nosotros: "sentáramos",
			vosotros: "sentarais",
			Uds: "sentaran",
		},
		Imperfect2: {
			yo: "sentase",
			tú: "sentases",
			Ud: "sentase",
			nosotros: "sentásemos",
			vosotros: "sentaseis",
			Uds: "sentasen",
		},
		Future: {
			yo: "sentare",
			tú: "sentares",
			Ud: "sentare",
			nosotros: "sentáremos",
			vosotros: "sentareis",
			Uds: "sentaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "sienta",
			Ud: "siente",
			nosotros: "sentemos",
			vosotros: "sentad",
			Uds: "sienten",
		},
		Negative: {
			tú: "no sientes",
			Ud: "no siente",
			nosotros: "no sentemos",
			vosotros: "no sentéis",
			Uds: "no sienten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy sentando",
			tú: "estás sentando",
			Ud: "está sentando",
			nosotros: "estamos sentando",
			vosotros: "estáis sentando",
			Uds: "están sentando",
		},
		Preterite: {
			yo: "estuve sentando",
			tú: "estuviste sentando",
			Ud: "estuvo sentando",
			nosotros: "estuvimos sentando",
			vosotros: "estuvisteis sentando",
			Uds: "estuvieron sentando",
		},
		Imperfect: {
			Uds: "estaban sentando",
			yo: "estaba sentando",
			tú: "estabas sentando",
			Ud: "estaba sentando",
			nosotros: "estábamos sentando",
			vosotros: "estabais sentando",
		},
		Conditional: {
			yo: "estaría sentando",
			tú: "estarías sentando",
			Ud: "estaría sentando",
			nosotros: "estaríamos sentando",
			vosotros: "estaríais sentando",
			Uds: "estarían sentando",
		},
		Future: {
			yo: "estaré sentando",
			tú: "estarás sentando",
			Ud: "estará sentando",
			nosotros: "estaremos sentando",
			vosotros: "estaréis sentando",
			Uds: "estarán sentando",
		},
	},
	Perfect: {
		Present: {
			yo: "he sentado",
			tú: "has sentado",
			Ud: "ha sentado",
			nosotros: "hemos sentado",
			vosotros: "habéis sentado",
			Uds: "han sentado",
		},
		Preterite: {
			yo: "hube sentado",
			tú: "hubiste sentado",
			Ud: "hubo sentado",
			nosotros: "hubimos sentado",
			vosotros: "hubisteis sentado",
			Uds: "hubieron sentado",
		},
		Past: {
			yo: "había sentado",
			tú: "habías sentado",
			Ud: "había sentado",
			nosotros: "habíamos sentado",
			vosotros: "habíais sentado",
			Uds: "habían sentado",
		},
		Conditional: {
			yo: "habría sentado",
			tú: "habrías sentado",
			Ud: "habría sentado",
			nosotros: "habríamos sentado",
			vosotros: "habríais sentado",
			Uds: "habrían sentado",
		},
		Future: {
			yo: "habré sentado",
			tú: "habrás sentado",
			Ud: "habrá sentado",
			nosotros: "habremos sentado",
			vosotros: "habréis sentado",
			Uds: "habrán sentado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya sentado",
			tú: "hayas sentado",
			Ud: "haya sentado",
			nosotros: "hayamos sentado",
			vosotros: "hayáis sentado",
			Uds: "hayan sentado",
		},
		Past: {
			yo: "hubiera sentado",
			tú: "hubieras sentado",
			Ud: "hubiera sentado",
			nosotros: "hubiéramos sentado",
			vosotros: "hubierais sentado",
			Uds: "hubieran sentado",
		},
		Future: {
			yo: "hubiere sentado",
			tú: "hubieres sentado",
			Ud: "hubiere sentado",
			nosotros: "hubiéremos sentado",
			vosotros: "hubiereis sentado",
			Uds: "hubieren sentado",
		},
	},
}
