var ser = {
	Indicative: {
		Present: {
			yo: "soy",
			tú: "eres",
			Ud: "es",
			nosotros: "somos",
			vosotros: "sois",
			Uds: "son",
		},
		Preterite: {
			yo: "fui",
			tú: "fuiste",
			Ud: "fue",
			nosotros: "fuimos",
			vosotros: "fuisteis",
			Uds: "fueron",
		},
		Imperfect: {
			yo: "era",
			tú: "eras",
			Ud: "era",
			nosotros: "éramos",
			vosotros: "erais",
			Uds: "eran",
		},
		Conditional: {
			yo: "sería",
			tú: "serías",
			Ud: "sería",
			nosotros: "seríamos",
			vosotros: "seríais",
			Uds: "serían",
		},
		Future: {
			yo: "seré",
			tú: "serás",
			Ud: "será",
			nosotros: "seremos",
			vosotros: "seréis",
			Uds: "serán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "sea",
			tú: "seas",
			Ud: "sea",
			nosotros: "seamos",
			vosotros: "seáis",
			Uds: "sean",
		},
		Imperfect: {
			yo: "fuera",
			tú: "fueras",
			Ud: "fuera",
			nosotros: "fuéramos",
			vosotros: "fuerais",
			Uds: "fueran",
		},
		Imperfect2: {
			yo: "fuese",
			tú: "fueses",
			Ud: "fuese",
			nosotros: "fuésemos",
			vosotros: "fueseis",
			Uds: "fuesen",
		},
		Future: {
			yo: "fuere",
			tú: "fueres",
			Ud: "fuere",
			nosotros: "fuéremos",
			vosotros: "fuereis",
			Uds: "fueren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "sé",
			Ud: "sea",
			nosotros: "seamos",
			vosotros: "sed",
			Uds: "sean",
		},
		Negative: {
			tú: "no seas",
			Ud: "no sea",
			nosotros: "no seamos",
			vosotros: "no seáis",
			Uds: "no sean",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy siendo",
			tú: "estás siendo",
			Ud: "está siendo",
			nosotros: "estamos siendo",
			vosotros: "estáis siendo",
			Uds: "están siendo",
		},
		Preterite: {
			yo: "estuve siendo",
			tú: "estuviste siendo",
			Ud: "estuvo siendo",
			nosotros: "estuvimos siendo",
			vosotros: "estuvisteis siendo",
			Uds: "estuvieron siendo",
		},
		Imperfect: {
			Uds: "estaban siendo",
			yo: "estaba siendo",
			tú: "estabas siendo",
			Ud: "estaba siendo",
			nosotros: "estábamos siendo",
			vosotros: "estabais siendo",
		},
		Conditional: {
			yo: "estaría siendo",
			tú: "estarías siendo",
			Ud: "estaría siendo",
			nosotros: "estaríamos siendo",
			vosotros: "estaríais siendo",
			Uds: "estarían siendo",
		},
		Future: {
			yo: "estaré siendo",
			tú: "estarás siendo",
			Ud: "estará siendo",
			nosotros: "estaremos siendo",
			vosotros: "estaréis siendo",
			Uds: "estarán siendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he sido",
			tú: "has sido",
			Ud: "ha sido",
			nosotros: "hemos sido",
			vosotros: "habéis sido",
			Uds: "han sido",
		},
		Preterite: {
			yo: "hube sido",
			tú: "hubiste sido",
			Ud: "hubo sido",
			nosotros: "hubimos sido",
			vosotros: "hubisteis sido",
			Uds: "hubieron sido",
		},
		Past: {
			yo: "había sido",
			tú: "habías sido",
			Ud: "había sido",
			nosotros: "habíamos sido",
			vosotros: "habíais sido",
			Uds: "habían sido",
		},
		Conditional: {
			yo: "habría sido",
			tú: "habrías sido",
			Ud: "habría sido",
			nosotros: "habríamos sido",
			vosotros: "habríais sido",
			Uds: "habrían sido",
		},
		Future: {
			yo: "habré sido",
			tú: "habrás sido",
			Ud: "habrá sido",
			nosotros: "habremos sido",
			vosotros: "habréis sido",
			Uds: "habrán sido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya sido",
			tú: "hayas sido",
			Ud: "haya sido",
			nosotros: "hayamos sido",
			vosotros: "hayáis sido",
			Uds: "hayan sido",
		},
		Past: {
			yo: "hubiera sido",
			tú: "hubieras sido",
			Ud: "hubiera sido",
			nosotros: "hubiéramos sido",
			vosotros: "hubierais sido",
			Uds: "hubieran sido",
		},
		Future: {
			yo: "hubiere sido",
			tú: "hubieres sido",
			Ud: "hubiere sido",
			nosotros: "hubiéremos sido",
			vosotros: "hubiereis sido",
			Uds: "hubieren sido",
		},
	},
}
