var serrar = {
	Indicative: {
		Present: {
			yo: "sierro",
			tú: "sierras",
			Ud: "sierra",
			nosotros: "serramos",
			vosotros: "serráis",
			Uds: "sierran",
		},
		Preterite: {
			yo: "serré",
			tú: "serraste",
			Ud: "serró",
			nosotros: "serramos",
			vosotros: "serrasteis",
			Uds: "serraron",
		},
		Imperfect: {
			yo: "serraba",
			tú: "serrabas",
			Ud: "serraba",
			nosotros: "serrábamos",
			vosotros: "serrabais",
			Uds: "serraban",
		},
		Conditional: {
			yo: "serraría",
			tú: "serrarías",
			Ud: "serraría",
			nosotros: "serraríamos",
			vosotros: "serraríais",
			Uds: "serrarían",
		},
		Future: {
			yo: "serraré",
			tú: "serrarás",
			Ud: "serrará",
			nosotros: "serraremos",
			vosotros: "serraréis",
			Uds: "serrarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "sierre",
			tú: "sierres",
			Ud: "sierre",
			nosotros: "serremos",
			vosotros: "serréis",
			Uds: "sierren",
		},
		Imperfect: {
			yo: "serrara",
			tú: "serraras",
			Ud: "serrara",
			nosotros: "serráramos",
			vosotros: "serrarais",
			Uds: "serraran",
		},
		Imperfect2: {
			yo: "serrase",
			tú: "serrases",
			Ud: "serrase",
			nosotros: "serrásemos",
			vosotros: "serraseis",
			Uds: "serrasen",
		},
		Future: {
			yo: "serrare",
			tú: "serrares",
			Ud: "serrare",
			nosotros: "serráremos",
			vosotros: "serrareis",
			Uds: "serraren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "sierra",
			Ud: "sierre",
			nosotros: "serremos",
			vosotros: "serrad",
			Uds: "sierren",
		},
		Negative: {
			tú: "no sierres",
			Ud: "no sierre",
			nosotros: "no serremos",
			vosotros: "no serréis",
			Uds: "no sierren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy serrando",
			tú: "estás serrando",
			Ud: "está serrando",
			nosotros: "estamos serrando",
			vosotros: "estáis serrando",
			Uds: "están serrando",
		},
		Preterite: {
			yo: "estuve serrando",
			tú: "estuviste serrando",
			Ud: "estuvo serrando",
			nosotros: "estuvimos serrando",
			vosotros: "estuvisteis serrando",
			Uds: "estuvieron serrando",
		},
		Imperfect: {
			Uds: "estaban serrando",
			yo: "estaba serrando",
			tú: "estabas serrando",
			Ud: "estaba serrando",
			nosotros: "estábamos serrando",
			vosotros: "estabais serrando",
		},
		Conditional: {
			yo: "estaría serrando",
			tú: "estarías serrando",
			Ud: "estaría serrando",
			nosotros: "estaríamos serrando",
			vosotros: "estaríais serrando",
			Uds: "estarían serrando",
		},
		Future: {
			yo: "estaré serrando",
			tú: "estarás serrando",
			Ud: "estará serrando",
			nosotros: "estaremos serrando",
			vosotros: "estaréis serrando",
			Uds: "estarán serrando",
		},
	},
	Perfect: {
		Present: {
			yo: "he serrado",
			tú: "has serrado",
			Ud: "ha serrado",
			nosotros: "hemos serrado",
			vosotros: "habéis serrado",
			Uds: "han serrado",
		},
		Preterite: {
			yo: "hube serrado",
			tú: "hubiste serrado",
			Ud: "hubo serrado",
			nosotros: "hubimos serrado",
			vosotros: "hubisteis serrado",
			Uds: "hubieron serrado",
		},
		Past: {
			yo: "había serrado",
			tú: "habías serrado",
			Ud: "había serrado",
			nosotros: "habíamos serrado",
			vosotros: "habíais serrado",
			Uds: "habían serrado",
		},
		Conditional: {
			yo: "habría serrado",
			tú: "habrías serrado",
			Ud: "habría serrado",
			nosotros: "habríamos serrado",
			vosotros: "habríais serrado",
			Uds: "habrían serrado",
		},
		Future: {
			yo: "habré serrado",
			tú: "habrás serrado",
			Ud: "habrá serrado",
			nosotros: "habremos serrado",
			vosotros: "habréis serrado",
			Uds: "habrán serrado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya serrado",
			tú: "hayas serrado",
			Ud: "haya serrado",
			nosotros: "hayamos serrado",
			vosotros: "hayáis serrado",
			Uds: "hayan serrado",
		},
		Past: {
			yo: "hubiera serrado",
			tú: "hubieras serrado",
			Ud: "hubiera serrado",
			nosotros: "hubiéramos serrado",
			vosotros: "hubierais serrado",
			Uds: "hubieran serrado",
		},
		Future: {
			yo: "hubiere serrado",
			tú: "hubieres serrado",
			Ud: "hubiere serrado",
			nosotros: "hubiéremos serrado",
			vosotros: "hubiereis serrado",
			Uds: "hubieren serrado",
		},
	},
}
