var servir = {
	Indicative: {
		Present: {
			yo: "sirvo",
			tú: "sirves",
			Ud: "sirve",
			nosotros: "servimos",
			vosotros: "servís",
			Uds: "sirven",
		},
		Preterite: {
			yo: "serví",
			tú: "serviste",
			Ud: "sirvió",
			nosotros: "servimos",
			vosotros: "servisteis",
			Uds: "sirvieron",
		},
		Imperfect: {
			yo: "servía",
			tú: "servías",
			Ud: "servía",
			nosotros: "servíamos",
			vosotros: "servíais",
			Uds: "servían",
		},
		Conditional: {
			yo: "serviría",
			tú: "servirías",
			Ud: "serviría",
			nosotros: "serviríamos",
			vosotros: "serviríais",
			Uds: "servirían",
		},
		Future: {
			yo: "serviré",
			tú: "servirás",
			Ud: "servirá",
			nosotros: "serviremos",
			vosotros: "serviréis",
			Uds: "servirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "sirva",
			tú: "sirvas",
			Ud: "sirva",
			nosotros: "sirvamos",
			vosotros: "sirváis",
			Uds: "sirvan",
		},
		Imperfect: {
			yo: "sirviera",
			tú: "sirvieras",
			Ud: "sirviera",
			nosotros: "sirviéramos",
			vosotros: "sirvierais",
			Uds: "sirvieran",
		},
		Imperfect2: {
			yo: "sirviese",
			tú: "sirvieses",
			Ud: "sirviese",
			nosotros: "sirviésemos",
			vosotros: "sirvieseis",
			Uds: "sirviesen",
		},
		Future: {
			yo: "sirviere",
			tú: "sirvieres",
			Ud: "sirviere",
			nosotros: "sirviéremos",
			vosotros: "sirviereis",
			Uds: "sirvieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "sirve",
			Ud: "sirva",
			nosotros: "sirvamos",
			vosotros: "servid",
			Uds: "sirvan",
		},
		Negative: {
			tú: "no sirvas",
			Ud: "no sirva",
			nosotros: "no sirvamos",
			vosotros: "no sirváis",
			Uds: "no sirvan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy sirviendo",
			tú: "estás sirviendo",
			Ud: "está sirviendo",
			nosotros: "estamos sirviendo",
			vosotros: "estáis sirviendo",
			Uds: "están sirviendo",
		},
		Preterite: {
			yo: "estuve sirviendo",
			tú: "estuviste sirviendo",
			Ud: "estuvo sirviendo",
			nosotros: "estuvimos sirviendo",
			vosotros: "estuvisteis sirviendo",
			Uds: "estuvieron sirviendo",
		},
		Imperfect: {
			Uds: "estaban sirviendo",
			yo: "estaba sirviendo",
			tú: "estabas sirviendo",
			Ud: "estaba sirviendo",
			nosotros: "estábamos sirviendo",
			vosotros: "estabais sirviendo",
		},
		Conditional: {
			yo: "estaría sirviendo",
			tú: "estarías sirviendo",
			Ud: "estaría sirviendo",
			nosotros: "estaríamos sirviendo",
			vosotros: "estaríais sirviendo",
			Uds: "estarían sirviendo",
		},
		Future: {
			yo: "estaré sirviendo",
			tú: "estarás sirviendo",
			Ud: "estará sirviendo",
			nosotros: "estaremos sirviendo",
			vosotros: "estaréis sirviendo",
			Uds: "estarán sirviendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he servido",
			tú: "has servido",
			Ud: "ha servido",
			nosotros: "hemos servido",
			vosotros: "habéis servido",
			Uds: "han servido",
		},
		Preterite: {
			yo: "hube servido",
			tú: "hubiste servido",
			Ud: "hubo servido",
			nosotros: "hubimos servido",
			vosotros: "hubisteis servido",
			Uds: "hubieron servido",
		},
		Past: {
			yo: "había servido",
			tú: "habías servido",
			Ud: "había servido",
			nosotros: "habíamos servido",
			vosotros: "habíais servido",
			Uds: "habían servido",
		},
		Conditional: {
			yo: "habría servido",
			tú: "habrías servido",
			Ud: "habría servido",
			nosotros: "habríamos servido",
			vosotros: "habríais servido",
			Uds: "habrían servido",
		},
		Future: {
			yo: "habré servido",
			tú: "habrás servido",
			Ud: "habrá servido",
			nosotros: "habremos servido",
			vosotros: "habréis servido",
			Uds: "habrán servido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya servido",
			tú: "hayas servido",
			Ud: "haya servido",
			nosotros: "hayamos servido",
			vosotros: "hayáis servido",
			Uds: "hayan servido",
		},
		Past: {
			yo: "hubiera servido",
			tú: "hubieras servido",
			Ud: "hubiera servido",
			nosotros: "hubiéramos servido",
			vosotros: "hubierais servido",
			Uds: "hubieran servido",
		},
		Future: {
			yo: "hubiere servido",
			tú: "hubieres servido",
			Ud: "hubiere servido",
			nosotros: "hubiéremos servido",
			vosotros: "hubiereis servido",
			Uds: "hubieren servido",
		},
	},
}
