var señalar = {
	Indicative: {
		Present: {
			yo: "señalo",
			tú: "señalas",
			Ud: "señala",
			nosotros: "señalamos",
			vosotros: "señaláis",
			Uds: "señalan",
		},
		Preterite: {
			yo: "señalé",
			tú: "señalaste",
			Ud: "señaló",
			nosotros: "señalamos",
			vosotros: "señalasteis",
			Uds: "señalaron",
		},
		Imperfect: {
			yo: "señalaba",
			tú: "señalabas",
			Ud: "señalaba",
			nosotros: "señalábamos",
			vosotros: "señalabais",
			Uds: "señalaban",
		},
		Conditional: {
			yo: "señalaría",
			tú: "señalarías",
			Ud: "señalaría",
			nosotros: "señalaríamos",
			vosotros: "señalaríais",
			Uds: "señalarían",
		},
		Future: {
			yo: "señalaré",
			tú: "señalarás",
			Ud: "señalará",
			nosotros: "señalaremos",
			vosotros: "señalaréis",
			Uds: "señalarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "señale",
			tú: "señales",
			Ud: "señale",
			nosotros: "señalemos",
			vosotros: "señaléis",
			Uds: "señalen",
		},
		Imperfect: {
			yo: "señalara",
			tú: "señalaras",
			Ud: "señalara",
			nosotros: "señaláramos",
			vosotros: "señalarais",
			Uds: "señalaran",
		},
		Imperfect2: {
			yo: "señalase",
			tú: "señalases",
			Ud: "señalase",
			nosotros: "señalásemos",
			vosotros: "señalaseis",
			Uds: "señalasen",
		},
		Future: {
			yo: "señalare",
			tú: "señalares",
			Ud: "señalare",
			nosotros: "señaláremos",
			vosotros: "señalareis",
			Uds: "señalaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "señala",
			Ud: "señale",
			nosotros: "señalemos",
			vosotros: "señalad",
			Uds: "señalen",
		},
		Negative: {
			tú: "no señales",
			Ud: "no señale",
			nosotros: "no señalemos",
			vosotros: "no señaléis",
			Uds: "no señalen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy señalando",
			tú: "estás señalando",
			Ud: "está señalando",
			nosotros: "estamos señalando",
			vosotros: "estáis señalando",
			Uds: "están señalando",
		},
		Preterite: {
			yo: "estuve señalando",
			tú: "estuviste señalando",
			Ud: "estuvo señalando",
			nosotros: "estuvimos señalando",
			vosotros: "estuvisteis señalando",
			Uds: "estuvieron señalando",
		},
		Imperfect: {
			Uds: "estaban señalando",
			yo: "estaba señalando",
			tú: "estabas señalando",
			Ud: "estaba señalando",
			nosotros: "estábamos señalando",
			vosotros: "estabais señalando",
		},
		Conditional: {
			yo: "estaría señalando",
			tú: "estarías señalando",
			Ud: "estaría señalando",
			nosotros: "estaríamos señalando",
			vosotros: "estaríais señalando",
			Uds: "estarían señalando",
		},
		Future: {
			yo: "estaré señalando",
			tú: "estarás señalando",
			Ud: "estará señalando",
			nosotros: "estaremos señalando",
			vosotros: "estaréis señalando",
			Uds: "estarán señalando",
		},
	},
	Perfect: {
		Present: {
			yo: "he señalado",
			tú: "has señalado",
			Ud: "ha señalado",
			nosotros: "hemos señalado",
			vosotros: "habéis señalado",
			Uds: "han señalado",
		},
		Preterite: {
			yo: "hube señalado",
			tú: "hubiste señalado",
			Ud: "hubo señalado",
			nosotros: "hubimos señalado",
			vosotros: "hubisteis señalado",
			Uds: "hubieron señalado",
		},
		Past: {
			yo: "había señalado",
			tú: "habías señalado",
			Ud: "había señalado",
			nosotros: "habíamos señalado",
			vosotros: "habíais señalado",
			Uds: "habían señalado",
		},
		Conditional: {
			yo: "habría señalado",
			tú: "habrías señalado",
			Ud: "habría señalado",
			nosotros: "habríamos señalado",
			vosotros: "habríais señalado",
			Uds: "habrían señalado",
		},
		Future: {
			yo: "habré señalado",
			tú: "habrás señalado",
			Ud: "habrá señalado",
			nosotros: "habremos señalado",
			vosotros: "habréis señalado",
			Uds: "habrán señalado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya señalado",
			tú: "hayas señalado",
			Ud: "haya señalado",
			nosotros: "hayamos señalado",
			vosotros: "hayáis señalado",
			Uds: "hayan señalado",
		},
		Past: {
			yo: "hubiera señalado",
			tú: "hubieras señalado",
			Ud: "hubiera señalado",
			nosotros: "hubiéramos señalado",
			vosotros: "hubierais señalado",
			Uds: "hubieran señalado",
		},
		Future: {
			yo: "hubiere señalado",
			tú: "hubieres señalado",
			Ud: "hubiere señalado",
			nosotros: "hubiéremos señalado",
			vosotros: "hubiereis señalado",
			Uds: "hubieren señalado",
		},
	},
}
