var sincopar = {
	Indicative: {
		Present: {
			yo: "sincopo",
			tú: "sincopas",
			Ud: "sincopa",
			nosotros: "sincopamos",
			vosotros: "sincopáis",
			Uds: "sincopan",
		},
		Preterite: {
			yo: "sincopé",
			tú: "sincopaste",
			Ud: "sincopó",
			nosotros: "sincopamos",
			vosotros: "sincopasteis",
			Uds: "sincoparon",
		},
		Imperfect: {
			yo: "sincopaba",
			tú: "sincopabas",
			Ud: "sincopaba",
			nosotros: "sincopábamos",
			vosotros: "sincopabais",
			Uds: "sincopaban",
		},
		Conditional: {
			yo: "sincoparía",
			tú: "sincoparías",
			Ud: "sincoparía",
			nosotros: "sincoparíamos",
			vosotros: "sincoparíais",
			Uds: "sincoparían",
		},
		Future: {
			yo: "sincoparé",
			tú: "sincoparás",
			Ud: "sincopará",
			nosotros: "sincoparemos",
			vosotros: "sincoparéis",
			Uds: "sincoparán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "sincope",
			tú: "sincopes",
			Ud: "sincope",
			nosotros: "sincopemos",
			vosotros: "sincopéis",
			Uds: "sincopen",
		},
		Imperfect: {
			yo: "sincopara",
			tú: "sincoparas",
			Ud: "sincopara",
			nosotros: "sincopáramos",
			vosotros: "sincoparais",
			Uds: "sincoparan",
		},
		Imperfect2: {
			yo: "sincopase",
			tú: "sincopases",
			Ud: "sincopase",
			nosotros: "sincopásemos",
			vosotros: "sincopaseis",
			Uds: "sincopasen",
		},
		Future: {
			yo: "sincopare",
			tú: "sincopares",
			Ud: "sincopare",
			nosotros: "sincopáremos",
			vosotros: "sincopareis",
			Uds: "sincoparen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "sincopa",
			Ud: "sincope",
			nosotros: "sincopemos",
			vosotros: "sincopad",
			Uds: "sincopen",
		},
		Negative: {
			tú: "no sincopes",
			Ud: "no sincope",
			nosotros: "no sincopemos",
			vosotros: "no sincopéis",
			Uds: "no sincopen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy sincopando",
			tú: "estás sincopando",
			Ud: "está sincopando",
			nosotros: "estamos sincopando",
			vosotros: "estáis sincopando",
			Uds: "están sincopando",
		},
		Preterite: {
			yo: "estuve sincopando",
			tú: "estuviste sincopando",
			Ud: "estuvo sincopando",
			nosotros: "estuvimos sincopando",
			vosotros: "estuvisteis sincopando",
			Uds: "estuvieron sincopando",
		},
		Imperfect: {
			Uds: "estaban sincopando",
			yo: "estaba sincopando",
			tú: "estabas sincopando",
			Ud: "estaba sincopando",
			nosotros: "estábamos sincopando",
			vosotros: "estabais sincopando",
		},
		Conditional: {
			yo: "estaría sincopando",
			tú: "estarías sincopando",
			Ud: "estaría sincopando",
			nosotros: "estaríamos sincopando",
			vosotros: "estaríais sincopando",
			Uds: "estarían sincopando",
		},
		Future: {
			yo: "estaré sincopando",
			tú: "estarás sincopando",
			Ud: "estará sincopando",
			nosotros: "estaremos sincopando",
			vosotros: "estaréis sincopando",
			Uds: "estarán sincopando",
		},
	},
	Perfect: {
		Present: {
			yo: "he sincopado",
			tú: "has sincopado",
			Ud: "ha sincopado",
			nosotros: "hemos sincopado",
			vosotros: "habéis sincopado",
			Uds: "han sincopado",
		},
		Preterite: {
			yo: "hube sincopado",
			tú: "hubiste sincopado",
			Ud: "hubo sincopado",
			nosotros: "hubimos sincopado",
			vosotros: "hubisteis sincopado",
			Uds: "hubieron sincopado",
		},
		Past: {
			yo: "había sincopado",
			tú: "habías sincopado",
			Ud: "había sincopado",
			nosotros: "habíamos sincopado",
			vosotros: "habíais sincopado",
			Uds: "habían sincopado",
		},
		Conditional: {
			yo: "habría sincopado",
			tú: "habrías sincopado",
			Ud: "habría sincopado",
			nosotros: "habríamos sincopado",
			vosotros: "habríais sincopado",
			Uds: "habrían sincopado",
		},
		Future: {
			yo: "habré sincopado",
			tú: "habrás sincopado",
			Ud: "habrá sincopado",
			nosotros: "habremos sincopado",
			vosotros: "habréis sincopado",
			Uds: "habrán sincopado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya sincopado",
			tú: "hayas sincopado",
			Ud: "haya sincopado",
			nosotros: "hayamos sincopado",
			vosotros: "hayáis sincopado",
			Uds: "hayan sincopado",
		},
		Past: {
			yo: "hubiera sincopado",
			tú: "hubieras sincopado",
			Ud: "hubiera sincopado",
			nosotros: "hubiéramos sincopado",
			vosotros: "hubierais sincopado",
			Uds: "hubieran sincopado",
		},
		Future: {
			yo: "hubiere sincopado",
			tú: "hubieres sincopado",
			Ud: "hubiere sincopado",
			nosotros: "hubiéremos sincopado",
			vosotros: "hubiereis sincopado",
			Uds: "hubieren sincopado",
		},
	},
}
