var sobornar = {
	Indicative: {
		Present: {
			yo: "soborno",
			tú: "sobornas",
			Ud: "soborna",
			nosotros: "sobornamos",
			vosotros: "sobornáis",
			Uds: "sobornan",
		},
		Preterite: {
			yo: "soborné",
			tú: "sobornaste",
			Ud: "sobornó",
			nosotros: "sobornamos",
			vosotros: "sobornasteis",
			Uds: "sobornaron",
		},
		Imperfect: {
			yo: "sobornaba",
			tú: "sobornabas",
			Ud: "sobornaba",
			nosotros: "sobornábamos",
			vosotros: "sobornabais",
			Uds: "sobornaban",
		},
		Conditional: {
			yo: "sobornaría",
			tú: "sobornarías",
			Ud: "sobornaría",
			nosotros: "sobornaríamos",
			vosotros: "sobornaríais",
			Uds: "sobornarían",
		},
		Future: {
			yo: "sobornaré",
			tú: "sobornarás",
			Ud: "sobornará",
			nosotros: "sobornaremos",
			vosotros: "sobornaréis",
			Uds: "sobornarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "soborne",
			tú: "sobornes",
			Ud: "soborne",
			nosotros: "sobornemos",
			vosotros: "sobornéis",
			Uds: "sobornen",
		},
		Imperfect: {
			yo: "sobornara",
			tú: "sobornaras",
			Ud: "sobornara",
			nosotros: "sobornáramos",
			vosotros: "sobornarais",
			Uds: "sobornaran",
		},
		Imperfect2: {
			yo: "sobornase",
			tú: "sobornases",
			Ud: "sobornase",
			nosotros: "sobornásemos",
			vosotros: "sobornaseis",
			Uds: "sobornasen",
		},
		Future: {
			yo: "sobornare",
			tú: "sobornares",
			Ud: "sobornare",
			nosotros: "sobornáremos",
			vosotros: "sobornareis",
			Uds: "sobornaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "soborna",
			Ud: "soborne",
			nosotros: "sobornemos",
			vosotros: "sobornad",
			Uds: "sobornen",
		},
		Negative: {
			tú: "no sobornes",
			Ud: "no soborne",
			nosotros: "no sobornemos",
			vosotros: "no sobornéis",
			Uds: "no sobornen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy sobornando",
			tú: "estás sobornando",
			Ud: "está sobornando",
			nosotros: "estamos sobornando",
			vosotros: "estáis sobornando",
			Uds: "están sobornando",
		},
		Preterite: {
			yo: "estuve sobornando",
			tú: "estuviste sobornando",
			Ud: "estuvo sobornando",
			nosotros: "estuvimos sobornando",
			vosotros: "estuvisteis sobornando",
			Uds: "estuvieron sobornando",
		},
		Imperfect: {
			Uds: "estaban sobornando",
			yo: "estaba sobornando",
			tú: "estabas sobornando",
			Ud: "estaba sobornando",
			nosotros: "estábamos sobornando",
			vosotros: "estabais sobornando",
		},
		Conditional: {
			yo: "estaría sobornando",
			tú: "estarías sobornando",
			Ud: "estaría sobornando",
			nosotros: "estaríamos sobornando",
			vosotros: "estaríais sobornando",
			Uds: "estarían sobornando",
		},
		Future: {
			yo: "estaré sobornando",
			tú: "estarás sobornando",
			Ud: "estará sobornando",
			nosotros: "estaremos sobornando",
			vosotros: "estaréis sobornando",
			Uds: "estarán sobornando",
		},
	},
	Perfect: {
		Present: {
			yo: "he sobornado",
			tú: "has sobornado",
			Ud: "ha sobornado",
			nosotros: "hemos sobornado",
			vosotros: "habéis sobornado",
			Uds: "han sobornado",
		},
		Preterite: {
			yo: "hube sobornado",
			tú: "hubiste sobornado",
			Ud: "hubo sobornado",
			nosotros: "hubimos sobornado",
			vosotros: "hubisteis sobornado",
			Uds: "hubieron sobornado",
		},
		Past: {
			yo: "había sobornado",
			tú: "habías sobornado",
			Ud: "había sobornado",
			nosotros: "habíamos sobornado",
			vosotros: "habíais sobornado",
			Uds: "habían sobornado",
		},
		Conditional: {
			yo: "habría sobornado",
			tú: "habrías sobornado",
			Ud: "habría sobornado",
			nosotros: "habríamos sobornado",
			vosotros: "habríais sobornado",
			Uds: "habrían sobornado",
		},
		Future: {
			yo: "habré sobornado",
			tú: "habrás sobornado",
			Ud: "habrá sobornado",
			nosotros: "habremos sobornado",
			vosotros: "habréis sobornado",
			Uds: "habrán sobornado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya sobornado",
			tú: "hayas sobornado",
			Ud: "haya sobornado",
			nosotros: "hayamos sobornado",
			vosotros: "hayáis sobornado",
			Uds: "hayan sobornado",
		},
		Past: {
			yo: "hubiera sobornado",
			tú: "hubieras sobornado",
			Ud: "hubiera sobornado",
			nosotros: "hubiéramos sobornado",
			vosotros: "hubierais sobornado",
			Uds: "hubieran sobornado",
		},
		Future: {
			yo: "hubiere sobornado",
			tú: "hubieres sobornado",
			Ud: "hubiere sobornado",
			nosotros: "hubiéremos sobornado",
			vosotros: "hubiereis sobornado",
			Uds: "hubieren sobornado",
		},
	},
}
