var sobrellevar = {
	Indicative: {
		Present: {
			yo: "sobrellevo",
			tú: "sobrellevas",
			Ud: "sobrelleva",
			nosotros: "sobrellevamos",
			vosotros: "sobrelleváis",
			Uds: "sobrellevan",
		},
		Preterite: {
			yo: "sobrellevé",
			tú: "sobrellevaste",
			Ud: "sobrellevó",
			nosotros: "sobrellevamos",
			vosotros: "sobrellevasteis",
			Uds: "sobrellevaron",
		},
		Imperfect: {
			yo: "sobrellevaba",
			tú: "sobrellevabas",
			Ud: "sobrellevaba",
			nosotros: "sobrellevábamos",
			vosotros: "sobrellevabais",
			Uds: "sobrellevaban",
		},
		Conditional: {
			yo: "sobrellevaría",
			tú: "sobrellevarías",
			Ud: "sobrellevaría",
			nosotros: "sobrellevaríamos",
			vosotros: "sobrellevaríais",
			Uds: "sobrellevarían",
		},
		Future: {
			yo: "sobrellevaré",
			tú: "sobrellevarás",
			Ud: "sobrellevará",
			nosotros: "sobrellevaremos",
			vosotros: "sobrellevaréis",
			Uds: "sobrellevarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "sobrelleve",
			tú: "sobrelleves",
			Ud: "sobrelleve",
			nosotros: "sobrellevemos",
			vosotros: "sobrellevéis",
			Uds: "sobrelleven",
		},
		Imperfect: {
			yo: "sobrellevara",
			tú: "sobrellevaras",
			Ud: "sobrellevara",
			nosotros: "sobrelleváramos",
			vosotros: "sobrellevarais",
			Uds: "sobrellevaran",
		},
		Imperfect2: {
			yo: "sobrellevase",
			tú: "sobrellevases",
			Ud: "sobrellevase",
			nosotros: "sobrellevásemos",
			vosotros: "sobrellevaseis",
			Uds: "sobrellevasen",
		},
		Future: {
			yo: "sobrellevare",
			tú: "sobrellevares",
			Ud: "sobrellevare",
			nosotros: "sobrelleváremos",
			vosotros: "sobrellevareis",
			Uds: "sobrellevaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "sobrelleva",
			Ud: "sobrelleve",
			nosotros: "sobrellevemos",
			vosotros: "sobrellevad",
			Uds: "sobrelleven",
		},
		Negative: {
			tú: "no sobrelleves",
			Ud: "no sobrelleve",
			nosotros: "no sobrellevemos",
			vosotros: "no sobrellevéis",
			Uds: "no sobrelleven",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy sobrellevando",
			tú: "estás sobrellevando",
			Ud: "está sobrellevando",
			nosotros: "estamos sobrellevando",
			vosotros: "estáis sobrellevando",
			Uds: "están sobrellevando",
		},
		Preterite: {
			yo: "estuve sobrellevando",
			tú: "estuviste sobrellevando",
			Ud: "estuvo sobrellevando",
			nosotros: "estuvimos sobrellevando",
			vosotros: "estuvisteis sobrellevando",
			Uds: "estuvieron sobrellevando",
		},
		Imperfect: {
			Uds: "estaban sobrellevando",
			yo: "estaba sobrellevando",
			tú: "estabas sobrellevando",
			Ud: "estaba sobrellevando",
			nosotros: "estábamos sobrellevando",
			vosotros: "estabais sobrellevando",
		},
		Conditional: {
			yo: "estaría sobrellevando",
			tú: "estarías sobrellevando",
			Ud: "estaría sobrellevando",
			nosotros: "estaríamos sobrellevando",
			vosotros: "estaríais sobrellevando",
			Uds: "estarían sobrellevando",
		},
		Future: {
			yo: "estaré sobrellevando",
			tú: "estarás sobrellevando",
			Ud: "estará sobrellevando",
			nosotros: "estaremos sobrellevando",
			vosotros: "estaréis sobrellevando",
			Uds: "estarán sobrellevando",
		},
	},
	Perfect: {
		Present: {
			yo: "he sobrellevado",
			tú: "has sobrellevado",
			Ud: "ha sobrellevado",
			nosotros: "hemos sobrellevado",
			vosotros: "habéis sobrellevado",
			Uds: "han sobrellevado",
		},
		Preterite: {
			yo: "hube sobrellevado",
			tú: "hubiste sobrellevado",
			Ud: "hubo sobrellevado",
			nosotros: "hubimos sobrellevado",
			vosotros: "hubisteis sobrellevado",
			Uds: "hubieron sobrellevado",
		},
		Past: {
			yo: "había sobrellevado",
			tú: "habías sobrellevado",
			Ud: "había sobrellevado",
			nosotros: "habíamos sobrellevado",
			vosotros: "habíais sobrellevado",
			Uds: "habían sobrellevado",
		},
		Conditional: {
			yo: "habría sobrellevado",
			tú: "habrías sobrellevado",
			Ud: "habría sobrellevado",
			nosotros: "habríamos sobrellevado",
			vosotros: "habríais sobrellevado",
			Uds: "habrían sobrellevado",
		},
		Future: {
			yo: "habré sobrellevado",
			tú: "habrás sobrellevado",
			Ud: "habrá sobrellevado",
			nosotros: "habremos sobrellevado",
			vosotros: "habréis sobrellevado",
			Uds: "habrán sobrellevado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya sobrellevado",
			tú: "hayas sobrellevado",
			Ud: "haya sobrellevado",
			nosotros: "hayamos sobrellevado",
			vosotros: "hayáis sobrellevado",
			Uds: "hayan sobrellevado",
		},
		Past: {
			yo: "hubiera sobrellevado",
			tú: "hubieras sobrellevado",
			Ud: "hubiera sobrellevado",
			nosotros: "hubiéramos sobrellevado",
			vosotros: "hubierais sobrellevado",
			Uds: "hubieran sobrellevado",
		},
		Future: {
			yo: "hubiere sobrellevado",
			tú: "hubieres sobrellevado",
			Ud: "hubiere sobrellevado",
			nosotros: "hubiéremos sobrellevado",
			vosotros: "hubiereis sobrellevado",
			Uds: "hubieren sobrellevado",
		},
	},
}
