var sobrar = {
	Indicative: {
		Present: {
			yo: "sobro",
			tú: "sobras",
			Ud: "sobra",
			nosotros: "sobramos",
			vosotros: "sobráis",
			Uds: "sobran",
		},
		Preterite: {
			yo: "sobré",
			tú: "sobraste",
			Ud: "sobró",
			nosotros: "sobramos",
			vosotros: "sobrasteis",
			Uds: "sobraron",
		},
		Imperfect: {
			yo: "sobraba",
			tú: "sobrabas",
			Ud: "sobraba",
			nosotros: "sobrábamos",
			vosotros: "sobrabais",
			Uds: "sobraban",
		},
		Conditional: {
			yo: "sobraría",
			tú: "sobrarías",
			Ud: "sobraría",
			nosotros: "sobraríamos",
			vosotros: "sobraríais",
			Uds: "sobrarían",
		},
		Future: {
			yo: "sobraré",
			tú: "sobrarás",
			Ud: "sobrará",
			nosotros: "sobraremos",
			vosotros: "sobraréis",
			Uds: "sobrarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "sobre",
			tú: "sobres",
			Ud: "sobre",
			nosotros: "sobremos",
			vosotros: "sobréis",
			Uds: "sobren",
		},
		Imperfect: {
			yo: "sobrara",
			tú: "sobraras",
			Ud: "sobrara",
			nosotros: "sobráramos",
			vosotros: "sobrarais",
			Uds: "sobraran",
		},
		Imperfect2: {
			yo: "sobrase",
			tú: "sobrases",
			Ud: "sobrase",
			nosotros: "sobrásemos",
			vosotros: "sobraseis",
			Uds: "sobrasen",
		},
		Future: {
			yo: "sobrare",
			tú: "sobrares",
			Ud: "sobrare",
			nosotros: "sobráremos",
			vosotros: "sobrareis",
			Uds: "sobraren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "sobra",
			Ud: "sobre",
			nosotros: "sobremos",
			vosotros: "sobrad",
			Uds: "sobren",
		},
		Negative: {
			tú: "no sobres",
			Ud: "no sobre",
			nosotros: "no sobremos",
			vosotros: "no sobréis",
			Uds: "no sobren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy sobrando",
			tú: "estás sobrando",
			Ud: "está sobrando",
			nosotros: "estamos sobrando",
			vosotros: "estáis sobrando",
			Uds: "están sobrando",
		},
		Preterite: {
			yo: "estuve sobrando",
			tú: "estuviste sobrando",
			Ud: "estuvo sobrando",
			nosotros: "estuvimos sobrando",
			vosotros: "estuvisteis sobrando",
			Uds: "estuvieron sobrando",
		},
		Imperfect: {
			Uds: "estaban sobrando",
			yo: "estaba sobrando",
			tú: "estabas sobrando",
			Ud: "estaba sobrando",
			nosotros: "estábamos sobrando",
			vosotros: "estabais sobrando",
		},
		Conditional: {
			yo: "estaría sobrando",
			tú: "estarías sobrando",
			Ud: "estaría sobrando",
			nosotros: "estaríamos sobrando",
			vosotros: "estaríais sobrando",
			Uds: "estarían sobrando",
		},
		Future: {
			yo: "estaré sobrando",
			tú: "estarás sobrando",
			Ud: "estará sobrando",
			nosotros: "estaremos sobrando",
			vosotros: "estaréis sobrando",
			Uds: "estarán sobrando",
		},
	},
	Perfect: {
		Present: {
			yo: "he sobrado",
			tú: "has sobrado",
			Ud: "ha sobrado",
			nosotros: "hemos sobrado",
			vosotros: "habéis sobrado",
			Uds: "han sobrado",
		},
		Preterite: {
			yo: "hube sobrado",
			tú: "hubiste sobrado",
			Ud: "hubo sobrado",
			nosotros: "hubimos sobrado",
			vosotros: "hubisteis sobrado",
			Uds: "hubieron sobrado",
		},
		Past: {
			yo: "había sobrado",
			tú: "habías sobrado",
			Ud: "había sobrado",
			nosotros: "habíamos sobrado",
			vosotros: "habíais sobrado",
			Uds: "habían sobrado",
		},
		Conditional: {
			yo: "habría sobrado",
			tú: "habrías sobrado",
			Ud: "habría sobrado",
			nosotros: "habríamos sobrado",
			vosotros: "habríais sobrado",
			Uds: "habrían sobrado",
		},
		Future: {
			yo: "habré sobrado",
			tú: "habrás sobrado",
			Ud: "habrá sobrado",
			nosotros: "habremos sobrado",
			vosotros: "habréis sobrado",
			Uds: "habrán sobrado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya sobrado",
			tú: "hayas sobrado",
			Ud: "haya sobrado",
			nosotros: "hayamos sobrado",
			vosotros: "hayáis sobrado",
			Uds: "hayan sobrado",
		},
		Past: {
			yo: "hubiera sobrado",
			tú: "hubieras sobrado",
			Ud: "hubiera sobrado",
			nosotros: "hubiéramos sobrado",
			vosotros: "hubierais sobrado",
			Uds: "hubieran sobrado",
		},
		Future: {
			yo: "hubiere sobrado",
			tú: "hubieres sobrado",
			Ud: "hubiere sobrado",
			nosotros: "hubiéremos sobrado",
			vosotros: "hubiereis sobrado",
			Uds: "hubieren sobrado",
		},
	},
}
