var socavar = {
	Indicative: {
		Present: {
			yo: "socavo",
			tú: "socavas",
			Ud: "socava",
			nosotros: "socavamos",
			vosotros: "socaváis",
			Uds: "socavan",
		},
		Preterite: {
			yo: "socavé",
			tú: "socavaste",
			Ud: "socavó",
			nosotros: "socavamos",
			vosotros: "socavasteis",
			Uds: "socavaron",
		},
		Imperfect: {
			yo: "socavaba",
			tú: "socavabas",
			Ud: "socavaba",
			nosotros: "socavábamos",
			vosotros: "socavabais",
			Uds: "socavaban",
		},
		Conditional: {
			yo: "socavaría",
			tú: "socavarías",
			Ud: "socavaría",
			nosotros: "socavaríamos",
			vosotros: "socavaríais",
			Uds: "socavarían",
		},
		Future: {
			yo: "socavaré",
			tú: "socavarás",
			Ud: "socavará",
			nosotros: "socavaremos",
			vosotros: "socavaréis",
			Uds: "socavarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "socave",
			tú: "socaves",
			Ud: "socave",
			nosotros: "socavemos",
			vosotros: "socavéis",
			Uds: "socaven",
		},
		Imperfect: {
			yo: "socavara",
			tú: "socavaras",
			Ud: "socavara",
			nosotros: "socaváramos",
			vosotros: "socavarais",
			Uds: "socavaran",
		},
		Imperfect2: {
			yo: "socavase",
			tú: "socavases",
			Ud: "socavase",
			nosotros: "socavásemos",
			vosotros: "socavaseis",
			Uds: "socavasen",
		},
		Future: {
			yo: "socavare",
			tú: "socavares",
			Ud: "socavare",
			nosotros: "socaváremos",
			vosotros: "socavareis",
			Uds: "socavaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "socava",
			Ud: "socave",
			nosotros: "socavemos",
			vosotros: "socavad",
			Uds: "socaven",
		},
		Negative: {
			tú: "no socaves",
			Ud: "no socave",
			nosotros: "no socavemos",
			vosotros: "no socavéis",
			Uds: "no socaven",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy socavando",
			tú: "estás socavando",
			Ud: "está socavando",
			nosotros: "estamos socavando",
			vosotros: "estáis socavando",
			Uds: "están socavando",
		},
		Preterite: {
			yo: "estuve socavando",
			tú: "estuviste socavando",
			Ud: "estuvo socavando",
			nosotros: "estuvimos socavando",
			vosotros: "estuvisteis socavando",
			Uds: "estuvieron socavando",
		},
		Imperfect: {
			Uds: "estaban socavando",
			yo: "estaba socavando",
			tú: "estabas socavando",
			Ud: "estaba socavando",
			nosotros: "estábamos socavando",
			vosotros: "estabais socavando",
		},
		Conditional: {
			yo: "estaría socavando",
			tú: "estarías socavando",
			Ud: "estaría socavando",
			nosotros: "estaríamos socavando",
			vosotros: "estaríais socavando",
			Uds: "estarían socavando",
		},
		Future: {
			yo: "estaré socavando",
			tú: "estarás socavando",
			Ud: "estará socavando",
			nosotros: "estaremos socavando",
			vosotros: "estaréis socavando",
			Uds: "estarán socavando",
		},
	},
	Perfect: {
		Present: {
			yo: "he socavado",
			tú: "has socavado",
			Ud: "ha socavado",
			nosotros: "hemos socavado",
			vosotros: "habéis socavado",
			Uds: "han socavado",
		},
		Preterite: {
			yo: "hube socavado",
			tú: "hubiste socavado",
			Ud: "hubo socavado",
			nosotros: "hubimos socavado",
			vosotros: "hubisteis socavado",
			Uds: "hubieron socavado",
		},
		Past: {
			yo: "había socavado",
			tú: "habías socavado",
			Ud: "había socavado",
			nosotros: "habíamos socavado",
			vosotros: "habíais socavado",
			Uds: "habían socavado",
		},
		Conditional: {
			yo: "habría socavado",
			tú: "habrías socavado",
			Ud: "habría socavado",
			nosotros: "habríamos socavado",
			vosotros: "habríais socavado",
			Uds: "habrían socavado",
		},
		Future: {
			yo: "habré socavado",
			tú: "habrás socavado",
			Ud: "habrá socavado",
			nosotros: "habremos socavado",
			vosotros: "habréis socavado",
			Uds: "habrán socavado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya socavado",
			tú: "hayas socavado",
			Ud: "haya socavado",
			nosotros: "hayamos socavado",
			vosotros: "hayáis socavado",
			Uds: "hayan socavado",
		},
		Past: {
			yo: "hubiera socavado",
			tú: "hubieras socavado",
			Ud: "hubiera socavado",
			nosotros: "hubiéramos socavado",
			vosotros: "hubierais socavado",
			Uds: "hubieran socavado",
		},
		Future: {
			yo: "hubiere socavado",
			tú: "hubieres socavado",
			Ud: "hubiere socavado",
			nosotros: "hubiéremos socavado",
			vosotros: "hubiereis socavado",
			Uds: "hubieren socavado",
		},
	},
}
