var soler = {
	Indicative: {
		Present: {
			yo: "suelo",
			tú: "sueles",
			Ud: "suele",
			nosotros: "solemos",
			vosotros: "soléis",
			Uds: "suelen",
		},
		Preterite: {
			yo: "solí",
			tú: "soliste",
			Ud: "solió",
			nosotros: "solimos",
			vosotros: "solisteis",
			Uds: "solieron",
		},
		Imperfect: {
			yo: "solía",
			tú: "solías",
			Ud: "solía",
			nosotros: "solíamos",
			vosotros: "solíais",
			Uds: "solían",
		},
		Conditional: {
			yo: "solería",
			tú: "solerías",
			Ud: "solería",
			nosotros: "soleríamos",
			vosotros: "soleríais",
			Uds: "solerían",
		},
		Future: {
			yo: "soleré",
			tú: "solerás",
			Ud: "solerá",
			nosotros: "soleremos",
			vosotros: "soleréis",
			Uds: "solerán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "suela",
			tú: "suelas",
			Ud: "suela",
			nosotros: "solamos",
			vosotros: "soláis",
			Uds: "suelan",
		},
		Imperfect: {
			yo: "soliera",
			tú: "solieras",
			Ud: "soliera",
			nosotros: "soliéramos",
			vosotros: "solierais",
			Uds: "solieran",
		},
		Imperfect2: {
			yo: "soliese",
			tú: "solieses",
			Ud: "soliese",
			nosotros: "soliésemos",
			vosotros: "solieseis",
			Uds: "soliesen",
		},
		Future: {
			yo: "soliere",
			tú: "solieres",
			Ud: "soliere",
			nosotros: "soliéremos",
			vosotros: "soliereis",
			Uds: "solieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "suele",
			Ud: "suela",
			nosotros: "solamos",
			vosotros: "soled",
			Uds: "suelan",
		},
		Negative: {
			tú: "no suelas",
			Ud: "no suela",
			nosotros: "no solamos",
			vosotros: "no soláis",
			Uds: "no suelan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy soliendo",
			tú: "estás soliendo",
			Ud: "está soliendo",
			nosotros: "estamos soliendo",
			vosotros: "estáis soliendo",
			Uds: "están soliendo",
		},
		Preterite: {
			yo: "estuve soliendo",
			tú: "estuviste soliendo",
			Ud: "estuvo soliendo",
			nosotros: "estuvimos soliendo",
			vosotros: "estuvisteis soliendo",
			Uds: "estuvieron soliendo",
		},
		Imperfect: {
			Uds: "estaban soliendo",
			yo: "estaba soliendo",
			tú: "estabas soliendo",
			Ud: "estaba soliendo",
			nosotros: "estábamos soliendo",
			vosotros: "estabais soliendo",
		},
		Conditional: {
			yo: "estaría soliendo",
			tú: "estarías soliendo",
			Ud: "estaría soliendo",
			nosotros: "estaríamos soliendo",
			vosotros: "estaríais soliendo",
			Uds: "estarían soliendo",
		},
		Future: {
			yo: "estaré soliendo",
			tú: "estarás soliendo",
			Ud: "estará soliendo",
			nosotros: "estaremos soliendo",
			vosotros: "estaréis soliendo",
			Uds: "estarán soliendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he solido",
			tú: "has solido",
			Ud: "ha solido",
			nosotros: "hemos solido",
			vosotros: "habéis solido",
			Uds: "han solido",
		},
		Preterite: {
			yo: "hube solido",
			tú: "hubiste solido",
			Ud: "hubo solido",
			nosotros: "hubimos solido",
			vosotros: "hubisteis solido",
			Uds: "hubieron solido",
		},
		Past: {
			yo: "había solido",
			tú: "habías solido",
			Ud: "había solido",
			nosotros: "habíamos solido",
			vosotros: "habíais solido",
			Uds: "habían solido",
		},
		Conditional: {
			yo: "habría solido",
			tú: "habrías solido",
			Ud: "habría solido",
			nosotros: "habríamos solido",
			vosotros: "habríais solido",
			Uds: "habrían solido",
		},
		Future: {
			yo: "habré solido",
			tú: "habrás solido",
			Ud: "habrá solido",
			nosotros: "habremos solido",
			vosotros: "habréis solido",
			Uds: "habrán solido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya solido",
			tú: "hayas solido",
			Ud: "haya solido",
			nosotros: "hayamos solido",
			vosotros: "hayáis solido",
			Uds: "hayan solido",
		},
		Past: {
			yo: "hubiera solido",
			tú: "hubieras solido",
			Ud: "hubiera solido",
			nosotros: "hubiéramos solido",
			vosotros: "hubierais solido",
			Uds: "hubieran solido",
		},
		Future: {
			yo: "hubiere solido",
			tú: "hubieres solido",
			Ud: "hubiere solido",
			nosotros: "hubiéremos solido",
			vosotros: "hubiereis solido",
			Uds: "hubieren solido",
		},
	},
}
