var sonar = {
	Indicative: {
		Present: {
			yo: "sueno",
			tú: "suenas",
			Ud: "suena",
			nosotros: "sonamos",
			vosotros: "sonáis",
			Uds: "suenan",
		},
		Preterite: {
			yo: "soné",
			tú: "sonaste",
			Ud: "sonó",
			nosotros: "sonamos",
			vosotros: "sonasteis",
			Uds: "sonaron",
		},
		Imperfect: {
			yo: "sonaba",
			tú: "sonabas",
			Ud: "sonaba",
			nosotros: "sonábamos",
			vosotros: "sonabais",
			Uds: "sonaban",
		},
		Conditional: {
			yo: "sonaría",
			tú: "sonarías",
			Ud: "sonaría",
			nosotros: "sonaríamos",
			vosotros: "sonaríais",
			Uds: "sonarían",
		},
		Future: {
			yo: "sonaré",
			tú: "sonarás",
			Ud: "sonará",
			nosotros: "sonaremos",
			vosotros: "sonaréis",
			Uds: "sonarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "suene",
			tú: "suenes",
			Ud: "suene",
			nosotros: "sonemos",
			vosotros: "sonéis",
			Uds: "suenen",
		},
		Imperfect: {
			yo: "sonara",
			tú: "sonaras",
			Ud: "sonara",
			nosotros: "sonáramos",
			vosotros: "sonarais",
			Uds: "sonaran",
		},
		Imperfect2: {
			yo: "sonase",
			tú: "sonases",
			Ud: "sonase",
			nosotros: "sonásemos",
			vosotros: "sonaseis",
			Uds: "sonasen",
		},
		Future: {
			yo: "sonare",
			tú: "sonares",
			Ud: "sonare",
			nosotros: "sonáremos",
			vosotros: "sonareis",
			Uds: "sonaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "suena",
			Ud: "suene",
			nosotros: "sonemos",
			vosotros: "sonad",
			Uds: "suenen",
		},
		Negative: {
			tú: "no suenes",
			Ud: "no suene",
			nosotros: "no sonemos",
			vosotros: "no sonéis",
			Uds: "no suenen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy sonando",
			tú: "estás sonando",
			Ud: "está sonando",
			nosotros: "estamos sonando",
			vosotros: "estáis sonando",
			Uds: "están sonando",
		},
		Preterite: {
			yo: "estuve sonando",
			tú: "estuviste sonando",
			Ud: "estuvo sonando",
			nosotros: "estuvimos sonando",
			vosotros: "estuvisteis sonando",
			Uds: "estuvieron sonando",
		},
		Imperfect: {
			Uds: "estaban sonando",
			yo: "estaba sonando",
			tú: "estabas sonando",
			Ud: "estaba sonando",
			nosotros: "estábamos sonando",
			vosotros: "estabais sonando",
		},
		Conditional: {
			yo: "estaría sonando",
			tú: "estarías sonando",
			Ud: "estaría sonando",
			nosotros: "estaríamos sonando",
			vosotros: "estaríais sonando",
			Uds: "estarían sonando",
		},
		Future: {
			yo: "estaré sonando",
			tú: "estarás sonando",
			Ud: "estará sonando",
			nosotros: "estaremos sonando",
			vosotros: "estaréis sonando",
			Uds: "estarán sonando",
		},
	},
	Perfect: {
		Present: {
			yo: "he sonado",
			tú: "has sonado",
			Ud: "ha sonado",
			nosotros: "hemos sonado",
			vosotros: "habéis sonado",
			Uds: "han sonado",
		},
		Preterite: {
			yo: "hube sonado",
			tú: "hubiste sonado",
			Ud: "hubo sonado",
			nosotros: "hubimos sonado",
			vosotros: "hubisteis sonado",
			Uds: "hubieron sonado",
		},
		Past: {
			yo: "había sonado",
			tú: "habías sonado",
			Ud: "había sonado",
			nosotros: "habíamos sonado",
			vosotros: "habíais sonado",
			Uds: "habían sonado",
		},
		Conditional: {
			yo: "habría sonado",
			tú: "habrías sonado",
			Ud: "habría sonado",
			nosotros: "habríamos sonado",
			vosotros: "habríais sonado",
			Uds: "habrían sonado",
		},
		Future: {
			yo: "habré sonado",
			tú: "habrás sonado",
			Ud: "habrá sonado",
			nosotros: "habremos sonado",
			vosotros: "habréis sonado",
			Uds: "habrán sonado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya sonado",
			tú: "hayas sonado",
			Ud: "haya sonado",
			nosotros: "hayamos sonado",
			vosotros: "hayáis sonado",
			Uds: "hayan sonado",
		},
		Past: {
			yo: "hubiera sonado",
			tú: "hubieras sonado",
			Ud: "hubiera sonado",
			nosotros: "hubiéramos sonado",
			vosotros: "hubierais sonado",
			Uds: "hubieran sonado",
		},
		Future: {
			yo: "hubiere sonado",
			tú: "hubieres sonado",
			Ud: "hubiere sonado",
			nosotros: "hubiéremos sonado",
			vosotros: "hubiereis sonado",
			Uds: "hubieren sonado",
		},
	},
}
