var soportar = {
	Indicative: {
		Present: {
			yo: "soporto",
			tú: "soportas",
			Ud: "soporta",
			nosotros: "soportamos",
			vosotros: "soportáis",
			Uds: "soportan",
		},
		Preterite: {
			yo: "soporté",
			tú: "soportaste",
			Ud: "soportó",
			nosotros: "soportamos",
			vosotros: "soportasteis",
			Uds: "soportaron",
		},
		Imperfect: {
			yo: "soportaba",
			tú: "soportabas",
			Ud: "soportaba",
			nosotros: "soportábamos",
			vosotros: "soportabais",
			Uds: "soportaban",
		},
		Conditional: {
			yo: "soportaría",
			tú: "soportarías",
			Ud: "soportaría",
			nosotros: "soportaríamos",
			vosotros: "soportaríais",
			Uds: "soportarían",
		},
		Future: {
			yo: "soportaré",
			tú: "soportarás",
			Ud: "soportará",
			nosotros: "soportaremos",
			vosotros: "soportaréis",
			Uds: "soportarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "soporte",
			tú: "soportes",
			Ud: "soporte",
			nosotros: "soportemos",
			vosotros: "soportéis",
			Uds: "soporten",
		},
		Imperfect: {
			yo: "soportara",
			tú: "soportaras",
			Ud: "soportara",
			nosotros: "soportáramos",
			vosotros: "soportarais",
			Uds: "soportaran",
		},
		Imperfect2: {
			yo: "soportase",
			tú: "soportases",
			Ud: "soportase",
			nosotros: "soportásemos",
			vosotros: "soportaseis",
			Uds: "soportasen",
		},
		Future: {
			yo: "soportare",
			tú: "soportares",
			Ud: "soportare",
			nosotros: "soportáremos",
			vosotros: "soportareis",
			Uds: "soportaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "soporta",
			Ud: "soporte",
			nosotros: "soportemos",
			vosotros: "soportad",
			Uds: "soporten",
		},
		Negative: {
			tú: "no soportes",
			Ud: "no soporte",
			nosotros: "no soportemos",
			vosotros: "no soportéis",
			Uds: "no soporten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy soportando",
			tú: "estás soportando",
			Ud: "está soportando",
			nosotros: "estamos soportando",
			vosotros: "estáis soportando",
			Uds: "están soportando",
		},
		Preterite: {
			yo: "estuve soportando",
			tú: "estuviste soportando",
			Ud: "estuvo soportando",
			nosotros: "estuvimos soportando",
			vosotros: "estuvisteis soportando",
			Uds: "estuvieron soportando",
		},
		Imperfect: {
			Uds: "estaban soportando",
			yo: "estaba soportando",
			tú: "estabas soportando",
			Ud: "estaba soportando",
			nosotros: "estábamos soportando",
			vosotros: "estabais soportando",
		},
		Conditional: {
			yo: "estaría soportando",
			tú: "estarías soportando",
			Ud: "estaría soportando",
			nosotros: "estaríamos soportando",
			vosotros: "estaríais soportando",
			Uds: "estarían soportando",
		},
		Future: {
			yo: "estaré soportando",
			tú: "estarás soportando",
			Ud: "estará soportando",
			nosotros: "estaremos soportando",
			vosotros: "estaréis soportando",
			Uds: "estarán soportando",
		},
	},
	Perfect: {
		Present: {
			yo: "he soportado",
			tú: "has soportado",
			Ud: "ha soportado",
			nosotros: "hemos soportado",
			vosotros: "habéis soportado",
			Uds: "han soportado",
		},
		Preterite: {
			yo: "hube soportado",
			tú: "hubiste soportado",
			Ud: "hubo soportado",
			nosotros: "hubimos soportado",
			vosotros: "hubisteis soportado",
			Uds: "hubieron soportado",
		},
		Past: {
			yo: "había soportado",
			tú: "habías soportado",
			Ud: "había soportado",
			nosotros: "habíamos soportado",
			vosotros: "habíais soportado",
			Uds: "habían soportado",
		},
		Conditional: {
			yo: "habría soportado",
			tú: "habrías soportado",
			Ud: "habría soportado",
			nosotros: "habríamos soportado",
			vosotros: "habríais soportado",
			Uds: "habrían soportado",
		},
		Future: {
			yo: "habré soportado",
			tú: "habrás soportado",
			Ud: "habrá soportado",
			nosotros: "habremos soportado",
			vosotros: "habréis soportado",
			Uds: "habrán soportado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya soportado",
			tú: "hayas soportado",
			Ud: "haya soportado",
			nosotros: "hayamos soportado",
			vosotros: "hayáis soportado",
			Uds: "hayan soportado",
		},
		Past: {
			yo: "hubiera soportado",
			tú: "hubieras soportado",
			Ud: "hubiera soportado",
			nosotros: "hubiéramos soportado",
			vosotros: "hubierais soportado",
			Uds: "hubieran soportado",
		},
		Future: {
			yo: "hubiere soportado",
			tú: "hubieres soportado",
			Ud: "hubiere soportado",
			nosotros: "hubiéremos soportado",
			vosotros: "hubiereis soportado",
			Uds: "hubieren soportado",
		},
	},
}
