var sorber = {
	Indicative: {
		Present: {
			yo: "sorbo",
			tú: "sorbes",
			Ud: "sorbe",
			nosotros: "sorbemos",
			vosotros: "sorbéis",
			Uds: "sorben",
		},
		Preterite: {
			yo: "sorbí",
			tú: "sorbiste",
			Ud: "sorbió",
			nosotros: "sorbimos",
			vosotros: "sorbisteis",
			Uds: "sorbieron",
		},
		Imperfect: {
			yo: "sorbía",
			tú: "sorbías",
			Ud: "sorbía",
			nosotros: "sorbíamos",
			vosotros: "sorbíais",
			Uds: "sorbían",
		},
		Conditional: {
			yo: "sorbería",
			tú: "sorberías",
			Ud: "sorbería",
			nosotros: "sorberíamos",
			vosotros: "sorberíais",
			Uds: "sorberían",
		},
		Future: {
			yo: "sorberé",
			tú: "sorberás",
			Ud: "sorberá",
			nosotros: "sorberemos",
			vosotros: "sorberéis",
			Uds: "sorberán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "sorba",
			tú: "sorbas",
			Ud: "sorba",
			nosotros: "sorbamos",
			vosotros: "sorbáis",
			Uds: "sorban",
		},
		Imperfect: {
			yo: "sorbiera",
			tú: "sorbieras",
			Ud: "sorbiera",
			nosotros: "sorbiéramos",
			vosotros: "sorbierais",
			Uds: "sorbieran",
		},
		Imperfect2: {
			yo: "sorbiese",
			tú: "sorbieses",
			Ud: "sorbiese",
			nosotros: "sorbiésemos",
			vosotros: "sorbieseis",
			Uds: "sorbiesen",
		},
		Future: {
			yo: "sorbiere",
			tú: "sorbieres",
			Ud: "sorbiere",
			nosotros: "sorbiéremos",
			vosotros: "sorbiereis",
			Uds: "sorbieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "sorbe",
			Ud: "sorba",
			nosotros: "sorbamos",
			vosotros: "sorbed",
			Uds: "sorban",
		},
		Negative: {
			tú: "no sorbas",
			Ud: "no sorba",
			nosotros: "no sorbamos",
			vosotros: "no sorbáis",
			Uds: "no sorban",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy sorbiendo",
			tú: "estás sorbiendo",
			Ud: "está sorbiendo",
			nosotros: "estamos sorbiendo",
			vosotros: "estáis sorbiendo",
			Uds: "están sorbiendo",
		},
		Preterite: {
			yo: "estuve sorbiendo",
			tú: "estuviste sorbiendo",
			Ud: "estuvo sorbiendo",
			nosotros: "estuvimos sorbiendo",
			vosotros: "estuvisteis sorbiendo",
			Uds: "estuvieron sorbiendo",
		},
		Imperfect: {
			Uds: "estaban sorbiendo",
			yo: "estaba sorbiendo",
			tú: "estabas sorbiendo",
			Ud: "estaba sorbiendo",
			nosotros: "estábamos sorbiendo",
			vosotros: "estabais sorbiendo",
		},
		Conditional: {
			yo: "estaría sorbiendo",
			tú: "estarías sorbiendo",
			Ud: "estaría sorbiendo",
			nosotros: "estaríamos sorbiendo",
			vosotros: "estaríais sorbiendo",
			Uds: "estarían sorbiendo",
		},
		Future: {
			yo: "estaré sorbiendo",
			tú: "estarás sorbiendo",
			Ud: "estará sorbiendo",
			nosotros: "estaremos sorbiendo",
			vosotros: "estaréis sorbiendo",
			Uds: "estarán sorbiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he sorbido",
			tú: "has sorbido",
			Ud: "ha sorbido",
			nosotros: "hemos sorbido",
			vosotros: "habéis sorbido",
			Uds: "han sorbido",
		},
		Preterite: {
			yo: "hube sorbido",
			tú: "hubiste sorbido",
			Ud: "hubo sorbido",
			nosotros: "hubimos sorbido",
			vosotros: "hubisteis sorbido",
			Uds: "hubieron sorbido",
		},
		Past: {
			yo: "había sorbido",
			tú: "habías sorbido",
			Ud: "había sorbido",
			nosotros: "habíamos sorbido",
			vosotros: "habíais sorbido",
			Uds: "habían sorbido",
		},
		Conditional: {
			yo: "habría sorbido",
			tú: "habrías sorbido",
			Ud: "habría sorbido",
			nosotros: "habríamos sorbido",
			vosotros: "habríais sorbido",
			Uds: "habrían sorbido",
		},
		Future: {
			yo: "habré sorbido",
			tú: "habrás sorbido",
			Ud: "habrá sorbido",
			nosotros: "habremos sorbido",
			vosotros: "habréis sorbido",
			Uds: "habrán sorbido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya sorbido",
			tú: "hayas sorbido",
			Ud: "haya sorbido",
			nosotros: "hayamos sorbido",
			vosotros: "hayáis sorbido",
			Uds: "hayan sorbido",
		},
		Past: {
			yo: "hubiera sorbido",
			tú: "hubieras sorbido",
			Ud: "hubiera sorbido",
			nosotros: "hubiéramos sorbido",
			vosotros: "hubierais sorbido",
			Uds: "hubieran sorbido",
		},
		Future: {
			yo: "hubiere sorbido",
			tú: "hubieres sorbido",
			Ud: "hubiere sorbido",
			nosotros: "hubiéremos sorbido",
			vosotros: "hubiereis sorbido",
			Uds: "hubieren sorbido",
		},
	},
}
