var sospechar = {
	Indicative: {
		Present: {
			yo: "sospecho",
			tú: "sospechas",
			Ud: "sospecha",
			nosotros: "sospechamos",
			vosotros: "sospecháis",
			Uds: "sospechan",
		},
		Preterite: {
			yo: "sospeché",
			tú: "sospechaste",
			Ud: "sospechó",
			nosotros: "sospechamos",
			vosotros: "sospechasteis",
			Uds: "sospecharon",
		},
		Imperfect: {
			yo: "sospechaba",
			tú: "sospechabas",
			Ud: "sospechaba",
			nosotros: "sospechábamos",
			vosotros: "sospechabais",
			Uds: "sospechaban",
		},
		Conditional: {
			yo: "sospecharía",
			tú: "sospecharías",
			Ud: "sospecharía",
			nosotros: "sospecharíamos",
			vosotros: "sospecharíais",
			Uds: "sospecharían",
		},
		Future: {
			yo: "sospecharé",
			tú: "sospecharás",
			Ud: "sospechará",
			nosotros: "sospecharemos",
			vosotros: "sospecharéis",
			Uds: "sospecharán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "sospeche",
			tú: "sospeches",
			Ud: "sospeche",
			nosotros: "sospechemos",
			vosotros: "sospechéis",
			Uds: "sospechen",
		},
		Imperfect: {
			yo: "sospechara",
			tú: "sospecharas",
			Ud: "sospechara",
			nosotros: "sospecháramos",
			vosotros: "sospecharais",
			Uds: "sospecharan",
		},
		Imperfect2: {
			yo: "sospechase",
			tú: "sospechases",
			Ud: "sospechase",
			nosotros: "sospechásemos",
			vosotros: "sospechaseis",
			Uds: "sospechasen",
		},
		Future: {
			yo: "sospechare",
			tú: "sospechares",
			Ud: "sospechare",
			nosotros: "sospecháremos",
			vosotros: "sospechareis",
			Uds: "sospecharen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "sospecha",
			Ud: "sospeche",
			nosotros: "sospechemos",
			vosotros: "sospechad",
			Uds: "sospechen",
		},
		Negative: {
			tú: "no sospeches",
			Ud: "no sospeche",
			nosotros: "no sospechemos",
			vosotros: "no sospechéis",
			Uds: "no sospechen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy sospechando",
			tú: "estás sospechando",
			Ud: "está sospechando",
			nosotros: "estamos sospechando",
			vosotros: "estáis sospechando",
			Uds: "están sospechando",
		},
		Preterite: {
			yo: "estuve sospechando",
			tú: "estuviste sospechando",
			Ud: "estuvo sospechando",
			nosotros: "estuvimos sospechando",
			vosotros: "estuvisteis sospechando",
			Uds: "estuvieron sospechando",
		},
		Imperfect: {
			Uds: "estaban sospechando",
			yo: "estaba sospechando",
			tú: "estabas sospechando",
			Ud: "estaba sospechando",
			nosotros: "estábamos sospechando",
			vosotros: "estabais sospechando",
		},
		Conditional: {
			yo: "estaría sospechando",
			tú: "estarías sospechando",
			Ud: "estaría sospechando",
			nosotros: "estaríamos sospechando",
			vosotros: "estaríais sospechando",
			Uds: "estarían sospechando",
		},
		Future: {
			yo: "estaré sospechando",
			tú: "estarás sospechando",
			Ud: "estará sospechando",
			nosotros: "estaremos sospechando",
			vosotros: "estaréis sospechando",
			Uds: "estarán sospechando",
		},
	},
	Perfect: {
		Present: {
			yo: "he sospechado",
			tú: "has sospechado",
			Ud: "ha sospechado",
			nosotros: "hemos sospechado",
			vosotros: "habéis sospechado",
			Uds: "han sospechado",
		},
		Preterite: {
			yo: "hube sospechado",
			tú: "hubiste sospechado",
			Ud: "hubo sospechado",
			nosotros: "hubimos sospechado",
			vosotros: "hubisteis sospechado",
			Uds: "hubieron sospechado",
		},
		Past: {
			yo: "había sospechado",
			tú: "habías sospechado",
			Ud: "había sospechado",
			nosotros: "habíamos sospechado",
			vosotros: "habíais sospechado",
			Uds: "habían sospechado",
		},
		Conditional: {
			yo: "habría sospechado",
			tú: "habrías sospechado",
			Ud: "habría sospechado",
			nosotros: "habríamos sospechado",
			vosotros: "habríais sospechado",
			Uds: "habrían sospechado",
		},
		Future: {
			yo: "habré sospechado",
			tú: "habrás sospechado",
			Ud: "habrá sospechado",
			nosotros: "habremos sospechado",
			vosotros: "habréis sospechado",
			Uds: "habrán sospechado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya sospechado",
			tú: "hayas sospechado",
			Ud: "haya sospechado",
			nosotros: "hayamos sospechado",
			vosotros: "hayáis sospechado",
			Uds: "hayan sospechado",
		},
		Past: {
			yo: "hubiera sospechado",
			tú: "hubieras sospechado",
			Ud: "hubiera sospechado",
			nosotros: "hubiéramos sospechado",
			vosotros: "hubierais sospechado",
			Uds: "hubieran sospechado",
		},
		Future: {
			yo: "hubiere sospechado",
			tú: "hubieres sospechado",
			Ud: "hubiere sospechado",
			nosotros: "hubiéremos sospechado",
			vosotros: "hubiereis sospechado",
			Uds: "hubieren sospechado",
		},
	},
}
