var subordinar = {
	Indicative: {
		Present: {
			yo: "subordino",
			tú: "subordinas",
			Ud: "subordina",
			nosotros: "subordinamos",
			vosotros: "subordináis",
			Uds: "subordinan",
		},
		Preterite: {
			yo: "subordiné",
			tú: "subordinaste",
			Ud: "subordinó",
			nosotros: "subordinamos",
			vosotros: "subordinasteis",
			Uds: "subordinaron",
		},
		Imperfect: {
			yo: "subordinaba",
			tú: "subordinabas",
			Ud: "subordinaba",
			nosotros: "subordinábamos",
			vosotros: "subordinabais",
			Uds: "subordinaban",
		},
		Conditional: {
			yo: "subordinaría",
			tú: "subordinarías",
			Ud: "subordinaría",
			nosotros: "subordinaríamos",
			vosotros: "subordinaríais",
			Uds: "subordinarían",
		},
		Future: {
			yo: "subordinaré",
			tú: "subordinarás",
			Ud: "subordinará",
			nosotros: "subordinaremos",
			vosotros: "subordinaréis",
			Uds: "subordinarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "subordine",
			tú: "subordines",
			Ud: "subordine",
			nosotros: "subordinemos",
			vosotros: "subordinéis",
			Uds: "subordinen",
		},
		Imperfect: {
			yo: "subordinara",
			tú: "subordinaras",
			Ud: "subordinara",
			nosotros: "subordináramos",
			vosotros: "subordinarais",
			Uds: "subordinaran",
		},
		Imperfect2: {
			yo: "subordinase",
			tú: "subordinases",
			Ud: "subordinase",
			nosotros: "subordinásemos",
			vosotros: "subordinaseis",
			Uds: "subordinasen",
		},
		Future: {
			yo: "subordinare",
			tú: "subordinares",
			Ud: "subordinare",
			nosotros: "subordináremos",
			vosotros: "subordinareis",
			Uds: "subordinaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "subordina",
			Ud: "subordine",
			nosotros: "subordinemos",
			vosotros: "subordinad",
			Uds: "subordinen",
		},
		Negative: {
			tú: "no subordines",
			Ud: "no subordine",
			nosotros: "no subordinemos",
			vosotros: "no subordinéis",
			Uds: "no subordinen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy subordinando",
			tú: "estás subordinando",
			Ud: "está subordinando",
			nosotros: "estamos subordinando",
			vosotros: "estáis subordinando",
			Uds: "están subordinando",
		},
		Preterite: {
			yo: "estuve subordinando",
			tú: "estuviste subordinando",
			Ud: "estuvo subordinando",
			nosotros: "estuvimos subordinando",
			vosotros: "estuvisteis subordinando",
			Uds: "estuvieron subordinando",
		},
		Imperfect: {
			Uds: "estaban subordinando",
			yo: "estaba subordinando",
			tú: "estabas subordinando",
			Ud: "estaba subordinando",
			nosotros: "estábamos subordinando",
			vosotros: "estabais subordinando",
		},
		Conditional: {
			yo: "estaría subordinando",
			tú: "estarías subordinando",
			Ud: "estaría subordinando",
			nosotros: "estaríamos subordinando",
			vosotros: "estaríais subordinando",
			Uds: "estarían subordinando",
		},
		Future: {
			yo: "estaré subordinando",
			tú: "estarás subordinando",
			Ud: "estará subordinando",
			nosotros: "estaremos subordinando",
			vosotros: "estaréis subordinando",
			Uds: "estarán subordinando",
		},
	},
	Perfect: {
		Present: {
			yo: "he subordinado",
			tú: "has subordinado",
			Ud: "ha subordinado",
			nosotros: "hemos subordinado",
			vosotros: "habéis subordinado",
			Uds: "han subordinado",
		},
		Preterite: {
			yo: "hube subordinado",
			tú: "hubiste subordinado",
			Ud: "hubo subordinado",
			nosotros: "hubimos subordinado",
			vosotros: "hubisteis subordinado",
			Uds: "hubieron subordinado",
		},
		Past: {
			yo: "había subordinado",
			tú: "habías subordinado",
			Ud: "había subordinado",
			nosotros: "habíamos subordinado",
			vosotros: "habíais subordinado",
			Uds: "habían subordinado",
		},
		Conditional: {
			yo: "habría subordinado",
			tú: "habrías subordinado",
			Ud: "habría subordinado",
			nosotros: "habríamos subordinado",
			vosotros: "habríais subordinado",
			Uds: "habrían subordinado",
		},
		Future: {
			yo: "habré subordinado",
			tú: "habrás subordinado",
			Ud: "habrá subordinado",
			nosotros: "habremos subordinado",
			vosotros: "habréis subordinado",
			Uds: "habrán subordinado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya subordinado",
			tú: "hayas subordinado",
			Ud: "haya subordinado",
			nosotros: "hayamos subordinado",
			vosotros: "hayáis subordinado",
			Uds: "hayan subordinado",
		},
		Past: {
			yo: "hubiera subordinado",
			tú: "hubieras subordinado",
			Ud: "hubiera subordinado",
			nosotros: "hubiéramos subordinado",
			vosotros: "hubierais subordinado",
			Uds: "hubieran subordinado",
		},
		Future: {
			yo: "hubiere subordinado",
			tú: "hubieres subordinado",
			Ud: "hubiere subordinado",
			nosotros: "hubiéremos subordinado",
			vosotros: "hubiereis subordinado",
			Uds: "hubieren subordinado",
		},
	},
}
