var subrayar = {
	Indicative: {
		Present: {
			yo: "subrayo",
			tú: "subrayas",
			Ud: "subraya",
			nosotros: "subrayamos",
			vosotros: "subrayáis",
			Uds: "subrayan",
		},
		Preterite: {
			yo: "subrayé",
			tú: "subrayaste",
			Ud: "subrayó",
			nosotros: "subrayamos",
			vosotros: "subrayasteis",
			Uds: "subrayaron",
		},
		Imperfect: {
			yo: "subrayaba",
			tú: "subrayabas",
			Ud: "subrayaba",
			nosotros: "subrayábamos",
			vosotros: "subrayabais",
			Uds: "subrayaban",
		},
		Conditional: {
			yo: "subrayaría",
			tú: "subrayarías",
			Ud: "subrayaría",
			nosotros: "subrayaríamos",
			vosotros: "subrayaríais",
			Uds: "subrayarían",
		},
		Future: {
			yo: "subrayaré",
			tú: "subrayarás",
			Ud: "subrayará",
			nosotros: "subrayaremos",
			vosotros: "subrayaréis",
			Uds: "subrayarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "subraye",
			tú: "subrayes",
			Ud: "subraye",
			nosotros: "subrayemos",
			vosotros: "subrayéis",
			Uds: "subrayen",
		},
		Imperfect: {
			yo: "subrayara",
			tú: "subrayaras",
			Ud: "subrayara",
			nosotros: "subrayáramos",
			vosotros: "subrayarais",
			Uds: "subrayaran",
		},
		Imperfect2: {
			yo: "subrayase",
			tú: "subrayases",
			Ud: "subrayase",
			nosotros: "subrayásemos",
			vosotros: "subrayaseis",
			Uds: "subrayasen",
		},
		Future: {
			yo: "subrayare",
			tú: "subrayares",
			Ud: "subrayare",
			nosotros: "subrayáremos",
			vosotros: "subrayareis",
			Uds: "subrayaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "subraya",
			Ud: "subraye",
			nosotros: "subrayemos",
			vosotros: "subrayad",
			Uds: "subrayen",
		},
		Negative: {
			tú: "no subrayes",
			Ud: "no subraye",
			nosotros: "no subrayemos",
			vosotros: "no subrayéis",
			Uds: "no subrayen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy subrayando",
			tú: "estás subrayando",
			Ud: "está subrayando",
			nosotros: "estamos subrayando",
			vosotros: "estáis subrayando",
			Uds: "están subrayando",
		},
		Preterite: {
			yo: "estuve subrayando",
			tú: "estuviste subrayando",
			Ud: "estuvo subrayando",
			nosotros: "estuvimos subrayando",
			vosotros: "estuvisteis subrayando",
			Uds: "estuvieron subrayando",
		},
		Imperfect: {
			Uds: "estaban subrayando",
			yo: "estaba subrayando",
			tú: "estabas subrayando",
			Ud: "estaba subrayando",
			nosotros: "estábamos subrayando",
			vosotros: "estabais subrayando",
		},
		Conditional: {
			yo: "estaría subrayando",
			tú: "estarías subrayando",
			Ud: "estaría subrayando",
			nosotros: "estaríamos subrayando",
			vosotros: "estaríais subrayando",
			Uds: "estarían subrayando",
		},
		Future: {
			yo: "estaré subrayando",
			tú: "estarás subrayando",
			Ud: "estará subrayando",
			nosotros: "estaremos subrayando",
			vosotros: "estaréis subrayando",
			Uds: "estarán subrayando",
		},
	},
	Perfect: {
		Present: {
			yo: "he subrayado",
			tú: "has subrayado",
			Ud: "ha subrayado",
			nosotros: "hemos subrayado",
			vosotros: "habéis subrayado",
			Uds: "han subrayado",
		},
		Preterite: {
			yo: "hube subrayado",
			tú: "hubiste subrayado",
			Ud: "hubo subrayado",
			nosotros: "hubimos subrayado",
			vosotros: "hubisteis subrayado",
			Uds: "hubieron subrayado",
		},
		Past: {
			yo: "había subrayado",
			tú: "habías subrayado",
			Ud: "había subrayado",
			nosotros: "habíamos subrayado",
			vosotros: "habíais subrayado",
			Uds: "habían subrayado",
		},
		Conditional: {
			yo: "habría subrayado",
			tú: "habrías subrayado",
			Ud: "habría subrayado",
			nosotros: "habríamos subrayado",
			vosotros: "habríais subrayado",
			Uds: "habrían subrayado",
		},
		Future: {
			yo: "habré subrayado",
			tú: "habrás subrayado",
			Ud: "habrá subrayado",
			nosotros: "habremos subrayado",
			vosotros: "habréis subrayado",
			Uds: "habrán subrayado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya subrayado",
			tú: "hayas subrayado",
			Ud: "haya subrayado",
			nosotros: "hayamos subrayado",
			vosotros: "hayáis subrayado",
			Uds: "hayan subrayado",
		},
		Past: {
			yo: "hubiera subrayado",
			tú: "hubieras subrayado",
			Ud: "hubiera subrayado",
			nosotros: "hubiéramos subrayado",
			vosotros: "hubierais subrayado",
			Uds: "hubieran subrayado",
		},
		Future: {
			yo: "hubiere subrayado",
			tú: "hubieres subrayado",
			Ud: "hubiere subrayado",
			nosotros: "hubiéremos subrayado",
			vosotros: "hubiereis subrayado",
			Uds: "hubieren subrayado",
		},
	},
}
