var subsistir = {
	Indicative: {
		Present: {
			yo: "subsisto",
			tú: "subsistes",
			Ud: "subsiste",
			nosotros: "subsistimos",
			vosotros: "subsistís",
			Uds: "subsisten",
		},
		Preterite: {
			yo: "subsistí",
			tú: "subsististe",
			Ud: "subsistió",
			nosotros: "subsistimos",
			vosotros: "subsististeis",
			Uds: "subsistieron",
		},
		Imperfect: {
			yo: "subsistía",
			tú: "subsistías",
			Ud: "subsistía",
			nosotros: "subsistíamos",
			vosotros: "subsistíais",
			Uds: "subsistían",
		},
		Conditional: {
			yo: "subsistiría",
			tú: "subsistirías",
			Ud: "subsistiría",
			nosotros: "subsistiríamos",
			vosotros: "subsistiríais",
			Uds: "subsistirían",
		},
		Future: {
			yo: "subsistiré",
			tú: "subsistirás",
			Ud: "subsistirá",
			nosotros: "subsistiremos",
			vosotros: "subsistiréis",
			Uds: "subsistirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "subsista",
			tú: "subsistas",
			Ud: "subsista",
			nosotros: "subsistamos",
			vosotros: "subsistáis",
			Uds: "subsistan",
		},
		Imperfect: {
			yo: "subsistiera",
			tú: "subsistieras",
			Ud: "subsistiera",
			nosotros: "subsistiéramos",
			vosotros: "subsistierais",
			Uds: "subsistieran",
		},
		Imperfect2: {
			yo: "subsistiese",
			tú: "subsistieses",
			Ud: "subsistiese",
			nosotros: "subsistiésemos",
			vosotros: "subsistieseis",
			Uds: "subsistiesen",
		},
		Future: {
			yo: "subsistiere",
			tú: "subsistieres",
			Ud: "subsistiere",
			nosotros: "subsistiéremos",
			vosotros: "subsistiereis",
			Uds: "subsistieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "subsiste",
			Ud: "subsista",
			nosotros: "subsistamos",
			vosotros: "subsistid",
			Uds: "subsistan",
		},
		Negative: {
			tú: "no subsistas",
			Ud: "no subsista",
			nosotros: "no subsistamos",
			vosotros: "no subsistáis",
			Uds: "no subsistan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy subsistiendo",
			tú: "estás subsistiendo",
			Ud: "está subsistiendo",
			nosotros: "estamos subsistiendo",
			vosotros: "estáis subsistiendo",
			Uds: "están subsistiendo",
		},
		Preterite: {
			yo: "estuve subsistiendo",
			tú: "estuviste subsistiendo",
			Ud: "estuvo subsistiendo",
			nosotros: "estuvimos subsistiendo",
			vosotros: "estuvisteis subsistiendo",
			Uds: "estuvieron subsistiendo",
		},
		Imperfect: {
			Uds: "estaban subsistiendo",
			yo: "estaba subsistiendo",
			tú: "estabas subsistiendo",
			Ud: "estaba subsistiendo",
			nosotros: "estábamos subsistiendo",
			vosotros: "estabais subsistiendo",
		},
		Conditional: {
			yo: "estaría subsistiendo",
			tú: "estarías subsistiendo",
			Ud: "estaría subsistiendo",
			nosotros: "estaríamos subsistiendo",
			vosotros: "estaríais subsistiendo",
			Uds: "estarían subsistiendo",
		},
		Future: {
			yo: "estaré subsistiendo",
			tú: "estarás subsistiendo",
			Ud: "estará subsistiendo",
			nosotros: "estaremos subsistiendo",
			vosotros: "estaréis subsistiendo",
			Uds: "estarán subsistiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he subsistido",
			tú: "has subsistido",
			Ud: "ha subsistido",
			nosotros: "hemos subsistido",
			vosotros: "habéis subsistido",
			Uds: "han subsistido",
		},
		Preterite: {
			yo: "hube subsistido",
			tú: "hubiste subsistido",
			Ud: "hubo subsistido",
			nosotros: "hubimos subsistido",
			vosotros: "hubisteis subsistido",
			Uds: "hubieron subsistido",
		},
		Past: {
			yo: "había subsistido",
			tú: "habías subsistido",
			Ud: "había subsistido",
			nosotros: "habíamos subsistido",
			vosotros: "habíais subsistido",
			Uds: "habían subsistido",
		},
		Conditional: {
			yo: "habría subsistido",
			tú: "habrías subsistido",
			Ud: "habría subsistido",
			nosotros: "habríamos subsistido",
			vosotros: "habríais subsistido",
			Uds: "habrían subsistido",
		},
		Future: {
			yo: "habré subsistido",
			tú: "habrás subsistido",
			Ud: "habrá subsistido",
			nosotros: "habremos subsistido",
			vosotros: "habréis subsistido",
			Uds: "habrán subsistido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya subsistido",
			tú: "hayas subsistido",
			Ud: "haya subsistido",
			nosotros: "hayamos subsistido",
			vosotros: "hayáis subsistido",
			Uds: "hayan subsistido",
		},
		Past: {
			yo: "hubiera subsistido",
			tú: "hubieras subsistido",
			Ud: "hubiera subsistido",
			nosotros: "hubiéramos subsistido",
			vosotros: "hubierais subsistido",
			Uds: "hubieran subsistido",
		},
		Future: {
			yo: "hubiere subsistido",
			tú: "hubieres subsistido",
			Ud: "hubiere subsistido",
			nosotros: "hubiéremos subsistido",
			vosotros: "hubiereis subsistido",
			Uds: "hubieren subsistido",
		},
	},
}
