var sucumbir = {
	Indicative: {
		Present: {
			yo: "sucumbo",
			tú: "sucumbes",
			Ud: "sucumbe",
			nosotros: "sucumbimos",
			vosotros: "sucumbís",
			Uds: "sucumben",
		},
		Preterite: {
			yo: "sucumbí",
			tú: "sucumbiste",
			Ud: "sucumbió",
			nosotros: "sucumbimos",
			vosotros: "sucumbisteis",
			Uds: "sucumbieron",
		},
		Imperfect: {
			yo: "sucumbía",
			tú: "sucumbías",
			Ud: "sucumbía",
			nosotros: "sucumbíamos",
			vosotros: "sucumbíais",
			Uds: "sucumbían",
		},
		Conditional: {
			yo: "sucumbiría",
			tú: "sucumbirías",
			Ud: "sucumbiría",
			nosotros: "sucumbiríamos",
			vosotros: "sucumbiríais",
			Uds: "sucumbirían",
		},
		Future: {
			yo: "sucumbiré",
			tú: "sucumbirás",
			Ud: "sucumbirá",
			nosotros: "sucumbiremos",
			vosotros: "sucumbiréis",
			Uds: "sucumbirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "sucumba",
			tú: "sucumbas",
			Ud: "sucumba",
			nosotros: "sucumbamos",
			vosotros: "sucumbáis",
			Uds: "sucumban",
		},
		Imperfect: {
			yo: "sucumbiera",
			tú: "sucumbieras",
			Ud: "sucumbiera",
			nosotros: "sucumbiéramos",
			vosotros: "sucumbierais",
			Uds: "sucumbieran",
		},
		Imperfect2: {
			yo: "sucumbiese",
			tú: "sucumbieses",
			Ud: "sucumbiese",
			nosotros: "sucumbiésemos",
			vosotros: "sucumbieseis",
			Uds: "sucumbiesen",
		},
		Future: {
			yo: "sucumbiere",
			tú: "sucumbieres",
			Ud: "sucumbiere",
			nosotros: "sucumbiéremos",
			vosotros: "sucumbiereis",
			Uds: "sucumbieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "sucumbe",
			Ud: "sucumba",
			nosotros: "sucumbamos",
			vosotros: "sucumbid",
			Uds: "sucumban",
		},
		Negative: {
			tú: "no sucumbas",
			Ud: "no sucumba",
			nosotros: "no sucumbamos",
			vosotros: "no sucumbáis",
			Uds: "no sucumban",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy sucumbiendo",
			tú: "estás sucumbiendo",
			Ud: "está sucumbiendo",
			nosotros: "estamos sucumbiendo",
			vosotros: "estáis sucumbiendo",
			Uds: "están sucumbiendo",
		},
		Preterite: {
			yo: "estuve sucumbiendo",
			tú: "estuviste sucumbiendo",
			Ud: "estuvo sucumbiendo",
			nosotros: "estuvimos sucumbiendo",
			vosotros: "estuvisteis sucumbiendo",
			Uds: "estuvieron sucumbiendo",
		},
		Imperfect: {
			Uds: "estaban sucumbiendo",
			yo: "estaba sucumbiendo",
			tú: "estabas sucumbiendo",
			Ud: "estaba sucumbiendo",
			nosotros: "estábamos sucumbiendo",
			vosotros: "estabais sucumbiendo",
		},
		Conditional: {
			yo: "estaría sucumbiendo",
			tú: "estarías sucumbiendo",
			Ud: "estaría sucumbiendo",
			nosotros: "estaríamos sucumbiendo",
			vosotros: "estaríais sucumbiendo",
			Uds: "estarían sucumbiendo",
		},
		Future: {
			yo: "estaré sucumbiendo",
			tú: "estarás sucumbiendo",
			Ud: "estará sucumbiendo",
			nosotros: "estaremos sucumbiendo",
			vosotros: "estaréis sucumbiendo",
			Uds: "estarán sucumbiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he sucumbido",
			tú: "has sucumbido",
			Ud: "ha sucumbido",
			nosotros: "hemos sucumbido",
			vosotros: "habéis sucumbido",
			Uds: "han sucumbido",
		},
		Preterite: {
			yo: "hube sucumbido",
			tú: "hubiste sucumbido",
			Ud: "hubo sucumbido",
			nosotros: "hubimos sucumbido",
			vosotros: "hubisteis sucumbido",
			Uds: "hubieron sucumbido",
		},
		Past: {
			yo: "había sucumbido",
			tú: "habías sucumbido",
			Ud: "había sucumbido",
			nosotros: "habíamos sucumbido",
			vosotros: "habíais sucumbido",
			Uds: "habían sucumbido",
		},
		Conditional: {
			yo: "habría sucumbido",
			tú: "habrías sucumbido",
			Ud: "habría sucumbido",
			nosotros: "habríamos sucumbido",
			vosotros: "habríais sucumbido",
			Uds: "habrían sucumbido",
		},
		Future: {
			yo: "habré sucumbido",
			tú: "habrás sucumbido",
			Ud: "habrá sucumbido",
			nosotros: "habremos sucumbido",
			vosotros: "habréis sucumbido",
			Uds: "habrán sucumbido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya sucumbido",
			tú: "hayas sucumbido",
			Ud: "haya sucumbido",
			nosotros: "hayamos sucumbido",
			vosotros: "hayáis sucumbido",
			Uds: "hayan sucumbido",
		},
		Past: {
			yo: "hubiera sucumbido",
			tú: "hubieras sucumbido",
			Ud: "hubiera sucumbido",
			nosotros: "hubiéramos sucumbido",
			vosotros: "hubierais sucumbido",
			Uds: "hubieran sucumbido",
		},
		Future: {
			yo: "hubiere sucumbido",
			tú: "hubieres sucumbido",
			Ud: "hubiere sucumbido",
			nosotros: "hubiéremos sucumbido",
			vosotros: "hubiereis sucumbido",
			Uds: "hubieren sucumbido",
		},
	},
}
