var sujetar = {
	Indicative: {
		Present: {
			yo: "sujeto",
			tú: "sujetas",
			Ud: "sujeta",
			nosotros: "sujetamos",
			vosotros: "sujetáis",
			Uds: "sujetan",
		},
		Preterite: {
			yo: "sujeté",
			tú: "sujetaste",
			Ud: "sujetó",
			nosotros: "sujetamos",
			vosotros: "sujetasteis",
			Uds: "sujetaron",
		},
		Imperfect: {
			yo: "sujetaba",
			tú: "sujetabas",
			Ud: "sujetaba",
			nosotros: "sujetábamos",
			vosotros: "sujetabais",
			Uds: "sujetaban",
		},
		Conditional: {
			yo: "sujetaría",
			tú: "sujetarías",
			Ud: "sujetaría",
			nosotros: "sujetaríamos",
			vosotros: "sujetaríais",
			Uds: "sujetarían",
		},
		Future: {
			yo: "sujetaré",
			tú: "sujetarás",
			Ud: "sujetará",
			nosotros: "sujetaremos",
			vosotros: "sujetaréis",
			Uds: "sujetarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "sujete",
			tú: "sujetes",
			Ud: "sujete",
			nosotros: "sujetemos",
			vosotros: "sujetéis",
			Uds: "sujeten",
		},
		Imperfect: {
			yo: "sujetara",
			tú: "sujetaras",
			Ud: "sujetara",
			nosotros: "sujetáramos",
			vosotros: "sujetarais",
			Uds: "sujetaran",
		},
		Imperfect2: {
			yo: "sujetase",
			tú: "sujetases",
			Ud: "sujetase",
			nosotros: "sujetásemos",
			vosotros: "sujetaseis",
			Uds: "sujetasen",
		},
		Future: {
			yo: "sujetare",
			tú: "sujetares",
			Ud: "sujetare",
			nosotros: "sujetáremos",
			vosotros: "sujetareis",
			Uds: "sujetaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "sujeta",
			Ud: "sujete",
			nosotros: "sujetemos",
			vosotros: "sujetad",
			Uds: "sujeten",
		},
		Negative: {
			tú: "no sujetes",
			Ud: "no sujete",
			nosotros: "no sujetemos",
			vosotros: "no sujetéis",
			Uds: "no sujeten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy sujetando",
			tú: "estás sujetando",
			Ud: "está sujetando",
			nosotros: "estamos sujetando",
			vosotros: "estáis sujetando",
			Uds: "están sujetando",
		},
		Preterite: {
			yo: "estuve sujetando",
			tú: "estuviste sujetando",
			Ud: "estuvo sujetando",
			nosotros: "estuvimos sujetando",
			vosotros: "estuvisteis sujetando",
			Uds: "estuvieron sujetando",
		},
		Imperfect: {
			Uds: "estaban sujetando",
			yo: "estaba sujetando",
			tú: "estabas sujetando",
			Ud: "estaba sujetando",
			nosotros: "estábamos sujetando",
			vosotros: "estabais sujetando",
		},
		Conditional: {
			yo: "estaría sujetando",
			tú: "estarías sujetando",
			Ud: "estaría sujetando",
			nosotros: "estaríamos sujetando",
			vosotros: "estaríais sujetando",
			Uds: "estarían sujetando",
		},
		Future: {
			yo: "estaré sujetando",
			tú: "estarás sujetando",
			Ud: "estará sujetando",
			nosotros: "estaremos sujetando",
			vosotros: "estaréis sujetando",
			Uds: "estarán sujetando",
		},
	},
	Perfect: {
		Present: {
			yo: "he sujetado,susujeto",
			tú: "has sujetado,susujeto",
			Ud: "ha sujetado,susujeto",
			nosotros: "hemos sujetado,susujeto",
			vosotros: "habéis sujetado,susujeto",
			Uds: "han sujetado,susujeto",
		},
		Preterite: {
			yo: "hube sujetado,susujeto",
			tú: "hubiste sujetado,susujeto",
			Ud: "hubo sujetado,susujeto",
			nosotros: "hubimos sujetado,susujeto",
			vosotros: "hubisteis sujetado,susujeto",
			Uds: "hubieron sujetado,susujeto",
		},
		Past: {
			yo: "había sujetado,susujeto",
			tú: "habías sujetado,susujeto",
			Ud: "había sujetado,susujeto",
			nosotros: "habíamos sujetado,susujeto",
			vosotros: "habíais sujetado,susujeto",
			Uds: "habían sujetado,susujeto",
		},
		Conditional: {
			yo: "habría sujetado,susujeto",
			tú: "habrías sujetado,susujeto",
			Ud: "habría sujetado,susujeto",
			nosotros: "habríamos sujetado,susujeto",
			vosotros: "habríais sujetado,susujeto",
			Uds: "habrían sujetado,susujeto",
		},
		Future: {
			yo: "habré sujetado,susujeto",
			tú: "habrás sujetado,susujeto",
			Ud: "habrá sujetado,susujeto",
			nosotros: "habremos sujetado,susujeto",
			vosotros: "habréis sujetado,susujeto",
			Uds: "habrán sujetado,susujeto",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya sujetado,susujeto",
			tú: "hayas sujetado,susujeto",
			Ud: "haya sujetado,susujeto",
			nosotros: "hayamos sujetado,susujeto",
			vosotros: "hayáis sujetado,susujeto",
			Uds: "hayan sujetado,susujeto",
		},
		Past: {
			yo: "hubiera sujetado,susujeto",
			tú: "hubieras sujetado,susujeto",
			Ud: "hubiera sujetado,susujeto",
			nosotros: "hubiéramos sujetado,susujeto",
			vosotros: "hubierais sujetado,susujeto",
			Uds: "hubieran sujetado,susujeto",
		},
		Future: {
			yo: "hubiere sujetado,susujeto",
			tú: "hubieres sujetado,susujeto",
			Ud: "hubiere sujetado,susujeto",
			nosotros: "hubiéremos sujetado,susujeto",
			vosotros: "hubiereis sujetado,susujeto",
			Uds: "hubieren sujetado,susujeto",
		},
	},
}
