var sumergir = {
	Indicative: {
		Present: {
			yo: "sumerjo",
			tú: "sumerges",
			Ud: "sumerge",
			nosotros: "sumergimos",
			vosotros: "sumergís",
			Uds: "sumergen",
		},
		Preterite: {
			yo: "sumergí",
			tú: "sumergiste",
			Ud: "sumergió",
			nosotros: "sumergimos",
			vosotros: "sumergisteis",
			Uds: "sumergieron",
		},
		Imperfect: {
			yo: "sumergía",
			tú: "sumergías",
			Ud: "sumergía",
			nosotros: "sumergíamos",
			vosotros: "sumergíais",
			Uds: "sumergían",
		},
		Conditional: {
			yo: "sumergiría",
			tú: "sumergirías",
			Ud: "sumergiría",
			nosotros: "sumergiríamos",
			vosotros: "sumergiríais",
			Uds: "sumergirían",
		},
		Future: {
			yo: "sumergiré",
			tú: "sumergirás",
			Ud: "sumergirá",
			nosotros: "sumergiremos",
			vosotros: "sumergiréis",
			Uds: "sumergirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "sumerja",
			tú: "sumerjas",
			Ud: "sumerja",
			nosotros: "sumerjamos",
			vosotros: "sumerjáis",
			Uds: "sumerjan",
		},
		Imperfect: {
			yo: "sumergiera",
			tú: "sumergieras",
			Ud: "sumergiera",
			nosotros: "sumergiéramos",
			vosotros: "sumergierais",
			Uds: "sumergieran",
		},
		Imperfect2: {
			yo: "sumergiese",
			tú: "sumergieses",
			Ud: "sumergiese",
			nosotros: "sumergiésemos",
			vosotros: "sumergieseis",
			Uds: "sumergiesen",
		},
		Future: {
			yo: "sumergiere",
			tú: "sumergieres",
			Ud: "sumergiere",
			nosotros: "sumergiéremos",
			vosotros: "sumergiereis",
			Uds: "sumergieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "sumerge",
			Ud: "sumerja",
			nosotros: "sumerjamos",
			vosotros: "sumergid",
			Uds: "sumerjan",
		},
		Negative: {
			tú: "no sumerjas",
			Ud: "no sumerja",
			nosotros: "no sumerjamos",
			vosotros: "no sumerjáis",
			Uds: "no sumerjan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy sumergiendo",
			tú: "estás sumergiendo",
			Ud: "está sumergiendo",
			nosotros: "estamos sumergiendo",
			vosotros: "estáis sumergiendo",
			Uds: "están sumergiendo",
		},
		Preterite: {
			yo: "estuve sumergiendo",
			tú: "estuviste sumergiendo",
			Ud: "estuvo sumergiendo",
			nosotros: "estuvimos sumergiendo",
			vosotros: "estuvisteis sumergiendo",
			Uds: "estuvieron sumergiendo",
		},
		Imperfect: {
			Uds: "estaban sumergiendo",
			yo: "estaba sumergiendo",
			tú: "estabas sumergiendo",
			Ud: "estaba sumergiendo",
			nosotros: "estábamos sumergiendo",
			vosotros: "estabais sumergiendo",
		},
		Conditional: {
			yo: "estaría sumergiendo",
			tú: "estarías sumergiendo",
			Ud: "estaría sumergiendo",
			nosotros: "estaríamos sumergiendo",
			vosotros: "estaríais sumergiendo",
			Uds: "estarían sumergiendo",
		},
		Future: {
			yo: "estaré sumergiendo",
			tú: "estarás sumergiendo",
			Ud: "estará sumergiendo",
			nosotros: "estaremos sumergiendo",
			vosotros: "estaréis sumergiendo",
			Uds: "estarán sumergiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he sumergido",
			tú: "has sumergido",
			Ud: "ha sumergido",
			nosotros: "hemos sumergido",
			vosotros: "habéis sumergido",
			Uds: "han sumergido",
		},
		Preterite: {
			yo: "hube sumergido",
			tú: "hubiste sumergido",
			Ud: "hubo sumergido",
			nosotros: "hubimos sumergido",
			vosotros: "hubisteis sumergido",
			Uds: "hubieron sumergido",
		},
		Past: {
			yo: "había sumergido",
			tú: "habías sumergido",
			Ud: "había sumergido",
			nosotros: "habíamos sumergido",
			vosotros: "habíais sumergido",
			Uds: "habían sumergido",
		},
		Conditional: {
			yo: "habría sumergido",
			tú: "habrías sumergido",
			Ud: "habría sumergido",
			nosotros: "habríamos sumergido",
			vosotros: "habríais sumergido",
			Uds: "habrían sumergido",
		},
		Future: {
			yo: "habré sumergido",
			tú: "habrás sumergido",
			Ud: "habrá sumergido",
			nosotros: "habremos sumergido",
			vosotros: "habréis sumergido",
			Uds: "habrán sumergido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya sumergido",
			tú: "hayas sumergido",
			Ud: "haya sumergido",
			nosotros: "hayamos sumergido",
			vosotros: "hayáis sumergido",
			Uds: "hayan sumergido",
		},
		Past: {
			yo: "hubiera sumergido",
			tú: "hubieras sumergido",
			Ud: "hubiera sumergido",
			nosotros: "hubiéramos sumergido",
			vosotros: "hubierais sumergido",
			Uds: "hubieran sumergido",
		},
		Future: {
			yo: "hubiere sumergido",
			tú: "hubieres sumergido",
			Ud: "hubiere sumergido",
			nosotros: "hubiéremos sumergido",
			vosotros: "hubiereis sumergido",
			Uds: "hubieren sumergido",
		},
	},
}
