var suplicar = {
	Indicative: {
		Present: {
			yo: "suplico",
			tú: "suplicas",
			Ud: "suplica",
			nosotros: "suplicamos",
			vosotros: "suplicáis",
			Uds: "suplican",
		},
		Preterite: {
			yo: "supliqué",
			tú: "suplicaste",
			Ud: "suplicó",
			nosotros: "suplicamos",
			vosotros: "suplicasteis",
			Uds: "suplicaron",
		},
		Imperfect: {
			yo: "suplicaba",
			tú: "suplicabas",
			Ud: "suplicaba",
			nosotros: "suplicábamos",
			vosotros: "suplicabais",
			Uds: "suplicaban",
		},
		Conditional: {
			yo: "suplicaría",
			tú: "suplicarías",
			Ud: "suplicaría",
			nosotros: "suplicaríamos",
			vosotros: "suplicaríais",
			Uds: "suplicarían",
		},
		Future: {
			yo: "suplicaré",
			tú: "suplicarás",
			Ud: "suplicará",
			nosotros: "suplicaremos",
			vosotros: "suplicaréis",
			Uds: "suplicarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "suplique",
			tú: "supliques",
			Ud: "suplique",
			nosotros: "supliquemos",
			vosotros: "supliquéis",
			Uds: "supliquen",
		},
		Imperfect: {
			yo: "suplicara",
			tú: "suplicaras",
			Ud: "suplicara",
			nosotros: "suplicáramos",
			vosotros: "suplicarais",
			Uds: "suplicaran",
		},
		Imperfect2: {
			yo: "suplicase",
			tú: "suplicases",
			Ud: "suplicase",
			nosotros: "suplicásemos",
			vosotros: "suplicaseis",
			Uds: "suplicasen",
		},
		Future: {
			yo: "suplicare",
			tú: "suplicares",
			Ud: "suplicare",
			nosotros: "suplicáremos",
			vosotros: "suplicareis",
			Uds: "suplicaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "suplica",
			Ud: "suplique",
			nosotros: "supliquemos",
			vosotros: "suplicad",
			Uds: "supliquen",
		},
		Negative: {
			tú: "no supliques",
			Ud: "no suplique",
			nosotros: "no supliquemos",
			vosotros: "no supliquéis",
			Uds: "no supliquen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy suplicando",
			tú: "estás suplicando",
			Ud: "está suplicando",
			nosotros: "estamos suplicando",
			vosotros: "estáis suplicando",
			Uds: "están suplicando",
		},
		Preterite: {
			yo: "estuve suplicando",
			tú: "estuviste suplicando",
			Ud: "estuvo suplicando",
			nosotros: "estuvimos suplicando",
			vosotros: "estuvisteis suplicando",
			Uds: "estuvieron suplicando",
		},
		Imperfect: {
			Uds: "estaban suplicando",
			yo: "estaba suplicando",
			tú: "estabas suplicando",
			Ud: "estaba suplicando",
			nosotros: "estábamos suplicando",
			vosotros: "estabais suplicando",
		},
		Conditional: {
			yo: "estaría suplicando",
			tú: "estarías suplicando",
			Ud: "estaría suplicando",
			nosotros: "estaríamos suplicando",
			vosotros: "estaríais suplicando",
			Uds: "estarían suplicando",
		},
		Future: {
			yo: "estaré suplicando",
			tú: "estarás suplicando",
			Ud: "estará suplicando",
			nosotros: "estaremos suplicando",
			vosotros: "estaréis suplicando",
			Uds: "estarán suplicando",
		},
	},
	Perfect: {
		Present: {
			yo: "he suplicado",
			tú: "has suplicado",
			Ud: "ha suplicado",
			nosotros: "hemos suplicado",
			vosotros: "habéis suplicado",
			Uds: "han suplicado",
		},
		Preterite: {
			yo: "hube suplicado",
			tú: "hubiste suplicado",
			Ud: "hubo suplicado",
			nosotros: "hubimos suplicado",
			vosotros: "hubisteis suplicado",
			Uds: "hubieron suplicado",
		},
		Past: {
			yo: "había suplicado",
			tú: "habías suplicado",
			Ud: "había suplicado",
			nosotros: "habíamos suplicado",
			vosotros: "habíais suplicado",
			Uds: "habían suplicado",
		},
		Conditional: {
			yo: "habría suplicado",
			tú: "habrías suplicado",
			Ud: "habría suplicado",
			nosotros: "habríamos suplicado",
			vosotros: "habríais suplicado",
			Uds: "habrían suplicado",
		},
		Future: {
			yo: "habré suplicado",
			tú: "habrás suplicado",
			Ud: "habrá suplicado",
			nosotros: "habremos suplicado",
			vosotros: "habréis suplicado",
			Uds: "habrán suplicado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya suplicado",
			tú: "hayas suplicado",
			Ud: "haya suplicado",
			nosotros: "hayamos suplicado",
			vosotros: "hayáis suplicado",
			Uds: "hayan suplicado",
		},
		Past: {
			yo: "hubiera suplicado",
			tú: "hubieras suplicado",
			Ud: "hubiera suplicado",
			nosotros: "hubiéramos suplicado",
			vosotros: "hubierais suplicado",
			Uds: "hubieran suplicado",
		},
		Future: {
			yo: "hubiere suplicado",
			tú: "hubieres suplicado",
			Ud: "hubiere suplicado",
			nosotros: "hubiéremos suplicado",
			vosotros: "hubiereis suplicado",
			Uds: "hubieren suplicado",
		},
	},
}
