var suponer = {
	Indicative: {
		Present: {
			yo: "supongo",
			tú: "supones",
			Ud: "supone",
			nosotros: "suponemos",
			vosotros: "suponéis",
			Uds: "suponen",
		},
		Preterite: {
			yo: "supuse",
			tú: "supusiste",
			Ud: "supuso",
			nosotros: "supusimos",
			vosotros: "supusisteis",
			Uds: "supusieron",
		},
		Imperfect: {
			yo: "suponía",
			tú: "suponías",
			Ud: "suponía",
			nosotros: "suponíamos",
			vosotros: "suponíais",
			Uds: "suponían",
		},
		Conditional: {
			yo: "supondría",
			tú: "supondrías",
			Ud: "supondría",
			nosotros: "supondríamos",
			vosotros: "supondríais",
			Uds: "supondrían",
		},
		Future: {
			yo: "supondré",
			tú: "supondrás",
			Ud: "supondrá",
			nosotros: "supondremos",
			vosotros: "supondréis",
			Uds: "supondrán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "suponga",
			tú: "supongas",
			Ud: "suponga",
			nosotros: "supongamos",
			vosotros: "supongáis",
			Uds: "supongan",
		},
		Imperfect: {
			yo: "supusiera",
			tú: "supusieras",
			Ud: "supusiera",
			nosotros: "supusiéramos",
			vosotros: "supusierais",
			Uds: "supusieran",
		},
		Imperfect2: {
			yo: "supusiese",
			tú: "supusieses",
			Ud: "supusiese",
			nosotros: "supusiésemos",
			vosotros: "supusieseis",
			Uds: "supusiesen",
		},
		Future: {
			yo: "supusiere",
			tú: "supusieres",
			Ud: "supusiere",
			nosotros: "supusiéremos",
			vosotros: "supusiereis",
			Uds: "supusieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "supón",
			Ud: "suponga",
			nosotros: "supongamos",
			vosotros: "suponed",
			Uds: "supongan",
		},
		Negative: {
			tú: "no supongas",
			Ud: "no suponga",
			nosotros: "no supongamos",
			vosotros: "no supongáis",
			Uds: "no supongan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy suponiendo",
			tú: "estás suponiendo",
			Ud: "está suponiendo",
			nosotros: "estamos suponiendo",
			vosotros: "estáis suponiendo",
			Uds: "están suponiendo",
		},
		Preterite: {
			yo: "estuve suponiendo",
			tú: "estuviste suponiendo",
			Ud: "estuvo suponiendo",
			nosotros: "estuvimos suponiendo",
			vosotros: "estuvisteis suponiendo",
			Uds: "estuvieron suponiendo",
		},
		Imperfect: {
			Uds: "estaban suponiendo",
			yo: "estaba suponiendo",
			tú: "estabas suponiendo",
			Ud: "estaba suponiendo",
			nosotros: "estábamos suponiendo",
			vosotros: "estabais suponiendo",
		},
		Conditional: {
			yo: "estaría suponiendo",
			tú: "estarías suponiendo",
			Ud: "estaría suponiendo",
			nosotros: "estaríamos suponiendo",
			vosotros: "estaríais suponiendo",
			Uds: "estarían suponiendo",
		},
		Future: {
			yo: "estaré suponiendo",
			tú: "estarás suponiendo",
			Ud: "estará suponiendo",
			nosotros: "estaremos suponiendo",
			vosotros: "estaréis suponiendo",
			Uds: "estarán suponiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he supuesto",
			tú: "has supuesto",
			Ud: "ha supuesto",
			nosotros: "hemos supuesto",
			vosotros: "habéis supuesto",
			Uds: "han supuesto",
		},
		Preterite: {
			yo: "hube supuesto",
			tú: "hubiste supuesto",
			Ud: "hubo supuesto",
			nosotros: "hubimos supuesto",
			vosotros: "hubisteis supuesto",
			Uds: "hubieron supuesto",
		},
		Past: {
			yo: "había supuesto",
			tú: "habías supuesto",
			Ud: "había supuesto",
			nosotros: "habíamos supuesto",
			vosotros: "habíais supuesto",
			Uds: "habían supuesto",
		},
		Conditional: {
			yo: "habría supuesto",
			tú: "habrías supuesto",
			Ud: "habría supuesto",
			nosotros: "habríamos supuesto",
			vosotros: "habríais supuesto",
			Uds: "habrían supuesto",
		},
		Future: {
			yo: "habré supuesto",
			tú: "habrás supuesto",
			Ud: "habrá supuesto",
			nosotros: "habremos supuesto",
			vosotros: "habréis supuesto",
			Uds: "habrán supuesto",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya supuesto",
			tú: "hayas supuesto",
			Ud: "haya supuesto",
			nosotros: "hayamos supuesto",
			vosotros: "hayáis supuesto",
			Uds: "hayan supuesto",
		},
		Past: {
			yo: "hubiera supuesto",
			tú: "hubieras supuesto",
			Ud: "hubiera supuesto",
			nosotros: "hubiéramos supuesto",
			vosotros: "hubierais supuesto",
			Uds: "hubieran supuesto",
		},
		Future: {
			yo: "hubiere supuesto",
			tú: "hubieres supuesto",
			Ud: "hubiere supuesto",
			nosotros: "hubiéremos supuesto",
			vosotros: "hubiereis supuesto",
			Uds: "hubieren supuesto",
		},
	},
}
