var surtir = {
	Indicative: {
		Present: {
			yo: "surto",
			tú: "surtes",
			Ud: "surte",
			nosotros: "surtimos",
			vosotros: "surtís",
			Uds: "surten",
		},
		Preterite: {
			yo: "surtí",
			tú: "surtiste",
			Ud: "surtió",
			nosotros: "surtimos",
			vosotros: "surtisteis",
			Uds: "surtieron",
		},
		Imperfect: {
			yo: "surtía",
			tú: "surtías",
			Ud: "surtía",
			nosotros: "surtíamos",
			vosotros: "surtíais",
			Uds: "surtían",
		},
		Conditional: {
			yo: "surtiría",
			tú: "surtirías",
			Ud: "surtiría",
			nosotros: "surtiríamos",
			vosotros: "surtiríais",
			Uds: "surtirían",
		},
		Future: {
			yo: "surtiré",
			tú: "surtirás",
			Ud: "surtirá",
			nosotros: "surtiremos",
			vosotros: "surtiréis",
			Uds: "surtirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "surta",
			tú: "surtas",
			Ud: "surta",
			nosotros: "surtamos",
			vosotros: "surtáis",
			Uds: "surtan",
		},
		Imperfect: {
			yo: "surtiera",
			tú: "surtieras",
			Ud: "surtiera",
			nosotros: "surtiéramos",
			vosotros: "surtierais",
			Uds: "surtieran",
		},
		Imperfect2: {
			yo: "surtiese",
			tú: "surtieses",
			Ud: "surtiese",
			nosotros: "surtiésemos",
			vosotros: "surtieseis",
			Uds: "surtiesen",
		},
		Future: {
			yo: "surtiere",
			tú: "surtieres",
			Ud: "surtiere",
			nosotros: "surtiéremos",
			vosotros: "surtiereis",
			Uds: "surtieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "surte",
			Ud: "surta",
			nosotros: "surtamos",
			vosotros: "surtid",
			Uds: "surtan",
		},
		Negative: {
			tú: "no surtas",
			Ud: "no surta",
			nosotros: "no surtamos",
			vosotros: "no surtáis",
			Uds: "no surtan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy surtiendo",
			tú: "estás surtiendo",
			Ud: "está surtiendo",
			nosotros: "estamos surtiendo",
			vosotros: "estáis surtiendo",
			Uds: "están surtiendo",
		},
		Preterite: {
			yo: "estuve surtiendo",
			tú: "estuviste surtiendo",
			Ud: "estuvo surtiendo",
			nosotros: "estuvimos surtiendo",
			vosotros: "estuvisteis surtiendo",
			Uds: "estuvieron surtiendo",
		},
		Imperfect: {
			Uds: "estaban surtiendo",
			yo: "estaba surtiendo",
			tú: "estabas surtiendo",
			Ud: "estaba surtiendo",
			nosotros: "estábamos surtiendo",
			vosotros: "estabais surtiendo",
		},
		Conditional: {
			yo: "estaría surtiendo",
			tú: "estarías surtiendo",
			Ud: "estaría surtiendo",
			nosotros: "estaríamos surtiendo",
			vosotros: "estaríais surtiendo",
			Uds: "estarían surtiendo",
		},
		Future: {
			yo: "estaré surtiendo",
			tú: "estarás surtiendo",
			Ud: "estará surtiendo",
			nosotros: "estaremos surtiendo",
			vosotros: "estaréis surtiendo",
			Uds: "estarán surtiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he surtido",
			tú: "has surtido",
			Ud: "ha surtido",
			nosotros: "hemos surtido",
			vosotros: "habéis surtido",
			Uds: "han surtido",
		},
		Preterite: {
			yo: "hube surtido",
			tú: "hubiste surtido",
			Ud: "hubo surtido",
			nosotros: "hubimos surtido",
			vosotros: "hubisteis surtido",
			Uds: "hubieron surtido",
		},
		Past: {
			yo: "había surtido",
			tú: "habías surtido",
			Ud: "había surtido",
			nosotros: "habíamos surtido",
			vosotros: "habíais surtido",
			Uds: "habían surtido",
		},
		Conditional: {
			yo: "habría surtido",
			tú: "habrías surtido",
			Ud: "habría surtido",
			nosotros: "habríamos surtido",
			vosotros: "habríais surtido",
			Uds: "habrían surtido",
		},
		Future: {
			yo: "habré surtido",
			tú: "habrás surtido",
			Ud: "habrá surtido",
			nosotros: "habremos surtido",
			vosotros: "habréis surtido",
			Uds: "habrán surtido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya surtido",
			tú: "hayas surtido",
			Ud: "haya surtido",
			nosotros: "hayamos surtido",
			vosotros: "hayáis surtido",
			Uds: "hayan surtido",
		},
		Past: {
			yo: "hubiera surtido",
			tú: "hubieras surtido",
			Ud: "hubiera surtido",
			nosotros: "hubiéramos surtido",
			vosotros: "hubierais surtido",
			Uds: "hubieran surtido",
		},
		Future: {
			yo: "hubiere surtido",
			tú: "hubieres surtido",
			Ud: "hubiere surtido",
			nosotros: "hubiéremos surtido",
			vosotros: "hubiereis surtido",
			Uds: "hubieren surtido",
		},
	},
}
