var suscribir = {
	Indicative: {
		Present: {
			yo: "suscribo",
			tú: "suscribes",
			Ud: "suscribe",
			nosotros: "suscribimos",
			vosotros: "suscribís",
			Uds: "suscriben",
		},
		Preterite: {
			yo: "suscribí",
			tú: "suscribiste",
			Ud: "suscribió",
			nosotros: "suscribimos",
			vosotros: "suscribisteis",
			Uds: "suscribieron",
		},
		Imperfect: {
			yo: "suscribía",
			tú: "suscribías",
			Ud: "suscribía",
			nosotros: "suscribíamos",
			vosotros: "suscribíais",
			Uds: "suscribían",
		},
		Conditional: {
			yo: "suscribiría",
			tú: "suscribirías",
			Ud: "suscribiría",
			nosotros: "suscribiríamos",
			vosotros: "suscribiríais",
			Uds: "suscribirían",
		},
		Future: {
			yo: "suscribiré",
			tú: "suscribirás",
			Ud: "suscribirá",
			nosotros: "suscribiremos",
			vosotros: "suscribiréis",
			Uds: "suscribirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "suscriba",
			tú: "suscribas",
			Ud: "suscriba",
			nosotros: "suscribamos",
			vosotros: "suscribáis",
			Uds: "suscriban",
		},
		Imperfect: {
			yo: "suscribiera",
			tú: "suscribieras",
			Ud: "suscribiera",
			nosotros: "suscribiéramos",
			vosotros: "suscribierais",
			Uds: "suscribieran",
		},
		Imperfect2: {
			yo: "suscribiese",
			tú: "suscribieses",
			Ud: "suscribiese",
			nosotros: "suscribiésemos",
			vosotros: "suscribieseis",
			Uds: "suscribiesen",
		},
		Future: {
			yo: "suscribiere",
			tú: "suscribieres",
			Ud: "suscribiere",
			nosotros: "suscribiéremos",
			vosotros: "suscribiereis",
			Uds: "suscribieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "suscribe",
			Ud: "suscriba",
			nosotros: "suscribamos",
			vosotros: "suscribid",
			Uds: "suscriban",
		},
		Negative: {
			tú: "no suscribas",
			Ud: "no suscriba",
			nosotros: "no suscribamos",
			vosotros: "no suscribáis",
			Uds: "no suscriban",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy suscribiendo",
			tú: "estás suscribiendo",
			Ud: "está suscribiendo",
			nosotros: "estamos suscribiendo",
			vosotros: "estáis suscribiendo",
			Uds: "están suscribiendo",
		},
		Preterite: {
			yo: "estuve suscribiendo",
			tú: "estuviste suscribiendo",
			Ud: "estuvo suscribiendo",
			nosotros: "estuvimos suscribiendo",
			vosotros: "estuvisteis suscribiendo",
			Uds: "estuvieron suscribiendo",
		},
		Imperfect: {
			Uds: "estaban suscribiendo",
			yo: "estaba suscribiendo",
			tú: "estabas suscribiendo",
			Ud: "estaba suscribiendo",
			nosotros: "estábamos suscribiendo",
			vosotros: "estabais suscribiendo",
		},
		Conditional: {
			yo: "estaría suscribiendo",
			tú: "estarías suscribiendo",
			Ud: "estaría suscribiendo",
			nosotros: "estaríamos suscribiendo",
			vosotros: "estaríais suscribiendo",
			Uds: "estarían suscribiendo",
		},
		Future: {
			yo: "estaré suscribiendo",
			tú: "estarás suscribiendo",
			Ud: "estará suscribiendo",
			nosotros: "estaremos suscribiendo",
			vosotros: "estaréis suscribiendo",
			Uds: "estarán suscribiendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he suscrito,suscripto",
			tú: "has suscrito,suscripto",
			Ud: "ha suscrito,suscripto",
			nosotros: "hemos suscrito,suscripto",
			vosotros: "habéis suscrito,suscripto",
			Uds: "han suscrito,suscripto",
		},
		Preterite: {
			yo: "hube suscrito,suscripto",
			tú: "hubiste suscrito,suscripto",
			Ud: "hubo suscrito,suscripto",
			nosotros: "hubimos suscrito,suscripto",
			vosotros: "hubisteis suscrito,suscripto",
			Uds: "hubieron suscrito,suscripto",
		},
		Past: {
			yo: "había suscrito,suscripto",
			tú: "habías suscrito,suscripto",
			Ud: "había suscrito,suscripto",
			nosotros: "habíamos suscrito,suscripto",
			vosotros: "habíais suscrito,suscripto",
			Uds: "habían suscrito,suscripto",
		},
		Conditional: {
			yo: "habría suscrito,suscripto",
			tú: "habrías suscrito,suscripto",
			Ud: "habría suscrito,suscripto",
			nosotros: "habríamos suscrito,suscripto",
			vosotros: "habríais suscrito,suscripto",
			Uds: "habrían suscrito,suscripto",
		},
		Future: {
			yo: "habré suscrito,suscripto",
			tú: "habrás suscrito,suscripto",
			Ud: "habrá suscrito,suscripto",
			nosotros: "habremos suscrito,suscripto",
			vosotros: "habréis suscrito,suscripto",
			Uds: "habrán suscrito,suscripto",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya suscrito,suscripto",
			tú: "hayas suscrito,suscripto",
			Ud: "haya suscrito,suscripto",
			nosotros: "hayamos suscrito,suscripto",
			vosotros: "hayáis suscrito,suscripto",
			Uds: "hayan suscrito,suscripto",
		},
		Past: {
			yo: "hubiera suscrito,suscripto",
			tú: "hubieras suscrito,suscripto",
			Ud: "hubiera suscrito,suscripto",
			nosotros: "hubiéramos suscrito,suscripto",
			vosotros: "hubierais suscrito,suscripto",
			Uds: "hubieran suscrito,suscripto",
		},
		Future: {
			yo: "hubiere suscrito,suscripto",
			tú: "hubieres suscrito,suscripto",
			Ud: "hubiere suscrito,suscripto",
			nosotros: "hubiéremos suscrito,suscripto",
			vosotros: "hubiereis suscrito,suscripto",
			Uds: "hubieren suscrito,suscripto",
		},
	},
}
