var tabletear = {
	Indicative: {
		Present: {
			yo: "tableteo",
			tú: "tableteas",
			Ud: "tabletea",
			nosotros: "tableteamos",
			vosotros: "tableteáis",
			Uds: "tabletean",
		},
		Preterite: {
			yo: "tableteé",
			tú: "tableteaste",
			Ud: "tableteó",
			nosotros: "tableteamos",
			vosotros: "tableteasteis",
			Uds: "tabletearon",
		},
		Imperfect: {
			yo: "tableteaba",
			tú: "tableteabas",
			Ud: "tableteaba",
			nosotros: "tableteábamos",
			vosotros: "tableteabais",
			Uds: "tableteaban",
		},
		Conditional: {
			yo: "tabletearía",
			tú: "tabletearías",
			Ud: "tabletearía",
			nosotros: "tabletearíamos",
			vosotros: "tabletearíais",
			Uds: "tabletearían",
		},
		Future: {
			yo: "tabletearé",
			tú: "tabletearás",
			Ud: "tableteará",
			nosotros: "tabletearemos",
			vosotros: "tabletearéis",
			Uds: "tabletearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "tabletee",
			tú: "tabletees",
			Ud: "tabletee",
			nosotros: "tableteemos",
			vosotros: "tableteéis",
			Uds: "tableteen",
		},
		Imperfect: {
			yo: "tableteara",
			tú: "tabletearas",
			Ud: "tableteara",
			nosotros: "tableteáramos",
			vosotros: "tabletearais",
			Uds: "tabletearan",
		},
		Imperfect2: {
			yo: "tabletease",
			tú: "tableteases",
			Ud: "tabletease",
			nosotros: "tableteásemos",
			vosotros: "tableteaseis",
			Uds: "tableteasen",
		},
		Future: {
			yo: "tableteare",
			tú: "tableteares",
			Ud: "tableteare",
			nosotros: "tableteáremos",
			vosotros: "tableteareis",
			Uds: "tabletearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "tabletea",
			Ud: "tabletee",
			nosotros: "tableteemos",
			vosotros: "tabletead",
			Uds: "tableteen",
		},
		Negative: {
			tú: "no tabletees",
			Ud: "no tabletee",
			nosotros: "no tableteemos",
			vosotros: "no tableteéis",
			Uds: "no tableteen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy tableteando",
			tú: "estás tableteando",
			Ud: "está tableteando",
			nosotros: "estamos tableteando",
			vosotros: "estáis tableteando",
			Uds: "están tableteando",
		},
		Preterite: {
			yo: "estuve tableteando",
			tú: "estuviste tableteando",
			Ud: "estuvo tableteando",
			nosotros: "estuvimos tableteando",
			vosotros: "estuvisteis tableteando",
			Uds: "estuvieron tableteando",
		},
		Imperfect: {
			Uds: "estaban tableteando",
			yo: "estaba tableteando",
			tú: "estabas tableteando",
			Ud: "estaba tableteando",
			nosotros: "estábamos tableteando",
			vosotros: "estabais tableteando",
		},
		Conditional: {
			yo: "estaría tableteando",
			tú: "estarías tableteando",
			Ud: "estaría tableteando",
			nosotros: "estaríamos tableteando",
			vosotros: "estaríais tableteando",
			Uds: "estarían tableteando",
		},
		Future: {
			yo: "estaré tableteando",
			tú: "estarás tableteando",
			Ud: "estará tableteando",
			nosotros: "estaremos tableteando",
			vosotros: "estaréis tableteando",
			Uds: "estarán tableteando",
		},
	},
	Perfect: {
		Present: {
			yo: "he tableteado",
			tú: "has tableteado",
			Ud: "ha tableteado",
			nosotros: "hemos tableteado",
			vosotros: "habéis tableteado",
			Uds: "han tableteado",
		},
		Preterite: {
			yo: "hube tableteado",
			tú: "hubiste tableteado",
			Ud: "hubo tableteado",
			nosotros: "hubimos tableteado",
			vosotros: "hubisteis tableteado",
			Uds: "hubieron tableteado",
		},
		Past: {
			yo: "había tableteado",
			tú: "habías tableteado",
			Ud: "había tableteado",
			nosotros: "habíamos tableteado",
			vosotros: "habíais tableteado",
			Uds: "habían tableteado",
		},
		Conditional: {
			yo: "habría tableteado",
			tú: "habrías tableteado",
			Ud: "habría tableteado",
			nosotros: "habríamos tableteado",
			vosotros: "habríais tableteado",
			Uds: "habrían tableteado",
		},
		Future: {
			yo: "habré tableteado",
			tú: "habrás tableteado",
			Ud: "habrá tableteado",
			nosotros: "habremos tableteado",
			vosotros: "habréis tableteado",
			Uds: "habrán tableteado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya tableteado",
			tú: "hayas tableteado",
			Ud: "haya tableteado",
			nosotros: "hayamos tableteado",
			vosotros: "hayáis tableteado",
			Uds: "hayan tableteado",
		},
		Past: {
			yo: "hubiera tableteado",
			tú: "hubieras tableteado",
			Ud: "hubiera tableteado",
			nosotros: "hubiéramos tableteado",
			vosotros: "hubierais tableteado",
			Uds: "hubieran tableteado",
		},
		Future: {
			yo: "hubiere tableteado",
			tú: "hubieres tableteado",
			Ud: "hubiere tableteado",
			nosotros: "hubiéremos tableteado",
			vosotros: "hubiereis tableteado",
			Uds: "hubieren tableteado",
		},
	},
}
