var tararear = {
	Indicative: {
		Present: {
			yo: "tarareo",
			tú: "tarareas",
			Ud: "tararea",
			nosotros: "tarareamos",
			vosotros: "tarareáis",
			Uds: "tararean",
		},
		Preterite: {
			yo: "tarareé",
			tú: "tarareaste",
			Ud: "tarareó",
			nosotros: "tarareamos",
			vosotros: "tarareasteis",
			Uds: "tararearon",
		},
		Imperfect: {
			yo: "tarareaba",
			tú: "tarareabas",
			Ud: "tarareaba",
			nosotros: "tarareábamos",
			vosotros: "tarareabais",
			Uds: "tarareaban",
		},
		Conditional: {
			yo: "tararearía",
			tú: "tararearías",
			Ud: "tararearía",
			nosotros: "tararearíamos",
			vosotros: "tararearíais",
			Uds: "tararearían",
		},
		Future: {
			yo: "tararearé",
			tú: "tararearás",
			Ud: "tarareará",
			nosotros: "tararearemos",
			vosotros: "tararearéis",
			Uds: "tararearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "tararee",
			tú: "tararees",
			Ud: "tararee",
			nosotros: "tarareemos",
			vosotros: "tarareéis",
			Uds: "tarareen",
		},
		Imperfect: {
			yo: "tarareara",
			tú: "tararearas",
			Ud: "tarareara",
			nosotros: "tarareáramos",
			vosotros: "tararearais",
			Uds: "tararearan",
		},
		Imperfect2: {
			yo: "tararease",
			tú: "tarareases",
			Ud: "tararease",
			nosotros: "tarareásemos",
			vosotros: "tarareaseis",
			Uds: "tarareasen",
		},
		Future: {
			yo: "tarareare",
			tú: "tarareares",
			Ud: "tarareare",
			nosotros: "tarareáremos",
			vosotros: "tarareareis",
			Uds: "tararearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "tararea",
			Ud: "tararee",
			nosotros: "tarareemos",
			vosotros: "tararead",
			Uds: "tarareen",
		},
		Negative: {
			tú: "no tararees",
			Ud: "no tararee",
			nosotros: "no tarareemos",
			vosotros: "no tarareéis",
			Uds: "no tarareen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy tarareando",
			tú: "estás tarareando",
			Ud: "está tarareando",
			nosotros: "estamos tarareando",
			vosotros: "estáis tarareando",
			Uds: "están tarareando",
		},
		Preterite: {
			yo: "estuve tarareando",
			tú: "estuviste tarareando",
			Ud: "estuvo tarareando",
			nosotros: "estuvimos tarareando",
			vosotros: "estuvisteis tarareando",
			Uds: "estuvieron tarareando",
		},
		Imperfect: {
			Uds: "estaban tarareando",
			yo: "estaba tarareando",
			tú: "estabas tarareando",
			Ud: "estaba tarareando",
			nosotros: "estábamos tarareando",
			vosotros: "estabais tarareando",
		},
		Conditional: {
			yo: "estaría tarareando",
			tú: "estarías tarareando",
			Ud: "estaría tarareando",
			nosotros: "estaríamos tarareando",
			vosotros: "estaríais tarareando",
			Uds: "estarían tarareando",
		},
		Future: {
			yo: "estaré tarareando",
			tú: "estarás tarareando",
			Ud: "estará tarareando",
			nosotros: "estaremos tarareando",
			vosotros: "estaréis tarareando",
			Uds: "estarán tarareando",
		},
	},
	Perfect: {
		Present: {
			yo: "he tarareado",
			tú: "has tarareado",
			Ud: "ha tarareado",
			nosotros: "hemos tarareado",
			vosotros: "habéis tarareado",
			Uds: "han tarareado",
		},
		Preterite: {
			yo: "hube tarareado",
			tú: "hubiste tarareado",
			Ud: "hubo tarareado",
			nosotros: "hubimos tarareado",
			vosotros: "hubisteis tarareado",
			Uds: "hubieron tarareado",
		},
		Past: {
			yo: "había tarareado",
			tú: "habías tarareado",
			Ud: "había tarareado",
			nosotros: "habíamos tarareado",
			vosotros: "habíais tarareado",
			Uds: "habían tarareado",
		},
		Conditional: {
			yo: "habría tarareado",
			tú: "habrías tarareado",
			Ud: "habría tarareado",
			nosotros: "habríamos tarareado",
			vosotros: "habríais tarareado",
			Uds: "habrían tarareado",
		},
		Future: {
			yo: "habré tarareado",
			tú: "habrás tarareado",
			Ud: "habrá tarareado",
			nosotros: "habremos tarareado",
			vosotros: "habréis tarareado",
			Uds: "habrán tarareado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya tarareado",
			tú: "hayas tarareado",
			Ud: "haya tarareado",
			nosotros: "hayamos tarareado",
			vosotros: "hayáis tarareado",
			Uds: "hayan tarareado",
		},
		Past: {
			yo: "hubiera tarareado",
			tú: "hubieras tarareado",
			Ud: "hubiera tarareado",
			nosotros: "hubiéramos tarareado",
			vosotros: "hubierais tarareado",
			Uds: "hubieran tarareado",
		},
		Future: {
			yo: "hubiere tarareado",
			tú: "hubieres tarareado",
			Ud: "hubiere tarareado",
			nosotros: "hubiéremos tarareado",
			vosotros: "hubiereis tarareado",
			Uds: "hubieren tarareado",
		},
	},
}
