var tardar = {
	Indicative: {
		Present: {
			yo: "tardo",
			tú: "tardas",
			Ud: "tarda",
			nosotros: "tardamos",
			vosotros: "tardáis",
			Uds: "tardan",
		},
		Preterite: {
			yo: "tardé",
			tú: "tardaste",
			Ud: "tardó",
			nosotros: "tardamos",
			vosotros: "tardasteis",
			Uds: "tardaron",
		},
		Imperfect: {
			yo: "tardaba",
			tú: "tardabas",
			Ud: "tardaba",
			nosotros: "tardábamos",
			vosotros: "tardabais",
			Uds: "tardaban",
		},
		Conditional: {
			yo: "tardaría",
			tú: "tardarías",
			Ud: "tardaría",
			nosotros: "tardaríamos",
			vosotros: "tardaríais",
			Uds: "tardarían",
		},
		Future: {
			yo: "tardaré",
			tú: "tardarás",
			Ud: "tardará",
			nosotros: "tardaremos",
			vosotros: "tardaréis",
			Uds: "tardarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "tarde",
			tú: "tardes",
			Ud: "tarde",
			nosotros: "tardemos",
			vosotros: "tardéis",
			Uds: "tarden",
		},
		Imperfect: {
			yo: "tardara",
			tú: "tardaras",
			Ud: "tardara",
			nosotros: "tardáramos",
			vosotros: "tardarais",
			Uds: "tardaran",
		},
		Imperfect2: {
			yo: "tardase",
			tú: "tardases",
			Ud: "tardase",
			nosotros: "tardásemos",
			vosotros: "tardaseis",
			Uds: "tardasen",
		},
		Future: {
			yo: "tardare",
			tú: "tardares",
			Ud: "tardare",
			nosotros: "tardáremos",
			vosotros: "tardareis",
			Uds: "tardaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "tarda",
			Ud: "tarde",
			nosotros: "tardemos",
			vosotros: "tardad",
			Uds: "tarden",
		},
		Negative: {
			tú: "no tardes",
			Ud: "no tarde",
			nosotros: "no tardemos",
			vosotros: "no tardéis",
			Uds: "no tarden",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy tardando",
			tú: "estás tardando",
			Ud: "está tardando",
			nosotros: "estamos tardando",
			vosotros: "estáis tardando",
			Uds: "están tardando",
		},
		Preterite: {
			yo: "estuve tardando",
			tú: "estuviste tardando",
			Ud: "estuvo tardando",
			nosotros: "estuvimos tardando",
			vosotros: "estuvisteis tardando",
			Uds: "estuvieron tardando",
		},
		Imperfect: {
			Uds: "estaban tardando",
			yo: "estaba tardando",
			tú: "estabas tardando",
			Ud: "estaba tardando",
			nosotros: "estábamos tardando",
			vosotros: "estabais tardando",
		},
		Conditional: {
			yo: "estaría tardando",
			tú: "estarías tardando",
			Ud: "estaría tardando",
			nosotros: "estaríamos tardando",
			vosotros: "estaríais tardando",
			Uds: "estarían tardando",
		},
		Future: {
			yo: "estaré tardando",
			tú: "estarás tardando",
			Ud: "estará tardando",
			nosotros: "estaremos tardando",
			vosotros: "estaréis tardando",
			Uds: "estarán tardando",
		},
	},
	Perfect: {
		Present: {
			yo: "he tardado",
			tú: "has tardado",
			Ud: "ha tardado",
			nosotros: "hemos tardado",
			vosotros: "habéis tardado",
			Uds: "han tardado",
		},
		Preterite: {
			yo: "hube tardado",
			tú: "hubiste tardado",
			Ud: "hubo tardado",
			nosotros: "hubimos tardado",
			vosotros: "hubisteis tardado",
			Uds: "hubieron tardado",
		},
		Past: {
			yo: "había tardado",
			tú: "habías tardado",
			Ud: "había tardado",
			nosotros: "habíamos tardado",
			vosotros: "habíais tardado",
			Uds: "habían tardado",
		},
		Conditional: {
			yo: "habría tardado",
			tú: "habrías tardado",
			Ud: "habría tardado",
			nosotros: "habríamos tardado",
			vosotros: "habríais tardado",
			Uds: "habrían tardado",
		},
		Future: {
			yo: "habré tardado",
			tú: "habrás tardado",
			Ud: "habrá tardado",
			nosotros: "habremos tardado",
			vosotros: "habréis tardado",
			Uds: "habrán tardado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya tardado",
			tú: "hayas tardado",
			Ud: "haya tardado",
			nosotros: "hayamos tardado",
			vosotros: "hayáis tardado",
			Uds: "hayan tardado",
		},
		Past: {
			yo: "hubiera tardado",
			tú: "hubieras tardado",
			Ud: "hubiera tardado",
			nosotros: "hubiéramos tardado",
			vosotros: "hubierais tardado",
			Uds: "hubieran tardado",
		},
		Future: {
			yo: "hubiere tardado",
			tú: "hubieres tardado",
			Ud: "hubiere tardado",
			nosotros: "hubiéremos tardado",
			vosotros: "hubiereis tardado",
			Uds: "hubieren tardado",
		},
	},
}
