var televisar = {
	Indicative: {
		Present: {
			yo: "televiso",
			tú: "televisas",
			Ud: "televisa",
			nosotros: "televisamos",
			vosotros: "televisáis",
			Uds: "televisan",
		},
		Preterite: {
			yo: "televisé",
			tú: "televisaste",
			Ud: "televisó",
			nosotros: "televisamos",
			vosotros: "televisasteis",
			Uds: "televisaron",
		},
		Imperfect: {
			yo: "televisaba",
			tú: "televisabas",
			Ud: "televisaba",
			nosotros: "televisábamos",
			vosotros: "televisabais",
			Uds: "televisaban",
		},
		Conditional: {
			yo: "televisaría",
			tú: "televisarías",
			Ud: "televisaría",
			nosotros: "televisaríamos",
			vosotros: "televisaríais",
			Uds: "televisarían",
		},
		Future: {
			yo: "televisaré",
			tú: "televisarás",
			Ud: "televisará",
			nosotros: "televisaremos",
			vosotros: "televisaréis",
			Uds: "televisarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "televise",
			tú: "televises",
			Ud: "televise",
			nosotros: "televisemos",
			vosotros: "televiséis",
			Uds: "televisen",
		},
		Imperfect: {
			yo: "televisara",
			tú: "televisaras",
			Ud: "televisara",
			nosotros: "televisáramos",
			vosotros: "televisarais",
			Uds: "televisaran",
		},
		Imperfect2: {
			yo: "televisase",
			tú: "televisases",
			Ud: "televisase",
			nosotros: "televisásemos",
			vosotros: "televisaseis",
			Uds: "televisasen",
		},
		Future: {
			yo: "televisare",
			tú: "televisares",
			Ud: "televisare",
			nosotros: "televisáremos",
			vosotros: "televisareis",
			Uds: "televisaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "televisa",
			Ud: "televise",
			nosotros: "televisemos",
			vosotros: "televisad",
			Uds: "televisen",
		},
		Negative: {
			tú: "no televises",
			Ud: "no televise",
			nosotros: "no televisemos",
			vosotros: "no televiséis",
			Uds: "no televisen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy televisando",
			tú: "estás televisando",
			Ud: "está televisando",
			nosotros: "estamos televisando",
			vosotros: "estáis televisando",
			Uds: "están televisando",
		},
		Preterite: {
			yo: "estuve televisando",
			tú: "estuviste televisando",
			Ud: "estuvo televisando",
			nosotros: "estuvimos televisando",
			vosotros: "estuvisteis televisando",
			Uds: "estuvieron televisando",
		},
		Imperfect: {
			Uds: "estaban televisando",
			yo: "estaba televisando",
			tú: "estabas televisando",
			Ud: "estaba televisando",
			nosotros: "estábamos televisando",
			vosotros: "estabais televisando",
		},
		Conditional: {
			yo: "estaría televisando",
			tú: "estarías televisando",
			Ud: "estaría televisando",
			nosotros: "estaríamos televisando",
			vosotros: "estaríais televisando",
			Uds: "estarían televisando",
		},
		Future: {
			yo: "estaré televisando",
			tú: "estarás televisando",
			Ud: "estará televisando",
			nosotros: "estaremos televisando",
			vosotros: "estaréis televisando",
			Uds: "estarán televisando",
		},
	},
	Perfect: {
		Present: {
			yo: "he televisado",
			tú: "has televisado",
			Ud: "ha televisado",
			nosotros: "hemos televisado",
			vosotros: "habéis televisado",
			Uds: "han televisado",
		},
		Preterite: {
			yo: "hube televisado",
			tú: "hubiste televisado",
			Ud: "hubo televisado",
			nosotros: "hubimos televisado",
			vosotros: "hubisteis televisado",
			Uds: "hubieron televisado",
		},
		Past: {
			yo: "había televisado",
			tú: "habías televisado",
			Ud: "había televisado",
			nosotros: "habíamos televisado",
			vosotros: "habíais televisado",
			Uds: "habían televisado",
		},
		Conditional: {
			yo: "habría televisado",
			tú: "habrías televisado",
			Ud: "habría televisado",
			nosotros: "habríamos televisado",
			vosotros: "habríais televisado",
			Uds: "habrían televisado",
		},
		Future: {
			yo: "habré televisado",
			tú: "habrás televisado",
			Ud: "habrá televisado",
			nosotros: "habremos televisado",
			vosotros: "habréis televisado",
			Uds: "habrán televisado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya televisado",
			tú: "hayas televisado",
			Ud: "haya televisado",
			nosotros: "hayamos televisado",
			vosotros: "hayáis televisado",
			Uds: "hayan televisado",
		},
		Past: {
			yo: "hubiera televisado",
			tú: "hubieras televisado",
			Ud: "hubiera televisado",
			nosotros: "hubiéramos televisado",
			vosotros: "hubierais televisado",
			Uds: "hubieran televisado",
		},
		Future: {
			yo: "hubiere televisado",
			tú: "hubieres televisado",
			Ud: "hubiere televisado",
			nosotros: "hubiéremos televisado",
			vosotros: "hubiereis televisado",
			Uds: "hubieren televisado",
		},
	},
}
