var templar = {
	Indicative: {
		Present: {
			yo: "templo,tiemplo",
			tú: "templas,tiemplas",
			Ud: "templa,tiempla",
			nosotros: "templamos",
			vosotros: "templáis",
			Uds: "templan,tiemplan",
		},
		Preterite: {
			yo: "templé",
			tú: "templaste",
			Ud: "templó",
			nosotros: "templamos",
			vosotros: "templasteis",
			Uds: "templaron",
		},
		Imperfect: {
			yo: "templaba",
			tú: "templabas",
			Ud: "templaba",
			nosotros: "templábamos",
			vosotros: "templabais",
			Uds: "templaban",
		},
		Conditional: {
			yo: "templaría",
			tú: "templarías",
			Ud: "templaría",
			nosotros: "templaríamos",
			vosotros: "templaríais",
			Uds: "templarían",
		},
		Future: {
			yo: "templaré",
			tú: "templarás",
			Ud: "templará",
			nosotros: "templaremos",
			vosotros: "templaréis",
			Uds: "templarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "temple,tiemple",
			tú: "temples,tiemples",
			Ud: "temple,tiemple",
			nosotros: "templemos",
			vosotros: "templéis",
			Uds: "templen,tiemplen",
		},
		Imperfect: {
			yo: "templara",
			tú: "templaras",
			Ud: "templara",
			nosotros: "templáramos",
			vosotros: "templarais",
			Uds: "templaran",
		},
		Imperfect2: {
			yo: "templase",
			tú: "templases",
			Ud: "templase",
			nosotros: "templásemos",
			vosotros: "templaseis",
			Uds: "templasen",
		},
		Future: {
			yo: "templare",
			tú: "templares",
			Ud: "templare",
			nosotros: "templáremos",
			vosotros: "templareis",
			Uds: "templaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "templa,tiempla",
			Ud: "temple,tiemple",
			nosotros: "templemos",
			vosotros: "templad",
			Uds: "templen,tiemplen",
		},
		Negative: {
			tú: "no temples,tiemples",
			Ud: "no temple,tiemple",
			nosotros: "no templemos",
			vosotros: "no templéis",
			Uds: "no templen,tiemplen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy templando",
			tú: "estás templando",
			Ud: "está templando",
			nosotros: "estamos templando",
			vosotros: "estáis templando",
			Uds: "están templando",
		},
		Preterite: {
			yo: "estuve templando",
			tú: "estuviste templando",
			Ud: "estuvo templando",
			nosotros: "estuvimos templando",
			vosotros: "estuvisteis templando",
			Uds: "estuvieron templando",
		},
		Imperfect: {
			Uds: "estaban templando",
			yo: "estaba templando",
			tú: "estabas templando",
			Ud: "estaba templando",
			nosotros: "estábamos templando",
			vosotros: "estabais templando",
		},
		Conditional: {
			yo: "estaría templando",
			tú: "estarías templando",
			Ud: "estaría templando",
			nosotros: "estaríamos templando",
			vosotros: "estaríais templando",
			Uds: "estarían templando",
		},
		Future: {
			yo: "estaré templando",
			tú: "estarás templando",
			Ud: "estará templando",
			nosotros: "estaremos templando",
			vosotros: "estaréis templando",
			Uds: "estarán templando",
		},
	},
	Perfect: {
		Present: {
			yo: "he templado",
			tú: "has templado",
			Ud: "ha templado",
			nosotros: "hemos templado",
			vosotros: "habéis templado",
			Uds: "han templado",
		},
		Preterite: {
			yo: "hube templado",
			tú: "hubiste templado",
			Ud: "hubo templado",
			nosotros: "hubimos templado",
			vosotros: "hubisteis templado",
			Uds: "hubieron templado",
		},
		Past: {
			yo: "había templado",
			tú: "habías templado",
			Ud: "había templado",
			nosotros: "habíamos templado",
			vosotros: "habíais templado",
			Uds: "habían templado",
		},
		Conditional: {
			yo: "habría templado",
			tú: "habrías templado",
			Ud: "habría templado",
			nosotros: "habríamos templado",
			vosotros: "habríais templado",
			Uds: "habrían templado",
		},
		Future: {
			yo: "habré templado",
			tú: "habrás templado",
			Ud: "habrá templado",
			nosotros: "habremos templado",
			vosotros: "habréis templado",
			Uds: "habrán templado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya templado",
			tú: "hayas templado",
			Ud: "haya templado",
			nosotros: "hayamos templado",
			vosotros: "hayáis templado",
			Uds: "hayan templado",
		},
		Past: {
			yo: "hubiera templado",
			tú: "hubieras templado",
			Ud: "hubiera templado",
			nosotros: "hubiéramos templado",
			vosotros: "hubierais templado",
			Uds: "hubieran templado",
		},
		Future: {
			yo: "hubiere templado",
			tú: "hubieres templado",
			Ud: "hubiere templado",
			nosotros: "hubiéremos templado",
			vosotros: "hubiereis templado",
			Uds: "hubieren templado",
		},
	},
}
