var timar = {
	Indicative: {
		Present: {
			yo: "timo",
			tú: "timas",
			Ud: "tima",
			nosotros: "timamos",
			vosotros: "timáis",
			Uds: "timan",
		},
		Preterite: {
			yo: "timé",
			tú: "timaste",
			Ud: "timó",
			nosotros: "timamos",
			vosotros: "timasteis",
			Uds: "timaron",
		},
		Imperfect: {
			yo: "timaba",
			tú: "timabas",
			Ud: "timaba",
			nosotros: "timábamos",
			vosotros: "timabais",
			Uds: "timaban",
		},
		Conditional: {
			yo: "timaría",
			tú: "timarías",
			Ud: "timaría",
			nosotros: "timaríamos",
			vosotros: "timaríais",
			Uds: "timarían",
		},
		Future: {
			yo: "timaré",
			tú: "timarás",
			Ud: "timará",
			nosotros: "timaremos",
			vosotros: "timaréis",
			Uds: "timarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "time",
			tú: "times",
			Ud: "time",
			nosotros: "timemos",
			vosotros: "timéis",
			Uds: "timen",
		},
		Imperfect: {
			yo: "timara",
			tú: "timaras",
			Ud: "timara",
			nosotros: "timáramos",
			vosotros: "timarais",
			Uds: "timaran",
		},
		Imperfect2: {
			yo: "timase",
			tú: "timases",
			Ud: "timase",
			nosotros: "timásemos",
			vosotros: "timaseis",
			Uds: "timasen",
		},
		Future: {
			yo: "timare",
			tú: "timares",
			Ud: "timare",
			nosotros: "timáremos",
			vosotros: "timareis",
			Uds: "timaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "tima",
			Ud: "time",
			nosotros: "timemos",
			vosotros: "timad",
			Uds: "timen",
		},
		Negative: {
			tú: "no times",
			Ud: "no time",
			nosotros: "no timemos",
			vosotros: "no timéis",
			Uds: "no timen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy timando",
			tú: "estás timando",
			Ud: "está timando",
			nosotros: "estamos timando",
			vosotros: "estáis timando",
			Uds: "están timando",
		},
		Preterite: {
			yo: "estuve timando",
			tú: "estuviste timando",
			Ud: "estuvo timando",
			nosotros: "estuvimos timando",
			vosotros: "estuvisteis timando",
			Uds: "estuvieron timando",
		},
		Imperfect: {
			Uds: "estaban timando",
			yo: "estaba timando",
			tú: "estabas timando",
			Ud: "estaba timando",
			nosotros: "estábamos timando",
			vosotros: "estabais timando",
		},
		Conditional: {
			yo: "estaría timando",
			tú: "estarías timando",
			Ud: "estaría timando",
			nosotros: "estaríamos timando",
			vosotros: "estaríais timando",
			Uds: "estarían timando",
		},
		Future: {
			yo: "estaré timando",
			tú: "estarás timando",
			Ud: "estará timando",
			nosotros: "estaremos timando",
			vosotros: "estaréis timando",
			Uds: "estarán timando",
		},
	},
	Perfect: {
		Present: {
			yo: "he timado",
			tú: "has timado",
			Ud: "ha timado",
			nosotros: "hemos timado",
			vosotros: "habéis timado",
			Uds: "han timado",
		},
		Preterite: {
			yo: "hube timado",
			tú: "hubiste timado",
			Ud: "hubo timado",
			nosotros: "hubimos timado",
			vosotros: "hubisteis timado",
			Uds: "hubieron timado",
		},
		Past: {
			yo: "había timado",
			tú: "habías timado",
			Ud: "había timado",
			nosotros: "habíamos timado",
			vosotros: "habíais timado",
			Uds: "habían timado",
		},
		Conditional: {
			yo: "habría timado",
			tú: "habrías timado",
			Ud: "habría timado",
			nosotros: "habríamos timado",
			vosotros: "habríais timado",
			Uds: "habrían timado",
		},
		Future: {
			yo: "habré timado",
			tú: "habrás timado",
			Ud: "habrá timado",
			nosotros: "habremos timado",
			vosotros: "habréis timado",
			Uds: "habrán timado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya timado",
			tú: "hayas timado",
			Ud: "haya timado",
			nosotros: "hayamos timado",
			vosotros: "hayáis timado",
			Uds: "hayan timado",
		},
		Past: {
			yo: "hubiera timado",
			tú: "hubieras timado",
			Ud: "hubiera timado",
			nosotros: "hubiéramos timado",
			vosotros: "hubierais timado",
			Uds: "hubieran timado",
		},
		Future: {
			yo: "hubiere timado",
			tú: "hubieres timado",
			Ud: "hubiere timado",
			nosotros: "hubiéremos timado",
			vosotros: "hubiereis timado",
			Uds: "hubieren timado",
		},
	},
}
