var tirar = {
	Indicative: {
		Present: {
			yo: "tiro",
			tú: "tiras",
			Ud: "tira",
			nosotros: "tiramos",
			vosotros: "tiráis",
			Uds: "tiran",
		},
		Preterite: {
			yo: "tiré",
			tú: "tiraste",
			Ud: "tiró",
			nosotros: "tiramos",
			vosotros: "tirasteis",
			Uds: "tiraron",
		},
		Imperfect: {
			yo: "tiraba",
			tú: "tirabas",
			Ud: "tiraba",
			nosotros: "tirábamos",
			vosotros: "tirabais",
			Uds: "tiraban",
		},
		Conditional: {
			yo: "tiraría",
			tú: "tirarías",
			Ud: "tiraría",
			nosotros: "tiraríamos",
			vosotros: "tiraríais",
			Uds: "tirarían",
		},
		Future: {
			yo: "tiraré",
			tú: "tirarás",
			Ud: "tirará",
			nosotros: "tiraremos",
			vosotros: "tiraréis",
			Uds: "tirarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "tire",
			tú: "tires",
			Ud: "tire",
			nosotros: "tiremos",
			vosotros: "tiréis",
			Uds: "tiren",
		},
		Imperfect: {
			yo: "tirara",
			tú: "tiraras",
			Ud: "tirara",
			nosotros: "tiráramos",
			vosotros: "tirarais",
			Uds: "tiraran",
		},
		Imperfect2: {
			yo: "tirase",
			tú: "tirases",
			Ud: "tirase",
			nosotros: "tirásemos",
			vosotros: "tiraseis",
			Uds: "tirasen",
		},
		Future: {
			yo: "tirare",
			tú: "tirares",
			Ud: "tirare",
			nosotros: "tiráremos",
			vosotros: "tirareis",
			Uds: "tiraren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "tira",
			Ud: "tire",
			nosotros: "tiremos",
			vosotros: "tirad",
			Uds: "tiren",
		},
		Negative: {
			tú: "no tires",
			Ud: "no tire",
			nosotros: "no tiremos",
			vosotros: "no tiréis",
			Uds: "no tiren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy tirando",
			tú: "estás tirando",
			Ud: "está tirando",
			nosotros: "estamos tirando",
			vosotros: "estáis tirando",
			Uds: "están tirando",
		},
		Preterite: {
			yo: "estuve tirando",
			tú: "estuviste tirando",
			Ud: "estuvo tirando",
			nosotros: "estuvimos tirando",
			vosotros: "estuvisteis tirando",
			Uds: "estuvieron tirando",
		},
		Imperfect: {
			Uds: "estaban tirando",
			yo: "estaba tirando",
			tú: "estabas tirando",
			Ud: "estaba tirando",
			nosotros: "estábamos tirando",
			vosotros: "estabais tirando",
		},
		Conditional: {
			yo: "estaría tirando",
			tú: "estarías tirando",
			Ud: "estaría tirando",
			nosotros: "estaríamos tirando",
			vosotros: "estaríais tirando",
			Uds: "estarían tirando",
		},
		Future: {
			yo: "estaré tirando",
			tú: "estarás tirando",
			Ud: "estará tirando",
			nosotros: "estaremos tirando",
			vosotros: "estaréis tirando",
			Uds: "estarán tirando",
		},
	},
	Perfect: {
		Present: {
			yo: "he tirado",
			tú: "has tirado",
			Ud: "ha tirado",
			nosotros: "hemos tirado",
			vosotros: "habéis tirado",
			Uds: "han tirado",
		},
		Preterite: {
			yo: "hube tirado",
			tú: "hubiste tirado",
			Ud: "hubo tirado",
			nosotros: "hubimos tirado",
			vosotros: "hubisteis tirado",
			Uds: "hubieron tirado",
		},
		Past: {
			yo: "había tirado",
			tú: "habías tirado",
			Ud: "había tirado",
			nosotros: "habíamos tirado",
			vosotros: "habíais tirado",
			Uds: "habían tirado",
		},
		Conditional: {
			yo: "habría tirado",
			tú: "habrías tirado",
			Ud: "habría tirado",
			nosotros: "habríamos tirado",
			vosotros: "habríais tirado",
			Uds: "habrían tirado",
		},
		Future: {
			yo: "habré tirado",
			tú: "habrás tirado",
			Ud: "habrá tirado",
			nosotros: "habremos tirado",
			vosotros: "habréis tirado",
			Uds: "habrán tirado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya tirado",
			tú: "hayas tirado",
			Ud: "haya tirado",
			nosotros: "hayamos tirado",
			vosotros: "hayáis tirado",
			Uds: "hayan tirado",
		},
		Past: {
			yo: "hubiera tirado",
			tú: "hubieras tirado",
			Ud: "hubiera tirado",
			nosotros: "hubiéramos tirado",
			vosotros: "hubierais tirado",
			Uds: "hubieran tirado",
		},
		Future: {
			yo: "hubiere tirado",
			tú: "hubieres tirado",
			Ud: "hubiere tirado",
			nosotros: "hubiéremos tirado",
			vosotros: "hubiereis tirado",
			Uds: "hubieren tirado",
		},
	},
}
