var titular = {
	Indicative: {
		Present: {
			yo: "titulo",
			tú: "titulas",
			Ud: "titula",
			nosotros: "titulamos",
			vosotros: "tituláis",
			Uds: "titulan",
		},
		Preterite: {
			yo: "titulé",
			tú: "titulaste",
			Ud: "tituló",
			nosotros: "titulamos",
			vosotros: "titulasteis",
			Uds: "titularon",
		},
		Imperfect: {
			yo: "titulaba",
			tú: "titulabas",
			Ud: "titulaba",
			nosotros: "titulábamos",
			vosotros: "titulabais",
			Uds: "titulaban",
		},
		Conditional: {
			yo: "titularía",
			tú: "titularías",
			Ud: "titularía",
			nosotros: "titularíamos",
			vosotros: "titularíais",
			Uds: "titularían",
		},
		Future: {
			yo: "titularé",
			tú: "titularás",
			Ud: "titulará",
			nosotros: "titularemos",
			vosotros: "titularéis",
			Uds: "titularán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "titule",
			tú: "titules",
			Ud: "titule",
			nosotros: "titulemos",
			vosotros: "tituléis",
			Uds: "titulen",
		},
		Imperfect: {
			yo: "titulara",
			tú: "titularas",
			Ud: "titulara",
			nosotros: "tituláramos",
			vosotros: "titularais",
			Uds: "titularan",
		},
		Imperfect2: {
			yo: "titulase",
			tú: "titulases",
			Ud: "titulase",
			nosotros: "titulásemos",
			vosotros: "titulaseis",
			Uds: "titulasen",
		},
		Future: {
			yo: "titulare",
			tú: "titulares",
			Ud: "titulare",
			nosotros: "tituláremos",
			vosotros: "titulareis",
			Uds: "titularen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "titula",
			Ud: "titule",
			nosotros: "titulemos",
			vosotros: "titulad",
			Uds: "titulen",
		},
		Negative: {
			tú: "no titules",
			Ud: "no titule",
			nosotros: "no titulemos",
			vosotros: "no tituléis",
			Uds: "no titulen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy titulando",
			tú: "estás titulando",
			Ud: "está titulando",
			nosotros: "estamos titulando",
			vosotros: "estáis titulando",
			Uds: "están titulando",
		},
		Preterite: {
			yo: "estuve titulando",
			tú: "estuviste titulando",
			Ud: "estuvo titulando",
			nosotros: "estuvimos titulando",
			vosotros: "estuvisteis titulando",
			Uds: "estuvieron titulando",
		},
		Imperfect: {
			Uds: "estaban titulando",
			yo: "estaba titulando",
			tú: "estabas titulando",
			Ud: "estaba titulando",
			nosotros: "estábamos titulando",
			vosotros: "estabais titulando",
		},
		Conditional: {
			yo: "estaría titulando",
			tú: "estarías titulando",
			Ud: "estaría titulando",
			nosotros: "estaríamos titulando",
			vosotros: "estaríais titulando",
			Uds: "estarían titulando",
		},
		Future: {
			yo: "estaré titulando",
			tú: "estarás titulando",
			Ud: "estará titulando",
			nosotros: "estaremos titulando",
			vosotros: "estaréis titulando",
			Uds: "estarán titulando",
		},
	},
	Perfect: {
		Present: {
			yo: "he titulado",
			tú: "has titulado",
			Ud: "ha titulado",
			nosotros: "hemos titulado",
			vosotros: "habéis titulado",
			Uds: "han titulado",
		},
		Preterite: {
			yo: "hube titulado",
			tú: "hubiste titulado",
			Ud: "hubo titulado",
			nosotros: "hubimos titulado",
			vosotros: "hubisteis titulado",
			Uds: "hubieron titulado",
		},
		Past: {
			yo: "había titulado",
			tú: "habías titulado",
			Ud: "había titulado",
			nosotros: "habíamos titulado",
			vosotros: "habíais titulado",
			Uds: "habían titulado",
		},
		Conditional: {
			yo: "habría titulado",
			tú: "habrías titulado",
			Ud: "habría titulado",
			nosotros: "habríamos titulado",
			vosotros: "habríais titulado",
			Uds: "habrían titulado",
		},
		Future: {
			yo: "habré titulado",
			tú: "habrás titulado",
			Ud: "habrá titulado",
			nosotros: "habremos titulado",
			vosotros: "habréis titulado",
			Uds: "habrán titulado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya titulado",
			tú: "hayas titulado",
			Ud: "haya titulado",
			nosotros: "hayamos titulado",
			vosotros: "hayáis titulado",
			Uds: "hayan titulado",
		},
		Past: {
			yo: "hubiera titulado",
			tú: "hubieras titulado",
			Ud: "hubiera titulado",
			nosotros: "hubiéramos titulado",
			vosotros: "hubierais titulado",
			Uds: "hubieran titulado",
		},
		Future: {
			yo: "hubiere titulado",
			tú: "hubieres titulado",
			Ud: "hubiere titulado",
			nosotros: "hubiéremos titulado",
			vosotros: "hubiereis titulado",
			Uds: "hubieren titulado",
		},
	},
}
