var tontear = {
	Indicative: {
		Present: {
			yo: "tonteo",
			tú: "tonteas",
			Ud: "tontea",
			nosotros: "tonteamos",
			vosotros: "tonteáis",
			Uds: "tontean",
		},
		Preterite: {
			yo: "tonteé",
			tú: "tonteaste",
			Ud: "tonteó",
			nosotros: "tonteamos",
			vosotros: "tonteasteis",
			Uds: "tontearon",
		},
		Imperfect: {
			yo: "tonteaba",
			tú: "tonteabas",
			Ud: "tonteaba",
			nosotros: "tonteábamos",
			vosotros: "tonteabais",
			Uds: "tonteaban",
		},
		Conditional: {
			yo: "tontearía",
			tú: "tontearías",
			Ud: "tontearía",
			nosotros: "tontearíamos",
			vosotros: "tontearíais",
			Uds: "tontearían",
		},
		Future: {
			yo: "tontearé",
			tú: "tontearás",
			Ud: "tonteará",
			nosotros: "tontearemos",
			vosotros: "tontearéis",
			Uds: "tontearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "tontee",
			tú: "tontees",
			Ud: "tontee",
			nosotros: "tonteemos",
			vosotros: "tonteéis",
			Uds: "tonteen",
		},
		Imperfect: {
			yo: "tonteara",
			tú: "tontearas",
			Ud: "tonteara",
			nosotros: "tonteáramos",
			vosotros: "tontearais",
			Uds: "tontearan",
		},
		Imperfect2: {
			yo: "tontease",
			tú: "tonteases",
			Ud: "tontease",
			nosotros: "tonteásemos",
			vosotros: "tonteaseis",
			Uds: "tonteasen",
		},
		Future: {
			yo: "tonteare",
			tú: "tonteares",
			Ud: "tonteare",
			nosotros: "tonteáremos",
			vosotros: "tonteareis",
			Uds: "tontearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "tontea",
			Ud: "tontee",
			nosotros: "tonteemos",
			vosotros: "tontead",
			Uds: "tonteen",
		},
		Negative: {
			tú: "no tontees",
			Ud: "no tontee",
			nosotros: "no tonteemos",
			vosotros: "no tonteéis",
			Uds: "no tonteen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy tonteando",
			tú: "estás tonteando",
			Ud: "está tonteando",
			nosotros: "estamos tonteando",
			vosotros: "estáis tonteando",
			Uds: "están tonteando",
		},
		Preterite: {
			yo: "estuve tonteando",
			tú: "estuviste tonteando",
			Ud: "estuvo tonteando",
			nosotros: "estuvimos tonteando",
			vosotros: "estuvisteis tonteando",
			Uds: "estuvieron tonteando",
		},
		Imperfect: {
			Uds: "estaban tonteando",
			yo: "estaba tonteando",
			tú: "estabas tonteando",
			Ud: "estaba tonteando",
			nosotros: "estábamos tonteando",
			vosotros: "estabais tonteando",
		},
		Conditional: {
			yo: "estaría tonteando",
			tú: "estarías tonteando",
			Ud: "estaría tonteando",
			nosotros: "estaríamos tonteando",
			vosotros: "estaríais tonteando",
			Uds: "estarían tonteando",
		},
		Future: {
			yo: "estaré tonteando",
			tú: "estarás tonteando",
			Ud: "estará tonteando",
			nosotros: "estaremos tonteando",
			vosotros: "estaréis tonteando",
			Uds: "estarán tonteando",
		},
	},
	Perfect: {
		Present: {
			yo: "he tonteado",
			tú: "has tonteado",
			Ud: "ha tonteado",
			nosotros: "hemos tonteado",
			vosotros: "habéis tonteado",
			Uds: "han tonteado",
		},
		Preterite: {
			yo: "hube tonteado",
			tú: "hubiste tonteado",
			Ud: "hubo tonteado",
			nosotros: "hubimos tonteado",
			vosotros: "hubisteis tonteado",
			Uds: "hubieron tonteado",
		},
		Past: {
			yo: "había tonteado",
			tú: "habías tonteado",
			Ud: "había tonteado",
			nosotros: "habíamos tonteado",
			vosotros: "habíais tonteado",
			Uds: "habían tonteado",
		},
		Conditional: {
			yo: "habría tonteado",
			tú: "habrías tonteado",
			Ud: "habría tonteado",
			nosotros: "habríamos tonteado",
			vosotros: "habríais tonteado",
			Uds: "habrían tonteado",
		},
		Future: {
			yo: "habré tonteado",
			tú: "habrás tonteado",
			Ud: "habrá tonteado",
			nosotros: "habremos tonteado",
			vosotros: "habréis tonteado",
			Uds: "habrán tonteado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya tonteado",
			tú: "hayas tonteado",
			Ud: "haya tonteado",
			nosotros: "hayamos tonteado",
			vosotros: "hayáis tonteado",
			Uds: "hayan tonteado",
		},
		Past: {
			yo: "hubiera tonteado",
			tú: "hubieras tonteado",
			Ud: "hubiera tonteado",
			nosotros: "hubiéramos tonteado",
			vosotros: "hubierais tonteado",
			Uds: "hubieran tonteado",
		},
		Future: {
			yo: "hubiere tonteado",
			tú: "hubieres tonteado",
			Ud: "hubiere tonteado",
			nosotros: "hubiéremos tonteado",
			vosotros: "hubiereis tonteado",
			Uds: "hubieren tonteado",
		},
	},
}
