var torcer = {
	Indicative: {
		Present: {
			yo: "tuerzo",
			tú: "tuerces",
			Ud: "tuerce",
			nosotros: "torcemos",
			vosotros: "torcéis",
			Uds: "tuercen",
		},
		Preterite: {
			yo: "torcí",
			tú: "torciste",
			Ud: "torció",
			nosotros: "torcimos",
			vosotros: "torcisteis",
			Uds: "torcieron",
		},
		Imperfect: {
			yo: "torcía",
			tú: "torcías",
			Ud: "torcía",
			nosotros: "torcíamos",
			vosotros: "torcíais",
			Uds: "torcían",
		},
		Conditional: {
			yo: "torcería",
			tú: "torcerías",
			Ud: "torcería",
			nosotros: "torceríamos",
			vosotros: "torceríais",
			Uds: "torcerían",
		},
		Future: {
			yo: "torceré",
			tú: "torcerás",
			Ud: "torcerá",
			nosotros: "torceremos",
			vosotros: "torceréis",
			Uds: "torcerán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "tuerza",
			tú: "tuerzas",
			Ud: "tuerza",
			nosotros: "torzamos",
			vosotros: "torzáis",
			Uds: "tuerzan",
		},
		Imperfect: {
			yo: "torciera",
			tú: "torcieras",
			Ud: "torciera",
			nosotros: "torciéramos",
			vosotros: "torcierais",
			Uds: "torcieran",
		},
		Imperfect2: {
			yo: "torciese",
			tú: "torcieses",
			Ud: "torciese",
			nosotros: "torciésemos",
			vosotros: "torcieseis",
			Uds: "torciesen",
		},
		Future: {
			yo: "torciere",
			tú: "torcieres",
			Ud: "torciere",
			nosotros: "torciéremos",
			vosotros: "torciereis",
			Uds: "torcieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "tuerce",
			Ud: "tuerza",
			nosotros: "torzamos",
			vosotros: "torced",
			Uds: "tuerzan",
		},
		Negative: {
			tú: "no tuerzas",
			Ud: "no tuerza",
			nosotros: "no torzamos",
			vosotros: "no torzáis",
			Uds: "no tuerzan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy torciendo",
			tú: "estás torciendo",
			Ud: "está torciendo",
			nosotros: "estamos torciendo",
			vosotros: "estáis torciendo",
			Uds: "están torciendo",
		},
		Preterite: {
			yo: "estuve torciendo",
			tú: "estuviste torciendo",
			Ud: "estuvo torciendo",
			nosotros: "estuvimos torciendo",
			vosotros: "estuvisteis torciendo",
			Uds: "estuvieron torciendo",
		},
		Imperfect: {
			Uds: "estaban torciendo",
			yo: "estaba torciendo",
			tú: "estabas torciendo",
			Ud: "estaba torciendo",
			nosotros: "estábamos torciendo",
			vosotros: "estabais torciendo",
		},
		Conditional: {
			yo: "estaría torciendo",
			tú: "estarías torciendo",
			Ud: "estaría torciendo",
			nosotros: "estaríamos torciendo",
			vosotros: "estaríais torciendo",
			Uds: "estarían torciendo",
		},
		Future: {
			yo: "estaré torciendo",
			tú: "estarás torciendo",
			Ud: "estará torciendo",
			nosotros: "estaremos torciendo",
			vosotros: "estaréis torciendo",
			Uds: "estarán torciendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he torcido,tuerto",
			tú: "has torcido,tuerto",
			Ud: "ha torcido,tuerto",
			nosotros: "hemos torcido,tuerto",
			vosotros: "habéis torcido,tuerto",
			Uds: "han torcido,tuerto",
		},
		Preterite: {
			yo: "hube torcido,tuerto",
			tú: "hubiste torcido,tuerto",
			Ud: "hubo torcido,tuerto",
			nosotros: "hubimos torcido,tuerto",
			vosotros: "hubisteis torcido,tuerto",
			Uds: "hubieron torcido,tuerto",
		},
		Past: {
			yo: "había torcido,tuerto",
			tú: "habías torcido,tuerto",
			Ud: "había torcido,tuerto",
			nosotros: "habíamos torcido,tuerto",
			vosotros: "habíais torcido,tuerto",
			Uds: "habían torcido,tuerto",
		},
		Conditional: {
			yo: "habría torcido,tuerto",
			tú: "habrías torcido,tuerto",
			Ud: "habría torcido,tuerto",
			nosotros: "habríamos torcido,tuerto",
			vosotros: "habríais torcido,tuerto",
			Uds: "habrían torcido,tuerto",
		},
		Future: {
			yo: "habré torcido,tuerto",
			tú: "habrás torcido,tuerto",
			Ud: "habrá torcido,tuerto",
			nosotros: "habremos torcido,tuerto",
			vosotros: "habréis torcido,tuerto",
			Uds: "habrán torcido,tuerto",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya torcido,tuerto",
			tú: "hayas torcido,tuerto",
			Ud: "haya torcido,tuerto",
			nosotros: "hayamos torcido,tuerto",
			vosotros: "hayáis torcido,tuerto",
			Uds: "hayan torcido,tuerto",
		},
		Past: {
			yo: "hubiera torcido,tuerto",
			tú: "hubieras torcido,tuerto",
			Ud: "hubiera torcido,tuerto",
			nosotros: "hubiéramos torcido,tuerto",
			vosotros: "hubierais torcido,tuerto",
			Uds: "hubieran torcido,tuerto",
		},
		Future: {
			yo: "hubiere torcido,tuerto",
			tú: "hubieres torcido,tuerto",
			Ud: "hubiere torcido,tuerto",
			nosotros: "hubiéremos torcido,tuerto",
			vosotros: "hubiereis torcido,tuerto",
			Uds: "hubieren torcido,tuerto",
		},
	},
}
