var tornear = {
	Indicative: {
		Present: {
			yo: "torneo",
			tú: "torneas",
			Ud: "tornea",
			nosotros: "torneamos",
			vosotros: "torneáis",
			Uds: "tornean",
		},
		Preterite: {
			yo: "torneé",
			tú: "torneaste",
			Ud: "torneó",
			nosotros: "torneamos",
			vosotros: "torneasteis",
			Uds: "tornearon",
		},
		Imperfect: {
			yo: "torneaba",
			tú: "torneabas",
			Ud: "torneaba",
			nosotros: "torneábamos",
			vosotros: "torneabais",
			Uds: "torneaban",
		},
		Conditional: {
			yo: "tornearía",
			tú: "tornearías",
			Ud: "tornearía",
			nosotros: "tornearíamos",
			vosotros: "tornearíais",
			Uds: "tornearían",
		},
		Future: {
			yo: "tornearé",
			tú: "tornearás",
			Ud: "torneará",
			nosotros: "tornearemos",
			vosotros: "tornearéis",
			Uds: "tornearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "tornee",
			tú: "tornees",
			Ud: "tornee",
			nosotros: "torneemos",
			vosotros: "torneéis",
			Uds: "torneen",
		},
		Imperfect: {
			yo: "torneara",
			tú: "tornearas",
			Ud: "torneara",
			nosotros: "torneáramos",
			vosotros: "tornearais",
			Uds: "tornearan",
		},
		Imperfect2: {
			yo: "tornease",
			tú: "torneases",
			Ud: "tornease",
			nosotros: "torneásemos",
			vosotros: "torneaseis",
			Uds: "torneasen",
		},
		Future: {
			yo: "torneare",
			tú: "torneares",
			Ud: "torneare",
			nosotros: "torneáremos",
			vosotros: "torneareis",
			Uds: "tornearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "tornea",
			Ud: "tornee",
			nosotros: "torneemos",
			vosotros: "tornead",
			Uds: "torneen",
		},
		Negative: {
			tú: "no tornees",
			Ud: "no tornee",
			nosotros: "no torneemos",
			vosotros: "no torneéis",
			Uds: "no torneen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy torneando",
			tú: "estás torneando",
			Ud: "está torneando",
			nosotros: "estamos torneando",
			vosotros: "estáis torneando",
			Uds: "están torneando",
		},
		Preterite: {
			yo: "estuve torneando",
			tú: "estuviste torneando",
			Ud: "estuvo torneando",
			nosotros: "estuvimos torneando",
			vosotros: "estuvisteis torneando",
			Uds: "estuvieron torneando",
		},
		Imperfect: {
			Uds: "estaban torneando",
			yo: "estaba torneando",
			tú: "estabas torneando",
			Ud: "estaba torneando",
			nosotros: "estábamos torneando",
			vosotros: "estabais torneando",
		},
		Conditional: {
			yo: "estaría torneando",
			tú: "estarías torneando",
			Ud: "estaría torneando",
			nosotros: "estaríamos torneando",
			vosotros: "estaríais torneando",
			Uds: "estarían torneando",
		},
		Future: {
			yo: "estaré torneando",
			tú: "estarás torneando",
			Ud: "estará torneando",
			nosotros: "estaremos torneando",
			vosotros: "estaréis torneando",
			Uds: "estarán torneando",
		},
	},
	Perfect: {
		Present: {
			yo: "he torneado",
			tú: "has torneado",
			Ud: "ha torneado",
			nosotros: "hemos torneado",
			vosotros: "habéis torneado",
			Uds: "han torneado",
		},
		Preterite: {
			yo: "hube torneado",
			tú: "hubiste torneado",
			Ud: "hubo torneado",
			nosotros: "hubimos torneado",
			vosotros: "hubisteis torneado",
			Uds: "hubieron torneado",
		},
		Past: {
			yo: "había torneado",
			tú: "habías torneado",
			Ud: "había torneado",
			nosotros: "habíamos torneado",
			vosotros: "habíais torneado",
			Uds: "habían torneado",
		},
		Conditional: {
			yo: "habría torneado",
			tú: "habrías torneado",
			Ud: "habría torneado",
			nosotros: "habríamos torneado",
			vosotros: "habríais torneado",
			Uds: "habrían torneado",
		},
		Future: {
			yo: "habré torneado",
			tú: "habrás torneado",
			Ud: "habrá torneado",
			nosotros: "habremos torneado",
			vosotros: "habréis torneado",
			Uds: "habrán torneado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya torneado",
			tú: "hayas torneado",
			Ud: "haya torneado",
			nosotros: "hayamos torneado",
			vosotros: "hayáis torneado",
			Uds: "hayan torneado",
		},
		Past: {
			yo: "hubiera torneado",
			tú: "hubieras torneado",
			Ud: "hubiera torneado",
			nosotros: "hubiéramos torneado",
			vosotros: "hubierais torneado",
			Uds: "hubieran torneado",
		},
		Future: {
			yo: "hubiere torneado",
			tú: "hubieres torneado",
			Ud: "hubiere torneado",
			nosotros: "hubiéremos torneado",
			vosotros: "hubiereis torneado",
			Uds: "hubieren torneado",
		},
	},
}
