var traducir = {
	Indicative: {
		Present: {
			yo: "traduzco",
			tú: "traduces",
			Ud: "traduce",
			nosotros: "traducimos",
			vosotros: "traducís",
			Uds: "traducen",
		},
		Preterite: {
			yo: "traduje",
			tú: "tradujiste",
			Ud: "tradujo",
			nosotros: "tradujimos",
			vosotros: "tradujisteis",
			Uds: "tradujeron",
		},
		Imperfect: {
			yo: "traducía",
			tú: "traducías",
			Ud: "traducía",
			nosotros: "traducíamos",
			vosotros: "traducíais",
			Uds: "traducían",
		},
		Conditional: {
			yo: "traduciría",
			tú: "traducirías",
			Ud: "traduciría",
			nosotros: "traduciríamos",
			vosotros: "traduciríais",
			Uds: "traducirían",
		},
		Future: {
			yo: "traduciré",
			tú: "traducirás",
			Ud: "traducirá",
			nosotros: "traduciremos",
			vosotros: "traduciréis",
			Uds: "traducirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "traduzca",
			tú: "traduzcas",
			Ud: "traduzca",
			nosotros: "traduzcamos",
			vosotros: "traduzcáis",
			Uds: "traduzcan",
		},
		Imperfect: {
			yo: "tradujera",
			tú: "tradujeras",
			Ud: "tradujera",
			nosotros: "tradujéramos",
			vosotros: "tradujerais",
			Uds: "tradujeran",
		},
		Imperfect2: {
			yo: "tradujese",
			tú: "tradujeses",
			Ud: "tradujese",
			nosotros: "tradujésemos",
			vosotros: "tradujeseis",
			Uds: "tradujesen",
		},
		Future: {
			yo: "tradujere",
			tú: "tradujeres",
			Ud: "tradujere",
			nosotros: "tradujéremos",
			vosotros: "tradujereis",
			Uds: "tradujeren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "traduce",
			Ud: "traduzca",
			nosotros: "traduzcamos",
			vosotros: "traducid",
			Uds: "traduzcan",
		},
		Negative: {
			tú: "no traduzcas",
			Ud: "no traduzca",
			nosotros: "no traduzcamos",
			vosotros: "no traduzcáis",
			Uds: "no traduzcan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy traduciendo",
			tú: "estás traduciendo",
			Ud: "está traduciendo",
			nosotros: "estamos traduciendo",
			vosotros: "estáis traduciendo",
			Uds: "están traduciendo",
		},
		Preterite: {
			yo: "estuve traduciendo",
			tú: "estuviste traduciendo",
			Ud: "estuvo traduciendo",
			nosotros: "estuvimos traduciendo",
			vosotros: "estuvisteis traduciendo",
			Uds: "estuvieron traduciendo",
		},
		Imperfect: {
			Uds: "estaban traduciendo",
			yo: "estaba traduciendo",
			tú: "estabas traduciendo",
			Ud: "estaba traduciendo",
			nosotros: "estábamos traduciendo",
			vosotros: "estabais traduciendo",
		},
		Conditional: {
			yo: "estaría traduciendo",
			tú: "estarías traduciendo",
			Ud: "estaría traduciendo",
			nosotros: "estaríamos traduciendo",
			vosotros: "estaríais traduciendo",
			Uds: "estarían traduciendo",
		},
		Future: {
			yo: "estaré traduciendo",
			tú: "estarás traduciendo",
			Ud: "estará traduciendo",
			nosotros: "estaremos traduciendo",
			vosotros: "estaréis traduciendo",
			Uds: "estarán traduciendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he traducido",
			tú: "has traducido",
			Ud: "ha traducido",
			nosotros: "hemos traducido",
			vosotros: "habéis traducido",
			Uds: "han traducido",
		},
		Preterite: {
			yo: "hube traducido",
			tú: "hubiste traducido",
			Ud: "hubo traducido",
			nosotros: "hubimos traducido",
			vosotros: "hubisteis traducido",
			Uds: "hubieron traducido",
		},
		Past: {
			yo: "había traducido",
			tú: "habías traducido",
			Ud: "había traducido",
			nosotros: "habíamos traducido",
			vosotros: "habíais traducido",
			Uds: "habían traducido",
		},
		Conditional: {
			yo: "habría traducido",
			tú: "habrías traducido",
			Ud: "habría traducido",
			nosotros: "habríamos traducido",
			vosotros: "habríais traducido",
			Uds: "habrían traducido",
		},
		Future: {
			yo: "habré traducido",
			tú: "habrás traducido",
			Ud: "habrá traducido",
			nosotros: "habremos traducido",
			vosotros: "habréis traducido",
			Uds: "habrán traducido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya traducido",
			tú: "hayas traducido",
			Ud: "haya traducido",
			nosotros: "hayamos traducido",
			vosotros: "hayáis traducido",
			Uds: "hayan traducido",
		},
		Past: {
			yo: "hubiera traducido",
			tú: "hubieras traducido",
			Ud: "hubiera traducido",
			nosotros: "hubiéramos traducido",
			vosotros: "hubierais traducido",
			Uds: "hubieran traducido",
		},
		Future: {
			yo: "hubiere traducido",
			tú: "hubieres traducido",
			Ud: "hubiere traducido",
			nosotros: "hubiéremos traducido",
			vosotros: "hubiereis traducido",
			Uds: "hubieren traducido",
		},
	},
}
