var transar = {
	Indicative: {
		Present: {
			yo: "transo",
			tú: "transas",
			Ud: "transa",
			nosotros: "transamos",
			vosotros: "transáis",
			Uds: "transan",
		},
		Preterite: {
			yo: "transé",
			tú: "transaste",
			Ud: "transó",
			nosotros: "transamos",
			vosotros: "transasteis",
			Uds: "transaron",
		},
		Imperfect: {
			yo: "transaba",
			tú: "transabas",
			Ud: "transaba",
			nosotros: "transábamos",
			vosotros: "transabais",
			Uds: "transaban",
		},
		Conditional: {
			yo: "transaría",
			tú: "transarías",
			Ud: "transaría",
			nosotros: "transaríamos",
			vosotros: "transaríais",
			Uds: "transarían",
		},
		Future: {
			yo: "transaré",
			tú: "transarás",
			Ud: "transará",
			nosotros: "transaremos",
			vosotros: "transaréis",
			Uds: "transarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "transe",
			tú: "transes",
			Ud: "transe",
			nosotros: "transemos",
			vosotros: "transéis",
			Uds: "transen",
		},
		Imperfect: {
			yo: "transara",
			tú: "transaras",
			Ud: "transara",
			nosotros: "transáramos",
			vosotros: "transarais",
			Uds: "transaran",
		},
		Imperfect2: {
			yo: "transase",
			tú: "transases",
			Ud: "transase",
			nosotros: "transásemos",
			vosotros: "transaseis",
			Uds: "transasen",
		},
		Future: {
			yo: "transare",
			tú: "transares",
			Ud: "transare",
			nosotros: "transáremos",
			vosotros: "transareis",
			Uds: "transaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "transa",
			Ud: "transe",
			nosotros: "transemos",
			vosotros: "transad",
			Uds: "transen",
		},
		Negative: {
			tú: "no transes",
			Ud: "no transe",
			nosotros: "no transemos",
			vosotros: "no transéis",
			Uds: "no transen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy transando",
			tú: "estás transando",
			Ud: "está transando",
			nosotros: "estamos transando",
			vosotros: "estáis transando",
			Uds: "están transando",
		},
		Preterite: {
			yo: "estuve transando",
			tú: "estuviste transando",
			Ud: "estuvo transando",
			nosotros: "estuvimos transando",
			vosotros: "estuvisteis transando",
			Uds: "estuvieron transando",
		},
		Imperfect: {
			Uds: "estaban transando",
			yo: "estaba transando",
			tú: "estabas transando",
			Ud: "estaba transando",
			nosotros: "estábamos transando",
			vosotros: "estabais transando",
		},
		Conditional: {
			yo: "estaría transando",
			tú: "estarías transando",
			Ud: "estaría transando",
			nosotros: "estaríamos transando",
			vosotros: "estaríais transando",
			Uds: "estarían transando",
		},
		Future: {
			yo: "estaré transando",
			tú: "estarás transando",
			Ud: "estará transando",
			nosotros: "estaremos transando",
			vosotros: "estaréis transando",
			Uds: "estarán transando",
		},
	},
	Perfect: {
		Present: {
			yo: "he transado",
			tú: "has transado",
			Ud: "ha transado",
			nosotros: "hemos transado",
			vosotros: "habéis transado",
			Uds: "han transado",
		},
		Preterite: {
			yo: "hube transado",
			tú: "hubiste transado",
			Ud: "hubo transado",
			nosotros: "hubimos transado",
			vosotros: "hubisteis transado",
			Uds: "hubieron transado",
		},
		Past: {
			yo: "había transado",
			tú: "habías transado",
			Ud: "había transado",
			nosotros: "habíamos transado",
			vosotros: "habíais transado",
			Uds: "habían transado",
		},
		Conditional: {
			yo: "habría transado",
			tú: "habrías transado",
			Ud: "habría transado",
			nosotros: "habríamos transado",
			vosotros: "habríais transado",
			Uds: "habrían transado",
		},
		Future: {
			yo: "habré transado",
			tú: "habrás transado",
			Ud: "habrá transado",
			nosotros: "habremos transado",
			vosotros: "habréis transado",
			Uds: "habrán transado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya transado",
			tú: "hayas transado",
			Ud: "haya transado",
			nosotros: "hayamos transado",
			vosotros: "hayáis transado",
			Uds: "hayan transado",
		},
		Past: {
			yo: "hubiera transado",
			tú: "hubieras transado",
			Ud: "hubiera transado",
			nosotros: "hubiéramos transado",
			vosotros: "hubierais transado",
			Uds: "hubieran transado",
		},
		Future: {
			yo: "hubiere transado",
			tú: "hubieres transado",
			Ud: "hubiere transado",
			nosotros: "hubiéremos transado",
			vosotros: "hubiereis transado",
			Uds: "hubieren transado",
		},
	},
}
