var trasplantar = {
	Indicative: {
		Present: {
			yo: "trasplanto",
			tú: "trasplantas",
			Ud: "trasplanta",
			nosotros: "trasplantamos",
			vosotros: "trasplantáis",
			Uds: "trasplantan",
		},
		Preterite: {
			yo: "trasplanté",
			tú: "trasplantaste",
			Ud: "trasplantó",
			nosotros: "trasplantamos",
			vosotros: "trasplantasteis",
			Uds: "trasplantaron",
		},
		Imperfect: {
			yo: "trasplantaba",
			tú: "trasplantabas",
			Ud: "trasplantaba",
			nosotros: "trasplantábamos",
			vosotros: "trasplantabais",
			Uds: "trasplantaban",
		},
		Conditional: {
			yo: "trasplantaría",
			tú: "trasplantarías",
			Ud: "trasplantaría",
			nosotros: "trasplantaríamos",
			vosotros: "trasplantaríais",
			Uds: "trasplantarían",
		},
		Future: {
			yo: "trasplantaré",
			tú: "trasplantarás",
			Ud: "trasplantará",
			nosotros: "trasplantaremos",
			vosotros: "trasplantaréis",
			Uds: "trasplantarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "trasplante",
			tú: "trasplantes",
			Ud: "trasplante",
			nosotros: "trasplantemos",
			vosotros: "trasplantéis",
			Uds: "trasplanten",
		},
		Imperfect: {
			yo: "trasplantara",
			tú: "trasplantaras",
			Ud: "trasplantara",
			nosotros: "trasplantáramos",
			vosotros: "trasplantarais",
			Uds: "trasplantaran",
		},
		Imperfect2: {
			yo: "trasplantase",
			tú: "trasplantases",
			Ud: "trasplantase",
			nosotros: "trasplantásemos",
			vosotros: "trasplantaseis",
			Uds: "trasplantasen",
		},
		Future: {
			yo: "trasplantare",
			tú: "trasplantares",
			Ud: "trasplantare",
			nosotros: "trasplantáremos",
			vosotros: "trasplantareis",
			Uds: "trasplantaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "trasplanta",
			Ud: "trasplante",
			nosotros: "trasplantemos",
			vosotros: "trasplantad",
			Uds: "trasplanten",
		},
		Negative: {
			tú: "no trasplantes",
			Ud: "no trasplante",
			nosotros: "no trasplantemos",
			vosotros: "no trasplantéis",
			Uds: "no trasplanten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy trasplantando",
			tú: "estás trasplantando",
			Ud: "está trasplantando",
			nosotros: "estamos trasplantando",
			vosotros: "estáis trasplantando",
			Uds: "están trasplantando",
		},
		Preterite: {
			yo: "estuve trasplantando",
			tú: "estuviste trasplantando",
			Ud: "estuvo trasplantando",
			nosotros: "estuvimos trasplantando",
			vosotros: "estuvisteis trasplantando",
			Uds: "estuvieron trasplantando",
		},
		Imperfect: {
			Uds: "estaban trasplantando",
			yo: "estaba trasplantando",
			tú: "estabas trasplantando",
			Ud: "estaba trasplantando",
			nosotros: "estábamos trasplantando",
			vosotros: "estabais trasplantando",
		},
		Conditional: {
			yo: "estaría trasplantando",
			tú: "estarías trasplantando",
			Ud: "estaría trasplantando",
			nosotros: "estaríamos trasplantando",
			vosotros: "estaríais trasplantando",
			Uds: "estarían trasplantando",
		},
		Future: {
			yo: "estaré trasplantando",
			tú: "estarás trasplantando",
			Ud: "estará trasplantando",
			nosotros: "estaremos trasplantando",
			vosotros: "estaréis trasplantando",
			Uds: "estarán trasplantando",
		},
	},
	Perfect: {
		Present: {
			yo: "he trasplantado",
			tú: "has trasplantado",
			Ud: "ha trasplantado",
			nosotros: "hemos trasplantado",
			vosotros: "habéis trasplantado",
			Uds: "han trasplantado",
		},
		Preterite: {
			yo: "hube trasplantado",
			tú: "hubiste trasplantado",
			Ud: "hubo trasplantado",
			nosotros: "hubimos trasplantado",
			vosotros: "hubisteis trasplantado",
			Uds: "hubieron trasplantado",
		},
		Past: {
			yo: "había trasplantado",
			tú: "habías trasplantado",
			Ud: "había trasplantado",
			nosotros: "habíamos trasplantado",
			vosotros: "habíais trasplantado",
			Uds: "habían trasplantado",
		},
		Conditional: {
			yo: "habría trasplantado",
			tú: "habrías trasplantado",
			Ud: "habría trasplantado",
			nosotros: "habríamos trasplantado",
			vosotros: "habríais trasplantado",
			Uds: "habrían trasplantado",
		},
		Future: {
			yo: "habré trasplantado",
			tú: "habrás trasplantado",
			Ud: "habrá trasplantado",
			nosotros: "habremos trasplantado",
			vosotros: "habréis trasplantado",
			Uds: "habrán trasplantado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya trasplantado",
			tú: "hayas trasplantado",
			Ud: "haya trasplantado",
			nosotros: "hayamos trasplantado",
			vosotros: "hayáis trasplantado",
			Uds: "hayan trasplantado",
		},
		Past: {
			yo: "hubiera trasplantado",
			tú: "hubieras trasplantado",
			Ud: "hubiera trasplantado",
			nosotros: "hubiéramos trasplantado",
			vosotros: "hubierais trasplantado",
			Uds: "hubieran trasplantado",
		},
		Future: {
			yo: "hubiere trasplantado",
			tú: "hubieres trasplantado",
			Ud: "hubiere trasplantado",
			nosotros: "hubiéremos trasplantado",
			vosotros: "hubiereis trasplantado",
			Uds: "hubieren trasplantado",
		},
	},
}
