var tratar = {
	Indicative: {
		Present: {
			yo: "trato",
			tú: "tratas",
			Ud: "trata",
			nosotros: "tratamos",
			vosotros: "tratáis",
			Uds: "tratan",
		},
		Preterite: {
			yo: "traté",
			tú: "trataste",
			Ud: "trató",
			nosotros: "tratamos",
			vosotros: "tratasteis",
			Uds: "trataron",
		},
		Imperfect: {
			yo: "trataba",
			tú: "tratabas",
			Ud: "trataba",
			nosotros: "tratábamos",
			vosotros: "tratabais",
			Uds: "trataban",
		},
		Conditional: {
			yo: "trataría",
			tú: "tratarías",
			Ud: "trataría",
			nosotros: "trataríamos",
			vosotros: "trataríais",
			Uds: "tratarían",
		},
		Future: {
			yo: "trataré",
			tú: "tratarás",
			Ud: "tratará",
			nosotros: "trataremos",
			vosotros: "trataréis",
			Uds: "tratarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "trate",
			tú: "trates",
			Ud: "trate",
			nosotros: "tratemos",
			vosotros: "tratéis",
			Uds: "traten",
		},
		Imperfect: {
			yo: "tratara",
			tú: "trataras",
			Ud: "tratara",
			nosotros: "tratáramos",
			vosotros: "tratarais",
			Uds: "trataran",
		},
		Imperfect2: {
			yo: "tratase",
			tú: "tratases",
			Ud: "tratase",
			nosotros: "tratásemos",
			vosotros: "trataseis",
			Uds: "tratasen",
		},
		Future: {
			yo: "tratare",
			tú: "tratares",
			Ud: "tratare",
			nosotros: "tratáremos",
			vosotros: "tratareis",
			Uds: "trataren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "trata",
			Ud: "trate",
			nosotros: "tratemos",
			vosotros: "tratad",
			Uds: "traten",
		},
		Negative: {
			tú: "no trates",
			Ud: "no trate",
			nosotros: "no tratemos",
			vosotros: "no tratéis",
			Uds: "no traten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy tratando",
			tú: "estás tratando",
			Ud: "está tratando",
			nosotros: "estamos tratando",
			vosotros: "estáis tratando",
			Uds: "están tratando",
		},
		Preterite: {
			yo: "estuve tratando",
			tú: "estuviste tratando",
			Ud: "estuvo tratando",
			nosotros: "estuvimos tratando",
			vosotros: "estuvisteis tratando",
			Uds: "estuvieron tratando",
		},
		Imperfect: {
			Uds: "estaban tratando",
			yo: "estaba tratando",
			tú: "estabas tratando",
			Ud: "estaba tratando",
			nosotros: "estábamos tratando",
			vosotros: "estabais tratando",
		},
		Conditional: {
			yo: "estaría tratando",
			tú: "estarías tratando",
			Ud: "estaría tratando",
			nosotros: "estaríamos tratando",
			vosotros: "estaríais tratando",
			Uds: "estarían tratando",
		},
		Future: {
			yo: "estaré tratando",
			tú: "estarás tratando",
			Ud: "estará tratando",
			nosotros: "estaremos tratando",
			vosotros: "estaréis tratando",
			Uds: "estarán tratando",
		},
	},
	Perfect: {
		Present: {
			yo: "he tratado",
			tú: "has tratado",
			Ud: "ha tratado",
			nosotros: "hemos tratado",
			vosotros: "habéis tratado",
			Uds: "han tratado",
		},
		Preterite: {
			yo: "hube tratado",
			tú: "hubiste tratado",
			Ud: "hubo tratado",
			nosotros: "hubimos tratado",
			vosotros: "hubisteis tratado",
			Uds: "hubieron tratado",
		},
		Past: {
			yo: "había tratado",
			tú: "habías tratado",
			Ud: "había tratado",
			nosotros: "habíamos tratado",
			vosotros: "habíais tratado",
			Uds: "habían tratado",
		},
		Conditional: {
			yo: "habría tratado",
			tú: "habrías tratado",
			Ud: "habría tratado",
			nosotros: "habríamos tratado",
			vosotros: "habríais tratado",
			Uds: "habrían tratado",
		},
		Future: {
			yo: "habré tratado",
			tú: "habrás tratado",
			Ud: "habrá tratado",
			nosotros: "habremos tratado",
			vosotros: "habréis tratado",
			Uds: "habrán tratado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya tratado",
			tú: "hayas tratado",
			Ud: "haya tratado",
			nosotros: "hayamos tratado",
			vosotros: "hayáis tratado",
			Uds: "hayan tratado",
		},
		Past: {
			yo: "hubiera tratado",
			tú: "hubieras tratado",
			Ud: "hubiera tratado",
			nosotros: "hubiéramos tratado",
			vosotros: "hubierais tratado",
			Uds: "hubieran tratado",
		},
		Future: {
			yo: "hubiere tratado",
			tú: "hubieres tratado",
			Ud: "hubiere tratado",
			nosotros: "hubiéremos tratado",
			vosotros: "hubiereis tratado",
			Uds: "hubieren tratado",
		},
	},
}
