var tronar = {
	Indicative: {
		Present: {
			yo: "trueno",
			tú: "truenas",
			Ud: "truena",
			nosotros: "tronamos",
			vosotros: "tronáis",
			Uds: "truenan",
		},
		Preterite: {
			yo: "troné",
			tú: "tronaste",
			Ud: "tronó",
			nosotros: "tronamos",
			vosotros: "tronasteis",
			Uds: "tronaron",
		},
		Imperfect: {
			yo: "tronaba",
			tú: "tronabas",
			Ud: "tronaba",
			nosotros: "tronábamos",
			vosotros: "tronabais",
			Uds: "tronaban",
		},
		Conditional: {
			yo: "tronaría",
			tú: "tronarías",
			Ud: "tronaría",
			nosotros: "tronaríamos",
			vosotros: "tronaríais",
			Uds: "tronarían",
		},
		Future: {
			yo: "tronaré",
			tú: "tronarás",
			Ud: "tronará",
			nosotros: "tronaremos",
			vosotros: "tronaréis",
			Uds: "tronarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "truene",
			tú: "truenes",
			Ud: "truene",
			nosotros: "tronemos",
			vosotros: "tronéis",
			Uds: "truenen",
		},
		Imperfect: {
			yo: "tronara",
			tú: "tronaras",
			Ud: "tronara",
			nosotros: "tronáramos",
			vosotros: "tronarais",
			Uds: "tronaran",
		},
		Imperfect2: {
			yo: "tronase",
			tú: "tronases",
			Ud: "tronase",
			nosotros: "tronásemos",
			vosotros: "tronaseis",
			Uds: "tronasen",
		},
		Future: {
			yo: "tronare",
			tú: "tronares",
			Ud: "tronare",
			nosotros: "tronáremos",
			vosotros: "tronareis",
			Uds: "tronaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "truena",
			Ud: "truene",
			nosotros: "tronemos",
			vosotros: "tronad",
			Uds: "truenen",
		},
		Negative: {
			tú: "no truenes",
			Ud: "no truene",
			nosotros: "no tronemos",
			vosotros: "no tronéis",
			Uds: "no truenen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy tronando",
			tú: "estás tronando",
			Ud: "está tronando",
			nosotros: "estamos tronando",
			vosotros: "estáis tronando",
			Uds: "están tronando",
		},
		Preterite: {
			yo: "estuve tronando",
			tú: "estuviste tronando",
			Ud: "estuvo tronando",
			nosotros: "estuvimos tronando",
			vosotros: "estuvisteis tronando",
			Uds: "estuvieron tronando",
		},
		Imperfect: {
			Uds: "estaban tronando",
			yo: "estaba tronando",
			tú: "estabas tronando",
			Ud: "estaba tronando",
			nosotros: "estábamos tronando",
			vosotros: "estabais tronando",
		},
		Conditional: {
			yo: "estaría tronando",
			tú: "estarías tronando",
			Ud: "estaría tronando",
			nosotros: "estaríamos tronando",
			vosotros: "estaríais tronando",
			Uds: "estarían tronando",
		},
		Future: {
			yo: "estaré tronando",
			tú: "estarás tronando",
			Ud: "estará tronando",
			nosotros: "estaremos tronando",
			vosotros: "estaréis tronando",
			Uds: "estarán tronando",
		},
	},
	Perfect: {
		Present: {
			yo: "he tronado",
			tú: "has tronado",
			Ud: "ha tronado",
			nosotros: "hemos tronado",
			vosotros: "habéis tronado",
			Uds: "han tronado",
		},
		Preterite: {
			yo: "hube tronado",
			tú: "hubiste tronado",
			Ud: "hubo tronado",
			nosotros: "hubimos tronado",
			vosotros: "hubisteis tronado",
			Uds: "hubieron tronado",
		},
		Past: {
			yo: "había tronado",
			tú: "habías tronado",
			Ud: "había tronado",
			nosotros: "habíamos tronado",
			vosotros: "habíais tronado",
			Uds: "habían tronado",
		},
		Conditional: {
			yo: "habría tronado",
			tú: "habrías tronado",
			Ud: "habría tronado",
			nosotros: "habríamos tronado",
			vosotros: "habríais tronado",
			Uds: "habrían tronado",
		},
		Future: {
			yo: "habré tronado",
			tú: "habrás tronado",
			Ud: "habrá tronado",
			nosotros: "habremos tronado",
			vosotros: "habréis tronado",
			Uds: "habrán tronado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya tronado",
			tú: "hayas tronado",
			Ud: "haya tronado",
			nosotros: "hayamos tronado",
			vosotros: "hayáis tronado",
			Uds: "hayan tronado",
		},
		Past: {
			yo: "hubiera tronado",
			tú: "hubieras tronado",
			Ud: "hubiera tronado",
			nosotros: "hubiéramos tronado",
			vosotros: "hubierais tronado",
			Uds: "hubieran tronado",
		},
		Future: {
			yo: "hubiere tronado",
			tú: "hubieres tronado",
			Ud: "hubiere tronado",
			nosotros: "hubiéremos tronado",
			vosotros: "hubiereis tronado",
			Uds: "hubieren tronado",
		},
	},
}
