var trotar = {
	Indicative: {
		Present: {
			yo: "troto",
			tú: "trotas",
			Ud: "trota",
			nosotros: "trotamos",
			vosotros: "trotáis",
			Uds: "trotan",
		},
		Preterite: {
			yo: "troté",
			tú: "trotaste",
			Ud: "trotó",
			nosotros: "trotamos",
			vosotros: "trotasteis",
			Uds: "trotaron",
		},
		Imperfect: {
			yo: "trotaba",
			tú: "trotabas",
			Ud: "trotaba",
			nosotros: "trotábamos",
			vosotros: "trotabais",
			Uds: "trotaban",
		},
		Conditional: {
			yo: "trotaría",
			tú: "trotarías",
			Ud: "trotaría",
			nosotros: "trotaríamos",
			vosotros: "trotaríais",
			Uds: "trotarían",
		},
		Future: {
			yo: "trotaré",
			tú: "trotarás",
			Ud: "trotará",
			nosotros: "trotaremos",
			vosotros: "trotaréis",
			Uds: "trotarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "trote",
			tú: "trotes",
			Ud: "trote",
			nosotros: "trotemos",
			vosotros: "trotéis",
			Uds: "troten",
		},
		Imperfect: {
			yo: "trotara",
			tú: "trotaras",
			Ud: "trotara",
			nosotros: "trotáramos",
			vosotros: "trotarais",
			Uds: "trotaran",
		},
		Imperfect2: {
			yo: "trotase",
			tú: "trotases",
			Ud: "trotase",
			nosotros: "trotásemos",
			vosotros: "trotaseis",
			Uds: "trotasen",
		},
		Future: {
			yo: "trotare",
			tú: "trotares",
			Ud: "trotare",
			nosotros: "trotáremos",
			vosotros: "trotareis",
			Uds: "trotaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "trota",
			Ud: "trote",
			nosotros: "trotemos",
			vosotros: "trotad",
			Uds: "troten",
		},
		Negative: {
			tú: "no trotes",
			Ud: "no trote",
			nosotros: "no trotemos",
			vosotros: "no trotéis",
			Uds: "no troten",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy trotando",
			tú: "estás trotando",
			Ud: "está trotando",
			nosotros: "estamos trotando",
			vosotros: "estáis trotando",
			Uds: "están trotando",
		},
		Preterite: {
			yo: "estuve trotando",
			tú: "estuviste trotando",
			Ud: "estuvo trotando",
			nosotros: "estuvimos trotando",
			vosotros: "estuvisteis trotando",
			Uds: "estuvieron trotando",
		},
		Imperfect: {
			Uds: "estaban trotando",
			yo: "estaba trotando",
			tú: "estabas trotando",
			Ud: "estaba trotando",
			nosotros: "estábamos trotando",
			vosotros: "estabais trotando",
		},
		Conditional: {
			yo: "estaría trotando",
			tú: "estarías trotando",
			Ud: "estaría trotando",
			nosotros: "estaríamos trotando",
			vosotros: "estaríais trotando",
			Uds: "estarían trotando",
		},
		Future: {
			yo: "estaré trotando",
			tú: "estarás trotando",
			Ud: "estará trotando",
			nosotros: "estaremos trotando",
			vosotros: "estaréis trotando",
			Uds: "estarán trotando",
		},
	},
	Perfect: {
		Present: {
			yo: "he trotado",
			tú: "has trotado",
			Ud: "ha trotado",
			nosotros: "hemos trotado",
			vosotros: "habéis trotado",
			Uds: "han trotado",
		},
		Preterite: {
			yo: "hube trotado",
			tú: "hubiste trotado",
			Ud: "hubo trotado",
			nosotros: "hubimos trotado",
			vosotros: "hubisteis trotado",
			Uds: "hubieron trotado",
		},
		Past: {
			yo: "había trotado",
			tú: "habías trotado",
			Ud: "había trotado",
			nosotros: "habíamos trotado",
			vosotros: "habíais trotado",
			Uds: "habían trotado",
		},
		Conditional: {
			yo: "habría trotado",
			tú: "habrías trotado",
			Ud: "habría trotado",
			nosotros: "habríamos trotado",
			vosotros: "habríais trotado",
			Uds: "habrían trotado",
		},
		Future: {
			yo: "habré trotado",
			tú: "habrás trotado",
			Ud: "habrá trotado",
			nosotros: "habremos trotado",
			vosotros: "habréis trotado",
			Uds: "habrán trotado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya trotado",
			tú: "hayas trotado",
			Ud: "haya trotado",
			nosotros: "hayamos trotado",
			vosotros: "hayáis trotado",
			Uds: "hayan trotado",
		},
		Past: {
			yo: "hubiera trotado",
			tú: "hubieras trotado",
			Ud: "hubiera trotado",
			nosotros: "hubiéramos trotado",
			vosotros: "hubierais trotado",
			Uds: "hubieran trotado",
		},
		Future: {
			yo: "hubiere trotado",
			tú: "hubieres trotado",
			Ud: "hubiere trotado",
			nosotros: "hubiéremos trotado",
			vosotros: "hubiereis trotado",
			Uds: "hubieren trotado",
		},
	},
}
