var tutear = {
	Indicative: {
		Present: {
			yo: "tuteo",
			tú: "tuteas",
			Ud: "tutea",
			nosotros: "tuteamos",
			vosotros: "tuteáis",
			Uds: "tutean",
		},
		Preterite: {
			yo: "tuteé",
			tú: "tuteaste",
			Ud: "tuteó",
			nosotros: "tuteamos",
			vosotros: "tuteasteis",
			Uds: "tutearon",
		},
		Imperfect: {
			yo: "tuteaba",
			tú: "tuteabas",
			Ud: "tuteaba",
			nosotros: "tuteábamos",
			vosotros: "tuteabais",
			Uds: "tuteaban",
		},
		Conditional: {
			yo: "tutearía",
			tú: "tutearías",
			Ud: "tutearía",
			nosotros: "tutearíamos",
			vosotros: "tutearíais",
			Uds: "tutearían",
		},
		Future: {
			yo: "tutearé",
			tú: "tutearás",
			Ud: "tuteará",
			nosotros: "tutearemos",
			vosotros: "tutearéis",
			Uds: "tutearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "tutee",
			tú: "tutees",
			Ud: "tutee",
			nosotros: "tuteemos",
			vosotros: "tuteéis",
			Uds: "tuteen",
		},
		Imperfect: {
			yo: "tuteara",
			tú: "tutearas",
			Ud: "tuteara",
			nosotros: "tuteáramos",
			vosotros: "tutearais",
			Uds: "tutearan",
		},
		Imperfect2: {
			yo: "tutease",
			tú: "tuteases",
			Ud: "tutease",
			nosotros: "tuteásemos",
			vosotros: "tuteaseis",
			Uds: "tuteasen",
		},
		Future: {
			yo: "tuteare",
			tú: "tuteares",
			Ud: "tuteare",
			nosotros: "tuteáremos",
			vosotros: "tuteareis",
			Uds: "tutearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "tutea",
			Ud: "tutee",
			nosotros: "tuteemos",
			vosotros: "tutead",
			Uds: "tuteen",
		},
		Negative: {
			tú: "no tutees",
			Ud: "no tutee",
			nosotros: "no tuteemos",
			vosotros: "no tuteéis",
			Uds: "no tuteen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy tuteando",
			tú: "estás tuteando",
			Ud: "está tuteando",
			nosotros: "estamos tuteando",
			vosotros: "estáis tuteando",
			Uds: "están tuteando",
		},
		Preterite: {
			yo: "estuve tuteando",
			tú: "estuviste tuteando",
			Ud: "estuvo tuteando",
			nosotros: "estuvimos tuteando",
			vosotros: "estuvisteis tuteando",
			Uds: "estuvieron tuteando",
		},
		Imperfect: {
			Uds: "estaban tuteando",
			yo: "estaba tuteando",
			tú: "estabas tuteando",
			Ud: "estaba tuteando",
			nosotros: "estábamos tuteando",
			vosotros: "estabais tuteando",
		},
		Conditional: {
			yo: "estaría tuteando",
			tú: "estarías tuteando",
			Ud: "estaría tuteando",
			nosotros: "estaríamos tuteando",
			vosotros: "estaríais tuteando",
			Uds: "estarían tuteando",
		},
		Future: {
			yo: "estaré tuteando",
			tú: "estarás tuteando",
			Ud: "estará tuteando",
			nosotros: "estaremos tuteando",
			vosotros: "estaréis tuteando",
			Uds: "estarán tuteando",
		},
	},
	Perfect: {
		Present: {
			yo: "he tuteado",
			tú: "has tuteado",
			Ud: "ha tuteado",
			nosotros: "hemos tuteado",
			vosotros: "habéis tuteado",
			Uds: "han tuteado",
		},
		Preterite: {
			yo: "hube tuteado",
			tú: "hubiste tuteado",
			Ud: "hubo tuteado",
			nosotros: "hubimos tuteado",
			vosotros: "hubisteis tuteado",
			Uds: "hubieron tuteado",
		},
		Past: {
			yo: "había tuteado",
			tú: "habías tuteado",
			Ud: "había tuteado",
			nosotros: "habíamos tuteado",
			vosotros: "habíais tuteado",
			Uds: "habían tuteado",
		},
		Conditional: {
			yo: "habría tuteado",
			tú: "habrías tuteado",
			Ud: "habría tuteado",
			nosotros: "habríamos tuteado",
			vosotros: "habríais tuteado",
			Uds: "habrían tuteado",
		},
		Future: {
			yo: "habré tuteado",
			tú: "habrás tuteado",
			Ud: "habrá tuteado",
			nosotros: "habremos tuteado",
			vosotros: "habréis tuteado",
			Uds: "habrán tuteado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya tuteado",
			tú: "hayas tuteado",
			Ud: "haya tuteado",
			nosotros: "hayamos tuteado",
			vosotros: "hayáis tuteado",
			Uds: "hayan tuteado",
		},
		Past: {
			yo: "hubiera tuteado",
			tú: "hubieras tuteado",
			Ud: "hubiera tuteado",
			nosotros: "hubiéramos tuteado",
			vosotros: "hubierais tuteado",
			Uds: "hubieran tuteado",
		},
		Future: {
			yo: "hubiere tuteado",
			tú: "hubieres tuteado",
			Ud: "hubiere tuteado",
			nosotros: "hubiéremos tuteado",
			vosotros: "hubiereis tuteado",
			Uds: "hubieren tuteado",
		},
	},
}
