var usurpar = {
	Indicative: {
		Present: {
			yo: "usurpo",
			tú: "usurpas",
			Ud: "usurpa",
			nosotros: "usurpamos",
			vosotros: "usurpáis",
			Uds: "usurpan",
		},
		Preterite: {
			yo: "usurpé",
			tú: "usurpaste",
			Ud: "usurpó",
			nosotros: "usurpamos",
			vosotros: "usurpasteis",
			Uds: "usurparon",
		},
		Imperfect: {
			yo: "usurpaba",
			tú: "usurpabas",
			Ud: "usurpaba",
			nosotros: "usurpábamos",
			vosotros: "usurpabais",
			Uds: "usurpaban",
		},
		Conditional: {
			yo: "usurparía",
			tú: "usurparías",
			Ud: "usurparía",
			nosotros: "usurparíamos",
			vosotros: "usurparíais",
			Uds: "usurparían",
		},
		Future: {
			yo: "usurparé",
			tú: "usurparás",
			Ud: "usurpará",
			nosotros: "usurparemos",
			vosotros: "usurparéis",
			Uds: "usurparán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "usurpe",
			tú: "usurpes",
			Ud: "usurpe",
			nosotros: "usurpemos",
			vosotros: "usurpéis",
			Uds: "usurpen",
		},
		Imperfect: {
			yo: "usurpara",
			tú: "usurparas",
			Ud: "usurpara",
			nosotros: "usurpáramos",
			vosotros: "usurparais",
			Uds: "usurparan",
		},
		Imperfect2: {
			yo: "usurpase",
			tú: "usurpases",
			Ud: "usurpase",
			nosotros: "usurpásemos",
			vosotros: "usurpaseis",
			Uds: "usurpasen",
		},
		Future: {
			yo: "usurpare",
			tú: "usurpares",
			Ud: "usurpare",
			nosotros: "usurpáremos",
			vosotros: "usurpareis",
			Uds: "usurparen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "usurpa",
			Ud: "usurpe",
			nosotros: "usurpemos",
			vosotros: "usurpad",
			Uds: "usurpen",
		},
		Negative: {
			tú: "no usurpes",
			Ud: "no usurpe",
			nosotros: "no usurpemos",
			vosotros: "no usurpéis",
			Uds: "no usurpen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy usurpando",
			tú: "estás usurpando",
			Ud: "está usurpando",
			nosotros: "estamos usurpando",
			vosotros: "estáis usurpando",
			Uds: "están usurpando",
		},
		Preterite: {
			yo: "estuve usurpando",
			tú: "estuviste usurpando",
			Ud: "estuvo usurpando",
			nosotros: "estuvimos usurpando",
			vosotros: "estuvisteis usurpando",
			Uds: "estuvieron usurpando",
		},
		Imperfect: {
			Uds: "estaban usurpando",
			yo: "estaba usurpando",
			tú: "estabas usurpando",
			Ud: "estaba usurpando",
			nosotros: "estábamos usurpando",
			vosotros: "estabais usurpando",
		},
		Conditional: {
			yo: "estaría usurpando",
			tú: "estarías usurpando",
			Ud: "estaría usurpando",
			nosotros: "estaríamos usurpando",
			vosotros: "estaríais usurpando",
			Uds: "estarían usurpando",
		},
		Future: {
			yo: "estaré usurpando",
			tú: "estarás usurpando",
			Ud: "estará usurpando",
			nosotros: "estaremos usurpando",
			vosotros: "estaréis usurpando",
			Uds: "estarán usurpando",
		},
	},
	Perfect: {
		Present: {
			yo: "he usurpado",
			tú: "has usurpado",
			Ud: "ha usurpado",
			nosotros: "hemos usurpado",
			vosotros: "habéis usurpado",
			Uds: "han usurpado",
		},
		Preterite: {
			yo: "hube usurpado",
			tú: "hubiste usurpado",
			Ud: "hubo usurpado",
			nosotros: "hubimos usurpado",
			vosotros: "hubisteis usurpado",
			Uds: "hubieron usurpado",
		},
		Past: {
			yo: "había usurpado",
			tú: "habías usurpado",
			Ud: "había usurpado",
			nosotros: "habíamos usurpado",
			vosotros: "habíais usurpado",
			Uds: "habían usurpado",
		},
		Conditional: {
			yo: "habría usurpado",
			tú: "habrías usurpado",
			Ud: "habría usurpado",
			nosotros: "habríamos usurpado",
			vosotros: "habríais usurpado",
			Uds: "habrían usurpado",
		},
		Future: {
			yo: "habré usurpado",
			tú: "habrás usurpado",
			Ud: "habrá usurpado",
			nosotros: "habremos usurpado",
			vosotros: "habréis usurpado",
			Uds: "habrán usurpado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya usurpado",
			tú: "hayas usurpado",
			Ud: "haya usurpado",
			nosotros: "hayamos usurpado",
			vosotros: "hayáis usurpado",
			Uds: "hayan usurpado",
		},
		Past: {
			yo: "hubiera usurpado",
			tú: "hubieras usurpado",
			Ud: "hubiera usurpado",
			nosotros: "hubiéramos usurpado",
			vosotros: "hubierais usurpado",
			Uds: "hubieran usurpado",
		},
		Future: {
			yo: "hubiere usurpado",
			tú: "hubieres usurpado",
			Ud: "hubiere usurpado",
			nosotros: "hubiéremos usurpado",
			vosotros: "hubiereis usurpado",
			Uds: "hubieren usurpado",
		},
	},
}
