var vagar = {
	Indicative: {
		Present: {
			yo: "vago",
			tú: "vagas",
			Ud: "vaga",
			nosotros: "vagamos",
			vosotros: "vagáis",
			Uds: "vagan",
		},
		Preterite: {
			yo: "vagué",
			tú: "vagaste",
			Ud: "vagó",
			nosotros: "vagamos",
			vosotros: "vagasteis",
			Uds: "vagaron",
		},
		Imperfect: {
			yo: "vagaba",
			tú: "vagabas",
			Ud: "vagaba",
			nosotros: "vagábamos",
			vosotros: "vagabais",
			Uds: "vagaban",
		},
		Conditional: {
			yo: "vagaría",
			tú: "vagarías",
			Ud: "vagaría",
			nosotros: "vagaríamos",
			vosotros: "vagaríais",
			Uds: "vagarían",
		},
		Future: {
			yo: "vagaré",
			tú: "vagarás",
			Ud: "vagará",
			nosotros: "vagaremos",
			vosotros: "vagaréis",
			Uds: "vagarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "vague",
			tú: "vagues",
			Ud: "vague",
			nosotros: "vaguemos",
			vosotros: "vaguéis",
			Uds: "vaguen",
		},
		Imperfect: {
			yo: "vagara",
			tú: "vagaras",
			Ud: "vagara",
			nosotros: "vagáramos",
			vosotros: "vagarais",
			Uds: "vagaran",
		},
		Imperfect2: {
			yo: "vagase",
			tú: "vagases",
			Ud: "vagase",
			nosotros: "vagásemos",
			vosotros: "vagaseis",
			Uds: "vagasen",
		},
		Future: {
			yo: "vagare",
			tú: "vagares",
			Ud: "vagare",
			nosotros: "vagáremos",
			vosotros: "vagareis",
			Uds: "vagaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "vaga",
			Ud: "vague",
			nosotros: "vaguemos",
			vosotros: "vagad",
			Uds: "vaguen",
		},
		Negative: {
			tú: "no vagues",
			Ud: "no vague",
			nosotros: "no vaguemos",
			vosotros: "no vaguéis",
			Uds: "no vaguen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy vagando",
			tú: "estás vagando",
			Ud: "está vagando",
			nosotros: "estamos vagando",
			vosotros: "estáis vagando",
			Uds: "están vagando",
		},
		Preterite: {
			yo: "estuve vagando",
			tú: "estuviste vagando",
			Ud: "estuvo vagando",
			nosotros: "estuvimos vagando",
			vosotros: "estuvisteis vagando",
			Uds: "estuvieron vagando",
		},
		Imperfect: {
			Uds: "estaban vagando",
			yo: "estaba vagando",
			tú: "estabas vagando",
			Ud: "estaba vagando",
			nosotros: "estábamos vagando",
			vosotros: "estabais vagando",
		},
		Conditional: {
			yo: "estaría vagando",
			tú: "estarías vagando",
			Ud: "estaría vagando",
			nosotros: "estaríamos vagando",
			vosotros: "estaríais vagando",
			Uds: "estarían vagando",
		},
		Future: {
			yo: "estaré vagando",
			tú: "estarás vagando",
			Ud: "estará vagando",
			nosotros: "estaremos vagando",
			vosotros: "estaréis vagando",
			Uds: "estarán vagando",
		},
	},
	Perfect: {
		Present: {
			yo: "he vagado",
			tú: "has vagado",
			Ud: "ha vagado",
			nosotros: "hemos vagado",
			vosotros: "habéis vagado",
			Uds: "han vagado",
		},
		Preterite: {
			yo: "hube vagado",
			tú: "hubiste vagado",
			Ud: "hubo vagado",
			nosotros: "hubimos vagado",
			vosotros: "hubisteis vagado",
			Uds: "hubieron vagado",
		},
		Past: {
			yo: "había vagado",
			tú: "habías vagado",
			Ud: "había vagado",
			nosotros: "habíamos vagado",
			vosotros: "habíais vagado",
			Uds: "habían vagado",
		},
		Conditional: {
			yo: "habría vagado",
			tú: "habrías vagado",
			Ud: "habría vagado",
			nosotros: "habríamos vagado",
			vosotros: "habríais vagado",
			Uds: "habrían vagado",
		},
		Future: {
			yo: "habré vagado",
			tú: "habrás vagado",
			Ud: "habrá vagado",
			nosotros: "habremos vagado",
			vosotros: "habréis vagado",
			Uds: "habrán vagado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya vagado",
			tú: "hayas vagado",
			Ud: "haya vagado",
			nosotros: "hayamos vagado",
			vosotros: "hayáis vagado",
			Uds: "hayan vagado",
		},
		Past: {
			yo: "hubiera vagado",
			tú: "hubieras vagado",
			Ud: "hubiera vagado",
			nosotros: "hubiéramos vagado",
			vosotros: "hubierais vagado",
			Uds: "hubieran vagado",
		},
		Future: {
			yo: "hubiere vagado",
			tú: "hubieres vagado",
			Ud: "hubiere vagado",
			nosotros: "hubiéremos vagado",
			vosotros: "hubiereis vagado",
			Uds: "hubieren vagado",
		},
	},
}
