var vagabundear = {
	Indicative: {
		Present: {
			yo: "vagabundeo",
			tú: "vagabundeas",
			Ud: "vagabundea",
			nosotros: "vagabundeamos",
			vosotros: "vagabundeáis",
			Uds: "vagabundean",
		},
		Preterite: {
			yo: "vagabundeé",
			tú: "vagabundeaste",
			Ud: "vagabundeó",
			nosotros: "vagabundeamos",
			vosotros: "vagabundeasteis",
			Uds: "vagabundearon",
		},
		Imperfect: {
			yo: "vagabundeaba",
			tú: "vagabundeabas",
			Ud: "vagabundeaba",
			nosotros: "vagabundeábamos",
			vosotros: "vagabundeabais",
			Uds: "vagabundeaban",
		},
		Conditional: {
			yo: "vagabundearía",
			tú: "vagabundearías",
			Ud: "vagabundearía",
			nosotros: "vagabundearíamos",
			vosotros: "vagabundearíais",
			Uds: "vagabundearían",
		},
		Future: {
			yo: "vagabundearé",
			tú: "vagabundearás",
			Ud: "vagabundeará",
			nosotros: "vagabundearemos",
			vosotros: "vagabundearéis",
			Uds: "vagabundearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "vagabundee",
			tú: "vagabundees",
			Ud: "vagabundee",
			nosotros: "vagabundeemos",
			vosotros: "vagabundeéis",
			Uds: "vagabundeen",
		},
		Imperfect: {
			yo: "vagabundeara",
			tú: "vagabundearas",
			Ud: "vagabundeara",
			nosotros: "vagabundeáramos",
			vosotros: "vagabundearais",
			Uds: "vagabundearan",
		},
		Imperfect2: {
			yo: "vagabundease",
			tú: "vagabundeases",
			Ud: "vagabundease",
			nosotros: "vagabundeásemos",
			vosotros: "vagabundeaseis",
			Uds: "vagabundeasen",
		},
		Future: {
			yo: "vagabundeare",
			tú: "vagabundeares",
			Ud: "vagabundeare",
			nosotros: "vagabundeáremos",
			vosotros: "vagabundeareis",
			Uds: "vagabundearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "vagabundea",
			Ud: "vagabundee",
			nosotros: "vagabundeemos",
			vosotros: "vagabundead",
			Uds: "vagabundeen",
		},
		Negative: {
			tú: "no vagabundees",
			Ud: "no vagabundee",
			nosotros: "no vagabundeemos",
			vosotros: "no vagabundeéis",
			Uds: "no vagabundeen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy vagabundeando",
			tú: "estás vagabundeando",
			Ud: "está vagabundeando",
			nosotros: "estamos vagabundeando",
			vosotros: "estáis vagabundeando",
			Uds: "están vagabundeando",
		},
		Preterite: {
			yo: "estuve vagabundeando",
			tú: "estuviste vagabundeando",
			Ud: "estuvo vagabundeando",
			nosotros: "estuvimos vagabundeando",
			vosotros: "estuvisteis vagabundeando",
			Uds: "estuvieron vagabundeando",
		},
		Imperfect: {
			Uds: "estaban vagabundeando",
			yo: "estaba vagabundeando",
			tú: "estabas vagabundeando",
			Ud: "estaba vagabundeando",
			nosotros: "estábamos vagabundeando",
			vosotros: "estabais vagabundeando",
		},
		Conditional: {
			yo: "estaría vagabundeando",
			tú: "estarías vagabundeando",
			Ud: "estaría vagabundeando",
			nosotros: "estaríamos vagabundeando",
			vosotros: "estaríais vagabundeando",
			Uds: "estarían vagabundeando",
		},
		Future: {
			yo: "estaré vagabundeando",
			tú: "estarás vagabundeando",
			Ud: "estará vagabundeando",
			nosotros: "estaremos vagabundeando",
			vosotros: "estaréis vagabundeando",
			Uds: "estarán vagabundeando",
		},
	},
	Perfect: {
		Present: {
			yo: "he vagabundeado",
			tú: "has vagabundeado",
			Ud: "ha vagabundeado",
			nosotros: "hemos vagabundeado",
			vosotros: "habéis vagabundeado",
			Uds: "han vagabundeado",
		},
		Preterite: {
			yo: "hube vagabundeado",
			tú: "hubiste vagabundeado",
			Ud: "hubo vagabundeado",
			nosotros: "hubimos vagabundeado",
			vosotros: "hubisteis vagabundeado",
			Uds: "hubieron vagabundeado",
		},
		Past: {
			yo: "había vagabundeado",
			tú: "habías vagabundeado",
			Ud: "había vagabundeado",
			nosotros: "habíamos vagabundeado",
			vosotros: "habíais vagabundeado",
			Uds: "habían vagabundeado",
		},
		Conditional: {
			yo: "habría vagabundeado",
			tú: "habrías vagabundeado",
			Ud: "habría vagabundeado",
			nosotros: "habríamos vagabundeado",
			vosotros: "habríais vagabundeado",
			Uds: "habrían vagabundeado",
		},
		Future: {
			yo: "habré vagabundeado",
			tú: "habrás vagabundeado",
			Ud: "habrá vagabundeado",
			nosotros: "habremos vagabundeado",
			vosotros: "habréis vagabundeado",
			Uds: "habrán vagabundeado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya vagabundeado",
			tú: "hayas vagabundeado",
			Ud: "haya vagabundeado",
			nosotros: "hayamos vagabundeado",
			vosotros: "hayáis vagabundeado",
			Uds: "hayan vagabundeado",
		},
		Past: {
			yo: "hubiera vagabundeado",
			tú: "hubieras vagabundeado",
			Ud: "hubiera vagabundeado",
			nosotros: "hubiéramos vagabundeado",
			vosotros: "hubierais vagabundeado",
			Uds: "hubieran vagabundeado",
		},
		Future: {
			yo: "hubiere vagabundeado",
			tú: "hubieres vagabundeado",
			Ud: "hubiere vagabundeado",
			nosotros: "hubiéremos vagabundeado",
			vosotros: "hubiereis vagabundeado",
			Uds: "hubieren vagabundeado",
		},
	},
}
