var validar = {
	Indicative: {
		Present: {
			yo: "valido",
			tú: "validas",
			Ud: "valida",
			nosotros: "validamos",
			vosotros: "validáis",
			Uds: "validan",
		},
		Preterite: {
			yo: "validé",
			tú: "validaste",
			Ud: "validó",
			nosotros: "validamos",
			vosotros: "validasteis",
			Uds: "validaron",
		},
		Imperfect: {
			yo: "validaba",
			tú: "validabas",
			Ud: "validaba",
			nosotros: "validábamos",
			vosotros: "validabais",
			Uds: "validaban",
		},
		Conditional: {
			yo: "validaría",
			tú: "validarías",
			Ud: "validaría",
			nosotros: "validaríamos",
			vosotros: "validaríais",
			Uds: "validarían",
		},
		Future: {
			yo: "validaré",
			tú: "validarás",
			Ud: "validará",
			nosotros: "validaremos",
			vosotros: "validaréis",
			Uds: "validarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "valide",
			tú: "valides",
			Ud: "valide",
			nosotros: "validemos",
			vosotros: "validéis",
			Uds: "validen",
		},
		Imperfect: {
			yo: "validara",
			tú: "validaras",
			Ud: "validara",
			nosotros: "validáramos",
			vosotros: "validarais",
			Uds: "validaran",
		},
		Imperfect2: {
			yo: "validase",
			tú: "validases",
			Ud: "validase",
			nosotros: "validásemos",
			vosotros: "validaseis",
			Uds: "validasen",
		},
		Future: {
			yo: "validare",
			tú: "validares",
			Ud: "validare",
			nosotros: "validáremos",
			vosotros: "validareis",
			Uds: "validaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "valida",
			Ud: "valide",
			nosotros: "validemos",
			vosotros: "validad",
			Uds: "validen",
		},
		Negative: {
			tú: "no valides",
			Ud: "no valide",
			nosotros: "no validemos",
			vosotros: "no validéis",
			Uds: "no validen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy validando",
			tú: "estás validando",
			Ud: "está validando",
			nosotros: "estamos validando",
			vosotros: "estáis validando",
			Uds: "están validando",
		},
		Preterite: {
			yo: "estuve validando",
			tú: "estuviste validando",
			Ud: "estuvo validando",
			nosotros: "estuvimos validando",
			vosotros: "estuvisteis validando",
			Uds: "estuvieron validando",
		},
		Imperfect: {
			Uds: "estaban validando",
			yo: "estaba validando",
			tú: "estabas validando",
			Ud: "estaba validando",
			nosotros: "estábamos validando",
			vosotros: "estabais validando",
		},
		Conditional: {
			yo: "estaría validando",
			tú: "estarías validando",
			Ud: "estaría validando",
			nosotros: "estaríamos validando",
			vosotros: "estaríais validando",
			Uds: "estarían validando",
		},
		Future: {
			yo: "estaré validando",
			tú: "estarás validando",
			Ud: "estará validando",
			nosotros: "estaremos validando",
			vosotros: "estaréis validando",
			Uds: "estarán validando",
		},
	},
	Perfect: {
		Present: {
			yo: "he validado",
			tú: "has validado",
			Ud: "ha validado",
			nosotros: "hemos validado",
			vosotros: "habéis validado",
			Uds: "han validado",
		},
		Preterite: {
			yo: "hube validado",
			tú: "hubiste validado",
			Ud: "hubo validado",
			nosotros: "hubimos validado",
			vosotros: "hubisteis validado",
			Uds: "hubieron validado",
		},
		Past: {
			yo: "había validado",
			tú: "habías validado",
			Ud: "había validado",
			nosotros: "habíamos validado",
			vosotros: "habíais validado",
			Uds: "habían validado",
		},
		Conditional: {
			yo: "habría validado",
			tú: "habrías validado",
			Ud: "habría validado",
			nosotros: "habríamos validado",
			vosotros: "habríais validado",
			Uds: "habrían validado",
		},
		Future: {
			yo: "habré validado",
			tú: "habrás validado",
			Ud: "habrá validado",
			nosotros: "habremos validado",
			vosotros: "habréis validado",
			Uds: "habrán validado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya validado",
			tú: "hayas validado",
			Ud: "haya validado",
			nosotros: "hayamos validado",
			vosotros: "hayáis validado",
			Uds: "hayan validado",
		},
		Past: {
			yo: "hubiera validado",
			tú: "hubieras validado",
			Ud: "hubiera validado",
			nosotros: "hubiéramos validado",
			vosotros: "hubierais validado",
			Uds: "hubieran validado",
		},
		Future: {
			yo: "hubiere validado",
			tú: "hubieres validado",
			Ud: "hubiere validado",
			nosotros: "hubiéremos validado",
			vosotros: "hubiereis validado",
			Uds: "hubieren validado",
		},
	},
}
