var vedar = {
	Indicative: {
		Present: {
			yo: "vedo",
			tú: "vedas",
			Ud: "veda",
			nosotros: "vedamos",
			vosotros: "vedáis",
			Uds: "vedan",
		},
		Preterite: {
			yo: "vedé",
			tú: "vedaste",
			Ud: "vedó",
			nosotros: "vedamos",
			vosotros: "vedasteis",
			Uds: "vedaron",
		},
		Imperfect: {
			yo: "vedaba",
			tú: "vedabas",
			Ud: "vedaba",
			nosotros: "vedábamos",
			vosotros: "vedabais",
			Uds: "vedaban",
		},
		Conditional: {
			yo: "vedaría",
			tú: "vedarías",
			Ud: "vedaría",
			nosotros: "vedaríamos",
			vosotros: "vedaríais",
			Uds: "vedarían",
		},
		Future: {
			yo: "vedaré",
			tú: "vedarás",
			Ud: "vedará",
			nosotros: "vedaremos",
			vosotros: "vedaréis",
			Uds: "vedarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "vede",
			tú: "vedes",
			Ud: "vede",
			nosotros: "vedemos",
			vosotros: "vedéis",
			Uds: "veden",
		},
		Imperfect: {
			yo: "vedara",
			tú: "vedaras",
			Ud: "vedara",
			nosotros: "vedáramos",
			vosotros: "vedarais",
			Uds: "vedaran",
		},
		Imperfect2: {
			yo: "vedase",
			tú: "vedases",
			Ud: "vedase",
			nosotros: "vedásemos",
			vosotros: "vedaseis",
			Uds: "vedasen",
		},
		Future: {
			yo: "vedare",
			tú: "vedares",
			Ud: "vedare",
			nosotros: "vedáremos",
			vosotros: "vedareis",
			Uds: "vedaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "veda",
			Ud: "vede",
			nosotros: "vedemos",
			vosotros: "vedad",
			Uds: "veden",
		},
		Negative: {
			tú: "no vedes",
			Ud: "no vede",
			nosotros: "no vedemos",
			vosotros: "no vedéis",
			Uds: "no veden",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy vedando",
			tú: "estás vedando",
			Ud: "está vedando",
			nosotros: "estamos vedando",
			vosotros: "estáis vedando",
			Uds: "están vedando",
		},
		Preterite: {
			yo: "estuve vedando",
			tú: "estuviste vedando",
			Ud: "estuvo vedando",
			nosotros: "estuvimos vedando",
			vosotros: "estuvisteis vedando",
			Uds: "estuvieron vedando",
		},
		Imperfect: {
			Uds: "estaban vedando",
			yo: "estaba vedando",
			tú: "estabas vedando",
			Ud: "estaba vedando",
			nosotros: "estábamos vedando",
			vosotros: "estabais vedando",
		},
		Conditional: {
			yo: "estaría vedando",
			tú: "estarías vedando",
			Ud: "estaría vedando",
			nosotros: "estaríamos vedando",
			vosotros: "estaríais vedando",
			Uds: "estarían vedando",
		},
		Future: {
			yo: "estaré vedando",
			tú: "estarás vedando",
			Ud: "estará vedando",
			nosotros: "estaremos vedando",
			vosotros: "estaréis vedando",
			Uds: "estarán vedando",
		},
	},
	Perfect: {
		Present: {
			yo: "he vedado",
			tú: "has vedado",
			Ud: "ha vedado",
			nosotros: "hemos vedado",
			vosotros: "habéis vedado",
			Uds: "han vedado",
		},
		Preterite: {
			yo: "hube vedado",
			tú: "hubiste vedado",
			Ud: "hubo vedado",
			nosotros: "hubimos vedado",
			vosotros: "hubisteis vedado",
			Uds: "hubieron vedado",
		},
		Past: {
			yo: "había vedado",
			tú: "habías vedado",
			Ud: "había vedado",
			nosotros: "habíamos vedado",
			vosotros: "habíais vedado",
			Uds: "habían vedado",
		},
		Conditional: {
			yo: "habría vedado",
			tú: "habrías vedado",
			Ud: "habría vedado",
			nosotros: "habríamos vedado",
			vosotros: "habríais vedado",
			Uds: "habrían vedado",
		},
		Future: {
			yo: "habré vedado",
			tú: "habrás vedado",
			Ud: "habrá vedado",
			nosotros: "habremos vedado",
			vosotros: "habréis vedado",
			Uds: "habrán vedado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya vedado",
			tú: "hayas vedado",
			Ud: "haya vedado",
			nosotros: "hayamos vedado",
			vosotros: "hayáis vedado",
			Uds: "hayan vedado",
		},
		Past: {
			yo: "hubiera vedado",
			tú: "hubieras vedado",
			Ud: "hubiera vedado",
			nosotros: "hubiéramos vedado",
			vosotros: "hubierais vedado",
			Uds: "hubieran vedado",
		},
		Future: {
			yo: "hubiere vedado",
			tú: "hubieres vedado",
			Ud: "hubiere vedado",
			nosotros: "hubiéremos vedado",
			vosotros: "hubiereis vedado",
			Uds: "hubieren vedado",
		},
	},
}
