var venerar = {
	Indicative: {
		Present: {
			yo: "venero",
			tú: "veneras",
			Ud: "venera",
			nosotros: "veneramos",
			vosotros: "veneráis",
			Uds: "veneran",
		},
		Preterite: {
			yo: "veneré",
			tú: "veneraste",
			Ud: "veneró",
			nosotros: "veneramos",
			vosotros: "venerasteis",
			Uds: "veneraron",
		},
		Imperfect: {
			yo: "veneraba",
			tú: "venerabas",
			Ud: "veneraba",
			nosotros: "venerábamos",
			vosotros: "venerabais",
			Uds: "veneraban",
		},
		Conditional: {
			yo: "veneraría",
			tú: "venerarías",
			Ud: "veneraría",
			nosotros: "veneraríamos",
			vosotros: "veneraríais",
			Uds: "venerarían",
		},
		Future: {
			yo: "veneraré",
			tú: "venerarás",
			Ud: "venerará",
			nosotros: "veneraremos",
			vosotros: "veneraréis",
			Uds: "venerarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "venere",
			tú: "veneres",
			Ud: "venere",
			nosotros: "veneremos",
			vosotros: "veneréis",
			Uds: "veneren",
		},
		Imperfect: {
			yo: "venerara",
			tú: "veneraras",
			Ud: "venerara",
			nosotros: "veneráramos",
			vosotros: "venerarais",
			Uds: "veneraran",
		},
		Imperfect2: {
			yo: "venerase",
			tú: "venerases",
			Ud: "venerase",
			nosotros: "venerásemos",
			vosotros: "veneraseis",
			Uds: "venerasen",
		},
		Future: {
			yo: "venerare",
			tú: "venerares",
			Ud: "venerare",
			nosotros: "veneráremos",
			vosotros: "venerareis",
			Uds: "veneraren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "venera",
			Ud: "venere",
			nosotros: "veneremos",
			vosotros: "venerad",
			Uds: "veneren",
		},
		Negative: {
			tú: "no veneres",
			Ud: "no venere",
			nosotros: "no veneremos",
			vosotros: "no veneréis",
			Uds: "no veneren",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy venerando",
			tú: "estás venerando",
			Ud: "está venerando",
			nosotros: "estamos venerando",
			vosotros: "estáis venerando",
			Uds: "están venerando",
		},
		Preterite: {
			yo: "estuve venerando",
			tú: "estuviste venerando",
			Ud: "estuvo venerando",
			nosotros: "estuvimos venerando",
			vosotros: "estuvisteis venerando",
			Uds: "estuvieron venerando",
		},
		Imperfect: {
			Uds: "estaban venerando",
			yo: "estaba venerando",
			tú: "estabas venerando",
			Ud: "estaba venerando",
			nosotros: "estábamos venerando",
			vosotros: "estabais venerando",
		},
		Conditional: {
			yo: "estaría venerando",
			tú: "estarías venerando",
			Ud: "estaría venerando",
			nosotros: "estaríamos venerando",
			vosotros: "estaríais venerando",
			Uds: "estarían venerando",
		},
		Future: {
			yo: "estaré venerando",
			tú: "estarás venerando",
			Ud: "estará venerando",
			nosotros: "estaremos venerando",
			vosotros: "estaréis venerando",
			Uds: "estarán venerando",
		},
	},
	Perfect: {
		Present: {
			yo: "he venerado",
			tú: "has venerado",
			Ud: "ha venerado",
			nosotros: "hemos venerado",
			vosotros: "habéis venerado",
			Uds: "han venerado",
		},
		Preterite: {
			yo: "hube venerado",
			tú: "hubiste venerado",
			Ud: "hubo venerado",
			nosotros: "hubimos venerado",
			vosotros: "hubisteis venerado",
			Uds: "hubieron venerado",
		},
		Past: {
			yo: "había venerado",
			tú: "habías venerado",
			Ud: "había venerado",
			nosotros: "habíamos venerado",
			vosotros: "habíais venerado",
			Uds: "habían venerado",
		},
		Conditional: {
			yo: "habría venerado",
			tú: "habrías venerado",
			Ud: "habría venerado",
			nosotros: "habríamos venerado",
			vosotros: "habríais venerado",
			Uds: "habrían venerado",
		},
		Future: {
			yo: "habré venerado",
			tú: "habrás venerado",
			Ud: "habrá venerado",
			nosotros: "habremos venerado",
			vosotros: "habréis venerado",
			Uds: "habrán venerado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya venerado",
			tú: "hayas venerado",
			Ud: "haya venerado",
			nosotros: "hayamos venerado",
			vosotros: "hayáis venerado",
			Uds: "hayan venerado",
		},
		Past: {
			yo: "hubiera venerado",
			tú: "hubieras venerado",
			Ud: "hubiera venerado",
			nosotros: "hubiéramos venerado",
			vosotros: "hubierais venerado",
			Uds: "hubieran venerado",
		},
		Future: {
			yo: "hubiere venerado",
			tú: "hubieres venerado",
			Ud: "hubiere venerado",
			nosotros: "hubiéremos venerado",
			vosotros: "hubiereis venerado",
			Uds: "hubieren venerado",
		},
	},
}
