var ver = {
	Indicative: {
		Present: {
			yo: "veo",
			tú: "ves",
			Ud: "ve",
			nosotros: "vemos",
			vosotros: "veis",
			Uds: "ven",
		},
		Preterite: {
			yo: "vi",
			tú: "viste",
			Ud: "vio",
			nosotros: "vimos",
			vosotros: "visteis",
			Uds: "vieron",
		},
		Imperfect: {
			yo: "veía",
			tú: "veías",
			Ud: "veía",
			nosotros: "veíamos",
			vosotros: "veíais",
			Uds: "veían",
		},
		Conditional: {
			yo: "vería",
			tú: "verías",
			Ud: "vería",
			nosotros: "veríamos",
			vosotros: "veríais",
			Uds: "verían",
		},
		Future: {
			yo: "veré",
			tú: "verás",
			Ud: "verá",
			nosotros: "veremos",
			vosotros: "veréis",
			Uds: "verán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "vea",
			tú: "veas",
			Ud: "vea",
			nosotros: "veamos",
			vosotros: "veáis",
			Uds: "vean",
		},
		Imperfect: {
			yo: "viera",
			tú: "vieras",
			Ud: "viera",
			nosotros: "viéramos",
			vosotros: "vierais",
			Uds: "vieran",
		},
		Imperfect2: {
			yo: "viese",
			tú: "vieses",
			Ud: "viese",
			nosotros: "viésemos",
			vosotros: "vieseis",
			Uds: "viesen",
		},
		Future: {
			yo: "viere",
			tú: "vieres",
			Ud: "viere",
			nosotros: "viéremos",
			vosotros: "viereis",
			Uds: "vieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "ve",
			Ud: "vea",
			nosotros: "veamos",
			vosotros: "ved",
			Uds: "vean",
		},
		Negative: {
			tú: "no veas",
			Ud: "no vea",
			nosotros: "no veamos",
			vosotros: "no veáis",
			Uds: "no vean",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy viendo",
			tú: "estás viendo",
			Ud: "está viendo",
			nosotros: "estamos viendo",
			vosotros: "estáis viendo",
			Uds: "están viendo",
		},
		Preterite: {
			yo: "estuve viendo",
			tú: "estuviste viendo",
			Ud: "estuvo viendo",
			nosotros: "estuvimos viendo",
			vosotros: "estuvisteis viendo",
			Uds: "estuvieron viendo",
		},
		Imperfect: {
			Uds: "estaban viendo",
			yo: "estaba viendo",
			tú: "estabas viendo",
			Ud: "estaba viendo",
			nosotros: "estábamos viendo",
			vosotros: "estabais viendo",
		},
		Conditional: {
			yo: "estaría viendo",
			tú: "estarías viendo",
			Ud: "estaría viendo",
			nosotros: "estaríamos viendo",
			vosotros: "estaríais viendo",
			Uds: "estarían viendo",
		},
		Future: {
			yo: "estaré viendo",
			tú: "estarás viendo",
			Ud: "estará viendo",
			nosotros: "estaremos viendo",
			vosotros: "estaréis viendo",
			Uds: "estarán viendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he visto",
			tú: "has visto",
			Ud: "ha visto",
			nosotros: "hemos visto",
			vosotros: "habéis visto",
			Uds: "han visto",
		},
		Preterite: {
			yo: "hube visto",
			tú: "hubiste visto",
			Ud: "hubo visto",
			nosotros: "hubimos visto",
			vosotros: "hubisteis visto",
			Uds: "hubieron visto",
		},
		Past: {
			yo: "había visto",
			tú: "habías visto",
			Ud: "había visto",
			nosotros: "habíamos visto",
			vosotros: "habíais visto",
			Uds: "habían visto",
		},
		Conditional: {
			yo: "habría visto",
			tú: "habrías visto",
			Ud: "habría visto",
			nosotros: "habríamos visto",
			vosotros: "habríais visto",
			Uds: "habrían visto",
		},
		Future: {
			yo: "habré visto",
			tú: "habrás visto",
			Ud: "habrá visto",
			nosotros: "habremos visto",
			vosotros: "habréis visto",
			Uds: "habrán visto",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya visto",
			tú: "hayas visto",
			Ud: "haya visto",
			nosotros: "hayamos visto",
			vosotros: "hayáis visto",
			Uds: "hayan visto",
		},
		Past: {
			yo: "hubiera visto",
			tú: "hubieras visto",
			Ud: "hubiera visto",
			nosotros: "hubiéramos visto",
			vosotros: "hubierais visto",
			Uds: "hubieran visto",
		},
		Future: {
			yo: "hubiere visto",
			tú: "hubieres visto",
			Ud: "hubiere visto",
			nosotros: "hubiéremos visto",
			vosotros: "hubiereis visto",
			Uds: "hubieren visto",
		},
	},
}
