var veranear = {
	Indicative: {
		Present: {
			yo: "veraneo",
			tú: "veraneas",
			Ud: "veranea",
			nosotros: "veraneamos",
			vosotros: "veraneáis",
			Uds: "veranean",
		},
		Preterite: {
			yo: "veraneé",
			tú: "veraneaste",
			Ud: "veraneó",
			nosotros: "veraneamos",
			vosotros: "veraneasteis",
			Uds: "veranearon",
		},
		Imperfect: {
			yo: "veraneaba",
			tú: "veraneabas",
			Ud: "veraneaba",
			nosotros: "veraneábamos",
			vosotros: "veraneabais",
			Uds: "veraneaban",
		},
		Conditional: {
			yo: "veranearía",
			tú: "veranearías",
			Ud: "veranearía",
			nosotros: "veranearíamos",
			vosotros: "veranearíais",
			Uds: "veranearían",
		},
		Future: {
			yo: "veranearé",
			tú: "veranearás",
			Ud: "veraneará",
			nosotros: "veranearemos",
			vosotros: "veranearéis",
			Uds: "veranearán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "veranee",
			tú: "veranees",
			Ud: "veranee",
			nosotros: "veraneemos",
			vosotros: "veraneéis",
			Uds: "veraneen",
		},
		Imperfect: {
			yo: "veraneara",
			tú: "veranearas",
			Ud: "veraneara",
			nosotros: "veraneáramos",
			vosotros: "veranearais",
			Uds: "veranearan",
		},
		Imperfect2: {
			yo: "veranease",
			tú: "veraneases",
			Ud: "veranease",
			nosotros: "veraneásemos",
			vosotros: "veraneaseis",
			Uds: "veraneasen",
		},
		Future: {
			yo: "veraneare",
			tú: "veraneares",
			Ud: "veraneare",
			nosotros: "veraneáremos",
			vosotros: "veraneareis",
			Uds: "veranearen",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "veranea",
			Ud: "veranee",
			nosotros: "veraneemos",
			vosotros: "veranead",
			Uds: "veraneen",
		},
		Negative: {
			tú: "no veranees",
			Ud: "no veranee",
			nosotros: "no veraneemos",
			vosotros: "no veraneéis",
			Uds: "no veraneen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy veraneando",
			tú: "estás veraneando",
			Ud: "está veraneando",
			nosotros: "estamos veraneando",
			vosotros: "estáis veraneando",
			Uds: "están veraneando",
		},
		Preterite: {
			yo: "estuve veraneando",
			tú: "estuviste veraneando",
			Ud: "estuvo veraneando",
			nosotros: "estuvimos veraneando",
			vosotros: "estuvisteis veraneando",
			Uds: "estuvieron veraneando",
		},
		Imperfect: {
			Uds: "estaban veraneando",
			yo: "estaba veraneando",
			tú: "estabas veraneando",
			Ud: "estaba veraneando",
			nosotros: "estábamos veraneando",
			vosotros: "estabais veraneando",
		},
		Conditional: {
			yo: "estaría veraneando",
			tú: "estarías veraneando",
			Ud: "estaría veraneando",
			nosotros: "estaríamos veraneando",
			vosotros: "estaríais veraneando",
			Uds: "estarían veraneando",
		},
		Future: {
			yo: "estaré veraneando",
			tú: "estarás veraneando",
			Ud: "estará veraneando",
			nosotros: "estaremos veraneando",
			vosotros: "estaréis veraneando",
			Uds: "estarán veraneando",
		},
	},
	Perfect: {
		Present: {
			yo: "he veraneado",
			tú: "has veraneado",
			Ud: "ha veraneado",
			nosotros: "hemos veraneado",
			vosotros: "habéis veraneado",
			Uds: "han veraneado",
		},
		Preterite: {
			yo: "hube veraneado",
			tú: "hubiste veraneado",
			Ud: "hubo veraneado",
			nosotros: "hubimos veraneado",
			vosotros: "hubisteis veraneado",
			Uds: "hubieron veraneado",
		},
		Past: {
			yo: "había veraneado",
			tú: "habías veraneado",
			Ud: "había veraneado",
			nosotros: "habíamos veraneado",
			vosotros: "habíais veraneado",
			Uds: "habían veraneado",
		},
		Conditional: {
			yo: "habría veraneado",
			tú: "habrías veraneado",
			Ud: "habría veraneado",
			nosotros: "habríamos veraneado",
			vosotros: "habríais veraneado",
			Uds: "habrían veraneado",
		},
		Future: {
			yo: "habré veraneado",
			tú: "habrás veraneado",
			Ud: "habrá veraneado",
			nosotros: "habremos veraneado",
			vosotros: "habréis veraneado",
			Uds: "habrán veraneado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya veraneado",
			tú: "hayas veraneado",
			Ud: "haya veraneado",
			nosotros: "hayamos veraneado",
			vosotros: "hayáis veraneado",
			Uds: "hayan veraneado",
		},
		Past: {
			yo: "hubiera veraneado",
			tú: "hubieras veraneado",
			Ud: "hubiera veraneado",
			nosotros: "hubiéramos veraneado",
			vosotros: "hubierais veraneado",
			Uds: "hubieran veraneado",
		},
		Future: {
			yo: "hubiere veraneado",
			tú: "hubieres veraneado",
			Ud: "hubiere veraneado",
			nosotros: "hubiéremos veraneado",
			vosotros: "hubiereis veraneado",
			Uds: "hubieren veraneado",
		},
	},
}
