var verificar = {
	Indicative: {
		Present: {
			yo: "verifico",
			tú: "verificas",
			Ud: "verifica",
			nosotros: "verificamos",
			vosotros: "verificáis",
			Uds: "verifican",
		},
		Preterite: {
			yo: "verifiqué",
			tú: "verificaste",
			Ud: "verificó",
			nosotros: "verificamos",
			vosotros: "verificasteis",
			Uds: "verificaron",
		},
		Imperfect: {
			yo: "verificaba",
			tú: "verificabas",
			Ud: "verificaba",
			nosotros: "verificábamos",
			vosotros: "verificabais",
			Uds: "verificaban",
		},
		Conditional: {
			yo: "verificaría",
			tú: "verificarías",
			Ud: "verificaría",
			nosotros: "verificaríamos",
			vosotros: "verificaríais",
			Uds: "verificarían",
		},
		Future: {
			yo: "verificaré",
			tú: "verificarás",
			Ud: "verificará",
			nosotros: "verificaremos",
			vosotros: "verificaréis",
			Uds: "verificarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "verifique",
			tú: "verifiques",
			Ud: "verifique",
			nosotros: "verifiquemos",
			vosotros: "verifiquéis",
			Uds: "verifiquen",
		},
		Imperfect: {
			yo: "verificara",
			tú: "verificaras",
			Ud: "verificara",
			nosotros: "verificáramos",
			vosotros: "verificarais",
			Uds: "verificaran",
		},
		Imperfect2: {
			yo: "verificase",
			tú: "verificases",
			Ud: "verificase",
			nosotros: "verificásemos",
			vosotros: "verificaseis",
			Uds: "verificasen",
		},
		Future: {
			yo: "verificare",
			tú: "verificares",
			Ud: "verificare",
			nosotros: "verificáremos",
			vosotros: "verificareis",
			Uds: "verificaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "verifica",
			Ud: "verifique",
			nosotros: "verifiquemos",
			vosotros: "verificad",
			Uds: "verifiquen",
		},
		Negative: {
			tú: "no verifiques",
			Ud: "no verifique",
			nosotros: "no verifiquemos",
			vosotros: "no verifiquéis",
			Uds: "no verifiquen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy verificando",
			tú: "estás verificando",
			Ud: "está verificando",
			nosotros: "estamos verificando",
			vosotros: "estáis verificando",
			Uds: "están verificando",
		},
		Preterite: {
			yo: "estuve verificando",
			tú: "estuviste verificando",
			Ud: "estuvo verificando",
			nosotros: "estuvimos verificando",
			vosotros: "estuvisteis verificando",
			Uds: "estuvieron verificando",
		},
		Imperfect: {
			Uds: "estaban verificando",
			yo: "estaba verificando",
			tú: "estabas verificando",
			Ud: "estaba verificando",
			nosotros: "estábamos verificando",
			vosotros: "estabais verificando",
		},
		Conditional: {
			yo: "estaría verificando",
			tú: "estarías verificando",
			Ud: "estaría verificando",
			nosotros: "estaríamos verificando",
			vosotros: "estaríais verificando",
			Uds: "estarían verificando",
		},
		Future: {
			yo: "estaré verificando",
			tú: "estarás verificando",
			Ud: "estará verificando",
			nosotros: "estaremos verificando",
			vosotros: "estaréis verificando",
			Uds: "estarán verificando",
		},
	},
	Perfect: {
		Present: {
			yo: "he verificado",
			tú: "has verificado",
			Ud: "ha verificado",
			nosotros: "hemos verificado",
			vosotros: "habéis verificado",
			Uds: "han verificado",
		},
		Preterite: {
			yo: "hube verificado",
			tú: "hubiste verificado",
			Ud: "hubo verificado",
			nosotros: "hubimos verificado",
			vosotros: "hubisteis verificado",
			Uds: "hubieron verificado",
		},
		Past: {
			yo: "había verificado",
			tú: "habías verificado",
			Ud: "había verificado",
			nosotros: "habíamos verificado",
			vosotros: "habíais verificado",
			Uds: "habían verificado",
		},
		Conditional: {
			yo: "habría verificado",
			tú: "habrías verificado",
			Ud: "habría verificado",
			nosotros: "habríamos verificado",
			vosotros: "habríais verificado",
			Uds: "habrían verificado",
		},
		Future: {
			yo: "habré verificado",
			tú: "habrás verificado",
			Ud: "habrá verificado",
			nosotros: "habremos verificado",
			vosotros: "habréis verificado",
			Uds: "habrán verificado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya verificado",
			tú: "hayas verificado",
			Ud: "haya verificado",
			nosotros: "hayamos verificado",
			vosotros: "hayáis verificado",
			Uds: "hayan verificado",
		},
		Past: {
			yo: "hubiera verificado",
			tú: "hubieras verificado",
			Ud: "hubiera verificado",
			nosotros: "hubiéramos verificado",
			vosotros: "hubierais verificado",
			Uds: "hubieran verificado",
		},
		Future: {
			yo: "hubiere verificado",
			tú: "hubieres verificado",
			Ud: "hubiere verificado",
			nosotros: "hubiéremos verificado",
			vosotros: "hubiereis verificado",
			Uds: "hubieren verificado",
		},
	},
}
