var viajar = {
	Indicative: {
		Present: {
			yo: "viajo",
			tú: "viajas",
			Ud: "viaja",
			nosotros: "viajamos",
			vosotros: "viajáis",
			Uds: "viajan",
		},
		Preterite: {
			yo: "viajé",
			tú: "viajaste",
			Ud: "viajó",
			nosotros: "viajamos",
			vosotros: "viajasteis",
			Uds: "viajaron",
		},
		Imperfect: {
			yo: "viajaba",
			tú: "viajabas",
			Ud: "viajaba",
			nosotros: "viajábamos",
			vosotros: "viajabais",
			Uds: "viajaban",
		},
		Conditional: {
			yo: "viajaría",
			tú: "viajarías",
			Ud: "viajaría",
			nosotros: "viajaríamos",
			vosotros: "viajaríais",
			Uds: "viajarían",
		},
		Future: {
			yo: "viajaré",
			tú: "viajarás",
			Ud: "viajará",
			nosotros: "viajaremos",
			vosotros: "viajaréis",
			Uds: "viajarán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "viaje",
			tú: "viajes",
			Ud: "viaje",
			nosotros: "viajemos",
			vosotros: "viajéis",
			Uds: "viajen",
		},
		Imperfect: {
			yo: "viajara",
			tú: "viajaras",
			Ud: "viajara",
			nosotros: "viajáramos",
			vosotros: "viajarais",
			Uds: "viajaran",
		},
		Imperfect2: {
			yo: "viajase",
			tú: "viajases",
			Ud: "viajase",
			nosotros: "viajásemos",
			vosotros: "viajaseis",
			Uds: "viajasen",
		},
		Future: {
			yo: "viajare",
			tú: "viajares",
			Ud: "viajare",
			nosotros: "viajáremos",
			vosotros: "viajareis",
			Uds: "viajaren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "viaja",
			Ud: "viaje",
			nosotros: "viajemos",
			vosotros: "viajad",
			Uds: "viajen",
		},
		Negative: {
			tú: "no viajes",
			Ud: "no viaje",
			nosotros: "no viajemos",
			vosotros: "no viajéis",
			Uds: "no viajen",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy viajando",
			tú: "estás viajando",
			Ud: "está viajando",
			nosotros: "estamos viajando",
			vosotros: "estáis viajando",
			Uds: "están viajando",
		},
		Preterite: {
			yo: "estuve viajando",
			tú: "estuviste viajando",
			Ud: "estuvo viajando",
			nosotros: "estuvimos viajando",
			vosotros: "estuvisteis viajando",
			Uds: "estuvieron viajando",
		},
		Imperfect: {
			Uds: "estaban viajando",
			yo: "estaba viajando",
			tú: "estabas viajando",
			Ud: "estaba viajando",
			nosotros: "estábamos viajando",
			vosotros: "estabais viajando",
		},
		Conditional: {
			yo: "estaría viajando",
			tú: "estarías viajando",
			Ud: "estaría viajando",
			nosotros: "estaríamos viajando",
			vosotros: "estaríais viajando",
			Uds: "estarían viajando",
		},
		Future: {
			yo: "estaré viajando",
			tú: "estarás viajando",
			Ud: "estará viajando",
			nosotros: "estaremos viajando",
			vosotros: "estaréis viajando",
			Uds: "estarán viajando",
		},
	},
	Perfect: {
		Present: {
			yo: "he viajado",
			tú: "has viajado",
			Ud: "ha viajado",
			nosotros: "hemos viajado",
			vosotros: "habéis viajado",
			Uds: "han viajado",
		},
		Preterite: {
			yo: "hube viajado",
			tú: "hubiste viajado",
			Ud: "hubo viajado",
			nosotros: "hubimos viajado",
			vosotros: "hubisteis viajado",
			Uds: "hubieron viajado",
		},
		Past: {
			yo: "había viajado",
			tú: "habías viajado",
			Ud: "había viajado",
			nosotros: "habíamos viajado",
			vosotros: "habíais viajado",
			Uds: "habían viajado",
		},
		Conditional: {
			yo: "habría viajado",
			tú: "habrías viajado",
			Ud: "habría viajado",
			nosotros: "habríamos viajado",
			vosotros: "habríais viajado",
			Uds: "habrían viajado",
		},
		Future: {
			yo: "habré viajado",
			tú: "habrás viajado",
			Ud: "habrá viajado",
			nosotros: "habremos viajado",
			vosotros: "habréis viajado",
			Uds: "habrán viajado",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya viajado",
			tú: "hayas viajado",
			Ud: "haya viajado",
			nosotros: "hayamos viajado",
			vosotros: "hayáis viajado",
			Uds: "hayan viajado",
		},
		Past: {
			yo: "hubiera viajado",
			tú: "hubieras viajado",
			Ud: "hubiera viajado",
			nosotros: "hubiéramos viajado",
			vosotros: "hubierais viajado",
			Uds: "hubieran viajado",
		},
		Future: {
			yo: "hubiere viajado",
			tú: "hubieres viajado",
			Ud: "hubiere viajado",
			nosotros: "hubiéremos viajado",
			vosotros: "hubiereis viajado",
			Uds: "hubieren viajado",
		},
	},
}
