var zurcir = {
	Indicative: {
		Present: {
			yo: "zurzo",
			tú: "zurces",
			Ud: "zurce",
			nosotros: "zurcimos",
			vosotros: "zurcís",
			Uds: "zurcen",
		},
		Preterite: {
			yo: "zurcí",
			tú: "zurciste",
			Ud: "zurció",
			nosotros: "zurcimos",
			vosotros: "zurcisteis",
			Uds: "zurcieron",
		},
		Imperfect: {
			yo: "zurcía",
			tú: "zurcías",
			Ud: "zurcía",
			nosotros: "zurcíamos",
			vosotros: "zurcíais",
			Uds: "zurcían",
		},
		Conditional: {
			yo: "zurciría",
			tú: "zurcirías",
			Ud: "zurciría",
			nosotros: "zurciríamos",
			vosotros: "zurciríais",
			Uds: "zurcirían",
		},
		Future: {
			yo: "zurciré",
			tú: "zurcirás",
			Ud: "zurcirá",
			nosotros: "zurciremos",
			vosotros: "zurciréis",
			Uds: "zurcirán",
		},
	},
	Subjunctive: {
		Present: {
			yo: "zurza",
			tú: "zurzas",
			Ud: "zurza",
			nosotros: "zurzamos",
			vosotros: "zurzáis",
			Uds: "zurzan",
		},
		Imperfect: {
			yo: "zurciera",
			tú: "zurcieras",
			Ud: "zurciera",
			nosotros: "zurciéramos",
			vosotros: "zurcierais",
			Uds: "zurcieran",
		},
		Imperfect2: {
			yo: "zurciese",
			tú: "zurcieses",
			Ud: "zurciese",
			nosotros: "zurciésemos",
			vosotros: "zurcieseis",
			Uds: "zurciesen",
		},
		Future: {
			yo: "zurciere",
			tú: "zurcieres",
			Ud: "zurciere",
			nosotros: "zurciéremos",
			vosotros: "zurciereis",
			Uds: "zurcieren",
		},
	},
	Imperative: {
		Affirmative: {
			tú: "zurce",
			Ud: "zurza",
			nosotros: "zurzamos",
			vosotros: "zurcid",
			Uds: "zurzan",
		},
		Negative: {
			tú: "no zurzas",
			Ud: "no zurza",
			nosotros: "no zurzamos",
			vosotros: "no zurzáis",
			Uds: "no zurzan",
		},
	},
	ContinuousProgressive: {
		Present: {
			yo: "estoy zurciendo",
			tú: "estás zurciendo",
			Ud: "está zurciendo",
			nosotros: "estamos zurciendo",
			vosotros: "estáis zurciendo",
			Uds: "están zurciendo",
		},
		Preterite: {
			yo: "estuve zurciendo",
			tú: "estuviste zurciendo",
			Ud: "estuvo zurciendo",
			nosotros: "estuvimos zurciendo",
			vosotros: "estuvisteis zurciendo",
			Uds: "estuvieron zurciendo",
		},
		Imperfect: {
			Uds: "estaban zurciendo",
			yo: "estaba zurciendo",
			tú: "estabas zurciendo",
			Ud: "estaba zurciendo",
			nosotros: "estábamos zurciendo",
			vosotros: "estabais zurciendo",
		},
		Conditional: {
			yo: "estaría zurciendo",
			tú: "estarías zurciendo",
			Ud: "estaría zurciendo",
			nosotros: "estaríamos zurciendo",
			vosotros: "estaríais zurciendo",
			Uds: "estarían zurciendo",
		},
		Future: {
			yo: "estaré zurciendo",
			tú: "estarás zurciendo",
			Ud: "estará zurciendo",
			nosotros: "estaremos zurciendo",
			vosotros: "estaréis zurciendo",
			Uds: "estarán zurciendo",
		},
	},
	Perfect: {
		Present: {
			yo: "he zurcido",
			tú: "has zurcido",
			Ud: "ha zurcido",
			nosotros: "hemos zurcido",
			vosotros: "habéis zurcido",
			Uds: "han zurcido",
		},
		Preterite: {
			yo: "hube zurcido",
			tú: "hubiste zurcido",
			Ud: "hubo zurcido",
			nosotros: "hubimos zurcido",
			vosotros: "hubisteis zurcido",
			Uds: "hubieron zurcido",
		},
		Past: {
			yo: "había zurcido",
			tú: "habías zurcido",
			Ud: "había zurcido",
			nosotros: "habíamos zurcido",
			vosotros: "habíais zurcido",
			Uds: "habían zurcido",
		},
		Conditional: {
			yo: "habría zurcido",
			tú: "habrías zurcido",
			Ud: "habría zurcido",
			nosotros: "habríamos zurcido",
			vosotros: "habríais zurcido",
			Uds: "habrían zurcido",
		},
		Future: {
			yo: "habré zurcido",
			tú: "habrás zurcido",
			Ud: "habrá zurcido",
			nosotros: "habremos zurcido",
			vosotros: "habréis zurcido",
			Uds: "habrán zurcido",
		},
	},
	PerfectSubjunctive: {
		Present: {
			yo: "haya zurcido",
			tú: "hayas zurcido",
			Ud: "haya zurcido",
			nosotros: "hayamos zurcido",
			vosotros: "hayáis zurcido",
			Uds: "hayan zurcido",
		},
		Past: {
			yo: "hubiera zurcido",
			tú: "hubieras zurcido",
			Ud: "hubiera zurcido",
			nosotros: "hubiéramos zurcido",
			vosotros: "hubierais zurcido",
			Uds: "hubieran zurcido",
		},
		Future: {
			yo: "hubiere zurcido",
			tú: "hubieres zurcido",
			Ud: "hubiere zurcido",
			nosotros: "hubiéremos zurcido",
			vosotros: "hubiereis zurcido",
			Uds: "hubieren zurcido",
		},
	},
}
